### ISSUE TITLE
FALLA EN PARSEO DE EXTRA DATA GENERAL LEVICOM

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1]
CONECTOR LEVICOM. PROCESAMIENTO DE DATOS EXTRA.
CUANDO EN EL H5 QUE ES LA DIRECCIÓN DE ENTREGA, NO VIENEN TODOS LOS CAMPOS DE LA DIRECCIÓN, NO RESPETA LA POSICIÓN DE LOS ESPACIOS EN BLANCO Y NO ENVIA CORRECTAMENTE LOS DATOS EXTRAS.

CUANDO VIENE INCOMPLETO, NO ENTREGA BIEN LA DATA.

H5|DISTRIBUIDORA INDUSTRIAL DE BALEROS SA DE CV|XAXX010101000||Pelicano Ñ1275|   |     |                 |||Guadalajara     |Col. Morelos    |MEXICO|44910|||||||||||||

CUANDO VIENE COMPLETA, SI ENTREGA BIEN LA DATA.

H5|DISTRIBUIDORA INDUSTRIAL DE BALEROS SA DE CV|XAXX010101000||CALLE 21      |118|INT 3|PROGRESO NACIONAL|||GUSTAVO A MADREO|DISTRITO FEDERAL|MEXICO|44910|||||||||||||

EN AMBOS CASOS PAIS Y CÓDIGO POSTAL LLEGAN CORRECTAMENTE, PERO SOLO EN EL SEGUNDO CASO LO MUESTRA OK.

**Comment by jccastillo0007** [comment]
Necesito mas detalle para saber cual es exactamente el problema, utilize los dos strings que pusiste en un archivo y en ambos casos los proceso bien, no no te la diferencia.

Puedes decirme cual es el comportamiento erroneo.

**Comment by jccastillo0007** [comment]
RIJO SAID:

EL PROBLEMA, ES QUE SI NO LLEGAN TOOOODOS LOS DATOS DEL DOMICILIO DE ENTREGA (H5), ENTONCES REVUELVE LOS CAMPOS. COMO QUE LOS RECORRE.

UN PROBLEMA RECUERRENTE, QUE YA SE HA PRESENTADO EN EL PASADO… CHAAAAA.

EN ESTOS EJEMPLOS, LA ÚNICA DIFERENCIA ENTRE LOS ARCHIVOS DE TEXTO ES QUE PARA H5, EN UNO SOLO VIENE DATOS DE CALLE, PAIS Y CP (EL QUE DICE COPIA.TXT) , Y EN EL OTRO SI VIENE TODO COMPLETITO.

ENTONCES EN EL QUE DICE COPIA, EL PAIS Y EL CP, LOS RECORRE Y ENVÍA COMO NUMERO EXTERIOR Y NUMERO INTERIOR.

SI ME EXPLICO?

PAIS SIEMPRE DEBE SER DATO EXTRA 11, Y LO ENVÍA COMO SE LE HINCHA UN HUEVO, DEPENDIENDO DE CUÁNTOS DATOS PREVIOS FALTEN.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
NO, LO QUE SUCEDIÓ CON LA VERSIÓN QUE SUPUESTAMENTE CORRIGE, ES QUE AHORA NO ALMACENA EN BD TODAS LAS TRANSACCIONES. ESTO ES A PARTIR DE LA 2A OCASIÓN QUE LEVANTAS FACTURA-T PARTIENDO DE UNA BD LIMPLIA.

**Comment by jccastillo0007** [comment]
Done
