### ISSUE TITLE
Catalogo de productos

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#10]
Precio debe ser Precio Unitario

Predial debe ser Cuenta Predial

Cuenta predial y aduanas, que aparezcan debajo de descripcion complementaria

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
EL CATÁLOGO DE ADUANAS, DEBE SER INDEPENDIENTE DE LOS PRODUCTOS.
ES EN LA PANTALLA DE FACTURAS, DONDE SE ASOCIA. PUEDEN EXISTIR MUCHOS PRODUCTOS ASOCIADOS A UNA MISMA ADUANA (PARA EL MISMO EMBARQUE).
TAMBIÉN PUEDE SER EL MISMO PRODUCTO, QUE CADA DIFERENTE OCASIÓN QUE ES IMPORTADO, TIENE DISTINTO NÚMERO DE PEDIMENTO, Y POSIBLEMENTE FECHA Y ADUANA TAMBIÉN

**Comment by jccastillo0007** [comment]
Voy a marcar este issue como duplicado con el item 30
