### ISSUE TITLE
Error 115 con la plantilla wcfdi_Arca, en pru

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#100]
Intenté probar la nueva plantilla para la otra IAP, y me marcó el error 115.
Me puedes indicar de que se trata?

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
ok, el tema fue que el dato extra al final, si lo envía al pdf, pero también lo intentaba incluir en el complemento de donatarias. eso fue lo que se corrigió
