### ISSUE TITLE
CFDIv3.3 - Nodo Emisor - Desaparece domicilio fiscal y expedido en

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1005]
Ya no se enviarán al XML.
Solo quedará el lugar de expedición.
Los campos actuales se mantienen y se mandan al PDF de manera temporal, pero solo se hará obligatorio la captura del CP que además debe ser tomado del catálogo.

**Comment by jccastillo0007** [comment]
Ojo. esto nos pega en todas las key que hemos generado, en web me parece que se puede cambiar en el keygenerator, pero para standalone, habrá que cambiarles el key.

**Comment by RigoFlores** [comment]
No veo porque nos pega...
El domicilio se incluye en las llaves viejas.... y podría incluirse en las llaves nuevas.

Lo que no debe hacerse, y eso será con una VERSIÓN NUEVA DE ESCRITORIO, es enviar estos datos al XML. 
Incluso, te lo apuesto ahora mismo, habrá clientes que pidan que se mantenga esta información en el PDF, mientras se digiere este cambio tan drástico.
