### ISSUE TITLE
CFDIv3.3 - Receptor + CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1008]
Cuando se incluya el CCE, en el nodo receptor se incluirá la siguiente información del receptor:

Residencia Fiscal - Clave del Pais. 
NOTA: (También se puede incluir cuando el RFC sea XEXX010101000, aún cuando no se incluya el CCE)

NumRegIdTrib.- Este dato se captura en la pantalla de CCE.

**Comment by jccastillo0007** [comment]
pues esto ya esta no? que me falta?

**Comment by RigoFlores** [comment]
Hoy son opcionales esos datos. Cuando entre 3.3, será a oevo.

Nombre de Emisor - obligatorio (sin CCE opcional)
Nombre de Receptor obligatorio (sin CCE opcional)

Como lo hacemos?

**Comment by RigoFlores** [comment]
es decir aplica para cfdi 3.3
