### ISSUE TITLE
CFDIv3.3 - Incluir la clave del producto - Catálogo del SAT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1010]
Es un catálogo del SAT enorme. Imagínate para los productos o servicios facturables, según el SAT.
Por ejemplo, para la TIA se ocupa:

![image](https://cloud.githubusercontent.com/assets/2912775/25242311/c94db4d0-25be-11e7-86df-bbee45e18e43.png)
![image](https://cloud.githubusercontent.com/assets/2912775/25242349/e785f53e-25be-11e7-9ba1-331d58130ebf.png)
![image](https://cloud.githubusercontent.com/assets/2912775/25242361/f1d43f64-25be-11e7-951d-76ab82bf8104.png)
![image](https://cloud.githubusercontent.com/assets/2912775/25242394/06242952-25bf-11e7-96c0-5e7ab49f5bc9.png)

Lo que había pensado es crear un catálogo local para cada cliente.
Esto es partiendo del catálogo general (o quizás ni eso), que el cliente dé de alta el catálogo que sirva para sus propósitos. Siempre debe incluir la clave genérica:

![image](https://cloud.githubusercontent.com/assets/2912775/25242427/2dd0b092-25bf-11e7-98c9-cca31e63d464.png)

**Comment by jccastillo0007** [comment]
mmmmm yo digo que no implementemos esto... yo creo que le van a dar para atras o van a agregar la clasica opción de otros... y esa van a usar los clientes.

**Comment by jccastillo0007** [comment]
Entonces, vamos a dejar que los clientes capturen su propio catálogo de productos, solo vamos a agregar una liga al SAT para descargar dicho catálogo, para ese tema hay que levantar otro ticket.
