### ISSUE TITLE
CFDIv3.3 - Incluir la clave de unidad a nivel concepto - catálogo SAT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1011]
Es un catálogo enorme.
Debemos aplicar la misma solución, que para el catálogo de claves del producto...

**Comment by jccastillo0007** [comment]
mmmmm yo digo que no implementemos esto... yo creo que le van a dar para atras o van a agregar la clasica opción de otros... y esa van a usar los clientes.

**Comment by jccastillo0007** [comment]
Entonces, vamos a dejar que los clientes capturen su propio catálogo de productos, solo vamos a agregar una liga al SAT para descargar dicho catálogo, para ese tema hay que levantar otro ticket.
