### ISSUE TITLE
CFDIv3.3 - Conceptos - Incluir el descuento a nivel producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1012]
Para el XML y PDF, si es que aplica..

**Comment by RigoFlores** [comment]
OK, quedó bien para el XML.
Ahora enviar la variable descuento a nivel producto. ¿Le llamamos descuentoPro o simplemente descuento y como va a nivel producto, pues no se supone que se confunda con la otra a nivel general?

**Comment by jccastillo0007** [comment]
Sugerencia de Rijo, del ticket 993
"La forma de solucionarlo, es que una vez que eligieron el tipo de comprobante... cartaporte traslado o traslado... entonces al agregar productos... no debe permitir capturar descuento...
De lo contrario queda inconsistente el CFDI... por un lado para los cálculos y total si considera el descuento, pero no lo envía... jeje... el punto es que no aplica para T o P"

**Comment by jccastillo0007** [comment]
además "No debe existir descuento A NIVEL CONCEPTO - cuando el tipo de comprobante es T o P"

**Comment by RigoFlores** [comment]
No mezclemos issues... este se refiere a que se deben reportar descuentos a nivel producto... y al final solo quedaba el nombre de la variable, cuál sería... eso es todo. Repito la pregunta:

Ahora enviar la variable descuento a nivel producto. ¿Le llamamos descuentoPro o simplemente descuento y como va a nivel producto, pues no se supone que se confunda con la otra a nivel general?


No mezclemos con el 993, que es otra cosa...

**Comment by jccastillo0007** [comment]
descuento tal cual, no afecta el descuento a nivel cfdi

**Comment by jccastillo0007** [comment]
sin embargo la app, no esta lista para enviar descuentos a nivel producto, lo que hace con los descuentos capturados a nivel productos, es trasladarlo a nivel cfdi.

Asi que dejaré pendiente un poco este punto.

Pregunta, el total de descuentos a nivel producto, debe coincidir con el total de descuentos a nivel cfdi. ?

**Comment by RigoFlores** [comment]
El total de descuentos a nivel general, ahora mismo los calculas a partir de los descuentos a nivel producto.
Incluso, cuando se agrega un producto a la factura, ahí se captura el descuento.

Se trata de enviar ese dato que capturaron a nivel producto, junto con todos los demás capturados.
La variable a nivel producto como se llamará?
La dejamos así 'descuentoPro'?
