### ISSUE TITLE
CFDIv3.3 - Incluir el nodo de impuestos a nivel producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1013]
Ahora por cada producto se reportará un nodo de impuestos, si es que aplica.

Para los traslados:
Base
Impuesto (del catálogo)
Tipo de Factor (del catálogo)
Tasa o Cuota (del catálogo)
Importe (debe incluir el número de decimales que corresponde a la moneda)

Para los retenidos:
Base
Impuesto (del catálogo)
Tipo de Factor (del catálogo)
Tasa o Cuota (del catálogo)
Importe (debe incluir el número de decimales que corresponde a la moneda)

**Comment by jccastillo0007** [comment]
oye, entonces se reportará los impuestos a nivel producto y a nivel general ? osea dos veces ?

**Comment by RigoFlores** [comment]
si, en el esquema aparecen ambos.

**Comment by jccastillo0007** [comment]
oye la  tasa o cuota no es de un catálogo, que no es la tasa que se va a cobrar en ese impuesto.?

**Comment by RigoFlores** [comment]
Si y No.
Si es de un catálogo (que según yo no debería) y no, porque realmente ese catálogo son rangos de valores:
![image](https://cloud.githubusercontent.com/assets/2912775/25880910/b50aded0-34ff-11e7-9d68-8c052f08d324.png)


Por ejemplo, para IVA (impuesto), con el factor (tasa), trasladado, la tasa solo puede tener 2 valores 0.000000 ó 0.16000 (de acuerdo al catálogo).

**Comment by RigoFlores** [comment]
realmente lo que debemos entender de este issue, es que ahora se reportan a nivel producto los impuestos trasladados y retenidos (si aplican). Por cada distinto tipo de impuesto, se reportará un elemento de traslado o retenido.
OJO, aquí no entran los impuestos locales...!!!

**Comment by jccastillo0007** [comment]
done... la tasa o cuota, que la sigan capturando como hasta ahora.

**Comment by RigoFlores** [comment]
Jala bien para los trasladados, pero marca error al crear XML, si le incluyo algún impuesto retenido, ya sea IVA o ISR.

**Comment by jccastillo0007** [comment]
fixed
