### ISSUE TITLE
CFDIv3.3 - Conceptos - Información aduanera

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1014]
Ahora solo se enviará, en su caso, número de pedimento.
Todo lo demás desaparece.

**Comment by RigoFlores** [comment]
En web, mandó el nombre en lugar del número de pedimento.
De hecho, hay que eliminar los 2 datos que no aplican, y dejar solo una caja de texto, con etiqueta "Número de Pedimento"

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
No está mandando la aduana a nivel concepto... puedes probar con este valor de ejemplo
La ingresé desde la ventana de agregar concepto

104738078003832

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Marca el siguiente error:

El número de pedimento es inválido (3)

De hecho si capturo el pedimento en el catálogo de productos, cuando lo agrego a la factura no aparece.
Y bueno lo que hice fue agregarlo ahí, en la pantalla de agregar producto... y como quiera marca error..

**Comment by jccastillo0007** [comment]
Pues ese error, es algo de datos... no tengo idea que número de aduana sea correcta.

**Comment by RigoFlores** [comment]
en el conector tampoco jala lo del pedimento... simplemente no lo incluye en le XML
El número de prueba podría ser 168133346006076

**Comment by jccastillo0007** [comment]
Pues aqui si no se como ayudar... si pones el número de pedimento en la pantalla de agregar producto, si lo agrega al xml.. pero finkok manda el error de que el número de pedimento es inválido

Te mando por correo el xml que acabo de generar

**Comment by RigoFlores** [comment]
Ya jaló para el web, no así para el conector.
Esta es la cadena correcta:

            <cfdi:InformacionAduanera NumeroPedimento="14  43  3701  4000683"/>
