### ISSUE TITLE
CFDIv3.3 - Nodo Impuestos - no existe para el tipo T, N, P

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1015]
así como está en nómina, que no existe ahora mismo, así para Traslado y Pago.

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
OK, para traslado está OK.
Queda pendiente todo lo de P... levantaremos issues aparte para ese complemento
