### ISSUE TITLE
CFDIv3.3 - Nodo Impuestos - se reportan claves

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1016]
Para los impuestos retenidos:
Impuesto (clave tomada del catálogo)
Importe

Para los impuestos trasladados:
Impuesto (clave tomada del catálogo)
Tipo de Factor  (clave tomada del catálogo)
Tasa o Cuota
Importe

**Comment by RigoFlores** [comment]
Para ambos tipos de impuestos, se reportará un nodo para cada distinto tipo de impuesto... tal como lo hace ahora, pero con los nuevos datos...

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
Si envia las claves de los trasladados. De los retenidos no he podido probar, ya que marca error.
Voy a cerrar este issue, cuando se corrija el otro revisaré si todo está OK
