### ISSUE TITLE
CFDIv3.3 - Actualizar la versión, así como apuntar al nuevo esquema

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1017]
La versión es la 3.3 (valor fijo).
Apuntar al nuevo esquema del xsd.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
La versión ya cambió.
La URL del esquema aún aparece la 3.2
xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd

**Comment by jccastillo0007** [comment]
cierto... se me había pasado.

**Comment by jccastillo0007** [comment]
ya esta usando el nuevo schema eso si.
