### ISSUE TITLE
Nomina 1.2 - Falta la percepcion tipo viáticos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1018]
con clave 050, está faltando en el listado que despliega la plataforma

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
Se ocupa en producción.... chiaaaaa....!!!!

**Comment by RigoFlores** [comment]
además tampoco jala en pru....

nom165 : El nodo Nomina.Emisor.EntidadSNCF debe existir. (3)

chiaaaaa...

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Se cierra sin haber ejecutado pruebas.
