### ISSUE TITLE
Web CFDI v3.3 - Catálogo de Monedas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1019]
1) Poder elegir por descripción de moneda (no solo por clave). Si desconoces la clave, no hay forma de encontrar la moneda.

2) Agregar un campo para ser incorporado al PDF, donde se indique la leyenda que aparecerá enseguida de la cantidad con letra. Etiqueta sería "Leyenda cantidad con letra", por ejemplo "Mil quinientos DOLARES AMERICANOS"

3) Agregar un campo para que sea colocado al final de la cantidad con letra enviada al PDF. (por ejemplo, en el caso de peso mexicano, sería M.N.)

**Comment by jccastillo0007** [comment]
Esto esta duplicado con el ticket 672.

**Comment by RigoFlores** [comment]
Imagínate cuánto tiempo tiene sin atención, que hasta se duplica... aquí el texto del 672, para cerrar aquel... y tener mayor visibilidad aquí...
En el CFDI v3.3, se manejarán alrededor de 23 catálogos. Según yo, vale la pena poder capturarlos en tablas para ser desplegados, o en otro caso, tener muy claro y a la mano la manera de que hasta yo pueda modificarlos cuando sea necesario.

Para monedas distintas al MXN (peso mexicano), requerir capturar el tipo de cambio
Para moneda igual al MXN, no será necesario solicitar el tipo de cambio, ni enviarlo al XML
Para todo tipo de moneda, solicitar la leyenda que desplegará en la cantidad con letra, para la moneda en sí, así como para el sufijo que se agregará al final de la cantidad con letra.
Ejemplo:
Moneda: MXN
Tipo de cambio: (no se requiere para MXN)
LeyendaCantidadconLetra: Pesos
Sufijo: M.N.
Es decir estarían faltando 2 campos, para mostrar en el catálogo.

En la adecuación a producción de estos nuevos campos, de cara a lo que se tiene ahora mismo, se llenarían de la siguiente manera:

Moneda: MXN
TipoCambio: vacío
LeyendaCantidadConLetra: PESOS
Sufijo: M.N.

Para cualquier otra moneda:
Moneda: USD
TipodeCambio: 19.00
LeyendaCantidadConLetra:USD (es decir sería igual que el dato moneda)
Sufijo: (vacío; ellos lo llenarían de acuerdo a sus necesidades).

la cantidad con letra, queda:

veinte PESOS 15/100 M.N.

**Comment by jccastillo0007** [comment]
Si, y de hecho ya vi porque no se había atendido, no es tan sencillo pues la utilería que cambia de números a letras una cantidad, le agrega esas leyendas, si le cambio a esa utileria, le pega a standalone...

Este también me parece que no es un blocker para avanzar en cfdi3.3.

**Comment by RigoFlores** [comment]
A esa utilería, a juerzas le envias la leyenda de la moneda, ya que así se comporta hoy mismo.
En el caso mas 'barato', es tomar la leyenda de descripción de moneda, para que apareza en la cantidad con letra, siempre y cuando se pueda modificar.
Por ejemplo por omisión dice "PESO MEXICANO", para MXN. Si es posible cambiarlo a PESOS sin pegarle a nada, esa puede ser la descripción a la cantidad con letra.
