### ISSUE TITLE
Se brinca los folios con el error 401

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#102]
Posiblemente con varias situaciones de error, suceda lo mismo

**Comment by jccastillo0007** [comment]
Rechazado, el folio queda listo para ser reutilizado, lo verifique con el folio 131 de la iap

Probablemente hay que implemtentar algo para dar visibilidad anlos folios reutilizables, para que bo crean que se perdieron

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
ok, no se lo brinca, pero no muestra los reutilizables en la pantalla de factura ni de folios. 
Lo cierro, y abro otro para los reutilizables
