### ISSUE TITLE
CFDIv3.3 - Catálogo de Impuestos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1020]
Se deben mostrar los siguientes combos:

a) Tipo: traslado/retenido  (YA IMPLEMENTADO)
b) Impuesto: IVA, ISR, IEPS, etc.  (YA IMPLEMENTADO; SE ENVIARÁ LA CLAVE AL XML
![image](https://cloud.githubusercontent.com/assets/2912775/25671561/20a89dc6-2ff6-11e7-8cfc-80de077b715b.png)

c) Tipo de Factor: Tasa, Cuota, Exento. (POR OMISIÓN, SERÁ Tasa, YA QUE ES EL MAS COMÚN; SE ELIGIRÁ Exento, PARA EL CASO DE IVA EXENTO).
d) DESAPARECE 'IVA exento' DEL LISTADO ACTUAL, YA QUE AHORA TENDRÁN QUE ENVIAR EL TIPO DE FACTOR PARA INDICAR ESTA CONDICIÓN.

**Comment by RigoFlores** [comment]
Una pantalla similar a: 

![impuestos](https://cloud.githubusercontent.com/assets/2912775/25683308/2ec9ea56-3021-11e7-89ce-557587967fd6.PNG)

**Comment by jccastillo0007** [comment]
oye, y que pasa con todo el monton de impuestos ademas de iva, isr, ieps ?

HOSPEDAJE("Hospedaje"), MILLAR("5 al millar"), CEDULAR(
			"IMP CEDULAR"), ADICIONAL("ADICIONAL 25%"), INDUSTIRA("0.2% DE LA CAPACITACIÓN DE LA INDUSTRIA DE LA CMIC"), VIGILANCIA(
			"0.5% DE LA INSPECCIÓN, VIGILANCIA Y CONTROL"), GARANTIA("FONDO DE GARANTIA"), ICYVSFP("INSPECCIÓN Y VIGILANCIA"), PCYAICIC(
			"ICIC"), ACCEA("APORTACIÓN DE ATENCIÓN A CONTINGENCIAS"), RETPORINC("RET. POR INC."), DEVDERET("DEV DE RET"), SUPERVISION_CEA(
			"1.5% SUPERVISION CEA"), MILLAR_CMIC("5% AL MILLAR  C.M.I.C."), MILLAR_SFP("5% AL MILLAR  INSPECCION SFP"), MILLAR_ICIC(
			"2% AL MILLAR I.C.I.C."), INSPECCION("DERECHO POR LOS SERVICIOS DE INSPECCIÓN, VIGILANCIA Y CONTROL");

**Comment by RigoFlores** [comment]
Todos esos son impuestos locales. Su operación no cambia, ya que perteneces a un complemento, precisamente el de impuestos locales. Estos solamente llevan tipo, nombre, tasa e importe. 
Si queremos homologar su captura en la pantalla, sería siempre tasa el dato correspondiente a "Tipo de Factor", solo que nunca se usaría ese dato, que no aplica en los impuestos locales.

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
Falta poner el valor por omisión a 'Tasa', para el parámetro tasa o cuota.... o como queda esto?

**Comment by jccastillo0007** [comment]
tasa o cuota, es el valor del impuesto que se debe cobrar, ese lo deben capturar.
la captura debe seguir siendo 16.00 o 10.00 como hasta ahora lo han capturado, y la app lo va a convertir a 0.16000 etc.
