### ISSUE TITLE
CFDIv3.3 - Marca error al generar carta porte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1021]
Error al crear XML (100)

**Comment by jccastillo0007** [comment]
hay que ser mas específico, el comprobante con folio 51 con la cuenta de la TIA, es una carta porte traslado, y la generó correctametne, y lo hizo a la primera.

**Comment by RigoFlores** [comment]
Si genera el error. Incluso con tu cuenta, a la primera lo generó.
Según yo es una incorrecta captura... o no entiendo, pero si marca error de generación...
Lo podemos revisar en conjunto para evitar este problema... yo genero el error, y tu lo revisas en bitácora.
