### ISSUE TITLE
CFDIv3.3 - Ajustes al Catálogo de Productos 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1022]
Ajustar lo siguiente:

a) Permitir la captura de Clave de Producto del catálogo del SAT. Por omisión '01010101'
b) Validar la longitud de la clave de producto, que debe ser 8 númerico.
c) Permitir la captura de la Clave de Unidad del catálogo del SAT. Por omisión ZZ (mutuamente definido).
d) Eliminar aduana y fecha, dejando solo número de pedimento.
e) Reacomodar pantalla. Ver imagen abajo.
f) Colocar por omisión, la primera moneda capturada en el catálogo
g) Presentar una liga para mostrar los catálogos del SAT. Dando click en las etiquetas correspondientes, y abriendo una nueva ventana, o una ventana modal.

**Comment by RigoFlores** [comment]
![catproductos](https://cloud.githubusercontent.com/assets/2912775/25677266/eb1a10ee-300a-11e7-9bfd-4099855bc8e4.PNG)

**Comment by jccastillo0007** [comment]
Falta el punto F y G.

El acomodo no quedo tal cual, pues hay componentes que son combos y se cambian a texto dependiendo de la operaci[on, y esos están hatsa arriba

**Comment by RigoFlores** [comment]
Ajustes a la pantalla actual:
1) El ID no es obligatorio, quitar el asterisco (o sea cómo???).
2) Producto o servicio, en lugar del mensaje de incluido en la factura, es máximo 50 caracteres. En automático la aplicación debe pasar cualquier información excedente, a la sección de descripción.
3) Quitar el control para captura de clave de unidad del SAT. Solo dejar el combo para elegir la unidad. Aquí se desplegarán las unidades que hayan capturado en el catálogo.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
casi quedó... falta que cuando la el producto/servicio rebase los 50 caracteres, hay que enviar el excedente a la sección de descripción... esto es para evitar que ese control se haga demasiado ancho en la pantalla... hay clientes que ahí captura una biblia, y se hace difícil la operación en pantalla...

**Comment by jccastillo0007** [comment]
listo...
