### ISSUE TITLE
Web CFDIv3.3 - Pantalla Agregar Producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1023]
Ahora a nivel producto, lleva mucho mas cosas, pero dada nuestra super implementación actual, esto será casi transparente para el usuaurio. Por un lado, ya se agregaron algunos datos en el catálogo de producto.
Ahora en esta pantalla, solo falta un dato, que es la base del cálculo de impuestos. Su VALOR POR OMISIÓN SERÁ EL SUBTOTAL, PERO LO PODRÁN TECLEAR MANUALMENTE. ESTE FEATURE NOS DEBE GENERAR MAS CLIENTES.
La pantalla propuesta es prácticamente la misma, teniendo las siguientes observaciones:
a) Aquí no aparecen las claves de producto y unidad del SAT, que fueron capturadas en el catálogo.
b) Se agrega el campo BASE para los impuestos. Este servirá PARA HACER EL CÁLCULO DEL IMPUESTO CORRESPONDIENTE. Por lo regular siempre será el subtotal, de hecho por eso será su valor por omisión. Pero habrá unos casos raros, donde el impuesto no se calcula sobre el subtotal. Entonces lo teclearán, y el cálculo del impuesto se basará en la BASE y no en el subtotal.
c) En el XML se tendrán que enviar el descuento, los impuestos trasladados (base, impuesto, tipo de factor, tasa o cuota, importe).
d) Se enviará el descuento a nivel producto
e) Se enviará el motivo del descuento, pero SOLO AL PDF.
f) Al XML y PDF, se enviarán las claves de producto y unidad, correspondientes a los catálogos del sat

**Comment by RigoFlores** [comment]
![agregarproducto](https://cloud.githubusercontent.com/assets/2912775/25684046/d82e41fc-3024-11e7-93e3-50780bdf021f.PNG)

**Comment by RigoFlores** [comment]
Variables NUEVAS al PDF, a nivel producto:
ProductoSAT
UnidadSAT
descuentoPro
baseIVA
impuestoIVA
tipoFactorIVA
tasaCuotaIVA
montoIVA
baseIEPS
impuestoIEPS
tipoFactorIEPS
tasaCuotaIEPS
montoIEPS
baseRetIVA
impuestoRetIVA
tipoFactorRetIVA
tasaCuotaRetIVA
montoRetIVA
baseISR
impuestoISR
tipoFactorISR
tasaCuotaISR
montoISR

**Comment by jccastillo0007** [comment]
oye , dices que no aparecen :  
a) Aquí no aparecen las claves de producto y unidad del SAT, que fueron capturadas en el catálogo.

Pero en la pantalla si aparecen los datos de unidad y id producto... tons no entendí

**Comment by jccastillo0007** [comment]
este tema de la base de impuestos, para los casos raros.... que no se tomará el subtotal... puede quedar pendiente? al menos para después de la primera versión del cfdi 3.3, ?

Por el tipo de componente que puede ser 1 a n y que es dinámico, no es tan tan sencillo, en power point si se ve sencillo pero no en la app.

Incluso el tema de quitar los datos que sobran de la aduana, no es tan tan sencillo.

**Comment by jccastillo0007** [comment]
Por cierto, ya solo se ingresará una sola aduana, o pueden ser varias como ahora lo permite la app ?

**Comment by RigoFlores** [comment]
Afirmativo, no entendiste.
Ahora existen dos claves de ID producto: la del SAT tomada de su catálogo y la interna (ésta última es la que siempre hemos manejado).
Ahora existen dos descripciones de producto: la del SAT tomada de su catálogo y la interna (ésta última es la que siempre hemos manejado).
Las que se toman del catálogo del sat, se capturan a nivel catálogo de producto, pero no se mostrarán aquí.

Lo de poder modificar la base para el cálculo de impuesto... no sé si estamos entendiendo lo mismo. Hoy en día, esa base es el subtotal que aparece en esta misma pantalla. Ya se realiza el cálculo, no hay mas. Lo que se solicita, es que ese subtotal aparezca como la base sugerida para el cálculo del impuesto correspondiente (IVA, IEPS, etc). Este feature, lo que permitirá, será soportar las facturas de gobierno, de las cuales tenemos muchos clientes. En otro caso, dejaremos de soportarlas y seguramente tendremos muchas broncas.

**Comment by RigoFlores** [comment]
El xsd, marca que puedan ser varios números de pedimento. Yo lo que he visto, es que los clientes solo capturan uno. Lo que sea mas fácil, dejemos solo una o varias.

**Comment by jccastillo0007** [comment]
con respecto a la unidad y descripción, solo se soportan una, lo que según yo acordamos es que los clientes tendrán que capturar la unidad, id de producto y descripción de acuerdo al catálogo del sat, es decir, solo habrá una, me parece que se le agrega complejidad, acaso el uso de unidad y id producto del sat es algo que los clientes no quieren utilizar y solo seleccionarán una opción para enviarla al xml, pero ellos quieren seguir manejando lo que ya han especificado en el catálogo ?

Lo de la base para calculo de impuestos, si lo entendí bien, pero no es tan sencillo, lo vamos a dejar para cuando cfdi 3.3 ya este estable

Lo  de aduanas, vamos a dejar solo un campo para capturar la aduana, y asi  tratar de hacerlo simple

**Comment by RigoFlores** [comment]
A ver, no es lo que se nos acomode mejor o sea mas simple.
Necesitamos enviar obligatoriamente la clave de unidad y descripción de producto del catálogo del SAT. Eso se captura en el catálogo de productos. Son 2 campos adicionales a lo actual.
Adicionalmente, la unidad interna (la actual), y la descripción (producto/servicio + descripcion en el catálogo de productos), también se debe soportar, ya que ahí capturan todo el detalle que se requiera, que por supuesto no tiene que ver con el catálogo del SAT.

No soportar la base para impuestos, asi de simple, dejamos de soportar a todos los clientes que facturan a gobierno... de esos si tenemos muchos, y otros que puedan llegar por aquellos proveedores que se nieguen a implementar este cambio.

Aduanas OK.

**Comment by jccastillo0007** [comment]
Pues dijiste que sería un caso muy raro eso de cambiar la base... :   

**Por lo regular siempre será el subtotal, de hecho por eso será su valor por omisión. Pero habrá unos casos raros, donde el impuesto no se calcula sobre el subtotal.**

y si lo vamos a soportar, pero no desde ya.

Lo de unidad y id producto, pues si lo teenemos que hacer desde ya, si no, no podrían timbrar.

**Comment by RigoFlores** [comment]
Si esos casos raros, son los que PAGARON PARA EMITIR FACTURAS DE GOBIERNO... esos raros serán unos 50 clientes quizás... todo el resto, no habría problema.... esos los dejaríamos fuera de entrada...

**Comment by jccastillo0007** [comment]
pues, dependiendo de todos los demás requerimientos que si son obligatorios para el 100% de los clientes, una vez teniendo eso, hacemos esto de inmediato, no he dicho que no

**Comment by RigoFlores** [comment]
Si te das cuenta, en esta pantalla solo cambia lo de agregar la base para el cálculo del impuesto.
La unidad que se muestre, será la que eligieron para el producto en el catálogo del producto.
Dado que el id interno es opcional, se puede mostrar hasta arriba el id SAT - id Interno - Descripción interna.

**Comment by jccastillo0007** [comment]
Done.

Agregue el campo base... ojo... algunos campos aqui o en los catálogos se ven medio mal alineados, hasta ahorita no me estoy fijando mucho en eso, solo en la funcionalidad, al final le doy una chaineada.

**Comment by RigoFlores** [comment]
Oye, el campo base va a nivel de cada impuesto incluido en el producto.
Recuerda que ese dato, se ocupará para el cálculo del impuesto....

**Comment by jccastillo0007** [comment]
si ok, pero es un solo monto base por producto cierto ? o es por impuesto?

**Comment by RigoFlores** [comment]
chiaaa... la respuesta está en el layout del archivo plano... es por impuesto

**Comment by RigoFlores** [comment]
ah cabrón, tons esto ques???


60 | Tanto por   ciento en peso
-- | --
61 | Parte por mil   millones (EUA)
74 | Milipascal
77 | Mili-pulgada
80 | Libra por   pulgada cuadrado absoluta

**Comment by RigoFlores** [comment]
en este caso, la descripción de la unidad del sat, coincidiría totalmente con la del cliente..


H87 | Pieza
-- | --

**Comment by jccastillo0007** [comment]
eso de las unidades es en el otro ticket chiaaaa

con lo de la base, crees que si se ocupe a nivel impuesto... porque eso si esta complicado... habiamos quedado de no soportarlo a ese nivel que no ?

**Comment by RigoFlores** [comment]
Si, olvida lo de unidades, eso es de otro issue, ya cerrado... lo de que la base va por tipo de impuesto... es importante, y muy importante para las facturas de gobierno... estos cabrones le calculan el IVA sobre el importe - descuento (esa es la base), pero para los impuestos locales lo calculan sobre el total... esto es... OCUPAN UNA BASE DISTINTA DE CÁLCULO PARA EL IVA Y PARA LOS IMPUESTOS LOCALES... quizás sea un error, pero de aquí a que cambia, si es que llega a cambiar, pasarán meses o años... y mientras podemos resolver a nuestros clientes actuales y hacernos de nuevos clientes...

**Comment by jccastillo0007** [comment]
esto es parte del otro issue, para incluir la base a nivel impuesto, cierto?

**Comment by RigoFlores** [comment]
afirmativo
