### ISSUE TITLE
En facturas programadas no aparece el PDF y XML en la consulta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1024]
Para este cliente..

rfc="SIS130211C95" nombre="Soluciones En Internet y Sistemas Computacionales SA de CV"

El problema es que tiene muchas facturas programadas, con envío automático por correo. Eso automatiza mucho de su operación.

Ahora tenemos que hacer que aparezcan (no se corrigió el reporte anterior), y además ellos tendrán que enviar manualmente todas las facturas...

**Comment by jccastillo0007** [comment]
Ya esta arreglado este issue, en PRO.

**Comment by RigoFlores** [comment]
Oye, y como resolvemos todas aquellas que se generaron y que tienen problemas.
Hay manera de detectarlas??
Hasta el momento tengo identificadas las de SIS130211C95 (día 04 de mayo) y GLS131106EQ4 (dia 01 de mayo), que ya hablaron.

**Comment by RigoFlores** [comment]
Me volvió a marcar el cliente... el problema fue después del día 24 de abril.
Tenemos que corregir todas las generadas después de esa fecha.

Los clientes tienen detenidos sus pagos... la otra es que me digas en que ruta puedo obtenerlas por lo pronto.....

**Comment by jccastillo0007** [comment]
entre hoy y ma;ana estoy renombrando  todas estas facturas

+----------+---------------+---------------+---------------+-----------+
| count(*) | sourceRFC     | targetRFC     | frequentlyDay | serie     |
+----------+---------------+---------------+---------------+-----------+
|        1 | SIS130211C95  | DCB140502UR4  |             1 | FE        |
|        1 | AEGR8208065W6 | SAE030617SV8  |             1 | A         |
|        1 | EASJ5902096V9 | MDI991005QV4  |             1 | SIN SERIE |
|        1 | GLS131106EQ4  | PME811231GW1  |             1 | A         |
|        1 | GAPJ590509NW0 | BPE130919LZ7  |             3 | SIN SERIE |

|        1 | SIS130211C95  | FEL051103RC1  |             4 | FE        |
|        1 | SIS130211C95  | PAYJ5603048H3 |             4 | FE        |
|        1 | SIS130211C95  | AQI140226DF9  |             4 | FE        |
|        1 | SIS130211C95  | ZAMD840205TA4 |             4 | FE        |
|        1 | SIS130211C95  | BME960110PM8  |             4 | FE        |
|        2 | SIS130211C95  | GCM011227V7A  |             4 | FE        |
|        1 | SIS130211C95  | OUD070126JR2  |             4 | FE        |
|        1 | SIS130211C95  | OEC140521NH0  |             4 | FE        |
|        1 | MAAP790113F86 | NWM9709244W4  |             4 | RH        |
|        1 | SIS130211C95  | CQC781121GA1  |             4 | FE        |
|        1 | SIS130211C95  | CAS141220C45  |             4 | FE        |
|        1 | SIS130211C95  | CSE960401BU6  |             4 | FE        |
|        1 | SIS130211C95  | CME021125H98  |             4 | FE        |
|        1 | SIS130211C95  | IRC900104IC3  |             4 | FE        |
|        1 | SIS130211C95  | HPL081016642  |             4 | FE        |
|        1 | SIS130211C95  | PESH660722HM2 |             4 | FE        |
|        2 | SIS130211C95  | CEL070423GD1  |             4 | FE        |
|        1 | MAAP790113F86 | NWM9709244W4  |             5 | RH        |

|        1 | GORS6101036S3 | PLE080530H31  |            26 | A         |
|        1 | VIRJ740120924 | COM121221T59  |            28 | CP        |
|        1 | GOHM610102MK3 | XAXX010101000 |            29 | A         |
|        1 | SIS130211C95  | PPR910701LEA  |            30 | FE        |
|        1 | TEM110609BT0  | SGE071121TB2  |            30 | SIN SERIE |
|        1 | SIS130211C95  | CCM871105CX1  |            30 | FE        |
|        1 | CCO091218L79  | CSE030226575  |            30 | G         |
|        1 | AEGR8208065W6 | TRE1005219F9  |            31 | A         |
+----------+---------------+---------------+---------------+-----------+
73 rows in set (0.75 sec)
