### ISSUE TITLE
CFDIv3.3 - Pantalla de Facturación Ajustes.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1025]
Desaparecen varios datos, y aparecen unos nuevos.
Aquí está la propuesta de como reacomodar dicha pantalla. Trato de hacerla funcional, y que la mayoría de los datos se carguen por omisión. Prácticamente solo deben capturar lo que sea estrictamente necesario.

![facturacion](https://cloud.githubusercontent.com/assets/2912775/25717512/4ab69136-30c8-11e7-96a6-1a911adc6c13.PNG)

**Comment by jccastillo0007** [comment]
número de tarjeta ya no se ocupa ?

No me digas que lo de pago en parcialidades ya no se ocupa tampoco, no ma....

lo de pagos y fecha de pago, supongo tampoco.

chiaaaa, mucho trabajo sin usarse

**Comment by RigoFlores** [comment]
Número de tarjeta, desaparece. Todo eso viene en el documento de mapeo.
Pago en parcialidades se manejará ahora con DOCUMENTO DE PAGO, QUE FALTA ESPECIFICAR.
Lo de pagos y fecha de pago... chiaaaa.... tenemos una aplicación de CxC.... mucho mas robusta. Y si lo ocupan los clientes, pero les ofreceremos lo mismo de Optibelt.

Todo eso se ocupó en su momento, y ahora el SAT define otra cosa; y optibelt también.

**Comment by RigoFlores** [comment]
Solo considerar que lugar de expedición, será solo un código postal, entonces será menos ancho.
La otra es, el ancho de uso de CFDI, no puede ser ajustado?
