### ISSUE TITLE
cfdiV3.3 - Documento de Pago - CFDI "estándar" - elementos NO REQUERIDOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1027]
Como platicamos, el documento de pago es un complemento, por lo tanto se basa en un CFDI estándar + complemento.
El CFDI Estándar es una versión rasurada, que omite algunos datos y otros van fijo. 
Este issue menciona los elementos QUE NO SE INCLUYEN:

A nivel General:

1. Forma de Pago
2. Metodo de Pago
3. Condiciones de Pago
4. descuento
5. tipo de cambio
6. Nodo Impuestos

A nivel concepto:

1. Id interno
2. unidad
3. descuento
4. Nodo Impuestos
5. Información Aduanera
6. Cuenta Predial
7.

**Comment by jccastillo0007** [comment]
done
