### ISSUE TITLE
Web cfdiV3.3 - Documento de Pago - CFDI "estándar" - elementos CON VALOR FIJO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1028]
A nivel general:

moneda: XXX
Tipo de Comprobante: P
uso CFDI: P01 

A nivel concepto (1 SOLO CONCEPTO):
ClaveProdServ:  84111506
cantidad: 1
Clave Unidad: ACT
descripcion: Pago
Valor Unitario: 0

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
OK, tanto este y el anterior lo cerraré, aunque realmente esto se levantó para el web.
Lo que aquí se implementó, tendrá utilidad en el web?

**Comment by jccastillo0007** [comment]
I hope so.

**Comment by RigoFlores** [comment]
No, mejor lo dejo para web

**Comment by jccastillo0007** [comment]
Done... sé que aún no lo puedes validar, pero para saber lo que ya esta implementado.
