### ISSUE TITLE
Cambiar Concepto por Descripcion en el catálogo de Impuestos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#103]
Aún a la fecha, no logro entender si ya están definidas las etiquetas en el estánalon, porque nos ponemos a inventar nombres.

**Comment by jccastillo0007** [comment]
Se le conoce como evolution / innovation ...

El standalone ya es parte del pasado, tiene años que ni lo levanto.

Saludos.
JC.

**Comment by RigoFlores** [comment]
El están alon contiene todos los conceptos que hemos manejado y evolucionado, desde el 2010 hasta la fecha.
Si todo ese know how lo echamos por la borda, se justifica todas estas fallas y tanto tiempo de desarrollo y estabilización.
Por cierto, para Paco (ya que es la única referencia de primera mano que tengo), efectivamente, el boom fue de octubre a marzo pasados; hoy ya estamos mas que quemados. El comenta también que la demanda bajó para él, a partir del mes pasado. Es lo mismo que comenté desde siempre, pero no lo escuchamos.
Lo único que podría medio ayudar, es liberar la funcionalidad que nos permita competir con el resto de proveedores, y que están listados en todos estos issues levantados. Quién sabe si nos alcance el tiempo....
