### ISSUE TITLE
Error en Pro - en consultas de remisiones no aparecen los PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1030]
Seguramente el problema de los nombres de archivos.
Lo que no sé, en que momento se cambió eso a partir del 24 de abril pasado a la fecha... 

COMO EJEMPLO CLIENTE MID140206PQ5, CON LAS REMISIONES DEL DÍA DE HOY

**Comment by jccastillo0007** [comment]
fixed
