### ISSUE TITLE
Web CFDIv3.3 - IVA exento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1031]
Cuando se define un impuesto con el tipoFactor = 'Exento', como es el caso de iva trasladado exento, entonces marca el error 

CFDI33157 : Si el valor registrado en el campo TipoFactor que corresponde a Traslado es Exento no se deben registrar los campos TasaOCuota ni Importe. (3)

Esto es porque en el exento, no se envia tasa o cuota, ni base.

**Comment by jccastillo0007** [comment]
Duplicado con el ticket 1089

**Comment by RigoFlores** [comment]
dejaré activo este issue... que es el original desde el 19 de mayo... no maaaa

**Comment by RigoFlores** [comment]
Hoy en día así se genera en el conector, y aunque no marca error, no estoy seguro que sea correcto, ya que no se reporta nada en los nodos de impuestos. Según la guía de llenado, es incorrecto ya que en el caso de traslado iva exento, no se envía lo de tasa o cuota, ni importe, pero todo lo demás si.
Entiendo que aplica para el nodo impuestos a nivel producto y a nivel general.

<cfdi:Conceptos>
    <cfdi:Concepto Cantidad="1.00" ClaveProdServ="01010101" ClaveUnidad="H87" Descripcion="IMPRESORA EPSON L355 numero de serie: 1234567" Importe="3500.00" NoIdentificacion="ART-001" Unidad="PIEZA" ValorUnitario="3500.00"/>
</cfdi:Conceptos>
<cfdi:Impuestos/>

**Comment by jccastillo0007** [comment]
ok, en web ya lo reporta bien correcto ?

**Comment by RigoFlores** [comment]
Si el issue dice web, y dice bug/defect.... creo que no es correcto para web

**Comment by jccastillo0007** [comment]
es que en tu comentario anterior mencionaste al conector, tons por eso me confundi, total que no entiendo como debe enviarse y que si y que no debe enviarse

**Comment by RigoFlores** [comment]
Es que me baso en el conector para generar escenarios que si jalen... pero bueno el comentario, si lo lees con calma, no ha cambiado... aquí lo repito:
El resumen es que en el conector se genera sin error, cuando es exento, peeeero, en teoría no cumple con la spec del SAT... de entrada vamos a generarlo igual que en el conector, mientras investigamos..

**> Hoy en día así se genera en el conector, y aunque no marca error, no estoy seguro que sea correcto, ya que no se reporta nada en los nodos de impuestos. Según la guía de llenado, es incorrecto ya que en el caso de traslado iva exento, no se envía lo de tasa o cuota, ni importe, pero todo lo demás si.
> Entiendo que aplica para el nodo impuestos a nivel producto y a nivel general.
> 
> cfdi:Conceptos
> <cfdi:Concepto Cantidad="1.00" ClaveProdServ="01010101" ClaveUnidad="H87" Descripcion="IMPRESORA EPSON L355 numero de serie: 1234567" Importe="3500.00" NoIdentificacion="ART-001" Unidad="PIEZA" ValorUnitario="3500.00"/>
> </cfdi:Conceptos>
> cfdi:Impuestos/
>**

**Comment by jccastillo0007** [comment]
Pues si asi lo acepta finkok, tons esta bien no.... en finkok se han puesto bien pickies..

**Comment by RigoFlores** [comment]
No creo que esté bien, pero pues lo está aceptando finkok, por lo pronto lo dejaremos así
