### ISSUE TITLE
CFDIv3.3 + Nomina 1.2 - unidad y clavedeservicio a nivel concepto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1033]
Dado que aparecen las 2 claves de catálogos del sat, a nivel producto tenemos:

ClaveProdServ = "84111505"
ClaveUnidad = "ACT"
Unidad desaparece (esta si aparece en cfdi 3.2 con valor "ACT"; para cfdi 3.3 desaparece)

Aplica Web y Conector

**Comment by jccastillo0007** [comment]
Done.
