### ISSUE TITLE
CFDIv3.3 - envía fijos los valores de clave de producto y clave de unidad a nivel concepto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1034]
Incluso la unidad interna también... supongo que para que timbrara inicialmente, pero si tenemos que dejarlo listo para que soporte todo lo soportable..

ClaveProdServ="01010101" NoIdentificacion="cfdi33" Cantidad="1.00" ClaveUnidad="LTR" Unidad="LTR"

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
no puedo validar???
sigue marcando internal error
