### ISSUE TITLE
CxC - Corrección de reporte por cliente cuando el pago es híbrido

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1035]
Contabiliza las notas de crédito a favor del cliente.
Ya es una historia de tiempo y está documentado en correo

**Comment by RigoFlores** [comment]
Sigue incorrecto... básicamente se ocupa que se muestre como en consulta de pagos...por ejemplo este pago, así se ve en dicha consulta:

![test40](https://cloud.githubusercontent.com/assets/2912775/26368099/38cf4d12-3fb6-11e7-9ad6-0c2492577952.PNG)

**Comment by RigoFlores** [comment]
Ese pago en la consulta de cartera por cliente se muestra así... ahora ya no duplica las NC, pero ahora duplica los pagos... 
![test40-cartera](https://cloud.githubusercontent.com/assets/2912775/26368164/60eee3f2-3fb6-11e7-9a8d-05120855388f.PNG)

**Comment by RigoFlores** [comment]
En cartera por cliente, le falta la referencia de pago a la NC, pero además los PA los está repitiendo... solo debería aparecer UNA SOLA VEZ EL PAGO...igual prácticamente que la consulta de pagos..

**Comment by jccastillo0007** [comment]
ok, lo de la referencia de pago a NC, si, aún no logro hacer que eso suceda.

Lo de duplicar el pago, no salió ayer en mis pruebas... debo ver porque 

Este ejercicio del pago TEST40 lo hiciste hoy, o es el que ya estaba hecho ?

**Comment by RigoFlores** [comment]
Borré el pago anterior, y lo volví a capturar... es mi ejemplo fijo...

**Comment by jccastillo0007** [comment]
done....

**Comment by jccastillo0007** [comment]
esta en PRU... y la consulta ya se despliega igual, habrá que validar si el tema de 60, 90 o 120 días si esta bien, yo no vi resultados porque no había facturas vencidas o no las encontré.

**Comment by RigoFlores** [comment]
Ya coloca bien los registros de cargos y abonos a nivel del pago, pero el saldo ahora se descompuso, checa este reporte del cliente BBT011122DR9, con número de cliente 180600. No me queda claro como va calculando los saldos, pero si sumas cargos y le restas abonos, el saldo final debería ser lo que indica en correcto (al final). Lo que dice incorrecto es lo que pone ahora mismo el reporte que genera la plataforma:

![image](https://cloud.githubusercontent.com/assets/2912775/26413147/a530778c-4070-11e7-8bd2-be7a375c9d4c.png)

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
El pago híbrido, aparentemente ya quedó.
Los saldos, aparentemente ya quedó.
Ahora capturé pagos adicionales de solo cash (sin notas de crédito), y la referencia TEST41 y TEST42, no se muestran en el reporte en excel... ni en pantalla... en azul te muestro lo que debería aparecer...
![image](https://cloud.githubusercontent.com/assets/2912775/26458300/6ebe576e-4138-11e7-945c-ed502d0e232a.png)

**Comment by jccastillo0007** [comment]
Ok, puedes probar todos los escenarios que tienes, y no ir uno por uno, terminariamos más rápido.

usa otros datos de otros clientes para que puedas hacer varias pruebas, asi nunca vamos a terminar.

**Comment by RigoFlores** [comment]
Si estoy viendo, pero como avanzar si el punto de partida estaba chueco, no me permitía avanzarle con las pruebas.
Por otro lado, optibelt tiene cualquier cantidad de escenarios, que incluso yo desconozco. Pero si trataré de validar todo lo que pueda.

**Comment by jccastillo0007** [comment]
pues este tema de pagos en cash e híbrido, si se podía probar desde antes.

Cómo se comporta con pagos con pura NC, o pagos hibrídos a mas de una factura, o una factura con n pagos híbridos... etc... si esta cañon, pero hay que cubrir el 20% de los casos que cubren el 80% de lo que usan.

**Comment by RigoFlores** [comment]
te mandé un correo... necesito el cueri para conocer la referencia de alguna factura pagada...
