### ISSUE TITLE
CxP - Agregar columna de referencia de pago a los reportes de cartera por cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1036]
Adicional a lo que se tiene ahora mismo, agregar en los reportes de excel y PDF, la columna de referencia de pago.
variable Jasper: referenciaPago

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
ya se envía la variable al jasper???

**Comment by jccastillo0007** [comment]
simon.
