### ISSUE TITLE
CxC - Agregar columna 60, 90 , 120 a los reportes de Cartera Cliente y Cartera General

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1037]
Requerimiento 3: en reporte de Cartera de Cliente y Cartera General… agregar la opción (checkbox o similar), para “Incluir 60, 90 y 120”
Son 3 columnas adicionales que se incluirán cuando habiliten el checkbox, que para cada factura del reporte, con status de VENCIDA… indicarán si ya pasaron mas de 59 días, mas 89 y mas de 120 días desde la fecha de vencimiento respectivamente.
En la columna correspondiente se indicará el saldo deudor.

**Comment by jccastillo0007** [comment]
puedes probar este req... para ver si cumple con lo solicitado, quiero acabar hoy estos pendientes de optibelt para que nos paguen

**Comment by RigoFlores** [comment]
No hace lo que tiene que hacer. De hecho coloca solo en el caso de 120, los días transcurridos.
a) Debe validar IF (N6>59 .AND. N6<90),  D6-E6,  0)   
N6 ES EL NÚMERO DE DIAS TRANCURRIDO DESDE LA FECHA DE VENCIMIENTO A LA FECHA ACTUAL
D6 SON LOS CARGOS DE ESE REGISTRO
E6 SON LOS ABONOS DE ESE REGISTRO
Lo mismo aplica para 90. En el caso de 120, solo validar que sea mayor a 119 los días transcurridos.
Al final de cada columna, colocar la sumatoria. Para este reporte no se deben considerar las PAGADAS, ya que se busca únicamente adeudos. Igual lo podemos hacer con el filtro que ya está implementado.

Ejemplo en amarillo....
CLIENTE: BTA130730R98.

![image](https://cloud.githubusercontent.com/assets/2912775/26415500/4e5fb8c0-4078-11e7-9175-3b3f1000d245.png)

**Comment by jccastillo0007** [comment]
En este ejemplo, todas caen en el rango de mas de 120 días... a menos que hay algo que no estoy entendiendo, hay alguna factura que debió poner en 60 o 90 ?

**Comment by jccastillo0007** [comment]
ah supongo que en contenido de la celda es incorrecto, ya que muestra los dias transcurridos, y se ocupa el monto del adeudo... a eso te refieres que esta mal ?

**Comment by jccastillo0007** [comment]
done.

Checa con el cliente con RFC AME.... le movi fechas para que aparezcan en cada columna de 60, 90 y 120..

No pone los totales, pero eso lo pueden sacar directo en excel...

**Comment by RigoFlores** [comment]
El reporte se va al PDF.
Las variables serían sesenta, noventa y cientoveinte.
Yo creo que si se hace necesario colocar los totales.
De lo demás parece estar bien.

**Comment by RigoFlores** [comment]
Oyesss... falta lo mismo pero en el reporte de cartera general, tal cual lo indica este issue.
De hecho, en ese reporte, tendrían que ir los sumarizados que no quieres implementar del reporte de cartera por cliente...

**Comment by jccastillo0007** [comment]
nos quedamos en que lo ibas a validar con ellos, puesto que en el reporte  general no puedo poner esa marca por cada factura, ya que es un concentrado por cliente.... eso quedo me parece por correo.

**Comment by RigoFlores** [comment]
Después de casi un año, resulta que ya no aparece la opción...

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Ahora, no aparecen los montos en las columnas que corresponde.
Es decir no está mostrando en las columnas de 60, 90 y 120 (o mas) lo que debe poner...

**Comment by RigoFlores** [comment]
este es el comentario, donde se indicaba cómo debe comportarse.


De hecho coloca solo en el caso de 120, los días transcurridos.
a) Debe validar IF (N6>59 .AND. N6<90), D6-E6, 0)
N6 ES EL NÚMERO DE DIAS TRANCURRIDO DESDE LA FECHA DE VENCIMIENTO A LA FECHA ACTUAL
D6 SON LOS CARGOS DE ESE REGISTRO
E6 SON LOS ABONOS DE ESE REGISTRO
Lo mismo aplica para 90. En el caso de 120, solo validar que sea mayor a 119 los días transcurridos.
Al final de cada columna, colocar la sumatoria. Para este reporte no se deben considerar las PAGADAS, ya que se busca únicamente adeudos. Igual lo podemos hacer con el filtro que ya está implementado

**Comment by jccastillo0007** [comment]
si esta saliendo la info... recuerda que es solo para vencidas...

Una vez mas... sería bueno reportar el defecto con datos de prueba, o escenario de prueba

**Comment by RigoFlores** [comment]
Asi es... te mandé un correo con un reporte donde claramente se nota el defecto... ahi viene todo lo que ocupas para reproducirlo en pro

**Comment by jccastillo0007** [comment]
ya vi... al parecer han capturado comas ',' en la referencia... 

Pregunta... vi que a un lado de referencia, existe otro campo referencia de pago... pero según yo, nunca se pone nada ahi... recuerdas porque pusimos ese campo

**Comment by RigoFlores** [comment]
En esa columna va la referencia de pago, una vez que se realiza el pago. Ves que en la pantalla de ingresar cobro se captura una referencia. OK, pues esa referencia debería mostrarse en la columna de referencia de pago.

En la columna referencia (la que no es referencia de pago), solo debe aparecer la referencia que se incluye en el txt para factura o nota de crédito.

Entonces... una factura tiene referencia desde que nace (igual que la Nota de crédito), y cuando esa factura es pagada, tiene ooootra referencia, que es la de pago.

En el renglón de la factura, dentro del excel, debería aparece la referencia nativa, así como la referencia de pago.

**Comment by jccastillo0007** [comment]
fixed en pru y pro

**Comment by RigoFlores** [comment]
Ya casi quedó, pero tiene un detalle en la columna de 60.
Ahí está mostrando el cálculo, cuando el número de días de vencimiento va de 1 a 90, y no.... en esa columna, solo debe aparecer cuando los días transcurridos sean de 60 a 89.

Para la columna de 60:

a) Debe validar IF (N6>59 .AND. N6<90), D6-E6, 0)
N6 ES EL NÚMERO DE DIAS TRANCURRIDOS DESDE LA FECHA DE VENCIMIENTO A LA FECHA ACTUAL
D6 SON LOS CARGOS DE ESE REGISTRO
E6 SON LOS ABONOS DE ESE REGISTRO

**Comment by jccastillo0007** [comment]
mmm además del tema del calculo de fecha de 60 - 89, también esta calculando mal el monto de abonos y cargos... no entendi muy bien lo que pusiste arriba

**Comment by jccastillo0007** [comment]
fixed en pru y pro

**Comment by RigoFlores** [comment]
Híjole, pues nuevamente no quedó.
A los que son menores que 60 días, esos van en 0 en la columna.
Ahora mismo los está colocando en la columna de 120 y con el monto de la factura.
Debería quizás aparecer en la columna de 60 y con ceros. O simplemente no aparecer.
Te mandaré un ejemplo por correo.

**Comment by jccastillo0007** [comment]
ok, si habia un error... ya no lo va a poner en ninguna columna
