### ISSUE TITLE
CxC - Registro de un pago solo en CASH - Reporte cartera x cliente incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1038]
Si hago el registro de un pago solo en cash, una o varias facturas.
En reporte de cartera por cliente (sin ningún filtro) no muestra el registro del pago, POR LO TANTO NO LO DESCUENTA DE LOS SALDOS DEL CLIENTE. Y no muestra la referencia de pago en cash.

Si le aplico el filtro de pagadas, si muestra la referencia de pago, pero al no aparecer el registro del pago (PA), el saldo es incorrecto. Generalmente con este filtro, el saldo debería ser 0.

En el reporte de cartera general, el saldo para ese mismo cliente Si es correcto, es decir si considera el pago en efectivo capturado pero no mostrado en el reporte de cartera por cliente.

Estoy trabajando con el cliente BBT011122DR9 NÚMERO DE CLIENTE 180600, no tiene sucursales.

**Comment by jccastillo0007** [comment]
si, es correcto, y es lo que te puse en el otro ticket... este issue se coló como parte de las primeras pruebas, ya que el código solo muestra un registro tal cual de pago en cash, en caso de un pago híbrido, de otra forma solo se registra el tipo de pago = PA..

Tengo que ver como resolverlo, porque este si esta mas cabron, ya que hasta ahora no se guarda en base de datos un row tal cual del pago.

Oye el título es incorrecto, debería empezar con CxC, cierto ?

**Comment by RigoFlores** [comment]
Correcto.
Todo lo que depuremos y dejemos jalando en CxC, va a ser de muuuucha relevancia cuando entre en vigor el documento de pago, ya que precisamente se aplicará en pagos parciales o diferidos. Yo entiendo que eso nos dará ventajas enormes, el tener un módulo de CxC, en lugar de solo generar el CFDi de pago
