### ISSUE TITLE
Vuelve a generar el folio1 con al presentarse el error 301 del SAT (al facturar)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#104]
Al momento de facturar, cuando se presenta el error 301, referente a que el RFC receptor no existe, la pantalla se mantiene, incluso con el tentativo folio siguiente. Si en ese escenario se elige otro RFC (uno correcto) y se elige generar la factura, si la genera pero con el Folio 1, aunque el tentativo siguiente haya sido el 30.
Supongo que este comportamiento también se presenta con algún otro tipo de error.

**Comment by jccastillo0007** [comment]
Hay mucha diferencia entre el folio 1 y folio 30, estas seguro que era 
la misma serie ?

Saludos.
JC.

**Comment by RigoFlores** [comment]
Existen 3 facturas con folio 1 SIN SERIE.... tu dirás

**Comment by jccastillo0007** [comment]
No lo pude reproducir....

**Comment by RigoFlores** [comment]
Ya no lo pude reproducir tampoco, pero es un hecho que se presentó. Las facturas con folio 1 SIN SERIE, generadas en mayo son la prueba. Me preocupa demasiado que esto se pudiera presentar con un cliente; me preocupa aún mas que de repente ya no se presenta el problema, sin saber que pasó.

**Comment by jccastillo0007** [comment]
Estuve haciendo refactor, asi que seguramente ahi lo arregle

Con que usuario tienes ese caso?
Para revisar la historia...

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
se volvió a presentar el problema, y me indicaste que ya lo tenías identificado...
Favor de indicar cuando ya se cierre

**Comment by jccastillo0007** [comment]
?????

Ya quedo, cierto ???

**Comment by RigoFlores** [comment]
NO ESTOY SEGURO, MAS BIEN TE PREGUNTARÍA QUE PASÓ CUANDO TE AVISÉ QUE YA SE HABÍA REPRODUCIDO NUEVAMENTE; NO SÉ SI TUVISTE CHANCE DE REVISAR EL LOG DE ESE DÍA

**Comment by jccastillo0007** [comment]
Si, ya esta resuelto... la primera vez, comente que se resolvio con otros refactors... cuando lo volviste a detectar, me meti a fondo y si encontre un problema.

Done.

**Comment by RigoFlores** [comment]
OK, dado que no puedo reproducirlo, lo aceptaré por OK.
