### ISSUE TITLE
Optibelt - Envía los correos a una lista que no corresponde al número de cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1040]
En un correo está documentado.
Me dijiste que quizás está tomando el RFC pero no el número de cliente.
Este RFC si tiene 2 clientes asociados en optibelt.
RFC Receptor:	BRI060821H70
Nombre Receptor:	Binasa Refacciones Industriales SA de CV

**Comment by jccastillo0007** [comment]
Te han reportado este issue otra vez ?

Que paso con su CRM chacarron?

**Comment by RigoFlores** [comment]
Ya no han reportado nada. Cerraré este issue.
En cuanto al minCRM, dijeron que me enviarían información adicional, la bolita está de su lado, y por lo pronto tenemos muuuuucho que hacer, así que no los presiono.
