### ISSUE TITLE
Producción Nomina Empresarial - No almacena los rangos de fecha, ni recalcula la antigüedad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1043]
Cuando se corre la nómina empresarial... las fechas capturadas se deben actualizar en cada empleado involucrado.
Adicionalmente, se debe recalcular la antigüedad basada en las fechas capturadas.
Ahora mismo solo las fechas las coloca en el XML, pero en la BD se va quedando información que no está actualizada

**Comment by RigoFlores** [comment]
PUES AHORA SE PRESENTA CON UN CLIENTE QUE TIENE VARIOS EMPLEADOS.

EL PROBLEMA ES QUE CUANDO EN LA NÓMINA EMPRESARIAL, TU CAPTURAS LA FECHA INICIAL, FECHA FINAL Y FECHA DE PAGO,  NO SE RECALCULA LA ANTIGÜEDAD, NI SE ACTUALIZAN LAS FECHAS EN LOS REGISTROS DE LOS EMPLEADOS. SE TIENE QUE RESOLVER.

EN LA NÓMINA EMPRESARIAL, AGREGAR UN CHECK BOX, QUE PERMITA INDICAR SI ES NOMINA EXTRAORDINARIA. SI ES EL CASO, ENTONCES SE REPORTA TIPO DE NOMINA 'E', TODO EL PROCESO DE LA NOMINA EMPRESARIAL.


TODO LO ANTERIOR, SE DEBE A QUE NO ES POSIBLE GENERAR LA NÓMINA EMPRESARIAL CUANDO ES EXTRAORDINARIA, PTU.

**Comment by jccastillo0007** [comment]
done

falta lo del checkbox.

**Comment by jccastillo0007** [comment]
Listo...

Ojo... en la nomina de cada empleado, existe una condición, de que si el tipo de nómina es extraordinario, entonces la fecha inicial de pago y la fecha final de pago son iguales a la fecha de pago... esa condición aplicaría igual si eligen el tipo de nómina extraordinario en la nómina general.

**Comment by RigoFlores** [comment]
Afirmativo... si ya está implementado lo del checkbox, se procede como indicas para la nómina extraordinaria. Finalmente, cada ocasión que quieran generar nómina ordinaria desde nomina empresarial tendrá que calcular y almacenar las fechas, aún cuando la nómina empresarial anterior, haya sido extraordinaria.

La mayoría de las ocasiones no será nomina extraordinaria, y por ello deberá calcular y almacenar la antigüedad, y las fechas inicial, final y de pago,  cada vez que se trate de nómina ordinaria.

**Comment by RigoFlores** [comment]
Es decir, para nómina extraordinaria, es correcto que mantenga ese comportamiento que describes.
El hecho de que almacene las fechas y recalcule la antigüedad, no tiene mayor afectación, ya que enseguida tendrán que emitir una nómina ordinaria, y los datos volverán a su normalidad.

Algo que sería necesario, y por lo pronto lo dejaremos pendiente, a menos que digas que es simple su implementación, es que debemos tener una pantalla para nómina ordinaria y otra, prácticamente idéntica para nómina extraordinaria. Y eso por que?... porque cuando emiten la nomina extraordinaria, tienen que deshabilitar todos y cada uno de las percepciones y deducciones, para cada empleado y solo dejar las que correspndan a PTU por ejemplo. Una vez emitida la nómina extraordinaria, tienen que regresar a volver habilitar todas las percepciones y deducciones.
Otra forma mas simple, sería agregar otro checkbox, que indique nómina extraordinaria (así como el de hablilitar y deshabilitar percepciones), y así no tienen que estar habilitando y deshabilitando.
