### ISSUE TITLE
Web CFDI v3.3 - Pantalla Captura Pagos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1044]
Al final se generará un CFDI tipo 'P', y su captura se realizará a partir de la pantalla actual de CxC - Ingresar cobro. Hay muchas cosas que la aplicación deberá automatizar en el background, pero esa simplicidad en la que dejemos esta pantalla, deberá reflejarse en mayor número de clientes.
Campos adicionales son los que aparecen en letras rojas. Todo lo demás se tendrá que automatizar para generar el CFDI tipo pago, que es un CFDI rasurado mas el complemento de pago.
Los campos en * serán los que mas comúnmente se capturen. 
No sé si agregar los nuevos campos a la pantalla actual, o abrir una modal para capturar los datos nuevos.

![pantalla pagos](https://user-images.githubusercontent.com/2912775/27309539-090a09d6-551a-11e7-9af6-b79b0e839fd6.PNG)

**Comment by jccastillo0007** [comment]
CxC Ingresar Cobro = Captura de Pago o mas bien, genero otra página ?

**Comment by RigoFlores** [comment]
Afirmativo... CxC Ingresar Cobro = Captura de Pago
En esta pantalla, ahora mismo se capturan muchos de los datos del documento de recepción de pago.

Aquí había de 2 sopas:
a) dejar la pantalla tal cual está + un botón para abrir una ventana modal y capturar la información adicional requerida para el complemento de pago.
b) agregar los datos adicionales requeridos a la pantalla actual.

La opción que se propone aquí, es la (b).

**Comment by jccastillo0007** [comment]
ya estoy haciendo pruebas de timbrado....  pregunta... al momento de generar un documento de pago, sigo guardando los registros del pago ingresado como en cxc ingresar cobro ? o aqui solo sería el cfdi de pago?

según yo, aqui mismo se debería hacer el desmadre que hicimos en cxc ingresar cobro...

**Comment by RigoFlores** [comment]
No entendí... pero lo que si te puedo comentar, es que la idea es que ingresar pago en el módulo de CxC, VA DE LA MANO CON EMISIÓN DE DOCUMENTO DE PAGO.
Mucha información del documento de pago, se captura AHORA MISMO cuando se ingresa un cobro. Entonces mas bien se pondrá un checkbox, para indicar que se desea además de capturar el pago, GENERAR EL DOCUMENTO DE PAGO, con lo que se presentarán los datos adicionales para capturar...

**Comment by jccastillo0007** [comment]
Ya esta generando la factura en PRU...

Con el RFC ACO y tu RFC como cliente

**Comment by jccastillo0007** [comment]
Aún no considera los CFDi relacionados.

**Comment by RigoFlores** [comment]
Pero entonces como lo genero paso a paso?. Yo intenté y me marca error... esta es la pantalla
![pagos](https://user-images.githubusercontent.com/2912775/30560038-400d1898-9c7c-11e7-8147-2649a566c8fc.PNG)

**Comment by RigoFlores** [comment]
El tema de CFDI's relacionados, precisamente se completa cuando eliges una factura por pagar.
Pregunta, porque duplicaste la pantalla si tiene exactamente lo mismo???

**Comment by RigoFlores** [comment]
Aquí tenemos 3 caminos:
a) El mas directo y simple, es ocupar el proceso de registro de pago, para igualmente generar (opcionalmente) el documento de pago. Es opcional, porque no siempre que registres un pago, querrás generar un documento de pago. Una vez que eliges la factura de la lista, se te llenarán los datos (sugeridos) que van a nivel de cada documento relacionado dentro del complemento de pago.
b) El otro, es elegir uno o varios XML del disco duro, para que de ahí se tome la información del pago.
c) El otro mas laborioso, es que pueda el usuario capturar todos los datos del documento pagado.

**Comment by RigoFlores** [comment]
Cómo va a quedar esa pantalla duplicada???

**Comment by jccastillo0007** [comment]
Voy a eliminar la anterior... por ahora la deje porque no me quedaba claro....

**Comment by jccastillo0007** [comment]
done
