### ISSUE TITLE
Web CFDI v3.3 - Automatización de Documento de Pagos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1045]
Todo inicia atendiendo los issues 1027 y 1028.
La serie del documento a generar, será por omisión: DRP

Cuando en la pantalla de ingreso de cobro, se elige el RFC del cliente o el número de cliente, se conocerá cuál es el RFC receptor.
Conforme se vayan eligiendo facturas para asociarles un cobro, el complemento correspondiente a la recepción de pago, tendrá que obtener la siguiente información directamente del XML o en su caso de la BD. Por ello es muy importante, que el XML se suba primero en la plataforma: ya sea por conector, por escritorio, por plataforma web o subiéndola cuando se timbre con otro proveedor.

Los datos que se tienen que automatizar, ya que se tomarán de la factura que se va a pagar son:
UUID
Folio
Serie
Moneda
Tipo de cambio
Metodo de Pago
Numero de Parcialidad (se debe calcular, con base a los pagos asociados previamente al mismo CFDI)
Importe Saldo Anterior.  Se calcula con base a lo que se debía al CFDI antes del pago
Importe Saldo Insoluto. Se calcula con base al saldo que aún quede pendiente en el CFDI asociado.

Básicamente es eso. Como la beisbol, está simple que no?

**Comment by jccastillo0007** [comment]
done.
