### ISSUE TITLE
EL TIMBRADOR NO ENVIA LA MONEDA CORRECTA AL PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1046]
Si el XML incluye moneda distinta a pesos, de todos modos envía pesos al PDF.

**Comment by jccastillo0007** [comment]
listo, en el release 10.2.0

**Comment by RigoFlores** [comment]
En la cantidad con letra, al PDF, aún envía pesos, cuando la moneda en el XML es USD. Supongo que sucederá con cualquier moneda que sea distinta a pesos.
