### ISSUE TITLE
CFDI v3.3 - Variables nuevas para el PDF a nivel general

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1047]
A GENERAL:

usoCfdi   (clave.descripcion)
residenciaFiscal   (aplica para clientes extranjeros, es la clave y nombre del país)
numRegIdTrib   (aplica solo en el caso de complemento de comercio exterior)
tipoRelacion  (clave.descripcion)
cfdisRelacionados   (cadena de uuids, separados por ;)

**Comment by RigoFlores** [comment]
me faltó agregar esta...
tipoCfdi

esperamos recibir I, E, T, N o P

**Comment by jccastillo0007** [comment]
listo.

**Comment by RigoFlores** [comment]
chiaaaa... le pones el nombre que sea, menos el solicitado...
