### ISSUE TITLE
Conector CFDI v3.3 - Cuando ingresas 2 productos marca error en el nodo de impuestos trasladados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1048]
El nodo general de impuestos trasladados (es decir, no los impuestos a nivel producto), deben sumar los impuestos que tengan la misma combinación de impuesto, factor y tasa.
Actualmente forma el xml así, es decir está repitiendo el registro:

    <cfdi:Impuestos TotalImpuestosTrasladados="1120.00">
        <cfdi:Traslados>
            <cfdi:Traslado Impuesto="001" TipoFactor="Tasa" TasaOCuota="0.160000
" Importe="560.00"/>
            <cfdi:Traslado Impuesto="001" TipoFactor="Tasa" TasaOCuota="0.160000
" Importe="560.00"/>
        </cfdi:Traslados>

debería enviarlo así:

    <cfdi:Impuestos TotalImpuestosTrasladados="1120.00">
        <cfdi:Traslados>
            <cfdi:Traslado Impuesto="001" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="1120.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

**Comment by RigoFlores** [comment]
Solo se repetirán registros en ese nodo, si la combinación mencionada no existe previamente, por ejemplo, esta si es correcto que se repita, porque tasaocuota es distinto:

    <cfdi:Impuestos TotalImpuestosTrasladados="910.00">
        <cfdi:Traslados>
            <cfdi:Traslado Importe="560.00" Impuesto="001" TasaOCuota="0.160000" TipoFactor="Tasa"/>
            <cfdi:Traslado Importe="350.00" Impuesto="001" TasaOCuota="0.100000" TipoFactor="Tasa"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
pasame un txt con dos productos... pero que cuadren todas las sumas y restas de totales e impuestos.

**Comment by jccastillo0007** [comment]
crap...

**Comment by jccastillo0007** [comment]
fixed.
