### ISSUE TITLE
Conector v3.3 - Error con variable descuentoPro a nivel producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1049]
Las demas variables las acepta, pero en particular descuentoPro, marca error. Será que tenemos tipos distintos?

**Comment by jccastillo0007** [comment]
Ups... estaba como double... no me fije que todas son string.

fixed

**Comment by RigoFlores** [comment]
Negativo, sigue enviando error cuando incluyo esa variable en el jasper

**Comment by jccastillo0007** [comment]
Negativo lo negativo... debe ser algo en jasper, acabo de confirmar que la variable lleva este contenido
descuentoPro=$0.00

Lo puedes ver en el log arroja todo lo que se manda a jasper
