### ISSUE TITLE
Cuando existen varios rangos de folios sin serie, solamente se puede elegir uno de ellos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#105]
Si se cuenta con 2 o mas rangos sin serie y se quiere consultar o editar alguno de ellos, la aplicación siempre muestra el mismo rango, aunque se elija cualquiera de ellos.
Es decir, por la posición en la lista desplegada, existen 2 series SIN SERIE en distinta posición. Aunque se elija cualquiera de ellas, siempre muestra la misma serie.

**Comment by RigoFlores** [comment]
Aplica si se cuenta con serie o sin ella, en el rango de folios.

**Comment by jccastillo0007** [comment]
Done. Para la pantalla de catalogo de folios
No Done. Para la pantalla de factura.... siempre elige el primer rango de folios.

**Comment by RigoFlores** [comment]
Este issue se debe resolver, una vez que no se permita capturar folios con la misma serie.
Voy a cerrar este, para atenderlo desde el otro.
