### ISSUE TITLE
Conector v3.3 - Solo acepta moneda nacional

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1050]
No está tomando otras monedas del layout

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Falta enviar la descripción de la moneda en el PDF, en la variable moneda.

**Comment by jccastillo0007** [comment]
se mandará como USD.DOLAR ESTADOUNIDENSE  o MXN.PESO MEXICANO... de acuerdo al catálogo del SAT.
