### ISSUE TITLE
Conector v3.3 - no acepta la clave de impuesto IVA a nivel producto para trasladados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1057]
Debería ser la 002, pero solo acepta 001 que es el ISR, y ese no es impuesto trasladado, sino retenido.
Cuando le coloco 002, pone todo lo relacionado a impuestos en null.

**Comment by jccastillo0007** [comment]
Según mis datos, el impuesto 002 es el ISR no IVA , es decir, 001 = iva y 002 = isr

**Comment by RigoFlores** [comment]
Creo que tus datos están chuecos, aquí el catálogo del sat:
![catimpuestos](https://user-images.githubusercontent.com/2912775/28173560-6c8d45b6-67b4-11e7-816c-6d5c071e02aa.PNG)

**Comment by RigoFlores** [comment]
Como quiera, aún chuecos tus datos, no está aceptando el 002.

**Comment by RigoFlores** [comment]
te mandé un xml de la vida rial... está mas que confirmado que el IVA es 002.
Lo que no entiendo, es porqué finkok acepta 001 en impuestos trasladados, ya que el ISR de ninguna manera aplica para traslado; solo retención.

**Comment by jccastillo0007** [comment]
Ya cambié las claves... 001 = ISR, 002 = IVA y 003= IEPS.

ya timbre con 002 = iva... te debio llegar email
