### ISSUE TITLE
Conector v3.3 - No identifica correctamente el impuesto trasladado Ieps

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1059]
Lo reporta como si fuera impuesto retenido.
Aquí el ejemplo de la cadena...

concepto={10101505|ART-001|1|H87|PIEZA|RATAS IMPRESORA EPSON L355|informacion complementaria|3500.00|3500.00|||||Traslados[3500|001|Tasa|16.00000|560.00|3500|003|Tasa|0.0|0.0]Retenciones[|||||||||]extradata[|||||||||]}

**Comment by jccastillo0007** [comment]
Fixed.
