### ISSUE TITLE
Conector v3.3 - no jala el iva retenido

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1060]
No lo identifica correctamente

**Comment by jccastillo0007** [comment]
Ya jala, pero como agrega el complemento de leyendas fiscales, finkok marca error.

**Comment by RigoFlores** [comment]
no logro que jale...

**Comment by jccastillo0007** [comment]
el pedo aqui es que finkok manda una exception... e incluso se agrega el complemento de leyendas fiscales, y tal vez finkok no esta listo para algo asi...

**Comment by RigoFlores** [comment]
entonces hay que checarlo con finkok, que no?

**Comment by jccastillo0007** [comment]
ups... si estaba de nuestro lado...  no estaba creando la cadena original con la versión 3.3, cuando se le agregaba el complemento de leyendas fiscales

fixed.
