### ISSUE TITLE
Conector v3.3 - no jala el isr retenido

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1061]
Al igual que el iva retenido, marca null pointer exception

**Comment by jccastillo0007** [comment]
ya jala... pero ojo solo jala con isr retenido... si agregas iva retenido, le agrega el complemento de leyendas fiscales y con ese complemento finkok marca error.
Pero si usas solo isr retenido, si funciona

**Comment by jccastillo0007** [comment]
yo timbre uno con isr retenido con esta linea como concepto
concepto={01010101|ART-001|1|H87|PIEZA|IMPRESORA EPSON L355|informacion complementaria|3500.00|3500.00|||||Traslados[3500|001|Tasa|16.00000|560.00|||||]Retenciones[3500|002|Tasa|4.00000|140.00|||||]extradata[|||||||||]}

además los totales estaban mal... y ahorita finkok ya valida que la sumas y restas sean correctas... tuve que modificar tambien el total
aqui te pongo todo el archivo.

tipoDeComprobante=0
lugarExpedicion=76160
regimen=601
receptor=TIA101020BP4|COPPEL, S.A. DE C.V. .|||||||||||soporte@factura-t.com.mx|RESIDENCIA_FISCAL|NumRegIdTrib
usoCFDI=G03
serie=DD
folio=28170
formaDePago=02
condicionesDePago=60 DIAS FECHA FACTURA
metodoDePago=PPD
confirmacion=
CFDIRelacionados=
concepto={01010101|ART-001|1|H87|PIEZA|IMPRESORA EPSON L355|informacion complementaria|3500.00|3500.00|||||Traslados[3500|001|Tasa|16.00000|560.00|||||]Retenciones[3500|002|Tasa|4.00000|140.00|||||]extradata[|||||||||]}
subtotal=3500.00
descuento=
moneda=MXN|1
totalImpuestosRetenidos=140.00
totalImpuestosTrasladados=560.00
total=3920.00
CA=|||||||||||||||||

**Comment by RigoFlores** [comment]
Si procesa esta información pero algo está chueco:
a) Clave 002 es del IVA
b) cuando se incluye la clave 002 si lo procesó como retención, pero las variables al PDF llegan en nulo.
c) si checas el layout, la posición donde colocaste el impuesto retenido, corresponde al IVA y no al ISR. 
d) si hace correctamente las sumas de trasladados y retenidos, pero la clave está chueca y así lo está aceptando finkok.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by jccastillo0007** [comment]
Bueno se arregló el tema de los id de impuestos, pero creo que a[un falla para enviarlos al pdf.

**Comment by jccastillo0007** [comment]
fixed * 2

**Comment by RigoFlores** [comment]
Efectivamente, falta enviar la información de retenciones de isr al PDF.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
a nivel de producto, no llega. Envié correo

**Comment by jccastillo0007** [comment]
fixed.
