### ISSUE TITLE
Conector v3.3 - no identifica tipo de relación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1062]
La sintaxis propuesta es así:

CFDIRelacionados=04|461114AD-6ED0-4090-8D56-C209285C4857

sin embargo, creo que tenemos que separar dichos campos:
tipoRelacion=
CFDIRelacionados={serie|folio},{serie|folio}
CFDIRelacionados={uuid}

Te comentaba hace tiempo, que en el conector, no estamos retroalimentando resultados al ERP origen. Entonces, o retroalimentamos para que conozcan el uuid, o no sé como lo van a obtener. Yo he trabajado con cientos de clientes, y no podrán copiar el uuid del XML. Quizás del PDF, pero aún asi no será tan simple.
Creo que debemos dar las 2 opciones:
(a) sintaxis para que nosotros busquemos internamente serie y folio y (b), que simplemente envien el uuid.
Cómo la beisbol???

**Comment by jccastillo0007** [comment]
Bueno por ahora ya tomar el tipo de relación.... hay que cambiarlo por la opción  a) con la serie y folio... 

tipoRelacion=
CFDIRelacionados={serie|folio},{serie|folio}


Pero para tus pruebas sigue manejando el layout anterior de tiporelacion|uuid

**Comment by RigoFlores** [comment]
afirmativo, por lo pronto jaló solo para este esquema:

CFDIRelacionados=04|461114AD-6ED0-4090-8D56-C209285C4857

pero si quiero agregar otro uuid, separado por coma,o por llaves y coma... no jala.

Creo que sería bueno soportar las 2 opciones... con uuid, y con serie folio... se distinguen por la longitud.
El uuid siempre tendrá la misma longitud y es un solo dato.
Serie folio, siempre llevarían el | intermedio entre las llaves..

**Comment by jccastillo0007** [comment]
No, hay que especificar un solo formato, ya que el procesamiento de parseo se hace en base a la posición o en base al número de datos entre pipes... para soportar una u otra, tendría que hacer varios cambios, y dado que ellos no conocen el uuid, mejor lo dejamos como folio y serie.

**Comment by RigoFlores** [comment]
Sigue jalando solo este formato:

CFDIRelacionados=04|461114AD-6ED0-4090-8D56-C209285C4857

pero no acepta mas de un uuid.

**Comment by jccastillo0007** [comment]
Ups... tenemos problemas houston...
Resulta que en standalone, no guardamos el uuid de cada factura después de ser timbrada... luego entonces, si nos dan serie y folio, no vamos a obtener el uuid.

Asi que tendrán que ponerlo ellos, o tendriamos que buscar otra opción, cómo buscar los archivos XML o algo asi... pero sería mucho desmadre.

El formato soportado seguiria siendo: 

CFDIRelacionados=04|461114AD-6ED0-4090-8D56-C209285C4857

Cómo la beisbol.?

**Comment by jccastillo0007** [comment]
Never mind... si lo tenemos en la tabla de detalle.

**Comment by RigoFlores** [comment]
chiiiaaaaa^2

**Comment by RigoFlores** [comment]
tons, para cuando?
Insisto en que pueda ser una u otra línea, ya que habrá de los 2 casos.
Lo actual, ya jala... es decir con el UUID
podemos poner la otra opció con otra etiqueta par que no estés adivinando...

**Comment by jccastillo0007** [comment]
Fixed.

Hay que agregar a los archivos txt estos dos renglones.

CFDIRelacionados={a|161045308},{b|11},{c|161040813}
TipoRelacion=04


bueno la primer línea ya existe, pero hay que agregar el formato de serie|folio

**Comment by RigoFlores** [comment]
Ya jala por serie y folio, pero ahora ya no jala lo del uuid.
Algunas ocasiones no se almacena en BD el detalle de la factura, sobre todo cuando cierran la aplicación inmediatamente después de generar la factura. Ahí se pierde todo lo facturado en la última sesión.
Algunas otras ocasiones, es probable que el folio se repita... entonces ahí mandaría n uuids.

Yo si preveo desde ahora mismo, que serán necesarios 2 mecanismos para que el cliente elija. Lo podemos mantener así por lo pronto, pero como diría la abuela..."te vas a acordar de mi...", jeje
