### ISSUE TITLE
Conector v3.3 - no envia la descripción en la unidad del SAT del Producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1063]
Enviar la clave de la unidad y su descripción, ejemplo:

"H87.PIEZA"

En teoría también para el productoservicio del SAT, pero eso lo aguantaremos, yo creo que no es necesario por lo pronto.

**Comment by jccastillo0007** [comment]
No estamos guardando el catálogo de unidades del sat, de hecho en web tienen que capturar ellos la clave del sat.

La opción sería ponerla en el layout algo como key.descripcion... porque son un chingo como para cargarlo en memoria

**Comment by RigoFlores** [comment]
tssss.... esa si que es a oevito...

**Comment by jccastillo0007** [comment]
Estos datos se enviarán desde el archivo txt, así que no hay delito que perseguir.

**Comment by RigoFlores** [comment]
OK, lo que si puede pasar, es que se genere inconsistencia a nivel PDF, pero como lo acordaos así salimos por lo pronto.
