### ISSUE TITLE
Conector v3.3 - error en dato de seguridad key

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1065]
envía este error con ciertos archivos. Ya te los envié por correo

**Comment by jccastillo0007** [comment]
Si, también lo he visto... pero he validado los XML que generamos y si pasan la validación de finkok... sin embargo.. al momento de timbrar, marca este error :   

2017-07-16 23:24:30,284 DEBUG [http-bio-8080-exec-6] (FinkokService.java:80) - Sign CFDi request @ : http://demo-facturacion.finkok.com/servicios/soap/stamp?wsdl
2017-07-16 23:24:30,700 ERROR [http-bio-8080-exec-6] (FinkokService.java:143) - org.springframework.ws.client.WebServiceTransportException: Bad Gateway [502]
org.springframework.ws.client.WebServiceTransportException: Bad Gateway [502]

Y según yo no esta de nuestro lado.

**Comment by RigoFlores** [comment]
Si efectivamente no lo marca siempre con el mismo archivo.
Puedes checar con finkok?
Entiendo que seguimos ambiente de prueba con finkok, correcto?

**Comment by jccastillo0007** [comment]
Este error estaba relacionado con el tema de que no tomaba el template de 3.3 para la cadena original... ahorita ya pude timbrar los archivos que me enviaste.

**Comment by RigoFlores** [comment]
Seguimos haciendo el oso con finkok?... jejeje
