### ISSUE TITLE
Conector v3.3 - no toma en cuenta el subtotal cuando se incluyen descuentos en el producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1066]
El subtotal es la suma de importes de los productos.
El importe es cantidad * precio unitario.

SubTotal
Es la suma de los importes de los conceptos antes de descuentos e impuestos. No se permiten valores negativos.

Lo que está haciendo es restando el descuento al subtotal, y por ello marca error:

2017-07-18 00:00:30,302  INFO [pool-2-thread-1] (CFDiWSClient.java:77) - Factura
Ti ack : com.facturati.ws.binding.jaxb.Ack@1d9313[code=003,description=El TipoDe
Comprobante es I,E o N, el importe registrado en el campo no es igual a la suma
de los importes de los conceptos registrados.]

no está tomando en cuenta el subtotal incluido en el archivo. Lo eliminamos o lo consideramos?

**Comment by jccastillo0007** [comment]
Alcance a meter el fix de este issue..

**Comment by RigoFlores** [comment]
Todo quedó bien a nivel XML.
A nivel PDF, en el subtotal de la factura suma los importes MAS los descuentos.
Realmente solo debe sumar los importes.
Envié un correo con el detalle

**Comment by jccastillo0007** [comment]
fixed.
