### ISSUE TITLE
Conector v3.3 - No envía correctamente las variables base, para impuestos a nivel general.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1068]
Está enviando la base del primer producto, pero tiene que enviar la base de la suma de los productos con la misma tasa.
Ejemplo, si tenemos dos productos de $100.00 cada uno. A nivel producto la base del impuesto es $100.00, la tasa es del 16% y el importe del IVA es de $16.00.
A nivel de la factura la base es $200.00, la tasa es 16% y el importe del IVA son $32.00

A nivel factura, las variables que deben contener este valor son las abajo mencionadas. Recordar que son hasta 3 variables, porque agrupan los datos cuya combinación: impuesto y tasa, son iguales. En el ejemplo de arriba, se trata de IVA trasladado con tasa del 16%.

baseTrasladoIva1
baseTrasladoIva2
baseTrasladoIva3
baseTrasladoIeps1
baseTrasladoIeps2
baseTrasladoIeps3
baseRetencionIva1
baseRetencionIva2
baseRetencionIva3
baseRetencionIsr1
baseRetencionIsr2
baseRetencionIsr3

**Comment by jccastillo0007** [comment]
Done.
