### ISSUE TITLE
Conector v3.3 - no procesa el impuesto trasladado IEPS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1069]
No jala, ya que a nivel producto lo reporta como impuesto 003 (correcto), pero a nivel general lo reporta como 002. Esta salida de la consola, solo incluye IEPS, pero no IVA.

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="10101505" NoIdentificacion="ART-001" Canti
dad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="RATAS IMPRESORA EPSON L
355 informacion complementaria" ValorUnitario="4000.00" Importe="4000.00">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="4000.00" Impuesto="003" TipoFactor="Tas
a" TasaOCuota="0.500000" Importe="2000.00"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="2000.00">
        <cfdi:Traslados>
            <cfdi:Traslado Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.500000
" Importe="2000.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
</cfdi:Comprobante>

El error que marca es:

2017-07-19 18:37:44,579  INFO [pool-2-thread-1] (CFDiWSClient.java:77) - Factura
Ti ack : com.facturati.ws.binding.jaxb.Ack@4382f9[code=003,description=El valor
seleccionado debe corresponder a un valor del catalogo donde la columna impuesto
 corresponda con el campo impuesto y la columna factor corresponda con el campo
TipoFactor]

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Trabaja bien si solo incluyes el IEPS, pero no el IVA. Cuando incluyes los 2 impuestos trasladados, los reporta bien a nivel concepto, pero solo reporta uno a nivel genera, y por ello marca este error:

2017-07-20 11:11:36,260  INFO [pool-2-thread-1] (CFDiWSClient.java:77) - Factura
Ti ack : com.facturati.ws.binding.jaxb.Ack@1ac57dd[code=003,description=El campo
 Total no corresponde con la suma del subtotal, menos los descuentos aplicables,
 m├ís las contribuciones recibidas (impuestos trasladados - federales o locales,
 derechos, productos, aprovechamientos, aportaciones de seguridad social, contri
buciones de mejoras) menos los impuestos retenidos.]
