### ISSUE TITLE
Conector v3.3 - voy a eliminar la línea de descuento, ya que no se toma en cuenta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1071]
El descuento reportado al XML, se calcula a partir de los descuentos individuales a nivel producto.
Con ello la línea de descuento a nivel general es ignorada totalmente. 
Para depurar el archivo, la voy a eliminar del layout, le ves algún problema?????

**Comment by jccastillo0007** [comment]
mmmm actualmente no esta haciendo calculos, solo traslada la información, igual pasa con total y subtotal, asi que mejor lo dejamos.

Solo para pagos si aplica, porque no hay nada de descuentos en ningún lado

**Comment by RigoFlores** [comment]
Actualmente SI ESTÁ HACIENDO CÁLCULOS SUMANDO LOS DESCUENTOS A NIVEL PRODUCTO Y REPORTÁNDOLOS EN EL XML, AL IGUAL QUE SUMA Y AGRUPA LOS IMPUESTOS.
La línea de descuento a nivel general, LA IGNORA TOTALMENTE.
Te mandaré un correo para que corrobores lo que te digo.

Entonces, una vez que lo compruebes, entiendo que estarías de acuerdo en que se borre dicha línea?

**Comment by jccastillo0007** [comment]
Ok, ya se soporta el txt sin descuento, te mande por correo un txt con el que ya se genera un cfdi sin errores.
