### ISSUE TITLE
CFDI v3.3 - Sacar el catálogo de unidades a un menú, así como monedas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1073]
Es ese catálogo deberán capturar la clave de unidad del SAT, así como la descripción del SAT, y por si acaso la unidad interna.
Quizás esta última ya no se ocupe, pero no lo sabemos hoy.
Aquí en este catálogo, poner liga para descargar el catálogo de unidades del SAT.

El deber ser es que cuando le dieran agregar, se desplegara el catálogo de unidades del SAT, y que ellos fueran eligiendo las unidades que ocupan, a partir de dicho catálogo. Esto sería ideal, pero si no es posible, la solución chacarrona de arriba... ya que.

**Comment by jccastillo0007** [comment]
done

ahi mismo se agregará la clave de unidad del sat, y de ahi se tomará para ser enviada al xml y pdf

**Comment by RigoFlores** [comment]
OK, cambiar etiquetas:
clave SAT
Descripcion SAT
Descripcion Interna

**Comment by jccastillo0007** [comment]
No existe Descripción SAT, chiaaaa

**Comment by jccastillo0007** [comment]
vi lo que mencionaste de las unidades en el ticket de monto base por impuesto... chiaaaa

Hay que dejar solo una descripción... al xml se manda solo la clave asi que no necesitamos ambas.

**Comment by RigoFlores** [comment]
ah si, me equivoqué...
OK...
