### ISSUE TITLE
Producción - Mensaje de error en conector Navision (SQL Server)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1074]
DESDE SIEMPRE HEMOS TENIDO ESPORÁDICAMENTE ESTE ERROR. NO SÉ A QUE SE DEBA, QUIZÁS A CONCURRENCIA… QUE SE YO… AHORA ESTAMOS RETOMANDO EL TEMA, Y LOS ESPAÑOLES DICEN QUE ESTÁ DE NUESTRO LADO… COMO LA BEISBOL??

2017-06-15 02:20:49.0032 ERROR pool-5-thread-1 org.hibernate.util.JDBCExceptionReporter La transacción (Id. de proceso 55) quedó en interbloqueo en bloqueo recursos con otro proceso y fue elegida como sujeto del interbloqueo. Ejecute de nuevo la transacción.

ENCONTRÉ ESTA LIGA, SEGURAMENTE HAY MUCHAS MAS… HAY QUE APROVECHA LA MIGRACIÓN PARA ATENDER ESTE PROBLEMA… la segunda liga, la manda el informático de españa... chiaaaa

https://social.msdn.microsoft.com/Forums/es-ES/1cb134b7-38bb-44f7-8f54-d70ff421bab2/la-transaccin-id-de-proceso-qued-en-interbloqueo-en-lock-recursos-con-otro-proceso-y-fue?forum=sqlserveres

https://www.google.es/url?sa=t&source=web&rct=j&url=https://stackoverflow.com/questions/17907443/error-org-hibernate-util-jdbcexceptionreporter-cannot-load-jdbc-driver-class&ved=0ahUKEwiKuoe6jKnVAhXBVRQKHdJBAIYQFggcMAA&usg=AFQjCNEKCJoRXspaCAAgRDNMKgrQ6sHPEQ

**Comment by RigoFlores** [comment]
este si se sigue presentando.

**Comment by jccastillo0007** [comment]
supongo que ya no se presenta, pues no han dicho nada y ya tiene un anio...

**Comment by RigoFlores** [comment]
recuerda que este error es esporádico... si se sigue presentando... y el motivo es muy simple, cuando hay coincidencia de lectura en la tabla Factura-T entre las dos aplicaciones, navision y ft, se presenta, ya que como me has comentado, ft es monousuario hacia la bd y ellos seguramente no.
Total que si se presenta, pero hay issues de mucho mayor prioridad.
Cuando se presenta, me reportan y yo reinicio el sistema.

Lo cerraré, pero pues no está atendido. Sigamos con otros de mayor prioridad.
