### ISSUE TITLE
Producción - Error en nómina cuando no aplican deducciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1076]
ESTO LO CACHÉ DEL CATY.AUT
LO RESALTADO EN AMARILLO NO DEBERÍA INCLUIRSE, YA QUE NO APLICA LA DEDUCCIÓN… EN EL CASO DE NO HABER DEDUCCIONES, SIMPLEMENTE SE OMITE EL NODO (YA QUE ES OPCIONAL DE ACUERDO A LA SPEC), PERO DE ESTA MANERA QUE SE REPORTA AHORA MISMO, MARCA ERROR AL TIMBRAR…
ES COMO CUANDO NO APLICAN OTROS PAGOS, SIMPLEMENTE NO SE REPORTA EL NODO… 

    <cfdi:Emisor rfc="RIRV780214CA6" nombre="Valentin Rios Ramirez">
        <cfdi:RegimenFiscal Regimen="612"/>
    </cfdi:Emisor>
    <cfdi:Receptor rfc="RUCG7604101UA" nombre="GONZALO RUBIO CHAVEZ"/>
    <cfdi:Conceptos>
        <cfdi:Concepto cantidad="1" unidad="ACT" descripcion="Pago de nÃ³mina" valorUnitario="1694.15" importe="1694.15"/>
    </cfdi:Conceptos>
    <cfdi:Impuestos/>
    <cfdi:Complemento>
        <nomina12:Nomina FechaFinalPago="2017-08-06" FechaInicialPago="2017-07-31" FechaPago="2017-08-05" NumDiasPagados="7.000" TipoNomina="O" TotalPercepciones="1694.15" Version="1.2">
            <nomina12:Emisor Curp="RIRV780214HQTSML01" RegistroPatronal="Z341414210"/>
            <nomina12:Receptor AntigÃ¼edad="P93W" ClaveEntFed="QUE" Curp="RUCG760410HQTBHN00" Departamento="OPERATIVO" FechaInicioRelLaboral="2015-10-19" NumEmpleado="26" NumSeguridadSocial="14927540733" PeriodicidadPago="02" Puesto="AYUDANTE GENERAL" RiesgoPuesto="4" SalarioBaseCotApor="110.03" SalarioDiarioIntegrado="115.0" Sindicalizado="No" TipoContrato="01" TipoJornada="01" TipoRegimen="02"/>
            <nomina12:Percepciones TotalExento="1095.6" TotalGravado="598.55" TotalSueldos="1694.15">
                <nomina12:Percepcion Clave="003" Concepto="Participacion de los Trabajadores en las Utilidades PTU" ImporteExento="1095.6" ImporteGravado="598.55" TipoPercepcion="003"/>
            </nomina12:Percepciones>
            <nomina12:Deducciones/>
        </nomina12:Nomina>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by jccastillo0007** [comment]
fixed.

Pero hay que hacer varias pruebas, para asegurar que no se rompe nada.

**Comment by RigoFlores** [comment]
Realmente solo hice con y sin deducciones... y parece que está bien... donde sospechas que podría ser otro escenario de error?
Esto ya está en producción?? si apenas lo vas a subir, puedes inicializar el catalina.out o eso es por defaulta cada que reinicias?

**Comment by jccastillo0007** [comment]
ok, hoy lo subo y limpio el catalina out.

si funciona con y sin deducciones, entonces debemos estar bien, pues no se movió nada mas.
