### ISSUE TITLE
Conector v3.3 - marca error en las variables general de documentos de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1077]
Me está marcando error con las nuevas variables generales referentes a pago.
Si necesitamos eliminar variables, borrar todas las de datosextra21 en adelante, ya que el único cliente que lo ocupaba ya se desapareció y nos quedó a deber,,,

**Comment by jccastillo0007** [comment]
Fixed, con estos comentarios, te mandé por correo los templates buenos

1. Todas las variables deben empezar con minúsculas, ya lo cambié en el archivo que aqui te anexo

2. La variable fechaPago si existe, y esta definida para la nómina, pero como siempre se mandan todas, pues esa misma usé para el pago

3. La variable tipoCadPago, la tenías escrita con c minúscula y debe ser mayúscula

4. La variable fechaAduana no la habias eliminado del template de productos

5. La variable aduana se renombró por numeroAduana en el template de productos
