### ISSUE TITLE
Conector v3.3 - Documento de pago - envia al PDF como documento relacionado los documentos pagados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1078]
AL PDF envia como documentos relacionados, los documentos pagados, lo cual es incorrecto, ya que son cosas distintas.
Tipo de Relación y Documentos relacionados (a nivel general)
Documentos pagados (a nivel detalle).
Se resalta en amarillo
![doctorelacionadopago](https://user-images.githubusercontent.com/2912775/29102000-b20ded9e-7c7b-11e7-805b-24cccd4b20b0.PNG)

**Comment by jccastillo0007** [comment]
fixed.

Ya no manda los documentos relacionados en el mapo de cfdi relacionados... pero, a nivel producto, no tenemos donde enviar los documentos relacionados.
