### ISSUE TITLE
Producción - Opción de Ventas-Consultas-reenviar muestra correos incorrectos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1079]
Cuando envías una factura por correo, desde la opción de Ventas-Consultas-Enviar no está identificando los correos adecuadamente, cuando se trata de un RFC con varios clientes asociados:

El caso es:
Factura: 171055571
Cliente: 692350
RFC: XEXX010101000

Correos registrados en el catálogo de clientes para este cliente: C.Mackenzie@optibelt.ca; C.Stone@optibelt.ca

Correos incorrectos que aparecen cuando le das reenviar desde las consultas: s.sheeks@optibelt-usa.com; l.hudgins@optibelt-usa.com

Cabe mencionar que los correos incorrectos, son los que están asociados al cliente ‘base’, esto es cliente que aparece en la pantalla cuando eliges ese RFC (es decir, antes de cambiar a cualquier otro número de cliente).

**Comment by jccastillo0007** [comment]
Fixed.
ya esta en PRO junto con el otro error que se corrigió para la versión 3.2...
