### ISSUE TITLE
CFDI v3.3-Conector-No envía las variables de detalle al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1081]
Hay un mapeo chacarron que reutiliza variables a nivel producto, que antes jalaba pero ahora ya no..

PAGO | PRODUCTO ESTANDAR
-- | --
IdDocumento | unidad
Serie | idProducto
Folio | descripcion
MonedaDR | cuenta predial
TipoCambioDR | importe
MetodoDePagoDR | idProductoSAT
NumParcialidad | descripcionComplementaria
ImpSaldoAnt | valorUnitario
ImpPagado | cantidad
ImpSaldoInsoluto | descuento

**Comment by jccastillo0007** [comment]
fixed.

Tuve problemas con Internet ayer, checa si la última versión es de ayer aprox 12 am
