### ISSUE TITLE
Conector CFDI v3.3 - no envía la descripción del régimen del emisor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1082]
Únicamente envía la clave, falta la descripción

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ahora solo envía la descripción y no la clave...
recordar que el sat pide la clave y la descripción en el PDF.

**Comment by jccastillo0007** [comment]
chiaaaaa
fixed
