### ISSUE TITLE
Timbrador CFDI v3.3 - No envía todas las variables generales al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1083]
Las siguientes variables no se envían al PDF:
A nivel general:
Lugar de Expedición
Uso de CFDI
Método de Pago
Forma de Pago (lo envía como otros, y no como viene en el XML original)
Información de Documentos Relacionados (tipo de relación y cfdis relacionados)
Tasa de IVA  (revisar todos los impuestos)
Suma de impuestos trasladados  (revisar la sumatoria de los retenidos también)
Cantidad con letra envía PESOS en lugar de MXN

**Comment by jccastillo0007** [comment]
chiaaaa agregué las primeras 4... poco a poco voy a agregar las demás.

**Comment by RigoFlores** [comment]
De las primeras 4 variables reportadas como corregidas:
Lugar de Expedición - Incorrecto, el resto están OK.

**Comment by RigoFlores** [comment]
Ahora no envía el certificado SAT.

**Comment by jccastillo0007** [comment]
haber .... checale de nuez

**Comment by RigoFlores** [comment]
a) Forma de Pago .- le falta la descripción
b) No envía número de pedimento a nivel producto.
c) Está reportando retención de IVA en el PDF a nivel detalle y general, pero el XML original no lo lleva. Básicamente está repitiendo el IVA trasladado, como IVA retenido
d) Cuando si incluye retenciones de IVA e ISR en el XML original, no lo reporta en el PDF
e) el número de cuenta predial
f) la clave del régimen fiscal del emisor

**Comment by jccastillo0007** [comment]
Pasame los archivos XML con los que puedo probar los escenarios que mencionas... ya que todo debe cuadrar con los impuestos...

**Comment by jccastillo0007** [comment]
formaPago=02.CHEQUE NOMINATIVO //si lleva descripción

**Comment by jccastillo0007** [comment]
fixed.... 
las otras variables del b) al f) si tenian problemas.

**Comment by RigoFlores** [comment]
Ahora está pior... ya no procesa los archivos XML... y en pagos también marca error...

**Comment by jccastillo0007** [comment]
ya esta timbrando bien en PRU y Pagos también, solo continúa pendiente el problema de los XML... que jijos ya no me acuerdo..

**Comment by jccastillo0007** [comment]
supongo que este issue ya esta resuelto
