### ISSUE TITLE
Timbrador CFDI v3.3 - No envía todas las variables a nivel detalle

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1084]
A nivel producto, no llegan las siguientes variables al PDF:

ClaveProducto SAT
Clave-Descripcion Unidad SAT
Información de impuestos para los 4 tipos de impuestos estándar (base, clave, factor, tasa, importe) (

**Comment by jccastillo0007** [comment]
unidad y clave producto sat, ya estan...
Los impuestos son a nivel producto o a nivel global ?

**Comment by jccastillo0007** [comment]
checale con la versión de hoy

**Comment by RigoFlores** [comment]
El issue indica que es a nivel detalle (producto).
