### ISSUE TITLE
Conector CFDI v3.3 - no reporta correctamente la base de impuestos en nodo concepto, cuando se incluye descuento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1088]
Te mandé un correo con el texto que estoy probando.
Cuando el producto incluye un descuento, en el nodo de impuestos del concepto, no incluye correctamente el valor para base

**Comment by jccastillo0007** [comment]
fixed. aqui no se que paso, pero arreglé el tema de los impuestos iva e ieps, y luego probé este issue y si me funcionó.
