### ISSUE TITLE
Web v3.3 - Cuando defines IVA trasladado exento marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1089]
Ya que no debe enviarse el dato de tasaCuota, ni el importe.
Este es el error:

Si el valor registrado en el campo TipoFactor que corresponde a Traslado es Exento no se deben registrar los campos TasaOCuota ni Importe. (3).
Hoy en día así se genera en el conector, y aunque no marca error, no estoy seguro que así se reporte:

    <cfdi:Conceptos>
        <cfdi:Concepto Cantidad="1.00" ClaveProdServ="01010101" ClaveUnidad="H87" Descripcion="IMPRESORA EPSON L355 numero de serie: 1234567" Importe="3500.00" NoIdentificacion="ART-001" Unidad="PIEZA" ValorUnitario="3500.00"/>
    </cfdi:Conceptos>
    <cfdi:Impuestos/>

**Comment by jccastillo0007** [comment]
Pues aqui si no se como ayudar... si pones el número de pedimento en la pantalla de agregar producto, si lo agrega al xml.. pero finkok manda el error de que el número de pedimento es inválido

Te mando por correo el xml que acabo de generar

**Comment by jccastillo0007** [comment]
Ups.. el comentario anterior era para el issue de la aduana

**Comment by jccastillo0007** [comment]
fixed  te mando por correo el xml generado
