### ISSUE TITLE
No siempre envía el correo electrónico desde Están Alon

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#109]
Fíjate que tenemos un problema muy particular que ha empezado a generar ruido.
Resulta que cuando configuras una cuenta de gmail, como origen para enviar las facturas generadas por el sistema, en unas computadoras si lo hace (por ejemplo la mía) y en otras no (por ejemplo la de soporte). Yo tengo Windows 7 Home, y la otra Windows 7 Starter. Por donde crees que pudiera estar el problema? La versión de facturat y del java, es la misma en ambas máquinas.
Puedes agregarle algún nivel de debug, que nos indique cuál es el pedo?
Por cierto, también agregar un log especial, para indicar que las facturas se han enviado, o en su caso enviar el correo a otra cuenta de correo, por ejemplo la del emisor?

Esto sucedió con gmail; tenemos 2 clientes ya medio histéricos por este problema. Me comentas pls?

**Comment by jccastillo0007** [comment]
Pasame ambos logs para revisar

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
el problema es el antivirus. En algunos casos lo bloquea
