### ISSUE TITLE
Web CFDI v3.3 - no soporta los impuestos locales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1091]
Recordar que los impuestos locales, tienen definida su propia estructura... los impuestos locales son de mucha utilidad para las facturas de gobierno, y se reportan en un complemento.

OJO, aunque los estamos montando en la estructura de los impuestos estándar... lo cual es correctísimo para propósitos de su cálculo... al momento de reportarlo, deberá ser bajo la linea de impuestos locales, que es como sigue:

    <cfdi:Complemento>
        <implocal:ImpuestosLocales TotaldeRetenciones="45.0" TotaldeTraslados="0.0" version="1.0" xsi:schemaLocation="http://www.sat.gob.mx/implocal http://www.sat.gob.mx/sitio_internet/cfd/implocal/implocal.xsd">
            <implocal:RetencionesLocales ImpLocRetenido="5 al millar" Importe="45.0" TasadeRetencion="5.0"/>
        </implocal:ImpuestosLocales>
        <tfd:TimbreFiscalDigital xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" FechaTimbrado="2017-08-23T14:22:44" UUID="1EB930A6-99B4-4193-AA96-F1C80ACBA9F5" noCertificadoSAT="20001000000300022323" selloCFD="c/hIZ/GoXdo1VbksAvYSzxp9XqXu/nyeXn1gcjuCri0RaM8Om8tUnXrIh6C2/Ce3CdPQO/8eTxZ9veZ9V1gCnKa87E/HpSyiPHAY3yB1Uua83FiV46FyvI0sUQP9AWESPADK7DKtKb4o260L78sKTivJfvA0V18M7n+Hpn2GIhsxEJ9fpHXKQplCcEeOxu/OY1Q8yhXAfbuSBmrHqrnNbnMhMGVNdqDDPYEcPPmjFysGTYgNlNSCNWA1WGTX/sYAwu8YcH7jXoLfXWlbVur1Go4wcyEIfXN8M4YGFFj3DrByKhRu9koaWGUAQSIFaw0t4dXah3RpDrtAgwrEgGYbtA==" selloSAT="EDRGQchI5zzY1IAaFixznk5AzJ3oqjB88kc0s19prYoN/cQg1+FXj2KlyR92gIqlLp36p4xFkI6jQkjxRToaDSbtzK4eOvAoE7/OQPsADbR6WGMEGdaYyBvMDFG1Rmkf8UZy6UaXXHoBX+Wn4cE7hteaSXuv9CZrgaJdHCa1eU3h+McQMBmxPwdK9RUjzWHkHSOTRe91+Xh6LoAMtorMfzVZLKHrQl7F0sgKq8IXG3WxRq59txgtCPzD1+E9clMO4n1vwMK0V9Gw/dIhEE66B5u4SHsvqLukBndjy//TdfN8pyjcTzP4OAIpf7fDdZd/kzeFlMO9+UpEE5z9Y3NluA==" version="1.0" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/TimbreFiscalDigital/TimbreFiscalDigital.xsd"/>
    </cfdi:Complemento>

**Comment by jccastillo0007** [comment]
puedes checar, hay que dar de alta un impuesto local con valores de acuerdo al catálogo de impuestos, hice algunos cambios y ahora me envía esto :
 El valor del campo Impuesto que corresponde a Retención no contiene un valor del catálogo c_Impuesto.

con este xml 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="3.3" Folio="159" Fecha="2017-08-30T22:15:27" Sello="WcDQkzf7DQ8GLFocs4/4vn8V1JeLVp5W4ZkyNmW1MTp3A3Ekx6dLum38M/CxtZo96T+qK/yCysdkmRcqHfyVV2WpXpf3enotveWHf2JZ95QqpbwKQ+jYc366hGAOSkHo4Ie0p+t3s7VmMe/xGFYdffmvn6KKS5Qb0bxrwu1id6QKFfTDoOeFi8Y9gCYeltATOlfA6EFJjoOkmiO+ExP5+oqJBcY+h4TKQTCfjXCWraSTHxk0msfGiRAsMC++zqtdbF7r9Xi/tkkaDMo0Du7D8VmWVhmNdOWXorQYsvphTwrPhLwBvC1iM0zl8sSF1e2arYQ5rCM0Q8pzzwBp78lVdQ==" FormaPago="01" NoCertificado="20001000000300005692" Certificado="MIIF6zCCA9OgAwIBAgIUMjAwMDEwMDAwMDAzMDAwMDU2OTIwDQYJKoZIhvcNAQELBQAwggFmMSAwHgYDVQQDDBdBLkMuIDIgZGUgcHJ1ZWJhcyg0MDk2KTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMSkwJwYJKoZIhvcNAQkBFhphc2lzbmV0QHBydWViYXMuc2F0LmdvYi5teDEmMCQGA1UECQwdQXYuIEhpZGFsZ28gNzcsIENvbC4gR3VlcnJlcm8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQRGlzdHJpdG8gRmVkZXJhbDESMBAGA1UEBwwJQ295b2Fjw6FuMRUwEwYDVQQtEwxTQVQ5NzA3MDFOTjMxITAfBgkqhkiG9w0BCQIMElJlc3BvbnNhYmxlOiBBQ0RNQTAeFw0xNDExMjUwMDM3MjlaFw0xODExMjUwMDM3MjlaMIHXMScwJQYDVQQDFB5BTExJQU5DRSBFTVBF0U9TIFMgREUgUkwgREUgQ1YxJzAlBgNVBCkUHkFMTElBTkNFIEVNUEXRT1MgUyBERSBSTCBERSBDVjEnMCUGA1UEChQeQUxMSUFOQ0UgRU1QRdFPUyBTIERFIFJMIERFIENWMSUwIwYDVQQtExxBQ081NjA1MThLVzcgLyBIRUdUNzYxMDAzNFMyMR4wHAYDVQQFExUgLyBIRUdUNzYxMDAzTURGTlNSMDgxEzARBgNVBAsTClN1Y3Vyc2FsIDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6Rh93b3u9Av4e2WU8x28p2jRNcqSL2lcpQBw+95IBf0QdQn3y5Ghx2m/RhYwEOod9gUS7ER2E/+Rea5y0YItrcuPY0tWsql2ofER24luXBWxiD3+wjXbmoBSdmC+L/2/ZOl3m8Wk6iLxRIzTwDAGyQZup3LwVPC1zmWWVFM+d6TfGW4Ffe8sfR3XFRZusJQpO7JFDZUzCs/uFplVgtr1L2sYquhpwX4efUHpBFPYBIkXpUJMX3X5dAJyakEIJjw8mL3f5vyUkegHHngAO0ytbHayJ5eBApbRr7KYRQZbiSCn2UTtB9H5hSWN55iBwnCp4sPgD0PzcTzFAsyb+G4t9AgMBAAGjHTAbMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgbAMA0GCSqGSIb3DQEBCwUAA4ICAQCudqGjViZmgXKYh3JB2BSHy2/tPm1O5xrqWKe8IFzTIZKhDSfMBdmaF58MxfIpt2ccy3NDcr46n5ksnA4efkeNiZcR4U9W9dy19TjfHdZ4h8U/1jpk1DRb9AQO7/B7WCQL3ZY5yiRSJj+e4JG0SqrtPUgmMQIG6XNQUecAkDvqVEdPuovmvoQetKzFzJVt+KboaT3V5Wpmi56ojjupDnSM6ENqTmRrWSzizjVSTIYdLAu1d5k20MufxRd8IHP8VZED4BFvqeXJZkfaep/er0o7KzZZrcSCGCKtW1w8lMr9dX4fCDmcxNB4M22SqX0fx1IMvAGts2c6CXFFGe245wR1YqCvzAfyXTt/dYwh5kqWPjEm+PRUWD1woxkrpgn2P3Iv9BHXAlIvT+O943t6JQ9XBDlp1U/RNXDxvA/uWomCOUOrIkNsg4oQnxkc2geRtju5qkYhr7MEg8tyKYTNGqxNHJ+mOC4D3C0lC4lFerdnwEHrKk4+Pq0h9/f5AbFC73Crz4Vx7QjPvX6MjVcGvlfka+ov4zdtIc83/dPij3CSTUv9OCDrnfnaHlz8yQcF94dAOeW7ykYuimbZ6Hdi7JsnFMVHfDeDt9jDgQBBzoAdaJUxoYOA809sI1eZJR4kHEonlaiCGFqV6HpS6EtBVtfXft6j4DpLXQBqu8bIgYoSZA==" SubTotal="10.00" Moneda="MXN" TipoCambio="1" Total="11.10" TipoDeComprobante="I" MetodoPago="PUE" LugarExpedicion="62578" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd">
    <cfdi:Emisor Rfc="ACO560518KW7" Nombre="Usuario de pruebas de cfdi 33" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="FOPR681125BQ0" Nombre="RIGOBERTO MISAEL FLORES DE LA PAZ" UsoCFDI="G03"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="01010101" NoIdentificacion="cfdi33" Cantidad="1.00" ClaveUnidad="NA" Unidad="NA" Descripcion="pruebas para cfdi 33 ASDFASDF" ValorUnitario="10.00" Importe="10.00">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="10.00" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="1.60"/>
                </cfdi:Traslados>
                <cfdi:Retenciones>
                    <cfdi:Retencion Base="10.00" Impuesto="" TipoFactor="Tasa" TasaOCuota="0.050000" Importe="0.50"/>
                </cfdi:Retenciones>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="1.60">
        <cfdi:Traslados>
            <cfdi:Traslado Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="1.60"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
    <cfdi:Complemento>
        <implocal:ImpuestosLocales xmlns:implocal="http://www.sat.gob.mx/implocal" TotaldeRetenciones="0.5" TotaldeTraslados="0.0" version="1.0" xsi:schemaLocation="http://www.sat.gob.mx/implocal http://www.sat.gob.mx/sitio_internet/cfd/implocal/implocal.xsd">
            <implocal:RetencionesLocales ImpLocRetenido="5% AL MILLAR  C.M.I.C." Importe="0.5" TasadeRetencion="5.0"/>
        </implocal:ImpuestosLocales>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by RigoFlores** [comment]
Bueno, aquí hay varias cosas por comentar:
a) los impuestos locales no se reportan a nivel concepto, ya que no caen dentro del IVA, IEPS o ISR, ya sea trasladado o retenido.
b) Los impuestos locales se reportan únicamente a nivel de complemento.
c) Para no diferenciar entre la captura de un impuesto estándar y uno local, se toma la misma infraestructura, pero se reporta de manera particular al XML, esto es solo como complemento.
d) Entiendo del XML que subiste aquí, e incluso por el mensaje de error tan claro, que el error está en esa parte dentro del nodo de concepto, que evidentemente no debe existir cuando se trata de impuestos locales:

cfdi:Retenciones
<cfdi:Retencion Base="10.00" Impuesto="" TipoFactor="Tasa" TasaOCuota="0.050000" Importe="0.50"/>
</cfdi:Retenciones>

**Comment by jccastillo0007** [comment]
fixed.
