### ISSUE TITLE
Web CFDIv3.3 - marca error al facturar en moneda extranjera

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1092]
Te envía el siguiente error:

El campo Total no corresponde con la suma del subtotal, menos los descuentos aplicables, más las contribuciones recibidas (impuestos trasladados - federales o locales, derechos, productos, aprovechamientos, aportaciones de seguridad social, contribuciones de mejoras) menos los impuestos retenidos. 

yo creo que tiene que ver con que no se maneja el tipo de cambio a 6 decimales.

**Comment by jccastillo0007** [comment]
SubTotal="0.52" Moneda="USD" TipoCambio="19.123321" Total="0.61" 

Si se maneja a 6 decimales... pero como el total y subtotal se redondea, ahi se pierde un decimal...

**Comment by RigoFlores** [comment]
nos tendremos que meter a unos cálculos bien raros que hace el sat???

**Comment by RigoFlores** [comment]
´no está tan mal... inicialmente, el sat propone truncar o redondear.
Arranquemos con truncar que es lo mas sencillo.... peeeeeeeeeeero....
esto se realiza en el importe a nivel producto... porque???.... porque se debe truncar a los decimales que soporta la moneda en cuestión... ya comentamos que en general son 2 decimales....
con ello, el importe DEBE SALIR TRUNCADO A 2 DECIMALES.... una vez que el importe se maneja a 2 decimales.... el subtotal.... queda a 2 decimales también... y de ahí, todo debería cuadrar...

**Comment by jccastillo0007** [comment]
pero lo hago para todas las monedas o solo si es diferente de Pesos.

**Comment by RigoFlores** [comment]
Este es un asunto bastante delicado... ya que para algunos clientes no les cuadrará de manera precisa... impleméntalo para todas las monedas y deja revisar los números que arroja... con base a ello, tomamos alguna decisión... 
En teoría, ahora se debería hacer un cálculo de limite inferior y límite superior para el cálculo del importe... es un buen desmadre, y a la mera hora según yo, truncando se arma... pero bueno, vamos viendo

**Comment by jccastillo0007** [comment]
como esta medio cabrón... le metí una validación solo para monedas diferentes de MXN, y como el total y totales de impuestos son datos duros y el subtotal es mas volatile, entonces si hay algo que ajustar durante el redondeo, lo hago en el subtotal.

**Comment by RigoFlores** [comment]
no entendí... a ver otra vez...
