### ISSUE TITLE
Web CFDI v3.3 - no envia todas las variables generales al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1093]
Falta certificadoSAT y selloSAT

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Falta la descripción de la forma de pago..

**Comment by jccastillo0007** [comment]
mmmmta, otra vez reportando una por una...

**Comment by jccastillo0007** [comment]
Esto es lo que se manda a jasper
formaPago=01.EFECTIVO
que es lo que le falta?

**Comment by RigoFlores** [comment]
No falta... yo lo trunqué por código... chiaaaaa
