### ISSUE TITLE
Conector CFDI v3.3 - generar versión para producción

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1094]
Necesito ver si timbra en producción... igualmente probar la cancelación

**Comment by jccastillo0007** [comment]
Pssss todas las versiones que te paso a ti, son para producción, solo cambia el properties... sirve que checas si jala o no jojojo

**Comment by RigoFlores** [comment]
ojala fuera así de transparente... no jaló

**Comment by jccastillo0007** [comment]
?

**Comment by RigoFlores** [comment]
??... si tienes duda en el issue... el punto es que tu comentaste que toda versión que liberas es para producción... y me queda claro que toda la logística si, pero el pedo es el web service de producción... y a eso se refiere este issue... no está jalando en producción

**Comment by RigoFlores** [comment]
Estoy negociando con facturehoy el precio... según su cotización, el precio es mas IVA.
Ya acordé que al menos, el precio me lo consideren con IVA incluido, y estoy en la espera de un descuento adicional... si se puede que mejor.

**Comment by jccastillo0007** [comment]
listo 

https://efacturat.com.mx/eFacturaT3.3

**Comment by jccastillo0007** [comment]
Hoy te paso una version de connector apuntando a PRO de 3.3

**Comment by RigoFlores** [comment]
pues teorícamente ya está apuntando a producción... pareciera que sigue a pruebas, por el mensaje de error que mandó.

**Comment by jccastillo0007** [comment]
listo... hoy subi una versión que apunta a pro, incluso la probé tratando de generar un cfdi de pagos, pero fallo por mi régimen... pero ya esta apuntando a PRO.

**Comment by RigoFlores** [comment]
Pregunta, entonces esta versión no podrá cambiar de producción a pruebas, solo cambiando la bandera correspondiente en el properties??

**Comment by jccastillo0007** [comment]
Si, si es posible, funciona exactamente igual.

JC.

Saludos.
JC.
