### ISSUE TITLE
Web v3.3- Catálogo de formas de pago no está actualizado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1095]
a) Hay que ordenarlo en forma descendente.
b) 99 su descripción no es Otros, sino Por Definir
c) Le falta la clave 30.Aplicacion de Anticipos
d) El NA.NA ya no existe en el catálogo.

**Comment by jccastillo0007** [comment]
fixed.... ojo.... esto hay que hacerlo en PRO... voy a generar un readme.txt con todo l oque hay que hacer en PRO en la base de gatos.

**Comment by RigoFlores** [comment]
Todos los issues corregidos hay que llevarlos a pro, o como?

**Comment by jccastillo0007** [comment]
es que este es un cambio en base de datos... el resto se va con el código mismo... una razón mas por las que a veces no es bueno usar catálogos en bd

**Comment by RigoFlores** [comment]
yo creo que todo lo que tienes en tablas, que se despliega en combos (que debería ser todo, pero no lo es), debes preparar ya el query que corresponde a la actualización.
