### ISSUE TITLE
Web CFDI 3.3 - Catálogo de tipo de relación inválido

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1097]
Le falta el 06 y 07
y le sobra el R06

PD. recuerdas mis peticiones que todo catálogo estuviera en BD????...

**Comment by jccastillo0007** [comment]
Si, pero no me agrada, al menos no para este tipo de datos.

**Comment by jccastillo0007** [comment]
done.

Ojo... hasta la tarde voy a subir el release de lo que estoy haciendo... te aviso por email

**Comment by RigoFlores** [comment]
negativo, le falta la clave al 07

**Comment by jccastillo0007** [comment]
chiaaaa, le faltó el prefijo... malditas prisas.
fixed.

**Comment by RigoFlores** [comment]
sigue faltando la clave...

**Comment by jccastillo0007** [comment]
ahora si ya lo subi.
