### ISSUE TITLE
Web CFDI v3.3 - marca error con cantidad de producto distinta a 1

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1098]
Cuando agregas producto, y le cambias la cantidad... marca error... según yo es el mismo problema de la moneda... algo está mal por ahí...

El valor del campo Importe o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido (3)

Necesito el XML que se manda a timbrar, tanto en monedas distintas a MXN, como en este caso.. para analizar la falla

**Comment by jccastillo0007** [comment]
fixed.
