### ISSUE TITLE
Catalogo de clientes - muestra null en el dato de email

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#11]
El email muestar null si no se tiene capturado previamente

**Comment by jccastillo0007** [comment]
Done

**Comment by jccastillo0007** [comment]
Not yet ..... jojojo

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
NO PUEDO VALIDARLA, YA QUE NO MUESTRA LA INFORMACIÓN DEL EMAIL EN EL CATÁLOGO DE CLIENTE.

**Comment by RigoFlores** [comment]
VALIDADO, OK
