### ISSUE TITLE
Addenda Mabe

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#110]

**Comment by jccastillo0007** [comment]
plantaEntrega. No incluyó esta información super importante en la addenda. Creo que falta todo ese nodo.

codigoArticulo. Es requerido por addenda, pero no por el SAT. El XML origen NO lo contiene. Cuando no se incluya en el XML origen, colocar ID_GenericoFacturaT

descripcion="ESTUDIOS DE EVALUACION DE ASSESSMENT CENTER : ES",

AQUÍ LE COLOCÓ TEXTO DE MAS. DEBE TRUNCAR A 50 CARACTERES SI ES EL CASO que la cadena sea más larga, PERO NUNCA LLENAR CON ‘CARACTERES DE MAS’

JC. Este campo lleva Concepto + Descripcion, con un maximo de 50 caracteres, ahora quedo solo el Concepto. No se porque estaba asi, seguramente asi me lo habias pedido.

Aquí es parte del web, donde el famoso campo descripción sigue causando ruido + ruido + ruido. En web tenemos según entiendo: Concepto, Descripción (detallada) e Información Complementaria. Al PDF se envía Concepto + Descripción + Información Complementaria (aquí la petición sería quitar descripción, ya que por lo que veo, ahora hasta a ti te genera ruido; sigo sin verle utilidad hoy por hoy, y solo genera ruido).

Por otro lado, en el XML no existe un campo concepto. Existe el nodo concepto, y el parámetro descripción. Aquí se estaba duplicando eso. Me preocupa que se haya tratado de duplicar la descripción en este caso.

Tipo de Cambio. Solamente se incluirá cuando se contenga en el XML.

Validaciones:

 a)      El RFC emisor en el XML, debe ser el mismo asociado a la licencia del FacturaT. De lo contrario genera un XML, formando una imagen que diga ‘huevos’ o algo similar… jejejeje (en este caso nos intentarían meter gol).

b)      El RFC del receptor, deberá ser alguno del grupo MABE (ya lo habías comentado, pero igual confirmo).

c)       Manejaremos 2 esquemas del addendador

```
                                         i.            Pago anual emisión ilimitada de addendas

                                       ii.            Pago individual de addendas
```

 En ambos casos al igual que en la factura, se llevará un control ‘de folios’, junto con la vigencia.

En el caso de ilimitados, le asignaremos pinche mil folios; en el caso de pago individual, se asignará el número de addendas adquiridas.

**Comment by jccastillo0007** [comment]
Done

Nota.... Para que tome el campo de Planta Entrega... despues de ingresar el valor de la planta, se debe dar un click en algun otro lugar de la pantalla modal, antes de cerrarla, de este modo se graba el valor.... 

Si despues de ingresar el valor de la planta, cierran la ventana, no se graba dicho valor..

Ya se, ya se, ya se, hay un defecto abierto para agregar un boton de Aceptar en la pantalla modal... lo voy a trabajar durante la semana

**Comment by RigoFlores** [comment]
Al parecer 'ya casi' quedó listo, solo que generé una nota de crédito y le agregué la adenda, y lo sigue marcando como factura... chaaaaaaa
Al parecer está en jarcoud esa parte
Chaaaaaa*3
Y bueno agregar el botón de aceptar o cancelar. Neto está complicado eso???

**Comment by RigoFlores** [comment]
Otra cosa que acabo de encontrar, es que si la moneda es PESOS en el XML original, no la traslada a la adenda como MXN, que es el estándar: MXN, USD o YEN (son los valores válidos).
Cuando el tipo de cambio es 1.0, la moneda en la adenda debe ser MXN
Cuando el tipo de cambio no se incluya, asumiremos el tipo de moneda MXN en la adenda
Cuando el tipo de cambio sea distinto a 1.0, tomar los primeros 3 caracteres de la moneda en el XML e incluirlos en la adenda.
La otra mas simple, si gustas, es que capturen la moneda para evitar este issue.

**Comment by jccastillo0007** [comment]
Claro que esta hardcode, tu me dijiste que podia asumirlo

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
ESTO ES LO QUE SE COMENTÓ EN SU MOMENTO...(CORREO DEL 13 DE MAYO DEL 2013):
tipoDocumento="FACTURA" (*) en el XML únicamente se reporta ingreso, egreso y traslado. Supongo que lo más apropiado, sería capturaran cuál es el tipo de documento. La otra sería: Ingreso=FACTURA, egreso=NOTA DE CREDITO; dejaríamos fuera la opción de Nota de Cargo, que es ingreso también.

**Comment by RigoFlores** [comment]
donde cargo el XML de la adenda, que corresponda a nuestro cliente?

**Comment by jccastillo0007** [comment]
PENDIENTES.

MONEDA:

Con tipo de cambio 1.0, o cuando no se reporte en el xml origen,  el tipo de cambio: MXN

Cuanto tipo de cambio distinto de 1.0, entonces se toman los primeros 3 caracteres de la moneda reportada en el XML origen

 TIPO DE COMPROBANTE:

Cuando el XML origen, reporte Ingreso=FACTURA; cuando reporte Egreso=NOTA CREDITO; traslado, al parecer no está soportado (te lo confirmo).

 NOTA: EN LOS 2 ISSUES ANTERIORES, SE DEBERÁ

 VENTANA DE ADDENDA:

Agregar el botón de cerrar y cancelar

**Comment by jccastillo0007** [comment]
Done... excepto el tema del ok en la pantalla de addenda.

**Comment by RigoFlores** [comment]
Ya que casi la tengo, identifiqué oootros issues.
Particularmente que todos los campos (a excepción de referencia 2), son obligatorios en la adenda mabe, pero 'el addendador' no los valida. En ese caso, lo mas probable es que al someterlo al validador mabe, marque error por no llevar los campos obligatorios...

**Comment by RigoFlores** [comment]
RESUMIENDO:
A) FALTA EL OK EN LA VENTANA DE ADDENDA
B) FALTA VALIDAR LOS DATOS OBLIGATORIOS DE LA ADDENDA.

**Comment by jccastillo0007** [comment]
Solo falta el boton de OK en la ventana de addenda.... pero ese issue ya esta levantado.

**Comment by RigoFlores** [comment]
SI, REALMENTE EL ÚNICO PENDIENTE EN ESTE CASO ES EL TEMA DE VALIDAR LOS DATOS OBLIGATORIOS, COMO SON: ORDEN DE COMPRA, REFERENCIA1, NUMERO DE PROVEEDOR E ID PLANTA

**Comment by jccastillo0007** [comment]
Done.

Ya se validan los datos, y ya tiene el boton de OK.

**Comment by RigoFlores** [comment]
Noup, nada de eso tengo en ambiente de pru, usuario demo/demo.

**Comment by RigoFlores** [comment]
CORREGIR EL ERROR EN EL ENCABEZADO PARA EL ADDENDADOR

**Comment by RigoFlores** [comment]
LE SIGUE FALTANDO EL BOTÓN DE OK, PARA CERRAR LA VENTANA DE LA ADDENDA
