### ISSUE TITLE
Web CFDI 3.3 - CxC en ingresar cobros muestra recibos de nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1100]
El tiempo me da la razón una vez mas... 
En CxC no se deben mostrar los recibos de nómina.
En optibelt no se había detectado, ya que ellos no emiten nómina con nosotros, pero tenemos otros clientes que si emiten ambas.
Entonces un filtro para que no se muestren, NI SE CONSIDEREN en los cálculos, es filtrar toda serie NOM de CxC.

**Comment by jccastillo0007** [comment]
Done... solo para web 3.3

**Comment by RigoFlores** [comment]
Está bien para 3.3
