### ISSUE TITLE
Web CDFI v3.3 - No soporta la base a nivel de cada impuesto en productos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1101]
El dato base aplica a nivel de cada impuesto.
El dato base se sugiere igual al importe, y si el importe cambia (por cantidad y/o precio unitario), cambia el valor sugerido de la base
Cuando el dato base, se modifica manualmente, entonces ese dato SE DEBE TOMAR EN CUENTA, para el cálculo del impuesto en cuestión.

De hecho ahora mismo aparece un dato base a nivel producto (no a nivel impuesto), que en absoluto se ocupa para algo, es decir se lo pasa por los tompiates.

**Comment by jccastillo0007** [comment]
Defecto duplicado con el 1023.

**Comment by RigoFlores** [comment]
eso es para darle mayor realce e importancia a este issue... y bueno, a todos los que faltan
