### ISSUE TITLE
Web CFDI - Pasar a mayúsculas los catálogos de domicilio fiscal

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1102]
Aplica en el catálogo de clientes, para estado.
En el keygenerator, también.

**Comment by jccastillo0007** [comment]
no maaaa son casi 100 registros y eso es a manita...

**Comment by jccastillo0007** [comment]
benditos queries ... UPDATE StateCatalog SET name = UPPER(name);

Listo para Estado, algún otro?

**Comment by RigoFlores** [comment]
no lo veo, esto es para producción...

**Comment by RigoFlores** [comment]
Solo 3 países tienen estados asociados: mexico, usa y canadá.
Si eliges canadá, los estados los muestra con caracteres raros...
Esto me dí cuenta con un emisor que facturó a un cliente suyo, de canadá.

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
no puedo acceder al catálogo de clientes... marca error

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Como te pedí por correo... en el catálogo de clientes, los combos referentes al domicilio: pais, estado, municipio, localidad y colonia que son los catálogos del SAT, solo se ocupan para el CCE, y solo tenemos un cliente de esos. Entonces como manejamos esa captura para ese cliente????

Para el resto de clientes, hay que poner en los datos del cliente de libre captura, así como estaban antes. Finalmente los datos de domicilio, ya no serán obligados, ni para emisor, ni para receptor, solo se mostrarán en el PDF cuando el cliente así lo decida.

**Comment by jccastillo0007** [comment]
naaaa, dejalo asi, los clientes actuales ya lo tienen, y los clientes nuevos se deben acoplar a la solución, como quiera no estamos inventando nada, estamos pidiendo lo que pide el SAT... incluso si no quieren que no lo capture y listo.

**Comment by RigoFlores** [comment]
Es un desmadre, ahorita tenemos distinto producción de pruebas en el catálogo de clientes.

La solución para que los clientes no digan que no hubo cambios, es agregar el campo domicilio con las características antes acordadas.
