### ISSUE TITLE
Web CFDI v3.3 - Agregar como dato del cliente, el uso del CFDI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1103]
Según yo ya existía un issue, pero no lo veo.
Cuando elijan algún cliente, le mostrará el uso del CFDI para dicho cliente, pero con la posibilidad de cambiarlo.
Idéntico, como se hace con la unidad, en la ventana de agregar producto.

Porqué aquí?... sería muy común que el mismo cliente, cuando te compra... ocupe la factura para el mismo fin, y por ello se agrega al catálogo de clientes...

**Comment by jccastillo0007** [comment]
Entonces en la pantalla de facturación, ya no sería un combo ?

Y en el catálogo de clientes, se motrará el combo solo cuando no tengan nada, ya que seleccionen uno, ya solo se motrará como texto... pero ellos tendrán que escribir lo que quieran cambiar... seguro ?

**Comment by RigoFlores** [comment]
chiaaaaa.... comenté igual que las unidades..... esto es:

En el catálogo de clientes, para el cliente PATO SA se elige un uso del combo (el que no existe ahora). Digamos que sería el mas común para ese cliente.
En la pantalla de facturación, al elegir el cliente PATO SA, le pone el uso que se definió en el catálogo de cliente, pero con la opción de cambiarlo ahí mismo para esa factura, eligiendo dle combo.
Checa como está la unidad que se captura en el catálogo de producto, pero en la ventana de agregar producto, se puede cambiar para esa factura en particular.

**Comment by RigoFlores** [comment]
En el catálogo de clientes, se elige de un combo el Uso del CFDI (así como las unidades en el catálogo de productos. Ese dato, lo pueden cambiar como cualquier otro dato del catálogo de cliente, cuando se edita.

En la pantalla de facturación aparecerá por default el dato de Uso de CFDI que se definió para cada cliente en particular, pero lo podrían cambiar para esa factura en particular... (idéntico que en la ventana de agregar producto, puedes cambiar la unidad únicamente para esa factura).

**Comment by jccastillo0007** [comment]
ya esta en el catálogo de cliente.

Ojo... cuando dices se podrá editar... realmente es darles la opción de elegir otro, pero no de teclear uno diferente.

**Comment by RigoFlores** [comment]
Editar Uso de CFDI = elegir otro de la lista (catálogo)... sip en catálogo de clientes

En la pantalla de facturación, aparecerá el uso de cfdi elegido, pero se podrá cambiar solo para esa factura.

Marca error al acceder al catálogo de clientes.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
En el catálogo de clientes, ya almacena el uso del cfdi.
Pero cuando eliges el cliente para facturas, no muestra el uso que se tiene almacenado en el catálogo.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Hice una prueba con mi rfc. Como cliente tengo asignado el uso D01.
Al elegirlo en la pantalla de facturación, lo muestra correcto D01.
Al hacer una factura, al XML envía el D01 y al PDF envia el G01 (puedes checar con la factura 180).

**Comment by RigoFlores** [comment]
Enseguida elegí el método de pago P01 para mi mismo RFC, y al PDF le envió nuevamente G01 y al XML le envió el P01.
Aparentemente tiene fijo enviar al PDF un mismo uso.

**Comment by jccastillo0007** [comment]
fixed
