### ISSUE TITLE
Web CFDI v3.3 - no jala la conversión de monedas al momento de facturar.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1104]
Ejemplo, en el catálogo de productos, la moneda asociada es MXN para el producto X.
Si para ese producto X, en la pantalla de facturación elijo una moneda distinta a MXN, se genera el siguiente error:

El TipoDeComprobante es I,E o N, el importe registrado en el campo no es igual a la suma de los importes de los conceptos registrados. (3)

Esto es no jala la conversión de monedas.

**Comment by jccastillo0007** [comment]
este problema es por el decimal que nos sobra, por cuestiones de redondeo... aún no veo como corregirlo
