### ISSUE TITLE
Conector v3.3- dejó de trabajar descuentos...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1106]
Antes ya jalaba, ahora ya no soporta... marca:

2017-09-04 12:55:39,705 DEBUG [pool-2-thread-1] (CFDiWSClient.java:74) - 3556
2017-09-04 12:55:40,896  INFO [pool-2-thread-1] (CFDiWSClient.java:77) - Factura
Ti ack : com.facturati.ws.binding.jaxb.Ack@143fd2a[code=003,description=El TipoD
eComprobante es I,E o N, el importe registrado en el campo no es igual a la suma
 de los importes de los conceptos registrados.]
2017-09-04 12:55:40,897 DEBUG [pool-2-thread-1] (CFDiWSClient.java:79) - Propert
ies received : CFDi_FOLIO value : 1046
2017-09-04 12:55:58,145 ERROR [pool-2-thread-1] (ConnectorReader.java:265) - inv
alid file : C:\CONECTOR3.3\CONECTOR\Descuento.txt

**Comment by jccastillo0007** [comment]
ya subí otro release, cambiandole el nombre al zip, por si dropbox nos esta metiendo el pie

**Comment by RigoFlores** [comment]
Jjeje... si no es magia... el error sigue, pero se corrigió lo de pagos... no esperemos milagros, mejor hay que corregir..

2017-09-06 19:36:16,588  INFO [pool-2-thread-1] (CFDiWSClient.java:77) - Factura
Ti ack : com.facturati.ws.binding.jaxb.Ack@1e1329e[code=003,description=El TipoD
eComprobante es I,E o N, el importe registrado en el campo no es igual a la suma
 de los importes de los conceptos registrados.]
2017-09-06 19:36:16,590 DEBUG [pool-2-thread-1] (CFDiWSClient.java:79) - Propert
ies received : CFDi_FOLIO value : 1148
2017-09-06 19:36:38,581 ERROR [pool-2-thread-1] (ConnectorReader.java:265) - inv
alid file : C:\CONECTOR3.3\CONECTOR\Descuento.txt

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ya se puede timbrar, pero el dato de base (del IVA) a nivel producto, se envía incorrectamente al PDF.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
está pior, ahora no timbra en pru... desde el conector

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
sigue igual, no está enviando correctamente el dato de base de impuesto a nivel producto.
El precio unitario es 3,500.00
El descuento es $500.00
Importe: $3,500.00
Base: $3,000
IVA: $480


![baseincorrecta](https://user-images.githubusercontent.com/2912775/30437210-ab56ee72-9933-11e7-91db-fa1c74478101.PNG)

**Comment by jccastillo0007** [comment]
Yo verifiqué el log.... hoy voy a correr la prueba y te mando lo que se envía a jasper.

**Comment by RigoFlores** [comment]
no es necesario, estaba mostrando importe en esa plantilla... chiaaaa

**Comment by RigoFlores** [comment]
regresó el bug a nivel XML... habría que verificarlo en el PDF también, una vez que se corrija.
Cuando se incluye descuento, en el subtotal está enviando importe + descuento.
Recordar que subtotal = suma de importes
El impuesto se resta al subtotal, y se calculan los impuestos

**Comment by jccastillo0007** [comment]
fixed.

Es que cuando agregas todos los flavors con los que podemos generar cfdi, a veces se meten el pie unos con otros... 

en el caso de moneda extranjera, recuerda que tuve que hacer ajustes por unas decimales...

JC.
