### ISSUE TITLE
Web CFDi 3.3- No jaló la addenda mabe

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1107]
De hecho, subí el XML de configuración, tomado de un cliente en producción, y con datos predefinidos para no adivinarle. Hay dos problemas:
a) Al capturar la addenda, mezcló datos de ooootro archivo XML de configuración del CCE, con el archivo de configuración XML de mabe.
b) Marcó error al generar la factura.

**Comment by jccastillo0007** [comment]
al momento de abrir los datos de addenda en la pantalla de facturación... primero busca  un archivo con este formato Addenda_RFCReceptor.xml  si lo encuentra entonces lo muestra... asegúrate que con el usuario que estas probando, no tenga ese archivo con los datos de CCE.

Si lo pruebas y vuelve a fallar, dime como lo puedo reproducir para poder ver el log... no recuerdo que capturar en los datos extras.

**Comment by RigoFlores** [comment]
Hagamos lo siguiente... envíame todos los XML que tenga esa cuenta de ACO en web...
(sigo sin acceder a pruebas, me quedé en que me pedía algo... lo busqué en digital ocean, no lo hallé, te pregunté y la historia hasta ahí se quedó)...
Una vez que me los envíes, los borras del fail sistem, y empiezo desde cero otra vez.
Según yo, no se da el escenario que planteas, pero necesito asegurarlo.

**Comment by RigoFlores** [comment]
Subi solo el xml de addenda mabe.
El cliente es mabe sa de cv.
Cuando abro la pantalla de la addenda, le está agregando dos datos. 
Entiendo que lo está considerando como si este emisor ACO, tiene el plugin de CCE.
Cuando le doy timbrar, sigue marcando el error.

![image](https://user-images.githubusercontent.com/2912775/30444934-2b98d4e0-994a-11e7-90b4-96a3f042ab37.png)

**Comment by RigoFlores** [comment]
Si le agrego dos productos, duplica los campos fraccionarancelaria y unidadaduana.
Lo cual confirma que está considerando que este rfc emisor cuenta con el plugin de CCE.
No encuentro otra explicación.

**Comment by jccastillo0007** [comment]
Bueno pues como el RFC ACO es el RFC multi used para cualquier cosa, efectivamente tenía configurada el complemento de CCE.

Ya se lo quite.

JC.

**Comment by RigoFlores** [comment]
sigue con el mismo comportamiento...
esto es le agrega 2 datos que corresponden al CCE... quizás lo quitaste en PRU 3.2... o  no se...

**Comment by jccastillo0007** [comment]
ya esta jalando finkok, y ya esta jalando la addenda mabe... checala en chinga antes de que deje de funcionar.

**Comment by RigoFlores** [comment]
no, no jaló... no hace nada... es mas ya ni se puede acceder...

**Comment by RigoFlores** [comment]
La parte de impuestos de la addenda está chueca, tanto en el impuesto como en la tasa.
Así debe ser:

            <mabe:Traslados>
                <mabe:Traslado importe="1969.6" tasa="16.0" tipo="IVA"/>
            </mabe:Traslados>

y así la está mostrando:

            <mabe:Traslados>
                <mabe:Traslado importe="100.80" tasa="0.16" tipo="002"/>
            </mabe:Traslados>

**Comment by jccastillo0007** [comment]
De donde saco el 100.80 ? puedes enviarme todo el xml por email...

Esto es debido a los cambios hecho por el cfdi 3.3...

**Comment by RigoFlores** [comment]
Negativo, creo que no me expresé bien (ni tu hallaste la diferencia.... chiaaaaaa).
Comenté, lo que está mal es tanto el impuesto (002 en lugar de IVA) y la tasa (0.16 en lugar de 16.0). Eso es lo que está incorrecto. El monto del IVA es diferente, porque son distintas facturas.... chiaaaaa

Aún mas, emití una factura con retenciones, y es lo mismo... coloca la clave del sat, en lugar de IVA o ISR

    <cfdi:Impuestos TotalImpuestosRetenidos="88.20" TotalImpuestosTrasladados="100.80">
        <cfdi:Retenciones>
            <cfdi:Retencion Importe="63.00" Impuesto="001"/>
            <cfdi:Retencion Importe="25.20" Impuesto="002"/>
        </cfdi:Retenciones>
        <cfdi:Traslados>
            <cfdi:Traslado Importe="100.80" Impuesto="002" TasaOCuota="0.160000" TipoFactor="Tasa"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
Si vi la diferencia, y de hecho coincide con lo que se manda al CFDi normal... solo que asumí que era el mismo XML y que el monto también estaba mal... tons de hecho esta mas fácil.

**Comment by jccastillo0007** [comment]
Oye, si subes otro archivo con el mismo nombre, toma ese para la addenda... es decir, puedes hacer pruebas de todas las addendas, subiendo cada vez el archivo necesario, solo ponle el mismo nombre.

**Comment by RigoFlores** [comment]
No entendí... El archivo de addenda mabe lo eliminaste o eliminaste todos o no eliminaste nada?
Ya llevo 4 addendas probadas... y sigo
