### ISSUE TITLE
Conector CFDI v3.3 - no envia los datos extra a nivel producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1108]
Así de simple, no pasa los datos extra a nivel productos hacia el Jasper.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Ahora trata todo como si fueran datos extra...

En la versión 3.2 el layout era:
extradata[etiqueta|valor|etiqueta|valor| etiqueta|valor|etiqueta|valor|etiqueta|valor]


Es decir, no todos son datos extra, sino pares de 'etiqueta-datoextra' (algo que nunca estuve de acuerdo desde que se implementó, pero ni hablar, así funciona).
Seguramente varios clientes ocupan este layout de extra data, entonces ahí lo que pasará es que se correrán los datos. ¿Que hacemos?

**Comment by jccastillo0007** [comment]
fixed... ya lo ajuste al approach que ya esta implementado.. pa no cambiarle
