### ISSUE TITLE
Web CFDI3.3 - Agregar datos en la configuración del emisor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1109]
Estos datos se podrían ocupar en la recepción de pagos (documento de pagos). 
Pueden ser uno o mas bancos. Por ejemplo la tía tiene 2 cuentas bancarias.

- RFC banco
- Número de Cuenta

Veo 2 opciones:

a) En la pantalla de configuración del emisor, opción de agregar uno o varios pares de datos (rfc y cuenta). Tal como se hace para datos extra.
b) Un catálogo nuevo, el de Cuentas Bancarias Emisor, que solo tendría 2 campos mas el ID, pero que se pudieran agregar uno o varios registros.

Al momento de capturar la recepción de un pago, este dato lo elegirán de un combo.

**Comment by jccastillo0007** [comment]
ya esta en la pantalla de configuración... ojo, el combo en la captura del pago, despliega banco + cuenta, ya que un emisor puede tener varias cuentas en el mismo banco

**Comment by RigoFlores** [comment]
En la pantalla de cuentas por cobrar, esa información de bancos que se captura en la pantalla de configuración, pertenece al emisor... esto es, la cuenta destino... es decir, a donde llegará el pag.
En la pantalla de cxc, lo está desplegando en la cuenta origen, es decir, está chueco...

**Comment by jccastillo0007** [comment]
fixed
