### ISSUE TITLE
Corregir la seccion de totales de la factura

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#111]
Formatear la vista para que aparezcan los totales en este orden:

Subtotal
Descuentos
Subtotal - descuentos
Impuestos trasladados
Impuestos retenidos
Total

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
No sé si sea necesario eliminar las secciones que aparecen arriba, indicando traslados y retenciones.
Ya se muestran en la sección de totales; lo único que no se muestra son las tasas en caso que hubiera varias.
como vex?

**Comment by jccastillo0007** [comment]
Pues si lo pense, pero como hicimos un desmadre para soportar productos con impuestos de diferente tasa, no me digas que tenemos  un elefante blanco?

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
No para nada, en carta porte (retención 4%) esa sección está mas que justificada, al igual que en honorarios (iva 16%, ret iva 10.667%, ret isr 10%).
Pues dejémosla entonces, a menos que pusiéramos un controlito que la oculte o muestre a petición del usuario. Por omisión oculta.
