### ISSUE TITLE
Web CFDI 3.3 - ajustar pantalla del catálogo de clientes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1110]
Para dar mayor simplicidad, considerando que el domicilio del receptor (ni del emisor) ya no será obligatorio en el XML, pero algunos clientes lo pedirán en el PDF, se propone lo siguiente:

Para los clientes actuales: Domicilio será la concatenación del contenido de los campos separados por espacios de: calle, numero exterior, numero interior, colonia y referencia. 

Para los clientes ahí capturarán lo que requieran, pero evidentemente domicilio solo se almacenará en un campo, y sugiero que sea calle. Esto será igual para los clientes actuales que editen y salven.

Los campos de pais, estado y CP serán de libre captura.

El conjunto de datos _**banco, rfc banco y número de cuenta**_, pueden ser uno o varios, ya que un mismo receptor puede tener asociados varios bancos.
Estos datos de banco se ocuparán al momento de registrar un documento de pago.

Como la bestia?

![cat clientes](https://user-images.githubusercontent.com/2912775/30407701-6ae9f61e-98bf-11e7-8de1-1c1c86247401.PNG)

**Comment by jccastillo0007** [comment]
Tranquilo ...si no esta roto no le muevas.... asi como esta ahorita esta bien... la app agregará los domicilios cuando se trate de CCE...
Incluso si no se usa en el XML, pero los clientes lo quieren tener en el PDF, también se puede.

Esta muy fumado eso que dices, y tarde o temprano nos vamos a enfrentar con un problema al juntar el domicilio, además que estas sugiriendo un tratamiento diferente para clientes existentes y clientes nuevos... ahora si te la jalaste, se me hace que es la emoción de la laptop

**Comment by jccastillo0007** [comment]
No ma... y con la pantalla que enviaste, ni siquiera se optimiza, es lo mismo... si acaso debo ver como capturar varios bancos.
