### ISSUE TITLE
CCE + CFDI 3.3 - permitir capturar domicilio de emisor y receptor de acuerdo a catálogos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1111]
Lo que hoy en día se tiene para catálogos de clientes, se ocupará ÚNICAMENTE EN EL CASO DEL CCE (complemento de comercio exterior).
La pregunta es donde será la mejor opción para ubicarlo??
Podríamos abrir un menú para CCE, donde se capturen esos datos para el emisor y los distintos receptores.

Donde crees que deban ir???

**Comment by jccastillo0007** [comment]
si no esta roto no le muevas.... asi como esta ahorita esta bien... la app agregará los domicilios cuando se trate de CCE...
Incluso si no se usa en el XML, pero los clientes lo quieren tener en el PDF, también se puede.

**Comment by RigoFlores** [comment]
Ahora mismo, no hay forma de capturar el domicilio fiscal del emisor bajo el tema de las claves.. eso como se va a implementar???
Si bien en el CFDI 3.3 ya no se incluyen los domicilios en el XML estándar, para el complemento CCE si se incluyen... y adivina que???

> Calle es obligatorio.
> No ext, no int, colonia, localidad, referencia, municipio...son opcionales
> Estado, pais y CP son obligados.
> 

**_COINCIDE FULL CON MI APRROACH DEL MANEJO DE DOMICILIO... SERÁ UNA EXTRAÑA COINCIDENCIA???_**

**Comment by RigoFlores** [comment]
O ES UNA SEÑAL DEFINITVA DE COMO MANEJAR LOS DOMICILIOS???

**Comment by RigoFlores** [comment]
Uno de los cambios del CEE en 3.3 es que ahora se deben incluir los domicilios del emisor y receptor DENTRO DEL COMPLEMENTO, y con las claves que corresponda en los catálogos.

**Comment by RigoFlores** [comment]
pues ya lo pidieron... como lo previí hace 4 meses

**Comment by RigoFlores** [comment]
ya empezaron a presionar con este asunto...
a) en el XML estandar se debe incluir el dato de NumRegIdTrib cuando el receptor sea extranjero. Ese dato lo puedes tomar de los datos de addenda que se capturan.
b) Uso de CFDI: P01
c) en el complemento se requiere incluir los nodos de EMISOR Y RECEPTOR, donde se incluyen los domicilios basados en los catalogos del SAT para este complemento. Lo que hay que resolver aqui, es como incluir los datos del emisor, ya que ahora mismo el keygenerator no ocupa las claves.
d) ahora mismo, los datos de domicilio del receptor se envian al pdf como claves, lo cual es totalmente incorrecto. esas claves SOLO SE OCUPAN EN CASO DE ESTE COMPLEMENTO, Y AUN CON ELLO, AL PDF NO DE DEBEN ENVIAR CLAVES, SINO DESCRIPCIONES. O QUIZAS EL CLASICO CLAVE.DESCRIPCION.

Yo creo que cambiaron varias cosas, pero hay que ver si con estos cambios ya podemos timbrar el complemento en 3.3

**Comment by jccastillo0007** [comment]
ok, si tienes clientes que esperan este tema, pasame sus datos fiscales para yo ponerles la dirección correcta.

**Comment by RigoFlores** [comment]
Son la dirección que tienen definidos de estos RFC's en el keygenerator:

IME120610FQA
OTC131125BL4

**Comment by RigoFlores** [comment]
??

**Comment by RigoFlores** [comment]
Siguen a la espera...

**Comment by RigoFlores** [comment]
Otra crisis, ya el cliente la pidió hoy, y pues obviamente no había nada.
Aquí no olvidar que en el nodo receptor del XML estándar, se debe incluir el país de residencia, cuando el receptor sea extranjero.

**Comment by RigoFlores** [comment]
Yo creo que los domicilios del emisor y receptor, deben capturarse en la pantalla de la addenda, es decir al capturar el complemento. O si se complica mucho, solo el del emisor ya que el receptor de alguna manera ya se tiene. Por otro lado, podrían ocuparse otros 2 domicilios, el del propietario y el del destinatario. Así que posiblemente una tablita para llenar los domicilios, quedaría bien.
Así nos evitamos  pensar en como solucionar este asunto.
Como la beisbol???
Este es un complemento complicadísimo, pero si lo hacemos bien, puede generar.
Cuando se factura en cualquier moneda distinta de USD, aguas, se tienen que hacer cálculos y que cuadre... no ma.... primero convertir de moneda de facturación a MXN y de MXN a USD

**Comment by RigoFlores** [comment]
Oye ya están esperando este complemento... los traigo a vuelta y vuelta..
Lo que falta es hacer los mismos ajustes que hiciste para conector.
Y el tema mas complicado, son los domicilios que van en el complemento, para el emisor, receptor y opcionalmente, propietario y destinatario.
El del receptor ahora mismo se podría enviar al complemento.
El del emisor puede ser un archivo XML de configuración para este CCE (tipo properties), donde se capture el domicilio del emisor con las claves, para que simplemente se lea.

**Comment by jccastillo0007** [comment]
por ahora el domicilio del emisor, lo arreglamos directo en la base de datos...

**Comment by RigoFlores** [comment]
YA VALIDÉ Y LO HIZO BIEN EN PRU.
PUEDES SUBIRLO A PRO Y CONFIGURARLO PARA LOS RFCS MENCIONADOS ARRIBA?
