### ISSUE TITLE
Eliminar el Rango final del catalogo de folios.

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#112]
Eliminar el Rango final del catalogo de folios.

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
Ahora ya no debe permitir agregar una serie ya existente, debido a que ya no existirá el rango final.
Es decir, si dan de alta la serie A.... no debe permitir que se agregue otra serie A...no tiene sentido, ya que el sistema llevará el control de consecutivos por serie.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Que pasa con las cuentas en pru, donde existían ya varios rangos de folios con la misma serie?
Para finalmente poder validar el correcto comportamiento, deberíamos eliminar todas las series repetidas, dejando solamente la última.
Por ejemplo la cuenta rijo tiene 3 rangos SIN SERIE, y 2 rangos con serie A?
No es el caso de ningún cliente, afortunadamente, pero como arreglamos este tema para poder probar?

**Comment by jccastillo0007** [comment]
Borra todas lad series, o podemos limpiar toda la base de datos

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
No puedo borrar las series ya que se han utilizado. De hecho acordamos que vaciarías toda la BD, para poder validar el comportamiento. Las borras pls? Par rijo, demo, guest.
