### ISSUE TITLE
Web CFDI 3.3 - Solo quedará carta de porte traslado, se elimina ingreso y traslado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1122]
La funcionalidad de traslado se añadirá a Carta de Porte - Traslado

Desaparecer carta de porte ingreso, así como traslado...

**Comment by jccastillo0007** [comment]
chiaaaa
done.

**Comment by RigoFlores** [comment]
Es delicado este asunto... ya que debe darse un merge de lo que era carta de porte traslado + lo nuevo del CFDI tipo traslado... así lo consideraste??
Es decir, para propósitos del PDF se enviará una serie de datos extra, donde los 2 primeros que son remitente y destinatario (que se toman del catálogo de clientes), entre muchos otros datos extra.

**Comment by jccastillo0007** [comment]
esto se supone que ya esta no ?

**Comment by RigoFlores** [comment]
no estoy seguro... ya que no se hizo el merge carta porte de antes, con traslado en 3.3.
Digamos que quedó solo como traslado.
Voy a cerrarlo, pero revisaré el comportamiento de carta porte, sin el plugin correspondiente, que sería lo mas conveniente.
