### ISSUE TITLE
Web CFDI v3.3 - sin partirle su mauser, migrar PESOS a MXN

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1123]
Para todos nuestros clientes en producción, que tengan moneda like %PESO%, cambiarlas a MXN, pero muy importante... SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...SIN ROMPER LA RELACIÓN CON LOS PRODUCTOS...

los últimos clientes ya tienen MXN, pero los primeros le ponían PESOS o lo que quisieran, asegurar que el tipo de cambio, sea 1.0

**Comment by jccastillo0007** [comment]
pssss hay que actualizar los productos también, si no, si le rompemos la mad...

**Comment by RigoFlores** [comment]
hagámoslo en producción... eso nos ahorrará mucho tiempo y esfuerzo ... puedes hacer un cáliza, con la TIA... actualmente tenemos PESOS, y todos los productos evidentemente tienen PESOS, excepto el que generé para pruebas de 3.3

**Comment by jccastillo0007** [comment]
En PRO la TIA, ya tenía PESOS y MXN, tons, borré PESOS y actualicé los productos.

**Comment by RigoFlores** [comment]
Si, tenía MXN por la prueba que hice desde la URL de 3.3
Ya revisé unos cuantos productos y quedó bien. Mañana que haga una factura, confirmaré que todo está bien.

Pero, el issue es para hacer lo mismo para todos los clientes que tengan la moneda like %PESO%  (case valemadretive)

**Comment by RigoFlores** [comment]
Revisé desde PRO 3.3, algunos clientes al azar. Por ejemplo este: SORS921122AVA

Sigue teniendo PESOS tanto en catálogo de monedas, como en todos sus productos.

**Comment by jccastillo0007** [comment]
es que solo lo habia hecho para la TIA... ya esta par a tooooodos los clientes.
