### ISSUE TITLE
En producción - a todos los IVA trasladados y retenidos, así como al ISR asignarles Tasa en el parámetro Tasa o Cuota

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1124]
Para IVA trasladado del 16%, asignarle Tasa
Para IVA e ISR retenido, asignarle Tasa.

El que lleva cuota, será el IEPS, pero ese que ellos lo cambien.
y el IVA Exento, ese no lleva tasa ni cuota, sino Exento.

**Comment by jccastillo0007** [comment]
listo...

**Comment by jccastillo0007** [comment]
cual es la pregunta ?

**Comment by jccastillo0007** [comment]
Soy bueno... pero aún no logro adivinar que me quieres preguntar, de por si, luego ni entiendo jajajaja

**Comment by RigoFlores** [comment]
seguramente me faltó darle commit...
la pregunta era que en ambiente de 3.2 y 3.3 producción, están compartiendo la BD y los archivos de configuración?, de tal manera que ven lo mismo en consultas, y consecutivos de facturación... según yo, y así lo comentaste, lo único que no cuadra, es la plantilla del PDF.... como podemos hacerle, para que incluso eso no sea problema???

**Comment by jccastillo0007** [comment]
mmmm solo que para 3.3 la plantilla genérica sea cfdi_base3.3.jrxml y asi ya sería específica para 3.3

En 3.2 se llama cfdi_base

**Comment by RigoFlores** [comment]
podemos simplemente agregarle el 3 al final.
cfdi_base3.jrxml

La otra opción, es mantener el nombre, pero cambiando la carpeta común. Es importante este asunto para no tener que configurar una plantilla para cada cliente migrado.
Me comentas como quedaría pls?

**Comment by jccastillo0007** [comment]
yo creo que cfdi_base3.3.jrxml, es mejor porque asi se auto explica para que versión es.... de hecho no hay nada que configurar por cliente, todos los que usen la versión 3.3 usaran ese template.. en el mismo folder..

es bastante transparente y fácil de hacer.

**Comment by RigoFlores** [comment]
ok entonces a todas la plantillas estándares, se les aplicará la misma filosofía... se le agrega el 3.3 al final del nombre.
Yo decia solo 3, ya que el punto puede meter ruido en el failsistem
Pudiera ser también cfdi_base33.jrxml, para evitar ese posible conflicto.
