### ISSUE TITLE
Navision v3.3 - Generar versión de pruebas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1125]
Entiendo, que ahora mismo por el RFC del emisor tiene un comportamiento específico. Hay que ajustar lo requerido para que ahora trabaje con el RFC ACO.... como emisor.

Asimismo, apuntar a la BD de pruebas para 3.3, que ahora se llama:

PRUEBAS_SAT.

Ejemplo de cueri:

select*
from [PRUEBAS_SAT].[dbo].[MEXICO - IP - PEDIMENTO$Factura-T] 
where [Nº factura] 
in ( '17FVMX147' );

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
pero aún sigo haciendo pruebas

**Comment by RigoFlores** [comment]
hay que cambiar la llave también.... y el sello de ACO...
