### ISSUE TITLE
Navision 3.3 - agregar datos a tabla Factura-T después del timbrado exitoso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1126]
Ahora tenemos que llenar datos adicionales al momento del timbrado. Son los siguientes, y se ocuparán al momento de generar un pago:

![navision1](https://user-images.githubusercontent.com/2912775/30863006-7750ec48-a295-11e7-960b-8489d4d24062.PNG)

**Comment by jccastillo0007** [comment]
La mayoria de los datos ya se tienen en la tabla que definieron para pagos... y el que me faltaba que era el rfc receptor, lo estoy tomando de la vista NavisionCFDi... como que dato falta ?

**Comment by RigoFlores** [comment]
Negativo, los datos en la tabla de pagos son el CFDI de pagos propiamente.
Ahí existe uno que indica el folio de la factura... este folio no es el folio del DRP, es el folio de la factura que están pagando, para que de ahí se vaya a la tabla factura-t para traer los datos de esa factura, que corresponderá precisamente al nodo doctoRelacionado  del DRP

Estos son los datos que estarían faltando para el nodo doctoRelacionado del DRP:

IdDocumento  (UUID)
Serie  (es la que SI aparece en la tabla de pagos, para buscar en la tabla facturat)
Folio (es la que SI aparece en la tabla de pagos, para buscar en la tabla facturat)
MonedaDR
TipoCambioDR
MetodoDePagoDR

**Comment by jccastillo0007** [comment]
Con el folio de la factura de la tabla de pagos, es el folio de la factura original que estan pagando, tal como tu lo dices, entonces, con ese folio estoy leyendo la factura original de la tabla o mas bien vista NavisionCFDi, y de ahi estoy leyendo los datos del receptor y los datos para el docto relacionado, en la tabla facturat esos datos están de mas, ahi supongo hay que guardar el uuid y tal vez el sello del timbre, pero no datos del cfdi que están pagando, pues esos estan en la tabla original..

**Comment by RigoFlores** [comment]
ok, eso yo no lo sabía, que ya existía esa info. Al final ya que jale todo, les pediré que la eliminen si a nadie le sirve.
Entonces lo que se necesita es enviar esa info de la vista al documento de pago (nodo docto relacionado), ya que hasta mis últimas pruebas no se estaba incluyendo en el cfdi de pagos

**Comment by RigoFlores** [comment]
jeje, ya me votó el escritorio remoto porque estás tu conectado.
OK, prefiero que tu arregles lo que corresponda y yo mañana temprano valido

**Comment by jccastillo0007** [comment]
listo.

**Comment by jccastillo0007** [comment]
ya lo hace tanto para facturas como nota de credito... estoy checando que pedo con pagos.
