### ISSUE TITLE
Navision 3.3 - Tomar la información de unidad SAT y clave producto SAT de nuevos campos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1127]
a la tabla [MEXICO - IP - PEDIMENTO$Sales Invoice Line] le agregaron los siguientes campos:
![navision2](https://user-images.githubusercontent.com/2912775/30863613-1abecd7c-a297-11e7-9a43-660c53a4e47e.PNG)

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
hasta que pueda hacer pruebas podré validar...
