### ISSUE TITLE
Navision 3.3 - tomar los campos generales adicionales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1128]
De la tabla [MEXICO - IP - PEDIMENTO$Sales Invoice Header] tomar los siguientes campos para uso, tipo de relación y documentos relacionados:

![navision3](https://user-images.githubusercontent.com/2912775/30863900-d31e9118-a297-11e7-9f47-cf80bd9ccf78.PNG)

**Comment by jccastillo0007** [comment]
Oye, ellos siguen enviando esto en el regimen

cfd.setRegimen("REGIMEN GENERAL DE LEY PERSONAS MORALES");

Que no eso ya cambió?

**Comment by jccastillo0007** [comment]
Que pinches fumados estan estos weyes...

**Comment by RigoFlores** [comment]
no les pedí que lo cambiaran, ya que ese régimen o lo tomamos de la configuración o lo interpretamos... vamos, no es un dato que cambiará factura a factura

**Comment by jccastillo0007** [comment]
pues de hecho eso lo poniamos nosotros directamente, tons ahora que le pongo.?

**Comment by RigoFlores** [comment]
como así, pues le toca el 601

**Comment by jccastillo0007** [comment]
Listo... aqui voy a ir agregando los comentarios de las pruebas

**Comment by jccastillo0007** [comment]
Estoy intentando timbrar, pero me marca que no tiene acceso a las páginas del SAT, donde se tienen publicados los schemas para la cadena original.

Como por ejemplo:
http://www.sat.gob.mx/sitio_internet/cfd/implocal/implocal.xslt

Ese es un ejemplo pero son muchas...  no recuerdo como resolvimos eso la vez pasada, o si habran bloqueado esa URL

**Comment by RigoFlores** [comment]
no sé, supongo que tenemos que paserles las ligas de las que necesitamos acceder... de entrada el ejemplo de arriba, según yo, no lo ocupamos en navision... igual y es genérico

**Comment by jccastillo0007** [comment]
ya vi, modifiqué el xslt para que tome todo de forma local... en la 3.2
haré lo mismo para 3.3

**Comment by jccastillo0007** [comment]
done.
