### ISSUE TITLE
Mostrar en pantalla los folios reutilizables

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#113]
Aplica para pantalla de facturas y de folios.

**Comment by jccastillo0007** [comment]
Solo se puede aplicar en pantalla de facturas

La de folios es un catalogo, son diferentes tablas

JC@iPhone.
 Saludos.

**Comment by jccastillo0007** [comment]
Done, para la pantalla de facturas.

La pantalla del catálogo de folios, es mucho mas complicado, ya que hablamos de mezclar la información de dos tablas.

**Comment by RigoFlores** [comment]
no se como validarlo...:(
