### ISSUE TITLE
DRP - no está incluyendo los documentos relacionados con el pago realizado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1130]
Al elegirlos desde la pantalla de CxC, ya se tiene toda la información para llenar lo que se pide a nivel de documento pagado: 

IdDocumento - UUID
Serie  
Folio
MonedaDR
TipoCambioDR
MetodoDePagoDR
ImpPagado - conocemos el importe pagado.

LOS SIGUIENTES CAMPOS APLICAN CUANDO EL MÉTODO DE PAGO DE ESTE DOCUMENTO SEA PPD:
(PAGO EN PARCIALIDADES O DIFERIDO)

NumParcialidad -  sabemos si existen pagos previos para este mismo CFDI 
ImpSaldoAnt - conocemos el saldo anterior
ImpSaldoInsoluto - conocemos el saldo que resta

**Comment by jccastillo0007** [comment]
done

bueno casi done... generé un pago con un cfdi relacionado pero sin parcialidades, tons no me metí en broncas del tema de saldos pendiente y todo eso.

**Comment by RigoFlores** [comment]
Si entiendo que por lo pronto eso ayuda, pero tenemos que completarlo.
En cuentas por cobrar, al momento de capturar un pago parcial, tienes todos los elementos para conocer:
saldo anterior, importe del pago, número de parcialidad, y saldo insoluto...

Cómo quedamos con este punto, ya que lo pusiste a resuelto, pero no está full?

**Comment by RigoFlores** [comment]
en el documento relacionado al pago, cuando la factura original no lleva serie, si le está incluyendo

Serie="SIN SERIE"

en este caso, esta condición es interna a factura-t, por lo que simplemente no debería incluirse ese parámetro cuando la serie sea "SIN SERIE".

**Comment by jccastillo0007** [comment]
okas...

lo puse en resolved, solo para que hagas pruebas con ese escenario, mientras termino lo de parcialidades.

**Comment by RigoFlores** [comment]
ok, a nivel de un solo pago... le coloca SIN SERIE... eso es un error.
A nivel de pagos parciales, espero confirmación

**Comment by jccastillo0007** [comment]
listo... lo de SIN SERIE.

Oye, aqui hay un desmadre que no entiendo muy bien...

Si el método de pago es PUE.... no lleva los datos de saldo insoluto y pago  y saldo anterior, y tampoco parcialidad...  peeeeero, yo creo que algo puede quedar incosistente, si hacen 1 pago y lo reparten a n facturas... no se como se debe comportar, que tal que las facturas tienen método de pago PUE.... y resulta que el pago que aplican no es para pagar todo el saldo de la factura... eso se supone que no se podría no ?

**Comment by RigoFlores** [comment]
Estrictamente hablando, si el método de pago es PUE, debería pagarse completo ... SI, así es.
Hoy Finkok, está permitiendo que el PUE, acepte pagos parciales (no completos). Bien o mal, no sé, pero lo acepta.

A como tenemos el sistema actualmente, no existe validación alguna al respecto, porque incluso quizás ni el mismo cliente sabía que no se iba a pagar en una sola exhibición.
Ponerle un candado, sería por otro lado riesgoso, que no permitiera pagar una factura, que si se emitió como PUE, y que al final se pagó en parcialidades.

Yo había considerado esta situación, sugiriendo los valores (como lo solicité hace tiempo), y que el usuario tome la decisión de cambiarlos o nó. 
Si eso es muy tardado ahora mismo (ya ni recuerdo cual fue la respuesta, que mucha información, que una vez que se eligió el CFDI ya no se consulta, y bla bla bla)... entonces salimos como estamos... es decir que se pase el método de pago por los tompiates, y que acepte pagos en parcialidades. En menos nocivo. Igual y Fhoy, si valida esa condición...

**Comment by jccastillo0007** [comment]
si, es que la tabla donde aparecen los CFDi, no se pueden volver a cargar con la info de las cfdi seleccionadas, tendría que mostrar toda la info desde el inicio, y eso haría la tabla demasiado grande.

**Comment by RigoFlores** [comment]
Hice un drp pero marcó error... es es por la plantilla o porque?
Error al generar CFD (115)

No pude validar lo de 'SIN SERIE?, y tu me avisas cuando pueda validar lo de pagos parciales.

**Comment by jccastillo0007** [comment]
ya esta generando el pdf de los pagos.. para que cheques lo de SIN SERIE... de parcialidades, tengo que probar yo  primero , a[un no lo veo

**Comment by RigoFlores** [comment]
Negativo, no está jalando. Marca error porque se incluye el nombre del banco ordenante (origen).
De los siguientes datos:
RFC banco ordenante  (banco origen)
Nombre Banco ordenante
Cuenta Ordenante
RFC banco beneficiario  (banco destino)
Cuenta beneficiaria
Número de Operación

El único obligatorio es el nombre del banco, cuando el RFC de la cuenta ordenante sea XEXX01010100. (lo cual está raro, ya que si el RFC ordenante es opcional, entonces como saber si es el del extranjero).

En conclusión, este error se genera porque está enviando el nombre del banco ordenante cuando el RFC NO ES EL EXTRANJERO (XEXX010101000).

**Comment by jccastillo0007** [comment]
De hecho , lo probé sin capturar bancos, ni del emisor ni del receptor... y asi si lo timbra

**Comment by RigoFlores** [comment]
anexo imagen con el error...
![drp](https://user-images.githubusercontent.com/2912775/31457864-c3e5c7d2-ae83-11e7-9ee9-95e202d39ffd.PNG)

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Existe otro issue con lo del banco origen, que aunque se mencionó aquí, no se ha atendido.
Cerraré este, y dejaré abierto el otro.
