### ISSUE TITLE
Web v3.3 - Eliminar campos no necesarios de catálogo de clientes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1132]
Ya ví que no agregaste el campo de domicilio.
Como quiera hay que ocultar: localidad, referencia, no cuenta.

El orden correcto, de acuerdo a la lógica de las ligas es: PAIS, ESTADO, CP
y debajo municipio y colonia, ya que ahora cuando se aplican los filtros una vez elegido el dato anterior, quedan chuecos los datos.

Cómo va a quedar lo de los bancos de los receptores y emisores?

**Comment by jccastillo0007** [comment]
Bancos de receptores, los voy a mover a esa pantalla de clientes y el de los emisores a la pantalla de configuración... na mas deja termino la funcionalidad que falta

**Comment by RigoFlores** [comment]
Como te comentaba, el orden es el siguiente:
Calle  (se eliminan el resto de campos)
Pais, Estado y CP

Ya de por sí, tomar la colonia de un catálogo que no está actualizado, es un problema.

**Comment by jccastillo0007** [comment]
regreso calle arriba de pais, y le quito número int y ext .

**Comment by RigoFlores** [comment]
y colonia... esa colonia la capturarán en la calle...

**Comment by RigoFlores** [comment]
cuál fue el cambio, no ví... solo íbamos a dejar la calle, quitando int, ext, colonia y municipio

**Comment by jccastillo0007** [comment]
se acomodaron a como fue solicitado, no puedo quitar mas datos porque eso provocaría tener la información inconsistente...

**Comment by RigoFlores** [comment]
Tons al menos subir calle, numero exterior, interior...  arriba de país...

**Comment by jccastillo0007** [comment]
o que la ...
