### ISSUE TITLE
Web v3.3 - Agregar liga de buscador de claves de producto en catálogo de productos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1133]
En la pantalla de producto, agregar liga para que se abra en una ventana modal, la aplicación del SAT para clasificación de claves de producto / servicio.

http://200.57.3.46:443/PyS/catPyS.aspx

La liga debe indicarse con un label grande y vistoso para que lo ubiquen rápidamente.
Esto es muy importante, ya que desde ahí podremos descargar mucho soporte técnico.
Colocar esta liga configurable a nivel de la plataforma, por si llega a cambiar.

**Comment by jccastillo0007** [comment]
done
