### ISSUE TITLE
Web v3.3 - plantillas de PDF genéricas en la misma carpeta que la versión 3.2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1134]
Como platicamos, se nombraran de distinta manera los formatos de plantilla estándares que aplicarán para v3.3. Ya solo me indicas si será 3.3 o 33 el sufijo, por aquello de que el punto pueda causar conflicto en el failsisten

CON CAMBIO:

**base_products3.3.jasper
base_products3.3.jrxml
cfdi_base3.3.jrxml
cartaporte3.3.jrxml
cporte_products3.3.jasper
cporte_products3.3.jrxml
retenciones3.3.jrxml
retencion_products3.3.jasper
cfdi_nomina3.3.jrxml**

PERMANECEN IGUAL:
CarteraCliente.jrxml
CarteraGeneral.jrxml
cfdi_AcuseCancelacion.jrxml
pedido.jrxml
pedido_products.jasper
pedido_products.jrxml
remision.jrxml
remision_products.jasper
remision_products.jrxml
detalleCarteraCliente.jasper
detalleCarteraCliente.jrxml
detalleCarteraGeneral.jasper
detalleCarteraGeneral.jrxml
cotizacion.jrxml
cotizacion_products.jasper
cotizacion_products.jrxml

**Comment by jccastillo0007** [comment]
ok, yo las renombro ? lo que tengo en PRU ?

o mejor pasamelas para no mezclar templates, yo la verdad no tengo control sobre los templates, esas las manejas tu.

**Comment by jccastillo0007** [comment]
que sea con 33.

**Comment by RigoFlores** [comment]
Si, claro... yo te voy pasando... necesitaba saber como quedaban para renombrarlas....

**Comment by jccastillo0007** [comment]
tome las de la TIA de pro con terminación 33 y las puse en el folder genérico... la aplicación va a usar esa plantilla para facturas... poco a poco vamos subiendo las plantillas que tengas listas

**Comment by RigoFlores** [comment]
ok, me faltan las de carta porte y retenciones... las trabajaré tan pronto pueda...
