### ISSUE TITLE
V3.3 CxC - regresar el nombre original del menú

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1135]
En versión 3.2 se llama "Ingresar Pago"
En versión 3.3 se llama "Pagos"

Para hacerlo menos cambiante, se debe mantener en Ingresar Pago

**Comment by jccastillo0007** [comment]
listo... pero confunde con la opción que esta dentro del menú CxP

**Comment by RigoFlores** [comment]
Bueno, ahora mismo así lo tenemos... en producción.
Podríamos cambiarle a Ingresar Cobro, para que haga match con CxC

**Comment by jccastillo0007** [comment]
Done, como lo sugerí hace tiempo y ya no recuerdo tu respuesta algo de son cosas diferentes y no se que ...

**Comment by RigoFlores** [comment]
Como quiera siempre habrá confusión, sobre todo porque el documento fiscal que se puede generar, es el de recepción de pagos... ouch!!!

Dejémoslo así... a ver si no reclama optibelt...
