### ISSUE TITLE
V3.3 CxC - no permite registrar pago, sin necesidad de generar el CFDI de DRP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1136]
Anteriormente, la pantalla tenia un ícono de guardar. Eso es para simplemente registrar el pago.

Ahora si no capturas los datos del DRP, te marca error.
Tenemos que mantener la funcionalidad anterior, esto es, que el usuario pueda ingresar un pago, sin precisamente generar un CFDI de DRP a huevito.

Se supone que el botón debe ser único, y el checkbox, indicará si se debe generar o no el CFDI, en cuyo caso si se tiene que validar que se capturen los datos requeridos para dicho CFDI DRP

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
le moviste algo al registro de cobro?
Si consulto un pago realizado en una sola exhibición... digamos uno a uno  (se pagó el total de una factura)... al consultar el cobro... si lo encuentra, pero no aparece el abono realizado...

**Comment by jccastillo0007** [comment]
Fixed.
