### ISSUE TITLE
Conector V3.3 - en pagos, envia incorrectamente la variable tipoCambioP al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1137]
la está mandando como $0.00

**Comment by jccastillo0007** [comment]
si la moneda es MXN, el tipo de cambio no se informa en el conector, y pues no se manda ni en la factura ni en pagos ni al pdf.

chiaaaaa

**Comment by RigoFlores** [comment]
Si te das cuenta, el issue dice que al tipo de cambio le pone el signo de $, lo cual es incorrecto

**Comment by jccastillo0007** [comment]
Chiaaaa, yo me fui con que lo mandaba en 0.

**Comment by RigoFlores** [comment]
de hecho, también hay que corregir, que si no se incluye el tipo de cambio, no se envíe 0.00, ya que en sí 0 es un valor... simplemente debe ir vacío...

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Negativo, sigue igual. Hay que agregar a este issue, que las variables que no se envian, debe aparecer vacías en el PDF... ya que ahora aparecen con valores supongo yo iniciales:
![variablespagos](https://user-images.githubusercontent.com/2912775/31578079-b27d4d04-b0df-11e7-959a-625d1c37c556.PNG)

**Comment by RigoFlores** [comment]
En el ejemplo de arriba, no envié tipo de cambio, saldo anterior, importe pagado, saldo insoluto, número de pago. Nada de eso envié. Sin embargo lo muestra, supongo yo porque lo inicializas, ya que esa variables son utilizadas en productos... te recuerdo el mapeo.


PAGO | PRODUCTO   ESTANDAR
-- | --
IdDocumento | unidad
Serie | idProducto
Folio | descripcion
MonedaDR | cuenta   predial
TipoCambioDR | importe
MetodoDePagoDR | idProductoSAT
NumParcialidad | descripcionComplementaria
ImpSaldoAnt | valorUnitario
ImpPagado | cantidad
ImpSaldoInsoluto | descuento

**Comment by jccastillo0007** [comment]
fixed.

Asegurate de bajar la versión de hoy

**Comment by RigoFlores** [comment]
En el conector, no está enviando el saldo insoluto correctamente.
De hecho la variable donde lo estamos esperando es descuentoPro.

**Comment by jccastillo0007** [comment]
aún revisando

**Comment by jccastillo0007** [comment]
oye, recuerdas si esto ya se enviaba antes ? no encuentro evidencia de algún cambio mio, pero efectivamente no lo esta enviando...

Pregunta,,,, descuentoPro no lo tengo registrado, se manda en la sección de los dattos de los productos o del cfdi en general ?

**Comment by jccastillo0007** [comment]
Estos son los datos que se estan enviando actualmente 

	// Documento de Pagos
	private String formaDePagoP = "";
	private String monedaP = "";
	private String tipoCambioP = "";
	private String monto = "";
	private String numOperacion = "";
	private String rfcEmisorCtaOrd = "";
	private String nomBancoOrdExt = "";
	private String ctaOrdenante = "";
	private String rfcEmisorCtaBen = "";
	private String ctaBeneficiario = "";
	private String tipoCadPago = "";
	private String certPago = "";
	private String cadPago = "";
	private String selloPago = "";

**Comment by RigoFlores** [comment]
El saldo insoluto, como el nombre de la variable sugiere, es a nivel de producto.
Recuerda que nos aventamos 'la puntada' de no crear mas variables a nivel producto, para el pago, y reutilizamos las ya existentes.
Por ahí está el desmadre seguramente.
Y esa variable, no recuerdo si se enviaba o nó, posiblemente si.
También recuerda, que hay que corregir este problema a nivel conector estándar y revisar si también aplica para el conector de Navision

**Comment by jccastillo0007** [comment]
pues yo creo que mas bien nunca la hemos enviado... y hasta ahorita alguien la necesita... deja veo.

En el xml donde se manda ?

**Comment by RigoFlores** [comment]
Cómo así? Pues arriba está el cuadro de correspondencia.
Recuerda, no está enviando el saldo insoluto al PDF, y el tipo de cambio lo envía como $0.00
Para el caso de que la moneda del documento pagado sea MXN, el tipo de cambio, simplemente no se envía.


Folio="2063" IdDocumento="7419833f-0eb0-4021-a2a4-8c84b9350601" ImpPagado="368.88" ImpSaldoAnt="368.88" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PPD" MonedaDR="MXN" NumParcialidad="1" Serie="B"

**Comment by RigoFlores** [comment]
Aquí un ejemplo con moneda en USD, donde SI SE INCLUYE EL TIPO DE CAMBIO EN EL XML.

Folio="199" 
IdDocumento="CCF518B0-DC5C-4382-9470-CADEE893AA81" 
ImpPagado="1000.00" 
ImpSaldoAnt="3500.00" 
**ImpSaldoInsoluto="2500.00"** 
MetodoDePagoDR="PPD" 
**MonedaDR="USD"** 
NumParcialidad="1" 
Serie="DD" 
**TipoCambioDR="1"**

**Comment by RigoFlores** [comment]
Tenemos que cerrar ya este issue que es a nivel detalle del documento de pago (NO ES A NIVEL DE VARIABLES GENERALES):

a) Enviar al PDF el saldo insoluto, variable: descuentoPro
b) Cuando la moneda sea distinta a MXN, enviar el tipo de cambio al PDF, pero sin el signo $. El tipo de cambio se debe tomar del CFDI que se está pagando. Variable: importe

**Comment by jccastillo0007** [comment]
No ma... que desmadre... esto es a nivel del documento relacionado, ni siquiera de los datos del complemento de pago...

**Comment by jccastillo0007** [comment]
Sería mucho mas rápido si me pasaras la forma de reproducirlo... yo utilicé estos datos y si me esta enviando todo bien al xml y pdf... recuerda que el conector manda lo que se recibe en el campo documentoRelacionado

**Comment by jccastillo0007** [comment]
En este ticket que en el titulo dice "envia incorrectamente la variable tipoCambioP" , en realidad tu lo usaste para reportar dos errores distintos :  
1. el envío de saldo insoluto al pdf
2. el tipo de cambio cuando la moneda es USD en el documento relacionado

**Comment by jccastillo0007** [comment]
Para el primer defecto :  
1. el envío de saldo insoluto al pdf.

No lo pude reproducir... yo genere una factura con el txt que anexo y si me envió el saldo insoluto a ambos lados, xml y pdf
txt :  
[PagoCadPago.txt](https://github.com/jccastillo0007/eFacturaT/files/2280716/PagoCadPago.txt)


Asi me llegó la variable al pdf :  

descuentoPro=$500.00

**Comment by jccastillo0007** [comment]
Para el segundo defecto :  

2. el tipo de cambio cuando la moneda es USD en el documento relacionado

Esto aplica cuando el pago en si mismo tiene moneda MXN y el documento relacionado tiene USD... (si ambos son USD, me da un error de que no se debe informar el tipo de cambio)

Cuando la condición de arriba sucede... ya esta enviando el tipo de cambio 

<pagos:Pagos xmlns:pagos="http://www.sat.gob.mx/Pagos" Version="1.0">
            <pagos:Pago CadPago="||1|14032018|14032018|143609|40072|HSBC|VICTOREEN DE MEXICO S A DE C V|40|021180040598321626|VME871116R22|BANORTE/IXE|TRANSFORMACIONES INDUSTRIALES ESPECIALIZ|40|072818006675395694|TIE101203NZ4|PAGO VICTOREEN A TRANSFORMACIONES ESP DE|0|3172.14|00001000000305298787||Rea2+ZVznhwzMgEmiHX34OJt1BH3Z7vrbStBWrU++/5ZfAutP7jGANs1hHCM5+GAMrz6D71DVlAMhh5e/ATRGCkagqYqwtgAQmwsUOR30f49u24ZAkXsqbEVjGX6mjJE7Crbxu3ir4lRnNOCTFiHqj0gOge0vmXU1RpDj5YGlnw=" CertPago="TURBd01ERXdNREF3TURBek1EVXlPVGczT0RjPQ==" CtaBeneficiario="036680500105247319" CtaOrdenante="1234567890123456" FechaPago="2017-07-10T12:00:00" FormaDePagoP="03" MonedaP="MXN" Monto="1500.00" NumOperacion="123" SelloPago="VW1WaE1pdGFWbnB1YUhkNlRXZEZiV2xJV0RNMFQwcDBNVUpJTTFvM2RuSmlVM1JDVjNKVkt5c3ZOVnBtUVhWMFVEZHFSMEZPY3pGb1NFTk5OU3RIUVUxeWVqWkVOekZFVm14QlRXaG9OV1V2UVZSU1IwTnJZV2R4V1hGM2RHZEJVVzEzYzFWUFVqTXdaalE1ZFRJMFdrRnJXSE54WWtWV2FrZFlObTFxU2tVM1EzSmllSFV6YVhJMGJGSnVUazlEVkVacFNIRnFNR2RQWjJVd2RtMVlWVEZTY0VScU5WbEhiRzUzUFE9PQ==" TipoCadPago="01">
                <pagos:DoctoRelacionado Folio="666" IdDocumento="CCF518B0-DC5C-4382-9470-CADEE893AA81" ImpPagado="100.00" ImpSaldoAnt="2000.00" ImpSaldoInsoluto="400.00" MetodoDePagoDR="PUE" MonedaDR="USD" NumParcialidad="1" Serie="DD" TipoCambioDR="19.55"/>
            </pagos:Pago>
        </pagos:Pagos>

No logre hacer que timbrara porque me marcaba error en los montos...  y no supe como cuadrarlo en relación a pesos y USD... pero en el complemento de pagos ya se ve el tipo de cambio.. ese tipo de cambio lo toma del string :  

documentoRelacionado={CCF518B0-DC5C-4382-9470-CADEE893AA81|DD|666|USD|19.55|PUE|1|2000.0|100.00|400.0}

**Comment by RigoFlores** [comment]
Si, ya se hizo un desmadre este issue, y creo yo que en parte se debe a que se toma mucho tiempo su resolución.
Voy a tomar la versión que subiste, volveré a validar y te comentaré como quedó todo.

**Comment by RigoFlores** [comment]
no pues estuvo pior, ahora ni siquiera levanta el facturat. Ya te envié los pormenores del nuevo error. Igual y algo hice mal
