### ISSUE TITLE
Web DRP v3.3 - no está enviando las variables completas al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1138]
A nivel general, no está llegando lo siguiente (TODO LO MANDA EN null):

FechaPago:
Forma de Pago:
Moneda Pago:
Tipo de Cambio:
monto del Pago:
No. de Operación:
RFC Banco Origen:
Cuenta Origen:
Cuenta Destino:
RFC Banco Destino:
Banco Origen:

A nivel detalle, no está enviando la información de los documentos relacionados al pago... (OJO, no es el documento relacionado al CFDI en sí, sino al pago realizado).

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
Entiendo que aún no tienes las nuevas plantillas que terminan con 33.
Por ello es que me marca error al momento de generar un DRP?

**Comment by jccastillo0007** [comment]
no lo creo, porque no he implementado lo de las plantillas con 3.3...

**Comment by RigoFlores** [comment]
OK, entonces ahora mismo en PRU al momento de generar un DRP que plantilla busca???

SIGUE MARCANDO ESTO:

Error al generar CFD (115)
