### ISSUE TITLE
Web v3-3 - Nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1140]
Estos son los ajustes:
a) Cambiar la versión a 3.3
b) Forma de pago "99"  (anteriormente "en una sola exhibición")
c) tipo de cambio no debe existir  (hay que validar si acepta el 1)
d) tipo de comprobante = 'N'  (anteriormente egreso)
e) metodo de pago = "PUE"  (anteriormente NA)
f) debe permitir documentos relacionados solo con la relación '04', que es que sustituye a cfdi anterior. Es decir aquí no debe presentar el listado, si se incluye cfdi relacionado el tipo de relación ya está definido.
g) uso de CFDI "por definir"  (nuevo)
h) Nodo impuestos no debe existir  (hoy existe una madre así     <cfdi:Impuestos/>  )

A nivel producto:
1) clave del SAT = 84111505  (nuevo)
2) ClaveUnidad = "ACT"  (nuevo)
3) Unidad desaparece (esta si aparece en cfdi 3.2 con valor "ACT"; para cfdi 3.3 desaparece)
4) Incluir descuento

Urge el timbrador para probar todo este asunto

**Comment by jccastillo0007** [comment]
Ya tengo listo esta parte, pero finkok no esta timbrando en PRU... si sigue asi, tendremos que migrarnos a FactureHoy, pero no recuerdo cuales eran sus restricciones para timbrar en pru, te mando por correo un ejemplo de nómina pero sin timbre

**Comment by jccastillo0007** [comment]
Pide afuerza el uso de cfdi... si no marca error...

**Comment by RigoFlores** [comment]
asi es, y el requisito arriba dice que el uso es 'por definir', que es parte del catálogo

**Comment by RigoFlores** [comment]
Se me pasó incluir a nivel producto, el descuento cuya definición es:

Se debe registrar el valor del campoTotalDeducciones.

A quién se le ocurre poner duplicada la información... bueno ni pex, si falta eso...

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Ya te mandé la plantilla, para que la subas y pueda validarlo... tu me avisas

**Comment by RigoFlores** [comment]
Revisé el XML, y el método de pago PUE, no se está incluyendo, pero si debe ir, de acuerdo a la guía de llenado de la nómina.
La misma guía indica que no debe existir el tipo de cambio, pero si lo estás incluyendo en el XML.

Si acepta el timbrado es que ambos datos son condicionales, pero precisamente la condición en el caso de nómina es que no debe ir. Podemos jugarle al wey, pero eventualmente nos podemos meter en problemas.

**Comment by jccastillo0007** [comment]
Deja hago los cambios hoy y checo si lo timbra finkok..

**Comment by RigoFlores** [comment]
Es decir, si está timbrando ya... con esas 2 salvedades... que el tipo de cambio no debería incluirse, y el método de pago PUE no lo está incluyendo.
Al menos el método de pago, creo que si debe atenderse.

**Comment by jccastillo0007** [comment]
pues si, si lo acepto... lo voy a liberar a pro, junto con la nueva plantilla

**Comment by RigoFlores** [comment]
ok, la nueva plantilla no está en pru, falta que la subas...
