### ISSUE TITLE
Producción WEB - para todos los clientes... EXCEPTO OPTIBELT...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1143]
Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..Excepto optibelt..

Poner todas las facturas emitidas a status pagadas, con fecha de agosto 2017 hacia atrás.... para propósitos de CxC

**Comment by jccastillo0007** [comment]
Todas las emitidas, sin importar si estan vigentes o vencidas ?

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
hoy el sentido de vigentes o vencidas, solo hace sentido para optibelt... para nadie mas.
Ningún cliente ha configurado los días de crédito... de ahí que el cron (no automático) para actualizar status de las facturas, solo lo ocupa optibelt.
A partir de esta versión, lo ocuparán todos los clientes....

**Comment by RigoFlores** [comment]
Algo está raro... consulté un cliente cualquiera de la tia, desde producción 3.3, y solo algunas facturas aparecieron como pagadas, pero otras anteriores, no tienen status alguno...

![pagadas](https://user-images.githubusercontent.com/2912775/31144098-3d16169c-a845-11e7-8055-9236cda8fec7.PNG)

**Comment by jccastillo0007** [comment]
listo... me faltaban todos los que estaban vacíos.
