### ISSUE TITLE
Web v3.3 - en la pantalla de facturación, muestra lugar de expedición como municipio, estado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1145]
Ya no aplica eso... en su lugar simplemente el CP del emisor, tal cual se va al PDF y XML

De hecho antes estaba editable, ya que no se tenía definido su contenido... ahora está totalmente definido que es el CP de donde se emite la factura... matriz o sucursal... ese campo podría aparecer de solo lectura... pero ya no se puede editar.

Su contenido, al igual que en el XMl y PDF... sería el CP de lo que antes era el ExpedidoEn...

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Chiaaaa... está muy ancho el campo...
favor de pasarlo a la derecha, y reducir el ancho de la caja de texto.

**Comment by jccastillo0007** [comment]
done
