### ISSUE TITLE
Producción 3.3 - BLOCKER No permite cambiar cantidad y precio unitario de manera simultánea

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1146]
Si agregas producto, y le cambias la cantidad y además el precio unitario, te arroja el siguiente error:

El valor del campo Importe o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido (3)

Según yo tiene que ver con la base nuevamente.
La base siempre se debe sugerir al importe. Cada vez que actualiza la cantidad o el precio unitario, se debe sugerir la nueva base.
Lo que falta es hacerlo a nivel de impuesto, ya que eso se ocupará en las constructoras.

**Comment by jccastillo0007** [comment]
Repite 100 veces.
Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base, Debo modificar la base,

**Comment by RigoFlores** [comment]
Como comenté, la base que SI ACEPTA, es incorrecta.
La base que debería aceptar, es la reportada en el nodo de impuestos.

Fue un malentendido del concepto.
Esto se resolverá de raíz, cuando se corrija correctamente el manejo de la base. Por lo pronto, le diré a los clientes que capturen una base incorrecta para que jale... chiaaaaa

**Comment by RigoFlores** [comment]
No tardan en pedirnos facturas de gobierno, y ahí es donde la base a nivel impuesto se ocupará, sobre todo en los impuestos locales...
