### ISSUE TITLE
Web v3.3 - CxC - Ingresar cobro - no funciona el filtro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1147]
Hoy estoy empezando a utilizar ese módulo, para llevar el control interno, y además para irlo conociendo.
Estoy viendo que en las consultas de ingresar cobro, no está respetando el filtro de vigentes o vencidas... te arroja todas con cualquier filtro que apliques.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
parece que ya quedó... para confirmar puedes poner los días de crédito a 7, para todos los clientes del RFC ACO... y correr el proceso de actualizacion de status de facturas de cxc?

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
al menos en pru, ya respeta el filtro de vigentes o vencidas
