### ISSUE TITLE
Web 3.3 - mientras queda solucionado lo de la base, un guorcarraun

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1148]
Así como lo tenemos, confunde mas y sobre todo genera mensajes de error.... 
el guorcarraund solicitado es... o la base se actualiza en automático cada vez que cambien el precio unitario, o simplemente se quita e internamente se hace lo que proceda... hoy genera mas problemas que soluciones... porque ni es el concepto de base, ni está a nivel de impuestos, pero si genera mensajes de error y con ello llamadas de soporte y bla bla bla...

Insisto, muy pronto lo van a pedir los de gobierno, y hace falta validarlo

**Comment by jccastillo0007** [comment]
okas, lo quitamos... por mientras.

**Comment by RigoFlores** [comment]
ok, solo asegurando que si modifican el precio unitario, entonces que internamente haga lo que tenga que hacer..

**Comment by RigoFlores** [comment]
negativo, ya validé y marca error... y ahora no hay forma de corregirlo...

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ok, ya quedó... hoy frecibí la primera llamada de soporte ya que marcó error por el tema de la base.. si se puede subir este fix deunvez, mejor
