### ISSUE TITLE
OPTIBELT 3.3 - TOMAR EL TIPO DE CAMBIO DE LA PANTALLA DE FACTURA-T

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1149]
Es decir, en el archivo de texto formato levicom, se tomará la moneda como hasta ahora se realiza.
Como el tipo de cambio es obligatorio en 3.3, entonces este se deberá tomar del dato configurado en la pantalla de Factura-T, para la moneda que corresponda.

**Comment by jccastillo0007** [comment]
Ok, pero ojo... la moneda que nos llega en el archivo, debe estar en el catalogo de monedas.

**Comment by RigoFlores** [comment]
por supuesto, ya viste que solo se ocupan 3 monedas.

**Comment by RigoFlores** [comment]
Hice una prueba con la moneda USD.
Esa moneda NO EXISTIA EN EL CATÁLOGO DE MONEDAS DE FACTURA-T, y le asignó un tipo de cambio 1.0, lo cual es incorrecto

**Comment by RigoFlores** [comment]
Le agregué la moneda y si tomó el tipo de cambio...
OK, LO TOMAREMOS COMO BUENO
