### ISSUE TITLE
Marca error 301, cuando no se captura municipio en el domicilio fiscal receptor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#115]
Para el receptor el único dato obligatorio es país.
Deseable que capturen todo completo, pero realmente se debería solo validar el país.

**Comment by jccastillo0007** [comment]
Ese error lo esta mandando edicom / SAT, no se exactamente de donde viene...  pero además, el error es correcto....

El schema dice que :  
        <xs:attribute name="municipio" use="optional">
para el domicilio tanto del emisor como receptor, sin embargo, tambien dice :  

```
    <xs:attribute name="municipio" use="required">
```

para el domicilio fiscal del emisor... y es ahi donde no se esta cumpliendo.

**Comment by jccastillo0007** [comment]
Al emisor que di de alta, le faltaba el municipio como parte de su domicilio,.... ya lo probé y si funciono.

**Comment by RigoFlores** [comment]
ME PARECE QUE ALGO RARO VOLVIÓ A OCURRIR... QUE EXTRAÑO, DE REPENTE YA NO SE PUEDE REPRODUCIR EL ERROR

**Comment by jccastillo0007** [comment]
Lo que pasa, es que no lees mis correos y las notas de los defectos....

Comentaba que el error fue el municipio del campo "Expedido en" ahi si 
es obligatorio... entonces revise los datos del emisor que me enviaste, 
y me di cuenta que no le habia puesto municipio.... entonces se lo 
agregue y listo.

Saludos.
JC.

**Comment by RigoFlores** [comment]
Totalmente de acuerdo. Debo leer y prestar atención al comentario. A ti también te pasa, tons puto el que no lea chido, de aquí en delante.

Ya lo revisé y encontré algunos detalles interesantes en el anetso tuenti.
a) Tanto domicilio fiscal del emisor como el expedido en, son elementos opcionales. (podríamos quitarlos del XML y entiendo no habría impacto. Por supuesto, NO los eliminamos).
b) Dentro de su opcionalidad, el domicilio fiscal del emisor, tiene como obligatorios los campos de calle, municipio, estado, país y CP (tipo de variable ubicación fiscal).
c) Dentro de su opcionalidad, el expedido en, solo tiene como obligatorio el país (del tipo ubicación).
d) Por otro lado, el domicilio fiscal del RECEPTOR que es del tipo ubicación, también es opcional. Y dentro de su opcionalidad, por ser tipo ubicación, solo lleva obligatorio el país.

OK, aquí la única pregunta que me queda, es como funciona eso de un elemento opcional, que dentro de sus atributos incluye algunos como obligatorios???

**Comment by jccastillo0007** [comment]
Agreed.

Respecto a :
aquí la única pregunta que me queda, es como funciona eso de un elemento 
opcional, que dentro de sus atributos incluye algunos como obligatorios???

El elemento padre es opcional, puedes no incluirlo... peeeeero, si lo 
incluyes, entonces te chingas y debes agregar algunos elementos hijos 
obligatorios...

Asi como que si quieres una vieja, te chingas y a mantenerla....

Saludos.
JC.

**Comment by RigoFlores** [comment]
No pues está cabrón, mas bien si la quieres y opcionalmente te casas, entonces ya te obligaste a chingarte para mantenerla.... ya entendí......pinches opcionales-obligatorios, no deberían existir....jeje
