### ISSUE TITLE
OPTIBELT 3.3 - EL MÉTODO DE PAGO SERÁ PUE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1150]
Hoy en día, siempre aparece pago en una sola exhibición para sus facturas.
Con ello, facturat deberá enviar al XML la clave PUE para método de pago, y para el PDF deberá enviar igual la clave y descripción.

**Comment by jccastillo0007** [comment]
fixed.

Aun no se puede probar, hasta que te avise que ya esta lo de optibelt

**Comment by RigoFlores** [comment]
Pues ayer cambiaron este requisito, ya que originalmente ellos dijeron que se mantenga igual como hasta ahora, es decir PUE.
Sin embargo sus clientes ya le empezaron a pedir que deberán indicar PPD.
Estoy en plática con ellos, para saber cómo identificaremos el PPD.

**Comment by RigoFlores** [comment]
ya me definieron como será.
en el campo H1.8 viene una clave que se interpretará como:
19 = PUE
62 = PPD

**Comment by jccastillo0007** [comment]
Ok, el campo H1.8 se interpretaba como condiciones de pago... supongo que ya no se usará dicho campo.

**Comment by RigoFlores** [comment]
me parece que no estás contando la letra inicial del layout, que corresponde al campo 1, por ello no te salen las cuentas... pero entiendo que no se debe recorrer...

**Comment by RigoFlores** [comment]
H1||171059048||20171114|A144352 0001488561-1 171059048|20171114|19|25|

el que aparece con el número 19 es el campo H1.8
Anteriormente no venían las condiciones de pago, sino venía "pago en una sola exhibición /cuenta 111"
Ahora vendrá 19 = PUE, 62 = PPD
Pero no lo está haciendo

**Comment by jccastillo0007** [comment]
done.
