### ISSUE TITLE
Optibelt 3.3 - El uso de CFDI se tomará del catálogo del cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1151]
Ese dato no se incluirá en el archivo de texto.
En su lugar se tomará el dato de la pantalla de catálogo de clientes.
Agregar este dato a nivel de cliente y también a nivel de nombre alterno.

**Comment by jccastillo0007** [comment]
Será mejor que si lo incluyan, solo necesitamos la clave, hay muchos datos que no se utilizan, lo que pasa es que de querer resolverlo nosotros, hay que hacer varios cambios en la versión standalone para poner el catálogo de usos de CFDi en el catálogo de clientes y de nombres alternos.

**Comment by RigoFlores** [comment]
Ya hablé con ellos... el uso del CFDI se tomará del campo H1.31, es decir donde viene la forma de pago, y se incluirá de la siguiente manera, por ejemplo:

99/G01

Primero viene la clave de forma de pago, y enseguida una / y posteriormente el código del uso del CFDI.
Aquí es importante mencionar que podrían o no, incluirse espacios entre los datos, pero en definitiva todo lo que venga después del / (eliminando espacios), será el código de uso del CFDI.

**Comment by jccastillo0007** [comment]
done
