### ISSUE TITLE
Optibelt 3.3 - completar los datos de IVA de acuerdo a la tasa que se envia en el texto plano

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1152]
Solo manejan impuesto trasladado de IVA, con tasa 16 o tasa 0.
Completar los datos según corresponda:

                <cfdi:Traslados>
                    <cfdi:Traslado Base="420.00" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="67.20"/>
                </cfdi:Traslados>

**Comment by jccastillo0007** [comment]
fixed.
