### ISSUE TITLE
Optibelt 3.3 - CFDI relacionado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1153]
Solo cuando se emita una nota de crédito, se tomará el dato que corresponda a la factura relacionada.
el tipo de relación será:

01  - Nota de   crédito de los documentos relacionados

El dato del CFDI relacionado, te lo indico tan pronto lo conozca.

**Comment by jccastillo0007** [comment]
fixed.

Aun no se puede probar, hasta que te avise que ya esta lo de optibelt

**Comment by RigoFlores** [comment]
respecto al dato del CFDI relacionado

> para conocer la factura asociada a la nota, se capturará en el campo de observaciones (H1.6) el número de folio de la factura relacionada. Será la primera cadena de texto antes del primer espacio.

**Comment by jccastillo0007** [comment]
done.
