### ISSUE TITLE
Implementar addenda Gamesa en Web, junto con la creación del xsd

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1154]
Ya está desarrollada, solo falta agregar los RFC's receptores.
Estoy en espera de que me entreguen la información de los receptores.

**Comment by jccastillo0007** [comment]
no que mucha prisa?

**Comment by RigoFlores** [comment]
pues apenas están respondiendo...
No sé a cuál RFC le asociaste la addenda, pero debe ser este: GEM070226K52
Yo recuerdo que te lo envié, pero no veo donde.

Como quiera pls revisa que esté así, ya que di de alta ese rfc en pruebas, le configuré el archivo de addenda gamesa que enviaste y puro chile, no hizo nada.
Si es cuestión de agregar el RFC receptor, pls agrégalo tanto en pru como en pro...

**Comment by jccastillo0007** [comment]
Ok, de acuerdo... estaba configurado un tal RFC FOPR681125BQ0, quien sabe por que..

**Comment by RigoFlores** [comment]
está en pru y pro???... puedo probar ahora mismo???
No ma, otra vez el pinchi día completo, los clientes están locos... jeje
