### ISSUE TITLE
DRP - NO PERMITE CAPTURAR UN NOMBRE DE BANCO EXTRANJERO EN CATALOGO CLIENTES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1155]
De donde tomaste el catálogo de bancos que aparece en el catálogo de clientes, que se ocupa en DRP?
No está mal, pero creo que podriamos asociarle el RFC del banco, ya que no cambiará.
Creo que existe un catálogo de bancos de la nómina, pero en pagos no se especifica su uso. Insisto, no está mal, pero si vamos a entregar un listado, creo que podríamos ya agregarle el RFC.

En el caso de un banco extranjero, el nombre es obligatorio para DRP y no hay forma de capturarlo ahora mismo. Quizás hacer algo similar a los catálogos de domicilio, es decir que se pueda elegir de un catálogo y/o captura manual.

**Comment by jccastillo0007** [comment]
Es el catálogo de bancos que me enviaste.

**Comment by RigoFlores** [comment]
Cuál y cuando tu?

**Comment by jccastillo0007** [comment]
Con el query SELECT * FROM BANKCATALOG, puedes ver el catálogo completo, pasame los RFC de los bancos para agregarlos

**Comment by RigoFlores** [comment]
supongo que en algún momento lo envié... pero no para DRP... ah ya sé... es para nómina...
no tengo los RFC's de los bancos... habría que irlo alimentando de a poco...
la otra es simplemente dejar de libre captura los 3 datos...

Lo que es un hecho, es que para el RFC XEXX... se pueden definir nombres distintos de bancos, ya que son extranjeros...

**Comment by jccastillo0007** [comment]
bueno, pues que capturen el rfc ....

**Comment by RigoFlores** [comment]
no entendí, para el caso de bancos extranjeros, es decir RFC XEXX01010100, se requiere, es obligado reportar el nombre del banco.
Si comentas que ya está resuelto, indícame pls como debo capturar ese nombre...

**Comment by jccastillo0007** [comment]
cuando des de alta el banco en el catálogo de clientes, ahi capturan el nombre y el número de cuenta... según recuerdo, asi lo pediste no?

Si quieren varios nombres, tendrían que cambiarlo ahi.

JC

**Comment by RigoFlores** [comment]
pero solo aparece el listado de bancos y no se puede teclear distinto a dicha lista... (que la lista es de nómina, pero no de pagos...aunque es lo mismo, no lo es... jeje).
Cómo te decía, se puede mantener la lista, pero si no aparece, abrir un campo tipo los del domicilio, para que si no es juana, sea chana

**Comment by jccastillo0007** [comment]
Pues solo hay que agregar el banco extranjero, que siempre tiene un rfc XEXX0101010000 según yo.. y cada cliente captura el nombre que necesite.

**Comment by jccastillo0007** [comment]
a creo que no... lo que se captura es el RFC pero no el nombre del banco...

**Comment by RigoFlores** [comment]
TANTO PARA LA PANTALLA DE CONFIGURACIÓN, COMO PARA LA PANTALLA DE CATÁLOGO DE CLIENTES, EL NOMBRE DEL BANCO DEBE TECLEARSE

**Comment by RigoFlores** [comment]
ya brincó la liebre de este issue... los 3 datos deben ser de libre captura... en el catálogo de clientes.
Nombre, RFC y cuenta.
Un cliente quiso capturar para banco extranjero, y obvio que no pudo.
Pls te encargo

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
como funciona? 
En el catálogo de clientes podías elegir de la lista y te mostraba el item elegido en la caja de texto. Posteriormente podías cambiarlo si se requería.

Aquí eliges uno de la lista, y no lo coloca en la caja de texto. En ese caso como sabemos si ya está elegido o no?
