### ISSUE TITLE
DRP - Los datos de bancos y números de cuenta son opcionales para bancos nacionales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1156]
Ahora mismo, marca error si no los capturo.
Pinche SAT está cabrón, solicita un chingo de datos y a la mera hora se abre, y los pone como opcionales.

Vamos a dejar como obligatorios (*) el monto del pago, la fecha, la referencia, forma de pago, moneda.
Que los clientes decidan si quieren incluir información de los bancos o nó.
Pero para ello, debemos poder timbrar el DRP sin los datos del banco.

**Comment by jccastillo0007** [comment]
De hecho , asi lo probé sin capturar bancos, ni del emisor ni del receptor... y asi si lo timbra

**Comment by RigoFlores** [comment]
algo estamos haciendo diferente... anexo imagen...
![drp](https://user-images.githubusercontent.com/2912775/31457710-316c8b2a-ae83-11e7-9732-d96121dc1174.PNG)

**Comment by jccastillo0007** [comment]
fixed....

**Comment by RigoFlores** [comment]
Con la información mínima si jala
Cuando incluyes el banco destino,  si jala
Cuando incluyes el banco origen, no jala.

Recordar que el nombre del banco origen, ÚNICAMENTE ES REQUERIDO cuando el RFC del banco origen es XEXX010101000, es decir solo aplica para bancos de cuenta ordenante (origen), extranjeros. Para RFC's distintos a XEXX, NO APLICA EL NOMBRE DEL BANCO.
