### ISSUE TITLE
Conector v3.3 - Pagos, xml mal formado cuando no se incluye el RFC del banco

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1157]
Si nada mas se incluye la cuenta, pero no el RFC en el texto planto, genera un XML incorrecto, ya que si reporta los rfc's pero vacíos, y eso provoca un error... 

pagos:Pago CtaBeneficiario="036680500105247319" CtaOrdenante="03668
0500105247319" FechaPago="2017-07-10T00:00:00" FormaDePagoP="03" MonedaP="MXN" M
onto="2000.00" NumOperacion="123" **RfcEmisorCtaBen="" RfcEmisorCtaOrd=""**

**Comment by jccastillo0007** [comment]
fixed
