### ISSUE TITLE
Optibelt 3.3 - Forma de Pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1158]
Antes estaban al contrario forma de pago y método de pago.
OK, ya considerando ese cambio, realmente no van a hacer nada ellos.
Nosotros tenemos que enviar la clave que corresponda de acuerdo a lo que venga en el archivo.

Entiendo que prácticamente, tenemos que voltear lo de forma de pago y método de pago.
Y en la forma de pago, enviar la descripción que corresponda al PDF.

**Comment by jccastillo0007** [comment]
done.

Aun no se puede probar, hasta que te avise que ya esta lo de optibelt

**Comment by RigoFlores** [comment]
también aquí hay que correr un cueri, con el famoso distinct para identificar las distintas formas de pago que han enviado el último año...

**Comment by RigoFlores** [comment]
Ya cambiaron el enfoque, ya que ahora lo van a controlar desde su aplicación.
Ahora la clave de forma de pago, vendrá en el campo H1.31
Generalmente será 99, pero ellos lo colocarán.

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
mysql> select count(*), paymentWay  from CFD where sourceRFC = 'OME111223UN4' group by paymentWay;
+----------+-----------------------------------------+
| count(*) | paymentWay                              |
+----------+-----------------------------------------+
|       22 | 02.CHEQUE NOMINATIVO                    |
|     1327 | 03.TRANSFERENCIA ELECTRONICA DE FONDOS  |
|       10 | 99.OTROS                                |
|       18 | Cheque                                  |
|      129 | NA                                      |
|     2367 | Pago en una sola exhibicion/Cuenta      |
|     2546 | Pago en una sola exhibicion/Cuenta   NI |
|      318 | Pago en una sola exhibicion/Cuenta  N/A |
|      141 | Pago en una sola exhibicion/Cuenta 0035 |
|      168 | Pago en una sola exhibicion/Cuenta 0201 |
|        3 | Pago en una sola exhibicion/Cuenta 0414 |
|        4 | Pago en una sola exhibicion/Cuenta 0600 |
|       17 | Pago en una sola exhibicion/Cuenta 0634 |
|      379 | Pago en una sola exhibicion/Cuenta 0879 |
|       97 | Pago en una sola exhibicion/Cuenta 1601 |
|       11 | Pago en una sola exhibicion/Cuenta 1681 |
|        2 | Pago en una sola exhibicion/Cuenta 1691 |
|       12 | Pago en una sola exhibicion/Cuenta 1703 |
|      144 | Pago en una sola exhibicion/Cuenta 1711 |
|        3 | Pago en una sola exhibicion/Cuenta 2092 |
|       47 | Pago en una sola exhibicion/Cuenta 2125 |
|      180 | Pago en una sola exhibicion/Cuenta 2311 |
|      361 | Pago en una sola exhibicion/Cuenta 2341 |
|       88 | Pago en una sola exhibicion/Cuenta 2441 |
|      230 | Pago en una sola exhibicion/Cuenta 2712 |
|       16 | Pago en una sola exhibicion/Cuenta 2774 |
|       16 | Pago en una sola exhibicion/Cuenta 2784 |
|      110 | Pago en una sola exhibicion/Cuenta 2931 |
|        8 | Pago en una sola exhibicion/Cuenta 3420 |
|       82 | Pago en una sola exhibicion/Cuenta 3659 |
|       31 | Pago en una sola exhibicion/Cuenta 3694 |
|       34 | Pago en una sola exhibicion/Cuenta 3784 |
|      742 | Pago en una sola exhibicion/Cuenta 3790 |
|      223 | Pago en una sola exhibicion/Cuenta 3851 |
|       14 | Pago en una sola exhibicion/Cuenta 4168 |
|       26 | Pago en una sola exhibicion/Cuenta 4343 |
|        2 | Pago en una sola exhibicion/Cuenta 4420 |
|       56 | Pago en una sola exhibicion/Cuenta 4440 |
|       19 | Pago en una sola exhibicion/Cuenta 4496 |
|     1766 | Pago en una sola exhibicion/Cuenta 4842 |
|      319 | Pago en una sola exhibicion/Cuenta 4974 |
|        8 | Pago en una sola exhibicion/Cuenta 5006 |
|        8 | Pago en una sola exhibicion/Cuenta 5520 |
|      252 | Pago en una sola exhibicion/Cuenta 5542 |
|        1 | Pago en una sola exhibicion/Cuenta 5721 |
|       12 | Pago en una sola exhibicion/Cuenta 5774 |
|      141 | Pago en una sola exhibicion/Cuenta 5876 |
|      440 | Pago en una sola exhibicion/Cuenta 5894 |
|       57 | Pago en una sola exhibicion/Cuenta 5931 |
|       43 | Pago en una sola exhibicion/Cuenta 5978 |
|        5 | Pago en una sola exhibicion/Cuenta 5984 |
|        4 | Pago en una sola exhibicion/Cuenta 5993 |
|       26 | Pago en una sola exhibicion/Cuenta 6403 |
|      607 | Pago en una sola exhibicion/Cuenta 6485 |
|       27 | Pago en una sola exhibicion/Cuenta 6775 |
|        9 | Pago en una sola exhibicion/Cuenta 6778 |
|       92 | Pago en una sola exhibicion/Cuenta 6848 |
|        6 | Pago en una sola exhibicion/Cuenta 7225 |
|       29 | Pago en una sola exhibicion/Cuenta 7228 |
|       11 | Pago en una sola exhibicion/Cuenta 7325 |
|        4 | Pago en una sola exhibicion/Cuenta 7350 |
|       11 | Pago en una sola exhibicion/Cuenta 7613 |
|        1 | Pago en una sola exhibicion/Cuenta 7614 |
|       66 | Pago en una sola exhibicion/Cuenta 7664 |
|       58 | Pago en una sola exhibicion/Cuenta 7785 |
|        5 | Pago en una sola exhibicion/Cuenta 8506 |
|        5 | Pago en una sola exhibicion/Cuenta 8629 |
|       56 | Pago en una sola exhibicion/Cuenta 8980 |
|      270 | Pago en una sola exhibicion/Cuenta 9279 |
|       17 | Pago en una sola exhibicion/Cuenta 9607 |
|       41 | Pago en una sola exhibicion/Cuenta 9654 |
|      336 | Pago en una sola exhibicion/Cuenta CADO |
|        3 | Pago por adelantado                     |
|      319 | Transferencia                           |
+----------+-----------------------------------------+
74 rows in set (1.42 sec)

mysql> select count(*), paymentType from CFD where sourceRFC = 'OME111223UN4' group by paymentType;
+----------+-----------------------------------------+
| count(*) | paymentType                             |
+----------+-----------------------------------------+
|        8 | 01                                      |
|      519 | 02                                      |
|     9750 | 03                                      |
|      210 | 99                                      |
|     2740 | NA                                      |
|      384 | Pago en una sola exhibicion/Cuenta      |
|      172 | Pago en una sola exhibicion/Cuenta   NI |
|       45 | Pago en una sola exhibicion/Cuenta  N/A |
|        5 | Pago en una sola exhibicion/Cuenta 0035 |
|        8 | Pago en una sola exhibicion/Cuenta 0201 |
|        3 | Pago en una sola exhibicion/Cuenta 0414 |
|        6 | Pago en una sola exhibicion/Cuenta 0634 |
|       15 | Pago en una sola exhibicion/Cuenta 0879 |
|        6 | Pago en una sola exhibicion/Cuenta 1391 |
|        6 | Pago en una sola exhibicion/Cuenta 1537 |
|        4 | Pago en una sola exhibicion/Cuenta 1601 |
|        2 | Pago en una sola exhibicion/Cuenta 1703 |
|        6 | Pago en una sola exhibicion/Cuenta 1711 |
|        3 | Pago en una sola exhibicion/Cuenta 2125 |
|        5 | Pago en una sola exhibicion/Cuenta 2311 |
|      190 | Pago en una sola exhibicion/Cuenta 2341 |
|        3 | Pago en una sola exhibicion/Cuenta 2441 |
|       34 | Pago en una sola exhibicion/Cuenta 2712 |
|        3 | Pago en una sola exhibicion/Cuenta 2752 |
|        3 | Pago en una sola exhibicion/Cuenta 2931 |
|        3 | Pago en una sola exhibicion/Cuenta 3420 |
|        3 | Pago en una sola exhibicion/Cuenta 3659 |
|        7 | Pago en una sola exhibicion/Cuenta 3784 |
|       16 | Pago en una sola exhibicion/Cuenta 3790 |
|       13 | Pago en una sola exhibicion/Cuenta 4440 |
|        1 | Pago en una sola exhibicion/Cuenta 4496 |
|      276 | Pago en una sola exhibicion/Cuenta 4842 |
|       30 | Pago en una sola exhibicion/Cuenta 4974 |
|        2 | Pago en una sola exhibicion/Cuenta 5520 |
|       97 | Pago en una sola exhibicion/Cuenta 5542 |
|        7 | Pago en una sola exhibicion/Cuenta 5721 |
|       11 | Pago en una sola exhibicion/Cuenta 5876 |
|       56 | Pago en una sola exhibicion/Cuenta 5894 |
|       23 | Pago en una sola exhibicion/Cuenta 5931 |
|        2 | Pago en una sola exhibicion/Cuenta 5984 |
|       15 | Pago en una sola exhibicion/Cuenta 5993 |
|      120 | Pago en una sola exhibicion/Cuenta 6485 |
|        5 | Pago en una sola exhibicion/Cuenta 6775 |
|        3 | Pago en una sola exhibicion/Cuenta 6848 |
|        6 | Pago en una sola exhibicion/Cuenta 7225 |
|        1 | Pago en una sola exhibicion/Cuenta 7325 |
|        1 | Pago en una sola exhibicion/Cuenta 7614 |
|        5 | Pago en una sola exhibicion/Cuenta 7785 |
|        5 | Pago en una sola exhibicion/Cuenta 8980 |
|        3 | Pago en una sola exhibicion/Cuenta 9279 |
|        1 | Pago en una sola exhibicion/Cuenta 9559 |
|        4 | Pago en una sola exhibicion/Cuenta 9607 |
|      178 | Pago en una sola exhibicion/Cuenta 9654 |
|       31 | Pago en una sola exhibicion/Cuenta CADO |
|        3 | Pago por adelantado                     |
+----------+-----------------------------------------+
55 rows in set (1.40 sec)

**Comment by jccastillo0007** [comment]
que fumados

**Comment by RigoFlores** [comment]
OJO, en todo el archivo de texto, la primera letra es el campo 1, creo que estás recorriendo el número de campos.

**Comment by RigoFlores** [comment]
no está tomando la forma de pago del H1.31, al parecer está fijo. Ese campo está justo antes de la moneda. En el ejemplo de abajo es 03, es decir transferencia electrónica de fondos.

OJO. ya comenté que delante del 03, 99 o el valor que sea le agregarán / G01, es decir diagonal y el uso del CFDI. Ya logré que lo incluyan en el texto.

H1||171059048||20171114|A144352 0001488561-1 171059048|20171114|19|25|O|Factura Comercial||||||||||2017||||262307|16|||||03|MXN

**Comment by jccastillo0007** [comment]
done.
