### ISSUE TITLE
Optibelt - Moneda

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1159]
Asegurar que la moneda que hoy mismo manejan, la estemos mapeando a la clave del sat que le corresponda.
Entiendo que solo manejan 'pesos' y 'dolares'.
Parte de lo que tenemos que hacer, es un distinct de las monedas que se han ocupado el último año, y de ahí identificar cómo tenemos que mapearlas.

**Comment by jccastillo0007** [comment]
Ellos ya mandan MXN que es la clave del SAT, tons estamos bien.... quien sabe si usen USD... podemos preguntarles... 

en donde decias que revisara que monedas usan ?

**Comment by RigoFlores** [comment]
estoy seguro que si ocupan USD.
Lo que te decía es que de la información de cada CFDI de ellos almacenada en la BD del web, puedas darle un distinct de las monedas, para estar seguros cómo viene y cómo debemos mapearla.

**Comment by jccastillo0007** [comment]
mysql> select count(*), currency from CFD where sourceRFC = 'OME111223UN4' group by currency;
+----------+----------+
| count(*) | currency |
+----------+----------+
|        2 | EUR      |
|    15050 | MXN      |
|        6 | USD      |
+----------+----------+
3 rows in set (1.37 sec)

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
quiere decir que aquí no haremos nada y la enviaremos directo???
