### ISSUE TITLE
No funciona la conversión de monedas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#116]
Si el producto lo capturaste en moneda nacional y en la pantalla cambias a cualquier otra moneda, no realiza ni reporta correctamente la conversión. Ejemplo:

Producto 1, $100.00 MN
USD tipo de cambio 10.0

al elegir este producto y la moneda USD, el precio reportado en el XML y pdf, debería ser 10.00, en lugar de 100.00

Solamente reporta el cambio de moneda y el tipo de cambio diferente, pero no realiza la conversión.

**Comment by RigoFlores** [comment]
Quizás esto cobre relevancia con todo lo que traemos por delante...

**Comment by jccastillo0007** [comment]
Francisco, puedes hacer un debug y ver que es lo que esta pasando... puede estar complicado de resolver, pero primero revisa como funciona y vamos viendo.

**Comment by jccastillo0007** [comment]
Fixed.

Si no funcionan tus pruebas o detectas algo chueco, puedes checarlo con Fco directamente.
