### ISSUE TITLE
Catálogo de productos CFDI v3.3 - agregar opción para asignar la misma clave a todos los productos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1160]
Hay clientes que manejan miles de productos.
Agregar la clave uno por uno, será muy complicado.
Agregar un checkbox para asignar la clave capturada en ese momento, a todos los productos, al momento de guardar.

**Comment by jccastillo0007** [comment]
hmmm dado que no creo que eso aplique para la mayoria de nuestros clientes, prefiero que nos lo pidan y lo hacemos por query, si no hay que desarrollar algo que se va a usar una sola vez, por algunos clientes.

**Comment by RigoFlores** [comment]
Podria ser que se equivocaron y ahora tienen que cambiar todos las claves de producto.
Yo creo que si seria de utilidad...

**Comment by jccastillo0007** [comment]
cuando se equivoquen y quieran homologar tooooodos sus productos, que nos den la info y lo hacemos nosotros.
