### ISSUE TITLE
Conector 3.3 - cuando detecte cfdi tipo pago buscar la plantilla correspondiente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1161]
Se configura su plantilla para factura en el properties, as usual.

Llama o busca formato especial para:

- Acuse de cancelación  (cfdi_AcuseCancelacion.jrxml)
- Nota de Crédito  (cfdi_notaCredito33.jrxml, se puede poner que si no encuentra este, ocupe la que tiene configurada?????)
- DRP  (cfdi_pagos.jrxml)
- Nomina  (cfdi_nomina33.jrxml)

**Comment by jccastillo0007** [comment]
Asi es casi casi como funciona actualmente

Siempre busca un template configurado en su configuración  particular, si no existe, entonces usa la genérica para el tipo de documento, ahora lo que estas solicitando, es que tenga configurada un template específico para cada tipo de documento, antes de ir a buscar el genérico?

**Comment by RigoFlores** [comment]
Creo que te estás confundiendo con el web.
Aquí es el conector... o en general también aplica para escritorio.
Ahora mismo, ya busca las plantillas con nomenclatura especial para acuse de cancelación, recibo de nómina y nota de crédito. Eso ya lo hace ahora mismo.

Lo que se pide en este issue para el conector y asumo que sería lo mismo para escritorio, es que 

a) cuando se trate de pagos, busque una plantilla específica, igual que en los 3 casos anteriores
b) en el caso de nota de crédito, ahora mismo marca error si no la encuentra; lo que se pide es que si no halla en específico la nota de credito, que ocupe la misma plantilla que tiene configurada en el properties para aplicar en la nota de crédito

**Comment by jccastillo0007** [comment]
Ups, si, el titulo dice conector, pero yo estaba pensando en web.

**Comment by jccastillo0007** [comment]
Simon, si se puede, si no existe la plantilla cfdi_pagos.jrxml, entonces va a usar lo que se tenga configurado en la variable facturaTi.template

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
nop... otra vez no se entendíó...

eso que si no encuentra la plantilla, se vaya a la de default... es solo para nota de crédito.
La plantilla de pagos, es muy distinta a la de factura... ahí si debe buscar la plantilla específica para pagos...

chiaaaaaa

**Comment by jccastillo0007** [comment]
mmm pues la plantilla especifica de pagos será cfdi_pagos.jrxml y se va a incluir en standalone por default... tons ya no entendi

**Comment by RigoFlores** [comment]
es que comentaste esto:
Simon, si se puede, si no existe la plantilla cfdi_pagos.jrxml, entonces va a usar lo que se tenga configurado en la variable facturaTi.template

y precisamente eso no se pide.
Se pide que busque la plantilla específica para pagos siempre. Al igual que nómina y acuse de cancelación.
Y solo en caso de nota de crédito, si no encuentra la correspondiente, que use la configurada.

**Comment by jccastillo0007** [comment]
ah ok, por eeeeeso
asi queda

("CARTA DE PORTE"))  = "cartaporte33.jrxml";
("RECIBO DE NOMINA") = "cfdi_nomina.jrxml";
("NOTA DE CREDITO") = "cfdi_notacredito.jrxml" si no existe usa la que se configuró en el properties
"PAGO") = "cfdi_pago.jrxml";

**Comment by RigoFlores** [comment]
que no sería???

("CARTA DE PORTE")) = "cartaporte33.jrxml";
("RECIBO DE NOMINA") = "cfdi_nomina33.jrxml";
("NOTA DE CREDITO") = "cfdi_notacredito33.jrxml"

("PAGO") = "cfdi_pago.jrxml";

**Comment by RigoFlores** [comment]
pues no, ahora ni procesa los pagos...

**Comment by jccastillo0007** [comment]
Pues, ya deje todo con 33 al final
("CARTA DE PORTE")) = "cartaporte33.jrxml";
("RECIBO DE NOMINA") = "cfdi_nomina33.jrxml";
("NOTA DE CREDITO") = "cfdi_notacredito33.jrxml"
("PAGO") = "cfdi_pago33.jrxml";

Ahora no se porque jijos ya no procesa los archivos... ching....

**Comment by jccastillo0007** [comment]
ya esta jalando... y ahora si subi la version al dropbox

**Comment by RigoFlores** [comment]
no, no procesa ningún archivo...

**Comment by RigoFlores** [comment]
aceptó pagos OK.
nómina lo abriré en otro issue.
traslado marca error, ya que no reconoce el tipo=7;

**Comment by RigoFlores** [comment]
cuál es el tipo para traslado???

**Comment by jccastillo0007** [comment]
FACTURA("FACTURA", 0, "ingreso"), 
NOTA_CARGO("NOTA DE CARGO", 1, "ingreso"), 
NOTA_CREDITO("NOTA DE CREDITO", 2,"egreso"), 
HONORARIOS("RECIBO DE HONORARIOS", 3, "ingreso"), 
ARRENDAMIENTO("RECIBO DE ARRENDAMIENTO", 4, "ingreso"), 
DONACIONES("RECIBO DE DONATIVOS", 66, "ingreso"), 
NOMINA("RECIBO DE NOMINA", 7, "n"), 
CARTA_PORTE(	"CARTA DE PORTE - TRASLADO", 6, "traslado"), CARTA_PORTE_INGRESO("CARTA DE PORTE - INGRESO", 99, "ingreso"), 
DOCUMENTO_PAGO(	"DOCUMENTO DE PAGO", 8, "P"),
 REMISION("REMISION", 10, "ingreso");

**Comment by RigoFlores** [comment]
no jala carta porte por conector, tampoco tenemos algún caso con clientes, lo dejaremos pendiente.
