### ISSUE TITLE
Navision V3.3 - clave de producto y clave de servicio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1162]
Estas claves se obtendrán de los siguientes campos:

[Clave producto y servicio SAT] 
[Cód_ clave unidad SAT] 

ESTE ES EL CUERI PARA CONOCER EL DETALLE DE UNA FACTURA.

select 
[timestamp],
[Document No_] as "no. factura"
,[No_] as "referencia"
,[Cód_ arancelario] as "codigo arancelario"
,[type]
,[DESCRIPTION]
,[Clave producto y servicio SAT] as "claveProductoSAT"
,[Cód_ clave unidad SAT] as "claveUnidad"
,[UNIT OF MEASURE]
,[QUANTITY]
,[UNIT PRICE]
,[VAT %]
,[AMOUNT]
,[AMOUNT INCLUDING VAT]
,[LINE AMOUNT]
,[Line Discount Amount] as "monto descuento"
,[Nº pedimento]
,[fecha documento pedimento]  
from [PRUEBAS_SAT].[dbo].[MEXICO - IP - PRUEBAS SAT$Sales Invoice Line] 
where [Document No_] 
in ( '17FVMX167' ) order by [timestamp];

**Comment by RigoFlores** [comment]
Los campos nuevos aplican también, para la tabla correspondiente de nota de crédito.

**Comment by jccastillo0007** [comment]
done. que pinches fumados.

Hay que venderles un sistema bien hecho k.

**Comment by RigoFlores** [comment]
pues agregaron los campos nuevos, está bien que no?

**Comment by jccastillo0007** [comment]
si, pero su pinche base de datos, es todo un lio, no ma

**Comment by RigoFlores** [comment]
ah si... me dijeron que andaba echando la hueva por no entender que su BD, realmente eran varias...
