### ISSUE TITLE
CFDI Web - falta incluir clave de pais de residencia para receptor XEXX010101000

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1164]
Para receptor extranjero, se requiere incluir la clave del país de residencia.
Aplica para ingreso, egreso, traslado, pago.

**Comment by jccastillo0007** [comment]
te refieres en el catálogo de clientes ?

Si su cliente es del rfc XEXX010101000, ahi mismo pueden seleccionar el pais, internamente la app le pondrá la clave del pais.

**Comment by RigoFlores** [comment]
si, pero no lo reporta en el XML, en el campo de residenciafiscal

**Comment by jccastillo0007** [comment]
ah ok, ya lo habilité
