### ISSUE TITLE
Navision 3-3 - Header de factura y nota de crédito

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1166]
Se agregan estos campos:

,[Clave SAT]   (clave de relación) 
,[Nº factura relacionada SAT]  (folio de factura de documento relacionado, hay que consultar el UUID de la tabla estado, a partir del folio ingresado aquí)
,[Cód_ Uso CFDI SAT]  (código de uso de CFDI)
,[Cód_ País SAT]  (código del país del receptor, se ocupa cuando el RFC es extranjero)
,[Anticipo]  (indica que esta factura es anticipo, aunque entiendo que realmente no hay que hacer algo en particular, ya que ellos ya resolvieron todas las claves que van predefinidas en un anticipo)
,[Metodo Pago SAT]  (clave del método de pago)
,[Forma de Pago SAT]   (clave de la forma de pago)

El campo Currency Code, no cambia. Cuando está vacío se asume que la moneda es MXN, en otro caso buscar el código de moneda, tal cual se hace ahora mismo.

**Comment by jccastillo0007** [comment]
De aqui ya tengo todo, pero aqui no entendi 

,[Nº factura relacionada SAT] (folio de factura de documento relacionado, hay que consultar el UUID de la tabla estado, a partir del folio ingresado aquí)

Cual es la tabla estado ?

**Comment by RigoFlores** [comment]
no es tabla estado, me equivoqué... es la tabla factura-t, que al momento de timbrar vamos a llenar precisamente los campos requeridos aquí...

**Comment by jccastillo0007** [comment]
Estoy haciendo pruebas ya de timbrado pero :   

1. La factura que me diste para probar no tiene ning[un producto... ocupo tener datos consistentes para poder probar.
2. El RFC con el que se puede timbrar es ACO... .tons voy a cambiar la llave por un tiempo..

**Comment by jccastillo0007** [comment]
Listo... ya esta timbrando la factura de pruebas que me indicaste.

Ojo...

Me falta incluir algunos datos en la tabla facturat al terminar el timbrado.
Puedes probar con la instalación que esta en TestFacturaT33, ejecutando el  bat
Hay que estar actualizando la base de datos para que puedas generar mas de una factura
Estoy usando el RFC ACO...., entonces puse ahi la llave de ACO y active el conector de navision para el rfc ACO... esto te puede afectar si tratas de hacer pruebas fuera de navision con la misma licencia de ACO...

**Comment by jccastillo0007** [comment]
si encuentras defectos especificos hay que levantar otro ticket.

Por cierto, también me falta la NC y DRP.

**Comment by RigoFlores** [comment]
Para la nota de crédito, aplican los mismos cambios que para la factura.
En documento de recepción de pago, cuando en la tabla correspondiente el número de pago es 0, implica que se ha pagado el total de la factura (y no en parcialidades)

**Comment by RigoFlores** [comment]
lo de pago lo sacaré de aquí, pero la nota de crédito si la mantendré... al fin que ya no debe tardar...

**Comment by RigoFlores** [comment]
y también faltan los datos que se deben agregar a la tabla factura-t, ya que se ocuparán en pagos

**Comment by RigoFlores** [comment]
ya me pusieron un ultimátum.... chiaaaaa....

**Comment by RigoFlores** [comment]
está timbrando facturas y notas de crédito. 
Falta actualizar la tabla factura-t (con el mensaje de error y/o generales del CFDI), así como reportar los documentos relacionados a partir de su serie y folio.
