### ISSUE TITLE
Navision 3-3 - DRP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1167]
Aquí está mas tranquilo, ya que en una tabla se encuentra toda la información de pagos.

	  select *
from [PRUEBAS_SAT].[dbo].[MEXICO - IP - PRUEBAS SAT$Lineas Documento de pago]
where [Folio de la Factura] 
in ( '17FVMX170' );

Esta tabla cuando el campo estado sea 0, indicará que hay que timbrar un documento de pago.
Ahora hay que chequear la tabla estado para facturas, notas de crédito, y esta otra tabla para emisión de DRP.

**Comment by jccastillo0007** [comment]
Ya se esta procesando los pagos... pero no puedo timbrar por problemas de datos...

todos los registro tenían una forma de pago FSAT que no se que signifique, para poder hacer pruebas les puse 03.

Los RFC de algunas facturas, me los esta regresando diciendo que no están en el patron de RFC no cancelados.

**Comment by RigoFlores** [comment]
ojo, en la tabla de pagos se indica la serie y folio de las facturas pagadas, que es el nodo de documento relacionado del complemento de pago. Pero el registro en esta tabla, es propiamente el CFDI de tipo pago, que lleva un nodo de documento relacionado.

Nosotros tenemos que tomar esa información, para que en la tabla de factura-t busquemos los datos de las facturas pagadas, que se necesita incluir en el drp


IdDocumento
Serie
Folio
MonedaDR
TipoCambioDR
MetodoDePagoDR

**Comment by jccastillo0007** [comment]
okas, ya estoy aplicando esos cambios.

En la tabla que crearon para guardar la info de los pagos... le hace falta un campo como el de Resultado de la tabla FacturaT, para guardar el motivo de un posible error... solo tenemos el campo Estado para guardar el código de error o éxito.

**Comment by jccastillo0007** [comment]
[temp.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/1465631/temp.xml.txt)

**Comment by jccastillo0007** [comment]
ese es el archivo que ya se esta generando.

**Comment by RigoFlores** [comment]
Solicité ya los nuevos campos,
No sé cuál es tu criterio para asignar serie y folio para el CFDI de pago, pero ya solicité dicho campo, junto con varios que detecté que estaban faltando.
Voy a cerrar este issue general y abriré los detallados. Por lo pronto ya levanté un par de ellos me parece.

En cuanto a datos que detecté como faltantes (yo los omití en su momento), te pido muy atentamente agregar los siguientes campos en la tabla:

1.	Resultado en la tabla de Lineas Documentos de Pago, donde estaremos almacenando el resultado del timbrado. Similar a la tabla Factura-T.
2.	Serie y Folio que le corresponderá a este CFDI de pago 
3.	Clave Tipo de Relacion – campo que se ocupará en caso que se esté generando un pago como sustitución de un anterior (por cancelación por ejemplo que le toca la clave 04). 
4.	CFDIs relacionados. Número de UUID o serie y folio del documento de pago cancelado, es decir el que está siendo sustituido.
5.	TipoCadPago
6.	CertPago
7.	CadPago
8.	SelloPago
