### ISSUE TITLE
Blocker en Producción - reporte de impuestos inconsistente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1168]
A nivel nodo de impuestos general del CFDI, se debe reportar la suma de los impuestos de cada uno de los productos en la factura. El monto de impuestos a nivel producto lo estás redondeando, pero la sumatoria a nivel general consideras las cantidades sin redondear, y eventualmente puede dar diferencias.
Te mandé un ejemplo por correo de un problema que tiene un cliente ahora mismo.

**Comment by jccastillo0007** [comment]
Resuelto el super mega blocker.
Lo ando deployando a PRO.. en unos momentos.

**Comment by RigoFlores** [comment]
el cliente tuvo que regresar a la 3.2....
ni pex, gajes del oficio...
lo que es un hecho, es que tienes que revisar un correo que envié con este tema... es mas delicado de lo que parece
