### ISSUE TITLE
En opcion de Addenda, cambiar etiqueta de Facturar x Agregar Addenda

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#117]
Cambiar la etiqueta del botón de Facturar, por Agregar Addenda.

**Comment by RigoFlores** [comment]
Si fuera posible cambiar el ícono del botón, mucho mejor, por algo mas ad-hoc

**Comment by jccastillo0007** [comment]
La etiqueta es fácil.

El icono también es fácil, pero necesito que me lo mandes, por que eso de adhoc es muy subjetivo , como tus comparaciones de tiempos de desarrollo entre lenguajes.

JC@iPhone.
 Saludos.
