### ISSUE TITLE
Implementar 3.3 en escritorio - requerimientos iniciales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1170]
En resumen, me parece que son estos (no descarto que se me vayan por ahí algunos). 
Quieres que levante uno a uno en el github, o los atiendes de aquí, y lo que salga ya lo vamos subiendo al github?

En cuanto a pantallas:

Agregar campo para clave de unidad  (catálogo de unidades) sin afectar productos. Tomar la clave para el XML, así como en web.
Agregar campo para clave de productos  (catálogo de productos)
Agregar el catálogo de uso de CFDI en pantalla de facturación.
Actualizar el catálogo de forma de pago, método de pago.
Quitar número de tarjeta en la pantalla de facturación

Internamente:
Impuestos a nivel producto: Manejar la base=importe
Pasar a MXN todas las monedas similares a pesos, sin afectar la relación con los productos.
Lugar de expedición es el CP
Incluir manejo de descuentos e impuestos a nivel producto
Régimen fiscal tomarlo de la configuración como clave. en la configuración se capturará la clave.
Mapear a claves de impuesto, las definición de impuestos que tenemos ahora mismo en los catálogos
Todos los impuestos serán Tasa

**Comment by RigoFlores** [comment]
Con cuál está duplicado???

**Comment by jccastillo0007** [comment]
chiaaaaa 
https://github.com/jccastillo0007/eFacturaT/issues/1169

**Comment by RigoFlores** [comment]
marca error cuando incluyes descuentos...

2017-10-30 21:42:12,809  INFO [AWT-EventQueue-0] (CFDiWSClient.java:77) - Factur
aTi ack : com.facturati.ws.binding.jaxb.Ack@c169b0[code=003,description=El TipoD
eComprobante es I,E o N, el importe registrado en el campo no es igual a la suma
 de los importes de los conceptos registrados.]
