### ISSUE TITLE
Conector - Web - Escritorio - no acepta nombre vacío

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1171]
El RFC es el único dato obligatorio en el nodo receptor.
Incluso el nombre puede ir vacío.
De hecho para facturas público en general, se supone que el nombre debe ir vacío.

Cuando se timbra sin el nombre del receptor, marca XML mal formado, y si... ya que se forma así, y en ese caso no debe incluir el Nombre=""; simplemente omite ese atributo o parámetro.

    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="" UsoCFDI="P01"/>

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
para web y conector?

**Comment by RigoFlores** [comment]
En web sigue marcando el error... en conector, no veo ninguna nueva versión.

**Comment by jccastillo0007** [comment]
es que no lo subi ayer, ups...

pero ya esta

**Comment by RigoFlores** [comment]
no procesa los archivos.
Según yo es lo que te platiqué hace días, que tenías que abrir branches..., ya que solo podemos timbrar con un solo RFC emisor... entonces supongo que se quedó la versión que está "apuntando" a navision...

a) para conector estándar/escritorio
b) para navision
c) para optibelt

**Comment by jccastillo0007** [comment]
fixed.
