### ISSUE TITLE
Escritorio 3.3 - valores por omisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1173]
a) Colocar el minicatálogo de unidades, en la pantalla de catálogo de unidades así como en el web, para una quick reference.
b) forma de pago igual a transferencia
c) condiciones de pago igual a vacio
d) lugar de expedición, igual a solo lectura
e) uso de cfdi igual a gastos en general
f) en catálogo de productos, agregar link a la aplicación del sat para búsqueda de claves

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
faltó lo de condiciones de pago igual a vacío...
