### ISSUE TITLE
Implementar Nómina 3.3 por conector 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1174]
Todos los cambios son en el bagraunt, y esto lo ocupa figueacero a la de ya:
Estos son los ajustes:

a) Cambiar la versión a 3.3
b) Forma de pago "99" (anteriormente "en una sola exhibición")
c) Tipo de cambio no debe existir (hay que validar si acepta el 1)
d) Tipo de comprobante = 'N' (anteriormente egreso)
e) metodo de pago = "PUE" (anteriormente NA)
f) debe permitir documentos relacionados solo con la relación '04', que es que sustituye a cfdi anterior. g) uso de CFDI:  "99. Por definir" 
h) Nodo impuestos no debe existir (hoy existe una madre así cfdi:Impuestos/ )

A nivel producto:

clave del SAT = 84111505 (nuevo)
ClaveUnidad = "ACT" (nuevo)
Unidad desaparece (esta si aparece en cfdi 3.2 con valor "ACT"; para cfdi 3.3 desaparece)
Incluir descuento

**Comment by jccastillo0007** [comment]
estuve probando con el layout actual la nómina, pero me marca error en el row de productos... cómo quedarían los productos para generar la nómina ? con nuestro nuevo layout, me puedes preparar un txt

**Comment by RigoFlores** [comment]
ok, ya revisé... te refieres a migrar al layout nuevo en la sección del XML estándar.
Deja prepararlo y te lo envío.

**Comment by jccastillo0007** [comment]
te voy a enviar un xml generado desde la app, finkok dice xml mal formado, pero cuando uso su validador dice que todo esta ok... tons no se que le falte.

**Comment by jccastillo0007** [comment]
puedes probar en pro.?

**Comment by RigoFlores** [comment]
con la versión de hoy temprano? o vas a subir alguna versión nueva hoy o mas tarde?

**Comment by RigoFlores** [comment]
con la versión de hoy temprano, marca error... que no se reporta el uso del cfdi

**Comment by RigoFlores** [comment]
con el archivo que enviaste si jala, pero no busca la plantilla de nómina que según comentaste era cfdi_nomina33.jrxml

**Comment by RigoFlores** [comment]
Ya jala, solo falta:
a.	Indicar la clave del régimen fiscal  (aquí casi podría ser casi un hecho, que va fijo a 601).
b.	Indicar la clave de forma de pago. (esto es incorrecto, ya que es un valor fijo: 99) Aquí hay que dejarlo al valor fijo.
c.	Y bueno, lo que comentamos, que es que falta lo de documentos relacionados. Eso ya lo tienes por conector para factura. No sé si con ello ya pudiera jalar también para nómina

**Comment by jccastillo0007** [comment]
Done.
a, ya esta ok
b, fixed
c, ya funciona

**Comment by RigoFlores** [comment]
EN CUANTO LO PUEDA VALIDAR, LO CIERRO..
LO DE DOCUMENTOS RELACIONADOS, TE LO COMENTÉ QUE YA ESTABA PARA FACTURA, PERO NO LEES... CHIAAAAA

**Comment by RigoFlores** [comment]
la forma de pago correcta, ya veo que si la incluye en el XML.
los cfdis relacionados tambien los incluye.
No puedo probar en pru, queda pendiente la prueba en pro.
