### ISSUE TITLE
Web 3.3 - al menos el catálogo de forma de pago no está actualizado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1175]
No coincide con pruebas que está bien y en producción es incorrecto.
No sé si solo eso está chueco o que mas falta de actualizar

**Comment by jccastillo0007** [comment]
fixed.

Eso pasa cuando le hice caso a alguien y puse este catálogo en base de datos.
Chia.

**Comment by RigoFlores** [comment]
Es decir que se resolvió de la manera mas elegante y fácil que existe, que incluso yo pude haberlo hecho y yo podría cambiarlo en un futuro?
Se hizo el cambio, sin necesidad de compilar, ni reiniciar, ni deployar, ni nada...???

Al parecer queremos pasarnos a como deben manejarse los catálogos del SAT.
