### ISSUE TITLE
Web - Escritorio 3.3 - a nivel producto, falta incluir la variable numeroItem

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1176]
Resulta que los españoles la requieren, y no sé en que momento se quedó fuera de la jugada, pero bueno... ahora ya lo tenemos identificado... falta enviarla al jasper para web y para escritorio o conector

**Comment by jccastillo0007** [comment]
Según yo ya estaba, me falta solo agregar cuando se agregan productos en lugar de cfdi relacionados en los pagos...

**Comment by RigoFlores** [comment]
ah ok
