### ISSUE TITLE
Conector 3.3 - cuando se reporta cantidad mayor a 1, truena

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1177]
Lo que está haciendo es recalcular la base del cálculo de impuestos, aún cuando la base es un dato que ya viene en el layout. Está tronando...

cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd">
    <cfdi:Emisor Rfc="ACO560518KW7" Nombre="Cliente de pruebas de timbrado de fi
nkok" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="MCF100227NW0" Nombre="00110005 - MUEBLES Y COLCHONES FER
NANDEZ,S.A. DE C.V." UsoCFDI="P01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="40101602" NoIdentificacion="CF02020PGO141"
 Cantidad="200.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="CIRCULADOR DE A
IRE MCA KENMORE 127 (CAF2020MAN127)" ValorUnitario="5000.00" Importe="1000000.00
">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="200000000.00" Impuesto="002" TipoFactor
="Tasa" TasaOCuota="0.160000" Importe="160000.00"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="160000.00">
        <cfdi:Traslados>
            <cfdi:Traslado Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000
" Importe="160000.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
</cfdi:Comprobante>

**Comment by jccastillo0007** [comment]
fixed
