### ISSUE TITLE
Inicializar todas las variables de Jasper a null - conector - escritorio -web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1178]
Para propósitos de una plantilla dinámica, que muestre o nó campos, etc... necesito que todas las variables se inicien a null, ya que en las condiciones se compara con ese valor...

ahora mismo, algunas variables van a null, y otras a $0.00

**Comment by jccastillo0007** [comment]
haber checale con la versión de hoy.

**Comment by RigoFlores** [comment]
vi que aparentemente ya quedó para conector, asumo que escritorio va de la mano.
la pregunta es para web ya quedó también?

**Comment by RigoFlores** [comment]
en el conector, la variable descuento, llega como $0.00, cuando no se captura el descuento, que de acuerdo a lo solicitado aquí, debería llegar como ""

Es posible o no, que todas las variables que no se ocupan en alguna factura en particular, se envíen como "" ?

**Comment by jccastillo0007** [comment]
si, ya lo hice... solo que en algunas variables numericas, no las deja como "" y las formatea...
Pero eso también lo puedo corregir, solo que si hay que saber exactamente cuales son, por lo pronto se lo pongo al descuento, y me dices si encuentras mas

**Comment by RigoFlores** [comment]
la nueva versión se quedó apuntando a navision...
se está complicando ese asunto... no puedo validar nada nuevo de escritorio, y tampoco de navision...

**Comment by RigoFlores** [comment]
para confirmar, esto lo aplicaste para conector, escritorio y web???

**Comment by RigoFlores** [comment]
en web está distinto, lo cual me obliga a tener distintas plantillas para escritorio que para web.
Pls necesito que todas las variables se inicien de la misma manera en escritorio y en web.

En escritorio aparentemente están inicializadas a ""
En web me arroja 'null'

no sé cuál es la diferencia, pero necesito que se inicialicen igual...

**Comment by jccastillo0007** [comment]
ya apliqué estos cambios en web y standalone...

**Comment by RigoFlores** [comment]
en producción???
Se sigue comportando distinta la plantilla...

**Comment by jccastillo0007** [comment]
ya esta en PRO, lo subí ayer.. a PRU y PRO

**Comment by jccastillo0007** [comment]
Tenias razon me habían faltado algnos campos... ahora si ya esta.

**Comment by RigoFlores** [comment]
me parece que numeroAduana (a nivel producto) no lo estás inicializando bien... chécale, tanto en web como en escritorio.

**Comment by jccastillo0007** [comment]
fxied... tambi[en me falta cuenta Predial.

**Comment by RigoFlores** [comment]
la misma plantilla en escritorio ya se comporta ok, pero en web aparentemente tiene problemas con numero de aduana o cuenta predial.

**Comment by RigoFlores** [comment]
Esa plantilla quedó muy bien en escritorio, pero no puedo ocuparla en web, según yo porque no está inicializado a null cuenta predial o número de aduana.
Y la verdad esa plantilla me ahorrará mucho trabajo de soporte

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Realmente este issue nunca se concluyó, ya que la plantilla en web tiene que se distinta que en escritorio, debido a que las validaciones de comparación de string con null o vacío, no se comportan igual.
