### ISSUE TITLE
Cambiar nombre de XML con addenda, en el addendador

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#118]
Agregar el sufijo _Add, al nombre original del XML, después que se le agregó la adenda.

**Comment by jccastillo0007** [comment]
El archivo original del cliente, mantiene su nombre, el sistema no cambia el nombre.

Para el archivo que ya contiene la addenda, se maneja el mismo nombre que FacturaT, le pone a todas las facturas.

Aún así crees necesario que se agregue _ADD al archivo.. ? creo que no es necesario, además siempre pueden  bajar el original y el archivo con addenda....

Y si finalmente quieres que se agregue... no esta tan rápido, ya que estoy reutilizando el código (aunque tu digas que no se reutiliza), y en ningun caso se manejan sufijos en los archivos.

**Comment by RigoFlores** [comment]
Es correcto tu comentario. 
No sé porque pensé que se llamaban igual, y mi petición realmente era que se distinguieran en nombre.
Este issue no aplica, se acepta el rechazo.

**Comment by jccastillo0007** [comment]
A huevo por fin

JC@iPhone.
 Saludos.
