### ISSUE TITLE
Escritorio 3.3 - implementar documentos relacionados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1181]
Yo creo que la mas simple es agregar en la pantalla de facturación el listado de las opciones de documentos relacionados, y una caja de texto donde se capturen los UUID's separados por coma ','.

Como la beisbol?

**Comment by jccastillo0007** [comment]
Done.... hay que teclear el uuid y pueden ser varios separados por comas.

**Comment by RigoFlores** [comment]
en cuanto puedas, elimina los espacios que pueden existir entre uuid y uuid.
Cuando son varios y no hay espacios entre las comas, no hay problema. 
Si le pones espacio entre las comas, eso lo agrega al xml.

    <cfdi:CfdiRelacionados TipoRelacion="04">
        <cfdi:CfdiRelacionado UUID="92a3ae94-199f-417b-902d-c4dd96f5564e "/>
        <cfdi:CfdiRelacionado UUID=" 92a3ae94-199f-417b-902d-c4dd96f5564f"/>
    </cfdi:CfdiRelacionados>

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
no ví un nuevo rilis, si subiste?

**Comment by RigoFlores** [comment]
no he visto nuevo rilís
