### ISSUE TITLE
Escritorio 3.3 - enviar al web la información de las facturas como lo hace el superconector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1182]
Esto es para atender lo de documentos de pagos desde el web... cuando facturan desde escritorio.
No es necesario (por lo  pronto), recrear el PDF o subir el XML.

**Comment by jccastillo0007** [comment]
Esto lo hacemos para tooooodos los clientes ?

seguro, porque se va a incrementar mucho nuestra base de datos... 

que tal si lo hacemos solo para los que nos van pagando, actualmente esta habilitada esta funcionalidad para los RFCs de Figueacero y OME111223UN4....

**Comment by RigoFlores** [comment]
ok, lo haremos para los que vayan pagando escritorio update...

No va a ser tan fácil llevar este control... pero vamos viendo...

se le puede agregar al keygenerator este fichur?

**Comment by jccastillo0007** [comment]
noup, porque esa configuración se hace en el timbrador, que es el backend, el key generator solo aplica para cosas del frontend osea la interfaz gráfica.

**Comment by RigoFlores** [comment]
yo pienso que será un desmadre, ya que cuando lo pida un cliente de escritorio, es porque ya emitió la factura y cuando quiera emitir el drp no la va encontrar en su BD... eso sin contar que se tendrá que esperar un tiempo antes que se le habilite eso en la plataforma...

yo sigo pensando que no se suba el xml, ni el pdf... que eso se controle, pero la info que es almacenar en la DB no creo que afecte tanto... amén que ahora mismo, la mayoría de clientes están en web..

**Comment by jccastillo0007** [comment]
pues si quieres lo habilito de una buena vez, para que luego no te estén llamando .

**Comment by RigoFlores** [comment]
Se puede empatar habilitar esta función, junto con la actualización de escritorio/superconector?
Es decir, solo aquellos que hayan actualizado el facturat (y pagado), serán reconocidos en el server para subir sus facturas?
Creo que con eso amarraríamos que solo los que paguen tendrán derecho a utilizar ese módulo de CxC, que por otro lado, ya debe estar activo para todos.

**Comment by jccastillo0007** [comment]
negativo.... esto se hace en el server, hay que habilitarlo, no creo que nos pegue tanto... y podemos ganar clientes con ese feature.

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
que significa que ya esté don?
que todos los clientes actualmente en escritorio, ya están reflejando sus facturas en la BD del web?
o solo en pruebas, o como valido que ya está don?

**Comment by RigoFlores** [comment]
Generé una factura desde escritorio, apuntando a producción, con la versión de hoy en la mañana y no la envió a la  plataforma. Fue con el RFC de la tia... así que no está jalando esta parte.

**Comment by jccastillo0007** [comment]
listo
