### ISSUE TITLE
Agregar receptor para el complemento de servicios parciales de construcción

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1183]
Adicional a los RFC's que comentaste, agregar este: 

TQM041022SG6

rfcs ya existentes:
CII770127MA2
VCS120820NK6
CVA9210236L2

**Comment by jccastillo0007** [comment]
Lo aplique directo a PRO y PRU, no supe si era solo en PRU.. ups.

**Comment by RigoFlores** [comment]
ESTÁ MARCANDO UN ERROR DE XML MAL FORMADO...
QUIZÁS ASÍ NOS TOQUEN TODAS LAS ADDENDAS...

TE MANDARÉ POR CORREO EL RESULTADO, TANTO EN PRU COMO EN PRO

**Comment by RigoFlores** [comment]
SI, YA VALIDÉ EL ERROR... SI LE CAPTURO TODOS LOS DATOS NO MARCA EL ERROR.
ENTONCES SI HAY QUE CORREGIRLO, PERO MIENTRAS TANTO SI LE URGE, LE DIRÉ QUE LLENE TODOS LOS DATOS AUNQUE SEA CON "N/A"

**Comment by jccastillo0007** [comment]
y como que datos son opcionales ? o normalmente podrían ir vacíos.?

**Comment by RigoFlores** [comment]
es que los datos son domicilio... y no siempre lleva referencia, número interior, localidad, etc.
cuando no se capturan, entonces no se tendrían que enviar, pero se reportan como "", y marca error de equiemel mal formado

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
EN PRODUCCIÓN???

**Comment by jccastillo0007** [comment]
simon
