### ISSUE TITLE
Escritorio 3.3 - en nota de crédito envía mal la tasa del impuesto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1184]
la está enviando como 16.0000, en lugar de 0.16 como lo pide el sat.

**Comment by jccastillo0007** [comment]
no sé si lo arreglé mientras arreglaba los otros issues, pero cuando llegue a este, no lo pude reproducir, pues si reporta la tasa correctamente en el XML, de hecho si se puede timbrar.
