### ISSUE TITLE
Escritorio 3.3 - marca error con descuentos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1185]
Está marcando error cuando le indicas un descuento

**Comment by jccastillo0007** [comment]
fixed.

Wey, ya van mas de 100 defectos, y ya estaba en los ochentas... chiaaa asi como voy a terminar.

**Comment by RigoFlores** [comment]
cuando aplicas descuento, ya lo timbra y lo envía correctamente al XML.
En el PDF, el total de la factura lo envia incorrectamente, ya que no considera el descuento.

**Comment by jccastillo0007** [comment]
Fixed.
