### ISSUE TITLE
Web 3.3 - no acepta IVA tasa 0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1188]
marca internal error

**Comment by RigoFlores** [comment]
Esto afecta para entregar lo del complemento educativo, ya que las colegiaturas llevan iva tasa 0.

**Comment by jccastillo0007** [comment]
listo... es durante la migración, debo poner factor = tasa para que no marque ese error

**Comment by RigoFlores** [comment]
ACABO DE REALIZAR NUEVAMENTE LA PRUEBA, NO SE SI YA LO ATENDISTE, PERO YA NO MARCÓ EL INTERNAL ERROR
