### ISSUE TITLE
Web Instituciones educativas - debe permitir capturar la información complementaria

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1189]
Está bien que se incluya colegiatura o inscripcion como inicio de la información complementaria, para cambiar la descripción del producto, que pasa del nombre del alumno a colegiatura/inscripcion.

Pero todo lo que venga delante de ello, debe ser considerado como información complementaria del PDF, donde se menciona el mes que están pagando o cualquier otra leyenda que se ocupe.
Incluso, podrían indicar que esa información complementaria, se incluya en el XML

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
negativo, no jaló en pruebas

**Comment by RigoFlores** [comment]
Quedó chueco, por no decir peor…

•	Ahora manda el nombre del alumno como descripción al PDF y al XML
•	Colegiatura lo manda como información complementaria, no importa si es “colegiatura” o ”colegiatura mes de enero”
•	El nombre del alumno no lo envía como datoExtraPro3
•	Finalmente no incluye el complemento.

Pareciera como si toda la funcionalidad de complemento educativo hubiese dejado de existir, ya que se comporta exactamente como lo haría una factura estándar. Todo un desastre.
Te preguntaba cómo puedo saber que un cliente lo tiene activado en web. Tu mencionaste 4 rfc’s, pero eso está en hardcode en escritorio. En web, este es el primer cliente que tiene este complemento.

Ya casi estaba listo, y ahora a repetir todas las pruebas una vez que se corrija… necesitamos eficientar nuestro tiempo, no podemos estar retrabajando…

Cómo debería quedar de acuerdo a lo platicado, es que si la información complementaria es “colegiatura mes de noviembre 2017” y el producto es el ‘alumno’.

a)	La descripción al PDF y XML será “colegiatura”
b)	Información complementaria será “mes de noviembre 2017” 
c)	datoextraPro3 será el nombre del alumno, que el datoextrapro1 es el CURP y el 2, es el nivel escolar.
d)	una vez que se abre la ventana de datos extra y se cierra, esto indica que se debe incluir el complemento con los datos del alumno
e)	finalmente generar el PDF con los datosextraPro como dice el punto a, b y c. El XML se genera con complemento.

Tengo aún dudas…
En datos extra generales, los nombres de las variables deben ser exactamente los nombres de los niveles escolares del complemento?
En datos extra a nivel producto, cuando se trata del alumno, el dato extra 2, que es el nivel escolar, debe teclearse exactamente como se llama el nivel dentro del complemento?

No manches, voy a entregar algo que quedó chueco….

**Comment by RigoFlores** [comment]
mañana a como de lugar el cliente va a facturar...

**Comment by jccastillo0007** [comment]
te mande evidencia del funcionamiento.

**Comment by RigoFlores** [comment]
el complemento es incorrecto...

**Comment by jccastillo0007** [comment]
fixed. chiaaaa

**Comment by RigoFlores** [comment]
pues no, dime pls como lo generas paso a paso... a mí ni me lo incluye en el xml, y el pdf lo muestra como cualquier factura...
el ejemplo que mandaste el curp empieza con toma08, y ese rfc del alumno no existe...

**Comment by jccastillo0007** [comment]
estoy utilizando al alumno Abraham Alejandro Torres Mendoza, su curp empieza con toma08....
La factura debe  tener 1 solo producto
Debes poner la leyenda en información complementaria con la palabra mágica
Debes abrir la pantalla de datos extras a nivel general

y listo...

**Comment by RigoFlores** [comment]
ok.
