### ISSUE TITLE
Ampliar el rango de extra data general, de 30 a 80

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#119]
Hicimos pruebas con el están alon, y el jasper no truena, pero el facturat solo envía hasta 30 extra data.
Se requiere ampliar ese rango, ya que tenemos una factura prácticamente 'artesanal', debido a los datos tan distintos que lleva cada ocasión.

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
Sigue sin jalar... aquí tienes la salida del bat.....

2013-05-30 11:11:39,919 DEBUG [main](FacturaT.java:137) - Initializing FacturaT

2013-05-30 11:11:40,078 DEBUG [main](EmisorController.java:41) - we found the k
ey : facturaT_XAXX010101000_simple.cfdi
2013-05-30 11:11:40,171  INFO [main](EmisorController.java:88) - JSON KEY :{"ad
dress":{"country":"MEXICO","locale":"","municipio":"QUERETARO","name":"","neighb
ourhood":"LOS CEDROS","number_ext":"155","number_int":"-B","reference":"","state
":"QUERETARO","street":"AV UNIVERSIDAD","zipcode":"76150"},"cellPhone":"","colon
ia":"LOS CEDROS","country":"MEXICO","dateOfJoining":{"date":30,"day":4,"hours":1
7,"minutes":13,"month":7,"seconds":36,"time":1346364816745,"timezoneOffset":300,
"year":112},"email":"","features":[],"id":"XAXX010101000","localidad":"","munici
pio":"QUERETARO","name":"SU EMPRESA O PERSONA FISICA","name_contact":"","nextel"
:"","nextelId":"","number_ext":"155","number_int":"-B","phone1":"","phone2":"","
phone3":"","reference":"","rfc":"XAXX010101000","source":{"address":{"country":"
MEXICO","locale":"","municipio":"QUERETARO","name":"","neighbourhood":"LOS CEDRO
S","number_ext":"155","number_int":"-B","reference":"","state":"QUERETARO","stre
et":"AV UNIVERSIDAD","zipcode":"76150"},"cellPhone":"","email":"","name":"SU EMP
RESA O PERSONA FISICA","phone":"","rfc":"XAXX010101000"},"state":"QUERETARO","st
reet":"AV UNIVERSIDAD","type":"FACTURATi","zipcode":"76150"}
2013-05-30 11:11:40,304  INFO [main](EmisorController.java:105) - Type : FACTUR
ATi
2013-05-30 11:11:40,311 DEBUG [main](EmisorController.java:70) - Leyenda PDF :
ESTE DOCUMENTO ES UNA REPRESENTACION IMPRESA DE UN CFDI
2013-05-30 11:11:40,485 ERROR [main](FacturaT.java:197) - FILE NOT FOUND : C:\U
sers\Rijo\Documents\borrame\Factura-T.session.last
Exception in thread "main" org.springframework.beans.factory.BeanCreationExcepti
on: Error creating bean with name 'genericModelDao': Injection of autowired depe
ndencies failed; nested exception is org.springframework.beans.factory.BeanCreat
ionException: Could not autowire field: org.springframework.orm.hibernate3.Hiber
nateTemplate com.facturat.model.dao.GenericModelDao.hibernateTemplate; nested ex
ception is org.springframework.beans.factory.BeanCreationException: Error creati
ng bean with name 'hibernateTemplate' defined in class path resource [settings/d
ataLayer.xml]: Cannot resolve reference to bean 'sessionFactory' while setting b
ean property 'sessionFactory'; nested exception is org.springframework.beans.fac
tory.BeanCreationException: Error creating bean with name 'sessionFactory' defin
ed in class path resource [settings/dataLayer.xml]: Invocation of init method fa
iled; nested exception is org.hibernate.MappingException: class com.facturat.con
troller.connector.TUNION.CFD_Product_TUNION not found while looking for property
: id
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
ostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java
:283)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.populateBean(AbstractAutowireCapableBeanFactory.java:1055)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:450)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:287)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:189)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
preInstantiateSingletons(DefaultListableBeanFactory.java:557)
        at org.springframework.context.support.AbstractApplicationContext.finish
BeanFactoryInitialization(AbstractApplicationContext.java:842)
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:416)
        at com.facturat.view.FacturaT.loadContext(FacturaT.java:91)
        at com.facturat.view.FacturaT.<init>(FacturaT.java:49)
        at com.facturat.view.FacturaT.main(FacturaT.java:213)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not au
towire field: org.springframework.orm.hibernate3.HibernateTemplate com.facturat.
model.dao.GenericModelDao.hibernateTemplate; nested exception is org.springframe
work.beans.factory.BeanCreationException: Error creating bean with name 'hiberna
teTemplate' defined in class path resource [settings/dataLayer.xml]: Cannot reso
lve reference to bean 'sessionFactory' while setting bean property 'sessionFacto
ry'; nested exception is org.springframework.beans.factory.BeanCreationException
: Error creating bean with name 'sessionFactory' defined in class path resource
[settings/dataLayer.xml]: Invocation of init method failed; nested exception is
org.hibernate.MappingException: class com.facturat.controller.connector.TUNION.C
FD_Product_TUNION not found while looking for property: id
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
ostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.j
ava:504)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject
(InjectionMetadata.java:84)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
ostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java
:280)
        ... 13 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creati
ng bean with name 'hibernateTemplate' defined in class path resource [settings/d
ataLayer.xml]: Cannot resolve reference to bean 'sessionFactory' while setting b
ean property 'sessionFactory'; nested exception is org.springframework.beans.fac
tory.BeanCreationException: Error creating bean with name 'sessionFactory' defin
ed in class path resource [settings/dataLayer.xml]: Invocation of init method fa
iled; nested exception is org.hibernate.MappingException: class com.facturat.con
troller.connector.TUNION.CFD_Product_TUNION not found while looking for property
: id
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver
.resolveReference(BeanDefinitionValueResolver.java:328)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver
.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1305)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.populateBean(AbstractAutowireCapableBeanFactory.java:1067)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:450)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:287)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:189)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
findAutowireCandidates(DefaultListableBeanFactory.java:820)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
doResolveDependency(DefaultListableBeanFactory.java:762)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
resolveDependency(DefaultListableBeanFactory.java:680)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanP
ostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.j
ava:475)
        ... 15 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creati
ng bean with name 'sessionFactory' defined in class path resource [settings/data
Layer.xml]: Invocation of init method failed; nested exception is org.hibernate.
MappingException: class com.facturat.controller.connector.TUNION.CFD_Product_TUN
ION not found while looking for property: id
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1401)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:450)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:287)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:189)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver
.resolveReference(BeanDefinitionValueResolver.java:322)
        ... 28 more
Caused by: org.hibernate.MappingException: class com.facturat.controller.connect
or.TUNION.CFD_Product_TUNION not found while looking for property: id
        at org.hibernate.util.ReflectHelper.reflectedPropertyClass(ReflectHelper
.java:97)
        at org.hibernate.mapping.SimpleValue.setTypeUsingReflection(SimpleValue.
java:302)
        at org.hibernate.cfg.HbmBinder.bindSimpleId(HbmBinder.java:423)
        at org.hibernate.cfg.HbmBinder.bindRootPersistentClassCommonValues(HbmBi
nder.java:356)
        at org.hibernate.cfg.HbmBinder.bindRootClass(HbmBinder.java:295)
        at org.hibernate.cfg.HbmBinder.bindRoot(HbmBinder.java:166)
        at org.hibernate.cfg.Configuration.add(Configuration.java:702)
        at org.hibernate.cfg.AnnotationConfiguration.processArtifactsOfType(Anno
tationConfiguration.java:531)
        at org.hibernate.cfg.AnnotationConfiguration.secondPassCompile(Annotatio
nConfiguration.java:291)
        at org.hibernate.cfg.Configuration.buildMappings(Configuration.java:1148
)
        at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessi
onFactory(LocalSessionFactoryBean.java:717)
        at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPr
opertiesSet(AbstractSessionFactoryBean.java:211)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1460)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1398)
        ... 35 more
Caused by: java.lang.ClassNotFoundException: com.facturat.controller.connector.T
UNION.CFD_Product_TUNION
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.hibernate.util.ReflectHelper.classForName(ReflectHelper.java:123)

```
    at org.hibernate.util.ReflectHelper.reflectedPropertyClass(ReflectHelper
```

.java:93)
        ... 48 more
