### ISSUE TITLE
Web-Conector-Escritorio - no reporta correctamente la base del impuesto a nivel concepto en el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1190]
Cuando la cantidad es distinta a 1, no lo reporta correctamente.
Recordar que por lo pronto la base es el importe - monto descuento.
Ahora mismo está reportando el precio unitario

**Comment by RigoFlores** [comment]
lo reportaste como corregido en el skype, pero sigue apareciendo incorrecta la base en el PDF.
La base la estás enviando correctamente al XML, a nivel producto, ya que en otro caso tronaría.
Pues ese dato es el que debes enviar al PDF.

**Comment by jccastillo0007** [comment]
te mando evidencia...

**Comment by RigoFlores** [comment]
no he recibido nada.... hoy lo reconfirmé (la falla)... a menos que haya sido corregido... de hecho me di cuenta con un cliente en producción...

**Comment by RigoFlores** [comment]
Escritorio -web - conector...

sigue el problema cuando la cantidad es mayor que uno... te enviaré evidencia por correo

**Comment by jccastillo0007** [comment]
fixed.
