### ISSUE TITLE
Navision 3.3 - cuando existe un error en el timbrado, agregarlo a la tabla estado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1191]
Para facilitar el debugueo, se ocupa que en la tabla estado, cuando se genere un error al momento del timbrado, que se almacene cuál fue dicho error.

**Comment by jccastillo0007** [comment]
Este es un cambio grande... ya que la app no esta lista para guardar en base de datos el resultado de timbrado... eso se manda al log...  si guarda un tipo de error genérico dependiendo en que parte del proceso suceda.. y lo guarda con código 3.

**Comment by jccastillo0007** [comment]
Si es necesario, puedo hacer los cambios necesarios, pero sería hasta el final, ya que por ahora esta complicado.

**Comment by RigoFlores** [comment]
La idea sería para que ellos mismos pudieran debuguear, pero si podría quedar al final.
Lo que no quedaría al final, son los datos generales del CFDI cuando fue timbrado exitosamente.
