### ISSUE TITLE
Conector 3.3 - cuando incluye descuento y el iva es exento, manda incorrecto el total al pdf

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1194]
Son casos muy particulares. Lo está probando el nuevo cliente... y si que lleva 2 fallas encontradas, ya que está aplicando pinches casos de prueba raros...

**Comment by RigoFlores** [comment]
mañana se va a pro, el cliente que descubrió este issue.

**Comment by jccastillo0007** [comment]
Esto ya lo revisamos por email... deben mandar el total correcto en el txt
