### ISSUE TITLE
Conector - web - escritorio ; modificar la base para impuestos locales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1195]
Ya lo ocupamos para constructoras.
Te comentaba en un correo, que en general la base se podría requerir modificar UNICAMENTE para calcular los impuestos locales. 
Pero si en lugar de dar la opción de modificar la base, mejor capturamos como datos extra a nivel producto, los campos requeridos para los reportar los impuestos locales, que generalmente siempre son retenidos.

Tipo: retenido por omisión; podríamos no dar la opción de cambiar (hard code).
Nombre: nombre de impuesto local
Monto: monto de impuesto (se resta al total de la factura estándar)
tasa: es la tasa para reportar al complemento de impuestos locales.

Así es el complemento que nos falta para impuestos locales:

        <implocal:ImpuestosLocales xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" TotaldeRetenciones="1791.96" TotaldeTraslados="0.0" version="1.0" xsi:schemaLocation="http://www.sat.gob.mx/implocal http://www.sat.gob.mx/sitio_internet/cfd/implocal/implocal.xsd">
            <implocal:RetencionesLocales ImpLocRetenido="5 al millar" Importe="1791.96" TasadeRetencion="0.5"/>        </implocal:ImpuestosLocales>

Cómo la bestia?

**Comment by RigoFlores** [comment]
incluso no como datos extra, sino algo así como se captura el predial o el número de aduana.
Que se pudieran capturar 3 datos para los impuestos locales:
Nombre
Monto
Tasa

Cuando se capturan, se incluye el complemento de impuestos locales (retenidos), y además el monto se resta al total de la factura.

**Comment by RigoFlores** [comment]
Te la voy a poner mas fácil aún...
Se define el producto
ID. ImpLocRet1
Descripcion: 5 al millar
Precio Unitario: el monto del impuesto
Tasa: unidad o clave de unidad SAT

Cuando se agregue a una factura, se entiende que se quiere agregar impuestos locales, y el monto de este producto se resta al total... cómo la bestia???... chacarra pero jalador, que no???

**Comment by jccastillo0007** [comment]
esto ya lo estoy probando en web... espero que hoy ya quede listo...

**Comment by RigoFlores** [comment]
tenemos varios formados.
En escritorio y en web..

**Comment by jccastillo0007** [comment]
Listo... ya esta funcionando.
Usage:
El producto debe tener como :  
id = ImpLocal
nombre del producto debe ser exactamente uno de los impuestos locales que tenemos dados de alta en el sistema
descripción = Trasladado o Retenido tal cual
aunque no se ocupan, hay que capturar clave sat, moneda y unidad para poder guardar el producto

En la pantalla de facturación, se elige el producto ImpLocal y se captura de la siguiente manera:
cantidad = total del impuesto
valor unitario = tasa del impuesto

EL usuario ACO.. ya tiene dos productos con facha de ImpLocales, pueden ser trasladados o retenidos, y se pueden incluso incluir ambos en una factura..

Todo esto en web.

**Comment by RigoFlores** [comment]
ESTÁN PENDIENTES UN PAR DE PUNTOS, Y SOLO JALA PARA WEB.
LO CERRARÉ PARA ABRIRLOS APARTE
