### ISSUE TITLE
Navision DRP - no está incluyendo la fecha de pago en el complemento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1197]
Al menos lo que arroja en la consola, no se si después se asigne, ya que se timbra.

**Comment by RigoFlores** [comment]
hay que concluir este asunto, ya está generando el XML con el complemento, pero falta leer las montos correctamente, y supongo que volverá a brincar este tema de la fecha

**Comment by jccastillo0007** [comment]
done.
