### ISSUE TITLE
Navision 3.3 DRP -  marca errro al timbrado, creo yo porque no se reporta el nodo de docto relacionado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1198]
Cuadré los datos para que timbrara, pero está enviando esto:

[code=003,description=La suma
de los valores registrados en el campo ImpPagado de los apartados DoctoRelaciona
do no es menor o igual que el valor del campo Monto.]

No sé, si porque está reportando negativo en el importe pagado, o ahora ya está validando que se reporte el CFDI que se está pagando.

**Comment by RigoFlores** [comment]
está reportando cantidades negativas de pagos
Importe Saldo Anterior
Importe Pagado
Importe saldo insoluto

son los campos que se reportan a nivel detalle.

Monto o importe del Pago es el que se reporta a nivel general.

Según yo, estás haciendo cálculos o cambiando de signo las cantidades

**Comment by jccastillo0007** [comment]
puedes checar si los datos están bien en la base de datos ?

JC.

**Comment by jccastillo0007** [comment]
oye, nota de crédito y factura ya están ok ?

**Comment by RigoFlores** [comment]
no hay que mezclar cosas. Aquí es DRP. Si he logrado timbrar factura y nota, pero acomodando datos. Mañana tengo una sesión de pruebas con los españoles.

De pago, como aquí dice:
a) En el XML que muestra en consola, no se incluye la fecha del pago
b) está haciendo algunos cálculos que no debería. Hay que tomar simplemente la información.
c) Cuando el campo de número de pago es 0, indica que se pagó completa la factura.
d) creo que lo que falta definir, es cuando un pago afecta o aplica a varias facturas. Supongo que se necesita un campo llave para ello. Hoy si buscar por lo que  tienen estado=0, se intenta procesar el pago, pero no se está prestando atención si es una sola o varias facturas relacionadas al mismo pago. Creo yo por la referencia es que nos guiaremos a buscar. Esto es, si encuentras estado=0, luego buscas todas las de estado=0, con la misma referencia, y esas serían las facturas relacionadas al mismo pago.

**Comment by RigoFlores** [comment]
Los datos de cantidades en la BD, hoy en día existen algunos en negativo y otros positivo.
Pediré que todos sean positivos, y así simplemente los tomamos.
Nosotros no necesitamos hacer ningún cálculo, ya que todo está en la tabla. Entiendo que si se están haciendo cálculos.

**Comment by jccastillo0007** [comment]
fixed con sus asegunes.
