### ISSUE TITLE
Escritorio 3.3 - no funciona traslado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1199]
Eliges traslado, y con un producto con precio 0, como debe ser, y te manda el error 

2017-11-15 18:18:18,280  INFO [AWT-EventQueue-0] (CFDiWSClient.java:77) - Factur
aTi ack : com.facturati.ws.binding.jaxb.Ack@67b7c8[code=003,description=El valor
 del campo ValorUnitario debe ser mayor que cero (0) cuando el tipo de comproban
te es Ingreso, Egreso o Nomina]
2017-11-15 18:18:18,282 DEBUG [AWT-EventQueue-0] (CFDiWSClient.java:79) - Proper
ties received : CFDi_FOLIO value : 2956

**Comment by RigoFlores** [comment]
es decir, el traslado lo trata como ingreso

**Comment by jccastillo0007** [comment]
oye, estoy confundido,... si el precio es cero, pues el total va ser cero y el traslado es egreso... tons ya no entendí, puedes ser más explícito.

**Comment by RigoFlores** [comment]
egreso me refiero a carta porte.
En egreso todo tiene que ir con cero, pero si te das cuenta en el error, en lugar de mandar el tipo 'E', lo manda como 'I'
En resumen, un carta porte (tipo T), lo envía como si fuera factura (tipo N).

**Comment by jccastillo0007** [comment]
Con la versión de hoy, ya procesa el tipo de documento = T, peeeero no logre timbrar una factura, pues me marca xml inválido cuando el producto va en 0, tal vez me esta faltando algo mas... puedes checarlo.

**Comment by RigoFlores** [comment]
SI TIMBRA, SOLO HAY QUE CAPTURAR LOS VALORES CORRECTOS.
LO QUE SI ESTÁ FALTANDO, ES FORMATEE EL DATO EXTRA 1 Y 2, COMO LO HACIA ANTES, ESTO ES PARA LOS TIPO DATOS EXTRA TIPO CLIENTS. 
POR LO PRONTO ES LO ÚNICO QUE LE DETECTÉ.

    <field>
      <tag>Remitente</tag>
      <name>remitente</name>
      <type>CLIENTS</type>
      <length>120</length>
    </field>
    <field>
      <tag>Destinatario</tag>
      <name>destinatario</name>
      <type>CLIENTS</type>
      <length>120</length>
    </field

**Comment by jccastillo0007** [comment]
El emisor debe tener el plugin de carta porte en la licencia, para que se haga el formato correcto de los datos extras tipo Client.

**Comment by RigoFlores** [comment]
OK, lo voy a hacer ... sin embargo, ese candado ya no es necesario para carta porte... nosotros configuramos todo, plantilla, datos extra, etc... no debería ser un requisito ese plugin..
