### ISSUE TITLE
Pantalla factura - Permitir edición Método de Pago, además de la lista por omisión

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#12]
Metodo de pago, debe ser editable
El folio a utilizar muestra 0 cuando deberia ser 1, (en un rango de folios nuevo)

**Comment by jccastillo0007** [comment]
Resolved : El folio a utilizar muestra 0 cuando deberia ser 1, (en un rango de folios nuevo)

**Comment by RigoFlores** [comment]
EL METODO DE PAGO EDITABLE, OK.
EL FOLIO LO SIGUE PRESENTANDO INCORRECTO, Y NO LO PUDE VERIFICAR EN LA FACTURA, YA QUE NO LA PUEDE GENERAR

**Comment by jccastillo0007** [comment]
Solo hay detalles con los folios, lo tenemos que platicar para que nos entendamos...

**Comment by RigoFlores** [comment]
LO QUE DEBE SER EDITABLE, ES LA LISTA DESPLEGADA DEL METODO DE PAGO. ES DECIR, AÚN CUANDO SE PRESENTAN LAS OPCIONES MAS REQUERIDAS, EVENTUALMENTE ALGUN CLIENTE SOLICITA POR EJEMPLO "TRANSFERENCIA ELECTRÓNICA", "TRANSFERENCIA ELECTRONICA DE FONDOS", O ALGUNA OTRA FUMADA QUE LE EXIGE SU CONTADOR O CLIENTE.

**Comment by jccastillo0007** [comment]
Deprecated.
