### ISSUE TITLE
Soportar Carta porte desde el conector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#120]
Hoy la especificación indica:
CAMPO1:
tipoDeComprobante=3
0. Factura Comercial
1. Nota de Cargo
2. Nota de Crédito
3. Recibo de Honorarios
4. Recibo de Arrendamiento

Por lo tanto, al Carta Porte, le corresponde:

tipoDeComprobante=5

**Comment by RigoFlores** [comment]
Por cierto, el único cambio real, es que el tipo de comprobante en el XML, debe ser traslado, en lugar de ingreso o egreso.

**Comment by jccastillo0007** [comment]
El comprobante Carta Porte ya es soportado ..... chaaaaa

public enum CFD_TYPES {
    FACTURA ("FACTURA", 0, "ingreso"),
    NOTA_CARGO ("NOTA DE CARGO", 1, "ingreso"),
    NOTA_CREDITO ("NOTA DE CREDITO", 2, "egreso"),
    HONORARIOS ("RECIBO DE HONORARIOS", 3, "ingreso"),
    ARRENDAMIENTO ("RECIBO DE ARRENDAMIENTO", 4, "ingreso"), 
    DONACIONES ("RECIBO DE DONATIVOS", 6, "ingreso"),
    CARTA_PORTE ("CARTA PORTE", 8, "traslado");

tipoDeComprobante=8
