### ISSUE TITLE
Conector 3.3 - implementar CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1200]
Esta implementación la dejaremos prácticamente del lado del cliente.
Estoy definiendo un layout con tooodos los posibles datos que puede incluir el complemento, separados por |, y en renglones distintos por header, nodo, o elemento.

Se tratará simplemente de tomar lo que venga, y acomodarlo en el complemento.
En cuanto tenga el layout del texto, te lo envío.

**Comment by RigoFlores** [comment]
Ya te mandé el correo, lo están esperando desde hace semanas... tuvimos que priorizar, pero ahora ya les urge...

**Comment by jccastillo0007** [comment]
Actualizarlo en web a 3.3 es mas o menos sencillo, pero en standalone no existia este complemento, eso no es tan sencillo/rápido.

**Comment by jccastillo0007** [comment]
Cuales son los cambios necesarios para soportar este complemento en web con cfdi3.3 ?

**Comment by RigoFlores** [comment]
Incluir los domicilios del emisor y receptor DENTRO DEL COMPLEMENTO, y cumpliendo con las claves de municipios, estados, país, etc, como corresponda.
Deja revisar mas a detalle, está medio confusa su guia de validaciones para una versión y otra

**Comment by RigoFlores** [comment]
Pero en el conector, solo es tomar los datos que se reporten en el txt, y pasarlos a la estructura XML.

**Comment by jccastillo0007** [comment]
listo, con la version de hoy ya puedes empezar las pruebas, la licencia debe tener los plugins de datos extras y addendas.

**Comment by RigoFlores** [comment]
te mandé un correo, de manera inicial no hizo nada con la info del CCE

**Comment by jccastillo0007** [comment]
ya esta agregando el CCE, pero marca error de datos.. pide la clave de un pais cuando si se esta agregando... tal vez sea el ambiente de pruebas de finkok.. checale haber si le encuentras algo.

**Comment by RigoFlores** [comment]
ya lo subiste?

**Comment by jccastillo0007** [comment]
ya, se acaba de terminar de subir... termina en _4.zip

**Comment by RigoFlores** [comment]
NO SE PUEDE TIMBRAR... MARCA UN ERROR... QUE HACEMOS?

**Comment by jccastillo0007** [comment]
pues pensé que tu tendrías datos validados... supongo que hay que probar en producción, porque el error que manda finkok en pruebas es inconsistente.

**Comment by RigoFlores** [comment]
probé de todas maneras que pude, y no jaló nunca... es probable que finkok no jale con eso... montar un ambiente de producción tendrá que ser con la tia, mañana lo hago

**Comment by jccastillo0007** [comment]
que petch con este ticket...

**Comment by RigoFlores** [comment]
pues ya hizo crisis, el cliente dice que tiene un contenedor detenido ya en el barco... tsss
Lo que veo es que el error que manda es:
    <cfdi:Receptor Rfc="XEXX010101000" Nombre="COPPEL, S.A. DE C.V. ." UsoCFDI="
G03"/>

2018-01-30 17:01:03,962  INFO [pool-2-thread-1] (CFDiWSClient.java:77) - Factura
Ti ack : com.facturati.ws.binding.jaxb.Ack@3157a8[code=003,description=Se debe r
egistrar un valor de acuerdo al cat├ílogo c_Pais en en el campo ResidenciaFiscal
, cuando en el en el campo NumRegIdTrib se registre informaci├│n.]

Aquí la condición es que el campo de residencia fiscal, se debe incluir en el XML estándar, nodo receptor, cuando se incluye el CCE. Eso es obligatorio. Al menos eso es lo que está enviando por el momento.
URGE ATENDER ESTE ISSUE...

**Comment by RigoFlores** [comment]
mandé un correo con lo que hace falta componer del CCE por conector, hoy me volvió a marcar el de finanzas, que para cuando?

**Comment by RigoFlores** [comment]
según yo lo que falta, de lo que tenemos actualmente es... que en los datos del receptor, cuando se trata del RFC XEXX010101000, tiene que incluir el pais de residencia y el numregid:

    <cfdi:Receptor Rfc="XEXX010101000" Nombre="00178801 - ELICEO PLEITEZ PREZA" ResidenciaFiscal="SLV" NumRegIdTrib="06171406360018" UsoCFDI="G01"/>

**Comment by RigoFlores** [comment]
NO ESTÁ PROCESANDO MAS DE 1 PRODUCTO SIMULTÁNEAMENTE...

**Comment by jccastillo0007** [comment]
Fixed.

Habia un problema al parcer el id del segundo elemento de las mercancias.
