### ISSUE TITLE
Conector 3.3 - ajustar addenda coppel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1201]
Esta addenda ya la tenemos implementada por conector.
Solo que toda la información que es un chingo, se enviaba como datos extra.
Me parece que son como 24 datos o por ahí.
Dado que limitamos el número de datos extra máximo a 20, esta addenda tendrá que llevar otra etiqueta dentro del archivo de texto.

En lugar de 
CA=||||||||||....||||

que sea:
AddCoppel=||||||||||....||||

No se si internamente eso pegue por los datos extra que ahora ya no serian datos extra, de hecho no sé como los trata internamente la aplicación

Esta addenda se acompaña de datos extra a nivel producto, eso si permanece igual, no tuvo afectación.

**Comment by RigoFlores** [comment]
EL CLIENTE ME ENVÍA VARIOS CORREOS DIARIOS... TE MANDÉ UN TEXTO DE CÓMO SE ENVÍAN AHORA LOS DATOS EXTRA GENERALES Y PRODUCTO, PARA QUE SE GENERE LA ADDENDA

**Comment by jccastillo0007** [comment]
ya esta jalando.

aunque no hice nada en realidad.

**Comment by RigoFlores** [comment]
era cuestión de colocar los datos correctos, para lo que pedí archivos de la vida rial... pero no los pude probar porque no tenía versión de conector estándar.
Ya lo validé con versión de conector adecuada, generó addenda, no sé si correctamente pero en estructura parace que sí.
