### ISSUE TITLE
Escritorio 3.3 tiene fallas con la vista previa y datos extra.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1202]
Cada ocasión que le das vista previa, te incrementa 2 ceros en la tasa del iva
Sin haber capturado información extra, el  datoextra1 y el 2, contienen una cadena con variables o datos internos a la aplicación. Aparentemente estás ocupando los datos extra para otra cosa...

Si capturas un dato extra general, la aplicación truena, es decir ya no timbra, aunque te cambies de pantalla, y captures nuevamente la factura, ya no vuelve a jalar.

**Comment by RigoFlores** [comment]
al parecer es simplemente si invocas a la vista previa, se modifica el valor de la tasa del impuesto

**Comment by jccastillo0007** [comment]
Los datos extras no tienen nada que ver, en realidad el problema era la vista previa al ejecutarse n veces.

**Comment by RigoFlores** [comment]
hay que subirlo ya, si lo subes a medianoche, hasta mañana se puede probar, y si nos va bien todo jala, si tiene otro problema, un día mas aguantando a los clientes

**Comment by RigoFlores** [comment]
yo creo que hay que homologar... en web la vista previa envía el 16.0 %
en escritorio envía 0.16%... lo cual es un error en  automático para todas las plantillas en escritorio

**Comment by RigoFlores** [comment]
quedó apuntando al conector de navision, pero ni pedo... se va así... 
ya actualicé varios...

**Comment by RigoFlores** [comment]
NUEVAMENTE, CADA OCASIÓN QUE LE DAS VISTA PREVIA, MULTIPLICA POR 100 LA TASA DEL IVA.
IGUAL QUE LA OCASIÓN ANTERIOR, HOY CONFIGURÉ VARIOS CON ESTA VERSIÓN...

**Comment by jccastillo0007** [comment]
Fixed... cuando arreglé lo de impuestos locales en vista previa, me llevé de corbata ese fix... sorry.

**Comment by RigoFlores** [comment]
Si que es un cagadero...
Para una factura estándar ya jala todo ok... no importa si le das pinche mil veces a la vista previa...
Ahora se descompuso nuestro approach de impuestos locales, cuando le das vista previa, aunque sea una sola ocasión, truena nuevamente el tema de la tasa del IVA... ahora no la incrementa, ahora la disminuye... jajaja

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
no veo ningún nuevo rilís...

**Comment by jccastillo0007** [comment]
Lo subi el día 12/7

**Comment by RigoFlores** [comment]
El problema persiste.
En una factura estándar, no tiene problema... funciona todo bien.

El problema, como se reportó, es con los impuestos locales.
Cuando capturas una factura con impuestos locales, con el approach de producto 'impuesto' o 'chacarra' funciona bien si no le das vista previa. Una vez que le das vista previa, ya no reporta los impuestos locales al XML. Tienes que darle editar siempre al final al producto chacarra para que si lo incluya en los XML.

Si no queda claro, pregúntame k, pregúntame kkk

**Comment by jccastillo0007** [comment]
checale, según yo ya esta... yo ya pude hacer varias veces vista previa y luego facturar, y si incluye el complemento.
