### ISSUE TITLE
CxC - marca internal error cuando solicitas la cartera por cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1204]
lo intenté en 3.2 y 3.3, y se comporta igual
apliqué el filtro de vigentes mas vencidas de manera inicial marcó error; también después le agregué el filtro de fecha inicial, y el error fue el mismo

**Comment by jccastillo0007** [comment]
Con que cliente de la TIA lo puedo probar ?

**Comment by jccastillo0007** [comment]
no encuentro uno que me reproduzca el error.

**Comment by RigoFlores** [comment]
solo hay 2 clientes que ocupan esto, optibelt y la tia
Yo lo intenté con la cuenta de la tia en producción...

**Comment by jccastillo0007** [comment]
si, ya se eso, pero cuando entras a cartera por cliente, que cliente eliges ? (con el usuario de la tia)..?

**Comment by RigoFlores** [comment]
no, ninguno... como dice al inicio, solo apliqué el filtro de vigentes+vencidas, junto con el de fechas...
así lo hacía siempre... y es para conocer cuáles facturas no se han pagado por ejemplo, a partir de noviembre...
Si se ocupa... y se puede restringir a un rango de fechas máximo, así como el banco de unos 6 meses o cosa por el estilo

**Comment by jccastillo0007** [comment]
es que no lo pude reproducir... no me marco ninguna excepción, por eso creí que había que elegir un cliente en particular

**Comment by RigoFlores** [comment]
lo acabo de hacer nuevamente entrando con la tia.

Menú Cuentas x Cobrar - Cartera por cliente
Fecha inicial : 01 nov
Filtro: vigentes + vencidas

Resultado internal error. Si le doy regresar con la flecha del navegador, me lleva al resultado de la consulta.

**Comment by jccastillo0007** [comment]
fixed... era error de datos en PRO... ya lo arreglé... fue un defecto que se quedo por ahi ahora que subimos todas las facturas a web...
