### ISSUE TITLE
Escritorio 3.3 - datos extra + vista previa marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1206]
Si capturas una factura, luego capturas algún dato extra general... y luego le das vista previa y cierras la vista previa, marca error en al consola, y ya no facturará, ni timbrará mas en esa sesión. Tienes que salir y volver a entrar.

Si capturas la factura, le das vista previa y la cierras, y luego capturas el datos extra.... y le das facturar, ahí si trabaja sin problema.

**Comment by jccastillo0007** [comment]
No lo pude reproducir, a mi si me funcionó
Si lo puedes reproducir con la última versión de dropbox... pásame el log puede haber algo en los datos capturados

**Comment by RigoFlores** [comment]
los pasos son así:
a) capturas la factura normalita
b) capturas algun dato extra
c) le das preview y cierras 
d) le das facturar

en ese momento si genera la factura correctamente.
si repites el proceso ya valió madres, y nunca puede volver a timbrar en esa sesión, aun cuando solo ya no captures datos extra.

**Comment by RigoFlores** [comment]
YA TE MANDÉ EL PROCEDIMIENTO PARA QUE LO REPRODUZCAS

**Comment by jccastillo0007** [comment]
fixed.

Era una consecuencia de las chacarronadas que hemos hecho...

Espero que no surjan mas..

**Comment by RigoFlores** [comment]
tiene 2 detallitos, que cuando puedas hay que atender:
en la vista previa, las tasas de impuesto las manda como 0.16 por ejemplo, pero cuando lo timbra lo pone como 16.0 (en el pdf)
antes, si no tenías archivo de extrafields, te abría una ventana genérica y ahí capturabas tus datos extra; ahora lo sigue haciendo, pero lo que capturas ahí ya no lo pela como dato extra. Bueno o malo, no lo sé, pero no vaya a romper algo. Quizás solo valida porque dejó de jalar eso y lo dejamos así como está.
