### ISSUE TITLE
Imp Locales 3.3 web - no amarrar el nombre del 'producto' a impuestos ya definidos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1209]
Hoy estamos atascados de impuestos que no sabemos quién los ocupa, si se ocupan o no.
Lo mas limpio, sería que el nombre fuera libre captura.
Que paguen el feature de imp locales. Sobre todo los clientes nuevos.

**Comment by jccastillo0007** [comment]
Esto si le pega a muuuuchas cosas... en Web los impuestos deben existir en nuestro catálogo.
