### ISSUE TITLE
Imp Locales 3.3 web - enviar los totales de impuestos locales al pdf

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1210]
Por lo pronto solo tenemos una variable general que corresponde a los impuestos locales.

Solo se ocupa enviar el total de retenidos.

**Comment by jccastillo0007** [comment]
ya se estan enviando... y se tienen variables hasta para 5 impuestos locales.

**Comment by RigoFlores** [comment]
en cuanto a variables de impuestos locales al web, se cumple y se cierra.
Los totales de la factura en pantalla, preview y pdf timbrado, están chuecos, ya que consideran los montos de los productos chacas
