### ISSUE TITLE
Imp Locales en escritorio 3.3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1211]
Implementar la misma estrategia chaca pero super efectiva... tssss

**Comment by jccastillo0007** [comment]
listo.

**Comment by jccastillo0007** [comment]
El uso en standalone de impuestos locales es :

1. El producto debe tener ImpLocal como id, y de nombre lo que sea

2. Cantidad y valor unitario se usan igual que en web

3. En el caso de standalone, no hay descripción del producto a nivel catálogo.. tons... en la pantalla de agregar producto, la descripción complementaria debe ser Trasladado o Retenido

4. Debe tener datos extras y addendas como plugin...

5. Ya no se usa el plugin de complemento de impuestos

**Comment by RigoFlores** [comment]
Lo cerraré por la parte del XML quedó muy bien.
Pero abrí otro por la parte de pantalla y sobre todo y mas importante, vista previa y pdf timbrado
