### ISSUE TITLE
Imp Locales 3.3 web - reflejar en pantalla y en el pdf lo mismo que en el XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1212]
Ya no muestra el producto del impuesto local en el PDF, pero todo lo demás quedó chueco:

a) totales está incluyendo el producto 'del impuesto', es decir si lo manda a los totales, tanto en el preview, como en el PDF ya timbrado.
b) cuando agregar el producto impuesto y regresas a la pantalla de facturación, ahí si muestra dicho producto, amén de que los totales e impuestos en pantalla los muestra como si fuera un producto normal.

El a es indispensable, el b podría alivianarse un poco resolviendo el a, pero ideal resolver los 2.

**Comment by jccastillo0007** [comment]
ya esta funcionando como se espera... 
de hecho el total en el pdf contempla el impuesto local.. pero no se muestra como producto... y muestra la misma cantidad que se manda al XML cuando si se timbra, es decir, se hacen los calculos necesarios y el total si se ve afectado por el impuesto local como debe ser...

**Comment by RigoFlores** [comment]
Lo que comentaba, que es muy importante es que en la vista previa no se muestra el total correctamente, ya que suma el importe del producto impuesto.
Esto me ha detenido en entregar este múdulo

**Comment by jccastillo0007** [comment]
Pues eso esta bien si es un impuesto Trasladado, si fuera un impuesto Retenido, le resta el importe del total, eso es tal cual lo que se hace en el XML... no entiendo bien que es lo que se solicita..

**Comment by RigoFlores** [comment]
que en la vista previa... el total considere restar (o sumar) el impuesto local.... igualito como el PDF ya timbrado... pero ahora mismo muestra el total sumando los importes, incluso del producto hechizo

**Comment by RigoFlores** [comment]
el problema es la vista previa... el total no refleja los impuestos locales retenidos igual que en el PDF ya timbrado

**Comment by jccastillo0007** [comment]
no manches.... el problema del pdf no era solo en vista previa, incluso en la factura, el pdf salia mal en el total chiaaa, y yo que estaba buscando el problema solo en vista previa.
