### ISSUE TITLE
Imp Locales escritorio 3.3 - reflejar en pantalla y pdf lo mismo que el XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1213]
Se repite la historia que en web, en el PDF vista previa o ya timbrado, los totales incluyen el producto hechizo de impuestos. 
También en pantalla, pero por lo menos en el PDF vista previa y ya timbrado, debe reflejar lo mismo que el XML

**Comment by jccastillo0007** [comment]
Esto ya esta funcionando, dejame subir lo que tengo al dropbox, porque ya no me acuerdo cuando lo subi por última vez.

**Comment by RigoFlores** [comment]
Si, realmente quise decir en vista previa.
El PDF timbrado si muestra el total correcto, pero la vista previa no.
Al menos la vista previa debe reflejar los totales correctamente. Ya me comentaste que en la pantalla sería muy complicado

**Comment by jccastillo0007** [comment]
te mando por correo un ejemplo de vsita previa.

**Comment by RigoFlores** [comment]
una vez capturada la factura correctamente:
Si le das vista previa y luego timbrar, no incluye el complemento.
Si le das timbrar si lo hace.
Si le das vista previa, y luego te metes a editar el producto chaca, entonces si lo hace.

Se está perdiendo algo por ahí...

ya quedó para web igual?

**Comment by jccastillo0007** [comment]
listo.

**Comment by RigoFlores** [comment]
no tengo ninguna versión nueva... la última es del 27 y si tiene ese problema

**Comment by jccastillo0007** [comment]
Crap... no la subi...
