### ISSUE TITLE
Web 3.3 - no envia correctamente el total de la suma de IVAs

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1214]
Cuando todos los productos tienen la misma tasa, debe enviar en la variable siguiente, la sumatoria del iva de todos los productos

montoTrasladoIva1   (existen 3 grupos de variables, considerando que en la misma factura puedan manejar distintas tasas del IVA)

Sin embargo está enviando el IVA correspondiente únicamente al producto 1.
Se muestra incorrecto en el PDF, cuando la factura contiene mas de 1 producto.

**Comment by jccastillo0007** [comment]
fixed.
