### ISSUE TITLE
Nomina - completar el catálogo de bancos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1216]
Para nómina...

**Comment by jccastillo0007** [comment]
El catálogo tiene mas de 100 registros... pide el o los bancos que les hace falta y agregamos esos.

**Comment by RigoFlores** [comment]
MULTIVA

**Comment by jccastillo0007** [comment]
done.

Pru y Pro... se esta subiendo justo ahora

**Comment by RigoFlores** [comment]
oyes, pero si le asignaste el código de banco que le corresponde????

**Comment by jccastillo0007** [comment]
Simon.
