### ISSUE TITLE
Conector 3.3 - Modificar addenda coppel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1218]
Con los cambios en el layout, nos llevamos por las patas un dato que se iba a la addenda.
Esto es el nodo:

a.11.10.2 | netAmount |
a.11.10.2.1 | Amount |   | Decimal | R | Importe neto de la línea   de artículo    Importe neto =(Cantidad * Precio Bruto   Unitario)  – Descuentos | 
**_SUBTOTAL (TOMADO DEL LAYOUT DEL CONECTOR A NIVEL   PRODUCTO)_**

Ese dato es cantidad*importe-descuento

Digamos que es el equivalente a la base en el cálculo del IVA.

**Comment by jccastillo0007** [comment]
done.
