### ISSUE TITLE
Conector 3.3 - se bloquea con ventanas modales en caso de error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1219]
Se le tiene que dar aceptar para que continúe el procesamiento.
En el caso de figueacero por ejemplo, es un gran problema ya que esa pantalla nadie la está revisando normalmente.

Hace tiempo se solicitó que PARA EL CONECTOR no se muestren esas ventanas.

OJO. para escritorio si se requieren.

**Comment by jccastillo0007** [comment]
Ya agregué el RFC de figueacero.

**Comment by RigoFlores** [comment]
Yo no puede probarlo.
Se tiene que hacer lo mismo para los españoles, recuerda que ahí si es totalmente ciego el proceso, no tiene pantalla..
