### ISSUE TITLE
NO PERMITE EDITAR O ELIMINAR EL PRIMER REGISTRO EN CATALOGO DE FOLIOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#122]
EN CATÁLOGO DE FOLIOS, NO PERMITE EDITAR O ELIMINAR EL PRIMER REGISTRO. 
AÚN CUANDO EXISTAN VARIOS REGISTROS, EL PRIMERO NO LO PERMITE EDITAR.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
LO PROBÉ EN PRU Y EN PRO, Y SIGUE IGUAL.
