### ISSUE TITLE
DRP PRUEBAS - MARCA ERROR DE JASPER AL TIMBRARLO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1220]
NO SÉ SI EN PRODUCCIÓN HAGA LO MISMO...
SI ESTÁS INCLUYENDO LA PLANTILLA EN PRU Y PRO?

**Comment by jccastillo0007** [comment]
Pues ahora resulta que no encuentro ninguna plantilla cfdi_pagos33.jrxml... ni en PRO ni en PRU...
Lo que hace es buscar una plantilla en el folder de cada cliente, que contenga este nombre " cfdi_pagos33_" + rfc + ".jrxml"; si no existe, entonces busca en el folder genérico la plantilla cfdi_pagos33.jrxml , pero dicha plantilla no esta ni en PRU ni en PRO, ni en el folder de la TIA...

**Comment by jccastillo0007** [comment]
Tons pues pasame la mentada plantilla genérica para subirla... y para los clientes que ya la necesiten, solo ponle este nombre :  

cfdi_pagos33_" + rfc + ".jrxml"; 

y subela a su configuración y listo

**Comment by RigoFlores** [comment]
OJO, no hay que empezar a manejar distintos nombres para el formato genérico de plantillas.
En escritorio se llama cfdi_pago33.jrxml, y así hay que buscarlo/llamarlo en web.
Ya te envié nuevamente la plantilla.

**Comment by RigoFlores** [comment]
y sigue marcando error... hay que corregir lo de la nomenclatura...
