### ISSUE TITLE
PRODUCCION WEB 3.3 - ERROR EN VISTA PREVIA ESTÁNDAR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1221]
No está enviando clave de producto, ni clave de unidad, tampoco el uso del CFDI que se eligió en pantalla.

Al momento de timbrar lo hace bien, pero mientras tanto en la vista previa se presenta chueca la info y causa confusión al usuario

**Comment by jccastillo0007** [comment]
done. en PRU y PRO

**Comment by RigoFlores** [comment]
EN PRO ACABO DE CHECAR Y SIGUE IGUAL...

**Comment by RigoFlores** [comment]
EN PRU TAMPOCO...
