### ISSUE TITLE
Optibelt 3.3 - están fijas las claves de producto y unidad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1222]
Las claves del sat de producto, se deben asignar de acuerdo al listado que te envié anteriormente.
Las claves de unidad, básicamente son las correspondientes a Pz y Mt, es decir pieza y metros, es decir H87 y MTR

**Comment by jccastillo0007** [comment]
Ya estan las unidades, solo faltan las claves de productos.

**Comment by jccastillo0007** [comment]
Listo, ya están también los productos de acuerdo a su catálogo.

**Comment by RigoFlores** [comment]
no los está parseando correctamente. Envié un correo con la evidencia...

**Comment by jccastillo0007** [comment]
Haber checale con la versión de hoy... estaba esperando la cadena tal cual el catálogo, es decir, en mayúsculas...

Pero ahorita ya le vale si es mayúsculas o minúsculas.

Ojo.. en tu ejemplo la clave estaba mal, peeeero una vez corregido el defecto, aún asi se despliega una sola clave, todos los productos que enviaste pertenecen al mismo grupo

**Comment by RigoFlores** [comment]
al parecer no leiste el correo, sigue enviando todo fijo.
El ejemplo que envié en el correo tiene todas las claves distintas, de ahí que no estamos viendo lo mismo.

**Comment by jccastillo0007** [comment]
te sugiero que revises bien el txt que enviaste y el catálogo de productos de optibelt, y luego me dices que es lo que no lei bien.

En tu achivo de texto, para empezar hay dos productos con el mismo nombre "optibelt SUPER TX"

**Comment by RigoFlores** [comment]
este es el contenido del txt que envié por correo. En amarillo lo que se debe de parsear... para identificar su clave de producto del sat... según yo son todas distintas.
<img width="1249" alt="optibelt" src="https://user-images.githubusercontent.com/2912775/33920377-4192128c-df83-11e7-92bd-77dfca59d4eb.png">

**Comment by jccastillo0007** [comment]
Really.... el primer y tercer registro dicen "optibelt SUPER TX" ... eso es lo que se analiza

**Comment by RigoFlores** [comment]
ah si, una está repetida... pero igual todas las trata como si fueran lo mesmo..

**Comment by jccastillo0007** [comment]
checa el catálogo, chiaaa

**Comment by RigoFlores** [comment]
chiaaa... ya vi, todas aunque eran distintas tenían el mismo código... chiaaaaaa
