### ISSUE TITLE
Navision DRP - no asigna la serie y folio correspondiente en el documento generado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1224]
Esta asignando el mismo folio al CFDI de pago, que la factura pagada... jajaja...
El folio del documento de pago, es el que está en la tabla Factura-T cuando se dispara... chiaaaa

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
El que anteriormente si generó, aún con la serie y folio chuecos, ahora lo marca como error no clasificado.

**Comment by jccastillo0007** [comment]
listo...

Hay que preparar un pago para varias facturas.... para poder hacer pruebas.

**Comment by RigoFlores** [comment]
ok, queda pendiente validar un pago a varias facturas, si no jala levanto otro issue
