### ISSUE TITLE
Navision 3.3 - Marca error cuando la cantidad > 1

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1225]
Lo que está haciendo, para el cálculo de la base es multiplicar cantidad por importe...

Recordar que importe = cantidad * precio unitario
Base es Importe - descuentos

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
lo acabo de validar y sigue marcando el mismo error.
Factura 17FVMX192 en pruebas navision.

**Comment by RigoFlores** [comment]
sigue igual, factura 189

**Comment by jccastillo0007** [comment]
fixed
