### ISSUE TITLE
Generar Optibelt Producción 3.3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1226]
Ya mañana instalo.

**Comment by jccastillo0007** [comment]
este si quedo como hablamos por teléfono ?

**Comment by RigoFlores** [comment]
no los hallé por la tarde... supongo fiesta de fin de año....

**Comment by RigoFlores** [comment]
no jaló, con el properties apuntando a producción, hice mi oso de que no jaló... tiene como emisor al ACO

**Comment by jccastillo0007** [comment]
Pues no sé con que versión de facturat probaste... ahorita ya subi una nueva versión y verifique que el rfc OME usara el plugin de Levicom y el RFC ACO ya queda fuera de ese plugin

**Comment by RigoFlores** [comment]
con la última versión que probé y pasó todo... que me comentaste que al ponerlo a producción, se olvidaría de ACO y le haría caso a la llave... y esa no jaló, esa buscaba a ACO...
pero bueno, mañana vuelvo a actualizar, a ciegas..

**Comment by jccastillo0007** [comment]
Ok, el rfc configurado para levicom es OME111223UN4... hasta ahi si estamos ok ?

**Comment by RigoFlores** [comment]
ok, solo para asegurar... existen 2 formatos de levicom... el de optibelt OME111223UN4, y el de otros rfc's ETEalgo.... estamos con el primero
los otros por lo pronto, los perdimos

**Comment by jccastillo0007** [comment]
okas, que putos... tanto trabajo que costo hacer sus conectores

**Comment by RigoFlores** [comment]
cuál de todas las versiones corresponde al optibelt?

**Comment by jccastillo0007** [comment]
ayer subí la que soporta el cambio de forma de pago y método de pago, asi como 25 datos extras.
