### ISSUE TITLE
Escritorio - Impuestos locales, no envia las variables al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1227]
Enviar el contenido de las variables correspondientes:

	<field name="nombreImpLocal1" class="java.lang.String"/>
	<field name="tasaImpLocal1" class="java.lang.String"/>
	<field name="montoImpLocal1" class="java.lang.String"/>
	<field name="nombreImpLocal2" class="java.lang.String"/>
	<field name="tasaImpLocal2" class="java.lang.String"/>
	<field name="montoImpLocal2" class="java.lang.String"/>

hasta cuántas variables se soportan en escritorio y en web?
Entregué una ayer, desde la autopista cuando venia a México. Luego habló el cliente super agradecido, y dijo que nadie le había resuelto y que muchos clientes nos estarán buscando, supuestamente

**Comment by jccastillo0007** [comment]
orale, que chido...

**Comment by jccastillo0007** [comment]
tenemos espacio para 4 impuestos locales, tanto en web como standalone

**Comment by jccastillo0007** [comment]
Por cierto, solo se esta usando el primer impuesto local, tealmente se ocupan los 4 ? cuantos impuestos locales se pueden agregar a una misma factura.

**Comment by RigoFlores** [comment]
hace poco ví un ejemplo con 3 impuestos locales... tons hay que mantener los 4 que dices.

**Comment by jccastillo0007** [comment]
Listo... ya se soportan en standalone, hoy veo que petch con web.

**Comment by jccastillo0007** [comment]
En web no habia ningún problema, tons supongo ya se puede cerrar este issue

**Comment by RigoFlores** [comment]
cuál versión de escritorio atiende este issue. Anteeriormente se distinguían las de optibelt del estándar... ahora ya ni sé...
