### ISSUE TITLE
Web - Compras - Registrar CFDI de proveedores de la 3.3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1228]
Pensé que ya lo habías implementado como dijiste.
Hoy con la contabilidad, me vuelvo a enfrentar a hacer manualmente muchas cosas...

**Comment by jccastillo0007** [comment]
que falta aqui ? o no esta funcionando el tema de subir un CFDi ?

**Comment by RigoFlores** [comment]
no, no funciona lo de subir un CFDI.
Desde el menú de compras-registrar CFDI.
Esa misma función se debe ajustar en la plataforma para proveedores (si es que son distintas pantallas).
