### ISSUE TITLE
Algo chueco está en CxC - asigna cobros de una factura a otra

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1229]
Se le están cruzando los cables, y eso podría ser potencialmente un desastre, sobre todo para Optibelt que estará en auditoría...

Hoy generamos la factura F3780. Al intentar capturar el cobro, ya tenía asociado un cobro que estaba originamente asociado a la factura F3510

Otro caso es:
JEJU920704LL5   PAGO EL 10 DE SEP EN INBURSA $243.60
RIRV780214CA6 PAGO 28 DE DICIEMBRE EN BANCOMER $2784.00

Aparecía el pago de JEJU en el de RIRV, lo borre.
Y luego aparecía el pago de valentin en JEJU, también lo borre……checar que paso y que quede correcto

**Comment by RigoFlores** [comment]
Al querer registrar el pago de RIRV780214CA6  Factura 3767 no es posible, ya que no la muestra, es decir pareciera como si ya tuviera un pago registrado el pago. 
Si te vas a cartera por cliente, al consultar este cliente no aparece ningún pago asociado a esta factura.

**Comment by RigoFlores** [comment]
Al intentar registrar el pago de  F-3834    SALJ8206041H5    POR $1392.00  aparece una cantidad en negativo porque tiene asociado el pago de la F-3597 que corresponde a otro RFC

**Comment by RigoFlores** [comment]
Que onda con este issue, tenemos los cables cruzados en CxC... no se si optibelt lo tenga, pero nosotros si, y eso será un pedo al momento del DRP

**Comment by jccastillo0007** [comment]
ya ando en este, porque yo lo decidi como chingados no ... jajaja

**Comment by RigoFlores** [comment]
Al querer registrar el pago de la F-3928 ROSC671122492, no puede realizarlo porque aparece un pago por 487.20

**Comment by RigoFlores** [comment]
Al querer registrar el pago de $1392.00 factura F3956 de ROCR6408182W1,  ya aparece un pago registrado que no le corresponde...

**Comment by RigoFlores** [comment]
Ahora es con este otro rfc HEHV650502K79 F3991. 
Al tratar de registrar el cobro, aparece un cobro que corresponde a otra factura, la F3562.

Necesitas ya ver que onda con esto, ya que el reporte de cartera vencida no lo podemos generar por esta razón, y pues que te puedo decir, es lana que no estamos cobrando.

**Comment by RigoFlores** [comment]
ROCR6408182W1 Rosa Aurora Rossainzz, al tratar de registrar el pago de f-3993, aparece ya registrado un pago...
Cuando lo atenderemos finalmente?????

**Comment by jccastillo0007** [comment]
yo no veo pagos registrados para la factura f3993 de ROCR6408182W1

**Comment by jccastillo0007** [comment]
![rocr6408182w1](https://user-images.githubusercontent.com/2245679/37070844-816103da-21b1-11e8-9b35-a823f365e8cf.png)

**Comment by RigoFlores** [comment]
Es en la f3956... no en la 3993.... me confundí

**Comment by jccastillo0007** [comment]
ok, ya encontre el error... el asunto esta asi..

1. El pago si se asigna correctamente a la factura que seleccionaste inicialmente.
2. Cuando realizas la consulta de cartera o cuando consultas las facturas de un cliente para asignar otro pago... ahi estaba el problema...
3. Resulta que el campo utilizado para seleccionar las facturas de un pago en específico, era a través del tracking Id, y no era confiable, pues se puede repetir.... 
4. Le agregué al query que además del tracking Id, valide el UUID, de esta forma ya es único

5. El pedo es que algunas facturas ya se cambiaron a PAGADAS, y eso si no se porque , y no se como darle revert... unicamente manualmente en la base de datos.

6. Ya no debe seguir pasando, pero si hay que cambiar el estatus  a vigente o vencida según sea el caso para las facturas afectadas..

**Comment by RigoFlores** [comment]
jajaja... lo comenté hace meses (o años)... el tracking id no es confiable.... o told u....
todas las registradas como pagadas están ok....  tu corrige,  lo demás yo me encargo..

**Comment by RigoFlores** [comment]
Leyendo ya me confundí... es posible que en optibelt tengan problemas por este escenario de error?
Te recuerdo que ellos manejan el número de cliente.
Me parece raro, que emitiendo tantas facturas como lo hace, no hayan reportado este problema.

Además del tracking id, no se ocupa otra cosa para que se presente el problema... por ejemplo el número de cliente???

**Comment by jccastillo0007** [comment]
noup, realmente es una coincidencia muy dificil de cumplirse... por eso es que lo veias muy esporadicamente... 

El efecto real, es que en la consulta de cartera por cliente o al ingresar un cobro, al realizar un filtro por rfc, podían aparecer algunos pagos que no le pertenecen.. eso ahora ya lo arreglé, lo malo es que algunas facturas aparecen como pagadas y tal vez no lo están

**Comment by RigoFlores** [comment]
Sigo sin entender, porque razón algunas facturas pasarían al status de pagadas???
Los escenarios que nosotros detectamos, al estar chuecos, simplemente no se capturaron los pagos porque sería inconsistente.

Estoy segurísimo que a Optibelt se le debió presentar este escenario, y también que inmediatamente me lo hubiesen reportado.
Debe haber algo mas.
Es muy delicado este tema, ya que este módulo será utilizado para emitir el documento de pago.

**Comment by jccastillo0007** [comment]
correcto, yo tampoco sé porque están como pagadas... debo revisar todos los procesos que tenemos que ponen una factura como pagada, probablemente por ahi hay un escenario que al tomar el pago equivocado la puso como pagada... o probablemente lo hizo el usuario

Por ahora, lo que si es que ya no debe suceder la asignación erronea de pagos.

**Comment by RigoFlores** [comment]
A ver, cuando iniciamos hace tiempo con la versión 3.3. y el documento de pago, pedí poner todas las facturas a pagadas, y eso si se hizo... no será que te estás confundiendo con ese requisito?

**Comment by jccastillo0007** [comment]
no pues sabe....  tal ves si, no me acuerdo.

Ahorita el detalle es estar monitoreando que los pagos se asignen bien y que las facturas tengan el estatus correcto.

Ya esta corriendo a diario el update del estatus de cada factura, para ponerlas a vencidas de acuerdo a su fecha de expiración.

**Comment by RigoFlores** [comment]
Ya le ocurrió a optibelt...

**Comment by RigoFlores** [comment]
Te mandé un correo con los pasos para reproducirlo.
