### ISSUE TITLE
NAVISION PRO - NO ESTÁ JALANDO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1230]
TIENE LOS SIGUIENTES ISSUES:

•	ESTÁ LEYENDO LA TABLA FACTURA-T DE PRUEBAS 3.3
•	NO ESTÁ TIMBRANDO EN PRODUCCIÓN (YA QUE NO APARECEN LAS FACTURAS TIMBRADAS AYER, EN EL SAT)
•	NO ESTÁ ACTUALIZANDO LA TABLA FACTURA-T CUANDO YA TIMBRÓ LA FACTURA (YA SEA PRUEBAS O PRODUCCIÓN), POR LO QUE SE CICLA TIMBRANDO UNA Y OTRA VEZ LA MISMA FACTURA.
•	EL TEMPLATE QUE TENÍA CONFIGURADO ERA DE LA VERSIÓN 3.2 (POR ESO MARCABA EL ERROR)

LO EJECUTÉ DESDE C:\FacturaT

YA NOS ESTÁN ESPERANDO

**Comment by jccastillo0007** [comment]
fixed.

Ya esta corriendo navision como servicio, ya solo falta validar que la factura 208 este en el sat, tu puedes revisarlo ?

**Comment by RigoFlores** [comment]
aún no aparece
