### ISSUE TITLE
OPTIBELT - CAMBIOS ADICIONALES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1231]
QUE SE EQUIVOCARON EN VARIOS PUNTOS DEL MAPEO:

A) MÉTODO DE PAGO CAMPO H1.31
Cheque = PPD
Recibo = PUE
OJO: hay que considerar case insensitive

B) FORMA DE PAGO & USO DE CFDI. VIENEN JUNTOS EN EL CAMPO H1.8 EN LOS ÚLTIMOS 4 CARACTERES DE ESE CAMPO, YA QUE VIENE CON DATOS QUE NO ESTÁN BAJO SU CONTROL:
DE LOS ÚLTIMOS 4 CARACTERES DE ESE CAMPO, LOS PRIMEROS 2 SON FORMA DE PAGO DIRECTAMENTE, Y LOS ÚLTIMOS 2 SON USO DE CFDI, PERO HAY QUE MAPEARLOS:
EJEMPLOS          
ULTIMOS 4 CARACTERES DE H1.8     FORMA DE PAGO      USO DE CFDI PARA FACTURA
              99G1                                                    99                          G01
              03P1                                                     03                          P01
              02G3                                                     02                          G03

C) NOTA DE CRÉDITO. COLOCAR FIJO EL USO DE CFDI A G02

**Comment by jccastillo0007** [comment]
para tener todo en claro..
A) El campo H1.31 era usado para forma de pago y uso de cfdi, pero ahora será el método de pago y tendrá las palabras cheque o recibo, cierto ?

B) El campo H1.8 antes era el método de pago, pero ahora será forma de pago y uso cfdi
Estos son los únicos posibles valores o pueden venir mas ?

99G1 99 G01
03P1 03 P01
02G3 02 G03

**Comment by RigoFlores** [comment]
a) cierto, correcto, afirmativo.
b) ese campo se usará para forma de pago y uso de cfdi
de los últimos 4 caracteres de ese campo ya que traerá datos que no debemos pelar, los 2 primeros son tal cual la clave de forma de pago...
los 2 últimos representan el uso de CFDI 'truncado', ya que el P01 se incluye como P1, el G01 se incluye comoG1, el G03 se incluye como G3, etc... podemos pensar que la regla es que le falta el 0. 
Si te das cuenta, no está limitado su contenido, solo que para el uso del CFDI, le tendremos que agregar el '0' intermedio...

**Comment by jccastillo0007** [comment]
Sería mejor si nos definen cuales son los posibles usos de cfdi que ellos pueden usar... o tendría que validar todas las posibles opciones, pero sin el 0

**Comment by RigoFlores** [comment]
no entiendo lo de validar... si se manda tal cual viene, pero se le incluye el '0' intermendio, que validaciones habria que hacer??
G1=> G01
P1=> P01
G3=> G03

Esas aparentemente serán las mas comunes, sino es que las únicas, pero la regla puede quedar totalmente genérica.

**Comment by jccastillo0007** [comment]
ok, entonces no voy a validar que la clave sea válida, simplemente voy a agregar el 0 entre los dos caracteres.

**Comment by jccastillo0007** [comment]
listo.
La versión de hoy, ya incluye hasta 25 datos extras.
