### ISSUE TITLE
MUCHOS RFC'S DE PERSONAS FÍSICAS, TIENEN EL RÉGIMEN GENERAL DE PERSONAS MORALES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1232]
YA SON VARIOS CASOS DETECTADOS.
LAS PERSONAS FÍSICAS TIENEN ASIGNADO EL RÉGIMEN GENERAL DE LEY PERSONAS MORALES, QUE CASUALMENTE ES EL PRIMERO DE LA LISTA.
ME PARECE QUE RESETEASTE ALGO AHI, Y SE ESTÁ HACIENDO UN CAGADERO GRUEXO

**Comment by jccastillo0007** [comment]
y aqui que se ocupa o como ? como puedo saber si es persona física para asignarles el regimen adecuado? creo que hay una regla en el RFC no ?

**Comment by RigoFlores** [comment]
el problema es que antes de 'no se que situación o condición', todo estaba bien... pero ahora se dá el caso que muchas personas físicas tienen el régimen chueco... eso lo cambió el sistema... que hacer?... corregirlo, cómo? no tengo npi...

**Comment by jccastillo0007** [comment]
Los RFC de personas físicas son de 13 caracteres verdad, los de personas morales son de 14 cierto?

**Comment by RigoFlores** [comment]
MORALES 12, PF 13... el tema es que no todas las personas físicas tienen actividad empresarial, también hay incorporación fiscal
son los 2 para ellos

**Comment by RigoFlores** [comment]
personas morales 12
personas físicas 13

**Comment by jccastillo0007** [comment]
te mando por email un reporte para ver que hacemos... necesitamos encontrar un patron para arreglar el asunto.

**Comment by jccastillo0007** [comment]
Listo... las personas físicas que tenian algo de Moral... ya se los quite y les puse vacío... y los que tenían incorporación fiscal  mal escrito, ya lo corregí sin acento.

**Comment by jccastillo0007** [comment]
Aunque aún hay muchos que tienen configurado cosas raras. como 'regimen" no mamaaaaa

**Comment by RigoFlores** [comment]
YO CREO QUE LOS RAROS, YA NO ESTÁN FACTURANDO CON NOSOTROS

**Comment by RigoFlores** [comment]
no tengo forma de verificarlo....
