### ISSUE TITLE
Optibelt - par de defectos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1233]
No está inicializando las variables a "", caso concreto descripcionComplementaria a nivel de producto.
No está enviando las condiciones de pago que vienen en el archivo... campo h1.9, típicamente contiene un 25 ese campo

**Comment by jccastillo0007** [comment]
ok, condiciones de pago no se estaba contemplando, no se porque.

El 25 que significa o como ? o solo se manda y ya

**Comment by RigoFlores** [comment]
lo que venga se manda... son número de días...
