### ISSUE TITLE
soportar hasta 25 datos extra generales en escritorio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1234]
por aquello de la puta addenda coppel

**Comment by jccastillo0007** [comment]
listo.
con la versión generada ayer Enero 3, ya se soportan hasta 25 datos extras

**Comment by RigoFlores** [comment]
CHIAAA.... ESOS DE INDUSTRIAS MAN, OCUPAN HASTA EL 26..... (A QUIÉN PUTAS SE LE OCURRE???)
FAVOR DE AGREGAR UNO MAS

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
es la última versión en el dropbox?

**Comment by jccastillo0007** [comment]
SIMON
