### ISSUE TITLE
Agregar "Impuesto Municipal", como impuesto local en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1235]
Urge que no dependa de una lista en jarcoud los nombres de impuestos locales en web...

**Comment by RigoFlores** [comment]
Eliminar:
5% AL MILLAR C.M.I.C.

Cambiar:
5% AL MILLAR INSPECCION SFP    POR    5 AL MILLAR INSPECCION SFP
2% AL MILLAR I.C.I.C.                      POR    2 AL MILLAR I.C.I.C
5 AL MILLAR SUPERVICION Y VIGILANCIA     POR   5 AL MILLAR SUPERVISION Y VIGILANCIA

TODOS LOS CARACTERES CON ACENTO, DEJARLOS SIN ACENTO.
NO DEJAR MAS DE UN ESPACIO ENTRE CADENAS


Agregar:
0.04% SUPERVISION Y VIGILANCIA
2% DE SUPERVISION
2 AL MILLAR COLEGIO

**Comment by jccastillo0007** [comment]
Supongo que este ya no es necesario, elimino los impuestos locales que di de alta anteriormente?

**Comment by RigoFlores** [comment]
Afirmativo, si el nuevo enfoque ya quedó, entonces hay que eliminar los impuestos que diste de alta.
Una pregunta, lo de impuestos locales como antes estaba, podría ser un approach paralelo simultáneo para el caso que la base sea cantidad por precio unitario?

**Comment by jccastillo0007** [comment]
ups, me no entender... paralelo simultaneo para la base sea cantidad por precio unitario ? mejor lo hablamos

**Comment by jccastillo0007** [comment]
mejor dime cuales elimino, porque son un buen... y no quiero afectar a clientes que crean que ahi van a seguir.

**Comment by RigoFlores** [comment]
Vamos a dejarlo así como está... para no meter ruido... necesito hacer pruebas y ya te comentaré
