### ISSUE TITLE
Super conector Optibelt - no envía datos extra al PDF que se genera en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1238]
En el conector genera correctamente la factura, es decir con los datos extra.
Pero cuando es XML llega al web y genera el formato configurado en la cuenta de optibelt, no se envían los datos extra.

**Comment by jccastillo0007** [comment]
Envié evidencia de que si se mandan los datos extras a jasper

**Comment by RigoFlores** [comment]
TE MANDÉ UN CORREO CON MAYOR DETALLE... PRÁCTICAMENTE SON TOTALMENTE DISTINTOS

**Comment by jccastillo0007** [comment]
se me olvidó ponerlo a fixed.

**Comment by RigoFlores** [comment]
no han podido facturar, porque tienen broncas con su internet...
en cuanto se valide se comenta o cierra este issue

**Comment by RigoFlores** [comment]
NO ESTÁ INCLUYENDO EL NÚMERO DE PEDIMENTO EN EL PDF DE OPTIBELT, EL QUE SE REGENERA EN EL SERVIDOR WEB
