### ISSUE TITLE
Implementar envío de correos por servicio de paga

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1239]
Desde el escritorio, o desde el web, o cuando se envíen notificaciones de folios por vencer, utilizar el servicio de paga.

https://sendgrid.com/

**Comment by jccastillo0007** [comment]
avisame si te llegan un par de emails de prueba...

**Comment by RigoFlores** [comment]
si llegaron 2 correos enviados desde sendgrid.... así decía... jeje

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
ya quedó en web también????
