### ISSUE TITLE
Habilitar datos extras en combinación con impuestos locales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#124]
Generalmente impuestos locales, implica colocar en la sección de totales, leyendas y valores de esos impuestos precisamente. Por ejemplo, impuesto cedular, 5 al millar, 2% etc.
Entonces se requiere, que al igual que se hizo específico para CFE (rfc ARG1201271T9), se establezca pero en forma genérica, la manera de identificar y capturar los datos extra genéricos, así como los datos que corresponden a los impuestos locales.
Ejemplo:
<extradata>
    <fields>
        <field>
            <tag>Subtotal sin Cedular</tag>
            <name>subtotalSC</name>
            <type>STRING</type>
            <length>20</length>
        </field>
        <field>
            <tag>Impuesto 1</tag>
            <name>taxType1</name>
            <type>TAXES</type>
            <length>300</length>
        </field>
        <field>
            <tag>Tasa 1</tag>
            <name>taxTasa1</name>
            <type>NUMERIC</type>
            <length>10</length>
        </field>
        <field>
            <tag>Monto 1</tag>
            <name>taxAmount1</name>
            <type>NUMERIC</type>
            <length>10</length>
        </field>

```
</fields>
```

</extradata>

En este caso, el primer dato extra, es un dato general.
La opción podría ser la siguiente y tu me dices si es viable. 
Colocar al inicio todos los datos extra genéricos. Cuando aparezca el primer dato de tipo TAXES, eso indicará que de ahí en adelante, estamos capturando los datos para el complemento de Gobierno o Impuestos locales.
Recordar que para el complemento de impuestos locales, se captura con 3 datos: Impuesto, tasa y monto.
Recuerdo que habíamos comentado, que soportaríamos hasta 5 distintos impuestos.

**Comment by jccastillo0007** [comment]
Eso ya se puede que no? Los datos extras tienen un name, type y value

O no estoy entendiendo?

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
Lo que sucede con el plug in de gobierno, es que al parecer todos los toma como impuestos locales, es decir en la terna de: impuesto, tasa y monto.
Lo que se requiere es que podamos definir dentro de ese mismo XML, datos extra normalitos (que no se irán al complemento de impuestos locales), sino que se usarán en el PDF.
En conclusión, es mandar tooooodos los datos extra, tanto los que sean como los que no sean, impuestos locales.
