### ISSUE TITLE
Navision 3.3 Producción - error en nota de crédito con documentos relacionados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1241]
Te mandé un correo.
Creo que el problema es que en documentos relacionados, envías el folios interno en lugar del UUID.

**Comment by jccastillo0007** [comment]
Correcto, el UUID no esta bien formado, esto es lo que manda finkok

"XMLSyntaxError(u"Element '{http://www.sat.gob.mx/cfd/3}CfdiRelacionado', attribute 'UUID': [facet 'length'] The value '17FVMX208' has a length of '9'; this differs from the allowed length of '36'.",)"

**Comment by RigoFlores** [comment]
y ya quedó fixado???

**Comment by RigoFlores** [comment]
ya ví que no, y los españoles están parados de pestañas...

**Comment by jccastillo0007** [comment]
fixed, ya lo instale en Navision en el folder de producción.
