### ISSUE TITLE
Bajo circunstancias no muy claras, no incluye lugar de expedición en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1244]
Pensé que sucedía cuando no incluía email los datos del emisor.
Pero hoy encontré un caso, que te envié por correo donde si incluye el email y al momento de generar el XML, no incluye el lugar de expedición.

**Comment by RigoFlores** [comment]
creo que es que los datos de algunos clientes están chuecos... cuando los 'regrabas' como que se 'reordenan' y ya jala... el problema es conocer cuáles son esos clientes...

**Comment by jccastillo0007** [comment]
ya vi que es... hay algunos clientes como el rfc que me enviaste, que crearon una sucursal, pero no le pusieron todos los datos de la dirección... por eso lo mandaba nulo.

ya arregle la base de datos.

**Comment by RigoFlores** [comment]
Como dicen los clientes...'antes si lo hacia bien'... es decir, aunque tuvieran sucursal o nó, antes si enviaba bien los datos... pero bueno... vamos a pensar que si sea eso y que ya quedó corregido.
Espero que no se vuelva a presentar.
