### ISSUE TITLE
Conector - dejó de procesar nómina y pagos!!!

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1245]
urge corregir este asunto

**Comment by jccastillo0007** [comment]
pero cual es el comportamiento ?, no procesa el archivo, o marca algún error o algo no cuadra?

**Comment by RigoFlores** [comment]
invalid file dice el archivo de error... es decir no lo procesa, y si lo mueve con error a procesados

invalid file : C:\CONECTOR3.3\CONECTOR\Pagos.txt

**Comment by jccastillo0007** [comment]
si, ya le encontre, metio ruido lo de CCE por conector.... pero ya lo arreglé.

**Comment by RigoFlores** [comment]
lo de pagos ya lo procesa, pero lo de nómina aún no...

**Comment by jccastillo0007** [comment]
Tienes algun ejemplo de txt de nómina que  deba timbrar.

**Comment by jccastillo0007** [comment]
sigo sin poder identificar el problema de la nómina... todas las cifras cuadran

**Comment by RigoFlores** [comment]
si está cañón, y sin embargo figueacero lo tiene jalando...

**Comment by jccastillo0007** [comment]
tons no debe haber problema, debe ser un pedo de finkok

**Comment by RigoFlores** [comment]
tal como lo dice el mensaje, el importe que estamos enviando es incorrecto.... importe = cantidad x precioUnitario..... en el conector de nómina, el importe se está enviando como 
( cantidad x precio unitario ) - descuento.

hay que corregirlo en chinga, un cliente importante lo está esperando

**Comment by jccastillo0007** [comment]
hmmm bueno ese mensaje es muy genérico, lo manda siempre que no cuadran las cifras, cualquiera que sea el problema.

**Comment by jccastillo0007** [comment]
ya corregí ese tema... que de hecho la interpretación en nómina estaba diferente : 

product.setImporte(otrospagos + totalPercepciones - totalDeducciones)

Desconozco porque ahora truena, pero bueno, la asignación quedo solo : 
product.setImporte(otrospagos + totalPercepciones)

Me marco XML Mal formado, pero al validar el XML con el validador de finkok, me dijo que todo estaba bien.

Recuerdo que ya habiamos visto ese caso, que solo en producción se podía  timbrar.

**Comment by RigoFlores** [comment]
pero no subiste la versión???

**Comment by RigoFlores** [comment]
????

**Comment by jccastillo0007** [comment]
listo. ya lo subi
