### ISSUE TITLE
en escritorio hacer algunos ajustes de vista

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1247]
a) el tipo de relacion no se alcanza a leer completo, queda truncado en la lista desplegada
b) cuando un receptor tiene nombre alterno, este se muestra encima de otros datos.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Olvidé comentar lo de quitar el botón en consultas, de Descarga SAT.
Los teléfonos en la pestaña de la derecha son:
(01)-442-212-0347
(01)-442-543-0683

Quitar el domicilio (no le veo mucho caso ya a estas alturas).

**Comment by jccastillo0007** [comment]
done
