### ISSUE TITLE
Addendador Pilgrims - ajustarlo a la version 3.3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1248]
Hasta ahora un cliente que ocupa el addendador nos lo ha solicitado.
Pero tambien hay que hacerlo para el proceso de factura+addenda simultaneos.

Hoy en dia el addendador toma los siguientes datos del detalle:
idProducto
PrecioUnitario
Cantidad
Unidad de Medida (no es la del SAT, sino la descripcion interna)

Dado que el nodo de detalle cambio en el 3.3, se requiere hacer los ajustes en el addendador para pilgrims. Igual se ocupa al momento de emitir la factura + addenda pilgrims.

**Comment by jccastillo0007** [comment]
cual es el ajuste solicitado / requerido ? el tema de unidad de medida ? que utilice la del sat?

**Comment by RigoFlores** [comment]
el ajuste es que tome esos datos a nivel detalle, bajo la nueva estructura del XML.
O es independiente una cosa de la otra?
Estoy asumiendo que el addendador ocupa o busca bajo la estructura anterior.

**Comment by jccastillo0007** [comment]
Una vez revisado el proceso actual.
Los únicos datos que se mandaban a la addenda en web son, precio unitario y cantidad

El único dato que se pudo agregar es Unidad, al campo UdeM de la addenda

El campo IdProducto, no sé donde se deba enviar.

El resto de datos los toma de datos extras.

**Comment by RigoFlores** [comment]
PERO ENTONCES POR QUE NO JALA?
LO DE UNIDAD DE MEDIDA, MEJOR NO LO MANDES, SI NO LO MANDABAS NO LO MANDES... SUPONGO QUE ES OPCIONAL O NO APLICA PARA EL PROCESO 01

**Comment by jccastillo0007** [comment]
y que error te manda ?

**Comment by RigoFlores** [comment]
ACABO DE REVISAR Y NO MANDA ERROR... SEGÚN EL USUARIO LE ESTABA MANDANDO UN ERROR AL CAPTURAR Y NI MADRES. YO PENSÉ EN REVISAR DESPUÉS, PERO CON TANTA CHAMBA DE ME PASÓ.
PAGÓ ACTUALIZACIÓN.
LE PONDRÉ EL XML DEL FAMOSO ENFOQUE OPTIMIZADO.
