### ISSUE TITLE
Web - no está enviando los datos de CFDI relacionado al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1249]
Eso ya jalaba y ahora ya no envía nada.
Al acceder a la pantalla de facturación, o después del timbrado, dichas variables se deben inicializar a ""

**Comment by RigoFlores** [comment]
y ahora somos nosotros los que tenemos que cancelar una factura y refacturar y ocupar esa funcionalidad de tipo de relación y cfdis relacionados... chiaaaaa

**Comment by jccastillo0007** [comment]
jajaja, tons es una prueba real de que si se ocupa

**Comment by RigoFlores** [comment]
chiaaaa... pos seguro que se ocupa...
no puedes dejar de enviarlo así porque si... chiaaaa

**Comment by RigoFlores** [comment]
de hecho noté y varios clientes, que hace poco empezó aparecer el recuadro de documentos relacionados, cuando no debía aparecer... eso significa que fue cuando decidiste que no se ocupaba y por lo tanto no lo enviarías al pdf... y el tema es que todas las plantillas, que son muchas personalizadas, les pega cualquier decisión similar...

**Comment by jccastillo0007** [comment]
a cabron... yo decidi? yo casi no decido nada .... tons lo quito ?

**Comment by jccastillo0007** [comment]
acabo de hacer una prueba, y si mando el cfdi relacionado..

xml 
<cfdi:CfdiRelacionados TipoRelacion="04">
        <cfdi:CfdiRelacionado UUID="33CEA6DF-BFAA-495E-939C-2A30F5C45F47"/>
    </cfdi:CfdiRelacionados>

datos enviados a jasper

cfdisRelacionados=["33CEA6DF-BFAA-495E-939C-2A30F5C45F47"]

PDF. si muestra el string de documentos relacionados con la misma información


 no va muy bien formateado pero si se manda... esto fue al momento de facturar... tu en donde lo probaste ?

**Comment by RigoFlores** [comment]
En producción... hace poco tiempo, un recuadro donde se muestran los CFDIs relacionados, que estaba condicionado para que se mostrara solo en caso necesario, empezó a aparecer... de hecho puedo revisar nuestras facturas para ver en que fecha sucedió... no le hice mucho caso, pero cuando ya intenté corregir ese detalle, me dí cuenta que ya no se envían los datos de tipo de relación y cfdi's relacionados al PDF. Al menos en la vista previa no aparecen, y antes si aparecían... todo esto en web producción, tal cual dice este issue

**Comment by RigoFlores** [comment]
OK, ya está corregido, si lo envía al PDF timbrado en web, pero no lo envía en vista previa.
