### ISSUE TITLE
Habilitar el manejo de cantidades en impuestos, al menos en 3 decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#125]
Anteriormente ya contábamos con esta facilidad.
Ahora que estoy probando con impuestos retenidos, me doy cuenta que solamente acepta 2 decimales, y con ello muchos cálculos no resultan en lo esperado con el cliente. Por ejemplo, antes permitía el 10.667 y ahora lo maneja como 10.67

Yo creo que la regla debe ser general, tanto para web como para escritorio: hasta 6 decimales en cualquier variable que maneje decimales. El formato de la vista (PDF), no cambiaría, pero internamente, si se hace necesario manejar esa cantidad de decimales para llegar a las cantidades requeridas por los clientes.

**Comment by jccastillo0007** [comment]
Hay otro ticket donde se solicita 6 decimales.

Según esto ya esta a 6 decimales, pero debo verificar, por lo pronto este issue ya no procede y nos quedamos con el de 6 decimales.

**Comment by RigoFlores** [comment]
Impuestos no soporta 6 decimales, y si sería deseable.
Impuestos maneja 3 decimales... por lo tanto se cierra este issue, pero si hace falta hasta 6 en impuestos
