### ISSUE TITLE
Web - mostrar una ventana modal al inicio, cuando el certificado esté próximo a vencer

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1250]
Con 30 días de anticipación.
El letrero en rojo que ahora mismo aparece, nadie lo lee... y ha pasado cualquier cantidad de veces que se les vence y luego retrasan su facturación un chingo..... y sigue pasando...

**Comment by RigoFlores** [comment]
se siguen quedando sin facturar los clientes porque se les vencen sus sellos...

**Comment by jccastillo0007** [comment]
listo... pero no la he probado... jojojo... voy a forzar que se muestre en PRU para saber que ya esta

**Comment by RigoFlores** [comment]
entonces como lo validamos???

**Comment by RigoFlores** [comment]
OK, PARA VALIDARLO, AGREGUEMOS LA CONDICIÓN DE QUE LOS FOLIOS ESTÁN PRÓXIMOS A VENCER: 

A) QUEDAN MENOS DEL 10% DE SU ULTIMA COMPRA
B) FALTAN 2 SEMANAS O MENOS PARA VENCIMIENTO

**Comment by RigoFlores** [comment]
Estimado cliente, le informamos que:

a) Su **_CERTIFICADO DE SELLO DIGITAL_** está próximo a vencer
ó
b) Sus folios de facturación están próximos a terminarse o concluir su vigencia.

Para el punto (a) favor de apoyarse con su contador para tramitar un nuevo sello.
Para el punto (b), favor de llamarnos al (01-442) 212 0347 o escribirnos a contacto@factura-t.com.mx para solicitar folios adicionales.

Atentamente, Factura-T.

**Comment by jccastillo0007** [comment]
ok, ahorita sale siempre un pantalla modal al entrar a facturat, esa ventana solo saldr[a si el certificado ya va a expirar en PRO...

Ya solo me falta cambiar el msg

**Comment by RigoFlores** [comment]
Pero si estaríamos atendiendo las 2 condiciones???
Porque solo mencionaste una.

**Comment by jccastillo0007** [comment]
Si, ya tengo implementado las dos validaciones

En PRU sale siempre
En PRO solo cuando se cumpla con al menos una de las condiciones

**Comment by RigoFlores** [comment]
Hoy actualicé a un cliente su sello, ya que se había vencido.
No me presentó la pantalla.

**Comment by RigoFlores** [comment]
Ahora está peor, ya que la fecha de vencimiento del sello, ya no la muestra. 
Mucho menos presenta la pantalla indicando que ya se va a vencer el sello o los folios.

**Comment by jccastillo0007** [comment]
si, eso de la pantalla no lo he podido estabilizar... el pedo es que puedo hacer que siempre salga o que nunca salga... pero no que salga dependiendo de una condición...

**Comment by RigoFlores** [comment]
Si ponemos que siempre salga, será lo mismo que hoy sucede, es decir no lo verán.
Ahora cuando un cliente tiene mas de 1 rango de folios activos, solo muestra 1 de ellos. Ya lo han reportado varios.

Es posible que esa validación se coloque al acceder a ventas-facturas???

**Comment by jccastillo0007** [comment]
y como para que quieren ver todos sus rangos activos de folios ?

se puede poner en ventas-facturas, pero seria el mismo issue de cuando mostrar la ventana, siempre o con un botón..? pero automágicamente dependiendo de una condición no he encontrado como hacerlo.

**Comment by RigoFlores** [comment]
Lo de todos sus rangos, es simple:
a) Siempre había estado así, y de repente ya no.
b) cuando el cliente paga unos nuevos folios y aún tiene otros, el se deba cuenta. Ahora eso es lo que está pidiendo.
c) El sello, nosotros mismos no sabemos qué vigencia tiene. Ya estamos a ciegas en este momento

Una vez que facturan, cuando ya terminó todo el proceso, se podría activar esa validación y mostrar la ventana, solo cuando se vayan a vencer los folios o caducar el sello??

**Comment by RigoFlores** [comment]
si todo se complica entonces, hay que dejarlo como estaba... varios (muchos) clientes, ya han reclamado de que no ven todas sus recargas ni la fecha de vencimiento de sellos...

**Comment by RigoFlores** [comment]
Se puede dejarlo como antes, con letras negras.
Cuando se cumpla la condición, cambiar de tamaño (mas grandes) en color rojo?

**Comment by jccastillo0007** [comment]
listo

Luego me hecho otro clavado para ver lo de las letras...

**Comment by jccastillo0007** [comment]
capaz que lo pongo en rojo y negritas de una vez , pa que lo vean siempre

**Comment by RigoFlores** [comment]
no, en rojo estaba antes y se convierte en un mensaje que ya nadie leemos.
Si lo mostramos siempre en color negro, se perderá con el resto del texto mostrado al inicio.
Pero si de repente, cuando se cumpla la condición de folios próximos a vencerse y/o a terminarse, o la condición de que el sello está próximo a caducar, se muestra en color rojo, quizás logremos que lo lean.
