### ISSUE TITLE
WEB Impuestos locales bajo la modalidad de Producto-Impuesto los reporta como "LOCAL"

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1251]
solo en algunos casos, en otros los reporta bien.
En pruebas existe el producto-impuesto "Inspeccion y Vigilancia", para que revises.
Envié un correo

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
HICE LA PRUEBA CON 3 IMPUESTOS LOCALES DEL TIPO PRODUCTO-IMPUESTO, Y SI LO HIZO BIEN EN EL XML, CÁLCULOS TODO.

PERO AL PDF SOLO ENVIÓ LOS 2 PRIMEROS IMPUESTOS. 
ENTONCES EL PROBLEMA ES CUANDO MANEJAS 3 PRODUCTOS-IMPUESTO, SOLO ENVÍA 2. ME HABÍAS COMENTADO QUE HASTA 5 PRODUCTOS SE PODRÍA.

**Comment by RigoFlores** [comment]
VAIDEGÜEY, ESTA SOLUCIÓN YA LA PUEDES SUBIR A PRODUCCIÓN, PARA QUE ATENDAMOS EL PROBLEMA DE LUIS GUADARRAMA.

**Comment by jccastillo0007** [comment]
listo.
