### ISSUE TITLE
Addenda mabe no reporta correctamente la tasa de retención de iva

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1252]
y el addendador no permite capturar la unidad a nivel concepto que se reporta en la addenda, ya que algunos xml de otros proveedores no incluyen ese dato que nosotros si incluimos (la unidad a nivel concepto). Solo incluyen clave de unidad sat, y esa no sirve para la addenda. 
Al menos no por lo pronto

**Comment by jccastillo0007** [comment]
listo, ya esta jalando en PRU... no sé si era tan tan urgente,, pero ya lo subí a PRO, ya que cada domingo o lunes estoy haciendo un release para estar consistente con los ambiente.
