### ISSUE TITLE
Web - poder subir XML 3.3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1253]
tanto para facturas recibidas. Menu Ventas-Registrar CFDI Externo
como para proveedores. Menu Compras-Registrar CFDI
Asumo que la plataforma de proveedores, quedaría resuelto.

**Comment by RigoFlores** [comment]
hoy marcó un cliente que ocupa lo de proveedores, que no podía subir sus facturas 3.3... si se ocupa aunque ud no lo crea

**Comment by RigoFlores** [comment]
Se ocupará para el módulo de CxP en los condominios.
Vamos muy lento, prácticamente sin avance visible...

**Comment by jccastillo0007** [comment]
Según yo esto ya funciona... solo que debes probarlo solo con xml reales, ya que se valida que exista en el SAT, yo lo intenté desde el menú de ventas - registrar cfdi

**Comment by RigoFlores** [comment]
Pues no, al menos no me funciona a mí... este XML lo generé en el portal del SAT en enero pasado y simplemente no lo reconoce o no sé que significa el mensaje

<img width="397" alt="errorsubirxml" src="https://user-images.githubusercontent.com/2912775/39711645-e98787ea-51e5-11e8-9b26-e385b45028fa.PNG">

**Comment by jccastillo0007** [comment]
Me pasas el XML

Saludos.
JC.

**Comment by jccastillo0007** [comment]
listo.

**Comment by RigoFlores** [comment]
Cómo lo valido?
En PRU no puedo, porque no tengo XML donde el receptor sea ACO

En PRO, lo intenté desde Compras-Registrar CFDi, pero no lo puede subir.

Esto de subir XML 3.3, aplica para los menús de Compras-Registrar CFDi, Ventas-Registrar CFDi externo y Proveedores-Registrar CFDi.

Entonces para probar, desde cualquiera de ellos debería poder hacerlo.

**Comment by jccastillo0007** [comment]
Si, y para subir un XML 3.3 lo puedes hacer desde la cuenta de la TIA, ya que no se timbra, no importa que no sea el rfc ACO

**Comment by RigoFlores** [comment]
Marca internal error cuando intento entrar con la TIA101020BP4/test

**Comment by RigoFlores** [comment]
Sigue igual, no puedo entrar a facturat pru, con la cuenta de la tia para poder subir los XML emitidos y recibidos, eso anoche te mostré.
Me dijiste que la cuenta solo estaba creada/configurada para descargat, pero no para facturat

**Comment by jccastillo0007** [comment]
listo, ya se puede.

Y ya probé lo de subir cfdi como proveedor y si esta funcinando
