### ISSUE TITLE
Revisar si el DRP es enviado por correo, de acuerdo a la configuración

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1254]
Ayer hice uno con el cliente, y me comenta que no le llegó.
Revisando el panel de sendgrid, ni siquiera aparece listado su correo.
Creo que no está respetando la configuración de envío de correo automático, para los DRP.

**Comment by jccastillo0007** [comment]
fixed, hace como 2 o 3 semanas.

**Comment by RigoFlores** [comment]
generé 2 documentos de pago hoy, y ninguno me llegó por correo.

**Comment by jccastillo0007** [comment]
ok, ya revise... como en esa pantalla no tenemos las opciones de seleccionar envio de email al emisor o receptor... entonces toma la configuración que se tiene del usuario de facturat, en la pantalla de configuración...

**Comment by jccastillo0007** [comment]
siempore no, algo paso y no jalo en PRO, tons le di rollback

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Acabo de generar el documento con serieFolio PAGO3 desde la cuenta de la TIA, y no me llegó ni a mí, ni al correo que tiene configurado ese cliente.
Previamente cambié la configuración a que siempre lo envíe al emisor y receptor.

**Comment by RigoFlores** [comment]
volví a revisar y solo me llegó el PDF, pero no el XML

**Comment by RigoFlores** [comment]
están esperando
