### ISSUE TITLE
Conector 3.3 - no envía correctamente el uso del CFDI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1256]
Cuando se trata de los DXX, en su logar lo envía como G01.
En pantalla lo hace bien, en conector lo hace chueco.

**Comment by RigoFlores** [comment]
Me están presionando mucho con este issue.
Es para conector... debe quedar una versión de pruebas para ACO, así como para producción.
Lo que se subió ayer para pruebas busca el formato optibelt.

**Comment by jccastillo0007** [comment]
chiaaaa, después de hacer circo maroma y teatro para timbrar desde conector con mi rfc en producción...
El resumen es que no pude usar ningún DXX, porque se esta validando que el uso del CFDi sea coherente con el RFC y con el régimen  y como estaba tratando de usar el rfc de la  TIA como receptor, pues no aplica ningún tipo DXX
Pero cabe se;alar que aunque no se timbraba, veia en el log el xml y si enviaba el uso de CFDi DXX.
Con lo que si pude timbrar fue con el uso de cfdi P01.

 <cfdi:CfdiRelacionados TipoRelacion="04">
        <cfdi:CfdiRelacionado UUID="DC2D674B-92DC-47B8-B2C8-12CF1E9EA0EB"/>
    </cfdi:CfdiRelacionados>
    <cfdi:Emisor Rfc="CAAJ7506072P2" Nombre="Juan Carlos Castillo Alvarez" RegimenFiscal="612"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="COPPEL, S.A. DE C.V. ." UsoCFDI="P01"/>

**Comment by RigoFlores** [comment]
Aquí tenemos un problema... para empezar no podemos tomar nuevamente una decisión de cambiar datos de la factura, eso ya de entrada es grave.
La otra, es como te decía también con el pedimiento, si no jala, buscarle porque no. Necesitamos investigar cuál es la combinación adecuada.

Solo para entender, cómo quedó este asunto????? porque veo que SIGUE CAMBIANDO EL USO, cuando debería marcar error y no hacer la factura. 
Ahora, cuál es el mensaje que regresa el PAC???

**Comment by RigoFlores** [comment]
el uso del CFDI en el texto plano, traía espacios al final de la línea... no se que hacía internamente pero lo interpretaba como G01.
