### ISSUE TITLE
Escritorio - truncar la descripción a 999 caracteres en el XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1258]
Resulta que ahora, no sé no recuerdo porque... la descripción que llega al XML es la descripción del catálogo de producto + la informacion complementaria.
En facturas de gobierno, la información complementaria puede llegar a mas de 2,000 caracteres.
El límite del SAT para la descripción en el XML es de 1,000 caracteres.
Entonces lo podemos mantener así, con la salvedad de truncar o validar que la descripción no rebase la longitud.

2018-01-24 12:32:46,416 DEBUG [AWT-EventQueue-0] (CFDiWSClient.java:74) - 4216
2018-01-24 12:32:47,553  INFO [AWT-EventQueue-0] (CFDiWSClient.java:77) - Factur
aTi ack : com.facturati.ws.binding.jaxb.Ack@ff5996[code=003,description=XML mal
formadoElement '{http://www.sat.gob.mx/cfd/3}Concepto', attribute 'Descripcion':
 [facet 'maxLength'] The value '100 FOLIOS PAGO CORRESPONDIENTE A LA ESTIMACION
4 (CUATRO) FINIQUITO REFERENTE AL CONTRATO DE O]

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
NEGATIVO, NO JALÓ Y YO ME COMPROMETÍ A ENTREGAR HOY ESE FIX....
QUE HACEMOS???

**Comment by RigoFlores** [comment]
EN ESTA IMAGEN LOS 00000 EMPIEZAN A PARTIR DE 1001 CARACTERES DE LA INFORMACIÓN COMPLEMENTARIA, ESO SIN TOMAR EN CUENTA LA DESCRIPCIÓN ESTÁNDAR...

<img width="423" alt="descripcion" src="https://user-images.githubusercontent.com/2912775/35390355-bcc45bb0-01a0-11e8-9f44-ae4391cbfadb.PNG">

**Comment by jccastillo0007** [comment]
listo... ya lo probé.

Debes usar todo el zip que subí no solo el jar de facturat, porque el fix no esta en ese jar.

**Comment by RigoFlores** [comment]
Jamás hago eso, excepto cuando tu me dices que así lo hago... borro todos los jars y sustituyo los nuevos..

**Comment by RigoFlores** [comment]
y ahora si ya lo hizo... digamos que quedó a 997, pero no hay pexcado....
