### ISSUE TITLE
Super conector optibelt - formatear el dato de pedimento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1259]
del dato que se toma del archivo de texto, referente al pedimento formatearlo de la siguiente manera:

2 digitos + 2 espacios + 2 dígitos + 2 espacios + 4 decimales + 2 espacios + el resto del campo

si el resto del campo mide 6 decimales, repetir el último decimal.

esta última regla, seguramente se modificará, pero no me han definido como quedará, y tienen la facturación detenida para variar...

ejemplo:
original:
104738078003832

formateado:
10  47  3807  8003832

En ese ejemplo los últimos números son 7, pero habrá casos que no. entonces se deberán completar ocn el último dígito (por lo pronto)

**Comment by RigoFlores** [comment]
el lunes tendré una junta para que me indiquen como manejar el tema que el número de pedimento no venga completo... puedes enviarme un listado con las distintas longitudes que han incluido el número de pedimento el año pasado pls??

**Comment by RigoFlores** [comment]
Se acordó que se va a formatear así como lo pedí originalmente, asegurando ellos que la longitud es correcta.
OJO, son 2 espacios en cada hueco.

original:
104738078003832

formateado:
10  47  3807  8003832

**Comment by RigoFlores** [comment]
ya no supe cuál es la versión correcta para producción y si existe alguna para pruebas. 
me comentas?

**Comment by RigoFlores** [comment]
voy a tener una versión de pruebas de optibelt???
o cómo puedo validarlo???

**Comment by jccastillo0007** [comment]
hoy subo una versión de pruebas para optibelt con el rfc ACO... la marcaré como Optiblet.zip
