### ISSUE TITLE
No respeta la configuración del correo en el envío del correo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1261]
Tanto en web como en escritorio, debemos tomar la cuenta de correo, cuando esta es personalizada, para que sean enviados los correos.
Tuve que dar regresión en figueacero a los últimos fixes, porque el envío desde sendegrid, con la cuenta noreply, no estaba jalando (tenía muchos rebotes).
Necesitamos tomar de la configuración o del properties, la cuenta de email, para que se ponga en sendgrid como la cuenta de envío....

**Comment by RigoFlores** [comment]
Ya urge esta solución tanto para web, como escritorio.

**Comment by jccastillo0007** [comment]
osea quieres que se pueda configurar en algún lugar la cuenta que aparezca en el correo como de quien envía el correo ?

**Comment by jccastillo0007** [comment]
que quieres decir con que muchos rebotes de sendgrid

**Comment by RigoFlores** [comment]
actualicé figueacero...  enviaba los correos desde sendgrid, con la cuenta de no reply... pues no sé porque razón, marcaba error en casi todos los correos... que la dirección estaba incorrecta o algo así... el punto es que marcaba errores... al darle regresión, dejó de marcar los errores.... figueacero ahora mismo, envía desde una cuenta de ellos....

**Comment by jccastillo0007** [comment]
mmmm entonces este problema es solo por la cuenta de figueacero ?
ubicas un email para buscarlo en sendgrid y ver que enviaba

**Comment by RigoFlores** [comment]
no, no lo recuerdo...
el tema no solo es de figueacero.... si logro probar como satisfactorio el envío desde sendgrid, con la cuenta del cliente (y sin pedirle contraseña, ni configuración), eso si será un madrazo....
por lo pronto, optibelt ya lo espera...
lo que me comentó el proveedor del hosting, es que con sendgrid, efectivamente puedes ocupar cualquier cuenta como 'la origen', pero realmente quién lo envía es sendgrid, con su servidor/parámetros smpt... lo cual implica, que podríamos definir 'cualquier cuenta origen' para cada cliente, y eso sería BASTANTE DESEABLE.... 

conclusión, tenemos que leer la cuenta personalizada del cliente, y enviar los correos como si fuera 'la cuenta de correo origen'.....

**Comment by jccastillo0007** [comment]
asi es, asi funciona sendgrid, crei que eso ya habia quedado claro...

ok, entonces leemos una cuenta de email del properties de standalone y esa cuenta será usada para el from del correo , eso es lo que se esta solicitando

**Comment by jccastillo0007** [comment]
Antes de hacer ese relajo... hagamos una prueba.

Acabo de configurar la cuenta : facturacion@factura-t.com.mx 
como cuenta para envios de correos... podemos actualizarle a figueacero para revisar como funciona... a mi se me hace que mas bien figueacero puede tener filtros de spam por cuentas noreply....

**Comment by RigoFlores** [comment]
negativo, la consola decía que enviaba desde el noreply, aún con la cuenta configurada de figueacero...
esto no solo es para escritorio, sino también para web...

**Comment by RigoFlores** [comment]
es decir, si se solicita que la cuenta leida del properties (escritorio) o pantalla de configuración (web) sea utilizada para el from cuando se envia desde sendgrid

**Comment by jccastillo0007** [comment]
si, entiendo eso de que no pelaba los datos de la cuenta configurada... 

el tema es que tiene otras implicaciones, ya que ahorita nos interesa solo el email a utilizarlo como emisor del correo, pero esos datos tienen otras validaciones para cuando realmente quieren utilizar su servidor de envio de correos smtp..

**Comment by RigoFlores** [comment]
eso de que realmente quieran utilizar su servidor de correos, con el sendgrid entiendo que ya no se ocuparía... podemos comentar ese código y guardarlo para el caso que el sendgrid no nos funcione, o para algún caso particular... de la configuración solo se pide tomar la cuenta de correo origen y descartar el resto de los datos...

**Comment by jccastillo0007** [comment]
yeap, eso es justo lo que esta medio delicado.. ya que el código de envío de correos se usa en varios lugares, y se validaba la info de que usaran su propio servidor... tons, no es tan transparente... podemos hacer la prueba con el nuevo email antes de

**Comment by jccastillo0007** [comment]
subi un release a dropbox con el tema del nuevo correo...

**Comment by jccastillo0007** [comment]
esto es para standalone.

**Comment by RigoFlores** [comment]
Este issue se refiere a que tome la configuración del correo personalizado (web o escritorio), y que utilizando el servicio smtp de sendgrid, envíe los correos.
En resumen, lo que ya hemos platicado el sábado pasado.

**Comment by jccastillo0007** [comment]
listo... lo acabo de probar en PRU con y sin cuenta configurada y funciona correctamente

**Comment by RigoFlores** [comment]
validé en escritorio y no toma cualquier correo... supongo que ahí no está implementado... y si está haciendo falta...

**Comment by RigoFlores** [comment]
Si jaló en escritorio, pero no jaló en web... le puse un correo x, cuenta inexistente y no jaló...
