### ISSUE TITLE
DRP - aceptar pagos de facturas en versión 3.2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1263]
Los datos que van a nivel de detalle, en el DRP, que ahora también es llamado por el sat como RECIBO ELECTRÓNICO DE PAGO (REP).

OJO. Estos datos son a nivel detalle del REP (ya que también lleva un header), a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, a nivel detalle, 

UUID
Serie
Folio
moneda
metododepago .- la guía de llenado del REP indica 

> Se debe registrar la clave PPD (Pago en parcialidades o diferido) que se registró en el campo MetodoPago del documento relacionado.

numero de parcialidad
importe saldo anterior
importe pagado
importe saldo insoluto.

Estos últimos 4 datos no se toman del XML pagado. 
Los primeros 5 datos se toman del XML pagado, y tendrá que considerarse que pueden ser de la 3.2 o 3.3

**Comment by jccastillo0007** [comment]
que dijo ....

**Comment by RigoFlores** [comment]
cuando emites un DRP...  desde la pantalla de CXC-Ingresar cobro..... capturas varias datos, pero al final seleccionas una factura o varias facturas, que son las que se están pagando... de esa una o varias facturas, tomas algunos datos que se reportan a nivel de detalle dentro del DRP... esos datos son los mencionados anteriormente... esos datos se podrían tomar de un xml v3.2 o de un xml v3.3, lo cual implica que tienes que identificarlos para una versión o para otra...

**Comment by jccastillo0007** [comment]
ya quedamos que solo se soportaran cfdi versión 3.3

**Comment by RigoFlores** [comment]
yo creo que de alguna u otra manera, tendremos que soportar la 3.2
Y eso sería con una pantalla adicional seguramente... por lo pronto lo cierro, pero es muy probable que se tenga que retomar el tema.
