### ISSUE TITLE
Addendador MABE - realizar ajustes de location y versión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1264]
Mandé un correo:

Proveedor, es necesario realizar los siguientes cambios a su XML:
1.	La liga marcada de verde colocarla en la sección de complemento de su XML
2.	Eliminar las ligas marcadas de azul ya que estas pertenecen al nodo complemento y ya están en el mismo
3.	Colocar la liga correcta para la versión 3.3 ya que la marcada con fuchsia es de la versión 3.2

A este cliente le super urge

**Comment by RigoFlores** [comment]
lo que no entendí, es porque modificamos a como viene el XML original.
Yo esperaría que solo se agregara la sección de addenda y eso es todo. Porque trastocar el xml original???

**Comment by jccastillo0007** [comment]
asi es como lo regresa facturehoy... no puedo modificarlo...  
el punto 3 esta muy raro... asi lo generamos ? facture hoy marcaria error no ?

**Comment by RigoFlores** [comment]
creo que si lo estamos generando así, pero solo en el addendador... recuerda que esto es a nivel addendador... ahí no interviene facturehoy para nada

**Comment by jccastillo0007** [comment]
a pues si encontre algo en el addendador... ya quedó en PRU y PRO.
