### ISSUE TITLE
optibelt - envía invertida el forma y el método de pago en el servidor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1265]
en el conector está OK, pero en el servidor lo invierte

**Comment by jccastillo0007** [comment]
mmm ya lo habia arreglado... lo viste hoy en producción?

**Comment by RigoFlores** [comment]
no lo he revisado... como le dí regresión al último cambio en escritorio, no estaba seguro.
Entonces, es independiente una cosa de la otra???

**Comment by jccastillo0007** [comment]
si, ese error se corrigió en el servidor.
