### ISSUE TITLE
Conector - el precio unitario no lo está respetando en todos los casos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1268]
Comentaba que en la frontera se facturan cantidades en miles, pero precios unitarios ridículamente pequeños (por volumen)
Tenemos un caso que el precio unitario es 0.001, pero se facturan miles de piezas, pero la aplicación no respeta el precio unitario y lo envía como 0.00, y con ello se genera un error.
Me mandaron un xml de otro proveedor donde si se respeta el precio unitario.
Te mandé un correo con el XML del otro proveedor.

**Comment by jccastillo0007** [comment]
fixed release de hoy... le puse version 11.0.3

**Comment by RigoFlores** [comment]
lo del precio unitario a 3 o mas decimales, solo lo aplicaste al conector, o también a la pantalla?
aún no lo veo arriba, pero supongo que en cualquier momento aparecerá ...
esto puede significar abrir la caja de pandora.... tsss
