### ISSUE TITLE
Optibelt - subir los XML y PDF, y empatarlos con número de cliente y CxC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1269]
Optibelt ocupa el número de cliente para asociarlo a su cartera de vencidas o vigentes o pagadas.
Las facturas que te envié por correo son las que dejaron de subirse en una versión que instalamos en optibelt y que dejó de subir la info al web.

**Comment by jccastillo0007** [comment]
listo.

**Comment by RigoFlores** [comment]
Faltaron del folio 181060832 a la 181060980 y también falta la NC 183002508

**Comment by RigoFlores** [comment]
lo esperan de manera urgente ....

**Comment by jccastillo0007** [comment]
ups... no ma... no se como pero se me olvido... ya estan.

**Comment by RigoFlores** [comment]
faltó actualizar su fecha de vigencia... en condiciones de pago, viene un número... ese es el número de días que hay que agregar a la fecha de emisión, y actualizar como fecha de vencimiento...

**Comment by jccastillo0007** [comment]
done... bendito mysql
