### ISSUE TITLE
DURANTE EL PROCESO DE CANCELACIÓN MOSTRAR UN INDICADOR QUE ESTÁ TRABAJANDO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#127]
ALGO SIMILAR A CUANDO ESTÁ FACTURANDO, ES DECIR UN ICONITO DANDO VUELTAS QUE INDICA QUE ESTÁ EN PROCESO DE TIMBRADO.
EN ESTE CASO EL ICONO INDICARÍA QUE ESTÁ EN PROCESO DE CANCELAR

**Comment by jccastillo0007** [comment]
fixed
