### ISSUE TITLE
Escritorio - en exportar resultados de consultas de facturas, agregar campos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1270]
al final del excel, agregar la forma de pago, método de pago y uso de CFDI

**Comment by RigoFlores** [comment]
me lo siguen esperando

**Comment by jccastillo0007** [comment]
listo.
La mala noticia es que noté que no se estaba salvando el uso de cfdi en la base de datos...

**Comment by RigoFlores** [comment]
si ya vi.
Hoy generé una factura y en el reporte aparece todo junto en una misma celda: uuid, método de pago, forma de pago, y uso de cfdi. Hay que separarlo en distintas columnas.

1E155039-FC39-46FA-814C-BFF8B877643CPPD02D10.Pagos por servicios educativos (colegiaturas)

**Comment by jccastillo0007** [comment]
ups
fixed

**Comment by RigoFlores** [comment]
En la columna de forma de pago, algunos los reporta como 

03.TRANSFERENCIA ELECTRONICA DE FONDOS

y otros como:

2 o 99

es decir, solo el número sin cero a la izquierda, ni descripción de la forma.
Creo que hay que homologar de una u otra manera, pero que sea igual.

**Comment by jccastillo0007** [comment]
crap.... asi es como esta salvado en la base de gatos....

quieres que se homologue solo en el reporte de excel verdad ?

**Comment by jccastillo0007** [comment]
listo... ya le puse esa validación
