### ISSUE TITLE
Web - en consultas exportar, agregar campos al reporte en excel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1271]
al final del excel, agregar forma de pago, método de pago, uso de cfdi y UUID

**Comment by RigoFlores** [comment]
lo siguen esperando.... desde hace 20 días...

**Comment by jccastillo0007** [comment]
Mas que el tiempo del ticket, yo me administro por prioridades, hay que definir EN EL TICKET, la prioridad

**Comment by RigoFlores** [comment]
si se ocupa la prioridad, pero tendría que ser a nivel de cada issue, y no dentro del issue.
Igual y genero 3 tipos de label que indiquen la prioridad de los issues... pero que la prioridad quede dentro de la descripción del issue, no lo veo mu funcional
