### ISSUE TITLE
Addendador Pilgrims - le está enviando el schema de la 3.2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1273]
http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd
Lo que no me queda muy claro es porque tiene que modificar esa parte...
Supongo que todos los addendadores están igual..??

<?xml version="1.0" encoding="UTF-8"?><cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Certificado="MIIF9jCCA96gAwIBAgIUMDAwMDEwMDAwMDA0MDM4ODEzNzQwDQYJKoZIhvcNAQELBQAwggGyMTgwNgYDVQQDDC9BLkMuIGRlbCBTZXJ2aWNpbyBkZSBBZG1pbmlzdHJhY2nDs24gVHJpYnV0YXJpYTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMR8wHQYJKoZIhvcNAQkBFhBhY29kc0BzYXQuZ29iLm14MSYwJAYDVQQJDB1Bdi4gSGlkYWxnbyA3NywgQ29sLiBHdWVycmVybzEOMAwGA1UEEQwFMDYzMDAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBEaXN0cml0byBGZWRlcmFsMRQwEgYDVQQHDAtDdWF1aHTDqW1vYzEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMV0wWwYJKoZIhvcNAQkCDE5SZXNwb25zYWJsZTogQWRtaW5pc3RyYWNpw7NuIENlbnRyYWwgZGUgU2VydmljaW9zIFRyaWJ1dGFyaW9zIGFsIENvbnRyaWJ1eWVudGUwHhcNMTYxMDA2MTcwOTIxWhcNMjAxMDA2MTcwOTIxWjCBljEaMBgGA1UEAxMRUkFVTCBKVUFSRVogTE9QRVoxGjAYBgNVBCkTEVJBVUwgSlVBUkVaIExPUEVaMRowGAYDVQQKExFSQVVMIEpVQVJFWiBMT1BFWjEWMBQGA1UELRMNSlVMUjYyMDgyMjYxMTEbMBkGA1UEBRMSSlVMUjYyMDgyMkhRVFJQTDA3MQswCQYDVQQLEwIwMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJYD8pdg5VT2QW3E60TIewBXcbjRlRAsO5bH4rIkHtEdi7QC840igj+IGLnz6a3bEmu+T8YTL3WQyMa4VBxNB3SJvCYsbXeOA3SjhlZ1mdygkjsbYItuixYJMQvEF8KpE1TX7dL3herrWI1ed0n0vZXJQvhWpI9ylAY3BsZ29iyWrdqkt36DiWdV9Tp0nqCg0Z/m5E0OfsuSWA4IY5YTRfAFJDCPxSsIA+f2o7J/EZN5uv5I9AwC+MnCF9l68hGYu4toECPG+4+LPqPZrtk9yePy+WVL/GhkOujb0+ufzPqtZ6rDCC7550DAEsNqXX4XtVPG90K4I1PtKMC9HcicapECAwEAAaMdMBswDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCBsAwDQYJKoZIhvcNAQELBQADggIBAE4SDYrLwRqYBBGvdFgoKOdRzHzI6As5j/jr7RNzUuCeEdpHR/yTSDCJJfSg/rVrKasad95Tn1zUhzywcGM/79WUadCUAMgbKwrgyKgS1jIQp74E3CKwLevusRGXbjFovZGH86TwqKKgZBvFDl+hjykHVNyYD7welemlwH1WFP7b7eK0BpkKj0+c2VGV7wRWzR7QGTO7s4bd/78v/iO9rBH/5gi7BXf3cXScwV4oYq31N4ISf2j2nmlcDHfSQX3mCn474x+iNcrMH/Whg6JF58yqVHrsXWnODbohYZJcpBvwkrxnMlj57mjQsj0I6buAADwnLeEk0HjcbhOlQ12OV2oA06BHxwZ/14FpN4ZNZQlL0U/3b0BVmohqjjF/Nv8O6LpyTDMUwrS5hVs/GVmxwmWN2FENQ5dNDbJCYrcEyV5pcZfvqXUxSf1Sz6XFwFoO9hjTNlSHod1QuYhNhXbFEGfuBMYJ6S3af5H71Tf91xo9LA5rEn9ZHdRlxmEGH+ktGTUpznY6ThmWtvCntFYZlnOyt2JRDH1Tr3Vkmdj57NO10dZl9VJEFFUaJ3WHr4Q+yKtsaNy8S77uM42A2P1uRKL9wxmiwKdrM8ZyR81upMPOiIDfbfD89PGaDAK3KhU0k11vChjQld6gJZr/R502H0ezgRGg0HAh0Tl3gRbhc9I+" CondicionesDePago="CONTADO" Fecha="2018-02-01T11:11:05" Folio="3815" FormaPago="03" LugarExpedicion="76130" MetodoPago="PPD" Moneda="MXN" NoCertificado="00001000000403881374" Sello="NC8jBPh3N7+racyUNtORCdJum4E2ccVf/d4Za1TnYdRELl7xANlwwm8N2g153gi/Mh8d86M7FBNEJjJBzS2yQ0hb3jsTNhmfE3owS7GAoazsByx/pgHpSx04WIgTyMDApQg+oDC8pDdBtw9aKMs2UdQe9Dpyx4PUvhiEOI40PTxyrfudoZFP60M7DTADZAJ609fmMo1shN8aY8lVUaZ0ob1Utz0iAOpXPHVlqrr1qJ6C1vCPMeE0Q/KE+Lsmi8icC8oeG0XNBOZn1XzeQJQYXEYYc0kUtyGkP2XaAiYCFGCxU9/w9pVUtp4ivLzP+Z0x0K+a6Bgsnm41cdy4RgfOLg==" SubTotal="10500.00" TipoCambio="1" TipoDeComprobante="I" Total="12180.00" Version="3.3" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/TimbreFiscalDigital/TimbreFiscalDigital.xsd">

**Comment by RigoFlores** [comment]
favor de revisar la addenda pepsico también... ya nos pagó la actualización un cliente

**Comment by jccastillo0007** [comment]
de hecho, cuando corregí el addendador para Mabe, se corrigió para todos los que usan addendador.
