### ISSUE TITLE
CxC - Ingresar cobro - no permite filtrar por número de cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1274]
En optibelt particularmente se ocupa un mismo RFC de cliente para varias sucursales.
De ahí que trabajan con el nombre alterno y un número de cliente distinto para cada sucursal y matriz.

Cuando vas a ingresar un cobro solo te permite filtrar por RFC, pero si le capturas también un número de cliente, marca error cuando le indicas que registre el cobro.

**Comment by RigoFlores** [comment]
Lo que se necesita es que permita filtrar por RFC, o por RFC + número de cliente

**Comment by RigoFlores** [comment]
esto es para optibelt, lo están esperando.

**Comment by RigoFlores** [comment]
que para cuándo?

**Comment by jccastillo0007** [comment]
te mando unas pantallas por email... lo hice con el RFC XEXX... sin número de cliente, y con  2 números de clientes y me filtro todo bien... chiaaa

**Comment by jccastillo0007** [comment]
ya también puede filtrar por número de cliente nada mas
