### ISSUE TITLE
AGREGAR UN REPORTE AL KEYGENERATOR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1275]
NECESITO UN REPORTE DE LAS RECARGAS, CON LAS COLUMNAS SIGUIENTES:

SE PODRÁ SOLICITAR EL REPORTE EN UN RANGO DE FECHAS (DE ACTIVACIÓN) CON LA OPCIÓN DE COMBINARLO POR DISTRIBUIDOR, POR RFC, ASCENDENTE O DESCENDENTE
 
Columnas:

DISTRIBUIDOR, FECHA DE ACTIVACION, FECHA DE ULTIMA FACTURA, # FOLIOS ACTIVADOS, # FOLIOS RESTANTES, NOMBRE, RFC, CORREO, TELÉFONO, CONTACTO

**Comment by jccastillo0007** [comment]
el reporte que ya genera el key generator tiene todo lo que buscas, excepto el tema de distribuidor, correo, telefono y contacto... se lo voy a agregar... pero ya te mande por correo el resultado del query de distribuidores,

**Comment by RigoFlores** [comment]
negativo, el reporte actual contiene mas columnas... eso es lo de menos... peeeero

- solo incluye la última recarga de cada RFC
- no muestra filtros requeridos para generar el reporte
- no incluye la columna de distribuidor

**Comment by jccastillo0007** [comment]
ya casi tengo el reporte....

**Comment by jccastillo0007** [comment]
listo, lo subi al dropbox
falto la fecha de última factura...

**Comment by RigoFlores** [comment]
como que lo subiste, que no se genera desde el key generator?
O donde lo busco?

**Comment by jccastillo0007** [comment]
chiaaaa
se llama reporte de folios.csv y esta dentro de la carpeta de FacturaT

**Comment by RigoFlores** [comment]
Aquí el contenido de dropbox de hace un momento, no hay nada, actualizado al día de ayer... voy a actualizar en este momento el drotbots...
<img width="586" alt="antes de actualizar" src="https://user-images.githubusercontent.com/2912775/36157893-819e0d6a-10a0-11e8-82ad-7a1d1d45220c.PNG">

**Comment by RigoFlores** [comment]
oye, pero ya puedo generarlo?
según yo no, o no vi donde...

**Comment by jccastillo0007** [comment]
noup... solo por medio de un par de queries y hacer un merge en excel... que fue lo que te pase

**Comment by RigoFlores** [comment]
ok, en espera...

**Comment by jccastillo0007** [comment]
listo... ya esta en PRU... ma;ana lo subo a PRO

**Comment by jccastillo0007** [comment]
en el key generator, en la opción de Reporte de Folios... hasta abajo aparece una opción que dice: Reporte de Recargas... y listo.

El filtrado por fecha o por lo que quieras, ya mejor lo haces en excel...

**Comment by RigoFlores** [comment]
Hay que eliminar las comas ',' de los nombres de cliente porque recorre las columnas y no arroja los resultados confiables.
También algunas fechas no tienen el mismo formato y tampoco se ordenan correctamente.

**Comment by jccastillo0007** [comment]
ya le quite las comas... hice una validación de la fecha, pero la verdad sabe porque salen diferentes... chiaaa

**Comment by RigoFlores** [comment]
es posible que estén guardados con distinto formato en la BD?

**Comment by jccastillo0007** [comment]
si, ya que hemos dado de alta folios a manita, y luego con el key generator... luego los actualizo a un solo formato

**Comment by RigoFlores** [comment]
tons nos esperamos a que se homologue el formato de fecha, para que cierre este issue.
No vayamos a pegarle a las validaciones de folios disponibles y vencimiento, etc.

**Comment by jccastillo0007** [comment]
Oye, estaba revisando el excel... y resulta que la info si esta bien... es solo el pinche formato que por sus huevos excel le da a algunos datos...

Si te colocas en una celda con el formato equivocado, y si ves el contenido real, si tiene el formato correcto.

Solo tienes que formatear el formato de las columnas de fecha y ya excel lo va a acomodar bien

Suena medio raro, si quieres lo vemos por teléfono y te voy diciendo

**Comment by RigoFlores** [comment]
ahí lo voy revisando...
