### ISSUE TITLE
CONECTOR - INCLUIR LOS NUEVOS ESCENARIOS DE ERROR EN EL LOG DE ERROR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1277]
El conector, cuando tiene errores, genera un archivo de salida con extensión log o algo así.
En figueacero se están generando algunos errores, que al ser nuevos supongo yo, no se reportan en el archivo de error, y entonces yo tengo que estar buscando donde está el problema.
Imagínate si vamos a estar así. Ellos no corrigen en tiempo real, yo tengo que estar validando archivo por archivo sus errores, y lo peor... el cliente puede estar volteando a ver otras opciones.

De los errores que he detectado con ellos al momento son:
RFC inexistente en el SAT
La suma de importes no coincide

Es decir, el error que se presente en la consola, motivo del NO PROCESAMIENTO DEL ARCHIVO, tiene que incluirse en el archivo de error de salida del conector, esos que tienen extensión errorlog.

**Comment by jccastillo0007** [comment]
si, eso estaria bien... pero lo malo es que la función que genera ese error, no tiene comunicación con el conector, y pues no se puede asi como esta implementado... voy a tener que hacer algunos cambios

**Comment by jccastillo0007** [comment]
done... checale con la versión de hoy, tambien hice unos cambios en web.. para que ayude a ver el mensaje real..
