### ISSUE TITLE
Recibo electrónico de pago (antes DRP) - agregar leyenda en el campo cuenta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1278]
Se le llama de distintas manera, pero según yo quedará finalmente el recibo electrónico de pago (REP).
En el campo del número de cuenta, tanto para receptor (catálogo de clientes), como para emisor (configuración), agregar la leyenda:

(10 a 50 caracteres)

y validar que lo capturado cumpla con dicho requisito.

**Comment by jccastillo0007** [comment]
done... y directo a PRO pa que no digas.

**Comment by jccastillo0007** [comment]
creo que algo paso en la pantalla de configuración y no estavalidando el tama;ao de la cuenta... hoy lo checo

**Comment by RigoFlores** [comment]
hay algo importante en la captura de la cuenta de los clientes.
Resulta que dependiendo de la forma de pago, es la longitud específica de la cuenta.
Para las siguientes formas de pago, esas son las longitudes correctas:
Transferencia:  10, 16 o 18 
Cheque:  11 o 18
Tarjeta crédito o débito: 16
Tarjeta de Servicios: de 15 a 16.
Efectivo: no aplica
Ayer estaba generando un video tutorial y brincó un error inmediatamente.
No me quiero imaginar los errores ya con todos los clientes generando los REP's

Para reducir el número de errores y su consecuente llamada de soporte, hay que aplicar las validaciones arriba mencionadas, al momento de elegir la forma de pago del REP, que son las mas comunes.
Para las cuentas del emisor (cliente nuestro), hay que forzar a que sean 18, es decir que siempre se capture la CLABE, que no?
Cómo la beisbol de las grandes ligas?

**Comment by RigoFlores** [comment]
también hay que quitar la validación que se capture la cuenta bancaria a huevo en el catálogo de clientes. Hoy generó al menos 10 llamadas

**Comment by jccastillo0007** [comment]
porque obliga a que sea la claBe? no veo porque no puedan capturar otra cuenta

**Comment by jccastillo0007** [comment]
ya quite la validación de que debe existir la cuenta... solo la va a validar si existe el rfc, es decir, si realmente quieren dar de alta una cuenta.

**Comment by RigoFlores** [comment]
la clabe se captura, para asegurar que no marque error en la cuenta del emisor.
La validación debe quitarse de TODO LO QUE TENGA QUE VER CON CUENTA... hay clientes en el catálogo, que nunca recibirán un documento de pago... entonces, no tenemos que forzar a que capturen una cuenta...

**Comment by jccastillo0007** [comment]
con respecto al emisor, mi comentario va enfocado a que no necesariamente debe ser la clabe, si no  que sea entre 10 y 50 caracteres

**Comment by RigoFlores** [comment]
tengo que hacer pruebas con los números de cuenta del emisor

**Comment by RigoFlores** [comment]
ya ví, no acepta cualquier número de 10 a 50, como dicta la spec.... hice la prueba con 13 y marcó error ... chiaaa.

Esa leyenda debe indicar algo así como un cuadro:

Forma de pago: longitudes válidas
Transferencia: 10, 16 o 18
Cheque: 11 o 18
Tarjeta crédito o débito: 16
Tarjeta de Servicios: de 15 a 16.

**Comment by jccastillo0007** [comment]
La validación de longitud ya esta hecha... incluso ya no pide la cuenta de forma obligatoria, solo la va a validar si capturan el RFC del banco y la cuenta no...

Tranquilo con los mensajes de error... no mostramos cuadros solo mensajes de error en rojo...

Si quieres agrego esas condiciones a un costado del campo No. Cuenta

**Comment by RigoFlores** [comment]
Si, esa leyenda que quede a un lado del número de cuenta, eso nos evitará muchos soportes...

De hecho, ya quitando la validación, se eliminaron 10 llamadas diarias al menos.
