### ISSUE TITLE
A todos los clientes en web, agregar el módulo de CxC en caso que no lo tengan

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1279]
Por query, ya tenemos que abrir ese feature a todos los clientes QUE ACTUALMENTE NO LO TENGAN , ya que lo estoy haciendo a manita y ya no tiene sentido.

OJO: no se tienen que perder los features actuales. ES ADICIONAL A LO QUE YA TENGAN.
UN SEGUNDO OJO: en caso de se le active CXC por query, favor de crear también por query también la serie PAGO con folio inicial 1.

**Comment by jccastillo0007** [comment]
noup, no se puede por query... ni habilitar el CxC ni la serie pago... 

lo de CxC no se puede porque hay que respetar lo que quiera que tengan previamente
la serie pago, no se puede porque si bien es solo un query, se debe aplicar solo para los que no tengan la serie creada actualmente.

**Comment by RigoFlores** [comment]
OK, si no es posible habilitar por query, entonces quitar la validación en la aplicación para que lo muestre solo en caso que lo tenga configurado y en su lugar que lo muestre siempre.
Lo de la serie, para cada RFC emisor, en caso que no existe, se crea con folio 1. Si bien no se puede por query, entonces hay que hacer un pequeño desarrollo que agregue dicha serie.
Queremos agilizar las cosas, recuerda que tenemos cientos de clientes en web y configurar este tema para todos ellos, será mucho trabajo.


De hecho, ya voy a lanzar la promoción donde facturas, notas de crédito, nómina y REP son incluidos en la contratación inicial. Con ello, queremos hacernos de mas clientes, y fomentar que los actuales, ocupen servicios adicionales y consuman folios.
Es decir, la configuración estándar debe habilitar facturas, nómina y REP.

**Comment by RigoFlores** [comment]
a) quitar la validación para que siempre muestra CxC
b) al dar de alta un cliente, siempre habilitar CxC.

Con eso se atiende este issue.

**Comment by jccastillo0007** [comment]
la a) no es posible, pues le doy en la madre al sistema de seguridad, ya que aunque tuvieran acceso a la pantalla, al momento de usarla también se valida que se tengan los privilegios

la b) si es posible, voy a checar el key generator

**Comment by jccastillo0007** [comment]
opción b done.

**Comment by RigoFlores** [comment]
En la siguiente llave nueva, validaré el punto (b).

**Comment by RigoFlores** [comment]
También le asignó lo de CxP.
Solo se requiere CxC

**Comment by RigoFlores** [comment]
Cada vez mas clientes hablan para que se les habilite lo de CxC.
Cuando sean todos será una chinga.
No lo puedes agregar al KeyGenerator? Es decir para editar clientes y desde ahí habilitarlo.

**Comment by jccastillo0007** [comment]
Done, cualquier update que hagas, va a verificar si ya tiene CxC, si no lo tiene, lo agrega.

También ya le quite lo de CxP

**Comment by RigoFlores** [comment]
negativo, sigue igual.
Hice un update en un cliente, y no le apareció la opción de CxC

**Comment by jccastillo0007** [comment]
es que no lo subi a PRO... pero hoy lo subo

lo checaste en PRU? (yo si)

**Comment by jccastillo0007** [comment]
siempre no, algo paso y no jalo en PRO, tons le di rollback

**Comment by jccastillo0007** [comment]
listo ya esta en PRO

**Comment by RigoFlores** [comment]
Me parece que solo agregó en el role lo de "CXC", pero al parecer también se ocupa que se agregue lo de DATOS_EXTRA en los plugines. Es correcto?
A este RFC le dí update en el keygenerator.

mysql> select * from Users where client_id in (select id from Client where rfc = 'LCS071210ARA');
+----+--------------+----------------------+--------------+-----------+--------+
| id | password     | role                 | userId       | client_id | emails |
+----+--------------+----------------------+--------------+-----------+--------+
| 50 | LCS071210ARA | ["ADMIN","CxC_MENU"] | LCS071210ARA |       145 | NULL   |
+----+--------------+----------------------+--------------+-----------+--------+


mysql> Select * from ClientPlugins where owner = 'LCS071210ARA';
+------+----------+--------------+
| id   | features | owner        |
+------+----------+--------------+
| 2479 | []       | LCS071210ARA |
+------+----------+--------------+

**Lo que se ocupa por lo pronto, es que me indiques exactamente que se requiere para que se pueda emitir el documento de pago.**

**Comment by RigoFlores** [comment]
no entendí por que se cerró. 
Preguntaba que me indicaras exactamente que es lo que espera para que si incluya el documento de  pago en el XML?
Según yo además del menú de CxC, ocupa al menos datos extra.

**Comment by jccastillo0007** [comment]
negativo... no se ocupan datos extras... lo que si se ocupa son datos de addenda, pero eso se habilita al tener cualquier complemento o addenda.

en este caso, se habilita con CxC Menu

**Comment by RigoFlores** [comment]
No le afecta que tenga duplicado lo de nómina? Es que tomé el registro del cliente, y simplemente le dí guardar para que se agregue el menú de CxC. Y si lo agregó, pero duplicó el feature de nomina:

mysql> select * from Users where client_id in (select id from Client where rfc = 'AAN130315FN3');
+------+--------------+----------------------------------------------------------------+--------------+-----------+--------+
| id   | password     | role                                                           | userId       | client_id | emails |
+------+--------------+----------------------------------------------------------------+--------------+-----------+--------+
| 1379 | AAN130315FN3 | ["ADMIN","CONFIG_NOMINA_MENU","CxC_MENU","CONFIG_NOMINA_MENU"] | AAN130315FN3 |     44472 | NULL   |
+------+--------------+----------------------------------------------------------------+--------------+-----------+--------+
1 row in set (0.01 sec)
