### ISSUE TITLE
MARCA ERROR CUANDO LE DOY CLICK EN DATOS EXTRA EN WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#128]
PARA EL USUARIO DEMO EN PRUEBAS, ME MARCA ERROR CUANDO LE QUIERO CAPTURAR LOS DATOS EXTRA EN WEB
ESTO ES PARA PROBAR LO DE CARTA PORTE EN WEB

**Comment by jccastillo0007** [comment]
fixed
