### ISSUE TITLE
En WEB, la fecha enviada al PDF, debe tener el mismo formato que en escritorio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1282]
Está enviando un formato medio raro, que en algunos casos provoca que ciertos portales donde validan el PDF (hazme el recabrón favor, lo que es no tener nada que hacer), no pasa la validación porque no tiene el mismo formato.

La fecha del PDF en escritorio está bien: 02/02/2018 11:14:09

**_La fecha del PDF en web es incorrecta:  2/8/18 9:11 AM_**

Favor de homologar la hora. En escritorio es correcto.

**Comment by RigoFlores** [comment]
Algunos validadores siguen rebotando nuestras facturas, por el formato en el PDF.
Yo creo que debe ser simple su corrección, que no?

**Comment by RigoFlores** [comment]
Siguen llamando por este error, ya que la fecha si tiene especificado un formato en el anexo 20

**Comment by jccastillo0007** [comment]
fixed... chia validar un PDF no ma
