### ISSUE TITLE
Quitar la validación que obliga a capturar el número de cuenta en clientes y configuración

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1283]
Ya nos costó perder un cliente.
No está de acuerdo en capturar información que no ocupa.

Lo que se pidió en su momento es validar la longitud de la cuenta capturada.
Lo que se hizo, fue forzar a que se capture la cuenta, lo cual es distinto. Lo que se implementó genera llamadas de soporte y por otro lado, ya nos costó que se vaya un cliente (ojalá que sea un berrinche y regrese), pero mientras tanto ya se fue.

La validación de la longitud, se debe hacer SOLO EN CASO QUE SE HAYA CAPTURADO LA CUENTA, o si es preciso, agregar un botón de validación... que se yo, cualquier cosa, menos solicitar capturar la cuenta forzosamente.

**Comment by jccastillo0007** [comment]
La validación en el catálogo de clientes se quito desde que lo pediste

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
no, no se había quitado, por ello el cliente se fue ayer...
quizás estaba en pruebas, pero no en producción...
