### ISSUE TITLE
Error de Nota de Crédito Navision 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1284]
Yo recuerdo que ya lo había reportado y se había corregido, pero bueno, ahí está otra vez.

La base de impuesto IVA que se reporta, en lugar de ser el importe, es cantidad x importe.

importe = cantidad x precio unitario
base de impuesto = importe

lo incorrecto es que está enviando base de impuesto = importe x cantidad.
Para variar, nos están esperando con esta corrección.

**Comment by jccastillo0007** [comment]
Si, yo también recuedo que ya se habia corregido, aunque pudo haber sido para el conector normal y no para navision, aunque no estoy seguro

Esto es lo que esta en el código :  
new TAX(TAX.IVA, TaxesTypes.TRASLADADO, NumberConverter.toDouble(item.getTasaIvaTra()), tax, Taxes.IVA, "Tasa", product.getImporte()));

El último parámetro es product.getImporte() que es lo que se estaba enviando, e importe = cantidad x precio unitario...

Ojo... ese dato es importe se toma directamente del producto de la base de datos... 

voy a revisar la base de datos, es probable que lo estén guardando mal

**Comment by jccastillo0007** [comment]
Nevermind... ya vi donde estaba el error... y si, ya lo habiamos corregido antes, pero como se corrigió al momento de crear el XML... habría que hacer un cambio en el conector de Navision

Lo subo a su folder ahora mismo
