### ISSUE TITLE
EN WEB, FACTURAS DE OPTIBELT NO APARECEN ASOCIADAS AL NUMERO DE CLIENTE CORRECTO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1287]
EL NÚMERO DE CLIENTE ES 692236
SON DEL GRUPO DE FACTURAS QUE NO SE SUBIERON EN SU MOMENTO CORRECTAMENTE.

LAS FACTURAS SON:

181060919
181060920
181060921
181060922
181060923

**Comment by jccastillo0007** [comment]
fixed.
