### ISSUE TITLE
Algunos clientes requieren que se muestre el domicilio fiscal emisor o receptor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1288]
Sobre todo receptor.
Si lo muestro como antes, envía puras claves (ya que eso quedó para CCE, ignorando al resto de clientes).

Necesitamos resolver ese asunto..
a) Para facturas que no llevan el CCE, enviar el domicilio fiscal del receptor al PDF como se hacía anteriormente, es decir con descripciones y no con claves.
b) para los 2 únicos clientes que ocupan CCE en web y que ya están esperando la solución, el domicilio del receptor, se envía en claves al nodo receptor del CCE, pero en el PDF debería ir la descripción.

Viéndolo así, el requisito es muy puntual. Enviar al PDF el domicilio fiscal del receptor, con la descripción del campo y no con las claves.

**Comment by jccastillo0007** [comment]
done....

**Comment by RigoFlores** [comment]
como quedó la solución?, para poder validarlo

**Comment by jccastillo0007** [comment]
pues al momento de crear el pdf... se validan los datos que traen clave, si es así, se busca el nombre en el catálogo
