### ISSUE TITLE
Navision Factura - no está enviando el número de pedimento al XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1290]
No entiendo porque se lo brincó a lo cabrón, se me hace que está igual que como estaba optibelt, que de huevos lo quitamos...

**Comment by jccastillo0007** [comment]
mmmm ya no entendi, entre este defecto y el 1289.... y no... no lo esta quitando de huevos... lo manda , si y solo si , tanto el pedimento como la fecha del pedimento tienen información

**Comment by jccastillo0007** [comment]
pues, este ticket se contradice con el 1289... pero bueno, le voy a quitar el tema de validar y enviar la fecha de pedimento.. y solo va a enviar el número de pedimento.
