### ISSUE TITLE
Optibelt - No asigna correctamente la fecha de vencimiento en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1291]
Cuando se sube la factura desde el superconector al web, no asigna correctamente la fecha de vencimiento, ya que la pone igual a la fecha de emisión.
La fecha de vencimiento es igual a la fecha de emisión + número de días en condiciones de pago

**Comment by jccastillo0007** [comment]
listo... siempre y cuando el número que venga en condiciones de pago, sea un número ... sin caracteres alfanuméricos... que según vi en la base de gatos, si esta bien para optibelt.
lo subi a PRU y PRO.

**Comment by RigoFlores** [comment]
pues no, hoy me reportaron nuevamente el problema en producción.... es con las facturas de hoy...
<img width="662" alt="fechavencimiento" src="https://user-images.githubusercontent.com/2912775/36399555-f61eb8d8-1591-11e8-9f08-9cac064bca9d.png">

**Comment by jccastillo0007** [comment]
jajaja, todas las facturas que pusiste ahi, son del 19 de enero, no de febrero...

Como quiera revise y en efecto algo raro esta pasando... en el release de hoy, agregue unos logs que me pueden ayudar a corregirlo...

Diles que ma;ana tampoco va a estar listo jajaja, pero pasado ma;ana espero que si.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Quedó arreglado a partir de hoy, pero todas las que no tienen correcta la fecha de vencimiento, hay que correrles el cueri mágico, que resultó no ser tan mágico...

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
negativo, sigue igual y ya te imaginarás al cliente... acabo de ejecutar una consulta de cartera x cliente, del día 19 de enero...
<img width="498" alt="fechavencimiento2" src="https://user-images.githubusercontent.com/2912775/36563926-36d9e798-17e1-11e8-9938-62e3571ae6df.png">

**Comment by jccastillo0007** [comment]
chiaaaa
espero que ahora si ya estén todos los rangos de fecha...

He encontrado registros donde las condiciones de pago tiene algo asi 

60 DIAS FECHA DE FACTURA

Para esas facturas, va a fallar el approach de tomar el número de días... ya que se esta esperando únicamente un número.

**Comment by jccastillo0007** [comment]
chiaaaa
espero que ahora si ya estén todos los rangos de fecha...

He encontrado registros donde las condiciones de pago tiene algo asi 

60 DIAS FECHA DE FACTURA

Para esas facturas, va a fallar el approach de tomar el número de días... ya que se esta esperando únicamente un número.

Pero esta un poco raro, ya que la mayoria si trae solo el número... son solo algunas con esa info

**Comment by RigoFlores** [comment]
Si no mal recuerdo, tomábamos el numero hasta el primer espacio.
De cualquier manera, si debería llegar solo el número. A ver que me dicen...
