### ISSUE TITLE
Se duplica el timbrado de XML con tamaño arriba de 100K

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1292]
El escenario está muy identificado.
Cuando el XML rebasa los 100k de tamaño y se envía a timbrar, entonces facture hoy lo toma como una petición asíncrona.
La respuesta de facturehoy, Factura-T lo considera un mensaje de error, y le reintenta por Finkok. Finkok timbra correctamente y regresa el XML timbrado.

Pero la petición a facturehoy si se envió, y en algún momento, se volverá a timbrar ese XML también (por sus procesos asíncronos), duplicando la factura en el SAT, pero no así en Factura-T.

Entonces, tenemos que poner un candado para que los XML, digamos arriba de 90K de tamaño, se vayan por finkok directamente para evitar que se dupliquen las facturas en el SAT, ya que ni siquiera nosotros ni el cliente nos enteramos de esa duplicidad.

Es un cliente que emite muchas facturas, es de Tamaulipas. Sergio me pide que le pongamos un bypass hacia Finkok, pero eso posiblemente ya nos costaría porque subiría el volumen de timbrado por finkok.

Pero bueno, tu dime como podemos manejar este detalle.

**Comment by jccastillo0007** [comment]
por ahora se van a ir por finkok estos emisores : 

FLM030313DJ6
DMR840730523

y vamos a ver como resolverlo desde raiz
