### ISSUE TITLE
Navision - intercalar un espacio en el número de pedimento p facturas y notas de crédito

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1293]
El número de pedimento, en todo caso vendrá con 1 espacio.
Hay que agregar un espacio adicional para cumplir con el SAT.

Por ejemplo:
17 43 4325 7003170
debe pasar a:
17  43  4325  7003170

**Comment by jccastillo0007** [comment]
aqui no se ve claramente el tema de los dos espacios... 

deben ir entre cada serie de números ?

2 espacios = 17__43__4325__7003170
1 espacio = 17_43_4325_7003170

**Comment by jccastillo0007** [comment]
subi un release al dropbox, con el prefijo de Navision.. implementando este req.

Deja dos espacios entre cada serie de números, para que quede asi 

17__43__4325__7003170

El pedimento debe tener 4 series de números.

Puedes probarlo en PRU de navision para ver que todo este bien

Ahorita esta implementado solo para facturas.. falta notas de crédito.

**Comment by RigoFlores** [comment]
ya lo subí y lo dejé en producción.
Entonces, faltaría lo de notas de crédito pls...

**Comment by RigoFlores** [comment]
si quedó para notas de crédito?
