### ISSUE TITLE
Catálogo de Clientes - actualizar los catálogos de domicilio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1294]
Se requiere actualizar los catálogos del domicilio fiscal del receptor.
Yo creo que va a ser complicado mantenerlos actualizados todo el tiempo, pero bueno... quizás esta primera actualización hay que hacerla.
Solo se ocupan para el CCE.

Porque mejor no los agregamos al XML de configuración del CCE, y así que se capturen tecleen únicamente cuando se ocupen.

En el catálogo de clientes estándar, regresar como estaba anteriormente, es decir de libre captura.

**Comment by RigoFlores** [comment]
El catálogo de países y estados, no creo que cambie mucho.
La colonia y municipio, tienen la opción de libre captura, ahí no hay tanto problema, aunque deberíamos dejarlos ya de libre captura únicamente, porque el catálogo solo se ocupa para CCE, y hemos definido solo enviar la información requerida.

Realmente el único catálogo que hay que mantener actualizado, es el de códigos postales. Pero incluso, ahí 

http://www.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/c_CP.xls

**Comment by RigoFlores** [comment]
ya ví, y el CP en el domicilio del receptor, también puede ser de libre captura...
Entonces, donde encontraste el error del CP que no existía en el catálogo??

**Comment by RigoFlores** [comment]
Ya ví, lo reportaste en el emisor. Pero si el CP es de libre captura en el keygenerator, no entendí donde estaba el problema. Entonces como se deben capturar los datos del emisor en el keygenerator, para que puedan emitir CCE???

Este issue se originó a partir de tu correo... que dice...

El segundo RFC, OTC...., tiene mal el código postal, colonia y localidad... no encontré ninguna coincidencia, ni en el catálogo que tenemos cargados nosotros, ni en internet...
Consigueme los datos correctos y lo doy de alta.

**Comment by jccastillo0007** [comment]
porque el zip code de OTC... no estaba en el catálogo que tenia cargado de códigos postales...

Para domicilios del emsior nosotros lo podemos arreglar en la base de datos, son solo 2 creo...

Para domicilios de receptores, hay que validar muy bien el nombre del municipio en el catálogo que tenemos cargado

**Comment by jccastillo0007** [comment]
ya podemos cerrar este issue?
