### ISSUE TITLE
Residencia fiscal y numregidfisc solo se ocupan en el CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1295]
Ahora los está enviando, supongo yo en todos los complementos.
Al menos en el de servicios parciales de construcción.
Solo se debe enviar al XML estándar, en los datos del receptor para el caso del CCE

**Comment by RigoFlores** [comment]
Aclaración: residencia fiscal se tendría que enviar cuando el receptor es XEXX010101000.
pero para clientes nacionales o XAXXX, no se envían esos 2 datos que estoy reportando

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
en cuanto tenga oportunidad, lo validaremos... ya le comenté al cliente...
