### ISSUE TITLE
CCE - en el nodo emisor y receptor, enviar solo los datos de domicilio que son obligatorios.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1296]
estos son los únicos datos obligatorios, para que le agregamos complejidad agregando claves de datos que no son requeridos???:

Calle, Estado, Pais y CP  

calle es de libre captura
país, se toma del catálogo
para MEX, USA y CAN, se valida la clave de estado
para MEX, se valida el CP

**Comment by jccastillo0007** [comment]
para que le agregamos complejidad agregando claves de datos que no son requeridos???:

Porque asi se pidio originalmente, y ahora se solicita que si se capturen cuando se requiere..

**Comment by jccastillo0007** [comment]
por ahora no hay que agregar la info de la dirección a los datos extras, eso incluye varios cambios.

Pero para efectos del CCE, ya no se contemplan datos como localidad, referencia, municipio y colonia

**Comment by RigoFlores** [comment]
OK, pero originalmente se pidió que se capturara el domicilio del receptor con claves... UNICAMENTE PARA EL CASO DE CCE.... la solución fue hacerlo general, y de ahí se armó gran revuelo de issues, que hasta tuvimos que ponerle una libre captura al lado de cada campo del catálogo.

por lo pronto no tengo forma de validar en producción, ya que hoy no se pudo generar el CCE, por enésimo día...

**Comment by RigoFlores** [comment]
Al menos en pruebas, marcó error...
Porque dice algo del municipio del emisor, que supuestamente ya no se envia

CCE170 : El atributo cce11:ComercioExterior:Emisor:Domicilio:Municipio debe contener una clave del catálogo de catCFDI:c_Municipio donde la columna clave de c_Estado debe ser igual a la clave registrada en el atributo Estado. (3)

**Comment by jccastillo0007** [comment]
Ahorita esta en PRU, me marco error en el código postal del emisor, tal vez si requiere otro datos y no solo los que mencionaste.... hay  que checar

**Comment by RigoFlores** [comment]
EN PRODUCCIÓN SI LO HIZO BIEN, VAMOS A MANEJAR TODO PARA PRUEBAS, HASTA QUE YA QUEDE BIEN PROBADO.

**Comment by RigoFlores** [comment]
En el nodo emisor del CCE, ya está enviando nuevamente todos los datos del domicilio...

solo se ocupan los 4 mencionados arriba.

**Comment by RigoFlores** [comment]
revisé unos anteriores y estaba enviando varios datos.
Resulta que si envía el municipio, también espera la localidad, y entonces si que se hace un desmadre.


La solución fue eliminar el municipio del domicilio fiscal del emisor desde el keygeneratos, con ello se evita que lo envíe.
