### ISSUE TITLE
CCE - en el catálogo de clientes, no permite capturar estado para paises distintos de CAN, USA y MEX

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1297]
Para paises distintos a México, USA y Canadá.
En ese caso debería ser de libre captura, ya que no existe un catálogo para ellos.
Anteriormente si se tenía así, según recuerdo.

**Comment by RigoFlores** [comment]
Este issue va de la mano con el de enviar el domicilio para nombres alternos.
Lo que sucede es que muchas de las exportaciones van a centroamérica... así que necesitamos permitir la libre captura o listado, para el estado dentro del catálogo de clientes...

**Comment by jccastillo0007** [comment]
almost ready

**Comment by jccastillo0007** [comment]
done.

pru y pro
