### ISSUE TITLE
CCE - no envía los datos del domicilio receptor para nombres alternos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1298]
El RFC del receptor, al ser exportación casi siempre será el XEXX010101000, por lo que se ocuparán nombres alternos para capturar los distintos datos del cliente.
Para ello, se hace necesario que los datos de domicilio del receptor, cuando se le facture a un nombre alterno, sean enviados al nodo correspondiente del complemento de comercio exterior.

**Comment by jccastillo0007** [comment]
fixed, lo puedes checar en PRU

**Comment by RigoFlores** [comment]
negativo, ahora ya se descompuso por otro lado. Tanto para el RFC base XEXX010101000, como para nombre alterno, marca esto:

CCE173 : El atributo cce11:ComercioExterior:Emisor:Domicilio:CodigoPostal debe contener una clave del catálogo catCFDI:c_CodigoPostal donde la columna clave de c_Estado debe ser igual a la clave registrada en el atributo Estado, la columna clave de c_Municipio debe ser igual a la clave registrada en el atributo Municipio y si existe el atributo de Localidad, la columna clave de c_Localidad debe ser igual a la clave registrada en el atributo Localidad. (3)

**Comment by RigoFlores** [comment]
ya lo está esperando un cliente. Pensé que iba a estar listo hoy.

**Comment by jccastillo0007** [comment]
crei que te lo habia puesto aqui en el ticket... si, a mi tambien me arroja eso... pero eso tiene que ver con que quite varios datos de la dirección en el complemento,  no tanto con los alternos.. hoy lo checo.

Dile al cliente que use lo que esta en producción, eso sigue igual, para que no este esperando

**Comment by jccastillo0007** [comment]
no se que esta pasando... ya genere un cfdi con los mismos datos que antes se generaban y me sigue enviando ese error

**Comment by jccastillo0007** [comment]
mi sospecha es que se están haciendo mas validaciones, si el código postal tiene cargados algunos municipios en el catálogo del sat, entonces se debe incluir el municipio en el cce, pero si no tiene cargado nada, entonces estabien omitirlo

De eso me di cuenta al validar varias facturas en el catálogo de código postal que esta en el dropbox

**Comment by RigoFlores** [comment]
Lo que vi es que ese error lo envía finkok EN PRUEBAS.
Si lo mismo lo envío a PRODUCCIÓN, facturehoy lo timbra correctamente con esos datos mínimos: pais, estado, CP y calle del emisor.

Esto lo hice enviando el XML a timbrar, y jugando con los datos contenidos en él...
Así que yo creo que tenemos que subirlo a producción para validar con los clientes... como vex???

**Comment by jccastillo0007** [comment]
ojo... ya vi cual es el secreto
de acuerdo a los catálogos del SAT... si el código postal tiene asignados los municipios... entonces el SAT exige que se mande el municipio, eso es lo que esta pasando ahora mismo en PRU.... pero si por alguna razón el código postal no tiene cargados los municipios, entonces se puede no enviar nada... 

esto le agrega mas complejidad a la solución.

Como debe quedar desde el punto de vista de FacturaT, si se captura un Municipio, se debe enviar su respectiva clave al SAT, y si no se captura nada, pues no se manda nada... será algo tendremos que validar en cada emisor y receptor que use el CCE...

Ahora mismo en PRU no funciona porque le quite el municpio, pero se lo puse y ya volvió a timbrar...

La pregunta es, lo libero a Producción o no ?

**Comment by RigoFlores** [comment]
Tu teoría no se cumple con el ejemplo que ayer timbré en producción.
El CP que ingresé en el domicilio del emisor dentro del complemento, fue el 09070. 

En el catálogo de CP del CCE, si aparece un municipio para ese CP, pero yo no se lo incluí y aún así lo timbró.

Creo que facturehoy está aplicando distintos criterios a finkok para el tema del domicilio del emisor dentro del complemento. (quizás también para el receptor).
Total que a mi parecer, y leyendo la spec, aparentemente facturehoy estaría bien.
Yo creo que hay que subirlo a producción.

**Comment by jccastillo0007** [comment]
ok, ojo... si existe un municipio cargado en la dirección del receptor, lo va a buscar en el catálogo, si lo encuentra lo va a mandar, si no lo encuentra o no tiene ningún municipio capturado, entonces no manda nada...

Lo mismo para el emisor, que hasta el momento solo son dos clientes nuestros.

**Comment by RigoFlores** [comment]
Hice la prueba en producción con el rfc IME120610FQA (me dió chance de hacer pruebas, para 'asegurar su correcta configuración'), con un nombre alterno, y no está enviando el CP.
El nombre alterno del RFC extranjero XEXX010101000 es guatemala. Tu mismo puedes verificar que si tiene el CP capturado, sin embargo al nodo del receptor dentro del complemento CCE, no lo envía, y marca XML mal formado:

            <cce11:Receptor>
                <cce11:Domicilio Calle="SPS BARRIO MEDINA 13 CALLE 8 AVE" Estado="SAN PEDRO SULA" Pais="GTM"/>
            </cce11:Receptor>

Espero que corrigiendo esto ya quede..

**Comment by RigoFlores** [comment]
Siguen esperando los clientes...

**Comment by RigoFlores** [comment]
También en producción, pero con el rfc directo (sin nombre alterno), cuando el país es distinto a MEX, CAN o USA, tampoco envía el código postar del receptor, dentro del complemento y evidentemente marca error...

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
esto ya quedó corregido en su momento, pero tuviste que editar el domicilio del emisor a manopla, para cumplir con los catálogos del sat
