### ISSUE TITLE
Navision - agregar al siguiente dato extra general el campo Due Date

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1299]
Solo aplica para la factura.
El siguiente dato extra general debe incluir este campo "Due Date", que se encuentra en la tabla "Sales Invoice Header".
Si desconoces cuál dato extra es el siguiente disponible, avísame para aventarme el clavado a ver cuál es...

**Comment by RigoFlores** [comment]
ya revisé, según vi, es el dato extra10, el siguiente disponible.

**Comment by jccastillo0007** [comment]
no es tan trivial... lo de menos es cambiar el dato extra, peeeero, hay que cambiar la vista creada NavisionCFDi.... y eso recuerdo lo hacen ellos.

Entonces yo hago el cambio en el ambiente de PruebasSAT, y pideles que cambien la vista en PRoducción... y ya luego subo el cambio

**Comment by jccastillo0007** [comment]
ya esta el cambio en PRU, te voy a mandar el script de la vista por si es mas fácil para ellos

**Comment by RigoFlores** [comment]
de las vistas que ocupamos nosotros, ellos ni siquiera las conocen... porque no las ocupan... 
nosotros seguramente siempre hemos creado la vista que se requiera...  o quieres que les comente?

**Comment by RigoFlores** [comment]
Ya les comenté y crearon la nueva vista.
Ya tenemos listo el cambio en código?

**Comment by jccastillo0007** [comment]
si, deja lo subo

**Comment by jccastillo0007** [comment]
No me dio tiempo de subirlo a Navision, pero lo deje en dropbox..

**Comment by RigoFlores** [comment]
Sigo sin poder validar este issue.
Ahora marcó XML mal formado, y aparentemente todo está OK.
Les pedí que revisaran si los números de pedimento eran correctos.

**Comment by RigoFlores** [comment]
Ya timbró la nota de crédito.
En cuanto generen la siguiente factura, podré validar este issue.
