### ISSUE TITLE
Cuando marca error de cancelación, el XML vacío lo genera en el directorio PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#130]
Cuando intentas cancelar desde la pantalla del escritorio, y marca un error (el 205 por ejemplo), el PDF y XML los coloca en el mismo directorio, esto es en el directorio PDF.
Entiendo que el XML debería colocarlo en el directorio XML y asimismo el PDF en su correspondiente carpeta PDF

**Comment by jccastillo0007** [comment]
fixed
