### ISSUE TITLE
Optibelt - Ingresar cobro por número de cliente, no es posible

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1300]
En la pantalla de Ingresar cobro, cuando filtras únicamente por número de cliente, no se puede hacer el registro del pago. Este es el error realmente que se había levantado en otro issue.

Yo creo que desplegando la factura en la parte inferior de esa pantalla, bajo cualquier criterio: rfc, número de clientes, fechas, rango de folios... de ahí se muestra un listado de facturas.... al elegir una o varias de ellas, se conocerá el RFC del cliente al cuál se registrará el pago.

Optibelt ocupa mucho registrar solo eligiendo por número de cliente, ya que todos sus clientes extranjeros tiene el RFC XEXX010101000, entonces el número de cliente ayuda mucho en ese escenario.

Según yo eso ya jalaba, en otro caso no lo hubiera aceptado optibelt. Como quiera lo levantaré como nuevo requerimiento.

**Comment by jccastillo0007** [comment]
marca algún error en particular ?

**Comment by RigoFlores** [comment]
lo intenté en pruebas, y marca lo siguiente:

Cliente no seleccionado

Aún cuando si despliega las facturas asociadas al número de cliente.
Como comenté desde el principio, según yo cuando solo eliges el número de cliente, no está asociando el RFC que le corresponde a dicho cliente.

**Comment by jccastillo0007** [comment]
fixed... ya esta en pru y pro
