### ISSUE TITLE
Optibelt - corregir el status de la facturas de este año, con base a la fecha de emisión y condiciones de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1301]
Seguimos atorados con optibelt.
Si bien aparentemente se corrigió el tema de la fecha de vencimiento... pero eso va de la mano con el status... 

si la fecha aún no se alcanza, entonces es vigente... 
si la fecha ya se alcanzó y no han pagado es vencida... 
y cuando se paga su status es pagada...

ya están muy nerviosos con el tema, termina el 2o mes del año, y aún no puden tener estable la aplicación...

**Comment by jccastillo0007** [comment]
mmmm, pues si me imagino.. y seguimos encontrando los defectos ahorita

**Comment by jccastillo0007** [comment]
lo que no entiendo es, cuando se recibe la factura desde el super conector, se acaba de timbrar cierto... entonces su estatus siempre es vigente o como ? no entiendo bien que es lo que hace falta al momento de generar la factura

**Comment by RigoFlores** [comment]
Si seguimos encontrando defectos de algo que en principio no tendría que tocarse y por ello no se validó (envío de datos extra, asignar fecha de vencimiento, asignar status), ahora veo que se tendría que haber validado todo lo que el año pasado nos llevó meses dejar estable... .

El asunto es que con tantas aspirinas que le hemos dado a optibelt este año, han quedado cosas chuecas:
<img width="280" alt="statusoptibelt" src="https://user-images.githubusercontent.com/2912775/36740279-9453648e-1ba7-11e8-86d3-d4f5a982e501.png">

**Comment by RigoFlores** [comment]
Realmente tomando en cuenta tu comentario, que es totalmente fundamentado...
a) el status inicial es vigente
b) con base a las condiciones de pago, de calcula la fecha de vencimiento
c) en un cron que debe ejecutarse diariamente, se debe actualizar el status de las facturas. Este proceso se ejecuta únicamente sobre las facturas con status vigente. Pero dados los jarabitos que le hemos dado al enfermito, pues ahora se requiere también recalcular sobre todas las facturas de este año.


El tema de este issue es el punto (c), que realmente se divide en 2 puntos:

i) ejecutar el cálculo de status de facturas con status distinto a pagadas. Para que se defina si está vigente o vencida con base a la fecha de vencimiento. Este es un mejoralito mas al enfermo, ya que solo actualizamos la fecha de vencimiento por fuera, pero no el status.

ii) ejecutar el cron DIARIAMENTE, que actualice el status de las facturas distintas a pagadas. Básicamente para pasar las vigentes a vencidas, cuando aplique el caso. Eso ya lo ejecutan unos cueris mágicos, lo que no sé, es porque no se ha puesto el cron... así como tenemos en de las facturas periódicas.

**Comment by jccastillo0007** [comment]
ok, entonces el punto c es lo que falta.

Hoy trabajo en eso, y lo aplicaré a todas las facturas de este año.

Algo mas que este pendiente?

JC.

Saludos.
JC.

2018-02-27 10:23 GMT-06:00 RigoFlores <notifications@github.com>:

**Comment by RigoFlores** [comment]
de este issue, al parecer no... pero mientras no se corrija, ellos revisan y quizás hallen otra cosa.
De optibelt también tenemos el pendiente que no pueden ingresar el pago, cuando eligen el número de cliente únicamente...

**Comment by RigoFlores** [comment]
Correrlo a todas las facturas de este año, pero que tengan status distinto de pagadas...

**Comment by jccastillo0007** [comment]
listo... de hecho corri el script sobre todas las facturas vigentes...

de optibelt tenían vencidas solo 56

ojo... sigue el detalle de que algunas facturas llegan con condiciones de pago y una leyenda... ejemplo " 25 sobre fecha factura" o algo asi... esas facturas no se esta actualizando correctamente la fecha de vencimiento

**Comment by jccastillo0007** [comment]
ya quedo configurado el cron... hoy y ma;ana va a correr, pero no va a actualizar nada... solo quiero ver que se ejecute y reporte correctamente... ya que todo este bien, activo la actualizaci´øn, eso será el jueves.

**Comment by jccastillo0007** [comment]
Confirma con ellos si debemos validar y de alguna manera soportar el tema de que en condiciones de pago no llega solo un número, y si es el caso... pueden asegurar que siempre llega primero el número y luego la leyenda >

**Comment by RigoFlores** [comment]
Oye, corregiste el status de todas las facturas de este año con status DISTINTO A PAGADAS???

El problema reportado en la imagen, muestra facturas con fecha de vencimiento en marzo, pero con status igual a vencidas, lo cual es incorrecto.

**Comment by RigoFlores** [comment]
pásame el cueri para hacerlo, ya he quedado muy mal con optibelt, los traigo a vuelta y vuelta, y esto no termina de quedar completo

**Comment by RigoFlores** [comment]
y también indícame pls cuáles facturas vienen con condiciones de pago con el número y la leyenda..
