### ISSUE TITLE
Conector Documento de Pago - si no incluye serie de la factura pagada marca error...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1302]
CONECTOR

En el nodo de documento relacionado del documento de recepción de pago, respecto a las facturas que se cubren con el pago recibido, si no se incluye serie en el archivo de texto, marca XML mal formado... ya que envía al xml serie=""

**Comment by jccastillo0007** [comment]
Esto lo marca en el complemento de pago verdad.. no tanto en el cfdi.

**Comment by RigoFlores** [comment]
afirmativo, aplica para el complemento de pago.
No lo puedo probar, lo que subiste está apuntando (buscando) a Navision...

**Comment by jccastillo0007** [comment]
listo.
