### ISSUE TITLE
Nomina - falta la percepción 050 - Viáticos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1303]
No sé en que momento desapareció, o porque no se ve.
Al rato o mañana revisaré todos los catálogos.

Hoy voy saliendo a la escuela de mi hija a una entrega de reconocimientos...

**Comment by jccastillo0007** [comment]
se me paso actualizar el ticket... ayer agregue la percepción 50 en pru y pro

**Comment by RigoFlores** [comment]
como que lo corregiste antes que lo levantara???

Sigue igual en producción, es decir no aparece el concepto de viáticos, que debe aparecer al final por ser el 050.

**Comment by jccastillo0007** [comment]
ahora si ya la vi en la nomina de pro
