### ISSUE TITLE
DescargaT - no permite generar una factura a partir de una remisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1305]
Manda error de seguridad Cer/key o algo así.
Si puedo consultar y descargar.
El reporte que genera en excel, al momento de exportar, debe ser el mismo que en la pantalla de Ventas-Consultas, al parecer le faltan columnas.

**Comment by jccastillo0007** [comment]
acabo de descubrir código en descargat que no es compatible con cfdi  3.3... al momento de generar el CFDi... se ocupa un refactor para no tener código duplicado

**Comment by RigoFlores** [comment]
Entonces... que vamos a hacer?

**Comment by jccastillo0007** [comment]
ya estoy en el refactor desde antier... espero que ya quede hoy

**Comment by jccastillo0007** [comment]
Listo, puedes iniciar pruebas.

**Comment by RigoFlores** [comment]
No me da acceso al descargaT.
Me puedes pasar la url correcta, así como el pwd de TIA101020BP4 para entrar a validar?

**Comment by jccastillo0007** [comment]
http://efacturat-stagging.com.mx:8080/DescargaTuCFDi

TIA101020BP4 / test

**Comment by RigoFlores** [comment]
Marcó lo siguiente, cuando intenté facturar una remisión: 

CFDI33142 : El campo ClaveProdServ, no contiene un valor del catálogo c_ClaveProdServ. (3)

**Comment by jccastillo0007** [comment]
checa el producto que agregaste en la remision

**Comment by RigoFlores** [comment]
es el único que existe con código 01010101

**Comment by jccastillo0007** [comment]
ok lo checo, yo generé una sin pedos...

**Comment by jccastillo0007** [comment]
Revise tus remisiones y no tienen nada guardado en la tabla de productos,

mysql> select basePrice , complementaryDescription , name, price, productKey, productKeySAT , quantity unit, unitSAT from CFD_Products where id = 203 or id = 202;
+-----------+--------------------------+---------+-------+------------+---------------+------+---------+
| basePrice | complementaryDescription | name    | price | productKey | productKeySAT | unit | unitSAT |
+-----------+--------------------------+---------+-------+------------+---------------+------+---------+
|     10000 | otras tuercas.           | Tuercas | 10000 | P01        | NULL          |    1 | H87     |
|       500 | NULL                     | Tuercas |   500 | P01        | NULL          |    1 | H87     |
+-----------+--------------------------+---------+-------+------------+---------------+------+---------+
2 rows in set (0.01 sec)

**Comment by jccastillo0007** [comment]
ya vi, si habia un error al momento de hacer la remision.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
NO ESTÁ ARRIBA EL DESCARGAT

**Comment by RigoFlores** [comment]
sigo sin poder probar, hace 10 días...

**Comment by jccastillo0007** [comment]
chiaaaa y yo que en chinga arreglo los defectos

**Comment by jccastillo0007** [comment]
ya esta disponible, desde hacer 4 días

**Comment by RigoFlores** [comment]
pues apenas hoy me notificas que ya puedo entrar... pero realmente lo que si pasó es que ya está disponible la pantalla de acceso... cuando le ingreso el usuario TIA101020BP4/test... marca internal error... tssss.... chiaaaaa

**Comment by jccastillo0007** [comment]
listo..

**Comment by RigoFlores** [comment]
Ya generé la factura, pero ahora cuando la consulto desde facturat, aparece 2 veces la factura generada desde descargat. 
Es la misma factura, repetida 2 veces.

**Comment by jccastillo0007** [comment]
si esta dos veces en la base de datos... cómo la generaste ?

**Comment by jccastillo0007** [comment]
creo que ya entendi lo que escribiste arriba... generaste la factura desde descargat, y se generó dos veces, deja veo

**Comment by RigoFlores** [comment]
Sigue duplicando las facturas, cuando la generas desde DESCARGA-T

**Comment by jccastillo0007** [comment]
Esto esta bien pinche raro... no le encuentro el problema

**Comment by jccastillo0007** [comment]
no inventes , esto estuvo muy pinche absurdo... resulta que se duplicaban porque en el timbrador tenemos la funcionalidad de guardar todos los CFD que nos llegan desde conector... pero no estaba validando que viniera desde el descargat, chiaaaa

utilicé la addenda facturat, para identificar que el cfdi viene de descargat
