### ISSUE TITLE
Configuración de Condominio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1307]
Pensemos que el rfc emisor está a cargo de una unidad condominal:

Varios condominios
Varios edificios dentro de cada condominio
Varios pisos en cada edificio
Varias casas por piso.

A cada casa o departamento, tenemos que identificarlo como un receptor de CFDI, que en muchos casos podrían tener el mismo RFC genérico asociado. Cómo le hacemos?? OJO, por ahí pudieramos pensar en el número de cliente.
Los diferentes niveles de organización del condominio, arriba mencionados, servirán al momento de generar reportes, como criterios de filtro.

**Comment by jccastillo0007** [comment]
Veo dos opciones

1. Número de cliente, como bien dices... no importan los diferentes niveles de cada fraccionamiento, al final, todos tienen un id único, ese puede ser su cliente id.
2. Nombres alternos, pero me da miedo usar esta opción, siempre salen detalles.

La opción 1, aplica de forma transparente, incluso, para que sea mas fancy, cuando se firme el rfc emisor administrador del fraccionamiento, podemos ponerle Casa Id, o algo asi, en lugar de No. Cliente.

**Comment by jccastillo0007** [comment]
Hay algún requerimiento especial para el CFDi?

Algo específico que nos haga falta para empezar a atender a condominios?

**Comment by RigoFlores** [comment]
OJO, el número de cliente se basa en el nombre alterno.

Nos falta que podamos generar reportes de cobranza por número de cliente (ID casa eso ya está), o por cualquier nivel del condominio (eso no está y es algo que puntualmente pidieron).
Falta que podamos registrar salidas de lana (sin factura!!!), recuerda la famosa caja chica de los condominios. Debería salir por cheque toda la lana.
Falta que los proveedores puedan subir sus facturas, que se validen ante el sat y que se pueda programar su pago (en ese caso, es darle una repasada completa a CxP).
Falta que en el descargat, un condómino pueda consultar sus facturas por número de cliente (o como definamos que es).
El CFDi no tiene un requerimiento específico, quizás el nombre "Recibo de Pago", podría ser.
Y de ahí, los requisitos que vayan saliendo.

**Comment by RigoFlores** [comment]
Existe otro concepto importante en el condominio. Quedó pendiente en nuestra implementación de CxC.
Esto es el Saldo a favor. En la factura normal cuando un cliente "paga de mas" o por adelantado. No es muy común.

En el condominio, si es común que si una empresa renta un depa o casa para su empleado, pague el mantenimiento anual de un chingadazo. Esto es que durante el año completo, tendría saldo a favor que poco a poco se iria consumiendo hasta llegar al año. Si es importante este concepto.

**Comment by jccastillo0007** [comment]
ok, hay que dividir este requerimiento en tickets tipo "missing functionality" y anteponiendole Condominio, para identificar

Hay varias cosas que ya están, pero hay que darle una revisada, como CxP y lo de proveedores

**Comment by jccastillo0007** [comment]
listo.

Checa la pantalla, yo creo que cubre todos los casos.

Ya se relaciona con un RFC de algún cliente capturado previamente, e incluso con su número de cliente, no me has dicho si en realidad hay que generar una factura con algún complemento, o es solo para llevar bien controlado las CxC y CxP de un condominio.

**Comment by RigoFlores** [comment]
La factura no lleva ningún complemento.

**Comment by jccastillo0007** [comment]
ya di de alta varios condominios en pru... checale

**Comment by RigoFlores** [comment]
si revisé, pero ví que permite repetir el número de cliente, lo cual es incorrecto... el número de cliente es por casa o departamento o local, lo cual no debe repetirse.

Otra cosa que noté, es que solo se debe poder definir UN SOLO CONDOMINIO, ya que será un condominio por rfc receptor.

**Comment by jccastillo0007** [comment]
lo del cliente no lo creo, ya que una persona puede tener mas de una casa, y según lo que yo he visto (al menos aqui en la colonia) esta ligada a la misma persona, y no a otra...

Lo del condominio también es un asegun... ya que un administrador de condominios (espero que tengamos alguno) puede usar la app para varios condominios

**Comment by RigoFlores** [comment]
Definitivamente una misma persona puede tener varias casas o departamentos. Es un hecho, aquí también pasa.
Aquí el punto, es que en los reportes que generemos, el filtro mas granular es por casa.
Quizás también queramos obtener uno por persona, y ahí quizás convengan ambos enfoques.

Si un administrador, trabaja en varios condominios, entonces se creará una cuenta por cada RFC emisor (cliente nuestro), y cuál sería el caso entonces de poder dar de alta varios condominios asociados a un solo RFC, que por definición cada condominio tiene su propio y único RFC.

Si no tenemos ningún administrador, y por lo tanto no echamos andar este proyecto, tendemos a que el negocio desaparezca, ya que únicamente los folios no creo que nos den para mantenernos, ya no digamos crecer. Esa es la apuesta y es también, lo que debimos platicar en mi visita a GDL, pero pues no se pudo platicar del futuro de la TIA.

**Comment by RigoFlores** [comment]
Si entendí bien, y trata de dar simplemente el nombre del condominio, ya que el siguiente nivel son casas o locales, entonces ahí es donde no me permite guardar, me pide obligatorios algunos datos que no debería, ya que no son necesarios. O cómo debo darlo de alta?
Entendería que los únicos datos obligatorios, son Condominio y casa, que son el nivel mas básico.
También entiendo que primero capturas solo el nombre del condominio (paso 1), para después ir capturando cada casa, que a su vez cada casa va a estar relacionada con un RFC y número de cliente, que diste de alta previamente en el catálogo de clientes, es correcto?


<img width="346" alt="condominio" src="https://user-images.githubusercontent.com/2912775/39924421-51478bf0-54ed-11e8-8b96-eb6dc29f0053.PNG">

**Comment by jccastillo0007** [comment]
hay que ingresar todos los datos... desde nivel 1 hasta casa... de ahi el sistema mostrará los domicilios ya dados de alta, para reutilizar la ifno, es decir...

La primera vez capturas nivel 1 (condominio) y el resto de datos.... hasta una casa.

La siguiente vez, ya aparece el condominio creado anteriormente y ya solo lo seleccionas.

**Comment by RigoFlores** [comment]
Ya vimos anoche, aquí surgen 2 puntos:

a) Solo se debe dar de alta un condominio.
b) Nivel 2 será opcional, para el caso de que el condominio o plaza sea simple.

**Comment by jccastillo0007** [comment]
done
