### ISSUE TITLE
DescargaT - envíar los correos por el nuevo servicio de sendgrid

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1308]
los intenta enviar por el esquema anterior...

**Comment by jccastillo0007** [comment]
ya esta en pru

**Comment by RigoFlores** [comment]
HICE LA PRUEBA, PERO ME LLEGÓ EL CORREO DE noreply@factura-t.com.mx.
ESO ME INDICA QUE SIGUE IGUAL.

RECUERDA QUE ME REFIERO A DESCARGA-T

**Comment by jccastillo0007** [comment]
lo voy a subir a PRO

**Comment by jccastillo0007** [comment]
ya debe tomar la nueva libreria

**Comment by RigoFlores** [comment]
negativo, sigue igual...

**Comment by jccastillo0007** [comment]
es que no lo subi a PRO, hoy lo subo

**Comment by RigoFlores** [comment]
lo volví a intentar, y sigue enviando desde noreply@factura-t.com.mx

**Comment by jccastillo0007** [comment]
listo

**Comment by jccastillo0007** [comment]
de hecho el email que envía es el mismo, solo cambia la plataforma que ahora es sendgrid
