### ISSUE TITLE
En impuestos locales en web, hace referencia al xsd de la 3.2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1309]
Hay que modificar en todo el código, cualquier referencia al xsd de la 3.2.
Caso concreto en el web, manda esto cuando incluyes impuestos locales:

xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 **_## http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd_** http://www.sat.gob.mx/implocal http://www.sat.gob.mx/sitio_internet/cfd/implocal/implocal.xsd"

**Comment by jccastillo0007** [comment]
fixed.
en PRU, mañana lo subo a PRO

**Comment by RigoFlores** [comment]
en escritorio aún lo manda como 32

**Comment by jccastillo0007** [comment]
en serio... con la version de ayer...

**Comment by RigoFlores** [comment]
lo validé en pruebas y seguía mandando el 32
Lo acabo de hacer en producción y ahí si está bien.
Estoy asumiendo que pruebas, al menos incluye todo lo de pro, que no???

**Comment by jccastillo0007** [comment]
pero hablas desde standalone verdad

**Comment by jccastillo0007** [comment]
y estas usando una versión reciente de standalone verdad

**Comment by RigoFlores** [comment]
no , estaba hablando de pru web

**Comment by jccastillo0007** [comment]
ah ok... chiaaaa habias dicho que era standalone... creo que no habia subido el release del fix de laversión a PRU... ahorita lo subo

**Comment by RigoFlores** [comment]
OK, en web creo que ya se corrigió, tanto pru y pro.

**Comment by RigoFlores** [comment]
Ya solo queda pendiente en escritorio, ya que no se subió ninguna nueva versión.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Descargué la versión de escritorio, y generé factura con impuestos locales, vía los 'productos-impuestos', y sigue incluyendo referencia al 3.2
Si la factura la generas sin impuestos locales, lo hace correctamente.
