### ISSUE TITLE
Navision - cálculo incorrecto del subtotal y total en nota de crédito, cuando incluye descuentos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1311]
El subtotal, es la suma de importes (antes de descuentos). 
Así dice el SAT:

Atributo requerido para representar la suma de los importes de los conceptos **antes de descuentos e impuesto**. No se permiten valores negativos.

Ahora mismo el subtotal, se está reportando como suma de importes **menos descuento**.
El total lo calcula bien, es decir subtotal mas impuestos trasladados, pero como de origen es incorrecto el subtotal, evidentemente el total también sale mal.

En  producción puedes validar esto con la nota de crédito 18AVMX010.
Ya detuvimos esta nota de crédito con ellos, cuando justo ayer indiqué que ya estábamos al 100%.... chiaaaaa...

**Comment by jccastillo0007** [comment]
listo.

Después de varias semanas sin saber de esto, imagine que ya estaba, pero veo que siguen a prueba y error.

En este caso, el subtotal guardado en base de datos, es incorrecto, pues considera el descuento, para corregirlo, no tomo en cuenta el subtotal de la base de datos, y se calcula con cantidad por importe.

**Comment by RigoFlores** [comment]
voy a actualizar, pero me suena que aquí tenemos otra fuente de error... a menos que el total tampoco lo tomes de su base de datos.

**Comment by RigoFlores** [comment]
ya actualicé y ahora se descompuso el IVA a nivel producto, lo calcula mal.

**Comment by jccastillo0007** [comment]
el iva a nivel producto, se calcula sobre el subtotal - descuento ?

Si es asi, entonces supongo que por eso ellos guardan el subtotal menos el descuento

**Comment by RigoFlores** [comment]
ya estoy confundido cada vez mas.
Cuales datos calculamos con navision?
Cómo nos conviene que quede?

**Comment by RigoFlores** [comment]
pero hay que asegurar no pegarle a los demás.
Con la versión que subí hoy, el IVA  a nivel producto, curiosamente se reporta a la mitad de lo que debía ser. Esto en el nodo de impuestos. La base está bien, pero el IVA no.
Urge ya cerrar esto, tenemos una lana detenida ahí, amén que hay que empezar con el tema del condominio.

**Comment by jccastillo0007** [comment]
pues mira... originalmente, (si una nota de crédito no tiene descuento)

Cantidad
Precio Unitario
Subtotal
Total = Subtotal - descuento + impuestos trasladados

se tomaban tal cual de sus tablas, con respecto al impuesto trasladado, ellos tienen un campo llamado "[AMOUNT INCLUDING VAT]" que nosotros le llamamos ivaTra, ese campo es el impuesto trasladado + el subtotal

En Notas de crédito sin descuento, todo cuadraba bien, apesar de la chacarronada del campo [AMOUNT INCLUDING VAT]

Ahora que tienen notas de crédito con descuento... resulta que ellos tienen el subtotal ya sin descuento... entonces el campo subtotal se movia y era incorrecto, lo que hice ayer fue no tomar en cuenta el subtotal de ellos y nosotros asumir que :   
Subtotal = cantidad * importe

hasta ahi todo bien, pero el impuesto trasladado que tienen en [AMOUNT INCLUDING VAT], recuerda que tiene sumado el subtotal, tons ahi esta el desmadre.

Que podemos hacer :  

1. Que ellos no guarden el subtotal como (subtotal - descuento)
2. Corregir nosotros el cálculo del impuesto trasladado a nivel producto

Para efectos de agilizar las cosas, la versión de hoy, implementa la opción 2

Si ellos corrigen sus cochinadas e implementan la opción 1, entonces yo le puedo dar rollback a lo que hice ayer y hoy y todo quedaría mas transparente

**Comment by RigoFlores** [comment]
Los datos del cálculo, aparentemente ya están OK.
Ahora marcó XML mal formado y no sé ni por donde buscarle.
Por lo pronto pedí que revisaran si los números de pedimento eran correctos.
Seguimos atorados con este cliente, no sé si por ellos o por nosotros, pero el resultado es el mismo, estamos perdiendo credibilidad.
