### ISSUE TITLE
Conector - si el precio unitario incluye 6 decimales, no lo envía al PDF.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1315]
Solo envía 4 decimales al PDF y requieren los 6 decimales.
Enviar los decimales que se incluyan en el texto

**Comment by jccastillo0007** [comment]
Solo para el precio unitario ?

**Comment by RigoFlores** [comment]
En este caso, lo están pidiendo en particular para el precio unitario.
En teoría los importes, montos de impuestos, totales, etc van con los decimales de la moneda, en este caso son 2 decimales.
Donde se ocupan 6 decimales, principalmente son en precio unitario y cantidad

**Comment by jccastillo0007** [comment]
Done.
