### ISSUE TITLE
Condominio - Dar de alta la estructura organizacional de un condominio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1316]
Poder definir desde 1 hasta n niveles de organización.
Ejemplo:

Condominio - Edificio - Piso - Departamento
Condominio - Cotto - Sección  - Calle - Número de Casa

Esto servirá para poder aplicar filtros en caso de reportes.

**Comment by jccastillo0007** [comment]
oye, 
Condominio / Colonia / Fracionamiento siempre existirá, ese sería nuestro nivel 1

Calle, No Ext, No Int,  también siempre existe, cierto

Lo que esta en dilema es :  
Edificio, Piso, Departamento 
o
Coto 
o
Sección 

Yo veo de 5 a 7 niveles... porque quieres que sean N, crees que encontremos algo que no se pueda adaptar ?

**Comment by RigoFlores** [comment]
No creo que sean demasiados niveles.
Yo me imaginaba algo así como cuando capturas en catálogo de clientes los correos, que puedes agregar uno o varios (es decir, n).

El mas bajo nivel es la casa o departamento. (es decir, la vivienda en sí)
De ahí podría seguir piso y/o calle
Quizás Edificio
Condominio, cotto, sección.
Unidad Condominal (se compone de varios condominios)

**Comment by jccastillo0007** [comment]
el problema con es que no es solo capturarlos como con los correos, o los teléfonos... en este caso van relacionados y son secuenciales... es decir, no puede haber un piso si no hay un edificio, o un depa .... y sin importar si es edificio o coto o colonia, siempre hay una calle y un número exterior, no esta tán facil, sobre todo pensando en todos los filtros que pueden pedir, como saber todos los depas de un edificio, o las casas de un coto etc

**Comment by jccastillo0007** [comment]
oye, pregunta.

Un cliente de facturat, con el plugin de condominios... puede tener mas de un condominio ?

Asi como un administrador de condominios?

**Comment by RigoFlores** [comment]
A nivel de usuario, podría ser...
A nivel de rfc emisor, solo es un condominio por rfc...

**Comment by jccastillo0007** [comment]
ya subi a Pru y Pro lo que sería la primer pantalla para captura de condominios... solo esta disponible para la TIA y para ACO

**Comment by RigoFlores** [comment]
no entendí lo que hace esa pantalla... :(

**Comment by jccastillo0007** [comment]
sigo en esta pantalla, los pinches filtros identados para los diferentes niveles del domicilio, es lo que no me sale.

**Comment by RigoFlores** [comment]
Me marca internal error en pruebas.

**Comment by jccastillo0007** [comment]
listo.

Ya se puede incluso relacionar rfc y número de cliente.

**Comment by RigoFlores** [comment]
Explícame como funciona pls.
El condominio mas básico es como donde vivo, solo hay 43 casas y ya. No tiene nombre de calle ni nada, solo es una cuadra.
El otro caso, por ejemplo un condominio con 4 edificios, con 4 niveles cada edificio, con 4 departamentos por edificio. 

En ambos casos, como se mapea el RFC+# cliente hacia la organización del condominio???

**Comment by jccastillo0007** [comment]
el condominio donde vives, por supuesto que hay calle, y seguramente es una sola calle para todos, con un solo número exterior, y 43 números interiores o lotes.

Siempre hay una calle.

Y en el caso de edificios con n pisos... estuve dandole vuelta y viendo algunos ejemplos que conozco de edificios, y la verdad siempre se resume a calle, no int y no ext, donde calle y no exterior es siempre igual para todos, y solo cambia el no interior, que normalmente incluye el piso y departamente en el mismo nombre, como 1001, 1002, 2001, 2002 etc.

**Comment by RigoFlores** [comment]
OJO, creo que estamos confundiendo el concepto de calle.
Una cosa es el domicilio del condominio, que es la dirección estándar.
La otra, es que al INTERIOR DEL CONDOMINIO existan varias calles o andadores.

Para que se ocupará esta función? Pues para que tu puedas generar un reporte de cartera por cliente o cartera general, donde le puedas aplicar un filtro adicional a los que ya existen ahora mismo: por edificio, o por calle, por andador, por edificio-piso, o por algún otro filtro dentro de la organización del condominio.

Para propósitos de dar de alta condóminos (vecinos), esto se hace dentro del catálogo de clientes y ahí mismo ya lleva un domicilio con calle, número interior, exterior que corresponden al interior del condominio. En mi caso, sería únicamente el número exterior, ya que no tiene nombre la calle. La colonia sería quizás el nombre del condominio.
En el caso de la plaza comercial, que tiene 15 locales, pues cuando se da de alta cada local, solo se le asigna el número de local y ya (en el domicilio del receptor).

Para un condominio mas grande, como donde entiendo vives tu, es en el catálogo de clientes, donde se le debería según yo, asociar en qué cotto, edificio, sección, etc pertenece.

**Comment by jccastillo0007** [comment]
Creo que este ticket esta duplicado con el 1307.
