### ISSUE TITLE
Condominio - identificar los receptores por RFC genérico + condominio en el descargaT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1317]
El RFC genérico lo ocupa cualquier condominio (emisores).
Dentro de la organización de un condominio, se repiten los RFC's genéricos.
Hay que manejar el nombre alterno y/o número de cliente (según yo es lo mismo).

En el descargaT, tenemos que poder identificar el receptor de manera única.
Hoy en día, si entras con el RFC, te presenta las facturas de varios emisores. Eso hay que modificarlo, para que en el caso de un condominio, solo pueda descargar y consultar las facturas propias.

Esto debe hacer match, cuando un receptor que no pertenece a ningún condominio, quiera descargar alguna factura ya sea del emisor 1 o el emisor 2, o el emisor n.

**Comment by jccastillo0007** [comment]
Repetido con el ticket 1304

**Comment by RigoFlores** [comment]
mas bien el 1306. Aquí el texto de aquel... que lo importante es que tengas la idea clara.
Y si como comentamos, esto debería aplicar únicamente para el RFC genérico XAXX010101000

Ya pensando en la aplicación para los condominios, resulta que el mismo RFC receptor que en muchos casos será XAXX010101000 para los residentes que no quieren factura a su nombre, tendrá multiples nombres alternos, para uno mismo rfc emisor que es el del condominio.
Entonces debemos soportar que el mismo rfc con su nombre alterno, pueda acceder para descargar las facturas que solo le corresponden a dicho residente.

XAXX010101000 - Nombre alterno = Casa10
XAXX010101000 - Nombre alterno = Casa23

cuando el residente de la casa 10 acceda al descargat, solo deberá ver sus facturas.

Hoy en día solo soporta registrarse por RFC.

OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO OJO

Ese RFC genérico XAXX010101000 y sus respectivos nombres alternos son receptores de facturas, deben poder distinguir a cuál RFC emisor están relacionados.
Esto es, imagina que todos los RFC's emisores tienen dado de alta el rfc receptor genérico. Entonces ahora mismo, si te registrar para ese RFC genérico en el descargaT, podrás ver toooooodas las facturas de toooooodos los emisores, lo cual por supuesto no es deseable,

**Comment by jccastillo0007** [comment]
y esta pior... porque la aplicación puede soportar XAXX010101000 + Nombre alterno, como llave para entrar, peeeero, solo soporta tener un password por RFC... asi que esto se sale del contexto del descargat... debo pensar en otra opción.

**Comment by RigoFlores** [comment]
Lo que se me ocurre, es que internamente al password que capturen, le agregues el RFC emisor + el número de cliente.

Es decir si el pwd que definieron o capturaron es 'acces0', en la bd deberías registrar acces0_TIA101020BP4_23.

En el ejemplo ese cliente es de la tia, y tiene número de cliente 23.... ellos solo teclearían acces0, pero la aplicación le agregaría el resto... es una opción que pensé hace tiempo, cuando empezó esto hace ya varios meses...

**Comment by jccastillo0007** [comment]
listo, pero solo lo probé localmente

**Comment by RigoFlores** [comment]
no lo puedo validar yo?
Y cómo es que se valida?
Tendría que pedir el rfc del condominio, así como el número de cliente, que no?

**Comment by jccastillo0007** [comment]
ok, asi es como funciona.

Para receptores con un rfc en particular, ellos se deben registrar en nuestro portal descargat de manera natural

Para receptores con rfc XAXX010101000, cuando dan de alta una casa, seleccionando todos los niveles de un condominio, se va a crear automaticamente el usuario de esa casa, con esta estructura 

XAXX010101000_B45464, donde B45464 es la casa de ese condomino

Con ese usuario y el password "facturat" podrán ingresar al descargat

**Comment by RigoFlores** [comment]
pero que pasará cuando 2 condominios (emisores), tengan simplementa la casa 29 o el número que sea?
No identificará el RFC del emisor...

**Comment by jccastillo0007** [comment]
si, porque cuando hacen login in, deben indicar de que condominio son... entonces no importa si la casa tiene el mismo id, como C4, se valida también el nombre del condominio.

**Comment by RigoFlores** [comment]
Como platicamos, cuando se ingrese con el rfc genérico, está de sobra el sufijo con el identificador de la casa.
En lugar de XAXX010101000_C2, solo se ingresa el rfc XAXX010101000, ya que como quiera se indica el RFC del condominio y la casa.

**Comment by jccastillo0007** [comment]
done
