### ISSUE TITLE
Condominio - soportar el saldo inicial

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1319]
Cuando se inicia la operación de un condominio, un receptor (vecino) podrá tener saldo a favor o en contra. Entonces ese saldo inicial servirá para calcular su estado de cuenta.
OJO, no estoy seguro que el saldo inicial se ocupará en todo momento cuando se genere el estado de cuenta de un vecino. Dependerá de cómo está implementado ese reporte.

**Comment by jccastillo0007** [comment]
Ya esta soportado, en el catálogo de cliente se puede capturar... y según yo ya se usa en CxC, pero, habría que validar todos los lugares donde se debe usar...

**Comment by RigoFlores** [comment]
El tema es que todos los según tu, no jalan.
Una cosa es que exista el campo en el catálogo de clientes, y otra muy distinta es que se tome en cuenta al momento del cálculo de la cartera. 
Acabo de hacer una prueba, y nada, está como siempre, es decir que nunca se ha tomado en cuenta ese campo.
Si el saldo inicial es positivo, es que debe. En caso contrario, saldo inicial negativo, es que tiene saldo a favor.
No hay forma de colocar un botón o algo, que una vez que capturas el saldo inicial, le des commit para que ese dato no se vuelva a modificar en futuras ocasiones. Esto es que tome el saldo inicial y ya lo deje fijo para cada cliente.

**Comment by jccastillo0007** [comment]
mas bien hay que hacer que se tome en cuenta, eso es supongo en CxC...

Eso que dices que se asigne un saldo inicial y se deje fijo... es precisamente el campo de saldo inicial del cliente.

**Comment by jccastillo0007** [comment]
por cierto, este resumen del saldo inicial, me lleva a pensar que eso se solicito, nunca se implemento correctamente, pero tampoco nunca se ha usado, lo cual me lleva a pensar que fue otro requerimiento que realmente no fue necesario, y creimos que se iba a usar...

es hasta ahora donde ya debe usarse y supongo ahora si se va a validar que se contabilice correctamente.

**Comment by RigoFlores** [comment]
En la parte de CxC, precisamente se ocupaba para un cliente nuevo, que se le pudiera asociar un saldo inicial. Optibelt es el único usuario de CxC que realmente explota el módulo con reportes y todo, pero ellos no ocuparon esa información.

Se solicitó saldo inicial, pensando en cualquier otro cliente, al igual que monto máximo de crédito.
Ese saldo inicial, es para cargar el saldo a favor o deudor, de cualquier cliente, y en particular del sistema de condominios.

Lo que el saldo inicial se quede fijo, me refiero a que no puede estar cambiando cada ocasión que se nos ocurra. Es como cuando generas una factura y aún no se paga, entonces ese cliente tiene un saldo deudor, que no cambiará a menos que pague. 
Quizás no me estoy explicando. Es un valor que suma o resta en el cálculo de la cartera de cada cliente de manera inicial.

**Comment by RigoFlores** [comment]
De hecho si te das cuenta, el requisito no era que existiera un campo en el catálogo de clientes, eso ya existe desde hace mucho.
El requisito es que se tome en cuenta cuando se genere la cartera de cada cliente, y precisamente se dió de alta como un requerimiento nuevo, PORQUE EVIDENTEMENTE NO EXISTE.

**Comment by RigoFlores** [comment]
Según yo, atendiendo este requerimiento, podemos empezar con el condominio al nivel mínimo...

**Comment by jccastillo0007** [comment]
ya esta contemplando el saldo inicial en PRU

**Comment by jccastillo0007** [comment]
pero no se como se refleja eso en los archivos de excel

**Comment by RigoFlores** [comment]
El saldo inicial en positivo, se interpreta como que ese cliente arranca con un adeudo.
El saldo inicial en negativo, se interpreta como que ese cliente arranca con un saldo a favor.

Imagina que iniciamos en un condominio o plaza comercial, donde no se han emitido remisiones o facturas desde nuestra aplicación, pero un condómino o locatario tiene un adeudo de $1,000.00. Entonces, se le emite una remisión o factura a ese condómino por $500.00, que aún no ha pagado.
Entonces la cartera para ese cliente deberá ser el saldo inicial + la factura = 1,000 + 500 = $1,500.00

**Comment by jccastillo0007** [comment]
si, eso si me queda claro.. y las sumas y restas ya las esta haciendo...
pero si exportas la consulta a excel, donde se pone el saldo inicial?

**Comment by jccastillo0007** [comment]
ya esta listo este requerimiento

**Comment by RigoFlores** [comment]
Bueno, en pantalla no está reflejando ese saldo. Ni siquiera he intentado el excel.
En ambiente de pruebas, me día de alta con un saldo inicial de 500, pero no se ve reflejado al consultar la cartera de cliente, solo refleja una factura de 1,160.00 que generé.

Donde verse reflejado? Quizás para no moverle, agregar un registro (similar al de factura), y que diga Saldo Inicial, o SI, mostrando el abono que puede ser a favor o en contra. Sería un registro único.

La otra es que a nivel de encabezado, se indique como un parámetro (similar a la fecha, cliente, etc), el saldo inicial.

**Comment by jccastillo0007** [comment]
ok, ya esta el tema de que se contabilicen, falta el tema de mostrarlo de alguna forma en la pantalla y en el reporte

**Comment by RigoFlores** [comment]
OK, entonces hay que mostrarlo en pantalla y en el reporte.
OJO, cuando el saldo inicial es positivo, quiere decir que el receptor debe.
Cuando es negativo, quiere decir que tiene saldo a favor.

Ahora mismo lo está considerando al revés. El saldo inicial lo está restando, en lugar de sumarlo.
En pocas palabras, el saldo inicial lo tiene que sumar siempre, ya que si tiene signo negativo, en automático por simple aritmética lo estará restando.

**Comment by jccastillo0007** [comment]
Listo, ya se muestra como primer row de la consulta...

**Comment by RigoFlores** [comment]
Le puedes asociar al SI, la fecha igual o menor al de la primera factura o remisión.
Esto es porque si solicito un reporte de cartera de cliente, a partir de una fecha X, siempre muestra el saldo inicial.

El saldo inicial debe tratarse como la factura 0, pero no debe mostrarse siempre.

**Comment by jccastillo0007** [comment]
me parece que en lugar de manejar el concepto de saldo inicial... habrá que manejar nota de crédito o factura... ya que el saldo inicial actualmente se captura en el catálogo de clientes, y de ahi se toma al generar un reporte de cxc por cliente.... no hay un registro como tal al cual asignarle una fecha y siempre se debe tomar en cuenta, para que los número cuadren, si hacen consulta de cxc a partir de una fecha, y no se contempla el saldo inicial, me parece que no saldría la cantidad correcta

**Comment by RigoFlores** [comment]
OK, entonces eliminemos ese campo de la pantalla de catálogos del cliente.
No me convence mucho, pero suena razonable.

Ya en el camino, veremos como nos va con ese asunto.
