### ISSUE TITLE
EN DATOS EXTRA CARTA PORTE, MOSTRAR NOMBRE EN LUGAR DEL RFC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#132]
PARA REMITENTE Y DESTINATARIO, SE REQUIERE ELEGIR DESDE EL COMBO, POR NOMBRE Y NO POR RFC.
TAL CUAL LO HACE EN ESCRITORIO

**Comment by jccastillo0007** [comment]
done
