### ISSUE TITLE
Documento de Pago - soportar CFDI relacionado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1320]
El mismo código que ya se tiene en la factura, para elegir el tipo de relación y documento relacionado, hay que incorporarlo dentro del cuadro que se habilita en CxC - Ingresar Cobro, cuando se elige que se incluya el CFDI de Pago.

Lo solicité hace varios meses, pero se ignoró. Finalmente ya lo están pidiendo los clientes.
Esto es para indicar cuando un documento de pago se tiene que volver a emitir porque el documento de pago anterior era incorrecto.

**Comment by RigoFlores** [comment]
?

**Comment by RigoFlores** [comment]
Igualmente lo están esperando en la frontera. Y ya tenemos 2 semanas que se reportó y meses desde que se solicitó...

**Comment by jccastillo0007** [comment]
oye, los cfdi relacionados son los que se estan pagando con ese cobro... son los documentos relacionados, y esto que estas pidiendo son los cfdi relacionados cierto ?

que pinche desmadre.

**Comment by jccastillo0007** [comment]
odio los documentos/cfdi relacionados

**Comment by jccastillo0007** [comment]
y esos cfdi relacionados, se deben agregar a nivel del cfdi cierto? no van al nivel del documento de pago

**Comment by RigoFlores** [comment]
afirmativo, debí indicar cfdi relacionado en lugar de documento relacionado.
Aplica para web y conector... estamos perdiendo unos clientes de la frontera por ambos casos

**Comment by RigoFlores** [comment]
Esos clientes son maquiladoras, te imaginarás que tienen un buen consumo, pero estamos en la tablita por no cubrir este requisito...

**Comment by jccastillo0007** [comment]
tengo el código listo, pero no lo pude probar

**Comment by jccastillo0007** [comment]
Listo en PRU

**Comment by RigoFlores** [comment]
en chinga a pro
