### ISSUE TITLE
Agregar header y footer nuevos en la plataforma de facturación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1321]
Ya los envié por correo, si están muy chonchos, hay que compactarlos.
El footer, se tiene que cargar hacia la derecha para que no tape el menú cuando lo extiendes, sobre todo el menú de abajo.

**Comment by jccastillo0007** [comment]
chiaaaa como este ticket terminó siendo un bug y defect...

El footer lo puse centrado...

Ya esta en PRU y PRO...

las imágenes están bien chidas... pero no se si el azul tan fuerte va con los demás colores que tenemos, tal vez tengamos que cambiar los iconos

**Comment by RigoFlores** [comment]
En pro no se muestra... en pru se muestra chueco, donde la petición es cargarlo totalmente a la derecha... no se hizo el ajuste en la ubicación...
<img width="681" alt="header footer" src="https://user-images.githubusercontent.com/2912775/38316258-e78a42e4-37ef-11e8-94f3-76f37535459d.PNG">

**Comment by jccastillo0007** [comment]
Debe aparecer al centro, dale refresh o reload para que no tome en cuenta tu cache
![new header](https://user-images.githubusercontent.com/2245679/38345403-87a6509a-387e-11e8-9da7-29da0bd7d795.png)
