### ISSUE TITLE
Optibelt - nota de crédito, no respeta el uso del CFDI en el XML, pero si en el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1322]
Al XML siempre le envía el mismo valor, y en el PDF si refleja lo que se envía en el archivo de texto.

**Comment by jccastillo0007** [comment]
fixed.

Release de hoy en la noche.

**Comment by RigoFlores** [comment]
Validé desde la plataforma (ya que ellos tienen conector), y entre el PDF y XML sigue existiendo diferencia... todos los PDF tienen tipo de uso G01 y en los XML aparece el G02.
Estas facturas con las que se envían por correo a los clientes, so... sigue estando chueco.

Habría que revisar cuál es el correcto. Solicitaré algunos archivos solo para validar cuál es la neta, pero de que están chuecos, pues si, siguen chuecos...

**Comment by jccastillo0007** [comment]
aqui entonces cual es el que esta bien, xml o pdf ?

Yo creo que el xml, pues es el que viene desde standalone y probablemente en la conversión a PDF se esta perdiendo, pero hay que confirmar

**Comment by jccastillo0007** [comment]
según lo que vi, si es posible que el problema era el PDF... ya hice unos cambios, voy a monitorear la base de datos para ver si se corrigio

**Comment by jccastillo0007** [comment]
acabo de verificar esto en la  base de datos de producción, y ya esta corregido.. checale para poder cerrar este ticket

**Comment by jccastillo0007** [comment]
ya generaron mas NC.
| 577379 | 2018-05-14 14:39:42 | NOTA DE CREDITO   | G_02            |
| 577380 | 2018-05-14 14:39:48 | NOTA DE CREDITO   | G_02            |
| 577381 | 2018-05-14 14:39:52 | NOTA DE CREDITO   | G_02            |
| 577383 | 2018-05-14 14:39:56 | NOTA DE CREDITO   | G_02            |
| 577384 | 2018-05-14 14:40:00 | NOTA DE CREDITO   | G_02            |
| 577385 | 2018-05-14 14:40:05 | NOTA DE CREDITO   | G_02            |
| 577386 | 2018-05-14 14:40:09 | NOTA DE CREDITO   | G_02            |
| 577387 | 2018-05-14 14:40:14 | NOTA DE CREDITO   | G_02            |
| 577388 | 2018-05-14 14:40:18 | NOTA DE CREDITO   | G_02            |
| 577389 | 2018-05-14 14:40:23 | NOTA DE CREDITO   | G_02            |
| 577390 | 2018-05-14 14:40:27 | NOTA DE CREDITO   | G_02            |
| 577391 | 2018-05-14 14:40:32 | NOTA DE CREDITO   | G_02            |
| 577392 | 2018-05-14 14:40:36 | NOTA DE CREDITO   | G_02            |
| 577393 | 2018-05-14 14:40:40 | NOTA DE CREDITO   | G_02            |

**Comment by RigoFlores** [comment]
Pues sigue mal; no creo que tenga que ver con la BD.
Según yo, tiene que ver las variables que se envían al PDF, cuando llega a la plataforma.
El problema hay que recordarlo, y es que el XML y PDF tienen distinto uso de CFDI.
El bueno, debe ser el XML, ya que el uso que aparece en el PDF, no aplica para nota de crédito.

**Comment by jccastillo0007** [comment]
chiaaa ya vi que era... ahora si, apartir de mañana vuelve a checar pl
