### ISSUE TITLE
Conector - Documento de Pago - ignora el documento relacionado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1323]
No está tomando en cuenta lo siguiente dentro del texto plano de pago:

**CFDIRelacionados={P|250}
TipoRelacion=04**

El tipo de relación si lo envia al PDF, pero el UUID no lo envía al PDF
Al XML no envía ningún dato de este nodo

también sería bueno considerar que si viene un solo dato dentro de

CFDIRelacionados={P|250}

se trata directamente del uuid. Por ejemplo:

CFDIRelacionados={97943061-E8F0-4657-A88B-EC182C8DA919}

**Comment by jccastillo0007** [comment]
ok, pero, pueden venir n cfdi relacionados ?

**Comment by RigoFlores** [comment]
si, podrían ser varios. Entonces uno entre cada corchetes.
OJO, las dos opciones simultáneas se ocupan.
Ya que podrian querer relacionar un CFDI que no se hizo en facturat

**Comment by RigoFlores** [comment]
Tenemos detenidos clientes de la frontera. Ya me habló para comentar que están pensando en cambiarse.

**Comment by jccastillo0007** [comment]
ya tengo esta implementación... la subí hoy al dropbox.
Puedes probarla, pero no te va a timbrar por el pedo del PRU con digital ocean, pero en el log puedes ver el xml
Si todo lo ves bien, puedes probarlo en PRO e incluso liberarlo a quien lo esta esperando

En web tengo el código, pero ahi no pude probar la generación del XML

**Comment by jccastillo0007** [comment]
Soporta estas combinaciones.

TipoRelacion=04

CFDIRelacionados={|161045308},{|11},{|161040813}

CFDIRelacionados={CCF518B0-DC5C-4382-9470-CADEE893AA81},{CCF518B0-DC5C-4382-9470-CADEE893AA81}

CFDIRelacionados={|161045308},{|11},{|161040813},{CCF518B0-DC5C-4382-9470-CADEE893AA81},{CCF518B0-DC5C-4382-9470-CADEE893AA81}

**Comment by RigoFlores** [comment]
quedó robusto...!!!

**Comment by RigoFlores** [comment]
ahora truena, cuando le incluyo en un texto de pago, el documento relacionado.
Envíe un correo con el archivo de texto que está tronando

**Comment by jccastillo0007** [comment]
El campo cadPago es obligatorio, se espera algo como :   

cadPago=||1|14032018|14032018|143609|40072|HSBC|VICTOREEN DE MEXICO S A DE C V|40|021180040598321626|VME871116R22|BANORTE/IXE|TRANSFORMACIONES INDUSTRIALES ESPECIALIZ|40|072818006675395694|TIE101203NZ4|PAGO VICTOREEN A TRANSFORMACIONES ESP DE|0|3172.14|00001000000305298787||Rea2+ZVznhwzMgEmiHX34OJt1BH3Z7vrbStBWrU++/5ZfAutP7jGANs1hHCM5+GAMrz6D71DVlAMhh5e/ATRGCkagqYqwtgAQmwsUOR30f49u24ZAkXsqbEVjGX6mjJE7Crbxu3ir4lRnNOCTFiHqj0gOge0vmXU1RpDj5YGlnw=


Y en el archivo que me enviaste, no traia ningún documento relacionado

**Comment by RigoFlores** [comment]
Hay una confusión... existen 4 campos que cuando se incluye alguno, se esperan OBLIGATORIOS los otros 3, sin embargo puede ser que no se incluya ninguno de los 4, y no debe marcar error por ese motivo
TipoCadPago, CertPago, SelloPago y CadPago.

Adicionalmente, no está aceptando los CFDI's relacionados. Pls verifica bien.

**Comment by jccastillo0007** [comment]
hhhmmmm pues no sabia de esa combinación de los 4 súper valores... de hecho no tengo ninguna validación al respecto... no se como lo estén usando hoy en día.

**Comment by jccastillo0007** [comment]
ya le quite el tema de que cadpago sea obligatorio... el archivo que me enviaste ya lo procesa correctamente.
Lo que se me hizo raro es que el archivo que me enviaste no tiene nada de documentos relacionados, ya que esos se incluyen en un campo independiente llamado documentoRelacionado

Si estamos hablando de lo mismo ?

**Comment by jccastillo0007** [comment]
de hecho me encontré un archivo con el que probé anteriormente lo de documentos relacionados... te lo mandé por email.

**Comment by RigoFlores** [comment]
OK, pero no encontré ninguna nueva versión.
En cuanto esté listo, lo valido. Muy importante, es la regla de que si aparece uno de los 4 datos, entonces tendrían que incluirse los 4 datos. Si no se incluye ninguno, no hay problema.
Cómo lo están haciendo? Sergio el de tamaulipas, creo que está enviando todo ,pero eso marcará error tarde o temprano, quizás mas temprano que tarde.
