### ISSUE TITLE
CxC - Cartera por Cliente - Exportar a excel marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1324]
Con la cuenta de la TIA accedo a CxC - Cartera por cliente.
Le indico una fecha inicial y la condición de vigentes+vencidas.
Genero reporte y lo muestra en pantalla.
Al momento de tratar de exportarlo al excel, me marca error (internal error).

**Comment by jccastillo0007** [comment]
done
