### ISSUE TITLE
Nómina - No reconoce la longitud del curp como válida, y si está correcta... 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1325]
Rfc del empleado: SAMR000202E40
Su curp está correcta en longitud, pero si quiero guardar el registro marca que debe ser de 18 caracteres.

Curp: SAMR000202HQTNNBA1

Ahora mismo se lo actualicé manualmente, pero cualquier cambio en fechas que hagan estará marcando lo mismo…

**Comment by RigoFlores** [comment]
Tenemos a este cliente detenido.....

**Comment by jccastillo0007** [comment]
pues crei que lo habias actualizado directo en base de datos.... 

Como quiera ya con pruebas arriba ya puedo revisarlo, ahorita lo hago

**Comment by jccastillo0007** [comment]
que cliente es ?

chiaaaa

**Comment by jccastillo0007** [comment]
ya vi que es... según esta validación de curps

[A-Z]{4}[0-9]{6}[A-Z]{6}[0-9]{2}

Al final de la curp, esta esperando 2 dígitos... y el empleado de arriba tiene A1... 
tons supongo que la validación esta mal... ya que aseguras la CURP esta bien

**Comment by jccastillo0007** [comment]
done, directamente en PRO

**Comment by RigoFlores** [comment]
Si actualicé en BD, pero no permitía guardar ningún cambio, por lo que comentas, es porque se volvía a aplicar una validación. 
De hecho el patrón del curp es el siguiente, donde el penúltimo puede ser letra o número y el último caracter si debe ser número:

[A-Z][A,E,I,O,U,X][A-Z]{2}[0-9]{2}[0-1][0-9][0-3][0-9][M,H][A-Z]{2}[B,C,D,F,G,H,J,K,L,M,N,Ñ,P,Q,R,S,T,V,W,X,Y,Z]{3}[0-9,A-Z][0-9]
