### ISSUE TITLE
Implementar mailing, desde una IP dedicada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1326]
En teoría desde ahí, nosotros mismos vamos construyendo nuestra reputación (en el mailing... jeje).
Entiendo que en los correos, deberíamos incluir links para borrar de la lista, y otras cosas que 'deben ser' o existir en un 'correo decente'.
Entiendo que no solo se trata de mandar el correo de la ip dedicada, también hay que hacer chamba en los correos.
Por otro lado, es el único camino para garantizar la entrega o quizás ocupar un 'carrusel' de cuentas de gmail, para el envio de los correos... cómo vex???

**Comment by RigoFlores** [comment]
Optibelt, siguen siendo el dolor de cabeza con este asunto.
Hoy les puse una cuenta de correo (del emisor) de gmail, y empezó bien, pero con el paso de las horas empezó el rebotadero... creo que definitivamente necesitamos servicio de ip dedicada, o quizás necesitamos ajustar la plantilla de correo que enviamos, para que cumpla con los cánones del emailing

**Comment by jccastillo0007** [comment]
O quiza Optibelt deba configurar nuestro dominio @factura-t.com.mx como no
SPAM o no bloquearlo.. o algo asi.

Si con gmail también lo rebotaron, no se si la IP fija funicione, tal vez
este de su lado.

JC

Saludos.
JC.

2018-04-25 19:43 GMT-05:00 RigoFlores <notifications@github.com>:

**Comment by RigoFlores** [comment]
Podemos reintentar enviar desde factura-t.com.mx, pero el tema no es el dominio, el tema de la IP desde donde se encuentra el servidor smtp de salida, y esa dirección IP al ser compartida, es muy probable que se encuentre en el blacklist.

Ya crearon una cuenta en gmail, la pueden hacer de paga y que desde ahí se envíe con los parámetros propios de esa cuenta. Lo podemos hacer? 
Es decir mantener el esquema actual con proveedor de paga, pero para ciertos clientes configurar su cuenta de correo con SUS PROPIOS PARÁMETROS????

**Comment by jccastillo0007** [comment]
Puedes seguir las instrucciones que te mande para comprar una ip dedicada... para poder hacer el switch

**Comment by RigoFlores** [comment]
Tienes cuenta en sendinblue?
En caso afirmativo, pásame los datos.

**Comment by jccastillo0007** [comment]
Sendingblue
___________

jccastillo@factura-t.com.mx
password por email

**Comment by RigoFlores** [comment]
te debió llegar un correo de confirmación y supongo con instrucciones o claves, para los siguientes pasos
