### ISSUE TITLE
Agregar el Sello de Pago al conector para generar el documento de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1327]
Está faltando ese dato.
Adicionalmente la cadena de pago, está llena de "|", por lo que es importante bajar a un renglón único el dato de cadena de pago, y tomarla desde el = hasta el final.

CadPago=||1|21032018|21032018|140815|40072|HSBC|VICTOREEN DE MEXICO S A DE C V|40|021180040598321626|VME871116R22|BANORTE/IXE|TRANSFORMACIONES INDUSTRIALES ESPECIALIZ|40|072818006675395694|TIE101203NZ4|PAGO VICTOREEN A TRANSFORMACIONES ESP DE|0|12102.63|00001000000305298787||BKuyW4jYUVNaFx1NH4RlMmy6A6okHu7L0h5eeNnkZ2rEz5U3rgzx3aQ1yxuBTm/MMzs2jWcP1QAlxu2ocaDcgDoeJlWDpzqPIUCQUuB7yPtcWqxoSEryUB6QxlsbMZp0Bjc7QoZm0WLoouPOTaPi4eQqBylyR6s2xeve8rFO/KY=

**Comment by RigoFlores** [comment]
ya te mandé un ejemplo de un texto de como queda... lo están esperando ....

**Comment by RigoFlores** [comment]
lo siguen esperando... hablan diario..

el tema de pagos que no jala en web, y que no jala por conector, es un asunto ya de urgencia

**Comment by RigoFlores** [comment]
Ya te mandé como quedaría el layout de pagos... no veo porque ello tendría que detener este issue, pero bueno..

**Comment by jccastillo0007** [comment]
listo.
Te mande por correo el txt utilizado y el xml generado.

En el archivo que me enviaste, tenia el tipCadPago = 40 y no lo acepta, lo cambie a 01
