### ISSUE TITLE
ESTÁ GENERANDO DOCUMENTO DE PAGO (PDF) PERO SIN INCLUIR EL COMPLEMENTO EN EL XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1328]
ANEXO EJEMPLO… ES DE PRODUCCIÓN. (LO ENVIÉ POR CORREO)
SI ALGO ESTÁ MAL EN PRUEBAS, CON EL CONECTOR, MANDA UN MENSAJE DE ERROR Y NO TIMBRA NI GENERA NADA DE DOCUMENTO DE PAGO.

EN PRODUCCIÓN (WEB), SI GENERA XML Y PDF, PERO ESTÁ MAL PORQUE NO INCLUYE EL COMPLEMENTO EN EL XML… LO QUE HE VISTO ES QUE SI ALGO ESTÁ MAL, NO SÉ PORQUE RAZÓN SIMPLEMENTE NO INCLUYE EL COMPLEMENTO, PERO EL PDF SI MUESTRA TODO Y EL CLIENTE SE QUEDA CON QUE TODO ESTUVO BIEN.

**Comment by jccastillo0007** [comment]
por un lado, eso sucede cuando no se incluyen todos los datos extras que se necesitan en el complemento... algo ahi debe estar faltando, tienes el txt ?

**Comment by RigoFlores** [comment]
es en web...

**Comment by RigoFlores** [comment]
Te mandé un correo con toda la información para reproducirlo...
Están esperando desde hace un buen rato que no jala esto...

**Comment by jccastillo0007** [comment]
chiaaaa
Generé varios documentos de pago en PRU...

Revisé el caso específico del cliente que me enviaste, y resulta que no tiene el plugin de addendas.... el cuál es requerido para todos los complementos y addendas, igual que el plugin de datos extras.

Ahora si te viste muy novato k

**Comment by jccastillo0007** [comment]
Ya le agregue el plugin de addendas

**Comment by RigoFlores** [comment]
La novatez, surge porque en el issue 1279 estás indicando otros requerimientos que se ocupan, para que se pueda emitir el complemento de pago.
Aquí te resumo lo que comentabas en ese issue:

> negativo... no se ocupan datos extras... lo que si se ocupa son datos de addenda, pero eso se habilita al tener cualquier complemento o addenda.
> 
> en este caso, se habilita con CxC Menu
