### ISSUE TITLE
Definir final y realmente lo que se ocupa para generar el documento de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1329]
Pese a la novatez, no se había especificado lo que realmente se ocupa. Ese cliente que comentas que ya arreglaste, tiene lo siguiente. Eso ya se asigna desde el KEYGENERATOR????????

mysql> select * from Users where client_id in (select id from Client where rfc = 'SER990210RXA');
+------+--------------+----------------------+--------------+-----------+--------+
| id   | password     | role                 | userId       | client_id | emails |
+------+--------------+----------------------+--------------+-----------+--------+
| 1357 | SER990210RXA | ["ADMIN","CxC_MENU"] | SER990210RXA |     31487 | NULL   |
+------+--------------+----------------------+--------------+-----------+--------+
1 row in set (0.01 sec)

mysql>      Select * from ClientPlugins where owner = 'SER990210RXA';
+------+----------------------------------+--------------+
| id   | features                         | owner        |
+------+----------------------------------+--------------+
| 2490 | ["EXTRA_DATA_IN_CFD","ADDENDAS"] | SER990210RXA |
+------+----------------------------------+--------------+
1 row in set (0.00 sec)

**Comment by jccastillo0007** [comment]
en ClientPlugins, debe tener extradata y addendas, todos los clientes que ocupen una addenda o un complemento

**Comment by RigoFlores** [comment]
OK...
