### ISSUE TITLE
CAMBIÓ LA CODIFICACION DE FONTS EN WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#133]
AHORA APARECEN LOS ACENTOS CON SÍMBOLOS RAROS

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
WEY NO HAY QUE HACER CAMBIOS DE ESTE TIPO TAN A LA LIGERA. AFORTUNADAMENTE ESTO NO ES FUE COSTOSO (ESPERO), PERO HABRÁ OTROS COMO EL DEL ERROR 009 QUE NOS CUESTE MUCHO ESFUERZO, ESTRESS Y HASTA PÉRDIDA DE BUENOS CLIENTES (SON LOS MAS SUCEPTIBLES A LOS ERRORES).
