### ISSUE TITLE
Navision - ajuste en el campo de CFDI relacionados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1331]
No se había considerado que podrían existir mas de una factura relacionada a un mismo CFDI.
Hoy en dia, en el campo :  

[Nº factura relacionada SAT] de la tabla [MEXICO - IP - PEDIMENTO$Sales Invoice Header]

De la tabla se almacena el número de folio interno, con lo que vamos a buscarlo y colocamos el UUID en el parámetro que corresponda dentro del XML.

Ahora se podrán leer varias facturas relacionadas, pero soportando el esquema actual.

Se me ocurre que pudiéramos leer varios folios separados por coma ',', por por pipe '|'.

Comenta pls...
Ya nos hicieron el pedido, asi que tenemos que entregar el cambio.

**Comment by jccastillo0007** [comment]
Te mande por correo la respuesta... 

Lo voy a implementar con | pipe

vale

**Comment by jccastillo0007** [comment]
aplica solo para facturas ? o notas de crédito también ?

De hecho viendo el código, solo aplica para Nota de Crédito...  ups

**Comment by jccastillo0007** [comment]
subi un release hoy... para hacer pruebas en navision con el rfc ACO....

**Comment by RigoFlores** [comment]
pero ese release solo se puede probar en su ambiente de pruebas... correcto???
Pásame un ejemplo de cómo lo estás esperando leer...

**Comment by RigoFlores** [comment]
Ahora mismo así se llena ese campo para la nota de crédito:

18FVMX040

entiendo que debe ser 18FVMX040|18FVMX042|18FVMX045

por ejemplo??

Ya está el código en el servidor navision, o hay que llevarlo?

**Comment by jccastillo0007** [comment]
Si correcto, se espera algo como :   

18FVMX040|18FVMX042|18FVMX045

El código hay que llevarlo al ambiente de pruebas de Navision, esta implementado solo para notas de crédito.

**Comment by RigoFlores** [comment]
Negativo, el principal requerimiento es para facturas, que es donde se ocupará.
Que bueno que ya está para nota de crédito, pero donde se ocupará es en facturas...

**Comment by jccastillo0007** [comment]
ya lo agregue a facturas...  raro que antes no estaba.

Ojo... para que encuentre dicha factura, debe existir un pago para esa factura previamente...

**Comment by RigoFlores** [comment]
Lo de los CFDI's relacionados, en facturas no se había presentado el caso, pero si existe el campo y todo está listo para que se pueda considerar.
No veo porque deba existir un pago para una factura relacionada??? No debería ser condición.

De hecho donde se va a buscar el UUID de cada folio dentro del campo de relacionados, es a la tabla de Factura-T. Ahí cada CFDI timbrado almacena su UUID, y nada tiene que ver si está pagado o no, o cancelado o lo que sea...

**Comment by jccastillo0007** [comment]
pues, capaz que es tema de las vistas ... yo no recuerdo porque esta asi... 

me parece que el tema de cfdi relacionados fue desarrollado para cuando se registraban pagos... debo hacer otros cambios para facturas.

Supongo que tampoco se ha usado en notas de credito, pues no hay reportado que no funcione

**Comment by RigoFlores** [comment]
Cuando se genera un pago, puede o no tener documentos relacionados, en el XML estándar.
Pero dentro del complemento de pago, tiene sus doctos relacionados, que son los CFDI que se están pagando.
No sé si para los pagos está considerando esa condición.

Pero para una factura estándar, ese campo se ocupa para indicar los CFDI's relacionados.

En nota de crédito SIEMPRE lleva un CFDI relacionado, y aún no se presenta la condición que lleve mas de uno. Por eso el requisito es para la factura estándar, y aprovechando de una vez para notas de crédito, pero no se ha presentado el caso para notas.

**Comment by jccastillo0007** [comment]
listo, subi un release al dropbox ya con la corrección de leer el uuid de la tabla facturat

**Comment by RigoFlores** [comment]
No hay tal rilís... y el cliente sigue en espera...

**Comment by jccastillo0007** [comment]
chiale... eso pasa por usa dropbox como devops

**Comment by RigoFlores** [comment]
Pues no, no jaló... checa esta consulta... según yo está el formato correcto.. 18FVMX089|18FVMX090
Y no incluyó nada en el XML, y por añadidura tampoco en el PDF

<img width="508" alt="navisioncfdisrelacionados" src="https://user-images.githubusercontent.com/2912775/40203038-9092c4ea-59e9-11e8-92d9-f1662de66a38.PNG">

**Comment by RigoFlores** [comment]
Este fue el query con el que actualicé ese campo:

update [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Sales Invoice Header] set  [Nº factura relacionada SAT] = '18FVMX089|18FVMX090' where [No_] 
in ( '18FVMX093' );
