### ISSUE TITLE
Nuevamente está mostrando los CFDI's de pago en los reportes de CxC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1332]
Recuerda que  los CFDI's de pago no deben aparecer para propósitos de CxC, en cuanto a reportes.
De hecho únicamente como opción de emitir el CFDI de pago, cuando se ingresa un pago, pero fuera de ahí, no deben aparecer para nada.

Te mandé un correo con evidencia.

**Comment by jccastillo0007** [comment]
Fixed,... en PRU y PRO
