### ISSUE TITLE
Navision - Nota de crédito envía el total incorrecto al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1333]
Al XML lo envía bien, pero al PDF lo envía incorrecto.
Según yo, eso ya se había presentado y corregido antes..

[evidencia issue.zip](https://github.com/jccastillo0007/eFacturaT/files/1993548/evidencia.issue.zip)

Aquí tienes 2 notas de crédito del día 07 de mayo, y te darás cuenta que el total en el XML es correcto, pero cuando lo envía al PDF ya va chueco...

**Comment by jccastillo0007** [comment]
listo. subi un release al dropbox...

Ya he arreglado esto varias veces, no recuerdo si las anteriores eran facturas y ahora estas son NC, o si ellos no guardan de forma consistente los datos en su base de datos.
chiaaa

**Comment by RigoFlores** [comment]
la información es correcta en la BD, en otro caso no permitiría timbrar el PDF, si las cantidades no coincidieran.
El problema es o era al enviar el total al PDF.
Apenas voy a validar en pro, junto con lo de los CFDIs relacionados múltiples para notas o facturas

**Comment by jccastillo0007** [comment]
como fueron las pruebas ?

**Comment by RigoFlores** [comment]
No hay ambiente de pruebas para Navision, según yo tendrías que generar una versión exclusiva para pruebas.
Así que dependemos de que generen una nota de crédito, ahora mismo voy a ver si existe alguna...

**Comment by RigoFlores** [comment]
Casualmente hicieron una ayer, y si ya quedó...
