### ISSUE TITLE
Addendador Mabe - ajuste a la medida para  TME080527TY3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1334]
Para este RFC emisor TME080527TY3, la unidad de medida en todo producto o servicio dentro de la adenda mabe debe ser siempre ‘SER’.
Es decir, ignorar la unidad de medida que viene en el XML estándar... solo para este RFC...

Me confirmas pls?

**Comment by jccastillo0007** [comment]
Listo en PRO...
