### ISSUE TITLE
CCE - cuando la factura original es en MXN, en el complemento no reporta bien los USD

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1336]
Y es que en el complemento, se deben reportar los importes en USD.
Por lo tanto falta hacer la conversión a nivel de cada producto y a nivel general de los importes, para reportarlos en USD, así como incluir el tipo de cambio que se tenga capturado en el catálogo de monedas.

**Comment by jccastillo0007** [comment]
eso es en web verdad?

Porque para optibelt ya esta jalando

Y el connector estándar no hace calculos, solo reporta lo que llega

**Comment by jccastillo0007** [comment]
ya cerramos este ticket ?
