### ISSUE TITLE
En la pantalla de Ventas-Facturas no debe aparecer la serie PAGO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1337]
La serie PAGO solo se ocupa para los recibos electrónicos de pago.
No debe aparecer en la pantalla de facturación.
Según yo, ya se había levantado anteriormente este issue.

**Comment by jccastillo0007** [comment]
done en PRU... aún no lo subo a PRO

**Comment by RigoFlores** [comment]
OK, cuando se suba a pro lo cerramos. 
Ya ví que en pru si está...
