### ISSUE TITLE
Cuando falla el timbrado del CFDI de pago, no registrar el pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1338]
Es muy común, y lo será mucho mas cuando sea obligatorio que por captura incorrecta en los datos del CFDI de pagos, no se timbre, y envía el mensaje de error, sin embargo el pago en la BD si se registra.
Cuando quieren volver a capturar el CFDI de pago, resulta que la factura ya no aparece, porque ya se registró el pago en la BD.

La petición, es que primero pase el timbrado correctamente, y enseguida se registre el pago en la BD.

Ahora nos marcan para ver como resolver, y hay que borrar el pago y explicarles bla bla bla... la idea es minimizar los soportes.
Yo ya me ví saliendo a presentar el sistema de condominios por todos lados aquí... así que necesitamos minimizar las llamadas de soporte

**Comment by jccastillo0007** [comment]
Done
