### ISSUE TITLE
Condominio CxP - Agregar la opción de Consultar Pago en el sumenú

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1340]
Al igual que CxC, se requiere un menú para consultar los pagos registrados.
Debe aparecer en pantalla igual que aparece en CxC.
De igual manera, se podrán borrar para poder capturarlos nuevamente, para evitar la opción de editarlos.

**Comment by jccastillo0007** [comment]
listo... lo subo a PRO ?

**Comment by RigoFlores** [comment]
si, ahora mismo, nadie ocupa CxP, entonces podemos probar directamente en pro
