### ISSUE TITLE
Conector, escritorio y web - no envía correctamente los formatos de fecha al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1341]
Me lo reportaron, pero no puedo validarlo en pruebas.
Puedes checar que por conector, no sé si sea lo mismo que emitir desde la pantalla de escritorio, si se envien los **formatos de fecha igual que al XML**?

**Comment by jccastillo0007** [comment]
From Rijo :  

EN EL CONECTOR, ESCRITORIO Y WEB NO SE ESTÁ ENVIANDO EL FORMATO ADECUADO DE FECHA Y HORA AL PDF. TIENE QUE SER IGUAL EL FORMATO XML Y PDF. POR EJEMPLO 2018-05-15T14:53:33

**Comment by jccastillo0007** [comment]
Conste.....
Done.

**Comment by RigoFlores** [comment]
Ahorita el que esperan, que ya urge es el del conector... es decir necesito una nueva versión del facturat para escritorio (conector)

**Comment by jccastillo0007** [comment]
ya esta listo en dropbox version 1.3.0.5
JC

**Comment by RigoFlores** [comment]
No manches, lo dejaste apuntando a Navision...
Necesitamos una sola versión para evitar esta situación. Ahora se retrasa un día todo...
