### ISSUE TITLE
No está enviando por correo la llave generada o actualizada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1342]
El keygenerator no está enviando correo con la llave.
Tampoco se envían los correos recordatorios de folios próximos a vencer (como ya te había comentado, tiene mucho tiempo que eso dejó de jalar).

Total que seguimos con un desmadre en el tema del mailing.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Lo de recibir la llave, ya jala.

Me falta revisar lo de las notificaciones, pero eso lo voy a hacer hasta la siguiente semana.
