### ISSUE TITLE
Implementar CCE por conector Optibelt

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1343]
Ellos hacen facturas en MXN o en USD o en EUR donde van a incluir el CCE.
Ahora mismo, la primera factura la hicieron en MXN en web. Se la aceptaron, pero evidentemente tiene un error, que ya está levantado. En el complemento los importes van en USD, por lo tanto se debe hacer la equivalencia, tomando en cuenta el tipo de cambio reportado en el texto (que es el mismo que se reporta en el XML).
 
Los puntos que tenemos que considerar en esta implementación son:
 
 
A nivel encabezado:
Campo H1.31 Cuando la moneda de la factura sea MXN, debemos tomar en cuenta el campo de tipo de cambio. Por ejemplo “19.20”. Si la factura se emitió en USD, entonces el tipo de cambio ya debe incluirse ahora mismo. Si la factura es en MXN o EUR, entonces se debe indicar el tipo de cambio respecto al dólar americano.
 
En el header del CCE se reporta el tipo de cambio, pero los importes a nivel header y detalle, van en USD. Por lo tanto hay que hacer una conversión de la moneda de la factura a USD, ocupando el tipo de cambio reportado en el campo anterior.
 
A nivel de emisor, reportar el domicilio de optibelt, con las claves que pide el CCE. Esto se puede quedar fijo, o mapearlo de los datos que vienen en la llave (licencia) de facturat.
 
 
A nivel del receptor dentro del CCE:
Campo H4.13 Tomar la clave del país de acuerdo al catálogo del SAT. 
Campo H4.12 Tomar la clave del estado de acuerdo al catálogo del SAT. 
Campo H4.5 De aquí se toma la calle la calle 
Campo H4.14 De aquí se toma el código postal
Campo H4.4 Capturar el Número de Registro de Identificación Tributaria.
Campo H4.4 Cuando este campo contenga un dato (normalmente no lo tiene), Factura-T lo interpretará como indicativo que se requiere incluir el CCE.
 
 
Ellos si ocuparán el campo de destinatario en algunos casos. Esto es, cuando se incluya los datos del H5, entonces de ahí se tomarán los datos del destinatario.

Campo H5.13 Tomar la clave del país de acuerdo al catálogo del SAT. 
Campo H5.12 Tomar la clave del estado de acuerdo al catálogo del SAT. 
Campo H5.5 De aquí se toma la calle la calle 
Campo H5.14 De aquí se toma el código postal
Campo H5.4 Capturar el Número de Registro de Identificación Tributaria del destinatario.

A nivel detalle:
Campo D.2 – Indicar un identificador del producto que debe ser distinto para cada producto dentro de la factura. Este identificador es interno a optibelt. Ahora mismo no lo incluye
La fracción arancelaria y la unidad, nos la estarán indicando cómo 'calcularla', ya que solo manejan máximo 10 fracciones.

**Comment by jccastillo0007** [comment]
y el excel apa ?

**Comment by RigoFlores** [comment]
Voy a levantar issues individuales y específicos conforme vaya avanzando con las pruebas.
