### ISSUE TITLE
Fecha de Pago que se envía al PDF es incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1344]
Tenemos un cliente que es super quisquilloso, y que ha revisado con lupa el documento de pago, en particular el PDF. La fecha debe cumplir como se indica aquí... la hora que nadie conocerá, deberá incluirse como 12:00:00

Se debe registrar la fecha y hora en la que el beneficiario recibe el pago. Se expresa en la forma
aaaa-mm-ddThh:mm:ss, de acuerdo con la especificación ISO 8601. En caso de no contar con la
hora se debe registrar 12:00:00.
Ejemplo: En este caso se emitió el CFDI con complemento para recepción de pagos el día 10 de
enero de 2017, colocando dicha fecha en el campo Fecha de este CFDI y el pago se realizó el día
3 de enero de 2017, el cual se debe registrar en este campo de la siguiente manera:
FechaPago= 2017-01-03T12:11:09
Ejemplo: En este caso se emitió el CFDI con complemento para recepción de pagos el día 10 de
enero de 2017, colocando dicha fecha en el campo Fecha de este CFDI y el pago se realizó el día
15 de diciembre de 2016, el cual se debe registrar en este campo de la siguiente manera:
FechaPago= 2016-12-15T10:10:09

**Comment by RigoFlores** [comment]
PUES AHORA NUEVAMENTE, ESTÁ ENVIANDO LA FECHA, SIN LA HORA AL PDF.
DEBE ENVIAR LA HORA POR DEFAULT

**Comment by RigoFlores** [comment]
En el XML si la envía correctamente...
FechaPago="2018-09-07T12:00:00"

**Comment by jccastillo0007** [comment]
fixed
