### ISSUE TITLE
Conector - Fecha de Pago en el documento de pago en XML y PDF se toma tal cual del txt

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1346]
Hay que enviar al PDF y al XML, la cadena que se incluya tal cual en el archivo de texto.
Debe cumplir con el formato estándar, pero eso se lo dejaremos al cliente.

OJO, estamos hablando de la fecha de pago. No es la fecha de emisión, ni certificación.

**Comment by jccastillo0007** [comment]
listo, soporta fechas de pago, del complemento de pago, con formato :  
2017-07-10T02:02:02
2017-07-10

**Comment by RigoFlores** [comment]
se me pasó comentar algo, chiaaaaa.....
Cuando no conoces la hora, se debe reportar como 12:00:00.

**Comment by jccastillo0007** [comment]
alcance hacerlo hoy
