### ISSUE TITLE
CCE Optibelt - no está reportando el ID a nivel detalle del CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1349]
Recordar que el ID del producto en el XML estándar, se reporta igual a nivel detalle del CCE.
Ahora lo que manda, no se de donde lo está tomando, pero dentro del archivo de texto de optibelt, corresponde al campo D.2

cce11:Mercancia CantidadAduana="1.0" FraccionArancelaria="73269099" **NoIdentificacion="00Z6"** UnidadAduana="01" ValorDolares="9688.32" ValorUnitarioAduana="9688.32"

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
No sé de donde está tomando el ID, pero como se menciona arriba debe tomarlo del campo D,2 dentro del archivo de texto de levicom
Ahora mismo, lo reporta como ART-01

        <cfdi:Concepto ClaveProdServ="01010101" **NoIdentificacion="ART-001"** Canti
dad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="IMPRESORA EPSON L355 nu
mero de serie: 1234567" ValorUnitario="3500.000000" Importe="3500.000000">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="3500.00" Impuesto="002" TipoFactor="Tas
a" TasaOCuota="0.000000" Importe="0.00"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="0.00">
        <cfdi:Traslados>
            <cfdi:Traslado Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.000000
" Importe="0.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
    <cfdi:Complemento>
        <cce11:ComercioExterior xmlns:cce11="http://www.sat.gob.mx/ComercioExter
ior11" CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="FOB" Observaciones=
"Observaciones" Subdivision="0" TipoCambioUSD="19.0" TipoOperacion="2" TotalUSD=
"3500.00" Version="1.1">
            <cce11:Emisor>
                <cce11:Domicilio Calle="1ER RETORNO UNIVERSITARIO" CodigoPostal=
"76269" Colonia="1269" Estado="QUE" Municipio="011" NumeroExterior="1" NumeroInt
erior="65B" Pais="MEX"/>
            </cce11:Emisor>
            <cce11:Receptor NumRegIdTrib="889010357">
                <cce11:Domicilio Calle="WATERVIEW DRIVE" CodigoPostal="48309" Es
tado="MI" NumeroExterior="2968" Pais="USA"/>
            </cce11:Receptor>
            <cce11:Mercancias>
                <cce11:Mercancia CantidadAduana="1.0" FraccionArancelaria="84145
101" **NoIdentificacion="ART-001"** UnidadAduana="06" ValorDolares="3500.0" ValorUni
tarioAduana="3500.0"/>

**Comment by jccastillo0007** [comment]
eso es justo como lo hace. el campo D2 se toma tanto para el id del producto del xml estándar como el id de la mercancia... es lo mesmo
