### ISSUE TITLE
CCE OPTIBELT - está convirtiendo al revés los importes de MXN a USD

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1350]
Cuando la moneda del cfdi estándar es en MXN, se debe reportar en USD en el CCE.
Está haciendo una conversión multiplicando los importes MXN por el tipo de cambio.

En este caso, el equivalente en dólares es dividir los importes de MXN entre el tipo de cambio.

**Comment by jccastillo0007** [comment]
ups... me falló la operación..

**Comment by RigoFlores** [comment]
OJO con los cálculos.

ValorUnitarioAduana = Precio Unitario del XML estándar (en USD)
ValorDolares = (cantidad x Precio Unitario) (en USD).
TotalUSD = Sumatoria de ValorDolares.   (esto equivale al subtotal del XML estándar expresado en USD).

Actualmente el TotalUSD está considerando el total, y no el subtotal.

            <cce11:Mercancias>
                <cce11:Mercancia CantidadAduana="3.0" FraccionArancelaria="73269
099" NoIdentificacion="ID-123456789" UnidadAduana="01" ValorDolares="48.71924290
22082" ValorUnitarioAduana="16.2397476340694"/>
            </cce11:Mercancias>

**Comment by jccastillo0007** [comment]
listo... checale

**Comment by RigoFlores** [comment]
no, sigue mal y el tiempo sigue pasando... dentro del CCE, valorDolares, como comenté, debe ser igual cantidad aduana por Valor Unitario Aduana. Ahora está colocando ValorDolares = Valor unitario... 

            
                cce11:Mercancia CantidadAduana="3.0" FraccionArancelaria="73269
099" NoIdentificacion="ID-123456789" UnidadAduana="01" ValorDolares="308.88" Val
orUnitarioAduana="308.88"/>
