### ISSUE TITLE
CCE Optibelt - Domicilio del emisor y destinatario dentro del CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1351]
Enviar únicamente:
CP
Clave de Estado
Clave de País
Calle

El resto de datos son opcionales. Hay que dejarlo lo mas simple posible, igual que cuando lo implementamos para el conector estándar.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Quedó para el nodo emisor, pero no quedó para el nodo destinatario.

**Comment by jccastillo0007** [comment]
chiaaaa

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Pues ya se regresó, hoy generamos uno... y en el nodo emisor ya está enviando el municipio nuevamente, y ya rebotó... no sé porque lo está volviendo a enviar.
Mientras tanto, dime donde lo cambio y así se arregla. Recuerda que es una clave, lo que se ocupa en este caso.

**Comment by RigoFlores** [comment]
este issue, realmente nunca se atendió... porque envía los datos que captures en el domicilio del emisor (keygenerator).

La solución fue eliminar el municipio del domicilio fiscal del emisor desde el keygeneratos, con ello se evita que lo envíe.
