### ISSUE TITLE
CCE por conector estándar y para Optibelt - Nodo receptor no debe incluir NumRegIdTrib

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1352]
Ya se descompuso para la versión estándar también, así como para Optibelt.
 
Para la versión 3.3, **el nodo receptor dentro del CCE** no debe incluir el NumRegIdTrib="889010357", ya que este parámetro se incluye en el nodo receptor del XML estándar, solo en el caso cuando se incluye el CCE.

Correcto:
            <cce11:Receptor>
                <cce11:Domicilio Calle="SPS BARRIO MEDINA 13 CALLE 8 AVE" CodigoPostal="21103" Estado="SAN PEDRO SULA" Pais="HND"/>
            </cce11:Receptor>

Incorrecto:
            <cce11:Receptor NumRegIdTrib="889010357">
                <cce11:Domicilio Calle="WATERVIEW DRIVE" CodigoPostal="48309" Es
tado="MI" NumeroExterior="2968" Pais="USA"/>
            </cce11:Receptor>

**Comment by jccastillo0007** [comment]
Ok, pero no marca error, si lo acepta

Que saca en la versión estándar?

**Comment by RigoFlores** [comment]
Si marca error...

En ambos casos, dentro del complemento, nodo receptor incluye el NumRegIdTrib.... pos ya lo dije,,,, chiaaaaaa....

<cce11:Receptor NumRegIdTrib="889010357">

**Comment by jccastillo0007** [comment]
a mi no me marco error, marco algo del número de pedimento, pero no del NumRegIdTrib ... pero bueno... ya se lo quite

**Comment by RigoFlores** [comment]
ya quedó para optibelt.
Cómo puedo validarlo para el conector estándar? 

Entendería que la versión que subiste, solo se puede ocupar para optibelt?  (**VERIFICADO 2018**: esa versión solo sirve para optibelt. Falta subir esta corrección para la versión estándar)

**Comment by RigoFlores** [comment]
Claro que primero te marcó el error de pedimento (levantado en issue aparte), pero al corregirlo modificando el contenido del archivo de texto, se generó este otro error.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
para optibelt ya estaba, pero sigo esperando la versión estándar para validar que se corrigió ahí también.

**Comment by jccastillo0007** [comment]
listo, osea que nunca debe poner el numregid en el receptor, valiendole madres quien es el emisor, cierto ?

**Comment by RigoFlores** [comment]
Afirmativo, el emisor no influye ahí.
Lo que si influye, es que si el receptor NO ES EL RFC EXTRANJERO, entonces ahí no lleva el país de residencia, ni el numregid, ya que eso SOLO APLICA PARA receptores con rfc XEXX010101000.

No creo que sea tan común que una exportación, vaya con datos de receptor mexicano, pero hice la prueba y no jaló, ya que le quiere poner el país y supongo también el regid.

Entonces tanto para optibelt, como para la versión estándar, se tienen que omitir estos datos, cuando el rfc sea nacional o genérico nacional. Cómo ves, lo corregimos de una vez, o hasta que brinque la rana?

**Comment by jccastillo0007** [comment]
Pues de hecho no esta validando el receptor... simplemente si se tiene el CCE, no le pone nunca el numregid en el nodo receptor del complemento...  sin importar el rfc

No se como deba ir el nodo propietario o destinatario, por ahora no pone nada

En tu prueba, seguramente no jaló porque agregó el pais... pero ese escenario no creo que suceda.
