### ISSUE TITLE
CCE optibelt... no debe incluir el número de pedimento a nivel estándar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1353]
Es algo que desconocía, pero según el mensaje de error...  en el XML estándar NO SE DEBE INCLUIR EL NÚMERO DE PEDIMENTO, en caso que el XML incluya el CCE.

En pocas palabras, solo para el caso de CCE, no incluir el número de pedimento.

Aplica para el conector estándar y en web. Por lo pronto, urgiría para el conector estándar y para optibelt.

**Comment by jccastillo0007** [comment]
done
