### ISSUE TITLE
Navision Pagos - no está incluyendo la información del receptor en el CFDI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1356]
Aparentemente no está leyendo de la tabla factura-t, los datos de la factura que está relacionada al pago.
Te mandé un correo por la mañana.

**Comment by jccastillo0007** [comment]
listo... ya esta arreglado y ya generé el documento de pago.

lo que pasó fue que efectivamente había un problema al leer la tabla de facturat.
Pero también tuve que actualizar la tabla de pagos con estos queries :  
update [IPNavision400SP2].[dbo].[NavisionDRP] set targetRFC = 'PLM861226IU7'
update [IPNavision400SP2].[dbo].[NavisionDRP] set parcialidad = 1

esos campos estaban vacíos.

Deje el facturat abajo para que chequen antes de levantarlo

**Comment by RigoFlores** [comment]
Esa tabla que comentas es una vista que tu creaste, correcto?
Ya que la tabla original de Navision es [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Lineas Documento de pago]

Además, cuando la parcialidad es 0, indica que el pago se hizo totalmente.
No olvidar que si la forma de pago de la factura que se está pagando es PPD, entonces se debe reportar el número de parcialidad =1.

Es importante lo que comentas, ya que a esa tabla le hicieron unos cambios a mano, para que jalara y necesito saber cómo funciona realmente.

**Comment by jccastillo0007** [comment]
si el método de pago es PPD, la parcialidad = 1 , pero eso lo deben hacer ellos, pues en el conector de navision, no se valida el método de pago.

y si, es una vista que yo cree, y el campo rfc lo jala de la tabla facturat...  y esa tabla facturat ellos insertan ahi los datos...tons les esta faltando el rfc del receptor

**Comment by RigoFlores** [comment]
Me parece que no... esa tabla nosotros la llenamos al momento que regresamos del timbrado.
El RFC del receptor, tendrías que tomarla de esa tabla, si correcto, pero de la factura que están pagando.
Cuando se emite una factura y se timbra los datos del receptor y todos los demás dentro de la tabla, los actualizamos nosotros.
Cuando se va a generar un pago, nosotros vamos a conocer varios datos de la factura o facturas pagadas. Entre ellos el receptor de dicho pago. 
Entonces según yo, a quién le falta tomar ese dato del lugar correcto, es a nosotros.

**Comment by jccastillo0007** [comment]
cierto... revise la tabla facturat, y facturas del año pasado no  tienen el rfc, pero este año ya lo tienen... seguramente antes no guardaba el rfc , pero ya lo estan guardando

**Comment by RigoFlores** [comment]
Chiaaa... el año pasado no lo guardaban porque no existían los campos.
A partir de la 3.3, yo solicité que agregaran los campos que se ocupan para documentos relacionados (UUID), y para pagos (RFC receptor entre otros datos).
Ellos no guardan esa informacion. Nosotros la guardamos una vez que se timbra el CFDI.

**Comment by RigoFlores** [comment]
retomando este comentario:
si el método de pago es PPD, la parcialidad = 1 , pero eso lo deben hacer ellos, pues en el conector de navision, no se valida el método de pago.

Se contrapone con el acuerdo con ellos, de que si la parcialidad la colocan como 0, nosotros debemos interpretarlo como que la factura se pagó en su totalidad. De que nos servía saber eso, pues que no se debería reportar la parcialidad, pero ya vimos que podría o no reportarse, dependiendo del método de pago de una factura QUE YA ESTÁ EMITIDA DE TIEMPO ATRÁS, y que por lo tanto ellos no tienen control alguno del método de pago que se capturó en su momento. Lo que si es muy probable, es que casi en todo caso sea PPD.

**Comment by RigoFlores** [comment]
Entonces, ya está instalada en el servidor de Navision, la versión que si va a leer el rfc receptor a la tabla Factura-T?

**Comment by RigoFlores** [comment]
?

**Comment by RigoFlores** [comment]
Estoy en espera a validar...

**Comment by jccastillo0007** [comment]
no, no esta en el server, yo solo lo subi al dropbox
