### ISSUE TITLE
Optibelt CCE - no está calculando correctamente valorDolares dentro del CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1357]
No está considerando la cantidadAduana, para el cálculo de valorDolares dentro del CCE.
Ahora mismo aunque la cantidad sea mayor a 1, valorDolares lo está reportando igual a valorUnitarioDolares.

Recordar que a nivel nodo de mercancías:

valorDolares = cantidadAduana * valorUnitarioDolares.

y tampoco olvidar que totalUSD = sumatoria de valorDolares.

En pocas palabras, los cálculos son equivalentes al XML estándar pero expresando en USD

importe=cantidar x valor unitario
Subtotal = sumatoria de importes.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
sigue igual...

**Comment by jccastillo0007** [comment]
de hecho lo que estaba alrevés es que en valor dolares estaba reportando el valor valor unitario dolares y viceversa... eso si estaba mal, aunque no es lo que reportaste aqui...

**Comment by RigoFlores** [comment]
en los 2 datos estaba el mismo dato, aunque la cantidad era 3.
Te mandé el archivo con el que estoy probando.
Voy a cerrar este issue, pero ya abrí otro por el tema de decimales, sigue marcando error.
Ahora el sat está muy mamón con las sumas...
