### ISSUE TITLE
CCE conector estándar, y Optibelt - cuando el receptor sea distinto a XEXX...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1358]
Querría decir que el receptor es nacional... entonces cuando se incluya el CCE .... en el XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar XML estándar

nodo receptor, no incluir país de residencia, ni numidreg  

Es decir, estos 2 parámetros solo aplican para el receptor dentro del XML estándar siempre y cuando se cumplan 2 condiciones:
a) se requiere incluir el CCE
b) el receptor es nacional  (distinto a XEXX010101000)

**Comment by jccastillo0007** [comment]
haber checale...

**Comment by jccastillo0007** [comment]
para el conector estándar, nosotros reportamos lo que ello mandan en el txt, esta es una validación que deben contemplar al momento de crear el txt

**Comment by RigoFlores** [comment]
yo creo que todo eso si deberíamos nosotros resolverlo, pero a ver que sale. 
Yo estimo que se generarán muchas llamadas de soporte por este issue.

Solo eliminé el numregid y ya quedó

**Comment by RigoFlores** [comment]
En el txt, cuando el receptor es nacional, no hay manera de incluir el CCE, ya que el parámetro que indica que debe ir con CCE, es precisamente el numregid... y si lo incluyo, entonces marca error, porque se quiere incluir el pais de residencia y numregid para un receptor nacional.
Como no sabemos si se presentará el caso, lo podemos dejar ahora así, pero es probable que si tengamos que resolver este issue de alguna manera.
