### ISSUE TITLE
Optibelt CCE - ValorUnitarioAduana y ValorDolares con 2 decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1359]
Cuando el XML original está en pesos, tienes que hacer la conversión a USD, de acuerdo con el tipo de cambio.
Eso ya lo hace, pero ahora tiene este otro detalle.
A nivel nodo de mercancías dentro del CCE, valorUnitarioAduana y valorDolares, debe ir con 2 decimales.
Una vez que todos los productos de la factura, dentro del CCE, entonces se hace la sumatoria de valorDolares para reportar el TotalUSD (el que va en el header del CCE).

Marca error por que ahora mismo se están reportando 13 decimales... jajaja

Esto aplica igual para el CCE estándar.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
no tengo versión para validar ... no la has subido

**Comment by jccastillo0007** [comment]
como no... la subi el mismo dia que lo arregle

**Comment by jccastillo0007** [comment]
hoy subo un refresh
