### ISSUE TITLE
Ventas - Consultas - Las remisiones no las puedo 'convertir' a facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1360]
La momento de darle editar a una remisión, inmediatamente marca que no se puede timbrar.
Si aún con ello, intento timbrar, me marca XML mal formado.

Puedes chequear en pruebas con la remisión 15 del día de hoy.

**Comment by jccastillo0007** [comment]
Listo, en pru.

Si habia un problema porque no validaba que se capturre un uso de cfdi, y uno de los productos no tenia la clave del sat
