### ISSUE TITLE
Agregar un reporte a Optibelt

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1361]
Pudiera ser una variante del reporte de Cartera de Clientes - Pagadas
Lo que se ocupa es agregar una columna que indique el número de días transcurridos desde la emisión de la factura (esa fecha ya la tenemos), hasta que se liquida al 100% (es precisamente en el momento que se pone a status pagada).

Puede ser que agreguemos la opción de un check box, para incluir esa información en el reporte de Cartera de Cliente, solo para el caso que se elija el filtro de pagadas. Cómo la beisbol?

**Comment by jccastillo0007** [comment]
pues yo creo que será mejor agregar esa info siempre... y no solo para optibelt..
seria solo en excel o también en pantalla ?

**Comment by RigoFlores** [comment]
Pues yo creo en ambas.
OJO, solo aplica cuando el filtro de pagadas está seleccionado, ya que con las vencidas o vigentes, no se puede mostrar tal fecha....

**Comment by jccastillo0007** [comment]
listo..

Hay dos temas, vi en el reporte de optibelt, que en row de titulos, tenia dos referencias, una como referencia y otra como referencia de pago... pero no encontre donde se llema la referencia de pago, como quiera agregue al final lo de los dias de crédito

El otro tema es que cuando pasa menos de 24 hrs, no muestra nada

**Comment by RigoFlores** [comment]
Son dos conceptos distintos.
La referencia viene de origen cuando se timbra el CFDI. Es una referencia propia de la factura o nota de crédito.

La referencia de pago, se captura al momento de ingresar el cobro. 
Esto quiere decir, que la referencia solo aplica para facturas y notas de crédito, mientras que la referencia de pago solo aplica para los pagos. 
Ya ví el reporte y estás ocupando la misma columna. Voy a esperar los comentarios de optibelt, ya que según entiendo esto fue un cambio en el formato.

**Comment by jccastillo0007** [comment]
como que la misma columna? agregue una que dice dias de credito, no te aparece?

**Comment by RigoFlores** [comment]
Me refiero a que ocupas la misma columna para referencia, y ahí muestras los dos conceptos: referencia y referencia de pago. En la columna referencia de pago, no muestra nada; anteriormente si estaban separadas de acuerdo a la explicación de arriba.
En cuanto a la nueva columna, de días de crédito, si la vi y como comenté estoy esperando retro de optibelt.  Yo creo que el nombre no es correcto días de crédito, quizás días de pago, pero bueno ellos ya me dirán.

**Comment by jccastillo0007** [comment]
okas, ya me estaba asustando
