### ISSUE TITLE
Las remisiones se pueden Facturar n veces

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1363]
Anteriormente una vez que una remisión había sido facturada, ya no podía volverse a facturar.
Ahora mismo, la misma remisión la puedes facturar n veces.

Tanto desde Descarga-T, como desde Factura-T.
En descargat, una vez que la remisión era facturada, ya no aparecía si la consultabas nuevamente (creo que te indicaba que esa remisión ya había sido facturada).
Igual en facturat, cuando querías facturar una remisión facturada previamente.

**Comment by jccastillo0007** [comment]
okas... deja arreglo primero el 1305, seguro esto es porque ahora tenemos un estatus de CxC y no solo de facturas

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Al parecer quedó en descargat.
Pero desde facturat, generé todas las facturas que quise, con la misma remisión... jeje

**Comment by RigoFlores** [comment]
ahora solo generé una factura con una remisión que hice hoy (pruebas, REM1, cuenta TCM), peeero, después de generar la factura, a partir de la remisión, ésta última ya no aparece... jeje

**Comment by jccastillo0007** [comment]
es que ya esta utilizada o generada ... debo quitarle ese filtro en el query

**Comment by RigoFlores** [comment]
así es, la remisión solo quedará para el seguimiento, pero no debe desaparecer... no existe manera de identificar cuando una factura se emitió a partir de una remisión?

**Comment by jccastillo0007** [comment]
listo en pru
