### ISSUE TITLE
Dar opción de editar registros de condominos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1364]
Cuando una casa cambia de dueño, o se renta a otro inquilino o locatario, quizás sea necesario ajustar el RFC y número de cliente.
Entonces se debe dar la opción de editar ese registro.
Sería me parece el único dato a editar (RFC, que va de la mano con el número de cliente).

**Comment by jccastillo0007** [comment]
ya logre hacer que al darle click en el check box , cargue los datos del condominio, solo falta que cargue el rfc al cual esta asignado y hacer de solo lectura los campos
