### ISSUE TITLE
Catálogo de Clientes, validar que el número de cliente no se repita

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1365]
Al momento de capturar un nuevo cliente, ya sea rfc nuevo o nombre alterno, NO DEBE PERMITIR CAPTURAR UN NÚMERO DE CLIENTE que ya haya sido asignado anteriormente.

**Comment by jccastillo0007** [comment]
listo

se fue hasta pro con el release de hoy

**Comment by RigoFlores** [comment]
Si un mismo RFC, no permite repetir el número de cliente.
Pero si se trata de RFC's distintos, si permite repetir el número de cliente.

En pocas palabras, no debe permitir que se repita el número de cliente, independientemente de cuál RFC se trate.

**Comment by jccastillo0007** [comment]
listo... me suena a una validación que después vamos a quitar... ya que me parece que el número de cliente pudiera repetirse para diferentes RFC receptores.

**Comment by RigoFlores** [comment]
Recuerda que el número de cliente, es como el RFC, es decir debería ser único para cada emisor.
El ejemplo lo tenemos en optibelt, donde por supuesto que ningún cliente se debe repetir, ya que sus consultas las filtran por número de cliente.
En caso que quisieramos filtrar por todos los clientes asociados a un mismo RFC, entonces se aplica el filtro de RFC, y no de número de cliente.
