### ISSUE TITLE
Producción - Cuando reenvia facturas por correo lo hace chueco

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1366]
Lo detectó Optibelt, pero según yo aplica para todos

El número de cliente es 231504, RFC “DBS860101786”
Cuando se timbró, si llegó el correo a los destinatarios, de acuerdo a su configuración y de acuerdo a la bitácora de sendinblue.

Cuando le dan reenviar, se envió a otros correos. Según yo esto tiene que ver con que al reenviar, elige la lista de correos del rfc base, y no se va a buscar la configuración de los nombres alternos, que finalmente corresponden a los distintos números de cliente para un mismo RFC.

**Comment by jccastillo0007** [comment]
subi un posible fix a PRU, puedes tratar de reproducirlo y ver si jala

**Comment by RigoFlores** [comment]
Al parecer si jala... le dí reenviar, y si tomó el correo que le corresponde a cada número de cliente
(Si te das cuenta el número de cliente cada vez es mas relevante)
