### ISSUE TITLE
Cuando subes XML como proveedor, no se refleja en consultas del emisor.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1367]
Subí un XML ingresando con el usuario DIG971205KB1  (proveedor de la tia).

Si consulto accediendo a la plataforma con el usuario DIG971205KB1, muestra 2 XML.
Pero si accedo con la cuenta de la TIA, desde el menú de Compras-Consultas, solo muestra 1 XML.

De los 2 XML que realmente deberían mostrarse en ambos lados (tanto ingresando como proveedor o como receptor), uno lo subí con la cuenta de la tia, menú Compras-Registrar CFDi) y el otro que subí precisamente con la cuenta de DIG971205KB1  (es decir con perfil como proveedor), menú Proveedores-Registrar CFDi.

**Comment by jccastillo0007** [comment]
deja veo, yo hice la misma prueba

**Comment by jccastillo0007** [comment]
listo... ya revise tus dos facturas... tenían diferente createdBy puesto que las subiste de diferente lugar... como ese es un escenario válido, le quite la validación de quien creo o subió la factura
