### ISSUE TITLE
Corregir el reporte de Cartera Vencida - columna días de crédito

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1371]
mandé un correo con la explicación y ejemplo.
Los días de crédito no los está calculando bien, está mas alto.
Aparentemente a los días, le está sumando 1, por cada semana transcurrida.
Dicho de otra manera, como si las semanas fueran de 8 días.

**Comment by RigoFlores** [comment]
ya me están presionando...

**Comment by jccastillo0007** [comment]
fixed en PRO
