### ISSUE TITLE
Condominios - Configuracion capturar los siguientes parámetros

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1372]
1. Cuota de   mantenimiento
2. Período de pago de la cuota
3. Definir si una casa pagará de acuerdo el período o nó
4. Fecha límite de pago (día del mes, que es la fecha límite de pago). Esta opción, pudieran ser los días de crédito del catálogo de clientes.
5. Porcentaje de penalización  (por lo pronto solo se capturará, sin   usarlo en el proceso)

**Comment by jccastillo0007** [comment]
no manches... como que definir si va a pagar bien o no... chiaaaaa

explicame el caso de uso de ese campo, pl

**Comment by RigoFlores** [comment]
Cuando eliges que si pagará de acuerdo al período, entonces significa que pagará mes a mes.
También significa, que la SP se generará automáticamente para esta casa, todos los días 01 de cada mes.

Si no pagará de acuerdo al período, quizás haga pagos anuales o que se yo, pero no se generarán automáticamente las SP, sino a demanda.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Oye, el parámetro de si la casa paga o no, de acuerdo a la configuración, va en la pantalla de catálogos de casas, ya que ese ajuste es a nivel de casa.
El resto de parámetros, están bien a nivel configuración general...

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Negativo, creo que seguimos hablando de cosas distintas en el concepto de estructura del condominio.
El condominio tiene su domicilio fiscal.
La casa tiene su domicilio fiscal.  (en ambos casos, ya no se ocupan en el CFDI).

La estructura del condominio, tiene niveles. Esos niveles, pueden ser manzanas, edicficios, corredores, clusters, cottos, etc. Serán distintos en cada caso. Eso es lo que no estoy viendo.

El número exterior, número interior, id de casa, por supuesto no son parte de la estructura, ya que son datos propio de cada casa.
