### ISSUE TITLE
Condominios - Emitir solicitud de pago (SP) de forma automática

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1373]
Generar "Solicitud de Pago" (SP) de acuerdo al período configurado, para todos los clientes que aplica, por un monto de la cuota, y con fecha de vencimiento de acuerdo a lo configurado. (no aplica para pagos anuales). Utilizará la plantilla solicitudPago.jrxml (se le envían los mismos datos que una remisión).
El concepto debe ser "Cuota de Mantenimiento", ID: CUOT-MANNTO, clave SAT: 80131801, considerar los datos adicionales definidos en la pantalla de configuración.

**Comment by RigoFlores** [comment]
La solicitud se generará todos los días 01 de cada período definido.

**Comment by jccastillo0007** [comment]
no manches, de donde te fumaste un documento solicitud de pago SP ? jajajaja
ya lo vi en varios tickets... la duda que tengo es...
un SP nace aqui en este ticket? de forma automática, o hay algún lugar donde se da de alta

**Comment by RigoFlores** [comment]
aquí nace la SP.
Recuerda que hay condominios que no facturan, entonces para ello la solicitud de pago sería el equivalente a la factura.
Al momento de dar de alta una nueva casa, se definirá si se requiere generar automáticamente la SP (con un checkbox o similar)

**Comment by jccastillo0007** [comment]
si no eligen que pague de acuerdo al periodo definido... no se va a generar automáticamente una SP, pero entonces, cuando se hará? o se substituye con una factura tal cual cuando paguen

**Comment by RigoFlores** [comment]
se hace al momento que se requiera... recuerda algo, para que no te pierdas tanto... una solicitud de pago, sería el equivalente a una remisión... se puede emitir anytime...

**Comment by RigoFlores** [comment]
imagina la SP como una remisión.
La SP se puede emitir en forma periódica (como las facturas).
O también se puede emitir any moment.

Ambas, la automática o manual, implicarán una CxC.

**Comment by jccastillo0007** [comment]
en que pantalla se va a poder emitir un SP? en la de remisiones ?

**Comment by RigoFlores** [comment]
recuerda que la nomenclatura cambia.
No hay remisiones en condominio, y en su lugar habrá solicitudes de pago

**Comment by RigoFlores** [comment]
Cambia el nombre, pero la idea básica es la misma.
La solicitud de pago, es el documento que indicará que una casa debe la mensualidad.
El caso de una remisión, esta se entrega, cuando el material o servicio ha sido suministrado.

Ambos representan una deuda del cliente.

**Comment by jccastillo0007** [comment]
ya tienes la plantilla  solicitudPago.jrxml ?

**Comment by jccastillo0007** [comment]
de la pantalla de remision que ahora será solicitud de pago, hay varios datos que según yo no aplican, como dirección, nombre alterno, lugar de expedición, etc...

Puedes definir exactamente que debe llevar esa pantalla, para no estar adivinando evitar cambios cuando veas la pantalla

**Comment by RigoFlores** [comment]
OK, mas que en remisión que quedó obsoleta esa pantalla, sería en la de facturación, ya que eventualmente una SP se convertiría en una factura, es decir se debe poder pasar de SP a factura (así como se pasa de remisión a factura).

Los datos necesarios para una SP, serían: 
nombre
RFC
ID de casa
Forma de Pago (99 para las automáticas)
Método de Pago  (PPD para las automáticas)
Serie (podemos manejar SP)
Folio
Moneda

Luego la opción de elegir los productos, que en este caso serían servicios.
Quitar incluir leyendas fiscales, y también eso de incluir CCE.
Quitar lo de addendas.
Dejar lo de SP periódicas.

Creo que es todo.
En lo que te facilito una plantilla, podrías ocupar la de la factura. Ahí solo faltaría el número o identificador de casa, que puedes crear una variable, o mientras tanto ocupar datoextra1

**Comment by jccastillo0007** [comment]
ya esta la pantalla de solicitud de pago manual

Esta usando por el momento el mismo template de remisiones, pero con el nombre de cfdi_sp33.jrxml

**Comment by RigoFlores** [comment]
Ya emití una, faltaría probar que si el cliente tiene indicado que si se genere automaticamente la SP, entonces que la emita automáticamente.

**Comment by RigoFlores** [comment]
Esa SP, deberá emitirla automáticamente cada día 01 de mes o dependiendo del período de cobro de la cuota de mantenimiento.

**Comment by RigoFlores** [comment]
Vamos a priorizar los issues para condominios... con este se inicia... 
Dependiendo de la configuración:

- Cuota de mantenimiento
- Período de Pago
- Día de Pago

junto con este dato capturado en el catálogo de casas/locales (período de pago regular = SI). 

La SP debería generarse de manera automática con los siguientes datos:
Detalle:
ID concepto: CUOTAM  (junto con todo lo que incluya ese servicio en el catálogo de servicios)

Generales:
nombre (de la casa en cuestión)
RFC 
ID de casa
Forma de Pago (99 )
Método de Pago (PPD)
Serie (SP)
Folio
Moneda

**Comment by jccastillo0007** [comment]
este issue esta duplicado con el 1377 chiaaa

**Comment by RigoFlores** [comment]
Negativo, eso parece pero no.
Aquí se solicita que todos los días 01, se genere la SP de manera automática, si así está definido (SI) para cada casa, con el parámetro: Periodo de pago regular (esto es en el catálogo de casas). 
Eso significa que se generará el dia 01 la SP, con estado vigente, y diario se actualizará su edo. Pasará a vencida, cuando se rebase la fecha definida en Configuración - Dia de Pago.

Se debe generar el día 01 de cada mes, o bimestre o trimestre, o depende del parámetro configurado en administración - configuración: Periódo de Pago. 
El monto de dicha SP, será el definido en la misma pantalla de administración-configuración: cuota de mantenimiento.

El issue 1377, se refiere a emitir UNA FACTURA DE MANERA AUTOMÁTICA AL INGRESAR UN COBRO.

**Comment by jccastillo0007** [comment]
el primer paso para este requerimiento fue que agregue un campo de fecha de siguiente factura... esto lo tienen  que capturar al momento de dar de alta una casa, o si la dieron de alta sin fecha.. la pueden agregar después en el catálogo de casas

**Comment by RigoFlores** [comment]
pero si la fecha siempre sería el 01 de cada mes... o cada bimestre o el período definido.
Para que queremos otra fecha?

**Comment by jccastillo0007** [comment]
básicamente, la necesito la primera vez, para que en base a esa fecha, calcular las siguientes, pues una casa puede empeza a facturar cualquier día, y no siempre debo calcular el siguiente periodo, apartir de la fecha de la última factura... por ejemplo si un fraccionamiento va por bimestre, y un cliente empieza a habitar la casa o empieza a pagar el mtto en un mes que no toca pago... ese cliente podría tener que pagar a diferente frecuencia...

**Comment by RigoFlores** [comment]
Es que precisamente, la configuración te indica si el pago es mensual, bimestral, etc.
Si una casa está configurada para que emita de acuerdo a periodo de pago regular, entonces se deberá emitir automáticamente el día 01 de cada mes, o bimestre o que corresponda.

Vamos si una persona llega a ocupar el día 15 de octubre, y el pago es bimestral (enero, marzo, mayo, julio, septiembre, noviembre), entonces quizás tenga que pagar los últimos 15 días de octubre, pero lo que es un hecho es que el 01 de noviembre, se generará automáticamente su siguiente SP.

Creo que debemos platicarlo...

**Comment by jccastillo0007** [comment]
oye, y como voy a identificar el monto y el concepto a pagar en la solicitud de pago?

**Comment by RigoFlores** [comment]
El monto se captura en el menú Administración-Configuración; ahí se captura el monto 'estándar', 'regular' o por 'omisión'. Para eso es ese parámetro.
El concepto, es el de "CUOTA DE MANTENIMIENTO"...
La información complementaria, sería "CORRESPONDIENTE AL MES DE ...." (indicar el mes que corresponda, es decir, el mes actual).

Cuando una casa está configurada para emitir dentro del periódo regular... entonces se emite el dia 01 de cada mes (o el período que corresponda), por la cantidad configurada, y el concepto que se indica arriba.

**Comment by RigoFlores** [comment]
Esto es, para condominios o fraccionamientos, donde hay cientos de casas.
La otra opción, si es muy complicado esto, es poner la opción de emitir las SP de manera manual, un botón o algo. Solo que con esta opción, caemos en el riesgo, que lo puedan emitir mas de una vez por mes, lo cual sería un caos...

**Comment by jccastillo0007** [comment]
ok, se me esta complicando un poco...

el tema de concepto e información complementaria, esta bien dejarla tal cual... no será que diferentes fraccionamientos, quieran definir diferentes leyendas...

**Comment by RigoFlores** [comment]
pues si quieres ponemos un ID específico para ese producto de donde tomaremos la leyenda (CUOTA-MANNTO por ejemplo), y ya que le pongan la leyenda que quieran de su descripción.
Ahora el "correspondiente al mes tal"... pues no hay mas, al ser automática corresponderá al mes en curso, no hay opción.

Todo esto, hoy en día ya se hace con las facturas periódicas. Realmente no debería ser distinto.

**Comment by jccastillo0007** [comment]
ya esta generando SP de forma automática.. pero aún me faltan algunos ajustes... este fin ya queda listo

**Comment by jccastillo0007** [comment]
ya genera la SP automática, con los datos del producto de cada cliente... 
se debe tener un producto con id = CMM, y de ahi se tomarán todos los datos para generar la SP, se asume que el iva será del 16%

Ya solo me falta generarla de acuerdo a la frecuencia de cada condominio, por ahora esta diario, y he generado un buen... incluso cada minuto... por si ves muchas SP no te vayas a asustar

**Comment by RigoFlores** [comment]
No entendí eso de con los datos de producto de cada cliente. Dirás mas bien de cada emisor (condominio o fraccionamiento).

ID producto = CMM, ok, de acuerdo.
IVA del 16%, para condominios y fraccionamientos, en general no aplica, ya que son sociedades o asociaciones SIN FINES DE LUCRO, con lo cual el IVA es tasa exenta.
Ahora si esto lo consideramos para plazas comerciales, ahí seguramente que si aplicará el IVA. Entonces podemos arrancar con la tasa exenta por omisión, pero si debemos considerar el mecanismo para definir esa parte. Quizás en la pantalla de configuración, agregar ese parámetro.

En cuanto a la generación automática, veo que genera varias SP sin casa asociada. Esto es además de las casas que si están dadas de alta, aparecen unas SP fantasma. Esas evidentemente están incorrectas:

<img width="603" alt="SPfantasmas" src="https://user-images.githubusercontent.com/2912775/66939660-1fc6b980-f009-11e9-9476-1ae7553f4b77.PNG">

**Comment by jccastillo0007** [comment]
[10:59 PM, 10/17/2019] JC: ya vi que paso
[10:59 PM, 10/17/2019] JC: no eran huérfanas
[11:00 PM, 10/17/2019] JC: tu las dejaste huérfanas... porque al parecer en estos días borraste algunas casas
[11:00 PM, 10/17/2019] JC: al menos estas
[11:00 PM, 10/17/2019] JC: Residencial San Mateo-EDIFICIO 1-PISO 1
Residencial San Mateo-EDIFICIO 2-PISO 1
Residencial San Mateo-EDIFICIO 2-PISO 1
Residencial San Mateo-EDIFICIO 2-PISO 1
Residencial San Mateo-EDIFICIO 1-PISO 2
Residencial San Mateo-EDIFICIO 1-PISO 1
Residencial San Mateo-EDIFICIO 1-PISO 1
Residencial San Mateo-EDIFICIO 1-PISO 1

**Comment by RigoFlores** [comment]
esas tiene mucho tiempo que se borraron, pero además si te das cuenta, solo son dos casas, y lo estás contando n veces... yo creo que no se están borrando del todo, o no sé.
Hace muuucho tiempo que no toco las casas, al contrario, he visto que tu has agregado.

**Comment by jccastillo0007** [comment]
ya encontré el problema... esos condominios se borraron y en aquel entonces no borra los clientes de la tabla client... y por eso estaba generando esas facturas fantasmas

**Comment by jccastillo0007** [comment]
ya va a estar generando las SP de acuerdo al periodo configurado... me hacen falta un par de pruebas mas, y te lo paso a ti para que lo pruebes

**Comment by jccastillo0007** [comment]
Oye, en la pantalla de configuración tenemos capturado un monto de mantenimiento, pero ese dato se va a tomar del producto llamado Cuota de Mantenimiento... se me hace que lo podemos quitar

**Comment by jccastillo0007** [comment]
quedo configurado de forma bimestral, se que no se presta para pruebas, pero esta ligado a la pantalla de configuración

**Comment by RigoFlores** [comment]
necesito probar esto en pru, antes que inicie el siguiente mes...
ya que el tema del IVA no aplica
y va a generar un chingo de SP con iva

**Comment by RigoFlores** [comment]
en PRU ya quedó. 
SI genera las SP que corresponden automáticamente.
Falta probar que las genere el día 01 del período correspondiente, en este caso mensualmente.
Entonces porque no pones eso en pruebas, y si vemos que jala pues ya lo llevamos a producción.

OJO, faltaría incluir en el nombre del archivo el ID casa, y asimismo enviarlo al PDF de solicitud de pago.

**Comment by jccastillo0007** [comment]
ya le quite el tema de que se ejecute diario... ahora ya lo va hacer de acuerdo al periodo y dia configurado.

**Comment by RigoFlores** [comment]
Pero te comenté en la priorización de issues lo siguiente:
Es decir van los 3 issues resueltos juntos.

1649 .- enviar al PDF de SP, el id casa
1644 .- incluir en el nombre de la SP, el ID casa
1373.- generación de SP automática. Hay que ponerla en pru, ya con el período elegido, es decir, mensualmente para que lo genere el día 01. Va de la mano con el issue 1649 y 1644

**Comment by RigoFlores** [comment]
aquí falta corregir que el ID casa, tanto en el correo como en la SP, no se está enviando correctamente

**Comment by jccastillo0007** [comment]
fixed
