### ISSUE TITLE
Condominios - SP actualizar su status diariamente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1374]
La solicitud de pago, tendrá que actualizar su status diariamente.
Vigente cuando no se haya rebasado el número de días configurado.
Vencida, cuando se haya rebasado el número de días configurado.

Los días configurados, se tomarán como la fecha del mes en cuestión.
Por ejemplo, el día 01 de emite la SP de manera automática. Los días de pago son 10, entonces si no tiene status de pagada el día 11, tendrá que pasar de vigente a vencida.

**Comment by jccastillo0007** [comment]
no se solicitó la captura de cuando una SP se pasa a vencida, únicamente se solicitó la captura del día de pago.

**Comment by RigoFlores** [comment]
OK, este issue solicita lo que dices que no se solicitó, pero lo rechazaste... jeje.

Si bien se captura la fecha de pago. Entonces como podemos enterarnos que una SP cambia de status??
Pues ejecutando el cron diariamente, igual que en optibelt, para saber si ya pasó de vigente a vencida, que no?

**Comment by RigoFlores** [comment]
A ver, realmente NO SE TRATA DE UNA CAPTURA.
Se trata de un cron, que cuando se ejecuta ACTUALIZA EL STATUS de las SP.
Imagínate que el adminsitrador, quiere saber las casas que no han pagado  todavía pero que están dentro del plazo (vigentes), o quizás quiera conocer solo la cartera vencida (status vencida) o quizás quiera conocer ambas (vigentes + vencidas). Esta actualización del status es algo ELEMENTAL BÁSICO EN ESTE SISTEMA

**Comment by RigoFlores** [comment]
Las SP se emiten el día 01 de cada mes, o cada trimeste, o bimestre, o como se haya definido.
Las SP se emitirán automáticamente para la casa, siempre que así se haya definido en los datos de la casa.
La SP nace con estado de vigente, y cuando se paga, pasa a pagada.
La SP pasa de vigente a vencida, cuando se alcanza la fecha de pago que se configuró en Administración-Configuración del condominio.
