### ISSUE TITLE
Condominios - SP implementar cancelación de una SP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1375]
Si por cualquier razón se genera una SP de manera incorrecta, se tendrá que cancelar de la misma manera que hoy se cancela una factura.
La condición para cancelar una SP es que no tenga status de pagada o facturada.

**Comment by RigoFlores** [comment]
Generará un acuse de cancelación. Se guardará la fecha y hora de cancelación.

**Comment by RigoFlores** [comment]
En la priorización de issues dentro de condominios, este va al principio, ya que si generaron una SP por error, o deben corregir algún dato, se deberá cancelar la SP.

Cuando se cancele una SP, deberá enviarse un correo a la casa involucrada, indicando que ese documento de pago ha sido cancelado.

OJO, una SP de pago que tiene un documento de pago asociado, NO PODRÁ CANCELARSE.

**Comment by RigoFlores** [comment]
urge...

**Comment by jccastillo0007** [comment]
oye, esto  "OJO, una SP de pago que tiene un documento de pago asociado, NO PODRÁ CANCELARSE."  se refiere a que la SP ya fue pagada cierto? que fue lo que pusiste en el primer comentario

**Comment by jccastillo0007** [comment]
ya ando haciendo pruebas de esto ..

**Comment by RigoFlores** [comment]
Afirmativo, una SP que ya fue pagada, no podrá cancelarse.

En caso de querer cancelar una SP ya pagada, deberá eliminarse el pago, lo cual implicará cancelar el documento de pago asociado. Creo que esto ya lo hace, pero no lo pude verificar, ya que no está jalando.

**Comment by jccastillo0007** [comment]
ya esta cancelando, y validando que la SP no este ya pagada.
Me falta el acuse de cancelación y el email

**Comment by RigoFlores** [comment]
ok, el correo lo debe enviar al propietario, siempre y cuando tenga capturado el correo (obvio).
Ocupo esta corrección en producción ,ya que hay algunas SP que tengo que cancelar

**Comment by jccastillo0007** [comment]
ok, hoy lo subo

**Comment by RigoFlores** [comment]
ok, ya cancela.
Solo como dices, falta el acuse y el email.
