### ISSUE TITLE
Condominios - CxC capturar cobros asociados a una Solicitud de Pago (SP)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1376]
Se deberán ingresar cobros asociados a una SP con status de vigente o vencida. Esto es, adicional a las facturas vigentes o vencidas, ahora se mostrarán las SP con el mismo status.

La manera de trabajar será idéntica a lo que hoy se tiene para facturas, esto es:

a) Al pagarla totalmente, cambiar status a pagada o facturada, según sea el caso.
b) Manejar pagos parciales

**Comment by jccastillo0007** [comment]
oye, esta funcionalidad ya casi estaba lista... peeeero... si tenemos una SP que se va a utilizar como documento relacionado durante la generación de un Documento de Pago, pues no jala porque el SP no es un CFDI, tendriamos que generar primero el CFDI del SP y luego el DRP ... voy bien o me regreso

**Comment by RigoFlores** [comment]
Una SP NO SE PUEDE OCUPAR COMO DOCUMENTO RELACIONADO, ya que no es un CFDI.

Este issue, se refiere a que se pueda registrar un cobro de una SP, pero no está considerando que se emitirá un REP (recibo electrónico de pago, que es un CFDI).

En principio, si ocupan SP en teoría no están emitiendo facturas.
Ahora si un condómino, si ocupa factura, entonces se ejecuta el proceso de generar una factura (CFDI) a partir de una SP. En ese momento, la SP cambia de status y ya no aparecería como 'cobrable'. En su lugar aparecería la factura, y si fuera necesario, entonces si se generaría un documento de pago.

La verdad no creo que el documento de pago lo ocupen en condominio, pero en una plaza quizás si.

Si respondí tu pregunta???

**Comment by jccastillo0007** [comment]
a cabron ahora se llama REP

respecto a la pregunta, pues mas o menos...  entonces al generar un pago , pueden elegir una SP, pero no se va a generar un CFDi de pago... entonces... simplemente que no elijan el checkbox de generar cfdi de pago...  y la SP se debe marcar como pagada, cierto ?

**Comment by jccastillo0007** [comment]
listo... se pueden agregar pagos a sp, sin cfdi y las sp pagadas en su totalidad se marcan como pagadas

**Comment by RigoFlores** [comment]
Capturé una SP, que le correspondió la SP8, y luego ingresé su cobro.
Cuando consulto el cobro con referencia SP8, si lo muestra como pagado. Con el RFC receptor FOPR, emisor ACO.
En cartera de cliente, la SP8, aparece como vigente.

Es decir en un lado aparece como pagada y en otro aparece como vigente. Yo hice el registro de pa

**Comment by jccastillo0007** [comment]
fixed.

Si puedes, prueba todos los escenarios posibles, no te detengas en uno solo, si no, nunca acabaremos

**Comment by RigoFlores** [comment]
Validé que:
a) Una SP puede ser cobrable.
b) Una SP puede ser cobrable en parcialidades
c) Se puede borrar su cobro, y la SP vuelve a su estado de Vigente
d) En cartera por cliente, muestra bien su estado, dependiendo si está pagada totalmente o parcialmente 
e) En Ingresos-Consultas, no aparece como pagada, pero por lo pronto no lo vamos a solicitar. En el reporte de excel (al darle exportar) si aparece como pagada.

Seguiré validando conforme vaya pudiendo
