### ISSUE TITLE
Condominios CxC - Ingresar Cobro de una SP, generar factura automática

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1377]
Cuando se va a ingresar un cobro de una SP, con status de vigente o vencida, se deberá indicar si se requiere generar el CFDI de manera automática.
Esto es para que al momento de capturar el cobro (que es lo mismo que ahora todo administrador realiza en sus 'exceles'), se realicen varias operaciones simultáneas:

a) Registrar el cobro
b) Cambiar de status la SP a facturada
c) Emitir el CFDI correspondiente al pago, agregando como datos extra la fecha de pago, y la SP asociada.
d) El CFDI recién emitido, será de tipo ingreso y nacerá con status de pagada.

**Comment by jccastillo0007** [comment]
despues de emitir una SP manual, se puede consultar y apartir de ahi generar una factura,, esto ya funciona.

Ahora me falta ejecutarlo desde CxC

**Comment by jccastillo0007** [comment]
no has capturado la estructura de condominios para poder probar la generación automática.... podría hacerlo yo, pero la idea es que lo hicieras tú para que veas como funicona

**Comment by RigoFlores** [comment]
ya capturé para el rfc FOPR y para XAXX

**Comment by RigoFlores** [comment]
La idea es adicional a lo que comentas, es que cuando voy a registrar un pago de una SP, tengan un checkbox, para indicar si quieren factura. Si la quieren, que se genere de manera automática, sin necesidad de capturar nada adicional.

**Comment by jccastillo0007** [comment]
Hay algunos datos predefinidos para un cfdi de pago, como la serie = PAGO y la moneda = XXX, para el nuevo CFDI de la SP que nacerá con estatus de Pagada,  se están definiendo estos datos :

Serie = ""
Moneda = "MXN"
Solo va a aplicar si realizan un pago a una solicitud de pago... pero no si eligen varias solicitudes de pago

**Comment by RigoFlores** [comment]
la serie puede ser C (de condominios) o CO, para las facturas emitidas desde condominio.. así ya no le andamos buscando... que sea alguna serie (C o CO), es tan igual como definir que no habrá serie.

**Comment by RigoFlores** [comment]
Este issue, solicita que cuando se capture un cobro de una casa, opcionalmente (checkbox), se genere la factura automáticamente (la factura de dicho pago), tomando en cuenta los datos del la SP.
En caso de elegir que si se ocupa factura, entonces la SP pasa a estado 'Facturada', y la factura nace ya con el estado de 'Pagada'.
Una SP con status de 'Facturada', ya no entra en ningún cálculo de ingresos, ya que su lugar lo tomará la factura emitida.
