### ISSUE TITLE
CON EL SESSION LAST, ALGUNAS OCASIONES NO LEVANTA EL ESTÁN ALON

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#138]
ALGUNAS OCASIONES, NO SIEMPRE BORRA EL SESSION LAST CUANDO SE CIERRA LA APLICACIÓN CORRECTAMENTE
ALGUNAS OCASIONES, CUANDO EXISTE EL SESSION LAST, LA APLICACIÓN SE QUEDA EN LA PRIMERA PANTALLA (TENEMOS QUE MATAR EL PROCESO Y ELIMINAR EL SESSION.LAST, PARA QUE LEVANTE)

**Comment by jccastillo0007** [comment]
Les encargo que me manden el log cuando una situacion asi suceda.... estuve revisando el codigo y no encontre algo fuera de lo normal.

**Comment by RigoFlores** [comment]
EL TEMA ES CUANDO EL SESSION LAST ESTÁ VACÍO. ESO YA LO VALIDÉ.

**Comment by jccastillo0007** [comment]
Esto supongo que ya no sucede, o tienes identificado el escenario?

**Comment by RigoFlores** [comment]
Si sucede, pero tanto esperamos a la resoluciónm que ahora simplemente se corrige en la máquina del cliente. 
No está plenamente identificado el escenario, pero si se presenta 2-3 veces a la semana
