### ISSUE TITLE
Condominios CxP - Ingresar pago (ajustes requeridos)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1380]
En la pantalla de ingresar pago, se deben considerar los CFDI's donde nuestro cliente (que generalmente es emisor), ahora aparecerá como receptor. Estos CFDIs, deben tener status de vigente o vencida. 

De la pantalla actual, hay que modificar:
a) En lugar de tipo Pago, colocar forma de pago y listar las opciones del catálogo del SAT
b) Eliminar la etiqueta "Folio (solo para NC)", así como su caja de texto.
c) Al consultar el listado de documentos por pagar, se mostrarán en la misma pantalla, el mísmo número de renglones como en CxC, que me parece son 200 o 300. Actualmente solo muestra 10 documentos por pantalla.

**Comment by jccastillo0007** [comment]
done en pru

**Comment by RigoFlores** [comment]
Accedí a PRU con la cuenta de la tía, CxP- ingresar Pago... si no le pongo ningún filtro y hago la consulta, muestra remisiones, pedido y documentos de pago...
Aquí solo de deben mostrar ingresos y si acaso egresos (notas de crédito), que además NO TENGAN EL status de pagada.

**Comment by RigoFlores** [comment]
Hoy emití una factura... que se te vas a Compras consultas, ahí aparece como vigente. Es el folio F1.
Pero si te vas a CxP-Ingresar pago, entonces ahí no aparece.

**Comment by jccastillo0007** [comment]
chiaaaa, creo que habia otro ticket que pedia mostrar todo... bueno creo que era para el descargat...

**Comment by jccastillo0007** [comment]
listo, lo voy a subir a PRO

**Comment by RigoFlores** [comment]
quizás sea inconsistencia de data, pero si no le pongo filtros, en producción, con la cuenta de la tia, me muestra 3 facturas pagadas:

![pagadas](https://user-images.githubusercontent.com/2912775/53050151-49b9e300-345e-11e9-8044-675ceeb5ebd6.JPG)

**Comment by jccastillo0007** [comment]
habia dos cosas raras... analicé la primer factura con serie FE y folio 1.

1. el estatus que ahi aparece es el de CXC y efectivamente esta pagada, sin embargo, el estatus que debia aparecer era el de CXP

2. Este probablemente no es problema sino duda... esa factura la tia es receptora y el emisor es 
+--------------+---------------------------------------------+
| sourceRFC    | sourceName                                  |
+--------------+---------------------------------------------+
| DAI031009S58 | DISEÑOS Y ACCESORIOS INDUSTRIALES SA DE CV  |
+--------------+---------------------------------------------+

pero el estatus de CxC es Pagada y el CxP es Registrada, ese escenario es como coincidencia ?

**Comment by RigoFlores** [comment]
Si accedes con la cuenta de la tía a la plataforma.
En CxP, la tía es receptor
En CxC, la tia es emisor

Todos los reportes y pantallas de CxP, la tía es receptor, y se debe considerar el status de CxP.

Todos los reportes y pantallas de CxC, la tía es emisor, y se debe considerar el status de CxC.

**Comment by jccastillo0007** [comment]
ya esta en PRO
