### ISSUE TITLE
Condominios - CxP Compras ajustes 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1381]
Cuando se registra un CFDI en el menú de "Compras-Registrar CFDI", ya sea con la cuenta del proveedor, o con la cuenta del condominio, este subirá con status de vigente (siempre que supera la validación del SAT). Esto ya lo hace ahora mismo, según yo.

En el menú de Compras-Consultas, se podrá editar un CFDI, solo para cambiar la fecha de pago. El status no se deberá cambiar desde ahí. Solo la fecha de pago.

Diariamente se tendrán que actualizar los status de los CFDI's de proveedores. Cambiará de vigente a vencida, si la fecha de pago ha sido superada, y el status del CFDI era vigente.

Mientras no se defina una fecha de pago, el status será vigente.

**Comment by jccastillo0007** [comment]
listo... solo me falta el cron para actualizar las facturas a vencidas
que estatus es el que se debe actualizar, el de CxC o CxP o los dos ?

**Comment by RigoFlores** [comment]
aquí hablamos de CxP....
El de CxC ya lo hace, que no??? (jjejeje... chiaaaaa)

**Comment by RigoFlores** [comment]
1) No está validando en el SAT. Generé una factura, la intenté subir de inmediato y la aceptó. Si me voy al SAT a consultarla, aún no está registrada. Entonces no está funcionando la validación de que la factura del proveedor está registrada en el SAT.

![noregistradosat](https://user-images.githubusercontent.com/2912775/52873826-8d86b280-3115-11e9-840d-86902895e9ac.JPG)

**Comment by RigoFlores** [comment]
Cuando editas la fecha de pago:
1) Si la fecha es anterior a la fecha actual, el status lo debe poner a vencido.
2) Si la fecha es igual o posterior a la actual, el status debe ser vigente.

Tampoco lo está haciendo

**Comment by jccastillo0007** [comment]
Respecto a la validación con el SAT, es correcto, no se esta realizando.
El servicio del SAT no esta funcionando para cfdi 3.3... habrá que ver si ya lo arreglaron.

**Comment by jccastillo0007** [comment]
Respecto al estatus CxP, a vencida o vigente según sea el caso, ya esta listo en PRO

**Comment by RigoFlores** [comment]
Pero tenemos el servicio del facturehoy para conocer el status, que no???
La validación ante el SAT, es una de las pocas CARTAS FUERTES QUE TIENE ESTE MÓDULO, es decir, es muuuuuy importante que se ejecute.

**Comment by RigoFlores** [comment]
Ya está jalando el cron en producción?

**Comment by jccastillo0007** [comment]
si, el cron ya esta en PRO

cual servicio de facture hoy ? no recuerdo eso

**Comment by RigoFlores** [comment]
no serviría el de consultar si hay cfdi's por aceptar cancelación (buzonT)?.... supongo una posible respuesta, es que no existe en el SAT.

O cualquiera de los de cancelación, independientemente de quién timbró el XML, no serviría???

**Comment by jccastillo0007** [comment]
negativo... los APIs del buzòn no regresa nada si no hay facturas por timbrar... no se consulta por factura, se consulta de forma general, y te regresa una lista de facturas por cancelar

los de cancelaciòn, puede ser, pero la va a cancelar jajajaaj

igual y preguntamos, o deja veo si el web service del sat esta disponible, no recuerdo porque dejo de funcionar

**Comment by RigoFlores** [comment]
Si, hay que ver de que manera se valida.
Según yo cuando importas CFDI Externos, ahí también se debería validar, pero pues ya no sé.

Insisto, de lo poco que tenemos para darle un valor agregado, es asegurar que las facturas recibidas están registradas en el SAT

**Comment by RigoFlores** [comment]
Este issue se cerrará cuando se corrija el mensaje en la pantalla, referente a que la factura está cancelada o no está publicada en el SAT.
Aquí se refiere al menú de compras-Subir CFDI, o el menú de Proveedores-Subir CFDI

**Comment by RigoFlores** [comment]
Intenté subir a pruebas, con la cuenta de la tia, una factura buena (publicada en el sat y vigente), y la rechazó, enviando el mensaje aquel grosero.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Ahora, en pruebas, cuenta de la tia, intenté subir una factura buena, y el mensaje es que no existe en el SAT.

Esto desde facturat, ya que condominios me marca que no está disponible.

**Comment by jccastillo0007** [comment]
Esto ya esta jalando cierto? solo falta validar el tema de validar la factura cuando es ingresar pago... pero eso esta en otro ticket

**Comment by RigoFlores** [comment]
ya me confundí... porque este ticket es de condominios, y todo se está corrigiendo en la plataforma de FT. Se reflejará en automático a condominios???

**Comment by jccastillo0007** [comment]
noup, ya estemos ok con CxC y CxP voy a replicarlo a condominios..

pero si ya esta jalando en efacturat... pues ya estará en condominios, pero no podemos dejarlo abierto, si no siento que no avanzo
