### ISSUE TITLE
Condominios CxP - Proceso de Registrar Pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1382]
El proceso de registrar pagos, es similar al de registrar cobros, pero si tiene sus variantes. Recordar que aquí se listarán las facturas que son de proveedores, es decir donde nuestro cliente es el receptor.

a) Una factura pagada, pasará a status de pagada (que raro, no?)
b) El monto de una factura debe aparecer en abonos.
c) Los pagos realizados, deberán aparecen en cargos.
d) Se podrán pagar facturas con distinto RFC emisor, ya que por ejemplo con un cheque se puede cubrir el pago de varios proveedores. Con ello, la condición de elegir RFC de proveedor, es solo opcional.

**Comment by jccastillo0007** [comment]
oye, tanto en CxC como CxP , hay opción de ingresar pago... es normal que se llame igual la pantalla?

en CxC es ingresar cobro, pero la pantalla de captura dice PAGO
en CxC es ingresar pago, y la pantalla de captura dice PAGO

como ahi que?

**Comment by jccastillo0007** [comment]
Dudas

a) Una factura pagada, pasará a status de pagada (que raro, no?)###  JC. Listo
b) El monto de una factura debe aparecer en abonos. ### JC. no me queda claro este punto, tal vez estoy confundido
c) Los pagos realizados, deberán aparecen en cargos. ### JC. no me queda claro este punto, tal vez estoy confundido
d) Se podrán pagar facturas con distinto RFC emisor, ya que por ejemplo con un cheque se puede cubrir el pago de varios proveedores. Con ello, la condición de elegir RFC de proveedor, es solo opcional. ### JC. Esto ya funciona asi

**Comment by RigoFlores** [comment]
Estrictamente hablando, ambos caen en la categoría de cobros y también pagos, dependiendo la perspectiva, es decir cliente o proveedor, emisor o receptor de las facturas.

Si nos apegamos al estándar administrativo de CxC, pues lo que ingresamos sería un cobro  (sin embargo el SAT le llamó documento de Cobro, por ello cambiamos el título de la pantalla). En la pantalla lo podemos dejar como "Cobros"

Si nos apegamos al estándar administrativo de CxP, pues lo que ingresamos sería un pago, entonces así lo podemos dejar en pantalla.

**Comment by RigoFlores** [comment]
El tema de cargo abono, tiene que ver con conceptos de contabilidad.
Activos - cuando te pagan, se registra como lo hacemos en CxC
Pasivos - deudas, cuanto tu pagas, se cambia la fórmula.
El monto de la factura del proveedor debe aparecer en Abono.
El monto de lo que pagamos a un proveedor, se debe registrar en Cargo.
Hoy eso está al revés. Una solución bastante simple, pero piñata, es simplemente cambiar la etiqueta de las columnas. Pero en los reportes, también deberían cambiar las etiquetas de dichas columnas.

![cargo-abono](https://user-images.githubusercontent.com/2912775/53106827-7111be00-34f9-11e9-9f2e-be9b2c540424.JPG)

**Comment by RigoFlores** [comment]
Aquí el mas sintetizado resumen de como aplican las reglas para activos (CxC) y pasivos (CxP).

![cargos y abonos](https://user-images.githubusercontent.com/2912775/53112646-55acb000-3505-11e9-877b-46335439fda0.jpeg)

**Comment by RigoFlores** [comment]
Interpretación para las pantallas y reportes que se generen en excel:

Activos (CxC): Saldo = Cargo - Abono

Pasivos (CxP): Saldo = Abono - Cargo

**Comment by RigoFlores** [comment]
hoy intenté registrar un pago, y en lugar de quedar el saldo en 0, quedó en negativo. jejeje
Cuenta de la tía, proveedor AAZR7411149T2  ( es la única factura que subí de ese proveedor).

**Comment by jccastillo0007** [comment]
hay que verificar otra vez este reporte

**Comment by RigoFlores** [comment]
Sigue igual, lo hice ayer.

**Comment by jccastillo0007** [comment]
checale

**Comment by RigoFlores** [comment]
pues ya no queda en negativo, pero las columnas están chuecas, eso será un problema contable.
Nuevamente, esto solo aplica para CxP:    (no tocar nada de CxC)

- EL MONTO DE LA FACTURA DE UN PROVEEDOR VA EN LA COLUMNA DE ABONO.
- LOS PAGOS DE NUESTRO CLIENTE, TOTALES O PARCIALES, VAN EN LA COLUMNA DE CARGO
- EL SALDO DE UNA FACTURA DE PROVEEDOR = ABONO - CARGO

**Comment by jccastillo0007** [comment]
esto ya esta en pru

**Comment by RigoFlores** [comment]
En la pantalla ya se arregló, lo de abonos (factura del proveedor) y cargos (pagos de nuestro cliente)
Detalles pendientes:
a)  que pide forzosamente seleccionar un proveedor. Recuerda que aquí lo que se trata es de revisar los egresos en un rango de fecha, sin importar a cuál proveedor se pagó. Con ello se deriva el punto (b).
b) cuando elijas los rangos de fecha, no deben ser de la fecha de emisión de la factura del proveedor(es), sino de la fecha en que se realizaron los pagos.

**Comment by jccastillo0007** [comment]
hablas de la pantalla de registrar pagos o de reporte de pagos?

Para consultar pagos sin proveedor, se usa la de reporte general ... que no?

**Comment by RigoFlores** [comment]
Pantalla de Reporte de Pagos.
Ya comentamos que se ocupa conocer todos los egresos en un período de tiempo, no se necesita filtrar por proveedor. Aún mas, las fechas capturadas corresponden a las fechas de pagos, no a las fechas de emisión de las facturas del proveedor.
En los condominios y en cualquier contabilidad básica, se ocupa conocer los egresos en un período de tiempo, y eso no lo tenemos ahora mismo.

Por otro lado, el reporte general, te dirá el histórico por proveedor. Esto es, cuánto le has pagado desde que inició como proveedor.

**Comment by jccastillo0007** [comment]
El reporte general no sirve para lo que dices... agregandole las opciones de rango de fechas, y filtrando las fechas por fecha de pago ?

**Comment by RigoFlores** [comment]
podría servir, pero hasta donde recuerdo, el reporte general solo arroja un registro, y el reporte de pagos vienen desglosados todos lo pagos realizados.
Por ejemplo, en el condominio se le paga quincenalmente la vigilancia, entonces aparecerían 2 pagos al mismo proveedor.
Total que son cosas distintas, el reporte general es toooodo lo que se le ha pagado a cada uno de los proveedores, lo podemos dejar, aunque no sé si tenga mucho caso.

**Comment by jccastillo0007** [comment]
me parece que este esta duplicado con el 1546 ?

**Comment by RigoFlores** [comment]
Este es mas general, pero lo cerraré y cualquier cosa que haga falta, se trabaja en otro issue específico.
