### ISSUE TITLE
Condominios CxP - registrar pagos parciales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1383]
Se podrán realizar pagos parciales a facturas de proveedores.
Por ejemplo, anticipos de un trabajo.

No creo que sea tan común, este issue lo podemos dejar con prioridad de 2 rayitas abajo, pero no lo quiero pasar por alto.

**Comment by jccastillo0007** [comment]
esto ya esta soportado no? 
se puede agregar pagos parciales, y la factura del proveedor va mostrando el saldo deudor
