### ISSUE TITLE
Condominios - CxP permitir registrar un pago a distintas facturas de proveedores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1384]
Es probable que cuando tu emites un cheque como condominio, lo hagas para cubrir varias facturas.
Entonces un pago, podría estar asociado a facturas de distintos RFC's emisores (de proveedores).

Con ello la condición de elegir el RFC para poder registrar pago, debe ser opcional.
Se puede consultar las facturas por rango de folios o por fecha. Realmente creo que el rango de folios, saldría sobrando, pero bueno, por lo pronto lo mantendremos.

Entonces en los reportes de pagos a proveedores, un mismo pago podría aparecer con proveedores distintos, pero eso lo levantaré en otro issue.

**Comment by jccastillo0007** [comment]
done..

en el filtro el rfc es opcional

Crees que sea buena idea agregar el rfc a la tabla de resultados de la búsqueda

**Comment by RigoFlores** [comment]
si, considerando que el rfc será opcional, si sería buena idea agregarlo en la tabla de resultados de la búsqueda.

**Comment by RigoFlores** [comment]
no maaaa... creo que lo hiciste para CxC, y no para CxP... estoy en lo cierto????

**Comment by jccastillo0007** [comment]
noup...

**Comment by jccastillo0007** [comment]
ya vi que CxP tiene un problema y no carga en PRU... deja veo que petch

**Comment by RigoFlores** [comment]
El primero pedo que veo, es que si consulto, me aparecen pinche mil facturas, casi estoy seguro que son las emitidas y no las recibidas.
Aquí tiene que consultar solo las facturas que se hayan subido por parte del proveedor, o através del menú Egresos-Registrar CFDI.

**Comment by jccastillo0007** [comment]
yo solo veo 2..
![image](https://user-images.githubusercontent.com/2245679/45333422-be960200-b53b-11e8-9913-7bf01cafff52.png)

**Comment by RigoFlores** [comment]
y yo muchas...
<img width="807" alt="muchasfacturascxp" src="https://user-images.githubusercontent.com/2912775/45372967-dad58580-b5b3-11e8-8dbd-0219194d28e0.PNG">

**Comment by RigoFlores** [comment]
No sé de donde toma esas facturas, bueno hasta remisiones... jeje... por ello digo que está chueco algo.
Esas series son las que ocupamos nosotros. Los proveedores, seguramente ocupan cualquier otra serie distinta.

**Comment by jccastillo0007** [comment]
en que ambiente, y con que usuario?

**Comment by RigoFlores** [comment]
OK, YA VÍ QUE PERMITE PAGAR FACTURAS DE DISTINTOS PROVEEDORES.
CÓMO LO REGISTRE O QUE HAGA CON ESE PAGO, ESO ES OOOTRA HISTORIA.
YA QUE NECESITAMOS HOMOLOGAR LA FORMA EN QUE SE REGISTRAN DICHOS PAGOS.
