### ISSUE TITLE
Condominios Catálogo de Proveedores - no permitir que se repita el número de proveedor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1385]
Al igual que número de cliente, el número de proveedore es irrepetible.

**Comment by jccastillo0007** [comment]
En donde se encuentra el catálogo de proveedores ?

**Comment by RigoFlores** [comment]
cómo donde, en el menú de catálogos...

**Comment by jccastillo0007** [comment]
pues no esta en tu documento donde definiste los menus... chiaaaa

**Comment by jccastillo0007** [comment]
fixed
