### ISSUE TITLE
CxC - Cartera de Cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1389]
Cuando el reporte no filtre por RFC y/o número de cliente, incluir en el excel una columna con el RFC, el nombre y el número de cliente.

Hoy en día para revisar ese reporte, tengo que estar buscando factura por factura, para ver de qué cliente se trata.

**Comment by jccastillo0007** [comment]
lo mas adecuado es siempre agregar esas columnas... si no se ocupan es mas fácil y práctico eliminarlas en excel

**Comment by RigoFlores** [comment]
Generé un reporte de cartera vencida, sin el filtro del rfc, y no aparece la nueva columna con el rfc en el excel... que es precisamente el motivo de este issue, pero no.
o que fue lo que si se hizo para que aparezca como resuelto?

**Comment by jccastillo0007** [comment]
jajaja apenas lo estoy subiendo
chiaaaa

**Comment by RigoFlores** [comment]
cuando el nombre del cliente, tiene comas, recorre todo...
Entonces pls, eliminar las comas del nombre para que no recorra...

**Comment by jccastillo0007** [comment]
chaaaa

**Comment by jccastillo0007** [comment]
ya esta listo... se me paso avisarte ayer
