### ISSUE TITLE
NO GENERA FACTURA DESDE EL AMBIENTE DE PRUEBAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#139]
NO SE QUE LE SUCEDE AL DEMO, PERO NO JALA.
ES IMPORTANTE TENERLO ARRIBA PARA MOSTRARLO A LOS CLIENTES...

**Comment by jccastillo0007** [comment]
Te refieres al stand alone ? o web ?

Saludos.
JC.
