### ISSUE TITLE
Condominios Catálogos - Casas/Locales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1390]
La pantalla es muy parecida a lo que tenemos hoy, solo se eliminan algunas etiquetas y cambian otras.
De hecho esta pantalla, si le cambias número de cliente, por número de proveedor, tendrás también la pantalla de proveedores.

Se ocupa que en las etiquetas del campo teléfono se despliegue: movil, casa, trabajo, whatsApp

<img width="410" alt="pantallacasas" src="https://user-images.githubusercontent.com/2912775/43171429-b12452d0-8f6f-11e8-9b89-f57eefdd7753.PNG">

**Comment by jccastillo0007** [comment]
falta acomodar las cosas y el checkbox de la dirección fiscal... pero ya tiene casi todo

**Comment by RigoFlores** [comment]
marca internal error, simplemente por acceder

**Comment by jccastillo0007** [comment]
fixed... chiaaa

tiene detalles al momento de actualizar los registros... pero puedes probar dar de alta

**Comment by RigoFlores** [comment]
Necesitamos volver a capturar uno juntos.
La neta no le agarro a esa pantalla.

**Comment by jccastillo0007** [comment]
chiaaaa pues asi como vamos avanzar

haber si ma;ana podemos hablar y lo hacemos... voy a borrar todo
