### ISSUE TITLE
Condominios Catálogos - Servicios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1391]
Esa pantalla será idéntica a lo que tenemos hoy, pero se elimina el tema de cuenta predial, y de número de pedimento.

En lugar de decir producto / servicio, cambia a Servicio (o producto).

Otra cosa, es bajar la captura de ClaveProductoSAT al tercer renglón, para que finalmente desaparezca un renglón y se vea mas limpia la pantalla.

**Comment by jccastillo0007** [comment]
solo me falta acomodar lo de productoSAT... lo subo la sig vez que suba cambios
