### ISSUE TITLE
Al momento de timbrar retenciones marca un error...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1392]
Cuanto intentas timbrar una retención marca error en la fecha del documento.
No se de donde aparece en el log, una fecha de issue, de diciembre 2018.
Lo traté de reproducir en pruebas, y marca error al timbrar...

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<retenciones:Retenciones xmlns:retenciones="http://www.sat.gob.mx/esquemas/retencionpago/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="1.0" FolioInt="RET3" Sello="eBZc/nqeFQryshKFUTiD59laRvEqNZliagEczzz/sgZjoh5LU/OlEDL0ZFiLyhLWIa+oUvuCsZ9hryqtkuq+OjdZXdHn2lAd3tQ42i21xfjwSG9XyQJGNKzmh+OATVNBwxbQnk3OlPiI1iQAsn/XMb9hbmsO6552jIYy78H4jb+ZVBMc8nIuSyFps3aLMuYUYR1nGqFUqlfEhFWnCJVqS98kKS8cyKN/ydOEWukFn3fheXHW7w0/+Ny726SEEfdqsO4smG3xD+6oNFZMGx10EE2gMM/S6pfT7Dfzw7e3ZXhS91S6UJQvtChvIvsP5tVmRSrupuORuTPtgw1HvAm2+Q==" NumCert="00001000000407276285" Cert="MIIGZjCCBE6gAwIBAgIUMDAwMDEwMDAwMDA0MDcyNzYyODUwDQYJKoZIhvcNAQELBQAwggGyMTgwNgYDVQQDDC9BLkMuIGRlbCBTZXJ2aWNpbyBkZSBBZG1pbmlzdHJhY2nDs24gVHJpYnV0YXJpYTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMR8wHQYJKoZIhvcNAQkBFhBhY29kc0BzYXQuZ29iLm14MSYwJAYDVQQJDB1Bdi4gSGlkYWxnbyA3NywgQ29sLiBHdWVycmVybzEOMAwGA1UEEQwFMDYzMDAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBEaXN0cml0byBGZWRlcmFsMRQwEgYDVQQHDAtDdWF1aHTDqW1vYzEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMV0wWwYJKoZIhvcNAQkCDE5SZXNwb25zYWJsZTogQWRtaW5pc3RyYWNpw7NuIENlbnRyYWwgZGUgU2VydmljaW9zIFRyaWJ1dGFyaW9zIGFsIENvbnRyaWJ1eWVudGUwHhcNMTcwODE4MTYwNjE5WhcNMjEwODE4MTYwNjE5WjCCAQUxMTAvBgNVBAMTKEdMT0JPV09STEQgTEFOR1VBR0UgU0NIT09MIFMgREUgUkwgREUgQ1YxMTAvBgNVBCkTKEdMT0JPV09STEQgTEFOR1VBR0UgU0NIT09MIFMgREUgUkwgREUgQ1YxMTAvBgNVBAoTKEdMT0JPV09STEQgTEFOR1VBR0UgU0NIT09MIFMgREUgUkwgREUgQ1YxJTAjBgNVBC0THEdMUzEzMTEwNkVRNCAvIFdBQU44NTAyMjMxTDkxHjAcBgNVBAUTFSAvIFdBWEE4NTAyMjNNTkVMWE4wNTEjMCEGA1UECxMaR0xPQk9XT1JMRCBMQU5HVUFHRSBTQ0hPT0wwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCprkkclewiCWF8sfB64R8XjNBfv1cJIaTCLkBmK9futVVA7iHH44RUAXGr9TyimFqQz7IoRZ/PHk9gWU50kzN5DKSc/5HEpZl0Ueiqii90Z17emjFJIBMOkc1qwmxNy2EfMdIWbbYc8+8U0VhVYqhZ/wUtYvfrcV1WRy9XfStfcmxPGurh3q6kEMDqSKT37C0z3JvAjtHz6JmgYifgNvUiBI/XiyGemS7LYTilppU5HbxcWbhwFdZzduovWDkpkTQU1mI4iRxGj5AYTEOp2uATSAxkqVLz54ejZBaPp/FJO2BrLLEB4E0YPvy8W6mODxnfBj4p00liMDoI66Uw9RPnAgMBAAGjHTAbMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgbAMA0GCSqGSIb3DQEBCwUAA4ICAQCJV4+j+fir3b5YNVfWCJ3YTr0tzkctC5wrF6/WA4uFvKX+ofVqt3aEjDWDBopf30XQRxoAff5OryJ1FnwepjCxeCfzxbiGEIrJlxPi19zZ6zKVbSdftBUWvVlAU8GkJlpVMAyya67NEGy7W9SAFraXsgseQvFjuWULts0cGp7ooHUh9V9bRX1eBt8nOFTbl6MhZLSLIRI8Tv+o3FKc6/Ko2lFkJnEWGudUCyupcwurSyiGGvJiJKfKu+na60mqaFEvYYGQs0ewa437qou3ZECHM0FeM86Hero76CZ9PVnKqyi9juueb4aqHn6Jn09HHnrsbCJ/ipK7c8pZDqGZml5eNlDUApscO3WF/14ejmYQXr/SbgaoXaip9hAaH7kJmaq8ibRCJa4iZQfNSgWYOJWYJ+yxln/7jov2mbD1BmKzFGWSoCyFCmRgfrcfp5dPjF5XP3nLmII/tLOtSGtpm5jqjkeCYaBWf3ENUrvwDCTeXkw1eP6BlLTQt+XCDbWb6bvbJRGr853gj329Dqf1Lwx7Iru9c+MDibF2uQnIPS0Wzaro0Oydq/ddf3AtzDJgQ4irmgSVDzmJmin9+UUmEX/Y9u+dE7w0ssWaLzFzX9KCbrp9TGU3kbOcjNFwSkUgA4G65x5bF1fAlJoZM3fUrvnkeIt5/Q1E2f7+GQ/056vN7g==" FechaExp="2018-07-30T19:49:46-05:00" CveRetenc="01" xsi:schemaLocation="http://www.sat.gob.mx/esquemas/retencionpago/1 http://www.sat.gob.mx/esquemas/retencionpago/1/retencionpagov1.xsd">
    <retenciones:Emisor RFCEmisor="GLS131106EQ4" NomDenRazSocE="Globoworld Language School S de RL de CV"/>
    <retenciones:Receptor Nacionalidad="Nacional">
        <retenciones:Nacional RFCRecep="CAOA591229PA4" NomDenRazSocR="ALICIA CABRERA OCAMPO"/>
    </retenciones:Receptor>
    <retenciones:Periodo MesIni="1" MesFin="12" Ejerc="2017"/>
    <retenciones:Totales montoTotOperacion="154222.24" montoTotGrav="154222.24" montoTotExent="0.0" montoTotRet="0.0">
        <retenciones:ImpRetenidos BaseRet="154222.24" Impuesto="01" montoRet="15422.24" TipoPagoRet="Pago definitivo"/>
    </retenciones:Totales>
</retenciones:Retenciones>
2018-07-30 19:49:47,182 DEBUG [http-8443-27] (PacnessService.java:188) - Get folios from DB (GLS131106EQ4) : 1
2018-07-30 19:49:47,182 DEBUG [http-8443-27] (PacnessService.java:209) - only one CFDiFolios founded : com.cfd.shared.model.CFDiFolios@25c4efb7[id=5521,emisor=GLS131106EQ4,ini_range=2200,fin_range=3200,current_folio=2772,status=ON_USE,dateOfIssue=04/12/2018 17:19:29,date=04/12/2017 17:19:29,lastTransaction=<null>,newFolios=0,paymentType=<null>]
2018-07-30 19:49:47,235 DEBUG [http-8443-27] (PacnessService.java:120) - Message: El comprobante tiene una fecha/hora mayor a la actual
2018-07-30 19:49:47,236 DEBUG [http-8443-27] (CFDManager.java:1007) - update status : 124 : El comprobante tiene una fecha/hora mayor a la actual

**Comment by jccastillo0007** [comment]
Cómo lo puedo reproducir en Pruebas ?
A mi me marca error en el sello, pero no se si estoy capturando bien la info...

SI viste que el error de pro, pudiera ser solamente el tema de sincronizaci[on del server vs el server del pac..?

"update status : 124 : El comprobante tiene una fecha/hora mayor a la actual"

**Comment by RigoFlores** [comment]
hay una fecha que marca diciembre 2018
según yo por ahí va el tema

**Comment by RigoFlores** [comment]
en el log que te mandé, vienen los datos a capturar... los puedes tomar del XML

**Comment by jccastillo0007** [comment]
no encontr[e un correo con esa info... si lo tienes a la mano, me lo puedes volver a enviar pl

**Comment by jccastillo0007** [comment]
en el xml que viene aqui arriba en el ticket, no hay ninguna fecha de diciembre 2018

**Comment by jccastillo0007** [comment]
estuve haciendo pruebas con la info del cliente...  crei que tenía que ver con la hora del servidor, que fuera un poco adelantada, pero la retrase un poco y me seguia dando error... 

Eso no ha cambiado en mucho tiempo ... asi que el problema no es de código

**Comment by jccastillo0007** [comment]
que petch con este tema, si fue de datos ?

**Comment by RigoFlores** [comment]
Aún no responde el cliente, hoy lo checo.

**Comment by RigoFlores** [comment]
ya respondió el cliente. Sigue el problema. Usario=yesi, pwd= ye999.
Esta es la pantalla que marca el error, pero donde se ven los datos para hacer la prueba.

<img width="678" alt="retenciones" src="https://user-images.githubusercontent.com/2912775/43869437-0d188416-9b38-11e8-8c38-012dbbf583e8.PNG">

**Comment by RigoFlores** [comment]
Marca el error en el sello, no sé si cambió o que pasó.
Esta es la liga que hallé con información de retenciones...

https://www.sat.gob.mx/consulta/65554/conoce-el-esquema-de-factura-electronica-de-retenciones-e-informacion-de-pagos

En la parte inferior derecha, se ubican las ligas al estándar y catálogos. Hay que revisar en el estándar si no cambió la forma de sellar. Quizás si.

**Comment by RigoFlores** [comment]
entendí que el pac dijo que era el sello...

**Comment by jccastillo0007** [comment]
yeap... ya logre timbrar de forma exitosa... pero hay un detalle

El algoritmo para sellar retenciones es SHA1
y el algoritmo para sellar cfdi es SHA256

lo cual no entiendo, nunca habia diferenciado entre tipos de CFDi para usar uno u otro algoritmo de sellado... algo paso que no nos enteramos... sabes desde cuando no usaban retenciones ?

Tengo que implementar la diferencia en tiempo de ejecución para diferenciar entre ellos...

Ya mañana queda listo.

**Comment by RigoFlores** [comment]
Lo que entiendo que sucede, es que para la versión 3.3 cambió el algoritmo de sellado de SHA1 a SHA256, pero solo para el CFDI.
Con ello, las retenciones se quedaron en la modalidad anterior.

**Comment by jccastillo0007** [comment]
ya esta listo retenciones en pru... pero me truena la plantilla de retenciones ... 
Si ya tienes una plantilla válida, asignasela al RFC ACO para que purebes..

Nos faltaría la plantilla genérica retenciones33.jrxml

**Comment by RigoFlores** [comment]
déjame verla... entiendo que cambiaste todo como para el cfdi 3.3, pero así como el SAT le hizo, nada de ello tendría que cambiar, incluso ni la plantilla... 
pero bajo el entendido que manejas una sola sección para el jasper, voy a migrar la plantilla de retenciones, aún cuando nada cambió

**Comment by RigoFlores** [comment]
Ya la subí a la cuenta de ACO en pruebas.
Intenté timbrar, y me volvió a dar un error...

Error al timbrar el CFDi de retenciones (124)

**Comment by jccastillo0007** [comment]
Esta marcando error en el template de productos.. por el campo fechaAduana

Caused by: java.lang.NoSuchMethodException: Unknown property 'fechaAduana'  template retencion_products.jasper

Pasame ese template, el .jrxml, para yo arreglarlo, si no vamos a estar a prueba y error.

**Comment by jccastillo0007** [comment]
copie la plantilla base_productos33.jasper a retencion_producs.jasper y si funciono...

Mandame los templates finales para subir todo a PRO

**Comment by RigoFlores** [comment]
ya te los mandé.
Los configuré en pruebas, pero no los jaló.
Deben tener un nombre en particular?? 
Según recuerdo, no se deben llamar igual que el genérico.

Cuál será el nombre genérico del template para retenciones???

**Comment by RigoFlores** [comment]
cuando llevamos correcciones a pro, ya que mientras no se suban, para los clientes es lo mismo, es decir no le estamos resolviendo?

**Comment by jccastillo0007** [comment]
ya esta en PRO, lo subí ayer en la noche

**Comment by RigoFlores** [comment]
si, el asunto es que no me dijiste cuál era la nomenclatura requerida para la plantilla estándar.
Lo investigué a prueba y error en producción, para subir la plantilla que estaba buscando.
