### ISSUE TITLE
No está validando correctamente el CBB leído desde el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1393]
Cuando lees el CBB con un lector de QR, te debe mandar a la liga del SAT y es como una macro o api, que vacía los datos en el verificador del SAT.
Nuestro código no lo está haciendo correctamente. Al menos detecté que le falta un & entre ? y id?, es decir debería quedar ?&id= Te lo envié por correo. Se lo agregué manualmente y no jaló, supongo yo porque al final el fe= lleva una cadena que incluye todo lo anterior.

https://verificacfdi.facturaelectronica.sat.gob.mx/default.aspx?id=da83924b-3d8e-4228-8579-0e70434d4496&re=WEB120216SD0&rr=XAXX010101000&tt=48068.9964&fe=L9amNg==

**Comment by jccastillo0007** [comment]
Leí este cbb de una factura de at&t y ni siquiera carga los datos en la pantalla de verificación del sat

https://verificacfdi.facturaelectronica.sat.gob.mx/default.aspx??id=1741D459-FCCF-4401-AFD6-5B02EB27455D&re=CNM980114PI2&rr=XAXX010101000&tt=3300.00&fe=19XnqQ==

**Comment by jccastillo0007** [comment]
ya encontre la diferencia, no es el & que descubriste.

Checa estas dos cadenas

https://verificacfdi.facturaelectronica.sat.gob.mx/default.aspx?&id=ac0888cd-a8a2-4e4b-a16b-8be8bf42dfbf&re=CAAJ7506072P2&rr=TIA101020BP4&tt=24360.0&fe=OaxNkA==

https://verificacfdi.facturaelectronica.sat.gob.mx/default.aspx?id=ac0888cd-a8a2-4e4b-a16b-8be8bf42dfbf&re=CAAJ7506072P2&rr=TIA101020BP4&tt=24360.00&fe=gvf2Zg==

La primera la generamos nosotros y es incorrecta.
La segunda la generó el SAT, al momento de consultar la representación impresa de la misma factura.

La diferencia son los últimos 8 caracteres, nosotros estamos poniendo los 8 últimos caracteres del sello del sat, y en realidad deben ir los últimos 8 caracteres del sello del emisor

Te voy a generar una versión standalone para probar..

**Comment by RigoFlores** [comment]
Pues se ocupa en escritorio, pero sobre todo en web ... en ambos.

**Comment by jccastillo0007** [comment]
Listo... subo un release de standalone, y otro a web... ya generé yo una factura y ya la valida correctamente

**Comment by jccastillo0007** [comment]
no alcance a terminar lo de pagos.... ma;ana espero que ya quede listo

**Comment by RigoFlores** [comment]
AHORA EL TOTAL NO LO ESTÁ REPORTANDO CORRECTAMENTE.
ESE TOTAL EN EL QR, DEBE SER EL MISMO QUE SE ENVÍA AL XML, DE LO CONTRARIO QUEDA CHUECO Y POR ELLO NO VALIDA.
TE ENVIÉ CORREO.
OTRA MAS DE PRODUCCIÓN.....

**Comment by jccastillo0007** [comment]
fixed... standalone release 11.0.1 y web PRU...

**Comment by RigoFlores** [comment]
Hice la prueba inicialmente para web pru, y no está jalando... esta es la cadena que envía el CBB.
Si te das cuenta envía 4 decimales al total.

https://verificacfdi.facturaelectronica.sat.gob.mx/default.aspx?id=3C4CA678-D11E-4B58-90DE-FF1CC28FF9AE&re=ACO560518KW7&rr=TIA101020BP4&tt=116.7656&fe=iQxWSQ==

y el XML de esa factura que es la A54, por si gustas checar indica entre otros muchos parámetros:

Moneda="MXN" TipoCambio="1" **Total="116.77"**

es decir a menos en web, no quedó la corrección. Ahora sigo con escritorio

**Comment by RigoFlores** [comment]
Ya hice la prueba en escritorio, capturando las mismas cifras para reproducir el escenario.
En este caso, si jaló OK, es decir reportó el total a 2 decimales, tal cual se incluye en el XML.

https://verificacfdi.facturaelectronica.sat.gob.mx/default.aspx?id=BF5D111E-29FB-47AC-A876-9683CDA188B3&re=TCM970625MB1&rr=TIA101020BP4&tt=116.77&fe=/LR7jQ==

**Comment by jccastillo0007** [comment]
fixed... ayer no subi el cambio a web

**Comment by RigoFlores** [comment]
OK, en pruebas ya quedó bien este asunto. Al menos a nivel del contenido del CBB.
La prueba end to end, es timbrar en producción, y que al leer el cbb valide correctamente en el sat.
Lo cerraré en cuanto supere esa prueba...

**Comment by RigoFlores** [comment]
cuando subimos a pro esto???
