### ISSUE TITLE
Navision - Implementar ajustes de documentos relacionados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1394]
Estoy revisando si solo aplica para 'facturas globales' que le llaman ellos.
Es una factura que ampara el total de un servicio, y donde se han recibido uno o varios anticipos. Para nosotros es una factura estándar (hasta este momento), ya que no hacemos ningún distingo entre esa factura y una normalita.

Pero estoy esperando la respuesta si aplica también para factura estándar y nota de crédito.
Como quiera, ya tengo que dar de alta este issue, para no perderlo de vista

**Comment by RigoFlores** [comment]
Ya platiqué con ellos. Solo aplica para facturas.
Las notas de crédito, permanecen igual que como está ahora.
Ellos consideran que solo aplica para facturas 'globales'.
También consideran que en facturas estándares no se presenta el caso de tener que relacionarlas con otro CFDI.

Por lo tanto, para conocer los documentos relacionados de una factura, se tendrá que ejecutar este cueri en producción:

SELECT [Factura]
      ,[Factura anticipo]
FROM [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Relacion factura anticipo]
where [Factura] = '15FVMX049'

si lo quisieras hacer en pruebas, sería:

SELECT [Factura]
      ,[Factura anticipo]
FROM [PRUEBAS_SAT].[dbo].[MEXICO - IP - PRUEBAS SAT$Relacion factura anticipo]
where [Factura] = '15FVMX049'

**Comment by jccastillo0007** [comment]
subi al dropbox una versión que implementa el nuevo query... esta enfocado a pruebas.... puedes checar pl

**Comment by jccastillo0007** [comment]
En la carpeta C://TestFacturat33 instale una versión de pruebas... al ejecutarlo, no tengo datos para probar...
la factura 15FVMX049 no existe en la vista NavisionCFDi que en realidad es la tabla...Sales Invoice Header

Aunque si existen registros en la tabla Relacion factura anticipo.

Lo que si pude corroborar, es que la versión generada desde mi lap, si se puede ejecutar en otros ambientes

**Comment by RigoFlores** [comment]
Si no es posible validar en pruebas, entonces, tenemos que irnos a producción.
Como quiera esa parte específica de cfdis relacionados para factura, no está jalando como ellos quieren.
De aquí a que nos ponemos de acuerdo en el ambiente de pruebas, vamos a perder mucho tiempo, mejor hacerlo en pro, como vex?

**Comment by jccastillo0007** [comment]
ok, ahorita subo un release apuntando a la base de datos de pro
la dejo en dropbox

**Comment by jccastillo0007** [comment]
subi un release 11.0.1 sin prefijo de navision, pero te sirve igual.. pues es una versi[on de producción, realmente depende de la licencia

**Comment by RigoFlores** [comment]
OK, en cuanto me avisen lo validaré para proceder a cerrar este issue.

**Comment by jccastillo0007** [comment]
recuerda instalar la última versión en Navision... yo no lo hice para producción.

**Comment by RigoFlores** [comment]
Si, ya la pasé a producción.
En cuanto me digan que ya está postearon su cambio, entonces levanto la nueva versión.

**Comment by jccastillo0007** [comment]
listo, esta en dropbox con fecha de hoy}

**Comment by RigoFlores** [comment]
(este issue estaba en espera de que se presente el escenario, y ya lo volviste a subir?)
No creo que comentaste el issue incorrecto.

Como quiera estoy en espera de validar 2 issues de navision

**Comment by RigoFlores** [comment]
No jaló. Subí la última versión que me indicaste (hace 6 días). El jar mas reciente, tiene fecha del 28 de agosto.

Ejecuto este cueri:

SELECT [Factura]
      ,[Factura anticipo]
FROM [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Relacion factura anticipo]
where [Factura] = '18FVMX191'

y el resultado es:

18FVMX191	18FVMX163

Es decir, quieren relacionar la factura que se está emitiendo (191), con la factura anteriormente emitida (163), pero ni el XML, ni el PDF reflejan ello en su contenido.

**Comment by jccastillo0007** [comment]
listo... ya lo corregí y lo instalé en el server de navision.

La última factura generada el día hoy a las 9:01 pm aprox, con el folio 18FVMX191 ya trae el documento relacionado.

Lo malo es que generé varias veces la factura... y me parece que mando emails... tienen que cancelarlas

**Comment by RigoFlores** [comment]
PREGUNTA 1, DESDE DONDE ENVÍA EL CORREO: SERVIDOR NAVISION O PLATAFORMA?

OBSERVACIÓN, CUANDO EL PDF SE 'REGENERA' EN WEB, NO ESTÁ ENVIANDO TODAS LAS VARIABLES AL PDF. DE LAS QUE NOTÉ, ASÍ DE ENTRADA SON LAS DE DOCUMENTO RELACIONADO PRECISAMENTE.

**Comment by jccastillo0007** [comment]
del servidor de navision, todos los emails de standalone, se mandan desde el servidor del cliente... 

Hay que checar que variables faltan y levantar un issue para eso
