### ISSUE TITLE
No está timbrando los recibos de nómina el conector - XML mal formado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1395]
No le hallo. 
Los que antes si timbraba, ahora ya no.

Lo único que se me ocurre, es que veo algunos caracteres extraños (por ejemplo en la etiqueta antigüedad, o en la descripción del concepto). Aquí la salida:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www
.w3.org/2001/XMLSchema-instance" xmlns:nomina12="http://www.sat.gob.mx/nomina12"
 Version="3.3" Serie="NOM" Folio="100" Fecha="2018-08-07T21:00:28" Sello="O5BY8X
z9nnE0JfSU0kluzOZf+b8SYvXOsGEYA9LonP4KDv95wJu03TUG+/ZXwkbnZbr7xpSLrUpZeSrw+y2+kx
n9Ds8gcep8NBlEYc2OjoZPwooqZygvLnW3cLLLhV80nMbDaukpiW2PY1go+FQRpZqbLaS3WxJm6Dv6Ik
H39FWZvqdbrfoZ+XlENdLI25rhINMsAqI/y+dR4CLk/R8MFiuzZ8mbE+h3YaQ+beiXowATuvQE6NO5qy
p5TJE5pSwSiwUVcekzUHVDrZS6Z5S+6DDAUepqGs0Pmr9zKdWEVAmvJsXG05puNYBPH3fA6jlZjUiu8I
aNHNNVsuJxE4sGug==" FormaPago="99" NoCertificado="20001000000300005692" Certific
ado="MIIF6zCCA9OgAwIBAgIUMjAwMDEwMDAwMDAzMDAwMDU2OTIwDQYJKoZIhvcNAQELBQAwggFmMSA
wHgYDVQQDDBdBLkMuIDIgZGUgcHJ1ZWJhcyg0MDk2KTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5
pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQ
gZGUgbGEgSW5mb3JtYWNpw7NuMSkwJwYJKoZIhvcNAQkBFhphc2lzbmV0QHBydWViYXMuc2F0LmdvYi5
teDEmMCQGA1UECQwdQXYuIEhpZGFsZ28gNzcsIENvbC4gR3VlcnJlcm8xDjAMBgNVBBEMBTA2MzAwMQs
wCQYDVQQGEwJNWDEZMBcGA1UECAwQRGlzdHJpdG8gRmVkZXJhbDESMBAGA1UEBwwJQ295b2Fjw6FuMRU
wEwYDVQQtEwxTQVQ5NzA3MDFOTjMxITAfBgkqhkiG9w0BCQIMElJlc3BvbnNhYmxlOiBBQ0RNQTAeFw0
xNDExMjUwMDM3MjlaFw0xODExMjUwMDM3MjlaMIHXMScwJQYDVQQDFB5BTExJQU5DRSBFTVBF0U9TIFM
gREUgUkwgREUgQ1YxJzAlBgNVBCkUHkFMTElBTkNFIEVNUEXRT1MgUyBERSBSTCBERSBDVjEnMCUGA1U
EChQeQUxMSUFOQ0UgRU1QRdFPUyBTIERFIFJMIERFIENWMSUwIwYDVQQtExxBQ081NjA1MThLVzcgLyB
IRUdUNzYxMDAzNFMyMR4wHAYDVQQFExUgLyBIRUdUNzYxMDAzTURGTlNSMDgxEzARBgNVBAsTClN1Y3V
yc2FsIDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6Rh93b3u9Av4e2WU8x28p2jRNcqS
L2lcpQBw+95IBf0QdQn3y5Ghx2m/RhYwEOod9gUS7ER2E/+Rea5y0YItrcuPY0tWsql2ofER24luXBWx
iD3+wjXbmoBSdmC+L/2/ZOl3m8Wk6iLxRIzTwDAGyQZup3LwVPC1zmWWVFM+d6TfGW4Ffe8sfR3XFRZu
sJQpO7JFDZUzCs/uFplVgtr1L2sYquhpwX4efUHpBFPYBIkXpUJMX3X5dAJyakEIJjw8mL3f5vyUkegH
HngAO0ytbHayJ5eBApbRr7KYRQZbiSCn2UTtB9H5hSWN55iBwnCp4sPgD0PzcTzFAsyb+G4t9AgMBAAG
jHTAbMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgbAMA0GCSqGSIb3DQEBCwUAA4ICAQCudqGjViZmgXK
Yh3JB2BSHy2/tPm1O5xrqWKe8IFzTIZKhDSfMBdmaF58MxfIpt2ccy3NDcr46n5ksnA4efkeNiZcR4U9
W9dy19TjfHdZ4h8U/1jpk1DRb9AQO7/B7WCQL3ZY5yiRSJj+e4JG0SqrtPUgmMQIG6XNQUecAkDvqVEd
PuovmvoQetKzFzJVt+KboaT3V5Wpmi56ojjupDnSM6ENqTmRrWSzizjVSTIYdLAu1d5k20MufxRd8IHP
8VZED4BFvqeXJZkfaep/er0o7KzZZrcSCGCKtW1w8lMr9dX4fCDmcxNB4M22SqX0fx1IMvAGts2c6CXF
FGe245wR1YqCvzAfyXTt/dYwh5kqWPjEm+PRUWD1woxkrpgn2P3Iv9BHXAlIvT+O943t6JQ9XBDlp1U/
RNXDxvA/uWomCOUOrIkNsg4oQnxkc2geRtju5qkYhr7MEg8tyKYTNGqxNHJ+mOC4D3C0lC4lFerdnwEH
rKk4+Pq0h9/f5AbFC73Crz4Vx7QjPvX6MjVcGvlfka+ov4zdtIc83/dPij3CSTUv9OCDrnfnaHlz8yQc
F94dAOeW7ykYuimbZ6Hdi7JsnFMVHfDeDt9jDgQBBzoAdaJUxoYOA809sI1eZJR4kHEonlaiCGFqV6Hp
S6EtBVtfXft6j4DpLXQBqu8bIgYoSZA==" SubTotal="32891.54" Descuento="7891.54" Moned
a="MXN" Total="25000.00" TipoDeComprobante="N" MetodoPago="PUE" LugarExpedicion=
"88179" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/si
tio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/nomina http://www.sat.gob.mx
/sitio_internet/cfd/nomina/nomina11.xsd">
    <cfdi:Emisor Rfc="ACO560518KW7" Nombre="Cliente de pruebas de timbrado de fi
nkok" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="GAVD500406PF1" Nombre="DAVID GARZA VILLARREAL" UsoCFDI="
P01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111505" Cantidad="1" ClaveUnidad="ACT" D
escripcion="Pago de n├│mina" ValorUnitario="32891.540000" Importe="32891.540000"
 Descuento="7891.54"/>
    </cfdi:Conceptos>
    <cfdi:Complemento>
        <nomina12:Nomina FechaFinalPago="2018-06-29" FechaInicialPago="2018-06-1
6" FechaPago="2018-07-04" NumDiasPagados="14" TipoNomina="O" TotalDeducciones="7
891.54" TotalPercepciones="32891.54" Version="1.2">
            <nomina12:Emisor/>                                                    nodo emisor, antiguedad, departamento, 
            <nomina12:Receptor Antig├╝edad="P193W" Banco="012" ClaveEntFed="TAM"  fecha inicio, banco, puesto, salarios, sindicalizado
 Curp="GAVD500406HTSRLV07" Departamento="DIRECTOR GENERAL" FechaInicioRelLaboral  tipo de contrato=09, jornada=99.
="2014-10-03" NumEmpleado="1" PeriodicidadPago="03" Puesto="DIRECTOR GENERAL" Ri
esgoPuesto="1" SalarioBaseCotApor="2387.6" SalarioDiarioIntegrado="0.0" Sindical
izado="No" TipoContrato="99" TipoJornada="01" TipoRegimen="09"/>
            <nomina12:Percepciones TotalExento="0.0" TotalGravado="32891.54" Tot
alSueldos="32891.54">
                <nomina12:Percepcion Clave="099" Concepto="HON ASIM SAL" Importe  tipo=46
Exento="0.0" ImporteGravado="32891.54" TipoPercepcion="001"/>
            </nomina12:Percepciones>
            <nomina12:Deducciones TotalImpuestosRetenidos="7891.54">
                <nomina12:Deduccion Clave="155" Concepto="ISPT" Importe="7891.54
" TipoDeduccion="002"/>
            </nomina12:Deducciones>
        </nomina12:Nomina>
    </cfdi:Complemento>
</cfdi:Comprobante>
2018-08-07 21:00:31,645 DEBUG [pool-2-thread-1] (FacturaTiCreator.java:1074) - C
alling FacturaTi to sign this cfdi
2018-08-07 21:00:31,648 DEBUG [pool-2-thread-1] (CFDiHelper.java:41) - regular C
FD length : 4691
2018-08-07 21:00:31,653 DEBUG [pool-2-thread-1] (CFDiHelper.java:43) - zip CFD l
ength : 2965
2018-08-07 21:00:31,654 DEBUG [pool-2-thread-1] (CFDiHelper.java:45) - decode CF
D length : 3956
2018-08-07 21:00:31,656 DEBUG [pool-2-thread-1] (CFDiHelper.java:55) - FacturaTi
 will get this : EMISOR value : ACO560518KW7
2018-08-07 21:00:31,657 DEBUG [pool-2-thread-1] (CFDiHelper.java:55) - FacturaTi
 will get this : RECEPTOR value : GAVD500406PF1
2018-08-07 21:00:31,658 DEBUG [pool-2-thread-1] (CFDiHelper.java:55) - FacturaTi
 will get this : CLIENT_SERIE value : NOM
2018-08-07 21:00:31,659 DEBUG [pool-2-thread-1] (CFDiHelper.java:55) - FacturaTi
 will get this : CLIENT_FOLIO value : 100
2018-08-07 21:00:31,660 DEBUG [pool-2-thread-1] (CFDiHelper.java:55) - FacturaTi
 will get this : HAS_ADDENDA value :
2018-08-07 21:00:31,668 DEBUG [pool-2-thread-1] (CFDiWSClient.java:74) - 3956
2018-08-07 21:00:33,904  INFO [pool-2-thread-1] (CFDiWSClient.java:77) - Factura
Ti ack : com.facturati.ws.binding.jaxb.Ack@1536370[code=003,description=301 : XM
L mal formado]
2018-08-07 21:00:33,905 DEBUG [pool-2-thread-1] (CFDiWSClient.java:79) - Propert
ies received : CFDi_FOLIO value : 343

**Comment by jccastillo0007** [comment]
me pasas el txt que intentan timbrar... para tratar de reproducir

**Comment by jccastillo0007** [comment]
no pude correr estas pruebas. ... la app se queda como bloqueada sin avanzar... tu si puedes ?

casi recuerdo que ya habia pasado antes pero no recuerdo que fue, y tu?

**Comment by RigoFlores** [comment]
hay un antecedente en el issue 1245...

**Comment by jccastillo0007** [comment]
subi un release que ya procesa los archivos... pero creo que sigue mal con el pac

**Comment by RigoFlores** [comment]
Correcto, al menos ya procesa el archivo, pero marca XML mal formado.
Capturé un recibo de nómina en web, con los mismos datos y si timbró.
Acto seguido, tomé el XML y le quité el timbre para procesarlo en el conector (como si fuera timbrador), pero no, al parecer el timbrador dejó de jalar o no sé porque no procesó el XML.

Esta prueba, era para ver si lo que está mal es el sello o el timbre, ya que estaríamos partiendo de un XML timbrado en web.

**Comment by jccastillo0007** [comment]
pasame el xml que trataste de timbrar

Ya probaste en PRO ?

**Comment by jccastillo0007** [comment]
que wey... pues yo puedo verlo en consultas en web... peeeero no lo encontré... donde fue tu?

**Comment by jccastillo0007** [comment]
ya finalmente encontré el problema... y fueron los putos namespaces...

Aún cuando en desarrollo si se genera bien con los namespaces, resulta que al timbrar en web.... se analiza si trae o no addenda facturat, y en ese proceso perdía los namespaces... lo que me lleva a pensar que tiene mucho que no funcionaba eso... chiaaaa

Ya la subi a PRU... el fix es en web no standalone... mañana lo subo a PRO

**Comment by RigoFlores** [comment]
negativo, eso no tiene mucho que dejó de funcionar... el primer reporte fue 02 de agosto, poco antes.
Recuerda que el asunto es por conector... no entiendo que se corrigió en web, si ahí si jalaba bien.

Total, que aún no jala..
