### ISSUE TITLE
No está enviando la variable tipo de cambio en el documento de pago para moneda distinta a MXN

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1396]
Esto es en WEB.

A nivel documentoRelacionado, es decir la factura o facturas que están pagando, no se está reportando correctamente el tipo de cambio cuando la moneda es distinta a MXN. (es el mismo pedo que tenemos por conector).
Ahora mismo, envía un 1.0 en el tipo de cambio, cuando en la factura pagada la moneda son USD y el tipo de cambio es distinto a 1.

Casi estoy seguro que este issue ya lo había levantado anteriormente, y quizás nunca se atendió.

Aquí tenemos detenidos ahora a otros clientes.

Cada vez veo mas lejano que podamos concluir lo de condominios. No estamos cerrando issues en producción, y al contrario, ya se vienen nuevos temas con lo de pagos que entra en septiembre, así como la nueva cancelación.

**Comment by jccastillo0007** [comment]
Listo en Standalone y PRU

**Comment by RigoFlores** [comment]
ah cabrón, este issue es para web....
Si ya está corregido para escritorio, tons hay que documentarlo en el propio.
Asumo que ya subiste otra versión, compilada o generada igual que la de navision, para que si levante.

**Comment by RigoFlores** [comment]
voy a replantear el escenario de error, entonces cerraré este issue para no confundir
