### ISSUE TITLE
Factura-T - escritorio no está levantando

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1397]
No levanta la última versión de escritorio. Lo intento levantar con el mismo bat que he ocupado al menos los últimos 2-3 años.
Aquí la salida de la consola.

<img width="434" alt="nolevantafactura-t" src="https://user-images.githubusercontent.com/2912775/44170105-e78db900-a09b-11e8-8874-9be213d26688.PNG">

**Comment by jccastillo0007** [comment]
Ya lo probé en tres máquinas diferentes, incluyendo navision , y si levanta... checa bien tu máquina... y las actualizaciones de java, o el bat... algo pasó el sábado en tu máquina.... 

esto quita mucho tiempo

**Comment by RigoFlores** [comment]
lo único que te puedo comentar... es que versiones anteriores, y la versión que subiste de navision, si levantan. 
las 2 últimas versiones que subiste de escritorio, no levantan.

Mismo ambiente, misma BD, mismo procedimiento de borrado y copiado, todo igual.
Lo hice para la versión de navision, y si levantó... repetí por las dudas para las versiones de escritorio y no levantó....

**Comment by jccastillo0007** [comment]
El release 11.0.1 que acabo de subir... te sirve para tus pruebas y las de navision

**Comment by RigoFlores** [comment]
ya levantó en pru, y procesó un texto plano para validar.
Mismo procedimiento, mismo ambiente, mismo todo.
