### ISSUE TITLE
Pantalla Factura - Alinear sección de totales

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#14]
Alienar todos los campos numericos a la derecha
En los totales, se coloca primero subtotal y despues descuento
En la tabla de productos agregar el descuento
Los totales deben ser :  
1. Subtotal
2. Descuento
3. Subtotal - descuento
4. Total imp tra
5. Total imp ret
6. Total

**Comment by RigoFlores** [comment]
LA VARIABLE DE SUBTOTAL - DESCUENTO, SE LLAMA subtotalSD

**Comment by jccastillo0007** [comment]
No supe si reabriste este defecto, valide todo lo mencionado en los comentarios anteriores y ya esta funcionando correctamente.

**Comment by RigoFlores** [comment]
No, no coincide con el orden que te menciono al inicio.
Lo cerraré porque tenemos que trabajar en el acomodo de los datos, amén del diseño.
El acomodo está a nuestro alcance, y el diseño ya lo veremos poquito mas adelante
