### ISSUE TITLE
Conector - Documento de Pago - no envía el saldo insoluto al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1400]
Cuando el saldo insoluto es = 0.00, si lo envía al XML, pero no lo envía al PDF.

Cuando el saldo insoluto es > 0, NO HAY PROBLEMA.

**Comment by jccastillo0007** [comment]
fixed

**Comment by jccastillo0007** [comment]
Esto le va a pegar a todas las plantillas que usan el campo descuentoPro, incluso cuando se esperaba no recibir 0.0

**Comment by RigoFlores** [comment]
deja revisar, ya que si afecta a todo, lo mejor será crear las variables apropiadas para los pagos a nivel producto, porque estamos reutilizando las variables que fueron definidas para otra cosa

**Comment by RigoFlores** [comment]
pues aparece $0.00 como descuento a nivel producto, en una factura estándar.
Esperemos que no le afecte
