### ISSUE TITLE
Implementar nuevo esquema de cancelación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1401]
Lo primero es echarle un vistazo a la documentación, para ver que tanto implica.

**Comment by jccastillo0007** [comment]
ya estoy haciendo pruebas... pero recibo un nullpointerexception... si ma;ana sigue igual, les mando correo

**Comment by jccastillo0007** [comment]
ya esta listo... lo probamos cuando finalmente vaya a salir a pro

**Comment by RigoFlores** [comment]
ok
