### ISSUE TITLE
Permitir capturar la hora al momento de capturar el documento de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1402]
En algunos casos muy específicos, se requiere capturar.
Sería sin la letra T.
Únicamente en modo HH:MM:SS

**Comment by RigoFlores** [comment]
Hoy lo volvieron a solicitar, otro cliente

**Comment by jccastillo0007** [comment]
El problema con este campo es que no podemos validar el formato, pues es un string, será responsabilidad de ellos que ingresen bien los datos.
De hecho se tendría que capturar toda la fecha y hora
Aún asi lo quieren ?

**Comment by RigoFlores** [comment]
Tendría que ser algo así, como una caja de texto, con el valor por omisión:

12:00:00

Indicando que ese es el valor por omisión, y que deben respetar el formato en caso de cambiar el valor:

HH:MM:SS

Si se equivocan, sería problema de ellos... a menos que pudiéramos dar una casilla distinta para horas, minutos y segundos. NO lo creo necesario, pero eso ayudaría a reducir el riesgo de error humano.

**Comment by jccastillo0007** [comment]
pero debe ser toda la fecha, no solo la hora

**Comment by RigoFlores** [comment]
Es que la fecha ya la están capturando del calendario. Eso no cambia.
A un lado una caja de texto con el default: 12:00:00  (sin la T)
Entonces si le cambian, que sea con ese mismo formato.

**Comment by jccastillo0007** [comment]
esta muy chacarron eso... si desean cambiar la hora... entonces que capturen todo mejor

**Comment by RigoFlores** [comment]
Pero la fecha se captura del calendario y está bien.
Lo que se puede hacer, para que no se vea tan chacarrón, es que a un lado del calendario o donde tu creas, se despliegue una caja de texto editable, que una vez capturada la fecha, se muestre el dato completo, por ejemplo: "2018-10-16T12:00:00", y si quieren modificar algo, que ahí lo hagan.

Como la vislumbras???

**Comment by jccastillo0007** [comment]
ya esta la caja de texto... pero no logre que la ponga en la fecha de pago... wip

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Chiaaa... se fue a producción, y ni siquiera lo ví.

A ver platícame como funciona. Veo que agregaste la caja de texto, donde se despliega la fecha, cuando ésta se elige desde el ícono de calendario.
Esa fecha que se despliega cuando eliges desde el ícono del calendario, debe tener el horario por omisión, es decir 12:00:00, y ahora mismo coloca 00:00:00, lo cual es incorrecto.

a) Que pasa si no selecciono la fecha? (porque la fecha desplegada por omisión es correcta)

**Comment by jccastillo0007** [comment]
ok, le cambio la fecha default.

Si no selecciona ninguna fecha, se toma la que se presenta en el campo inicial y se le agrega T12:00:00

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
listo en pru...

**Comment by RigoFlores** [comment]
si no selecciona fecha, marca error.
Es decir la fecha que coloca por default no la está tomando correctamente.

**Comment by jccastillo0007** [comment]
crap, fixed pru y pro

**Comment by RigoFlores** [comment]
Ya no marcó error.
Jejeje, ahora le agrega la hora de emisión cuando no cambian la fecha.
Debe agregar la hora por omisión, eso es 12:00
Es un pequeño detalle, pero de una vez que quede corregido

**Comment by jccastillo0007** [comment]
no lo creo que sea necesario... si ellos no capturan una fecha en particular, es porque no les afecta, y la hora del sistema esta bien... si quieren una fecha específica, la capturarían, no manches

**Comment by RigoFlores** [comment]
sale, luego no se diga que pido cambios a lo cabrón.

**Comment by RigoFlores** [comment]
si el cliente la hace de a pedo, de manera muy desleal, le diré que porque no capturó la fecha y hora...
