### ISSUE TITLE
Web - Documento de Pago - tipo de cambio en documento relacionado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1404]
Premisa:
CFDI de pago: es en sí el XML que estaremos generando. 
Documento relacionado, corresponde a los datos del o los XML que dentro del complemento, se están reportando como pagados (independientemente si es total o parcial el pago).

Aquí el issue es:
Cuando la moneda de pago (MonedaP) del CFDI , sea IGUAL a la moneda del documento relacionado (MonedaDR),  **NO SE REQUIERE REPORTAR TipoCambioDR.**

Ahora mismo, si el pago es distinto a MXN, por ejemplo USD, y el documento relacionado se emitió en USD tambiéon, si envía el TipoCambioDR y genera un error.

**Comment by jccastillo0007** [comment]
Listo...

**Comment by RigoFlores** [comment]
está en pro???

**Comment by RigoFlores** [comment]
ayer se me pasó revisarlo... lo acabo de revisar, y sigue marcando el error... tenemos al cliente esperándonos en pro...

CRP206 : La suma de los valores registrados en el campo ImpPagado de los apartados DoctoRelacionado no es menor o igual que el valor del campo Monto. (3)

**Comment by jccastillo0007** [comment]
ese es un problema de las cantidades, no del tipo de cambio... a mi también me salia cuando no me cuadraban las cantidades


Si se trata de otro problema, hay que abrir otro ticket

**Comment by RigoFlores** [comment]
Negativo. En el conector lo puedo reproducir cuántas veces quiera.
Si no incluyo el TipoCambioDR, y la moneda es USD para el pago y para el documento relacionado, lo timbra sin mayor contratiempo.

En otro caso SI INCLUYO EL TipoCambioDR, entonces envía ese error mencionado arriba.
Mi teoría es que se hace una conversión cuando se incluye el tipo de cambio y por ello marca ese mensaje. Este problema lo tengo muy bien acotado, ya que estuve haciendo muchas pruebas para identifcarlo.

Favor de corregir, como se menciona en este issue.

**Comment by jccastillo0007** [comment]
ok, deja reproduzco el problema

**Comment by jccastillo0007** [comment]
pues, no, hay otro escenario que no has identificado...
no pude reproducirlo... y probé con estos datos.

tipoDeComprobante=8
regimen=601
lugarExpedicion=76160
receptor=TIA101020BP4|TECNOLOGIAS DE INFORMACION APLICADA SA DE CV||||||||||||||
serie=P
CA=|||||||||||||||||||
pago=2017-07-10|03|USD|10.25|2000.0|123|||1234567890123456||036680500105247319|01|00001000000305298787|Rea2+ZVznhwzMgEmiHX34OJt1BH3Z7vrbStBWrU++/5ZfAutP7jGANs1hHCM5+GAMrz6D71DVlAMhh5e/ATRGCkagqYqwtgAQmwsUOR30f49u24ZAkXsqbEVjGX6mjJE7Crbxu3ir4lRnNOCTFiHqj0gOge0vmXU1RpDj5YGlnw=
cadPago=||1|14032018|14032018|143609|40072|HSBC|VICTOREEN DE MEXICO S A DE C V|40|021180040598321626|VME871116R22|BANORTE/IXE|TRANSFORMACIONES INDUSTRIALES ESPECIALIZ|40|072818006675395694|TIE101203NZ4|PAGO VICTOREEN A TRANSFORMACIONES ESP DE|0|3172.14|00001000000305298787||Rea2+ZVznhwzMgEmiHX34OJt1BH3Z7vrbStBWrU++/5ZfAutP7jGANs1hHCM5+GAMrz6D71DVlAMhh5e/ATRGCkagqYqwtgAQmwsUOR30f49u24ZAkXsqbEVjGX6mjJE7Crbxu3ir4lRnNOCTFiHqj0gOge0vmXU1RpDj5YGlnw=
documentoRelacionado={CCF518B0-DC5C-4382-9470-CADEE893AA81|DD|666|USD||PUE|1|2000.0|2000.00|0.0}

**Comment by jccastillo0007** [comment]
Estuve jugando con diferentes monedas y con y sin tipo  de cambio... si no pongo el tipo de cambio y la moneda es diferente, me arroja un error que dice que el tipo de cambio se debe reportar.

Pero como ves en los datos arriba, el documento relacionado no tiene tipo de cambio dr y si se timbra de forma correcta... 

Si puedes pasame los datos que tu usas al probar

**Comment by RigoFlores** [comment]
Comenté lo del conector, porque ahí tengo control para reproducirlo, así como también el control para que jale.
El problema es en web, y cuando me preguntaste con cuál factura podrías probar te lo indiqué.
Cualquier factura que hagas en USD, con un tipo de cambio distinto de 1, y luego quieras hacer el pago también en USD te marcará error.

**Comment by jccastillo0007** [comment]
listo, ya quedo jalando en PRU y PRO

Probé el tema de USD vs USD y si jalo...

Probé el tema de MXN vs USD o USD vs MXN y no, no jaló por algo medio raro... de las conversiones que mencionas... lo raro es que recuerdo que en conector lo probé y si funcionó... en fin

**Comment by RigoFlores** [comment]
si lo de pago con moneda distinta, es otra cosa.... y quizás si esté bien, pero como te comenté depende del tipo de cambio. Yo si tengo claro ese escenario, lo validaré y si jala pues ya estamos, sino abriré otro issue
