### ISSUE TITLE
Conector - Documento de Pago - TipoCambioDR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1405]
El tipo de cambio del documento relacionado "TipoCambioDR", únicamente se debe enviar cuando la moneda del pago "MonedaP", sea distinta a la moneda del documento relacionado "MonedaDR".

Eso depende del contenido del archivo de texto.

Solo hay que quitarle el signo de $ que acompaña al tipo de cambio que envía al PDF.

**Comment by jccastillo0007** [comment]
no puedo quitarle el $ porque eso le pegaria a todas los templates de los productos... mas bien modifica la plantilla o asi que se quede

**Comment by jccastillo0007** [comment]
Que desmadre...  espero que con las pruebas que hice ya este bien

**Comment by RigoFlores** [comment]
Existe un escenario, que no aprueba, y no sé que tan común sea.
Espero que no se presente, ya que es contradictorio.
El documento relacionado se emitió en MXN, y se pagó en USD.
Aquí la regla dice que cuando ambas monedas son distintas, se deben reportar los 2 tipos de cambio.

Esta regla se contradice, cuando el documento relacionado está en MXN, no se reporta el tipo de cambio.

Esperemos a ver si mas adelante, se llega a requerir ese ajuste.

Mientras tanto, este issue, que era quitarle el signo, no se cubrió, pero lo atenderé por plantilla
