### ISSUE TITLE
CxC - CFDI de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1407]
Cuando el emisor, cuenta con mas de 2 cuentas bancarias configuradas, no las muestra en el combo.
Si solo tiene una cuenta configurada, si la muestra.

Validé para los datos del cliente, y al parecer ahí no presenta el problema

**Comment by jccastillo0007** [comment]
que raro... el usuario ACO... solo tiene una cuenta configurada y no la muestra en el combo...

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
en pru si, hay que subirlo a pro...

**Comment by RigoFlores** [comment]
cuándo?

**Comment by RigoFlores** [comment]
seguimos igual en pro no está el cambio...

**Comment by jccastillo0007** [comment]
done
