### ISSUE TITLE
CFDI de pago en web - no está enviando el número de parcialidad cuando metPago=PPD

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1408]
Cuando el método de pago "MetodoDePagoDR" del documento relacionado (factura que se está pagando) es PPD, se debe informar el número de parcialidad.

Te mandé un correo explicando el tema

**Comment by jccastillo0007** [comment]
no me llego correo

**Comment by jccastillo0007** [comment]
hoy en dia manda 1 en parcialidad si el metodo de pago es PPD

if (paymentWay.compareToIgnoreCase("PPD") == 0) {
								relatedDocuemnts.append("1"); // numero de parcialidad
							} else {
								relatedDocuemnts.append("");
							}

**Comment by jccastillo0007** [comment]
este es el segundo ticket viejo que vuelves a levantar, que pasa ?

**Comment by RigoFlores** [comment]
No entendí el comentario.
Pero ya ví, el XML que reportaron es de marzo. No me dí cuenta.
Pediré que lo revisen nuevamente.
