### ISSUE TITLE
WEB Documento de pago - la hora de pago por omisión es incorrecta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1409]
Ya se había solicitado que se pueda capturar la hora de pago.
Pero en lo que está listo, la hora de pago por omisión es 12:00:00, y ahora mismo está enviando 00:00:00.

Cuando se pueda capturar dicha hora, el dato sugerido será el default.

**Comment by jccastillo0007** [comment]
Esto ya lo habiamos resuelto... generé ahorita un drp... y esta es la hora que puso

FechaPago="2018-08-29T12:00:00"

tons , estas hablando de otra fecha de pago ?

**Comment by RigoFlores** [comment]
Olvídalo, el tema es que me reportaron un error, con un XML emitido en marzo.
Chiaaaaaa...
