### ISSUE TITLE
PERDIDAD DE INFORMACIÓN EN ESCRITORIO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#141]
YA INDENTIFIQUÉ UN ESCENARIO 100% REPRODUCIBLE PARA LA PÉRDIDA DE INFORMACIÓN. 
Y ESO ES CUANDO REALIZAS CUALQUIER TRANSACCIÓN HACIA LA BD, (CATÁLOGOS, FACTURAS, ETC), Y TE SALES INMEDIATAMENTE DE LA APLICACIÓN, DICHA TRANSACCIÓN NO SE ALMACENA EN EL facturat_db.log

**Comment by jccastillo0007** [comment]
Duplicado con el ticket 161
