### ISSUE TITLE
WEB - cuando se genera el documento de pago, no incluir addenda

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1411]
La addenda según yo, solo se ocupa en facturas.
Quizás aún no en documentos de pago.
Pero por lo pronto, pueden meter ruido las addendas.

Tenemos que inhibirlas cuando el CFDI sea de tipo pago.

**Comment by jccastillo0007** [comment]
para standalone ya esta en la versión de hoy, faltaría web

**Comment by jccastillo0007** [comment]
fixed.
