### ISSUE TITLE
Documento de Pago Web - en el envío automático por correo no envía el XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1412]
No sé si en todos los casos, pero te envié un correo donde puedes checarlo en la consula de sendinblue, y verás que no está enviando el XML, solo el PDF.

Y como es de pago, pues ya están parados de pestañas.

**Comment by RigoFlores** [comment]
siguen en espera

**Comment by jccastillo0007** [comment]
fixed
