### ISSUE TITLE
Navision - Cuando la moneda de pago es distinta a la moneda del CFDI relacionado, debe enviar el tipo de cambio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1413]
Te envié un correo. Aquí te lo ponto

CUANDO LA MONEDA DEL DOCUMENTO RELACIONADO, ES DISTINTA A LA MONEDA DEL PAGO, SE DEBE ENVIAR EL TIPO DE CAMBIO A NIVEL DETALLE:

EN ESTE EJEMPLO, LA FACTURA SE EMITIÓ EN USD, Y EL PAGO ES EN MXN

ENTONCES A NIVEL DETALLE (RESALTADO EN AMARILLO), FALTÓ REPORTAR EL TIPO DE CAMBIO, TANTO EN XML COMO EN PDF.

        <pagos:Pagos xmlns:pagos="http://www.sat.gob.mx/Pagos" Version="1.0">
            <pagos:Pago CtaBeneficiario="03504856627" CtaOrdenante="072306003233612088" FechaPago="2018-08-30T12:00:00" FormaDePagoP="03" MonedaP="MXN" Monto="7674.52" NumOperacion="1" RfcEmisorCtaBen="SIN9412025I4" RfcEmisorCtaOrd="BMN930209927">

                <pagos:DoctoRelacionado Folio="188" IdDocumento="08b44fdd-c1d5-4226-8032-f9b745ce8806" ImpPagado="7674.52" ImpSaldoAnt="405.30" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PUE" MonedaDR="USD" Serie="18FVMX"/>           

 </pagos:Pago>        
</pagos:Pagos>

**Comment by jccastillo0007** [comment]
fixed
