### ISSUE TITLE
Navision Pagos - 1 solo pago, múltiples facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1415]
Está repitiendo el monto global del pago (campo [monto o importe del Pago]), para cada una de las facturas en lugar de tomar el individual de cada factura (campo [Importe Pagado]), de la tabla que se indica en el cueri:

  select *
from **[IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Lineas Documento de pago]**
where [CFDI pago]
in ( '18PAMX0005' );

**Comment by jccastillo0007** [comment]
fixed
