### ISSUE TITLE
Navision Pagos - 1 solo pago a n facturas, repite el proceso n veces

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1416]
Hicieron el pago del cueri de abajo:

  select *
from [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Lineas Documento de pago]
where [CFDI pago]
in ( '18PAMX0005' );

el cual aplica para 5 facturas.
El proceso lo ejecutó 5 veces; hicimos la prueba en conjunto y así fue.

**Comment by jccastillo0007** [comment]
fixed
