### ISSUE TITLE
Migrar BD a Web - cliente GCA960513V78

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1418]
Se subieron los productos, sin la clave SAT.
Se subieron las unidades, sin la clave SAT, pero ya lo arregle.

En el catálogo de clientes, favor de subir nuevamente el de ITE430714KI0.
Tiene varios sucursales (nombres alternos). Puedes colocar como nombre alterno, el estado correspondiente a la direccion de cada sucursal pls???

**Comment by jccastillo0007** [comment]
Lo de productos también lo arreglaste, o sigue pendiente?

**Comment by RigoFlores** [comment]
sigue pendiente, son bastantes para hacerlo a patín

**Comment by jccastillo0007** [comment]
pssss lo de productos, no va a estar tan fácil....

**Comment by jccastillo0007** [comment]
listo... ya están los productos.

No esta de mas que le den una revisada, no vaya ser que los puse chuecos.

Recuerda las correcciones que hicimos al proceso de migración... para que la sig vez lo arregle desde el código... las tienes presentes ?

**Comment by RigoFlores** [comment]
en esta ocasión, faltaron las claves del sat de las unidades. No hay tanto problema.
Noté que algunos clientes, no tenían correctamente el país. No sé si fue porque lo escribieron distinto a cómo tu lo esperas.
Y finalmente el catálogo de productos, no incluía el código del sat correspondiente.
