### ISSUE TITLE
Cambiar el prefijo del complemento de pagos, de pagos a pago10

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1423]
Ya otro cliente se quejó, y es que se someten a los validadores de los PAC y son ellos quiénes la hacen de a pedo en su afán de ser puristas.
Total que contra ello no podremos, y hay que modificar en el conector estándar, optibelt y navision, así como en el web, el prefijo del pago. Ahora dice pagos y se ocupa que diga pago10  (chiaaaaa)

<img width="939" alt="prefijopagos" src="https://user-images.githubusercontent.com/2912775/45453406-616a8f80-b6a6-11e8-860b-d3eb333d9e90.PNG">

**Comment by jccastillo0007** [comment]
done
standalone en dropbox
web en pru

**Comment by RigoFlores** [comment]
En web ya lo hace, hay que llevarlo a pro.
En conector estándar, ya lo hace. 

Pregunta, esta versión funciona idéntica para optibelt y para navision???

**Comment by jccastillo0007** [comment]
si

**Comment by RigoFlores** [comment]
oyes, si lo subiste a pro?

**Comment by jccastillo0007** [comment]
noup, hoy lo subo
