### ISSUE TITLE
En producción - Marca un error al generar el Pago 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1424]
Yo lo capturé, porque es para la tia, pero todo se ve bien. 
Lo he capturado así cualquier cantidad de veces.

El pedo que veo yo, es que según entiendo si lo timbra, pero nadie se entera, porque marca error, pero el CFDI ya fue timbrado

[Error en PAGO 115.txt](https://github.com/jccastillo0007/eFacturaT/files/2384993/Error.en.PAGO.115.txt)

Anexo la salida del catalina.

**Comment by jccastillo0007** [comment]
el pedo fue que elegiste un rfc que utiliza la addenda CCE, y habia un lugar donde no se estaba validando que en pagos no se agregan addendas.

**Comment by RigoFlores** [comment]
Entonces, no había quedado aquello que para pagos no se considere la addenda.
Ya que ese cliente en específico, me pidió su rep (la tendencia es llamarle rep, recibo electrónico de pago).
Tu me dices cuándo ya puedo generarlo en pro
