### ISSUE TITLE
Pagos conector - cuando son mas de 2 facturas, con distinta moneda, envía distinto TC a cada CFDI pagado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1425]
No se arregló con la ultima versión.
El tema es que cuando la monedaP es distinta a la monedaDR, se debe reprotar el TipoCambioDR.
Pero si además son mas de una factura las que se pagan, a cada una le envía distinto TipoCambioDR.

Te enviaré un correo con el archivo que ocupo, pero ya te lo había enviando anteriormente.
Otra cosa, el TC envíalo al PDF con al menos 4 decimales, de preferencia 6 decimales.

**Comment by jccastillo0007** [comment]
el fix que se liberó fue para navision y web... en conector estándar no se hacen cálculos.
