### ISSUE TITLE
Web Pagos - cuando las monedas de pago y dr son distintas, marca error al pagar 2 o mas facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1426]
Ahora mismo en pruebas, con la cuenta TCM, intento pagar las facturas 14 y 15 del RFC FOPR.
Se emitieron en USD, pero intento pagarlas en MXN y marca error. Checa la pantalla.

<img width="362" alt="sigueerror" src="https://user-images.githubusercontent.com/2912775/45649568-4aa2af00-ba91-11e8-9349-2263aeb07fbc.PNG">

**Comment by jccastillo0007** [comment]
ya vi el error, es por el tipo de cambio, en web no lo estsaba redondeando, lo puse a 4 dígitos

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ya no marca el error, pero al PDF solo estás enviando 2 decimales, ocupamos yo creo al menos 4.

**Comment by RigoFlores** [comment]
y este cambio no llegó a pro...

**Comment by jccastillo0007** [comment]
DONE
