### ISSUE TITLE
Web Pagos - cuando en la captura de pagos, se incluya alguna NC marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1427]
Supongo que está intentando colocarla como parte de los CFDIs pagados, pero no.
Cuando en un pago híbrido que incluye notas de crédito, se debe aplicar todo como antes funcionaba para propósitos de CxC, peeeeero para el tema del CFDI de pagos, solo se deben incluir las facturas.
Adicionalmente, como no se debe incluir la NC, tampoco se debe considerar en el monto del pago, el importe de dichas notas de crédito.

Para capturar un pago híbrido, se captura primero la cantidad en cash (esta es la que se debe reportar el CFDI de pagos), ya que cuando eligen una NC se incrementa este número. Para el registro interno de CxC está bien, pero para el CFDI de pagos, no se debe considerar ni la NC o NC's, ni su importe

<img width="404" alt="errornc" src="https://user-images.githubusercontent.com/2912775/45656083-1affa100-baa9-11e8-8bc6-14bf140f30d2.PNG">

**Comment by jccastillo0007** [comment]
y que pasa si el importe en cash, que es el que se reporta, no alcanza para pagar todas las facturas seleccionadas... ya que en pantalla pueden considerar NC y con eso pagar n facturas... esto ya se esta complicando al identificar casos especiales como este

**Comment by jccastillo0007** [comment]
con que datos puedo reproducirlo?

**Comment by RigoFlores** [comment]
Como platicamos anoche, voy a reunirme mañana con optibelt para plantear este tema, y revisar lo de un reporte que están solicitando.
