### ISSUE TITLE
Navision - Dato Extra 5, darle separación entre cada campo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1429]
Es una concatenación de una dirección, pero aparece todo junto y el cliente opina lo siguiente.
Creo que hay que darle espacio entre campo y campo que concatenamos.

<img width="701" alt="de5 navision" src="https://user-images.githubusercontent.com/2912775/45786401-eb31d400-bc35-11e8-86a1-37af90a1bd70.PNG">

**Comment by jccastillo0007** [comment]
en que tipo de documento?

**Comment by jccastillo0007** [comment]
como no especifica en que tipo de CFDI, revise el código, y solo encontre algo parecido para cuando se trata de facturas normales.... y lo que encontré es que si se esta dando espacio entre los diferentes campos :   
					new Field("shipto", item.getShipToCity() + " " + item.getShipToCountry() + " " + item.getShipToZipCode()));

Habrá que revisar la base de datos, para ver como lo tienen ellos capturado, chiaaaa

**Comment by RigoFlores** [comment]
ok, si es en facturas.
Si estás claro que así es como se está enviando, voy a revisar varias facturas a ver si en todas presenta el problema, o quizás simplemente así está capturado.

**Comment by RigoFlores** [comment]
ya revisé la bd, y al parecer lo tienen bien... no tendría porque mostrarse sin espacios.
Este es el cueri que yo ejecuto:

select [No_] 
      ,[Name] as "banco IP"
      ,[Country Code]
      ,[Address]
      ,[Address 2]
      ,[City]
      ,[County]
      ,[Post Code]
      ,[CCC No_]
      ,[Clabe]
      ,[SWIFT Code]
      ,[IBAN]
     
 from [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Bank Account] where No_=
(select  [Banco cobro] 
      FROM [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Sales Invoice Header]
      where [No_] in ( '18FVMX209' ))

**Comment by RigoFlores** [comment]
y el resultado viene todo bien, con espacios, y cuando son campos independientes, pues la aplicación debería separarlos....

**Comment by RigoFlores** [comment]
<img width="539" alt="navision espacios" src="https://user-images.githubusercontent.com/2912775/45975330-931a1980-c009-11e8-8314-f4c06389ae68.PNG">

**Comment by RigoFlores** [comment]
por lo que al parecer, si tenemos un problema de nuestra parte.
