### ISSUE TITLE
Conector estandar, conector Navision y Escritorio, formatear el valor de baseIVA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1430]
Formatear la variable de baseIVA a nivel producto, ya que no aparece separada por , cuando son miles.
En general, los valores de impuesto, formatearlos con seperador de miles

<img width="237" alt="de6 navision" src="https://user-images.githubusercontent.com/2912775/45786685-34ceee80-bc37-11e8-9530-7742aa8c1140.PNG">

**Comment by jccastillo0007** [comment]
fixed, pero no lo he instalado en Navision
