### ISSUE TITLE
Nomina - cuando no incluye deducción de ISR, no incluir parámetro TotalImpuestosRetenidos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1431]
Yo creo que con el cambio que subiste, le pegamos a este otro tema.
**Cuando las deducciones NO INCLUYEN ISR, no se debe incluir este parámetro**:

Incorrecto:
   <nomina12:Deducciones TotalImpuestosRetenidos="0.0" TotalOtrasDeducciones="24.94">

Correcto
<nomina12:Deducciones TotalOtrasDeducciones="24.94">

**Comment by jccastillo0007** [comment]
no ma,,, era un pinche if... por cierto solo se daba el caso en web, en standalone todo debe estar bien
