### ISSUE TITLE
Condominios - Ingresos - Consultas editar SP (pagada)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1432]
Solo se puede generar la factura (CFDI) de una SP, siempre y cuando la SP NO ESTÉ PAGADA.
Si la SP ya estuviera Pagada, tendrían que borrar el pago, y volverlo a capturar.
Entonces al momento de capturar el pago de la SP, entonces ahí es donde se podría generar el CFDI.

Lo que sucedió, es que pagué una SP (la 8) y luego al consultar y editar, si me permitió generar la factura y le asigno el folio SP9. En ese momento, ya teníamos 2 documentos asociados al mismo concepto (cuota de mantenimiento), uno pagado la SP, y otro pendiente de pago la factura con folio SP9.

**Comment by jccastillo0007** [comment]
ya esta validando si esta pagada la SP, si es así, manda mensaje y no permite la edición
