### ISSUE TITLE
nomina Web - se están incluyendo parámetros que no aplican

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1433]
Todo se está yendo por finkok, porque facturehoy está rechazando.
Ya ví la spec, y creo que tienen razón los de fhoy.
Urge corregir, nos cuesta y no estamos cancelando por finkok.

Te mandé un correo con el detalle del issue.

**Comment by RigoFlores** [comment]
Estimado cliente  el problema que arroja es debido a que se esta declarando el atributo "TotalSeparacionIndemnizacion", el cual no debe existir, ya que solo se debe declarar cuando existen percepciones con TipoPercepcion 022 ó 023 ó 025.

Lo anterior se puede ver en la página 54, a partir la quinta línea donde se describe el elemento "TipoPercepcion" del siguiente documento:

http://omawww.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/Complementoscfdi/nomina12.pdf


Lo mismo aplica para el atributo TotalJubilacionPensionRetiro, el cual tampoco debe existir, esa validacion, se puede encontrar en la misma parte que la validación anterior, pero a partir de la octava línea del elemento "TipoPercepcion".

**Comment by jccastillo0007** [comment]
pude reproducir y corregir el problema.

Lo probé en PRU, y si funcionó.

Lo subí  a PRO, pero no se como probarlo
