### ISSUE TITLE
Web Pagos - Cuando un cliente tiene nombres alternos, no muestra o incluye la cuenta bancaria correspondiente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1434]
Un cliente que tiene varios nombres alternos.
Cada nombre alterno tiene sus propios números de cuenta.
Cada nombre alterno tiene un número de cliente.

Cuando estás capturando el documento de pago, eliges el RFC y el número de cliente, ahí es donde el sistema debe saber cuáles cuentas bancarias debe presentar al momento de capturar el pago.
Ahora mismo no muestra ninguna cuenta bancaria, cuando ya elegiste el RFC y el número de cliente.

Ahora mismo tenemos un problema con optibelt, te enviaré un correo para detallarlo

**Comment by RigoFlores** [comment]
lo puedes reproducir con el RFC FOPR, en ambiente de pruebas
tiene 1 nombre alterno, y no muestra datos de cuenta, ni de matriz, ni de nombre alterno, aunque ambos tienen capturada la cuenta

**Comment by jccastillo0007** [comment]
esto lo puedo validar con este cliente de facturat :   TCM970625MB1  ?

**Comment by jccastillo0007** [comment]
actualmente si muestra un número de cuenta, que es el de la cuenta matriz... supongo que te refieres a que si elijen el nombre alterno, debe mostrar el número de cuenta del nombre alterno....

Hay que redactar bien los requerimientos, luego por eso nos lleva varios días tan solo entender lo que se requiere

**Comment by jccastillo0007** [comment]
![image](https://user-images.githubusercontent.com/2245679/46249141-0c3eb580-c3ea-11e8-9451-c030e37e7813.png)

**Comment by RigoFlores** [comment]
Tienes razón, hay que redactar bien los issues.
El escenario es que un mismo RFC receptor, tiene varios nombres alternos, y en el caso específico de Optibelt, le llaman números de cliente. Esto sucederá con cualquier otro cliente nuestro que ocupe el RFC genérico, y que le asigne varios nombres alternos (para condominios será muy común, pero para RFC extranjero en las empresas, también lo será)
Cada número de cliente, tiene sus propias cuentas bancarias.

Cuando se captura el pago, en algún momento se elige el RFC + número de cliente. Con ello ya se tiene identificado de cuál nombre alterno se trata.
Enseguida cuando capturan el CFDI, debe mostrar la cuenta correspondiente a ese nombre alterno.
Al menos cuando intenté reproducirlo en pruebas, no presentaba ninguna cuenta, aunque cada nombre alterno si tenía definida una. Eso me dice, que no en todo caso se presenta dicho problema.

Y la otra cosa y mas importante, es que no envía los datos de cuenta bancaria, al documento de pago, ni en el PDF ni en el XML

**Comment by RigoFlores** [comment]
No se corrigió, al menos en pruebas sigue igual.

**Comment by jccastillo0007** [comment]
ya esta en PRU, ahorita lo voy a subir a PRO
