### ISSUE TITLE
Cuentas x Cobrar - pagos parciales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1435]
Tenemos un escenario que ocuparemos a la de ya, y que no se me había ocurrido validar, ni que se fuera a presentar.

Antes que existiera el documento de pago, podíamos llevar pagos parciales, de hecho podemos.
Una factura, puede tener asociados varios pagos parciales (PA). Y cuando generas la cartera por cliente ahí aparecen, los n pagos registrados a una misma factura.
Hasta ahí todo bien.

Ahora lo que se ocupa, es que si una factura recibió algún pago parcial antes del CFDI de pago, pues se registra. Pero si ya tiene por ejemplo cargado 1er pago parcial sin CFDI de pago, y ahora van a registrar un segundo pago, pero ya con documento de pago, entonces el número de parcialidad debería respetarse y lo está reportando como 1.

En otras palabras, si una factura tiene 2 pagos parciales previos al REP, y le realizan un tercer pago parcial pero ya con REP, en el contenido del REP se debe reflejar que se trata de la parcialidad número 3.
Hoy en día lo reporta como la primera parcialidad. 

Lo ocupamos para ya....

**Comment by jccastillo0007** [comment]
Esta es la condición que tenía antes

if (paymentWay.compareToIgnoreCase("PPD") == 0) {
	relatedDocuemnts.append("1"); // numero de parcialidad
} else {
        relatedDocuemnts.append("");
}

es decir que solo manda 1 cuando el metodo de pago es PPD, y estamos hablando del método de pago del cfdi relacionado, osea de la factura que están pagando

Lo que se pide en este ticket es sobreescribir esa funcionalidad cierto ?

**Comment by jccastillo0007** [comment]
listo
