### ISSUE TITLE
Creo que se movió algo en pruebas. Pagos con RFC con nombre alterno.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1436]
Desde el menú de CxC, ingresar cobro.
Cuando vas a consultar las facturas, eliges el RFC y enseguida el número de cliente.
Lo acabo de hacer en pro, con la cuenta de optibelt, eligiendo el RFC AME00, y trabaja bien.

En pruebas si repites el proceso con la cuenta TCM. 
Eliges la factura para el RFC FOPR, y luego eliges algún número de cliente.
En ese momento el RFC que elegiste, desaparece. No sé que tanto afecte que esa parte esté distinta en pru que en pro.

**Comment by jccastillo0007** [comment]
Fixed
