### ISSUE TITLE
Escritorio y Web - En tipos de relación, agregar 2 tipos nuevos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1437]
Hay que agregar los 2 últimos tanto en la pantalla de facturación, como en la pantalla de pagos, como en la pantalla de nómina. 
Ahorita urge mas en Pagos Web.
Por cierto en la pantalla de nómina individual, aparece el ícono para elegir CFDI's relacionados, pero no aparece el combo para elegir el tipo de relación.

c_TipoRelacion        Descripción
01   Nota de crédito de los documentos relacionados
02   Nota de débito de los documentos relacionados
03   Devolución de mercancía sobre facturas o traslados previos
04   Sustitución de los CFDI previos
05   Traslados de mercancías facturados previamente
06   Factura generada por los traslados previos
07   CFDI por aplicación de anticipo 
08   Factura generada por pagos en parcialidades 
09   Factura generada por pagos diferidos

**Comment by jccastillo0007** [comment]
done
