### ISSUE TITLE
Escritorio Pagos - no incluye el schema location de pagos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1438]
Según yo, está faltando reportar esto, que en web si lo hace, pero en conector no.

xsi:schemaLocation="http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos10.xsd"

te mandaré un correo con ambos XML; uno generado en conector y otro en web

**Comment by jccastillo0007** [comment]
solo que no estes usando la última versión, o que la última versión que subi no tenga el cambio que ya había hecho...

Ahorita voy a subir otra versión... yo hice CFDi de pagos y si incluye el schema location
