### ISSUE TITLE
PAGOS web y conector - subir el namespace del pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1439]
Pues ya se puso complicado el asunto... te envié un correo, pero básicamente comenta femsa que es incorrecto el namespace a nivel de nodo de complemento.
Fhoy dice que puede ir arriba o abajo **(aunque originalmente dijo que tenía que ir abajo, ahora se retractó)**, entonces para que no haya pedo, pues hay que subirlo.

<img width="477" alt="namespace1" src="https://user-images.githubusercontent.com/2912775/46562391-81fec180-c8c1-11e8-916b-33830b4276d7.png">

**Comment by RigoFlores** [comment]
**PIDEN QUITARLO DE AQUÍ Y SUBIRLO...**

<img width="394" alt="namespace2" src="https://user-images.githubusercontent.com/2912775/46562410-917e0a80-c8c1-11e8-8d70-23c7aba0fc22.png">

**Comment by jccastillo0007** [comment]
listo desde conector, con la versión de hoy en la noche

**Comment by jccastillo0007** [comment]
al parecer si funciono también en PRO, checale

**Comment by RigoFlores** [comment]
pero ya quedó en web o no?

**Comment by RigoFlores** [comment]
no hay versión del 07 de octubre. Lo mas nuevo es del 03

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
pues quedó abajo, pero voy a esperar la respuesta de fhoy.
me parece que tienen un desmadre con este tema
