### ISSUE TITLE
LOS MENSAJES DE ERROR EN WEB, SON INCONSISTENTES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#144]
COMO EJEMPLO UN ERROR EN EL RFC DEL RECEPTOR, LO ENVÍA COMO 'ERROR EN EL PAC'.
ESTOS DETALLES TAN SIMPLES SON MUY COSTOSOS, PORQUE EN LUGAR QUE EL MENSAJE LE INDIQUE DIRECTAMENTE AL CLIENTE QUE HAY UN ERROR EN EL RFC DEL RECEPTOR, NOS LLAMAN, NOS PONEMOS A INVESTIGAR HASTA ENCONTRARLE.
ALGO QUE TOMARÍA 1 MINUTO EN IDENTIFICAR, NOS PODRÍA LLEVAR UNA HORA O MAS EN ATENDER.

**Comment by jccastillo0007** [comment]
este tema quedo resuelto con el desmadre que se armó desde aquel martes negro....

Si ubicas otros errores inconsistentes, hay que levantar otra ficha y con la información detallada para poder reproducirlo.
