### ISSUE TITLE
Pantalla de Facturas y Pantalla de Pagos - CFDI's relacionados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1440]
Cuando se elige algún tipo de relación, hoy tenemos que elegir a partir de una consulta los CFDI's relacionados.
Necesitamos agregar una caja de texto alterna, pera que se pueda capturar directamente el o los UUIDs de los CFDI's relacionados.
Esto se deriva, para hacer compatible todo el tema de pagos, con facturas CFDI v3.2

**Comment by RigoFlores** [comment]
Por cierto, esto lo solicité en su momento, hace muchos meses cuando implementamos lo de los CFDI's relacionados, pero pues lo rechazaste o me bateaste o algo así.

**Comment by RigoFlores** [comment]
hay que aguantar este issue

**Comment by RigoFlores** [comment]
Jeje, pedí que se aguantara este issue, pero en todo caso, haría falta en la pantalla de la factura, y lo agregaste en la pantalla de pagos.

**Comment by jccastillo0007** [comment]
done en PRU

**Comment by RigoFlores** [comment]
Validado en pru.
Cuando llegue a pro, lo cierro.

**Comment by RigoFlores** [comment]
Por cierto, es posible que podamos cobrar este cambio, por ello había pedido que se aguantara.
Entonces, yo creo que el posteo a pro, debe aguantar de este issue.
