### ISSUE TITLE
Actualizar listado de formas de pago - web y escritorio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1441]
El pinche SAT sigue sacando parches.
Para la pantalla de facturación y pagos, actualizar las formas de pago.
Aplica para WEB y escritorio, pero por lo pronto para WEB urgiría.
LE ESTÁ FALTANDO LA FORMA 31

c_FormaPago | Descripción
-- | --
01 | Efectivo
02 | Cheque   nominativo
03 | Transferencia   electrónica de fondos
04 | Tarjeta   de crédito
05 | Monedero   electrónico
06 | Dinero   electrónico
08 | Vales   de despensa
12 | Dación   en pago
13 | Pago   por subrogación
14 | Pago   por consignación
15 | Condonación
17 | Compensación
23 | Novación
24 | Confusión
25 | Remisión   de deuda
26 | Prescripción   o caducidad
27 | A   satisfacción del acreedor
28 | Tarjeta   de débito
29 | Tarjeta   de servicios
30 | Aplicación   de anticipos
**31 | Intermediario   pagos**
99 | Por   definir

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
negativo, la forma es 31, en lugar de 33.
Los asteriscos, los pone github porque quería resaltar en negritas, no porque sean parte de la descripción

**Comment by jccastillo0007** [comment]
done
