### ISSUE TITLE
Incrementar número de decimales tipoCambioDR calculado en pagos cuando va de MXN a USD

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1442]
Estamos recibiendo varios rechazos, ya que el tipo de cambio se está reportando a 3 decimales, pero si le hacen falta hasta 6 decimales, para que el cálculo que hace coincida y no marque error.

Así como está ahora, resulta que el importepagado al aplicar el tipo de cambio (esto es la sumatoria de los importes pagados en la o las facturas), es mayor al monto pagado, es decir el que se captura al inicio.
Eso no está permitido, y marca error.

Nos hace faltan reportar a 6 decimales el tipoCambioDR

**Comment by jccastillo0007** [comment]
en standalone, solo se reporta lo que se recibe

**Comment by RigoFlores** [comment]
Sigue igual. 
En pru hice la factura fe31, por 232 USD y el pago en MXN es de 4,373.57

y sigue marcando el error


CRP206 : La suma de los valores registrados en el campo ImpPagado de los apartados DoctoRelacionado no es menor o igual que el valor del campo Monto. (3)

**Comment by RigoFlores** [comment]
si, en escritorio se reporta lo recibido. Siempre se me olvida.

**Comment by jccastillo0007** [comment]
listo, a 6 decimales...

**Comment by RigoFlores** [comment]
ok, la conclusión es que fhoy y finkok, aplican distintos criterios.
En el caso de pagos, nos conviene ir por fhoy, ya que es mas 'suave' con las reglas.
Habría que buscar cuál es el deber ser... pero si, hay una fórmula para calcular los límites superior e inferior, en este tipo de situaciones.
