### ISSUE TITLE
CxC-Consulta de cobros muy tardado para pagos que involucran varias facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1443]
Cuando un cobro involucra varias facturas, se tarda en exceso para presentar el resultado.

Por ejemplo, si consultas en produccion, emisor OME111223UN4 y la referencia 18911, verás que se tarda yo creo que bastante para el reporte que genera... y conforme el pago abarca mas facturas, se hace mucho mas tardado.

A mi me parece que algún índice por ahí está haciendo falta

**Comment by jccastillo0007** [comment]
si, puede ser, y ese puede ser el causante de los problemas del tomcat

**Comment by RigoFlores** [comment]
ouch!!!

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
cómo lo corregiste?
