### ISSUE TITLE
Conector - Consultas Exportar - con el tipo de factura = Documento de Pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1444]
Se requeire en excel, cuando le den exportar con el filtro de documento de pagos, Incluir la información siguiente 

Respecto a la factura o facturas pagadas:
a) UUID
b) Serie
c) Folio
d) Importe Pagado
e) Saldo anterior
f) Saldo insoluto
g) número de parcialidad
h) Método de pago
i) MonedaDR

Respecto al general de Pago
j) fecha de pago
k) monto pagado
l) forma de pago
m) cuenta origen
n) cuenta destino
o) numero de operacion
p)tipoCambioP
q) monedaP

Se entendería que los campos que son generales, cuando se trate de un pago a varias facturas, se pudieran repetir dentro del excel, o los reportas como consideres..

**Comment by jccastillo0007** [comment]
Porque dice Conector ?

**Comment by RigoFlores** [comment]
Lo que pasa es que viene de Figueacero el requisito, pero realmente tendría que decir Escritorio.
Amén que en escritorio, la única manera de generar pagos es vía el conector.

**Comment by jccastillo0007** [comment]
Estaba preparando el reporte y ups... no se estaba guardando la info del complemento de pago y de las facturas pagadas....
Ya hice cambios para que lo guarde como debe ser, pero sería apenas apartir de la nueva versión de standalone...

**Comment by jccastillo0007** [comment]
Si lo anterior causa mucho problema, se podria tratar de leer los datos desde la cadena original, esa si la tenemos guardada... pero sería un poco engorroso, cómo ves ?

**Comment by RigoFlores** [comment]
Podríamos importarla de los XML que ya hayan generado, previo a la liberación?

**Comment by jccastillo0007** [comment]
listo, checale

**Comment by jccastillo0007** [comment]
aunque ahorita el rfc aco.. procesa los archivos con formato levicom

**Comment by RigoFlores** [comment]
Si quedó... peeero eliminaste toda información (excepto la fecha) propia del CFDI de pago. 

Entonces faltan las columnas al inicio de:
Serie
Folio
UUID

Todo esto pero del propio CFDI de Pago

**Comment by jccastillo0007** [comment]
chiaaaa hay que definir bien los campos, al principio pusiste lo que se requería puntualmente

done
