### ISSUE TITLE
Liberar versión de escritorio con cancelación fhoy y finkok

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1445]
Necesitamos de una vez ver que onda con la cancelación.
Podemos empezar con fhoy, pero seguramente se requerirán los 2.

**Comment by jccastillo0007** [comment]
el fin de semana quiero dedicarme a la cancelacion en escritorio... de preferencia no hay que tener tickets urgentes

**Comment by RigoFlores** [comment]
Ya empezó a presionar Figueacero con este tema.
Necesito esta versión de escritorio, para pruebas, con cancelación.

OJO. Debemos incrementar los status de una factura. Cuando una factura está en proceso, deberá poderse volver a consultar, para validar cómo está su estatus.
Vigente
Cancelada
En proceso  (cuando se espera la respuesta del receptor)
No cancelable
Rechazada

**Comment by jccastillo0007** [comment]
Para poder terminar con esto... necesito poder timbrar en PRU con el RFC LAN.. que es el que acepta FactureHoy...  a menos que quieras que probemos en PRO... y eso solo funcionaría si facturehoy ya tiene la cancelación en PRO

**Comment by RigoFlores** [comment]
Estamos a 3 días de este asunto, y no lo tenemos listo.
Casi puedo apostar que no estará en producción antes del 31, ya que no sería legal.
Hace 2 meses levanté la mano con esto, y a 3 días no lo tenemos.
No sé que haga falta de facturehoy, pero necesitamos marcarles directamente, si no no atienden.
Dime que pido, pregunto o exijo para desatorar este tema.

**Comment by jccastillo0007** [comment]
yo creo que lo van a postponer... pero como quiera deja veo si ya puedo probar...

en producción es más fácil pero chacarron

**Comment by jccastillo0007** [comment]
listo, empecemos con pruebas... no esta tan dificil y creo que no se requieren mas estatus

Hasta eso que ahora si FactureHoy hizo un buen trabajo.. se simplifica mucho...

aunque perdemos el tema de cancelacion de cfdi expirados

**Comment by RigoFlores** [comment]
Con la versión de hoy, generé por la mañana una factura a un RFC receptor cualquiera, y al querer cancelarla me marca error de cancelación con el PAC.
No sé, si dentro de los amarres del ambiente de pruebas, solo trabaja con ciertos RFC's receptores.
Ocupé la nueva llave, el nuevo sello y nada.

**Comment by RigoFlores** [comment]
De hecho, ya viendo la consola, arroja lo siguiente:

2018-10-31 13:02:45,527 DEBUG [AWT-EventQueue-0] (CFDiHelper.java:77) - FacturaT
i will get this : SAT_FOLIO value : f3b09b8c-0768-46b5-96d9-62fa8b1ddcf6
2018-10-31 13:02:46,564  INFO [AWT-EventQueue-0] (CFDiWSClient.java:103) - Factu
raTi ack : com.facturati.ws.binding.jaxb.Ack@1f54031[code=24,description=CA24 -
Orden de cancelacion del CFDI previamente registrada]
2018-10-31 13:02:46,566 DEBUG [AWT-EventQueue-0] (FacturaTiCreator.java:493) - C
ancel process result : 24 description : CA24 - Orden de cancelacion del CFDI pre
viamente registrada

El mensaje en el log, es que la petición está previamente registrada
El mensaje en pantalla, es Error de Cancelación con el PAC
El mensaje visual, es que no cambia el status, y con ello, para el usuario simplemente falló la cancelación.

De ahí la importancia de los status y los mensajes correctos.

En este caso, no sé que hay que hacer para consultar cuando ya se haya cancelado dicha factura.

**Comment by jccastillo0007** [comment]
Ok, tendremos tres estatus

activa
cancelada
en proceso de cancelación... (que nombre le podemos poner a este estatus)

en el caso de tu prueba...   cuando el error de facturehoy sea el 24 ( CA24 - Orden de cancelacion del CFDI previamente registrada), el estatus se va a poner como cancelada, pues eso es lo que significa

**Comment by jccastillo0007** [comment]
no se porque te mando error de cancelación con el pac... debio mostrar el mensaje de facture hoy

**Comment by jccastillo0007** [comment]
ya hice varias pruebas y si jala... voy a subir esto a producción..

**Comment by jccastillo0007** [comment]
bueno, lo subi pero no hice deploy... me espero a que ma;ana platiquemos en la ma;ana

**Comment by RigoFlores** [comment]
Se le debe avisar al usuario cuando haya sido rechazada.
Ahora cuál es la diferencia de enviada previamente a quiero conocer el status?

Entonces nosotros debemos llevar el control del flujo internamente?
Incluso, hasta conocer si tiene documentos relacionados?

**Comment by jccastillo0007** [comment]
done.... hay otros tickets para cada escenario de cancelaci[on... pero además necesito que facture hoy ya responda bien con los escenarios de cancelación con aprobación

**Comment by RigoFlores** [comment]
no ví ninguna versión nueva de escritorio en el drotbots..
