### ISSUE TITLE
Implementar Complemento de Comercio Exterior para Optibelt

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1447]
Ya te mandé toda la información.
Hay que sacarlo rápido, ya que espero que nos hagan el pedido de ajustes para etsa.

**Comment by jccastillo0007** [comment]
oye, se puede que mas bien implementen el layout ya implementado para CCE desde conector

CCEH=|2|A1|0|||FOB|0|Observaciones|19.0|3500
CCEE=|1ER RETORNO UNIVERSITARIO|1|65B|1269|||011|QUE|MEX|76269
CCEP=|
CCER=889010357|WATERVIEW DRIVE|2968||||||MI|USA|48309
CCED=||||||||||||
CCEM={ART-001|84145101|1|06|3500|3500}

**Comment by jccastillo0007** [comment]
oye ya me confundi... vi el código y ya tenemos implementado el cce para optibelt...

**Comment by jccastillo0007** [comment]
de hecho si procesa el archivo que me enviaste... chiaaaaa

me marca error en los totales pero puede ser por el archivo... checale con la versión de hoy... y con el RFC ACO... te va a procesar el layout de Optibelt.

**Comment by jccastillo0007** [comment]
pues ya hice varias pruebas y parece que si esta listo

**Comment by RigoFlores** [comment]
Este es un requerimiento viejo, pero que no se había confirmado, porque estaban investigando lo de la fracción arancelaria.
Te mandé un correo, donde anexé 3 archivos, 1 lo procesa, pero los otros 2 no.
Aquí está faltando agregar el "-1", "-2", "-3", etc, en el identificador del producto. Pareciera que pensaste que con lo que ya estaba codificado, pero el word que envié por correo vienen todos los requisitos puntuales.

**Comment by jccastillo0007** [comment]
que mas requisitos puntuales faltan ?

**Comment by RigoFlores** [comment]
Se nota que no leiste la spec que mandé... aquí los voy a pegar del documento word que te envié por correo:

REQUISITO 1: MONEDA
Campo H1.31 Cuando la moneda de la factura sea MXN, debemos tomar en cuenta el campo de tipo de cambio. Por ejemplo “19.20”. Si la factura se emitió en USD, entonces el tipo de cambio ya debe incluirse ahora mismo. Si la factura es en MXN o EUR, entonces se debe indicar el tipo de cambio respecto al dólar americano.
 
En el header del CCE se reporta el tipo de cambio, pero los importes a nivel header y detalle, van en USD. Por lo tanto hay que hacer una conversión de la moneda de la factura a USD, ocupando el tipo de cambio reportado en el campo anterior."

Si la moneda es en MXN o EUR, se toma el tipo de cambio y se convierten los totales a dólares, esto es solo para el complemento, o también para la factura como tal. (LA CONVERSIÓN ES SOLO PARA EL COMPLEMENTO).
Si la moneda esta en USD, todo se reporta normal. (EXACTO, QUE ES ASÍ COMO FUNCIONA AHORA MISMO, TANTO PARA WEB COMO PARA EL CONECTOR)
 

REQUISITO 1.1:  TIPO DE CAMBIO
EL TIPO DE CAMBIO SE TOMARÁ DE LO QUE SE CAPTURE EN EL ESCRITORIO. TAMPOCO OPTIBELT ME HIZO LA OBSERVACIÓN.

REQUISITO 2: ID PARA LOS PRODUCTOS DENTRO DEL CCE
Campo D.2 – Indicar un identificador del producto que debe ser distinto para cada producto dentro de la factura. Este identificador es interno a optibelt. Ahora mismo no lo incluye

Esto ya se incluye, porque dices que no? SEGÚN ELLOS Y YO NO. DEBE CORRESPONDER AL CAMPO ID DENTRO DEL XML ESTÁNDAR, SECCIÓN CONCEPTO. Y DEBE SER DISTINTO PARA CADA PRODUCTO. SI LO ESTÁS TOMANDO DE AHÍ?. BUSQUÉ EN EL XML DE ELLOS Y NO SE INCLUYE EL ID EN EL XML (YA QUE ES OPCIONAL).

REQUISITO 3: CLAVE DE ESTADO DEL RECEPTOR
2. Aun no se interpreta la clave del estado del receptor. (OK, AUNQUE SI NO SE IMPLEMENTA, MARCARÁ ERROR).
REQUISITO 4: CLAVE DE PAÍS DEL RECEPTOR
Pais del receptor se esta considerando, mexico, usa, estados unidos, canada, sin importar mayúsculas y minúsculas. (POR LO PRONTO HABLARON DE ESTADOS UNIDOS, PERO NO SE DESCARTA PARA NADA, ALGÚN OTRO PAÍS). NO PODRÍAMOS HACER UN CATÁLOGO DE TEXTO, PARA IR AGREGANDO SOLO LOS PAÍSES QUE SE VAYAN OCUPANDO?

REQUISITO 5: FRACCIÓN ARANCELARIA Y UNIDAD ADUANA
Unidad y fracción arancelaria estan fijos. (EN LO QUE ENTREGAN LA INFORMACIÓN, ES CORRECTO)

 
REQUISITO 6: HEADER DEL CCE
 
CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="EXW" Subdivision="0" TipoCambioUSD="se indica abajo" TipoOperacion="2" TotalUSD="se calcula si la factura es en moneda distinta a USD, tomando en cuenta el tipo de cambio" Version="1.1"
 
 
 
REQUISITO 7: DOMICILIO DEL EMISOR DENTRO DEL CCE
 
                <cce11:Domicilio Calle="5 DE FEBRERO" CodigoPostal="76120" Estado="QUE" Municipio="014" NumeroExterior="1702-C" NumeroInterior="BODEGA 5" Pais="MEX"/>            </cce11:Emisor>
Del emisor lo puedes tomar de la llave, y hacer el mapeo que corresponda a las claves de estado y país. Otra opción es iniciar con los datos fijos

REQUISITO 8: DOMICILIO DEL RECEPTOR DENTRO DEL CCE
            <cce11:Receptor>
                <cce11:Domicilio Calle="565 E. Fullerton Avenue" CodigoPostal="60188" Estado="IL" Pais="USA"/>            </cce11:Receptor>

Del receptor y destinatario lo tomas del H4 y H5 respectivamente, de acuerdo a lo indicado abajo. OJO hay que hacer el mapeo que corresponda a las claves de estado y país. 

REQUISITO 9 DOMICILIO DEL DESTINATARIO DENTRO DEL CCE
SE DEBE TOMAR DEL CAMPO H5





REQUISITO 10: NÚMERO DE REGISTRO DE IDENTIFICACIÓN TRIBUTARIA
Campo H4.4 Capturar el Número de Registro de Identificación Tributaria.

REQUISITO 11: CONOCER CUÁNDO SE DEBE INCLUIR EL CCE EN LA FACTURA
Campo H4.4 Cuando este campo contenga un dato (normalmente no lo tiene), Factura-T lo interpretará como indicativo que se requiere incluir el CCE.
 
 
 
REQUISITO 11: DETALLE DEL PRODUCTO 
 
                <cce11:Mercancia CantidadAduana="1.0" FraccionArancelaria="73269099" NoIdentificacion="D2" UnidadAduana="01" ValorDolares="9688.32" ValorUnitarioAduana="9688.32"/>            </cce11:Mercancias>        </cce11:ComercioExterior>
 
La fracción arancelaria y su unidad, se obtendrán de una manera similar a como se obtiene ahora la clave de producto SAT en las facturas de Optibelt. Esto es nos pasarán un Excel donde se establezcan las reglas para hacer el mapeo de descripción de producto vs fracción arancelaria/unidad.
Cantidad Aduana.- es la cantidad en el detalle del XML estándar
ValorDólares . es el importe convertido a USD para el caso que la factura sea en MXN o cualquier otra distinta a USD.
ValorUnitarioAduana. es el precio unitario del XML estándar convertido a USD para el caso que la factura sea en MXN o cualquier otra distinta a USD.
 
Todo lo que tiene que ver con convertir de MXN a USD, es lo que no tenemos en web. Por lo pronto no lo han pedido.
 
 
 
 
A nivel del receptor dentro del CCE:
Campo H4.13 Tomar la clave del país de acuerdo al catálogo del SAT. 
Campo H4.12 Tomar la clave del estado de acuerdo al catálogo del SAT. 
Campo H4.5 De aquí se toma la calle la calle 
Campo H4.14 De aquí se toma el código postal
Campo H4.4 Capturar el Número de Registro de Identificación Tributaria.
Campo H4.4 Cuando este campo contenga un dato (normalmente no lo tiene), Factura-T lo interpretará como indicativo que se requiere incluir el CCE.
 
 
A nivel detalle:
Campo D.2 – Indicar un identificador del producto que debe ser distinto para cada producto dentro de la factura. Este identificador es interno a optibelt. Ahora mismo no lo incluye

**Comment by jccastillo0007** [comment]
no manches... nada mas dime que falta

**Comment by RigoFlores** [comment]
chiaaaa, de que sirve que haga todo un desglose de requisitos...??
