### ISSUE TITLE
Optibelt - CCE no agrega el sufijo al ID del producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1449]
El ID del producto, tanto para el XML estándar, como para el CCE debe ser el campo D.2
Ahora mismo, el ClaveProdServ= a nivel estándar, quién sabe de donde lo toma
A nivel detalle, en el CCE, este parámetro NoIdentificacion="4014486259605", si lo asigna del D.2, pero no le agrega el "guión consecutivo".

Hay que agregar el "-1", "-2", "-3", etc, al identificador del producto, dependiendo del número de producto que se trate

**Comment by jccastillo0007** [comment]
Esto ya lo hace bien :   
El ID del producto, tanto para el XML estándar, como para el CCE debe ser el campo D.2

Para la clave prod serv, lo toma de un catálogo definido por ellos, dependiendo el nombre del producto 
	CP("OPTIBELT CP","27112132"),
	ALPHA_FLEX("OPTIBELT ALPHA FLEX","26111802"),
	ALPHA_LINEAR_f("OPTIBELT ALPHA LINEAR _ F","26111802"),
	ALPHA_LINEAR("OPTIBELT ALPHA LINEAR (Steel)","26111802"),
	ALPHA_POWER("OPTIBELT ALPHA POWER","26111802"),
	ALPHA_POWER_S("OPTIBELT ALPHA POWER Sleeves","26111802"),
	ALPHA_TORQUE("OPTIBELT ALPHA TORQUE","26111802"),
	ALPHA_TORQUE_Sleeves("OPTIBELT ALPHA TORQUE Sleeves","26111802"),
	HTD("OPTIBELT HTD","26111802"),
	HTD_LINEAR("OPTIBELT HTD LINEAR (Glass fibre)","26111802"),
	HTD_LINEAR_S("OPTIBELT HTD LINEAR (Steel)","26111802"),
	OMEGA("OPTIBELT OMEGA","26111802"),
	OMEGA_FAN("OPTIBELT OMEGA FAN POWER","26111802"),
	OMEGA_HL("OPTIBELT OMEGA HL","26111802"),
	OMEGA_HP_1("OPTIBELT OMEGA HP","26111802"),
	OMEGA_HP_2("OPTIBELT OMEGA HP LINEAR (Glass fibre)","26111802"),
	OMEGA_LINEAR("OPTIBELT OMEGA LINEAR (Glass fibre)","26111802"),
	OMEGA_Sleeves("OPTIBELT OMEGA Sleeves","26111802"),
	STD("OPTIBELT STD","26111802"),
	STD_HL("OPTIBELT STD HL","26111802"),
	STD_HP("OPTIBELT STD HP","26111802"),
	STD_LINEAR("OPTIBELT STD LINEAR (Glass fibre)","26111802"),
	ZR("OPTIBELT ZR","26111802"),
	ZR_("OPTIBELT ZR / Omega","26111802"),
	ZR_LINEAR("OPTIBELT ZR LINEAR (Glass fibre)","26111802"),
	ZR_LINEAR_S("OPTIBELT ZR LINEAR (Steel)","26111802"),
	ZRK("OPTIBELT ZRK","26111802"),
	ZRK_SET("OPTIBELT ZRK_SET","26111802"),
	BLUE_POWER("OPTIBELT BLUE POWER","26111801"),
	DK("OPTIBELT DK","26111801"),
	KB("OPTIBELT KB","26111801"),
	KB_BLUE("OPTIBELT KB BLUE POWER","26111801"),
	KB_RED("OPTIBELT KB RED POWER 3","26111801"),
	MARATHON("OPTIBELT MARATHON 1","26111801"),
	RB("OPTIBELT RB","26111801"),
	RBK("OPTIBELT RBK","26111801"),
	RBK_D("OPTIBELT RBK D","26111801"),
	RBP("OPTIBELT RBP","26111801"),
	RED_POWER("OPTIBELT RED POWER 3","26111801"),
	RED_POWER_3("OPTIBELT RED POWER 3 CLASSIC","26111801"),
	SK("OPTIBELT SK","26111801"),
	SUPER_("OPTIBELT SUPER KBX_POWER","26111801"),
	SUPER_TX("OPTIBELT SUPER TX","26111801"),
	SUPER_X_POWER("OPTIBELT SUPER X_POWER","26111801"),
	TRUCK_POWER("OPTIBELT TRUCK POWER","26111801"),
	TRUCK_POWER_KB("OPTIBELT TRUCK POWER KB","26111801"),
	TRUCK_POWER_KBX("OPTIBELT TRUCK POWER KBX","26111801"),
	TRUCK_POWER_MARATHON("OPTIBELT TRUCK POWER MARATHON 2","26111801"),
	TRUCK_POWER_RBK("OPTIBELT TRUCK POWER RBK","26111801"),
	VARIO_POWER("OPTIBELT VARIO POWER","26111801"),
	VB("OPTIBELT VB","26111801"),
	WR("OPTIBELT WR","26111801"),
	OPTIMAX_HF("OPTIBELT OPTIMAX HF","26111804"),
	KK("OPTIBELT KK","31151904"),
	KKA("OPTIBELT KKA","31151904"),
	KKS("OPTIBELT KKS","31151904"),
	KKW("OPTIBELT KKW","31151904"),
	OPTIMAT_PKR("OPTIBELT OPTIMAT PKR","31151904"),
	RR("OPTIBELT RR","26111803"),
	RR_PLUS("OPTIBELT RR PLUS","26111803"),
	FS_Taper_Buchse("OPTIBELT FS Taper_Buchse","26111531"),
	QD_Bushings("OPTIBELT QD Bushings","26111531"),
	TB("OPTIBELT TB with inch bores","26111531"),
	TB_Bores("OPTIBELT TB with metric bores","26111531"),
	KS("OPTIBELT KS","26111806"),
	LD_Bushings("OPTIBELT LD Bushings","26111806"),
	LD_Sheaves("OPTIBELT LD Sheaves","26111806"),
	MS("OPTIBELT MS","26111806"),
	QD_Sheaves("OPTIBELT QD Sheaves","26111806"),
	RBS("OPTIBELT RBS","26111806"),
	TN("OPTIBELT TN","26111806"),
	ZRS("OPTIBELT ZRS","26111806"),
	ZRW("OPTIBELT ZRW","26111806"),
	LB("OPTIBELT LB","26111500"),
	OPTIMAT_DK("OPTIBELT OPTIMAT DK","26111500"),
	OPTIMAT_FK("OPTIBELT OPTIMAT FK","26111500"),
	OPTIMAT_OE("OPTIBELT OPTIMAT OE","26111500"),
	SERVICE_TOOLS("OPTIBELT SERVICE TOOLS","26111500"),
	Nuevos("OPTIBELT Nuevos","26111500");

**Comment by RigoFlores** [comment]
Si, la clave de producto está bien. Esa es la clave producto SAT.
De lo que se trata este issue, es que tanto el id producto a nivel XML estándar, como el ID producto a nivel CCE, sean tomados del D.2+"-numero de renglón".

Ahora mismo solo lo hace para el nodo del complemento, pero no para el XML estándar.
Entonces, el SAT pide que sean iguales ambos y no lo procesa.

NoIdentificacion="4014486259605"     (XML ESTÁNDAR)

NoIdentificacion="4014486259605-1"  (NODO DEL COMPLEMENTO CE)

**Comment by RigoFlores** [comment]
El ID producto debe ser igual en el XML estándar como en el nodo de CCE.
De lo contrario marca error.

**Comment by jccastillo0007** [comment]
chiaaaa, tu que entiendes con este requerimiento

"A nivel detalle, en el CCE, este parámetro NoIdentificacion="4014486259605", si lo asigna del D.2, pero no le agrega el "guión consecutivo"."


done.

**Comment by RigoFlores** [comment]
jaja... chiaaaaa
