### ISSUE TITLE
Navision - Colocar el XML y PDF de pago en otra carpeta. Solo los pagos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1450]
Facturas y Notas de Crédito no se mueven.
Hoy tenemos dentro de la carpeta del MesAño, una carpeta XML y PDF.
Dentro de la carpetaMesAño, creamos una que se llame REP, y debajo de ella pueden ir los XML y PDF de pagos, o si quieres en carpetas independientes, una para XML y otra para PDF

**Comment by jccastillo0007** [comment]
Done... pero no lo probe... este cambio les debe costar unos 10k por tipo de archivo no?

**Comment by RigoFlores** [comment]
Tiene 2 problemas:

a) No está creando la carpeta en automático. Debe crearla así como en las facturas.
b) Cuando timbra el REP, no lo presenta en pantalla, porque busca la ruta estándar.

Quizás el (b) no sea problema, pero el (a) si que lo es.
Pls envíame todos los XML que se timbraron y que no se almacenaron en el servidor, porque 'no encontraba la ruta'. Algo así será su nombre: 18PAMX17_ATE9606175K7_19oct2018

**Comment by RigoFlores** [comment]
c) Tercer problema detectado... generaron una nota de crédito, y la colocó en la carpeta REP.

Recuerda que las facturas y notas de crédito, no iban a cambiar su ubicación.
Unicamente el documento de pago (REP).

Aquí el log de todo el desmadrito....
[FacturaT.log](https://github.com/jccastillo0007/eFacturaT/files/2497143/FacturaT.log)

**Comment by jccastillo0007** [comment]
crap, es cierto, no valide el tipo de CFDi

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Pues la única forma de probar, es llevándolo a producción.
En cuanto se valide que las notas, facturas se almacenan donde antes, y pagos en la carpeta REP, entonces cerraré este issue...
