### ISSUE TITLE
Web Etiqueta incorrecta en el complemento de instituciones educativas privadas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1451]
Tenemos una observación del un cliente que ocupa el Complemento educativo. Nuevamente la etiqueta está causando problemas. Yo se que has dicho que no importa y te creo, pero los puristas indican que debe llevar la etiqueta tal cual lo indica el estándar del SAT, y todos los namespaces, deberían ir arriba ya de cajón.
Etiqueta erronea: "ns2", etiqueta correcta "iedu".

Ahora mismo se genera así:

            <cfdi:ComplementoConcepto>
                <ns2:instEducativas xmlns:ns2="http://www.sat.gob.mx/iedu" CURP="GUBN130114HMCRRCA4" autRVOE="09050221 15-08-2005" nivelEducativo="Preescolar" nombreAlumno="NICOLAS GUERRERO BARRANCO" rfcPago="GUSM710528BYA" version="1.0"/>
            </cfdi:ComplementoConcepto>

Y lo que debería ser es:

            <cfdi:ComplementoConcepto>
                <iedu:instEducativas xmlns:ns2="http://www.sat.gob.mx/iedu" CURP="GUBN130114HMCRRCA4" autRVOE="09050221 15-08-2005" nivelEducativo="Preescolar" nombreAlumno="NICOLAS GUERRERO BARRANCO" rfcPago="GUSM710528BYA" version="1.0"/>
            </cfdi:ComplementoConcepto>

**Comment by jccastillo0007** [comment]
ya hice los cambios, implementé la misma estrategia que pagos... pero no lo he probado, tienes como probarlo ?

**Comment by RigoFlores** [comment]
Si está en producción no jaló, ya que hoy emitieron facturas y salió igual.
Si es en pru, confirma cuál RFC tiene asociado el complemento educativo.

**Comment by RigoFlores** [comment]
En pruebas, con ACO, tampoco jaló.
Ahí ni siquiera incluyó el complemento de instituciones educativas.

Así es que funciona esto:

Esta es la configuración para trabajar el complemento educativo en línea.

Keygenerator:
Deben tener el plugin de addendas, esto es en el keygen y 
Deben ser emisores del plugin de complemento educación.... esto es en código... 

Configuración

Deben tener datos extas a nivel general con los RVOE, donde el nombre del RVOE debe ser exactamente escrito como lo pide el SAT, esto es Preescolar, Primara, Secundaria, Bachillerato 

Catálogo de productos:
Nombre del producto o servicio, será el nombre del alumno
Debe tener el dato extra 1 igual al CURP
Dato extra 2 el nivel educativo

Facturación:
Las facturas deben tener un solo producto
En la información complementaria, se debe incluir al inicio la palabra colegiatura o inscripción
Antes de timbrar, abrir la ventana de datos extra y darle aceptar.

**Comment by jccastillo0007** [comment]
solo esta en PRU... ya le puse al rfc ACO el complemento de educación pero no agregó el complemento.. algo mas falta

**Comment by RigoFlores** [comment]
así es, porque incluso no envió la información del complemento al PDF, como información complementaria, que es como debe suceder.
Porque no checas en producción como está?

Ese checklist que publiqué, fue algo que te pregunté en su momento para documentar como se debe emitir este complemento.

**Comment by RigoFlores** [comment]
Diario me preguntan...

**Comment by jccastillo0007** [comment]
Listo en PRU, con el RFC ACO

**Comment by RigoFlores** [comment]
ya lo validé, lo podemos llevar a producción hoy?

**Comment by jccastillo0007** [comment]
yeap
