### ISSUE TITLE
Optibelt CCE - unidad en el nodo complemento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1452]
Platicamos que en el nodo complemento, a nivel detalle, la unidad siempre será "01", excepto cuando el campo D2, tenga los siguientes valores, en cuyo caso la unidad será "06":

4014486286175
4014486286045
4014486286113
4014486286120
4014486286106
4014486286069
4014486286076
4014486286083
4014486286090

**Comment by jccastillo0007** [comment]
done
