### ISSUE TITLE
Optibelt - CCE cuando la moneda de la factura sea MXN, se debe convertir a USD para el nodo complemento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1453]
Si la moneda del archivo de texto es MXN, entonces para propósitos del complemento, se debe convertir algunos datos, tomando en cuenta el TC (que se lee de facturat).

a nivel header del complemento:

TotalUSD="1400.00"

a nivel de detalle, se deben convertir estos datos  (precio unitario e importe, respectivamente:
ValorUnitarioAduana="350.00"
ValorDolares="700.00"

Creo que ya son todos los requerimientos del complemento

**Comment by jccastillo0007** [comment]
ok, pero seguro nos vamos a meter en problemas de redondeo

**Comment by jccastillo0007** [comment]
revisando el código, esto ya lo hace.
