### ISSUE TITLE
WEB - Editar Fecha de Vencimiento para las facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1454]
Este lo pidió optibelt, y ya se hacía antes, pero ahora ya no.
Cuando le das consultas en web, y una vez desplegada las facturas, le puedes dar editar.
Ahí se abre una pantalla actualmente. Creo que el único parámetro que debería editarse es precisamente la fecha de vencimiento.
Cuando la cambias y le das aceptar (que ahora mismo ya no tiene ese botón), entonces recalcula su status  y lo asigna a esa factura en particular.

**Comment by jccastillo0007** [comment]
de hecho no aparece la fecha de vencimiento

El botón de salvar, sale solo si se trata de un documento que se pueda editar... se supone que una factura ya generada no se puede modficiar, salvo el dato que estas solicitando

**Comment by RigoFlores** [comment]
Exacto, eso ya funcionaba anteriormente, no sé en que momento se inhibió.
Pero está bien, quizás en lugar de presentar tantos datos, solo sería capturar la fecha de vencimiento.

**Comment by jccastillo0007** [comment]
negativo, y no es tan trivial, pues al mostrar dicho botón podrían volver a facturar e incluso cancelar, debo agregar varias validaciones

**Comment by RigoFlores** [comment]
Lo que yo estoy comentando, es que cuando le den editar a una factura timbrada, entonces se abra una ventana donde únicamente aparecerá el dato de fecha de vencimiento. Ahí es donde la podrían editar, y con el botón de guardar solo se actualiza dicha fecha y a la vez se 'recalcula' su status.
Los demás datos estarían de sobra.

**Comment by jccastillo0007** [comment]
ya casi tengo este req. ya muestra los campos y el botón de salvar... pero tengo un error raro al momento de actualizar la fecha, espero que mañan ya este listo

**Comment by jccastillo0007** [comment]
listo en pru

**Comment by RigoFlores** [comment]
Si cambia la fecha, pero comentaba que al momento del cambio debe actualizar su estatus de CxC.
Si antes del cambio aparecía como vencida, pero al cambiar la fecha, se cambia a vigente, debe actualizar dicho status.

En Pru hoy le cambié la fecha de vencimiento con el rfc TCM a la factura 796; le actualicé a 15 de octubre, y su status no cambió. Debió indicar vencida.

Es la única manera de probar, ya que supongo que en pru no está corriendo el cron que actualiza el status de las facturas, y todas estás vigentes aún cuando la fecha de vencimiento ya pasó.

**Comment by jccastillo0007** [comment]
cierto... se me paso eso

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Validé en producción, y no le cambió la vigencia.... o solo quedó en pru?

**Comment by RigoFlores** [comment]
ya validé en pru, y tampoco quedó.
No le cambia el status, y eso es junto con el cambio de fecha, integran el requerimiento completo.
La idea es que, si a una factura que estaba vencida, le ajustan la fecha y pasa a vigente, entonces en el reporte de Cuentas x Cobrar, ahí se debe reflejar el cambio de status.

**Comment by jccastillo0007** [comment]
yo lo cheque validando la misma factura en el reporte de cxc y si cambia el valor de vigente a vencida o viceversa, dependiendo la fecha capturada... tons... 

dame tus datos de prueba

**Comment by RigoFlores** [comment]
si, estaba capturando la fecha de abajo.
No es tan intuitivo, pero bueno, ya quedó.
