### ISSUE TITLE
Cuando una factura se genera de manera automática (programada) no se le asigna fecha de vencimiento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1456]
Y por lo tanto no tiene CxCStatus asociado, y por lo tanto no se le puede generar el REP....

**Comment by jccastillo0007** [comment]
en realidad el cxc status se asigna directamente en vigente, cuando se genera la factura...

y también la fecha de expiración


listo en PRU

**Comment by RigoFlores** [comment]
pues en las automáticas no estaba sucediendo eso.
Por eso te pedí el cueri para actualizar el status... no estaba actualizado.

Tu comentas que eso no sucede, o que eso ya está resuelto???

**Comment by RigoFlores** [comment]
lo validé en pru, y si le asoció fecha de vencimiento.
No sé si fue fix, o si ya se subió a pro... pero si hay que subirlo a pro
