### ISSUE TITLE
Web Ventas-Registrar CFDI externo, rfc receptor con & no lo puede importar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1457]
Tenemos un caso con un cliente del grupo etsa, donde el rfc del receptor, incluye la secuencia de escape para el ampersand:

cfdi:Receptor Rfc="S&amp;T980427D19"

te lo mandé por correo.
No pueden subir el XML, ya que al validarlo con el sat, marca error.

**Comment by RigoFlores** [comment]
ELLOS LO ESTÁN GENERANDO BIEN... ASÍ ESTÁ LA SPEC DEL SAT

**Comment by RigoFlores** [comment]
Ya me están presionando con esto... 
Por cierto la spec del sat dice:

El documento XML debe expresarse bajo el estándar de codificación UTF-8 y en particular se deben usar secuencias de escape cuando en los valores especificados dentro de los atributos del archivo exista alguno de los siguientes casos especiales.
 En el caso del & se debe usar la secuencia &amp;
 En el caso del “ se debe usar la secuencia &quot;
 En el caso del < se debe usar la secuencia &lt;
 En el caso del > se debe usar la secuencia &gt;
 En el caso del ‘ se debe usar la secuencia &apos;
Ejemplo:
Para representar nombre=“Juan & José & “Niño”” se usa nombre=”Juan &amp; José &amp; &quot;Niño&quot;”

**Comment by jccastillo0007** [comment]
una buena noticia y una mala

la buena, es que no tiene nada que ver el tema del &, eso se resuelve bien

la mala, es que no estaba mandando los datos correctos del SelloSAT, que es el último dato de lo que se manda a validar

Ya esta el fix, lo voy a subir a PRU y PRO

**Comment by RigoFlores** [comment]
lo voy a cerrar, pedí que me confirmaran, pero no me confirmaron.
Asumo que se corrigió
