### ISSUE TITLE
Si un usuario no tiene el plugin de admin, no abre la ventana de CFDI's relacionados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1458]
Aún cuando el usuario si tiene acceso a facturación. Entonces si debería abrir la ventana de CFDI's relacionados, pero no lo hace.
Solo la abre si tiene el plugin admin.

Anexo el cueri específico. En este caso, que es el del cliente que reportó en PRO
El usuario GLS131106EQ4  si abre la ventana de CFDI's relacionado. Pero por ejemplo el usuario yesi que es quién factura, no puede relacionar un CFDI, porque no abre la ventana.

mysql> select * from Users where client_id in (select id from Client where rfc = 'GLS131106EQ4');
+------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------+--------------+-----------+--------------------------------+
| id   | password     | role                                                                                                                                          | userId       | client_id | emails                         |
+------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------+--------------+-----------+--------------------------------+
| 1151 | GLS131106EQ4 | ["ADMIN","CATALOGS_MENU","VENTAS_MENU","COMPRAS_MENU","RETENTIONS_MENU","CxC_MENU","ADMIN_MENU","EMAIL_VENTAS","EMAIL_COMPRAS","NO_CANCELAR"] | GLS131106EQ4 |     22977 |                                |
| 1258 | cc148        | ["CATALOGS_MENU","VENTAS_MENU","COMPRAS_MENU","USER"]                                                                                         | Raul         |     22977 | ["raul@tingsystems.com"]       |
| 1266 | ye999        | ["CATALOGS_MENU","VENTAS_MENU","COMPRAS_MENU","RETENTIONS_MENU","ADMIN_MENU","EMAIL_VENTAS","EMAIL_COMPRAS","USER","CxC_MENU"]                | yesi         |     22977 | ["facturas@thegloboworld.com"] |
| 1470 | 452178       | ["CATALOGS_MENU","VENTAS_MENU","USER"]                                                                                                        | Pedro        |     22977 |                                |
+------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------+--------------+-----------+--------------------------------+

**Comment by jccastillo0007** [comment]
listo..

**Comment by RigoFlores** [comment]
no tengo forma de validarlo en pru... lo subirás a pro?
