### ISSUE TITLE
CxC - Cartera de Cliente vigente + vencida, sin filtro adicional, al exportar marca internal error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1459]
Con la cuenta de la tia en producción, genero la cartera vencida (vigente + vencida) sin ningún filtro adicional , y al exportar al excel, marca internal error

**Comment by jccastillo0007** [comment]
fixed en pru

**Comment by jccastillo0007** [comment]
si todo esta bien, me avisas y lo libero a pro en chinga loca

**Comment by RigoFlores** [comment]
Probé en pruebas, con la cuenta ACO, sin ningún filtro mas que vigente + vencida, y siguió marcando el mismo error.

**Comment by jccastillo0007** [comment]
lo acabo de probar

**Comment by jccastillo0007** [comment]
yyyyy ya se fue a pro

**Comment by RigoFlores** [comment]
en producción, con la cuenta de la tia.
Menú CxC - Cartera de Cliente
Filtro: vigente + vencida (únicamente este filtro).

Una vez que despliega el resultado en pantalla, le das exportar para generar el excel y te sigue mandando internal error.

**Comment by RigoFlores** [comment]
en pruebas ya no marcó el error....

**Comment by jccastillo0007** [comment]
ya debe estar en pro también.

**Comment by RigoFlores** [comment]
Pues no k... deberías de ejecutar en producción con los datos que te dí....

**Comment by jccastillo0007** [comment]
tons no he subido el release... hoy lo subo y pruebo con los datos que enviaste
