### ISSUE TITLE
Cancelación escritorio - una factura cancelada previamente no le cambia el status

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1460]
Cuando existe una factura que ha sido cancelada previamente, si te lo indica como respuesta.
Lo que no hace es cambiar el status

**Comment by jccastillo0007** [comment]
hay dos posibles respuestas para este caso..
1. que ya esta cancelada
2 que sigue en proceso de cancelación.

Si es el caso 1, pues no le cambia el estatus porque ya esta cancelada
Si es el caso 2, si le debe cambiar el estatus a En PRoceso de Cancelación

En el ambiente de pruebas de facturehoy, nunca pude reproducir el caso 2

**Comment by RigoFlores** [comment]
Es el caso que la factura aparece activa.
Pero realmente ya está cancelada (tu la cancelaste en tus pruebas, es la que te mandé)
Y cuando yo solicito la cancelación, el mensaje es correcto, es decir ya está cancelada, pero debe cambiar el status de activa a cancelada en la pantalla.

**Comment by jccastillo0007** [comment]
Esto ya esta funcionando, aunque no lo he podido reproducir porque  mis facturas son canceladas de forma automática, pero el error que regresaba facture hoy ya esta arreglado..

**Comment by RigoFlores** [comment]
No tengo un caso en escritorio, pero en web si y no le cambia el status.
El mensaje que regresa el pac es:

CA24 - Orden de cancelacion del CFDI previamente registrada.38481532 Estatus : En espera de aceptación

pero no cambia el status
Lo puedes checar con la cuenta de la tia, receptor fopr68, folio PAGO10, es una factura.
esa factura la generé y cancelé en escritorio.

**Comment by RigoFlores** [comment]
Sigue igual este punto.... no le cambia el status...

**Comment by jccastillo0007** [comment]
ya vi, a que te refieres con que no cambia el estatus ?

**Comment by RigoFlores** [comment]
si una factura... por ejemplo, fue cancelada en el SAT... en la plataforma o en el escritorio, aparecerá como vigente...
Entonces al intentar cancelarla desde facturat, le indicará al usuario que ya estaba previamente cancelada, y en ese momento le cambia el status dentro del sistema.

**Comment by jccastillo0007** [comment]
el status al que te refieres, es el que aparece en las consultas de cartera por cliente ? 

O donde estas viendo ese status... 

Ya entendí a lo que te refieres y si, tienes razón, solo quiero estar seguro en que pantalla ves ese status

**Comment by jccastillo0007** [comment]
y me parece que este issue esta duplicado con el 1477

**Comment by RigoFlores** [comment]
Estamos hablando de escritorio
Si filtro por vigentes o canceladas... una factura que ya la detectó como cancelada en el SAT  (cuando intentas cancelarla nuevamente), entonces tendría que pasar de vigente a cancelada... 
Cuando aplicas el filtro de vigente ya no aparece y el filtro de cancelada si.

A eso me refiero con cambiar el status. Que sería bueno que se mostrara de alguna manera en pantalla

**Comment by jccastillo0007** [comment]
hoy hice una prueba y si me funciono, puedes checar, esto en PRU y con la última vresión de standalone... el cambio que hice fue en web
