### ISSUE TITLE
Cancelación Escritorio PRO - no está cancelando en pro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1462]
Hice varias facturas por ahí de las 5:15 en adelante.
Hace una media hora las cancelé todas, y lo hizo en chinga... como si no estuviera realmente haciéndolo. Solo decía que si las canceló con éxito.

Las verifiqué en el SAT y todas ellas las marca como vigentes.
Algo raro, es que aparecieron en chinga en el SAT. Supongo que es por la hora.
Pero bueno, no está cancelando. Pareciera que se quedó apuntando a pruebas o no se, pero no se tarda en la cancelación, porque lo hace en chinga

**Comment by jccastillo0007** [comment]
fixed
