### ISSUE TITLE
Producción Web/ Escritorio - Cancelación por plazo vencido

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1465]
La cancelación de CFDI por plazo vencido sucede cuando el receptor, después de 72 horas no realiza la
autorización o rechazo de la cancelación.

**Comment by jccastillo0007** [comment]
Hay que probar este escenario, todo depende de facture hoy, no hay nada que cambiar en código.

**Comment by RigoFlores** [comment]
ok, lo probaré también....
