### ISSUE TITLE
Producción Escritorio/Web Cancelación con UUID relacionado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1466]
Escenario:
Se emite la factura A.  (factura "hijo")
Se emite la factura o nota de crédito B, y se define una relación a la factura A. (factura "padre")

La factura A, no puede ser cancelada.
La factura B, si podría ser cancelada.

En caso que se cancele la factura B, hasta entonces ya se podría cancelar la factura A.

**Comment by jccastillo0007** [comment]
hay que probar este escenario, todo depende del estatus que regrese facture hoy, yo no tengo nada que hacer en realidad.
