### ISSUE TITLE
Ventas - Registrar CFDi Externo, darle ByPass a la validación del SAT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1467]
Antes de registrar un XML externo, la plataforma checa que esté registrado y vigente en el SAT.
Supongo yo con algún WS del SAT, o algo similar.
Bueno, pues ese servicio ya no jala. Está marcando error y no pueden continuar.

Hay que actualizarlo con los nuevos servicios del sat, para obtener el status de una factura.

**Comment by RigoFlores** [comment]
En caso que no esté disponible, podemos darle bypass por un par de días.
Ahora mismo nos pueden esperar para el lunes a primera hora

**Comment by jccastillo0007** [comment]
sabes cual es el nuevo servicio del sat ?

por bypass te refieres a no validar ante el sat ?

**Comment by jccastillo0007** [comment]
ya no va a validar ante el sat, hasta nuevo aviso

**Comment by RigoFlores** [comment]
Asi es, no validaremos ante el SAT, hasta el nuevo aviso.
Pero solo confirma que efectivamente se ocupaba el servicio del SAT, e indícame pls como se llama para buscar su sustituto.

**Comment by RigoFlores** [comment]
falta que me digas el nombre del servicio para validar el status.... con ese nombre empiezo a rastrear el nuevo servicio

**Comment by jccastillo0007** [comment]
si te refieres al web service que mandaba llamar para validar la factura

https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc?WSDL

Pero ya no esta disponible... cuando scanneas un cfdi te manda a un portal con esta url

https://verificacfdi.facturaelectronica.sat.gob.mx/

Pero no es un web service

**Comment by RigoFlores** [comment]
oye, con los servicios de fhoy, podemos checar si un cfdi timbrado por cualquier pac, está registrado ya en el portal del SAT???

**Comment by RigoFlores** [comment]
para regresar la validación en la parte de subir facturas externas o de proveedores
