### ISSUE TITLE
Conector Optibelt - Soportar CFDI relacionado en NC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1468]
Se requiere poder agregar CFDI relacionados en una NC.
Para ello, en el archivo de texto, en el campo H1.6, cuando inicie con:
CFDI=uuid1;uuid2,...uuidn (espacio)

Se deberá entender que se trata de CFDI relacionados con el tipo de relación:

"01.Nota de crédito de los documentos relacionados"

**Comment by jccastillo0007** [comment]
El tipo relación esta fijo en "01.Nota de crédito de los documentos relacionados", siempre que es una nota de crédito

**Comment by jccastillo0007** [comment]
listo con la versión de hoy... lo puedes probar con el rfc ACO...

**Comment by RigoFlores** [comment]
No procesa con esta cadena inicial:
H1||183002949||CFDI=B7092567-5E97-4A63-85F3-F7E9B3B252B5 20181026|G602988 284300|20181026|Pago en una sola exhibicion/Cuenta 99G1|25 dias fecha de factura|O|Nota de Credito||||||||||2018||||284300|16|||||Cheque|MXN||||||||||||||P||||||||

dime donde o como quedo, o mándame el archivo por email.

**Comment by jccastillo0007** [comment]
mandame el txt que corresponda a una nota de crédito, yo tengo solo facturas

**Comment by jccastillo0007** [comment]
Listo.
1. El campo CFDI=.... se habia definido en la posicion H1.6 pero se esta enviando en la posición H1.5
2. El prefijo CFDI se esperaba como CFDi

Ya corregidos ambos detalles, ya lo procesa.

**Comment by RigoFlores** [comment]
Tienes razón, no era H1.6... me equivoqué. Ud Disculpe.
Ya quedó.
