### ISSUE TITLE
CFDI de Pagos - lo genera sin información del complemento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1469]
Al parecer cuando sucede esto, es cuando el banco del cliente es banamex.
Esto es que no eligen ningún banco del listado, y según yo por ello marca error, ya que en la BD el nombre del banco aparece como nulo, y eso pues no se que provoque.
Mandaré por correo XML para que lo cheques

**Comment by RigoFlores** [comment]
Traté de reproducirlo, pero no lo logré.
Necesitas basarte en el XML timbrado que te envié por correo, para que le des traza en el catalina, es un error grave.

**Comment by jccastillo0007** [comment]
a este no le entendi, pero parece ser lo mismo que el issue 1470

**Comment by RigoFlores** [comment]
El asunto es que genera un CFDI de pago, pero no le incluye el complemento de pago, todo completito lo omite.
Ya te había comentado antes, pero pensaba que era una mala captura.
Hoy me pasó a mí, y no supe ni porqué. 
Todo estuvo bien capturado.

**Comment by jccastillo0007** [comment]
ya vi que paso con el xml que me enviaste, no se seleccionó una moneda de pago

paymentWay=03.TRANSFERENCIA ELECTRONICA DE FONDOS,currency=<null>,currencyRate=<null>

Tal vez por error no se hizo... 

Le voy a poner una validación y en todo caso que marque ese error

**Comment by RigoFlores** [comment]
oye, la validación de la moneda está bien, solo que debemos aplicarla SOLO EN CASO QUE SE DEFINA GENERAR EL CFDI DE PAGO.
Es decir, si solo vamos a registrar el pago, no debería exigir la moneda y si lo hace.

Aplicar esta validación, solo en caso que SI SE VAYA A GENERAR EL CFDI DE PAGO.

**Comment by jccastillo0007** [comment]
fixed en pru

**Comment by RigoFlores** [comment]
ok en pru, cuándo lo llevamos a pro???
