### ISSUE TITLE
AGREGAR CANCELACIÓN VIA EL CONECTOR MULTIRFC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#147]
IDENTIFICAR LOS ARCHIVOS DE CANCELACIÓN PARA CADA UNO DE LOS RFC'S

**Comment by jccastillo0007** [comment]
Done version 7.2.3.

La solución fue agregar el rfc emisor y rfc receptor al nombre del archivo de cancelación
