### ISSUE TITLE
CFDI Pagos - No incluye los datos del banco origen

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1470]
Al parecer todo está bien capturado, pero al momento de generar el Pago, no incluye los datos del banco origen.
Te mandaré correo con la evidencia.

**Comment by RigoFlores** [comment]
PARA REPRODUCIRLO CON LA CUENTA DE OPTIBELT EN PRODUCCION:

fecha de pago 30 oct
monto pago: 17446.49
referencia: 19127

rfc receptor: GOMR6004274M8
numero de cliente: 179901
facturas pagadas: 181071080 y 181071124

forma: transferencia
moneda: mxn
cuenta origen: la única que aparece
cuenta destino: la única que aparece

**Comment by jccastillo0007** [comment]
el error parece ser que : 

El banco ingresado fue BANK SOURCE BANAMEX:002180700657284099

Pero esa cuenta no esta dada de alta en el catálogo de clientes de optibelt para el cliente : GOMR6004274M8 ya que dicho cliente tiene estos datos :  
BANAMEX , 0021800212366424412

La cuenta debe ser la misma

**Comment by RigoFlores** [comment]
lo cuál es aún peor, ya que el sistema está tergiversando la información?
eso es lo que debo entender???
porque no lo reproduces y analizas bien

**Comment by jccastillo0007** [comment]
mas bien, actualiza la cuenta banamex, del cliente GOMR6004274M8, en el catálogo de clientes... y ponle el número de cuenta 002180700657284099

puedo hacerlo yo... 

Mas que tergiversando la información, además de que no se que significa tergiversando... el sistema lo que hace es valida que la cuenta capturada, corresponda a una cuenta ya previamente configurada en el catálogo de clientes

**Comment by jccastillo0007** [comment]
listo, hice algunos cambios en los números de cuenta, y si era eso... te voy a enviar los xml por email

Deje las cuentas tal como estaban...

Voy a revisar la validación para contemplar ese escenario

**Comment by jccastillo0007** [comment]
como quiera agregué una validación para checar si vuelve a pasar... lo malo es que ya no puedo probar con los mismos datos porque ya generé el cfdi de pago

**Comment by RigoFlores** [comment]
Bueno, yo generé varios pagos de ellos en mis pruebas, así que no debería tener problema.
Como quiera, voy a repetir los 2 pagos para asegurar que quedaron bien.

PD Significado de tergiversar
tr. Desfigurar o interpretar erróneamente palabras o sucesos:
no tergiverses mis palabras y no pongas en mi boca cosas que no he dicho.

lo que quise decir, es que estábamos mezclando, malinterpretando, chocolateando los datos de las cuentas cuando un cliente tiene nombres alternos... además de que no enviaba la info al pdf... chiaaaaaaa

**Comment by RigoFlores** [comment]
Apenas en primer pago que volví a capturar, se presentó el problema nuevamente

**Comment by jccastillo0007** [comment]
try again
