### ISSUE TITLE
Plataforma Web - DEJÓ DE ENVIAR POR EMAIL LOS PAGOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1471]
No sé, pero hoy estuve monitoreando y no los envía automáticamente al momento de la emisión.
Facturas si. 
Entonces es algo con los pagos

**Comment by jccastillo0007** [comment]
acabo de generar pagos en pru y pro y si envió el correo, de hecho te debió llegar a ti uno (el de producción)...

Hay que tener bien configurado las opciones de envío de correos al emisor y/o receptor, asi como que el cliente debe tener correos capturados , chiaaa

**Comment by RigoFlores** [comment]
Obviamente si tienen configurada la opción de envío automático.
Me pareció ver que un correo tenía un caracter chueco con ese cliente, ya que es un listado de correos.
Les pediré que revisen... yo creo que si un correo está mal escrito, no debería de dejar de enviar hacia el resto de destinatarios.
