### ISSUE TITLE
Cancelación - Si cancela facturas y notas de crédito. Pero pagos no

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1472]
No sé si para pagos se ocupa algo especial, pero manda errores.
No sé si es nuestro error o del PAC o del SAT, el hecho es que hay un error ahí.
Para reproducir el problema, con el pago 43 en producción, con la cuenta de la tia.
O con el usuario de optibelt, los pagos: 424, 425

Si se cancelan, no hay pedo, es la intención.

16 CA16 - Ocurrio una interrupción en el servicio del SAT, intente mas tarde Estatus : No Procesado

**Comment by jccastillo0007** [comment]
oye, ya te dieron alguna respuesta de este issue? ya no he visto emails

**Comment by RigoFlores** [comment]
YA EMPEZÓ A CANCELAR.
EL MENSAJE ES INCONSISTENTE, PERO VAMOS VIENDO QUE RESPONDEN.

**Comment by jccastillo0007** [comment]
Este issue debe ser arreglado por facture hoy

Ya quedo ?

**Comment by RigoFlores** [comment]
al parecer si
