### ISSUE TITLE
Agregar este RFC a los emisores de CCE - RECA8311198E2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1473]
Es lo único que se ocupa?
O un plugin adicional?

**Comment by RigoFlores** [comment]
YA VI, Y NO EXISTE EL PLUGIN DE COMERCIO EXTERIOR, PERO EN MI SUPER MANUAL DICE QUE SI LO LLEVA:

PARA CONFIGURAR UNA NUEVA CUENTA EN LA PLATAFORMA EN LÍNEA:

(la dirección del cliente es: MONTE ATLAS # 51 COLONIA LA LOMA, QUERETARO, QRO CP 76116)


1. La dirección del emisor (pais, cp, estado) deben ser acordes a los catálogos, la calle es de libre captura
2. El emisor (cliente facturat) debe tene el plugin de complemento CE
3. El emisor, debe estar dado de alta como emisor de complemento CE
4. El receptor, debe tener su dirección (pais, cp, estado) deben ser acordes a los catálogos, la calle es de libre captura
5. Debe tener configurado el archivo de xml que corresponde al complemento CE

**Comment by RigoFlores** [comment]
Digamos que lo mismo que tiene este RFC que emite el CCE: OTC131125BL4

**Comment by jccastillo0007** [comment]
listo
