### ISSUE TITLE
Escritorio - CONSULTAS - Exportar Reporte de Excel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1475]
Ya se quejaron algunos clientes.
Quieren que las facturas y notas de crédito le salgan juntas en el mismo reporte, como antes se hacía.
Ahora si no eligen tipo de CFDI no genera el reporte.

Entonces lo que podemos hacer, es que si no eligen tipo de CFDI, que incluya facturas y notas, así como antes.
Y solo en caso que elijan cfdi tipo pago, entonces que genere el excel solo con la informacion de pagos.

**Comment by jccastillo0007** [comment]
de hecho esa era la intención... pero había un bug... jojojo

**Comment by RigoFlores** [comment]
pues quedó igual que al principio.
Esto es, generé un reporte sin filtro de tipo de documento, e incluyó tanto facturas, notas de crédito y pagos.
Lo que se ocupa es, nuevamente:

Entonces lo que podemos hacer, es que si no eligen tipo de CFDI, que incluya facturas y notas, así como antes.
Y solo en caso que elijan cfdi tipo pago, entonces que genere el excel solo con la informacion de pagos.

**Comment by jccastillo0007** [comment]
chiaaaa

listo... checale
