### ISSUE TITLE
Pagos de grupo ETSA - no registra correctamente el método de pago del docto relacionado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1476]
Del cliente ETE790117358, con misma contraseña para la plataforma.
Para las facturas que suben por medio de Ventas - Registrar CFDI externo.
Cuando genera el CFDI de pago, no está reportando correctamente el método de pago a nivel del complemento de pago (en el detalle).
Ejemplo: PAGO342
si te das cuenta todos los reporta con método de pago PUE, siendo que en la factura original, es decir la que subieron con la opción de registrar cfdi externo, si contiene el método de pago PPD.
Recuerdo que anteriormente, estabas guardando chueca la información de las facturas.
Se me hace que le reinyectamos el defecto... chiaaaaa

               <pago10:DoctoRelacionado Folio="16416" IdDocumento="437F646E-A8AF-4B88-8578-0D81FA014621" ImpPagado="2444.28" ImpSaldoAnt="2444.28" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PUE" MonedaDR="USD" NumParcialidad="1"/>
                <pago10:DoctoRelacionado Folio="16472" IdDocumento="03E92126-2451-429A-A215-6694419FDB3F" ImpPagado="2444.28" ImpSaldoAnt="2444.28" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PUE" MonedaDR="USD" NumParcialidad="1"/>
                <pago10:DoctoRelacionado Folio="16557" IdDocumento="6AC6A8DD-A983-4C12-818E-5308EF41B1AC" ImpPagado="2444.28" ImpSaldoAnt="2444.28" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PUE" MonedaDR="USD" NumParcialidad="1"/>
                <pago10:DoctoRelacionado Folio="16676" IdDocumento="B5071F25-9147-457A-A3C3-7EF196FC4146" ImpPagado="1629.52" ImpSaldoAnt="1629.52" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PUE" MonedaDR="USD" NumParcialidad="1"/>
                <pago10:DoctoRelacionado Folio="16734" IdDocumento="0B37CB4A-2A30-4FAB-8337-37B4A8CD14B8" ImpPagado="2444.28" ImpSaldoAnt="2444.28" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PUE" MonedaDR="USD" NumParcialidad="1"/>

**Comment by jccastillo0007** [comment]
fixed... el tema es el puto cambio de método de pago por forma de pago... hice varias validaciones

**Comment by RigoFlores** [comment]
oyes y lo de subir el XML, cuando se trata de un zip?
Quedó también?

**Comment by jccastillo0007** [comment]
noup, eso es otro ticket...
