### ISSUE TITLE
Cancelación- genera acuse e indica que se envió al sat, pero la factura es no cancelabel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1477]
CON LA CUENTA DE LA TIA EN PRODUCCIÓN.
FACTURA F4486, AL CANCELARLA ENVÍA EL MENSAJE DE:

Cancelación enviada al SAT satisfactoriamente Estatus :

(NO ENTIENDO LA RAZÓN DEL STATUS VACÍO)

Y LE GENERA UN ACUSE.   
DE HECHO, EN LA PLATAFORMA LE CAMBIA EL STATUS A CANCELADA.
LUEGO VOY AL SAT, Y CHECO SU STATUS Y ME INDICA QUE ES NO CANCELABLE.
TENEMOS ALGO CHUECO AHÍ.

<img width="652" alt="no cancelable" src="https://user-images.githubusercontent.com/2912775/48796557-95c18400-ecc5-11e8-94cf-bb81f01548e9.PNG">

**Comment by jccastillo0007** [comment]
El mensaje que se envió petición al sat, lo manda facture hoy... sin embargo, como no ponía nada en estatus esa era la confusión, ahora si va a poner un mensaje de que no es cancelable

**Comment by jccastillo0007** [comment]
listo... lo malo es que pues ya genero un acuse .... y pues ya no lo puedo quitar, a menos que lo haga a manita

**Comment by RigoFlores** [comment]
pues si podemos eliminar ese acuse y ponerla a vigente, para volver a darle que la cancele.
Y entonces, aquí es donde entraría el status no cancelable. 
O cómo se entera el usuario que esa factura es no cancelable???

El sat manejó 2 status. Vigente o Cancelada,  otro donde se indica no cancelable, cancelable con autorización, cancelada sin autorización, etc.

**Comment by RigoFlores** [comment]
Le volví a dar cancelar. No sé si sea correcto o nó. Si ya está totalmente seguro que está cancelado, debería indicar que ya ha sido cancelada.
Pero pensando en que no estamos validando eso, le dí cancelar nuevamente.
Ahora el mensaje es:

11 Cancelación enviada al SAT satisfactoriamente Estatus : No Cancelable Estado CFDi : Vigente

Lo cual es correcto. Peeeeero, si ya se validó ese status, entonces la factura debería convertirse en Vigente, y no... la mantiene con status de cancelada dentro de FT.

Hoy en día no tenemos columna de estado o status en la consulta.
La única manera que tenemos para identificar una factura cancelada, es que tiene un acuse asociado.
En este caso, que la aplicación ya se enteró que es vigente, no debería eliminar ese acuse también.

La otra es agregar la columna de status y estado para que a simple vista se pueda identificar si una factura está cancelada.

Como la beisbol???
