### ISSUE TITLE
Tener opción de Generar vista previa en documento de Pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1478]
Muchos clientes lo han pedido.
Yo lo pedí desde el inicio, pero fui bateado.
Ahora es la gente que mantiene a la tia, la que lo pide.

**Comment by jccastillo0007** [comment]
chiaaaa , 

bueno, ahora ya esta mucho mas estable, voy habilitar esta funcionalidad

**Comment by jccastillo0007** [comment]
listo en PRU

**Comment by RigoFlores** [comment]
si la genera bien... peeeeero cuando generas la vista previa, borra todo lo capturado.
Evidentemente, hay que mantenerlo para que puedan generar el documento de pago, una vez validado con la vista previa.

También ví que ya agregaste el default de la moneda. Con ello podrías quitar ya la validación que la moneda se incluya.

**Comment by jccastillo0007** [comment]
fixed en PRU

**Comment by RigoFlores** [comment]
HAY QUE LLEVARLO A PRO.
