### ISSUE TITLE
Registrar CFDI externos desde un zip, no sube los XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1479]
Solo los registra.
Creo que es bueno subirlos

**Comment by jccastillo0007** [comment]
después de hacer manita de puerco a las validaciones de esta funcionalidad... resulta que los archivos si se suben.. pero creo que se colocan en un folder erróneo

Probé con ACO ... con facturas que generé hoy... tons debo esperarme a mañana

**Comment by jccastillo0007** [comment]
ya lo reproduje, y si subió los XML... 
voy a necesitar que me consigas un zip de ellos para ver que pasa
