### ISSUE TITLE
IMPLEMENTAR LOS IMPUESTOS LOCALES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#148]
SE ENVIÓ LA SPEC DE IMPUESTOS LOCALES 'DEBER SER', DESDE HACE TIEMPO...

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
COMO SE OBTIENEN O ENVÍAN LOS DATOS AL PDF DE ACUERDO A LO SOLICITADO?
CANTIDAD    DESCRIPCION PRECIO UNITARIO IMPORTE
3   HOSPEDAJE HABITACIÓN SENCILLA   $1,200.00   $3,600.00 
10  MINUTOS LLAMADAS TELEFÓNICAS    $10.00      $100.00 

```
    SUBTOTAL     $3,700.00 
    IVA  $592.00 
    IMP HOSPEDAJE    $720.00 
    OTRO IMPUESTO    $18.00 
    TOTAL    $3,554.00 
```
