### ISSUE TITLE
Migrar ambiente de producción a Digital Ocean

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1480]
Los pagos mensuales siguen siendo muy altos en rackspace, y el dolar sigue subiendo.
Pagamos mas de servidor que de renta en la oficina.

**Comment by jccastillo0007** [comment]
a cabron.... es demasiado... ok, voy a trabajar en eso para ahorrar en ese sentido

**Comment by RigoFlores** [comment]
marcó error de PDF, al generar nómina. Debes colocar todos los templates de producción.
Tampoco pudo generar una factura a partir de una remisión

**Comment by RigoFlores** [comment]
Los acentos mayúsculas y minúsculas, eñes, &s se ven bien.

**Comment by jccastillo0007** [comment]
logré hacer una factura a partir de una remisión, y no encontré una remisión creada por ti... con que datos probaste?

Con que usuario provaste lo de nómina?

**Comment by RigoFlores** [comment]
Seguramente es el usuario. Yo entré con TCM970625MB1. Con ese usuario probé todo, ya que ACO no tiene sellos.
aquí lo que generé ayer, y ahí aparece la remisión que no me permitió timbrar.

<img width="640" alt="remision" src="https://user-images.githubusercontent.com/2912775/49882654-ad88b580-fdf6-11e8-97f2-033c34a2b4ad.PNG">

**Comment by RigoFlores** [comment]
Manda el mensaje de, pero si tiene clave de producto del SAT. De hecho solo hay 2 productos capturados

CFDI33142 : El campo ClaveProdServ, no contiene un valor del catálogo c_ClaveProdServ. (3)

**Comment by RigoFlores** [comment]
El tema de la remisión, tiene que ver cuando pasas de una cotización a una remisión, y si de ahí te quieres ir a una factura ya no lo hace. Supongo que eso debe estar en producción ahora mismo.
Cuando solo inicias con la remisión y luego la factura, si la hace bien.

Lo de nómina, según yo, es pasar los templates de producción

**Comment by jccastillo0007** [comment]
okas, checo lo de remisión y los templates de PRO, ahora mismo tiene lo de PRU

**Comment by jccastillo0007** [comment]
ya actualice los templates de PRO en PRU
ahorita checo lo de cotizacion - remision - factura

**Comment by RigoFlores** [comment]
En el nuevo server, con la cuenta TCM, y el único empleado que existe dado de alta en nómina, me sigue marcando el error:

Error en generador PDF - Jasper (101)

No es de jasper, o será otra cosa?

**Comment by jccastillo0007** [comment]
listo... faltaba el font Arial.ttf, ya lo instalé

**Comment by RigoFlores** [comment]
pues ahora está abajo, y no hay forma de probar

**Comment by jccastillo0007** [comment]
correcto, hacia falta el font Arial.ttf, ya lo subi.

Ya esta también el tema de crear remisión a partir de un pedido

**Comment by RigoFlores** [comment]
lo siento un poco lento... tiene las mismas características que producción actual?
Y eso que no tiene toda la carga de producción.

**Comment by jccastillo0007** [comment]
no inventes... esta super rápido...

**Comment by jccastillo0007** [comment]
cuando hacemos el switch, estaba pensando en la sig semana, pero antes de año nuevo la usan un buen... tons talvez valga la pena hacerlo el 1 o 2 de Enero... cómo ves?

Tengo dudas con el certificado, según yo si lo puedo migrar porque lo que se asegura es el dominio... pero no estoy 100% seguro

**Comment by RigoFlores** [comment]
La última semana del año, así como la primera del siguiente, el timbrado baja al 70%, de acuerdo a cifras del año pasado.
Podría ser cualquiera de las 2. Entre mas pronto, menos pagaremos en RackSpace (que pasaría si reducimos el servidor por estos días, así como de entrada?)

Por otro lado, es importante contar con tu disponibilidad de tiempo para checar el comportamiento, ese es otro factura para decidir cuándo será mas adecuado.

Finalmente, tenemos que asegurar el tema del certificado.

**Comment by jccastillo0007** [comment]
entonces voy a empezar el domingo 23 , y si voy a estar disponible para estar revisando y brincar en caso de que lago surja... la fecha de corte de rackspace creo que es 5 o 6 de cada mes, asi que estariamos en buen tiempo para ya no pagar en febrero
