### ISSUE TITLE
NO actualiza el status de una factura ya cancelada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1481]
Esto se levantó hace tiempo, y se resolvió; ahora nuevamente vuelve a aparecer.
Tengo varios casos, sobre todo con los clientes, y ya están presionando mucho con justa razón:

a) el sistema no les avisa que YA ESTÁ CANCELADA, entonces no saben ni que pedo.
b) el sistema no cambia el status a cancelada, ni genera el acuse (no mayor razón no saben que pedo)
c) el sistema envía un mensaje que solo confunde al cliente, pero que no le dice nada al cliente:

11 CA24 - Orden de cancelacion del CFDI previamente registrada.38481532 Estatus : En espera de aceptación

Tenemos un caso en casa, que se trata de la factura (ingreso) que generé en escritorio y que tiene el folio PAGO10, emitida el 05 de septiembre (esa se canceló el 08 de noviembre). Lo puedes consultar en web. 
Esa factura cuando la tratas de "recancelar," no le cambia el status y te muestra el mensaje arriba descrito. Al menos, el mensaje es consistente para web y escritorio.

Recordar que si una factura ya está cancelada, tenemos que cambiar su estatus y entregar el acuse correspondiente.
No será que antes de enviar a cancelar, se tiene de alguna manera que revisar su status????

**Comment by RigoFlores** [comment]
Con la cuenta de la tia en producción WEB. 
Facturas al receptor RFC FOPR681125BQ0 de fecha 01 y 08 de noviembre.
Ya están canceladas en el sat, pero aparecen activas. Al cancelar envía el siguiente mensaje:

CA24 - Orden de cancelacion del CFDI previamente registrada.38481532 Estatus : Cancelado sin aceptación

Pero no le está cambiando el status

**Comment by RigoFlores** [comment]
Que pasó con este issue? Ya tenemos meses con él.
Con la cuenta de la TIA en producción, si buscas el folio 10, o el folio 8 QUE SE RESALTAN EN AMARILLO EN LAS IMÁGENES, podrás reproducir este issue.

<img width="711" alt="factura8" src="https://user-images.githubusercontent.com/2912775/51061407-d3050c80-15b8-11e9-9487-3b4ecd2ab2e5.PNG">


<img width="694" alt="factura10" src="https://user-images.githubusercontent.com/2912775/51061417-d9938400-15b8-11e9-9cd9-2a2869cd2cff.PNG">

**Comment by jccastillo0007** [comment]
fixed... de hecho lo subi a PRO.. y lo probé con las facturas que mencionaste arriba.

Ojo, en esos casos facture hoy no regresa el acuse

Pequeño aviso fuera de este ticket, como subí esta versión a PRO, puedes checar los reportes generales de Optibelt de CxC en pro
