### ISSUE TITLE
NO APARECEN ALGUNAS FACTURAS EN CXC PARA GENERAR EL CFDI DE PAGO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1482]
EN PRODUCCIÓN:
CLIENTE: GCA960513V78
FACTURA: 4464

NO TENÍA STATUS VENCIDA, Y SE LO PUSE.
NO TENÍA FECHA DE VENCIMIENTO, Y SE LO PUSE
(TENIA NULL EN AMBOS)

ENTIENDO QUE ESO LE PASA A ESE CLIENTE DE LAS FACTURAS 4475 HACIA ATRÁS... QUE SON LAS QUE EMITIÓ EN ESCRITORIO ANTES DE EMPEZAR A FACTURAR DESDE LA PLATAFORMA.
ESTÁ MUY RARO EL PROBLEMA, YA QUE EN VENTAS-CONSULTAS SI APARECEN, PERO EN CXC PARA GENERAR EL PAGO NO.

**Comment by jccastillo0007** [comment]
ya vi que es... hay alrededor de 200 facturas con folio anterior a 4475, que no tienen el UUID cargado... y eso provoca que no se muestren en la pantalla de CxC...

Voy a tener que sacarlo de los XML, para actualizar la base de datos... tendrás los XML ?

**Comment by RigoFlores** [comment]
No, como los voy a tener. Son del cliente.
Esos XML están en la plataforma. Se subieron por el superconector. No los puedes tomar de ahí?
Coméntame para ver si los puedo solicitar. Pero no se tratará de duplicarlos, sino de completarlos.

Ahora, cuántos clientes estarán en ese caso?

**Comment by jccastillo0007** [comment]
listo...

solo faltaron algunas del 2017 y las de junio del 2018 que no me enviaste el excel, si son necesarias, hoy las subo

**Comment by RigoFlores** [comment]
Ya envié el excel con Junio, a mi se me pasó.
Pero una duda, porqué no se subieron correctamente con el superconector???? o donde está el origen de la falla?
Quizás fue una migración, eso si puede ser... confirmas?

**Comment by jccastillo0007** [comment]
Si, puede se la migración o si esos xml se subieron desde el menú de subir un xml... habrá que hacer pruebas

**Comment by jccastillo0007** [comment]
ya subi  todo
