### ISSUE TITLE
Implementar complemento de pago a extranjero en CFDI de Retenciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1483]
Hoy en día tenemos desarrollado el complemento de Dividendos para el CFDI de Retenciones.
Ahora necesitamos agregarle otro complemento, el de Pagos a extranjeros.

Evidentemente, ambos son opcionales, y dependerán de lo que me indiques, que típicamente ha sido un archivo XML de configuración.
Te mando la info por correo

**Comment by RigoFlores** [comment]
No es CCE, es retenciones.
Te mandé la información por correo, y el cliente ya lo está esperando.
Ya pagó desde la semana pasada.

**Comment by jccastillo0007** [comment]
no puedo probar porque el ambiente de pruebas de facture hoy no esta disponible
pero asi quedaría el xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<retenciones:Retenciones xmlns:retenciones="http://www.sat.gob.mx/esquemas/retencionpago/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="1.0" FolioInt="RET2" Sello="bH7X88GTTCuDPYupzgd7Qq3sRkrk3BHjL9yaOskg+1Ap9ofDLRj+kXIQhz0YqxWBdi+JGIdHT6NWjfl3z7AUwdwayj2SswQ4bhWs1cktZcaaaEuxdskU4rkaEz9FXvlpzykI7RE9gzAHSWvGMmSOfW1Z6ed/noyQ3Jo5WB7M2fbbexX4aKSn7J+IKXesO+wO2CDmBktlAHJykBV7NyzB2rz/qb7Z39nwe6ByOIsDwGU2bjm7EqF9FPDvubAcagntH4kliquOuP5O4j7yMYwCa5RgQN5l/rlxb9vjz6JfgOvYnjhTFE6cPLL33Uv9u1Wdd8oGuNgYggSyzCTRdksWgw==" NumCert="20001000000300022815" Cert="MIIFxTCCA62gAwIBAgIUMjAwMDEwMDAwMDAzMDAwMjI4MTUwDQYJKoZIhvcNAQELBQAwggFmMSAwHgYDVQQDDBdBLkMuIDIgZGUgcHJ1ZWJhcyg0MDk2KTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMSkwJwYJKoZIhvcNAQkBFhphc2lzbmV0QHBydWViYXMuc2F0LmdvYi5teDEmMCQGA1UECQwdQXYuIEhpZGFsZ28gNzcsIENvbC4gR3VlcnJlcm8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQRGlzdHJpdG8gRmVkZXJhbDESMBAGA1UEBwwJQ295b2Fjw6FuMRUwEwYDVQQtEwxTQVQ5NzA3MDFOTjMxITAfBgkqhkiG9w0BCQIMElJlc3BvbnNhYmxlOiBBQ0RNQTAeFw0xNjEwMjUyMTUyMTFaFw0yMDEwMjUyMTUyMTFaMIGxMRowGAYDVQQDExFDSU5ERU1FWCBTQSBERSBDVjEaMBgGA1UEKRMRQ0lOREVNRVggU0EgREUgQ1YxGjAYBgNVBAoTEUNJTkRFTUVYIFNBIERFIENWMSUwIwYDVQQtExxMQU43MDA4MTczUjUgLyBGVUFCNzcwMTE3QlhBMR4wHAYDVQQFExUgLyBGVUFCNzcwMTE3TURGUk5OMDkxFDASBgNVBAsUC1BydWViYV9DRkRJMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgvvCiCFDFVaYX7xdVRhp/38ULWto/LKDSZy1yrXKpaqFXqERJWF78YHKf3N5GBoXgzwFPuDX+5kvY5wtYNxx/Owu2shNZqFFh6EKsysQMeP5rz6kE1gFYenaPEUP9zj+h0bL3xR5aqoTsqGF24mKBLoiaK44pXBzGzgsxZishVJVM6XbzNJVonEUNbI25DhgWAd86f2aU3BmOH2K1RZx41dtTT56UsszJls4tPFODr/caWuZEuUvLp1M3nj7Dyu88mhD2f+1fA/g7kzcU/1tcpFXF/rIy93APvkU72jwvkrnprzs+SnG81+/F16ahuGsb2EZ88dKHwqxEkwzhMyTbQIDAQABox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDANBgkqhkiG9w0BAQsFAAOCAgEAJ/xkL8I+fpilZP+9aO8n93+20XxVomLJjeSL+Ng2ErL2GgatpLuN5JknFBkZAhxVIgMaTS23zzk1RLtRaYvH83lBH5E+M+kEjFGp14Fne1iV2Pm3vL4jeLmzHgY1Kf5HmeVrrp4PU7WQg16VpyHaJ/eonPNiEBUjcyQ1iFfkzJmnSJvDGtfQK2TiEolDJApYv0OWdm4is9Bsfi9j6lI9/T6MNZ+/LM2L/t72Vau4r7m94JDEzaO3A0wHAtQ97fjBfBiO5M8AEISAV7eZidIl3iaJJHkQbBYiiW2gikreUZKPUX0HmlnIqqQcBJhWKRu6Nqk6aZBTETLLpGrvF9OArV1JSsbdw/ZH+P88RAt5em5/gjwwtFlNHyiKG5w+UFpaZOK3gZP0su0sa6dlPeQ9EL4JlFkGqQCgSQ+NOsXqaOavgoP5VLykLwuGnwIUnuhBTVeDbzpgrg9LuF5dYp/zs+Y9ScJqe5VMAagLSYTShNtN8luV7LvxF9pgWwZdcM7lUwqJmUddCiZqdngg3vzTactMToG16gZA4CWnMgbU4E+r541+FNMpgAZNvs2CiW/eApfaaQojsZEAHDsDv4L5n3M1CC7fYjE/d61aSng1LaO6T1mh+dEfPvLzp7zyzz+UgWMhi5Cs4pcXx1eic5r7uxPoBwcCTt3YI1jKVVnV7/w=" FechaExp="2018-12-14T17:06:17-06:00" CveRetenc="01" xsi:schemaLocation="http://www.sat.gob.mx/esquemas/retencionpago/1 http://www.sat.gob.mx/esquemas/retencionpago/1/retencionpagov1.xsd">
    <retenciones:Emisor RFCEmisor="LAN7008173R5" NomDenRazSocE="Usuario de pruebas de nomina 1.2"/>
    <retenciones:Receptor Nacionalidad="Nacional">
        <retenciones:Nacional RFCRecep="XAXX010101000" NomDenRazSocR="Cliente de pruebas"/>
    </retenciones:Receptor>
    <retenciones:Periodo MesIni="1" MesFin="8" Ejerc="2018"/>
    <retenciones:Totales montoTotOperacion="100.0" montoTotGrav="100.0" montoTotExent="0.0" montoTotRet="10.0">
        <retenciones:ImpRetenidos BaseRet="100.0" Impuesto="01" montoRet="10.0" TipoPagoRet="Pago definitivo"/>
    </retenciones:Totales>
    <retenciones:Complemento>
        <pagosaextranjeros:Pagosaextranjeros xmlns:pagosaextranjeros="http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros" EsBenefEfectDelCobro="SI" Version="1.0" xsi:schemaLocation="http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros/pagosaextranjeros.xsd">
            <pagosaextranjeros:NoBeneficiario ConceptoPago="18" DescripcionConcepto="descripcion concepto" PaisDeResidParaEfecFisc="US"/>
            <pagosaextranjeros:Beneficiario CURP="CAAJ750607HDFSLN02" ConceptoPago="18" DescripcionConcepto="descripcion concepto" NomDenRazSocB="jccastillo" RFC="CAAJ7506072P2"/>
        </pagosaextranjeros:Pagosaextranjeros>
    </retenciones:Complemento>
</retenciones:Retenciones>


Este complemento se activaría si el rfc receptor es el XAXX010101000 o hay algún otro trigger de que se trata de un complemento de pago de extranjeros

**Comment by jccastillo0007** [comment]
ya esta funcionando en integración, solo para el RFC XAXX010101000, aqui te anexo el XML de la addenda de como quedó definido... el nombre es importante, pues asi lo busca la aplicación... 
Avísame cuál sería el trigger en realidad... probablemente no es el rfc XAXX010101000

**Comment by jccastillo0007** [comment]
[Addenda_XAXX010101000.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/2682384/Addenda_XAXX010101000.xml.txt)

**Comment by RigoFlores** [comment]
No lo sé, supongo que si es al extranjero, debe ser XEXX010101000.... ya está en producción?

**Comment by RigoFlores** [comment]
Los datos de retención para un extranjero, que aplicarán para nuestro cliente en particular.
La neta está muy chacarrón que queden fijos.


RFC Emisor: SAU170517SZ4
RFC Receptor: XEXX010101000

Para el complemento:

Expresar si el beneficiario del pago es la misma persona que retiene: NO

PAIS DE RESIDENCIA : ESPAÑA  (es decir le toca la clave ES)
CONCEPTO DE PAGO : 01 SERVICIOS PROFESIONALES
DESCRIPCION DEL CONCEPTO: Servicios profesionales de elaboración de planos y dibujos de maquinaria de procesos automatizados para la industria de la refrigeración

**Comment by jccastillo0007** [comment]
okas... ya esta en PRU... lo de que quede fijo es temporal...

**Comment by jccastillo0007** [comment]
Puedes probar con el rfc LAN.... para que si se pueda timbrar.... si esta todo ok, le configuro el xml al rfc SAU.. para que cheques en PRO, y mientras veo lo del botón para editar los datos extras

**Comment by RigoFlores** [comment]
el concepto de pago lo reporta como 1, y debe ser 01

**Comment by jccastillo0007** [comment]
deja modifico el xml, ahi le puse el 1

**Comment by jccastillo0007** [comment]
negativo... no acepta 01 

Element '{http://www.sat.gob.mx/esquemas/retencionpago/1/pagosaextranjeros}NoBeneficiario', attribute 'ConceptoPago': [facet 'enumeration'] The value '01' is not an element of the set {'1', '2', '3', '4', '5', '6', '7', '8', '9'}.

Chiaaaa

**Comment by RigoFlores** [comment]
en el catálogo dice 01, pero bueno, lo dejamos en 1.
Me envías pls el XML de configuración, por si hay que cambiar algun dato.
Y hay que llevarlo a PRO.

**Comment by RigoFlores** [comment]
ya vi, era otro catálogo, que efectivamente va del 1 al 9

1 Artistas, deportistas y espectáculos públicos
2 Otras personas físicas
3 Persona moral
4 Fideicomiso
5 Asociación en participación
6 Organizaciones Internacionales o de gobierno
7 Organizaciones exentas
8 Agentes pagadores
9 Otros

**Comment by jccastillo0007** [comment]
ya lo subi a PRO, solo falta el archivo... pero como tiene otro configurado, no sabia si lo podía reemplazar

**Comment by RigoFlores** [comment]
si súbelo, y mañana veo lo del otro

**Comment by RigoFlores** [comment]
como quiera se queda en el servidor el anterior, correcto? solo dime el nombre pls.

**Comment by RigoFlores** [comment]
Sigue marcando error en producción:
Algo de que la fecha del CFDI es mayor que la actual, algo así.

Pero revisando me dí cuenta que en el estándar de retenciones (antes del complemento), existe un parámetro para decir si es Nacional o Extranjero el receptor, y yo creo que ahí es donde está mal, ya que el RFC es extranjero, pero ese parámetro está harcodeado a que sea Nacional. Así está ahora:

    retenciones:Receptor Nacionalidad="Nacional"
        retenciones:Nacional RFCRecep="XEXX010101000" NomDenRazSocR="COLBRAN GRUPO 3, S.L"

Entonces ahí, hay que cambiarle cuando el RFC del receptor sea XEXX, cambiarle a Nacionalidad="Extranjero", además que en este caso, **no lleva el RFC** y la leyenda indica Extranjero, en lugar de Nacional, quedando de la siguiente manera:

    retenciones:Receptor Nacionalidad="**Extranjero**"
        retenciones:**Extranjero** NomDenRazSocR="COLBRAN GRUPO 3, S.L"

**Comment by jccastillo0007** [comment]
ya subi el fix a pru y al nuevo server

**Comment by RigoFlores** [comment]
estoy recordando de este issue, quizá haya que retomarlo... jeje
