### ISSUE TITLE
Implementar el Buzon-T

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1484]
1. Deberá desplegar las facturas pendientes por aceptar la cancelación. Sabemos que solamente el UUID.
2. A los clientes que paguen por dicha función, al acceder a la plataforma, les indicará que tienen facturas pendientes por aceptar o rechazar cancelación
3. Deberá dar la opción para aceptar o rechazar la cancelación.
4. Presentará los filtros de rango de fecha, UUID para consultar y desplegar la información.
5. Deberá generar un reporte en excel, del histórico de las facturas solicitadas, ya sea aceptadas o rechazadas.
6. Deberá ser configurable, esto es solo los clientes que paguen, podrán acceder a dicha opción (de preferencia que lleguen hasta la cocina, pero al momento de consultar, que les indique que esa funcionalidad no está habilitada, porque tiene un costo)

**Comment by jccastillo0007** [comment]
Tengo dudas con el punto 4, pues en realidad se presentarán todas las facturas que esten pendientes de cancelar.

El punto 5, me falta de implementarlo

**Comment by RigoFlores** [comment]
Como te decía, cuando aplico filtro de fecha o status, el resultado en pantalla no cambia, es el mismo.

**Comment by RigoFlores** [comment]
También tengo duda en porque se tarda tanto en la consulta.
Esa información se almacena internamente? Algo así como lo de la tabla CFD, pero para las recibidas?
Estoy pensando en el escenario que el nuestro cliente, no accede al sistema en mas de 3 días hábiles, y con ello la factura se cancelaría en automático. Ahí la plataforma como refleja ese cambio de estado de "Por Autorizar" a "Cancelada"?

**Comment by RigoFlores** [comment]
El viernes en pruebas para el usuario ACO, aparecían 3 facturas... y ahora solo aparecen 2.
Se debería entender que una se canceló 'por tiempo', entonces esa ya no aparecerá nunca mas, o cómo quedó?

**Comment by RigoFlores** [comment]
mañana ya probaré el buzónT en producción
a ver que dice el SAT, con las facturas que generé a mi nombre...

**Comment by RigoFlores** [comment]
Ya volví a validar esto... resulta que no había configurado mi sello en producción.
La buena, es que si lo cancela.
La mala es que no deja ni rastro, ni acuse, ni nada.
Si me voy a consultas, no me arroja nada. Se ocupa en chinga ya, lo de consultas. que aparezcan los que se cancelaron (o que se rechazaron).

**Comment by jccastillo0007** [comment]
ya vi que paso, no habia creado la tabla donde se debe guardar la info... la voy a crear hoy ya dar de alta la factura que cancelaste hoy

Cual es el acuse que quieres, algo como esto :  
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.
org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><ProcesarRespuestaResponse xmlns="http://cancelacfd.sat.gob.mx"><ProcesarRespuestaResult RfcReceptor="FOPR681125BQ0" RfcPac
="CAD100607RY8" CodEstatus="1000" Fecha="2019-02-20T16:47:53.5770358"><Folios Respuesta="Aceptacion"><UUID>6C6F5566-1B15-443B-BCD1-5250FFA656E1</UUID><EstatusUUID>1000</EstatusUUID></Folios><Signat
ure Id="SelloSAT" xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.
w3.org/2001/04/xmldsig-more#hmac-sha512"/><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116"><XPath>not(ancestor-or-self::*[local-name()='Signature'])
</XPath></Transform></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/><DigestValue>4Btr2VDxNYvPofKGM6Qgs5r63VPj5hZgISd94U7QAqawKU4NcBAPPOhbhdWr5B4OmObSXmHL/gomq7ZnHaIT
EQ==</DigestValue></Reference></SignedInfo><SignatureValue>QGn71Hc9tVHStKG/dZ1BFfCbdLZJ9HBhezBexCl2M7G1trIYrviN/3A31eTg6Pt/dXxOzMmGOlLGWpm1mgSJ4Q==</SignatureValue><KeyInfo><KeyName>000010888888000
00031</KeyName><KeyValue><RSAKeyValue><Modulus>ujwIJaMKWWmawqDpHx/OS10pXzEh2SQhY02y64v9Q0+I+0dGlIrjFJeGrsHqAT3JoYnh38Dxwta98t/7++dh2hOgiZEwRignWRIlOgM1MefBHEyY+hi4vHpZgPKq/hJVfHf9nOvlb5UgIHMTCEwrDp
3qk9O5XtTEycnWwiqleG0c1J9sfbRxC0gYBHsNTH85OEtSXYMkiWNYNnFbIc7B0sgp2y18jUxUCNFBMMTV0tz2sxRF+V4hblaPjI75RWmvs9E4lD7MVmW3z7LIlSajuSL8eOqoerSkQhPBABIeQenEPQwRTt3ej3XpVaBsOmagIPZZI3RvOVh+5mcXDE5txQ==</M
odulus><Exponent>AQAB</Exponent></RSAKeyValue></KeyValue></KeyInfo></Signature></ProcesarRespuestaResult></ProcesarRespuestaResponse></s:Body></s:Envelope>

**Comment by jccastillo0007** [comment]
ya esta lista la consulta

**Comment by RigoFlores** [comment]
Entendí que subirías la cancelación de ayer, pero al hacer la consulta no muestra nada.
En cuanto al acuse, algo que nos indique cómo fue el proceso. De hecho en pantalla se mencionó un mensaje indicando que se había procesado la petición o algo parecido, junto con un código.
Hoy trabajaré el video y captaré el mensaje exacto.

Puede ser el mismo formato que ocupamos desde la cancelación estándar.

**Comment by RigoFlores** [comment]
Encontré 3 detalles:
a) Que en el acuse de cancelación, el RFC del receptor, aparece en la etiqueta del emisor
b) Que en consultas, solo aparece la última cancelación, es decir no aparece el histórico. Con la prueba que hice en la cuenta de FOPR681125BQ0, deberían aparecer 2 CFDI's cancelados
c) Falta implementar el 'semaforo' que nos indique si tenemos peticiones pendientes por cancelar.

**Comment by jccastillo0007** [comment]
cual acuse de cancelación? ya te lo genero? no puedo consultarlo después de que lo cancelaste, donde debería aparecer?

el semáforo si falta

**Comment by jccastillo0007** [comment]
del histórico, no procede antes de ayer, es decir, ayer solo di de alta un registro manualmente de la TIA, pero no de tu RFC... a partir de hoy ya se van acumular.

**Comment by RigoFlores** [comment]
Si generó un acuse de cancelación. Aquí la imagen de la pantalla y del acuse.
Si te das cuenta en el acuse aparece el RFC del receptor (porque en el caso de BuzonT, nuestro cliente es receptor), aparece en el emisor.
Al parecer el sello de cancelación está incompleto.


![buzont](https://user-images.githubusercontent.com/2912775/53256673-0a71d900-368e-11e9-9212-2c4b4cc7d8e7.JPG)

![acusebuzont](https://user-images.githubusercontent.com/2912775/53256738-2d03f200-368e-11e9-81a8-00a18ac3f544.JPG)

**Comment by RigoFlores** [comment]
Creo que lo que debemos incluir en el acuse, pudiera ser:

                           RfcReceptor="FOPR681125BQ0" RfcPac="CAD100607RY8" CodEstatus="304"
                           Fecha="2019-02-08T12:30:57.2860182">
                           <Folios Respuesta="Aceptacion">
                                  <UUID>694C7A15-726D-4F9A-9854-19FC0D7B3593</UUID>
                                  <EstatusUUID>304</EstatusUUID>
                           </Folios>
                                         <DigestValue>rnf9wGoeDsxH5RTuB6eMRUfoohl0oDntrRrARgdsvhK4sNPpqnde82H/Ic6OxaWli6M9OQdcczrVXW5pwDlGpw==</DigestValue>
<SignatureValue>xXX+0tm0TfgvXXK9l8miJvo87X2WAiGSyGYHDU+22/KDhGEwbqfeajFz2w8SveLeC1Km7oCsLDJCARFPuA2oOg==</SignatureValue>

**Comment by RigoFlores** [comment]
Lo del histórico, OK.
Donde mostrar el acuse? ... así como en el menú de Ventas-Consultas, cuando una factura está cancelada, aparece el acuse del lado derecho; así mismo se debe mostrar, en la pantalla de BuzonT-Consultas.

**Comment by jccastillo0007** [comment]
mmm pero recuerda que en el buzon-t, no tenemos registro de la factura... tal vez solo del uuid, asi quieres que se muestre

**Comment by jccastillo0007** [comment]
subi una version a PRO, pero no jalo...

**Comment by RigoFlores** [comment]
En consultas, solo mostrará el UUID, no tenemos mas datos, pero a su lado derecho, mostrar el acuse

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
falta el semáforo, falta que en el acuse aparezca en el lugar correcto el rfc del receptor y ahora se agregó el punto que no procesa los rechazos...

**Comment by jccastillo0007** [comment]
tienes algún ejemplo del acuse ? busque en PRO con tu rfc y la tia, pero no encontre... no se a que se refiere este punto :   
falta que en el acuse aparezca en el lugar correcto el rfc del receptor

**Comment by jccastillo0007** [comment]
creo que ya se a que campo te refieres.

y ya esta arreglado desde hace un rato

**Comment by RigoFlores** [comment]
OK, solo queda pendiente el semáforo y que procese los rechazos...

**Comment by RigoFlores** [comment]
Lo de los rechazos está pendiente por validar, bajo el entendido que ya está implementado.
Lo del semáforo, hasta que alguien lo solicite?
