### ISSUE TITLE
Cancelación por conector - Está enviando mensajes distintos al sat a consola y al pdf

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1485]
En el SAT está cancelada
En la consola primero dice que canceló bien, y mas adelante que no se canceló.
El PDF dice que no se canceló.
El XML de cancelación no se genera

Envíe un correo con evidencia

**Comment by jccastillo0007** [comment]
No pude probar que mis cambios esten correctos, porque facture hoy  tiene abajo el web service  de cancelaci[on de pruebas... mañana les envío correo

**Comment by jccastillo0007** [comment]
Listo... checa con la versión que subi hoy al dropbox

**Comment by RigoFlores** [comment]
voy a ver que verifique el cliente
