### ISSUE TITLE
Web - CCE cuando se trata de un RFC de persona física, incluir el CURP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1486]
Para el complemento de comercio exterior, cuando el RFC emisor es de una persona física, se debe incluir el CURP (tomado de la configuración) en el nodo emisor dentro del CCE.
Ejemplo:

            <cce11:Emisor Curp="RECA831119HTSSRD05">
                <cce11:Domicilio Calle="MONTE ATLAS 551 LA LOMA" CodigoPostal="76116" Estado="QUE" Pais="MEX"/>

**Comment by jccastillo0007** [comment]
me recuerdas los datos para generar un CCE... en web

**Comment by jccastillo0007** [comment]
creo que ya vi donde esta... peeeero, me es dificil liberar ahorita a PRO, por lo que ando haciendo con el nuevo server... es urgente?

**Comment by RigoFlores** [comment]
Te mandé los datos para generar un CCE por correo.
Pues quizás pueda esperar un poco este asunto, pero hay algunos otros que no. Por ejemplo, lo del CFDI de retenciones para pagos a extranjeros.

**Comment by jccastillo0007** [comment]
[Addenda_XAXX010101000.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/2682383/Addenda_XAXX010101000.xml.txt)

**Comment by jccastillo0007** [comment]
listo... lo voy a subir a PRO de un vez y vemos que petch

**Comment by RigoFlores** [comment]
lo probé y marca error, aún no está en pro?

**Comment by jccastillo0007** [comment]
si, ya lo subi.

donde lo corriste?, yo lo probé en PRU... ahi también podrías probarlo con mi RFC, ya esta todo configurado

**Comment by RigoFlores** [comment]
no recuerdo donde fue... creo que fue en pro?

**Comment by ofeliatorres** [comment]
Alguien que me apoye con registros de curp para extranjeros
