### ISSUE TITLE
Optibelt - CCE, no está tomando la clave del país cuando es distinta a USA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1489]
Supongo que Canada también lo acepta (CAN); no hice la prueba. Solamente MEX, USA y CAN ocupan catálogo de estados. El resto del mundo, el estado es de libre captura.

Pero hicimos para Panamá que es lo que ellos requieren, cuya clave es PAN y no jaló.
Aquí el archivo para validar....

[MXRE181073098.TXT](https://github.com/jccastillo0007/eFacturaT/files/2688194/MXRE181073098.TXT)

Tenemos que cambiar el RFC de pruebas para optibelt, ya que ACO se venció el sello, y no les ví ganas de actualizarlo.

**Comment by jccastillo0007** [comment]
Fixed.

Ya soporta cualquier otro pais

Ahora el RFC dinámico para probar los conectores especiales sera LAN7008173R5

Trate de timbrar el txt que me enviaste... pero facture hoy marca este error
2018-12-17 21:31:40,621 DEBUG [http-nio-8080-exec-60] (SealerPACProcess.java:360) - Link/Ruta Acuse Recepcion SAT: CE208 - El atributo cce11:ComercioExterior:Mercancias:Mercancia:FraccionArancelaria debe tener un valor vigente del catálogo catCFDI:c_FraccionArancelaria.

Eso ya es un problema de datos.

**Comment by RigoFlores** [comment]
cuáles son los conectores especiales? Optibelt y Navision?
y como es el mismo RFC para 2 conectores distintos?

**Comment by jccastillo0007** [comment]
hay otro que empieza con ETE...

y esos conectores no se podrán probar al mismo tiempo con el mismo rfc LAN... tendremos que cambiarlo, tal como lo haciamos antes con ACO..

**Comment by RigoFlores** [comment]
el de ETE, ya no lo tenemos por lo pronto.
Realmente, tienes que dejar el de optibelt de base para el rfc LAN.
