### ISSUE TITLE
OPTIBELT - GENERAR EL REPORTE DE DÍAS DE CRÉDITO POR MES POR NUMERO DE CLIENTE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1490]
EN ESE REPORTE, SE DEBERÁ OBTENER UN PROMEDIO, DE LOS DÍAS QUE SE TARDAN EN PAGAR LAS FACTURAS POR MES.
HOY EN DÍA, SI GENERAS UN REPORTE DE CARTERA POR CLIENTE, CON FILTRO PAGADAS, YA TE ARROJA ESA INFORMACIÓN,
COMO PLATICAMOS NO ES POR FECHA DE FACTURA, SINO POR FECHA DE LIQUIDACIÓN DE FACTURA.
SE REQUIERE GENERAR POR NÚMERO DE CLIENTE. ESO SOLO LE SIRVE A OPTIBELT.

COMO PODEMOS HACER QUE LE SIRVA A TODOS, LOS QUE NO OCUPAN NÚMERO DE CLIENTE?

**Comment by jccastillo0007** [comment]
cuando generas un reporte general de CxC...  elige la opcion de 60, 90 y 120 y genera el repote.

Hasta abajo de la informaci[on normal del reporte, aparece lo del promedio de d[ias de cr[edito... solo que esta de forma horizontal y no vertical... pero checa si eso les puede servir... ya que esta muy complejo acomodarlo de forma vertical...

**Comment by RigoFlores** [comment]
Ya generé el reporte y no ví nada.
Ahora si es el reporte general, un renglón corresponde a cada cliente. Con ello, no es posible poner el promedio en la parte inferior, ya que ese promedio es POR CADA NÚMERO DE CLIENTE.

**Comment by RigoFlores** [comment]
ya ví, lo subiste en pru... deja revisarlo

**Comment by RigoFlores** [comment]
Es como te decía... el promedio MENSUAL por cliente, debe mostrarse a nivel de número de cliente.
Según yo, debe ser otro reporte, porqué tratarlo de meterlo en ese reporte de cartera general, es lo que supongo se complica...

**Comment by jccastillo0007** [comment]
oye, y el promedio del número de días  que se tardó en pagar el cliente, se debe calcular solo de las facturas que ya están pagadas verdad,.... osea si lleva n pagos pero aún hay un saldo por liquidar, no se debe contemplar esos días

**Comment by RigoFlores** [comment]
Si, tienen que estar pagadas al 100%.

**Comment by jccastillo0007** [comment]
vaya... hasta que muevo un ticket a resolved... aún no hay gasolina, pero ya casi esta el reporte...

**Comment by RigoFlores** [comment]
Oye, ya le liberé a Optibelt, a ver que me dicen ellos del reporte.
Yo creo que debería incluir las facturas pagadas dentro del mes, aunque hayan sido emitidas en meses anteriores, porque si no, entiendo que solo estamos considerando las emitidas y pagadas en el mismo mes. Creo que no ayudaría para sus propósitos.

**Comment by RigoFlores** [comment]
Sigo en espera de su retro, pero como quiera tendremos que considerar los pagos recibidos por mes.... en otro reporte... jeje

**Comment by RigoFlores** [comment]
lo voy a cerrar, aún no me dan retro, supongo que tendrá sus detalles.
