### ISSUE TITLE
para el cliente SAU170517SZ4, dejó de funcionar la addenda mabe (por lo de retenciones)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1491]
Cuando implementamos lo de retenciones con pago para extranjero que nos tardamos un buen, comenté que el disparador fuera cuando elijan el rfc XEXX010101000 desde la pantalla de retenciones.

Ahora desde la pantalla de facturación, está marcando error al momento de hacer una factura con addenda mabe porque según yo está intentando meter el complemento de pago a extranjeros (que solo aplica para retenciones) en las facturas.

**Comment by RigoFlores** [comment]
Hay que arreglar el desmadre.

Addenda MABE (o incluso alguna otra) para los XML que contengan el RFC correspondiente.

CCE para cuando se elija que se incluya el CCE, así como que tenga el XML configurado (si quieres le definimos un nombre de un vez, por ejemplo Addenda_CCE)

(ahora mismo le agrega 2 datos por cada producto en la factura, al momento de capturar la addenda mabe; eso solo aplica para CCE)

Lo de retenciones me dijiste que es totalmente independiente.

**Comment by jccastillo0007** [comment]
ya quedo arreglado, peeeero, el tema de que agrega dos datos en los datos de addenda, no lo puedo arreglar ahora, dada la implementación que se tiene... sin embargo, esos datos serán ignorados al momento de generar la addenda
