### ISSUE TITLE
OPTIBELT - NO ESTÁ ENVIANDO CORRECTAMENTE EL DATO EXTRA2 AL PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1492]
El dato extra 2, debe ser el campo H1.6, es decir tomando el ejemplo de abajo, debe ser = A145863 19/01/2018 181061115|20180122
y en su lugar está mandando la fecha (H1.5), es decir es INCORRECTO=20180123

tomando en cuenta que el campo H1.1, es propiamente H1, el campo H1.2 viene vacío, y así sucesivamente.

H1||181061115||20180123|A145863 19/01/2018 181061115|20180122|Pago en una sola exhibicion/Cuenta 99G1|60|O|Factura Comercial||||||||||2018||||180600|16|||||Cheque|MXN||||||||||||||P||||||||

adicionalmente, no está enviando al pdf el número de pedimento, y sin embargo en el XML si lo incluye.

**Comment by jccastillo0007** [comment]
cual campo es el número de pedimento

**Comment by jccastillo0007** [comment]
el número de pedimento a nivel producto ?

**Comment by RigoFlores** [comment]
es este parámetro dentro del XML

 <cfdi:InformacionAduanera NumeroPedimento="18  81  3334  8002156"/>

en el archivo, ahí lo tienes. De hecho, se le hace un procesamiento para formatearlo.

D|4044978160270|40103200|                  XPA   1332XEAX  optibelt SUPER XE-POWER PRO||2.00|Pz||162.32||||||||||||||||162.32|16.00|||A|07/08/18|1**88133348002156**||||||324.64|324.64|51.94|||||||||||||||||||||||||||||||||||

**Comment by RigoFlores** [comment]
el número de pedimento, solo tiene sentido a nivel producto.
no existe a nivel general

**Comment by jccastillo0007** [comment]
listo... checa con el segundo release de hoy... en el dropbox.

el issue 1, quedo arreglado... que por cierto, siempre se ha estado enviando mal... y hasta ahora lo detectaron.

el issue 2, al parecer también... peeeero espero no le pegue a otros jasper templates, esta bien tricky el manejo de las aduanas

**Comment by RigoFlores** [comment]
Negativo, la referencia es un dato fundamental que ellos ocupan en el módulo de cobranza que ellos le llaman. Puedes obtener un reporte de Cartera de Cliente, del mes de noviembre, donde verás que la referencia se almacenaba sin mayor problema. Asimismo, esas facturas las puedes revisar en consultas, y te darás cuenta que si presentaba en el PDF.

**Comment by RigoFlores** [comment]
Ayer revisé con ellos, si el layout se había desplazado en ese campo, y no.
De hecho si se hubiera desplazado, el resto de campos del header se hubiera movido también.

**Comment by RigoFlores** [comment]
El tema del número de pedimento sigue sin enviarlo, pero además está enviando cuenta predial, y aquí para nada aplica

**Comment by RigoFlores** [comment]
numeroAduana creo que es la variable donde tendría que enviar el número de pedimento.

Pero además está enviando el número de predial, lo cual para nada debe hacerlo. Anexo el archivo de prueba de optibelt.

            <cfdi:CuentaPredial Numero="40103200"/>

[MXRE191073461.TXT](https://github.com/jccastillo0007/eFacturaT/files/2742449/MXRE191073461.TXT)

**Comment by jccastillo0007** [comment]
okas, deja pruebo con el archivo

**Comment by jccastillo0007** [comment]
osea el predial no debe enviarlo ni al xml ? o te refieres solo al pdf?

**Comment by RigoFlores** [comment]
el predial no se debe enviar a ningún lado.
El predial aplica únicamente en el caso de recibo de arrendamiento.

**Comment by jccastillo0007** [comment]
oye eso de la cuenta predial ya lo mandaba desde antes cierto ?

**Comment by jccastillo0007** [comment]
quite lo del predial... y ya se manda el pedimento al pdf.... haber checale con la versión de hoy

**Comment by RigoFlores** [comment]
La cuenta predial no se enviaba, tomé una factura del año pasado al azar, y no incluía la cuenta predial, y si enviaba el pedimento.

Con la nueva versión que liberaste ayer, ya no se envía la cuenta predial al XML, ni PDF.
Lo que sigue sin enviar al PDF, es el pedimento, esto es la variable numeroAduana.

**Comment by RigoFlores** [comment]
Entiendo que todo el desmadre surge a partir de que se implementó el CCE para optibelt.

**Comment by jccastillo0007** [comment]
confirmado

numeroAduana=18  81  3334  8002156,cuentaPredial=,

**Comment by jccastillo0007** [comment]
<cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="26111500" NoIdentificacion="4044978160270-1" Cantidad="2.00" ClaveUnidad="H87" Unidad="Pz" Descripcion="XPA 1332XEAX optibelt SUPER XE-POWER PRO" ValorUnitario="162.320000" Importe="324.640000">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="324.64" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="51.94"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
            <cfdi:InformacionAduanera NumeroPedimento="18  81  3334  8002156"/>
        </cfdi:Concepto>
    </cfdi:Conceptos>

**Comment by RigoFlores** [comment]
listo ahora si ya quedó.
