### ISSUE TITLE
CxC - Cartera de Cliente, no muestra resultados con filtro vigentes + vencidas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1493]
Con la cuenta de la tia en producción.
Si accedes al menú de CxC - Ingresar cobro, y así sin ningún filtro le dar consultar (en la sección del paso 2), te desplegará todas las facturas que son cobrables, es decir las facturas que no han sido pagadas, y por lo tanto deberían tener status de vigentes o vencidas.

Si en CxC - Cartera de clientes, aplico el filtro de vigentes + vencidas, no muestra ningún resultado.
No si si al momento de la migración se perdió ese status o que pasó, pero al menos en la cuenta de la tia no se despliega nada.

**Comment by jccastillo0007** [comment]
Por alguna razón, había un registro en la base de datos con un campo en la tabla CFD, el campo es cancelDate y tenía el valor 0000-00-00....

mysql> select id, serie, folio, cancelDate,date, targetRFC, CxCStatus, SATStatus  from CFD where sourceRFC = 'TIA101020BP4' and id = 504846;
+--------+-------+-------+---------------------+---------------------+---------------+-----------+-----------+
| id     | serie | folio | cancelDate          | date                | targetRFC     | CxCStatus | SATStatus |
+--------+-------+-------+---------------------+---------------------+---------------+-----------+-----------+
| 504846 | A     |  5885 | 0000-00-00 00:00:00 | 2018-01-31 15:50:52 | XAXX010101000 | Vencida   | Vigente   |

Eso causaba el error

**Comment by RigoFlores** [comment]
oye, y no se presenta el caso para otros RFC´s?

**Comment by jccastillo0007** [comment]
noup..., no encontré mas fechas con ese formato
