### ISSUE TITLE
No está llegando el consumo de folios diario, al correo contacto@factura-t.com.mx

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1494]
Desde la migración del servidor, dejó de jalar.

**Comment by RigoFlores** [comment]
Sigo sin tener visibilidad de como vamos.
Hace una semana lo comenté.
Nos movemos muy lento.
Yo creo que necesitamos ya cambiar de estrategia, no está funcionando así como vamos.
Condominios, que supuestamente en agosto íbamos a tener la primer versión, simplemente no ha habido avance desde entonces.

**Comment by jccastillo0007** [comment]
serio... chiaaaa

**Comment by jccastillo0007** [comment]
pues es que no he dado de alta los scripts jojojo

**Comment by RigoFlores** [comment]
se ocupa esa información desde el día 27 de diciembre, hasta que ya quede en línea de manera cotidiana.

**Comment by jccastillo0007** [comment]
ya configure el cron, ma;ana ya debe llegar

**Comment by RigoFlores** [comment]
si llegó, pero en ceros.
