### ISSUE TITLE
Agregar algunas deducciones que faltan en nómina en producción.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1495]
Se trata del catálogo de deducciones:

Faltan mas, pero con descripcion muuy larga, mejor hasta que se ocupen. Por lo pronto agregar estas 2:

100 | Ajuste en   Viáticos exentos
101 | ISR   Retenido de ejercicio anterior

**Comment by jccastillo0007** [comment]
listo
