### ISSUE TITLE
Navision, del conector al web, no envía los documentos relacionados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1496]
Lo detectaron para nota de crédito, pero asumo que aplica para facturas también.
En el servidor de navision está bien el PDF, pero no está llegando la info al web.

**Comment by jccastillo0007** [comment]
me parece que encontré el problema, tienes forma de probarlo

se puede con cualquier otro archivo, no necesariamente de navision

**Comment by jccastillo0007** [comment]
ya esta en pro

**Comment by RigoFlores** [comment]
no tengo que actualizar el facturat de navision, es decir del conector?
