### ISSUE TITLE
No se está actualizando el status de las facturas en producción

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1497]
El cron o proceso que debe validar si una factura está vigente o vencida, no está corriendo.
Tenemos afectación principalmente en optibelt.

**Comment by jccastillo0007** [comment]
ya puse el cron, ma;ana ya deber ejecutarse

**Comment by RigoFlores** [comment]
lo voy a cerrar, esperando que ya se actualice el status.
A ver que me dice Optibelt.
