### ISSUE TITLE
Detalles en Descarga-T - Consultas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1498]
a) Mostrar el status de las facturas. El receptor debe conocer si están vigentes o no. Aqui la pregunta es, reflejar el status de la plataforma o del SAT directamente????
b) Incluir todo tipo de CFDI: ingreso, egreso, traslado, nómina y/o pago. (ojo, NO CONSIDERAR remisiones, cotizaciones, pedidos). Para los condominios será necesario mostrar las Solicitudes de Pago, pero esa es otra historia.
c) Al parecer no está tomando en cuenta el filtro de fechas, para desplegar las facturas en consultas.

**Comment by jccastillo0007** [comment]
a) Mostrar el status de las facturas. El receptor debe conocer si están vigentes o no. Aqui la pregunta es, reflejar el status de la plataforma o del SAT directamente???? 
Seria de la plataforma, si no, la consulta sería super lenta

**Comment by jccastillo0007** [comment]
b) Incluir todo tipo de CFDI: ingreso, egreso, traslado, nómina y/o pago. (ojo, NO CONSIDERAR remisiones, cotizaciones, pedidos). Para los condominios será necesario mostrar las Solicitudes de Pago, pero esa es otra historia.

No esta incluyendo todo? detectaste que falta

**Comment by jccastillo0007** [comment]
c) Al parecer no está tomando en cuenta el filtro de fechas, para desplegar las facturas en consultas.

No aplica, si toma en cuenta el rango de fechas, chiaaaaa

**Comment by RigoFlores** [comment]
A) OK
B) SOLO MOSTRABA FACTURAS. INGRESO. EL RESTO, SEGÚN YO, NO LO MOSTRABA. AL MENOS PAGOS, SEGURO QUE NO.
c) si funciona el filtro de fechas, ya lo verifiqué.

**Comment by jccastillo0007** [comment]
listo ya esta en PRU
Ojo... es la primera vez que modifico que descargat, desde hace muuuuucho tiempo... desde que  cambie de máquina
Los archivos que subo para deployar la app, tienen diferente tamaño de PRO y PRU, se me hace que tal vez algo me falta... haber como lo ves

**Comment by RigoFlores** [comment]
oye, para validar lo del status, necesito que algunas estén canceladas.
Lo puedes subir a pro, y como quiera ahí vemos lo que falte antes de liberarlo, o cómo sugieres?

**Comment by jccastillo0007** [comment]
okas, subiendo
