### ISSUE TITLE
OPTIBELT - Reporte de Pagos recibidos por rango de fecha

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1499]
Pues justo lo que no hicimos en el reporte anterior, al considerar el rango de fechas de emisión de facturas en lugar de los pagos.
Bueno, pues ahora quieren un reporte (OTRO NUEVO), donde por rango de fechas se incluya:

**Reporte de Pagos recibidos por Rango de Fecha**

Fecha de pago, RFC receptor, # cliente, Importe pagado, Referencia

Supogo yo, ordenado por fecha, y si al final puede incluir un sumarizado de los importes pagados, mejor.

Supongo yo que debe ser un reporte aparte, menu dentro de CxC:  "Reporte de Pagos"

**Comment by jccastillo0007** [comment]
Bueno, al menos nos van a pagar otro reporte, no esta nada mal jojojo

Y no se ve dificil

**Comment by RigoFlores** [comment]
Pues hay que apurarle, porque está lo otro de Navision. A ver si quedan los 2 este fin de semana.

**Comment by jccastillo0007** [comment]
Lo subo a Pro

**Comment by RigoFlores** [comment]
Si, ya que vimos que en pru, tenemos mucha inconsistencia de datos.
Entonces lo valido en pro...

**Comment by jccastillo0007** [comment]
ya esta en pro

**Comment by RigoFlores** [comment]
SI LO VÍ, SEGÚN YO LO HABÍA COMENTADO.
QUIZÁS FUE POR CORREO.
