### ISSUE TITLE
En Catalogo de clientes Permite Repetir el RFC

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#15]

**Comment by RigoFlores** [comment]
AHORA YA NO PUEDE, NI ALMACENAR EL REGISTRO

**Comment by RigoFlores** [comment]
OK, YA SE PERMITE ALMACENAR EL REGISTRO, Y ADEMÁS YA VALIDA QUE NO SE REPITA EL RFC
