### ISSUE TITLE
No se están actualizando la vigencia de los folios de los clientes en producción.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1501]
Es decir, les estamos dando vigencia ilimitada... lo cual, pega en los ingresos también.

**Comment by jccastillo0007** [comment]
listo... hay un problema con el query... me marca este error

ERROR 1292 (22007): Truncated incorrect date value: '28/07/2019 23:00:00'

Pero no se de donde saca esa fecha... esta raro... por ahora actualicé los folios manualmente

**Comment by RigoFlores** [comment]
no está resuelto... sigue dejando pasar folios.
Voy a ejecutar el cueri que mencionaste

**Comment by RigoFlores** [comment]
sigue sin enviar la información correcta, según yo porque no toma la fecha del día anterior.

**Comment by jccastillo0007** [comment]
ya debe  estar correcto.
