### ISSUE TITLE
OPTIBELT - Dejó de incluir la fracción arancelaria cuando se trata de facturas con CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1502]
Aparentemente el último cambio, que era enviar el número de pedimento al PDF, le pegó.
También estaba enviando anteriormente la cuenta predial, pero esa no se ocupaba en ningún momento y ese ajuste también se hizo.

Ahora genera así el complemento:

    <cfdi:Complemento>
        <cce11:ComercioExterior xmlns:cce11="http://www.sat.gob.mx/ComercioExter
ior11" CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="EXW" Subdivision="0
" TipoCambioUSD="18.98" TipoOperacion="2" TotalUSD="776.55" Version="1.1">
            <cce11:Emisor>
                <cce11:Domicilio Calle="5 DE FEBRERO" CodigoPostal="76120" Estad
o="QUE" Municipio="014" Pais="MEX"/>
            </cce11:Emisor>
            <cce11:Receptor>
                <cce11:Domicilio Calle="565 E. Fullerton Avenue" CodigoPostal="6
0188" Estado="IL" Pais="USA"/>
            </cce11:Receptor>
            <cce11:Mercancias>
                <cce11:Mercancia CantidadAduana="20.0" FraccionArancelaria="null
" NoIdentificacion="4014486083149-1" UnidadAduana="01" ValorDolares="310.62" Val
orUnitarioAduana="15.53"/>
                <cce11:Mercancia CantidadAduana="30.0" FraccionArancelaria="null
" NoIdentificacion="4014486083149-2" UnidadAduana="01" ValorDolares="465.93" Val
orUnitarioAduana="15.53"/>
            </cce11:Mercancias>
        </cce11:ComercioExterior>
    </cfdi:Complemento>

Si lo pruebas con este archivo, que en producción del cliente si jala, ya que no le he actualizado a la super última versión:

[MXRE191074239.TXT](https://github.com/jccastillo0007/eFacturaT/files/2815065/MXRE191074239.TXT)

**Comment by RigoFlores** [comment]
Este archivo si lo procesa bien, incluye pedimento y lo manda al PDF, pero no incluye el CCE.

[MXRE191073461_estandar.TXT](https://github.com/jccastillo0007/eFacturaT/files/2815081/MXRE191073461_estandar.TXT)

**Comment by jccastillo0007** [comment]
fixed

**Comment by jccastillo0007** [comment]
el archivo estándar que enviaste, no le pone el CCE porque no trae nada en el campo H4 posición 4, ese dato es requerido para este campo del receptor NumRegIdTrib

**Comment by RigoFlores** [comment]
Te mandé un ejemplo con CCE y otro sin CCE, pero con el pedimento, para ver que no le pegue.
