### ISSUE TITLE
Navision - implementar cancelación y ajustar el tema de CFDI's relacionados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1503]
Te mandé un correo. 
Se trata de implementar la cancelacion de CFDI, así como homologar el proceso de CFDI's relacionados de un CFDI a otro.

**Comment by RigoFlores** [comment]
**Cancelación:**
Se requiere enviar a cancelar una factura desde Factura-T. La forma de saber que un CFDI debe ser cancelado, es cuando el “Estado” = 4 en la tabla [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Factura-T]. Según ellos, solo lo ocuparán para pagos, pero pues este approach es genérico.

Hoy en día cuando un CFDI se debe timbrar se coloca Estado = 0, Si se timbró exitosamente el Estado cambia a 2; si tuvo error, el Estado cambia a 3.
Entonces, ahí mismo cuando el estado = 4, será un indicativo que ese CFDI en particular, se debe cancelar. 

Factura-T ejecutará el proceso de cancelación y reportará el resultado.
Los valores y su significado son:

VALOR DE CAMPO “Estado”	Interpretación
0	El CFDI debe timbrarse, es decir es un CFDI nuevo.
2	El CFDI se timbró exitosamente
3	El CFDI no se pudo timbrar
4	El CFDI debe cancelarse
5	El CFDI se canceló exitosamente
6	El CFDI no se pudo cancelar
7	El CFDI está en proceso de cancelación

No sé si sea relevante, pero si una factura no se pudo cancelar, desde Navision se contará con la facilidad para reintentar la cancelación, eso es, volver a poner el estado = 4, en la factura a cancelar o ‘recancelar’.

**Relación entre CFDI’s**

Para la relación entre CFDI’s, ocuparemos la tabla actual: 

[MEXICO - IP - PEDIMENTO$Relacion factura anticipo]

1)	Los tipos de relación se indicarán en la columna TipoRelacion (que será nueva para esta tabla). Cómo referencia, Navision ocupará las siguientes tipos de relación, pero eso será transparente para Factura-T 
Nota de Crédito: 01. Nota de crédito de los documentos relacionados
Documento de Pago: 04. Sustitución de los CFDI’s previos
Factura Global: 07. CFDI por aplicación de Anticipo
Nota de Crédito asociada a Factura Global: 07. CFDI por aplicación de Anticipo
2)	La columna “Factura anticipo”, siempre contendrá el folio del CFDI que está por emitirse, es decir la que está por timbrarse. Por ejemplo: 18FVMX280, 18PAMX0030, 18AVMX029.
3)	La columna “Factura” contendrá el folio del CFDI a relacionar (el que ya fue emitido anteriormente). Por ejemplo: 18FVMX180, 18PAMX0040, 18AVMX039.
4)	El esquema anterior de relación para facturas estándares y notas de crédito, dejará de funcionar (era manual). Para CFDI de Pago, este esquema es nuevo.
5)	El esquema actual para facturas globales, se ajustaría a estos cambios para dejar todo homologado.
6)	Cuando se emita una factura estándar, una factura global, una nota de crédito o un documento de pago, y se requiera relacionar con otro(s) CFDI(s) ya timbrados, entonces se deberá agregar un registro a la tabla, por cada CFDI relacionado. Esto es, si existen varios CFDI’s relacionados a un mismo CFDI, existirán varios registros, como por ejemplo la factura FVMX163, que tiene 3 CFDI’s relacionados

**Comment by RigoFlores** [comment]
Existe un status mas, que es el del 'en proceso de cancelación'.
Como quiera hay que agregar dicho status en la aplicación. No podemos aprovechar para de una vez ajustar los códigos mencionados arriba, para empatar con lo que les pasé a los españoles???

**Comment by jccastillo0007** [comment]
okas, tenemos ambiente de pruebas, con datos consistentes para probar?

La cancelación como tal no se puede probar muy bien, pues traen un relajo... pero el tema de los cfdi relacionados si se puede probar

**Comment by jccastillo0007** [comment]
Oye el punto 4 que arriba mencionas

4\. El esquema anterior de relación para facturas estándares y notas de crédito, dejará de funcionar (era manual). Para CFDI de Pago, este esquema es nuevo.

No es correcto del todo, para facturas ya se tiene implementado este esquema basado en la tabla Relacion Factura Anticipo

**Comment by jccastillo0007** [comment]
Este punto

2)	La columna “Factura anticipo”, siempre contendrá el folio del CFDI que está por emitirse, es decir la que está por timbrarse. Por ejemplo: 18FVMX280, 18PAMX0030, 18AVMX029.

esta raro... como que la factura que esta por timbrarse, ese dato ya se toma de la tabla facturat...  en que casos debo tomar esa columna

**Comment by jccastillo0007** [comment]
No sé a que se refiere una factura estándar vs una factura global

**Comment by jccastillo0007** [comment]
subi una versiòn al dropbox, con los nuevos còdigos, sigo trabajando con el tema de los cfdi relacionados.

**Comment by RigoFlores** [comment]
EN LA TABLA FACTURA-T SABES CUÁL FOLIO ESTÁ POR TIMBRARSE. EN LA TABLA RELACION FACTURA ANTICIPO, SI APARECE EL FOLIO QUE ESTÁ POR TIMBRARSE, IMPLICA QUE ESE FOLIO QUE ESTÁ POR TIMBRARSE TIENE CFDIS RELACIONADOS. ES DECIR, NOS INDICARÁ SI UN CFDI POR EMITIR TIENE O NO CFIDS RELACIONADOS.

FACTURA ESTÁNDAR Y FACTURA GLOBAL, ES UN TÉRMINO DE ELLOS, PARA NOSOTROS ES TRANSPARENTE.

**Comment by jccastillo0007** [comment]
okas ya entendi.

La tabla en cuestion, aún no tiene el campo tipo relación...
CREATE TABLE [dbo].[MEXICO - IP - PEDIMENTO$Relacion factura anticipo](
	[timestamp] [timestamp] NOT NULL,
	[Factura] [varchar](20) COLLATE Modern_Spanish_CI_AI NOT NULL,
	[Factura anticipo] [varchar](20) COLLATE Modern_Spanish_CI_AI NOT NULL,

Necesito que se lo agreguen, para que pueda hacer pruebas...

Me avisas cuando este listo, el query de arriba lo saque tanto de la base de datos de PRO y de PRUEBAS SAT

**Comment by jccastillo0007** [comment]
Oye para los documentos de pago, es el mismo proceso para identificar los CFDI relacionados... peroen el caso de documentos de pago, se llaman documentos relacionados cierto?, incluso llevan mas datos, no solo el UUID.

Si estamos hablando del mismo procedimiento, me confunde la diferencia entre cfdi relacionados para facturas y NC, por otro lado, documentos relacionados para pagos

**Comment by RigoFlores** [comment]
Negativo, en cualquier CFDI pueden o no, existir los CFDI's relacionados.
Lo propuesto aquí de CFDIs relacionados, se refiere a ese punto en cualquier XML:

    <cfdi:CfdiRelacionados TipoRelacion="04">
        <cfdi:CfdiRelacionado UUID="92247288-BD1F-4FF4-8896-096A24773478"/>
        <cfdi:CfdiRelacionado UUID="CCF518B0-DC5C-4382-9470-CADEE893AA81"/>
        <cfdi:CfdiRelacionado UUID="CCF518B0-DC5C-4382-9470-CADEE893AA81"/>
    </cfdi:CfdiRelacionados>

particularmente, cuando hablamos de pagos, y en específico de Navision, existe el concepto de documentos relacionados, que se toman de la siguiente tabla: 

  select *
from [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Lineas Documento de pago]
where [CFDI pago]
in ( '19PAMX0007' );

en un cfdi de pago, se reflejan los documentos relacionados, dentro del complemento de recepción de pago:

        <pago10:Pagos Version="1.0">
            <pago10:Pago CtaBeneficiario="036680500105247319" CtaOrdenante="036680500105247319" FechaPago="2018-07-09T12:00:00" FormaDePagoP="03" MonedaP="MXN" Monto="4000.00" NumOperacion="03210123">
                **<pago10:DoctoRelacionado Folio="31482" IdDocumento="CCF518B0-DC5C-4382-9470-CADEE893AA81" ImpPagado="116.00" ImpSaldoAnt="116.00" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PPD" MonedaDR="USD" NumParcialidad="1" Serie="DD" TipoCambioDR="0.058"/>
                <pago10:DoctoRelacionado Folio="31482" IdDocumento="DDF518B0-DC5C-4382-9470-CADEE893AA81" ImpPagado="116.00" ImpSaldoAnt="116.00" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PPD" MonedaDR="USD" NumParcialidad="1" Serie="DD" TipoCambioDR="0.058"/>**
            </pago10:Pago>
        </pago10:Pagos>

**Comment by RigoFlores** [comment]
ya solicité la creación del nuevo campo a la tabla en cuestión...

**Comment by RigoFlores** [comment]
ya está creado el nuevo campo [Tipo de relación]

**Comment by jccastillo0007** [comment]
ok subi un zip al dropbox, con los cambios.
No lo pase a PRO, porque no estoy seguro si esta todo listo para las pruebas

**Comment by RigoFlores** [comment]
sigo en espera que me indiquen que ya puedo probar...

**Comment by RigoFlores** [comment]
Oye ya llevé la nueva versión, y si levante el facturat, pero no hizo nada.
Le pusimos estado = 4, a un pago inexistente (solo existía en la tabla facturat), y no hizo nada, ni marcó error.
Le pusimos estado=4, a un pago de la vida rial (con toda la integridad de data), pero tampoco hizo nada.
Le puse estado = 0, a un pago inexistente, y tampoco hizo nada.

En conclusión, aunque si levantó, no hizo nada. Cambiarán los nombres de los campos...

**Comment by jccastillo0007** [comment]
ok, igual y para la próxima me avisas y yo checo...
revisaste el log de facturat?

**Comment by RigoFlores** [comment]
no lo revisé... en la consola, no mandaba ningún mensaje... solo decía que 0 cfdis por procesar.
Supongo no se cumplían las condiciones para que se pudiera procesar.
Algo importante es que la tabla de relaciones, no debería ser condición para timbrar, ya que no todas las facturas incluyen CFDI's relacionados

**Comment by jccastillo0007** [comment]
correcto, no es condición

Cuando agreguen sus campos, me dices para yo hacer pruebas

**Comment by RigoFlores** [comment]
OK, entonces para buscar CFDI's relacionados en FACTURAS, se queda tal cual está ahora. 

Para buscar CFDI's relacionados en PAGOS, se han creado nuevos campos:


Enabled         Field No.                    Field Name    
Yes                  4                                  Nº pago                       Alfanumérico  20        
Yes                  5                                  Nº pago cancelado     Alfanumérico  20        


Tabla: 50138 - Relacion factura anticipo
N° Pago - es el folio del pago que se emitirá
N° Pago Cancelado - contendrá el folio del pago que se tiene que relacionar.

**Comment by jccastillo0007** [comment]
negativo... para buscar cfdi relacionados en facturas, habias dicho que se iba a reemplazar por el nuevo approach... ya cambiaron de opinión?

4. * El esquema anterior de relación para facturas estándares y notas de crédito, dejará de funcionar (era manual). Para CFDI de Pago, este esquema es nuevo.
5. * El esquema actual para facturas globales, se ajustaría a estos cambios para dejar todo homologado.

**Comment by jccastillo0007** [comment]
a reserva de aclarar mi comentario de arriba.

Subi una versión diferente a navision, y al levantar factura, estaba haciendo bien el pooling, pero no había facturas para probar

**Comment by RigoFlores** [comment]
Es que manejan conceptos medio complicados. Para ellos una factura estándar es distinta a una 'factura global'. Y manejan esa distinción, incluso a nivel de CFDI relacionados. Pero no te confundiré mas.

Total que se ocupará la misma tabla 'Relacion factura anticipo', pero para CFDI relacionados en facturas y notas de crédito serán unos campos y para pagos, serán otros campos (los últimos mencionados en este issue).

**Comment by jccastillo0007** [comment]
hice pruebas y funciona bien el timbrado normal..
faltaría probar en si el tema de cfdi relacionados

**Comment by RigoFlores** [comment]
de hecho también falta probar la cancelación, y de acuerdo a lo que comentaste anoche, no está jalando.

**Comment by jccastillo0007** [comment]
listo.. y probé la cancelación, y de hecho con los diferentes escenarios...

cancelación directa, error al cancelar, y en proceso de cancelación.

Tuve que generar mas facturas, pero luego las cancelé... pero si recomiendo validar que solo quede una factura vigente del folio '19FVMX061', no vaya ser que se me paso cancelar alguna

**Comment by RigoFlores** [comment]
se hizo una mezcla de información en los acuses y status, yo creo que algo no anda bien...

**Comment by jccastillo0007** [comment]
hay que probar con información fresca y en un flujo natural, sin manipular la base de datos

**Comment by RigoFlores** [comment]
Sigo en espera de que me den retroalimentación... chiaaaa

**Comment by RigoFlores** [comment]
Timbré la factura 116, que tiene CFDI relacionado y no jaló... es decir, no incluyó el CFDI relacionado en el XML. Aquí la pantalla del sql server, y también el cueri:

select *
from [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Relacion factura anticipo]
where [Factura] in ( '19FVMX116' );

![docto relacionado](https://user-images.githubusercontent.com/2912775/55523381-1ca84500-5646-11e9-90a6-dd571a98f9c6.JPG)

**Comment by jccastillo0007** [comment]
listo... estaba haciendo mal el query a la tabla de relacion factura, lo subi al dropbox

**Comment by RigoFlores** [comment]
Traían un cagadero. 
Total que pidieron ajustar nuevamente la tabla y aprovechando, le pedí que para TODO CFDI (factura, nota de crédito y pago), se ocupe **la misma tabla para conocer los documentos relacionados quedando así:**

Tabla: MEXICO - IP - PEDIMENTO$CFDI relacionados
Campos:
CFDI
CFDI relacionado
Tipo Relación



![cfdiRelacionado](https://user-images.githubusercontent.com/2912775/55741943-1e7e5980-59f4-11e9-8ba4-56c75755f40a.JPG)

**Comment by RigoFlores** [comment]
recuerda el tema de la vista alterna, ya que directamente en la tabla no es posible...
entendería que deberías crear nuevamente esa vista, y apuntar todos los tipos de CFDI a los mismos campos...

**Comment by jccastillo0007** [comment]
CFDI Relacionados es una nueva tabla?

Quitaron lo de pago y pago anticipo verdad

**Comment by RigoFlores** [comment]
Si es una nueva tabla y si quitaron los otros campos.
Ahora para cualquier tipo de CFDI, las columnas serán las mismas para buscar si tiene CFDI relacionados.

**Comment by jccastillo0007** [comment]
listo... puedes checar si jala todo ok

esto de cfdi relacionado aplica solo para cfdi y pagos... no tengo nada para nc

**Comment by RigoFlores** [comment]
No jaló, te mandaré el log por correo.
Algo que se me había olvidado comentarte, es que la fecha en la tabla de Factura-T, se guarda chueca. Eso cambió, ya que antes lo almacenaba bien. Así debe mostrarse:

![fechaIP](https://user-images.githubusercontent.com/2912775/55815786-7f6e6600-5ab6-11e9-97d5-24e44c38ba1c.JPG)


Y cuando lo almacenamos, la fecha le agrega la fecha y hora. Ellos tienen que estar cambiando manualmente ese campo para que no marque error en Navision.
Creo que eso es en parte la razón de la falla que presentó con esta última versión.

Este es el error:

2019-04-09 10:38:09,925 ERROR [pool-3-thread-1] (NAVISION_ConnectorProcessor.jav
a:987) - org.springframework.dao.DataIntegrityViolationException: StatementCallb
ack; SQL [update [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Factura-T] se
t Estado = '3' , Resultado = 'Hibernate operation: could not execute query; unca
tegorized SQLException for SQL [select this_.timestamp as timestamp21_0_, this_.
factura as factura21_0_, this_.facturaAnticipo as facturaA3_21_0_, this_.tipoRel
acion as tipoRela4_21_0_ from NavisionRelacionFactura this_ where this_.factura=
?]; SQL state [null]; error code [0]; La conversi├│n de timestamp a DATE no es c
ompatible.; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException:
 La conversi├│n de timestamp a DATE no es compatible.' where [N┬║ factura] = '19
FVMX116']; Los datos de cadena o binarios se truncar├¡an.; nested exception is c
om.microsoft.sqlserver.jdbc.SQLServerException: Los datos de cadena o binarios s
e truncar├¡an.
org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL
[update [IPNavision400SP2].[dbo].[MEXICO - IP - PEDIMENTO$Factura-T] set Estado
= '3' , Resultado = 'Hibernate operation: could not execute query; uncategorized
 SQLException for SQL [select this_.timestamp as timestamp21_0_, this_.factura a
s factura21_0_, this_.facturaAnticipo as facturaA3_21_0_, this_.tipoRelacion as
tipoRela4_21_0_ from NavisionRelacionFactura this_ where this_.factura=?]; SQL s
tate [null]; error code [0]; La conversi├│n de timestamp a DATE no es compatible
.; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: La conve
rsi├│n de timestamp a DATE no es compatible.' where [N┬║ factura] = '19FVMX116']
; Los datos de cadena o binarios se truncar├¡an.; nested exception is com.micros
oft.sqlserver.jdbc.SQLServerException: Los datos de cadena o binarios se truncar

**Comment by RigoFlores** [comment]
No jaló lo de CFDI relacionados. Según yo es el mismo problema que tenemos con la cancelación, que no está ubicando el uuid correcto en la tabla facturat. Yo creo que la vista no se está actualizando o que se yo.

Problemas:
a) Colocar la hora como 12:00:00 en la tabla de facturaT. Quizás sea parte de la problemática.
b) El UUID del CFDI relacionado, no tengo idea de donde lo está tomando, pero mientras la tabla indica que la nota de crédito con folio 19AVMX013 se relacione a la factura 19FVMX116, cuyo uuid es 639ae1a5-8a21-434e-9fdc-02ea040004f0, en su lugar le colocó un uuid, que no he logrado ubicar siquiera en ninguna factura de marzo ni abril. Este uuid chueco es bff11905-4e8d-4e06-baf2-a41a775aa1b2

**Comment by jccastillo0007** [comment]
a) fixed
b) fixed

te mando el xml que acabo de generar , la tabla factura ya tiene la fecha chacarrona con hora 12:00:00

Chiale

**Comment by RigoFlores** [comment]
no mams, no está tomando el tipo de relación, en lugar del 07 que indica la tabla, le puso 01... eso si, chiaaaa.....
además que estamos retrasando un pago, quedamos como super novatos... por no decir otra cosa... no manches, este requerimiento es relativamente sencillo y llevamos MESES con él

**Comment by jccastillo0007** [comment]
![image](https://user-images.githubusercontent.com/2245679/56074438-32b9b200-5d78-11e9-8db1-6c20fcb7f297.png)

**Comment by jccastillo0007** [comment]
la que yo genere ayer, tiene 01

**Comment by RigoFlores** [comment]
según yo revisé eso, obvio era lo primero a revisar... pues no sé que pasó.
Ya timbré y si colocó el tipo de relación y también el uuid correcto.
