### ISSUE TITLE
Documento de pago- pago en USD a una factura emitida en MXN

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1504]
Cuando la factura se emitió en MXN, y se recibe un pago en USD, no permite generar el documento de pago, ya que el importe del cobro es evidentemente (en USD) menor que el monto del pago en MXN.
Aquí la pantalla para el cliente DLA090826L62.
El problema no es tan simple. Esta condición solo se debe permitir cuando la moneda de la factura sea en MXN y la moneda del pago sea extranjera. Aún no es suficiente ello. Quizás debamos poner la condición que solo se permita esta situación, cuando se emite el documento de pago.

![pago usd to mxn](https://user-images.githubusercontent.com/2912775/52577215-3f0ca780-2de7-11e9-9ebc-bb05ad1010ac.JPG)

**Comment by jccastillo0007** [comment]
pero entonces cómo debe funcionar, hay que cambiar los usd a pesos, de acuerdo al tipo de cambio?

algo asi ya estaba funcionando, pero creo que solo por conector no?

**Comment by RigoFlores** [comment]
estoy haciendo pruebas, creo que aunque el pago haya sido en USD, para una factura emitida en MXN, se debe reportar el importe pagado en MXN (convertido).
Mientras no se demuestre lo contrario, voy a cerrar este issue

**Comment by RigoFlores** [comment]
Oye, está complicado este asunto... aún no sé como va... para poder finalmente conocer el detalle...
NECESITO UNA VERSIÓN DE ESCRITORIO, PARA QUE POR EL CONECTOR PUEDA HACER PRUEBAS.
YA CASI ME QUEDÓ, PERO RESULTA QUE CUANDO LA MONEDA DEL DOCUMENTO RELACIONADO (FACTURA) ES MXN, NO REPORTA EL TIPO DE CAMBIO A NIVEL DOCUMENTO DE PAGO.

Por esa razón marca error... entonces necesito que ese candado se abra, solo para esa versión de prueba (que validaré en producción, por cierto). 

La petición, es una versión de escritorio, que cuando el archivo de texto, a nivel de documento de pago incluya el tipo de cambio, lo envíe al XML

**Comment by jccastillo0007** [comment]
ya subi esa versión al dropbox... si pone los dos tipos de cambio... pero no timbra la factura... supongo que vas hacer varias pruebas para ver si encuentras la combinación indicada

**Comment by RigoFlores** [comment]
la última versión en el dropbox es de las 9:15 y no pone el tipo de cambio.
repetí el proceso de borrar y poner los jars, y el resultado fue igual

**Comment by RigoFlores** [comment]
me parece que es un escenario, que no está especificado por el sat... mañana haré una prueba en el mismísimo sat, a ver si puedo...
