### ISSUE TITLE
Remisiones/DescargaT, no les está asignando el ID a las remisiones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1505]
Si hago una consulta en producción con la cuenta de la tía, con fecha de hoy 11 de febrero, aparecerá una remisión a nombre de FOPR681125BQ0, pero la columna ID aparece vacía.

Con ello, no se pueden convertir las remisiones en facturas desde el DescargaT, ya que falta ese dato. Al no poder hacer facturas, no puedo terminar de probar el DescargaT.

Ese dato, necesitamos enviarlo al PDF de la remision en esta varible:  $F{trackingId}, creo que no la estás enviando. Me avisas cuando lo tengas, para cambiar la plantilla. Si la cambio ahora mismo, marcará error.

**Comment by jccastillo0007** [comment]
listo

el trackingId ya se esta enviando al PDF... solo me faltaba crear la remisión con dicho valor

Cree otra remisión para validarlo en PRO con la TIA

**Comment by RigoFlores** [comment]
Oye, no sé si derivado de esto que le ajustaste, ahora en la vista previa... no se envía el número de folio al PDF.
En su lugar se envía la hora...
chiaaaaaa

**Comment by RigoFlores** [comment]
La remisión la intenté facturar desde descargaT, y me marca que folios no disponibles.
No sé si está checando folios del receptor, pero debería ser del emisor, en este caso la TIA.
Remisión 7, que es la que hiciste ayer, por si quieres reproducir el problema.

Como quiera, revisé los folios del receptor y también tiene vigentes..

**Comment by jccastillo0007** [comment]
listo.... 
acabo de generar la remision folio 8, y la facture desde descargat...

descargat, estaba usando el ambiente de pru
