### ISSUE TITLE
WEB Vista previa - en lugar del folio, está mostrando la hora

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1506]
Varios clientes llamaron hoy, se ve que ocupan mucho la vista previa.
Según yo con el cambio del descargat que subiste anoche, se movió este punto.

Si le das vista previa desde la pantalla de facturación, en lugar del folio, te pone un dato raro, al parecer es la hora.

**Comment by jccastillo0007** [comment]
fixed
