### ISSUE TITLE
CxP - generar un documento equivalente a la remisión, pero para pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1507]
No todos los pagos estarán respaldados de una factura, por ejemplo caja chica emite un cheque por un documento que ampara varios gastos, no facturados.
Si fuera desde el punto de vista de emisor, este sería una remisión.

Desde el punto de vista de nuestro cliente como receptor, esto podria ser simplemente un 'Pago' o algo similar. La plantilla PDF, por lo pronto, puede ser la misma que una remisión.

Un 'Pago' se manejará como un documento que tiene que ser pagado, idéntico a una factura de un proveedor.

**Comment by RigoFlores** [comment]
le podríamos llamar en lugar de pago... al documento, podría ser un 'Egreso', lo cual sería la contraparte de la 'Remision'

**Comment by jccastillo0007** [comment]
Osea un Egreso, lo generamos, y luego donde debe aparecer? o donde se va a utilizar o cambiar por un pago formal?

**Comment by RigoFlores** [comment]
Este egreso, es idéntico a una remisión, pero desde el punto de vista de proveedor.
Donde debe aparecer? En la pantalla de Compras, menú Egreso. Sería una captura similar a la remisión, evidentemente se podría o no, elegir RFC/Nombre de un proveedor.
Este documento, donde se utilizará, pues en CxP, será tratado como una factura, pero que no será timbrado. Será para justificar las salidas de caja chica.

Esto se ocupará mucho en los condominios.

**Comment by RigoFlores** [comment]
Cuando se consulten las CxP que están pendientes de pago, deben aparecer facturas y egresos (documento egreso), con el status de vigente o vencida.

**Comment by jccastillo0007** [comment]
ya esta generando egresos, pero por alguna razon esta tronando al generar el pdf

**Comment by jccastillo0007** [comment]
oye, entonces un documento de egreso debe aparecer en CxP, como pendiente de pago, pero no deberia mas bien utilizarse para pagar otras facturas ? o como van a pagar un egreso

**Comment by RigoFlores** [comment]
El egreso es para CxP,  como una Solicitud de Pago en CxC (condominios).
Si le vas a dar salida a un cheque de caja chica, el 'Egreso' será el documento que respalde dicha salida.
El egreso, se paga igualito a una factura de un proveedor, esto es por transferencia, efectivo, etc.; lo mas común debería ser por cheque.

**Comment by RigoFlores** [comment]
Jejeje... ya ví la pantalla del Egreso, y ahí se despliegan los datos de los CLIENTES, y los productos del emisor y todo respecto al emisor. 
Lo que debe reflejarse, son los datos de algún proveedor. Y los productos, pues pudieran ser tomados del mismo catálogo, para evitar hacer mas pantallas.

Es que si no estamos entendiendo el concepto, pues menos lo reflejaremos en pantalla.

El proveedor sube una factura, y en CxP ingresar pago, se le paga, punto.
OK, el egreso hace las veces de una factura de un proveedor, que será igualmente pagada. Para qué? Para justificar una salida de lana que no cuenta con respaldo de factura, hay muchos casos, pero el mas claro es la caja chica.

**Comment by jccastillo0007** [comment]
oye, por alguna razón no esta funcionando la vista previa en PRU, crei que era algo del Egreso, pero en realidad, tampoco funciona para facturas

**Comment by RigoFlores** [comment]
Pero que marca en el catalina?
Estamos apuntando al repositorio correcto?
Raro que no funcione la vista previa de las facturas

**Comment by RigoFlores** [comment]
Cuál es la serie que está buscando. Asumo que EGRESO.
Para mantener un estándar (a 3 letras), pudiera ser solo EGR.

**Comment by jccastillo0007** [comment]
listo

**Comment by jccastillo0007** [comment]
oye, eso de tener que soportar un egreso, sin un rfc como cliente... esta medio cabron.. ya que todo el manejo de archivos se basa en el emisor... y en este caso nuestro cliente es el receptor...

podemos forzar a usar el XAXX ?

**Comment by RigoFlores** [comment]
Si, que sea el XEXX010101000, pero de hecho que ellos lo capturen.
No cambies nada. Para ello es el rfc genérico, sip

**Comment by RigoFlores** [comment]
Es decir, para la emisión de egresos, que no quede amarrado al código, pero es un hecho que si no se ocupa un rfc válido, se ocupará el rfc genérico, para no romper el esquema actual.

**Comment by RigoFlores** [comment]
sigue marcando error al generar el PDF

**Comment by jccastillo0007** [comment]
ya esta jalando y la base de datos esta limpia en PRU
