### ISSUE TITLE
Configuracion Web - al cambiar o agregar algún parámetro, marca error en datos de seguridad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1508]
No está tomando el password del certificado que ya se tiene almacenado y configurado y validado.
Entonces cuando se agrega un logo  o una archivo de addenda, o cualquier cambio, marca error.
Se necesita mantener el password que ya se tiene almacenado

**Comment by jccastillo0007** [comment]
fixed, solo en PRU

**Comment by jccastillo0007** [comment]
ya esta en PRO tambi[en

**Comment by RigoFlores** [comment]
según yo, la corrección que hiciste... ahora provoca que cuando estoy cambiando la contraseña... caso concreto un cliente nuevo, que no tenía contraseña previa almacenada... siempre marca el error de datos de seguridad... se me hace que pasará con todos los nuevos... o todos aquellos que cambien el certificado y por ende la contraseña...

**Comment by jccastillo0007** [comment]
al parecer ya quedo, esta en pru unicamente

**Comment by RigoFlores** [comment]
Que bueno que fue en pru.
Se arregló lo de la configuración del sello que no lo aceptaba... peeeeero ahora se descompuso nuevamente el motivo original de este issue, esto es que vuelve a pedir la contraseña del sello. De hecho ahora mismo ya lo borra, y anteriormente no.
Cuando estás modificando la configuración pero que no interviene algún cambio de sello (logo, plantilla, addenda, datos extra, cuenta bancaria, etc), se desconoce dicha contraseña, y hay que buscarla en la BD y se hace muy tardado y complicado. Además que cuando el cambio lo hace el cliente, no se lo permitiría ni de chiste.

En el campo contraseña debe mantener la almacenada en la BD, EXCEPTO cuando ese campo sea el que estés cambiando. En otro caso, no tiene ni porqué cambiarlo, ni porqué pedirlo.

![contrasenia](https://user-images.githubusercontent.com/2912775/53900195-975b5180-4001-11e9-8fff-2939c0a13786.JPG)

**Comment by jccastillo0007** [comment]
Que caray... ayer me pareció que funcionaba bien... capaz que tiene que ver con el cache o cookies

**Comment by jccastillo0007** [comment]
ok, ahora si, me parece que ya esta listo

**Comment by RigoFlores** [comment]
ya quedó en pru, hay que llevarlo a pro
