### ISSUE TITLE
Implementar addenda Tsys

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1509]
Te envié un correo con lo que se ocupa. 
no tenemos el xsd.
solo se captura un dato, el de orden de compra.
aquí el ejemplo:

  <cfdi:Addenda>
    <hp:ITSB version="1.1" xmlns:hp="http://www.itsmartbusiness.com/sitio_internet/EVA00/" OdeC="PO-0000">
    </hp:ITSB>
  </cfdi:Addenda>

**Comment by jccastillo0007** [comment]
no manches, en serio nada mas asi ?

es para web?

**Comment by jccastillo0007** [comment]
que RFC emisor seria ? el del xml?

**Comment by RigoFlores** [comment]
SI, ES PARA WEB.
EL NADA MAS ASÍ?, SIGNIFICA QUE ESTÁ MUY SIMPLE O QUE NECESITAMOS ALGO MAS?

HOY ME PASAN EL RFC RECEPTOR, AL PARECER POR EL EJEMPLO QUE ME ENVIARON, PUDIERA SER EL XEXX010101000.
YO TE CONFIRMO. EL ARCHIVO DE CONFIGURACIÓN DEBERÍA INCLUIR ESE RFC EN EL NOMBRE, PARA DISTINGUIRLO.
SOLAMENTE EN EL CASO DE CAPTURAR LA ADDENDA SE INCLUIRÍA, EN OTRO CASO SE IGNORA.
RECUERDO QUE ESE RFC YA TIENE ALGO EN CÓDIGO, HABRÍA QUE ASEGURARSE DE NO PEGARLE.

**Comment by jccastillo0007** [comment]
podemos ligarlo al rfc emisor y no al receptor...

osea, siempre que el emisor sea GOSE830906LG7 y se capture algo en el archivo de addenda, entonces agregamos la addenda

**Comment by RigoFlores** [comment]
Me parece buena solución, pero lo que me preocupa es que para esta addenda en particular, se rompa el esquema estándar del resto de addendas... como que ahí no me suena.

La addenda aplicaría para estos rfc's EMISORES EMISORES, es decir de nuestros clientes:

SIE150519922
GIE030819G99

pero yo creo que es mejor que el archivo XML, contenga el rfc del receptor, como en cualquier otra addenda, para no tener casos de excepción. Tu me dices como queda... voy a presionar porque me entreguen el RFC del receptor

**Comment by RigoFlores** [comment]
rfc receptor: TSS940421JYA

**Comment by jccastillo0007** [comment]
listo, ya esta en PRU...  y en base al receptor...

Ojo... otros receptores, que de casualidad le facturen al mismo rfc TSS, también les generaría la addenda

**Comment by jccastillo0007** [comment]
ya lo subi a pro, por si de una vez lo quieres entregar

**Comment by RigoFlores** [comment]
Pero cuál es el XML de dicha addenda?
Cualquiera otro de nuestros clientes, puede tener ese mismo receptor, pero mientras no se capturen los datos de la addenda, no tendría por que incluirla.

Aún mas, si cualquier otro cliente no tiene configurado el plugin de addenda, ni el XML correspondiente, pues ni siquiera se enteraría que se puede incluir dicha addenda para ese receptor.

**Comment by RigoFlores** [comment]
Yo veo 2 cosas:
Eo resaltado en negritas, no se incluye en la addenda generada.
El XML estándar, aparece en una sola línea, en lugar de formateado como siempre lo hemos generado.

  <cfdi:Addenda>
    <hp:ITSB version="1.1" xmlns:hp="http://www.itsmartbusiness.com/sitio_internet/EVA00/" OdeC="PO-0000">
    **</hp:ITSB>**
  </cfdi:Addenda

**Comment by jccastillo0007** [comment]
El formateo no se puede hacer, ya que no tenemos schema... y no se puede validar-ordenar en base al schema

el  </....> que falta, no se ocupa, pues esta la addenda en una sola linea... el cierre de tags se ocupa cuando se tiene en diferentes lineas

**Comment by RigoFlores** [comment]
no me han aceptado la addenda, porqué aún no tienen la necesidad de generarla.
Lo cerraré, y llegado el momento lo revisamos si hay algo pendiente
