### ISSUE TITLE
CxP - Ingresar Pagos - muestra facturas canceladas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1512]
Eso es algo que en CxC, ya que la cancelación y actualización de status, se hace desde la aplicación.
Para el caso de CxP, las facturas no las emitimos nosotros, entonces desconocemos su status.
Veo 2 problemas:

a) No se ha resuelto el tema que cuando un proveedor o el mismo receptor de la misma (nuestro cliente en el caso de CxP), sube una factura, se valide su vigencia ante el SAT. Debe resolverse ya.
b) En todo lo que es CxP, podría existir el riesgo de que una factura que esté por pagar, ya esté cancelada. Entonces al menos en las facturas de proveedores con status de vigente o vencida, debemos validar su status ante el SAT, antes de someterlas al proceso de CxP. Esto podría hacerse al momento de elegir una factura por pagar, o al momento de hacer la consulta al ingresar Pago.

Cómo vex, donde puede quedar mejor esa consulta.

La otra es que se haga la consulta, y que siempre esté presente el botón de validar vigencia a las facturas resultado de la consulta, lo cual pudiera resultar tardado.
O bien que se valide en automático, cuando una factura de un proveedor, sea elegida para ser pagada, cómo vex?
También puede validarse al momento de generar cualquier reporte. Eso sería mas tardado aún.

**Comment by jccastillo0007** [comment]
Asumo que en la descripción siempre te refieres a CxP verdad

**Comment by jccastillo0007** [comment]
En todos los casos es tardado..  ya que se debe hacer una por una...
Yo creo que se va hacer al momento de que elijan una factura y someterla a pago, ya que en ese caso, solo validamos una factura.... si lo hicieramos en consultas tendriamos que validar todas las facturas.

Pero antes que todo, dejame ver que pasa con el proceso de validación ante el SAT

**Comment by RigoFlores** [comment]
Si, este issue todo se refiere a CxP.

Probablemente el proceso de validación del SAT, tenga una versión en batch.
Ahora, seguro que lo que tenemos para cancelación de facturas de cualquier PAC, no sirve para validar?
Porqué he leído que algunos servicios del SAT, solo están disponibles para los PAC. Por ejemplo el de cancelación, es solo para PAC's

**Comment by RigoFlores** [comment]
FactureHoy respondió sobre los servicios que se pueden ocupar para conocer el status de una factura

**Comment by jccastillo0007** [comment]
Estoy trabajando en este ticket, ya tengo el servicio de facture hoy
Estoy haciendo pruebas, solo que tal vez lo suba a PRO porque el servicio de facture hoy solo funciona con producci[on

**Comment by RigoFlores** [comment]
OK, si no hay opción, que se suba a producción.
Ahora cómo quedaría el mecanismo de validacion?

a) al momento de subir facturas del proveedor
b) al momento de desplegar la consulta para ingresar pago (CxP)
c) al momento que se elige una o varias facturas, se valida que esté vigente?

**Comment by jccastillo0007** [comment]
Ok,,, hoy lo subo....

Por ahora se cubre el escenario c), se valida al momento de que le dan salvar, si esta cancelada en el SAT, avisa en pantalla y marca la factura como cancelada, para que ya no aparezca

El escenario b), no es buena idea, ya que en la consulta pueden ser muchas facturas a validar

Falta implementar el escenario a)

**Comment by RigoFlores** [comment]
OK, entonces para el tema de CxP y/o compras:

a) Cuando se sube un XML, en ese momento se valida su vigencia. Si no está vigente, no se sube y se envía el mensaje.
b) En CxP, cuando se capture un pago asociado a una o varias facturas, se validará en ese momento que las facturas por pagar están vigentes. Si no lo están, no procesa el pago y además se cambia el status a cancelada para que ya no aparezca en las facturas por pagar.

Queda pendiente el punto (a).

**Comment by jccastillo0007** [comment]
Ya esta implementado el punto a)

**Comment by RigoFlores** [comment]
oye, pero el punto (b) ya se había reportado como atendido, que no?

**Comment by RigoFlores** [comment]
Me dijiste que solo en producción se podía validar.
Tomé un XML recibido, y le modifiqué el UUID. Con eso ya es un XML no válido.
Lo intenté subir a la plataforma desde Compras-Registrar CFDI, y madres!!! que si lo acepta...
Chiaaaaaa

Es decir, esa factura que subí no está registrada en el SAT, y como quiera la aceptó.
La validación debe ser que esté vigente... (no cancelada Y registrada en el SAT)

**Comment by jccastillo0007** [comment]
jaja creo que no lo subi a pro
hoy lo subo, y lo pruebo igual que tu lo hiciste

**Comment by jccastillo0007** [comment]
ya esta funcionando, pero arroja el error muy feo directo del pac... debo darle una chaineada
Lo probé con la cuenta de la TIA en pru, desde la opción de subir un xml en compras

**Comment by RigoFlores** [comment]
OK, hay que controlar ese mensaje y aplicar lo mismo, al momento que se quiera pagar una factura.
Creo que este punto que parece tan simple, puede ser de gran valor al momento de ofrecer este módulo.

**Comment by RigoFlores** [comment]
Hice la misma prueba, subiendo una factura buena, es decir publicada y vigente, y la rechazó, no la subió. Supongo que este es el error feo aquel...

Error al verificar el CFDi con el SAT
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><ConsultaResponse xmlns="http://tempuri.org/"><ConsultaResult xmlns:a="http://schemas.datacontract.org/2004/07/Sat.Cfdi.Negocio.ConsultaCfdi.Servicio" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><a:CodigoEstatus>N - 602: Comprobante no encontrado.</a:CodigoEstatus><a:EsCancelable/><a:Estado>No Encontrado</a:Estado><a:EstatusCancelacion/></ConsultaResult></ConsultaResponse></s:Body></s:Envelope>

**Comment by jccastillo0007** [comment]
aún no termino lo de formatear el mensaje...

Pero de entrada, en el mensaje anterior.. marca esto N - 602: Comprobante no encontrado, ante eso no hay mucho que hacer de nuestro lado... ahi estuvo bien que no lo subiera.

**Comment by RigoFlores** [comment]
Hay que checarlo con fhoy... pero hay que desatorar los issues...

**Comment by jccastillo0007** [comment]
espera, si esto lo hiciste en PRU, pues obvio fhoy va a marcar que no existe... lo vamos a tener que probar en PRO, hoy arreglo el pinche mensaje feo..

**Comment by jccastillo0007** [comment]
ya esta formateado el mensaje... lo voy a subir a PRO para hacer algunas pruebas... 
a ti te marcaba no encontrado porque era el ambiente de pruebas, y ahi siempre mandan esa respuesta...

**Comment by jccastillo0007** [comment]
probé el tema de subir xml de un proveedor desde el menú de compras, y ya esta validando bien contra el SAT y mostrando bien el mensaje... me falta validar las otras opciones de ingresar pago para ver que filtre las canceladas

**Comment by RigoFlores** [comment]
Este issue, se refiere a CxP - Ingresar pago.
Cuando se va a realizar el pago de una factura, debe validar que esté vigente y registrada en el SAT.
Aunque, de hecho, para que la factura aparezca ahí, anteriormente debió estar vigente y registrada. 

Aquí se puede validar solamente que esté vigente, o si da lo mismo, que valide también que esté publicada.

**Comment by jccastillo0007** [comment]
si, ya también esta ese escenario, el proceso sería asi...
cuando se da de alta una factura de un proveedir, ahi se revisaría si el cfdi esta en el sat y esta vigente.

Después en teoría se cancela la factura por alguna razón

Posteriormente para registrar un pago... si aparecerá la factura cancelada, al seleccionarla para pagarla, se va a validar otra vez en el SAT, si dicha factura aparece cancelada, mostrará un mensaje en pantalla, y guardará esa factura como cancelada... 

En las siguientes búsquedas de facturas para ingresar un pago, ya no va a aparecer...

**Comment by jccastillo0007** [comment]
yo no tengo facturas de algún proveedor, como para probar este ticket, tu tienes de la tia?

Si no, pues hay que generar algunas entre la tia, tu rfc y el mío... pero de bajo valor

**Comment by RigoFlores** [comment]
Hice una factura con mi RFC para la tía, desde la plataforma.
La cancelé desde el SAT. Esperé a que estuviera realmente cancelada. Obvio esa cancelación no se refleja en el sistema, ya que no están conectados.

Capturé el pago "F2" (en producción), y si aceptó el pago. 

Conclusión, no está jalando esa validación de que la factura esté vigente, antes de aceptar la captura del pago.

**Comment by jccastillo0007** [comment]
el pago también lo hiciste desde tu RFC ?
fue en CxC ingresar cobro ? 

tu RFC no muestra el menú de CxC, estoy confundido

**Comment by RigoFlores** [comment]
La factura la emití yo (emisor) para la tia (receptor).
Con ello, **accediendo con la cuenta de la tía, esa factura le aparece como de un proveedor**.
Esa factura yo la cancelé en el sat.

Luego con la cuenta de la tía, en CxP, le capturé un pago a esa factura, y si lo aceptó, aún cuando ya está cancelada en el SAT.

**Comment by jccastillo0007** [comment]
a cabron... deja veo si puedo hacer eso yo mismo...

**Comment by RigoFlores** [comment]
lo puedes hacer con la misma factura que yo hice, pero bueno, si quieres emitir la propia para tus pruebas, está bien.

**Comment by jccastillo0007** [comment]
ya lo hice, y pude revisarlo y corregirlo... lo subi a PRO....

**Comment by RigoFlores** [comment]
Desde el menú de compras, validé:
a) Subir un CFDI vigente - OK
b) Subir un CFDI cancelado - OK (no lo permitió, mandó el mensaje que el CFDI se encuentra cancelado)

Desde el menú de CxP - Ingresar pago, validé:
a) Registrar pago de un CFDI Cancelado - OK
b) Registrar pago de un CFDI Vigente - OK
