### ISSUE TITLE
No jala el CFDI con CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1517]
FactureHoy, dice que faltan algunos schemalocation, y colocarlos en el header y bla bla bla.
Finkok dice que dentro del nodo emisor del CCE, ahora ya quiere que vaya el municipio y localidad, en caso que existan en los catálogos del SAT.

Cuál de las 2 soluciones te parece mas simple?
FactureHoy, si timbró sin municipio, ni localidad, pero hay que cambiar o actualizar los schemalocation.

Finkok, necesita agregar 2 datos del domicilio del emisor, en el nodo emisor del CCE.

Tu define, pero pronto, porque ya nos estará marcando error... y quizás Optibelt, también tenga problemas. 
Para no pegarle tanto, quizás lo de los namespaces y esas cosas, no crees?

**Comment by RigoFlores** [comment]
el correo de facturehoy, te llegó a ti también, donde dan las observaciones de los schema location

**Comment by jccastillo0007** [comment]
deja veo y hago pruebas
tienes un txt que pueda usar, cualquiera de los que ya teniamos ?

**Comment by RigoFlores** [comment]
TE LOS MANDÉ POR CORREO, 2 ARCHIVOS DE TXT

**Comment by jccastillo0007** [comment]
ya hice los cambios en standalone para mostrar los schema location... tienes forma de probar en producción?

Subi el release al dropbox

**Comment by RigoFlores** [comment]
En escritorio si jaló, pero en web no está jalando. Te envié correo con evidencia

**Comment by jccastillo0007** [comment]
ya esta generando en producción el XML con los schema location adecuados...

**Comment by RigoFlores** [comment]
probé con optibelt la última versión, y marcó lo mismo que marcaba en web anteriormente, cuando se presentaba el error con facturehoy:

2019-03-22 13:19:37,356 DEBUG [http-nio-8080-exec-16] (SealerPACProcess.java:510) - Link/Ruta Acuse Recepcion SAT: 301 - XML mal formado : No es posible resolver schemalocation de complemento <cce11:

2019-03-22 13:19:37,357 DEBUG [http-nio-8080-exec-16] (Validator.java:244) - CFDi Status : 003 : OME111223UN4 - XEXX010101000 - 76145 - 191075663 -  - null - 22032019131937

**Comment by RigoFlores** [comment]
de hecho hay algo muy extraño, tomé la consola de optibelt, y ahí aparentemente formó bien el XML, pero en el catalina se muestra distinto... eso es 'normal'?
