### ISSUE TITLE
CxP - Reporte por proveedor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1518]
Hay que llamarle, Reporte de Pagos. En general podrías generar reportes de pagos realizados o de pagos pendientes por hacer (propiamente CxP).
No debe pedir forzosamente elegir un proveedor, ya que deberías poder consultar los pagos realizados en un período de tiempo.
También deberías poder consultar las cuentas por pagar, y eso involucra varios proveedores.

Ahora cuando registras un pago, se hace un desmadre con los cálculos.
Ahorita con la cuenta la de TIA pagué una factura, folio 925594 y el saldo aparece como negativo. Estamos haciendo chuecas las cuentas.

![CxP negativo](https://user-images.githubusercontent.com/2912775/54561542-80661900-498a-11e9-9617-441141d28207.JPG)

**Comment by jccastillo0007** [comment]
hay que checar otra vez el resultado de este reporte.. ahorita esta toda la base de datos limpia.

Oye, el reporte de general de CxP es el que se usa para consulta general.. y no por proveedor

**Comment by RigoFlores** [comment]
El resultado es el mismo, sigue mostrando números negativos. Si checas los pagos realizados al RFC NWM97, lo podrás constatar.

Hay que cambiar este menú y nombre del reporte, como "Reporte de Pagos".

En CxC, tu puedes consultar por rango de folios, por fechas, por cliente.

En CxP hay que hacer el equivalente, esto es que, también debes conocer a cuántos proveedores les has pagado en el mes (por rango de fechas y status pagadas), o a cuáles les debes (pueden o no aplicar filtros). Aquí puede salir la cartera vencida, pero de los proveedores. Ese mismo reporte se puede generar por un rango de fechas mayor a un mes, o por un proveedor en específico, o por todos los proveedores. Es decir todos los filtros deben ser opcionales.

Por otro lado el reporte general, te dirán el total de pagos realizados a cada uno de los proveedores. Sin importar rango de fechas, ni nada. En un consolidado. A diferencia del reporte de Pagos, que desglosa cada factura pagada a los proveedores.

**Comment by jccastillo0007** [comment]
checale

**Comment by RigoFlores** [comment]
sin cambio alguno, de mis últimos comentarios, todos se mantienen idénticos...

![reporteProveedor](https://user-images.githubusercontent.com/2912775/54858568-212a4080-4ccb-11e9-8d72-62ac1d585a19.JPG)

**Comment by jccastillo0007** [comment]
Ok, ya le cambie el nombre al reporte... ojo.. se llama igual que un reporte que esta en CxC, Reporte de Pagos, no sé si eso vaya a ser confuso...

Ya cambié las columnas

Todo esto ¨En CxP hay que hacer el equivalente, esto es que, también debes conocer a cuántos proveedores les has pagado en el mes (por rango de fechas y status pagadas), o a cuáles les debes (pueden o no aplicar filtros). Aquí puede salir la cartera vencida, pero de los proveedores. Ese mismo reporte se puede generar por un rango de fechas mayor a un mes, o por un proveedor en específico, o por todos los proveedores. Es decir todos los filtros deben ser opcionales.

Por otro lado el reporte general, te dirán el total de pagos realizados a cada uno de los proveedores. Sin importar rango de fechas, ni nada. En un consolidado. A diferencia del reporte de Pagos, que desglosa cada factura pagada a los proveedores.¨

Es lo que se va a tener en el reporte consolidado no?

**Comment by RigoFlores** [comment]
Podríamos nombrar al otro reporte, "Reporte de Cobros"...

**Comment by RigoFlores** [comment]
Si nos vamos a CxP - reporte de pagos en pantalla, con la cuenta de la tia, proveedor NW te arroja esto, todas las facturas ya están pagadas. recordar que saldo = abono (monto de factura del proveedor) - cargo (pago de nuestros clientes, receptor de la factura en el caso de CxP), pero aparecen en columnas distintas.

![reportePagos](https://user-images.githubusercontent.com/2912775/55117594-0122c480-50b1-11e9-9180-333a520980fa.JPG)

**Comment by RigoFlores** [comment]
El tema en este punto, es que se despliegan en columnas chuecas.
Monto de factura de proveedor: abonos
Monto de los pagos de nuestro cliente: cargos
Saldo del proveedor: abonos - cargos

**Comment by jccastillo0007** [comment]
esto ya esta listo... en pru
