### ISSUE TITLE
Compras - Egresos ajustes menores en pantalla de egreso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1519]
Un listado de ajustes menores a la pantalla de egreso:
a) Eliminar la dirección
b) Eliminar lugar de expedición
c) Forma de Pago y Método de pago, apegarlo al catálogo del SAT
d) El botón para generar el egreso, cambiar el ToolTip a 'Generar Egreso'
e) Ocupar la plantilla Egreso33.jrxml, o en su defecto solo la de Egreso.jrxml

**Comment by jccastillo0007** [comment]
done en PRU

**Comment by RigoFlores** [comment]
faltó el punto (d)

**Comment by jccastillo0007** [comment]
negativo, si esta el punto d... pero tienes que actualizar el cache...  dale botòn derecho del mouse y refrescar o en configuraciòn busca la opciòn de borrar cache

**Comment by RigoFlores** [comment]
pues sigue diciendo generar remisión, en lugar de generar egreso.
Lo hice con un navegador nuevo...

**Comment by jccastillo0007** [comment]
no manches ... ahora si ya lo super cheque... hay que borrar caché

**Comment by RigoFlores** [comment]
no es necesario borrar el caché, jaló así sin borrarlo.
Pero bueno, lo bueno que tu lo viste el sábado, porque luego no me crees... jeje
