### ISSUE TITLE
Identificar un RFC cuando se trate de FE en lugar de FT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1520]
Creo conveniente identificar cuando un cliente pertenece a FE y no a FT.
Agregar un campo en la tabla de cliente o algo similar.
En la pantalla del keygenerator, sería un checkbox.

Un cliente actual de FT, tendría cuenta en automático en FE?

Cómo vex?

**Comment by RigoFlores** [comment]
como funcionará este checkbox?
Ya vi que está en producción.
Un usuario de FT es usuario de FE, o son mutuamente excluyentes?
Un usuario de FE, puede ser usuario de DescargaT?

**Comment by jccastillo0007** [comment]
son excluyentes... 
el usuario fe solo puede usar fe... 

en la tabla de clientes se crea un registro para cada nuevo cliente de fe, con todo y su configuración, pero con acceso a fe unicamente

**Comment by jccastillo0007** [comment]
La TIA, tu RFC y el mio, ya tienen acceso a todas las aplicaciones...

**Comment by RigoFlores** [comment]
OK, si ya ví.
Pero bueno, el tema podría ser que pueda pasar de FT a FE, eso ya se pueda ahora mismo?
Si las cuentas mencionadas tienen acceso a ambas plataformas, entonces quiere decir que existe un perfil que sirve para ambas?? ClientType = otro nuevo???
