### ISSUE TITLE
CxP - Reporte de Pagos (excel), con detalles:

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1521]
![reportePagosExcel](https://user-images.githubusercontent.com/2912775/55121709-5535a500-50c1-11e9-942b-a661d773fa1c.JPG)

**Comment by RigoFlores** [comment]
Aquí los detalles:

- En en encabezado, quitar el renglón de Cliente, ya que nuestro cliente (que en CxP, es el receptor del CFDI), no tiene número de cliente. Está bien que aparezca su RFC y Nombre.
- Las columnas de abono, son para los importes de las facturas y las columnas de cargo, son para reflejar los pagos realizados por nuestro cliente.
- No se refleja el status de la factura del proveedor. El status de un pago capturado es NA.
- En la columna de nombre, rfc se debe reflejar los datos de los proveedores.
- En la columna de número cliente, cambiar a número de proveedor (ahora mismo no se ocupa, se puede dejar para uso futuro o simplemente eliminar)

**Comment by jccastillo0007** [comment]
Listo... solo el tema de los importes... puedes checar y ver si ya estan alineados... si no... dime cuales intercambiar pl.. porque para mi es un desmadre...

**Comment by RigoFlores** [comment]
El tema de las columnas quedó bien. No pude verificar si no se movió el reporte de cartera en CxC, ya que marca internal error en esa opción.
Lo que falta aquí es:

1. No se refleja el status de la factura del proveedor (vigente, vencida o pagada).

2. El status correspondiente al renglón de pago capturado puede ser NA o Pagada o Aplicado. Realmente el pago pues como tal, no tiene un status. Cuando aparece en el reporte, pues ya se hizo

3. En la columna de nombre, rfc se debe reflejar los datos de los proveedores. (recordar que ese reporte puede o no filtrarse por rfc/nombre del proveedor)

4. En la columna de número cliente, cambiar a número de proveedor (ahora mismo no se ocupa, se puede dejar para uso futuro o simplemente eliminar)

![Reporte de Pagos](https://user-images.githubusercontent.com/2912775/57548489-affc2680-7326-11e9-8453-e50ec020b00d.JPG)

**Comment by jccastillo0007** [comment]
checale otra vez

**Comment by RigoFlores** [comment]
El reporte en excel es idéntico, no se refleja ningún cambio.
No recuerdo si en la pantalla se había reportado algo, pero ahí se ve todo bien, excepto que sigue pidiendo  el rfc del proveedor, cuando debe permitir la consulta únicamente por el rango de fechas o incluso sin ningún filtro. A diferencia del reporte general, que ahí aparecería un solo registro por cada proveedor, con todos los abonos y cargos sumarizados en dicho registro, en este reporte de pagos, aparecen cada uno de los pagos (vigentes y pagados)  desglosados uno a uno.

**Comment by RigoFlores** [comment]
voy a cerrar este issue, para abirir uno con los detalles que aún restan
