### ISSUE TITLE
Factura Económica - depuración de pantallas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1523]
En catálogo de productos, eliminar la etiqueta de dice "datos extra"

en catálogo de clientes, eliminar los campos (y reacomodar los que si queden):
numero de cliente
contacto
dias de crédito
limite de crédito
saldo inicial
teléfono
listado de bancos (que ellos lo tecleen directamente)

En pantalla de facturación, eliminar:
sucursal emisor
id
incluir complemento de leyendas fiscales
incluir complemento de CCE
addenda
datos extra 
guardar como factura períodica (leyenda y check box), así como lo de seleccionar fecha recurrente.

en pantalla de consultas eliminar filtro de:
id (el que se ubica a la derecha de fecha final)
usuario

**Comment by RigoFlores** [comment]
Necesito hacer los videos en esas pantallas que son las que mas se usan durante la facturación

**Comment by RigoFlores** [comment]
En la pantalla de facturación, al elegir el tipo de CFDI, solo mostrar:

Factura
Recibo de Honorarios
Recibo de Arrendamiento
Nota de Crédito

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Encontré algo adicional:
Catálogo de clientes:
-Eliminar Captura de Curp
-Cambiar etiqueta, Razón Social por Nombre o Razón Social
-Quitar la captura de datos extra
-Eliminaste la captura de los datos de cuenta bancaria, pero solo se pidió eliminar el listado de bancos. Si se complica déjalo igual que en FT. Aunque realmente el listado de bancos solo ha confundido a los clientes.

Pantalla de Configuración:
-Eliminar captura de CURP y leyenda correspondiente
-Eliminar captura de addenda y leyenda correspondiente
-Eliminar completamente la configuración del correo, o quizás dejar solo la leyenda de "Cuenta de correo para envío de Facturas"
-Eliminar captura de datos extra y leyenda correspondiente.

**Comment by jccastillo0007** [comment]
En el catálogo de clientes no hay datos extras.

El resto, ya esta

**Comment by RigoFlores** [comment]
Ya estamos cerca, a nada:
a) En el catálogo de clientes, mover a la derecha lo de sucursal, y pasar en medio lo de nombre o razón social. Esto es por usabilidad y navegabilidad. 
b) Lo de datos extra, obvio me equivoqué de pantalla, pero se refiere a catálogo de productos. Ahí sigue apareciendo, y no lo vamos a soportar.
c) En la pantalla de configuración, cuando trato de entrar, marca internal error. No puede validar las correcciones.
d) Creo que vale la pena agregar el menú de Administración-Cambio de Pwd, para que puedan cambiar su contraseña, porque ahora mismo queda fija, y es común que la cambien, sobre todo cuando el que estaba a cargo de la facturación, ya no está en la empresa, pero conoce el link y el usuario y pwd, entonces ellos deben poder cambiarla.

**Comment by RigoFlores** [comment]
solo falta el punto a, b y d.

**Comment by jccastillo0007** [comment]
listo en PRU y PRO
