### ISSUE TITLE
Cuando eliges un RFC para hacer recarga, presentar los datos de almacenamiento de CFDI's

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1524]
Necesitamos que se muestre la cantidad de CFDI's almacenados por año, y el promedio de los mismos, SIN CONSIDERAR 2019.
Esto es para saber cuántas facturas tienen almacenadas, y cuánto les tocaría pagar en caso de necesitar el resguardo ilimitado.

**Comment by jccastillo0007** [comment]
Listo, esta solo en PRU, no lo puedo subir a PRO hasta que arregle lo de Optibelt... si alguien contrata, me avsias y yo lo marco en base de  datos

**Comment by RigoFlores** [comment]
ok, solo revisa el promedio, porque presenta un dato raro...
