### ISSUE TITLE
Agregar en el KeyGenerator, un checkbox o similar que indique que es cliente de FE o FT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1525]
Necesitaremos para los usuarios de Factura Económica, identificar cuando son clientes de FE o cuando se trata de clientes FT.
Hoy en día ese combo estaría vacío, ya que todos son clientes FT, pero arrancando la FE necesitamos distinguir cuál es de cual.

**Comment by jccastillo0007** [comment]
listo... esta hasta abajo de los plugins...
Esto esta solo en PRU, no lo puedo subir a PRO hasta que arregle lo de Optibelt... si alguien contrata, me avsias y yo lo marco en base de  datos

**Comment by RigoFlores** [comment]
OK, ese indicador solo será para resaltar que ese cliente nos contrató FE.
Internamente en la aplicación también tendrá efecto?
Es decir, debería impedir el acceso a FT, y solo permitirlo en FE.
Así quedaría finalmente?

**Comment by jccastillo0007** [comment]
correcto

**Comment by RigoFlores** [comment]
ok, ya hay que subirlo a producción... se ocupa
