### ISSUE TITLE
Revisar como está el tema de Retenciones con complemento de Dividendos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1526]
Lo necesitamos para este cliente DMR840730523
Yo intenté hacerlo, pero no me incluye en complemento de dividendos.
Supongo que está en hardcode que pueda emitir el complemento algún cliente en particular, lo puedes revisar pls y darlo de alta.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Favor de agregar este RFC para complemento de dividendos.
CMI0408179R0

Se define en hardcode, correcto?

**Comment by jccastillo0007** [comment]
No se define en hardcode...

con que se llenen todos los campos en pantalla debe funcionar

**Comment by RigoFlores** [comment]
Pues si, al parecer solo es dando de alta la serie RET y capturando todos los datos de la pantalla de Retenciones-Constancia.
Así lo hice y jaló.
Yo creo que antes no estaba así, ya que por ello levanté issues para ello, pero bueno, ahora está así.
