### ISSUE TITLE
FT - Agregar checkbox en catálogo de clientes para crear usuario DescargaT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1527]
Para hacer transparente la creación del usuario de DescargaT, hay que crear el acceso desde el catálogo de clientes de FacturaT.
El usuario y pwd serán el RFC en mayúsculas.
Los datos serán los mismos que aparecen en el catálogo de clientes.

EXCEPCIONES: No se debe crear el usuario indicando la causa, cuando:

a) El RFC del cliente es XAXX o XEXX (rfc genérico nacional o extranjero).
b) Ya existe ese usuario en DescargaT o como cliente de FacturaT

**Comment by jccastillo0007** [comment]
hmmmm cual es el catálogo de clientes de facturat ?

**Comment by RigoFlores** [comment]
Ahora hago diferencia entre FT y FE.
FT es la plataforma que tenemos actualmente con todos nuestros clientes.
Comentaste que sería lo mas simple, agregar ese checkbox en el catálogo de clientes, para crear los usuarios de descargaT. 
Esto es para dar de alta a los clientes de nuestros clientes en descargaT. No olvidar las excepciones

**Comment by RigoFlores** [comment]
En FE, no existirá acceso a DescargaT para los clientes de nuestros clientes. Por ello solo se pidió para FT.
Tenemos que ir definiendo muy bien, porque FT cuesta mas que FE.

**Comment by jccastillo0007** [comment]
Ya aparece este botón en el catálogo de clientes.. pero aún no lo uses, pues estoy haciendo pruebas...

Ojo.. para dar de alta un cliente en descargat, cómo le haces tu?

**Comment by RigoFlores** [comment]
Tengo que acceder a la url de descargat y si no existe el usuario, lo primero es dar click en "Registrarme"... y pues una vez que te registras, entonces ya continuas normal...

**Comment by jccastillo0007** [comment]
listo... que desmadre... asi es como quedo la implementación.

- El único usuario que tiene activada la opción de crear clientes para descargat es la TIA
- El cliente seleccionado en el catálogo de cliente, se dará de alta como un emisor en el descargat, ojo, para esto nos deben pagar ese servicio
- Dicho cliente tendrá acceso tanto a FT como DescargaT
- Todos los clientes del cliente seleccionado, se darán de alta en el descargat como receptores, estos RFC no tendrán acceso a FT solo a DescargaT


Ya esta en PRU, y yo lo probé con tu user FOPR... ojo, solo puedes probar una vez, pues las siguientes veces ya no hará nada

**Comment by jccastillo0007** [comment]
avisame si lo subo a PRO

**Comment by RigoFlores** [comment]
Primero necesito ver de que se trata, ya que no veo cambio alguno en el catálogo de clientes en PRU para la cuenta de la TIA.
Existen varios asegunes:
a) El cliente de nuestro cliente (receptor), podría ser nuestro cliente también (es decir sería emisor para FT y receptor para DT).
b) El receptor de un cliente en particular, podría ser receptor de otro cliente, es decir, ser receptor para dos emisores distintos.
c) Un proveedor de un cliente nuestro (que al final se crea una cuenta en FT con perfil de proveedor), podría ser receptor de cualquier otro cliente.

Todo esto ya estaba jalando. Lo único que se pidió es que desde el catálogo de clientes, se hiciera lo mismo que se hace cuando se registra el receptor en el portal de DT.

**Comment by RigoFlores** [comment]
Ah ya ví que no es un checkbox, sino es el botón de facturar... chiaaaaa.

d) que pasa si le dan nuevamente click a ese botón
e) que pasa con los clientes que se vayan agregando después que ya le dieron click a ese botón?

**Comment by RigoFlores** [comment]
OK, pues yo creo que solo falta pasarlo al keygen, en la pantalla donde se generan las llaves y/o se actualizan los datos del cliente...

**Comment by RigoFlores** [comment]
Y falta lo de no crear la cuenta para XAXX y XEXX

**Comment by jccastillo0007** [comment]
listo, ya esta en pro

**Comment by RigoFlores** [comment]
Entonces, solo para entender porque te pregunté en el wa pero se perdió seguramente...
Desde el catálogo de clientes de la cuenta de la tia, es que se podrá activar esta opción para los clientes?
Pero ese ícono también aparece para toooodos los clientes, ahí que función tendrá? 
Por eso yo decía que en el keygenerator debería aparecer ese botón.

**Comment by RigoFlores** [comment]
?

**Comment by jccastillo0007** [comment]
el icono solo aparecía para la TIA.
pero de todos modos ya moví esa funcionalidad al keygenerator, al momento de cargar folios.

**Comment by jccastillo0007** [comment]
Ojo... el icono se  repite, el de hasta arriba es para el decargat, y el de en medio es para crear la factura de la recarga de folios

**Comment by RigoFlores** [comment]
El ícono de enmedio no jala desde hace muchos meses.
Tampoco la información mostrada en esa sección...
Lo veremos en su momento
