### ISSUE TITLE
Pantalla de Configuración FT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1528]
En la configuración del correo, dejar solo un textbox, con la leyenda:
"Cuenta de correo para el envío:"
Entiendo que solamente con ese parámetro, el correo se enviaría a nombre del ese correo, correcto?

**Comment by jccastillo0007** [comment]
psss ya ni me acuerdo, creo que no... deja lo pruebo, igual y esa funcionalidad se la quitamos no?

**Comment by jccastillo0007** [comment]
ya mejor quite las opciones de email

**Comment by RigoFlores** [comment]
En FT, daría mas argumentos del porqué cuesta mas por aquel lado.
Hice una prueba en producción capturando los datos de la cuenta de correo, y no cambia el correo de envío.
Yo estoy cuasi seguro que eso ya jalaba, o quizás sea desde escritorio.

**Comment by RigoFlores** [comment]
Ya validé en escritorio, y pues no jala tampoco.
Insisto, necesitamos tener argumentos al momento que nos enfrentemos a los clientes, del porqué FT es mas caro que FE.

Hay que activar esta opción.
Que con el parámetro: "Cuanta de correo para envío de CFDI's:", se ocupe como 'el sender' de las facturas. Eso ya lo hacíamos, estoy seguro.

**Comment by jccastillo0007** [comment]
pero eso lo reviso en FT cierto ? para que sea uno de los argumentos de porque cuesta más...

en FE, que sea siempre la TIA

**Comment by RigoFlores** [comment]
correcto, solo para FT.
Para FE, así como ya está...

**Comment by RigoFlores** [comment]
de hecho así lo menciona el título del issue... jeje

**Comment by jccastillo0007** [comment]
listo en PRU, ma;ana lo subo a PRO

**Comment by RigoFlores** [comment]
Lo validé en pruebas, y aunque le capturé un correo 'pato', lo sigue enviando desde el mismo de noreply@email-facturat.com

**Comment by jccastillo0007** [comment]
te mande un correo desde esa cuenta, enviado por la cuenta patito..

**Comment by RigoFlores** [comment]
ya ví lo que pasa... si generas la factura y la envías en ese momento si jala.

Pero si la envías desde Ventas-Consultas, ahí es donde ya no jala

**Comment by jccastillo0007** [comment]
listo...
también lo puse para acuses y cancelación

**Comment by jccastillo0007** [comment]
hoy lo subo a PRO

**Comment by RigoFlores** [comment]
pues algo raro pasó... optibelt, tenía configurado un correo, no sé si pato o no, pero tenía definido un correo y me reportó que no estaba recibiendo ningún cfdi. 
Lo revisé en sendinblue, y aparecía algo así como status aplazado.
Borré ese correo de la configuración y a partir de ese momento empezó a recibir sus CFDI's.

Probé con la tía, y el correo pato que tiene, si está enviando las facturas... en tiempo real... tons ya no entendí que puede pasar con eso.
