### ISSUE TITLE
En el consumo de folios x cliente, no está considerando los de finkok

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1532]
Por ejemplo para este cliente si checas cuántos folios ha consumido en el keygenerator, dice que 0 desde su última recarga, y ya lleva cerca de 1,000
Seguro eso está pasando con varios clientes.
Y también esa debe ser la razón que los consumos diarios que se envían por correo diariamente, no coinciden con los arrojados por el super cueri que enviaste para conocer el consumo.

**Comment by jccastillo0007** [comment]
negativo... el consumo de folios se obtiene de las facturas timbradas... y no de cada pac

**Comment by jccastillo0007** [comment]
pasame el rfc del cliente para revisar

**Comment by RigoFlores** [comment]
Que wey, según yo le había dado copy paste.
Este es el rfc EPN010312GC0

**Comment by RigoFlores** [comment]
![folios](https://user-images.githubusercontent.com/2912775/55799382-d7957000-5a96-11e9-92f9-fc3ce484c782.JPG)

**Comment by RigoFlores** [comment]
El hecho es que si yo ejecuto este cueri que tu me pasaste, el consumo diario NO COINCIDE con lo que se envía diariamente por correo, eso ya lo había reportado. 
Por esa razón, pienso que en ese conteo (el que se envía por correo) no se incluye lo de FINKOK.
Pero bueno, el punto es que ese cliente nuestro EPN01, que es uno de los que está 'alambrado' para que se vaya por finkok, no refleja consumo alguno de folios, y al día de hoy llevará de 800 - 1000 folios consumidos desde su última recarga.

CONSUMO DIARIO
select  DATE_FORMAT(STR_TO_DATE(date,'%d%m%Y%H%i%s'), '%Y%m%d')fecha, status, count(*) from CFDiDetail 
where DATE_FORMAT(STR_TO_DATE(date,'%d%m%Y%H%i%s'), '%Y%m') like '201904' and status = 0 
group by  DATE_FORMAT(STR_TO_DATE(date,'%d%m%Y%H%i%s'), '%Y%m%d'), status;

**Comment by jccastillo0007** [comment]
no ma.... encontraste algo interesante...
Hay varias cosas... 
1. el historico de consumo de folios de los clientes... esta mostrando solo las facturas que se hacen en web, y las facturas que se hacen en standalone, a partir de que se implementó el hecho de que siempre salvamos el cfdi en web. Por lo que clientes standalone medio antiguos... no se esta contabilizando en su resumen de facturas por año... no sé si esto este bien o mal

2. el pinche cliente EPN010312GC0, siempre se va por finkok , y efectivamente no le estabamos contabilizando su consumo de folios... ojo.. solo para este cliente.. el resto de clientes que se van por finkok, dado que facture hoy marca error, en esos casos si se contabiliza bien el consumo de folios..

3. El punto anterior puede explicar la diferencia en la contabilización de folios vs el reporte diario.

4. Ya actualicé el consumo de folios del RFC EPN010312GC0, pinches changos

**Comment by jccastillo0007** [comment]
vale ma....
segùn los queries, ya nos debe mas de 1000 folios 

mira... este es su consumo real por año...
mysql> select DATE_FORMAT(STR_TO_DATE(date,'%d%m%Y%H%i%s'), '%Y')fecha, status, count(*) from CFDiDetail  where status = 0 and emisor = 'EPN010312GC0'  group by DATE_FORMAT(STR_TO_DATE(date,'%d%m%Y%H%i%s'), '%Y');
+-------+--------+----------+
| fecha | status | count(*) |
+-------+--------+----------+
| 2016  | 0      |     1620 |
| 2017  | 0      |     1696 |
| 2018  | 0      |     2001 |
| 2019  | 0      |      940 |
+-------+--------+----------+
4 rows in set (0.78 sec)

Es un total de  6257 timbres

**Comment by jccastillo0007** [comment]
De acuerdo a su consumo de folios... 

mysql> select * from CFDiFolios where emisor = 'EPN010312GC0';
+------+---------------+---------------------+--------------+-----------+-----------+--------+---------------------+
| id   | current_folio | dateOfIssue         | emisor       | fin_range | ini_range | status | date                |
+------+---------------+---------------------+--------------+-----------+-----------+--------+---------------------+
| 3896 |          2279 | 15/05/2017 16:06:49 | EPN010312GC0 |      3500 |         0 |      4 | 14/05/2016 16:06:49 |
| 4966 |          4381 | 16/05/2018 17:21:07 | EPN010312GC0 |      6000 |      3500 |      4 | 16/05/2017 17:21:07 |
| 5936 |          6000 | 18/05/2019 09:41:25 | EPN010312GC0 |      8000 |      6000 |      0 | 18/05/2018 09:41:25 |
+------+---------------+---------------------+--------------+-----------+-----------+--------+---------------------+
3 rows in set (0.00 sec)

**Comment by jccastillo0007** [comment]
Si contabilizas sus folios consumidos reales vs los folios consumidos de cada uno de sus paquetes...
primer paquete consumieron 2279
segundo paquete consumieron 881
tercer paquete, no tiene registro por el error

6257 timbres usados - 3160 timbres si registrados, resulta que no hemos registrados  3097 timbres... y su  último paquete de folios fue de solo 2000, pinches changos..

que hacemos.. ?
ya subi el fix... pero hay que cobrarles k

**Comment by jccastillo0007** [comment]
por lo pronto ya le quite 1500 folios de su último rango... pero aún nos deben

**Comment by RigoFlores** [comment]
Pues yo reporté esto desde que lo ví, hace varias semanas, pero también ha sido ignorado.
El reporte que llega diariamente, no coincide con el cueri.

Este cliente ha pagado por 8,000 folios. Entonces solo hay que actualizar el número actual de la ultima recarga...

**Comment by RigoFlores** [comment]
Por cierto, si hay otros clientes que están alambrados ,para que se vayan por finkok.
Deben estar en el mismo caso.

**Comment by jccastillo0007** [comment]
noup, ya lo revise... estos weyes son los unicos

Han pagado por 8000 folios, pero muchos expiraron, de las primeras dos recargas.. por eso es que tienen saldo deudor

**Comment by RigoFlores** [comment]
según yo no nos deben.
Han consumido 6 mil y fracción.
Han pagado 8,000 mil... tons cuál es su deuda?
Solo hay que asegurar que en el último conteo vaya de acuerdo a lo CONSUMIDO A PARTIR DE SU ÚLTIMA RECARGA..

**Comment by jccastillo0007** [comment]
el tema es que muchos folios expiraron, por eso es que no se contemplan los 8000 que han pagado
a menos que las condiciones sean diferentes con ellos k

**Comment by RigoFlores** [comment]
OK, entiendo lo que dices.
De sus 2 primeras recargas, pagaron 6,000 folios y solo consumieron 3,160
De su última recarga, pagaron 2,000 y han consumido 3,097. Por eso es que dices que nos deben

No tienen condiciones especiales, mas que se van por finkok. Estoy seguro que te solicité algún otro RFC que también se fuera solo por finkok.

Pero bueno, yo como lo veo, es que en total han pagado 8,000 folios y han consumido 6,000 y fracción.
Entonces, pues realmente no deben (aunque los folios tengan vigencia de 1 año), considera que ellos son buenos clientes.
Finalmente si se queda ya como está que le agregaste 1,500 y se termine lo que falta está bien.

El asunto es que sigue sin contabilizar los folios, está con los mismos 1,500 que le ajustaste; ellos consumen diario.

**Comment by jccastillo0007** [comment]
Ok, hoy checo eso… 

Te voy a mandar los otros rfc que se van por finkok también.

**Comment by RigoFlores** [comment]
si, habías comentado que solo ese, pero si estoy seguro que hay mas, al menos uno

**Comment by jccastillo0007** [comment]
Estos son los otros 3 rfc que siempre se van por finkok, entre ellos yo, pero ya me eliminé de la lista

**Comment by jccastillo0007** [comment]
Con respecto a :'EPN010312GC0' 

No ha facturado ayer ni hoy.. por eso sigue igual... seguiremos revisando

**Comment by RigoFlores** [comment]
No apareció la lista de los que se van por finkok....

**Comment by jccastillo0007** [comment]
a que te refieres, ya me confundí...

En el reporte que se manda por correo, se obtienen numero de facturas timbradas, basado en archivos xml y también en la base de datos... puede haber algunas diferencias muy pequeñas, pues el archivo xml siempre se guarda, pero si el proceso de timbrado falla, en la base de datos no existirá ese registro.

en ningún caso se distingue entre facture-hoy y finkok... , el único problema que había es que el cliente EPN no estaba reportando su consumo de folios. pero eso ya quedó arreglado
