### ISSUE TITLE
https:// para la FE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1533]
Creo que necesitamos otro certificado e instalarlo.
Que se necesita para contar ya con ello?

**Comment by jccastillo0007** [comment]
ma;ana compro el certificado y lo configuro

Lunes y martes voy a tener un poco mas de tiempo, pues voy a trabajar desde casa.

**Comment by jccastillo0007** [comment]
oye, voy a tener que crear otro servidor para el factura-economica, ya que no puedo poner otro certificado en el mismo tomcat para la app factura-economica, cómo ves ?

**Comment by RigoFlores** [comment]
ok, pues si no hay de otra, ya que...
y no se puede ocupar el mismo certificado para esa otra aplicación???

**Comment by jccastillo0007** [comment]
noup, porque el certficado es para el dominio...
y no podemos tener dos certificados en el mismo tomcat

**Comment by jccastillo0007** [comment]
ya se esta usando el nuevo server, y con la misma base de datos, ahora solo me falta fijar el certificado que compramos

**Comment by jccastillo0007** [comment]
listo... ya esta el server, con seguridad y usando la misma base de datos que ft

**Comment by RigoFlores** [comment]
oye, y cuánto costo el certificado y el nuevo server??

**Comment by jccastillo0007** [comment]
El certificado fueron los 20 USD que se pagaron con paypal
El server es de los baratos, de 40 USD mensual
