### ISSUE TITLE
Navision - En los pagos realizados en MXN, está incluyendo el tipo de cambio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1534]
Eso ya estaba jalando, pero ahora cuando el pago se realiza en MXN, entonces le incluye el tipo de cambio y eso marca error. El parámetro es: MonedaP que cuando es MXN, no debería reportar esto: TipoCambioP="1.0"

No sé porque se movió esa parte. Lo tenemos para el pago 19PAMX0032 y 19PAMX0033

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www
.w3.org/2001/XMLSchema-instance" xmlns:pago10="http://www.sat.gob.mx/Pagos" Vers
ion="3.3" Serie="19PAMX" Folio="33" Fecha="2019-04-12T15:32:18" Sello="QjB3ldau2
rbKV2Y4Bh6eIZX8hkRaHvFrzvF0Qwy4isPXDAaguszfdM7gkBYE7HHJ+xm455orKa4pPdaZi6x7LQS00
Ys90K6cug9QX0NePMkmiC1/oyOrrbtW4xc9jgTzze86iVbA6t9KPAtfMVGK5aprtbHeFg/429nMLih1x
QLnwCNI0LoWNbiv0+DXSiMUMn3kLv19ENi9XyDLZY8mxB+Cy2L3nctJVTdcYOIVpethV63Qg5mjHZpiS
bZxp3aNPgmbJ40Phxo/T5bGzVNk3FVp0vFU23YfHttzZqN8u8J9cHuKbf8MpZ5MyDA1M4juoAzhQK6BC
UfuSWgevhsQaA==" NoCertificado="00001000000408757869" Certificado="MIIGSzCCBDOgA
wIBAgIUMDAwMDEwMDAwMDA0MDg3NTc4NjkwDQYJKoZIhvcNAQELBQAwggGyMTgwNgYDVQQDDC9BLkMuI
GRlbCBTZXJ2aWNpbyBkZSBBZG1pbmlzdHJhY2nDs24gVHJpYnV0YXJpYTEvMC0GA1UECgwmU2Vydmlja
W8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZ
SBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMR8wHQYJKoZIhvcNAQkBFhBhY29kc0BzYXQuZ29iL
m14MSYwJAYDVQQJDB1Bdi4gSGlkYWxnbyA3NywgQ29sLiBHdWVycmVybzEOMAwGA1UEEQwFMDYzMDAxC
zAJBgNVBAYTAk1YMRkwFwYDVQQIDBBEaXN0cml0byBGZWRlcmFsMRQwEgYDVQQHDAtDdWF1aHTDqW1vY
zEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMV0wWwYJKoZIhvcNAQkCDE5SZXNwb25zYWJsZTogQWRtaW5pc
3RyYWNpw7NuIENlbnRyYWwgZGUgU2VydmljaW9zIFRyaWJ1dGFyaW9zIGFsIENvbnRyaWJ1eWVudGUwH
hcNMTcxMjI5MTYwNzQ3WhcNMjExMjI5MTYwNzQ3WjCB6zEvMC0GA1UEAxMmSS5QLiBJTkdFTklFUklBI
ERFIFBST0RVQ0NJT04gU0EgREUgQ1YxLzAtBgNVBCkTJkkuUC4gSU5HRU5JRVJJQSBERSBQUk9EVUNDS
U9OIFNBIERFIENWMS8wLQYDVQQKEyZJLlAuIElOR0VOSUVSSUEgREUgUFJPRFVDQ0lPTiBTQSBERSBDV
jElMCMGA1UELRMcSUlQMDkwOTI5NEw1IC8gRkVSSjcwMTIyNEtDMzEeMBwGA1UEBRMVIC8gRkVSSjcwM
TIyNEhORVJETjA5MQ8wDQYDVQQLEwZNQVRSSVowggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBA
QCJuRV5hjGyNrQMmoG9lY8AyKFQ1NL81aQIKIdK1dSWv5tqYbR0R7ZsdOevmf3ln9JSBP973z2EyC+Sr
ZDthfPQBb11D+gZmC5L9yvB539H4elPTa7kTapLrZjm/F9G2PfJAiZEHB7O6G4LVV9m7tqm4/XlzGkEr
cmZGgfNQWhoi0RLvFsO8Y+f5WOVg5ODjpYb/CK15uY7WTO1uR5mcnfSqIPRmCjSP/i+5YZFmU+w9dHzg
jqTwYmrT64Q7pWZnCjbB5YIK8mWcoYnTJjT91cXAFRBpSXZs3T2NWDWRtfBb5zWUdi7LI+Iex2QSQJ+4
4a6CJLWk83MS5vyQ/1kD5xNAgMBAAGjHTAbMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgbAMA0GCSqGS
Ib3DQEBCwUAA4ICAQAWrsUYAMJfli3Hx2fz9DE3lormDpwHTPuDSHczO5H/rOV+2pC9gn9BaRv+oaF+N
6/nSdvPXGH6N2X5RclBYickAQoRi5wPq85XZiINvS1IpTdgGnogF5B6+gsT3N7aypzRNoWbQTf4M1cSG
IbDoRAzvYzgxPvK8RD4ji/HU/o5M7IibPigjOEn57LZpXWiyPPH2z+CMicoGpYwkipzojmlRZpDg3N0N
TUryQ5BOzCt1kZaA2lRfKc8oOob5TYXR2Q5eJ/apr+8pt3sed3dVvQRYTk5rh54dqGSTXuUHPF4KvAkW
/9WDXyuX6ZHgP+EohXqoSNBnSK/DES7agz7MUegdr0xp5xMICzFGqv320ipdFvx/ln62AeibXsqZPMRY
05mSLDuyq8rVqOmPRl+DU8CMAf79f3wAK/KOhcIMSFMghj8oVNoCx4jyRbbIwtOtyH44e6b7anc+4Mo0
uUODigEO6rzO0nRGcoH6SoApdi88Bp3r5TiJFEZ0npGKvTOYCGtlgBIkj+Fm+GluKe4b8s269IytTyfU
fTIO+DPIpHRctU4ojVDmqYqyfjhDzQYM4DQQk2TLFCoJwAnbmYi6b4Ty65YbxBUNL+l0frgZq9FQTCiq
eY9gb9wYEYGicQ5PEvTRtLcTlzisim+/vQ9qQhSw6cqQLAyMB1buZpWW1U3qA==" SubTotal="0" Mo
neda="XXX" Total="0" TipoDeComprobante="P" LugarExpedicion="76090" xsi:schemaLoc
ation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cf
dv33.xsd http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pa
gos/Pagos10.xsd">
    <cfdi:Emisor Rfc="IIP0909294L5" Nombre="I.P. INGENIERIA DE PRODUCCION S.A DE
 C.V" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TEM120811761" UsoCFDI="P01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" D
escripcion="Pago" ValorUnitario="0" Importe="0"/>
    </cfdi:Conceptos>
    <cfdi:Complemento>
        <pago10:Pagos Version="1.0">
            <pago10:Pago CtaBeneficiario="044680035048566274" CtaOrdenante="0020
60700099773017" FechaPago="2019-04-11T12:00:00" FormaDePagoP="03" MonedaP="MXN"
Monto="5823.76" NumOperacion="001000" RfcEmisorCtaBen="SIN9412025I4" RfcEmisorCt
aOrd="BNM840515VB1" TipoCambioP="1.0">
                <pago10:DoctoRelacionado Folio="029" IdDocumento="8fb4459e-1ff5-
4d3f-916a-0391f4bd98f6" ImpPagado="5823.76" ImpSaldoAnt="5823.76" ImpSaldoInsolu
to="0.00" MetodoDePagoDR="PPD" MonedaDR="MXN" NumParcialidad="1" Serie="19FVMX"/
>
            </pago10:Pago>
        </pago10:Pagos>
    </cfdi:Complemento>

**Comment by jccastillo0007** [comment]
listo...  tienes forma de probar tu, sin hacerlo con ellos...

**Comment by jccastillo0007** [comment]
lo subi al dropbox... ahora no lo subi a navision

**Comment by RigoFlores** [comment]
Oye, pero porqué se presenta esto de que ya jalaba y 'se descompone'.
En este caso, porqué dejó de jalar algo que ya trabajaba?
Solo nos estamos quemando gacho con el cliente.
Que hay que hacer para evitar esto...?
Ahora en cada posteo de Navision, no sé que se va a tronar con el nuevo rilis...
