### ISSUE TITLE
Problema para generar el 2o pago parcial del cliente OTC131125BL4

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1535]
Te mandé un correo.
La factura 888 tiene un pago asociado, el pago 65.
Pero no aparece en cartera de cliente.
si quieres capturar el segundo pago, esa factura indica que el saldo deudor es el total, es decir no está considerando ese primer pago.
Si consultas la referencia de pago, si aparece pero se ve algo raro, creo que le falta la factura asociada a dicho pago (190109888).

**Comment by jccastillo0007** [comment]
OTC131125BL4  es el emisor o receptor?
este número 190109888 de que es?
la factura 888 es de 116,000 ?

**Comment by RigoFlores** [comment]
OTC es el emisor.
el número de la referencia que se capturó en el pago asociado a la factura 888
116,000 USD es el monto original de la factura, pero el primer pago de 34,800 no se ve reflejado como el pago parcial 1.
Sin embargo si generó ese primer pago, e indica en el documento correspondiente que el saldo insoluto es 81,200, es decir le resta los 34,800.00 al monto de la factura.
Pero cuando quieres capturar el 2o pago, no aparece registrado el primer pago.

**Comment by RigoFlores** [comment]
te mandé por correo la evidencia...

**Comment by RigoFlores** [comment]
se podría pensar que borraron el pago, pero si consultas esa referencia en CxC-consulta de cobros, si aparece.
El CFDI del pago correspondiente si aparece como vigente.
A menos que hayan intentado cancelar y que lo haya rechazado el sat, pero se borró algo en el registro del pago, que lo dejó inconsistente

**Comment by jccastillo0007** [comment]
parece que ya quedo listo... el petch es que por alguna razon el tracking id es nulo para las facturas de este rfc., sabes como generan sus facturas?

en la busqueda de pagos.. se hace por medio del tracking id o uuid... pero como el tracking id es nulo, por eso no los econtraba... ya lo puse como opcional..

**Comment by RigoFlores** [comment]
Borré uno de los 2 pagos de la tabla Payments.
En cartera x cliente, no se refleja el único pago que quedó.
Ahora, si intento capturar el segundo pago, y le doy vista previa, el primer pago no lo toma en cuenta, e indica que lo que estoy capturando es el primer pago apenas.

![capturaChueca](https://user-images.githubusercontent.com/2912775/56629478-14bf3d80-6613-11e9-8f81-eb3fcfd3548b.JPG)


![capturachueca2](https://user-images.githubusercontent.com/2912775/56629487-20126900-6613-11e9-9714-32f4d32457ed.JPG)

**Comment by jccastillo0007** [comment]
listo, ya se ve el pago en el reporte de cartera por cliente

**Comment by RigoFlores** [comment]
ok, ya se compuso, pero lo mas interesante es saber que pasó?
Es decir como llegamos a eso???
