### ISSUE TITLE
Navision - cambiar la hora que se registra en la tabla Factura-T

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1537]
La hora que ponéis en los registro de factura-t tiene que ser: 12:00:00 a.m. Ahora estáis marcando 12:00:00 p.m.

**Comment by jccastillo0007** [comment]
ya le hice un cambio... pero la verdad no se si jale... porque no se como lo interpreta SQLServer... puedes probar con alguna factura, pago o NC

**Comment by RigoFlores** [comment]
pues no, solamente subiendo el cambio. 
Voy a hacerlo

**Comment by RigoFlores** [comment]
el lunes sabremos que onda

**Comment by RigoFlores** [comment]
no me han dicho nada, supongo que ya quedó... cualquier cosa, lo reabrimos
