### ISSUE TITLE
CxC - Ingresar cobro paso 2, dar opción de buscar por nombre

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1538]
Además del RFC, dar opción de buscar por nombre o rfc.
El nombre puede quedar arriba de rfc y número de cliente

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Hay que conectar el rfc con el nombre, así como en la pantalla de catálogo de clientes o en la pantalla de facturación.
Esto es, si eliges el rfc, el nombre se actualiza, y viceversa.

Ahora mismo lo que está pasando, es que puedo elegir un nombre, y luego un rfc que no corresponde, y así queda, chueco.

No olvidar que cuando el RFC cambia, pues también se reinicia el número de cliente.

**Comment by RigoFlores** [comment]
Además que no relaciona el nombre con el RFC, si quiero capturar un cobro solo eligiendo el nombre del cliente, no muestra el número de cuenta capturado del cliente.
Es decir, está desligado el nombre del RFC. Debe existir esa liga.

**Comment by jccastillo0007** [comment]
listo... en pru

**Comment by RigoFlores** [comment]
Ya quedó, pero es posible:
a) Limitar el ancho del combo donde se muestra el nombre... o
b) reacomodar esos campos de la siguiente manera
*Arriba nombre.
*Abajo rfc, numero de cliente y vigencia.

Mira como se ve de gachio... y hay clientes que tienen nombres mucho mas largos.

<img width="712" alt="ingresarCobro" src="https://user-images.githubusercontent.com/2912775/57869108-ef64c000-77c9-11e9-806a-e4bd7d5baffc.PNG">

**Comment by RigoFlores** [comment]
Aquí en pruebas, con la cuenta de TCM.
Di de alta un nombre alterno para el cliente FOPR, le asigné el número de cliente 11.
Hoy hice una factura con ese nombre alterno.
Si lo elijo en CxC - ingresar cobro, muestra facturas adicionales a la única que debería mostrar; que es la que hice hoy.
Total que algo que parecía muy simple, le ha pegado a todo por todos lados.
Solo era que al elegir el nombre, mostrara su RFC, y viceversa. Todo lo demás no se mueve.
Aquí lo nuevo es el nombre, pero si causará tanto problema, lo regresamos... creo que está todo movido o quizás lo que pasa es que no estamos considerando el número de cliente correcto en el query de la consulta.

**Comment by jccastillo0007** [comment]
ya acomode el nombre en la parte de arriba, de hecho lo hice ayer cuando vi que era el mismo caso de cartera de clientes... pero ya no subí el último release.
 Que dramático eres... simplemente no tomaba en cuenta el número de cliente

**Comment by RigoFlores** [comment]
Pues sigue el desamdre. Para en pru, emisor PCM. El RFC receptor FOPR, que tiene números de cliente 1 y 11... si yo elijo el cliente 11, me muestra algunas facturas que no corresponden, y además NO ME MUESTRA una factura que hice hoy (FEE-16) para ese número de cliente.

De hecho no encontré en el reporte de Ventas-Consultas, que se incluya el número de cliente. 
Hay que agregarlo para darle traza a este issue, ya que estoy a ciegas con respecto a cuál factura le corresponde cuál número de cliente.

Aplica para ingresar cobro y para cartera de cliente

**Comment by jccastillo0007** [comment]
listo, ya esta en pru y pro

**Comment by RigoFlores** [comment]
Tiene que ser como en catálogo de clientes, o en la pantalla de facturación.
Esto es, tanto el RFC, como el nombre, deben mostrarse en orden alfabético.
Ahora mismo, solo el RFC aparece en orden.
El nombre aparece desordenado, de tal manera que no es funcional para buscar algún cliente por nombre.

**Comment by jccastillo0007** [comment]
chiaaaa , listo
