### ISSUE TITLE
CxC - Cartera de cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1539]
Además del RFC, dar la opción de buscar por nombre.
esto es para que el usuario pueda buscar por rfc o por nombre, lo que le quede mejor.

**Comment by jccastillo0007** [comment]
chiaaaaa

**Comment by RigoFlores** [comment]
En pruebas lo intenté validar, pero al entrar a esa opción del menú, con la cuenta de la tia, marca internal error

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Hay que conectar el rfc con el nombre, así como en la pantalla de catálogo de clientes o en la pantalla de facturación.
Esto es, si eliges el rfc, el nombre se actualiza, y viceversa.

Ahora mismo lo que está pasando, es que puedo elegir un nombre, y luego un rfc que no corresponde, y así queda, chueco.

No olvidar que cuando el RFC cambia, pues también se reinicia el número de cliente.

**Comment by jccastillo0007** [comment]
listo en pru

**Comment by RigoFlores** [comment]
3 detalles que vi:

1) Cuando el rfc/nombre tiene asociado un número de cliente (o varios como en el caso de optibelt), solo debe mostrar ese número de cliente, o en su caso NO mostrar ninguno. Ahora mismo, como que algo anda chueco ahí, ya que a veces lo muestra bien, otras muestra de más, y otra no muestra cuando si debe (jeje). Con la cuenta de TCM970625MB1 en pruebas, este rfc FOPR tiene el número de cliente 1, y de repente se muestra así:

<img width="452" alt="numeroCliente 2" src="https://user-images.githubusercontent.com/2912775/57867532-efaf8c00-77c6-11e9-987d-8ec8bcb9b254.png">
<img width="472" alt="numeroCliente" src="https://user-images.githubusercontent.com/2912775/57867533-efaf8c00-77c6-11e9-88f6-09830ddb4da3.png">

**Comment by RigoFlores** [comment]
2) si consulto cartera de cliente, sin elegir nombre/rfc, marca internal error. Esa consulta para mí es de lo mas común, así identifico a todos los clientes que nos deben.

3) El campo nombre, de preferencia ponerlo hasta arriba y solo, ya que con nombres muy largos se deforma la pantalla muy gacho. Mejor que queda solo ese campo arriba de RFC y número de cliente, y si se pudiera limitar el tamaño del combo, mucho mejor.

**Comment by jccastillo0007** [comment]
listo..., ya están los 3 puntos...

Ojo, para el caso 1, el combo de números de clientes, muestra todos los números de cliente... cuando eliges un rfc, se auto selecciona su respectivo número de cliente y nombre
si eliges un nombre, se auto selecciona el rfc y número de cliente... y  asi....

**Comment by jccastillo0007** [comment]
todo lo subo a pro el fin de semana

**Comment by RigoFlores** [comment]
Pues no, algo quedó chueco. El reacomodo ya está, se ve mucho mejor. Bien.
Cuando eliges nombre o rfc, si te pone el número de cliente que corresponde. Bien.

Peeeero..
Una vez que eliges cualquier RFC, aunque te pone su número de cliente, si le das click al listado, te muestra todos, lo cual no debe ser, solo debe mostrar la lista de los números de cliente relacionados a ese RFC.
Otra cosa que pasa, es que si le das consultar, no muestra ningún resultado. Solo muestra resultados con el cliente con número de cliente 1. Supongo yo que se queda en memoria con ese número de cliente, y cuando consultas con cualquier otro rfc, no te muestra nada en el resultado, aunque si debería.

**Comment by RigoFlores** [comment]
De hecho no había que moverle nada, excepto que cuando eligieran por nombre, lo asociara a su RFC. De ahí en adelante todo igualito.
Y si elegían por RFC, ahí apareciera el nombre relacionado.
Eso era todo, y ahora yo creo que todo está desajustado. No lo podríamos subir así, ya que optibelt se volvería loco.
Incluso CxC-Ingresar cobro, también se desajustó ya.

**Comment by jccastillo0007** [comment]
listo en pru y pro

**Comment by RigoFlores** [comment]
El nombre de los clientes lo muestra sin orden alguno.
Tanto RFC como nombre, deben aparecer en nombre alfabético.

**Comment by jccastillo0007** [comment]
chiaaa , listo
