### ISSUE TITLE
Las facturas emitidas en FE, no se ven en FT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1540]
No será lo mas común, pero para clientes que pasen de un lado a otro, será necesario.

**Comment by jccastillo0007** [comment]
Yo si pude ver facturas de mi rfc... simplemente filtrando por fecha

**Comment by jccastillo0007** [comment]
revise con mi rfc, con el tuyo y con la TIA, y si se ven todas las factuas
chiaaaa

**Comment by RigoFlores** [comment]
el 29 de marzo, se emitió una factura desde FE, con la cuenta de la tia... por 97 mil pesos, algo así...
esa SE EMITIÓ DESDE FE
esa no se veía en FE, no aparecía ni el PDF, ni el XML... estoy seguro de ello

**Comment by RigoFlores** [comment]
anexo evidencia, lo acabo de volver a verificar... desde FT no se ve lo emitido en FE..

![FE no se ve en FT](https://user-images.githubusercontent.com/2912775/57183488-49cd5a80-6e73-11e9-9518-9e9d302f50ce.JPG)

**Comment by jccastillo0007** [comment]
el registro en base de datos si se ve... en ambos portales.

Supongo que te refieres solo al xml y pdf... en ese caso, no se ven porque están almacenados en diferente servidor

**Comment by RigoFlores** [comment]
Correcto, me refiero al XML y PDF, ya que antes si se veían.
Entonces haber cambiado de server la FE nos pegó ahí.
OK, tons no hay mucho que hacer....
