### ISSUE TITLE
Recibo de Nomina - no está enviando el subtotal al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1541]
Me comentan que en algunos casos, tampoco el monto del descuento.
Yo generé un recibo hoy en producción con la cuenta de la tia, y si ves el PDF, no aparece el total de percepciones, que corresponde a la variable de subtotal.

**Comment by jccastillo0007** [comment]
Verifique en PRU y PRO, busque el log del recibo que generaste, y si va el subtotal... debe ser algo en la plantilla

Anexo pedazo del log que se va al jasper

2019-05-02 14:53:08,777 DEBUG [https-jsse-nio-8443-exec-51] (CFDBusinessLogicProvider.java:327) - com.efacturat.core.util.jasper.beans.JasperCFDBean@4eb77cbc[nombreEmisor=TECNOLOGIAS DE INFORMACION
 APLICADA SA DE CV,rfcEmisor=TIA101020BP4,correoEmisor=,telefonoEmisor=,calleFiscal=FRAY LUIS DE LEON,noExteriorFiscal=3051,noInteriorFiscal=29,coloniaFiscal=CENTRO SUR,localidadFiscal=,referenciaF
iscal=,municipioFiscal=QUERETARO,estadoFiscal=Querétaro,paisFiscal=MEXICO,cpFiscal=76090,nombreExpedidoEn=,calleExpedidoEn=,noExteriorExpedidoEn=,noInteriorExpedidoEn=,coloniaExpedidoEn=,localidadE
xpedidoEn=,referenciaExpedidoEn=,municipioExpedidoEn=,estadoExpedidoEn=,paisExpedidoEn=,cpExpedidoEn=,nombreReceptor=JUAREZ MORALES EDGAR RAMIRO,rfcReceptor=JUME890620KB3,correoReceptor=,calleRecep
tor=,noExteriorReceptor=,noInteriorReceptor=,coloniaReceptor=,localidadReceptor=,referenciaReceptor=,municipioReceptor=,estadoReceptor=Querétaro,paisReceptor=MEXICO,cpReceptor=,usoCfdi=P01.Por defi
nir,tipoRelacion=,residenciaFiscal=,cfdisRelacionados=,numRegIdTrib=,tipoCFDi=Nomina,nombreCF=RECIBO DE NOMINA,regimen=601.General de Ley Personas Morales,fechaExpedicion=2019-05-02T14:53:07,lugarE
xpedicion=76090,imagenAlterna=/eFacturaT/customers/TIA101020BP4/files/cbb_images/NOM120_TIA101020BP4_JUME890620KB3_02May2019_145307.png,imagenLogo=/eFacturaT/customers/TIA101020BP4/setup/LogoFactur
a.jpg,leyendaPDF=ESTE DOCUMENTO ES UNA REPRESENTACION IMPRESA DE UN CFDI,cadenaOriginal=||1.1|78604298-2d85-4b85-bc97-8f29b0f33a63|2019-05-02T14:53:08|CAD100607RY8|jnHBdSYDeZbnVwNCjLXFjGid/r9pqFWh1
2X5jBAGKqoBgsK1ca8igmiUAV7hTC4tAORuFlFNU6HgXZg8j/5YhSEE+ZmD+MFSlzHqCqtpzzhYZkAXVWeI8U91BSKcf3BkBMZKWTi4zStFX+yXdxEZOvb0zxyKRZaaJmBAd4nC0Gf8QM6Jn5HteuKlCWzQ5B5KT2Kgd7gndWv3veHv0POI4smnLqMYNFpgK83Abt
aSW7zOkeGatAQDQjaG/cd2Y1jnwumtkanVCIoJ7E4oGE8i8IGj6B3n9fhFRTYncIRaM9kY0gPpTFg7d7FHRDLEvBEhnOB6oCNMTSsaD12Gi8RHqA==|00001000000406144089||,marcaAgua=<null>,formaPago=99.POR DEFINIR,metodoPago=PUE.Pa
go en una sola exhibición,condicionesPago=,moneda=MXN,tipoDeCambio=$1.00,folioSAT=78604298-2d85-4b85-bc97-8f29b0f33a63,noCertificadoSAT=00001000000406144089,selloSAT=bG2QGRfdKLvmeZk4iJPyG4o8b/ZZrf6
j/34UzmUWSCABJxytZciL2ytoo3VgV8HB29zd8K6KD3qmorF2WtXRWYOUeVEO74oY4l9cB/EkWxzHHCIA5U/AVXeZw3Lg8x1mzIPX4XZrtCxhkGAIfrs+zNutQdK0+Mleh40cyw7KVhqxUNRduXj2T9QXcihxOqJoh4A1/euCsoB7juhWPdgrLhFaxy/SIyzl/93V
VLIV4/uJXfO5PD/EgDEIpJn0dPrNnmtb47AuLUMg8qZn5+qeJiWLC6RhEWzOdULMFyDThE7Ej0bQcFJay6qpb7b+80mKElurG4OgmRgik/8kq67ceg==,fechaCertificacion=2019-05-02T14:53:08,noCertificadoEmisor=00001000000403834481,
selloEmisor=jnHBdSYDeZbnVwNCjLXFjGid/r9pqFWh12X5jBAGKqoBgsK1ca8igmiUAV7hTC4tAORuFlFNU6HgXZg8j/5YhSEE+ZmD+MFSlzHqCqtpzzhYZkAXVWeI8U91BSKcf3BkBMZKWTi4zStFX+yXdxEZOvb0zxyKRZaaJmBAd4nC0Gf8QM6Jn5HteuKlC
WzQ5B5KT2Kgd7gndWv3veHv0POI4smnLqMYNFpgK83AbtaSW7zOkeGatAQDQjaG/cd2Y1jnwumtkanVCIoJ7E4oGE8i8IGj6B3n9fhFRTYncIRaM9kY0gPpTFg7d7FHRDLEvBEhnOB6oCNMTSsaD12Gi8RHqA==,folio=120,serie=NOM,datoExtra1=,datoE
xtra2=,datoExtra3=,datoExtra4=,datoExtra5=,datoExtra6=,datoExtra7=,datoExtra8=,datoExtra9=,datoExtra10=,datoExtra11=,datoExtra12=,datoExtra13=,datoExtra14=,datoExtra15=,datoExtra16=,datoExtra17=,da
toExtra18=,datoExtra19=,datoExtra20=,products=[com.cfd.shared.utils.jasper.JasperProductBean@705e4303],numeroProductos=1**,subtotal=$1,292.00**,montoDescuento=$76.00,motivoDescuento=,subtotalSD=$1,216.
00,sumatoriaTraslado=$0.00,subtotalConTraslado=$1,292.00,sumatoriaRetencion=$0.00,total=$1,216.00,totalConLetra=MIL DOSCIENTOS DIECISEIS  MXN 00/100 M.N.,baseTrasladoIva1=,baseTrasladoIva2=,baseTra
