### ISSUE TITLE
reordenar los menús de FT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1543]
Los traemos hechos un revoltijo... ahora que estoy tratando de describir la plataforma, me doy cuenta de ello. Según yo deberían quedar así:

Catálogos  (generales a la aplicación)

Ventas   (emisión de facturas  notas de crédito)
CxC       (captura de pagos de facturas y emisión de pagos)

Compras  (subir facturas recibidas, y emisión de egresos, que son gastos/pagos sin cfdi)
CxP     (registro de facturas pagadas y por pagar a proveedores
Buzon-T  (aceptación o rechazo de cancelación de facturas de proveedores)

Nomina  (otro tipo de CFDI)
Retenciones  (otro tipo de CFDI)

Addendador (servicio aislado de lo anterior, aplica para facturas emitidas)

Administración  (configuración y usuarios)
KeyGenerator (solo la TIA).

y bueno el DescargaT es aparte de todo ello, tiene que ver con los receptores.
Y el menú de Compras, al cual pueden acceder los proveedores, siempre que los den de alta.

**Comment by RigoFlores** [comment]
Cuanto terminemos CxP, y si le agregamos almacenes e inventarios, prácticametne ya tendríamos un ERP

Le faltaría POS, Bancos, RH... pero esos módulos no son muy comunes, bueno el POS si que se ocupa en todos lados...

**Comment by jccastillo0007** [comment]
donde queda proveedores y contabilidad económica?

**Comment by RigoFlores** [comment]
Proveedores???... según yo eso está en catálogo de proveedores, junto con lo de Compras... o que opciones tiene ese menú (yo no lo veo en ningún lado)

Contabilidad Electrónica, queda en standby. En dado caso, tendrías que ponerlo debajo del addendador.

**Comment by jccastillo0007** [comment]
es que hay que entrar con usuario proveedor.

El resto ya esta

**Comment by RigoFlores** [comment]
jaja, cuando entras como proveedor, ese menú es el único que se muestra. 
Lo puedes poner al principio... o al final, será lo mismo.... jeje
