### ISSUE TITLE
Subir videos tutoriales a FE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1544]
La capacitación principal que se ocupa en la FE, es la de los siguientes videos. 
Entonces para que tengan la ayuda en línea, favor de agregarlo a la pantalla que corresponda, Así como en algún momento se agregaron los de FT:

CÓMO AGREGAR UN PRODUCTO (catálogos-productos)
https://youtu.be/4q4X5J8yrWg

como agregar un cliente:  (catálogos-clientes)
https://youtu.be/gJ3Ysm4iIZQ

como generar una factura  (cfdi-facturas)
https://youtu.be/U7LxRDP8P8Q

cómo cancelar una factura  (cfdi-consultas)
https://youtu.be/Wyv18j5XRgM

como generar un recibo electrónico de pago
https://youtu.be/Y-fAxht_NPY  (CFDI-PAGOS)

**Comment by jccastillo0007** [comment]
listo...

no maaaaa, los videos que ya estaban en la aplicación, apuntaban a videos de FT

**Comment by jccastillo0007** [comment]
ya puse los videos... pero no se ven... no se porque... deja reviso

**Comment by jccastillo0007** [comment]
solo me faltan consultas y pagos... porque antes no tenían video.

**Comment by RigoFlores** [comment]
Como dices, falta agregar consultas y pagos.
También eliminar, el video del menú de catálogo de impuestos, que también apuntan a FT.

Finalmente subirlo a pro, ya que solo se encuentra en PRU.

**Comment by jccastillo0007** [comment]
ya eliminé el de impuestos, addendas y nómina... ajuste la resolución... solo falta consultas y pagos

**Comment by jccastillo0007** [comment]
todo lo subo a pro el fin de semana

**Comment by jccastillo0007** [comment]
listo, ya están los videos que faltaban

**Comment by RigoFlores** [comment]
ok, hay que subirlos a pro
