### ISSUE TITLE
CxP - Reporte de pagos - no permite generar el reporte si no eliges RFC de proveedor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1546]
Como ya hemos platicado, debe de permitir generar el reporte sin necesidad de elegir RFC del proveedor.
Imagínate que queremos reportar a los condominios, los pagos que se hicieron en abril.
Entonces lo único que elegimos son pagos realizados del 01 al 30 de abril.
Ahí mostrará todos los pagos realizados, sin importar si fueron 2 o mas pagos al mismo proveedor.

**Comment by jccastillo0007** [comment]
sirve si al reporte de pagos general le pongo un filtro por fecha ?

**Comment by RigoFlores** [comment]
Ya mezclase temas... pero bueno, si serviría AL REPORTE GENERAL DE PAGOS, agregarle filtros por rango de fechas... sip

**Comment by jccastillo0007** [comment]
es  que al reporte general de pagos... le pongo las fechas, y ya se resuelve lo que buscas

**Comment by RigoFlores** [comment]
La diferencia es:

El reporte general te entregará UN SOLO REGISTRO, con el monto de tooooodas las facturas de cada proveedor, así como la suma de toooodos los pagos realizados. Si le pones período de tiempo, pues serán los que caigan dentro del rango de fechas. Pero es un solo registro.

Por otro lado, sn el reporte de pagos... si no se elige proveedor, te dará un desglose detallado de CADA PAGO REALIZADO A CADA PROVEEDOR. Por ejemplo, si durante abril pagaste 2 facturas al mismo proveedor, te aparecerán 2 registros para ese proveedor.

**Comment by jccastillo0007** [comment]
ya le quite el constraint de proveedor o número de proveedor, checale

**Comment by RigoFlores** [comment]
OK, genera el reporte, pero falta colocarle la columna de status.
Lo abriré en otro issue
