### ISSUE TITLE
CxP- Reporte de Pagos - manejo de filtros vigente, vencida o pagadas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1547]
Si el filtro es vigentes, vencidas o ambas, deberá presentar todas las facturas pendientes de pago que cumplan la condición elegida. Si se eligió un rango de fechas, **se toma en cuanta la fecha de emisión de las facturas de los proveedores**. Si no se elige período, se mostrarán todas las facturas que cumplan la condición.

**Si el filtro es de pagadas**, entonces se mostrarán las facturas pagadas y sus pagos relacionados. Si se incluye un rango de fechas... para este filtro... **se deben considerar las fechas de los pagos y no las fechas de las facturas**.  (fecha de pago, OJO, no es lo mismo que fecha de registro de pago, sino la fecha cuando se hizo el pago. Yo puedo registrar hoy 16 de mayo, un pago que realicé el pasado 10 de mayo; la fecha de pago es 10 de mayo)

**Si no se elige ningún filtro de vigentes, vencidas, pagadas... las fechas que se considerarán (en caso de haber elegido un rango de fechas) son las de las facturas.**

**Comment by RigoFlores** [comment]
**Aplicar la fecha de pago cuando el filtro sea pagadas**, precisamente es para que pueda conocer los pagos realizados en el rango de fechas elegido.
Pensando en condominios, yo quiero conocer los pagos realizados durante el mes de abril por ejemplo, pero quizás ahí pagué algunas facturas de marzo, sin embargo si se requiere conocer de dicho pago.

**Comment by jccastillo0007** [comment]
demasiado complejo.... basado en las fechas...

no puedo basarme en la fecha de los pagos, para facturas pagadas... ya que para leer los pagos primero debo conocer las facturas... una vez que tenga la factura, voy a leer los pagos de esas facturas, y  se crea una dependencia circular...

**Comment by RigoFlores** [comment]
Ok, entonces tendremos que generar ooootro reporte, así como en CxC, que solo se enfocaba a los pagos. 
Es que si te pones a revisar los requisitos para un reporte de pagos realizados, las fechas de las facturas pasan a un segundo término. Si quieres conocer los pagos realizados en un rango de fechas, entonces se debe considerar las fechas de pagos, no la de las facturas. Que tal si este mes, pagaste una factura del año pasado de 100,000 pesos ... no aparecería en tus egresos, lo cuál sería un grave problema.

Cómo ves, entonces generamos otro reporte, para que este se quede con fechas de la factura?

En el caso de facturas de proveedores no pagadas, obvio ahí si entra la fecha de la factura.
Pero para el filtro de pagadas, ahí si se ocupa la fecha del pago.

**Comment by jccastillo0007** [comment]
ok, hay que crear otro ticket, definiendo lo que se solicita

**Comment by RigoFlores** [comment]
ok, abriré otro.
Mientras tanto, de este issue, tenemos pendiente que muestra bien el filtro de pagada, vencida o vigente de manera individual. Si se elige el filtro de 'vigente mas vencida' no muestra nada...

**Comment by jccastillo0007** [comment]
listo pru y pro
