### ISSUE TITLE
CxP - Cartera de Proveedor, no muestra correctamente los EGRESOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1548]
En pruebas con la cuenta de la TIA, he generado y registrado pago de 2 egresos.
Recordar que el EGRESO es como una remisión pero del lado de compras. Por ejemplo para registrar salida de lana, sin factura de por medio. El mas claro ejemplo, es caja chica. 

Entonces tenemos los EGRESOS con folios 1 y 2, pero los muestra como si fueran facturas y no muestra el pago asociado. Así los muestra (INCORRECTO).

<img width="390" alt="egresoPagado" src="https://user-images.githubusercontent.com/2912775/57895021-15f91a00-780f-11e9-9750-0a70f060aa72.PNG">

Así los debería mostrar (CORRECTO), pero la clave en lugar de FA (Factura), es EGRESO.

<img width="446" alt="facturaPagada" src="https://user-images.githubusercontent.com/2912775/57895084-6bcdc200-780f-11e9-9c7a-dc4fd39b6cd7.PNG">

**Comment by jccastillo0007** [comment]
listo pru y pro

**Comment by RigoFlores** [comment]
Ya muestra como referencia EGRESO, bien.
Sigue sin mostrar los pagos asociados a los egresos. 
Hoy emití un egreso en pruebas (folio 3), con la cuenta de la tia. El RFC del proveedor es XAXX... y capturé el pago cuya referencia es "cheque 125"
Pero no lo muestra en el reporte. Es decir, aunque indica que está pagada, no muestra el registro del pago. 

<img width="809" alt="reportePagos" src="https://user-images.githubusercontent.com/2912775/58191826-03566900-7c85-11e9-9a4a-a0955b9a6995.PNG">

**Comment by jccastillo0007** [comment]
Este reporte es el reporte general de pagos ?

**Comment by RigoFlores** [comment]
jaja... nop, antes se llamaba reporte de pagos, pero hace poco lo nombramos correctamente y corresponde a Cartera de Proveedor.

**Comment by RigoFlores** [comment]
Este problema sigue.
Capturé un egreso en pru, menú compras-egreso, con el folio 5 por 1160.00, proveedor XAXX.
Luego en menú CxP-Ingresar Pago, capturé el pago asociado  ese egreso, con la referencia "cheque 126".
Al generar el reporte de cartera de proveedor, para ese proveedor, muestra solo los egresos, indica que están pagados, pero los pagos asociados no se reflejan como un registro, y tampoco se considera en el cálculo del saldo.

<img width="869" alt="carteraProveedores" src="https://user-images.githubusercontent.com/2912775/59553923-c9b20e80-8f61-11e9-80ce-0200fdcbc40b.PNG">

**Comment by RigoFlores** [comment]
Supongo que cuando se arregle este issue, se arreglará también que en reporte genereal, tampoco considera para propósitos del saldo, los pagos realizados a los egresos.

**Comment by jccastillo0007** [comment]
esto ya esta listo, falta ver lo del pago del egreso... pero no encontre nada con la referencia "cheque 125"

**Comment by jccastillo0007** [comment]
si hay algo que falta, mejor cierra etse ticket y abre otro.. ya que se hizo un desmadre
al menos en mi mente retorcida

**Comment by RigoFlores** [comment]
si quieres abro otro, pero sería exactamente igual al primer comentario...
Un EGRESO es para soportar una salida de lana, SIN FACTURA. Es el equivalente a una remisión del lado de ventas o CxC.
Imagina que sacarás un cheque de caja chica.
Entonces generas en el menú de Compras-Egresos, un EGRESO por el monto de la salida de dinero.
Luego en CxP-Ingresar Pago, ahí se captura el 'pago' (realmente salida de lana por la caja chica).

OK, pues el tema, es que ese pago realizado a un egreso, no se muestra en ningún reporte de CxP.
No sucede así, cuando capturas un pago a una factura de un proveedor.
Si no encontraste nada con la referencia 'cheque 125", entonces eso confirma el issue... EN CXP, NO SE ESTÁN REGISTRANDO ESOS PAGOS O SALIDAS DE LANA, HACIA UN EGRESO. (EGRESO ES UN DOCUMENTO QUE AMPARA SALIDA DE LANA, SIN FACTURA).

Si quieres lo platicamos mejor.

**Comment by RigoFlores** [comment]
en producción, con la cuenta de la tia, capturé el egreso 1, 2 y 3. 
Por cierto, eso fue porque no encontraba la plantilla y el EGRESO 1 y 2, no tienen PDF asociado. Quizás habría que implementar la 'cancelación' o edición o borrado de un egreso mal capturado...

Total, que solo el EGRESO 3, generó correctamente el PDF.
El reporte asociado a los egresos lo muestra así:

<img width="866" alt="CARTERA_DE_PROVEEDORES" src="https://user-images.githubusercontent.com/2912775/59723276-ae5a3400-91eb-11e9-80fb-f0246af15532.PNG">

**Comment by RigoFlores** [comment]
y debe mostrarlo así:

<img width="746" alt="CARTERA_DE_PROVEEDORES" src="https://user-images.githubusercontent.com/2912775/59723447-4bb56800-91ec-11e9-82c7-c1348d366547.PNG">

**Comment by RigoFlores** [comment]
si consultas el pago en CxP-Consulta de Pagos, con referencia 'RENTA JUNIO 2019', si aparece un resultado, es decir, si se guarda de alguna manera ese pago, pero no se refleja en los reportes
