### ISSUE TITLE
Cancelación en web - no puede reintentar una cancelación previamente rechazada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1549]
Cuando una factura se intenta cancelar y el receptor la rechaza, ya no acepta un segundo intento de cancelación.

11 CA24 - Orden de cancelacion del CFDI previamente registrada.59418241 Estatus : Cancelación rechazada por el receptor

Una factura que ha sido rechazada en su primer intento, realmente queda como una factura cancelable nuevamente.
No sé si tengamos que ocupar otro método o que estará pasando?

en producción puedes revisar con: USUARIO Y PWD: EASJ5902096V9, factura 321

**Comment by jccastillo0007** [comment]
Este defecto lo arregló facture hoy

**Comment by RigoFlores** [comment]
ok, lo dejaré abierto para validarlo.
Esta prueba tarda días, ya que debe pasar algún tiempo, antes de que la factura se vuelva cancelable con aceptación

**Comment by RigoFlores** [comment]
pues no, no hizo algo distinto.
Una factura que yo le emití a la tía: folio 3 del 23 de mayo.

Desde la plataforma, con mi cuenta, la cancelé la primera vez.
Desde la plataforma, con la cuenta de la tia, rechacé la solicitud de cancelación.
Desde la plataforma, con mi cuenta, la intenté recancelar... el mensaje es el mismo:

11 CA24 - Orden de cancelacion del CFDI previamente registrada.65280141 Estatus : En espera de aceptación

Si entro al portal del SAT, donde se cancelan las facturas, con mis credenciales de persona fisica, ahi indica :

Estatus de Proceso de Cancelación:  Solicitud Rechazada

Pero en definitiva, desde la plataforma, no lo está reintentando, o no sé que pasa.
Que hacemos???

**Comment by jccastillo0007** [comment]
contesta el correo donde nos dicen que quedo corregido... con los datos de esta nueva factura...

**Comment by jccastillo0007** [comment]
aqui que petch...

**Comment by RigoFlores** [comment]
pues sigue igual... no es tan común el escenario...
si se vuelve a presentar, ahí tendremos la evidencia para fhoy.
Ahora mismo no tenemos el escenario, para reproducirlo.
