### ISSUE TITLE
CxP - Reporte de pago, no reporta el status de las facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1550]
Favor de agregar un título: "**Reporte de Pagos**", así como el rango de fechas:
Fecha del reporte:
Fecha Inicial:
Fecha Final:

**Si se ocupa el filtro de pagadas, los rangos de fecha son los de pago.
Si se ocupa el filtro de vigentes o vencidas, los rangos de fecha son los de la emisión de la factura.**

Y finalmente reportar el status de la factura en el reporte:

<img width="797" alt="reportePagos" src="https://user-images.githubusercontent.com/2912775/58113880-2832d980-7bbc-11e9-83c2-acc243f41e26.PNG">

**Comment by jccastillo0007** [comment]
fixed... aunque hay otros detalles, este defecto ya se arregló
