### ISSUE TITLE
CxP - Reporte General marca error y no muestra la información correcta.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1552]
Creo que a este reporte no se le ha trabajado nada, ya que las columnas que muestra no aplican y marca error si lo generas.

El reporte general en CxP, indica la sumatoria por cada proveedor de sus abonos (facturas recibidas) menos los cargos (pagos realizados), para obtener el saldo.
Saldo = Sumatoria abonos (factura recibidas) - sumatoria cargos (pagos realizados)

eso para cada proveedor.

Si aplicamos un filtro de fecha, podríamos conocer por ejemplo, cuánto nos ha facturado y cuanto le hemos pagado a cada proveedor en ese período. Un solo registro por proveedor. Algo muy similar al reporte general de CxC. Así luce ese reporte. La columna de número de proveedor se la podemos dejar para uso futuro.:

<img width="420" alt="carteraGeneral" src="https://user-images.githubusercontent.com/2912775/58271549-e9368c80-7d51-11e9-874d-2bdb51aba095.PNG">

**Comment by jccastillo0007** [comment]
ya arregle el tema del error al generar el excel...

voy a necesitar que me generes un ejemplo claro y real del ambiente de pruebas, para ver como se debe presentar la informaci[on, para que yo lo pueda replicar..

**Comment by RigoFlores** [comment]
ok, puedes eliminar toda la información de catálogo de proveedores y de facturas recibidas para la cuenta de la tia... obvio, también los pagos realizados a esas facturas... dejarlo limpio para generar ese escenario de pruebas

**Comment by RigoFlores** [comment]
hablo del ambiente de pruebas y la cuenta de la tia.
Ahí tenemos que poder subir facturas de proveedores y que la validación se haga en producción, esto es en el SAT.
De hecho para validar CxP en pruebas, no habría otra opción, aún en ambiente de pruebas.

Entonces para entregarte un ambiente 'limpio' y consistente de información, necesito que se limpie todo lo de proveedores, compras, registro de pagos a proveedores, y catálogo de proveedores. De igual manera que las validaciones de facturas canceladas, vigentes en el SAT, se haga hacia producción.

**Comment by jccastillo0007** [comment]
no se puede probar en PRU, porque se usa la misma URL de timbrado para conocer el estatus de las pruebas... no se puede manejar diferentes urls en un mismo ambiente, hay que hacer el setup en pro u omitir la validación en pru para crear los datos de prueba

**Comment by RigoFlores** [comment]
Se puede omitir la validación en pruebas, pero siempre y cuando se garantice que en pro si se lleve a cabo.
Como quiera entonces también hay que limpiar el ambiente de producción (y el de pruebas), pero solamente lo referente a:
a) Catálogo de proveedores
b) Pagos registrados a facturas de proveedores
c) Facturas de proveedores

Supondría que con eso, ya los reportes aparecerían en vacío y empezaría de cero.
Algo que es importante, es atender el issue 1545, esto es que no regresa el status a vigente o vencida, cuando se borra el registro de un pago registrado a un proveedor.

**Comment by jccastillo0007** [comment]
listo, ambiente limpio en cuanto a proveedores de la TIA

Mejor checalo en pro, no vaya ser que se me olvide activa la validación

me chute todos los pagos de CxC  también (de la TIA)

**Comment by RigoFlores** [comment]
no asustes, de CxC en  producción para la tía, no le toques nada... yo lo ocupo para dar seguimiento a los clientes que deben facturas.
Supongo que te refieres a que borraste los pagos de CxP, en producción, para la cuenta de la tia.
Dejaste las facturas, que también pedí que se borraran, pero al borrar los proveedores, quedaron huérfanas. Así déjalo, a ver como trato de generar el escenario para el reporte.

**Comment by jccastillo0007** [comment]
okas, me avisas , si estorban las puedo borrar también

**Comment by RigoFlores** [comment]
Ya te envié por correo, la información y formato del reporte general.

**Comment by jccastillo0007** [comment]
ya esta el reporte de proveedores, checalo en pru ... ma;ana temprano lo libero a PRO, porque ahorita están usando mucho la aplicación

**Comment by RigoFlores** [comment]
Chiaaa.... este issue es del reporte general, no del cartera de proveedores...

Solicité el **reporte general de pagos**, pero no... no se genera como se solicitó. 
Anexo imagen de cómo debe generarse, donde le faltaría ordenarlo por nombre o por número de proveedor.


<img width="609" alt="reporteGeneral" src="https://user-images.githubusercontent.com/2912775/58573197-db29b580-8202-11e9-929a-08639365ecaa.PNG">

**Comment by jccastillo0007** [comment]
cómo saco el reporte general.. en pru no me sale... y en pro tengo un problema con el reporte, cómo lo puedo reproducir.

**Comment by RigoFlores** [comment]
en pru no sale, porqué no está implementado o que?
En pru, con la cuenta de la tia, debería salir el reporte general solo para 2 proveedores, uno que es TCM y el otro XAXX, pero si debería generarse

**Comment by RigoFlores** [comment]
ya que ambos tienen facturas...

**Comment by jccastillo0007** [comment]
wey... estoy todo confundido... ya me hice pelotas entre tanto reporte, con el mismo nombre pero de CxC o CxP...

Todo lo de CxC ya esta bien? y esto es para CxP ?

Porque según yo el de CxC no esta generando toda la info, debemos ser bien específicos porque ya estoy todo confundido

**Comment by RigoFlores** [comment]
por eso el nombre del issue inicia con CxP.
Tiene captura de pago
consulta de pago
cartera de proveedores
reporte general

aquí se trata del reporte general. Es un solo registro por proveedor, donde se sumarizan todos los abonos y todos los cargos... y el saldo por proveedor, es el sumarizado de abonos menos el sumarizado de cargos.

**Comment by RigoFlores** [comment]
lo que pasa es que creo que no te estás concentrando, pero CxC y CxP, tienen reportes parecidos, pero los únicos nombres que son iguales, es el de reporte general

**Comment by jccastillo0007** [comment]
ok si puede  ser, ya que la semana pasada me dejo medio apendejado, pero entonces, el excel de arriba que pusiste como ejemplo, como lo reproduzco ?

**Comment by jccastillo0007** [comment]
y todo lo de CxC esta bien ?

**Comment by RigoFlores** [comment]
en producción se tiene toda la información para generarlo
obvio, no se genera, pero ahí se tiene la batería de datos... para la cuenta de la tia

**Comment by RigoFlores** [comment]
lo de CxC, si está bien por lo pronto... seguramente se ocuparán cambios....
Ahora para lo de condominios, se ocupa lo de SP (solicitud de pago), dentro de CxC,  pero deja revisar si algo está faltando y lo manejo en otro issue

**Comment by RigoFlores** [comment]
así se vería el reporte general de CxP, en pruebas, con fecha inicial desde el 01 de enero del 2019, entrando con la cuenta de la tia

<img width="593" alt="REPORTE GENERAL CXP" src="https://user-images.githubusercontent.com/2912775/59322013-0ba92f00-8c9a-11e9-9c94-cee811bcc88c.PNG">

**Comment by jccastillo0007** [comment]
Si ok… por lo que veo esta muy alejado de lo que se requiere … pensé que ya estaba cercano … pero noup

 

JC

 

De: RigoFlores <notifications@github.com>
Responder a: jccastillo0007/eFacturaT <reply@reply.github.com>
Fecha: martes, 11 de junio de 2019, 22:41
Para: jccastillo0007/eFacturaT <eFacturaT@noreply.github.com>
CC: JC <jccastillo0007@gmail.com>, Assign <assign@noreply.github.com>
Asunto: Re: [jccastillo0007/eFacturaT] CxP - Reporte General marca error y no muestra la información correcta. (#1552)

 

así se vería el reporte general de CxP, en pruebas, con fecha inicial desde el 01 de enero del 2019, entrando con la cuenta de la tia

**Comment by RigoFlores** [comment]
pero si es exactamente lo mismo que el reporte general, de CxC.... la misma idea, el mismo concepto

**Comment by jccastillo0007** [comment]
haber, checale en PRU... no esta consolidando los movimientos por proveedor, eso va a estar medio canijo..

**Comment by jccastillo0007** [comment]
cual sería el reporte de CxC que hablabamos por whatsapp que es lo mismo pero obvio con la interpretación de CxC ? sería el de cartera general ? porque no se parecen...

**Comment by RigoFlores** [comment]
El reporte general como quedó, es prácticamente el mismo que el cartera de proveedores.
Para que cumpla su cometido, debe sumarizar los cargos y abonos por proveedor, de lo contrario no tiene mucho caso.

Y si, este reporte es el símil a  Cartera General de CxC. Este reporte de CxC, solo funciona bien para Optibelt, ya que supongo que está considerando el número de cliente. Si en producción lo genero para la cuenta de la TIA, no lo genera correctamente.

**Comment by jccastillo0007** [comment]
también debe sumarizar la info en pantalla o solo en el excel?

**Comment by RigoFlores** [comment]
si, generalmente el excel es un reflejo de la pantalla... creo que si debe mostrarlo igual
