### ISSUE TITLE
Addenda Mabe - modificar la forma de reportar las tasas en traslados y retenciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1554]
En la addenda, para los nodos de traslados y retenciones, en el parámetro tasa, reportarlo tal cual se reporta al SAT. 
Ahora mismo se reporta como 16.00 o 4.00

Este punto, se lo están pidiendo solo a un cliente que ocupa el addendador para MABE; a todos los demás no les han observado este punto. Cómo podemos atenderlo para que podamos cobrar este cambio?? Es decir que no se generalice a todos, sino conforme lo vayan solicitando?
Aún mas, como puedo conocer los clientes que hoy mismo emiten con la addenda mabe?? Esto es para contactarlos personalmente y venderles el cambio.

<mabe:Traslados>
<mabe:Traslado tipo="IVA" tasa="0.16" importe="2469.96"/>
</mabe:Traslados>
<mabe:Retenciones>
<mabe:Retencion tipo="RET" tasa="0.04" importe="557.49"/>
</mabe:Retenciones>

**Comment by jccastillo0007** [comment]
listo en pRU

**Comment by jccastillo0007** [comment]
ya esta en pro
