### ISSUE TITLE
CxP- Ingresar pago, las fechas de los rangos deben incluirse en el cueri

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1555]
Cuando vas a capturar un pago y defines un rango de fecha, la fecha final no se incluye dentro del cueri. Es decir, si la fecha final es 31 de enero, las facturas de ese día ya no aparecen en el resultado. Le tengo que decir fecha final = 01 de febrero, para que si aparezcan las facturas del 31 de enero.
No sé si pase lo mismo con la fecha inicial. Hay que revisar que en todas las consulas de CxP así se manejen las condiciones >= o <=.

**Comment by jccastillo0007** [comment]
Asi están las condiciones de fecha... si no te salen algunas facturas, puede ser por el tema de la hora, min y segundos... tienes un ejemplo

**Comment by RigoFlores** [comment]
Si tengo ejemplo. Con la factura que lo detecté y que no se ve, tiene fecha de Fecha="2019-02-28T22:20:04". 
Si le pongo fecha final 28 feb, no sale. Si le pongo fecha final 01 de marzo, si sale.
es en pro, es con la cuenta de la tia.

<img width="626" alt="28Feb 2" src="https://user-images.githubusercontent.com/2912775/58473825-32e6f480-810f-11e9-86a7-6daba210b823.PNG">
<img width="620" alt="28Feb" src="https://user-images.githubusercontent.com/2912775/58473826-32e6f480-810f-11e9-8c14-9e363622654b.PNG">

**Comment by jccastillo0007** [comment]
si, es por la hora.... chiaaa

**Comment by RigoFlores** [comment]
a las 22:20 ya lo considera otro día????
chiaaaaa....

**Comment by jccastillo0007** [comment]
no, es que toma por default la hora 00:00:00   pero ya lo corregí
