### ISSUE TITLE
CxP - Reporte de Pagos, ordenar el resultado por fecha

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1556]
Cuando presentamos el resultado de una consulta en pantalla o lo exportamos a excel, aparacen desordenados (quizás sea por folio), pero se ve todo un desorden, porque los folios de los proveedores son muy diversos y dispersos.
La petición, es que tanto en pantalla como en el excel, el orden sea por fecha.

**Comment by jccastillo0007** [comment]
listo... peeeero, igual se puede  ver medio raro porque se incluyen los pagos... y el orden es solo por fecha de la factura

**Comment by RigoFlores** [comment]
Lo que dices es correcto, pero al menos ya tiene un orden, porque de otra manera, estaba casi al azar.
Ahora tomando en cuenta lo que dices (yo le llamo que no es tan 'legible') este reporte... propuse 10 puntos de mejora. Uno era precisamente el orden.

Por otro lado para emitir un reporte mas 'legible', por ello es que te envié mi segunda propuesta de reporte. Contiene la misma información, pero mostrada de distinta manera.
