### ISSUE TITLE
CxP - Cartera de Proveedores, detalles restantes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1557]
Estos detalles aún quedan pendientes por atender:

1. EN LA COLUMNA CLAVE, CUANDO SE TRATA DE UN PAGO, QUE DIGA 'PAGO'. AHORA MISMO DICE 'null'.
2. LA COLUMNA DE REFERENCIA, PARA LOS PAGOS, DEJARLA VACIA, YA QUE AHORA MISMO DICE 'null'.
3. LA COLUMNA DE SERVICIO, CUANDO SE TRATA DE PAGOS.. O SE DEJA EL MISMO SERVICIO DEL PROVEEDOR, O SE DEJA VACÍO. AHORA MISMO DICE 'null'
4. EL SALDO SE CALCULA RESTANDO LA SUMATORIA DE ABONOS - LA SUMATORIA DE CARGOS. AHORA MISMO SUMA LA COLUMNA DE SALDOS Y SALE UNA CANTIDAD FUERA DE CONTEXTO.
5. EL TÍTULO DEL REPORTE ES CARTERA DE PROVEEDORES
6. INDICAR EL NOMBRE DE NUESTRO CLIENTE, QUE EN ESTE CASO ES EL RECEPTOR DE LAS FACTURAS.
7. INDICAR EL RANGO DE FECHA QUE ABARCA EL REPORTE

**Comment by jccastillo0007** [comment]
Supongo que estos dos , solo es si aplica

INDICAR EL NOMBRE DE NUESTRO CLIENTE, QUE EN ESTE CASO ES EL RECEPTOR DE LAS FACTURAS.
INDICAR EL RANGO DE FECHA QUE ABARCA EL REPORTE

ya que no siempre se seleccionan... debo ver como se hace eso

**Comment by RigoFlores** [comment]
el nombre de nuestro cliente no cambia.
Si ese reporte lo genera optibelt, pues ahí aparecerá su nombre.
Así con cualquier otro cliente. Esto es en el encabezado.
En cuanto al rango de fechas, correcto, solamente si aplica, aunque en general, creo que casi siempre lo definirían.

**Comment by jccastillo0007** [comment]
avance con lo del nombre y la fecha... pero algo no esta bien.. con la  tabla en la app y el excel

**Comment by RigoFlores** [comment]
ASÍ VA EL AVANCE A ESTE ISSUE, LO VALIDÉ EN PRUEBAS:

1. EN LA COLUMNA CLAVE, CUANDO SE TRATA DE UN PAGO, QUE DIGA 'PAGO'. AHORA MISMO DICE 'null'.
2. LA COLUMNA DE REFERENCIA, PARA LOS PAGOS, DEJARLA VACIA, YA QUE AHORA MISMO DICE 'null'.
3. LA COLUMNA DE SERVICIO, CUANDO SE TRATA DE PAGOS.. O SE DEJA EL MISMO SERVICIO DEL PROVEEDOR, O SE DEJA VACÍO. AHORA MISMO DICE 'null'
4. EL SALDO SE CALCULA RESTANDO LA SUMATORIA DE ABONOS - LA SUMATORIA DE CARGOS. AHORA MISMO SUMA LA COLUMNA DE SALDOS Y SALE UNA CANTIDAD FUERA DE CONTEXTO.
5. INDICAR EL RANGO DE FECHA QUE ABARCA EL REPORTE

GENERÉ UN REPORTE EN PAGOS, Y AHORA LA COLUMNA CLAVE, CUANDO SE TRATA DE FACTURAS, DICE PAGO... SUPONGO QUE ES PARTE DE LO QUE DICES QUE ESTÁS VIENDO ENTRE LA APLICACIÓN Y EL EXCEL

**Comment by jccastillo0007** [comment]
listo en pru

**Comment by RigoFlores** [comment]
no es muy consistente la información en pru, se me hace que tendría que probarlo en pro...
creo que los puntos que quedaron pendientes por resolver, son el 1 y 2, pero se agregan 2. Necesito confirmarlo en pro.
Sin embargo, en pru veo notas de crédito de proveedores (lo cual no es muy común), pero si fuera el caso, la nota de crédito DE UN PROVEEDOR no se incluye en la columna de abono, sino de cargo, ya que es como si fuera un pago.

**Comment by RigoFlores** [comment]
también veo que los registros de pago (CxP) a los egresos, no se ven reflejados en ningún lado... esto ya está levantado en otro issue, pero es de mayor impacto, ya que esa salida no se refleja en ningún lado...

**Comment by RigoFlores** [comment]
MIRA EL REPORTE SALE ASÍ AHORA MISMO:

<img width="865" alt="CARTERA_DE_PROVEEDORES" src="https://user-images.githubusercontent.com/2912775/59715118-c70d1e80-91d8-11e9-99f9-72e78a24db1f.PNG">
