### ISSUE TITLE
Dar de alta en harcode a este rfc IDL050415MT0 para emitir CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1558]
CHIAAAAAA.... jarcoud...!!!!

**Comment by jccastillo0007** [comment]
esto es en web cierto ?

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
estoy esperando datos del cliente para probar, mientras lo cierro, y si hay problemas, lo reopeneo
