### ISSUE TITLE
CxP - Cartera de proveedores, un pago a una factura lo reporta chueco en el excel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1560]
Registré un pago a una factura de un proveedor AAZR7411149T2, si lo registró bien.
La referencia es PAGO FACTURA F53, y si la consulto (CxP-Consulta de pagos) lo despliega digamos bien a secas... jeje.
Si me voy a CxP-Cartera de Proveedores, y consulto para ese proveedor en particular AAZR7411149T2, el excel arroja lo siguente:

<img width="770" alt="CARTERA_DE_PROVEEDORES" src="https://user-images.githubusercontent.com/2912775/59720609-eca02500-91e4-11e9-8806-fcd9cd825483.PNG">

**Comment by RigoFlores** [comment]
cómo debería desplegarlo es así. En amarillo resalto los puntos:
a) la clave debería ser FACTURA para el registro de la factura
b) la clave debería ser PAGO para el registro del pago
c) en la columna servicio se debería desplegar el servicio de ese proveedor, registrado en el catálogo de proveedores.




<img width="774" alt="CARTERA_DE_PROVEEDORES" src="https://user-images.githubusercontent.com/2912775/59720766-486aae00-91e5-11e9-9730-672c65100ae9.PNG">

**Comment by jccastillo0007** [comment]
el tema de factura o pago, ya quedo resuelto

el caso del servicio, se toma la descripción del producto 1 de la factura

**Comment by RigoFlores** [comment]
para ello se solicitó el campo adicional de servicio, en el catálogo de proveedores, para describir el servicio ahí. 
Es de ahí donde se debe tomar para los reportes.

**Comment by jccastillo0007** [comment]
chiaaaa, listo
