### ISSUE TITLE
CxP - Reporte General, no está sumarizando los pagos realizados hacia EGRESOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1561]
Mismo caso, solo contabiliza pagos realizados a proveedores, con factura.

No contabiliza, pagos (salidas de lana) respaldados por un EGRESO.

**Comment by RigoFlores** [comment]
te mandé un correo, con otro caso... en particular en producción, con tu rfc como proveedor, no coinciden los saldos de cartera por proveedor vs reporte general ... todo es CxP

**Comment by jccastillo0007** [comment]
ok, ya lo estoy checando... peeeero no me confundas, este ticket es de los egresos y de los pagos de los egresos... mas no de facturas reales como el caso de mi rfc, chiaaa

**Comment by RigoFlores** [comment]
si, es que ambos casos era un error en el reporte general
