### ISSUE TITLE
Condominios - Pasar todo lo de CxC y CxP de FT a condominios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1562]
para emparejar todo lo que ya se hizo allá.
La diferencia será que en CxC, una solicitud de pago (SP), será un documento 'cobrable' al igual que una factura.
En condominios se podrá ingresar un cobro a partir de una factura o de una SP.

**Comment by jccastillo0007** [comment]
listo en pru, hay que levantar algún ticket muy específico al tratamiento de SP

**Comment by RigoFlores** [comment]
quieres un ticket para todo lo que es SP?

**Comment by RigoFlores** [comment]
lo de CxP, es distinto a como está en FT producción... eso no está actualizado

**Comment by jccastillo0007** [comment]
necesito que seas mas específico... noté algunas diferencias en el menú y en las páginas que muestra cada opción del menú, pero no sé si ha eso te refieres.

**Comment by RigoFlores** [comment]
mientras que el menú y pantallas de CxC es idéntico, en el caso de CxP no sucede así.
Para capturar el pago, que es una de las pantallas principales, no se capturan los mismos datos, ni las mismas etiquetas.
Asumí que se copiaría idéntico...

**Comment by RigoFlores** [comment]
CxP- Ingresar pago, está como estaba hace mas de 1 año, yo creo que es totalmente obsoleta.
CxP - Consulta de pago, se ve igual... habría que validar si en el backend también está igual, asumo que no. No puedo probar, ya que no puedo subir XML de proveedores en pruebas.

**Comment by jccastillo0007** [comment]
listo en pru

**Comment by RigoFlores** [comment]
OK, el menú de CxP, en apariencia, ya es el mismo.
Falta probar su funcionamiento, pero mientras no pueda generar documento de egreso o subir un XML de un proveedor, no lo puedo hacer
