### ISSUE TITLE
CxC - Condominios - Ingresar cobro, la clave de una solicitud de pago es SP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1566]
Ahora mismo aparece FA tanto para solicitud de pago, como para factura.
Lo que está en amarillo es una SP, y su clave dice que es FA.

<img width="387" alt="sp" src="https://user-images.githubusercontent.com/2912775/60066351-76139380-96cc-11e9-86ab-95270e1bc51b.PNG">

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
jajaja... ahora toooodas las muestra como SP, incluso las facturas. 
Esto es para que visualmente y en el reporte sepas que es una factura y que es una SP.
Entonces las facturas deben llevar su propia clave (FA) distinta a la solicitud de pago (SP).

<img width="397" alt="CxCclave" src="https://user-images.githubusercontent.com/2912775/60387664-18849b80-9a6c-11e9-929c-0dd11bca81de.PNG">

**Comment by jccastillo0007** [comment]
fixed
