### ISSUE TITLE
Condominios CxC - Ingresar cobro, pulir detalles estéticos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1567]
1. El encabezado es Cobros, en lugar de Pagos.
2. En Paso 2,  cambiar etiqueta a Elegir Documentos Pagados
3. Cambiar Razón Social, por Nombre
4. cambiar RFC cliente, por RFC Casa/Depto
5. Cambiar número de cliente, por ID casa/depto

**Comment by RigoFlores** [comment]
Recordar que en condominio, el ID casa, será lo que en facturación es el número de cliente

**Comment by jccastillo0007** [comment]
done
