### ISSUE TITLE
Condominios - CxC, Cartera por Casa, las claves están chuecas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1568]
No está considerando las SP, solo muestra facturas.
Aquí en condominios una SP, tiene la misma función que una factura, es decir es un documento que respalda un ingreso, entonces debe aparecer en cualquier sección donde se requiera consultar ingresos.
La excepción a esta regla, es cuando una SP tiene status de cancelada o facturada.
Pero si está vigente, vencida o pagada, debe mostrarse en los reportes de cartera por casa, o general.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
ahora muestra las SP, pero con una clave EG, debería ser SP.
Adicionalmente no muestra todas las pagadas....pero levantaré otro issue para no revolver.

<img width="398" alt="spPagadas" src="https://user-images.githubusercontent.com/2912775/60387411-5c75a180-9a68-11e9-97a2-59dcad03ed52.PNG">

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Pues ahora se regresó el issue original, ya no muestra las SP, solo las facturas.

En la pantalla, hay que mostrar el id casa, en lugar de los días de crédito.

**Comment by jccastillo0007** [comment]
listo, checale
