### ISSUE TITLE
Condominios - SP - enviar el número de casa al PDF de la SP y de la factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1569]
En la SP (y en la factura), debe aparecer el ID casa (número de cliente para facturación, aquí será ID casa).
En qué variable lo quieres enviar... podría ser una nueva o en referenciaFiscal.
Tu díme.
Nuestra experiencia de reutilizar variables originalmente para un fin, en otro, ha sido un desastre, pero tu dime.

**Comment by jccastillo0007** [comment]
ya existe el campo para número de cliente en la facturación no? entiendo que en condominios es el mismo campo, tons que se vaya en la misma variable

**Comment by RigoFlores** [comment]
pues no lo hallé... cuál variable sería?
Al menos en las plantillas, no existe dicha variable.

**Comment by jccastillo0007** [comment]
tienes razon.. no existe... que extranio, nadie ha solicitado que se despliegue el número de cliente ?

**Comment by jccastillo0007** [comment]
mejor agregamos la variable numeroCliente... peeero la duda que tengo... estoy viendo que al realizar una factura o SP, nos basamos en los datos del cliente, que aparecen en el catálogo de casas...  durante la creación de Facturas o SP, nunca aparecen los datos del condominio o de la casa en particular... solo se ocupa el id de la casa, o que mas datos ?

**Comment by RigoFlores** [comment]
el número de cliente se envía como dato extra en optibelt, que es el único que lo ocupa. OJO con eso, no vaya a meterle ruido a optibelt, o internamente si existe el campo variable número de cliente?
Otra cosa respecto al número de cliente... para las casas, seguramente será alfanumerico. Eso no pegará?

Entonces la variable será 'numeroCliente', ok? Ese debería ser la llave primaria para el catálogo de casas.

Por lo pronto, solo ocuparemos el número de casa en SP o Facturas, que en condominios es idCasa, pero es igual. Será la variable numeroCliente.

**Comment by jccastillo0007** [comment]
si, internamente si existe el número de cliente.

El número de cliente es alfanumérico, tons ahi estamos bien

Si, la variable será numeroCliente en el jasper

**Comment by jccastillo0007** [comment]
listo en pru

**Comment by RigoFlores** [comment]
pues no, marcó el siguiente error:


2019-06-29 11:51:23,291 ERROR [http-nio-8080-exec-97] (JasperCreatorImpl.java:247) - net.sf.jasperreports.engine.JRException: Error retrieving field value from bean : numeroCliente                                                                                                                                                                     net.sf.jasperreports.engine.JRException: Error retrieving field value from bean : numeroCliente
--

**Comment by jccastillo0007** [comment]
Done  numeroCliente=CASA 29

**Comment by RigoFlores** [comment]
pues no marca error el PDF de solicitud de pago, ni el PDF de la factura (lo que se emite en ingresos), pero no se despliega en ninguno de los 2 PDF's el dato de número de cliente

**Comment by jccastillo0007** [comment]
entonces esta del lado del jasper, pues la variable ya se esta mandando... en el log puedes verlo

**Comment by RigoFlores** [comment]
ya la envía al SP pero a la factura nomás no llega... puedes chequear?

**Comment by jccastillo0007** [comment]
no ma... ya se decidió a enviarla jajajaj
chiaaaa deja veo la factura

**Comment by RigoFlores** [comment]
pues no lo estaba enviando, la plantilla es la misma...

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
que bueno que ya se decidió también a enviarlo... jejeje
