### ISSUE TITLE
Condominios - Compras - Egreso, no permite generar un documento de egreso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1571]
Entiendo que debe ser complicado copiar de un lado a otro, ya que hay funcionalidad que no aplica de FT a Condominios, pero entonces eso implica repetir tooooodas las pruebas, y volver a levantar toooodos los issues pasados?
Este issue se levantó en su momento para FT
Cuando intento generar un egreso desde Compras-Egresos, marca este error:

Error al leer informacion del certificado (102)

Siendo que un egreso no requiere del certificado. Los submenús de Compras, estás en distinto orden que en producción. Asumiría que el funcionamiento de esos submenús no está actualizado...

Que hacemos?, se nos van a ir semanas en todo esto....

**Comment by jccastillo0007** [comment]
En condominios no existe el menú de compras... solo el de egresos chiaaaaa luego porque me confundo.

la funcionalidad si esta actualizada... el orden de los menús y sub menus no lo había actualizado

Y pues si, hay que repetir todas las pruebas específicas para condominios y levantar lo que no funcione, no hay de otra pues es un business case diferente y estamos tratando de reutilizar funcionalidad

**Comment by jccastillo0007** [comment]
Este menú de Egresos, no fue actualizado, solo solicitaste CxC y CxP, debo copiar la funcionalidad?

De hecho una forma de ahorrar tiempo, es analizar la funcionalidad que se requiere, y pedir todo junto, y no conforme avanzas en las pruebas

**Comment by jccastillo0007** [comment]
listo en pru

**Comment by RigoFlores** [comment]
toda la funcionalidad de Ventas, CxC, Compras y CxP, debió actualizarse, con los cambios de nomenclatura respectiva.

**Comment by RigoFlores** [comment]
el punto es que no permite generar un documento de egreso, marca:

Error al leer informacion del certificado (102)

**Comment by RigoFlores** [comment]
Muchas pruebas son secuenciales, recuerda que es una especia de flujo de trabajo... es un proceso secuencial.
Entonces, mientras no pueda siquiera iniciar... generando un documento de egreso o registrando una factura de proveedor, pues no puedo avanzar en todo lo demás... consultas, reportes, CxP, etc

**Comment by jccastillo0007** [comment]
listo en pru

yo generé un egreso de 1 peso

**Comment by RigoFlores** [comment]
se reabrió con las correcciones de anoche

**Comment by jccastillo0007** [comment]
ya se que es, fue por la confusión de que a un egreso le estaba poniendo solicitud de pago

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
pero ya genere varias para hacer pruebas... haber si no te moví tus pruebas...
