### ISSUE TITLE
Condominios - Ingresos - Consultas, no actualiza el status de las SP ya pagadas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1572]
Tenemos pagadas las solicitudes de pago 1 y 3, así como la factura 2, todas ellas con serie SP.
Si me voy a ingresos-consultas, la única que refleja que está pagada es la 2, es decir la factura. Las SP, no las refleja como pagadas.

En la tabla de Payments, si están reflejados todos los pagos.

**Comment by jccastillo0007** [comment]
si se actualizaba el status, solo que la consulta no estaba completa... como las SP no tienen UUID , ahi es donde no encontraba los pagos realizados
Crei que toda SP se pagaba por medio de una factura.

**Comment by RigoFlores** [comment]
Desde ahí necesitamos tener el concepto muy claro.
La SP eventualmente podría o no ser facturada. (algunas casa ocuparán factura, otras no).

Si no es facurada, se contabiliza para ingresos y CxC. Como si fuera factura, pero sin timbrar.

Si una SP se factura al momento de capturar el cobro en CxC, o al momento de editar una SP pagada, entonces pasa a status de facturada, y en ese momento ya no se toma en cuenta para los reportes de CxC.
