### ISSUE TITLE
Condominios-CxC-Cartera por casa, pagadas. No refleja correctamente cargos y abonos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1574]
En CxC, que representa los ingresos del condominio, los montos de las SP y Facturas, se colocan como cargos... y los pagos registrados, como abonos.
Ahora mismo muestra todo como abono, y salen saldos incorrectos (negativos).
NO confundirse, en CxC se muestras los INGRESOS, es decir las SP o FA en el columna de cargos.
En CxP, es al contrario, pero eso es oootro boleto.

<img width="408" alt="SaldoIncorrecto" src="https://user-images.githubusercontent.com/2912775/60387952-33590f00-9a70-11e9-876d-1286235881ac.PNG">

**Comment by jccastillo0007** [comment]
listo, este se arregló con algún otro pues me sale bien el resultado

**Comment by RigoFlores** [comment]
Ahora lo que está mal, es el saldo.

Saldo = cargo - abono.

Aquí la columna saldo, debería aparecer así:
1000.00
0.0
1,000.00
2,000.00
3,000.00

<img width="359" alt="carteraxcasa" src="https://user-images.githubusercontent.com/2912775/60608936-2d23a500-9d86-11e9-871e-16cd90cd68d4.PNG">

**Comment by RigoFlores** [comment]
Creo que todo el problema se deriva, a que NO ESTÁ INCLUYENDO O MOSTRANDO LAS SP en el reporte de cartera por casa, pero de alguna manera si está considerando los pagos realizados a las SP...
No sé, algo raro....

**Comment by jccastillo0007** [comment]
checale

**Comment by RigoFlores** [comment]
así si baila mija con el siñor...!!!
