### ISSUE TITLE
Condominios - CxC - Cartera general, solo considerar facturas, pero faltan las solicitudes de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1575]
Si generas el reporte ahora mismo, solo muestra la casa 28, pero falta mi RFC.
Debe mostrar un registro por casa...
en cargo la sumatoria de SP (no facturadas ni canceladas), y facturas (no canceladas)...
en abono, la sumatoria de todos los pagos registrados a SP o FA.

Ese reporte en producción, ya había quedado pero le seguimos batallando

**Comment by jccastillo0007** [comment]
Hay algo raro en la base de datos, antes de arreglarlo quiero ver si recuerdas que hiciste... tengo tres datos con el mismo trackingId
mysql> select id, invoiceName, CxCStatus, CxPStatus, sourceRFC, trackingId, targetRFC     from CFD order by trackingId ;
+----+-------------------+-----------+-----------+---------------+------------+---------------+
| id | invoiceName       | CxCStatus | CxPStatus | sourceRFC     | trackingId | targetRFC     |
+----+-------------------+-----------+-----------+---------------+------------+---------------+
|  4 | SOLICITUD DE PAGO | Pagada    | Vigente   | TCM970625MB1  | 103410     | XAXX010101000 |
|  5 | SOLICITUD DE PAGO | Vigente   | Vigente   | TCM970625MB1  | 103410     | XAXX010101000 |
|  6 | SOLICITUD DE PAGO | Vigente   | Vigente   | TCM970625MB1  | 103410     | XAXX010101000 |

**Comment by RigoFlores** [comment]
Si recuerdo lo que pasó.
Cuando estuve probando la plantilla de SP, la primera vez... marcó error del jasper.
Sin salirme de la pantalla de Solicitud de Pago, hice un cambio en la plantilla y la pasé por ftp, y volvió a marcar error. Creo que por el nombre.
Y finalmente al tercer intento, que fue sin salirme de la pantalla de SP, ya con la plantilla de SP correcta, es que ya generó la SP. 

Creo que eso no es fácilmente reproducible en producción, de cualqueir manera ese ID, debería de alguna manera, asegurar ser único...
Por otro lado, esos folios que se brincó, cualquier cliente estaría haciéndola de emoción.

**Comment by RigoFlores** [comment]
Ya veo lo que pasa, en cartera general solo está considerando las facturas.
Pero debe considerar las SP con status de vigente, vencida o pagada. 

Lo comento, porque hace falta implementar la cancelación de una SP o la facturación de una SP, en cuyo caso su status será cancelada o facturada, y esas no se consideran en ningún reporte de CxC.

**Comment by RigoFlores** [comment]
Así muestra la cartera general...

![image](https://user-images.githubusercontent.com/2912775/60631369-cffb1400-9dc4-11e9-88ca-dbc35adeb9cf.png)

pero si te vas a ingresos consultas, verás que existen las SP (en amarilo) y que no se consideran en el reporte de cartera general.

<img width="623" alt="IngresosConsultas" src="https://user-images.githubusercontent.com/2912775/60631454-19e3fa00-9dc5-11e9-8602-cb1ca182fb2f.PNG">

**Comment by jccastillo0007** [comment]
ya esta listo, creo
