### ISSUE TITLE
Condominios-CxP-Cartera de Proveedores, muestra las claves chuecas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1576]
Jejeje... están al revés respecto a CxC.
En CxP, las claves de los documentos de egreso debe ser EGRESO o EG (como ahora mismo aparece en CxC), pero aparece como SOLICITUD DE PAGO.

<img width="422" alt="carteraProveedores" src="https://user-images.githubusercontent.com/2912775/60388157-0ce8a300-9a73-11e9-95f7-3935c97bf267.PNG">

**Comment by jccastillo0007** [comment]
y en CxC que debe ser? SP ?

Aqui me confunde un poco....

**Comment by RigoFlores** [comment]
CxP ocupa documento de egreso, o facturas de proveedores, que viene del menú de Egresos.
CxP es un proceso ligado a egresos. En egresos se registran las facturas de proveedores o los documentos de egreso.

En los reportes un egreso, debería llevar clave EG o EGRESO. Asimismo una factura de un proveedor debería llevar la clave FA o FACTURA.
Cuando se registra un pago para un egreso o factura de proveedor, ese debería llevar la clave PAGO O PA.

**Comment by RigoFlores** [comment]
Por otro lado en Ingresos, tenemos Solicitudes de Pago y Facturas.
CxC es un proceso ligado a Ingresos, ya que ahí se registran los pagos a las facturas o a las SP's.

La solicitud de pago, en los reportes lleva la clave SP o SOLICITUD DE PAGO. La factura lleva la clave FA o FACTURA.
En CxC, cuando se registra un pago a una SP o a una factura, el registro lleva clave PAGO o PA.

**Comment by RigoFlores** [comment]
Cuando me refiero a reportes son:
CxC . Cartera x Casa
CxP. Cartera de Proveedores

Reporte general en ambos, aunque creo que ahí no aplican las claves, ya que no se muestran facturas o pagos o cobros individuales, sino sumarizados.

**Comment by jccastillo0007** [comment]
ya vi que uno de los problemas no era el reporte en si... si no cuando creas el documento de egreso, le ponia solicitud de pago, en lugar de egreso... eso ya lo corregi... checale

**Comment by RigoFlores** [comment]
pero lo checo, sin recapturar nada?

**Comment by RigoFlores** [comment]
lo de las claves quedó, pero ahora resultó otro issue. Lo levantaré aparte
