### ISSUE TITLE
Condominios-CxP-Cartera de proveedores, no jala el filtro de Vigentes+Vencida

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1577]
Te digo, todos estos issues los levanté en CxP de FT.
La neta no deberían aparecer nuevamente...

Si filtro vigente, si presenta resultados.
Vencidas no presenta resultados, ya que no hay documentos vencidos.
Si aplico el filtro de vigente+vencida, no muestra nada y si debería mostrar las mismas que muestra con solo el filtro de vigentes.

**Comment by jccastillo0007** [comment]
fixed
