### ISSUE TITLE
Condominios-Egresos-Consultas, muestra como pagado un egreso, que se eliminó

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1578]
El EGRESO con folio 1, capturé su pago. Lo hizo bien, y luego en reportes lo reportó, digamos bien.
Luego desde CxP-Consulta de Pagos lo eliminé (borré el pago a ese EGRESO).
Pero en Egresos-Consultas, sigue apareciendo como pagado.
Si intento volver a captura un pago en CxP-Ingresar pago, si aparece como 'pagable', pero con status de 'pagada'... jejeje

<img width="598" alt="egresoPagado" src="https://user-images.githubusercontent.com/2912775/60388282-c3995300-9a74-11e9-992e-d38fdcb8ea5d.PNG">

<img width="560" alt="egresoPagado2" src="https://user-images.githubusercontent.com/2912775/60388311-16730a80-9a75-11e9-9cc8-c5aacb07529c.PNG">

**Comment by jccastillo0007** [comment]
fixed
