### ISSUE TITLE
Condominios - CxC - cartera x casa, no funciona la consulta sin filtro de status

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1579]
Si hago una consulta sin filtro de status, solo muestra las vigentes + vencidas.
Tengo que seleccionar el filtro de pagadas, para que muestre las pagadas
El filtro de vigentes, vencidas, o vigentes + vencidas, aparentemente si funciona.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ya muestra todas, pero solo facturas.
Está faltando que muestre las SP

**Comment by RigoFlores** [comment]
Aquí la imagen de que solo muestra las facturas ese reporte, cuando lo solicito sin filtro o con filtro, igual solo muestra facturas.

<img width="388" alt="soloFacturas" src="https://user-images.githubusercontent.com/2912775/60630700-eb642000-9dc0-11e9-9b60-595a977607f0.PNG">


Sin embargo, si consultas en ingresos, podrás ver que hay varias solicitudes de pago, y que no se toman en cuenta en este reporte de cartera x casa:

<img width="571" alt="sps" src="https://user-images.githubusercontent.com/2912775/60630761-3bdb7d80-9dc1-11e9-8580-7cd97587c5f2.PNG">

**Comment by jccastillo0007** [comment]
listo
