### ISSUE TITLE
Condominios -CxC - Cartera General - solo muestra las facturas o sp que no han sido pagadas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1580]
Debe sumarizar por casa, todas las facturas vigentes, vencidas o pagadas, junto con las SP igual con el mismo status... en la columna de cargos.
Todos los pagos realizados por cada casa, los debe sumarizar en la columna abonos.
Claro, todo esto dentro del rango de fechas que corresponda.

Ahora mismo, solo está considerando las facturas o SP, que no han sido pagadas.
Entonces no refleja en cargos las facturas o SP pagadas, ni en cargos los pagos realizados por casa.

**Comment by RigoFlores** [comment]
Esto sucede si no le pones filtro de status.
Si ocupas algun filtro de status, si muestra la info correspondiente; pero solo incluye las facturas, y también debe considerar las SP con status de vigente, vencida o pagada

**Comment by jccastillo0007** [comment]
te falto ejemplo de que sale, y de como debe salir...

**Comment by jccastillo0007** [comment]
creo que se solucionó con el ticket 1575

**Comment by jccastillo0007** [comment]
vi algo raro, que me causa ruido... el reporte de cxc cartera general, solo tomaba facturas y faltaban solicitudes de pago, como bien dices... peeeero además tomaba las facturas ya pagadas... si no están pagadas no las tomaba en cuenta, eso esta super raro no? y asi esta en facturat

**Comment by RigoFlores** [comment]
Negativo, el problema sigue. 
Así sale ahora mismo (no voy a generar mas facturas ni SP, para no moverlo):

<img width="325" alt="carteraGeneral" src="https://user-images.githubusercontent.com/2912775/60615249-4f242400-9d94-11e9-9b99-87cf66795b1b.PNG">

así debería salir, considerando que rigoberto tiene 3 SP y 1 factura, de esas 4, 2 SP están pagados, quedando pendiente de pago 1 SP y 1 factura.
La casa 28, CÓMO ÚNICAMENTE TIENE 3 FACTURAS, entonces si refleja bien el caso:

<img width="359" alt="carteraGeneral23" src="https://user-images.githubusercontent.com/2912775/60615447-c0fc6d80-9d94-11e9-9895-030a757d7ac6.PNG">

**Comment by RigoFlores** [comment]
Es decir, ahora el problema se replantea, a que en este reporte de CxC - cartera general, solo incluye las facturas pagadas y no pagadas, y debe incluir también las SP pagadas y no pagadas.

**Comment by jccastillo0007** [comment]
Esto es solo en el reporte csv? en pantalla ya estamos bien ?

**Comment by RigoFlores** [comment]
en pantalla y en excel se presenta el problema

**Comment by jccastillo0007** [comment]
pero en pantalla , ya muestra las SP cierto... ese era otro ticket

**Comment by RigoFlores** [comment]
ahora mismo está así....

Es decir, ahora el problema se replantea, a que en este reporte de CxC - cartera general, solo incluye las facturas pagadas y no pagadas, y debe incluir también las SP pagadas y no pagadas.

**Comment by jccastillo0007** [comment]
ya esta listo, al menos en pantalla

**Comment by RigoFlores** [comment]
si, y el reporte se ve bien también
