### ISSUE TITLE
Condominios - CxC - Reporte de Pagos, no despliega el número de casa.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1581]
En la columna dice 'número de cliente', hay que cambiarlo por 'casa' o 'ID casa', y desplegar ese dato en el reporte.

Por otro lado, quizás el RFC no diga nada, mejor sería mostrar el nombre en la columna.

**Comment by jccastillo0007** [comment]
quedo lo del nombre, pero no se ve en todos los registros... me falta agregar lo del id casa

**Comment by RigoFlores** [comment]
ahí está el pedo de tener todos los pagos en una misma tabla.
Ahora mismo se despliegan tanto cobros (CxC), como pagos (CxP).
Este reporte solo debe incluir los cobros que se capturaron en CxC - Ingresar Cobro.

Incluso, por esa razón no se despliega el nombre del receptor... ahí donde no se muestra, esos son pagos pero de CxP.

**Comment by RigoFlores** [comment]
Y SI, FALTA EL ID CASA

**Comment by RigoFlores** [comment]
los renglones que no tienen nombre (en amarillo), corresponden a CxP. NO deben aparecer en este reporte. Son pagos a proveedores, mas no cobros a casas.
Y bueno, la columna referencia, debe mostrar el ID casa.

<img width="382" alt="reportePagos" src="https://user-images.githubusercontent.com/2912775/60630442-cc18c300-9dbf-11e9-89b9-10dca537e82f.PNG">

**Comment by jccastillo0007** [comment]
hmmm pero entonces algo esta mal... porque el emisor y receptor de CxC son diferentes a CxP

**Comment by RigoFlores** [comment]
si, seguro algo anda mal... jeje
Pero el punto, es que está desplegando, me parece, todos los pagos de la tabla....
y debería desplegar solo los pagos que se capturaron en CxC, esto es en ingreso de cobros.

**Comment by jccastillo0007** [comment]
oye lo peor es que asi esta en facturat....

**Comment by RigoFlores** [comment]
este reporte, solo lo ocupa optibelt
en ese entonces no existía CxP
y  ahora que tenemos nuestro primer cliente que ocupa CxP en facturat, no sé si esté requiriendo de este reporte que tiene fallas.

**Comment by jccastillo0007** [comment]
ya corregi el tema de que muestra facturas de CxP chiaaaa

**Comment by jccastillo0007** [comment]
ya esta el id de la casa, aunque muestra 0 porque no tiene nada capturado el único registro que sale... haber checale.

**Comment by RigoFlores** [comment]
tenemos 3 registros de casa. Todos ellos tienen capturados el id casa. Entonces no los está mostrando.
<img width="524" alt="idCasa" src="https://user-images.githubusercontent.com/2912775/60902621-86cc1980-a235-11e9-8e68-f870723c894a.PNG">

**Comment by RigoFlores** [comment]
Ese dato lo debe tomar del catálogo, ya que ese ID difícilmente cambiará, aún cuando la casa cambie de dueño o de inquilino.
Así que no creo que deba estar ligado a la factura o a la solicitud de pago en cuestión.

**Comment by RigoFlores** [comment]
Aún con todo lo anterior, ese número de casa existe desde hace días, y todas las pruebas que he estado reseteando, ya lo incluían. 
Es decir, tampoco el dato lo tiene ligado a la factura o solicitud de pago.

**Comment by jccastillo0007** [comment]
okas

**Comment by jccastillo0007** [comment]
listo
