### ISSUE TITLE
Condominios - Catálogo de proveedores no incluye el campo servicio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1583]
No manches, todo eso ya estaba antes... chiaaaa... siento que nos regresamos gacho...
Se había agregado un campo en pantalla y en BD supongo también, para capturar el servicio que brinda cada proveedor, pero ya no aparece en el catálogo de proveedores

**Comment by jccastillo0007** [comment]
eso fue en facturat... chiaaaa, lo único que se movio a condominio fue cxc y cxp

**Comment by jccastillo0007** [comment]
listo
