### ISSUE TITLE
Condominios - CxC - Ingresar cobro, generar un documento que ampare el cobro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1587]
Cuando registras un cobro en CxC, significa que una casa realizó un pago.
Ahora mismo, solo registramos el pago.
Pero imagina que una casa va a la oficina de administración a pagar en efectivo, y qué se lleva como comprobante de pago??
Este comprobante de pago, tendría que ser algo similar a cuando generamos del complemento de pago, pero sin timbrar (opcionalmente se timbraría).

Lo que no sé, es donde se consultarían estos documentos?
Quizás en CxC, Reporte de Pagos, ahí se podría indicar el PDF a un lado de cada pago...

Cómo vex?

**Comment by jccastillo0007** [comment]
tenemos template ?

como no se va a timbrar, yo creo que hay que generar algo muy sencillo, como una remision o cotización pero que diga algo de pago de mantenimiento o la descripción del pago que están haciendo

**Comment by RigoFlores** [comment]
si, totalmente de acuerdo, que sea simple, pero que indique lo que se está pagando.
Para ello, debería incluir el concepto y la información complementaria de lo que están pagando (ya sea factura o solicitud de pago).

De hecho ese documento, debe ser similar al jasper del cfdi de pago.
Deja revisar para ver que info debe llevar...

**Comment by RigoFlores** [comment]
creo que debe llevar esto. Cuando generamos el cfdi de pago, reutilizamos variables que eran de otra cosa, y se hizo un desmadre... tú dime como las enviarás.
cfdi_cobrosf.jrxml sería el nombre del jasper.

GENERAL:

serie: PAGOSP
folio: el que corresponda
nombre emisor
rfc emisor

nombre receptor
rfc receptor
id casa

fecha de pago
forma de pago
moneda
tipo de cambio
importe del pago
referencia.

Usuario que capturó el pago

DETALLE:
(Tomado de la solicitud de pago o de la factura, enviar los siguientes datos)
Concepto: producto o servicio
Información complementaria

Saldo anterior
Importe Pagado
Saldo insoluto

**Comment by jccastillo0007** [comment]
oye, y porque no que generen el documento de pago... a fuerza... de esa manera ya generamos xml y pdf.... y nos conviene también por el lado de consumo de folios..

**Comment by RigoFlores** [comment]
Si hay varias razones por las cuales no es tan viable esa opción:
a) No todos los condominios facturan cada casa, de ahí que no se pueda generar un CFDI complemento de pago, ya que no existiría la factura para asociarla.
b) como mucha gente, los condominios entre menos 'te acerques' al SAT, mucho mejor.
c) Cuando una casa pida factura, lo mas probable es que primero pague y luego se le emita la factura. O no sé, pero puede darse el caso.
d) En este caso, contrario a facturat, no nos conviene el consumo de folios, ya que la mensualidad que se cobra ya incluye hasta x número de folios, los ocupen o no. Entonces, nos conviene que casi no ocupen folios. Recuerda la estrategia comercial de ir cada vez menos, dependiendo de los folios para los ingresos, y los condominios es una muestra clara de ello.
e) En resumen si necesitamos ese recibo de pago, que no es electrónico, y que indique claramente qué se pagó. Si te das cuenta, en el CFDI de complemento de pago, ni siquiera aparece el concepto de lo que se pagó.

**Comment by jccastillo0007** [comment]
chiaaa

**Comment by jccastillo0007** [comment]
listo

Ahora en la pantalla de Consulta de Cartera por Casa, voy agregar la funcionalidad de que muestre el pdf

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
pero como se llaman las nuevas variables?
En cartera x casa, y en reporte de pagos, creo que ahí quedaría mostrar ese PDF.

**Comment by RigoFlores** [comment]
voy a revisar como queda, pero si se hará un desmadre nuevamente, porque según yo, se ocuparán nuevas variables, y eso será motivo de confusionismo

**Comment by jccastillo0007** [comment]
osea se manda lo mismo como si fuera un documento de pago... hay que identificar los campos que faltan y los agrego... de entrada tienes todo lo de un pago

**Comment by RigoFlores** [comment]
ok, los campos que faltan son:

A nivel general: numeroCasa y usuario (de la plataforma, el que capturó el pago).

A nivel detalle:  el **concepto** de la SP o factura que se está pagando, **incluyendo la descripción complementaria:**

Por ejemplo:
"Cuota de Mantenimiento mensual (este sería el concepto)" + "Correspondiente al mes de Junio 2019 ( esta sería la información complementaria)"

Podemos ocupar la variable a nivel producto, $F{datoExtraPro1}

Como vex?

**Comment by RigoFlores** [comment]
ya está la plantilla, pero marca error, seguramente porque no envía el número de casa

**Comment by jccastillo0007** [comment]
asi es,... falta enviar el número de casa, ahora lo agrego

**Comment by jccastillo0007** [comment]
chiaaa habiamos dicho que seria en numeroCliente... 
pero ya le cambie a numeroCasa
A nivel producto, ya se mandan todas las variables... nombre del producto, descripción y descripción complementaria... no entendi porque mandarlas en el dato extra pro1..?

**Comment by RigoFlores** [comment]
chiaaaa.... cuando me refería a número de casa, precisamente es la variable de numeroCliente.
Entonces ya creaste una nueva??
no maaaa... voy a tener que ajustar las plantillas y ya estamos sobre tiempo

**Comment by jccastillo0007** [comment]
jajaja si k, yo como voy a saber lo  que estas pensando o a lo que te refieres en realidad... chiaaaa

soy bueno pero no tanto...

**Comment by RigoFlores** [comment]
Si, ya empezamos con las complicaciones. 
Lo que sucede, es que para el PDF de pagos, ahora mismo se hace un mapeo de datos:

PAGO	               -       PRODUCTO ESTANDAR
IdDocumento        -          unidad
Serie                       -         idProducto
Folio                       -        descripcion
MonedaDR             -        cuenta predial
TipoCambioDR       -        importe
MetodoDePagoDR  -       idProductoSAT
NumParcialidad       -      descripcionComplementaria
ImpSaldoAnt            -      valorUnitario
ImpPagado               -     cantidad
ImpSaldoInsoluto     -      descuento

Entonces la variable de descripción y descripción complementaria, ya están ocupadas propiamente en pagos (para otro uso, jejeje). Por ello no podemos ocuparlas. Esa es la razón por la que sugerí que en datoExtraPro1, se envíe el concepto + la descripción complementaria... **DEL DOCUMENTO QUE SE ESTÁ PAGANDO.**

Por otro lado, ya no me quedó claro, en cuál variable enviarás el id Casa, ya que antes era en el numeroCliente y ahora cómo quedó??

**Comment by jccastillo0007** [comment]
el id casa se va a enviar en numeroCasa

**Comment by jccastillo0007** [comment]
ya se lo puse... en pru no veo datos de prueba... puede generarlos ? es que no quiero mover el ambiente para el demo... como no te han avisado nada... mejor a ve preparando pro para el demo y asi yo le puedo mover a pru

**Comment by RigoFlores** [comment]
y tal cual, el cliente preguntó si ahí en ese documento, se muestra el concepto que se está pagando, esto es lo que yo pedía:

Concepto + Información complementaria... como dato extra pro 1

**Comment by RigoFlores** [comment]
numeroCasa, ya está llegando.
Si es necesario enviar ese dato extra pro 1, con el concepto e información complementaria de la SP o factura que se está pagando.

**Comment by jccastillo0007** [comment]
y no esta llegando ?, deja checo porque no

**Comment by RigoFlores** [comment]
ah, ya lo estás enviando? Lo voy a probar.... jeje

**Comment by RigoFlores** [comment]
ya lo validé, y no, no está enviando en el dato extra pro 1, la información solicitada.

**Comment by jccastillo0007** [comment]
2019-07-25 22:58:37,867 DEBUG [http-nio-8080-exec-66] (CFDBusinessLogicProvider.java:314) - com.cfd.shared.utils.jasper.JasperProductBean@6772cd1a[unidad=ACT,idProducto=<null>,descripcion=Pago,valorUnitario=,importe=,cantidad=1.00,numeroItem=1,descripcionComplementaria=,numeroAduana=,cuentaPredial=,datoExtraPro1=CUOTA DE MANTENIMIENTO MENSUAL del mes de febrero,datoExtraPro2=,datoExtraPro3=,datoExtraPro4=,datoExtraPro5=,datoExtraPro6=,datoExtraPro7=,datoExtraPro8=,datoExtraPro9=,datoExtraPro10=,precioUCD=,importeCD=,productoSAT=84111506,unidadSAT=<null>,descuentoPro=0.00,baseIVA=,impuestoIVA=,tipoFactorIVA=,tasaCuotaIVA=,montoIVA=,baseIEPS=,impuestoIEPS=,tipoFactorIEPS=,tasaCuotaIEPS=,montoIEPS=,baseRetIVA=,impuestoRetIVA=,tipoFactorRetIVA=,tasaCuotaRetIVA=,montoRetIVA=,baseISR=,impuestoISR=,tipoFactorISR=,tasaCuotaISR=,montoISR=]
2019-07-25 22:58:37,868 DEBUG [http-nio-8080-exec-66] (CFDBusinessLogicProvider.java:314) - com.cfd.shared.utils.jasper.JasperProductBean@59061026[unidad=null,idProducto=SP,descripcion=6,valorUnitario=996.00,importe=1.00,cantidad=1.00,numeroItem=2,descripcionComplementaria=5,numeroAduana=,cuentaPredial=MXN,datoExtraPro1=,datoExtraPro2=,datoExtraPro3=,datoExtraPro4=,datoExtraPro5=,datoExtraPro6=,datoExtraPro7=,datoExtraPro8=,datoExtraPro9=,datoExtraPro10=,precioUCD=1.00,importeCD=-994.00,productoSAT=PUE,unidadSAT=,descuentoPro=995.00,baseIVA=,impuestoIVA=,tipoFactorIVA=,tasaCuotaIVA=,montoIVA=,baseIEPS=,impuestoIEPS=,tipoFactorIEPS=,tasaCuotaIEPS=,montoIEPS=,baseRetIVA=,impuestoRetIVA=,tipoFactorRetIVA=,tasaCuotaRetIVA=,montoRetIVA=,baseISR=,impuestoISR=,tipoFactorISR=,tasaCuotaISR=,montoISR=]


Ya lo esta enviando, al menos en el primer producto, no sé cuantos se pinten en jasper o porque tenemos dos productos en el caso de los pagos

**Comment by RigoFlores** [comment]
veo la plantilla de pagos,  el 'primer producto' no lo pinta.... se ve el espacio.
no recuerdo porqué está así, pero aparentemente, el primer producto 'se lo brinca', y solo pinta el segundo.
lo cual quiere decir, que la info debería llegar en el segundo producto

**Comment by RigoFlores** [comment]
los productos tienen esta condición para pintarse:
( ($F{descripcion})== "Pago" ? new Boolean(false) : new Boolean(true) )

Lo cual me dice, que solo en el primer producto, se envía la descripción de "Pago", y a partir del segundo producto, ya se envía la info correcta.  Eso tu me lo indicaste que fuera así.

En el caso del documento de este issue, tienes que hacer lo mismo, es decir, brincarte el primer producto, solo indicando que la descripción="Pago"
