### ISSUE TITLE
CxP - Ingresar Pago.. muestra egresos o facturas ya pagadas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1588]
Recordar que aquí solo se muestran los documentos de egreso o facturas de proveedores, que tengan status de VIGENTE O VENCIDA.
Las pagadas no, ya que además ya están en 0 para su cobro.

<img width="601" alt="ingresarPago" src="https://user-images.githubusercontent.com/2912775/60732749-76076500-9f10-11e9-974b-8235ad588019.PNG">

**Comment by jccastillo0007** [comment]
a mi no me sale nada con esa consulta... puedes verificar

**Comment by RigoFlores** [comment]
es que los borré... ya los capturé nuevamente, y si, sigue igual... ahora si lo puedes checar...

<img width="610" alt="ingresarPago" src="https://user-images.githubusercontent.com/2912775/60745388-9ef31e80-9f3f-11e9-9148-2f6466335201.PNG">

**Comment by jccastillo0007** [comment]
fixed
