### ISSUE TITLE
Condominios-CxC-Cartera x Casa, no muestra el ID casa

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1589]
Ahí es muy importante que lo muestre, al igual que lo incluya en el reporte excel.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
si consulto sin filtro alguno, marca internal error

**Comment by RigoFlores** [comment]
con filtro de rfc si jala, pero con filtro de status no, ni de folio inicial tampoco... hay que revisarlo

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ya no marca internal error.
Pero la casa que muestra, es fija siempre. Reseteé mis pruebas, tengo 3 casas y generé 1 sp para cada casa, y 1 factura para 2 casas. Si consulto la cartera x casa, a todas les ponde casa 28.... chiaaaaa

<img width="399" alt="carteraxCasa" src="https://user-images.githubusercontent.com/2912775/61069846-d72cae00-a3d2-11e9-8e7f-76177ef60c73.PNG">

**Comment by jccastillo0007** [comment]
ya vi... de hecho si buscas por cada una de ellas, si muestra la casa que es.. .solo falla cuando buscas sin filtro, déjame lo checo

**Comment by jccastillo0007** [comment]
fixed
