### ISSUE TITLE
Condominios - CxC - Ingresar cobro, agregar la columna de ID Casa

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1590]
En lugar de referencia, que está de sobra, ya que ahí no aplica.
Esa referencia aplica para optibelt, ya que las facturas 'nacen' con una referencia, que es adicional a la referencia de pago.
En este caso no aplica, pero si ayudaría mucho el id casa

**Comment by jccastillo0007** [comment]
en el paso 2, ya hay un combo que se llama id casa, que por cierto creo que no funciona.... donde debería quedar el id casa?

**Comment by RigoFlores** [comment]
en la matriz que despliega después de la consulta, hay una columna que indica id casa....
pero quizás tengas razón, si elegimos el filtro previo, ya no tendría caso.
Entonces creo que hay que corregir lo del filtro de id casa

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
OK, ya no se agregará la columna de ID casa, ya que existe el filtro. 
Entonces hay que eliminar la columna referencia.

Por otro lado, el filtro de ID casa, o de RFC o de Nombre deben ser consistentes.
Si elijo el filtro de ID casa... que creo que será de lo mas común, entonces se debe actualizar el RFC y nombre. De igual manera si eligen el RFC o Nombre, se debe actualizar el ID casa. Hoy está chueco...

<img width="395" alt="ingresarCobro" src="https://user-images.githubusercontent.com/2912775/61065570-91b7b300-a3c9-11e9-96ec-dec7a3ef6039.PNG">

**Comment by RigoFlores** [comment]
El filtro de ID casa, a diferencia de facturat, aquí en condominios siempre debe desplegar todos los ID casas disponibles.
Porqué? Pues precisamente por eso, porque con ese filtro tendrás el chance de elegir cualquier casa del condominio.
Si eligen otro RFC, se actualiza el ID casa y nombre. Si eligen otro nombre, se actualiza el RFC y el ID casa. Si eligen el ID casa, se actualiza el RFC y el nombre.
debe ser consistente la info.

**Comment by RigoFlores** [comment]
Y todavía no lo platicamos, pero podrías ir pensando el tema de que muchas casas tendrán el RFC genérico. Entonces cómo manejaremos esto?.

**Comment by jccastillo0007** [comment]
En este caso es muy complicado, hacer que sean consistentes y que se actualicen automáticamente... a diferencia de facturat como bien dices..
Lo que es muy complejo es "Si eligen otro RFC, se actualiza el ID casa y nombre. Si eligen otro nombre, se actualiza el RFC y el ID casa. Si eligen el ID casa, se actualiza el RFC y el nombre."

tal vez tengamos que enfocarnos en buscar por casa y no por rfc... dado que son condominios.. aqui el método de reconocimiento de los residentes es la casa y no el rfc.. ni nombre

**Comment by RigoFlores** [comment]
Si puede ser.... buscar por casa.
De hecho, para todo este sistema, por condominio, la llave primaria e irrepetible, debe ser el número de casa.
Se busca por RFC ya que varias casas podrían tener el RFC genérico, y ahí es donde una vez elegido dicho RFC, solo presentaría esas casas asociadas al mismo rfc.

**Comment by jccastillo0007** [comment]
estoy tratando de hacerlo pero si se esta complicando, me esta haciendo cosas raras

**Comment by jccastillo0007** [comment]
ya esta funcionando... al buscar por rfc o nombre... se actualiza el combo de casa... pero al buscar por casa ahi si no se van a actualizar el rfc y nombre

**Comment by RigoFlores** [comment]
Hoy que hablé con el cliente, el comenta que se ocupa buscar primero por calle y luego por casa.
Realmente tenemos que pensar en algo mas genérico.
Esto es buscar por los diferentes niveles del condominio, empezando por el mas alto y dejando al final el id casa.
Comenta que buscar por rfc y nombre, no es algo funcional. De hecho, el dice que para propósitos de reportes, no se ocuparía eso.

**Comment by jccastillo0007** [comment]
ya lo sabia....

**Comment by RigoFlores** [comment]
si, así se pidió desde el inicio. 
Necesitamos darle velocidad a esto.

**Comment by RigoFlores** [comment]
al acceder al menú de CxC - Ingresar cobro, marca internal error, ni siquiera despliega la pantalla.

**Comment by jccastillo0007** [comment]
chiaaaa, es que probaste muy rápido... ya se esta subiendo
