### ISSUE TITLE
Producción - Escritorio addenda Liverpool, dar de alta un nuevo rfc EMISOR y unos RECEPTORES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1591]
EMISOR, EMISOR, EMISOR, EMISOR... chiaaaaaa...   DIMM950517UA0

ahora, se agregan estos RFC's a los receptores de la ADDENDA LIVERPOOL.

Almacenes comerciales Liverpool sa de cv    ACL1505087W3

Operadora Comercial Liverpool sa de cv      OCL091202ML1

**Comment by jccastillo0007** [comment]
osea un emisor y dos receptores, cierto... ya esta en la versión de hoy 
chiaaa, como quieres que me acuerde de esos detalles de standalone
