### ISSUE TITLE
Producción - regresar a los clientes que están alambrados por finkok a fhoy

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1592]
Por lo pronto, no tendremos PAC alterno.
Deja busco una opción... tengo varias propuestas...
Le revocaron su certificación, al menos por 1 año

**Comment by jccastillo0007** [comment]
no ma.... me tarde mas en quitar tus labels de este ticket, que en quitar finkok como pac nuestro..

solo lo deje en pruebas... ahi nos vamos a dar cuenta cuando de plano ya este abajo

**Comment by RigoFlores** [comment]
jajajaja...ok
