### ISSUE TITLE
Condominios - Catálogo de casas, no carga los datos previamente capturados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1593]
Si quieres editar un registro y lo eliges por nombre, no carga los datos del registro.
Solo si eliges por RFC, los carga correctamente.

De hecho, además de esos 2 campos, el principal para editar un registro, debe ser número de casa.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Lo cerraré, solo enfocado a que ya los carga por rfc o nombre.
Pero falta por id casa,
