### ISSUE TITLE
Condominios-Catálogos de casas, detalles varios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1594]
a) Eliminar la captura del curp, creo que no se ocupa
b) Cuando guardas un registro, dice 'cliente' guardado con éxito. Cambiar a 'casa'.
c) empiezas capturando rfc, nombre... y luego pais, estado, cp y municipio... después cuando capturas los datos de la estructura del condominio, borra los datos de rfc nombre.
d) quitar días de crédito, limite de crédito y saldo inicial. No se ocuparán.
e) La llave principal es id casa. Luego rfc y nombre para la facturación estos datos podrían ser opcionales ya que en algunos casos no se ocupará factura; luego nombre, teléfono y correo del inquilino; también nombre, teléfono y correo del propietario. Faltan algunos datos, y el orden de captura debía ser así como se indica.

**Comment by jccastillo0007** [comment]
nombre, teléfono y correo del inquilino y del propietario, serían diferentes al nombre y rfc de facturación...
Al inicio deben capturar un rfc y nombre... a huevo porque si no, le dan en la torre a un montón de cosas...
El id de casa que capturan no puede ser la llave principal , pues podría coincidir entre varias casas de varios fraccionamientos... lo que tu ves como id casa es lo que capturan en Casa, pero lo que realmente es el id casa, se conforma de varios datos del domicilio capturado... osea que es un pedo

**Comment by RigoFlores** [comment]
nombre, teléfono y correo del inquilino y del propietario, serían diferentes al nombre y rfc de facturación...?
Si, son datos independientes. Podrían llegar a ser iguales los 3, pero también podrían ser distintos los 3.
De hecho datos del inquilino, son opcionales, ya que no siempre tienes tu casa (propietario) en renta, muchas veces tu mismo la ocupas... jeje.

**Comment by RigoFlores** [comment]
Al inicio deben capturar un rfc y nombre... a huevo porque si no, le dan en la torre a un montón de cosas...
ok, se puede mantener así, pero que no los borre conforme sigues capturando el registro. Ese es el issue.

Cuando me refiero a que el ID casa sea la llave principal, me refiero a que por condominio, no se debe repetir, amén que todas las consultas y reportes, deberían basarse en dicho número de casa.

**Comment by RigoFlores** [comment]
solo quedó pendiente el último punto (e)

**Comment by jccastillo0007** [comment]
hay un detalle... se pueden almacenar n emails y n teléfonos... pero no puedo identificar de quien son... hacer eso implica cambiar muchas cosas... mejor que agreguen todos los datos que quieran sin tener que definirlo...
En nombre dejamos el nombre del propietario, y el campo contacto le ponemos inquilino.. cómo ves?

**Comment by RigoFlores** [comment]
es que nombre, se ocupa para la facturación.
Un inquilino, podría solicitar una factura a nombre de su empresa (cuando la empresa les cubre el gasto de la renta), entonces se debe aumentar un campo al menos.
Lo teléfonos que si sean un solo listado. Pero podríamos cambiar las etiquetas. Propietario Fijo, Propietario Movil, Inquilino Fijo, Inquilino Móvil, Factura Fijo, Factura Móvil.
Y el correo, pues ahí si no sé, porque los correos que se definan, ahí será donde se envíe la información de facturas, pagos, etc.

**Comment by RigoFlores** [comment]
Es que si debemos ir trabajando en adecuar mas que parchar.
Este será el ERP de condominios, y debe quedar bien adecuado a las necesidades.

Yo creo que los campos si deben agregarse en específico para esta pantalla.
Para propietario e inquilino: nombre, telefono(s), correo.
Para facturación: rfc, nombre, email. Uso de CFDI.

**Comment by jccastillo0007** [comment]
ya estoy haciendo los cambios necesarios

**Comment by RigoFlores** [comment]
Pues ahora no permite guardar un registro, hace cosas muy raras, como duplicar los campos de captura.
Tenemos que ajustar lo que se necesite, para irnos en firme con todo lo que venga.
Esto es, que para cada condominio, el ID de casa, debe ser único (llave primaria), no debe permitir repetirse. 

El orden de captura de esta pantalla debería ser:

1. Iniciar con un identificador de casa y cargo regular (si/no).
2. Luego la estructura del condominio.
3. Enseguida capturar País, estado, CP y Municipio.
4. Nombre, correo1 y correo2, telefono 1 y telefono 2 del propietario.
5. Nombre, correo1 y correo2, telefono 1 y telefono 2 del inquilino.
6. RFC, nombre y uso de CFDI para la factura.
7. Datos de la cuenta bancaria.

Aqui debemos definir también, a cuál correo (propietario o inquilino) se estarán enviando las notificaciones de: solicitudes de pago o facturas, pagos recibidos, comunicación en general.

**Comment by jccastillo0007** [comment]
ya esta funcionando el tema de elegir la casa por medio de la estructura del fraccionamiento, y no por rfc o nombre...

aún me falta agregar campos para propietario e inquilino, los campos que ya existían se tomaron como los campos de facturación... si que fue tricky, ya tenía el código porque antes asi estaba, pero si costo trabajo adaptarlo de acuerdo a las pantallas

**Comment by RigoFlores** [comment]
aún no permite almacenar una casa nueva... chiaaaaa...

<img width="520" alt="CAT CASAS" src="https://user-images.githubusercontent.com/2912775/61827582-85e8d980-ae2a-11e9-9514-1a49615b84ba.PNG">

**Comment by RigoFlores** [comment]
ahora marca internal error cuando trato de guardar una casa

**Comment by jccastillo0007** [comment]
listo... ya esta jalando para agregar casas...
