### ISSUE TITLE
Poner ambiente de pruebas para generar CCE desde escritorio (conector)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1595]
Ya sea que al RFC LAN le quites que solo lea optibelt, o que des de alta un nuevo RFC de pruebas de finkok, ya que LAN es el único rfc de pruebas para fhoy.
Que desde ese punto de vista, convendría que fuera LAN el rfc con el que tengo que probar.

**Comment by jccastillo0007** [comment]
según esto... el código dice que LAN no se esta usando con ningún conector... asi que lo puedes usar para CCE
