### ISSUE TITLE
CCE desde web - soportar CFDI tipo traslados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1596]
Hasta el momento solo soportamos CFDI tipo Ingreso.
Cuando se trata de CFDI tipo traslado, cambian algunas cosas.
El CFDI estándar, sale con un total de 0.00, de ahí que también dentro del CCE, los precios unitarios e importes salgan en 0. Según yo aquí no hay nada que hacer.
Igual se debe incluir el motivo de traslado, según yo tampoco hay nada que hacer, ya que existe un campo para ello.

Cambios para el CFDI tipo T y que además incluye el CCE:
a) La unidadAduana = '99'
b) la fracción arancelaria NO se debe incluir.
c) Opcionalmente, se puede incluir el nodo Destinatario del CCE, el cual lleva los siguientes campos, estos los deberían capturar en la pantalla de captura del complemento, pero SIN AFECTAR A LO QUE TENEMOS ACTUALMENTE:

Nombre="TECNOLOGIAS DE INFORMACION APLICADA" 
NumRegIdTrib="889010358"
Calle="CALLE GRINGA DEL DESTINATARIO" 
CodigoPostal="48309" 
Estado="MI" 
NumeroExterior="8868" 
Pais="USA"

**Comment by jccastillo0007** [comment]
ya subi a pru los últimos cambios...
ya esta configurado el archivo que me enviaste
ya lo esta leyendo bien, aunque le agregue los datos extras al final del producto, no afecta

pero, me marca muchos errores de datos , mejor pruebalo tu

Ya habia un archivo cargado en PRU del rfc XEXX... para addendas, no se cual era, pero lo borre para que pudiera tomar el archivo que subí en la pantalla de configuración.

Por cierto, aún tenemos el problema que si editan algo en la pantalla de configuración, cuando le dan salvar, marca error de certificado... chiaaa en chrome no funciona el fix que puse

**Comment by RigoFlores** [comment]
me atoré porque me marca este error:

CCE164 : El atributo cce11:ComercioExterior:Emisor:Curp no se debe registrar si el atributo Rfc del nodo cfdi:Comprobante:Emisor es de longitud 12. (3)

el rfc receptor es XEXX
El total del cfdi debe ser 0.0
la moneda USD

El curp dice ahí que no se debe incluir en rfc de long 13. 
Esto es, el curp no se incluye para personas morales.
Está haciendo una excepción para el rfc genérico extranjero, que aunque es de 13 caracteres de longitud, no se trata de una persona física.

Corrige y vuelvo a probar a medio día. Voy a méxico, pero a la hora de la comida, podré volver a probar

**Comment by jccastillo0007** [comment]
ya quite la curp, y luego me pidio el municipio del emisor...
ya se lo puse y ahora dice que el zipcode del receptor no es correcto
ahi si ya no se que hacerle
