### ISSUE TITLE
Duplica registros en la tabla condominio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1597]
Si borras un registro de casa, y luego lo vuelves a capturar, lo duplica en dicha tabla, refiriéndome a que el ID casa lo capturas idéntico.

No sé como esté planteado el funcionamiento de dicha tabla, pero me parece que está mezclando conceptos.

Por un lado, tendría que ser la estructura del condominio. Una vez definida, NO TENDRÍA PORQUE CAMBIAR dicha estructura. Ya estaría definida.

Por otro lado, al capturar los datos de una casa, solo se tendría que invocar a dicha estructura previamente definida. Pero lo que hace, es que en esa misma tabla guarda algunos datos de la casa, lo cual es cuando creo que se hace pelotas.

Ahora si borro el registro de una casa, tendría que eliminar el correspondiente registro en esa tabla de condominios, que no???

**Comment by jccastillo0007** [comment]
fixed... al eliminar una casa del catálogo, no se estaba eliminando de la tabla condominios

**Comment by RigoFlores** [comment]
no puedo dar de alta nuevos registros, para luego borrarlos...
es decir no puedo validar el issue. Si borro alguno existente ahora mismo (solo tenemos 3 registros), nos quedaremos con solo 2 registros para pruebas.

**Comment by RigoFlores** [comment]
sigo sin poder dar de alta casas... marca este error:

El campo 'rfcTextOwner' es obligatorio.
El campo 'rfcTextInquilino' es obligatorio.

<img width="520" alt="CAT CASAS" src="https://user-images.githubusercontent.com/2912775/61827526-5d60df80-ae2a-11e9-8ff9-2f5518053c0e.PNG">

**Comment by RigoFlores** [comment]
sigo sin poder validar, ya que no permite guardar un registro nuevo.
Marca internal error

**Comment by jccastillo0007** [comment]
oye k, si estas probando en pruebas..?
la pantalla de arriba, no corresponde a lo que tengo ahorita en pruebas
ya acomode los campos de pais, estado y código postal
chiaaaa

**Comment by jccastillo0007** [comment]
Este tema de duplicar registros, ya esta corregido

**Comment by RigoFlores** [comment]
esa pantalla fue de hace algunos días, y si... solo estoy en pruebas.
