### ISSUE TITLE
Condominios - CxC - cartera de casas, pagadas. No muestra el documento de pago generado.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1598]
Si consulto la cartera x casa, con el filtro de pagadas, debería mostrar el PDF de registro del pago, y no la solicitud de pago o factura. 
Ahora mismo, si consulto la cartera muestra las SP, pero no los recibos de pago.
Me surgió la duda, si borramos un regsitro de pago, que pasará con el recibo que se generó.
Quizás ese recibo se tiene que generar 'al vuelo', no crees???

<img width="526" alt="pagos" src="https://user-images.githubusercontent.com/2912775/61476417-a4defb80-a952-11e9-85a9-8699f6f4247a.PNG">

**Comment by RigoFlores** [comment]
Cuando se consulta CxC - Cartera por casa, y se elige una consulta que involucra pagos realizados (por ejemplo con el filtro pagadas o simplemente sin filtro) , al darle exportar incluir el documento de pago involucrado.

Es decir, ahora mismo cuando le damos exportar, se genera un zip, con las facturas (PDF y XML), así como los PDF de las solicitudes de pago. 
Bueno, dentro de ese zip, incluir los documentos de pago correspondientes cuando la consulta así lo arroje. Por ejemplo, esta consulta si incluye pagos (en amarillo), OK, pues al darle exportar, los PDF's de esos pagos se incluyan en el ZIP

<img width="539" alt="pagos" src="https://user-images.githubusercontent.com/2912775/63062977-6e988b80-bec0-11e9-8f8d-9a01da10cf8a.PNG">

**Comment by jccastillo0007** [comment]
este es el mismo problema que describí en el issue anterior que cerraste... mejor lo platicamos

**Comment by RigoFlores** [comment]
Si hay que platicarlo... ya que cuando se registra un pago, solo puede haber 2 opciones que son excluyentes:
a) generar un documento de pago: puede aplicara para SP o factura.
ó
b) generar un cfdi con complemento de pago, que únicamente aplica para factura.

Entonces no veo que se tenga que tomar la decisión si incluir uno y otro. De hecho, es muuuuy probable que el documento de pago, se ocupe poco o nada.

**Comment by RigoFlores** [comment]
lo que se pide únicamente, es que en el zip, se incluyan los documentos de pago... si se complica, por lo pronto, podemos dejar fuera los posibles CFDI con complemento de pago, que pudieran llegar a generarse

**Comment by RigoFlores** [comment]
de acuerdo a lo platicado, no hay forma de relacionar un registro de un pago... al documento de pago generado, entonces hay que corregir eso... es decir, agregar el campo o campos que sean necesarios para que quede dicha relación...

**Comment by jccastillo0007** [comment]
ya vi como si esta relacionado el pago y el cfdi generado, se va hacer por medio de la info de documento relacionado, ahi si tengo la serie y el folio...

**Comment by RigoFlores** [comment]
En qué menú se ven los documentos de pago?
Vi en CxC - Cartera por casa, exportar, y en el zip no están.
Vi en CxC - Reporte de pagos, aquí creo que sería el lugar ideal y se muestran unos PDFs, pero son las solicitudes de pago y no los recibos de pago.

Solo se muestran en Ingresos - Consultas, pero ahí como que no tendrían porqué mostrarse, o en todo caso deberían indicar a cuál SP o Factura están asociados.
