### ISSUE TITLE
Condominios - CxC- recibo de pago de una SP, no hay forma de recuperarlo.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1599]
Estamos generando un documento, que le llamaremos recibo de pago, cuando registramos el cobro de una SP o Factura, pero que no lleva CFDI de pago (regularmente nunca lo pedirán).
A ese recibo de pago se envían los mismos datos que al CFDI de pago, aunque en otro issue ya he solicitado que se envíen algunos otros datos.

Total, que el punto es el siguiente:
Cuando se registre un cobro de una SP o Factura (sin CFDI de Pago), se genera un recibo de pago, el jasper se debe llamar: pagoSP.jrxml, para que se coloque en la carpeta de los jasperTemplates. Ahorita lo estoy truqueando con una plantilla a la medida para pagos, pero eso implica que para cada cliente habría que hacer lo mismo, y por otro lado, que si generan un CFDI con complemento de pago, saldría incompleto.
Por otro lado, ese documento que se generó, nunca se podrá recuperar nuevamente, ya que no aparece en ninguna consulta. Solicité que se pudiera recuperar, pero en su lugar se presentan las SP, en lugar de esos recibos de pago (jeje). Las SP no es necesario ponerlas ahí, ya que esas se recuperan desde Ingresos-Consultas. Necesitamos que los Recibos de Pago (RP), se puedan recuperar para enviar por correo, o para imprimir o para lo que sea.

<img width="504" alt="recibosPago" src="https://user-images.githubusercontent.com/2912775/61478220-b3c7ad00-a956-11e9-88ab-19b92ce178e5.PNG">

Según yo, el lugar ideal es en el reporte de pagos, ya que ahí se desglosan los pagos registrados. 
Ahí deberían existir filtros adicionales, como estructura del condominio, casa, fecha de pago, rango de fechas para que al realizar la consulta, ahí se muestren los RP.
También podrían presentarse en CxC - Cartera por casa - Pagadas, como una segunda opción para descargarlos o enviarlos por correo.

<img width="326" alt="reportePagos" src="https://user-images.githubusercontent.com/2912775/61478513-45371f00-a957-11e9-8cb0-1069ed595dea.PNG">

**Comment by jccastillo0007** [comment]
Tenemos un problema aqui...
Paso 1, se emite una solicitud de pago, que es un cfdi tipo solicitud de pago y no se timbra
Paso 2, se emite un recibo de pago para pagar la solicitud de pago del paso 1
Paso 3, se genera un CFDi tipo recibo de pago, (sin complemento de pago y sin timbrar) 

Lo que se quiere ver en las consultas es el pdf generado en el paso 3 cierto?

El problema es que el pago del paso 2, esta relacionado con la solicitud de pago del paso 1, y no con el cfdi generado en el paso 3

 como la beisbol

**Comment by RigoFlores** [comment]
Mi no entender el paso 3.
Si aplicas el paso 2, el paso 3 ya no aplica. Son excluyentes.
O emites recibo de pago para registrar un pago a factura o a solicitud de pago.... o emites un cfdi con complemento de pago, asociado a una factura.

Un recibo de pago puede aplicar tanto a solicitud de pago, como a factura. Este último caso, cuando no se necesita el complemento de pago.

Por otro lado el complemento de pago, UNICAMENTE aplica para una factura, NO PUEDE aplicar para una solicitud de pago, ya que no contiene todos los elementos que ocupa el CFDI de pago.

**Comment by jccastillo0007** [comment]
si es correcto.
El paso 3 se ejecuta como resultado del paso 2, es decir, es la misma acción.. no es otra acción... asi ya queda claro o mejor lo platicamos

**Comment by RigoFlores** [comment]
ah ok, entiendo... lo voy a plantear así...
Para emitir un cfdi con complemento de pago, hay que ejecutar paso 1, 2 y 3.
En este caso solo se genera el CFDI de pago, pero NO SE EMITE EL documento de pago... es decir, no se tienen que emitir los 2.
Cuando le dan click en checkbox que dice incluir "CFDi de pago", eso implica que se generará el PDF de complemento de pago, pero NO el PDF del documento de pago.
