### ISSUE TITLE
En Catalogo de clientes No se puden Agregar clientes Extranjeros

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#16]
A que te refieres con este tema ? cual es el requerimiento para un extranjero ?

**Comment by jccastillo0007** [comment]
Me puedes indicar las características de clientes extranjeros ?

**Comment by RigoFlores** [comment]
SE REFIERE A QUE NO ESTABA ACEPTANDO EL RFC XEXX010101000, PERO AL PARECER YA LO ACEPTA
