### ISSUE TITLE
PANTALLA DE NÓMINA

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#160]
G)     EN LA PANTALLA DE NÓMINA, ASEGURAR QUE COLOQUEN EL BANCO, ASÍ COMO SUGERIR EL ID Y DESCRIPCIÓN PARA PERCEPCIONES Y DEDUCCIONES, CON LA POSIBILIDAD QUE LO CAMBIEN.

**Comment by jccastillo0007** [comment]
Done. y creo que estaba duplicado.
Aplica solo en el ERP

**Comment by RigoFlores** [comment]
INCORRECTO, SE PUEDE ALMACENAR EL REGISTRO, SIN EL BANCO

**Comment by jccastillo0007** [comment]
Yo había puesto la validación de que si el banco no era informado, se pusiera uno por default.... entonces quieres que lo hagamos obligatorio...

**Comment by RigoFlores** [comment]
oye, quién genera el error cuando falta el banco? El sat?
Si fuera el caso, su xsd marca como no obligatorio, pero con minInclusive value=1 (lo cual no se que signifique, pero asumo que no es opcional).
Aquí hay 2 temas:
a) por simplicidad se podría colocar un banco por omisión, pero sería algo que el cliente ni siquiera se enteraría, creo que está cabrón.
b) dado que se requiere el banco, entonces colocar el (*) de obligatorio, y que ellos elijan el banco que necesiten. Agregar todo el listado de bancos.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
WEY YA ME ESTOY HACIENDO PELOTAS, DONDE PROBAR ESTO. EN PRU NO JALA. DEJA CHECAR EN ERP

**Comment by RigoFlores** [comment]
ya lo ví, está en el erp
