### ISSUE TITLE
Web CFDI + CCE, no enviar datos de destinatario, cuando no se capture.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1600]
Cuando NO se captura la información del destinatario, no debe reportarse en el XML, ya que marca el error. Para empezar reporta el nodo vacío, y creo que ahí es donde se genera el error.

           <cce11:Destinatario>
                <cce11:Domicilio/>
            </cce11:Destinatario>

La información del destinatario son los nuevos campos que agregamos para el CCE + tipo T.

<img width="260" alt="destinatario" src="https://user-images.githubusercontent.com/2912775/61751061-b4a07a80-ad6c-11e9-86aa-5c23f81cdf6a.PNG">

**Comment by RigoFlores** [comment]
En cuanto al CFDI tipo I, aún si capturaron los datos del destinatario, no se debe enviar.
Ahora si no queremos agregar y agregar candados, con decirle al cliente que no lo capture, será suficiente.

**Comment by jccastillo0007** [comment]
este ya quedo cierto?
