### ISSUE TITLE
Condominios - Catálogo de casas, internal error si no se captura datos de facturación.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1601]
Marca internal error, si no se capturan los datos de inquilino o de facturación.
Recordar que lo único que si deberíamos esperar, son datos del propietario, ya que la casa podría no estar en renta, o no requiere factura.
Con ello los datos de inquilino y de facturación, deben ser opcionales.

Según yo, hoy lo que si espera son datos de facturación (rfc y nombre), de lo contrario marca internal error.

Yo creo que los datos de propietario, inquilino y facturación deben ser opcionales.
Capaz que no quieren dar datos de propietario tampoco (por confidencialidad), entonces con el ID de la casa, se puede trabajar. O que sea el nombre del propietario, correo y teléfono, los únicos dato obligados de esa parte. 

Por eso decía que la estructura + ID casa, ahora deben ser la llave en el catálogo.

Cómo la beisbol?

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ya permite guardar sin ningún dato de propietario, inquilino o facturación.
Pero ahora si guardo el registro así (sin ninguno de los 3 datos), ya no se puede editar... marca que error

Configuración inicial de Condominios errónea

**Comment by jccastillo0007** [comment]
fixed
