### ISSUE TITLE
Condominios - Internal error, se 'hace pelotas' con los combos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1602]
Esto puede suceder con el RFC genérico, que esté asociado a varias casas.
También podría suceder si el mismo dueño tiene mas de 1 casa o depa.

Entonces si elijo una casa con el RFC XAXX (por ejemplo la casa cuyo ID es E1P1D3).
No hago nada; solo ahora elijo otra casa (por ejemplo la casa cuyo ID es E2P3D4).
Se genera el internal error.

Esto sucede supongo en todas las pantallas, pero lo puedo reproducir en catálogo de casas y en Ingresos - solicitud de pago / facturas.

Aquí a como está ahora la aplicación de condominios, si le quitamos este error, podríamos evitarnos el 'nombre alterno', para RFC's repetidos, si este issue lo resolvemos.
Se trata que cualquier casa pueda tener cualquier RFC , incluso repetidos.
Todos los documentos de ingresos, facturas y cobros, tienen que estar relacionados por ID casa, y no por RFC de facturación.

**Comment by RigoFlores** [comment]
Supongo que hace corto circuito ahora mismo, porque aún se conserva en muchos lados la llave que el RFC deba ser único.

**Comment by RigoFlores** [comment]
ya ví, que aunque no tengan el mismo rfc marca ese internal error.
Eliges una en catálogos de clientes... (la elijo directamente, sin previos filtros).
Enseguida elijo cualquier otra, y se genera el error,

**Comment by jccastillo0007** [comment]
exacto... este problema no tiene que ver con el rfc... pues ya esta usando la casa como id... mas bien es el desmadre de que una vez que buscas una casa, ya no se puede volver a buscar otra casa... los combos se hacen pelotas...

**Comment by RigoFlores** [comment]
Pero cuando accedes a la pantalla, todos esos objetos tienen cierto valor...
No se le puede poner un botón de limpiar ahí a un ladito para que inicie las variables nuevamente?

**Comment by jccastillo0007** [comment]
creo que ya lo arreglé, puedes verificarlo con el catálogo de casas.. si esta bien lo replico al resto de screens donde están los combos

**Comment by RigoFlores** [comment]
para probar, primero intenté dar de alta mas casas, para tener mas combinaciones de prueba.
El punto es que encontré dos problemas:
a) **No guarda los nuevos registros.**
b) Cuando estás capturando un nuevo registro de casa, capturas la sección de la estructura.. y luego pasas al domicilio, al elegir estado, borra todos los datos del domicilio; aparentemente ahí se genera una inconsistencia.

**Comment by RigoFlores** [comment]
consulté la tabla de condominios, y de alguna manera si los almacenó, pero no los muestra en pantalla. 
El tema es que si hay un problema con el nuevo enfoque.
De los últimos 5 registros... los primeros 2 los 'confunde' al momento de querer registrar una solicitud de pago. elijo uno u otro, y muestra las mismas solicitudes de pago pendientes. Así lo dejaré para que lo revises.

De los últimos 3 registros, son los que capturé en catálogo de casas, pero que no muestra en pantalla; para caso práctico, no existen en el sistema pero si en la B D

<img width="950" alt="pelotas" src="https://user-images.githubusercontent.com/2912775/63190968-0915dd80-c02d-11e9-812b-2357db2d777b.PNG">

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ya no marca internal error, aún hace algunas cosas raras... por lo pronto cerraré este, y abriré otro para los detalles..
