### ISSUE TITLE
Condominios - CxC - Ingresar Cobro, muestra registros vacíos de RFC o nombre

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1603]
Estuve borrando registros de casas.
No sé, supongo que por ahí podría ir este tema de que muestra unos registros vacíos al momento de intentar consultar por RFC.
Aunque todas las consultas se tienen que alinear a como están los catálogos, y seguramente lo de elegir por RFC o nombre, desaparecerá, aún con ello, creo que algo de basura se queda en la BD, cuando se borran registros de casas.

<img width="419" alt="COBROS" src="https://user-images.githubusercontent.com/2912775/62075740-82c76200-b20b-11e9-929a-db3faafc9a6d.png">

**Comment by jccastillo0007** [comment]
si, pero este issue se anula ahora que le ponga los filtros de casa, en lugar de rfc
