### ISSUE TITLE
Condominios - catálogo de casas - dar opción de exportar el catálogo a excel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1604]
Estoy seguro que lo pedirán.
Incluir todos los datos que se capturan en pantalla, incluyendo la estructura del condominio.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
faltan los correos y teléfonos de propietario e inquilino; correo(s) de facturación.
Y si pagará con el período regular.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
en el excel, cuando si tiene capturado el teléfono, recorre las columnas. Como que no está extrayendo correctamente ese dato.
Anexo imagen del excel generado. Checa la columna nombre inquilino, la cual muestra el teléfono en los 2 primeros registros.

<img width="737" alt="telefonoscasas" src="https://user-images.githubusercontent.com/2912775/63231450-8e41f380-c1e1-11e9-9a5d-763cd85d2f3c.PNG">

**Comment by jccastillo0007** [comment]
ah ups, no vi tu último comentario.

una vez que le quite la info extra del json... va a ser dificil mostrar los teléfonos sin comas... igual para los emails

**Comment by RigoFlores** [comment]
los teléfonos, ni los emails llevan coma... si acaso llevarán espacios o guiones... pero no, comas ",", no llevan

**Comment by RigoFlores** [comment]
si te das cuenta lo que pasa ahora mismo, es que CUANDO SI INCLUYE EL DATO DEL TELÉFONO, se recorre una columna. Cuando no lo incluye, no sucede ello.

**Comment by jccastillo0007** [comment]
es por JSON, pero ya se lo voy a quitar, cada item lo separa por comas

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
se compuso algo, ya están alineados todos los campos.
Se descompuso otra cosa, ahora no muestra todos los datos...
Me preocupa que la bd no sea consistente. 

<img width="914" alt="exportarCasas" src="https://user-images.githubusercontent.com/2912775/63366225-e2161f00-c33e-11e9-993d-9f0aae961d84.PNG">

**Comment by jccastillo0007** [comment]
peque;o error de dedo
fixed

**Comment by RigoFlores** [comment]
oye, puedes poner el dato de id casa, en la columna A, pls

**Comment by jccastillo0007** [comment]
done
