### ISSUE TITLE
Condominios - Solicitud de pago, enviar el nombre del propietario en lugar de rfc/nombre

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1605]
La solicitud de pago no se timbra.
Por esa razón, el rfc y nombre ahí, salen sobrando.
El nombre del inquilino, puede cambiar cada cierto tiempo.

Creo que lo que debe aparecer en lugar de rfc y nombre, es el nombre del propietario.
En cuál variable me lo envías?

OJO, si en lugar de solicitud de pago, si ocupan generar factura, entonces ahí si va el nombre y rfc de facturación.

**Comment by jccastillo0007** [comment]
eso es solo al jasper verdad

**Comment by jccastillo0007** [comment]
te lo voy a mandar en la misma variable 
nombreReceptor=INQUILINO CASA 80
solo que cuando es una solicitud de pago, le pongo el nombre del inquilino, eso haria que este dato fuera obligatorio... y que tal si es el mismo propietario... tengo que validar esos dos datos, cierto, si esta vacio el inquilino le mando el otro

**Comment by RigoFlores** [comment]
Jeje... 
Lo que te pedí es que se envíe el nombre del propietario, ese es el que no cambia.
El nombre del inquilino, puede cambiar cada año o hasta mas seguido.

No nos compliquemos tanto.
Se envía el nombre del propietario,  a la variable nombreReceptor. En caso que no la hayan capturado, simplemente no se mostrará, ya que tu la enviarás vacía.

**Comment by RigoFlores** [comment]
Ya validé, y si, se está enviando el nombre del inquilino.

Hay que cambiarlo a propietario.

**Comment by jccastillo0007** [comment]
okas, done
