### ISSUE TITLE
Condominios - CxC - Ingresar cobro, envía las variables chuecas al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1606]
No envía lugar de expedición, ni refernecia al documento de pago en PDF.
Y las variables de forma de pago, moneda, tipo de cambio, monto del pago están chuecas

<img width="594" alt="reciboPago" src="https://user-images.githubusercontent.com/2912775/62088173-0c862800-b22a-11e9-9365-9e97f6e11569.PNG">

**Comment by jccastillo0007** [comment]
genere una solicitud de pago, y el log manda que esto se mando a jasper


lugarExpedicion=62578
formaPago=<null>
moneda=XXX
tipoDeCambio=$0.00

sin embargo jasper si se muestra chueco... es algo en la plantilla

fue le PAGO - 2

**Comment by jccastillo0007** [comment]
so... ya lo checaste?

**Comment by RigoFlores** [comment]
generé nuevamente uno, y sigue igual el error.
Me traje la plantilla del servidor, para super revisar y si, si está bien. Mira, así aparece en el jasper:
Las variables están bien asignadas, y esta plantilla volvió a mostrar los datos chuecos.

<img width="413" alt="doctoPago" src="https://user-images.githubusercontent.com/2912775/62646062-19360a80-b913-11e9-8c57-9028dc169780.PNG">

**Comment by jccastillo0007** [comment]
estas usando formaDePagoP, monedaP etc... las variables se mandan sin la P... 
Quieres que las cambie, no sabía si asi lo habías estado buscando desde el inicio

**Comment by RigoFlores** [comment]
Lo que si se acordó, es que íbamos a tomar  y partir del jasper del complemento de pago.
Eso fue lo que hice.
Si te das cuenta, toooodas las variables en ese cuadro, son específicas para el complemento de pago, no entendería porque tendríamos que mezclar las variables del documento de pago, con el cfdi estándar.

Me parece que por estandarización, debemos manejar lo mismo que el complemento de pago.
En resumen, si tendrían que ser las variables con la P.

Como vex?

**Comment by jccastillo0007** [comment]
pues también los manda ..

formaDePagoP=03,monedaP=MXN,tipoCambioP=1.00
fechaPago=2019-08-08T20:53:08


Ojo.. solo lo manda si generan el documento de pago... si no, pues no.... ese sería el problema de usar las variables de jasper para pago

**Comment by RigoFlores** [comment]
ok, dime como quedaría... porque este es un documento de pago, pero que no incluye el cfdi de pago... como queda?

**Comment by jccastillo0007** [comment]
creo que encontré cómo hacerlo de forma adecuada.

Pregunta. si no solicitan el documento de pago... que tipo de pago le pongo ? 

efectivo ?

**Comment by jccastillo0007** [comment]
le deje fijo 01, que es efectivo... esto aplicará solo cuando sea una SP  sin documento de pago..

las variables si quedarán con la P al final

**Comment by RigoFlores** [comment]
Para salir del paso está bien, pero la forma de pago es un DATO IMPORTANTE en la cobranza. Imagínate que le quieran dar seguimiento a una aclaración, y que todo diga EFECTIVO, no pues para nada, jeje.

Por lo tanto, la solución de raiz pudiera ser una de:
a) Subir la textbox forma de pago al paso 1. Si se genera el CFDI de pago, de ahí se toma el dato.
b) Habilitar la captura del paso 3 siempre, y ÚNICAMENTE cuando le seleccionen 'incluir CFDi de Pago', entonces generarlo.

Para mí, la solución (a) es la mejor, ya que la (b) propone muchos datos a capturar y realmente no serviría ninguno, mas que la forma de pago y si acaso la moneda. Por cierto, hoy la moneda también se asigna por omisión, lo cual en algún momento representará un problema, cuando el AMC salga de México, o incluso en condominios de alto pedorraja en México.

**Comment by RigoFlores** [comment]
Por cierto, de la forma de pago que se envía el PDF, mas que la clave, se ocupa la descripción, o en su caso los 2 datos.

**Comment by jccastillo0007** [comment]
listo.

Antes se mandaba la descripción, y luego se mandó la clave... si le pongo todo, alguna plantilla puede descomponerse, o tal vez el xml se vea impactado

**Comment by RigoFlores** [comment]
en el pdf de las facturas siempre se envía la clave y descripción.
Aquí según yo, debe ser lo mismo.

**Comment by jccastillo0007** [comment]
ya se esta subiendo la versión que manda ambas
espero no se rompa algo
