### ISSUE TITLE
Condominios - CxC - eliminar la opción de registrar CFDi externo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1607]
no creo que se de el caso, y menos para los ingresos, ya que ahí casi no estarán facturando.
Dejémosla disponible, por si en un futuro la llegan a pedir.
por lo pronto quitarla

**Comment by jccastillo0007** [comment]
pero es mas bien en ingresos que no?

en CxC no tenemos esa opción

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
correcto, era en ingresos.
Ya me confundo con tantas opciones, y es que las pruebas casi siempre hay que repetirlas todas....
