### ISSUE TITLE
Condominios - CxC, agregar la búsqueda que se tiene en catálogos e Ingresos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1608]
Para el menú de Ingresar Cobro y Cartera por Casa.
En los otros menús, no se ocupa esa búsqueda

**Comment by jccastillo0007** [comment]
ya están todas las opciones de ingresos... voy con CxC

**Comment by jccastillo0007** [comment]
ya solo me falta ponerlo en cobros

**Comment by RigoFlores** [comment]
Así es, solo falta agregarlo a la opción de CxC - ingresar cobro

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Aquí tiene un defecto. 
Capturas el paso (1), esto es monto, fecha de pago y REFERENCIA. (según yo, aquí además de esos 3 datos, hay que subir la forma de pago del paso 3, pero eso es oootra cosa).

Luego en el paso 2, buscas la casa, ya sea directamente en el combo de casas o navegando en los combos. Cuando llegas finalmente a elegir la casa... SE BORRA LA REFERENCIA CAPTURADA.
Los datos del paso 2, no tendrían porqué cambiar los del paso 1. Si no te das cuenta, se podría ir el documento sin referencia.

Total, que si bien ya existe la forma de navegar por la estructura de la casa, ahora no tiene porque borrar los datos del paso 1.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ok, quedó casi todo, pero la forma de pago, la debe enviar al pdf con la descripción.
Ejemplo: 01. Transferencia electrónica de fondos.

Ahora mismo solo envía 01, lo cual no dice gran cosa si no conoces el catálogo.
