### ISSUE TITLE
Ingresos - Consultas, eliminar tipos de CFDI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1609]
En ese filtro, solo dejar: factura, nota de crédito, solicitud de pago y documento de pago.

Documento de pago, tendría que ser que muestre tanto los no timbrados, que supongo serán la mayoría, como los complementos de pago, que yo creo que casi no se ocuparán.

<img width="166" alt="tipocfdi" src="https://user-images.githubusercontent.com/2912775/62091148-3729ae00-b235-11e9-8ee6-18e20cfddf46.png">

**Comment by RigoFlores** [comment]
por cierto, si filtro por solicitud de pago o documento de pago, marca internal error

**Comment by jccastillo0007** [comment]
fixed
