### ISSUE TITLE
Evitar que se pierda la informacion en memoria al cerrar la aplicacion

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#161]
1) QUE CUANDO SE CIERRA INMEDIATAMENTE, NO 'ALCANZA' A GUARDAR LA BD (EL
FACTURAT_DB.LOG SE QUEDA VACÍO), DUPLICANDO FOLIOS EN LA SIGUIENTE SESIÓN

**Comment by RigoFlores** [comment]
se puede evitar o no?

**Comment by jccastillo0007** [comment]
Si es posible, forzar a escribir los cambios realizados a la base de
datos... requiere de R&D​, que tanta prioridad tiene este issue?
