### ISSUE TITLE
Condominios - Catálogo de casas, no muestra el correo del inquilino aunque si lo tiene

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1610]
Si elijo una casa, donde si tiene capturados los correos de inquilino y propietario, no muestra el correo del inquilino.

<img width="390" alt="correo" src="https://user-images.githubusercontent.com/2912775/62142372-d8574980-b2b3-11e9-8cf3-3bd322c0532d.PNG">

Hasta que le doy editar ya muestra el correo del inquilino:

<img width="520" alt="correos" src="https://user-images.githubusercontent.com/2912775/62142440-fcb32600-b2b3-11e9-8e92-370edd2eb717.PNG">

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
jajaja... ahora no muestra el email del propietario.
Lo puedes chequear con la casa 80

**Comment by jccastillo0007** [comment]
fixed
