### ISSUE TITLE
Condominios - CxC - Cartera general, mostrar nombre de propietario y NO de inquilino

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1612]
En pantalla debe mostrar el nombre del propietario (ahora mismo muestra el nombre del inquilino), así como el id casa. También esos se deben enviar al excel.

Eliminar el checkbox de 60, 90 y 120, ya que aquí no aplica.

<img width="336" alt="carteraGeneral" src="https://user-images.githubusercontent.com/2912775/62145554-49e5c680-b2b9-11e9-9b0e-29496912061a.PNG">

**Comment by jccastillo0007** [comment]
listo...

Ojo.. el nombre no lo debemos cambiar, pues se toma de la factura generada, y si fue hecha a nombre del inquilino, no podemos cambiar esa info...

Por cierto, la base de datos ya esta toda corrupta... algunas cosas no coinciden.. has borrado cosas a manita ?

debemos identificar si es cosa nuestra o no

**Comment by RigoFlores** [comment]
No hago nada a manita, mas que reiniciar todo lo de ingresos, cxc, egresos  pagos con estos cueris.

Quizás lo que está chueco es que antes en la solicitud de pago se ponía el nombre del inquilino, y ahora se enváa el nombre del propietario. O  cómo tu dices, se mas específico... que es lo que no coincide o está corrupto?


delete from CFD_CFD_Products;
delete from CFD;
delete from CFD_Products;
delete from CFD_FinancialDetails;
delete from Payments;
update ClientFolios set currentFolio = '0' where owner = 'TCM970625MB1';

**Comment by RigoFlores** [comment]
la casa 80 tiene algunos problemas, yo no he borrado nada a manita.
mira como se ve la cartera general (que no muestra el número de casa) y también el rfc en la captura de cobros (que se muestran registros duplicados, el rfc de la TIA es el que le corresponde a la casa 80).

<img width="326" alt="casa 80" src="https://user-images.githubusercontent.com/2912775/62331935-22425a00-b483-11e9-8ea5-a9b5e875fcd0.PNG">


<img width="469" alt="rfcDuplicados" src="https://user-images.githubusercontent.com/2912775/62331940-25d5e100-b483-11e9-8b24-344e4d190dd3.png">

**Comment by jccastillo0007** [comment]
En este caso, habia algo chueco en la base de datos

mysql> select id, rfc, owner, homeNickname from Client;
+------+---------------+--------------+---------------------------------------------------------------------------+
| id   | rfc           | owner        | homeNickname                                                              |
+------+---------------+--------------+---------------------------------------------------------------------------+
|    1 | TCM970625MB1  | FacturaT     | NULL                                                                      |
| 5820 | FOPR681125BQ0 | TCM970625MB1 | Residencial San Mateo-CONDOMINIO1-null-null-SAN FELIPE-40-1300-CASA 40    |
| 5823 | XAXX010101001 | TCM970625MB1 | Residencial San Mateo-SIN-SIN-SIN-SAN SIMON-23-23-PSS23                   |
| 5832 | XAXX010101000 | TCM970625MB1 | Residencial San Mateo-EDIFICIO 1-PISO 1-null-ANDADOR C-3-NO APLICA-E1P1D3 |
| 5842 | XAXX010101000 | TCM970625MB1 | Residencial San Mateo-EDIFICIO 2-PISO 3-null-ANDADOR F-4-NO APLICA-E2P3D4 |
| 5846 | TIA101020BP4  | TCM970625MB1 | Residencial San Mateo-CONDOMINIO1-null-null-SAN FELIPE-80-3051-CASA 80    |
+------+---------------+--------------+---------------------------------------------------------------------------+
6 rows in set (0.00 sec)

Los registros con id  5845,  5844,5833 y 5831 no tenian un condominio asociado.. ahorita ya esta todo consistente... hay que identificar cuando algo se mueve...

**Comment by RigoFlores** [comment]
Sigue sin mostrar el nombre del propietario, muestra ahora el nombre de facturación.
Es no siempre se utilizará, pero el nombre del propietario regularmente se debe llenar.

<img width="382" alt="carteraGral" src="https://user-images.githubusercontent.com/2912775/62644108-fa357980-b90e-11e9-91f6-4f60ff74a512.PNG">

**Comment by RigoFlores** [comment]
me preocupa lo de las bd chueca, porque lo único que hago es editar, borrar, agregar registros, y según yo no está siendo consistente con el borrado de registros.

Este issue marca puntualmente el nombre del propietario, y resulta que se muestra el nombre de la factura, no sé porque todo esto nos retrasa y nos retrasa, siendo algo que creo es relativamente simple.

**Comment by jccastillo0007** [comment]
lo que pasa es que la info se toma de la factura, y si se genera a nombre del inquilino ese es el que aparece, no estoy seguro si debamos cambiar eso

**Comment by jccastillo0007** [comment]
![image](https://user-images.githubusercontent.com/2245679/62670640-92585080-b959-11e9-9577-37701776bb1c.png)

**Comment by jccastillo0007** [comment]
acabo de probar, y eso me sale... esta bien no ?

**Comment by RigoFlores** [comment]
así si... deja ver
