### ISSUE TITLE
Condominios - Catálogo de casas no almacena email de propietario.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1614]
Chiaaaa... seguimos con problemas... no podemos dejar firme la base de todo, que ese el catálogo de casas.
Al agregarle el campo de correo de facturación en la pantalla (que se pidió desde el inicio, pero que apenas se atendió), supongo que  por ese cambio, ahora el correo del propietario, lo almacena como correo del inquilino, y el correo del propietario lo deja en blanco.

Es decir capturas todo bien en la pantalla, y después de guardarlo, lo consultas, y el correo del propietario que habías capturado, lo asigna al correo del inquilino, y el del propietario queda en blanco.

<img width="389" alt="propietario" src="https://user-images.githubusercontent.com/2912775/62319082-cec01400-b462-11e9-8357-a9abf29dc906.PNG">

**Comment by jccastillo0007** [comment]
fixed
