### ISSUE TITLE
CxC - Cartera por casa. Ajustes varios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1615]
Aquí se muestran los PDF que corresponden a solicitudes de pago o facturas.

Se puede hacer:
a) También se muestren lo documentos de pago correspondientes.
b) Que solo se muestren los documentos de pago
c) Eliminar los PDF de esa pantalla, y que se muestren mas registros en la pantalla.

La opción de exportar, debería generar un zip con los PDF de las solicitudes de pago/ facturas y documentos de pago correspondientes.

**Comment by jccastillo0007** [comment]
me confunde lo que pides... a y b se contradicen, incluso también el c

**Comment by jccastillo0007** [comment]
al exportar ya no se ocupan el excel y pdf ?

**Comment by RigoFlores** [comment]
Se trata de elegir una opción (a), o (b) o (c), es decir, una de las 3. 
Yo me quedaría con la (c). Que no se muestren los PDF's en pantalla, y a la vez que se puedan mostrar mas registros en esa pantalla.

Ahora, al dar exportar se ocupan 2 cosas:
1) El excel con el reporte
2) Un zip con los PDF de facturas, solicitudes de pago y documentos de pago resultantes de la consulta. Los XML, solo en el caso de facturas. 

Hoy en día, tenemos un PDF como reporte (ejecutivo), igual podríamos mantenerlo, aunque no sería tan tan importante por lo pronto.

**Comment by jccastillo0007** [comment]
ok, entonces esto ya esta hecho 
c) Eliminar los PDF de esa pantalla, y que se muestren mas registros en la pantalla.

**Comment by jccastillo0007** [comment]
De estos item:

Ahora, al dar exportar se ocupan 2 cosas:
1. El excel con el reporte
2. Un zip con los PDF de facturas, solicitudes de pago y documentos de pago resultantes de la consulta. Los XML, solo en el caso de facturas.

El 1 ya esta.
Deja veo como jijos hago el 2

**Comment by RigoFlores** [comment]
si, el (1) siempre ha existido.
el 2 es exactamente lo mismo que haces en Vemtas-Consultas, cuando le das exportar. Se genera el zip con los PDF y XML.

**Comment by jccastillo0007** [comment]
listo... checa si se incluyen todos los archivos vale

**Comment by RigoFlores** [comment]
si, al parecer si todos....
