### ISSUE TITLE
Migración de catálogo de clientes, de escritorio a Web rfc TRF120111E21

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1617]
Se ocupa para este cliente:

TRF120111E21

Te mandaré su BD por correo, así como su llave. 
No ocupas nada mas?

**Comment by RigoFlores** [comment]
y luego?

**Comment by RigoFlores** [comment]
ahora también este otro RFC: CUJE790815NS9
Solo se ocupan los clientes que están de la versión 3.3. 
Es decir, de los XML que llegaron desde escritorio al web.

**Comment by jccastillo0007** [comment]
y tienes forma de bajar todos los RFC?, buscarlos por día esta ca... no recuerdo si alguna búsqueda nos da todos los xml y los podemos bajar por zip... deja veo

**Comment by RigoFlores** [comment]
si, en ventas consultas, sin ningún filtro, te dará todos los XML generados bajo la versión 3.3
De ahí le das exportar y te genera un zip co los xml y pdfs

**Comment by RigoFlores** [comment]
obvio, el cliente ya está también como loco.
Hace 7 días espera esta migración.

**Comment by RigoFlores** [comment]
ya están esperando los 2 RFC's

**Comment by jccastillo0007** [comment]
listo, ya están los clientes... no sé cómo sacaste los rfc y nombres, pero venían muchos duplicados..

**Comment by RigoFlores** [comment]
tienes razón... se me pasó filtrar esa parte.

Los rfcs los tomé de todas las facturas generadas en versión 3.3
Y pues si, lo mas probable es que varios se repitan, esto es, los clientes (receptores) que son recurrentes.
