### ISSUE TITLE
Web - No puede timbrar un cfdi con complemento del INE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1618]
El usuario es MAHP4803129K5
Todos sus recibos de honorarios, son iguales cada mes.
Hasta el mes pasado si timbró, porque se fue por finkok. 
Puedes consultar el XML de Julio, para que veas que datos lleva, pero el único producto (honorarios profesionales) ya incluye el precio unitario correcto. Incluye deducciones de ISR e IVA. Los datos de la addenda, ya están precargados; para capturar la addenda solo se abre la ventana, se le da click en cualquier parte blanca de la ventana y finalmente se cierra.

Ahora ya marca error. Te mandé todo por correo.

2019-08-07 13:09:53,488 ERROR [https-jsse-nio-8443-exec-12] (CFDBusinessLogicProvider.java:356) - 003 : 301 - XML mal formado : No es posible resolver schemalocation de complemento <ine:

**Comment by RigoFlores** [comment]
ya lo mandé a fhoy, tu no le puedes buscar?
La cliente está chingue y chingue...

**Comment by RigoFlores** [comment]
FactureHoy, al menos ya respondió que una url es incorrecta:
http://www.sat.gob.mx/sitio_internet/cfd/ine/ine10.xsd

Correcta:
http://www.sat.gob.mx/sitio_internet/cfd/ine/ine11.xsd

Lo raro es que finkok si lo estaba timbrando, no maaaaa..... tsssss... se me hace que por ahí también le suspendieron su certificación...

Ya corregido, de todos modos no lo timbra, sigue marcando el mismo error...

**Comment by RigoFlores** [comment]
en el xml que se genera en la salida del catalina.out, lo tomé y le modifiqué eso que comentó fhoy;  desde el conector intenté timbrarlo y mandó el mismo error.
Por ello pedí a fhoy, que ellos lo intenten, pero igual van lentos.

**Comment by jccastillo0007** [comment]
ya subi a pro el fix con el schema 11 del ine
