### ISSUE TITLE
Condominios - Ingresos - Solicitud de pago mostrar propietario en lugar de rfc-nombre

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1619]
El RFC y nombre (de la facturación), no entran en juego en una solicitud de pago.
OJO, si están relacionados en el momento que una solicitud de pago la quieran facturar, pero eso es ooootra historia.
Me refiero a la pantalla. Ahí no tiene caso que se muestre el RFC y Nombre.
En su lugar mostrar el nombre del propietario.

<img width="427" alt="solicitudPago" src="https://user-images.githubusercontent.com/2912775/62723566-a1c9af00-b9d6-11e9-9652-821df97494dd.PNG">

**Comment by jccastillo0007** [comment]
fixed
