### ISSUE TITLE
no asigna correctamente el nombre en el acuse de cancelación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#162]
en la versión 8.0.1, cuando se cancela una factura sin serie, aunque la cancelación ya está ok, el nombre del acuse en pdf y XML, solo lo almacena como '.cancelado', lo cual provoca que todos los acuses del mes se sobreescriban, y lo que es lo mismo, se pierdan.

**Comment by jccastillo0007** [comment]
fix it.
