### ISSUE TITLE
Condominios - Ingresos/consultas - CxC/cartera x casa, no funcionan las jerarquías de la estructura del condominio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1620]
A ver si puedo explicarme.
En estos 2 menús, se ocupa realizar consultas, y para ello se aplica el filtro para elegir la casa, o un conjunto de ellas.

Por ejemplo, si elijo en el segundo nivel: Condominio 1 SIN NINGÚN OTRO FILTRO HACIA ABAJO, solo debe darme las casas que estén ligadas al condominio 1. Es decir solo mostraría casa 40 y casa 80. 
Pero si elijo el 2o nivel como EDIFICIO 2, no debería darme ninguna casa, ya que todas mis pruebas solo las estoy realizando sobre casa 40  y casa 80. Sin embargo, me despliega la información de todo. No está aplicando este filtro.

Es decir, no está funcionando correctamente el filtro por estructura del condominio.
Aquí el ejemplo, el único filtro es EDIFICIO 2, y al consultar, no debería aparecer nada.

<img width="548" alt="FILTRO" src="https://user-images.githubusercontent.com/2912775/62724758-4d73fe80-b9d9-11e9-889b-2aaa7f22e255.PNG">

**Comment by jccastillo0007** [comment]
ya esta listo en ingresos/consultas

**Comment by RigoFlores** [comment]
OK para Ventas-consultas, queda pendiente CxC-Cartera por casa

**Comment by jccastillo0007** [comment]
listo
