### ISSUE TITLE
ACTIVAR EMISIÓN DE RETENCIONES PARA NUEVO RFC Y ENVIAR LOS DATOS DEL COMPLEMENTO AL JASPER

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1621]
Alta de Dividendos para el RFC TIE101203NZ4 

Y CUANDO SE EMITA EL **DOCUMENTO DE RETENCIONES JUNTO CON EL COMPLEMENTO DE DIVIDENDOS**, ENVIAR LA INFO DEL COMPLEMENTO AL PDF.
ANEXO UN XML COMPLEMENTO, YA SOLO TU ME DIRÁS EN QUE VARIABLES LLEGAN.

DividOUtil CveTipDivOUtil="06" 
MontDivAcumExt="0.0" 
MontDivAcumNal="285720.0" 
MontISRAcredNal="85720.0" 
MontISRAcredRetExtranjero="0.0" 
MontISRAcredRetMexico="0.0" 
MontRetExtDivExt="0.0" 
TipoSocDistrDiv="Sociedad Nacional"/>

Remanente ProporcionRem="0.0"/>

**Comment by RigoFlores** [comment]
ahora mismo el rfc que tiene dividendos ya configurado es DMR840730523

**Comment by jccastillo0007** [comment]
las variables ya se mandan al jasper, como datos extras.. en este orden

		List<Field> fields = cfd.getExtraData();

		fields.add(new Field("retencion", shared.getKeyRetention()));
		fields.add(new Field("descretencion", shared.getDescRetention()));
		fields.add(new Field("curpemisor", shared.getSourceCURP()));
		fields.add(new Field("nacionalidad", shared.getTargetNationality()));
		fields.add(new Field("curpreceptor", shared.getTargetCURP()));
		fields.add(new Field("mesinicial", shared.getIniMonth()));
		fields.add(new Field("mesfinal", shared.getEndMonth()));
		fields.add(new Field("ano", shared.getYear()));
		fields.add(new Field("gravable", shared.getGravable() + ""));
		fields.add(new Field("exento", shared.getExento() + ""));
		fields.add(new Field("retenido", shared.getTotalRetenido() + ""));

Dividendos

		fields.add(new Field("dividendos_type", shared.getDividendosType()));
		fields.add(new Field("montdivacumext", df.format(shared.getMontDivAcumExt())));
		fields.add(new Field("montdivacumnal", df.format(shared.getMontDivAcumNal())));
		fields.add(new Field("montisracrednal", df.format(shared.getMontISRAcredNal())));
		fields.add(new Field("montisracredretext", df.format(shared.getMontISRAcredRetExtranjero())));
		fields.add(new Field("isracredretmex", df.format(shared.getMontISRAcredRetMexico())));
		fields.add(new Field("montretextdivext", df.format(shared.getMontRetExtDivExt())));
		fields.add(new Field("proporcionrem", df.format(shared.getProporcionRem())));
		fields.add(new Field("tiposocdistrdiv", shared.getTipoSocDistrDiv()));

**Comment by jccastillo0007** [comment]
ya le puse los plugins al cliente que indicaste

**Comment by RigoFlores** [comment]
con la primera variable tronó... chiaaaaa... **dividendos_type**


2019-08-13 16:33:36,466 ERROR [https-jsse-nio-8443-exec-11] (JasperCreatorImpl.java:247) - net.sf.jasperreports.engine.JRException: Error retrieving field value from bean :  dividendos_type                                                                                                                                                             net.sf.jasperreports.engine.JRException: Error retrieving field value from bean : dividendos_type
--

**Comment by RigoFlores** [comment]
Ya solo falta timbrarlo para cerrar el isusue, pero me deben los datos para la prueba.
Creo que quieren o tienen un caso especial, que al parecer no lo soportamos ahora, pero esperemos a que me manden el ejemplo del XML.

**Comment by RigoFlores** [comment]
creo que ya se a que se refieren, tanto del complemento como del cfdi de retenciones, existen algunos atributos que son OPCIONALES, y ahora mismo los pide a huevo, entonces si falta corregir eso.

**Comment by jccastillo0007** [comment]
bueno, nos esperamos al ejemplo, para no estar experimentando
pues no definiste los OPCIONALES

**Comment by RigoFlores** [comment]
están en los xsd... te los listo?

**Comment by jccastillo0007** [comment]
no, porque al final no sabemos si ese es el problema, mejor nos vamos a la segura
además de que nos aseguramos que ya lo van a usar, por lo visto no les urge o no lo necesitan todavía.

**Comment by RigoFlores** [comment]
no hay problema ahora mismo, pero cuando no quieren incluir un dato que deber[ia ser opcional, la aplicacion lo incluye con valor de 0, y eso ya en si es un dato valido.
Lo que dicen es que si no lo capturan, no debe enviarse.

Y me han estado hablando diario, y aunque no es tanto, es una lana atorada, nos interesa ya entregarles. Esperemos al ejemplo

**Comment by RigoFlores** [comment]
no tanto que digan como debe ser, sino que si un dato opcional no se debe incluir, que haya la manera de no incluirlo.

**Comment by jccastillo0007** [comment]
y el ejemplo del xml?, cuando te llamen recuérdales que lo necesitamos

ellos son los primeros que usan el cfdi de retenciones? o porque no había tronado antes, lo que mencionas es muy genérico "tanto del complemento como del cfdi de retenciones, existen algunos atributos que son OPCIONALES, y ahora mismo los pide a huevo,"
