### ISSUE TITLE
Condominios - Ingresos - Consultas - Agregar ID casa a la matriz que se muestra

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1622]
Si realizamos una consulta, el resultado en pantalla no muestra el ID casa, no sabemos a quién pertenecen las SP.
Creo que podemos eliminar la columna RFC, y en su lugar mostrar el ID casa.

<img width="622" alt="ingresosConsulta" src="https://user-images.githubusercontent.com/2912775/63182480-47ed6880-c018-11e9-84ab-79fab0ef32ef.PNG">

**Comment by jccastillo0007** [comment]
checa este , recuerdo que si subi un fix... pero no lo probé

**Comment by RigoFlores** [comment]
ok, ya quedó en pantalla.
Olvidé pedirlo en el excel, de preferencia después de la fecha (columna B).

**Comment by jccastillo0007** [comment]
done
