### ISSUE TITLE
Condominios - Implementar el seguimiento a casos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1623]
Como te sugería, hay que empezar con algo básico.
Según yo, lo que te envié por correo, puede funcionar. es como ir guardando un excel.
si la llave es : ID CASA + NOMBRE ISSUE + FECHA apertura ordenado por ID, pues en automático te da la cronología de los comentarios. Incluso por fecha del comentario, te daría igualmente la cronología.

Campos generales del caso son (HEADER):

Nombre   caso
Fecha apertura
Usuario apertura
Status

El resto serían campos que se van agregando como en 'detalle' del caso (DETAIL).

FECHA 
| USUARIO 
| COMENTARIO 
| USUARIO DESTINO 
| RUTA ARCHIVO

Presentarlo en pantalla, solo sería algo así como una matriz de datos, donde solo se puede editar los campos que el usuario haya capturado.
Exportarlo sería generar un excel.

**Comment by jccastillo0007** [comment]
en los campos de arriba estas manejando tres usuarios, puedes definir que usuarios son en cada caso... recuerda que con la tecnologia actual, no podemos manejar matriz editables tipo excel

**Comment by RigoFlores** [comment]
Usuario apertura, es el usuario que crea el caso.
En el detalle:
Usuario es el que captura el comentario
Usuario destino, es  el usuario quién debe leer el comentario.

Por ejemplo el primer comentario, el usuario apertura y usuario, son los mismos. Por ejemplo CASA 40. El usuario destino, sería ADMIN.   (la casa 40 levanta un caso para el usuario administrador). Eventualmente podría ser cualquiera de los usuarios del sistema para ese condominio, por lo pronto la comunicación sería de una casa hacia el usuario administrador, y viceversa.

**Comment by jccastillo0007** [comment]
y son usuarios o casas ? y de donde se tomará los usuarios, ?

**Comment by RigoFlores** [comment]
ok, es buena pregunta. Son realmente casas y administración.
Aquí ya entra en juego el tema de repositorios a nivel casa, a nivel general y a nivel administración.

Una casa debe tener un usuario para acceder al sistema, y de solo consulta podrá ver su historial.
Es similar al descargaT. Donde podrá realizar varias consultas de solo su casa, y otras que serán a nivel general. Asimismo, tendrá la opción de levantar los casos.

El usuario admin, tendrá acceso al repositorio general, al repositorio por casa y al repositorio de la administración. También tendrá acceso a consultar los casos que le vayan levantando, así como comentarlos, para que vayan de regreso a la casa origen.

**Comment by jccastillo0007** [comment]
sigo avanzando en este tema... estoy trabajando ahorita en la opción de incidencias del propietario... ya estoy en la pantalla modal para agregar mas comentarios o cerrar el issue
