### ISSUE TITLE
condominios - catálogos de casas, al borrar un registro, pedir confirmación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1624]
Para que no lo borren por accidente.... que pida confirmación

**Comment by RigoFlores** [comment]
Mostrar el ID casa y nombre de propietario, al solicitar la confirmación.

**Comment by jccastillo0007** [comment]
esto ya lo tengo... pero ahorita ya se me descompusieron los combos... no se puede probar

**Comment by jccastillo0007** [comment]
done
