### ISSUE TITLE
Condominios - catálogos de casas, elijo una casa y luego otra, se hace pelotas con la data.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1625]
De los registros ya existentes, elijo uno y lo presenta en pantalla en modo 'solo lectura'. Por ejemplo la casa 40.

<img width="443" alt="casa1" src="https://user-images.githubusercontent.com/2912775/63216596-3762ee00-c0fd-11e9-9b39-f632261a8735.PNG">

Sin salirme de la pantalla, elijo otra casa, por ejemplo el E1P1D1. Mantiene los datos de la casa anterior. Si le doy editar, borra todo... es decir, si quiero editar esa casa, perdería toda la info:

<img width="504" alt="casa2" src="https://user-images.githubusercontent.com/2912775/63216724-421e8280-c0ff-11e9-97ae-9ab9ba8da516.PNG">

Así se ve después que le doy editar; borra todos los datos, pero además el id casa está chueco.

<img width="483" alt="editarcasa" src="https://user-images.githubusercontent.com/2912775/63216736-8578f100-c0ff-11e9-8e4b-f49deabf7f1b.PNG">

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Para búsqueda de lo que hoy existe, me parece que si quedó. Aún marca de repente internal error, pero no he identificado el escenario.

Peeeero, si quiero dar de alta por ejemplo, un nuevo departamento, del edificio 1 o 2, simplemente lo sobreescribe al anterior, es decir... a como está ahora mismo, digamos que solo permite un depa para una misma combinación de "edificio-piso-calle", lo cual no termina de quedar... yo pienso que deberían existir las tablas anidadas con constrainst necesarios, así como por ejemplo los estados, que están asociados a los países; cambias de pais, cambia el listado de estados... pero como tu veas..

**Comment by jccastillo0007** [comment]
Fixed.
