### ISSUE TITLE
Actualización de addenda MABE - Web y Escritorio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1626]
Y cómo podemos manejarla para cobrarla a cada cliente que ocupe, sobre todo en web?
Por un lado está el tema de web, que es el prioritario, y por otro lado el tema de escritorio.
Cómo vex?

<img width="517" alt="mabeCambios" src="https://user-images.githubusercontent.com/2912775/63458219-0265dc80-c418-11e9-825e-275e483421ae.PNG">

En escritorio, adicionalmente tenemos el problema de la forma en que se reportan las tasas dentro de la addenda.

**Comment by RigoFlores** [comment]
[referencia MABE.zip](https://github.com/jccastillo0007/eFacturaT/files/3531872/referencia.MABE.zip)

Este es el XML que da como ejemplo mabe.
Según yo, es lo mismo que mandaste en tu modificación manual, esto es se repite:

 **xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"**  

tanto en el XML estándar, como en el header de la addenda. Amén de agregar la s, en el  **https**, en el schema location y en el namespace.

**Comment by RigoFlores** [comment]
A los de mabe se les pasó una 's', anteriormente eras solo 2 's' y realmente son 3 las que se ocupan.
Faltaba la del xsd

<img width="557" alt="mabeCambios" src="https://user-images.githubusercontent.com/2912775/63799576-f4113800-c8d1-11e9-8f61-a0f12b6b50a8.PNG">

**Comment by jccastillo0007** [comment]
chiaaaa, 

ya lo subi.

**Comment by RigoFlores** [comment]
Sigue mal la addenda, tanto al momento de facturar como en el addendador:
lo que está en negritas lo repite 3 veces; solo la segunda repetición es correcta, la primera y tercera no deben ir, amén que no contienen la 's'.
Además le falta esta parte:

xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"


mabe:Factura **xmlns:mabe="http://recepcionfe.mabempresa.com/cfd/addenda/v1" xmlns:mabe="https://recepcionfe.mabempresa.com/cfd/addenda/v1" xmlns:mabe="http://recepcionfe.mabempresa.com/cfd/addenda/v1"** fecha="2019-08-30" folio="336" ordenCompra="9500604350" referencia1="336" tipoDocumento="FACTURA" version="1.0" xsi:schemaLocation="https://recepcionfe.mabempresa.com/cfd/addenda/v1 https://recepcionfe.mabempresa.com/cfd/addenda/v1/mabev1.xsd">


La addenda debería verse así:

mabe:Factura xmlns:mabe="https://recepcionfe.mabempresa.com/cfd/addenda/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" fecha="2019-08-30" folio="336" ordenCompra="9500604350" referencia1="336" tipoDocumento="FACTURA" version="1.0" xsi:schemaLocation="https://recepcionfe.mabempresa.com/cfd/addenda/v1 https://recepcionfe.mabempresa.com/cfd/addenda/v1/mabev1.xsd">

**Comment by jccastillo0007** [comment]
como puedo reproducir esto en web en la pantalla de facturaci´øn, no con el addendador

**Comment by jccastillo0007** [comment]
o si tienes el escenario de pruebas en el addendador, también puedo checarlo ahi

pero necesito saber como reproducirlo

**Comment by jccastillo0007** [comment]
solo falta el xsi, pero ese no debe se necesario, que no ma....

**Comment by jccastillo0007** [comment]
listo... aunque queda todo en una sola linea.... tendrán que formatearlo con algún editor web o algo asi...

**Comment by RigoFlores** [comment]
no jaló para el addendador, faltaría ahí.
Para escritorio, se me hace que lo dejamos pendiente.

**Comment by jccastillo0007** [comment]
ya lo puse en el addendador, ya esta en pru
