### ISSUE TITLE
No coinciden los importes del XML con los del PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1628]
Fue un buen avance lo que hiciste. Al menos los totales ya coinciden.
Pero deben coincidir todos los importes.

A nivel producto:

Precio Unitario
Importe
Base IVA
IVA

A nivel general:
Subtotal
Descuento
IVA
total

parecería que solo tomaste los totales y eso lo igualaste en el PDF, pero se requiere que todo coincida.
En pruebas con el usuario TCM, y la factura 38 la suma de subtotal mas iva, no es igual al total

<img width="476" alt="redondo" src="https://user-images.githubusercontent.com/2912775/63908621-79394180-c9e5-11e9-812e-9a13a18ab3d4.PNG">

**Comment by jccastillo0007** [comment]
checale en pru .. a nivel producto no debe haber diferencia, o ya detectaste alguna ?

**Comment by jccastillo0007** [comment]
ya quedo?

**Comment by RigoFlores** [comment]
no he tenido tiempo de revisar. Hoy habló el cliente, le dije que me diera chance de revisar
Es delicado el asunto, así que hay que revisarlo con lupa. Amén que es tardado, estar comparando pdfs vs xmls

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
al parecer ya quedó, vamos a producción
