### ISSUE TITLE
Agregar tipo de relación y cfdis relacionados en nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1629]
en la pantalla de recibo de nómina.
lo ideal, es que los cfdis relacionados que busque, sean solo de tipo nómina. 
si se complica, pues que quede como está y que le pongan el filtro tipo nomina

**Comment by jccastillo0007** [comment]
done...

Como reutilicé el código que esta en la pantalla de facturación, que los usuarios eligan el tipo de comprobante nómina.

**Comment by RigoFlores** [comment]
cuando quieres elegir el cfdi relacionado, no aparecen los recibos de nómina.
En esta pantalla, de hecho, deberías ser los únicos a elegir, o en su defecto, que si se pueda filtrar por recibos de nómina.
Incluso filtré por número de folio, y ni así mostró la nómina, seguro tiene un candado

**Comment by jccastillo0007** [comment]
se me paso decirte que esto ya funciona, ups
