### ISSUE TITLE
generar el shell para mac, de versión 8.0.1

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#163]
ahora mismo, no jala con el Shell anterior.

**Comment by jccastillo0007** [comment]
fix it

**Comment by RigoFlores** [comment]
EL ÚLTIMO SHELL QUE ENVIASTE, NO JALA.
INCLUSO TENGO LA IMPRESIÓN QUE EL EXE DE WINDOWS, NO JALA DEL TODO. POR AHÍ SI TIENE ALGUNAS VARIABLES DE AMBIENTE, O SI TIENE INSTALADO EL JAVA 7 O ALGO AÚN NO TOTALMENTE IDENTIFICADO, NO JALA.

**Comment by RigoFlores** [comment]
?

**Comment by jccastillo0007** [comment]
Te mando correo.

**Comment by RigoFlores** [comment]
el Shell en mac, no jala para el JDK interno del facturat
