### ISSUE TITLE
Condominios - No aplica correctamente los filtos de ID casa

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1630]
Si consultas las solicitudes de pago, existe4 4. Puedes consultar el PDF y ahí aparece a que casa se asignaron.
La casa vhc24 y c20VS, solo tienen calle como estructura.

folio - casa
1 - vhc24
2 - vhc24
3 - C20VS
4 - casa 40

Si te vas a ingresos consultas, la 1, 2 y 3 las asigna a la misma casa, es decir no distingue la 1 y 2, de la 3.
<img width="600" alt="vntasconsultas" src="https://user-images.githubusercontent.com/2912775/64464078-14a87180-d0cc-11e9-9467-a7b9b9864c9a.PNG">

**Comment by RigoFlores** [comment]
Si te vas a CxC - ingresar cobro, y le aplicas el filtro de la c20vs, te muestra todas las SP que están asociadas a la vhc24. 
Creo que cuando la estructura solo es la calle, se está haciendo camotes.

<img width="534" alt="carteraCasa" src="https://user-images.githubusercontent.com/2912775/64464148-7bc62600-d0cc-11e9-8286-f86cd60bc7b6.PNG">

**Comment by RigoFlores** [comment]
Para reproducir el issue, tienes que generar una SP para la casa cuyo ID es C20VS.
Desde que nace la SP y la consultas, ya se la está asignando a la casa vhc24.

Según yo, esto se produce porque esas casas no tienen mayor estructura mas que el nombre de la calle.
Entonces, si quieres capturar un pago para la casa C20VS, pues no aparece nada.
Todos los pagos pendientes aparecen para la casa vhc24.

OJO, cabe mencionar que borré todo y solo estoy trabajando con esas 2 casas.

**Comment by jccastillo0007** [comment]
esto yo creo que ya se arregló con todos los fixes de filtros
