### ISSUE TITLE
Producción URGENTE - Afectaciones del cambio de cálculos en el XML y PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1631]
Pues hoy ha sido un día complicado por este tema, varias llamadas. El asunto es que los siguientes datos a nivel general, los está reportando a 6 decimales:

a) Subtotal, para facturas con moneda distinta a MXN
b) Descuento, en facturas con descuento o en nómina (las deducciones de nómina se reportan como descuentos), ahí también se reportan con 6 decimales.

Hasta el momento, esos son los escenarios detectados.

**Comment by jccastillo0007** [comment]
fixed
