### ISSUE TITLE
Implementar complemento de leyendas fiscales por conector, y enviarla al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1633]
Nos están pidiendo esta leyenda por conector:

    <leyendasFisc:LeyendasFiscales version="1.0" xmlns:leyendasFisc="http://www.sat.gob.mx/leyendasFiscales">
      <leyendasFisc:Leyenda disposicionFiscal="RGCE" norma="5.2.6" textoLeyenda="TEXTO LEYENDA:De conformidad con el Art. 29 Fracción I de LIVA, con la regla 4.3.21, 5.2.6 Fracción II y 5.2.7 de las RGCE, empresa que transfiere IMPRESOS RTM, S. A. DE C.V. a la empresa ENTAIL ENGINE LLC No. de programa IMMEX: 696-2012" />
    </leyendasFisc:LeyendasFiscales>

supongo que cada elemento de la leyenda, nos lo deberían enviar en un campo, por ejemplo:

CLF=disposicionFiscal|norma|textoLeyenda|

La otra opción es dejar fijo lo de disposición fiscal y norma, y que envíen los datos de empresa e IMMEX:

TEXTO LEYENDA":  De conformidad con el  Artículo 29  fracción  I de la Ley  del  IVA,  y  con las reglas  4.3.21, 5.2.6 fracción II  y 5.2.7 de las RGCE, empresa que transfiere  Transformaciones  Industriales  Especializadas  del  Valle  S.  de  RL  de  CV,. a la empresa  (nombre del cliente) con  No. de programa IMMEX: (número del IMMEX del cliente)

CLF=nombreCliente|IMMEX

**Comment by jccastillo0007** [comment]
cual es mi sorpresa, que esto ya esta implementado... con que se manden los 3 campos extras con la información adecuada, ya los procesa, ojo,,, deben ir los tres

CA=RGCE|5.2.6|TEXTO LEYENDA:De conformidad con el Art. 29 Fraccion I de LIVA, con la regla 4.3.21, 5.2.6 Fraccion II y 5.2.7 de las RGCE, empresa que transfiere IMPRESOS RTM, S. A. DE C.V. a la empresa ENTAIL ENGINE LLC No. de programa IMMEX: 696-2012


Usaremos el campo CA para campos adicionales... ya los procesa y crea el complemento de forma correcta.

**Comment by RigoFlores** [comment]
no puede quedar así... el cliente que lo pidió, maneja muuuchos datos extra por conector....
por ello la petición es que la etiqueta sea:

CLF=disposicionFiscal|norma|textoLeyenda|

Recuerda que la leyenda tiene que enviarse al PDF... y ahí como le haremos, si el cliente ya maneja pinche mil datos extra?

Además no puede estar condicionado a que existe IVA retenido. Son leyendas independientes. Si se incluye el IVA retenido y además esta leyenda, tendrían que ir dos leyendas......

**Comment by jccastillo0007** [comment]
done
