### ISSUE TITLE
Ajustar el Importe para el nodo de TotalImpuestosTrasladados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1634]
Como consecuencia de los cambios realizados la semana pasada, nos han estado llamando varios clientes, donde algunos portales de sus clientes son 'validadores', y les están regresando las facturas por este campo de Importe, ya que tiene que ir a 2 decimales y no a 6.

Ahora mismo, a nivel de TotalImpuestosTrasladados, ya lo estamos enviando a 2 decimales; entonces, solo es cuestión de que el Importe, dentro de ese nodo, sea igual a 2 decimales; esto es simplemente replicarlo.
Lo mismo aplicaría para el Importe del IEPS dentro de TotalImpuestosTrasladados.
Y para TotalImpuestosRetenidos, igual, ajustar el Importe a nivel del IVA e ISR.

**OJO, esto NO ES A NIVEL DE CONCEPTO, sino a nivel general: TotalImpuestosTrasladados y TotalImpuestosRetenidos.**

    <cfdi:Impuestos TotalImpuestosTrasladados="512.32">
        <cfdi:Traslados>
            <cfdi:Traslado Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" **Importe="512.324800"**/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
listo en pru

**Comment by RigoFlores** [comment]
al parecer ya quedó
hice varias pruebas con el iva y con impuestos retenidos y si quedó bien...

Esto es un parchesote para no perder clientes, pero nosotros estábamos bien.
En algún momento, estoy seguro que se regresará ese código..

**Comment by RigoFlores** [comment]
Oye, hay forma de mantener los 6 decimales dentro únicamente del nodo de retenciones, cuando exista MAS DE UNA RETENCIÓN.
Esto es, en los recibos de honorarios y arrendamiento, se retiene el IVA y el ISR.
Pero es muy común que pase que con el redondeo, lo reportado dentro del nodo, sea distinto a lo reportado en los totales.
Sólo sería para el caso de mas de una retención.

**Comment by jccastillo0007** [comment]
me parece que si se puede... pero se va ver medio chueco

**Comment by RigoFlores** [comment]
Si estará chueco, pero está ocurriendo muy frecuentemente, como son 2 impuestos retenidos los que suman al nodo... ejemplo:

las cifras para cálculo interno son:

IVA retendido: 10.324
ISR retenido: 9.312
Total retenidos: 19.636

A como se reporta ahora en el XML, lo anterior sería:
IVA retendido: 10.32
ISR retenido: 9.31
**Total retenidos: 19.64**  

Esto genera el error que el total, no es igual a la suma de los impuestos individuales
Peeeero, si en los retenidos, cuando se trate de mas de un impuesto, se reportan todos los decimales, este error nunca existiría.

En general, es muy probable que se presente cuando los trasladados o retenidos, manejen mas de un tipo de impuesto o mas de una tasa.
Lo que se ha reportado al momento, solamente tiene que ver con retenciones de ISR e IVA, esto es recibos de honorarios y arrendamiento.

**Comment by jccastillo0007** [comment]
y como deberia reportarse tu ejemplo de arriba?

**Comment by RigoFlores** [comment]
La corrección que hicimos estuvo bien (lo de dos decimales), solo que cuando se trata de mas de un impuesto, ahí puede suceder (50% de posibilidades), que marque error.
Este caso, marca error, y mas abajo como debería ser para que no lo marque:

<img width="948" alt="rentencionesBad" src="https://user-images.githubusercontent.com/2912775/67094923-5f60e300-f17a-11e9-9ada-017377de7021.PNG">


<img width="899" alt="retencionesOK" src="https://user-images.githubusercontent.com/2912775/67095013-91724500-f17a-11e9-8111-884157fec1b9.PNG">



Si en el nodo de retenciones a nivel global, lo reportamos con 6 decimales, ya no marcaría el error.
Solo es cuando hay mas de 1 impuesto, y lo mas común es que sea en las retenciones para recibo de honorarios o de arrendamiento.
Para el caso de una sola retención, se puede dejar como está ahora mismo.

**Comment by jccastillo0007** [comment]
pero para el caso de una sola retención, supongo que no pasa nada si también se deja a 6 decimales, cierto ?

**Comment by RigoFlores** [comment]
No estoy seguro para el caso de 1 sola retención.
Hicimos lo de 6 decimales, para poder ajustar cualquier combinación de cantidad, precio unitario, impuestos.
Peeeeeero, muchos portales pendejos, empezaron a rechazar nuestras facturas porque en los nodos de traslados y retenciones (a nivel general), se reportaban con 6 decimales. Y aunque no deberían rechazarlo, podríamos perder varios clientes. Con ello, se definió reportar a 2 decimales esos nodos.

Peeero ahora, cuando se reporten mas de 2 tasas o tipos de retenciones (seguro si son mas de 2 traslados, pasaría lo mismo), tenemos el 50% de posibilidades que se de el error.

En resumen, sería bueno dejar 2 decimales dentro del nodo traslados o retenciones, cuando se trate de un solo impuesto. Y reportar con 6 decimales, cuando se trate de mas de 2 retenciones o traslados.

**Comment by jccastillo0007** [comment]
puedes checar en PRU

**Comment by RigoFlores** [comment]
Pues lo hizo igualito, cuando se trata de 2 retenciones, no hay diferencia... chéca esta salida del catalina... con ese precio unitario, tasa de retención del iva del 10.667 se puede reproducir el problema.

<img width="960" alt="retenciones" src="https://user-images.githubusercontent.com/2912775/67412913-cec54100-f585-11e9-9266-33d35ef07dbd.PNG">

**Comment by jccastillo0007** [comment]
listo... chiaaa que wey... ayer se me olvidó subir el jar del cambio..
