### ISSUE TITLE
Implementar repositorio por cada para casa del condominio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1635]
Lo están esperando urgente...!!! Es nuestra oportunidad para entrar en uno los 5 mejores fraccionamiento de qro.
Cuando una casa acceda a esta opción, tendrá acceso a:

INGRESOS - CONSULTAS 
CXC - CARTERA POR CASA
CXC - REPORTE DE PAGOS

pero con el filtro de la casa que corresponda.

OJO, no todas las casas tendrán RFC, de hecho muy pocas. 
Se podría hacer que el usuario fuera el correo electrónico del propietario de la casa????

**Comment by RigoFlores** [comment]
En los otros sistemas que he checado, el acceso es por email.
No sé en tu caso de viveok, supongo que igual..

**Comment by jccastillo0007** [comment]
ya se tienen los filtros en la página de login, funciona con el user TCM y entra todo normal

Si usas el user FOPR ...  con el password test, solo verás los menús que indicaste, aún me falta restringir las consultas y funcionalidad en las pantallas que se muestran

Por otro lado, la pantalla de login, tiene algunos problemas cuando te equivocas de user/pwd o condominio, como que no refresca bien... 

Velo checando, haber si vamos bien

**Comment by RigoFlores** [comment]
Aparece la estructura del condominio, no tendría que aparecer. Al usuario solo le interesa ingresar su usuario y contraseña.
Cómo le haremos para que el mismo usuario, por ejemplo 'casa20' del condominio 1 y del condominio2  no se confundan al momento de ingresar?
Por ello creo que el email, podría ser el usuario ideal, ya que cada persona tiene un único correo (bueno, puede tener varios, pero solo con uno de ellos entra).
Y si el mismo correo lo ocupa un usuario final, y tiene varias casas en varios condominios, entonces podría elegir a cuál condominio quiere acceder.

**Comment by jccastillo0007** [comment]
mientras no revisemos la opción de email, habrá que seleccionar la estructura de la casa, no sé que tanto se vaya a romper si usamos el email como id de usuario en lugar de rfc.

Recuerda que los emails ni siquiera son obligatorios, y tenemos email para owner, rfc fiscal e inquilino

**Comment by RigoFlores** [comment]
si, aquí lo comentado es que se podría poner como obligado el correo del propietario, y ese sería el usuario para acceder a la plataforma.
Una casa o departamento, podrá no tener inquilino, podrá no requerir factura, pero un propietario siempre existirá. Entonces el dato obligado es nombre y correo del propietario.
