### ISSUE TITLE
condominios - varios detalles

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1636]
1) si la casa no tiene usuario para acceder al repositorio por casa, no permite capturarlo, marca internal error al intentar editar y guardar.

2) si como administrador , me voy a ingresos - consultas o CxC-cartera por casa, no me permite definir los filtros para la casa a consultar. Tengo que hacer consultas generales.

3) si entro como casa 40 por ejemplo, y le doy consultar no me aparecen las solicitudes de pago que si muestra cuando entro como administrador. 

4) si la casa no tiene RFC definido para facturar, entonces en ventas consultas no asocia la SP a la casa, y en general, creo que esa solicitud de pago queda algo así como huérfana

**Comment by RigoFlores** [comment]
5. si entro como casa 40, y reviso la cartera por casa o reporte de pagos, no me arroja nada, pero si tendría que arrojar resultados. Si estamos alambrando desde la bd, eso no funciona

6.- entrando como administrador en cxc - cartera por casa, o cxc - cartera general, marca internal error al solicitar el reporte

**Comment by RigoFlores** [comment]
El (1) y (3) ya fueron corregidos.
Pendientes 2, 4, 5 y 6.

**Comment by jccastillo0007** [comment]
esto pasa por mezclar fallas en un solo ticket, chiaaa
 Ya esta listo el punto 2.

**Comment by jccastillo0007** [comment]
los puntos 5 y 6, se deben a los zombies que generamos por lo que se reporta en el punto 4.
Tons, voy a arreglar el 4, pero creo que lo mas sano va ser borrar todo de CFD... excepto la estructura del condominio

cómo ves?

**Comment by jccastillo0007** [comment]
listo, limpie todo, y genere 2 SP para la casa 40, y para la casa 100 y al parecer, los puntos 4, 5 y 6 ya quedaron.. checale... si quieres borra todas las SP

**Comment by jccastillo0007** [comment]
ya están los puntos 4, 5 y 6
