### ISSUE TITLE
Dar de alta RFC MOVA710515223 para complemento educativo en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1637]
Se hace en jarcoud... chiaaaaa

**Comment by jccastillo0007** [comment]
oye, al RFC AVA621016TH4 se le hacen varias cosas al momento de facturar, para generar el complemento educativo, pero eso esta solo en standalone, en web no... tons, en web solo voy agregar el rfc MOVA710515223 como emisor del complemento educativo, esta bien?

**Comment by jccastillo0007** [comment]
done
