### ISSUE TITLE
Condominios - Solicitudes de pago quedan huérfanas, cuando la casa no tiene rfc

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1639]
Se hace un desmadre, porque la sp no queda asociada a la casa donde la capturaste.
Si quieres capturar un pago para esa casa, pues arroja toooodas las sp que no han sido pagadas, independientemente de la casa a la que corresponden.

**Comment by jccastillo0007** [comment]
mas bien el filtro no esta funcionando, al rato veo

**Comment by jccastillo0007** [comment]
Fixed

Eran los filtros

**Comment by RigoFlores** [comment]
Pues lo sigo viendo igual:

Ingresos - Consultas no relaciona la SP a la casa

<img width="636" alt="huerfanas1" src="https://user-images.githubusercontent.com/2912775/65977412-7d6adb80-e437-11e9-98be-22882a20c249.PNG">


CxC - Ingresar cobro, si elijo la casa 100 que no tiene rfc capturado, me muestra toooodas las SP que no han sido pagadas, independientemente de la casa.

<img width="465" alt="huerfanas" src="https://user-images.githubusercontent.com/2912775/65977290-4dbbd380-e437-11e9-82ce-d22d2b234bbe.PNG">


En cartera por casa, ahí SI MUESTRA LO CORRESPONDIENTE A LA CASA 100:

<img width="413" alt="huerfanas3" src="https://user-images.githubusercontent.com/2912775/65977541-bb67ff80-e437-11e9-9e0c-a173534332b1.PNG">

**Comment by jccastillo0007** [comment]
es que solo lo arreglé para cartera por casa... ahorita lo hago en las otras dos opciones

**Comment by jccastillo0007** [comment]
listo
