### ISSUE TITLE
Condominios - CxC - Consulta de Cobro, si se borra un cobro, el documento de pago queda 'vivo'

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1641]
Ya pasó que borré un cobro, pero el documento de pago asociado se mantuvo 'vivo', esto representa un pago inexistente a favor de la casa.

Creo que cuando borren un cobro, se debe:
a) cancelar el documento de pago asociado, y esto implica que no se considerará dentro de ningún reporte, excepto Ingresos - Consultas, donde aparecerá como cancelado.
b) Enviar correo a la casa, notificando que ese documento de pago, ha sido cancelado y por lo tanto no se registra dicho pago a su favor.

como la besibol?

**Comment by jccastillo0007** [comment]
trabaje en este ticket... ya tengo la lógica... pero no esta cancelando el documento de pago... tengo que ver porque..

En ingresos consultas, agregué la columna estatus para que se pueda ver cuando el docto de pago esta cancelado

**Comment by RigoFlores** [comment]
Si consulto (Ingresos - consultas) los documentos de pago de la casa 100 aparece esto (3 vigentes, 2 cancelados):

<img width="621" alt="casa100 1" src="https://user-images.githubusercontent.com/2912775/66354281-ef588e80-e929-11e9-814b-14e715941592.PNG">

Si me voy a la cartera de esa casa, solo aparece un pago de los supuestos 3 vigentes:

<img width="427" alt="casa100 2" src="https://user-images.githubusercontent.com/2912775/66354366-3181d000-e92a-11e9-96d0-19fd89cbf73a.PNG">

Finalmente en el reporte de pagos, pues aparece solo un pago...

<img width="419" alt="casa100 3" src="https://user-images.githubusercontent.com/2912775/66354419-60984180-e92a-11e9-95fc-083632b5521d.PNG">


Será porque se quedaron 'huérfanas' o existe una inconsistencia adicional?

**Comment by jccastillo0007** [comment]
listo, ya esta

**Comment by RigoFlores** [comment]
explícame como lo validaste, ya estoy un poco perdido con este issue.
Según yo, cuando borras un cobro, se debe cancelar en automático el documento de pago asociado a dicho cobro, así quedó?

**Comment by jccastillo0007** [comment]
si, asi  esta implementado.
1. se borra el cobro en la tabla de pagos "payment"
2. se marca el documento de pago en la tabla cfd, como cancelado
3. en las consultas por casa, ya no aparece el pago y el saldo deudor continua siendo como antes del cobro

**Comment by RigoFlores** [comment]
Acabo de borrar un cobro en pru, cuya referencia era 'pago casa 3', y el documento de pago asociado, lo indica como vigente.
Si bien, en la casa ya eliminó ese pago, el documento se mantuvo 'vivo', lo cual para la casa representa un pago que no ha realizado.
Estamos dando vueltas y vueltas, a fichas que anteriormente ya estaban resueltas y se vuelven a abrir.

**Comment by jccastillo0007** [comment]
ya hice varias pruebas, parece que ya esta

**Comment by RigoFlores** [comment]
con la cuenta de CSR de pru, borré dos pagos y los documentos de pago correspondientes siguen apareciendo como vigentes.
En particular puedes checar con la referencia 'pago casa 5', que ya la borré, pero su documento de pago sigue vigente. Al menos así aparece en Ingresos- Consultas.

<img width="682" alt="pago vigente" src="https://user-images.githubusercontent.com/2912775/68631430-7dd3a900-04b0-11ea-8208-3d844dc2167f.PNG">

**Comment by jccastillo0007** [comment]
ya descubrí otro problema grave... 
dado que hay facturas que se generan de forma automática, y dicho proceso corre en chinga loca... resulta que el tracking Id es igual para varias SP, y ya no es único chiaaaa

**Comment by jccastillo0007** [comment]
ups... necesitamos limpiar la base de datos... 
y empezar de nuevo con la generación de SP automáticas

**Comment by RigoFlores** [comment]
siempre he comentado del ID, eso que le pones el timestamp, no lo hace único ni lo garantiza
quizás si fuera el segundo del time stamp transcurrido desde no se que año, podría ser... pero ni así.

Ya limpié la BD, nuevamente.

**Comment by RigoFlores** [comment]
ok, ya lo esta poniendo a cancelado

**Comment by jccastillo0007** [comment]
chiaaaa, sabia que ibas a decir, te lo dije....

Lo que hice fue agregar el tracking Id a milisegundos... ahi si ya no va ser duplicado

**Comment by jccastillo0007** [comment]
habrá que limpiar también producción y debo subir la versión de ayer a pro

**Comment by RigoFlores** [comment]
no, producción no puedes borrar, eso ya lo tengo capturado.

Creo que no ha quedado claro que eso es un piloto que estaré mostrando a los posibles clientes, y es un piloto con datos reales

**Comment by jccastillo0007** [comment]
si quedo claro, pero si usas SP generadas automáticamente, no te va a funcionar la cancelación... haz tus pruebas para ver que todo este consistente, de lo contrario, habrá que borrar lo que ya se genero.

**Comment by RigoFlores** [comment]
En producción, no hay aún SP generadas automáticamente.
Estoy solo confirmando que ya quedó bien, para que se generen en automático.

Si entiendo bien, a partir de cierta fecha, las que se generen en automático en producción, y se les registre un cobro, si dicho cobro se borra, entonces el Documento de pago si se podrá cancelar, es correcto?

O es que ningún cobro cargado a una SP que se generó automáticamente, se podrá cancelar?

**Comment by jccastillo0007** [comment]
asi es, debido al defecto que encontré con el tracking number, que se repite para todas las SP generadas en el mismo segundo... no se podrán cancelar, pues marcará un error en la base de datos

**Comment by RigoFlores** [comment]
por eso, pero ahora mismo en producción, NO EXISTEN SP generadas automáticamente
Aún mas, las SP que existen, ya fueron pagadas y todo eso. No habrá necesidad de cancelarlas.
Voy a generar manualmente las de noviembre, porque según yo existe un pedo con las SP automáticas, pero hoy lo voy a confirmar
