### ISSUE TITLE
Implementar leyendas fiscales para web, IMEX.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1642]
Es un requisito medio complicado. 
A ver si me explico:

La leyenda es esta:

leyendasFisc:LeyendasFiscales version="1.0" xmlns:leyendasFisc="http://www.sat.gob.mx/leyendasFiscales">
<leyendasFisc:Leyenda 
disposicionFiscal="RGCE" 
norma="5.2.6" 
textoLeyenda="TEXTO LEYENDA:Operación de conformidad con  las reglas 5.2.6 Fracción II y 4.3.21 Fracción I y 5.2.7 de las RGCE vendido a  POWELL ELECTRICAL SYSTEMS, INC. entregado en PROCESOS LOGISTICOS Y ELECTRONICOS, SA DE CV.  RFC.  PLE080530H31  con PROGRAMA IMMEX que adquiere No. 445-2008 />

Ahora la leyenda tenemos que integrarla nosotros. Varía de factura a factura.

1. La empresa que dice "vendido a"  es el nombre del receptor del CFDI
2. La empresa que dice "entregado en", es el nombre de la que se elija del dato extra 1, que será del tipo CLIENT, como si fuera carta porte.
3. El número IMMEX de esa empresa, será lo que se capture en el campo referencia del punto anterior (dato extra 1, tipo CLIENT).

Solo se incluirá el complemento, cuando tenga configurado un XML que tu me digas, y además que tenga capturado algo en el campo referencia.

También se ocupa que el dato extra 1, tomado de un tipo CLIENT, si incluya el RFC del registro elegido. Hoy en día, ese tipo de dato extra, solo se ocupa en carta de porte, y ahí no se requiere el rfc. Para este caso si se ocupa.

**Comment by jccastillo0007** [comment]
este no es el que esta ligado a iva retenido? 

el que acabamos de hacer en standalone?

**Comment by jccastillo0007** [comment]
no esta tan tan tan complejo

**Comment by RigoFlores** [comment]
si, es el que acabamos de hacer para conector, si.
NO está ligado al IVA retenido; es el mismo complemento, pero mientras para el iva retenido siempre aplica, en este caso aplicará cuando se capturen los datos de la addenda o datos extra, según sea la solución.

No es complejo, lo complicado es realmente reflejar varios datos en el PDF de manera automática, y por ello se detallaron los requerimientos.

**Comment by RigoFlores** [comment]
la leyenda que incluyó en la primera prueba es:

"TEXTO LEYENDA:Operación de conformidad con las reglas 5.2.6 Fracción II y 4.3.21 Fracción I y 5.2.7 de las RGCE vendido a RIGOBERTO FLORES entregado en rfc de pruebas para addenda tsys**&#xA;, Real del Monte&#xA;Aquixtla, PUEBLA, MEXICO, 72060** con PROGRAMA IMMEX que adquiere No. 123456789"

Al parecer le está incluyendo un domicilio que no va.
Señalado en negritas.

**Comment by RigoFlores** [comment]
la primera parte "TEXTO LEYENDA:", hay que eliminarla.

Y también falta enviar al pdf los datos del dato extra1 (tipo CLIENT), pero a diferencia del carta porte, aquí si se debe incluir el RFC.

**Comment by RigoFlores** [comment]
Oye, y otra cosa... el número IMMEX, cambiará cliente a cliente, por ello se pidió que fuera parte del catálogo de clientes. Ya ví que no existe el campo referencia, entonces ocupemos algún otro campo, por ejemplo contacto o algún otro libre (que casi no se ocupe), ya que de lo contrario, en cada factura tendrían que capturar ese dato, y seguro que se les pasará en algún caso.

Para una primera versión podría salir así, pero si se ocupa que el IMMEX, se capture para cada cliente, que será elegido como dato extra 1, tipo CLIENT.

**Comment by RigoFlores** [comment]
OK, de los pendientes que quedan:

a) Enviar en el dato extra1, los datos tal cual salen en el carta porte, agregando el RFC (en carta porte no aparece el RFC). Así aparece hoy en día. El RFC estaría bien que apareciera DEBAJO DEL NOMBRE.

<img width="281" alt="cartaPorte" src="https://user-images.githubusercontent.com/2912775/66766585-06d8cf80-ee74-11e9-9754-14a3a151a208.PNG">

Te había comentado que el RFC no va en la leyenda, pero dicen que lo mantenga ahi. Entonces el único defecto es este que aquí comento.

**Comment by RigoFlores** [comment]
Oye, se me pasó que también al PDF hay que enviar la leyenda del complemento.
Solo la leyenda.... tu me dices en que dato extra la enviarás... sería bueno en el datoextra7

**Comment by jccastillo0007** [comment]
listo, parece que ya quedo

EL Dato extra 8, tiene la leyenda tipo carta porte, agregando el rfc
El dato extra 9, tiene la leyenda
Pero el dato extra 1, lleva el dato del cliente seleccionado en datos extras y también el número immex...

**Comment by RigoFlores** [comment]
solo que los datos extra que mencionas en el comentario anterior, son el 7 y 8 para la leyenda tipo carta porte mas rfc, y para la leyenda del complemento, respectivamente.

**Comment by RigoFlores** [comment]
pues ahora el dato 8, lo está enviando incompleto. Debe ser asi:

La empresa que dice "vendido a" es el nombre del receptor del CFDI
La empresa que dice "entregado en", es el nombre de la que se elija del dato extra 1, que será del tipo CLIENT, como si fuera carta porte.
El número IMMEX de esa empresa, será lo que se capture en el campo referencia del punto anterior (dato extra 1, tipo CLIENT).

Ejemplo:

"TEXTO LEYENDA:Operación de conformidad con las reglas 5.2.6 Fracción II y 4.3.21 Fracción I y 5.2.7 de las RGCE vendido a RIGOBERTO FLORES entregado en rfc de pruebas para addenda tsys** , Real del Monte Aquixtla, PUEBLA, MEXICO, 72060** con PROGRAMA IMMEX que adquiere No. 123456789"

pero lo está entregando incompleto...

2019-12-04 17:21:17,623 DEBUG [https-jsse-nio-8443-exec-52] (InvoicePanel.java:1112) - extra data : SERGIO JAVIER GARCIA GARZA                                               GAGS751015F56                                                                                                                                                                ESCORPION, 74, SATELITE                                                                                                                                                      , TAMAULIPAS, MEXICO, 87458                                                                                                                                                  2019-12-04 17:21:17,623 DEBUG [https-jsse-nio-8443-exec-52] (InvoicePanel.java:1112) - extra data : Operación de conformidad con las reglas 5.2.6 Fracción II y 4.3.21 Fracc ión I y 5.2.7 de las RGCE vendido a POWELL ELECTRICAL SYSTEM, INC. entregado en
--
