### ISSUE TITLE
Condominios - Incluir en el nombre de la SP el id CASA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1644]
Hoy aparece null, supongo que porque no tienen RFC asociado.
Y por el simple nombre no se conoce de que casa es.

**Comment by RigoFlores** [comment]
En general en la SP, y en el documento de pago, incluir el id CASA

**Comment by jccastillo0007** [comment]
me no entender...

A que te refieres con el nombre de la SP ?

Al campo nombre que se muestra dentro de la SP ?

**Comment by RigoFlores** [comment]
EL NOMBRE DE LA SP ES "SP23_CSR080825SN8_null_28Oct2019_143935"

AHÍ NO APARECE EL ID CASA, EN SU LUGAR APARECE null.

ESTO ES PARA QUE AL VER EL PDF, YA SEPAMOS DE QUE CASA SE TRATA EL DOCUMENTO.
APLICA SP Y DP

**Comment by jccastillo0007** [comment]
estoy haciendo pruebas de este cambio... esta medio tricky porque el id casa puede traer espacios y eso genera un problema en el nombre del archivo

**Comment by jccastillo0007** [comment]
listo, pero solo probé con una solicitud de pago

**Comment by RigoFlores** [comment]
no quedó, la nombra así:

PAGO1_CSR080825SN8_CENTRO_SUR_RESIDENCIAL_CONDOMINIO_1_31Oct2019_120212.pdf

y debe ser así:

PAGO1_CSR080825SN8_CASA_2_31Oct2019_120212.pdf

**Comment by RigoFlores** [comment]
pues al parecer si le nombra correctamente, pero si lo quiero descargar en consultas, ya no aparece.
Supongo que el cambio de nomenclatura, impide que se puedan ver los PDF's desde

Ingresos-Consultas

**Comment by jccastillo0007** [comment]
listo, ya corregí la forma de buscar el pdf en consultas
