### ISSUE TITLE
Condominios - ajustes en el correo enviado de SP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1645]
En el asunto ahora dice:

Recepción de nuevo(a):SOLICITUD DE PAGO, Emisor: TCM970625MB1, Receptor: FOPR681125BQ0, Serie/Folio: SP50

Debe decir:
Recepción de nuevo(a):SOLICITUD DE PAGO, Emisor: NOMBRE DEL CONDOMINIO, Receptor: ID CASA, Serie/Folio: SP50

En el cuerpo del correo dice:

Usted ha recibido un nuevo CFDI(SOLICITUD DE PAGO)
Estimado   PROPIETARIO CASA 40

SAN   MATEO RESIDENCIAL generó el siguiente CFDI(SOLICITUD DE PAGO):

UUID: | null
Serie: | SP
Folio: | 50
RFC Emisor: | TCM970625MB1
Nombre Emisor: | SAN MATEO RESIDENCIAL
RFC Receptor: | FOPR681125BQ0
Nombre Receptor: | PROPIETARIO CASA 40
Total: | $ 1000.0
Fecha de Emisión: | 28/10/2019 15:11:03
Para     mayor información, contactar al emisor en el siguiente correo:
Correo Electronico: | []
  |  
*Anexo encontrará el     archivo PDF y XML correspondiente.

Debe decir:

Usted ha recibido una nueva SOLICITUD DE PAGO
Estimado   PROPIETARIO CASA 40

SAN   MATEO RESIDENCIAL generó la siguiente SOLICITUD DE PAGO:

Serie: | SP
Folio: | 50
Nombre Emisor: | SAN MATEO RESIDENCIAL
Nombre Receptor: PROPIETARIO CASA 40
Total: | $ 1000.0
Fecha de Emisión:  28/10/2019 15:11:03

Para     mayor información, contactar al emisor en el siguiente correo:
Correo Electronico:  desplegar el correo del condominio

*Anexo encontrará el     archivo PDF correspondiente.

**Comment by jccastillo0007** [comment]
no maaaa, el correo es un template genérico... chiaaa

**Comment by jccastillo0007** [comment]
ya hice los cambios del receptor y emisor... falta lo de cfdi (solicitud de pago) y quitar el uuid

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
la variable ID casa, está medio cuatreapeada, chueca...
Así llegó el asunto del correo... lo que está en negritas, solo debería ser el ID casa

Recepción de nuevo(a):SOLICITUD DE PAGO, Emisor: Residencial San Mateo, Receptor: **Residencial San Mateo-Coto 1-null-null-bosques-c2-1202-casa 2**, Serie/Folio: SP12

**Comment by jccastillo0007** [comment]
crap... deja hago mas pruebas, según yo ya estaba, voy a probar con la casa 2
