### ISSUE TITLE
Condominios - Implementar soporte a pagos por anticipado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1646]
Partiendo que un pago anticipado, es un saldo a favor de la casa, mismo que se va descontando a lo largo del año, creo que una forma de hacerlo es:

a) Emitir una nota de crédito, serie NC con el pago anticipado.
b) Se podrá o no, configurar la emisión de SP automáticas para este caso. Eso dependerá si el pago anticipado incluye un beneficio (descuento) o no. Si no incluye descuento, pues se pueden emitir las SP automáticas. En otro caso, pues se tendrán que emitir manualmente para cada casa que pague por anticipado. En este punto no hay nada que hacer.
c) Al registrar un cobro a esa casa, se tomará la NC emitida y de ella se descontará el monto de la SP que se esté pagando (la correspondiente a cada mes). La NC seguirá 'viva' o vigente, mientras no se agote el saldo de la misma.

Ejemplo:
En el condominio no hay descuento, entonces en la cuota adelantada la casa paga $12,000.00, ya que la cuota mensual es de $1,000.00
En enero se emite una SP, y se registra el cobro con la NC. El saldo restante es $11,000.00
En febrero se emite una SP, y se registra el cobro con la NC. El saldo restante es $10,000.00

y así hasta que en Diciembre se emite la SP última del año, y el saldo disponible de la NC es de $1,000.00 mismos que se ocupan para cubrir la SP de diciembre, y hasta ahí queda el asunto.

La NC vigente, deberá aparecer como saldo a favor de las casas, de tal manera que en los reportes de cartera por casa, se verá reflejado dicho saldo a favor.

Si tienes alguna otra propuesta, podríamos platicarla.

**Comment by jccastillo0007** [comment]
yo veria este caso solo de forma esporádica, por algún descuento o reembolso, que en lugar de darle el dinero a la persona de la casa, se le va a abonar a cuenta de mantenimiento... 

En el caso que describes arriba, mas bien se generaría un pago anualizado, y su próximo pago será hasta el siguiente a;o... para que hacerlo mensual , si ya se sabe que pago anual ?

**Comment by RigoFlores** [comment]
La casa paga anualmente.
En enero, esa casa tiene un saldo a favor de 11,000 pesos... Esos 11,000 pesos, no se pueden disponer por parte del condominio.
Para temas de pagos y adeudos, esa casa tiene 11,000 a favor.
Para febrero, se registra un pago con la NC, y ahora solo tendrá 10,000 a favor...

el objetivo, es ir presentando, como ese pago anticipado se va tomando en cuenta a lo largo del año.
No porque te pague en enero, dispondrás de él... de alguna manera se debe reflejar que se tiene un dinero que no es propio....

Imagina que todos pagaran anticipado... te lleva 500,000 de un madrazo, pero no por eso los gastará el condominio, sino tendrá que irlos administrando mes a mes... esa es la intención de este issue.

**Comment by jccastillo0007** [comment]
hmmm no estoy seguro... en el fraccionamiento donde vivo no lo manejan asi

Yo he pagado semestral, y me dan mi recibo semestral...  como use el fraccionamiento ese dinero, es otro tema, pues el dinero ya se pago y ya esta en la cuenta del fraccionamiento...

**Comment by RigoFlores** [comment]
para cuando no se maneja así, no hay nada que hacer. Así lo soportamos.

Para cuando se maneja distinto, es decir que si se tiene contablemente que reportar como un 'adeudo' por llamarle de una manera, que propiamente es una nota de crédito que se va descontando con el tiempo, eso no lo soportamos y es lo que queremos hacer, soportarlo.

**Comment by jccastillo0007** [comment]
oye, y esto no se soporta actualmente ?

Según yo para pagar facturas, se pueden usar NC, y se va descontando... puedo moverle en pru o ya tienes tus pruebas definidas... si es asi, puedo generar otro condominio para hacer mis pruebas

**Comment by RigoFlores** [comment]
preferiría que generaras otro condominio, con el TCM para poder facturar en pru...

no, eso no se soporta actualmente. Si se puede pagar con NC en las facturas, pero son completas. No queda 'viva' la NC, se debe utilizar completa.

**Comment by RigoFlores** [comment]
creo que tenemos que darle a este issue....
