### ISSUE TITLE
Condominios - CxC - Ingresar cobro, detalles varios:

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1647]
(A) 
Si estás capturando varios cobros, pierde la moneda una vez que capturaste el primer cobro. Para el segundo cobro, hay que volver a configurarla, esto es habilitar "incluir CFDI de pago", elegir la moneda, y luego quitar la casilla de "incluir CFDI de pago" (es decir un desmadre para reestablecer la moneda).

(B) 
Una vez que capturas un pago y lo guardas, mantener en pantalla para el siguiente pago:
(1) la misma fecha de pago
(2) la misma forma de pago. 
(3) el mismo importe pagado.
(4) cuando eliges la casa, que esa sea ya la búsqueda, y no que tengas que darle adicionalmente en la lupa el click.

**Comment by RigoFlores** [comment]
C)
Que cuando inicies la captura, el default de forma de pago, sea transferencia electrónica

**Comment by RigoFlores** [comment]
importante darle a este issue
de hecho la captura de un cobro se complica sin atender este issue.

Aún mas, necesitamos implementar la importación de un excel... que la misma aplicación genere (exporte) el layout del excel, para posteriormente se llene con los datos de cobros de las casas y importarlos... algo así, que sea mucho mas dinámico... eso no excluye la corrección motivo de este issue

**Comment by jccastillo0007** [comment]
no ma... estas solicitando funcionalidad nunca antes desarrollada.

Lo del excel, esta mucho mas complicado... para eso mejor levanta otros tickets para especificar lo que se requiere... eso del export e import esta medio loco

**Comment by jccastillo0007** [comment]
B y C no son defectos, es nueva funcionalidad... no todo lo que levantas es defecto

**Comment by jccastillo0007** [comment]
Del A, no entendí muy bien, y trate de reproducirlo, pero solo tenias una moneda dada de alta en PRU, no quise crear otra para entender cual es el problema que estas teniendo...

Del B: 1,2 y 4 ya están listos

Del C: ya esta listo

**Comment by RigoFlores** [comment]
lo de la moneda es castroso.
Has de cuenta que estás capturando varios cobros.
El primero lo hace sin pedos.
A partir del segundo, la moneda 'se pierde'. Es decir está vacío, aún con una sola moneda que es el caso. Y que tienes que hacer?..
Habilitar que se requiere el CFDI de pago (para acceder a elegir la moneda), luego elegir la moneda (la única que existe) y finalmente quitar el checkbox del CFDI de pago. 
Eso se tiene que hacer para cada cobro que captures (a partir del segundo en adelante), en la misma sesión, esto es sin cambiarte de pantalla. Estás capturando varios cobros y te mantienes en la misma pantalla. 

Lo del excel, solo fue un comentario, aquí no se está solicitando.
Recuerda que lo que buscamos es simplicidad y que sea usable. Ambos son importantes.

**Comment by RigoFlores** [comment]
Capturé un primer pago.... como lo indica esta pantalla...

<img width="354" alt="pago1" src="https://user-images.githubusercontent.com/2912775/69167487-ad8b3e00-0aba-11ea-8b04-ae5c4e722b70.PNG">


Después de guardarlo, lo que se presenta en pantalla es:

<img width="339" alt="pago2" src="https://user-images.githubusercontent.com/2912775/69167537-c1cf3b00-0aba-11ea-91f7-a0ec01ec72f1.PNG">

Esto es, no mantiene la fecha de pago, la forma de pago, el importe del pago. 
Ahí se ve también, como se pierde la moneda.
Lo que si quedó, es que al elegir la casa, se realiza la búsqueda y que la forma de pago inicial es transferencia.

**Comment by RigoFlores** [comment]
Esto es, sigue pendiente esto:
(A)
Si estás capturando varios cobros, pierde la moneda una vez que capturaste el primer cobro. Para el segundo cobro, hay que volver a configurarla, esto es habilitar "incluir CFDI de pago", elegir la moneda, y luego quitar la casilla de "incluir CFDI de pago" (es decir un desmadre para reestablecer la moneda).

(B)
Una vez que capturas un pago y lo guardas, mantener en pantalla para el siguiente pago:
(1) la misma fecha de pago
(2) la misma forma de pago.
(3) el mismo importe pagado.

**Comment by jccastillo0007** [comment]
fixed... todo lo pendiente
