### ISSUE TITLE
Condominios - CxP - Registro de pago, no pone pagada cuando el pago > importe de factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1648]
Si el pago realizado, rebasa el monto de la factura, no la pone a pagada.
Ejemplo concreto, Telmex emite su factura con centavos y a la hora del cobro 'redondea' (que poca madre, no?). Entonces por ejemplo:

La factura indica un importe de $566.93, pero el pago realizado fue de $567.00, porque así lo pide y hace Telmex.
Si registro ese pago de 567 a una factura de 566.93.... la factura NO LA PONE A PAGADA, sino considera un saldo insoluto de -0.07, lo cual es incorrecto.
Si el pago registrado es mayor o igual al monto de la factura, pues esa factura ya debe quedar PAGADA.
Ahora mismo queda como Vigente.

**Comment by jccastillo0007** [comment]
oye, esto es en CxP o CxC, solo para confirmar, porque hasta ahora no hemos hecho fixes de CxP

**Comment by RigoFlores** [comment]
CxP
