### ISSUE TITLE
Condominios - Enviar a la SP, la ID casa

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1649]
No recuerdo que variable se ocupa, pero no se está desplegando en el PDF de la SP dicha variable.
Hay que enviarla.

**Comment by jccastillo0007** [comment]
jajaja no recuerdas que variable es, pero si sabes que no se despliega jajaja ahora si te pasaste

**Comment by jccastillo0007** [comment]
,numeroCasa=casa 1

decidimos enviarlo en número casa, y si se esta enviando al jasper

**Comment by RigoFlores** [comment]
puedes revisar las SP anteriores y no las desplegaba.
Ahora ya las despliega, y también puedes revisar que la plantilla no ha cambiado desde hace muchas semanas.

**Comment by RigoFlores** [comment]
pues ahora nuevamente no está enviando la variable correcta... lo despliega así, donde debería ir el numero de casa, como una secuencia del domicilio, algo así está enviando.

**CENTRO SUR RESIDENCIAL CONDOMINIO 1-null-null-null-FRAY LUIS DE**

**Comment by jccastillo0007** [comment]
esto en el jasper verdad

**Comment by jccastillo0007** [comment]
ya vi que este ticket es para lo de jasper, ya lo arreglé también
