### ISSUE TITLE
NO SE PUEDE GENERAR PREVIEW EN RECIBO DE NÓMINA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#165]
EN EL AMBIENTE DE PRUEBAS Y PRODUCCIÓN, VALIDAR CON UN REGISTRO QUE DIMOS DE ALTA, Y QUE ENTIENDO NO DEBERÍA TENER PROBLEMA.
ES EL DE ARACELY SEGOVIA BLANCO.

**Comment by jccastillo0007** [comment]
Era por el tema de antiguedad... debe ser numérico, se implementó una validación para evitarlo
