### ISSUE TITLE
Condominios - poner nombre por omisión de un documento de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1650]
Cuando una SP se paga, el cfdi del documento de pago debe llamarse por omisión:
pago_SP.jrxml.

OJO, si se paga una factura sin solicitar CFDI de pago, es igual, se invoca a este jasper.

OJO, si se paga una factura y se requiere el complemento de pago, entonces se invoca al jasper que hoy mismo se llama para pagos en la facturación cfdi_pagos33.jrxml.

**Comment by jccastillo0007** [comment]
supongo que aqui : 

OJO, si se paga una factura

quisiste decir 

OJO, si se paga una SP

cierto?

**Comment by jccastillo0007** [comment]
cuando genero el jasper... sé que tipo de documento es, en los casos de este ticket estamos hablando de un documento de pago... pero en ese momento no sé si trae o no complemento... podemos hacerlo más fácil ? y dejar una sola plantilla , hoy en día es cfdi_pagos33.jrxml

**Comment by RigoFlores** [comment]
Lo que pasa es que esa plantilla (cfdi_pagos33.jrxml) contienen información que ni al caso, no aplica para un pago simple. No contiene información de la casa, etc... no es funcional.
Si revisar el recibo que te entregan cuando haces pago en tu condominio, no tiene nada que ver con un complemento de pago.


Lo que dice este issue, es que cuando se registra un pago, y no se requiere complemento de pago (ya sea SP o FA), se ocupe una plantilla (pago_SP.jrxml).
En el caso de ocupar el complemento de pago, entonces ahí se ocupa la plantilla estándar del CFDI (cfdi_pagos33.jrxml).

Voy a revisar si puedo hacer una plantilla que sea dinámica.

**Comment by jccastillo0007** [comment]
Esto es correcto :
Una SP o Documento de Pago, usaría la plantilla pago_SP.jrxml
Un CFDi con complemento de pago , usaría la plantilla cfdi_pagos33.jrxml

Entiendo que un documento de pago, no es un cfdi oficial, es como un recibo de pago...  cuando solicitan una factura oficial es la que trae el complemento de pago.

**Comment by RigoFlores** [comment]
no, una SP NO ocupa la plantilla pago_SP.jrxml

Esta plantilla la ocupará **un pago registrado a una SP o a una factura** que no ocupe complemento de pago.

**Comment by jccastillo0007** [comment]
ok, va de nuevo

Una SP, usaría la plantilla solicitudPago33.jrxml
Un Documento de Pago, hecho a una SP, usaría la plantilla pago_SP.jrxml
Un Documento de Pago, hecho a una factura, usaría la plantilla pago_SP.jrxml
Un CFDi con complemento de pago , usaría la plantilla cfdi_pagos33.jrxml

estamos ?

**Comment by RigoFlores** [comment]
Correcto, aunque la SP no tiene que ver con este issue, si ocupa esa plantilla (solicitudPago33.jrxml).

En este issue, estamos hablando de registro de pagos (CxC - Ingresar cobro) y las plantillas a ocupar.
Aclararía este comentario: 
"Un CFDi con complemento de pago , usaría la plantilla cfdi_pagos33.jrxml"

debe decir:

**Un cobro realizado a una FACTURA, y que ocupa complemento de pago, ocupa la plantilla cfdi_pagos33.jrxml y NO OCUPARÍA pago_SP.jrxml**

**Comment by jccastillo0007** [comment]
chiaaa na mas me confundes....

**Comment by jccastillo0007** [comment]
listo... 
pasame la plantilla pago_SP.jrxml.... por ahora para probar, solo renombre la plantilla de cfdi_pagos33.jrxml a pago_SP.jrxml... pero pasame la oficial y la subo a Pru

también puedes probar con la plantilla pago_SPrfc.jrxml , personalizada por usuario

como por ejemplo : pago_SPTIA101020BP4.jrxml

**Comment by RigoFlores** [comment]
si, esa plantilla está mas que probada, la he tenido que renombrar como lo mencionas.
Aquí la tienes... 

[pago_SP.zip](https://github.com/jccastillo0007/eFacturaT/files/3842602/pago_SP.zip)

**Comment by RigoFlores** [comment]
ya puse esa plantilla (pago_SP) donde debería estar y si la jaló bien.

**Comment by RigoFlores** [comment]
quedaría pendiente probar que cuando se trate de factura y emita un complemento, jale la plantilla correspondiente.
Pero no puedo generar una factura de condominios en ambiente de pruebas.
