### ISSUE TITLE
Condominios - está generando una SP ('factura') de manera automática, solo para la casa 2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1651]
tanto en pruebas como en producción, solo para la casa 2 se está generando una SP 'factura' de manera automatica.

Entonces está mal que se esté generando solo para la casa 2, y también está mal que en cartera de casa, la clave de la SP automática, sea FA (factura)

<img width="423" alt="facturaC2" src="https://user-images.githubusercontent.com/2912775/68254140-6f3c4c00-ffef-11e9-9338-3d1f599138dd.PNG">

**Comment by RigoFlores** [comment]
hay que eliminar esas 'FA', y generar automáticamente todas las que aplican... para el día 01...
ya se que ya pasó, pero debemos probar que las genere todas correctamente el día 06 por ejemplo o máximo 07

**Comment by jccastillo0007** [comment]
listo... si tenia un par de defectos, y el emisor CSR no tenia una frecuencia determinada en la pantalla de configuración... le puse diaria, pero se la puedes cambiar

**Comment by RigoFlores** [comment]
Necesito borrar las SP en producción que se generaron por error... cómo le hago?
Son las SP de la 42 en adelante...

**Comment by jccastillo0007** [comment]
esto ya debería estar resuelto, cierto?
