### ISSUE TITLE
Condominios - no muestra nada en cartera por casa, ni pagadas, ni NO pagadas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1652]
Ahora ya no muestra nada en cartera por casa... 

Si consulto en Ingresos-Consultas, aparecen 2 pagos.... que por cierto NO TIENEN CASA ASOCIADA... chiaaa, creo que esto ya se había corregido y ahora no muestra nuevamente....

<img width="622" alt="consultas ingresos" src="https://user-images.githubusercontent.com/2912775/68416001-391adb80-0159-11ea-8fe9-98a3f9ca6f68.PNG">

Si consulto en CxC - Cartera por casa, no despliega nada, con ningún filtro ni nada...
Si consulto en CxC - Reporte de pagos, si se reflejan esos pagos, pero igual sin PDF.

Total, que si quiero conocer quién ha pagado y quién debe, no se puede generar ese reporte

**Comment by jccastillo0007** [comment]
ya quedo...
