### ISSUE TITLE
Condominios - CxC-Cartera general, marca internal error al solicitar el reporte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1653]
Yo creo que esto ya jalaba también, pero ahora está marcando internal error cuando solicitas el reporte. Con alguno filtro o sin ningún filtro marca igual.
Este reporte debe mostrar por cada casa todos sus SP/FA vs Pagos realizados.

**Comment by jccastillo0007** [comment]
listo... aunque no estoy seguro si el resultado es correcto... ya no marca internal error
