### ISSUE TITLE
Condominios - al ingresar con el mismo usuario definido para distintas casas, marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1654]
Con la cuenta de la TIA en pruebas.
Solo existen 2 casas. Ambas su usuario de acceso es 'jccastillo'.
Si en la pantalla de acceso, primero elijo una casa y luego intento acceder, marca:

Usuario / Password / Condominio incorrecto

Todavía mas, en la pantalla de acceso, no tengo forma de elegir el condominio.
Cómo saber cuáles condominios debe presentar en caso que el usuario fuera el mismo para casas de distinto condominios. 
Según comentaste que eso ya lo tenía resuelto, pero al parecer no.
Y tampoco creo que sea tan fácil. Posiblemente ahora mismo, la opción sea no permitir que se repitan los usuarios en la tablas correspondientes.

**Comment by jccastillo0007** [comment]
Esto es lo que debo arreglar : 

en la pantalla de acceso, no tengo forma de elegir el condominio.

Si cargas la casa 1 o casa 2 con el usuario jccastillo si entra a su respectiva casa

**Comment by jccastillo0007** [comment]
listo... ya muestra la lista de los condominios disponibles...

sin embargo... los combos se comportan muy extra;o cuando hay errores, seguiré revisando y buscando opciones
