### ISSUE TITLE
Condominios - Egresos - Registrar CFDI, solo aceptar de tipo ingreso y egreso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1655]
Descargué del sat los CFDIs del condominio, y de ahí se bajaron algunos de tipo pago.
En la parte de CxP, solo se deben registrar CFDIs de tipo ingreso, y si acaso de tipo egreso.

Pero pago, traslado y nómina no.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
pues no, no quedó...
esto solo nos hace perder tiempo en probar y validar algo que no ha quedado.

Este es un CFDI de tipo pago y lo está aceptando...

<img width="639" alt="pago" src="https://user-images.githubusercontent.com/2912775/68707321-1f153a80-0557-11ea-906e-fdecdc2fbb00.PNG">

**Comment by RigoFlores** [comment]
aquí un cfdi tipo pago para rfc CSR en pru...

[complemento de pago telmex.zip](https://github.com/jccastillo0007/eFacturaT/files/3838048/complemento.de.pago.telmex.zip)

**Comment by jccastillo0007** [comment]
crap, agregué la validación en el lugar equivocado
