### ISSUE TITLE
Condominios - CxC Ingresar Cobro,  DP, leyenda incorrecta cuando se registra un pago a una SP automática

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1656]
CUANDO REGISTRAS UN PAGO A UNA SP QUE SE GENERÓ AUTOMÁTICAMENTE, NO ENVIA AL PDF DEL DOCUMENTO DE PAGO, LA LEYENDA CORRECTA 

EN PRU:

LA SP1 SE GENERÓ MANUALMENTE. 
EL DP1 SE GENERÓ CORRECTAMENTE EN LA LEYENDA DE “Concepto del Pago”:  CUOTA DE MANTENIMIENTO CORRESPONDIENTE AL MES DE NOVIEMBRE

CORRESPONDIENTE AL MES DE NOVIEMBRE, FUE LA INFORMACIÓN COMPLEMENTARIA DE LA SP CAPTURADA MANUALMENTE.

LA SP2 SE GENERÓ AUTOMÁTICAMENTE. 
EL DP2 SE GENERÓ INCORRECTAMENTE EN LA LEYENDA DE “Concepto del Pago”, ya que no incluye el mes: CUOTA DE MANTENIMIENTO

**Comment by jccastillo0007** [comment]
listo
