### ISSUE TITLE
Condominios CxC - Ingresar cobro, la primera vez no toma la referencia, aún cuando está capturada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1657]
te mandaré el video explicativo, ya que no es tan simple.
Bueno quizás, si, la primera vez que entras a la pantalla, aunque esté todo capturado correctamente, le das guardar y marca que no tiene la referencia capturada, aunque si la tiene.

**Comment by RigoFlores** [comment]
repitió el comportamiento con el segundo cobro, antes de salir de la pantalla.

**Comment by jccastillo0007** [comment]
fixed, otra yaga del framework que estamos usando...
