### ISSUE TITLE
Condominios CxC - Ingresar cobro, no mantiene la fecha de pago en el segundo cobro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1658]
Se trata de hacer esto muy dinámico. Por ello se pide mantener la fecha de pago.
No la está manteniendo, después que capturaste el primer cobro.

Otra cosa, hay que borrar tooooodos los cobros en producción. Ahorita aunque las solicitudes de pago aparecen vigentes, lo cual está bien, si consultas los documentos de pago, aparecen tooodos los que anteriormente se habían capturado.

Hay que borrar tooodos los cobros para empezar de nuevo. Urge.

**Comment by jccastillo0007** [comment]
ya hice pruebas en pru, y si mantiene la fecha, ahorita lo checo en PRO, y hago el clean up de la base de datos de los documentos de pago.

**Comment by jccastillo0007** [comment]
ya borre los documentos de pago, puedes checar otra vez lo de la fecha de pago en pro, debería funcionar
