### ISSUE TITLE
Web - Enviar una nueva variable al PDF, que es el total, antes de impuestos locales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1659]
Si tuviéramos esta factura:

subtotal:      1000.00
descuento:      200.00
nuevo subtotal: 800.00
IVA:            128.00
Total 1:        928.00
5 al millar:     50.00
Total:          878.00

hoy en día tenemos todos los datos, excepto el que se menciona en el total 1, esto es.... justo el total (subtotal - descuento + IVA), pero antes de restarle los impuestos locales. Los impuestos locales, no aplican en todos los casos, mas bien son excepcionales, pero pues en este caso son para un cliente que si los ocupa. Cuando no existen impuestos locales, el total 1 = Total, en el ejemplo de arriba.

Entonces se ocupa para un cliente, podríamos llamarle a esa variable: "preTotal"
lo podrias tener para mañana, y dejarlo listo para subirlo en el web???

**Comment by jccastillo0007** [comment]
negativo... no esta nada sencillo.
ya que se hacen los calculos al inicio, y no se guardan los valores para arrastrarlos al momento de hacer el jasper... necesito reproducirlo y ver donde sería el mejor lugar para ponerlo...

probablemente al momento de generar el jasper, trato de reconstruirlo para no pegarle a nada mas
