### ISSUE TITLE
ENVIAR A MAS DE UN CORREO DE EL CFDI DESDE EL CONECTOR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#166]
LO ESTÁN PIDIENDO LOS ALEMANES.
LO PODRÍAMOS COBRAR, NO MUCHO, PERO ALGODÓN.

**Comment by jccastillo0007** [comment]
done release 8.0.4

tambien aplica desde el standalone, los correos deben estar separados por ;
