### ISSUE TITLE
MatStore - generar una herramienta que desglose en archivo en modo 'legible'

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1663]
que el parseo lo ponga en modo legible, para temas de debugueo.
Habías comentado que en el log.
Podría ser un archivo aparte, que lo desmenuce y lo presente legible.

**Comment by jccastillo0007** [comment]
esto es en el cliente o en el server ?

**Comment by jccastillo0007** [comment]
Si es del lado del cliente, se despliega de esta manera 
[read file sample.txt](https://github.com/jccastillo0007/eFacturaT/files/4006737/read.file.sample.txt)

**Comment by RigoFlores** [comment]
en donde, que no lo veo?

**Comment by jccastillo0007** [comment]
en el log de la ejecución del cliente matstore
