### ISSUE TITLE
matStore - pantalla de factura al instante , detalles varios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1664]
Detalles:

1. Falta solicitar el uso del CFDI (no se debe esperar que se incluya en el archivo)
2. La fecha de compra se solicita o se elimina. Pero hoy dice "fecha de emisión" y no tiene sentido pedir esa fecha.
3. El folio y serie a ocupar, que sea FI  (factura al instante) para filtrar por serie las facturas que se emitieron desde esa pantalla. A nadie le interesará la serie, pero a nosotros nos puede servir de mucho.

**Comment by jccastillo0007** [comment]
Ok, ya están los 3 puntos arriba mencionados.
Ojo, la serie FI, debe ser creada manualmente para cada casa de materiales

**Comment by RigoFlores** [comment]
Pero la fecha de compra, o se utiliza o se elimina.
Solo cambiaste la etiqueta, pero no está requiriendo ese dato para generar la factura.

¿que hacemos, si la pedimos o solo la quitamos de pantalla?

**Comment by jccastillo0007** [comment]
si la vamos a usar... solo que aún no lo implemento, y como el volumen es bajo, ahorita no se ocupa... pero si la voy a validar.

**Comment by jccastillo0007** [comment]
listo, ya se esta validando la fecha
