### ISSUE TITLE
matStore - enviar pedido y fecha de compra al Jasper

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1665]
Puedes enviarlo como dato extra 1 (pedido) y datoextra2 (fecha de compra), para propósitos del jasper?

**Comment by jccastillo0007** [comment]
El pedido ya se manda en el campo trackingId, ya que de hecho ahi es donde se guarda desde el inicio.

Solo me faltaría agregar la fecha de compra en el dato extra 1

**Comment by jccastillo0007** [comment]
listo, ya esta implementado
