### ISSUE TITLE
matStore - no procesa los archivos de facturación normales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1666]
Ayer ya estaba generando facturas normalmente.
Ahora que se incluyó la serie FI para las facturas al instante o desde el descargaT, algo se movió y ya no  procesa los archivos que si incluyen toda la info de la factura.

Mandé un par de facturas con los archivos que ayer trabajé, les actualicé a cada uno de ellos su número de pedido para el RFC  MISC491214B86, y si le doy consultar, esos dos archivos aparecen ahí, sin timbrar y solo el PDF.

<img width="616" alt="matstore" src="https://user-images.githubusercontent.com/2912775/71547111-4d14d980-2961-11ea-84b6-2b1a29dbc9bf.PNG">

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
no del todo.
Para las facturas que llegan completas en el archivo, está tomando al serie FI, que esa está reservada para las facturas desde el descargaT (instantáneas o no).

Habías comentado que para facturas completas, ocuparía 'SIN SERIE', y para las otras se ocuparía la FI, precisamente para distinguir las facturas generadas en un lado y otro.

**Comment by jccastillo0007** [comment]
ok, entendí que todo lo de matstore usaría FI, lo cuál no tiene sentido porque FI es Factura al Instante... tons.. la cague... pero ya esta arreglado.

Por cierto, que serie ocuparán las facturas del corte por casa de materiales y las de matstore... por ahora tienen FI

**Comment by jccastillo0007** [comment]
listo, ya esta el descargat actualizado
