### ISSUE TITLE
Factura al instante - marca error cuando genera el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1667]
Pero si se emite la factura desde la plataforma estándar, no hay problema.

Error al generar CFD (115)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
negativo, marca lo mismo...

<img width="311" alt="matstore" src="https://user-images.githubusercontent.com/2912775/72002054-54af6a80-320c-11ea-8dc5-f0725deabe79.PNG">

**Comment by RigoFlores** [comment]
y si consulto desde la cuenta del receptor, pues no aparece el PDF.

<img width="575" alt="matstore" src="https://user-images.githubusercontent.com/2912775/72002272-b8399800-320c-11ea-8b24-9a492e4c9d2a.PNG">

**Comment by jccastillo0007** [comment]
fixed ahora si.
