### ISSUE TITLE
matStore - factura público en general de las casas de materiales, no se está generando

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1669]
Esta factura se debe generar el día 04 de cada mes, por aquellas ventas que no se facturaron.
Ahora lo estamos haciendo diariamente.
El día 04 de enero para el rfc de pruebas MISC491214B86, tenemos 2 registros sin facturar, y no se generó por ningún lado la factura con serie PG, que debería ser la de público en general por esas compras que no se facturaron.

<img width="620" alt="PG" src="https://user-images.githubusercontent.com/2912775/71836010-a58e5a00-3078-11ea-8008-db02683c0b2c.PNG">

**Comment by RigoFlores** [comment]
ya vi que se generó la factura PG.

Ahora lo que pasa es que no está 'eliminando' los tickets. Es decir, si me voy a un reporte de ventas-consultas, las ventas por ticket (que no se facturaron), aparecerían duplicadas ya que sería tickets y factura público en general.

Donde podemos enviar la información de los tickets considerados dentro de la factura Público en general?

**Comment by jccastillo0007** [comment]
solo me falta, limpiar el query en consultas, para no incluir los tickets facturados a PG

**Comment by RigoFlores** [comment]
oye y porqué no lo hacemos como DEBE SER...
esto es, los tickets que no son facturados, una vez que se facturan, que se conviertan en REMISIONES, y que si, de alguna manera podamos identificar en cuál factura PG están incluidos.

Cómo vex? 

Ahora mismo los sigue incluyendo en el monto de los ingresos:

<img width="555" alt="matstore" src="https://user-images.githubusercontent.com/2912775/72029121-8c3d0780-324a-11ea-82b4-c2e1052390df.PNG">

**Comment by jccastillo0007** [comment]
si, eso funcionaria, e incluso ayudaría a no considerar las remisiones para el calculo de comisiones de matstore... ya que no tomaría remisiones....
Ahora bien, porque no crear esos tickets no facturados como remisiones desde el mero principio... para que generarlas como facturas si no se facturan, como la beisbol?

**Comment by jccastillo0007** [comment]
el único problema aqui , es que el proceso de generar la factura a público en general, debe correr siempre antes del proceso de comisiones de matstore, de otra forma, podriamos dejar fuera todas las remisiones que no se facturaron al público en general

**Comment by RigoFlores** [comment]
Si este último punto, fue lo que me orilló a no solicitar crear la remisión desde el principio, pero si, así debería ser. No es tan simple. 
Si decidimos hacerlo tendríamos que considerar lo siguiente:

<img width="738" alt="matstore" src="https://user-images.githubusercontent.com/2912775/72091409-ba1b5e00-32d5-11ea-879d-9039e6a5b5a3.PNG">

**Comment by RigoFlores** [comment]
Además en el reporte de ventas (consultas-ventas), deberíamos agregar el filtro de Facuras + Remisiones,  donde las remisiones consideradas deberían tener status de creadas, esto es, que aún no se han facturado.

Así quedaría el DEBER SER...

**Comment by jccastillo0007** [comment]
En realidad solo es creada y facturada, porque cancelada y pagada no aplica para MatStore.

Ahora bien, el estatus facturada, se aplicará cuando dicha remisión se cubra por medio de una factura a PG.
Si la remisión se factura por medio del portal factura al instante, mas bien se actualizará  a  Factura, y dejará de ser Remisión.... estamos ?

**Comment by jccastillo0007** [comment]
done
