### ISSUE TITLE
calcular la suma de percepciones y de deducciones en el recibo de nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#167]
ya lo vi en vivo con cliente, y resultó absurdo que no lo hiciera a partir de la captura individual de cada percepción y deducción.

**Comment by RigoFlores** [comment]
se tiene que calcular los totales, con base a los datos exentos y gravados, percepciones y deducciones individuales. Hoy en día lo dejamos libre captura los totales y eso también genera inconsistencia. Por lo menos sumando, el usuario conocerá los totales desde antes del preview incluso.

**Comment by RigoFlores** [comment]
Ahora mismo, como comentaba, genera una inconsistencia.
Los totales reportados en el PDF, son la sumatoria de las percepciones y deducciones, gravadas y exentas. Lo cual me parece correcto.
En el XML, dicho total lo toma de lo capturado, y si la captura está chueca, ahí se genera la inconsistencia.
Los cálculos ya los hacemos, solo resta:
a) inhibir las capturas de totales (solo lectura)
b) actualizar los datos de los totales, con base a la sumatoria de los datos individuales

**Comment by jccastillo0007** [comment]
Yeap work in progress

JC@iPhone.
 Saludos.

**Comment by jccastillo0007** [comment]
Done... checalo en el ERP.
