### ISSUE TITLE
matStore - factura por comisión, duplica las ventas de tickets + factura PG

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1670]
Hoy corrió inicialmente el proceso de emitir facturas PG para los tickets que no se facturaron.
Entonces, como no está eliminando los tickets, pues la venta por ese concepto se duplica, esto para el cálculo de la factura de comisiones suma:

facturas emitidas + tickets no facturados + factura publico en general

solo que los 2 últimos puntos, son el mismo pero los está considerando doble, y con ello, la factura por comisión es mas alta de lo que debería.

Lo puedes checar con las facturas de hoy, del RFC MISC49

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
correcto, ya no considera los tickets no facturados en la factura de comsión.
