### ISSUE TITLE
matStore - facturas de comisiones, mostrar las facturas consideradas dentro de la comisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1671]
Cuando se genera una factura de comisiones de manera automática, incluir los datos de:

Serie, Folio, Fecha, RFC emisor, receptor, total, uuid

para cada factura considerada en las comisiones.
Se puede enviar como INFORMACIÓN COMPLEMENTARIA al PDF y también almacenar en la BD para futuros reportes.

**Comment by jccastillo0007** [comment]
hmmmm son demasiados datos... me parece que con el número de pedido es suficiente.
sobretodo porque esto ni siquiera es un requerimiento, para poder hacer match con las facturas consideradas en el cálculo de la comisión, se puede hacer con el número de pedido.

**Comment by RigoFlores** [comment]
yo decía porque al ver el PDF de una factura de comisiones podríamos saber cuáles facturas incluye y de cuál rfc, etc.
El pedido está bien, pero no dice nada al ver el PDF.
Los datos sugeridos son los generales de la factura, y con ello podríamos consultar dichas facturas.
Quizás el emisor no, ni el receptor... ya que esos son propios de la factura.
Posiblemente solo pedido, serie, folio, total.

**Comment by jccastillo0007** [comment]
ya puse la leyenda : 
serie: [serie] folio : [folio] pedido: [pedido]
en la descripción complementaria de cada producto, efectivamente no sale en el xml y si sale en el pdf

**Comment by RigoFlores** [comment]
Creo que estamos confundidos.
Lo que se hizo fue para facturas PUBLICO EN GENERAL, esto es para las facturas de las casas de materiales que se generan automáticamente, a partir de las remisiones.
Aún con ello, en el archivo de texto, se incluye la descripción complementaria.... y con esta leyenda que se le agrega, no sé cómo lo haces, pero se enciman las leyendas... checa.
Esto quiere decir, que la leyenda que le agregas, debe concatenarse a la descripción complementaria, en caso que se incluya en el archivo.

<img width="578" alt="matstore" src="https://user-images.githubusercontent.com/2912775/72363342-5371b800-36ba-11ea-8aad-26067016ee24.PNG">

**Comment by RigoFlores** [comment]
Ahora, para FACTURA DE COMISIONES, que es el punto de este issue, lo que se necesita es incluir como información complementaria, los datos de las facturas que están consideradas dentro de la factura de comisión:
pedido, serie, folio, total.
