### ISSUE TITLE
Al timbrar un cfdi con complemento de servicios parciales de construcción marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1672]
Mandé un correo con la información.
Básicamente intenta ponerle el campo residencia fiscal en el nodo emisor, y ese solo se ocupa en el complemento de comercio exterior. Este es el error que manda, cuando intenté timbrar en pruebas con el RFC TCM:

CFDI33134 : El RFC del receptor es de un RFC registrado en el SAT o un RFC genérico nacional y EXISTE el campo ResidenciaFiscal. (3)

Además necesito saber si se ocupa algo en hardcode para dar de alta algún cliente con ese complemento o solo con el XML de configuración es suficiente.

En producción tenemos ese complemento configurado para el cliente DLA090826L62

**Comment by jccastillo0007** [comment]
ese complemento es el mismo que el complemento de construcción ? porque no encuentro ninguno de parcialidades de construcción..

tampoco encontré referencia del rfc DLA090826L62

**Comment by RigoFlores** [comment]
como comenté anoche, si es el mismo.
Y no debe agregarle ese parámetro de pais de residencia.
Si no encontraste referencia a ese rfc, entonces es muy probable que no se defina en hardcode.

Pero ya no entendí, quedó corregido?

**Comment by jccastillo0007** [comment]
ya vi que paso, el RFC que usamos de prueba TCM.... estaba configurado para generar el complemento de comercio exterior... por eso le agregaba esos datos... ya se lo quite y funcionó bien.

Los RFC configurados para generar el complemento de construcción son : 

	COMPLEMENTO_CONSTRUCCION_1("CII770127MA2", XML_Types.CONSTRUCCION),
	COMPLEMENTO_CONSTRUCCION_2("VCS120820NK6", XML_Types.CONSTRUCCION),
	COMPLEMENTO_CONSTRUCCION_3("CVA9210236L2", XML_Types.CONSTRUCCION),
	COMPLEMENTO_CONSTRUCCION_4("TQM041022SG6", XML_Types.CONSTRUCCION),

Ninguno de los RFC que me enviaste están configurados con ese complemento

chiaaaa

**Comment by RigoFlores** [comment]
A ver, hay una confusión... una cosa es el rfc emisor y otra el RFC receptor.
Por lo que entiendo, al RFC emisor (nuestro cliente), no se le da de alta en hardcode, pero lo que si se ocupa en hardcode, es definir para cuáles RFC's receptores se debe considerar para el complemento. 

<img width="928" alt="complemento construccion" src="https://user-images.githubusercontent.com/2912775/73196918-182dab00-40f6-11ea-9719-cf491e896b6b.PNG">


Eso no me parece tan buena estrategia, pero bueno así está.
Lo ideal, es que por el nombre del XML de configuración se incluya el RFC del receptor, y así se conozca si aplica o no el complemento de  construcción, por ejemplo:

CFDi2AddConstruccion_TQM041022SG6.xml

indicaría que ese RFC RECEPTOR, puede aceptar el complemento, independientemente del RFC emisor. Algo así.

En resumen, ahora mismo, tendría que indicarte los RFC's receptores para el complemento de construcción.

**Comment by jccastillo0007** [comment]
se configuran ambos, tanto rfc emisores y receptores... 
Los emisores para estar seguros que nos pagaron el plugin de addendas o complementos
Los receptores para identfiicar quien debe recibir la addenda o complemento.

Existen addendas y/o complementos que se generan dependiendo los RFCs, pero hay otros que siempre se generan, sin importar el receptor.

Hay muchas variaciones, por eso se hizo asi.

**Comment by RigoFlores** [comment]
Para este complemento en particular, entiendo los emisores no se configuran, ya que te pasé un par de ellos, y no encontraste nada en jarcoud... el ejemplo que puse en la imagen de arriba, es un CFDI de producción con ese complemento, para el rfc emisor CMI04.
Lo que sí, es que el receptor del cfdi, si aparece en el listado que mencionaste arriba, esto es, RFC's receptores del complemento.
