### ISSUE TITLE
Al intentar generar un recibo de nómina con CFDI relacionado, marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1673]
Chiaaaa... no manches, esto es retrabajo...

está mandando esto al XML, cuando solo debe ser la clave...

cfdi:CfdiRelacionados TipoRelacion="04.Sustitución de los CFDI previos"

debería ser:

cfdi:CfdiRelacionados TipoRelacion="04"

Ahora cuando busca el CFDI relacionado, solo debe mostrar los recibos de nómina.
Está mostrando todo el desmadre de CFDI's

**Comment by jccastillo0007** [comment]
esto supongo nunca lo habían usado, ya que explícitamente esta poniendo el texto... ya le  cambié a mandar el código.

Respecto a la consulta, ese componente es genérico, no se puede personalizar, pero hay una opción para filtrar por tipo de CFDi... ahi pueden elegir Nómina

**Comment by jccastillo0007** [comment]
fixed
