### ISSUE TITLE
Condominios - CxP agregar en los combos de búsqueda, el nombre, y desplegar servicio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1675]
Es difícil saber cuál es el RFC del proveedor, entonces podríamos buscar también por nombre (además de los filtros ya existentes).
Al elegir por rfc o nombre al proveedor, mostrar en modo de solo lectura, el servicio que proporcionan

**Comment by RigoFlores** [comment]
En el listado de las consultas dentro de esta misma pantalla, agregar el RFC y servicio prestado.
Checa esta pantalla, si quiero registrar un pago, normalmente no conozco el rfc del proveedor. Entonces no sé a cuál rfc le tengo que asociar el pago.
 
Entonces dentro de los criterios de búsqueda, agregar nombre y servicio.
Y además también, en los resultados de la consulta, agregar el RFC y el servicio prestado por el proveedor. En esta pantalla que agregué, si se desplegara el rfc y servicio en los resultados, ya sabría a cuál rfc registrar el pago.



<img width="679" alt="pagos" src="https://user-images.githubusercontent.com/2912775/78412971-a4ff5400-75d2-11ea-820f-7cf02c7b3a34.PNG">

**Comment by jccastillo0007** [comment]
listo... ya esta la parte del nombre del proveedor y que se pueda volver a elegir la opción genérica, solo que para lograr esto último, los combos deben ser independientes.

La que pediste de mostrar el servicio, es realmente necesario?

**Comment by RigoFlores** [comment]
si, lo que pasa es que por ejemplo vas a registrar el pago de vigilancia... pero el rfc y nombre realmente podrían no decir mucho o nada... y ya con el servicio, sabes que ese rfc nombre, corresponde al servicio de vigilancia.
Yo he estado capturando esos pagos y si se complica no conocer cuál es el rfc de, por ejemplo vigilancia.
De hecho el servicio, podría ser el principal criterio para filtrar o buscar.

**Comment by RigoFlores** [comment]
ahora, si los combos son independientes, al elegir uno de ellos, los otros se deben 'alinear', esto es si eliges el servicio de recolección de basura, entonces al seleccionarlo, se muestra el rfc y nombre correspondiente

**Comment by jccastillo0007** [comment]
al ser independientes, me refiero a que al seleccionar uno delos combos , los otros NO se van a mover.. para autoseleccionar una de las opciones

**Comment by jccastillo0007** [comment]
voy agregar el servicio como combo, para que lo elijan, tu lo habías solicitado como solo lectura

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
ok, ya había quedado chido con nombre, rfc y servicio, todo sincronizado.
Pero bueno, se ve mas limpio así.
