### ISSUE TITLE
actualizar catálogos de nómina - ya envié un correo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1678]
Aquí está el resumen de los cambios, junto con los catálogos actualizados para cualquier referencia que quieras checar.
Las fechas que aparecen a la derecha no les hagas caso, no son parte de la descripción.
Algunas descripciones son muy largas, habría que abreviarlas o de que otra manera se puede hacer?

PERIODICIDAD DE PAGO: 
se agrega
10	Decenal

DEDUCCIONES, REVISAR TODO. CREO QUE CAMBIAN Y SE AGREGAN VARIOS

INCAPACIDADES: 
se agrega
04	Licencia por cuidados médicos de hijos diagnosticados con cáncer.

OTROS PAGOS:
cambia:
002	Subsidio para el empleo (efectivamente entregado al trabajador).	01/01/2017			
003	Viáticos (entregados al trabajador).	01/01/2017			
se agrega:
005	Reintegro de ISR retenido en exceso de ejercicio anterior (siempre que no haya sido enterado al SAT).	05/12/2017
006	Alimentos en bienes (Servicios de comedor y comida) Art 94 último párrafo LISR	01/01/2020
007	ISR ajustado por subsidio	01/01/2020
008	Subsidio efectivamente entregado que no correspondía (Aplica sólo cuando haya ajuste al cierre de mes en relación con el Apéndice 7 de la guía de llenado de nómina)	01/01/2020

PERCEPCIONES:
cambia:
047	Alimentación diferentes a los establecidos en el Art 94 último párrafo LISR
se agregan:
051	Pagos por gratificaciones, primas, compensaciones, recompensas u otros a extrabajadores derivados de jubilación en parcialidades	15/10/2018
052	Pagos que se realicen a extrabajadores que obtengan una jubilación en parcialidades derivados de la ejecución de resoluciones judicial o de un laudo	15/10/2018
053	Pagos que se realicen a extrabajadores que obtengan una jubilación en una sola exhibición derivados de la ejecución de resoluciones judicial o de un laudo	15/10/2018

REGIMEN
cambia:
05	Asimilados Miembros Sociedades Cooperativas Produccion	01/01/2017
06	Asimilados Integrantes Sociedades Asociaciones Civiles	01/01/2017
07	Asimilados Miembros consejos	01/01/2017
08	Asimilados comisionistas	01/01/2017
09	Asimilados Honorarios	01/01/2017
10	Asimilados acciones	01/01/2017
se agrega:
12	Jubilados o Pensionados	27/03/2017						
13	Indemnización o Separación	15/10/2018						

RIESGO:
Se agrega:
99	No aplica	13/08/2017

**Comment by jccastillo0007** [comment]
ya están todos los arriba mencionados , solo falta deducciones

**Comment by RigoFlores** [comment]
estoy esperando la pis of coud para revisar el catálogo de deducciones
