### ISSUE TITLE
Nómina - en régimen de asimilados, cuando no se incluye otros pagos, no enviar parámetro TotalOtrosPagos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1680]
En resumen, cuando NO SE INCLUYE INFORMACIÓN DEL NODO DE OTROS PAGOS, no debe enviar en el header el parámetro TotalOtrosPagos.

En detalle, cuando el régimen es cualquiera de los asimilados:

05 | Asimilados   Miembros Sociedades Cooperativas Produccion
06 | Asimilados   Integrantes Sociedades Asociaciones Civiles
07 | Asimilados   Miembros consejos
08 | Asimilados   comisionistas
09 | Asimilados   Honorarios
10 | Asimilados   acciones
11 | Asimilados   otros

El nodo de otros pagos, puede o no ir, Regularmente NO EXISTE, y en ese caso no se debe reportar el parámetro arriba mencionado.
Aquí el ejemplo, no se incluye información en el nodo otros pagos, pero si se reporta a nivel general el patámetro TotalOtrosPagos.

    <cfdi:Complemento>
        <nomina12:Nomina FechaFinalPago="2020-01-15" FechaInicialPago="2020-01-01" FechaPago="2020-01-15" NumDiasPagados="15.000" TipoNomina="O" TotalDeducciones="200.0" **TotalOtrosPagos="0.0"** TotalPercepciones="3000.0" Version="1.2">
            <nomina12:Receptor ClaveEntFed="QUE" Curp="CAAJ750607HDFSLN02" NumEmpleado="2" PeriodicidadPago="04" RiesgoPuesto="1" TipoContrato="09" TipoJornada="99" TipoRegimen="11"/>
            <nomina12:Percepciones TotalExento="0.0" TotalGravado="3000.0" TotalSueldos="3000.0">
                <nomina12:Percepcion Clave="046" Concepto="Ingresos asimilados a salarios" ImporteExento="0.0" ImporteGravado="3000.0" TipoPercepcion="046"/>
            </nomina12:Percepciones>
            <nomina12:Deducciones TotalImpuestosRetenidos="200.0" TotalOtrasDeducciones="0.0">
                <nomina12:Deduccion Clave="002" Concepto="ISR" Importe="200.0" TipoDeduccion="002"/>
            </nomina12:Deducciones>
        </nomina12:Nomina>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
YA SOLO LLEVARLO A PRO
