### ISSUE TITLE
Conector Nómina - cuando el nodo de otros pagos incluya importes de 0, incluirlo en el XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1681]
Ahora mismo, no soporta que el subsidio vaya con valor de 0.00.
Si va con valor 0.01, entonces si lo procesa bien.

Es el mismo error que se tenía en web.

Tener cuidado que si se incluye datos en la seccion de otros pagos, se debe reportar el parámetro de TotalOtrosPagos, que va a nivel header del complemento.
En caso que la sección de otros pagos venga vacía, no debe reportar el parámetro TotalOtrosPagos a nivel header.

Aquí un ejemplo de lo que si debería procesar:

[sueldos y Salarios.txt](https://github.com/jccastillo0007/eFacturaT/files/4141303/sueldos.y.Salarios.txt)

**Comment by jccastillo0007** [comment]
solo me falta probarlo bien bien

**Comment by jccastillo0007** [comment]
listo, ya lo subi, checale
