### ISSUE TITLE
Nomina - Otros Pagos, cambiar etiqueta de Total, por Importe

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1683]
Para mayor claridad con el tema de subsidio al empleo, que es el mas común en esa sección.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
No pues lo veo igual, espero que no hayas cambiado la etiqueta en otro lado.
Es cambiar la etiqueta Total, en la sección de otros pagos, por la etiqueta Importe

<img width="761" alt="otrosPagos" src="https://user-images.githubusercontent.com/2912775/74358138-8fb23a00-4d86-11ea-9ecf-a607bc01628c.PNG">

**Comment by jccastillo0007** [comment]
ya esta pero en PRU... aún no lo subo a PRO chiaaaa
