### ISSUE TITLE
Condominios - Administrador de Documentos - Consulta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1685]
Cuando ingresas las fechas en los filtros de búsqueda, deben ser las fechas asociadas al documento, NO deben ser las fechas cuando subiste el archivo.

El resultado de la consulta, debe ordenar por fecha asociada al archivo, NO debe ordenar por fecha cuando se subió el archivo.

**Comment by jccastillo0007** [comment]
ya no se usa la fecha de cuando se sube el archivo, se toma en cuenta la fecha seleccionada al subir el archivo... antes no estaba funcionando, pero ya jala.

**Comment by RigoFlores** [comment]
como le hago para borrar todo lo que hay, ya que supongo que se quedaron chuecas varias fechas y para validar, tengo que hacer la carga desde cero nuevamente...
