### ISSUE TITLE
Condominios - Administrador de documentos, limitar el tamaño del archivo a subir

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1686]
Creo que vale la pena limitar el tamaño del archivo que se va a subir, ya que nos pueden saturar el espacio en disco.

Cuánto crees que sea bueno?

Unos 3, 4 o 5 Mb?

**Comment by jccastillo0007** [comment]
no estoy seguro... tu hablabas de subir escrituras o reglamentos de condominios... esos son documentos muy grandes... 
En mi caso, las escrituras del régimen en condominio pesa 19 mg... yo creo que no debemos limitarlo, ya que justo lo que queremos es que suban todos los documentos...

capaz que lo dejamos asi, y monitoreamos, y vamos viendo... cómo ves?

**Comment by RigoFlores** [comment]
ok, manejemos un punto intermedio... que sea entonces de 30mb el tamaño máximo... es mucho, pero si no  ponemos límite, podrían tirar el server intentando subir archivos de terabytes...

**Comment by RigoFlores** [comment]
si es posible poner ese candado?

**Comment by jccastillo0007** [comment]
listo... si se puede agregar el candado, para que no saturen el servidor, sin embargo, si existe una primer carga inicial a un folder temporal, esto no lo puedo evitar.

Ya que se detecta que excede el límite de tama;o, se elimina

**Comment by jccastillo0007** [comment]
WTF !!!!

**Comment by RigoFlores** [comment]
chia, no se guardó la pregunta... si al elegir el archivo, antes de subirlo, no se pueden leer sus propiedades? según yo, debería poderse.

**Comment by jccastillo0007** [comment]
negativo... wicket lo sube a un folder temporal, y de ahi se mueve a la ruta final o se puede eliminar... pero si debe subirlo

**Comment by RigoFlores** [comment]
pues si no hay otra, esperar 10 min y luego que nos diga que no pudo...
