### ISSUE TITLE
Condominios - CxP- Registrar pago, una vez que elegiste un servicio para búsqueda ya no lo puedes quitar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1688]
Si en la búsqueda de facturas de proveedores, para registrar pagos, elijo un RFC, una vez que se elige, ya no hay forma de quitar ese filtro de RFC.
Digamos que a esa lista de RFC's de proveedores, le falta el famoso 'Seleccione uno' o algo así, que es equivalente a no indicar ningún RFC.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ya se madreó "pior", ahora si eliges el RFC o el nombre del proveedor durante la consulta, marca inmediatamente internal error....

**Comment by RigoFlores** [comment]
necesitamos pisarle pedal a las correcciones...
asi como está en pru, no podría mostrarlo a la persona que te comenté...

**Comment by jccastillo0007** [comment]
con que RFC pruebas tu?

**Comment by RigoFlores** [comment]
pues ahora ya no marca error, pero no jalan los filtros... elijo un rfc y muestra lo que quiere... y si lo haces por nombre, mismo caso... checa en la imagen


<img width="605" alt="pagos" src="https://user-images.githubusercontent.com/2912775/78617977-c1072d80-783e-11ea-8a0e-35b6f48bd72b.PNG">

**Comment by jccastillo0007** [comment]
chale.... ya vi

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
jajaja... según se solucionó quitando rfc y nombre, pero ahora cuando eliges un servicio, que es el único criterio de búsqueda que quedó (mas fechas y folios y status), ya no lo puedes quitar... es decir, ahora en la lista de servicios, está faltando el famoso 'seleccione uno'.

**Comment by jccastillo0007** [comment]
chiaaaa
fixed
