### ISSUE TITLE
Condominios - Egresos - registrar CFDI, solicitar el servicio asociado.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1689]
Cuando se registra un CFDi de un proveedor que NO EXISTE EN EL CATÁLOGO, y se le da guardar (como proveedor nuevo), que solicite capturar el servicio asociado a ese proveedor nuevo, ya que en otro caso, si se almacena el proveedor, pero queda sin servicio definido.

Lo que se hace ahora, es ir al catálogo de proveedores, y buscar dicho proveedor (para empezar, saber de cuál proveedor se trata, en medio de RFC's y nombres desconocidos) y luego capturar el servicio. Eso nos lo podemos ahorrar capturando el servicio desde que se sube por primera vez un CFDI de un proveedor nuevo.

**Comment by jccastillo0007** [comment]
este no lo había actualizado, pero ya esta listo...

**Comment by RigoFlores** [comment]
pues aparece una caja de texto para capturarlo, pero no lo guarda el servicio en el catálogo de proveedores.

**Comment by jccastillo0007** [comment]
debería de guardarlo, se me hace que no lo había subido completo

**Comment by jccastillo0007** [comment]
si encontre el problema, y lo arreglé... ya subí todo a Prod

**Comment by RigoFlores** [comment]
si ya lo guarda.
Hay otros issues importantes al respecto, pero los documentaré en nuevo issue.
