### ISSUE TITLE
Condominios - Egresos y CxP, quitar validación del SAT solo en PRUEBAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1690]
Cuando se sube un CFDI en el menú de Egresos - Registrar CFDI, o cuando desde el menú de CxP- registrar pago, se registra un pago a un CFDI, eliminar la validación que el CFDI esté registrado y vigente ante el SAT.
Eso solo aplicará para producción.

**Comment by jccastillo0007** [comment]
listo.
en Egresos ya se estaba ignorando... 
en ambos casos ya le puse la validación del ambiente

**Comment by RigoFlores** [comment]
en pruebas ya no pide validación.
Checaré en producción...
