### ISSUE TITLE
Condominios - CxP - cartera de proveedores, agregar el filtro de servicio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1691]
Hoy solo existe el filtro de rfc y número de proveedor...
Agregar el de servicio, así como lo hiciste en CxP - Ingresar pago, quedó bien.

**Comment by jccastillo0007** [comment]
en Egresos no hay un submenú de cartera de proveedores, supongo que te refieres al menú de Cuentas x Pagar... 
Quieres que deje solo el filtro de servicio? o que queden las tres opciones pero de forma independiente?

**Comment by RigoFlores** [comment]
en lugar de número de proveedor, podría ser servicio.
Ahora que pasa si eligen servicio, y luego rfc... estaría chueco eso, a cuál filtro le haria caso?
por ejemplo eligen vigilancia, y entonces en rfc solo debería mostrar los rfcs que tengan asociado el servicio de vigilancia, así quedaría?

**Comment by jccastillo0007** [comment]
no, ya he comentado que los combos son independientes... uno no actualiza al otro... esto es para poder limpiar el filtro y elegir la opción "Seleccionar uno"

Si eligen rfc y servicio, podemos darle preferencia a rfc, y luego sobre esos resultados, elegir los que tienen el servicio elegido... pero los combos seguiran siendo independientes.

**Comment by RigoFlores** [comment]
pues si debería actualizar, sería lo mínimo esperado.
Si se complica implementarlo, no significa que esté bien... de hecho estaría mal... pero bueno, pues si eligen los dos filtros, y la aplicación tiene que elegir unos solo (jeje), pues que sea servicio y no RFC

**Comment by jccastillo0007** [comment]
pueden estar ligados, pero se perdería la posibilidad de ya no elegir ninguno... que es lo que inicialmente se requería

**Comment by RigoFlores** [comment]
lo que se pide es agregar el filtro de servicio en este menú, y eso aún no se cumple.
Hoy existe el número de proveedor, y creo que podríamos prescindir de él, y en lugar colocar servicio, tal como lo mencioné arriba.
