### ISSUE TITLE
Condominios - CxC - Ingresar cobro, ocultar paso 3, a menos que se ocupe

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1693]
El paso 3, será raro que se ocupe.
Entonces podemos ocultarlo y mostrarlo a petición del usuario, cuando le den click en "incluir cfdi de pago", o algún botón equivalente.
Es decir, que por omisión, no muestre los datos del paso 3, ya que solo obligan a usar la barra lateral para buscar el botón de guardar el pago.

La otra opción, es en seguida del paso 2, colocar el botón de registrar pago.

**Comment by jccastillo0007** [comment]
a chinga... creo que si quedo chido

**Comment by RigoFlores** [comment]
si quedó chido..!!!
