### ISSUE TITLE
Condominios -CxP-Ingresar pago, varios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1694]
1) cuando entras a la pantalla, colocar por omisión, forma de pago, igual a transferencia electrónica de fondos..

Después de haber capturado y guardado el primer pago:

a) mantener la forma de pago del último pago capturado.
b) mantener la fecha de pago del último pago capturado.

Cuando vas a buscar los CFDI's de proveedores:

i) al seleccionar el servicio, ejecutar la búsqueda sin esperar a dar click en la lupa.

con lo anterior, se ahorran varios clicks durante el proceso de captura.

**Comment by jccastillo0007** [comment]
quedaron todos los items, excepto el i)

Esto es porque no solo es el servicio, tal vez quieran ingresar un rango de fechas, folios o elegir una vigencia... si se ejecuta la búsqueda de inmediato, y luego eligen otro dato para filtrar, terminará en doble búsqueda

**Comment by RigoFlores** [comment]
lo que aplica es que si quieren otro filtro, primero elijan las fechas o folios y luego el servicio.
pero bueno, vamos a ver... según yo si se ocupa que al elegir servicio, se realice la búsqueda
