### ISSUE TITLE
MatStore - Implementar cambios del layout, y subir ambiente de pruebas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1695]
Como comenté por correo, el layout sufrió cambios. Así dice dicho correo:

ESTOS SON LOS CAMBIOS EN EL LAYOUT.

a)	Siempre será factura, por lo que se elimina el campo
b)	Se elimina el método de pago del layout, siempre será PUE
c)	Se elimina condiciones de pago del layout, es un dato opcional
d)	La moneda siempre será MXN, por lo tanto se elimina moneda y tipo de cambio del layout

Anexo ejemplo del archivo de texto, y la descripción del layout actualizada.

Otras observaciones:
1.	El archivo debe tener extensión .csv
2.	El nombre del archivo será la fecha en formato DDMMAAA.csv, ejemplo: “11042020.csv”

Asimismo se solicita levantar el ambiente de pruebas...

**Comment by RigoFlores** [comment]
Aquí la descripción del layout y un archivo de ejemplo con 3 facturas.
La tercer factura no se factura al momento, tendría que ser desde la plataforma de factura al instante.

[Descripción LayoutCasaMateriales 2.0.zip](https://github.com/jccastillo0007/eFacturaT/files/4470607/Descripcion.LayoutCasaMateriales.2.0.zip)

**Comment by jccastillo0007** [comment]
Psss esto ya no aplica, pues el cliente se dio por vencido... chiaaaa
