### ISSUE TITLE
Condominios - Egresos - Registrar un CFDI, proveedor nuevo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1696]
Cuando se registre el CFDI de un proveedor nuevo y se guarde el registro de dicho proveedor en el catálogo de proveedores, se tiene que pedir el servicio asociado, pero aún más, no debe permitir guardar el registro del proveedor, si no se ha capturado el servicio.
Creo que puede ser:

Cuando le den guardar, si no ha capturado el servicio, pedir que se capture y vuelva a intentar guardar el registro del proveedor. Esto es asegurar que no se guarde el registro del proveedor, si no se ha capturado el servicio.

**Comment by jccastillo0007** [comment]
asi es como esta implementado, chiaaa

**Comment by RigoFlores** [comment]
Pues no, no está así.
Subí un XML de un proveedor nuevo; no le capturé el servicio; le dí guardar, y me mandó esta pantalla:

1) Si guardó el registro en el catálogo SIN servicio, lo cual es incorrecto.
2) Aunque el mensaje es correcto, no así la ejecución.
3) Cuando se presente esta situación, NO debe guardar el registro y además NO debe limpiar la pantalla, porque los datos del proveedor ya se han borrado, tal como se ve en la imagen.



<img width="631" alt="proveedor" src="https://user-images.githubusercontent.com/2912775/79360236-3e026900-7f09-11ea-9fde-bbcb568b19cd.PNG">
