### ISSUE TITLE
Condominios - Egresos y CxP, mantener consistencia en el campo servicio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1697]
Yo creo que se debe implementar un catálogo de servicios, y de ahí tomarlo/consultarlo en todo lugar donde se ocupe.
Catálogo de Proveedores, Ingresar CFDI nuevo, y consultas.
Hoy en día no tenemos consistencia en ese dato. Si dos proveedores brindan el mismo servicio, los ve como servicios distintos (te acabo de mandar un correo).

Hoy existe un catálogo de servicios, que tiene que ver mas bien con lo que se paga por parte del condómino, por ejemplo la cuota de mantenimiento.
Se podría ocupar el mismo, pero yo creo que son cosas distintas. Hay que implementar un catálogo de servicios de proveedores.

**Comment by jccastillo0007** [comment]
hmmm es suficiente con que el servicio no se duplique al elegirlo, o realmente se requiere un catálogo de servicios de proveedores

**Comment by RigoFlores** [comment]
Si no implementamos el catálogo, entonces caemos en la situación que un mismo servicio le llamen o escriban distinto: Vigilancia, Seguridad, Vigilancia y Seguridad, Guardias, etc, siendo que se trata del mismo servicio.
El deber ser sería hacer el catálogo de "Servicios Proveedores".

Podríamos salir sin ese catálogo, pero pues si corremos ese riesgo. Tendríamos que asegurar que si escriben exactamente el mismo servicio, no lo repita, y además que muestre todos los resultados de las facturas o proveedores con el mismo servicio.

**Comment by jccastillo0007** [comment]
bueno, ya esta la validación en la pantalla de pagos para no duplicar el servicio

Pues hay que levantar otro ticket para el catálogo de servicios de proveedor..
