### ISSUE TITLE
Timbrado XML mayores a 90kb, enviarlos a Finkok

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1698]
Ahora mismo, tenemos varios clientes que se van por Finkok siempre, y eso se debe a que emiten algunas de sus facturas muy grandes, esto es el XML supera los 100 kb de tamaño. Lo anterior implica que estamos consumiendo y pagando folios de mas con Finkok.

Ahora un segundo y mas grave problema, es cuando un cliente no está alambrado para irse siempre por Finkok, y se presenta la situación de un XML muy grande, lo que sucederá es que se timbrará dos veces, uno por FHoy y otro por Finkok, sin que nadie nos demos cuenta, ya que en ese caso el timbrado de FHoy es asíncrono. Ayer detecté un par de casos con Optibelt, sucedieron en noviembre y marzo pasado.

Lo que tendríamos que hacer es tomar el tamaño del XML previo a timbrarlo, si supera los 90Kb, entonces enviarlo en automático por Finkok.

**Comment by RigoFlores** [comment]
Se volvió a presentar un caso... generalmente son facturas de alto importe, y nadie se entera que están vigentes... hasta que aparecen en el SAT...

**Comment by jccastillo0007** [comment]
ya estoy trabajando en esto...  hoy agregué un log en el server para validar el tama;o de los XML... ma;ana voy a validar el log y si todo sale bien, subo el fix para que se vaya por finkok.

**Comment by jccastillo0007** [comment]
done... estoy validando 100,000 bytes que son 100kb... pero estaría bien ver un ejemplo al menos en PRU y ver que si funcione correctamente

**Comment by jccastillo0007** [comment]
Entre el 8 y el 11 de agosto, van como 15 xml que se van por finkok por el tama;o o porque tienen el constraint del rfc... pero estos 15 xml que te digo, como quieran miden mas de 100kb..
tons estamos bien

**Comment by jccastillo0007** [comment]
Para obtener los archivos que se fueron por finkok, sigue estas instrucciones.

1. entras al server y te cambias al folder donde esta el catalina.out
2. corres este comando
more catalina.out | grep -A1 "Size of this XML in bytes" 
3. vas a ver una salida como esta:
2020-08-12 20:42:37,649 DEBUG [http-nio-8080-exec-14] (Sealer.java:150) - Size of this XML in bytes : 
144532
4. El número 144532 es el tama;o del archivo en bytes
5. Entras al catalina.out, y buscas la parte inicial de los resultados, la parte de la fecha 2020-08-12 20:42:37,649
6. Debajo de esa línea vas a ver el XML en cuestion

**Comment by RigoFlores** [comment]
Revisé varios casos, y son prácticamente los que están con el bypass.
Difícil será ver otro caso, ya que no son tan comunes... le pediré a optibelt que me notifique cuando realice una de esas facturas chonchas....

**Comment by RigoFlores** [comment]
de los rfc's que tenemos ahora con bypass, favor de pasar FLM030313DJ6 y DMR840730523 a que timbren por fhoy, y solo cuando se cumpla la condición de tamaño, se irían por finkok.
No es mucho, pero pues nos ahorraríamos unos pesos...

**Comment by jccastillo0007** [comment]
listo, solo quedo este rfc configurado a irse siempre por finkok: SAFR720409BE2
