### ISSUE TITLE
Complemento de Pago-Factoraje, detalles varios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1699]
a) paso 4, puedes elegir rfc  o nombre, pero no pueden quedar chuecos. Esa funcionalidad es la estándar, que elige rfc y se coloca el nombre o viceversa.

b) paso 4, no sugiere la misma referencia que el paso 1, lo deja vacío.

c) paso 4, no sugiere que el importe del pago sea el saldo insoluto del paso 2

d) en el nodo 2 del XML que genera, no incluye la referencia.

e) en el paso 4, aún no he capturado el importe del cobro, pero en la factura ya aparece el importe. Debería aparecer en ambos, pero si captura el monto que NO liquide completamente, entonces debería cambiar en ambos lados. (checa la imagen abajo)

<img width="723" alt="factoraje" src="https://user-images.githubusercontent.com/2912775/79921861-b4ff9c00-83f8-11ea-96c5-e03b676647ea.PNG">

**Comment by jccastillo0007** [comment]
ya están listos el a, b y d

el c y e, quedan pendientes pues esta medio cabrón!!!!

**Comment by RigoFlores** [comment]
a) OK
b) sigue igual
d) no lo pude validar, porque ahora ya no aparecen las facturas que se están pagando en el segundo nodo.

ya no aparece el listado de facturas del paso 4. Antes apareceían, ver la imagen arriba. Incluso el saldo por pagar ya aparecía, ese podría ser el saldo insoluto sugerido.

**Comment by jccastillo0007** [comment]
ya están a, b, c y d

El e acordamos que por el momento no lo hariamos
