### ISSUE TITLE
Complemento de Pago - factoraje, el segundo nodo no registra pagadas las facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1700]
checa este ejemplo:

        <pago10:Pagos Version="1.0">
            <pago10:Pago CtaBeneficiario="1047322261" CtaOrdenante="012387004475083369" FechaPago="2020-04-01T12:00:00" FormaDePagoP="03" MonedaP="MXN" Monto="1100.00" NumOperacion="factoraje10" RfcEmisorCtaBen="BNM840515VB1" RfcEmisorCtaOrd="BNM840515VB1">
                <pago10:DoctoRelacionado Folio="63" IdDocumento="36BBBA19-2301-4316-BC49-64989D00C440" ImpPagado="100.00" ImpSaldoAnt="116.00" ImpSaldoInsoluto="16.00" MetodoDePagoDR="PUE" MonedaDR="MXN" NumParcialidad="1" Serie="FEE"/>
                <pago10:DoctoRelacionado Folio="64" IdDocumento="ED51AF6B-DA63-4D94-B681-91F8AC47DA22" ImpPagado="1000.00" ImpSaldoAnt="1160.00" ImpSaldoInsoluto="160.00" MetodoDePagoDR="PUE" MonedaDR="MXN" NumParcialidad="1" Serie="FEE"/>
            </pago10:Pago>
            <pago10:Pago FechaPago="2020-04-01T12:00:00" FormaDePagoP="17" MonedaP="MXN" Monto="176.0">
                <pago10:DoctoRelacionado Folio="63" IdDocumento="36BBBA19-2301-4316-BC49-64989D00C440" ImpPagado="16.00" ImpSaldoAnt="16.00" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PUE" MonedaDR="MXN" NumParcialidad="2" Serie="FEE"/>
                <pago10:DoctoRelacionado Folio="64" IdDocumento="ED51AF6B-DA63-4D94-B681-91F8AC47DA22" ImpPagado="160.00" ImpSaldoAnt="160.00" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PUE" MonedaDR="MXN" NumParcialidad="2" Serie="FEE"/>
            </pago10:Pago>
        </pago10:Pagos>

si revisas, el segundo pago deja a saldo insoluto = 0. para las facturas 63 y 64. El complemento de pago, está bien, solo le faltaba la referencia en el nodo 2.
Peeeero en la opción de CxC, ingresar cobro, si consultas esas facturas 63 y 64, indica que precisamente tienen un saldo insoluto, igual a lo que se pagó en el segundo nodo.

En resumen, si el segundo nodo liquida las facturas, que es lo mas probable que suceda, el sistema no pone esas facturas a pagadas, con obviamente saldo insoluto = 0.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
negativo, aún no queda del todo.
Si bien el saldo insoluto ya lo coloca a 0.00, no le cambia el status a pagada, y con ello sigue apareciendo en CxC, aún con saldo pendiente 0.

**Comment by jccastillo0007** [comment]
fixed
