### ISSUE TITLE
Complemento de pago factoraje, algunos detalles

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1701]
a) En el paso 4, podría quedar como está de manera inicial, pero también debería ser editable el monto del pago de cada factura, ya que ahora lo deja fijo.

b) El enfoque chacarrón del segundo header.
Hay que enviar dos productos dummy, uno será para dejar un espacio y el otro contendrá la info del segundo header:

PAGO               PRODUCTO ESTANDAR   ESPACIO   HEADER NODO 2

IdDocumento-----------unidad----------------------VACIO-----HEADER
Serie---------------------idProducto-------------------------------FechaDePago
Folio---------------------descripcion------------------------------FormaDePago
MonedaDR--------------cuenta-predial---------------------------moneda
TipoCambioDR---------importe-----------------------------------TipoDeCambio
MetodoDePagoDR----idProductoSAT----------------------------MontoPago
NumParcialidad-------descripcionComplementaria--------------Referencia
ImpSaldoAnt-----------valorUnitario------
ImpPagado-------------cantidad------
ImpSaldoInsoluto------descuento----

**Comment by RigoFlores** [comment]
te mandé un excel, con lo que se requiere... está mas complicado de lo que pensé...

**Comment by jccastillo0007** [comment]
quedo listo, el tema de todos los productos vacíos... y el header del header... pero me falta enviar los valores del header... pero me parece que ya puedes empezar con el template.

**Comment by RigoFlores** [comment]
el template está listo en pruebas... es compatible lo anterior con lo actual...

**Comment by jccastillo0007** [comment]
done... peeeero tengo broncas para mandar la forma de pago y el monto del pago en el header del nodo 2...

**Comment by RigoFlores** [comment]
de hecho en el header 2, estás repitiendo la información del jeder 1, lo cual es incorrecto...
<img width="511" alt="header" src="https://user-images.githubusercontent.com/2912775/80284816-6eef5480-86e6-11ea-9dd3-a6043c2c2a05.PNG">

**Comment by RigoFlores** [comment]
puedes enviar antes del jeder 2, un jeder del jeder:
En lugar de Vacio, que diga "Datos del pago Factoraje", y el resto de columnas tal cual está, es decir null o empty.

y después de los datos del jeder 2, quizás no enviar tantos vacíos, quizás con dos es mas que suficiente.

**Comment by jccastillo0007** [comment]
listo
