### ISSUE TITLE
Complemento de Pago, ya no genera los XML que no llevan factoraje

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1702]
Intenté hacer un complemento normal, y no jaló.
Marca "error no clasificado", esto es que no va completo el XML con el complemento, checa el cuerpo del XML, le falta el nodo del complemento.

 
<img width="933" alt="noclasificado" src="https://user-images.githubusercontent.com/2912775/80236658-0db17d80-8621-11ea-88fc-5d5deef5ba38.PNG">

**Comment by jccastillo0007** [comment]
fixed
