### ISSUE TITLE
Complemento de pago factoraje, otros detalles

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1703]
a) El jeder del segundo jeder, enviarlo con mayúsculas, para que resalte del segundo jeder.

<img width="577" alt="factoraje" src="https://user-images.githubusercontent.com/2912775/80398774-c673f880-887d-11ea-8696-e7431163b9a0.PNG">

b) Cuando pagas con factoraje, mas de una factura, el saldo insoluto que guarda en la BD para cada factura involucrada, lo pone a negativo, ya que le resta el total del importe pagado, en lugar de restar el pago de cada factura.

c) Y como resulta un saldo insoluto en negativo, no lo pone a pagada.

Si revisas la imagen de arriba, todo está bien, pero en la BD le restó $2,000 a cada factura, en lugar de 1000 que es el pago que le corresponde a cada factura... quedando así:

<img width="486" alt="factoraje2" src="https://user-images.githubusercontent.com/2912775/80399075-3bdfc900-887e-11ea-93da-ba8e00a4e790.PNG">

**Comment by jccastillo0007** [comment]
done
