### ISSUE TITLE
Complemento de pago Factoraje - CxC - Registro de cobro... no indica que lo realizó correctamente, cuando no hay CFDI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1706]
Si tu registras un cobro, sin emitir CFDI de pago (paso 3)... al darle guardar, no manda el mensaje de cobro registrado con éxito como anteriormente si lo hacía.

Ni siquiera tiene que ver con el tema del factoraje (obvio por los cambios realizados, si), pero lo que quiero decir, es que el error se presenta sin llegar al paso 3, y evidentemente paso 4.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
hay que subirlo a pro
