### ISSUE TITLE
Factura al instante - si no ingresas el RFC emisor, no encuentra los tickets

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1708]
Para central de abastos no debe pedir el RFC emisor como obligado

**Comment by jccastillo0007** [comment]
si se requiere, para saber que es de central de abastos.. y asi poder incluir la funcionalidad de agregar varios tickets en la misma factura

**Comment by RigoFlores** [comment]
Ellos pidieron que no se capture el RFC. Solo son dos datos: id ticket e importe. 

Por otro lado, desde el conector, al enviarlo y con los datos de la llave, ya se conoce el RFC emisor. Así que si se requiere, pues entonces hay que incluirlo para que lo muestre y no tengan que capturarlo. Está medio chafa eso, pero pues si se requiere a juerzas, pues que ya lo muestre por default.

**Comment by jccastillo0007** [comment]
hmmmm no entiendo, en la pantalla principal de factura al instante, deben capturar el rfc emisor, para saber donde buscar, ya que eventualmente va haber muchos clientes usando esa pantalla.
Cómo saber si se trata de ellos o no, recuerda que para no pedir la fecha del ticket, debemos saber que se trata de ellos, de lo contrario la fecha se requiere

**Comment by RigoFlores** [comment]
Si, el problema al que nos enfrentamos, es que en el ticket, no aparece el rfc de ellos... y entonces el usuario, difícilmente conocerá ese RFC.
Lo que yo comentaba, es que ese RFC se puede tomar de la llave, y al llegar a la plataforma, asociarlo a ese ticket. Con ello, ese ticket ya está predefinido a que solo con ese emisor se pueda facturar... se tendría que dar la combinación de id + total, para que se presentara un caso de duplicidad... lo cual podría llegar a darse, en cuyo caso, pues si que hay que resolverlo... jaja
Yo creo que por lo pronto no debe pedirlo, ellos serán los únicos usuarios de factura al instante...

La otra es listar los RFC's emisores que son usuarios de facturat, así como le hace en descargaT

**Comment by jccastillo0007** [comment]
ya esta listo, pero en el descargat, tendrán que elegir el emisor de la lista, sabes si en el ticket viene el nombre?

porque si no, se rompe toda la pantalla de descargat

**Comment by RigoFlores** [comment]
hasta donde entiendo, no viene el RFC en el ticket, podríamos pedir que lo incluyan en su siguiente impresión... jeje
Supongo son miles los que imprimen, y además, no estoy seguro que quieran incluir el RFC en esas impresiones.
Les puedo preguntar... 

Ahora mismo, hasta donde sé, no existen usuarios del descargat, cómo lo puedo saber?
