### ISSUE TITLE
Factura al instante - informar si encontró o no encontró el ticket

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1709]
En la pantalla no aparece nada.
Si no lo encuentra, solo no pasa nada.
Si lo encuentra, aparecen los datos abajo, pero no es muy intuitivo.

Enviar un mensaje (NO modal), que el ticket fue encontrado o no

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
el mensaje dice CFDI no encontrado...
Debe decir "Ticket o Remisión no encontrado"

**Comment by jccastillo0007** [comment]
Done
