### ISSUE TITLE
AGREGAR UNA PANTALLA DE CONFIGURACIÓN DE NÓMINA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#171]
CONSIDERAR PARÁMETROS GENERALES DE LA NÓMINA:
-LUGAR DE EXPEDICION (POR OMISIÓN EL FISCAL, PERO CON OPCIÓN DE MODIFICARLO, YA QUE ES EL LA PLAZA DONDE LABORA EL EMPLEADO)
-METODO DE PAGO / CUENTA BANCARIA, POR DEFAULT NO IDENTIFICADO
-CONDICIONES DE PAGO, POR DEFAULT DE CONTADO
-REGISTRO PATRONAL (QUITARLO DE LA PANTALLA ACTUAL)
-BANCO (CON OPCIÓN DE CAMBIARLO A NIVEL EMPLEADO)
-PERIODICIDAD DE PAGO (CON OPCION DE CAMBIARLO A NIVEL EMPLEADO)
-NO DIAS PAGADO (CON OPCION DE CAMBIARLO A NIVEL EMPLEADO)
-FECHA INICIAL DE PAGO
-FECHA FINAL DE PAGO
-FECHA DE PAGO
-BOTÓN PARA GENERAR TODOS LOS RECIBOS CAPTURADOS EN LA BD.
EN CASO DE GENERACIÓN MASIVA, NOTIFICAR BARRA DE AVANCE EN PANTALLA, QUE AUNQUE TARDE MAS DE 10 MINUTOS, NO SE BLOQUEÉ LA PANTALLA.

**Comment by jccastillo0007** [comment]
Ya esta la pantalla de configuración... ahorita solo tiene los datos indispensables para la operacion de nómina empresarial..

fecha de pago
fecha inicio de pago
fecha fin de pago...

Hay datos que quiero platicar contigo, para ver si los ponemos en la pantalla de configuración general o los dejamos en la pantalla por empleado.

El tema de antiguedad, talvez seria mejor no enviarlo al fin es opcional... como ves...

**Comment by jccastillo0007** [comment]
me parece que no es necesario invertir mas en esta pantalla... a reserva de que varios usuarios nos pidan esta funcionalidad.

**Comment by RigoFlores** [comment]
PUES REALMENTE LOS USUARIOS NO NOS LA PIDIERON EXPLÍCITAMENTE.
TODO VA ENFOCADO A LA SIMPLICIDAD Y FUNCIONALIDAD.
SI LO PODEMOS CERRAR, PARA NO DEJAR CASOS MEDIO-ABIERTOS, PERO NO SE DEBE DESCARTAR. 
ESTA ENGEISMENT NO SURGIÓ DEL CLIENTE, SI NO DEL RESPONSABLE FUNCIONAL.
