### ISSUE TITLE
Factura al instante - mostrar por omisión Uso de CFDI - Gastos en General

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1710]
Casi siempre será ese, entonces es mejor ponerlo por omisión.
Y mantenerlo después de emitir cada factura.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Solo cuando accedes a la pantalla lo muestra.....
Cuando has capturado la información del primer ticket, y el RFC receptor, nombre y correo...
Y después le agregas otro ticket... borra la información de uso, rfc, nombre y correo...

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
este ticket ya, pero sigue borrando el rfc, nombre y correo cuando agregas un ticket.
Quizás la solución sea subir la captura de tickets adicionales, arriba de el rfc, nombre, correo, para que eso lo tecleen al final.
