### ISSUE TITLE
Factura al instante - enviar como información complementaria, el ID ticket

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1711]
o como parte de la descripción, para poderle dar seguimiento a los tickets.
De qué otra forma sabremos que un ticket ya ha sido facturado?
Ahora mismo solo desaparece cuando ya se facturó, quizás no está tan mal, pero se pierde la traza.
Lo mejor sería que siguiera apareciendo, pero que ya no sea facturable.

**Comment by jccastillo0007** [comment]
entrando a efacturat con el emisor, se pueden ver las facturas que antes eran remisiones, tienen el mismo folio... pero los tickets que se incluyeron en otras facturas siguen siendo remisiones, ese si es un problema.

No sé como indicar si es o no facturable, en consultas

**Comment by RigoFlores** [comment]
Ya vi... a la factura le asigna el mismo ID que tenía la remisión, eso es un problema en sí, ya que se puede repetir, para temas de cancelación, temas de complemento de pago, etc.
El otro problema, como bien dices, es que a partir del segundo ticket en adelante, siguen apareciendo 'las remisiones' en pantalla.

Lo que yo creo que se debe hacer, es agregar el status de Facurada a los tickets, y en ese caso que se sigan mostrando todas, pero que se indiquen que ya fueron facturadas.

Aún así, el problema sigue siendo, cómo saber cuál factura le corresponde a cuál(es) ticket(s)...??

**Comment by RigoFlores** [comment]
creo que para este caso muy particular, y para no romperle nada a lo que tenemos, si le asignamos el ID producto = ID ticket, y tomando en cuenta que solo 1 ticket = 1 producto, pues con eso estaría resuelto lo de conocer cuáles tickets se incluyeron en cuáles facturas. Claro, tendrían que ver las facturas para conocerlo. Pero ya es algo.

Y lo otro, para no moverle mucho, poner las remisiones a canceladas, para que no aparezcan o para que se puedan filtrar... lo ideal, es ponerlas a facturadas.

**Comment by jccastillo0007** [comment]
[6:37 PM, 7/16/2020] JC: los productos van a tener como id, el ticket, eso me parece muy buena idea
[6:38 PM, 7/16/2020] JC: las remisiones ya facturadas, van a quedar como pagadas , esto se verá en el efacturat con el usuario de central de abastos

**Comment by RigoFlores** [comment]
bueno, aún queda un tema...  yo incluyo varios tickets en una factura... a todos ellos los pone como pagados, excepto a uno, es el primero, que ya no aparece en el listado... es decir, estamos desapareciendo un ticket, y deberían estar todos los facturados como pagados, que no?

**Comment by RigoFlores** [comment]
checa esta imagen, los tickets 1245, 1246 y 1247 fueron facturados, pero solo aparecen dos de ellos, mas la factura... eso está incompleto... chueco... creo yo deben aparecer los 3 tickets (los n que se incluyan en la factura), además de la factura.

<img width="644" alt="remision" src="https://user-images.githubusercontent.com/2912775/87740911-f6f66f00-c7a8-11ea-9890-60b89672459e.PNG">

**Comment by jccastillo0007** [comment]
es que la remisión que se uso para generar la factura, es decir, el primer ticket capturado, se utiliza para generar la factura, y se convierte en factura, no es que desaparezca

**Comment by RigoFlores** [comment]
si, me queda claro eso... pero la inconsistencia existe.
todos los tickets deben aparecer como pagados y adicionalmente la factura

**Comment by jccastillo0007** [comment]
al parecer ya quedo... se deja la remisión con estatus pagada y se crea una factura
