### ISSUE TITLE
Factura al instante - incluir mas de un ticket en una factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1712]
Falta agregar esa facilidad, de poder facturar o agregar mas de un ticket, en una factura

**Comment by jccastillo0007** [comment]
esto ya esta implementado, chiaaaa

**Comment by RigoFlores** [comment]
ayer lo intenté y no jaló. Ahora ya jala con sus asegunes:

a) está faltando el mensaje que el nuevo ticket se agregó a la factura, o en su caso que el ticket no fue encontrado.
b) cuando un ticket si lo encontró, y lo agrega, hay que borrarlo de la pantalla, ya que lo mantiene.
c) en el listado de productos que se van acumulando, agregar la columna del ticket.
d) Cuando genera la factura ya no coloca el ícono del PDF y XML para su descarga. OJO, no se pidió en el otro issue que se eliminaran estos íconos, sino hasta que le den buscar oootro ticket.

**Comment by jccastillo0007** [comment]
el problema original de este ticket, ya esta arregaldo.. incluso varios de los puntos que mencionaste.

si falta algo mas, mejor levanta otro ticket, no pongas varias cosas en el mismo ticket

**Comment by RigoFlores** [comment]
chiaaaaa... todos se refieren a lo mismo, pero ok, levantaré otros

**Comment by RigoFlores** [comment]
pues ya dejó de jalar... aunque en teoría puede agregar mas de un ticket, no muestra en pantalla los datos de los tickets agregados, y la sumatoria del total, se queda con lo del primer ticket.... dejó de jalar esto

**Comment by jccastillo0007** [comment]
anexo evidencia... ojo... ya se debe usar el RFC AMA... y no el XQI...
![Captura de Pantalla 2020-07-24 a la(s) 16 16 35](https://user-images.githubusercontent.com/2245679/88436187-5e27ab00-cdc9-11ea-9738-a75736a578ca.png)

**Comment by RigoFlores** [comment]
Ahorita ya quedó un poco ajustado a lo que teníamos antes y a lo que se pidió. Para completarlo y sea mas robusto y flexible, le falta lo siguiente:

a) el valor de contabilidad, debería solicitarse solo una vez, y aplicarlo donde corresponda header o subnodo. Hoy lo pedimos doble, pero solo se capturará uno u otro. Así que deberíamos pedirlo solo una vez.
b) Hoy solo aceptamos un valor de contabilidad, pero la spec dice de 0 a muchos. Podría darse el caso de requerir mas de uno, eso implicaría quizás que este dato fuera el último de la captura y todos los que se agreguen, pues serían adicionales de la contabilidad.
c) Ya no seguí haciendo pruebas, pero como el dato de contabilidad a nivel subnodo podría ir en vacío, ya no lo probé...
d) Hasta donde recuerdo, tenemos amarrado el complemento a ciertos RFC receptores (de partidos políticos), pero debemos abrirlo ya que los partidos cambian y además aplica para candidatos independientes y para AC aspirantes a partido.

Que chinga, no???
