### ISSUE TITLE
Factura al instante - quitar los íconos de PDF y XML, cuando se realiza una nueva búsqueda

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1713]
Si ya se realizó una factura.... se generan los íconos de PDF y XML en la parte inferior para la descarga, hasta ahí ok.

Si después ingresas nuevos datos de ticket, y le das buscar, en ese momento, quitar los íconos de PDF y XML, ya que ni corresponden al ticket buscado, y si confunden un poco.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
negativo...
Cuando has emitido tu primera factura, DEBEN APARECER ESOS ÍCONOS para su descarga. Ahora mismo no aparecen.
Si a partir de que ya has emitido una primera factura, quieres capturar otra... al capturar un nuevo ticket, o nuevo importe o darle buscar el nuevo ticket, en ese momento sería apropiado borrar esos íconos, pero antes no, ya que como está ahora, no hay forma de descargar las facturas... jaja

**Comment by jccastillo0007** [comment]
done

ayer se me olvidó subir la última versión que generé al server..
