### ISSUE TITLE
Factura al instante - no están llegando las facturas generadas por correo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1714]
cuando se captura el RFC, nombre, correo y uso, ya se indica precisamente el correo al que deben llegar.
Aquí es obligado que lleguen por correo. 
Pero no están llegando.

No se si sea porque el emisor, no tiene en la plataforma ninguna cuenta de correo configurada.
Configura alguna.

**Comment by jccastillo0007** [comment]
es porque el emisor tiene que tener configurada la opción de enviar siempre al emisor y receptor..

**Comment by RigoFlores** [comment]
Pues si tiene ambas opciones puestas, y de todos modos no llega.

Comenté que es probable que sea porque esa llave de pruebas ( XIQB891116QE4) no tiene definido ningún correo.

**Comment by jccastillo0007** [comment]
done..

faltaba darle de alta un correo al emsior en la tabla de clientes

**Comment by RigoFlores** [comment]
chiaaa... lo dije desde el primer comentario....
