### ISSUE TITLE
factura al instante - cuando se captura mas de un ticket, borra datos de rfc, nombre y correo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1715]
ya mantiene el uso del CFDI.
Pero sigue borrando el rfc, nombre y correo, cuando se agrega un ticket  a la factura.
Si subimos la captura de los tickets arriba de la sección de rfc, nombre y correo, pues con eso creo que estaría resuelto.

ahora mismo, por el orden de la pantalla, esto es un issue.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
ok, ya está, pero igual, me sigue pareciendo que para agregar mas tickets, está en lugar incorrecto, dentro del flujo de captura....
primero se capturan todos los tickets, o primero los datos del receptor.... pero no entremezclados...

de hecho estaría chido, primero los datos del receptor, para que los tickest y totales, queden juntos...
