### ISSUE TITLE
DescargaT - Generación de CFDI - no puedo generar facturas de abastos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1716]
Me pide la fecha como obligatoria, y además también el RFC del emisor, y ahí no aparece el rfc de pruebas de abastos, es decir...XIQB891116QE4.

La fecha no debe pedirla, y el rfc del emisor, pues si no hay de otra, por lo pronto que lo elijan de ahí, pero hay que darlo de alta en la lista.

Lo que se puede hacer para no romper con otras búsquedas, es que si capturan la fecha entonces que la incluya en el cueri, en otro caso que no la tome en cuenta.

**Comment by jccastillo0007** [comment]
ya puedes hacer pruebas, tiene el mismo comportamiento que factura al instante
