### ISSUE TITLE
Factura al instante - cambiar el orden de captura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1717]
para que tenga coherencia el proceso de captura... creo que quedaría mejor...
a) primero datos fiscales...
b) búsqueda de tickets...

así la captura de tickets se va reflejando en los totales... creo que es mas coherente...

hoy tenemos: búsqueda de 1er ticket - datos fiscales receptor - mas tickets

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
hoy capturé nuevamente tickets,  y no es nada intuitivo...
1) primero aparecen los cuadros del RFC receptor, ticket, total y fecha... ahí solo con capturar ticket y total, ya lo encuentra...
2) si deseas agregar mas tickets, tienen que hacerlo en ooootras casillas donde, se capturará el id ticket y total, igual que arriba, pero sin presentar las otras cajas de texto...

no se puede quedar solo en la segunda sección, es decir que solo pida al inicio ticket y total???
ya se que para otros clientes quizás sea necesario agregar el rfc o incluso la fecha, pero esos cuadros solo deberían ser mostrados cuando el ticket mas el total, TENGAN MAS DE UN RESULTADO, es decir que se repita esa combinación, en ese caso, pues ya se podría pedir que capturen el RFC Y/O FECHA.... no crees que esa ya sería la solución de raíz???

<img width="503" alt="tickets" src="https://user-images.githubusercontent.com/2912775/87838635-45654580-c85d-11ea-8b7c-d7270a4ebca0.PNG">

**Comment by RigoFlores** [comment]
ahora mismo, el ticket ya tiene asociado un RFC emisor cuando se guarda... ya sea para matstore, para abastos, o si se genera desde eFacturaT... entones ese dato, se podría pedir solo en caso que se repita la combinación ticket - total.

Que se mostrara una ventana adicional, solo en ese caso...

cómo la besibol???

**Comment by jccastillo0007** [comment]
wey... asi nunca vamos a terminar... 

dejame ver que se puede hacer

**Comment by RigoFlores** [comment]
si, lo que no se complique tanto, pero no manches, que no confunda al usuario, la neta es poco intuitivo...

La otra es poner al menos unas leyendas:

Paso 1.- Capture los datos del primer ticket.

Paso 2.- Si es necesario, agregue tickets adicionales a la factura.

Paso 3.- Capture sus datos de facturación.

Quizá eso ayude un poco, sin necesidad de tanto desmadre y cambio...

**Comment by jccastillo0007** [comment]
listo... al final deje simplemente la busqueda original, pero con el botón de agregar, pueden agregar mas tickets, no esta reservado solo para Abastos.. me parece que a mas clientes les puede funcionar... yo hago eso cuando facturo varios tickets de gasolina... entonces creo que nos estabamos metiendo en un problema de gratis...

**Comment by RigoFlores** [comment]
si, a huevo.
Quedó mejor así.
