### ISSUE TITLE
DescargaT - Generación de CFDI, no te indica que ya fue facturado el ticket, sino hasta que le dar facturar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1719]
El comportamiento de factura al instante, está muy bien... esto es, cuando le das agregar ticket, una vez capturado el número de ticket y el total, si éste ya fue facturado, te lo indica....

En descargat no funciona igual, es hasta que le das factura, cuando te dice que ya fue facturado, pero imagina que están capturando una factura con pinchemil tickets, entonces por uno solo, podrían perder toda la captura.

El punto es que al momento de agregar el ticket a la factura, debe indicar si ya fue facturado (si es el caso), es decir, hacerlo igual que en factura al instante.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Si correcto, solo hay que homologar el mensaje donde aplique en FI, o en DT o incluso en FT:
Debe decir:
"Ticket o Remisión ya facturado previamente"

Ahora dice:
"Ticket o Remisión generado previamente"

**Comment by jccastillo0007** [comment]
done
