### ISSUE TITLE
VALIDAR EN LA EN LA PANTALLA ACTUAL DE NÓMINA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#172]
VALIDAR:
-LOS QUE DATOS QUE SON REQUERIDOS
-LONGITUDES MÁXIMAS Y MÍNIMAS DE LOS DATOS CAPTURADOS

**Comment by FraQue0693** [comment]
Estoy analizando dicho requerimiento

**Comment by jccastillo0007** [comment]
Esto ya debe estar desde hace un buen...

**Comment by RigoFlores** [comment]
Opino lo mismo, pero no... acabo de hacer una prueba simple con la longitud mínima del CURP, y no... no lo pasó...

**Comment by jccastillo0007** [comment]
Francisco, puedes implementar todas las validaciones necesarias en la pantalla de nomina.
