### ISSUE TITLE
Factura al instante - te permite facturar un ticket ya facturado, desde descargat

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1720]
Si emites la factura desde descargaT para un ticket cualquiera, y ese mismo ticket lo intentas facturar posteriormente en factura al instante, te permite hacerlo, es decir se puede facturar dos veces el mismo ticket.

Hice la prueba al contrario, es decir, primero emití desde factura al instante y luego intenté volver a hacerlo desde descargaT el mismo ticket, y ahí si funciona bien, es decir no permite generarlo nuevamente

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
OK, solo el mensaje es incorrecto.
Ahora dice que el ticket no existe.
Debe decir que el ticket ya fue facturado

**Comment by jccastillo0007** [comment]
done
