### ISSUE TITLE
Plataforma de autofacturación, ocupa la misma serie para tickets (remisiones) que para factura.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1721]
Creo que las series adecuadas son:

FI .- facturas emitidas desde factura al instante
REM - tickets (remisiones) 
Sin folio o DT .- para las facturas generadas desde el DescargaT o desde el mismo eFacturaT.

Las remisiones no se deben 'eliminar' si ya se emitió la factura, hay que mantenerlas para consulta.

**Comment by jccastillo0007** [comment]
Remisiones con serie REM
Facturas al instante con serie FI
Facturas desde descargat con DT

solo falta resolver lo de no reusar la remision y clonarla, pero ese es otro defecto que me parece ya esta creado
