### ISSUE TITLE
los tickets vigentes, con mas de 60 días ya no se deben poder facturar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1722]
Se les dará a los clientes hasta 30 días para que puedan emitir sus facturas.
Si pasan esos 30 días, esos tickets se deberán poner a un status de tal manera que no puedan ser facturados.

Se pueden pasar a caducos, se pueden agregar a una tabla de tickets caducos, no sé, algo que se pueda consultar y quizás eliminarlos de las consultas.

**Comment by jccastillo0007** [comment]
done... además de que valida la fecha... y no deja facturarlo, le va a poner el estatus de expirada

**Comment by RigoFlores** [comment]
OK, entiendo que la fecha inicial se toma a partir de que se recibió el ticket. Correcto?

Por otro lado, hay forma de probarlo antes de que pasen esos 30 días??

**Comment by jccastillo0007** [comment]
solo alterando la fecha en la base de datos.., asi es como yo lo probé

**Comment by jccastillo0007** [comment]
ya actualicé la validación a 60 días

**Comment by RigoFlores** [comment]
ya está en pro?
Indícame pls que debo modificar para forzar que suceda ... cuál fecha, donde, cómo??
Es decir, el cueri para hacerlo en pru...

**Comment by jccastillo0007** [comment]
hoy lo subo a pro, junto con los otros cambios pedidos.

la fecha a modificar es el campo date de la tabla CFD de cada remisión que quieres forzar

**Comment by RigoFlores** [comment]
oyes, pásame pls el cueri para que pueda consultar las diferentes fechas de los tickets (dejando fuera la hora), para revisar cuáles son estas distintas fechas para este cliente... yo probé con este, pero como si incluye hora, minuto y segundo, pues arroja muchos registros... y solo interesa año, mes y día...


select distinct(date) from CFD where sourceRFC = "AMA131218E12" and serie = "REM";

**Comment by jccastillo0007** [comment]
mas o menos asi

select count(*), DATE_FORMAT(STR_TO_DATE(date,'%Y-%m-%d'), '%Y-%m-%d') day from CFD where sourceRFC = "AMA131218E12" and serie = "REM" group by day;
+----------+------------+
| count(*) | day        |
+----------+------------+
|       12 | 2020-07-21 |
|        8 | 2020-07-23 |
|        1 | 2020-07-24 |
|       39 | 2020-07-27 |
|       37 | 2020-07-28 |
|    31897 | 2020-08-01 |
|       12 | 2020-08-04 |
|   120418 | 2020-08-05 |
|     2202 | 2020-08-06 |
|       78 | 2020-08-08 |
|      130 | 2020-08-10 |
|      275 | 2020-08-11 |
+----------+------------+
12 rows in set, 65535 warnings (0.75 sec)

**Comment by RigoFlores** [comment]
chiaaaaa.... le faltaba el * en el count...
