### ISSUE TITLE
Configurar producción Descarga-T para el RFC - AMA131218E12

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1723]
Es el rfc de la vida rial, para el mercado de abastos

AMA131218E12

ADMINISTRADORA DEL MERCADO DE ABASTOS ESTRELLA SA de CV
AV. LOS ÁNGELES 1000, MERCADO DE ABASTOS ESTRELLA,
SAN NICOLAS DE LOS GARZA, NUEVO LEÓN, CP 66482

recordar que para pruebas, el RFC que ocupamos para este cliente es XIQB891116QE4

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
OK, si ya lo ví.
Hasta donde sé, no hay clientes ocupando esta plataforma de descargaT.
Necesitamos dejar únicamente el RFC nuevo, mas el FOPR681125BQ0, y si quieres el tuyo, para hacer pruebas

Ahora mismo, existen muchos pero solo confunden, ya que creo que no lo están ocupando, o cómo puedo saberlo?

**Comment by jccastillo0007** [comment]
done
