### ISSUE TITLE
Agregar el logo del cliente en factura al instante y en descargaT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1724]
Su logo ya está configurado en producción.

En su defecto, que cuando se presente una condición de error, en el mensaje se incluyan sus datos de contacto.
Lo que quieren ellos (y nosotros aún mas que ellos), es que al presentarse una situación de error, no nos llamen a nosotros, sino que los busquen a ellos.

<img width="156" alt="logoAbastos" src="https://user-images.githubusercontent.com/2912775/88000368-118b5980-cac3-11ea-80be-963bf9088769.png">

**Comment by jccastillo0007** [comment]
Este ticket ya no aplica asi como esta... ya veremos cuando alguien pague la personalización
