### ISSUE TITLE
Facturas emitidas desde FI o DT deben tener status de CxC pagadas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1725]
El status de CxC para las facturas emitidas desde Factura al instante y DescargaT, deben tener el status de CxC como pagadas, ya que de hecho nacen de un ticket pagado.
Ahora mismo la facturas TI no tienen status y DT, son vigentes.

Si me voy a Ventas-Consultas, con la cuenta del emisor, hago una consulta y exporto, me aparece así el resultado dentro del excel:

<img width="835" alt="tickets" src="https://user-images.githubusercontent.com/2912775/88080667-f9f4b500-cb44-11ea-9e38-866e57998123.PNG">

**Comment by jccastillo0007** [comment]
done
