### ISSUE TITLE
FI y DT, ocultar o eliminar sección de impuestos en la pantalla de emisión de facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1726]
Creo en en estas pantallas, no nos es de utilidad. Al receptor de la factura, la verdad es que le valdrá madres ese tema.
Además en DT no se muestran, jaja. En FI si se muestran.
Pero igual, hay que ocultarlos... en CSS sería display: none; (jaja).

<img width="464" alt="ft impuestos" src="https://user-images.githubusercontent.com/2912775/88212520-02b8ba00-cc1d-11ea-84e5-b40e2ca04170.PNG">

<img width="479" alt="fi impuestos" src="https://user-images.githubusercontent.com/2912775/88212536-08160480-cc1d-11ea-96d5-9cb8ee586ac0.PNG">

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
sigue igual FI.

<img width="464" alt="fi impuestos" src="https://user-images.githubusercontent.com/2912775/88307478-9ba90d00-ccd1-11ea-82d9-82985f0c8a8a.PNG">

DT también sigue igual. Lo que está en amarillo debe ocultarse.

<img width="386" alt="dt impuestos" src="https://user-images.githubusercontent.com/2912775/88307944-1a9e4580-ccd2-11ea-91a5-c99fa482d200.PNG">

**Comment by jccastillo0007** [comment]
tiene que limpiar tu cache.. si abres la página en otro browser ya no los vas a ver..

**Comment by RigoFlores** [comment]
lo abrí con 3 distintos navegadores, y ocurre lo mismo.
Vacié el caché del crome, y lo mismo.

**Comment by jccastillo0007** [comment]
donde probaste? aún no lo subo a prod

**Comment by RigoFlores** [comment]
ok, en pru
