### ISSUE TITLE
DT, al generar una factura, no se envía por correo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1727]
No sé porqué no lo envía, y tampoco tiene ningún checkbox, para indicarle que la envíe.
Recuerda que aquí es MUY importante que se envíen las facturas por correo al receptor.

Quizás ponerle los checxbox, para enviar o no la factura al receptor, solo para FT.

Al emisor, no sé si deba enviarla o no... tu cómo vex?
En FI, si se envía a ambos en automático, lo cual en principio está bien.
Solo pensando en pinche mil facturas, al rato nos pedirán que no se envíe al emisor... no sé....

Quizás tanto para FI y DT, tomar la configuración de FT, en cuanto a enviar la factura al emisor.
Y en el caso del receptor, siempre enviarla por correo, tanto FI, como DT.

Cómo la beisbol??

**Comment by jccastillo0007** [comment]
Asi es como debe funcionar, voy hacer pruebas 
"Quizás tanto para FI y DT, tomar la configuración de FT, en cuanto a enviar la factura al emisor.
Y en el caso del receptor, siempre enviarla por correo, tanto FI, como DT."

**Comment by RigoFlores** [comment]
en DT no la envía.
en FI si la envía.
La configuración tiene enviar siempre al emisor y receptor.

**Comment by jccastillo0007** [comment]
ya hice varios ajustes y pruebas y ya están llegando bien
