### ISSUE TITLE
Conector Remoto - Abastos, en caso de error, no mueve el archivo de texto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1729]
Y se queda ciclado, reintentando con el mismo archivo....  hasta que se cierra la aplicación, entonces es que ya libera al archivo, porque mientras está ciclado no lo puedes mover de carpeta.

De hecho probé con el archivo anexo.... tiene 6 tickets incluidos.
El ticket tercero y sexto, están mal, el total está con letra en lugar de con número...

El resultado en la plataforma, es que ingresó los primeros 3 tickets... los 2 primeros bien, y el tercero (que está mal en el archivo), lo ingresó con un total de 0.0... los tickets 5° y 6° que están buenos ya no los envió a la plataforma...

Lo que se esperaría, es que si procese bien los que están correctos, y los que están mal, que los reporte en el log... 
en el ejemplo del archivo de texto, interrumpió el procesamiento, aún cuando si existían registros correctos..

[ejemploVariosError.txt](https://github.com/jccastillo0007/eFacturaT/files/4962011/ejemploVariosError.txt)

**Comment by jccastillo0007** [comment]
esto no esta implementado... al encontrar un error termina el proceso

**Comment by RigoFlores** [comment]
ok, pero en el caso del archivo que te envié, lo procesó a medias... y por otro lado, guardó un registro chueco en el servidor...

esto se tendría que evitar un poco, con la validación de los registros del archivo, hay un issue levantado para ello

**Comment by jccastillo0007** [comment]
encontré porque no movía el archivo.. ya esta corregido junto con las validaciones... 

lo que puede pasar en este escenario, es que los primeros registros si se enviarán al server, y en cuanto exista un error ya no..
tendrían que validar que registros si se enviaron y cuales no... lo bueno es que en el log de errores, se muestra la línea que causo el error
