### ISSUE TITLE
COLOCAR TODOS LOS MENSAJES DE NÓMINAR AL INICIO DE LA PANTALLA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#173]
DADO QUE LOS BOTONES DE EDICIÓN, PREVIEW, GENERAR RECIBO, ETC, ESTÁN EN LA PARTE SUPERIOR, COLOCAR CUALQUIER MENSAJE AL USUARIO, INCLUSO CUANDO SE GENERÓ EL RECIBO EXITOSAMENTE, IGUAL EN LA PARTE SUPERIOR DE LA  PANTALLA.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
HICE LA PRUEBA GENERANDO UN RECIBO NORMAL, Y LA DESCARGA DE ARCHIVOS SIGUE APARECIENDO HASTA ABAJO.
DESPUÉS FORCÉ A UN ERROR, QUITANDO EL NÚMERO DE EMPLEADO QUE ES OBLIGATORIO, Y DESPUES DE GUARDAR, EL MENSAJE DE ERROR LO MANDÓ HASTA ABAJO TAMBIÉN

**Comment by jccastillo0007** [comment]
Los errores se van a mostrar arriba, pero los archivos no creo que se puedan Mover hacia arriba, esta funcionalidad esta en el erp

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
Revisar bien el tema de la descarga, ya que el botón de timbrado está hasta arriba, y cuando ya regresó del proceso de timbrado, simplemente desaparecer el registro en cuestión, pero no se indica nada. El usuario tiene que ir hasta abajo por los archivos.
