### ISSUE TITLE
Conector remoto - Abastos - validar archivo de texto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1730]
En un archivo de texto, cada registro debe contar con 4 campos. Validar:

C1. (clave producto SAT)  Que contenga 8 dígitos (no aplican otros caracteres)
C2.  (concepto) Que contenga al menos un caracter, el que sea
C3.- (total) Que sea un número mayor a 0
C4.- (id ticket) Que sea un alfanumérico
C5.- Es la fecha, no sé que pasa si no se incluye... por lo pronto no se valida nada.

Si algún registro no cumple, no se envía al servidor y se incluye en el log de errores.

Esto nos ahorrará muchas llamadas de soporte y tiempo.

**Comment by jccastillo0007** [comment]
done, solo en el caso del punto 2 y 4, en realidad solo se valida que no estén vacíos.

**Comment by RigoFlores** [comment]
si ya vi, en el ID ticket no valida que sea alfanumérico, solo que venga o no venga....
Yo creo que lo dejamos pendiente, pero si será necesario validarlo...
