### ISSUE TITLE
Conector remoto - Abastos , ignorar la fecha del archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1732]
Ahora mismo, si no se incluye la fecha, no procesa el archivo, lo marca como error.

Si la fecha no la ocupamos para validar el ticket, debemos ignorar ese campo.
Si necesitamos una fecha, para dar caducidad a un ticket, podría ser la fecha de recepción del ticket en el servidor.

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
subi una nueva versión de facturat abastos

**Comment by RigoFlores** [comment]
ok, ya no se requiere la fecha en el ticket, y la fecha que se tomará para contar los 30 días, será la fecha de recepción del ticket...
