### ISSUE TITLE
FI y DT - Mostrar el número de ticket cuando se agrega a la factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1734]
En FI ya lo mostraba y ahora ya no lo muestra....

<img width="575" alt="tickets" src="https://user-images.githubusercontent.com/2912775/88314291-4fae9600-ccda-11ea-8a1a-ba7d0013605e.PNG">

y en DT, pues también hace falta mostrarlo:

<img width="550" alt="dt" src="https://user-images.githubusercontent.com/2912775/88314423-85ec1580-ccda-11ea-991e-2cc66f975ce4.PNG">

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
muestra un dato distinto al número de ticket, no se de donde lo toma, pero no corresponde al número de ticket.
tanto para FI como DT, es lo mismo,

**Comment by jccastillo0007** [comment]
pues es el número de ticket recibido del conector, tienes un ejemplo

**Comment by RigoFlores** [comment]
lo hacía con la cuenta XI en pru.
Ahora en pro, al parecer está bien
