### ISSUE TITLE
FI y DT, permite agregar el mismo ticket n veces a la factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1735]
Tanto en FI como en DT, si estás capturando una factura, agregas los contenidos de los tickets.
Bueno pues lo que pasa, es que ahora mismo, se permite agregar el mismo ticket a la factura que estás capturando n veces.

Es decir podrías emitir una factura, agregando el mismo ticket 3 veces, por ejemplo.
Así se ve en FI. Lo que está resaltado en amarillo es un mismo ticket, y lo que no está resaltado es otro ticket duplicado.

<img width="561" alt="ti duplicados" src="https://user-images.githubusercontent.com/2912775/88314907-39550a00-ccdb-11ea-80fb-1477fe81ea14.PNG">

**Comment by jccastillo0007** [comment]
fixed

**Comment by jccastillo0007** [comment]
tiene un comportamiento raro.. debo seguir revisando,

**Comment by jccastillo0007** [comment]
ahora si ya esta listo
