### ISSUE TITLE
FI y DT, ya no permite agregar mas de un ticket a la factura 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1736]
Una vez agregado el primer ticket, y cuando se quiere agregar el segundo, aunque en la pantalla indica que si lo encontró, y el mensaje indica que se agregó, lo cierto es que... no aparece en la pantalla el segundo ticket, y además no se sumariza al total... está raro... solo muestra el primer ticket agregado... me refiero a la sección de totales...

**Comment by jccastillo0007** [comment]
anexo evidencia
![Captura de Pantalla 2020-07-24 a la(s) 16 16 35](https://user-images.githubusercontent.com/2245679/88436101-35071a80-cdc9-11ea-8531-58050bd650f5.png)

**Comment by RigoFlores** [comment]
seguramente eso lo hiciste en producción.
pero en el ambiente de pruebas, que es donde yo estoy probando no jala...
donde debo probar???
