### ISSUE TITLE
Conector Remoto - tomar de la llave los datos del emisor, y homologar carpeta de procesados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1737]
Los datos del emisor, tomarlos de la llave, como debe ser siempre.

La carpeta de procesados, para homologar con el conector estándar, debe estar debajo de la carpeta donde se leen los archivos de texto... ejemplo:

CFD\Procesados

Ahora mismo están así:

FacturaT\CFD
FacturaT\procesados
FacturaT\logs
FacturaT\System

**Comment by jccastillo0007** [comment]
done
