### ISSUE TITLE
FI - algunas veces no pone a pagados los tickets, y se pueden volver a facturar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1738]
Envié correo con evidencia.
No logro identificar bien el escenario de falla..
Creo que cuando en la misma sesión de FI, haces una factura tras otra, sucede ello a partir de la segunda factura,  pero no estoy seguro full.

Es crítico, porque imagina que puedan estar facturando y facturando los mismos tickets

**Comment by jccastillo0007** [comment]
ya hice muchas pruebas y esta mas consistente... no encontré un escenario donde no actualizara las remisiones, incluso facturando varias veces en la misma sesión de FI y DT

**Comment by RigoFlores** [comment]
no lo he visto en FT, pero si en FI. Hoy lo volvió a hacer en mi primera prueba....!!!

**Comment by RigoFlores** [comment]
mandé varios correos con evidencias, y en producción, ahora mismo lo hace siempre, para facturas con mas de 1 ticket.

**Comment by RigoFlores** [comment]
pues hice algunas pruebas y ya no se presentó el caso... no sé si ya haya sido corregido con lo que viste...
