### ISSUE TITLE
DT - Ya tienes capturados algunos tickets, e intentas capturar uno ya facturado, borra todo...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1740]
estoy capturando varios tickets, y ya aparecen agregados a la factura.
Si de repente capturo uno que ya está facturado (por error o como sea), manda el mensaje a pantalla, pero borra toooodo lo ya capturado...

Solo debe mandar el mensaje, pero no debe borrar lo ya capturado.

**Comment by RigoFlores** [comment]
también sucede lo mismo cuando tecleas un ticket que no existe... borra todo lo que ya habías capturado...

**Comment by jccastillo0007** [comment]
Este es justo el escenario que provoca que en FI se perdieran las primeras remisiones capturadas y por eso no las actualizaba a pagadas

**Comment by RigoFlores** [comment]
bajo este escenario, los datos del receptor los sigue borrando (los del los tickets los mantiene) y marca error, precisamente de que no tiene datos del receptor...

**Comment by RigoFlores** [comment]
cuando estás capturando una factura en DT, le has agregado o no algunos tickets, pero intentas agregar ya sea un ticket ya facturado o un ticket inexistente, entonces borra los datos del receptor... 
Y ya no los recupera mas, tienes que salirte de esa pantalla y regresar para volver a empezar, perdiendo todo lo ya capturado.

**Comment by jccastillo0007** [comment]
fixed
