### ISSUE TITLE
DT - estas capturando varios tickets, y tecleas uno que ya habías agregado, te borra el botón para facturar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1741]
Te manda el mensaje que ese ticket ya está agregado, pero borra el botón de facturar.
Borra el botón de facturar, y pues ya no hay manera de emitir la factura.
Tendrías que salirte y volver a entrar, pero si es una factura con muchos tickets, imagínate el desmadre...

**Comment by RigoFlores** [comment]
Ya vi, puedes agregar otro ticket y vuelven a aparecer los botones de facturar, pero como quiera si hay que corregir.
Que tal si no quieres agregar mas tickets...

**Comment by jccastillo0007** [comment]
fixed
