### ISSUE TITLE
DT y FI, permitir eliminar tickets agregados a la factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1743]
Si están capturando una factura de muchos tickets, y se equivocan en alguno, deberíamos contar con la facilidad para que lo eliminen. Cómo vex?

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
eso quedó muy bien...
finalmente esta plataforma, la han probado algunos clientes, pero bien a bien, nunca se ha utiilzado formalmente.
Por ello, es hasta ahora que están surgiendo varios detalles como este, para ir depurando su operación, funcionalidad y usabilidad simple.
