### ISSUE TITLE
Agregar videos tutoriales de ayuda, para FI y FT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1746]
Son videos para ayudar en la emisión de las facturas.

FI : https://youtu.be/BckLVasSF4c

FT: https://youtu.be/DgNuKwa9I8M

Para el registro en DT: https://youtu.be/qUspLQB7D-k

**Comment by jccastillo0007** [comment]
no manches, confundes mucho con FT si en realidad es DT

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
si, confundo seguido DT con FT.
Realmente DT debería ser "Plataforma de Autofacturación", esto es PA.
