### ISSUE TITLE
Agregar 2 emisores y un receptor, para emisión del Complemento INE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1748]
No recuerdo si tienes que dar de alta al receptor y al emisor también.
Según yo si, pero como quiera aquí tienes ambos datos.

Como referencia, este cliente actualmente emite con complemento INE MAHP4803129K5, cuyo cliente RFC receptor es PVE930113JS1

Emisores nuevos:
SIC1006295Y8 
SGB151127J47

Receptor nuevo:
MCI990630JR7

**Comment by jccastillo0007** [comment]
esta duplicado con el issue 1747 o cual es la diferencia ?

**Comment by RigoFlores** [comment]
es el mismo... ya me ha pasado en un par de ocasiones en la última semana, que genero un nuevo ticket o lo actualizo o lo reabro, y no se refleja en el listado de issues abiertos... cierro, vuelvo a abrir y no lo hace.
Entonces procedo a generarlo nuevamente para asegurarme...
