### ISSUE TITLE
Conector Remoto Abastos - quitar validación de número de folios temporalmente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1749]
Como te comenté, ahora ellos tienen blocks de tickets con los folios repetidos, pero no así con el total.
Lo que acordé es por lo pronto, que no valide el número de folio. El asegura que el total NO se repetirá.
Una vez que entren en circulación sus boletas con folios irrepetibles, ya no se repetirán los números de folios, ya que les agregarán unas letras a dichos tickets.

Ahora, surgió oooootro problema, que ya es viejo desde hace mucho, motivo de desacuerdos. Resulta que cuando haces una factura de un ticket,, por ejemplo la DT-1, le asignó un ID 221634. Pues al momento de tratar de cargar ese ticket NO lo permite, dice que ya existe.

En conclusión, 
1) el deber ser, sería validar número de ticket + total, que no se repita en REMISIONES ya cargadas. Por lo pronto podríamos eliminar la validación del número de ticket y que pasen todas. Mas adelante regresaríamos a la versión que valida el número de ticket.
2) Cuando queremos cargar los tickets, NO se debe validar vs el ID de una factura... no veo el porqué....son cosas y números distintos. En todo caso, debe validar el número de ticket contra los ID de las remisiones, no contra las facturas.
3) El ID de una factura, al ponerlo como la HHMMSS, se queda muy corto. Aún así, agregándole las milésimas, (que en algún momento se supone que se les agregó y no se porqué ya no lo maneja), es suceptible a que se repitan. Quizás agregarle las milésimas y la serie o que se yo, algo que sea menos vulnerable.

**Comment by jccastillo0007** [comment]
lo subi a pru y pro... hay que hacer varias validaciones para ver que no falle por otra cosa... el cambio de no validar los tickets duplicados, impacta en varios lados...
