### ISSUE TITLE
Generar 3 tipos de nómina distintos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#175]
Se requiere una vez al año generar la nómina para utilidades PTU y Aguinaldos.
A como está ahora mismo, tendrían que borrar su registro que ocupan todo el año y capturar uno que solo se ocupará una vez.
Hay que estudiar la forma de hacerlo

**Comment by jccastillo0007** [comment]
Done.

Ahora puedes habilitar y deshabilitar percepciones, deducciones, horas extras e incapacidades... con esto se permite capturar el aguinaldo por ejemplo, pero manternerlo deshabilitado, y solo habitliarlo en la nomina de diciembre.

**Comment by RigoFlores** [comment]
Tendremos que considerarlo como una solución temporal.
El tema es que tanto la nómina de PTU como Aguinaldo, ocupan deducciones como por ejemplo ISR al menos. Entonces, el usuario tendría que modificar tooooodos sus registros.
Y finalmente tendrían que entrar a todos y cada uno de los empleados, para deshabilitar todas las percepciones y deducciones que no apliquen para las nóminas especiales.
Hay que pensar en otro esquema.

**Comment by jccastillo0007** [comment]
No maaa fue bien complicado hacer esto, esto fue lo que nos retraso casi una semana, lo bueno es que se puede reutilizar para activar o desactivar desde la pantalla general de nomina

JC@iPhone.
 Saludos.
