### ISSUE TITLE
FI y FT - no permite agregar tickets con el mismo ID en la factura (con distinto total)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1750]
Si tienes varios tickets con el mismo número, e intentas agregarlo a una factura, no permite hacerlo.
Te dice que el ticket ya fue agregado a la factura.

Ticket o Remisión ya capturada

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
en pro sigue igual

**Comment by RigoFlores** [comment]
en pru, ya permite agregar a la factura (DT y FI), el mismo ticket con distinto importe.

Lo malo, es que ahora permite incluir el mismo ticket... es decir el mismo ticket-importe, lo puedo repetir n veces sin problema...

**Comment by jccastillo0007** [comment]
ya lo subi a prod... pero no logré arreglar ese error raro...ma;ana le seguiré

**Comment by RigoFlores** [comment]
pues si, sigue igual...

**Comment by jccastillo0007** [comment]
ya por fin quedo bien... checale en PRU

**Comment by RigoFlores** [comment]
ok, al parecer ya quedó... hay que llevarlo a pro....
ellos no tienen detectada esta falla, pero se les puede presentar.. incluso al receptor, le conviene que así se comporte el sistema...
