### ISSUE TITLE
FI - no encuentra un ticket, pero en DT si lo ubica

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1751]
En producción se trata del ticket 98, cuyo total es 98.80.
No se si por la fracción, en FI no lo encuentra cuando lo busco.
En DT lo encuentra sin problemas.

El 98 es un ticket ya repetido varias ocasiones; todas las anteriores ya fueron facturadas. Es producción.

**Comment by jccastillo0007** [comment]
si logra encontrarlo... se tarda un rato.. y esto también nos pega mucho en el performance de la app, posiblemente mas que la recepción de pinche mil remisiones, necesitamos que ya nos paguen la customización para poder ajustar la búsqueda por su rfc.

![Captura de Pantalla 2020-08-06 a la(s) 22 59 27](https://user-images.githubusercontent.com/2245679/89607756-df0a8c00-d838-11ea-91e1-0f1c198048d2.png)

**Comment by RigoFlores** [comment]
no lo hallaba, decía remisión no encontrada... lo hice varias veces... lo bueno es que ya está corregido
