### ISSUE TITLE
Producción Web - Mandar el tipo de cambio a 4 o 6 decimales al Jasper

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1752]
En el XML se manejan hasta 6 decimales en el tipo de cambio, pero al pdf solo llegan 2, entonces no se muestra completo...
Incluso, podrían enviarse esos 6 decimales, solo en el caso que la moneda sea distinta a MXN.

**Comment by RigoFlores** [comment]
otra cosa, en pantalla dentro de catálogo de monedas... redondea a 3 decimales en pantalla, pero en el XML envía hasta 6 decimales.
Creo que se debe manejar de manera homologada 6 decimales en XML, en pantalla y en el PDF.

**Comment by jccastillo0007** [comment]
ya se modificó en jasper para el PDF.
para el catálogo de monedas, el campo esta configurado como double, mostrará los decimales que tenga el valor sin ajustarlo a 3 o 6, has visto que le ponga 0  a la derecha hasta llegar a 3 decimales?

**Comment by RigoFlores** [comment]
lo que vi, es que por ejemplo 21.1234, lo pone como 21.123.... es decir redondea a 3 decimales.
Cuando es cero la fracción, que eso solo pasaría con MXN no sé.
El tipo de cambio tiene relevancia en monedas distintas al peso.
Por lo pronto, si ya está bien en el PDF, y en el XML... pues ni hablar, si en pantalla no se puede mostrar igual, pero si lo está considerando, pues así nos vamos...

**Comment by RigoFlores** [comment]
listo en pru
