### ISSUE TITLE
DT - está validando la fecha, cuando es mayor a la fecha de carga

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1754]
Si por error capturas la fecha en los campos de captura, un ticket no lo encontrará si capturan una fecha mayor a la fecha de ingreso del ticket.

Ejemplo:
ticket ID: del 312230 al 312239 (cualquiera de ellos, tienen mismo total, misma fecha de carga)
Total: $150.00
Fecha de carga al sistema: 10 de agosto...

Si ellos capturan una fecha menor o igual al 10 de agosto, si encuentra el ticket, peeero si capturan una fecha del 11 de agosto en adelante, no lo encontrará...

Se requiere eliminar o ignorar esa validación.

**Comment by jccastillo0007** [comment]
fixed, lo subi directo a pro
