### ISSUE TITLE
Dar de alta la addenda ARA - Retención fondo de garantía

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1755]
Ya envié un correo con toda la info.
Receptor:
CONSORCIO DE INGENIERIA INTEGRAL SA DE CV
RFC: CII770127MA2

Emisor:
DISTRIBUIDORA LAMARO S.A. DE C.V.
RFC : DLA090826L62

Son 3 requisitos en uno:

a)	Implementar la addenda
b)	Enviar info de la addenda al PDF
c)	El mismo CFDI, incluirá el complemento de servicios parciales de construcción, así que hay que ver que puedan convivir juntos. Ya revisé y este complemento se captura como si fuera addenda, entonces ahora cómo le vamos a hacer????

Es una addenda muy simple (incluye 3 datos únicamente), aquí tienes la liga del XSD, así como un ejemplo. El pedo creo yo, podría ser que convivan los dos, complemento y addenda.

http://201.148.157.232:81/Content/FondoGarantia/AddendaFondoGarantia.xsd

          <cfdi:Addenda>
                    <FondoGarantia:AddendaFondoGarantia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:FondoGarantia="http://201.148.157.232:81/Content/FondoGarantia" version="1.0" xsi:schemaLocation="http://201.148.157.232:81/Content/FondoGarantia http://201.148.157.232:81/Content/FondoGarantia/AddendaFondoGarantia.xsd">
                              <FondoGarantia:FondoGarantia Descripcion="ADDENDA RETENCION FONDO DE GARANTIA 5%" PeriodoEnMeses="12" Importe="6813.41"/>
                    </FondoGarantia:AddendaFondoGarantia>
          </cfdi:Addenda>

**Comment by jccastillo0007** [comment]
ya vi que paso
 tenemos un problema, el sistema esta preparado para expedir solo un complemento o addenda por emisor y por receptor...

ahorita tenia ligado el complemento de construcción y el fondo de garantia al receptor y por eso no funcionaba, tengo que ver como darle la vuelta a eso...

una opción es ligar la addenda de fondo de garantia al emisor, pero lo malo es que si llenan los datos de la addenda, podría estar generando la addenda sin que se requiera...

otra opción es ligar el complemento de construcción y la addenda fondo de garantía para que siempre se incluyan ambas para el cliente CII... pero no sé si sea el caso

cómo ves

**Comment by RigoFlores** [comment]
Chiaaaa... pues por eso comenté en el punto c que se ocupaban complemento y addendas juntos en el mismo XML.... eso hace 5 días.

Yo no le daría tantas vueltas... ya lo comenté...
En un solo XML de configuración de addenda/complemento: los primeros 3 datos son los de la addenda y el resto son los del complemento, es decir los que tienen actualmente. 
Por default, los datos de la addenda van vacíos siempre en ese XML, y si la capturan, entonces la addenda se incluye, si alguno de los 3 campos está vacío, entonces eso indica que la addenda fondo de garantía NO se debe incluir. Lo del complemento funcionaría tal cual funciona hoy mismo.

Si no le dan click a la opción de addenda, pues no se incluye ni complemento, ni addenda.

**Comment by jccastillo0007** [comment]
listo, puedes probar con el usuario TCM... ya tiene cargado los tres datos de la addenda, al final.

Si no incluyen los tres datos, no genera la addenda

**Comment by RigoFlores** [comment]
el receptor indicado, es al que le facturarán con complemento y con addenda, eso si jala.
Si no capturas la addenda, no la incluye, eso también jala.

Lo que no jala, es que si quieren incluir el complemento de servicios parciales de construcción, A CUALQUIER OTRO CLIENTE, ya no lo incluye. Quedó amarrado a un solo RFC.

El complemento DEBE FUNCIONAR COMO ANTES, esto es, que se pueda incluir para cualquier cliente.

Solo se agregó un receptor para la addenda, incluyendo el complemento.

De hecho, un funcionamiento total de esta solución, es que si NO CAPTURAN EL COMPLEMENTO, PERO SI LA ADDENDA, solo incluyera la addenda. Esto por lo pronto no lo ocuparemos, pero lo que si, es que debe jalar el complemento para cualquier cliente.

**Comment by jccastillo0007** [comment]
hay que usar este xml para ambas cosas complemento construcción y addenda fondo garantía.. 
campos del 1 al 11 son del complemento
campos del 12 al 14 son de la addenda y son mandatorios los tres para la generación


[CFDi2AddConstruccionAndFondoGarantia.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/5100550/CFDi2AddConstruccionAndFondoGarantia.xml.txt)

**Comment by RigoFlores** [comment]
ahora dejó de incluir la addenda.
NO la incluye en ningún caso, ni para RFC's que están dentro de la lista de receptores del complemento de servicios parciales de construcción, ni para los que no lo están.
Si incluye el complemento, solo para los RFC's correctos. Pero la addenda ya despareció.

**Comment by RigoFlores** [comment]
seguimos con este problema entonces...

**Comment by jccastillo0007** [comment]
hmmm este problema sigue... estoy confundido, si ya lo entregaste no?

**Comment by jccastillo0007** [comment]
quedamos en que voy a agregar un botón de OK en la pantalla de los datos extras... pero eso es un ticket diferente

**Comment by RigoFlores** [comment]
el tema aquí, es que no siempre incluye la addenda, recuerdas?
A mi me pasó varias veces, al cliente le pasó cuando emitió su única factura.
Lo que en teoría detectamos, es que no estaba tomando los datos capturados. Por eso íbamos a agregar el botón OK, o que la ventana cambiar su background color... para que nos indicara el momento en que ya tomó los datos capturados...

Eso es lo que esperamos, porque para propósitos prácticos, no jaló lo de incluir la addenda.

El cliente pagó, pero no pudo generar su addenda.

**Comment by jccastillo0007** [comment]
y apoco no reintento ? ya debio generar la factura, no manches

como quiera voy agregar el botón ok o hacer lo del background y probamos... por cierto, yo nunca pude reproducir ese error, siempre que ingresé los datos necesarios, si me generaba la addenda

**Comment by RigoFlores** [comment]
la factura se la generé yo desde el conector, tuve que poner un ambiente para hacerla... chiaaaaa....
si comentaste que nunca te falló a ti... y a mi me falló casi siempre... a ella le falló la única ocasión que lo intentó...

tu ocupas chrome??

**Comment by jccastillo0007** [comment]
ya agregué un botón de Save en la pantalla modal de addenda y datos extras
Puedes checar si eso resuelve el tema de los datos de addenda que no pasaban, según ustedes..

creo que no abriste otro ticket para eso verdad

**Comment by RigoFlores** [comment]
no, pues no ha quedado la addenda... jeje... todo es lo de mismo...
A ver, mi prueba número 1 en pruebas, fue quitar los datos de la addenda y dejar solo los del complemento... el resultado fue XML mal formado... esto se debe a que NO INCLUYÓ UN SOLO DATO DEL COMPLEMENTO... únicamente los namespaces y schemas y esas cosas... pero datos propiamente del complemento NO. Tons pues esto ya es ooootro problema para agregar a lo que ya existía... jeje

    <cfdi:Complemento>
        <servicioparcial:parcialesconstruccion xmlns:servicioparcial="http://www.sat.gob.mx/servicioparcialconstruccion" Version="1.0" xsi:schemaLocation="http://www.sat.gob.mx/servicioparcialconstruccion http://www.sat.gob.mx/sitio_internet/cfd/servicioparcialconstruccion/servicioparcialconstruccion.xsd">
            <servicioparcial:Inmueble/>
        </servicioparcial:parcialesconstruccion>
    </cfdi:Complemento>

**Comment by RigoFlores** [comment]
prueba número 2, capturé los 3 datos de la addenda y luego de darle tabulador y al final click en save, el resultado fue el mismo que el anterior...

    <cfdi:Emisor Rfc="TCM970625MB1" Nombre="Usuario de pruebas de nomina 1.2" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="CII770127MA2" Nombre="CONSORCIO DE INGENIERIA INTEGRAL, SA DE CV" UsoCFDI="G03"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="01010101" NoIdentificacion="TEST" Cantidad="1.00" ClaveUnidad="E48" Unidad="SERVICIO" Descripcion="PRODUCTO DE TESTEO" ValorUnitario="100.000000" Importe="100.000000">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="100.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="16.000000"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="16.00">
        <cfdi:Traslados>
            <cfdi:Traslado Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="16.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
    <cfdi:Complemento>
        <servicioparcial:parcialesconstruccion xmlns:servicioparcial="http://www.sat.gob.mx/servicioparcialconstruccion" Version="1.0" xsi:schemaLocation="http://www.sat.gob.mx/servicioparcialconstruccion http://www.sat.gob.mx/sitio_internet/cfd/servicioparcialconstruccion/servicioparcialconstruccion.xsd">
            <servicioparcial:Inmueble/>
        </servicioparcial:parcialesconstruccion>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by RigoFlores** [comment]
necesitamos hacer en conjunto las pruebas, tal parece que cada quien hace cosas en escenarios totalmente distintos...

**Comment by jccastillo0007** [comment]
Lo bueno, ya pude reproducirlo con las pruebas que pusiste arriba.

Lo malo, NPI de porque no traslada los valores

**Comment by jccastillo0007** [comment]
haber checale, creo que ya quedo...

Ahora el botón de guardar, guarda los datos, pero no cierra la ventana modal... hay que cerrarla directamente con la X

Si todo va bien, ma;ana veo como cerrar la ventana modal automáticamente

**Comment by RigoFlores** [comment]
pues el escenario de falla, ya te lo describí.
Primero capturo una factura, SIN addenda ARA, es decir le quito los últimos 3 datos. Lo hace bien, es decir, solo incluye el complemento.
Segundo, sin salir de la pantalla de facturación, ahora capturo la factura ya con datos de addenda y al XML timbrado no le incluye la addenda.
Revisé el catalina del caso de falla, y si te das cuenta, si aparecen capturados como datos extra los datos de la addenda, peeero pues no la está incluyendo. Aquí tienes la evidencia de la falla...

[catalina pru.txt](https://github.com/jccastillo0007/eFacturaT/files/5279319/catalina.pru.txt)


algo importante, es que si la primera factura es la que capturas con addenda, si la incluye.

Es decir, SI HAY UN TEMA QUE NO ESTÁ LEYENDO O TOMANDO CORRECTAMENTE LOS DATOS CAPTURADOS EN LA PANTALLA. Aquí ya quedó demostrado....

**Comment by jccastillo0007** [comment]
hay que tener una sesión de pruebas... acabo de seguir tus escenarios de prueba descritos arriba, y si me funciono las dos veces... hay algo que sucede durante el proceso que no estamos identificando

Ahora por otro lado... tu escenario de prueba de arriba, se contradice , primero dices:

Primero capturo una factura, SIN addenda ARA, es decir le quito los últimos 3 datos. Lo hace bien, es decir, solo incluye el complemento.
Segundo, sin salir de la pantalla de facturación, ahora capturo la factura ya con datos de addenda y al XML timbrado no le incluye la addenda.
Revisé el catalina del caso de falla, y si te das cuenta, si aparecen capturados como datos extra los datos de la addenda, peeero pues no la está incluyendo. Aquí tienes la evidencia de la falla...


y luego dices 

algo importante, es que si la primera factura es la que capturas con addenda, si la incluye.

Entonces ya no supe si la primer factura debe o no llevar addenda... lo peor es que , en ambos casos si me funciona

**Comment by jccastillo0007** [comment]
las últimas 5 o 6 facturas, las hice tratando de reproducir el problema... me funciono bien...

**Comment by RigoFlores** [comment]
jaja... finalmente el tema del orden de captura... y el tipo de datos...
descripción - string
período.- entero
importe - flotante

**Comment by RigoFlores** [comment]
Ahora, algo que ocupa el cliente, y es que tenga la opción de que en el XML se pueda incluir:
a) Solo el complemento
b) Solo la addenda
c) Ambos

El problema, es que se ocupa un solo XML, para los dos.
Ahora mismo, si no capturan los 3 últimos datos, no incluye la addenda. Pero siempre incluye el complemento.
Entonces, cómo le hacemos para que incluya solo la addenda sin complemento?
Sería que los primeros 11 datos vayan vacíos? O inclusive con que vaya vacío el primero, entonces significa que los primeros 11 datos serán ignorados y NO se incluirá el complemento, pero si se capturan los últimos 3 datos, entonces incluye la addenda.
Si me expliqué? Para el complemento se ocupan los primeros 11 datos y para la addenda los últimos 3 datos. Es decir, son 14 datos en total. Si no capturan el dato 1, entonces ignorar los primeros 11 datos. Y si los últimos 3 datos están capturados, entonces implica que solo quieren capturar la addenda sin complemento.

**Comment by jccastillo0007** [comment]
ya agregue el checkbox para el complemento de construcción, pero no me dio tiempo de probarlo... ya vencio el certificado del cliente TCM ... jajaja igual que el mio

**Comment by RigoFlores** [comment]
y cómo debe funcionar?
Si no se da click en el checkbox y además se capturan los 3 datos de la addenda, entonces solamente se incluye la addenda???

**Comment by jccastillo0007** [comment]
asi es... además de tener todos los datos del complemento, deben seleccionar el checkbox... para la addenda funciona igual que antes, depende de los últimos tres datos
