### ISSUE TITLE
Problemas con el esquema continúan, ahora para leyendas fiscales.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1757]
te pondré lo del correo aquí...

Tenemos desde la semana pasada problemas con el tema de los esquemas.
Todo esto a raíz me parece, que cambiamos algo para soportar dos complementos/addendas en un mismo XML para el cliente, distribuidora lamaro.

Bueno el punto aquí es el siguiente, marca error de los esquemas.
La forma de reproducirlo es:

a)	Te sales y entras a la plataforma para hacer la factura por primera vez. Si te quedas en la pantalla de facturación, y sigues haciendo facturas, no presentará error, y tampoco incluirá el complemento de leyendas fiscales.
b)	El rfc receptor, puede ser sergio javier garcia garza. Todo lo demás con los datos por omisión.
c)	El producto puede ser TARIMA TRIPLAY - TARIMA DE TRIPLAY 6mm. (CONTRACHAPADA) 37X34X4. Le pones 10 pesos de precio unitario. Hasta ahí todo normal.
d)	Enseguida eliges lo de incluir leyendas fiscales.
e)	Enseguida capturas datos extra, para pedimento, firma y orden de compra. Le das cerrar.
f)	Puedes darle vista previa o no
g)	Luego le das facturar y se generará el error que anexo en el archivo de texto…

Es importante el paso a, porque después de un error, ahí me quedé reintentando y no generó el error, pero tampoco incluía la leyenda de datos fiscales.
Este es uno caso mas del tema de error en el esquema.

[leyendasfiscales.txt](https://github.com/jccastillo0007/eFacturaT/files/5190995/leyendasfiscales.txt)

**Comment by jccastillo0007** [comment]
tengo que probar el producción ? chiaaa en pru no puedo reproducirlo

**Comment by RigoFlores** [comment]
no estoy seguro como reproducirlo en pru... este rfc emisor tiene algo especial en producción.. HEWP6607093B9 ?
Quizás está asociado a algún complemento o addenda o algo... eso puede hacer diferencia...
Voy a intentar reproducirlo en pru... pero según yo, debería tener los plugins idénticos al rfc que tiene el problema en pro

**Comment by RigoFlores** [comment]
Algo que se implementó para este RFC, es lo de IMMEX, que está documentado en el issue 1642.
Me parece que tratar de reproducirlo en pruebas, requiere algo mas que simplemente hacer la factura, ya que el tema este de leyendas fiscales IMMEX, está bien super a la medida...

**Comment by jccastillo0007** [comment]
fixed.
