### ISSUE TITLE
Error del esquema desde el conector (con retenciones y receptor tridonex)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1758]
Ya lo habíamos platicado antes. 
Se trata del conector estándar.
Envías un archivo de texto, CON RETENCIONES DE IVA O ISR, pero además el receptor es un RFC de tridonex... que en este caso no requiere addenda, pero el receptor es el de tridonex. No se incluyen los datos de la addenda.
Con ello, se genera el error del esquema.

Aquí te estoy anexando el archivo de texto, que genera el error... es decir ya incluye todo lo necesario para reproducir el problema.

[errorEsquema_CFD_A_5457.txt](https://github.com/jccastillo0007/eFacturaT/files/5191022/errorEsquema_CFD_A_5457.txt)

Creo que la solución comentada, fue que se valide para incluir la addenda tridondex, que se incluyan los datos necesarios para incluirla. Si no vienen, simplemente no se incluye. No estoy seguro que eso solucionaría el problema, pero puede ser que si.

**Comment by jccastillo0007** [comment]
para la addenda tridonex, solo se ocupan dos datos extras a nivel producto, ninguno a nivel general...
PO y Número de Identificación.

efectivamente se estaba generando aún cuando no se incluían los datos extra a nivel producto... 

La solución es, solicitar ambos datos a nivel producto, para generar el item de tridonex correspondiente a ese producto.
Después de procesar todos los productos, si se tiene al menos 1 registro completo en la addenda tridonex, si se genera, de lo contrario no se generaría.

esta bien ?

Por cierto. Este posible escenario siempre había existido.

**Comment by jccastillo0007** [comment]
subí la versión 11.0.1 de facturat para  resolver este issue

**Comment by RigoFlores** [comment]
descargué esa versión última... (la de ayer)... y ejecuté en pru con el archivo que te mandé... sigue incluyendo el esqueleto o parte del esqueleto de la addenda... y sigue marcando el mismo error... aquí la salida de la consola...

[errortridonex.txt](https://github.com/jccastillo0007/eFacturaT/files/5203517/errortridonex.txt)

este es el archivo del conector, que provoca el error... ese ya te lo había enviado por correo, pero aquí lo tienes...


[CFD_A_5457.txt](https://github.com/jccastillo0007/eFacturaT/files/5203523/CFD_A_5457.txt)
