### ISSUE TITLE
Habilitar o deshabilitar empleados de nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#176]
algunos clientes dan de baja a los empleados por una o varias quincenas y luego los vuelven a habilitar, sobre todos los empleados eventuales.
Quizás agregar un check botón, de habilitado/suspendido en cada registro.
Al momento de dar click en el botón mágico, solo tomaría los habilitados

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Ya aparece el botón, pero si deshabilito el registro, como quiera genera el recibo.
No estoy seguro si este botón solo funciona con el botón mágico o también debería impedir generar el recibo de manera individual.

**Comment by jccastillo0007** [comment]
Fixed
