### ISSUE TITLE
Permitir subir CFDI tipo pago a la plataforma

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1760]
La intención es que esos CFDI's que suban, los puedan relacionar desde la pantalla de emisión de Documentos de Pago.

Si se complica, dejar un texto donde puedan capturar una o varias UUID's para relacionar.

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
tienes mas cfdi que hay que subir? para probar el tema del tipo de factura

**Comment by RigoFlores** [comment]
no, no tengo mas cfdi's ... el cliente ya los subió.... le pediré otros y te aviso

**Comment by RigoFlores** [comment]
la siguiente semana me enviará algunos... mientras tanto, pues esperaremos antes de cerrar este issue
