### ISSUE TITLE
eliminar botones de save en la pantalla de agregar productos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1761]
No se de donde surgieron nuevos botones save... jajaja
No manches están en pro, hay que eliminarlos...

<img width="686" alt="save" src="https://user-images.githubusercontent.com/2912775/96524490-0cfb4c00-123e-11eb-8597-51da6fb39f62.PNG">

**Comment by jccastillo0007** [comment]
estos si se inyectaron con el botón de save de los datos extras... ya lo tuve que quitar
