### ISSUE TITLE
Generar reporte de recargas - de las últimas 50

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1762]
Es el reporte que genero desde el menú de KeyGenerator - Reporte de folios.
Ahora mismo se genera el "reporte de recargas" y está bien, aunque siento que estresa mucho al sistema generar ese reporte y en la gran mayoría de los casos, solo ocupo los últimos registros de las recargas.

Así que solicito un reporte que únicamente contenga las últimas 50 recargas.
Mantener los reportes actuales, pero agregar el de las últimas 50 recargas. 
El formato de este nuevo reporte, es idéntico al reporte de recargas, pero evidentemente solo las últimas 50 recargas.

**Comment by RigoFlores** [comment]
cada vez se tarda mas la consulta para actualizar las recargas de folios.
Es necesario implementar esta función.
Puede ser un checkbox que solo traiga las últimas 50, o 100. Con eso es suficiente.

**Comment by jccastillo0007** [comment]
aqui te dejo el query que puedes usar:

select * from CFDiFolios order by id DESC limit 100;

el limit 100 lo puedes modificar para ver menos o mas... 

que otra cosa necesitas?

**Comment by RigoFlores** [comment]
pos que genere el reporte... jejeje

**Comment by RigoFlores** [comment]
ya vi, en el cueri falta un campo que es el distribuidor... lo ocupo para saber cuántos folios deben los socios comerciales

**Comment by RigoFlores** [comment]
de hecho los campos que se ocupan son:

Distribuidor
fecha de carga
recarga o nuevo (cuando el rango inicial es 0, es nuevo, en otro caso es una recarga)
número de folios cargados
nombre
RFC

ese cueri es el que se ocupa con los últimos n registros.

**Comment by RigoFlores** [comment]
select date, fin_range, ini_range, emisor from CFDiFolios order by id DESC limit 100;

a este cueri le falta el nombre y distribuidor, que según entiendo están en la tabla Client (name y reseller) respectivamente.

**Comment by jccastillo0007** [comment]
select a.id, a.emisor, b.name, b.reseller,  a.ini_range, a.fin_range, a.status, a.date, a.dateOfIssue, a.current_folio from CFDiFolios a, Client b where a.emisor = b.rfc and b.owner = 'FacturaT' order by id DESC  limit 100;

**Comment by RigoFlores** [comment]
justo había terminado de juntar la información, chiaaaa...
