### ISSUE TITLE
La cadena original del PDF, está incorrecta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1763]
Esto sucedió entre el día 03 (OK) y el día 07 (ya incorrecto) de septiembre.
Después del UUID, viene la fecha y luego el RFC del PAC... esto es lo correcto, es decir así:

<img width="809" alt="cadena correcta" src="https://user-images.githubusercontent.com/2912775/96633290-8b0f2f80-12de-11eb-9384-4364ebe097ba.PNG">

Pero ahora muestra la fecha en un formato incorrecto y además ya no coloca el RFC del PAC, sino que repite el UUID, de esta manera:

<img width="821" alt="cadena incorrecta" src="https://user-images.githubusercontent.com/2912775/96633352-9d896900-12de-11eb-82d1-d335843661a2.PNG">

**Comment by jccastillo0007** [comment]
listo... 
ya lo probé en web en test, y lo subí a pro...
puedes checar en standalone

**Comment by jccastillo0007** [comment]
subi un release 11.0.5 de standalone para probar

**Comment by RigoFlores** [comment]
pero en escritorio, creo que no existía problema, que corrige?

**Comment by jccastillo0007** [comment]
si, es el mismo problema porque cambiaron el complemento de timbre fiscal, y de ahi se origino este problema

**Comment by RigoFlores** [comment]
ok
