### ISSUE TITLE
Conector Optibelt - factura CFDI en EUR, pero con CCE se debe reportar en USD

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1764]
Hoy en día soportamos para optibelt, facturas con CCE, donde el CFDI estándar puede ir en MXN o USD, sin pedos.

Pero ahora surge el tema de hacerlo en EUROS, o de hecho cualquier otra moneda con CCE.
Lo que se necesita, es dar de alta la clave de esa moneda con su tipo de cambio. Por ejemplo EUR: 24.00
También se ocupará la moneda USD con su tipo de cambio.

Y el CFDI estándar se reportará en la moneda de EUR con su tipo de cambio, y el CCE se reportará en USD con su respectivo TC.

lo que hay que hacer, es un cálculo intermedio, de acuerdo a la siguiente imagen:

<img width="260" alt="EUR A USD CCE" src="https://user-images.githubusercontent.com/2912775/97628197-fd27f880-19f1-11eb-88c6-7c25a373a9cf.PNG">

**Comment by jccastillo0007** [comment]
siempre no van a incluir los datos en el archivo de texto?, ya se acordó como va a funcionar?

**Comment by RigoFlores** [comment]
Entonces lo que hay que atender, cuando se requiera emitir CFDI en moneda distinta a USD y que incluya el CCE, es lo siguiente:

1) La factura estándar, va con la moneda que se indique y con el tipo de cambio correspondiente.
2) Con CCE, que siempre reporta en USD, con el tipo de cambio que ellos capturen, y que debe ser el publicado el día anterior en el DOF.

OK, pero para el caso de que la moneda sea EUR por ejemplo, hay que convertir el EUR a USD para reportarlo en el CCE.
Y se hace con la operación arriba indicada:

Para el CCE, el Precio Unitario =  PU en EUR *  (TC EUR  / TC USD)

**Comment by jccastillo0007** [comment]
puedes subir archivos de prueba y un ejemplo de cómo debe generarse el xml?

**Comment by jccastillo0007** [comment]
los tipos de cambio los capturan en el catálogo de monedas?

**Comment by RigoFlores** [comment]
El tipo de cambio de EUR y USD, se capturan en la pantalla de catálogo de monedas de Factura-T escritorio.
Para lograr que timbre un CCE, el tipo de cambio debe ser el que aparecen el día de ayer en el DOF. En este ejemplo, los tipos de cambio con cumplen con esa regla, pero para el ejemplo están bien.


Aquí tengo un ejemplo del txt, y de cómo debería salir el XML.
Al XML que generó, le modifiqué en la sección del CCE CCE CCE CCE

* la cantidad del producto (no sé porqué le puso 20 en lugar de 10; al parecer esto es un bug)
* El precio unitario = precio unitario CFDI estándar * TC EURO / TC USD = 102.62 * 22 / 20 = 112.88
* El valor en dólares = precio unitario * cantidad = 112.88 * 10 = 1128.80

[CCE_USD-EUR.txt](https://github.com/jccastillo0007/eFacturaT/files/10788646/CCE_USD-EUR.txt)
[xmlCCE-EUR-USD.txt](https://github.com/jccastillo0007/eFacturaT/files/10788647/xmlCCE-EUR-USD.txt)

**Comment by jccastillo0007** [comment]
Esto se resuelve con el ticket 2107 ?

**Comment by RigoFlores** [comment]
Vamos a atender esto, en otro issue.
