### ISSUE TITLE
En nómina, cuando el nodo de percepciones está deshabilitado, no reportar el atributo correspondiente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1767]
Resulta que para regresar ISR cuando se retuvo de mas en el ejercicio anterior, existe un tipo en "Otros Pagos", pero va solo. Sin percepciones, ni deducciones (aparentemente). Se trata de otros pagos - Reintegro de ISR pagado en exceso o quizás también de otros pagos-Reintegro de ISR retenido en exceso de ejercicio anterior (siempre que no haya sido enterado al SAT).

Entonces, bajo este escenacio no se debe reportar a nivel header el atributo "TotalPercepciones".
Creo que es mas complicado validar cuál es el tipo de otros pagos que se capturó, pero si sabemos cuando percepciones está deshabilitado en pantalla, entonces... creo que esa sería la solución... cuando esté deshabilitado ese nodo en la pantalla, pues no reportar el atibuto indicado.

Este es el error que arroja.

 El atributo Nomina.TotalPercepciones, no debe existir.

**Comment by RigoFlores** [comment]
Any new?

**Comment by jccastillo0007** [comment]
oye, y si el total percepciones es = 0, entonces no se reporta nada cierto? o hay casos en los que si se reporta ?

**Comment by jccastillo0007** [comment]
por ahora esta validando que si el total de percepciones es 0, entonces no agrega ese header, pero ahora salen otros errores propios del tipo otros pagos... para que los cheques...

nom226 : TipoRegimen es igual a 02, por lo tanto, el valor del atributo OtroPago.TipoOtroPago debe ser 002 y no deben existir los valores 007 y 008 en el atributo OtroPago.TipoOtroPago. (3)

Por otro lado, al momento de generar el XML, ya no se sabe si el componente percepciones del UI estaba o no deshabilitado, solo se conoce que las percepciones están vacías, si hay casos en los que si hay que incluir el total percepciones = 0, entonces si debemos hacer la validación con el tipo de Otros Pagos...

**Comment by RigoFlores** [comment]
Por lo pronto, lo podemos dejar así.
En teoría las percepciones no pueden ser = 0.
Pero el deber ser, es que si está deshabilitado el nodo de percepciones, entonces no incluir el atributo correspondiente.
