### ISSUE TITLE
Reportar la tasa de impuesto local, tal cual se captura en el campo cantidad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1768]
Hablamos del producto cuyo ID = ImpLocal. En este caso, se trata como impuesto local y se reporta así en el XML:

            <implocal:RetencionesLocales ImpLocRetenido="5 AL MILLAR INSPECCION  Y VIGILANCIA" Importe="1484.19" TasadeRetencion="0.5"/>
 
La TasadeRetención se captura en la cantidad, al momento de agregar el "producto". Todo funciona bien, excepto que no reporta la tasa, tal cual se capturó, es decir, en el ejemplo de arriba se capturó como 0.50, pero lo reporta como 0.5
Se necesita que lo pase de manera literal, tal cual se captura.
Todo lo demás, no moverle nada.

<img width="640" alt="implocal" src="https://user-images.githubusercontent.com/2912775/107550597-d784c080-6b96-11eb-80e2-cbd8fcbf11fe.PNG">

**Comment by jccastillo0007** [comment]
hay un problema, ya vi porque no respecta los 0 a la izq, ese campo es numérico desde la pantalla, y desde ahi se pierde...

lo que puedo hacer es validar, que si solo trae un decimal, que le ponga el 0, pero eso puede romper otros casos...

lo voy a hacer y subir a prod, para que ese cliente pueda facturar, y ya vemos si le doy para atrás,

**Comment by jccastillo0007** [comment]
hice una prueba y funcionó lo del 0.50, pero siguio marcando xml mal formado

<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:implocal="http://www.sat.gob.mx/implocal" Version="3.3" Serie="A" Folio="290" Fecha="2021-02-11T22:40:52" Sello="ENcNZufYnX2d/GRyQ5T0QYf4R15VdVn+y9VUvIl81DqGjRHnpv0k7xRIh42xhEB5sCeC4rpRGJ4iYA1N2GY8RiCthqvPVcuoWBkcb30cyTShcCCfV1zhQqFXI+8ILBs+/DJhUAFC/IgSbRTli4Hk6wIS2aCO4FHyjwQ1odcT53a/PWVEaJOpDeuwf1DQyV8CiYBb2oDTWvXUaz+UpKnmN/UR6Uv7nBqbm5Ftv2xNp+ZrRxJ9Cfx5tT9Ru6zPxM5w88OVTPY2HRob+fedpWiPrODinG3btAVBvv8JSIq/HKHmCn/X6lhO+AqqJog80aamPtXvbJtAHS4xg/jRYLuCiw==" FormaPago="03" NoCertificado="00001000000505625827" Certificado="MIIF/TCCA+WgAwIBAgIUMDAwMDEwMDAwMDA1MDU2MjU4MjcwDQYJKoZIhvcNAQELBQAwggGEMSAwHgYDVQQDDBdBVVRPUklEQUQgQ0VSVElGSUNBRE9SQTEuMCwGA1UECgwlU0VSVklDSU8gREUgQURNSU5JU1RSQUNJT04gVFJJQlVUQVJJQTEaMBgGA1UECwwRU0FULUlFUyBBdXRob3JpdHkxKjAoBgkqhkiG9w0BCQEWG2NvbnRhY3RvLnRlY25pY29Ac2F0LmdvYi5teDEmMCQGA1UECQwdQVYuIEhJREFMR08gNzcsIENPTC4gR1VFUlJFUk8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQQ0lVREFEIERFIE1FWElDTzETMBEGA1UEBwwKQ1VBVUhURU1PQzEVMBMGA1UELRMMU0FUOTcwNzAxTk4zMVwwWgYJKoZIhvcNAQkCE01yZXNwb25zYWJsZTogQURNSU5JU1RSQUNJT04gQ0VOVFJBTCBERSBTRVJWSUNJT1MgVFJJQlVUQVJJT1MgQUwgQ09OVFJJQlVZRU5URTAeFw0yMDExMDYxNzQwMThaFw0yNDExMDYxNzQwMThaMIHLMSUwIwYDVQQDExxKVUFOIENBUkxPUyBDQVNUSUxMTyBBTFZBUkVaMSUwIwYDVQQpExxKVUFOIENBUkxPUyBDQVNUSUxMTyBBTFZBUkVaMSUwIwYDVQQKExxKVUFOIENBUkxPUyBDQVNUSUxMTyBBTFZBUkVaMRYwFAYDVQQtEw1DQUFKNzUwNjA3MlAyMRswGQYDVQQFExJDQUFKNzUwNjA3SERGU0xOMDIxHzAdBgNVBAsTFkJvc3F1ZXMgZGUgU2FudGEgQW5pdGEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC9AF4EBehtF1iXhdAMprFP2g7khdtRqH4YYMrZFicYpCkFpxm493A61QjnVR6L9dJwg6QC0AhvexnmUEsYhC3wHil69MPMLmLVv1Xu5z+2VyyMdHzMTeKlGbjWvb6pQEc5AkUpR6XjuQHcsrRJwaMJCBu3mlF3Qc2+SeE/fh0vOKfo6IK+T+6RnUgLVVTX4Tk0UIiJGwXygntw2JHdcnHt6enA4ByTvSdB+/vcwHUekFUSLmKFRoW2HuqAwVCRR12XFvPgV2SGc1fqE/wNFDRR3oSCRtHMvFmCDW3FbvtISHL/d2QLalH6Rn3Dpq8voAI2uXm8JYlEWNwfpF6SToT/AgMBAAGjHTAbMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgbAMA0GCSqGSIb3DQEBCwUAA4ICAQAlOQXh1YFacaeoQS+r5iFgtUNqTNb+I2hIG8H55TlHIMOZUwGJl72UTHMTkUj9lyX3DnEDRCnZ1PrzzHNFeZ7eD6rpl9iDn6XZDXg4MNdTNwPBcSwiQruLw7/vf73ULA1ZUqZv33D+dNogE+fVFXHqg3s+XWlOaFFayV0peVEChMuUfvpOUGz5yLd2XFMhebQDZo8+Cu14+9eN7h6kRm3+iz53kyDJBhEB4gzwi4dk0SAbpPKmFmx9c260yCOOTzjYXk5FmXaiBH7Ggd7Ja5LUyKjZEw85UGKA4eBXOUGlUr9H/jI5uS3jt9Wo38iJj6huEr+J9mQdPGO2JipAiWZ/z3VT+rvaqV6+AuRHHJWb00isDa7sldCoiHO5NQTIlLd98CHKwXlpRudWukYO6q/o6brn3hrt5pfGr5h/nYXuiK0S4wolPyowrU0xGhO4ywDxctZhbsNUnqIh9oYEWlBHgCMpVSxN9jfEn6VuQugzVyyj9oX9STMANMji+QCMx4Robn+0g8bQbFdA7QAkpQQ+4VteYZ7mHyrhCHgXtP/6fm1OM/26hM76r0bCzA4xiHqP+J5zX1fHElctB0TcxwrDETZLd3hBvBtywIax+afGgTl3d4HkNMiH1kYs8+agoCKopFesBPRYW0H8Nve3Ib4Myrclisxf6C0YbWsSyUV+yw==" SubTotal="0.00" Moneda="MXN" TipoCambio="1" Total="-10.00" TipoDeComprobante="I" MetodoPago="PUE" LugarExpedicion="45645" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/implocal http://www.sat.gob.mx/sitio_internet/cfd/implocal/implocal.xsd">
    <cfdi:Emisor Rfc="CAAJ7506072P2" Nombre="Juan Carlos Castillo Alvarez" RegimenFiscal="612"/>
    <cfdi:Receptor Rfc="XAXX010101000" Nombre="Público en General" UsoCFDI="G03"/>
    <cfdi:Conceptos/>
    <cfdi:Complemento>
        <implocal:ImpuestosLocales TotaldeRetenciones="10.00" TotaldeTraslados="0.00" version="1.0" xsi:schemaLocation="http://www.sat.gob.mx/implocal http://www.sat.gob.mx/sitio_internet/cfd/implocal/implocal.xsd">
            <implocal:RetencionesLocales ImpLocRetenido="Tax JC" Importe="10.00" TasadeRetencion="0.50"/>
        </implocal:ImpuestosLocales>
    </cfdi:Complemento>
</cfdi:Comprobante>

se me hace que ese no era el problema

**Comment by jccastillo0007** [comment]
esta es la razón de que no lo timbro finkok en pru

XMLSyntaxError(u"Element '{http://www.sat.gob.mx/cfd/3}Comprobante', attribute 'Total': [facet 'minInclusive'] The value '-10.00' is less than the minimum value allowed ('0.000000').",)

asi que tal vez mi prueba no fue del todo buena, checa si funciona con el cliente

**Comment by RigoFlores** [comment]
ok, entonces está en producción, para hacer la factura del cliente...

**Comment by RigoFlores** [comment]
ya la hice y quedó.
Si acaso el detalle que le veo al guorkarraun, es que si se captura una tasa con 3 decimales pues ya valió madres... jeje
