### ISSUE TITLE
En menú de Nómina-Recibo de Nómina, agregar el siguiente banco al listado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1769]
La lista se estará actualizando con el tiempo, pero bueno, por lo pronto agregar este banco a la lista:

**_Sistema de Transferencias y Pagos (STP)._** 

La otra opción, es dejarlo de libre captura, aunque no se si nos traiga mas problemas.

**Comment by jccastillo0007** [comment]
se ocupa un id del banco... algo como esto :

BANAMEX("BANAMEX", "002")
BANCOMEXT("BANCOMEXT", "006")

**Comment by RigoFlores** [comment]
OK, así aparee en el catálogo:

646 | STP | Sistema de Transferencias y Pagos STP, S.A. de C.V.SOFOM ENR

lo que pides quedaría así: 

STP("STP", "646")

**Comment by jccastillo0007** [comment]
done
