### ISSUE TITLE
CUANDO NO EXISTEN DEDUCCIONES CAPTURADAS EN NÓMINA, NO GENERA PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#177]
cuando no capturas deducciones (que si es un caso de la vida rial), no genera correctamente el pdf.  lo que sucede, es que no envía las percepciones al pdf.

**Comment by jccastillo0007** [comment]
Fix it

**Comment by RigoFlores** [comment]
perdón, no es que no generaba el pdf, sino que no muestra las percepciones capturadas. 
Sigue igual, no las muestra.

**Comment by jccastillo0007** [comment]
fixed.
