### ISSUE TITLE
Nómina conector - no está calculando correctamente el atributo totalSueldos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1770]
En el conector, cuando se emite un recibo de nómina, para el nodo de Percepciones, existe un atributo o parámetro que se llama totalSueldos.

La spec dice:

El valor de este atributo debe ser igual a la suma de los atributos ImporteGravado e ImporteExento donde la clave expresada en el atributo TipoPercepcion **sea distinta** de 022 Prima por Antigüedad, 023 Pagos por separación, 025 Indemnizaciones, 039 Jubilaciones, pensiones o haberes de retiro en una exhibición y 044 Jubilaciones, pensiones o haberes de retiro en parcialidades.

El cliente está generando un recibo por indemnización, es decir cuya clave es 025. Sin embargo en total sueldos NO NO NO debe considerar el gravado y exento para esa clave. Tampoco para las otras claves mencionadas. 022, 023, 025 y 039.

Este es el archivo de texto que no puede procesar... con este se puede validar que se corrige...

[nominaSergio.txt](https://github.com/jccastillo0007/eFacturaT/files/6133651/nominaSergio.txt)

**Comment by jccastillo0007** [comment]
entonces esto es desde conector .

corri una prueba y me salio esto 
CFDI33131 : La clave del campo RegimenFiscal debe corresponder con el tipo de persona (fisica o moral)

**Comment by jccastillo0007** [comment]
pasame un archivo con el que me pueda enfocar al error del total sueldos

**Comment by jccastillo0007** [comment]
ok, se omiten para la suma de total sueldos, las percepciones con esta clave: 
022 Prima por Antigüedad
023 Pagos por separación
025 Indemnizaciones
039 Jubilaciones, pensiones o haberes de retiro en una exhibición
044 Jubilaciones, pensiones o haberes de retiro en parcialidades

**Comment by jccastillo0007** [comment]
ya vi que pasaba... resulta que la validación que se solicita aqui, ya estaba implementada... pero se tomaba en cuenta la clave de la percepción y no el tipo de percepción... por ejemplo, en el archivo de pruebas tenemos estas percepciones.

nominaPercepciones=
{002|061|Aguinaldo|546.11|275.81|HorasExtra[|||]},
{025|075|INDEMNIZACION|53752.50|0.00|HorasExtra[|||]}

El primer campo es el tipo de percepción y el segundo campo es la clave de percepción... para efectos de esta validación la clave de percepción es 061 y 075, por eso si los sumaba todos, pero en realidad se debe tomar el tipo de percepción, 002 y 025, y ya con eso no toma en cuenta la segunda percepción con 025

Por otro lado, una vez que cambie eso, marcaba error en el campo totalPercepciones a nivel del complemento de nómina, el cual también ajuste para que coincidiera.

Estos son cambios delicados, no sé porque no se había identificado antes, capaz que casi nadie lo usa o capaz que algo cambio el Sat, total que espero no se rompan otros casos de uso.

**Comment by jccastillo0007** [comment]
subi el zip 11.0.6 para tus pruebas

**Comment by RigoFlores** [comment]
OK, ya veo el tema.
Lo que sucede es que una es la clave del SAT (la primera), y otra es la clave de uso interno del cliente (la segunda).
Nosotros siempre debemos guiarnos en las claves del SAT, no podemos asumir que el cliente utilizará las mismas claves que el SAT defina. Al final, en las pruebas se pasó validar esta condición.
Por eso no había aparecido antes, ya que para las pruebas, ambas claves eran iguales.

El total de percepciones no tenía que haber variado, pero supongo que ahora no sumaba las percepciones de las claves arriba mencionadas, si eso ocurría, entonces había oootro problema.

OK, valido y te comento.

**Comment by RigoFlores** [comment]
La parte de totalSueldos ya quedó resuelta, pero ahora se descompuso cuando el régimen es asimilados. Tanto en el conector, como en el web.

**Comment by RigoFlores** [comment]
En el nodo receptor, cuando el régimen del receptor sea 05, 06, 07, 08, 09 o 10  (que es cualquiera correspondiente a Asimilados), no se deben incluir los datos que se indican:
Tanto en el web como por el conector, está marcando el mismo error. Incluso en web, cuando no se han capturado datos de esa sección (ver imagen). Desde siempre,  la pantalla se menciona que esos datos solo aplican para sueldos y salarios (clave 02)... no estoy seguro que solo apliquen para ello, pero lo que si estoy seguro, es que NO aplican para los regímenes arriba mencionados.

Lo raro es que marca error en el conector, y también en web.

<img width="723" alt="nomina" src="https://user-images.githubusercontent.com/2912775/111383421-ce8f7f00-866d-11eb-95c8-84ee1a4ce1b3.PNG">

**Comment by RigoFlores** [comment]
La pantalla de arriba, corresponde a pru, con el rfc emisor XI.
Lo que intentó timbrar es lo siguiente, si te das cuenta le está incluyendo el parámetro de riesgo, aún cuando no se capturó.

<img width="947" alt="nomina" src="https://user-images.githubusercontent.com/2912775/111383662-24642700-866e-11eb-9afa-874aa7d55a68.PNG">

**Comment by RigoFlores** [comment]
En el caso del conector para asimilados, si en el archivo NO se incluyen los datos que se necesitan, marca error, que no se incluyen los datos suficientes. 
En caso que si se incluyan esos datos, pues los intenta colocar en el XML y el SAT lo rechaza, digamos que igual que en web.

**Comment by RigoFlores** [comment]
Este archivo no incluye los datos que no se ocupan en asimilados, y no lo procesa porque dice que le faltan datos.

[asimilados.txt](https://github.com/jccastillo0007/eFacturaT/files/6152447/asimilados.txt)

**Comment by RigoFlores** [comment]
aquí está el archivo con el layout de nómina...

[Layout Nomina.txt](https://github.com/jccastillo0007/eFacturaT/files/6153257/Layout.Nomina.txt)

**Comment by jccastillo0007** [comment]
ya mezclaste dos defectos

**Comment by RigoFlores** [comment]
ok, considera por lo pronto el del conector.

Abriré otro para el web, pero es lo mesmo, según yo.

**Comment by RigoFlores** [comment]
lo que pasa, es que traté de ver cómo lo debía generar en el conector, y para ello me apoyé en el web, y me di cuenta que estabn igual, pero por lo pronto hay que ver lo del conector.

**Comment by jccastillo0007** [comment]
bueno pues si entendi bien, ya quedo arreglado tanto en conector como en web.

para conector subi el release 11.0.7
para web, subi un release a pru... lo probé con el cliente XIQ y con el primer empleado, tuve que deshabilitar otros pagos

nada tenía que ver con los cambios previos... una de dos, o ningún cliente nuestro ha usado esta funcionalidad, o el sat se puso ya mas estricto y esta validando estos detalles.

**Comment by RigoFlores** [comment]
OK, ya quedó resuelto lo del original de este issue.
Y lo otro también, solo que se debía a que el PAC ahora si, estaba aplicando las validaciones y anteriormente no lo hacía.

Lo que quedará, es que el cliente del conector, modifique su layout, cuando se trate de asimilados, ya que no debe incluir los datos que solo aplican para sueldos y salarios. Si los incluye, entonces si marcará el error.
