### ISSUE TITLE
Migrar Clientes y Productos de esta BD de escritorio hacia la plataforma en línea

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1771]
Aplica para este RFC: DOMS701126PS7

[facturat_db.zip](https://github.com/jccastillo0007/eFacturaT/files/6157765/facturat_db.zip)

**Comment by RigoFlores** [comment]
casualmente esta otra BD también hay que migrar...para este otro RFC EES930324DC4

[facturat_db.script.zip](https://github.com/jccastillo0007/eFacturaT/files/6160145/facturat_db.script.zip)

**Comment by jccastillo0007** [comment]
done...

Baje las llaves del servidor.

**Comment by RigoFlores** [comment]
Oye, no se pasó la clave del SAT ni la unidad. De la unidad, daré de alta las unidades estándar, pero no sé que pasaría si tiene alguna que no exista en las tablas de cada cliente.

Hoy me traeré otra BD que también pidieron que se migre.

**Comment by RigoFlores** [comment]
Aquí ya está la oootra BD para migrar. Clientes y productos.
Adentro del zip, va su licencia de escritorio.

[facturat_db_TAR090317GQ7.zip](https://github.com/jccastillo0007/eFacturaT/files/6337782/facturat_db_TAR090317GQ7.zip)

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Di de alta las unidades idénticas a como las tienen en su BD del escritorio y si las jala.
Lo que no quedó en el catálogo de los productos de las 3 BD, es la clave de producto SAT.
Esta vacía para todos los productos de los 3 RFC's.

**Comment by jccastillo0007** [comment]
hay que restablecer eso por query, quieres que lo haga yo o ya sabes como ?

**Comment by RigoFlores** [comment]
lo hice a manopla, ya está.
