### ISSUE TITLE
Ajustes personalizados en Web para cliente AUGM651103SPA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1772]
Se requiere de varios ajustes.

En la pantalla de facturación. precargar estos valores por omisión:
Forma de Pago: 99. Por definir
Método de pago: PPD

En la ventana de agregar el producto, que cargue por omisión los impuestos retenidos:
IVA: 10.667%
ISR: 10%

Hoy se muestra así:

![image](https://user-images.githubusercontent.com/2912775/114067117-131fcc00-9862-11eb-9603-11ad1bfc86aa.png)

Se requiere que en automático cargue estos impuestos retenidos. Tener cuidado cuando se tengan mas de 2 impuestos retenidos definidos.

![image](https://user-images.githubusercontent.com/2912775/114067292-47938800-9862-11eb-8b7b-7ef8fe94aebc.png)

**Comment by jccastillo0007** [comment]
ya subi un release a pru... ya aplica todo lo necesario, peeeero en la pantalla de productos, no se ven bien los impuestos retenidos, pero si los agrega, y el total es correcto, solo es un tema visual...

**Comment by RigoFlores** [comment]
para este issue, el cliente pide que se regrese el default en estos 2 puntos (pagará por el roll back):

forma de pago: transferencia electronica de fondos
método de pago: PUE

**Comment by RigoFlores** [comment]
Ahora si ya,  este  cliente pide que se regrese el default en estos 2 puntos (pagará por el roll back):

forma de pago: transferencia electronica de fondos
método de pago: PUE

**Comment by jccastillo0007** [comment]
done, en pru.

Avísame si lo subo a pro
