### ISSUE TITLE
Conector para el carta porte - revisar el tema de cancelación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1773]
Ya hemos entregado el conector con varios ajustes, particularmente el cambio en la estructura y nombre de carpetas cuando es multiconector, y finalmente también se cambió el nombre del archivo PDF y XML.

Ahora lo que falta asegurar es la cancelación, al menos desde el esquema de poner el XML timbrado en la misma carpeta de los archivos planos, ya que ahora mismo, aparentemente si cancela, pero no genera los acuses y el XML timbrado, lo mueve a la carpeta de "reintente mas tarde" en lugar de procesados. Algo tiene ahí la aplicación.

**Comment by jccastillo0007** [comment]
según esto si esta funcionando correctamente la cancelación... intenta cancelar y marca que no existe el xml... no sé si se pueda probar en producción para ver cual es el error

**Comment by RigoFlores** [comment]
Si, en producción se probó.
Puse el XML ya timbrado en la carpeta del conector. Estaba vigente en el SAT
Despues de procesarlo, mandó este mensaje a la consola:

2021-04-09 12:04:29,188 DEBUG [pool-2-thread-1] (Connector2Cancel.java:74) - Propety received : STATUS_PAC value : Cancelaci├│n enviada al SAT satisfactoriame
nte  Estatus : En proceso Estado CFDi : Vigente
2021-04-09 12:04:29,193 ERROR [pool-2-thread-1] (Connector2Cancel.java:83) - Error en proceso de cancelaci├│n : 011 description : Cancelaci├│n enviada al SAT
satisfactoriamente  Estatus : En proceso Estado CFDi : Vigente

Lo que entiendo es que todo funcionó correctamente, pero aún así la aplicación marca un error.
Después de esto, revisé el XML en el SAT y ya está cancelado. Así que pues algo tenemos chueco por ahí.

El problema son varios puntos:

a) No genera acuse de cancelación en la carpeta PDF y XML que corresponde
b) Mueve el XML a la carpeta "reintentar mas tarde" en lugar de moverla a la de procesados
c) En la consola, marca error en proceso de cancelación, cuando realmente SI envió a cancelar.

Este es el facturat.log de producción, por si te sirve.

[FacturaT.log](https://github.com/jccastillo0007/eFacturaT/files/6287435/FacturaT.log)

**Comment by jccastillo0007** [comment]
fixed.

Estaba esperando estatus de cancelado, y no validaba correctamente el estatus de enviado a cancelación... 

subi el release 11.0.7

**Comment by RigoFlores** [comment]
Si, ya genera el acuse y envía a cancelar.

Peeeeero, en este caso del carta porte, el acuse lo debe colocar en la misma carpeta donde se encontraba la factura.
Recuerda que para estos 2 RFC's ( CCR730127PD4 y TRA891031SXA ), la estructura de carpetas se basa en:

mesAño\Serie\PDF
mesAño\Serie\XML

Para el resto de clientes, el acuse si se debe almacenar en la ubicación estándar, esto es:

mesAño\PDF
mesAño\XML

o para el caso de los otros multiconectores:

mesAño\RFC\PDF
mesAño\RFC\XML

**Comment by jccastillo0007** [comment]
done... pero no lo probé porque no puedo cancelar.

**Comment by RigoFlores** [comment]
Lo probé en producción... sigue colocándolo en la carpeta estándar, esto es:

<img width="382" alt="cancela" src="https://user-images.githubusercontent.com/2912775/115060779-e6953100-9ead-11eb-9bc0-733391a90a0c.PNG">

Peeeero para el tema del carta porte y sus 2 RFC's específicos, y sus ajustes a la medida, debería colocarlos en:

<img width="480" alt="cancela2" src="https://user-images.githubusercontent.com/2912775/115061023-34119e00-9eae-11eb-9687-452bd7b6138f.PNG">

Para el resto, está bien donde los coloca ahora mismo.

**Comment by jccastillo0007** [comment]
ya esta funcionando la cancelación cierto?

**Comment by RigoFlores** [comment]
si está funcionando para el conector estándar.
No estoy seguro que en modo multiconector trabaja igual, pero ya lo veremos en su momento si es que se requiere.
