### ISSUE TITLE
Conector Carta Porte, cambiar uno de los dos RFC's emisores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1774]
Tenemos el conector carta porte multi emisor, que está configurado para estos 2 RFC's:

CCR730127PD4
TRA891031SXA

con los ajustes para las carpetas donde se almacenan los PDF y XML (por serie), además del nombre de los archivos (sin la hora al final).

El cambio que se requiere, es que en lugar de CCR730127PD4, se configure este otro rfc  **ATC900122NU0**.

**Comment by jccastillo0007** [comment]
done
