### ISSUE TITLE
Complementar el Complemento INE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1775]
Hoy en día, tenemos implementado el happy path, esto es solo incluímos el header del complemento y un nodo + subnodo que es opcional, no lo desarrollamos.
Pero resulta que ese nodo al parecer no es opcional, sino es CONDICIONAL.

Esto es, cuando el parámetro TipoProceso es igual a Campaña o Precampaña y tipo de comité diferente de  Ejecutivo Nacional, entonces se debe agregar el nodo de Entidad, Con los datos de ClaveEntidad, Ambito, y Contabilidad.

Este es el xsd del Complemento, para mayor información.

http://www.sat.gob.mx/sitio_internet/cfd/ine/ine11.xsd

Para probarlo, yo lo haré con estos datos.

A nivel header:
Tipo de Proceso: Campaña
TipoComite: Ejecutivo Estatal
IdContabilidad: solo aplica cuando Tipo de Proceso = Ordinario y tipo de comité = Ejecutivo Nacional. En otro caso, la contabilidad se reporta en el nodo entidad. Para probar en este caso, no aplicaría. 

A nivel nodo Entidad:
ClaveEntidad: QUE
Ambito: Local
Subnodo Contabilidad: 75192

Algunos parámetros dicen que son condicionales. Yo lo que haría es enviarlos solo en el caso que se capturen, para que se tenga esa flexibilidad. Si se captura el dato del header, nodo o subnodo, que se incluya, en otro caso no.

O tu me dices como queda?

Hoy el XML solo incluye los datos del header Anexo ejemplo). Le faltarían los datos del nodo entidad (que son 2), y el dato del subnodo contabilidad (que pueden ser varios). Nosotros podemos hacerlo solo para uno, pero no se si mas adelante tengamos necesidad de incluir mas.

[PAN400301JR5_Addenda.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/6338547/PAN400301JR5_Addenda.xml.txt)

**Comment by RigoFlores** [comment]
La batería de pruebas, para lo que hoy ya tenemos implementado, es:

                <field>
                        <tag>proceso</tag>
                        <name>Tipo proceso</name>
                        <type>STRING</type>
                        <length>20</length>
                        <value>Ordinario</value>
                </field>
                <field>
                        <tag>comite</tag>
                        <name>Tipo Comité</name>
                        <type>STRING</type>
                        <length>20</length>
                        <value>Ejecutivo Nacional</value>
                </field>
                <field>
                        <tag>contabilidad</tag>
                        <name>Id Contabilidad</name>
                        <type>STRING</type>
                        <length>20</length>
                        <value>308</value>
                </field>

**Comment by RigoFlores** [comment]
Para probar lo que hoy ya tenemos jalando y no le vayamos a partir su mami, aqui tienes los datos con los que se puede probar, son solo 3, y son los que van a nivel header:

Tipo proceso: Ordinario
comite: Ejecutivo Nacional
contabilidad: 308

**Comment by jccastillo0007** [comment]
Listo... alcance a implementarlo, se ve sencillo para un solo nodo de entidad... creo que mencionaste que podían ser varios.. pero ahorita solo se agrega una entidad.

Los datos extras deben venir 6 en total, si falta alguno ya no se agrega.

del 1 al 3 son los que ya tienes en el archivo, del 4 al 6 son

4. ClaveEntidad: QUE
5. Ambito: Local
6. Subnodo Contabilidad: 75192

debe ser en ese orden y el primero debe ser en mayúsculas y coincidir con el catálogo de entidades que viene en el schema

el segundo no importa si esta en mayúsculas o minúsculas

checale y me dices... solo esta en PRU

**Comment by jccastillo0007** [comment]
aunque no sé como lo vas a probar

**Comment by RigoFlores** [comment]
Ya lo probé, y cuando es estatal, la contabilidad del header no aplica. Entonces no se la capturé, el campo estaba vacío.
Aún con ello, SI la está reportando con un 0... así de esta manera:

<cfdi:Complemento>
        <ine:INE **IdContabilidad="0"** TipoComite="Ejecutivo Estatal" TipoProceso="Campaña" Version="1.1">
            <ine:Entidad Ambito="Local" ClaveEntidad="QTO">
                <ine:Contabilidad IdContabilidad="75192"/>
            </ine:Entidad>
        </ine:INE>
    </cfdi:Complemento>

**Comment by RigoFlores** [comment]
Según yo, si no se incluye ese parámetro de idContabilidad, entonces ya lo aceptaría.
Probé que lo anterior del complemento siguiera jalando y si, lo hace sin problema.

**Comment by jccastillo0007** [comment]
arregle varios detalles y validaciones que faltaban, el enum de tipo entidad no lo tenía actualizado...

actualmente ya genera el xml con complemento, pero primero dice que el tipo proceso = campana o precampa;a no debe existir, y si se lo quito , dice XML mal formado

        <ine:INE TipoComite="Ejecutivo Estatal" Version="1.1">
            <ine:Entidad Ambito="Local" ClaveEntidad="QUE">
                <ine:Contabilidad IdContabilidad="75192"/>
            </ine:Entidad>
        </ine:INE>

cuando fue a finkok a validar el xml completo, dice que : 

XMLSyntaxError(u"Element '{http://www.sat.gob.mx/ine}INE': The attribute 'TipoProceso' is required but missing.",)

tons pa sabe quien tiene la razón... al menos ahorita ya puedes jugar con los datos extras de la addenda..

**Comment by jccastillo0007** [comment]
este es el xml generado completo
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ine="http://www.sat.gob.mx/ine" Version="3.3" Folio="119" Fecha="2021-04-20T22:56:16" Sello="fnOO0wpJSRxtSsEM7L8sQ+fkEIF42jMEGWfcW5ZJ7WSDvuFDrTgZbhkPdIdMHkDhS47bN6pe4WDJ1uz6I4i5cYeh1xIcCzQJSiTw1jKEBVR7RJEFlBSsHmSAnesVFJa1TD+sSnH7XTKfqSACspZIfy19Wr4uN9OaRkOVJmQ6vhTFdZIP6OaOpqPLZSCIFIUKEqKke3JxZP1fJrmWc7J0/XmSCq9aI2JK5hfOklY5qu/2YCBtgmNXVyYDvbovvvGRhgFgCMs9NMV3g3PTLJJZ6tJ/7zzLkgQZd8EXlcN0OUT12D1m1PQrmeQp3JPPQtQAv9VCpMIs3C5oIdcAFk7VQQ==" FormaPago="99" NoCertificado="30001000000400002336" Certificado="MIIFjjCCA3agAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMzYwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI5MTk1MjQyWhcNMjMwNTI5MTk1MjQyWjCBtTEeMBwGA1UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTEWMBQGA1UELRMNWElRQjg5MTExNlFFNDEbMBkGA1UEBRMSWElRQjg5MTExNk1HUk1aUjA1MR4wHAYDVQQLExVCRVJFTklDRSBYSU1PIFFVRVpBREEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCp6FMIaf6NrmG278bVeJIlOEx3c7FepPkVLLbic9z28ws49OpajLa0xlmIb17lcPZWfm8VGRbRWHa6PY8KxbuBtN+k2/KjpVztGh3PPyHIVT6QoXJczzQaNMcuN3W+KoHGa4EvAqG8MchtTqhXX8U8Lds83pSRiPJKNCJ3x/CfnAK6LlxFi3NdIHYVRqNE/R4TPe38VbGVR/9wLsgGQhrhhQwWXnUcPBF5WB/myQEJJq/esuKWYlLugzJfZjklUs2ThrjSZM6YvBujmFqCz4t3fJU0lYEDNI8rT1PHy9LFdiXNeUZQf5c+1TfTdhdGQmYUWLdkyRSdF3tIkPb2+exHAgMBAAGjHTAbMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgbAMA0GCSqGSIb3DQEBCwUAA4ICAQAqYMNNHiDbDCrIGsNKpeT24HZVJ2gIJ8PuB/DdKxAFBANTp6KRQFb+7FoyVhP29H55DRre4Cyfrr0Bi5ZwGEaAv+D6/41N9M4/2TClgyZp4ppXPYZy0+AVM3ySsFwUfdancTeZjy0X9ETFcjj190x5W6FA63FaaX+YpuCgougKhi/cXT6HiFvi+STeMdsygJNyCuVXgC3hGnwYnBDheLp2HFuVI0ugF/zRnPaMFcRB1IL8Zi1wtg451E0YeGLm2x+WhWSZdzJoz+0NK+bC3+13JVUjj7wypfXMVwC5/x4H50pFbNnVp+jcgKvP9k+DQ2Qibe6kSrmKF57sndO/PtnK2g8ukKJmShDTfZJlSSf+xBZwbJ6yqYvmGuxtSd2kr4UFJ4jjFS7WeqCZ0TyVZ+sdQ6SJk2ed64YgSHsPHqmIPIn9acrLt/B+ycEACIC8Wb1AbvztKnb0dxCuuU2XfszSG08XHs2RA7hVmbe1d58lhIX7b32YUH5VmgOsSezUF4ji46Blci86l4nb9VbxAmrXAQtRWEiBAK+TR3k33MhCom/Dub7Xo16HJuJkEjleFdhmwCDpqs9/XFcfGybvKXTkd1OjaMkJ1XKzsNGQfKpXsFVl+O4vGsFMNmyU8c2YbPK+D2XwMJSeHjYFs6Oyc/TljED+/577EBElcF5Diu1vTw==" SubTotal="100.00" Moneda="MXN" TipoCambio="1" Total="116.00" TipoDeComprobante="I" MetodoPago="PPD" LugarExpedicion="45645" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/ine http://www.sat.gob.mx/sitio_internet/cfd/ine/ine11.xsd">
    <cfdi:Emisor Rfc="XIQB891116QE4" Nombre="Central de Abastos" RegimenFiscal="605"/>
    <cfdi:Receptor Rfc="PAN400301JR5" Nombre="PARTIDO ACCIÓN NACIONAL" UsoCFDI="G03"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="01010101" NoIdentificacion="PROD-TEST" Cantidad="1.00" ClaveUnidad="H87" Unidad="PZA" Descripcion="PRODUCTO DE PRUEBAS" ValorUnitario="100.000000" Importe="100.000000">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="100.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="16.000000"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="16.00">
        <cfdi:Traslados>
            <cfdi:Traslado Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="16.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
    <cfdi:Complemento>
        <ine:INE TipoComite="Ejecutivo Estatal" Version="1.1">
            <ine:Entidad Ambito="Local" ClaveEntidad="QUE">
                <ine:Contabilidad IdContabilidad="75192"/>
            </ine:Entidad>
        </ine:INE>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by RigoFlores** [comment]
Ahorita ya quedó un poco ajustado a lo que teníamos antes y a lo que se pidió, ya jala. 
Para completarlo y sea mas robusto y flexible, le falta lo siguiente:

a) el valor de contabilidad, debería solicitarse solo una vez, y aplicarlo donde corresponda header o subnodo. Hoy lo pedimos doble, pero solo se capturará uno u otro. Así que deberíamos pedirlo solo una vez.
b) Hoy solo aceptamos un valor de contabilidad, pero la spec dice de 0 a muchos. Podría darse el caso de requerir mas de uno, eso implicaría quizás que este dato fuera el último de la captura y todos los que se agreguen, pues serían adicionales de la contabilidad.
c) Ya no seguí haciendo pruebas, pero como el dato de contabilidad a nivel subnodo podría ir en vacío, ya no lo probé...
d) Hasta donde recuerdo, tenemos amarrado el complemento a ciertos RFC receptores (de partidos políticos), pero debemos abrirlo ya que los partidos cambian y además aplica para candidatos independientes y para AC aspirantes a partido.
e) Cuando el proceso es DISTINTO A campaña o precampaña, entonces el nodo y subnodo no aplican.

Que chinga, no???

Pues si se nos presenta la necesidad, lo actualizamos, pero aquí dejo documentado lo que según yo le falta.
