### ISSUE TITLE
En la emisión de Cotización con descuentos, no está pasando correctamente unas variables al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1776]
Cuando se generan cotizaciones con descuento, no se pasan correctamente las variables al PDF.
Ejemplo:

Aquí capturé una partida con cantidad 10 y precio unitario 100, para un importe = 1000.
Adicionalmente le apliqué un descuento del 15%. Con ello el cálculo del IVA se hace sobre 850.00
Hasta aquí todo bien:

<img width="623" alt="cot" src="https://user-images.githubusercontent.com/2912775/115614584-81797b00-a2b3-11eb-8166-ec8686316e68.PNG">

Pero ya en la sección de subtotales, hace un relajito:
El subtotal, lo muestra con descuento, luego el nuevo subtotal, le vuelve a restar el descuento.
Pero el IVA y el total, si están bien. Es decir el IVA se calcula sobre los 850 y el total son 850 + IVA.
Lo que está mal son las variables $F{subtotal} y $F{subtotalSD} que se envían al PDF cuando se trata de cotizaciones. Deben calcularse idénticamente que como se hace para las facturas.

<img width="180" alt="cot2" src="https://user-images.githubusercontent.com/2912775/115614704-a0780d00-a2b3-11eb-9a80-7fd78ed5be2c.PNG">

**Comment by jccastillo0007** [comment]
fixed..

lo subí a pru y lo probé, y como estaba muy fácil de identificar el problema ya resuelto, lo subí a pro

**Comment by RigoFlores** [comment]
ok
