### ISSUE TITLE
Conector para carta porte, quitar ventanas modales para estos RFC's

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1777]
ATC900122NU0
TRA891031SXA

Para que no detengan el procesamiento de los archivos planos. Ahora mismo se detectó para el XML mal formado, pero como bien dices, podría ser como los españoles, que no tienen ninguna ventana modal.
Recuerda que ellos procesarán mucho.
En el consumo diario, ya se nota que arrancaron.

**Comment by jccastillo0007** [comment]
listo, subí el release 11.0.9
