### ISSUE TITLE
Implementar Complemento de Carta Porte por Conector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1778]
He creado una carpeta en DropBox:

C:\Users\admin\Dropbox\FacturaT\PROYECTOS\CFDI3.3\cartaPorte

Contiene estos archivos, mas los catálogos del complemento y del CFDI estándar.

**layoutComplementoCartaPorte_Comentado.txt**  (describe con comentarios el complemento)
**layoutConectorCartaPorte SinComentarios.txt**  (es un ejemplo que podríamos procesar inicialmente, viene completo)

**MapeoComplemento.xlsx**   (viene el detalle de cada campo, en principio es lo mismo que el estándar, pero con otra vista)
**EstandarCartaPorte.pdf**  (Estándar del complemento).

http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte.xsd   (xsd del complemento)

Cualquier duda me comentas.
Me avisas cuando pueda revisar el XML formado, ya se que aún sin timbrar.

**Comment by RigoFlores** [comment]
Documentaré aquí los detalles iniciales. Ya para la siguiente vuelta de pruebas, abriré issues individuales.

Ya pude revisar,  encontré estos detalles:

a)	No muestra correctamente los acentos. Hay un parámetro que es Sí/No, y cuando es “Sí” no lo muestra correctamente, tampoco en otros campos donde se incluyan acentos, por ejemplo “Querétaro”.
b)	el año modelo del nodo identificación vehicular no lo reporta correctamente, como que no lo está parseando.

Y pendiente esto que ya habías reportado tu.

c)	Los nodos de remolques y cantidad transporta, solo se soporta un item  (deben soportar varios).
d)	Falta el nodo de figura transporte

En cuanto a la estructura, namespaces, etc, será hasta que contemos con un ambiente de pruebas que se podrá validar.
Por ejemplo, pensaría que al inicio de cada línea del complemento, debe llevar el “ns3:CartaPorte”, pero de eso no estoy seguro.

En cuanto a que no incluya en el XML los atributos que no se reportan en el archivo de texto, o los nodos no incluidos, muy bien, quedó chingón. 
Eso nos facilitará un chingo las pruebas. Flexibilidad le llamo yo, pero no se cuál sea el nombre de esa feature; quedó “a placer” para poner y quitar.  Así como puta con propina de 1000 varos, jajaja.

**Comment by jccastillo0007** [comment]
se llama anti usuarios pend...

**Comment by RigoFlores** [comment]
documentaré las fallas en otro issue
