### ISSUE TITLE
No envia las variables de aduana al pdf; tampoco las de posición

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#178]
No estamos recibiendo las variables correspondientes a la aduana en el PDF.
numeroAduana
fechaAduana
aduana (esta ya es opcional).

También recuerdo que nos enviarías en cada producto, el valor de posición, es decir el número de renglón que le toca a cada producto dentro de la factura. Cómo se llama esta variable?

**Comment by jccastillo0007** [comment]
Fixed.

La nueva variable para conocer el numero de producto es :  

numeroItem.

**Comment by RigoFlores** [comment]
OK, esta nueva variable ahora mismo se envía a cuál de estas opciones?

a) escritorio
b) demo web
c) producción
d) erp

**Comment by jccastillo0007** [comment]
Respuesta b, d y c*

*Se libera en el próximo deploy... ahora que liberemos addenda santander

Lo necesitas en Standalone ??? si ya va de salida.

**Comment by RigoFlores** [comment]
jajaja, el escritorio nunca saldrá, tenemos nuestros mejores clientes (conector) ahí....amén de todos aquellos que le tienen pavor al web (y con razón, aún no es sitio seguro...:( )
Me avisas cuando se envíe la nueva variable al escritorio???

**Comment by jccastillo0007** [comment]
Done.... release 8.0.7
