### ISSUE TITLE
CFDI de Retenciones e Información de pago - ajustar el tema del encoding y las claves de retención

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1780]
Te mandé un par de correos.

Uno donde se explica un encodig que se debe hacer desde ya, para las retenciones y pagos.

Otro correo, te comento que adicionalmente la clave de retenciones no es correcta, supongo que a todo le envía 01.
No se en qué momento se inyectó ese problema, chiaaaa.

**Comment by jccastillo0007** [comment]
Esto ya esta resuelto
