### ISSUE TITLE
Complemento de carta porte por conector - par de detalles 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1781]
a) no muestra correctamente los caracteres especiales.
b) no soporta varios nodos de operadores, propietario, arrendatario y notificado, hijos del nodo Figura Transporte

**Comment by RigoFlores** [comment]
sigue el problema de los caracteres especiales...

**Comment by jccastillo0007** [comment]
fixed, bueno solo el b, el a es un tema de interpretación del editor, pero el xml esta bien formado.
