### ISSUE TITLE
Complemento carta porte - traslado, no debe incluir el tipo de cambio en el CFDi estándar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1785]
Dentro del CFDI estándar, se aplican las siguientes reglas:

1. subtotal=total=0
2. moneda=XXX
3. tipo de cambio no se reporta.

Ahora mismo tenemos los 2 primero puntos, pero el 3ero aunque no incluya el tipo de cambio en el texto plano, lo incluye en el CFDI estándar y de ahí no puedo pasar para probar en sí el complemento.

**Comment by jccastillo0007** [comment]
fixed
