### ISSUE TITLE
Complemento de carta porte - enviar al PDF en el datoExtra14 el complemento 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1786]
Mientras encontramos mejor manera, y así mantendremos el formato actual de cartaPorte, y solo le agregamos este dato al final del reporte

**Comment by jccastillo0007** [comment]
el archivo xml que se esta generando, tiene 18 datos extras, por que dices que en el dato extra 14 ?

**Comment by RigoFlores** [comment]
busqué en la plantilla actual, y el último dato extra que se ocupa es el 13.
Ahora si tu me dices que estás enviando info en 18 datos extra, ok, entonces que sea en el datoextra19.

**Comment by RigoFlores** [comment]
ya vi, quedó finalmente en el 15, ya que el 14 se ocupa para saber si se imprime o no el contrato de la SCT
