### ISSUE TITLE
ERP-FACTURAS- NO REPORTA LOS DESCUENTOS CORRECTAMENTE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#179]
NO ESTÁ REPORTANDO EL MOTIVO DE DESCUENTO, Y TAMPOCO CALCULA LOS IMPUESTOS CORRECTAMENTE CUANDO SE INCLUYE DESCUENTOS.
TOTAL= ( SUBTOTAL - DESCUENTOS ) + IMP. TRASLADADOS - IMP. RETENIDOS

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
NEGATIVO, AHORA NO REPORTA EL MOTIVO DE DESCUENTO NI AL XML NI AL PDF.

**Comment by jccastillo0007** [comment]
Fixed.
