### ISSUE TITLE
Carta Porte - Miscelaneos, incluir el nombre alterno

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1793]
Seguramente se necesitará que para el mismo RFC, existan distintos domicilios, entonces hay que agregar al igual que en catálogo de clientes, la funcionalidad de nombre alterno.

**Comment by jccastillo0007** [comment]
no ma... esto lo voy a dejar al último porque hay que hacer varias maneobras

**Comment by RigoFlores** [comment]
creo que es importante, ya atender este punto.

**Comment by RigoFlores** [comment]
como hemos platicado, puede ser nombre alterno o así como está, agregar una etiqueta que NO SE REPITA. 

En la pantalla de captura del complemento, elegir por RFC y/o etiqueta. Pero si no hay mucho espacio, entonces solo por etiqueta.

**Comment by jccastillo0007** [comment]
done.

La  etiqueta la estoy poniendo como mandatoria, para poder hacer las validaciones
