### ISSUE TITLE
Carta Porte - Operadores, Propietarios, Arrendatario y Notificado no llevan datos adicionales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1795]
Excepto por Operadores, que se debe capturar su número de licencia, los otros 3 datos no llevan ningún dato adicional, esto es solo se cubren con lo que ya se capturó en misceláneos.
En todo caso, agregar el nombre alterno, para el caso que se ocupe el mismo RFC.

Aquí no tengo muy claro, si la llave está bien que sea el nombre, pero bueno por lo pronto así salimos y luego vemos si se hace necesario cambiarlo. Igual y una opción es presentar para elegir: RFC, Nombre y Nombre alterno.

**Comment by jccastillo0007** [comment]
fixed
