### ISSUE TITLE
Carta Porte - Web dudas de campos no definidos

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#1796]
Rijo... aqui te voy a poner algunos campos que no están definidos en el documento de word (la nomenclatura que ves, viene del conector, pero solo checa el nombre del campo

// header
		cp.setEntradaSalidaMerc(values[2]);
		cp.setViaEntradaSalida(values[3]);

// mercancias
			mercancias.setPesoBrutoTotal(NumberConverter.toBigDecimal(values[0]));
			mercancias.setUnidadPeso(values[1]);
			mercancias.setPesoNetoTotal(NumberConverter.toBigDecimal(values[2]));
			mercancias.setCargoPorTasacion(NumberConverter.toBigDecimal(values[4]));

// mercancia
			mc.setBienesTransp(values[0]);
			mc.setClaveSTCC(values[1]);
			mc.setClaveUnidad(values[4]);
			mc.setUnidad(values[5]);
			mc.setMaterialPeligroso(values[7]);
			mc.setCveMaterialPeligroso(values[8]);
			mc.setEmbalaje(values[9]);
			mc.setDescripEmbalaje(values[10]);
			mc.setFraccionArancelaria(values[14]);
			mc.setUUIDComercioExt(values[15]);

y asi hay muchos campos en cada componente que no se de donde se toman... y es lo que queria tener ya listo para programarlo

**Comment by RigoFlores** [comment]
En el word se menciona en amarillo los campos que no se capturan y que se deben incluir, ya sea valor fijo o calculados. Creo que solo hay un cálculo.
El resto de parámetros o atributos que no se mencionan, significa que en esta primera versión no serán soportados.

**Comment by RigoFlores** [comment]
Estamos saliendo con una versión light del carta porte.
Solo para autotransporte
Solo de 1 origen a 1 destino
No transporte de mercancía peligrosa.

Es decir, lo mismo que hoy tenemos.
Para la pantalla completa, si se ocuparían varios parámetros mas, pero eso sería otra app, recuerdas?
