### ISSUE TITLE
Conector Carta Porte, aparentemente no soporta el "Sí" en el parámetro material peligroso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1797]
Ni en la consola del facturat, ni en el catalina aparece bien el "Sí" (con acento), entonces no sé si es por ello que marca el error o es otra cosa.
¿Cómo puedo o puedes validar que si lo esté pasando correctamente?

Anexo el archivo de texto con el que no pasa.
[replicaTrasladoFinkok.txt](https://github.com/jccastillo0007/eFacturaT/files/6672547/replicaTrasladoFinkok.txt)

**Comment by RigoFlores** [comment]
Así aparece en el catalina.out

 <cartaporte:Mercancia BienesTransp="10191509" Cantidad="1.0" ClaveUnidad="3H" CveMaterialPeligroso="M1839" Descripcion="Insecticidas" Embalaje="4H2" **MaterialPeligroso="SÃ­"** Moneda="MXN" PesoEnKg="40.0" ValorMercancia="380.0"/>

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
realmente se atendió lo de TranspInternac="Sí" , pero no lo de material peligroso, ya que lo sigue marcando igual que como originalmente lo indica este issue.
Esto es para el conector... urge su corrección, para especificar lo de material peligroso en la pantallan.

**Comment by jccastillo0007** [comment]
done
