### ISSUE TITLE
Carta Porte Web - varios issues para el tipo Traslado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1799]
Obviamente no está timbrando, pero si genera el XML que manda a timbrar, de ahí vi estos puntos.
Son varios, mas o menos simples. Entonces los anotaré aquí. Si quieres luego separo los complicados. 

a) Total = Subtotal = 0.  Ahora mismo pone 0.00
b) Total distancia recorrida, no suma las distancias recorridas de los nodos de Origen o Destino (en realidad, creo que solo en los nodos destino se captura la distancia)
c) No está incluyendo los nodos de Origen, ni Destino.
d) A nivel de mercancía no está incluyendo la clave de la unidad, en su lugar incluye la descripción.
e) A nivel de mercancía, si no capturaste el peso que es opcional, se lo incluye como '0'.
f) A nivel de nodo operador y notificado, no está incluyendo las claves de estado, municipio, colonia. En su lugar incluye literalmente lo que se capturó. Supongo que lo mismo hará con los nodos destino y origen.

Aquí tienes el XML que generó.

[XMLcp.txt](https://github.com/jccastillo0007/eFacturaT/files/6718223/XMLcp.txt)

**Comment by jccastillo0007** [comment]
fixed.
