### ISSUE TITLE
CATALOGO DE CLIENTES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#18]
SI NO CAPTURAS EL CÓDIGO POSTAL, INDICA QUE EL CAMPO ZIP CODE ES REQUERIDO, CUANDO ESA ETIQUETA NO APLICA EN LA PANTALLA.
EN GENERAL REVISAR TODAS ESAS ETIQUETAS.

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
SIN PODER VALIDAR PORQUE NO PUEDO ALMACENAR EL REGISTRO

**Comment by jccastillo0007** [comment]
Ya esta corregido, pero de hecho ese campo ya no es requerido.

**Comment by RigoFlores** [comment]
CORREGIDO OK
