### ISSUE TITLE
Carta Porte - No soporta mas de un nodo mercancía

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1800]
Necesitamos soportar mas de un nodo

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Cuando capturo 2 mercancías, no incluye cada nodo mercancía dentro del nodo mercancias, si reporta 2 mercancías pero no así los nodos. Así sale:

            <cartaporte:Mercancias NumTotalMercancias="2">
                <cartaporte:AutotransporteFederal NombreAseg="AXXA" NumPermisoSCT="1234567890" NumPolizaSeguro="AXA1234567" PermSCT="TPAF01">
                    <cartaporte:IdentificacionVehicular AnioModeloVM="2020" ConfigVehicular="C3R3" PlacaVM="ABAC123"/>
                    <cartaporte:Remolques>
                        <cartaporte:Remolque Placa="BCD123" SubTipoRem="CTR014"/>
                        <cartaporte:Remolque Placa="DCB321" SubTipoRem="CTR012"/>
                    </cartaporte:Remolques>
                </cartaporte:AutotransporteFederal>
            </cartaporte:Mercancias>

**Comment by RigoFlores** [comment]
ya vi lo que pasa, ahora espera a huevo el ID origen y el ID destino, pero no precisamente se necesitan.

Solo en el caso de que exista MAS DE UN NODO DESTINO, estos Identificadores de origen y destino, serán requeridos.
Cuando no exista mas de un destino, entonces los ID son opcionales

**Comment by jccastillo0007** [comment]
solo captura el nodo id origen y id destino, se utilizan para saber si se capturo bien la info, se puede poner algo por omisión.

**Comment by RigoFlores** [comment]
llevan nomenclatura especial, si quieres poner un consecutivo para cada origen y destino... tienen un prefijo y 5 dígitos.
yo pienso que ponerlos a juerza, está chafón pero bueno pues...

ejemplo:

OR000001
DE000001

**Comment by jccastillo0007** [comment]
ahorita ya esta  con ese default, pero voy hacer los cambios para no depender del id...
