### ISSUE TITLE
Carta Porte tipo ingreso, no lo genera

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1801]
Debemos soportar carta porte tipo ingreso con el complemento.
De igual manera, se debe tener claro cuando se necesita un CFDI de tipo ingreso, pero SIN el complemento

**Comment by jccastillo0007** [comment]
vamos a tener un problema para esta opción...
ya que puede haber ingreso con complemento y sin complemento, pero tal vez con otra addenda

el tipo ingreso es una factura normal ?

**Comment by RigoFlores** [comment]
Si, el CFDI de tipo ingreso con complemento de carta porte, es factura normal. De hecho debe incluir retención de IVA, pero eso ya es propio de la captura.
Se puede dar el caso, remoto pero si es probable, que requiera el complemento de carta porte + otra addenda; por lo pronto no lo soportaremos.

Ahora, como platicamos, para distinguir una factura de un ingreso con complemento, agregaremos la opción de CFDI "Carta Porte-Ingreso", y la otra podría ser "Carta Porte-Traslado", para ser consistentes.

Otra cosa a considerar, es cómo controlar  el acceso para la emisión de Carta Porte Ingreso o Traslado?

**Comment by jccastillo0007** [comment]
done

para poder emitir carta porte ingreso o traslado, el cliente debe tener los plugins de addendas y de carta porte, asi lo podemos controlar

**Comment by RigoFlores** [comment]
no está generando el ingreso... a diferencia del traslado, la factura estándar se emite normal, esto es el total y subtotal son lo que se capture en la factura, la moneda NO es XXX. Se deben reportar los impuestos que se hayan capturado.

Al menos en el catalina, no se nota que eso haya cambiado. Se hecho ni siquiera el tipo de cfdi lo reporta como I

**Comment by jccastillo0007** [comment]
ya genera el xml, habrá que identificar otras cosas que falten o sobren para que lo pueda timbrar.
