### ISSUE TITLE
Carta Porte - Mercancías, hacer el valor y la moneda opcionales.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1802]
En el catálogo de mercancías, el valor y la moneda solo son requeridos para transporte aéreo.
Para autotransporte federal, son opcionales.

Entonces, debemos hacer que su captura no sea obligatoria en el catálogo, pero además si no se capturan, obviamente no se incluyen en el nodo mercancía del XML.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
cuando agrego una mercancía sin valor ni moneda, marca error.
Ni siquiera se alcanza a formar el XML en el catalina, marca error desde antes.

do : 16.0","price":16,"tax":"IVA","taxId":"IVA_Trasladado","type":"TRASLADADO"}],total_taxes_retenido=0.0,total_taxes_trasladado=40160.0]
2021-07-05 21:30:06,030 DEBUG [http-nio-8080-exec-43] (InvoicePanel.java:1166) - Options selected : []
2021-07-05 21:30:06,138 ERROR [http-nio-8080-exec-43] (JCLLoggerAdapter.java:532) - Unexpected error occurred
org.apache.wicket.WicketRuntimeException: Method onRequest of interface org.apache.wicket.behavior.IBehaviorListener targeted at com.efacturat.view.panel.InvoicePanel$34 {event='onClick'} on component [Component id = executeImage] threw an exception

**Comment by jccastillo0007** [comment]
ya soporta la mercancia sin moneda ni valor, 
pero finkok manda esto 003 : CP999 : Error no clasificado 
lo que significa que te toca identificar que pasa
