### ISSUE TITLE
Carta Porte - cuando no se incluya el remolque, no reportar nodo vacío

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1804]
Si no captura remolque, que es opcional, no debe reportar los nodos vacíos.
Ahora mismo lo hace así:

                <cartaporte:AutotransporteFederal NombreAseg="AXXA" NumPermisoSCT="1234567890" NumPolizaSeguro="AXA1234567" PermSCT="TPAF01">
                    <cartaporte:IdentificacionVehicular AnioModeloVM="2020" ConfigVehicular="C3R3" PlacaVM="ABAC123"/>
                    **<cartaporte:Remolques>
                        <cartaporte:Remolque/>
                        <cartaporte:Remolque/>
                    </cartaporte:Remolques>**
                </cartaporte:AutotransporteFederal>

Si no se captura ningún remolque, el nodo remolques no debe existir.
Marcó error no clasificado, jeje

**Comment by RigoFlores** [comment]
Mismo caso, si solo se captura un remolque, entonces se debe reportar UN SOLO NODO remolque, ya que ahora se reporta uno con datos y el otro vacío. Marca el mismo error no clasificado.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
pues a reserva de que lo pueda timbrar, a nivel del XML se ve bien este nodo, pero como no está incluyendo los nodos mercancia, no puedo asegurarlo. 
Asumiré que si jalará, cuando ya se pueda timbrar.
