### ISSUE TITLE
Carta Porte - Nodo Figura Transporte, no reportar nodos vacíos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1805]
Cuando no exista el nodo operador o propietario o arrendatario o notificado, NO se tiene que reportar en vacío.
Creo que incluso, a nivel de nodo FiguraTransporte, podría ir así para el caso que no se capture ninguno de los nodos mencionados arriba:

            <cartaporte:FiguraTransporte CveTransporte="01">
            </cartaporte:FiguraTransporte>

Ya que ahora mismo lo reporta así:

            <cartaporte:FiguraTransporte CveTransporte="01">
                **<cartaporte:Operadores/>
                <cartaporte:Notificado/>**
            </cartaporte:FiguraTransporte>

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
a reserva de validar que timbre correctamente, parece ser que si quedó.
