### ISSUE TITLE
Carta Porte - Implementar mapeo de complemento al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1806]
Para salir inicialmente, así quedarían los datos extra para el complemento de carta porte:

DATOS EXTRAS:

1: ORIGEN - NOMBRE, RFC Y DOMICILIO  (EN 3 RENGLONES)
2: DESTINO - NOMBRE, RFC Y DOMICILIO. DISTANCIA RECORRIDA: XXX (EN 4 RENGLONES)
3: MUNICIPIO + ESTADO - ORIGEN 
4: MUNICIPIO + ESTADO - DESTINO
5: FECHA DESTINO
6:
7: SUMATORIA DE PESOS (KGS) DE LOS NODOS MERCANCÍA
8:      (vacío porque se ocupa para material peligroso, y no lo soportaremos)
9: SUMATORIA DE LOS VALOR MERCANCIA DE LOS NODOS MERCANCÍA
10:  (vacío porque era el campo indeminzación no considerado en el complemento)
11: (vacío porque era el campo observaciones no considerado en el complemento)
12: NODO IDENTIFICACION VEHICULAR: CONFIG + PLACAS + AÑO
13: NOMBRE OPERADOR
14:  SI/NO (falta agregar checkbox de "Incluir Contrato en el PDF")
15: CONTENIDO DEL COMPLEMENTO DE CARTA PORTE

**Comment by jccastillo0007** [comment]
cual de estos datos ya se manda al pdf... yo no he podido timbrar un carta porte con complemento, entonces no puedo ver esta info en el log, y en el código esta medio confuso...

**Comment by RigoFlores** [comment]
no entiendo la pregunta... cuando se trataba del carta porte anterior, se enviaban todos los datos anteriores, porque se CAPTURABAN COMO DATOS EXTRA. Era parte de la solución de carta porte.

Hoy en día, la fuente de la data, es distinta (pantalla carta porte, miscelaneos y mercancía), y es precisamente lo que estoy mapeando. En lugar de tomarlos de la pantalla de datos extra, ahora se toma del origen arriba mencionado.

**Comment by jccastillo0007** [comment]
para los primeros datos extras, se va a duplicar el domicilio ?

que pasa si hay mas de un destino?

que quieres decir con lo del datoextra 14, no sé a que se refiere

Acabo de descubrir que la distancia recorrida en el nodo destino, es mandatoria, si no la agregas marca error, solo por si no lo sabias que igual y ya lo tienes bien idnetificado.

**Comment by RigoFlores** [comment]
En datos extra 1 y 2, va el RFC, nombre y domicilio... en 3 renglones distintos. El domicilio en "castellano", es decir, no con las claves que se envían al XML.

En los datos extra 3 y 4, solo es el municipio y estado. De alguna manera se repiten con el domicilio, pero solo en la parte de municipio y estado. La mayoría de las ocasiones, solo será el estado en "castellano", es decir, no la clave del estado.

Cuando exista mas de un origen o mas de un destino, ¿Podrás enviar en el dato extra 1... los n orígenes en 3 renglones cada 1, y asimismo los n destinos?

El dato extra 14. En la pantalla de captura del complemento, falta agregar un checkbox, que diga "Incluir Contrato SCT". Por omisión es NO (unchecked). El dato extra contendrá el valor de SI o NO.

En el dato extra16 podrás enviar n renglones, cada uno con los datos del nodo mercancía, así como sus etiquetas?

Si lo de la distancia recorrida se debe capturar siempre, si no no timbra.
Trabajaré en identificar ya, los mandatorios y los opcionales.

**Comment by jccastillo0007** [comment]
Ahi voy avanzando con este formateo, ya solo falta obtener los nombres del domicilio y no las claves, y formatear lo del dato extra 16 chiaaaa

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Algunos ajustes adicionales al PDF.

Dato Extra 1 al 5. Así llegan:

datoExtra1=ORIGEN - Origen - PREMIER AUTOCOUNTRY SA DE CV
ORIGEN - JUME890620KB3
ORIGEN - BLVD. PEDRO INFANTE PTE, 2995, Pueblo Bonito

datoExtra2=DESTINO - Destino - Tecnologias de Informacion Aplicada SA de CV
DESTINO - TIA101020BP4
DESTINO - Fray Luis de Leon 3051, 3051, Centro Sur

datoExtra3=Culiacan, SINALOA - ORIGEN
datoExtra4=Queretaro, QUERETARO - DESTINO
datoExtra5=02/07/2021

Deben llegar así como se indica abajo. 
Esto es quitar las etiquetas,  y en el mismo dato incluir municipio, estado, así como la fecha de cada ubicación, de preferencia con etiqueta. Numerar los orígenes y destinos. Recordar que si se incluyen mas de un origen o destino, se repetirá la info, por ello importante numerarlos.

datoExtra1= Origen1 - PREMIER AUTOCOUNTRY SA DE CV
JUME890620KB3
BLVD. PEDRO INFANTE PTE, 2995, Pueblo Bonito
Culiacan, SINALOA
Fecha Hora Salida: 2021-06-17

datoExtra2= Destino1 - Tecnologias de Informacion Aplicada SA de CV
TIA101020BP4
Fray Luis de Leon 3051, 3051, Centro Sur
Queretaro, QUERETARO – DESTINO
Fecha Programada llegada: 02/07/2021

datoExtra3=
datoExtra4=
datoExtra5=



Dato Extra 7. Así llega:
datoExtra7=$2,500.00

Ya no se ocupará, porque se incluye en el dato extra 16:
datoExtra7=


Dato Extra 12. Así llega:
datoExtra12 =C_3_R_3, ABAC123, 2020,

Deben llegar sin guiones bajos, no sé porqué se agregan.
datoExtra12 =C3R3, ABAC123, 2020,


Dato extra 16:  (QUITARLE EL SIGNO DE PESOS EN CANTIDAD Y EN PESO EN KILOGRAMOS y FORMATEARLO). No olvidar que si son varias mercancías, cada una va en esos 2 renglones

,datoExtra16=Bienes Transporta: 25101503 Descripción: 9BD265553M9182527 415554 RAM PROMASTER RAPID
Unidad: PIEZA   Clave Unidad: H87   Moneda: MXN   Cantidad: 2.00   Peso en Kilogramos: 2,500.00   Valor Comercial: $2,400,000.00

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
lo que faltó es que la sección de mercancías así lo manda:

Bienes Transporta: 25101503
Descripción: MERCANCÍA DE PRUEBA
Unidad: PIEZA
Clave Unidad: H87
Moneda: MXN
Cantidad: 3.00
Peso en Kilogramos: 1,000.00

Se requiere así, por cada mercancía. Para que la descripción vaya en un solo renglón y el resto de la info en otro.

Bienes Transporta: 25101503  Unidad: PIEZA  Clave Unidad: H87  Moneda: MXN  Cantidad: 3.00  Peso en Kilogramos: 1,000.00
Descripción: MERCANCÍA DE PRUEBA

**Comment by RigoFlores** [comment]
Cuando sea tipo TRASLADO, en los totales NO enviar impuestos, se ve algo extraño, chequea...

<img width="171" alt="totales" src="https://user-images.githubusercontent.com/2912775/126013920-60834749-0ec6-4900-b545-99c942ba94e3.PNG">

**Comment by jccastillo0007** [comment]
done
