### ISSUE TITLE
Carta Porte - Implementar cantidad transporta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1807]
Este nodo, dentro del nodo mercancías, ÚNICAMENTE se debe incluir cuando existan mas de 1 nodo destino.
En este caso, dentro de CADA UNO DE LOS NODOS mercancía, se incluirá el nodo cantidadTransporta

Cantidad: se toma de la cantidad del nodo mercancia
ID Origen: se toma el primer identificador origen que exista
ID Destino: se toma el primer identificador destino que exista

Esto está medio chacarrón, ya que aún no tengo claro cuáles ID's realmente se deben indicar, pero para cuando existan mas de un destino, por lo pronto así lo sacaremos.

                </cartaporte:Mercancia>
                <cartaporte:Mercancia BienesTransp="25101503" **Cantidad="5.0"** ClaveUnidad="H87" Descripcion="Automovil Nuevo Honda Civic" Moneda="MXN" PesoEnKg="3500.0" Unidad="Unidades" ValorMercancia="450000.0">
                    <cartaporte:CantidadTransporta **Cantidad="5.0"** IDDestino="DE123456" IDOrigen="OR000001"/>
                </cartaporte:Mercancia>

**Comment by jccastillo0007** [comment]
done
