### ISSUE TITLE
Carta Porte - ahora no soporta únicamente 2 ubicaciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1808]
al implementar lo de cantidad transporta, le pegamos al tema que ahora no soportamos un solo nodo origen y uno destino.

si no capturas 1 origen y 2 destinos (al menos) con su ID, no genera el XML timbrado

**Comment by jccastillo0007** [comment]
fixed, solo falta quitar lo del id, pero para eso hay otro ticket

**Comment by RigoFlores** [comment]
negativo, aún no genera con solo dos nodos de ubicación, es decir 1 origen y 1 destino

**Comment by RigoFlores** [comment]
ya revisé las validaciones del SAT, y efectivamente, los ID Origen y ID Destino, van de la mano con CantidadTransporta.
CantidadTransporta solo se necesita en caso de incluir mas de 2 destinos.
Para el caso de 1 origen y 1 destino, el parámetro de ID Origen ni Destino se deben incluir.

**Comment by jccastillo0007** [comment]
ya funciona sin id de origen y destino
