### ISSUE TITLE
ERP-FACTURAS. AL EDITAR PRODUCTOS, ELIMINA EL IMPUESTO CAPTURADO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#181]
SI EDITAMOS UN PRODUCTO YA AGREGADO A LA FACTURA, AL ABRIR LA VENTANA DE EDICIÓN, ELIMINA LOS IMPUESTOS CAPTURADOS ANTERIORMENTE.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
con el usuario democp/cartaporte, cuando agregamos un producto y elijo iva trasladado del 16.00 e iva retenido del 4%, no muestra el 4% sino el 16.666%
Los cálculos los realiza bien, pero en pantalla del producto (agregar o editar), muestra una tasa distinta del iva retenido elegido (es decir 16.666 en lugar de 4.00).
En este escenario, tengo definidos 3 impuestos retenidos. 
Si borro alguno de ellos, quedando solamente 2 impuestos retenidos, entonces si muestra la tasa elegida correctamente.

**Comment by jccastillo0007** [comment]
fixed.
