### ISSUE TITLE
Carta Porte - ubicación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1811]
Para autotransporte no aplica el tipo de estación. 01, 02 y 03 no aplican.
No marca error, pero no debe ir.

**Comment by jccastillo0007** [comment]
y luego ? que se ocupa ?

**Comment by RigoFlores** [comment]
es que al menos para ubicación tipo origen, si he visto que se le agrega el tipo de estación 01.
Para destino, creo que no lo agrega. 
Además que no debe ir, está inconsistente, en origen si, en destino no.

lo que se necesita, es que no se incluya el parámetro tipo de estación, ya que creo que solo aplica para marítimo, aunque como lo comenté al inicio, extrañamente no marca error al incluirlo.

**Comment by jccastillo0007** [comment]
done
