### ISSUE TITLE
Pantalla de Complemento, señalar los datos obligatorios.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1813]
Hay que ayudar al usuario indicando cuáles datos son de a huevito...
Aquí señalados con amarillo los obligados.

<img width="889" alt="obligados" src="https://user-images.githubusercontent.com/2912775/126363259-c4cb42b8-9030-444c-b76f-fa44668739bf.PNG">

<img width="743" alt="obligados2" src="https://user-images.githubusercontent.com/2912775/126363281-276d367c-b6cc-41b5-bdb0-f00594fb2dff.PNG">

**Comment by RigoFlores** [comment]
para el catálogo de mercancías... ahí se puede capturar el peso (no estoy seguro que si deba ir)... yo creo que lo podemos mantener, peeeero si una mercancía tiene capturado el peso en Kgs, entonces se debe precargar en la pantalla de carta porte, cuando se elija esa mercancía... con opción de cambiarlo.

![image](https://user-images.githubusercontent.com/2912775/126369968-fa163f67-e021-462f-85ab-ffe65513edd5.png)

**Comment by RigoFlores** [comment]
para el catálogo de misceláneos, igual mencionar los obligados.
<img width="741" alt="obligados3" src="https://user-images.githubusercontent.com/2912775/126374173-ed868b39-fea7-424a-b265-9c67fa7e6d3f.PNG">

**Comment by RigoFlores** [comment]
URGE ESTO, PARA AYUDAR AL USUARIO

**Comment by jccastillo0007** [comment]
done
