### ISSUE TITLE
Complemento de carta porte - Internacional

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1816]
Realmente son pocos requisitos:
1 Agregar parámetro   TransporteInternacional, por default No, pero el usuario podría elegir 'Sí'
2 En caso que sea 'Si', activar que el usuario indique si es entrada o salida
3 Para el caso de salida, agregar el tipo de ubicación   en origen = '01'; destino debe tener país distinto a MEX
4 Para el caso de entrada, agregar el tipo de estación   en destino = '03'; origen debe tener país distinto a MEX
5 Agregar el parámetro en el header, via de entradaSalida = '01'

Podríamos arriesgarnos cabrón y automatizarlo. Que las pantallas no cambien en nada.
a) Si el origen (cualquiera) tiene país distinto a MEX;  tratarlo como traslado internacional Sí, de entrada. Agregar tipo de estación en destino(s) = '03'
b) Si el destino (cualquiera) tiene país distinto a MEX; tratarlo como traslado internacional Sí, de salida. Agregar tipo de estación en origen(es)= '01'
c) Para cualquiera de los casos a o b, agregar el parámetro al header ViaEntradaSalida="01"

Ejemplo de Salida:

        <cartaporte:CartaPorte EntradaSalidaMerc="Salida" TotalDistRec="1221.0" TranspInternac="Sí" Version="1.0" ViaEntradaSalida="01">
            <cartaporte:Ubicaciones>
                <cartaporte:Ubicacion TipoEstacion="01">
                    <cartaporte:Origen FechaHoraSalida="2021-05-07T10:00:00" NombreRemitente="TECNOLOGIAS DE INFORMACION APLICADA SA DE CV" RFCRemitente="TIA101020BP4"/>
                    <cartaporte:Domicilio Calle="BLVD. PEDRO INFANTE PTE" CodigoPostal="80020" Colonia="2153" Estado="SIN" Localidad="02" Municipio="006" NumeroExterior="2995" Pais="MEX"/>
                </cartaporte:Ubicacion>
                <cartaporte:Ubicacion DistanciaRecorrida="1221.0">
                    <cartaporte:Destino FechaHoraProgLlegada="2021-05-10T10:00:00" NombreDestinatario="PREMIER AUTOCOUNTRY SA DE CV" RFCDestinatario="JUME890620KB3"/>
                    <cartaporte:Domicilio Calle="FRAY LUIS DE LEON" CodigoPostal="CP-001" Colonia="KABUL" Estado="KABUL" Municipio="KABUL" NumeroExterior="3051" Pais="AFG"/>
                </cartaporte:Ubicacion>
            </cartaporte:Ubicaciones>

**Comment by RigoFlores** [comment]
Faltó algo a nivel del nodo mercancía:  (ojo, no es en mercancías (detalle), en es mercancía (header))

Para entrada o salida, debe indicar la fracción arancelaria. (aquí está raro, ya que debería ser a nivel de cada mercancía, ya que cada una de ellas, si son distintas, podría tener distinta fracción arancelaria, pero bueno, así está)

Entonces aquí deben tener la facilidad para capturarlo. Capaz que en el catálogo de mercancía se agrega un campo opcional para capturarla. 

Y solamente en el caso de salida, adicionalmente se debe capturar un UUID igual en el nodo mercancia (header, no detalle)
En teoría este UUID lo podrían elegir de nuestro sistema o capturarlo manualmente, o quizás elegir el XML de donde lo puedan tomar. Según yo, este campo debía ser condicional, pero hoy si no lo capturo, marca error.

**Comment by jccastillo0007** [comment]
listo, ya agregue todos los cambios... solo necesito ver como hacer opcional lo de fracción arancelaria y uuid, pero ya puedes hacer pruebas

**Comment by RigoFlores** [comment]
En el header faltó agregar lo de: 
EntradaSalidaMerc="Salida"  (o Entrada, según sea el caso).

Otra cosa, ya vi que mercancía se repite para cada producto, entonces lo de fracción arancelaria y uuid, si van por cada mercancía. Aún no se incluyen

Me confundí ya que mercancias es a nivel header y mercancia es un nodo por cada mercancía transportada... chiaaaaa

**Comment by RigoFlores** [comment]
asi quedaria el xml, para que cheques los nodos:

[CP8_TIA101020BP4_02ago2021.txt](https://github.com/jccastillo0007/eFacturaT/files/6919946/CP8_TIA101020BP4_02ago2021.txt)

**Comment by jccastillo0007** [comment]
ok, no habia visto lo de EntradaSalidaMerc.... eso esta fácil... el otro no tanto

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
estoy tratando de probar apenas con 'entrada', esto es origen foráneo.
En la ubicación de ese origen foráneo, no está incluyendo el estado. No olvidar que solo en caso de MEX, USA y CAN se ocupará la clave para el estado, en cualquier otro caso, el estado es de libre captura.

Ya probé también con destino foráneo, y mismo caso, no incluye el estado en el domicilio.

**Comment by jccastillo0007** [comment]
listo... checale porque yo no lo probé.

**Comment by RigoFlores** [comment]
Ahora marca "internal error".

La forma de probarlo es: producto FLETE (ya que tiene capturado el número de pedimento, que es a huevo en internacional).
Le Asignas el 4% de IVA retenido.

En mercancías, ya vi que pusiste la fracción arancelaria y la quitaste de la pantalla de captura. Eso está bien. 
La mercancía que tiene una fracción arancelaria válida (ya que no es llenar de números únicamente, se valida el contenido) es 9BD265553M9182527.

Si es de entrada, no se debe capturar el UUID. (origen extranjero, destino México)
Si es de salida,  SI se debe capturar el UUID. (origen México, destino Extranjero)

Y pues todo lo demás es igual, Cuando lo mando timbrar, marca internal error de manera inmediata.

**Comment by RigoFlores** [comment]
Por cierto, había propuesto esta nueva pantalla para lo de internacional y material peligroso.

<img width="495" alt="mercancias" src="https://user-images.githubusercontent.com/2912775/128419598-181760a0-5f6b-4335-9e6e-7b4cbd309db2.PNG">

**Comment by RigoFlores** [comment]
Poner separado lo que es para internacional y también lo que es para material peligroso... no todo revuelto.
Incluso con sus etiquetas, esas ayudan mucho...

**Comment by jccastillo0007** [comment]
haber checale, arregle el internal error

**Comment by RigoFlores** [comment]
si, ese si, pero el error del estado, lo sigue marcando para la ubicación internacional, para la nacional si está incluyendo ya el estado.

CP161 : El atributo "Estado" no existe o no contiene un valor o no corresponde con una clave del "catCFDI:c_Estado". (3)

**Comment by RigoFlores** [comment]
<cartaporte:Origen FechaHoraSalida="2021-06-17T00:00:00" NombreRemitente="JUAN CARLOS CASTILLO ALVAREZ" RFCRemitente="CAAJ7506072P2"/>
                    <cartaporte:Domicilio Calle="AV INSURGENTES" CodigoPostal="52142" NumeroExterior="1202" Pais="CAN"/>
                </cartaporte:Ubicacion>
                <cartaporte:Ubicacion DistanciaRecorrida="100.0" TipoEstacion="03">
                    <cartaporte:Destino FechaHoraProgLlegada="2021-07-02T00:00:00" NombreDestinatario="Tecnologias de Informacion Aplicada SA de CV" RFCDestinatario="TIA101020BP4"/>
                    <cartaporte:Domicilio Calle="Fray Luis de Leon 3051" CodigoPostal="76090" Colonia="1317" Estado="QUE" Municipio="014" NumeroExterior="3051" NumeroInterior="29" Pais="MEX"/>
                </cartaporte:Ubicacion>

**Comment by RigoFlores** [comment]
si actualizaste las tablas de los estados para México, Canadá y USA?
Le cambié el estado de ontario a otro, y si jaló.
