### ISSUE TITLE
Complemento de carta porte - Material Peligroso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1818]
Pues siguen surgiendo las necesidades de los clientes... ahora con material peligroso, creo que tiene un impacto menor...
A nivel de nodo mercancía dentro del complemento se deben incluir estos 3 datos:

Pendiente por ficha del conector...

**Comment by jccastillo0007** [comment]
WTF

**Comment by RigoFlores** [comment]
Pendiente la descripción del issue, mientras no se arreglara el tema del 'Sí' para material peligroso.
Ya se arregló, y sigo haciendo pruebas para levantar la spec del issue de material peligroso.. chiaaaa

**Comment by RigoFlores** [comment]
Ya está.
Cuando se trata de material peligroso, se agregan los siguientes parámetros a nivel de cada una de las mercancías:

<<<<   cartaporte:Mercancia BienesTransp="15101506" Cantidad="6.0" ClaveUnidad="H87" **CveMaterialPeligroso="M0537" DescripEmbalaje="descripciÃ³n del embalaje del material peligrocho"** Descripcion="GASOLINA MAGNA" **Embalaje="4A"** FraccionArancelaria="2710129904" **MaterialPeligroso="Sí"** Moneda="MXN" PesoEnKg="2500.0" UUIDComercioExt="DCCFC038-7C9A-47E1-B860-74185776DCDF" Unidad="UNIDAD"   >>>

Entonces en el catálogo de mercancías se agregará lo siguiente:

<img width="495" alt="mercancias" src="https://user-images.githubusercontent.com/2912775/128413323-eded198a-6134-494a-91f5-f00e0305a885.PNG">

**Comment by RigoFlores** [comment]
Para la sección de material peligroso, si capturan clave material será indicativo que se trata de material peligroso, y con ello al integrar el complemento se agregarán los 4 parámetros arriba mencionados:

MaterialPeligroso="Sí"   (cuando capturen la clave de material, se agregará).
CveMaterialPeligroso="M0537" (aquí se deberá capturar la clave del material del catálogo)
Embalaje="4A"    (se captura la clave del embalaje del catálogo. Son 64 elementos, quizás convenga listarlos).
DescripEmbalaje="descripciÃ³n del embalaje del material peligrocho"   (este dato es opcional).

**Comment by RigoFlores** [comment]
Adicionalmente, tendrán la opción de capturar la fracción arancelaria de la mercancía, para el caso que sea entrada o salida del país. Con ello, la estaríamos eliminado de la pantalla de captura del complemento. OJO, solo la fracción arancelaria.

**Comment by jccastillo0007** [comment]
listo, haber checale si jala

**Comment by RigoFlores** [comment]
jajaja, si jaló lo de material peligroso... ahora a probar lo de internacional que no termina de jalar...
