### ISSUE TITLE
NO REGISTRA LOS PAGOS PARCIALES EN FACTURAS NO PAGADAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#182]
AL GENERAR FACTURAS POR COBRAR, NO HALLÉ LA MANERA DE AGREGAR UN PAGO PARCIAL. APARENTEMENTE LO HACE, PERO UNA VEZ QUE CIERRO LA VENTANA DE EDICIÓN DE FACTURA YA GENERADA, NO REFLEJA LO CAPTURADO (ES DECIR EL PAGO AGREGADO)

**Comment by jccastillo0007** [comment]
Acabo de hacerlo y si los registra, incluso en la pantalla de consulta registra el pago en la columna de pagado... hay que platicar este defecto para ver como lo estas haciendo.

**Comment by RigoFlores** [comment]
Cuando una factura se ha timbrado y no se le captura ningún pago.
Posteriormente desde consultas, editas la factura, lo único que te permite editar es agregarle pagos.
Registras un pago y regresas a refrescar la pantalla de consultas, y en la columna de pagos no aparece nada.
Si vuelves a editar para ver que pasó, si tiene un registro de un pago (que no te permite consultar, ni te muestra el contenido), pero ese registro no se refleja en la pantalla de consultas.
Lo acabo de hacer nuevamente...:(

**Comment by jccastillo0007** [comment]
Lo acabo de hacer y si refleja los pagos, lo hice tres veces con pagos de 1000 cada uno y si me refleja en consultas los 3000, te voy a mandar por mail las evidencias.

**Comment by RigoFlores** [comment]
Si, ya ví... es que hablamos de cosas distintas... yo realmente estaba revisando la columna de fecha de pago... ahí si no refleja nada como resultado de la consulta... y siguiendo tu ejemplo, si el cliente captura varios pagos, entonces la columna de fecha de pago, ¿que debería mostrar? 
Hay de 2... o se elimina dicha columna, o se muestra la fecha del último pago... (me parece razonable esta última). Voy a abrir otro issue para la ventana de edición de una factura ya timbrada...

**Comment by jccastillo0007** [comment]
Fixed.
