### ISSUE TITLE
Mercancías con fracción arancelaria, no incluirla en traslados nacionales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1822]
Si una mercancía tiene capturada la fracción arancelaria, pero no se trata de un traslado internacional, no debe incluir este dato en el nodo mercancia ya que marca error.
La fracción arancelaria, se utiliza únicamente en las entradas o salidas internacionales.

**Comment by jccastillo0007** [comment]
done
