### ISSUE TITLE
Complemento de Carta Porte - Implementar el catálogo de transportes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1823]
Para ir limpiando la pantalla de captura (* campos obligados):

* ID_transporte .- Alias único
* Tipo Vehículo  (presentando listado del catálogo).
* Placas
* Año
Remolque 1 Subtipo  (presentando listado del catálogo)
Remolque 1 Placa
Remolque 2 Subtipo (presentando listado del catálogo)
Remolque 2 Placa

Recordar que remolques pueden ser 0, 1 o 2. No hay mas opciones.

**Comment by jccastillo0007** [comment]
Oye, porque los datos de aseguradora, póliza etc.. no son parte del catálogo ?

**Comment by RigoFlores** [comment]
La clave de permiso y número de permiso, son uno por empresa... no están asociados a el transporte.
La aseguradora podría ser la misma. El número de póliza PUEDE ser distinto en cada auto, o podría ser el mismo para el caso de flotilla.
Por ello, no son parte del catálogo. De hecho, se ha pedido que se tomen los datos por omisión de un XML, con la opción que se puedan modificar. No estoy seguro que siempre sean los mismos.

**Comment by jccastillo0007** [comment]
Cual es el catálogo de remolques?

**Comment by RigoFlores** [comment]
El catálogo de remolques, tomado del catálogo del SAT, a eso se refiere.
El tipo de vehículo, también se toma del catálogo del SAT.

**Comment by RigoFlores** [comment]
en ambos catálogos, mostrar la clave y la descripción, para que puedan elegir de una lista.

**Comment by jccastillo0007** [comment]
pssss, me recuerdas donde están esos catálogos?

no los encuentro en el dropbox

**Comment by RigoFlores** [comment]
Chiaaaaa, si está en el dropbox. 

C:\Users\admin\Dropbox\FacturaT\PROYECTOS\CFDI3.3\cartaPorte\CatalogosCartaPorte.xls

Aquí tienes la liga del SAT:

http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/CatalogosCartaPorte.xls

**Comment by jccastillo0007** [comment]
ya esta una versión arriba en PRU, con este catálogo, 

aún me falta poner los catálogos del sat, pero igual ya puedes hacer algunas pruebas

**Comment by RigoFlores** [comment]
Está permitiendo duplicados en el ID.
Debe ser único el ID, igual que en todos los catálogos del carta porte.
Y si, faltan los catálogos de tipo de transporte y de subtipo de remolque

**Comment by jccastillo0007** [comment]
chiaaa me había fallado la validación... ya quedo lo de duplicados

**Comment by jccastillo0007** [comment]
agregué los catálogos de tipo de remolque, pero hay un comportamiento medio raro... aún no esta listo

**Comment by jccastillo0007** [comment]
ya esta también el catálogo de tipo vehículo

**Comment by RigoFlores** [comment]
Tiene aún varios detalles:

a) Cuando intentas timbrar un complemento de carta porte, marca internal error.
b) En la pantalla del catálogo de transportes, bajar el campo para capturar placa y año, ya que se pierden hasta la derecha.
c) en la pantalla de facturación, veo muy escondido la selección del transporte. Quizás ponerlo no tan pegado a lo de los permisos y seguros. 
d) La leyenda del transporte vamos a dejarla como "Transporte", ya que ahora dice ID, y eso no es muy intuitivo.
