### ISSUE TITLE
Complemento de carta porte - no envía dimensiones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1824]
El parámetro Dimensiones es opcional, dentro del nodo de mercancía.
No había hecho pruebas de ello, porque me parece que tendrá poco uso,  primero probé lo estrictamente necesario.

Ahora que lo intenté validar capturándolo en pantalla, si bien no marcó error, tampoco incluyó ese parámetro en el XML.

OJO, no es número, sino debe cumplir con este formato 30/40/30cm u otro similar para pulgadas... total que no es numérico.

**Comment by jccastillo0007** [comment]
ok, ya esta agregando lo que capturen, no valida el formato, por ahora solo agrega lo que se capture en pantalla
