### ISSUE TITLE
Complemento carta porte - datoextra3, indicar si, en caso de material peligroso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1825]
Cuando se detecte que la mercancía agregada al carta porte, enviar al datoextra3 un SI

datoExtra3 = SI/NO  dependiendo si se trata de material peligroso o no.

**Comment by jccastillo0007** [comment]
esta confuso el requerimiento... 
va a enviar No siempre que No sea material peligroso, de lo contrario mandaría Si.

**Comment by RigoFlores** [comment]
jajaja, chiaaaa... a la otra te lo pongo con palitos y bolitas...
es SI o es NO, pero no ambos, chiaaaa...
Quedó listo, aunque como dices envía lo mismo que al XML, chiaaaaa... pareces vieja, haces lo que quieres, jajajajaja
