### ISSUE TITLE
complemento de carta porte - pantalla de captura, etiquetas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1827]
agregar un (+) a:
Distancia recorrida
Cantidad
Peso

el (+) indicará al margen: únicamente número.

La etiqueta dimensiones agregarle (ejemplo: 30/40/30cm ).

La otra que se puede hacer, es que me pases el código donde yo pueda agregar el tooltip a cada una de las etiquetas, sería de mucha ayuda, cómo ves?

**Comment by jccastillo0007** [comment]
ya esta la de dimensiones.

de (+), no entendí bien, debo agregar la leyenda :  

 únicamente número

en algún lugar?

**Comment by jccastillo0007** [comment]
si es para indicar que solo se aceptan números, no debería ser (#) ?

**Comment by RigoFlores** [comment]
lo que sería mas claro, es que con el tooltip se indicara que solo es número.
Si no, igual a un lado de la etiqueta, con un paréntesis.
Pero para no poner tantas leyendas repetidas, yo sugería agregar a esas 3 etiquetas un (+), y en la parte inferior o en algún lado de la pantalla, así como dice *campos obligatorios, que dijera +Solo acepta números.

cómo la beisbol?

Con el tooltip, se puede dar mayor claridad de cada campo en la pantalla.

**Comment by jccastillo0007** [comment]
done.. puse el (+), porque los tooltip solo lo puedo poner en botones, pero no en campos de texto

**Comment by RigoFlores** [comment]
mejor poner la máscara a que solo acepte números.
cómo ves?

**Comment by RigoFlores** [comment]
está medio confuso todo... mejor solo indicar los obligatorios con el (*), y los que son solo números, por código poner la restricción, cómo ves?.
Los identificadores de origen y destino, solo son obligatorios cuando existe mas de un destino. Entonces, esos no llevan el *.

Por otro lado, las etiquetas tienen distinto tamaño, unas son muy pequeñas. Que todas queden como las de autotransporte.

**Comment by jccastillo0007** [comment]
ok, ya quite las etiquetas, y la captura ahora inicia del lado derecho, como cuando se usan números, pero no puedo evitar que capturen letras... 

Ya quite el asterisco de los identificadores de origen y destino

Creo que el tama;o del font usado en algunos componentes es menor, pues se trata de componentes dinámicos, no sé como cambiar eso, sigo investigando

**Comment by RigoFlores** [comment]
Entré a pruebas y siguen chuecos los asteriscos:

Origen - Ubicación Es obligatorio. 
Origen - Identificador NO es obligatorio

Destino  - Ubicación Es obligatorio. 
Destino - Identificador NO es obligatorio
Destino - Distancia recorrida es obligatorio

Mercancías - cantidad y peso son obligados.

En distancia recorrida, cantidad y peso, agregar en las etiquetas (SOLO NÚMEROS).

Creo que eso es todo.

<img width="792" alt="obligados" src="https://user-images.githubusercontent.com/2912775/132375596-4fee2696-ca92-4b18-8c70-2226bf99fe9d.PNG">

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
le falta un (*) en la licencia del operador... 
Y ya ponerlo en pro...

**Comment by jccastillo0007** [comment]
ok, hoy lo subo

**Comment by RigoFlores** [comment]
jajaja, ya le agregaste el * ahora a arrendatario, propietario y notificado.
Ahí NO lleva, ya que no son obligatorios... chiaaaa

**Comment by jccastillo0007** [comment]
ok, ya se lo quite, no lo puedo poner solo en origen y destino, ya que se aplica a todos.

**Comment by RigoFlores** [comment]
ok, pues por ahí quedó faltando en origen, destino y operador... pero bueno, si es el mismo id pues ya que...
