### ISSUE TITLE
Complemento de carta porte - Agregar check box en pantalla de captura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1828]
Enviar como dato extra 4, dependiendo si está chequeado o no.
Checked  - SI
Not Checked - NO

con ello, se incluirá el contrato de la SCT en el carta porte

**Comment by jccastillo0007** [comment]
no me queda claro si además del dato extra 4, hay algo mas que hacer, a que te refieres con que se incluirá el contrato de SCT en el carta porte?

**Comment by jccastillo0007** [comment]
listo.

**Comment by RigoFlores** [comment]
lo del contrato se maneja desde el jasper. 
Si datoextra4 = SI, entonces lo imprime, en otro caso lo omite. Pero es del Jasper.
