### ISSUE TITLE
Complemento de carta porte - Dato extra 16, agregar internacional y/o material peligroso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1829]
Cuando se detecte que la mercancía es de un traslado internacional, incluir en un tercer renglón el dato de fracción arancelaria.

Cuando se detecte que la mercancía corresponde a material peligroso, agregar en ese tercer renglón los datos de Clave de Material y Clave del Embalaje. Si se capturó la descripción de embalaje, igualmente agregarla.

El dato extra 16, contiene todas las mercancías trasladadas en 2 renglones. Ahora se estaría agregando un tercer renglón solo en caso de internacional y/o material peligroso.

**Comment by jccastillo0007** [comment]
listo, solo en PRU

**Comment by RigoFlores** [comment]
llevar este cambio a pro
