### ISSUE TITLE
NOMINA - AGREGAR LISTA DE TIPOS DE HORA EXTRA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#183]
Aunque no es un catálogo, únicamente se aceptan los valores literales de 'Dobles' o 'Triples'. Lo podemos agregar a un listado

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
ya muestra la lista, pero ahora no permite eliminarlas. recodar que no siempre se pagan las horas extra.
1) ya existe un registro de horas extra
2) agrego otro registro (lo muestra vacío y en ceros, ok)
3) elimino el registro original
4) guardo
5) consulto nuevamente, y me muestra el registro original

**Comment by jccastillo0007** [comment]
Fixed
