### ISSUE TITLE
Complemento de carta porte - Misceláneos, cuando el domicilio tenga país distinto a México omitir el rfc en el XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1830]
para misceláneos, cuando el país del domicilio sea distinto a México, omitir incluir el RFC en el XML.
Aplica para origen, destino, operador, propietario, arrendatario y notificado (jeje, todos).

Para no modificar que el RFC sea opcional en el catálogo de miscelaneos, mejor lo omitimos cuando el país sea distinto a méxico, cómo ves?

**Comment by jccastillo0007** [comment]
listo, solo se modifico el catálogo de miscelaneos para que no fuera un dato forzoso

ya esta en pru y pro

**Comment by RigoFlores** [comment]
Está marcando un error... aparentemente si guarda el registro, pero eso no es claro para el usuario, ya que aparece el mensaje de error... Después de darle guardar, con el campo del RFC vacío, marca lo siguiente:

<img width="596" alt="rfcnulo" src="https://user-images.githubusercontent.com/2912775/131524906-1532d147-68f5-439e-93ef-cfb6c8f7aaf7.PNG">

**Comment by RigoFlores** [comment]
me salí de ese menú, volví a entrar y no... no guardó el registro...  según yo, no subiste el cambio, ya que el comportamiento es idéntico al que se tenía ayer..

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
?
