### ISSUE TITLE
Conector - Complemento de carta porte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1831]
Implementar los mismos ajustes de datos, que se envían al PDF en la versión WEB.

**Comment by RigoFlores** [comment]
Así es como está. De hecho me parece que está todo desordenado, cómo ves si lo organizamos con datos extra consecutivos?

datoExtra1= varios renglones por cada origen del carta porte
1) Origen1 - PREMIER AUTOCOUNTRY SA DE CV
2) JUME890620KB3
3) BLVD. PEDRO INFANTE PTE, 2995, Pueblo Bonito
4) Culiacan, SINALOA
5) Fecha Hora Salida: 2021-06-17

datoExtra2= varios renglones por cada destino dentro del carta porte
1) Destino1 - Tecnologias de Informacion Aplicada SA de CV
2) TIA101020BP4
3) Fray Luis de Leon 3051, 3051, Centro Sur
4) Queretaro, QUERETARO – DESTINO
5) Fecha Programada llegada: 02/07/2021

datoExtra3=Si/No – indica si se transporta material peligroso.
datoExtra4==SI/NO para imprimir contrato.
datoExtra5=
datoExtra6=
datoExtra7=
datoExtra8=
datoExtra9=
datoExtra10=
datoExtra11=


Datos del Transporte.
datoExtra12 =C3R3, ABAC123, 2020,
datoExtra13= operador
datoExtra14

datoExtra15=Contenido del Complemento de carta porte (del XML)
datoExtra16= (son 3 renglones por cada mercancía transportada)
1)	Bienes Transporta: 25101503  Unidad: PIEZA Clave Unidad: H87 Moneda: MXN Cantidad: 2.00 Peso en Kilogramos: 2,500.00 Valor Comercial: $2,400,000.00
2)	Descripción: 9BD265553M9182527 415554 RAM PROMASTER RAPID
3)	Fracción arancelaria; clave de material peligroso, clave de embalaje, descripción de embalaje

**Comment by jccastillo0007** [comment]
solo me faltan las pruebas

**Comment by jccastillo0007** [comment]
subi una version de facturat standalone, tiene la misma implementación de web

es el zip 11.0.1

**Comment by RigoFlores** [comment]
el dato extra 2, destino está distinto al web. Algo le está agregando. De hecho, creo que no está incluyendo en origen ni en destino, el estado, municipio..

En el tercer renglón, donde se reporta mercancías, hay que separar cada dato y etiquetas

**Comment by jccastillo0007** [comment]
no agrega estado ni municipio porque no se tienen los nombres... ya agregué las claves.

**Comment by jccastillo0007** [comment]
listo, subí otro release, para la otra, pon ejemplos de como se ve y como se debe ver , porque luego no entiendo lo que realmente quisiste decir.

**Comment by RigoFlores** [comment]
mira el XML va así, son datos del conector...

                <cartaporte:Ubicacion>
                    <cartaporte:Origen FechaHoraSalida="2021-05-07T10:00:00" NombreRemitente="JORGE DE JESUS PIÃ‘A" RFCRemitente="JEPJ870925KU7"/>
                    <cartaporte:Domicilio Calle="Av Universidad" CodigoPostal="76160" Colonia="0163" Estado="QUE" Localidad="01" Municipio="014" NumeroExterior="361" NumeroInterior="piso2" Pais="MEX"/>
                </cartaporte:Ubicacion>
                <cartaporte:Ubicacion DistanciaRecorrida="1000.0">
                    <cartaporte:Destino FechaHoraProgLlegada="2021-05-10T10:00:00" NombreDestinatario="ROBERTO FORS PAEZ" RFCDestinatario="FOPR681125BQ0"/>
                    <cartaporte:Domicilio Calle="Insurgentes" CodigoPostal="44770" Colonia="0388" Estado="JAL" Localidad="03" Municipio="039" NumeroExterior="1000" NumeroInterior="Depto C-503" Pais="MEX"/>
                </cartaporte:Ubicacion>

En el PDF el origen llega así, es decir sin municipio, localidad, estado... tampoco colonia
Origen1 - JORGE DE JESUS PIÃ‘A
JEPJ870925KU7
Av Universidad, 361

Fecha Hora Salida: 07/05/2021


El destino llega así, ese si incluye municipio y estado , pero además con una leyenda DESTINO, que sobra:

Destino1 - ROBERTO FORS PAEZ
FOPR681125BQ0
Insurgentes, 1000
039, JAL - DESTINO
Fecha Programada llegada: 10/05/2021

**Comment by RigoFlores** [comment]
creo que lo de mercancías ya quedó...

**Comment by jccastillo0007** [comment]
listo, yo creo que ahora si ya quedo.

Ojo, algunos de esos errores seguro pasan en web, pues copie exactamente el mismo código, a menos que fuera error de dedo cuando hice adaptaciones.

**Comment by RigoFlores** [comment]
no he podido validarlo, ya que se inyectó un error nuevo... como que está buscando por una variable que ahí no aplica...

fechaSolicitudCancelacion dice


<img width="784" alt="error" src="https://user-images.githubusercontent.com/2912775/133863162-7fd68114-588c-4405-b55c-3504f2a86fa4.PNG">

**Comment by jccastillo0007** [comment]
Ese debe ser un error en el template, en código no se maneja esa variable fechaSolicitudCancelacion, y el error dice que no se puede obtener el valor de esa variable, y no se puede porque no se manda, verifica el jasper

**Comment by RigoFlores** [comment]
oyes, en el dato extra1 y 2, para cada domicilio estoy viendo que falta el Código Postal, chiaaaa...
Tons en web también... 

Por lo pronto aquí, hay que agregar después del estado, el código postal, esto es: ", C.P. códigoPostal"

**Comment by jccastillo0007** [comment]
ok, done.

Ojo, en web no se da este caso, porque en web si tenemos los catálogos de paises y estados... tons ahi estamos bien

**Comment by RigoFlores** [comment]
Cerraré este para que no crezca demasiado.
Abriré otro con los detalles que aún existen.
