### ISSUE TITLE
Carta Porte - Completar datos en el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1832]
Para web...

Nuevos:

DatoExtra5 = "Clave Permiso: " + cvePermiso + "  No. Permiso: " + noPermiso
DatoExtra6 = "Aseguradora: " + Aseguradora + " No. Póliza: " + NoPoliza

Cambio en:
DatoExtra12, cambiar a : "Tipo de Vehículo:  " + cveVehículo + " Placa: " + placa + " Año: " + año  

solo en caso de  1 o 2 remolques según sea el caso, agregar también + "Remolque 1: " + claveRemolque 1 + "Placa: " + placaRemolque1 +  " Remolque 2" + claveRemolque2 + " Placa: " + placaRemolque2

DatoExtra13 cambiar a:  "Operador: " + operador + " Licencia: " + noLicencia

**Comment by jccastillo0007** [comment]
checale en pru, antes de subir a prod todos los cambios de este y el otro ticket 1827

**Comment by RigoFlores** [comment]
Hay un detalle, aquí están al revés los datos, la clave la despliega en el número de permiso y viceversa:
DatoExtra5 = "Clave Permiso: " + cvePermiso + " No. Permiso: " + noPermiso

Adicionalmente, en el datoextra1, se le antepone un NO. Supongo que dependiendo de la captura, podría ser un SI. Según vi, creo que es el SI o NO, de incluir contrato.

Por otro lado, en el transporte, en caso de datoExtra12, si el vehículo lleva remolque, no está incluyendo la información del remolque, como se solicitó arriba en el origen del issue.

**Comment by jccastillo0007** [comment]
listo

para el caso del datoExtra12, seguro que no lo manda? le pone un <enter> entre autotransporte y cada uno de los remolques.

**Comment by RigoFlores** [comment]
ya vi, lo manda en 2 o 3 renglones, eso no estaba considerado en el jasper, pero ya.
