### ISSUE TITLE
DescargaT - tickets de abastos, no está incluyendo el ID producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1834]
Para abastos, cada ticket que se incluye en una factura, se agrega como un producto.
El ID de ese producto (nodo concepto), debe ser el número de ticket, y hoy revisé un XML, que te envié por correo, y ahí se ve que no está incluyendo dicho ID en la factura.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
en pruebas jaló, tanto Fi como con usuario y pwd.
Hay que llevarlo a pro, a ver que tal
