### ISSUE TITLE
Complemento de Carta Porte - Miscelaneos, permitir omitir el domicilio SIN enviar país

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1837]
En misceláneos, el operador puede ir sin domicilio. 
Entonces si quiero capturar un operador sin domicilio no capturo ningún dato, pero a huevo manda el país al XML, y pues truena. 

Ahí veo de dos sopas:
a) Se agrega el famoso "seleccione uno" al listado de países y con ello el domicilio no enviará nada, al no tener ningún dato que enviar. Me parece que este asegura al usuario, que no capturó nada de domicilio.

b) Cuando en el domicilio del operador o de cualquier otro misceláneo solo exista el país, NO ENVIAR nada al XML referente al nodo domicilio correspondiente. Me parece que este es mas automático.

**Comment by jccastillo0007** [comment]
fixed

Tomé la opción a

**Comment by RigoFlores** [comment]
Varios detalles.
a) El país por omisión debería ser MEX, y adicionalmente podrán elegir lo de "seleccione uno". Hoy aparece "seleccione uno" por omisión.
b) Para registros ya existentes, no muestra el "seleccione uno", solo para registros nuevos.
c) Cuando elijo un operador (misceláneo) que solo tiene capturado RFC y Nombre sin domicilio, no manda el nodo operador al XML y marca error, ya que es obligatorio para autotransporte.

**Comment by jccastillo0007** [comment]
a y b, son mutuamente excluyentes... como se implementó el tema de seleccione uno , ya no se puede mostrar un pais por omisión, y el b ya tampoco se puede.

c) ya esta corregido
