### ISSUE TITLE
DescargaT - pone a pagados los tickets cuando capturas un ticket inexistente, pero los borra y no los incluye en la factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1838]
Estás capturando una factura con varios tickets. Todo bien.
Luego, capturas un número de ticket inexistente. Te indica que ese ticket no existe.
Enseguida capturas uno correcto... lo que hace la plataforma, es borrar de la pantalla todos los tickets previamente capturados.

Peero eso que significa?
a) Que esos tickets que borró, los pondrá a pagados una vez que se emita la factura.
b) Que esos tickets que borró, no los puedes volver a capturar, ya que si lo intentas, te dice que ya está capturado (siendo que lo borró de la pantalla). De alguna manera los mantiene en memoria, no así en pantalla.
c) Esos tickets que borró, NO los incluye en la factura... (ni como producto, ni en los totales, ni nada)... peeeero, si los pone como pagados y ahí está el pedo. Ya no se pueden facturar después.

Este issue, según yo ya se había reportado y corregido antes, pero bueno...

**Comment by jccastillo0007** [comment]
listo, ya le encontre lo chueco.

Checalo en pru

**Comment by RigoFlores** [comment]
Pues generando la remisión desde el mismo web, ya no se presenta el problema.
Hay que llevarlo a pro.
