### ISSUE TITLE
Conector - Complemento de carta porte, homologar PDF con el web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1839]
Generé un archivo con los mismos datos de un XML que hice en web pruebas.
Estoy viendo estas diferencias en el PDF:

En web, se ve así. De hecho, le sigue sobrando la palabra DESTINO, en los destinos:

<img width="826" alt="odw" src="https://user-images.githubusercontent.com/2912775/135678378-50d4b77b-f19c-4dd8-be8b-c3b8cccc1bc9.PNG">

En el conector, esa misma parte, se ve así. Ya se que son claves de colonia, pero no está presentando la colonia del origen:
<img width="826" alt="odc" src="https://user-images.githubusercontent.com/2912775/135678459-dff3c1c4-9d44-4840-83fb-aa5fddc395a3.PNG">

abriré otro comentario, para documentar la otra parte.

**Comment by RigoFlores** [comment]
Luego en la parte inferior:

en Web se ve bien todo, incluso los totales muestran la retención del IVA.

![image](https://user-images.githubusercontent.com/2912775/135678639-8923ad72-909e-4b8f-a62d-085fa9ad88ce.png)


Pero en el conector, se ve así:

<img width="820" alt="totcon" src="https://user-images.githubusercontent.com/2912775/135678912-be7e9c9d-bcd3-4f18-bdd4-73d33282d34c.PNG">

Entonces, en conector hay que revisar los datos extra: 5, 6, 13 y 12, ya que no son iguales que en el web.
Adicionalmente, no está mostrando el IVA retenido, que es la variable $F{montoRetencionIva1}

**Comment by RigoFlores** [comment]
Subo un zip (hay que renombrar la extensión), conteniendo el archivo de texto con lo que probé, y las 2 facturas.

[234_IIA040805DZ4_TIA101020BP4_01Oct2021_125518.SoyUnzip.Txt](https://github.com/jccastillo0007/eFacturaT/files/7269858/234_IIA040805DZ4_TIA101020BP4_01Oct2021_125518.SoyUnzip.Txt)

**Comment by jccastillo0007** [comment]
ya agregue el contenido que faltaba mostrar, datos extras 5,6,12,13

También subí la colonia del origen, que la estaba poniendo en otro renglon, el null que ves, se me hace que es el número ext, ya que en el archivo txt, tienes calle y número exterior junto

Lo del iva retenido, no encontré nada raro... puedes volver hacer la prueba y checa en el log si se manda o no.

**Comment by RigoFlores** [comment]
Lo de retenciones, si lo manda al XML, pero no lo manda al PDF. Esta es parte de la salida a consola cuando le puse el archivo que te mandé:

baseRetencionIva1=,baseRetencionIva2=,baseRetencionIva3=,tasaRetencionIva1=,tasaRetencionIva2=,tasaRetencionIva3=,montoRetencionIva1=,montoRetencionIva2=,montoRetencionIva3=,baseRetencionIsr1=1000.00,baseRetencionIsr2=,baseRetencionIsr3=,tasaRetencionIsr1=4.00,tasaRetencionIsr2=,tasaRetencionIsr3=,montoRetencionIs

**Comment by RigoFlores** [comment]
Los domicilios podrían o no llevar algún dato... 
obligatorios: calle, país, estado y CP
Los otros son opcionales.
Entonces, cuando alguno no se incluye, no debe ponerle null

**Comment by jccastillo0007** [comment]
chiaaaaa , me hiciste revisar a detalle algo bien chacarron, y tanto para que estes mandando ISR retenido y no IVA retenido... chiaaaa, los datos los manda correctamente en el ISR retenido.

baseRetencionIsr1=1000.00,
tasaRetencionIsr1=4.00
montoRetencionIsr1=$40.00,

La clave para IVA es 002 y para ISR es 001, en el archivo de texto estas enviando

concepto={78101800|FLETE 21  81  3334  1000482|1|E48|SERVICIO|SERVICIO DE FLETE||1000.00|1000.00|||||Traslados[1000|002|Tasa|16.00000|160.00|||||]Retenciones[|||||1000|001|Tasa|4.0000|40.0]

Por otro lado ya esta validando que no incluya null en el número exterior e interior.

**Comment by jccastillo0007** [comment]
chiaaaaa , me hiciste revisar a detalle algo bien chacarron, y tanto para que estes mandando ISR retenido y no IVA retenido... chiaaaa, los datos los manda correctamente en el ISR retenido.

baseRetencionIsr1=1000.00,
tasaRetencionIsr1=4.00
montoRetencionIsr1=$40.00,

La clave para IVA es 002 y para ISR es 001, en el archivo de texto estas enviando

concepto={78101800|FLETE 21  81  3334  1000482|1|E48|SERVICIO|SERVICIO DE FLETE||1000.00|1000.00|||||Traslados[1000|002|Tasa|16.00000|160.00|||||]Retenciones[|||||1000|001|Tasa|4.0000|40.0]

Por otro lado ya esta validando que no incluya null en el número exterior e interior.

**Comment by RigoFlores** [comment]
chiaaa, sicierto, era ISR y yo estaba desplegando el IVA retenido, chiaaaalesssss.

Pero lo del null, si lo sigue enviando. Con el mismo archivo de texto puedes probar.
Aquí te dejo la plantilla para el conector de carta porte, para que veas que envia null en el origen

[complementocartaporte.jrxml.txt](https://github.com/jccastillo0007/eFacturaT/files/7333737/complementocartaporte.jrxml.txt)

**Comment by jccastillo0007** [comment]
negativo, acabo de probar otra vez, y esto es lo que manda al jasper 

datoExtra1=Origen1 - Tecnologias de Informacion Aplicada SA de CV
TIA101020BP4
Fray Luis de Leon 3051, , 1317
014, QUE, C.P. 76090
Fecha Hora Salida: 01/10/2021

datoExtra2=Destino1 - Tecnologias de Informacion Aplicada SA de CV
TIA101020BP4
Insurgentes, 1200, 4943
4943, 039, JAL, C.P. 44210
Fecha Programada llegada: 10/05/2021

solo lleva una "," de más.... algo debe estar pasando en el jasper
