### ISSUE TITLE
NOMINA - CAMBIAR EL OBJETO PARA FECHA DE INICIO RELACION LABORAL

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#184]
Ahora mismo se tiene que recorrer mes por mes. Cuando el empleado tiene varios años de antigüedad, hay que recorrer muchos meses.
Debería ser un control, que permita capturar el mes, dia y año.

**Comment by jccastillo0007** [comment]
El objeto actual ya lo permite, después de que te abre el calendario, vuelve a darle click el text box y puedes escribir la fecha con formato DD/MM/YY

**Comment by RigoFlores** [comment]
NO ES INTUITIVO, PERO POR LO PRONTO LO ACEPTAMOS
