### ISSUE TITLE
Migrar BD de clientes de escritorio al web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1840]
Necesitamos entregar esto asap, ya pagó hoy. 
Pls.

[facturat_db.script.txt](https://github.com/jccastillo0007/eFacturaT/files/7281427/facturat_db.script.txt)

**Comment by jccastillo0007** [comment]
ya quedaron los clientes cargados, desde la base de datos.

el cliente ya tenia algunos creados, entonces es posible que se dupliquen algunos clientes.

Si llegan mas request de migraciones, voy a tener que volver a escribir código, porque ahorita hay muchos cambios manuales.

**Comment by RigoFlores** [comment]
Si, hay que trabajar en ello yo creo, ya que no quedó del todo bien.
Los acentos le parten la mami. Mira...
Los corregiremos manualmente, chiaaaa

<img width="644" alt="cliente" src="https://user-images.githubusercontent.com/2912775/136460597-68b97cee-b3d3-4277-b0fb-79d12d133d8a.PNG">
