### ISSUE TITLE
Carta Porte - Misceláneos operador, no envía los datos del operador

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1842]
En los datos del operador, se puede omitir el domicilio. De eso no hay problema.
En el caso del operador, el RFC es obligatorio, tampoco hay problema, siempre que si se capture, je.

Pero en el caso del operador, el nombre podría omitirse. 
Si capturo un operador sin nombre y lo incluyo en en la captura del carta porte, NO ENVÍA los datos del operador, esto es RFC y domicilio (si es que se capturó).

En resumen, para misceláneos/operadores. El nombre es opcional y si no se captura, debe enviarse el RFC en el nodo Operador. Ahora mismo no envía el nodo operador y marca error:

**_El nodo "Operadores" debe existir, siempre que exista el nodo  "Mercancias:AutotransporteFederal"._**

**Comment by jccastillo0007** [comment]
hay un problema para implementar esta funcionalidad, se ocupa forzosamente el nombre o el nickname del operador

Lo que no sé, es si podemos forzar a capturar un nickname o identificador, si es que no capturan un nombre ???

**Comment by RigoFlores** [comment]
Si claro, el Identificador DEBE ser un dato obligatorio, ya que es lo que nos permite identificarlo al momento de la captura del complemento.
Si solo dejáramos el RFC por ejemplo, pues posiblemente no nos diga mucho. Pero con el Identificador "el cuñado", pues ya sabemos quién es, jeje.
En definitiva, el identificador es un dato obligatorio para todo misceláneo y mercancía.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
listo...
