### ISSUE TITLE
Carta Porte - Misceláneos, al editar poder elegir por RFC, Nombre y también por ID.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1843]
Al momento de editar un misceláneo, ahora mismo podemos elegirlo por RFC o Nombre.
Pero no podemos elegir por Identificador.
Si el RFC o nombre es el mismo para varios registros (lo cuál es común con mismo cliente, distintas ubicaciones o patios), es un problema ubicar el que queremos editar.

Entonces, para editar permitir elegir también por ID el misceláneo.

**Comment by jccastillo0007** [comment]
done, en pru
