### ISSUE TITLE
Carta Porte - Miscelaneos, agregar un checkbox para identificar el tipo de registro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1844]
El catálogo de misceláneos sirve para capturar origen, destino, operador, propietario, arrendatario y notificado.

Entonces, para cada registro, agregar un checkbox a elegir entre:

a) Origen
b) Destino 
c) Operador
d) Propietario
e) Arrendatario
f) Notificado

Y así en la pantalla de captura del complemento, dependiendo de donde se esté capturando, solo mostrar los registros que correspondan, según sea el caso.

He visto que conforme el cliente tiene mas orígenes, destinos, operadores, se complica un poco la selección de los mismos.

Incluso para editar en los catálogos, también poder aplicar o no el filtro para elegir el registro a editar.

**Comment by RigoFlores** [comment]
La otra opción es de plano separar los catálogos, aunque tendrían prácticamente los mismos campos.

**Comment by jccastillo0007** [comment]
listo... ya esta en PRU.

Deje abierta la posibilidad de que un mismo misceláneo , lo elijan como origen, destino, operador, etc... es decir mas de una opción.
