### ISSUE TITLE
Complemento Carta Porte - Internacional, dice el SAT que siempre no

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1845]
Anteriormente jalaba bien algo que hicimos, donde incluso yo le cuestioné a finkok porqué decían que tenía que ir, cuadno según yo no debería incluirse.

Bueno, pues ya se dieron cuenta del error, y ahora para transporte internacional (y en general para todo), NO aplica el tipo de estación a nivel nodo Ubicación. Ejemplo:

cartaporte:Ubicacion DistanciaRecorrida="1000.0" **TipoEstacion="03"**>
   cartaporte:Destino FechaHoraProgLlegada="2021-10-02T00:00:00" NombreDestinatario="Tecnologias de Informacion Aplicada SA de CV" RFCDestinatario="TIA101020BP4"/>
   cartaporte:Domicilio Calle="AV UNIVERSIDAD" CodigoPostal="76090" Colonia="1317" Estado="QUE" Municipio="014" NumeroExterior="361" NumeroInterior="PISO 2" Pais="MEX"/>
cartaporte:Ubicacion>

es eliminar en todo caso, el tipo de estación.
Antes se ponía para transporte internacional, ahora ya no debe ir.

**Comment by RigoFlores** [comment]
eso mismo puedes checar que cambió, en los archivos que te envié anteriormente, que todos jalaban y ahora ya los de internacional, ninguno jala. jaja

**Comment by jccastillo0007** [comment]
ok, si entendí bien, la idea es quitar tipo de estación del nodo ubicación, cierto

**Comment by RigoFlores** [comment]
pues digamos a rajatabla... si quitarlo... ese se ocupa en marítimo, aéreo y ferroviario.
