### ISSUE TITLE
Carta Porte 2.0 - Generales web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1847]
Los generales del web, se refiere a cambiar al nuevo xsd del complemento.
Enviar 2.0 en el campo de versión.
Modificar las urls que correspondan.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
no puedo validarlo, marca error...

738 : Prefijo y namespace con error: ns3 - http://www.sat.gob.mx/CartaPorte20 (3)

**Comment by jccastillo0007** [comment]
listo, puedes continuar con tus pruebas

**Comment by RigoFlores** [comment]
Ese error ya se quitó, ahora marca que no se reporta el nodo de figura transporte, es decir no está formando bien el XML en esa sección. 
Mis pruebas iniciales, solo incluyen al operador.

 CP172 : No existe el nodo "FiguraTransporte:TiposFigura" o se registro sin información.

y si está vacío, así lo manda...

            <cartaporte20:FiguraTransporte/>
        </cartaporte20:CartaPorte>

**Comment by jccastillo0007** [comment]
listo ya puedes continuar las pruebas

**Comment by RigoFlores** [comment]
pues sigue sin timbrar, pero cerraré este issue y cualquier otra cosa, abriré nuevos.
