### ISSUE TITLE
Carta Porte 2.0 - Misceláneos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1848]
Agregar el campo:

Número de licencia (aplica solo para operadores, pero bueno ahí que esté el campo disponible, libre captura; si aparece solo cuando le den check a operadores, sería ideal).

Al final de la pantalla, agregar los campos de :

- ParteTransporte, se elegirá de una lista, catálogo del SAT correspondiente.
- NumRegIdTribFigura (Número de Registro, equivalente el RFC para otros países. Texto libre).
- ResidenciaFiscalFigura (Residencia Fiscal, tomado del listado de países).

**Comment by RigoFlores** [comment]
De este issue, lo estrictamente necesario es agregar la parte transporte, incluso sin el catálogo. Lo cuál está limitado, pero así puede salir.
Tenemos un cliente que ocupa el nodo propietario.

Lo de incluir la licencia en el catálogo, implicaría quitar ese campo de la pantalla de captura del complemento. Pero pues ya se verá después.

**Comment by jccastillo0007** [comment]
done.
