### ISSUE TITLE
nomina-conector - no reporta retenciones de ISR en XML estándar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#185]
No se está reportando completamente las retenciones de impuestos (en concreto ISR), cuando la nómina se genera desde el conector.

**Comment by jccastillo0007** [comment]
fix it... el tema es que buscaba siempre la tasa de ISR.... ahora ya se dejo opcional

**Comment by RigoFlores** [comment]
EN LA ÚLTIMA VERSIÓN, YA REGRESÓ EL ERROR...

**Comment by jccastillo0007** [comment]
Fix it.

La variable totalImpuestosTrasladados=0 debe ser indicada con =0.
