### ISSUE TITLE
Carta Porte 2.0 - Pantalla de captura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1850]
Cuando agreguen un origen o destino, poner el valor del atributo tipoUbicacion  (nodo ubicación)
Cuando se trate de un traslado internacional, tomar el dato de PaisOrigenDestino (header), del domicilio que tenga un país distinto a MEX.
Calcular el PesoBrutoTotal (nodo mercancías), de la suma de pesoEnKg del nodo mercancía
Incluir la clave de unidad del peso bruto total, como KGM

En los seguros tenemos dos campos hoy; pero ahora necesitamos 3 grupos de datos seguros: Responsabilidad Civil, Medio Ambiente y Carga; todos ellos con 2 campos: Aseguradora y Póliza. Agregar un campo al final: Prima Seguro.

Eliminar el dato de número de licencia, ya que se capturará en el catálogo de misceláneos.

**Comment by RigoFlores** [comment]
De lo aquí listado, queda pendiente lo siguiente:
1) Cuando se trate de un traslado internacional, tomar el dato de PaisOrigenDestino (header), del domicilio que tenga un país distinto a MEX.
2) En los seguros tenemos dos campos hoy; pero ahora necesitamos 3 grupos de datos seguros: Responsabilidad Civil, Medio Ambiente y Carga; todos ellos con 2 campos: Aseguradora y Póliza. Agregar un campo al final: Prima Seguro.

**Comment by jccastillo0007** [comment]
NO CREAR TICKETS CON MULTIPLES REQUERIMIENTOS

LISTO
