### ISSUE TITLE
Conector Carta Porte 2.0 - Figura Transporte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1852]
No está reconociendo esta sección de **Partes transporte**:

//FiguraTransporte={TipoFigura|RFCFigura|NumLicencia|NombreFigura|NumRegIdTribFigura|ResidenciaFiscalFigura}
//PartesTransporte={parteTransporte|calle|noExt|noInt|colonia|localidad|referencia|municipio|estado|pais|CP},{},...{}

FiguraTransporte=01|CAAJ7506072P2|FED1234|ADRIAN MORENO GARCIA||
**PartesTransporte={|Insurgentes|1000|Depto C-503|0388|03||039|JAL|MEX|44770}**

Partes transporte, es un subnodo (opcional) que puede llevar un solo atributo y a la vez, puede o no incluir el subnodo domicilio.

Hay que considerar la etiqueta, solo como Figura, en lugar de FiguraTransporte

**Comment by jccastillo0007** [comment]
listo... 
ojo.. cuando se incluyen mas de una parte transporte, no se separa por comas, solo por {}{}{}{}
