### ISSUE TITLE
Conector Complemento de carta porte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1854]
Tiene aún varios detalles:

a) Cuando se trate de complemento de carta porte, debe buscar por la plantilla complementocartaporte.jrxml
b) No despliega los datos de los remolques (dato extra 8, renglón 4).
c) No está parseando los datos de propietario, arrendatario,  para partes transporte. Indicar un ejemplo.
d) Para que muestre las descripciones de las claves, las podemos pedir como parte de la info del conector. Así estaría bien?

**Comment by jccastillo0007** [comment]
listo a, b y c

para d, si esta bien si se incluyen en el conector.

**Comment by jccastillo0007** [comment]
no es necesario el ejemplo para el c, ya que el error estaba en el código no en el txt.
Este es el txt que uso para probar 
[Ingreso 2.0.txt](https://github.com/jccastillo0007/eFacturaT/files/7622456/Ingreso.2.0.txt)

**Comment by RigoFlores** [comment]
el punto c sigue algo incompleto... ya parsea el rfc y nombre del destinatario, y también lo de partes transporte, peeeero no así el domicilio.
Según yo, el formato del txt para esta sección, debería ser:

FiguraTransporte=02|CAAJ7506072P2||NOMBRE DEL PROPIETARIO|||Insurgentes|1000|Depto C-503|0388|03||039|JAL|MEX|44770}{PT01|Insurgentes|1000|Depto C-503|0388|03||039|JAL|MEX|44770
PartesTransporte={PT01}

Ya que el domicilio va independiente a partes transporte en el XML. Ahora mismo, no parsea el domicilio.

**Comment by jccastillo0007** [comment]
si, de acuerdo, el domicilio va en figura transporte, de hecho el domicilio no estaba ni en el xml ni en el pdf... ya quedo ahora si

este es el archivo utilizado
[Ingreso 2.0.txt](https://github.com/jccastillo0007/eFacturaT/files/7630678/Ingreso.2.0.txt)
.
