### ISSUE TITLE
Carta Porte 2.0 - Homologar el PDF a la versión de conector.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1855]
Está el documento word en la ruta del dropbox:

Dropbox\FacturaT\PROYECTOS\CFDI3.3\cartaPorte\v2.0\jasper\Mapeo PDF 20.docx

**Comment by RigoFlores** [comment]
ya subí la nueva plantilla jasper a pru, se llama complementocartaporte.jrxml

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
no está llegando el datoextra12, que es el propio complemento, es decir el XML

**Comment by jccastillo0007** [comment]
fixed
