### ISSUE TITLE
CCP WEB - no acepta mas de 1 mercancía

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1856]
Marca el error :

2021-12-02 18:20:38,046 DEBUG [http-nio-8080-exec-130] (SealerPACProcess.java:543) - El atributo "Mercancias:PesoBrutoTotal" no existe o el valor de este atributo no corresponde a la suma de los atributos "Mercancias:Mercancia:PesoEnKg".

Y es que cuando se trata de mas de 1 mercancía, el valor de PesoBrutoTotal, debe ser la suma del valor de PesoEnKg de cada mercancía.

**Comment by jccastillo0007** [comment]
listo, ya lo esta sumando correctamente, peeeero no sé si se deba multiplicar por la cantidad de cada mercancia

**Comment by RigoFlores** [comment]
Esto dice el estándar...
_Atributo requerido para indicar en kilogramos el peso estimado de los bienes y/o mercancías que se trasladan en los distintos medios de transporte._
Entiendo que el parámetro a nivel de mercancía, es el peso de todo el nodo... es decir cantidad x peso unitario...  al final, eso lo captura el usuario.
