### ISSUE TITLE
CCP v2.0 - transporte internacional, agregar PaisOrigenDestino al header del complemento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1858]
Cuando se trate de un traslado internacional, tomar el dato de PaisOrigenDestino (header), del domicilio que tenga un país distinto a MEX.
Sabemos que es un traslado internacional, porque ya sea el origen o el destino tiene una clave de país, distinta a MEX. Cuando se detecta eso, aplica la lógica de internacional, y en este caso, para la v2.0 se agregó ese atributo el header.

**Comment by jccastillo0007** [comment]
done
