### ISSUE TITLE
CCP v2.0 - misceláneos, no incluye el rfc para propietario, arrendatario o notificado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1859]
La neta solo probé para propietario, pero asumiría que es lo mismo.
Aunque está capturado el RFC, no lo está enviando al nodo de propietario y marca error.

2021-12-04 15:55:28,619 DEBUG [http-nio-8080-exec-77] (CFDManager.java:1185) - update status : 3 : CP173 : El valor registrado en el atributo "TiposFigura:RFCFigura" no se encuentra en la lista de RFC inscritos no cancelados del SAT (l_RFC), está vacío o ya se registro el atributo "TiposFigura:NumRegIdTribFigura".

BTW, lo de la captura de la licencia en el catálogo quedó bien, si lo lleva al XML

**Comment by jccastillo0007** [comment]
fixed, el error estaba en notificado y propietario, nunca se habia enviado por cierto.

**Comment by RigoFlores** [comment]
Ahora no envía lo capturado en parte transporte. 
Aplica solo para propietario y arrendatario, pero no importa (es decir eso no lo validaremos por lo pronto), siempre que se capture tiene que enviar la clave de parte transporte.

            <cartaporte20:FiguraTransporte>
                <cartaporte20:TiposFigura NombreFigura="RIGOBERTO FLORES" NumLicencia="FED123" RFCFigura="FOPR681125BQ0" TipoFigura="01"/>
                <cartaporte20:TiposFigura NombreFigura="ramiro juárez" RFCFigura="JUME890620KB3" TipoFigura="02">
                    <cartaporte20:Domicilio Calle="calle 21" CodigoPostal="07600" Estado="CIUDAD DE MEXICO" NumeroExterior="118" Pais="MEX"/>
                </cartaporte20:TiposFigura>
            </cartaporte20:FiguraTransporte>

**Comment by jccastillo0007** [comment]
fixed, de hecho solo el operador agregaba parte transporte... 

Ya esta en todas las opciones

**Comment by RigoFlores** [comment]
Si lo incluye solo si lo capturas, eso ya está bien.
 
Peeeero, ahora no está enviando el municipio en el domicilio del propietario, supongo arrendatario también.
Y es que por lo pronto, el PAC está validando que se incluya el municipio. 
Supongo luego podrían eliminar esta validación, pero el punto es que si en el domicilio del propietario está incluido el municipio, entonces pues si debería enviarlo. (clave del municipio).

**Comment by jccastillo0007** [comment]
fixed
