### ISSUE TITLE
CCP v2.0 - implementar captura híbrida por archivo csv

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1861]
ya envié el correo con toda la info.

**Comment by RigoFlores** [comment]
[Ejemplo.csv](https://github.com/jccastillo0007/eFacturaT/files/7656090/Ejemplo.csv)

este es el archivo.

**Comment by jccastillo0007** [comment]
Oye, el archivo esta separado por comas no por pipes "|" como habias dicho...

Pueden eliminar los dos primeros renglones? 
La idea es mostrar en pantalla todas las lineas cierto? tal como si ya hubieran seleccionado n mercancias en la pantalla, los datos a mostrar serían los mismos que están disponibles ahorita para mercancias, es decir, no se mostrarán todos los datos que vienen en el archivo, esos datos se tomarán en cuenta al momento de crear el complemento

**Comment by RigoFlores** [comment]
este archivo viene del excel.
Esto es, ellos lo toman y lo salvan como csv.
Y si, pediré que le quiten los 2 primeros renglones.

El segundo caso de la captura híbrida, es por el WS.
El tercer caso, si es un archivo con extensión csv, pero internamente, un solo registro separado por |

**Comment by RigoFlores** [comment]
respondiendo a esto:

**La idea es mostrar en pantalla todas las lineas cierto? tal como si ya hubieran seleccionado n mercancias en la pantalla, los datos a mostrar serían los mismos que están disponibles ahorita para mercancias, es decir, no se mostrarán todos los datos que vienen en el archivo, esos datos se tomarán en cuenta al momento de crear el complemento**

Afirmativo, debemos mantener la consistencia con las pantallas actuales. Los datos no mostrados, pues si se considerarán como bien dices, para enviar al equiemel...

**Comment by RigoFlores** [comment]
Marca XML mal formado, y entiendo que se debe a que la clave de unidad, la estás tomando como unidad.

Clave de Unidad es obligatoriom y es el dato que si viene en el archivo.
Unidad es opcional, y no viene en el archivo csv.

creo que con eso ya quedaría.

**Comment by RigoFlores** [comment]
OYE, CÓMO LE VAMOS A HACER PARA PERSONALIZAR EL FORMATO DEL ARCHIVO.
ASÍ DE ENTRADA ESTE FORMATO APLICA CUANDO EL RECEPTOR DEL CFDI SEA DVC910102VDA.

LIMITAREMOS TAMBIÉN EL EMISOR?

**Comment by jccastillo0007** [comment]
yo creo que si, hay que limitarlo por ambos, si por ahi cae otro emisor con el mismo requerimiento, ya chingamos

**Comment by RigoFlores** [comment]
si no se complica mucho, pues si, por emisor y receptor... en otro caso solo por receptor + plugin

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ya timbra, pero al cargar mercancías, agrega unos renglones vacíos que hay que quitar.
mira prueba con este archivo, es una sola línea, y le agrega otra vacía
[EjemploBase.csv](https://github.com/jccastillo0007/eFacturaT/files/7672700/EjemploBase.csv)
.

**Comment by RigoFlores** [comment]
ya vi, que la línea que le agrega es como "el encabezado" de "elija una opción". Se elimina y ya, pero sería mejor que no apareciera.

Ya timbró. Solo falta restringirlo para lo siguiente en producción:
Emisor: MPB041122H93
Receptor: DVC910102VDA

**Comment by RigoFlores** [comment]
Estoy probando en pru, con el archivo anexo y pasa lo siguiente. Ni siquiera me pude ir a pro.

[Copia de Ejemplo01_ventana.csv](https://github.com/jccastillo0007/eFacturaT/files/7759078/Copia.de.Ejemplo01_ventana.csv)



a) le tengo que capturar el ID destino y origen

b) Al cargar las mercancías, el primer renglón lo pone vacío, y además no incluye la primera mercancía.

c) marca error al timbrar...CP154 : El atributo "Mercancia:Moneda" no existe o está vacío, o no existe el atributo "Mercancia:ValorMercancia". (3)

**Comment by jccastillo0007** [comment]
a => fixed
b => renglón vacío fixed, respecto a la primer mercancia, el archivo de texto trae un character raro al inicio, que no se percibe con un editor de texto, mira:
![Screen Shot 2021-12-21 at 20 26 44](https://user-images.githubusercontent.com/2245679/147024700-3b002768-d541-4a77-872a-b1986d6a063b.png)


c) => el archivo trae comillas en los datos del precio de las mercancias 2 a la 4, y por eso ya no llega a parsear la moneda, chiaaaa

**Comment by jccastillo0007** [comment]
por cierto, el log va a desplegar una linea como esta:

2021-12-21 20:23:39,098 DEBUG [http-nio-8080-exec-70] (ComplementoCartaPortePanel.java:383) - line read : ï»¿1,A04-27478-036,7,25181608,,XME,Z01,39,116.40,814.79,NO,,Soportes colgantes de montaje,USD

Para que veas lo que se lee del archivo... ahi se ve el character raro que te digo

**Comment by jccastillo0007** [comment]
con el archivo original que me enviaste, si hace el parsing bien
[Ejemplo.csv](https://github.com/jccastillo0007/eFacturaT/files/7759549/Ejemplo.csv)

**Comment by RigoFlores** [comment]
OK, ya quedó listo.
Todo lo hice desde excel.
Le eliminé la info que no se ocupa, incluyendo el logo. Dejé solo mercancías.
En los campos numéricos, le di formato para no incluir comas (,).
Y lo salvé como csv.

con eso no tuvo problemas
