### ISSUE TITLE
CCP v2.0 - Captura híbrida, acotar su uso.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1862]
Ya timbró. Solo falta restringirlo para lo siguiente en producción:
Emisor: MPB041122H93
Receptor: DVC910102VDA

**Comment by jccastillo0007** [comment]
ups resulta que en la pantalla del complemento, no tengo disponible el rfc receptor, solo el emisor... mejor solo hay que validar el emisor, como quiera, él es el que nos paga por el proyecto, a menos que el costo del desarrollo se aplique por RFC receptor ?

**Comment by jccastillo0007** [comment]
por cierto, deje también el rfc IIA... para poder seguir haciendo pruebas

**Comment by RigoFlores** [comment]
ok, ahora aguanta antes de llevarlo a pro
