### ISSUE TITLE
CCP v2.0 Traslado - cargar las mercancías a los conceptos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1863]
Dar la opción, si que sea opcional, un botón en la pantalla de captura del complemento, que al darle click, las mercancías ya capturadas en el complemento, se repliquen en los conceptos del CFDI tipo traslado... cada vez que le den click, borrará todos los conceptos del CFDI estándar y cargaría las mercancías que en ese momento estén capturadas en la pantalla.

Según me comentaron, los del WS pepsi, nuestro cliente debe generar traslado, entonces tendrían que capturar manualmente las mercancías que llegan por ws en los conceptos, y así que pinches ventaja les ofrecemos???

Hay que hacerlo. Pero que sea opcional, ya que el SAT puede pinches cambiar de opinión...

**Comment by RigoFlores** [comment]
Este es el mapeo.
Se necesita para el tema del WS.
OJO, solo aplica para traslados.

<img width="659" alt="mapeo mercancias vs conceptos" src="https://user-images.githubusercontent.com/2912775/146426656-13703f86-c7f8-4ace-915a-f8e81bf0a81e.PNG">

**Comment by jccastillo0007** [comment]
haber checale

**Comment by RigoFlores** [comment]
negativo, marca error 115.

2021-12-20 11:15:55,739 ERROR [http-nio-8080-exec-7] (Errors.java:65) - 115 : Error al generar CFD

**Comment by jccastillo0007** [comment]
encontre un error, y ya lo arreglé, no estaba poniendo el total del producto.

checale

**Comment by RigoFlores** [comment]
cerca la bala... cuando hay mas de una mercancía, en el cfdi estándar se reporta la cantidad, pero el valor unitario y el importe los reporta iguales, y marca error.

hay de 2 sopas:

En mercancías se maneja el valor de mercancía = importe, y cantidad. Entonces, el precio unitario a nivel concepto sería = valor mercancia / cantidad...

la otra es enviar a conceptos, tanto el precio unitario como el importe = 0.00, ya que como quiera el traslado sale con 0.00
quizás esta sería la mas coherente, y hace alusión a un issue que levanté hace meses y que puse "no perdamos de vista este detalle",... jejeje somos unas gavers

**Comment by RigoFlores** [comment]
Ejemplo, esta mercancía:
<cartaporte20:Mercancia BienesTransp="40171500" Cantidad="63.0" ClaveUnidad="X4A" Descripcion="Tubos y tuberÃ­as comerciales" Moneda="USD" PesoEnKg="1.5" Unidad="X4A" ValorMercancia="2737.35"/>

la reporta así:

<cfdi:Concepto ClaveProdServ="40171500" NoIdentificacion="07-23715-001" Cantidad="63.00" ClaveUnidad="X4A" Unidad="X4A" Descripcion="Tubos y tuberÃ­as comerciales Tubos y tuberÃ­as comerciales" ValorUnitario="2737.350000" Importe="2737.350000"/>

aquí no olvidemos que la fórmula de importe= cantidad x valor unitario, y ahí es donde truena.
por eso, enviar el 0.0 para precio unitario e importe, resuelve el pedo.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
ahora esto:

                <cartaporte20:Mercancia BienesTransp="25101503" Cantidad="4.0" ClaveUnidad="H87" Descripcion="9BD265553M9182527 415554 RAM PROMASTER RAPID" Moneda="MXN" PesoEnKg="7500.0" Unidad="PIEZA" ValorMercancia="2400000.0"/>

lo pasó así:

        <cfdi:Concepto Cantidad="4.00" Descripcion="" ValorUnitario="0.000000" Importe="0.000000"/>

faltó la descripción, la clave del sat, la clave de unidad, la unidad (opcional).

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
ok, validé para ccp ingreso y no llevó las mercancías... bien.
