### ISSUE TITLE
CCP v2.0 - Captura Híbrida de mercancías formato FT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1864]
Hacer este separado por comas o por pipes.
Por comas, lo podrían generar desde excel. 

Por pipes, creo que solo desde un editor de texto.

igual y separado por comas es buena opción...

[layoutFTMercancias.txt](https://github.com/jccastillo0007/eFacturaT/files/7681445/layoutFTMercancias.txt)

**Comment by jccastillo0007** [comment]
ya estoy haciendo este requerimiento... comentarios del layout

MaterialPeligroso no se ocupa, se define si existe CveMaterialPeligroso

Pedimentos, funcionaria solo para un pedimento, ya que si son varios pedimentos van separados por comas, pero en este caso la separación por coma, no jalaria ya que se usa para separar todos los campos

**Comment by RigoFlores** [comment]
por un lado es si es material peligroso o no...
por otro lado, es la clave del material peligroso..

lo de un solo pedimento, por lo pronto, si puede ser...

**Comment by RigoFlores** [comment]
MaterialPeligroso|   Sí/No
CveMaterialPeligroso|  Clave de Material peligroso
Embalaje|       clave de embalaje
DescripEmbalaje    descripción del embalaje

**Comment by RigoFlores** [comment]
lo de varios pedimentos, podríamos separarlos por punto y coma... ;
pero de inicio, puede ir con un solo pedimento

**Comment by jccastillo0007** [comment]
Material peligroso = si / no, se asume si se informa clave de material peligroso

**Comment by jccastillo0007** [comment]
listo, por ahora no se usan clave STCC y material peligroso.. pero si hay que enviarlos en el archivo, mientras vemos como queda, el parseo del archivo si espera esos datos.

**Comment by RigoFlores** [comment]
no, no me carga nada... si tienes el archivo con el que estás probando, súbelo aquí pls...

**Comment by jccastillo0007** [comment]
puedes iniciar con este archivo
[layoutFTMercancias.txt](https://github.com/jccastillo0007/eFacturaT/files/7760065/layoutFTMercancias.txt)

**Comment by RigoFlores** [comment]
en este archivo, no está parseando la moneda. 
y pues al timbrar, marca ese error...
[ejemploFT.txt](https://github.com/jccastillo0007/eFacturaT/files/7765520/ejemploFT.txt)

**Comment by jccastillo0007** [comment]
listo
