### ISSUE TITLE
Tipos de CFDI en pantalla de facturación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1865]
Actualmente tenemos estos tipos de CFDI, en la pantalla de facturación:

<img width="189" alt="tipos CFDI" src="https://user-images.githubusercontent.com/2912775/146621053-fce86dde-ce9f-4fc9-9fa8-bfb0dcb91867.png">

Hay que eliminar nota de cargo, recibo de nómina y egreso.
Con ello estará mas limpia esa selección.

**Comment by jccastillo0007** [comment]
que ya no se usan esos ?

**Comment by jccastillo0007** [comment]
done, luego no me vayas a pedir que los vuelva a poner ...

**Comment by jccastillo0007** [comment]
cancelado el cambio... si elimino lo que se pide, al momento de facturar truena en varios lados... ya que se analiza que tipo de cfdi emitieron, y eso se hace con el arreglo de tipos que se tenía, puedo arreglar eso, pero no ahorita que hay muchas otras cosas que hacer
