### ISSUE TITLE
Captura Híbrida - Pepsi (web service) tiene detalles

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1866]
a nivel de XML:

No está reportando los nodos ubicaciones
No está reportando el total de distancia recorrida

        <cartaporte20:CartaPorte TranspInternac="No" Version="2.0">
            <cartaporte20:Ubicaciones/>

**Comment by jccastillo0007** [comment]
si los esta reportando, chiaaa

 <cartaporte20:CartaPorte TranspInternac="No" Version="2.0">
            <cartaporte20:Ubicaciones>
                <cartaporte20:Ubicacion FechaHoraSalidaLlegada="2021-11-19T00:00:00" IDUbicacion="OR107401" RFCRemitenteDestinatario="URE180429TM6" TipoUbicacion="Origen">
                    <cartaporte20:Domicilio CodigoPostal="08800" Pais="MEX"/>
                </cartaporte20:Ubicacion>
                <cartaporte20:Ubicacion DistanciaRecorrida="20.0" FechaHoraSalidaLlegada="2021-11-19T00:00:00" IDUbicacion="DE105502" RFCRemitenteDestinatario="XAXX010101000" TipoUbicacion="Destino">
                    <cartaporte20:Domicilio CodigoPostal="01280" Pais="MEX"/>
                </cartaporte20:Ubicacion>
            </cartaporte20:Ubicaciones>
            <cartaporte20:Mercancias NumTotalMercancias="2" PesoBrutoTotal="4058.2" UnidadPeso="KGM">
                <cartaporte20:Mercancia BienesTransp="24112702" Cantidad="5.0" ClaveUnidad="H87" Descripcion="Tarimas de plástico" PesoEnKg="115.0" Unidad="Pieza"/>
                <cartaporte20:Mercancia BienesTransp="50202306" Cantidad="240.0" ClaveUnidad="Caja" Descripcion="Refrescos" PesoEnKg="3943.2" Unidad="Caja"/>
                <cartaporte20:Autotransporte NumPermisoSCT="234234" PermSCT="TPAF01">
                    <cartaporte20:Seguros AseguraRespCivil="AXXA" PolizaRespCivil="AXXA001"/>
                </cartaporte20:Autotransporte>
            </cartaporte20:Mercancias>
            <cartaporte20:FiguraTransporte>
                <cartaporte20:TiposFigura NombreFigura="RIGOBERTO FLORES" NumLicencia="FED123" RFCFigura="FOPR681125BQ0" TipoFigura="01"/>
            </cartaporte20:FiguraTransporte>
        </cartaporte20:CartaPorte>

**Comment by jccastillo0007** [comment]
y ya corregí lo del total distancia recorrida

**Comment by RigoFlores** [comment]
No está reportando el estado y con ello marca error...
hasta en tu ejemplo se nota eso, jajaja

2021-12-20 11:23:00,118 DEBUG [http-nio-8080-exec-9] (CFDManager.java:1185) - update status : 3 : CP143 : El atributo "Domicilio:CodigoPostal" no contiene una clave del catálogo de "c_CodigoPostal" cuando la clave del país es "MEX" o la clave registrada no corresponde con el valor del atributo "Domicilio:Estado", "Domicilio:Municipio" y "Domicilio:Localidad"; o este está vacío.

**Comment by jccastillo0007** [comment]
listo, ya esta arreglado este issue, y ya esta mandando el pdf y xml a gepp.
