### ISSUE TITLE
El cálculo base IEPS del IVA no reporta bien la base del cálculo en los impuestos del concepto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1869]
En el nodo concepto, se reportan los impuestos.
Para los impuestos trasladados (IVA y/o IEPS), se debe reportar la base del cálculo.

El cálculo estándar, parte que la base para el IVA es = (cantidad x PrecioUnitario) - descuento
Cuando se trata del IVA base IEPS, entonces la base es = (cantidad x PrecioUnitario) - descuento + **_MontoIEPS_**

El cálculo del IVA base IEPS, lo hace bien, pero la base la reporta incorrectamente. En este caso, la base del IVA (base IEPS) debería ser 18,109.74, pero lo reporta como 14,316.00

<img width="946" alt="baseIEPS" src="https://user-images.githubusercontent.com/2912775/146828649-e1afd695-3f34-4da2-a18a-0b550afefc90.PNG">

**Comment by RigoFlores** [comment]
esa fecha que aparece ahí, es del catalina. ahí puedes buscar el detalle

**Comment by jccastillo0007** [comment]
fixed.

chiaaa pinches errores raros k

**Comment by RigoFlores** [comment]
está bien para el IVA base IEPS.

Peeeeero, cuando el IVA no es base IEPS, la base la debe reportar normalita, esto es = (precio unitario x cantidad) - descuento

si se compuso lo otro, pero le pegamos a toooooodos los clientes...

**Comment by jccastillo0007** [comment]
fixed, ya valida cuando si debe cambiar la base y cuando no

**Comment by RigoFlores** [comment]
quedó bien, hay que llevarlo a pro...
