### ISSUE TITLE
AGREGAR EL TOTAL A PAGAR EN LA PANTALLA DE NÓMINA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#187]
EL TOTAL A PAGAR YA SE CALCULA AHORA MISMO, ANTES DE GENERAR EL RECIBO. ENTONCES, COLOCAR UN DATO DE 'TOTAL A PAGAR' QUE MUESTRE:
SUMA DE PERCEPCIONES GRAVADAS Y EXENTAS, MENOS LA SUMA DE DEDUCCIONES GRAVADAS Y EXENTAS

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
No lo está calculando correctamente.
Se deben tomar las percepciones totales exentos + gravados, menos las deducciones totales exentas + gravadas.
Esto aplica para la nómina individual.

**Comment by jccastillo0007** [comment]
fixed.
