### ISSUE TITLE
Captura de CCP v2.0 - pide ID origen y destino, aunque no haya mas de 1 destino

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1870]
Antes del cambio de ayer, no pedía forzosamente el ID origen e ID destino en la pantalla de captura.
Ahora si no capturas, marca error, lo cual es absolutamente innecesario.

Necesitamos eliminar esa captura ya.

**Comment by jccastillo0007** [comment]
fixed
