### ISSUE TITLE
Implementar el nuevo esquema de cancelación 2022.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1871]
Este nuevo esquema inicia a partir del 01 de enero del 2022. No importa que sea CFDI 3.3 o el 4.0.

Básicamente al cancelar, se deberá indicar el motivo de la cancelación:
01 - Comprobante emitido con errores con relación
02 - Comprobante emitido con errores sin relación
03 - No se llevó a cabo la operación
04 - Operación nominativa relacionada en la factura global”

Para el motivo 01, se deberá indicar la factura relacionada. Entiendo el folio sat.

Este es el nuevo xsd. La verdad no me queda claro cómo funciona, pero si entiendo que se deberá indicar el motivo de cancelación y para el caso de 01, indicar el CFDI relacionado.
 
[CancelaCfdi.zip](https://github.com/jccastillo0007/eFacturaT/files/7757208/CancelaCfdi.zip)

esta es la liga con más información.

https://www.sat.gob.mx/consultas/43074/actualizacion-factura-electronica---reforma-fiscal-2022-

**Comment by RigoFlores** [comment]
Si el motivo es distinto a 01, debe dejar en solo lectura (INHIBIR) la selección del CFDI relacionado.

**Comment by jccastillo0007** [comment]
oye, puedo iniciar con los cambios del UI, peeeero, nosotros no cancelamos directo con el SAT, necesito que tanto facture hoy y finkok liberen su web service que soporte el tema de la razón de cancelación y el posible cfdi referenciado

**Comment by RigoFlores** [comment]
chiaaa.... te mandé el correo de finkok, donde indicaba que ya tenía todo listo para pruebas...

ahora, hacer pruebas con finkok nos ayudará, si finalmente tenemos que cancelar con fhoy?

**Comment by RigoFlores** [comment]
También ya te envié la información de fhoy para este tema... 
Esta es la pantalla de cancelación del sat, antes de aceptar pide el motivo:

![cancelación](https://user-images.githubusercontent.com/2912775/147860750-3f11a1c7-0128-49c8-bf38-622704c3121d.png)

Y este es el error que se marca ahora, al intentar cancelar.

<img width="671" alt="errorcancelacion" src="https://user-images.githubusercontent.com/2912775/147860761-4ece3490-bfc5-4411-b329-7aa759346dd0.PNG">

**Comment by jccastillo0007** [comment]
aqui solo falta el tema de cancelación de otros pacs, que no lo tiene listo facture hoy

**Comment by RigoFlores** [comment]
Entonces ya pide el motivo de cancelación y además la opción de elegir el CFDI relacionado y/o teclearlo.

**Comment by jccastillo0007** [comment]
ya hay un avance del motivo de cancelación, pero pues no se puede probar en pru

**Comment by RigoFlores** [comment]
si, ya vi la pantalla... hay que esperar la respuesta de fhoy y probar en producción... o desde pru, apuntar a pro para la cancelación... y podríamos probar capturando el uuid directamente, eso si podríamos hacer..

**Comment by RigoFlores** [comment]
Dice FHoy que ya está la implementación lista para con ellos.
Ahora, lo pendiente es la cancelación de otros PAC's.

**Comment by RigoFlores** [comment]
Oye, ya nos están pidiendo este tema de la cancelación...
Fhoy ya liberó para facturas de ellos... falta para otros pacs, pero esas son las menos.
Hay que probar en pro...

**Comment by jccastillo0007** [comment]
listo, lo libero en cuanto digas, depende de los otros tickets, ya que se iría todo

**Comment by RigoFlores** [comment]
Si se libera a producción, sería para probar si jala?

**Comment by jccastillo0007** [comment]
Completed.

Rijo, solo creas tickets pero no cierras los resueltos, chiaaa

**Comment by RigoFlores** [comment]
pues está faltando la cancelación para otros PACs, es decir no está totalmente validado.

**Comment by RigoFlores** [comment]
Oyes, y en el acuse, debemos incluir el motivo, y en su caso el UUID relacionado.
Esa info te la regresa FHoy, o cómo la obtenemos?

**Comment by jccastillo0007** [comment]
no he visto el acuse de un cfdi cancelado con un cfdi relacionado, dejame revisar

**Comment by RigoFlores** [comment]
OK, no se si hablamos de lo mismo.
La aplicación entrega un acuse que es un jasper, donde se vacía cierta info.
Otra cosa, es "el acuse" que entrega Fhoy con los datos de la cancelación.

Bueno, lo que requerimos es reflejar los datos del acuse de fhoy (sobre todo adicionando los nuevos, que son motivo y UUID relacionado, cuando sea el caso).

**Comment by RigoFlores** [comment]
Mira, algo aproximado así, debemos entregar nosotros... lo mas parecido


[Verificación de Comprobantes Fiscales Digitales por Internet.pdf](https://github.com/jccastillo0007/eFacturaT/files/7998465/Verificacion.de.Comprobantes.Fiscales.Digitales.por.Internet.pdf)
