### ISSUE TITLE
CCP v2.0 - catálogo de mercancías - Permite un ID (descripción corta) duplicado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1875]
Permite un ID (descripción corta) duplicado, y con ello genera error 115 al momento de la vista previa, ya no se diga el timbrado.
La descripción corta es como el identificador.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
que pasará con los que ya están duplicados en pro???
