### ISSUE TITLE
CCP v2.0, llevar algunos datos del transporte, al catálogo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1876]
Como parte de la capacitación a los clientes, y de ellos para nosotros, detecté que estos datos deben ir en el catálogo de transportes, ya que hoy me enteré que el permiso se otorga a nivel de cada tractor, camión, etc:

<img width="330" alt="autotransporte" src="https://user-images.githubusercontent.com/2912775/147837475-85f0d9b8-8c2c-4c5d-adeb-ee7614611b93.PNG">

**Comment by RigoFlores** [comment]
tons, ayudará que eso se cargue a nivel de cada transporte, y así evitar capturas de más...

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
????
