### ISSUE TITLE
CCP - Catálogo de transportes, actualizar catálogo del SAT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1879]
Actualizar el listado de tipo de transporte y remolque, ya que el SAT actualizó su catálogo el 31 de diciembre del 2021. (pestañas c_ConfigAutotransporte y pestaña c_SubTipoRem).

También actualizar la liga del catálogo de complemento de carta porte.

Aquí la liga nueva:

http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/CatalogosCartaPorte20.xls

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
quedó bien chacarrón, hasta el final
debería reflejar el catálogo del sat, chiaaa
