### ISSUE TITLE
CFDI3.3 - Actualizar catálogo de Regímenes fiscales en la pantalla de configuración

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1880]
Cambiaron algunos catálogos, entre ellos el de regímenes fiscales...

esta es la liga del nuevo listado... aquí si, se agregaron al final los nuevos...

http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/catCFDI_V_33_01012022.xls

**Comment by jccastillo0007** [comment]
done, en pru y pro

**Comment by RigoFlores** [comment]
lo validé en pru
