### ISSUE TITLE
CCP v2.0 - Validar los datos requeridos en catálogos de mercancías

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1881]
Cuando omiten alguno, está marcando error, y hay que buscarle por todos lados...

Descripción corta
Clave SAT (8 dígitos)
Pieza
Descripción

Si capturan Valor, entonces deben capturar moneda y viceversa.
Peso no lo estamos ocupando, pero si lo capturan por ejemplo=10, y en la pantalla de complemento de indican cantidad 10, entonces debería calcular el peso total de esa mercancía en 100, con la opción de cambiarlo. Así es como debería funcionar.

**Comment by jccastillo0007** [comment]
fixed, solo no se puede hacer lo de actualizar el peso total, al menos no en pantalla, pero si se podría hacer al momento de generar el complemento, mas no sé si sea buena idea

**Comment by RigoFlores** [comment]
acabo de guardar uno sin descripción... ya existía previamente.

**Comment by jccastillo0007** [comment]
ups, sorry, se me paso subir la versión... ya esta arriba

**Comment by RigoFlores** [comment]
Cuando das de alta una mercancía nueva, con los 4 datos requeridos, te marca que está faltando la unidad y no te permite guardarlo.
Yo había hecho la prueba editando una mercancía ya existente.

**Comment by jccastillo0007** [comment]
fixed
