### ISSUE TITLE
CCP v2.0 - catálogo de transportes, mover los seguros al catálogo, excepto el seguro de carga..

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1883]
Seguimos aprendiendo con los clientes. Y para a optimizar la captura al máximo, seguimos haciendo mejoras.
Mover los siguientes datos, al catálogo de transportes.

<img width="353" alt="seguros" src="https://user-images.githubusercontent.com/2912775/148429473-e2f94c60-69bd-4e66-9737-eadd2ca19989.PNG">

**Comment by RigoFlores** [comment]
y resulta que los remolques son intercambiables entre los distintos tractores.
Entonces quizás vale la pena hacer el catálogo de tractores y capturar cuando aplique, en la pantalla de captura del ccp.
Hoy hablé con un cliente, y si, necesitamos dar mayor facilidad y simplicidad, algunos en la competencia están en la calle con eso...

**Comment by jccastillo0007** [comment]
o quizá no (no por ahora), hasta que tengamos el resto de funcionalidad pendiente

**Comment by RigoFlores** [comment]
Si, con lo que ya conocemos ahora me queda claro que en el catálogo de transportes, deberíamos agregar lo siguientes datos:

- Seguro de Responsabilidad Civil   (siempre está asociado al transporte, aún cuando sean flotillas)
- Póliza de Responsabilidad Civil
- Propietario  (si el transporte pertenece a otra persona/empresa distinta del emisor, pues esto no cambia tan seguido)
- Arrendatario  (mismo caso que el anterior; si rentas un transporte con ciertas características, no cambiará mucho el dato del arrendatario).


Lo de los remolques, podría ser un catálogo aparte... ya que son como buenas putas.. un día van con un camión y otro se van con otro camión. Entonces, esas deben pasar a la pantalla de captura... asociados al transporte elegido.

**Comment by jccastillo0007** [comment]
esto ya se hizo como parte de los refactors
