### ISSUE TITLE
CFDI 4.0 - Incluir el régimen fiscal en el catálogo de clientes web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1884]
Ese listado será igual al que aparece en la pantalla de configuración.
No lo podemos poner por omisión, ya que depende del RFC receptor, si es persona física o moral, y como quiera necesitaremos capturarlo ya en la versión final.

Se puede poner como libre captura para captar la clave, pero realmente cómo debe quedar es el listado de la pantalla actual de configuración.

**Comment by jccastillo0007** [comment]
Done... y ya se manda dinámicamente al xml

**Comment by jccastillo0007** [comment]
.
