### ISSUE TITLE
CFDI 4.0 - valores por omisión para la prueba de timbrado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1885]
Realmente es difícil que haya valores por omisión, pero aquí va lo mas parecido:

1. Versión: '4.0'
2. Exportacion = '02' cuando se incluye el complemento de comercio exterior, en otro caso '01'.
3. Cuando el RFC receptor sea XAXX010101000 , se debe incluir el nodo InformacionGlobal con los valores por omisión: Periodicidad='01', Meses='01', año='2022', en otro caso el nodo no existe.
4. Incluir en el nodo receptor, el CP de su domicilio fiscal.
5. Incluir en el nodo receptor, el Régimen Fiscal capturado en el catálogo de clientes.
6. ObjetoImp ='02' cuando el nodo impuestos a nivel concepto exista. En otro caso '01' (cuando el CFDI no incluya nodo impuestos a nivel concepto).

**Comment by RigoFlores** [comment]
Al menos, lo que está mal, es que el régimen fiscal del receptor, debe ser la clave. Por ejemplo 626.

**Comment by jccastillo0007** [comment]
Done

Versión: '4.0'
Incluir en el nodo receptor, el CP de su domicilio fiscal.
Incluir en el nodo receptor, el Régimen Fiscal capturado en el catálogo de clientes.
ObjetoImp ='02' cuando el nodo impuestos a nivel concepto exista. En otro caso '01' (cuando el CFDI no incluya nodo impuestos a nivel concepto).

Faltan

Exportacion = '02' cuando se incluye el complemento de comercio exterior, en otro caso '01'.
Cuando el RFC receptor sea XAXX010101000 , se debe incluir el nodo InformacionGlobal con los valores por omisión: Periodicidad='01', Meses='01', año='2022', en otro caso el nodo no existe.

**Comment by RigoFlores** [comment]
Si, estamos a la espera de la respuesta de finkok.
Desde anoche les mandé el XML que marca el error del domicilio.

**Comment by RigoFlores** [comment]
Bueno, el error del domicilio, es porque ese RFC de pruebas, no tenía el CP que le correspondía. Entiendo entonces, que ahora se validará que el CP que se reporte en el receptor, corresponda de acuerdo al domicilio fiscal.

Pero ese ya se corrigió. Ahora apareció otro derivado de una omisión mía.
En el nodo de Impuestos - Traslados a nivel general (NO a nivel concepto), se requiere ahora reportar la base de los impuestos. Esta base en los impuestos trasladados, se calculará como **la suma de los valores base de impuestos trasladados a nivel concepto**, a nivel concepto. Entonces, este dato se me pasó y hay que calcularlo.

<img width="337" alt="traslados" src="https://user-images.githubusercontent.com/2912775/149809921-dc41ff00-2211-4dcf-b27d-d846d86df7e9.PNG">
