### ISSUE TITLE
Conector CFDI 4.0 - ajustes iniciales.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1886]
Estos son los datos nuevos:

exportacion=
facturasGlobales=Periodicidad | año | mes
DomicilioFiscalReceptor -> Tomar el dato del CP del receptor, del layout actual
RegimenFiscalReceptor  -> se tomará al final del renglón actual del receptor
objetoImp=

posiblemente el objetoImp, se pueda calcular; igual exportacion... 
pero por lo pronto agregamos todos. Anexo ejemplo del layout 4.0

[cfdi40.txt](https://github.com/jccastillo0007/eFacturaT/files/7831035/cfdi40.txt)

**Comment by jccastillo0007** [comment]
oye, en el conector ya no hay vuelta atras, una vez que haga cambios para cfdi 4, ya no tendremos soporte para cfdi 33
esta bien?

**Comment by RigoFlores** [comment]
Eso está muy drástico.
Si bien, no tenemos reportes de problemas ahora mismo, pues no estoy seguro que sea lo más adecuado.
No se podrá respaldar una versión por las recochinas dudas???

**Comment by jccastillo0007** [comment]
pues si, con git , con un branch diferente, asi lo haré

**Comment by jccastillo0007** [comment]
listo, hoy subo la primer versión cfdi4.0 compliant

**Comment by RigoFlores** [comment]
No está tomando el código postal del lugar original, lo está buscando en residencia fiscal, pero ahí va un código de país.
El código postal lo debe reportar como DomicilioFiscalReceptor, y si lo reporta. Pero el dato lo toma de residencia fiscal, en lugar del código postal del receptor.

<cfdi:Receptor Rfc="FOPR681125BQ0" Nombre="RIGOBERTO MISAEL FLORES DE LA PAZ" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="626" UsoCFDI="G03"/>

Por otro lado dice "Proceso Exitoso", pero mas adelante ya dice "Error en Timbrado". Aquí el log, y los archivos que ya jalan OK.

[SINRETENCION.txt](https://github.com/jccastillo0007/eFacturaT/files/7892873/SINRETENCION.txt)
[cfdi40.txt](https://github.com/jccastillo0007/eFacturaT/files/7892874/cfdi40.txt)
[FacturaT.log](https://github.com/jccastillo0007/eFacturaT/files/7892875/FacturaT.log)
