### ISSUE TITLE
Conector CFDI 3.3 - Actualizar la leyenda para el régimen 626

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1888]
En el conector actual, si acepta el código 626 que corresponde a "Régimen Simplificado de Confianza", pero lo reporta como "Régimen General de Ley".

Esto es, se necesita asociar esta leyenda para este régimen. O si lo queremos ver mas completo, actualizar las leyendas del catálogo de regímenes fiscales 2022.

OJO, si no mal recuerdo, las últimas versiones del conector, ahora solo estaba funcionando para una configuración tipo multiconector, es decir, ya no jalaba para el conector sencillo o normal. Echale un vistazo a eso también pls.

**Comment by jccastillo0007** [comment]
fixed, lo del conector un un rfc, es otro ticket.

**Comment by RigoFlores** [comment]
ya levanté el otro ticket, y no podré liberar esta versión, ya que le pegaría a todos los conectores que no son multirfc, que son todos casi.
