### ISSUE TITLE
CCC v2.0 - mercancías, agregar el campo material peligroso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1889]
Ahora mismo, si el usuario captura la clave de material peligroso y la clave del embalaje, nosotros asumimos que se trata de material peligroso y enviamos este parámetro así:
**MaterialPeligroso="Sí"**

junto con los datos de **clave de material peligroso**   y **clave de embalaje**; opcionalmente descripción del embalaje.

Ahora mismo, también pasa que cuando no se capturan esos datos, no se envían los 3 datos anteriores.

Pero hay un tercer caso, que no tenemos considerado. 
Cuando la mercancía podría o no ser material peligroso. En particular, cuando no lo es, se le debe indicar específicamente **MaterialPeligroso="No**". Pero el usuario debe indicarlo, para ello, hay que agregar una caja de texto en mercancía, "Material Peligroso: ", y si se llena con No, enviarlo así: **MaterialPeligroso="No"**

La otra opción, es que en el campo de Clave de material peligroso capturen "No", y solo en ese caso, enviar **MaterialPeligroso="No"**

<img width="658" alt="matPeligroso" src="https://user-images.githubusercontent.com/2912775/149018994-4bd21cbb-7336-4792-bee8-e6c12a122a75.PNG">

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Si funciona para el caso nuevo. Esto es, la mercancía tiene en la columna de material peligroso el 1,0 y el usuario define que No es peligroso. Eso está bien.

Peeero, para el caso donde el usuario captura información en clave de material peligroso y clave de embalaje, la aplicación enviaba el Sí porque pues el usuario así lo indica, al capturar esa info. Y ahora ya no lo está enviando. 

En cuanto el usuario captura clave de material peligroso y clave de embalaje, el sistema enviará en automático el Sí, y además lo guardará en el campo correspondiente, así creo debe quedar.

**Comment by RigoFlores** [comment]
Cuando la mercancía tiene un 0 en la columna de material peligroso, ahí de plano pues significa que NO es peligroso.
En ese caso no se envía nada en el atributo, simplemente se ignora. Peeeero ahora está pasando esto...
Es decir envía vacío el parámetro y evidentemente marca error.

No se pedía modificar naaada de lo anterior, solo agregar este campo y que se enviara como un No, cuando así lo definiera el usuario, en otro caso, mantener lo mismo que estaba antes...


<cartaporte20:Mercancia BienesTransp="20102305" Cantidad="100.0" ClaveUnidad="H87" Descripcion="COMPUTADORA MARCA HP MODELO AB-10, PROCESADOR INTEL ICORE7 16 GB RAM, 1TB, PANTALLA 22&quot;." FraccionArancelaria="9403200502" MaterialPeligroso="" Moneda="MXN" PesoEnKg="10000.0" Unidad="PIEZA" ValorMercancia="12000.0">

**Comment by jccastillo0007** [comment]
listo, ya quedo como acordamos en whatsapp, chiaa

**Comment by RigoFlores** [comment]
Si, solo que hay que hacerlo una lista, para evitar errores, o poner una etiqueta de cómo debe ser capturado:

Vacío (default)
Sí
No

**Comment by jccastillo0007** [comment]
quieres que suba esta versión? para subir lo de cancelación

**Comment by RigoFlores** [comment]
si, yo creo que podemos llevarla a pro.
