### ISSUE TITLE
NOMINA-EL BOTÓN DE SIMULADOR, NO CALCULA CORRECTAMENTE LOS TOTALES DE LOS HABILITADOS 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#189]
EL BOTÓN DE SIMULADOR INDICA LOS HABILITADOS Y LOS DESHABILITADOS, PERO EL CÁLCULO DE TOTAL A PAGAR NO ES CORRECTO

**Comment by jccastillo0007** [comment]
todavia no estaba terminado.. chaaaaaa inicialmente sumaba de 100 en 100, ahora ya debe estar correcto.

**Comment by RigoFlores** [comment]
si ya los calcula correctamente a partir de los individuales exentos y gravados, percepciones y deducciones. ok
ahora solo falta mostrar los totales en pantalla como solo lectura y mostrar esos cálculos que se ejecutan al timbrar.

**Comment by jccastillo0007** [comment]
Yeap work in progress

Ese es otro ticket, según yo

JC@iPhone.
 Saludos.
