### ISSUE TITLE
CCP v2.0 - Catálogo de transportes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1890]
Originalmente capturo un transporte con 2 remolques y lo guardo. Todo OK.
Luego me doy cuenta que solo debe llevar un solo remolque. Entonces lo edito.

Elimino las placas del segundo remolque y en la lista de tipo de remolque, lo pongo a "Seleccione uno" para según yo borrarlo, y le doy guardar.

Si consulto ese transporte después de modificarlo, si elimina la placa, pero el remolque lo mantiene. Eso generará un error al timbrar con ese transporte.

En resumen, cuando has capturado 2 remolques y guardas. Y después quieres eliminar uno, ya no te lo permite.

**Comment by jccastillo0007** [comment]
me voy a basar en la placa, para definir si se borra o no el remolque

**Comment by RigoFlores** [comment]
correcto, si no hay placa, no se envía la clave de tipo de remolque...  aunque en pantalla se verá otra cosa.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
al parecer si jaló, pero no ha timbrado.
es ahora otro error
