### ISSUE TITLE
CCP - misceláneos, no envía el número de registro ni residencia fiscal cuándo éstos se capturan,

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1891]
Estos campos se utilizan en traslados internacionales. 
Aquí lo que se necesita es enviarlos al XML, cuando se capturen.

Por ejemplo, el conector como simplemente envía lo que incluye el archivo de texto, si lo hace:

<cartaporte20:Ubicacion DistanciaRecorrida="1000.0" FechaHoraSalidaLlegada="2021-05-10T10:00:00" NombreRemitenteDestinatario="PREMIER AUTOCOUNTRY SA DE CV" NumRegIdTrib="123456" RFCRemitenteDestinatario="XEXX010101000" ResidenciaFiscal="AFG" TipoUbicacion="Destino">

En el caso de la plataforma, no lo hace. Simplemente no lo envía, y el SAT pues marca error cuando el rfc del origen o destino es XEXX010101000, lo cual indica que debe acompañarse de estos 2 datos que no está incluyendo.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
pues hace algo raro, de entrada está enviando una ubicación que yo no elegí.
luego marca internal error...

**Comment by jccastillo0007** [comment]
algo estas haciendo mal, comprobé que se mandara el origen seleccionado, cheque con la TIA de Qro, Gdl y Canada

**Comment by RigoFlores** [comment]
al parecer quedó, pero no timbra...por otro issue.
Lo cerraré mientras corriges lo otro...

**Comment by RigoFlores** [comment]
ya lo validé, si quedó corregido.
