### ISSUE TITLE
CCP - PDF, ajustar algunos datos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1892]
El 3 de enero, el SAT publicó el contenido oficial del PDF cuando incluye el complemento de carta porte.
Casi como lo definimos nosotros, sin embargo le falta uno que otro dato.
En el word del dropbox, estoy documentando los cambios resaltados en verde. Y aquí lo incluyo igualmente.

C:\Users\admin\Dropbox\FacturaT\PROYECTOS\CFDI3.3\cartaPorte\v2.0\jasper\Mapeo PDF 20.docx

[Mapeo PDF 20.docx](https://github.com/jccastillo0007/eFacturaT/files/7851163/Mapeo.PDF.20.docx)

**Comment by jccastillo0007** [comment]
ya agregue los cambios , excepto los cambios del dato extra 8, ya que el sistema no cuenta con las descripciones

**Comment by RigoFlores** [comment]
En Origen y Destino, después del ID, falta un enter.
Cuando no aplica el dato, manda "null", no se puede inicializar a vacío o algo así?


Del dato extra 8, no tenemos la descripción para la clave del permiso, OK. Pero si tenemos la descripción del transporte y del o los remolques. Esos están haciendo falta.

**Comment by jccastillo0007** [comment]
ok, ya quedo lo del enter y lo del null.

Para las descripciones, no se cuenta con ellas, pues esa sección del pdf se crea a partir del complemento, es decir, del xml, ahi no hay descripciones, tendría que hacer varios ajustes para poder extraer las descripciones
