### ISSUE TITLE
Conector 3.3 - soportar solo 1 RFC o MultiRFC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1893]
Anteriormente el mismo código, soportaba ambos esquemas.
Entiendo que buscaba la configuración multiRFC cuando se incluía el RFC Emisor dentro del archivo de texto.

Hoy, al parecer solo funciona bajo el esquema de multiRFC y ya no con un solo rfc emisor.

**Comment by jccastillo0007** [comment]
fixed, el problema era la creación de folders para el xml y pdf, como se modificó para multirfc, se introdujo un problema para single rfc
