### ISSUE TITLE
CCP - no envía la clave de permiso de un transporte al que le borré un remolque.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1894]
Si no mal recuerdo, este registro de transporte tenía 2 remolques.
Para la prueba de que permitiera eliminar un remolque, le borré uno. Y cerré el issue aquel.

<img width="769" alt="remolques" src="https://user-images.githubusercontent.com/2912775/149559853-86fc1df8-181e-41b8-a0e7-f40ea1bcffd9.PNG">

Pero ahora haciendo prueba con ese registro editado de transporte, resulta que no envía la clave de permiso al XML y marca XML mal formado.

                <cartaporte20:Autotransporte **NumPermisoSCT="1234567890"**>
                    <cartaporte20:IdentificacionVehicular AnioModeloVM="2020" ConfigVehicular="T2S1" PlacaVM="123ABC"/>
                    <cartaporte20:Seguros AseguraRespCivil="AXXA" PolizaRespCivil="AXA1234567"/>
                    <cartaporte20:Remolques>
                        <cartaporte20:Remolque Placa="123BCD" SubTipoRem="CTR003"/>
                    </cartaporte20:Remolques>
                </cartaporte20:Autotransporte>

Así que por ahí se quedó algo. Ahí está todo para que se pueda validar porqué no envía la clave de permiso.

**Comment by jccastillo0007** [comment]
No lo manda porque esta mal capturado, es TPAF chiaaa

**Comment by jccastillo0007** [comment]
.

**Comment by RigoFlores** [comment]
A poco estamos validando las claves del catálogo???
No, no creo. Porque en ese caso, mejor poner el listado de claves y ya con eso.

En caso que hubiera estado mal capturada, pues la envía mal y punto, y entonces se marcaría XML mal formado, pero no, no estaba enviando nada.

Ahora ya la envía.
