### ISSUE TITLE
CCP - solo activar la pantalla de captura para CCP Ingreso y CCP traslado, para el resto hacer lo de antes.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1895]
Hay clientes que tenían su addenda o complementos en las facturas, pero ahora que actualizaron para el complemento de carta porte, todo eso se fue a la verch.
Tons se me ocurre, que tenemos que dejar todo como estaba antes, y solo cuando se elija hacer CCP Ingreso o CCP traslado, habilitar la captura de la addenda (pantalla del complemento de CCP).

Si es cualquier otro tipo de CFDI (factura, nota de crédito, etc), entonces tomar su configuración actual. Si no tiene addenda o complemento, indicarlo. Si tiene alguna addenda o complemento, abrir la ventana que corresponda.

**Comment by jccastillo0007** [comment]
Done

**Comment by jccastillo0007** [comment]
.

**Comment by RigoFlores** [comment]
Puedes dar de alta el rfc IIA040805DZ4 en pru, con complemento de comercio exterior?
Es en versión 3.3.

Validé con addenda mabe y si funcionó.
Pero el caso que tenemos es para comercio exterior y mejor lo valido antes de soltarlo al cliente.

**Comment by jccastillo0007** [comment]
chiaaa
 supongo que es solo darlo de alta como receptor de CCE

**Comment by RigoFlores** [comment]
no receptor... nuestros clientes (emisores), los que emiten CCE, están en jarcoud... chiaaaaaa

**Comment by jccastillo0007** [comment]
si, ya esta, checale

**Comment by RigoFlores** [comment]
Pues no, algo que no está haciendo es que al elegir factura y quiero emitir con el complemento de comercio exterior.
Entonces, por cada producto, debe agregar la captura de fracción arancelaria y unidad.
pero no, no lo está haciendo. Solo muestra los datos configurados en el XML, pero los dos datos extra por cada producto, se agregan automáticamente y no lo está haciendo.
Puedes checarlo?

**Comment by jccastillo0007** [comment]
por alguna razón, esta solicitando que el cliente tenga el plugin de contabilidad electrónica, para hacer el comportamiento que describes arriba, suena raro pues no tiene nada que ver, no sé si fue un workaround implementado por alguna razón
Puedes checar un cliente de PROD que use el CCE y ver si tiene el plugin de CE?

**Comment by RigoFlores** [comment]
este cliente tiene el CCE... y si, tiene la CE, eso ya ni se ocupa...

<img width="311" alt="cce" src="https://user-images.githubusercontent.com/2912775/150446395-65bbcb42-0739-45e2-9a1d-274b80e9c854.PNG">

**Comment by jccastillo0007** [comment]
pues para tus pruebas , asi debe ser, luego vemos para quitarlo
eso de contabilidad electrónica es uno de los ejemplos de funcionalidad que hemos hecho y ni se ocupa

**Comment by RigoFlores** [comment]
ya estoy probando, pero ahora marca otro error.. en el municipio del domicilio fiscal del emisor, en la parte del complemento...
            <cce11:Emisor>
                <cce11:Domicilio Calle="AV UNIVERSIDAD" CodigoPostal="76100" Estado="QUE" Municipio="011" Pais="MEX"/>
            </cce11:Emisor>

Lo que no sé, es de donde está tomando el domicilio, ya que lo que envía son claves en la parte de estado y municipio.
Eso es parte de la configuración en jarcoud??? 
En ese domicilio del emisor de pruebas, la clave del muncipio es 014 y o 011, por eso marca error.

Lo cambias pls, y además me confirmas si eso es parte del famoso jarcoud?
