### ISSUE TITLE
CCP - no toma la plantilla personalizada para el PDF del CFDI CCP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1896]
El nombre que entiendo debe buscar en la carpeta setup del cliente, es por ejemplo:

complementocartaporte**XLO180801JP2**.jrxml

pero no lo está haciendo, se va a buscar la plantilla estándar.
Con ello, no podemos hacer ciertas personalizaciones.

**Comment by jccastillo0007** [comment]
.

**Comment by RigoFlores** [comment]
Bueno, enhacement no lo veo así, porque es parte de lo que siempre hemos manejado.
Lo importante es que ya quedó resuelto.
