### ISSUE TITLE
Conector CFDI 4.0 - no está tomando el CP del receptor del campo que corresponde

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1897]
Lo está tomando de residenciaFiscal, que es clave de país, no del código postal.
Debe tomarlo del campo previo al email del receptor

**Comment by jccastillo0007** [comment]
fixend

**Comment by RigoFlores** [comment]
yo creo que no subió correctamente. Sigue igual.

El zip si es de por la noche, pero en último jar dentro del zip es de las 3:47 PM, es decir poco antes de las 4 de la tarde.

**Comment by RigoFlores** [comment]
sigue igual...

**Comment by jccastillo0007** [comment]
chiaaaa, ahora si, ya lo probé <sin albur>
