### ISSUE TITLE
CFDI 4.0 - Pantalla de facturación - Permitir datos para factura global

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1898]
en un espacio similar a la sección de "CFDIs relacionados", agregar lo siguiente:

Cuando el RFC sea XAXX010101000 y el nombre sea “PUBLICO EN GENERAL”, entonces se debe capturar lo siguiente:

leyenda header: "Solo para Factura Global"

Periodicidad.- un listado del 01 al 05
Mes .- un listado del 01 al 18
Año .- debe ser numérico. Igual o mayor a 2022

las descripciones de periodicidad y mes, aún no están disponibles. Pero debemos tomarlas de una tabla.

**Comment by RigoFlores** [comment]
Aquí las descripciones del catálogo.

mes:

01	Enero
02	Febrero
03	Marzo
04	Abril
05	Mayo
06	Junio
07	Julio
08	Agosto
09	Septiembre
10	Octubre
11	Noviembre
12	Diciembre
13	Enero-Febrero
14	Marzo-Abril
15	Mayo-Junio
16	Julio-Agosto
17	Septiembre-Octubre
18	Noviembre-Diciembre


Periodicidad:

01	Diario
02	Semanal
03	Quincenal
04	Mensual
05	Bimestral

**Comment by RigoFlores** [comment]
falta este punto

**Comment by jccastillo0007** [comment]
solo me falta poder ocultarlo cuando el RFC no sea XAXX

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
ok, si hace falta mostrarlo cuando el rfc sea XAXX, pero sobre todo hace falta...
INCLUIRLO EN EL XML. chiaaaa... el nodo es InformacionGlobal, y hay que incluir la información capturada... chiaaaaa

**Comment by jccastillo0007** [comment]
eso ya esta funcionando , chiaaaa, acabo de hacer esta factura

<cfdi:InformacionGlobal Periodicidad="02" Meses="02" Año="2022"/>
    <cfdi:Emisor Rfc="IVD920810GU2" Nombre="INNOVACION VALOR Y DESARROLLO" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="XAXX010101000" Nombre="PUBLICO EN GENERAL" DomicilioFiscalReceptor="61957" RegimenFiscalReceptor="616" UsoCFDI="S01"/>

**Comment by RigoFlores** [comment]
sicierto, no lo ví... chiaaaaa....

Lo que se podría hacer también como opción es... cuando el RFC sea XAXX y el nombre "PUBLICO EN GENERAL"   (ambas condiciones), entonces validar que se haya capturado la info de la factura global. En caso que no, enviar el mensaje correspondiente.
En el caso que no se cumplan ambas condiciones, entonces, ignorar lo que se haya capturado para la factura global.

Se validan ambas condiciones, porque se podría emitir una factura a XAXX pero a nombre de persona física (sin RFC en el SAT)...
