### ISSUE TITLE
CFDI 4.0 - atributo exportacion

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1899]
Ahora mismo, este atributo que se incluye a nivel header, puede tener 3 valores:

01
02 .- cuando se incluya el complemento de comercio exterior
03

ahora mismo, desconozco cuándo será 01 o 03, no tengo descripción ni nada. 
Posiblemente podamos calcularlo o quizás tengan que elegirlo de una lista.
Por lo pronto, dar el valor 02 cuando se incluya el CCE, o 01 en otro caso.

Validaré este issue, emitiendo una factura con CCE.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
oye, entonces puedes agregar la rfc emisor, en jarcoud (chiaaaaaaaaaaaaaaaaaaaaaa) la emisión del CCE???

**Comment by jccastillo0007** [comment]
te refieres a IIA ? supongo que si, listo

**Comment by RigoFlores** [comment]
chiaaalesss..... estamos en CFDI 4.0, entonces esta petición es para IVD.

Pero bueno, como quiera lo de IIA servirá para oooootro issue.

Pero para validar el issue aquí en cuestión, se requiere **agregar en jarcoud el CCE para el RFC IVD en pru.**

**Comment by RigoFlores** [comment]
hay que agregar ese RFC en hardcoud para validar este issue.
y luego lo tenemos que quitar, es esta prueba.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Pues ya intenté generar el CCE en versión 4.0, y marca error.
Ni siquiera llega a generar el XML, truena antes... este es el catalina cuando truena... será lo de la addenda FT?

2022-02-03 17:48:51,586 DEBUG [http-nio-8080-exec-42] (JaxbXMLProvider.java:49) - Setup JaxbManager
CCE complement is being created : addenda data size : 16
2022-02-03 17:48:51,668 ERROR [http-nio-8080-exec-42] (CFDBusinessLogicProvider.java:127) - java.lang.ClassCastException: com.cfd.xml.provider.jaxb.cfdi_v40.Comprobante cannot be cast to com.cfd.xml.provider.jaxb.cfdi.Comprobante
java.lang.ClassCastException: com.cfd.xml.provider.jaxb.cfdi_v40.Comprobante cannot be cast to com.cfd.xml.provider.jaxb.cfdi.Comprobante

**Comment by RigoFlores** [comment]
Estos son los datos en pru 4.0, para emitir la factura con CCE y puedas reproducirlo:


<img width="670" alt="facturaCCE" src="https://user-images.githubusercontent.com/2912775/152450896-7f64f418-8322-4af4-b199-31a8bd314b87.PNG">


<img width="627" alt="datoComplemento" src="https://user-images.githubusercontent.com/2912775/152450925-d4b91b48-e690-489a-95e4-a135fb6c9e17.PNG">

**Comment by jccastillo0007** [comment]
Ya esta generando el cfdi y el complemento, anexo ejemplo.

Finkok marca error al timbrar diciendo : Errores con schemaLocations, namespaces y prefijos

Pero su validador dice: CFDI40138 El campo Nombre del emisor, no corresponde con el nombre del titular del certificado de sello digital del Emisor.
[temp.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8006837/temp.xml.txt)


Asi que para saber que pasa, mejor te lo deje para que le eches un ojo...

**Comment by RigoFlores** [comment]
[CCE_OK.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8019692/CCE_OK.xml.txt)

Mira, este es un CFDI 3.3 con complemento de CE.
Y los namespaces van en el header del CFDI, no a nivel complemento.
Creo que eso puede ser.

**Comment by jccastillo0007** [comment]
esto ya esta listo, cierto

**Comment by RigoFlores** [comment]
El catálogo es este:

01	No aplica - Cuando no se trata de una exportación, no se incluye un CCE
02	Definitiva  - Cuando se incluye CCE
03	Temporal - no sé en que momento aplica esto.

Ahora mismo, cuando se incluye CCE se manda 02, cuando no se incluye CCE se manda 01. 
Pero el 03 no sé cuando aplica.  

Creo que debemos hacerle un campo de captura en la pantalla de facturación, y que por omisión sea 01 en la lista.
En algún escenario que desconozco ahora mismo, se podría utilizar el 03 y no estaremos listos.

**Comment by RigoFlores** [comment]
algo dice aquí esta página. Al final me quedo igual, no se cuándo aplica. Tons que hacemos?
le dejamos al cliente que ellos definan, y ponemos la lista del catálogo. ???
Por default= 01


https://www.estrategiaaduanera.mx/exportacion-temporal-reparacion-control-aduanero-efectos-anexo-24-anexo-31/exportacion-temporal-tabla-03/


<img width="447" alt="temporal" src="https://user-images.githubusercontent.com/2912775/153502845-8e8973b9-43f6-4b78-8d57-11aaca3651f9.PNG">

**Comment by jccastillo0007** [comment]
mejor lo dejamos fijo en 01 o 02, y no hacemos nada mas, para no retrabajar, lo implementamos cuando sea requerido

**Comment by RigoFlores** [comment]
no sería retrabajo, hoy la norma dice que puede ser 01, 02 o 03.
Pero pues si quieres lo dejamos así.

Si tiene CCE va con 02, en otro caso 01.

cuando brinque la liebre, a ver si no hay pedo
