### ISSUE TITLE
ES MUY COMÚN QUE MANDE EXCEPCIONES A PANTALLA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#19]
POR LO REGULAR SIEMPRE QUE ACCEDO A LAS DISTINTAS PANTALLAS GENERA UN ERROR DE EXCEPCION. DEFINITIVAMENTE SI ESO NO SE CONTROLA, IDENTIFICA Y CORRIGE, PODEMOS PENSAR EN SALIR A PRO. ES UN PROBLEMA RECURRENTE DESDE SIEMPRE

**Comment by jccastillo0007** [comment]
JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
CADA OCASIÓN QUE SE PRESENTE, ENVIARÉ LA PANTALLA POR CORREO
