### ISSUE TITLE
NOMINA - BOTON DE GENERAR NOMINA - FUNCIONAMIENTO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#190]
Entiendo que el botón de generar nómina debe:
a) generar uno a uno los recibos de empleados habilitados
b) indicar el avance 1 de 10, 2 de 10, etc
c) no estoy seguro de dar la opción de cancelar (quizás no nos convenga, ya que si se equivocaron, pues que generen todos, los cancelen y generen nuevamente otros folios)
d) la pantalla no debe permitir hacer nada mas, en lo que se procesan los recibos. Solo mostrar el avance.
e) Implementar manejo de errores. (se desconectan de internet, se vuelven a conectar y se van a la pantalla. que pasa si aún no termina el procesamiento de la nómina y ya están listos para volver a generarla?).
f) Generar un reporte de los recibos generados correctamente, y los que no se pudieron generar.
g) al final indicar que los recibos generados, los pueden descargar en la pantalla de consultas.

**Comment by jccastillo0007** [comment]
Por el momento es viable implementar los puntos a, c, d, e y f...

c. no se permite cancelar
e. no se bien como probar este scenario, una vez que le dan facturar, se pone en chinga en el servidor... lo cual es independiente al browser o a internet... el problema seria que se conecten otra vez y vuelvan a ejecutar la nomina, se duplicarian en este escenario

**Comment by RigoFlores** [comment]
el punto e sería que se fueran a consultas para reflejar o visualizar el avance?

**Comment by RigoFlores** [comment]
el punto (e), pudiera manejarse si en la opción de adenda empresarial, se indica un resumen del último proceso solicitado/ejecutado.
Por ejemplo, 10 recibos, totales y mostrar las fechas.
Al menos tendrían una idea de lo último que se hizo, en caso de desconectarse.

**Comment by RigoFlores** [comment]
se cierra este issue, y se abre otro con los pendientes.
