### ISSUE TITLE
CFDI 4.0 - nodo concepto, Atributo ObjetoImp 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1900]
Si el nodo concepto, incluye el nodo de impuestos, su valor debe ser 02.

Los posibles valores son 01, 02, 03.
No conocemos las descripciones, ni cuándo debe ser 01 o 03, por lo pronto, asignaremos 01 cuando no exista el nodo de impuestos en el nodo concepto (OJO, concepto, no conceptossss).

Probaré este issue, capturando una factura sin impuestos.

**Comment by jccastillo0007** [comment]
Esto ya esta implementado

**Comment by RigoFlores** [comment]
ok, está pendiente saber cuándo será 01 o cuándo será 03.
Aún más, si es necesario agregar la opción que lo capturen.
