### ISSUE TITLE
CFDI 4.0 con complemento de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1901]
**Necesitamos definir si los datos los consultaremos de la BD o del XML,** esto para:

- Web
- Conector (Estándar, Navision, Optibelt, Abastos).

Los datos que necesitamos, entiendo son todos los que se incluye en el nodo de impuestos GENERAL, del CFDI 4.0

    <cfdi:Impuestos TotalImpuestosRetenidos="206.67" TotalImpuestosTrasladados="160.00">
        <cfdi:Retenciones>
            <cfdi:Retencion Impuesto="001" Importe="100.00"/>
            <cfdi:Retencion Impuesto="002" Importe="106.67"/>
        </cfdi:Retenciones>
        <cfdi:Traslados>
            <cfdi:Traslado Base="1000.0" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="160.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

Cuando generamos el complemento de pago, la info de las facturas pagadas (moneda, total, método de pago, UUID, etc), ¿las tomas de donde?

Hoy en día, solo se permite un pago por cada CFDI.
Lo nuevo, es que debemos  permitir capturar varios pagos en un solo CFDI. 

De lo anterior, a nivel global se deberán reportar los datos de los impuestos pagados en moneda nacional MXN.

Además a nivel de cada documentorelacionado, se deberán reportar los impuestos pagados (a) en la moneda del documento y (b) en la moneda del pago.

Un escenario es que por ejemplo, la factura se emitió en Euros, el pago se hizo en USD, y parte de la info se debe reportar en MXN.

**Comment by jccastillo0007** [comment]
todos los datos se mandan como datos extras para generar el complemento de pagos

esta bien pinche raro

**Comment by RigoFlores** [comment]
jajaja... no entendí...
cuando se incluye información en el complemento de pago (XML), se debe reportar el UUID, la moneda, método de pago, total, etc... de cada factura pagada...
la pregunta es esos datos de donde se toman?... de la BD o del XML?

**Comment by jccastillo0007** [comment]
de la BD, al leer la factura que se esta pagando

**Comment by RigoFlores** [comment]
ok, pues si todos los datos de impuestos del CFD, que por ello incluí el nodo correspondiente, se almacenan en BD, pues de ahí tomaremos la información.
