### ISSUE TITLE
Eliminar la addenda Factura-T del web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1902]
Dejarla como pendiente cuando se llegue a requerir.
Su objetivo era poder reconstruir un PDF con datos extra, a partir del XML con addenda FT, pero esa funcionalidad no la tienen ningún PDFOR.

Y ahora está causando mucho ruido.
Entonces hay que quitarla del código, comentarla.

**Comment by RigoFlores** [comment]
O al menos para lo que es complemento de carta porte.
No se si el addendador, la agregue, pero me parece que el complemento de carta porte si.

**Comment by jccastillo0007** [comment]
chiaaa

done
