### ISSUE TITLE
CFDI 4.0 - Nodo Impuestos - Traslados - Traslado, no reporta correctamente la base

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1904]
La base, es un dato nuevo para este 4.0
La base debe ser la suma de las bases del impuesto de los productos dentro de la factura, para la llave: 
**Impuesto - TipoFactor - Tasa.**
esa es la llave de los impuestos.

Ahora mismo, si agrego varios productos, o le cambio la cantidad del producto, se hace pelotas con la base. En el ejemplo de abajo, LO CORRECTO DEBERÍA SER:

            <cfdi:Traslado Base="**3000.0**" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="480.00"/>
            <cfdi:Traslado Base="**2000.0**" Impuesto="003" TipoFactor="Tasa" TasaOCuota="0.265000" Importe="530.00"/>

Pero lo reporta INCORRECTAMENTE de esta manera:

            <cfdi:Traslado Base="**5000.0**" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="480.00"/>
            <cfdi:Traslado Base="**5000.0**" Impuesto="003" TipoFactor="Tasa" TasaOCuota="0.265000" Importe="530.00"/>

Este es el ejemplo:

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="02" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="producto de prueba 2" ValorUnitario="1000.000000" Importe="1000.000000" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="1000.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="160.000000"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>

        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="01" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="producto de prueba 1" ValorUnitario="2000.000000" Importe="2000.000000" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="2000.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="320.000000"/>
                    <cfdi:Traslado Base="2000.000000" Impuesto="003" TipoFactor="Tasa" TasaOCuota="0.265000" Importe="530.000000"/>
                </cfdi:Traslados>
                <cfdi:Retenciones>
                    <cfdi:Retencion Base="2000.000000" Impuesto="001" TipoFactor="Tasa" TasaOCuota="0.100000" Importe="200.000000"/>
                </cfdi:Retenciones>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>

    <cfdi:Impuestos TotalImpuestosRetenidos="200.00" TotalImpuestosTrasladados="1010.00">
        <cfdi:Retenciones>
            <cfdi:Retencion Impuesto="001" Importe="200.00"/>
        </cfdi:Retenciones>
        <cfdi:Traslados>
            <cfdi:Traslado Base="**5000.0**" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="480.00"/>
            <cfdi:Traslado Base="**5000.0**" Impuesto="003" TipoFactor="Tasa" TasaOCuota="0.265000" Importe="530.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
no se hace pelotas, simplemente no estaba agrupando la base de acuerdo al tipo de impuesto, y ya sabíamos que así estaba.

Ya esta corregido

**Comment by RigoFlores** [comment]
negativo, sigue con problemas... no lo reporta bien, cuando la cantidad en el concepto es distinto de 1... mira... Aquí la base debe ser 2100.00, y reporta 1100.00

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="01" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="producto de prueba 1" ValorUnitario="100.000000" Importe="100.000000" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="100.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="16.000000"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="02" Cantidad="2.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="producto de prueba 2" ValorUnitario="1000.000000" Importe="2000.000000" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="2000.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="320.000000"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="336.00">
        <cfdi:Traslados>
            <cfdi:Traslado Base="1100.0" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="336.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
ok, ya vi
En los productos, la base se multiplica por la cantidad, y eso lo hacia al momento de crear el xml, faltaba hacerlo para los impuestos...

**Comment by RigoFlores** [comment]
SIGUE MAL EL CÁLCULO DE LA BASE, CHECA ESTE EQUIEMEL... AQUÍ LA BASE DEBIÓ SER 45,400 PARA TRASLADOS

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="01" Cantidad="4.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="producto de prueba 1" ValorUnitario="100.000000" Importe="400.000000" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="400.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="64.000000"/>
                </cfdi:Traslados>
                <cfdi:Retenciones>
                    <cfdi:Retencion Base="400.000000" Impuesto="001" TipoFactor="Tasa" TasaOCuota="0.100000" Importe="40.000000"/>
                </cfdi:Retenciones>
            </cfdi:Impuestos>
        </cfdi:Concepto>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="02" Cantidad="45.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="producto de prueba 2" ValorUnitario="1000.000000" Importe="45000.000000" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="45000.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="7200.000000"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosRetenidos="40.00" TotalImpuestosTrasladados="7264.00">
        <cfdi:Retenciones>
            <cfdi:Retencion Impuesto="001" Importe="40.00"/>
        </cfdi:Retenciones>
        <cfdi:Traslados>
            <cfdi:Traslado Base="1100.0" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="7264.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
chiaaa, no lo había subido

**Comment by RigoFlores** [comment]
ok, al parecer ya quedó.
Para el complemento de pago necesitaremos contar CON LA MISMA INFORMACIÓN DE LAS RETENCIONES, ESTO ES:

        <cfdi:Retenciones>
            <cfdi:Retencion Impuesto="001" Importe="600.00"/>
            <cfdi:Retencion Impuesto="002" Importe="213.34"/>
        </cfdi:Retenciones>
        <cfdi:Traslados>
            <cfdi:Traslado Base="8000.0" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="1280.00"/>
        </cfdi:Traslados>

SI OBSERVAS, CUANDO SE REPORTAN LOS DATOS DE IMPUESTOS TRASLADADOS GENERALES DEL CFDI, ESTOS SE REPORTAN y CLASIFICAN COMPLETOS Base, Impuesto, TipoFactor, TasaOCuota, Importe,

podemos guardar esa misma info a NIVEL GENERAL pero para retenciones???
ESO NOS AHORRARÁ MUUUUCHO TRABAJO PARA LA EMISIÓN DEL COMPLEMENTO DE PAGO.
