### ISSUE TITLE
Carta porte misceláneos - forzar al domicilio capturar de las listas cuando el pais sea méxico

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1906]
El usuario puede capturar libremente los datos del domicilio, cuando el país es méxico.
Sobre todo cuando no encuentra la colonia, o cosas así.
Entonces necesitamos forzar a que cuando el país sea México, no se pueda teclear los datos que deben tomarse de la lista, como son: Estado, Municipio, CP, Colonia.

Indicar que los datos forzosos en el domicilio, son Pais, Estado y CP.

**Comment by jccastillo0007** [comment]
no recomiendo limitar la colonia y municipio, ya que vamos a tener muchas llamadas por que no encuentran los datos correctos en el catálogo, y además no son obligatorios

**Comment by jccastillo0007** [comment]
bueno, ahorita ya están protegidos todos
