### ISSUE TITLE
Complemento de recepción de pago v2.0 - requisitos generales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1907]
Entiendo, si llegar a estar totalmente seguro, que este complemento solo aplicará para el CFDI versión 4.0.
Porque entonces que pasará cuando en mayo, se reciban pagos de facturas que se hicieron en 3.3? Ahí si no sé, quizás debemos mantener, si es posible el pago 3.3 y el 4.0 simultaneamente.

pero bueno, los requisitos generales son:

Exportacion	valor fijo = 01
"FormaPago,  MetodoPago, CondicionesDePago, Descuento, TipoCambio"	no deben existir
usode CFDI	debe ser CP01
objetoImp	debe ser 01
ObjetoImpDR	Si el valor registrado en este atributo es “02” el nodo hijo ImpuestosDR del nodo DoctoRelacionado debe existir en caso contrario no debe existir dicho nodo. Es decir, cuando el docto relacionado, contenga al menos un impuesto, entonces el valor será '02'

**Comment by RigoFlores** [comment]
Pues aquí los motivos de la falla:

UsoCFDI debe ser CP01

TipoCambioP  y EquivalenciaDR, cuando se trate de MXN, debe ser '1', y no '1.0' (si, ya sé una mamada). Cuando aplique un tipo de cambio real, será a 6 decimales.

BaseDR, TasaOCuotaDR y TasaOCuotaP se deben reportar a 6 decimales.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
faltó lo del uso del cfdi, no lo cambió

**Comment by RigoFlores** [comment]
mira, aquí estaba solicitando ese tipo de uso para el CFDI de tipo traslado, no se que pasó o porque no estaba trabajando. Estoy seguro que si jalaba.
