### ISSUE TITLE
Complemento de pago 2.0, cálculos a realizar para el pago.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1908]
Te mandé por correo un excel con los cálculos que se requiere hacer. tiene comentarios en la hoja del excel. Aquí lo tienes igualmente. Este es el bueno, le hice unos ajustes, tenía errores.

Si quieres lo platicamos, para que te lo explique.

[calculos compPago 2.0.xlsx](https://github.com/jccastillo0007/eFacturaT/files/7964736/calculos.compPago.2.0.xlsx)

**Comment by jccastillo0007** [comment]
ya voy aqui:

<cfdi:Complemento>
        <pago20:Pagos xmlns:pago20="http://www.sat.gob.mx/Pagos20" Version="2.0" xsi:schemaLocation="http://www.sat.gob.mx/Pagos20 http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos20.xsd">
            <pago20:Pago FechaPago="2022-02-02T21:46:24" FormaDePagoP="03" MonedaP="MXN" Monto="116.00" NumOperacion="001">
                <pago20:DoctoRelacionado Folio="90" IdDocumento="C6628CD4-24A1-512A-851D-CF233996EB83" ImpPagado="116.00" ImpSaldoAnt="116.00" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="1"/>
            </pago20:Pago>
        </pago20:Pagos>
    </cfdi:Complemento>

**Comment by jccastillo0007** [comment]
ya esta generando el xml con el complemento de pago y los impuestos respectivos del escenario básico, pero finkok sigue diciendo que hay error en lso schemas... hay que checar con ellos

**Comment by RigoFlores** [comment]
ya timbra los escenarios básicos:

a) varias facturas con uno o mas productos, todos con iva 16% únicamente, en MXN
b) varias facturas con misma tasa de IVA y retenciones del mismo tipo y tasa (ISR 1.25%), en MXN

**Comment by RigoFlores** [comment]
El siguiente escenario que no timbra es cuando en la factura, de un solo productos se incluye mas de 1 retención, en este caso 2 retenciones, en MXN.

Aquí tienes la factura XML y el pago en XML con comentarios de lo que está mal y cómo debería ir...

[1factura 1 producto varis retenciones.zip](https://github.com/jccastillo0007/eFacturaT/files/8051923/1factura.1.producto.varis.retenciones.zip)

**Comment by RigoFlores** [comment]
el siguiente escenario no timbra. Son 2 facturas con distintas retenciones y distintas bases de la retención.  En MXN.

Aquí tienes la factura XML y el pago en XML con comentarios de lo que está mal y cómo debería ir...

[2facturas varias retenciones.zip](https://github.com/jccastillo0007/eFacturaT/files/8051990/2facturas.varias.retenciones.zip)

**Comment by RigoFlores** [comment]
este es un escenario simple, de una factura originalmente emitida en USD y pagada en MXN.
mismo caso, se menciona en el XML lo que está incorrecto y correcto

[facturaenUSD simple.zip](https://github.com/jccastillo0007/eFacturaT/files/8052156/facturaenUSD.simple.zip)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
falta el tercer escenario, que es el de USD. 
Creo que resolviendo ese, se desatoran varias cosas.

**Comment by jccastillo0007** [comment]
lo acabo de hacer, funciono tal cual esta ahorita el cálculo, pero sin hacer conversiones de moneda, chiaaa
[pagos.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8054177/pagos.xml.txt)

**Comment by jccastillo0007** [comment]
ya esta generando el xml tal cual se solicitó, peeero, Finkok dice que:  

El campo BaseP que corresponde a Traslado, no es igual a la suma de los importes de las bases registrados en los documentos relacionados donde el impuesto del documento relacionado sea igual al campo ImpuestoP de este elemento y la TasaOCuotaDR del documento relacionado sea igual al campo TasaOCuotaP de este elemento.

Al parecer  la conversión de las cantidades en los impuestos, de acuerdo a la equivalencia, no lo esta aceptando

[pagos.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8065722/pagos.xml.txt)

**Comment by RigoFlores** [comment]
si, lo checaré con ellos.
Por lo pronto, ya se cubrió lo que se solicitó en este issue.
Vamos a esperar la respuesta de finkok. Yo pienso que interpreté bien la spec y la guía de llenado, pero pues ellos tienen la sartén por el mango.

**Comment by RigoFlores** [comment]
La respuesta de finkok es la siguiente:

Revisando el XML que amablemente nos comparte podemos observar que se debe a que se esta haciendo incorrectamente la operación. 

Para sacar la BaseP se realiza BaseDR / EquivalenciaDR, en su XML podemos observar que tiene en su BaseP 2100.000000 pero realizando la operación podemos observar que da de resultado 2100.002100 ya truncado hasta 6 decimales, ese sería el valor correcto.

Se pasan de corneta, en algunos casos, si a dos putos decimales, y aquí a 6. Para pinches saber??
Pero bueno, los cálculos todo está bien, excepto que quieren que se reporte a 6 decimales los importes del nodo ImpuestosP. Debe truncarse a 6 decimales.

**Comment by jccastillo0007** [comment]
listo, ya esta funcionando, y ya timbro el ejemplo que estabamos manejando....

**Comment by RigoFlores** [comment]
lo cerraré, aunque hay varios escenarios por probar.
Ya abriremos otros, si es necesario.
