### ISSUE TITLE
Complemento de nómina para cfdi v4.0 - generales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1909]
Pues si, resulta que a varias cosas le ha pegado estos cambios. 
Aquí los cambios generales para nómina. Al parecer serían todo, pero ya validaré cuando se atienda.

1. Actualizar los URLS, esquemas, location etc...  
2. Exportación - valor fijo 01
3. InformaciónGlobal - no debe existir
4. Régimen fiscal receptor - debe ser "605"
5. uso de CFDI - debe ser "CN01"
6. ObjetoImp - debe ser "01"
7. los atributos FechaPago, FechaInicialPago, FechaFinalPago y FechaInicioRelLaboral se homologa la forma de expresión del formato fecha, esto es: AAAA-MM-DD

**Comment by jccastillo0007** [comment]
oye, los puntos 1 al 6 son del cfdi 4, eso ya esta implementado.

Solo faltaría ver el tema de las fechas de la nómina como tal

Probablemente el punto 5 también se deba forzar cuando es nómina.

**Comment by RigoFlores** [comment]
Pues se trata de revisar todos. Algunos ya están, pero no todos.
4 al 7, hay que dejarlos fijos así.
El CFDI 4.0 que hoy ya timbra, tiene fijos algunos datos. No significa que así tengan que quedar siempre, no.

Y bueno, la intención es implementar estos cambios, siento que nos está ganando el tiempo y no veo que la vayamos a librar... te comenté que me quedaría a documentar esto el viernes, precisamente para ver si salía el fin de semana ya .

**Comment by jccastillo0007** [comment]
no sé si sea buena idea dejarlos fijos... pero bueno, solo aplica para el 4 y 5, los otros no es necesario hacer algo en específico.

**Comment by RigoFlores** [comment]
pues hice un recibo, y le puso versión del cfdi 3.3, jaja.
Este cambio es para el cfdi 4.0

**Comment by RigoFlores** [comment]
Lo que si ya se atendió:

Actualizar los URLS, esquemas, location etc...
Exportación - valor fijo 01
InformaciónGlobal - no debe existir
ObjetoImp - debe ser "01"


Lo que no hizo:

Régimen fiscal receptor - debe ser "605"
uso de CFDI - debe ser "CN01"
los atributos FechaPago, FechaInicialPago, FechaFinalPago y FechaInicioRelLaboral se homologa la forma de expresión del formato fecha, esto es: AAAA-MM-DD

De hecho no incluyó siquiera el complemento de nómina

**Comment by jccastillo0007** [comment]
ya quedo lo del régimen fiscal y uso del cfdi, 

Respecto a las fechas, yo no le puedo dar formato eso es del schema

Ahorita el error que se recibe es:   

El campo DomicilioFiscalReceptor del receptor, debe encontrarse en la lista de RFC inscritos no cancelados en el SAT.

**Comment by RigoFlores** [comment]
Pues no está reportando el domicilio fiscal del receptor. Chiaaaaaa

No estoy levantando tooodos los requisitos, se supone que está corriendo sobre cfdi 4.0

**Comment by jccastillo0007** [comment]
ok, ya corregí eso, peeeero, en pantalla no existen campo para capturar el domicilio fiscal del empleado, o al menos el código postal, por ahora le puse directo en base de datos al empleado que estamos usando.

**Comment by jccastillo0007** [comment]
este error que pedo, pinche finkok :

 El valor del campo Descuento debe tener hasta la cantidad de decimales que tenga registrado el campo importe del concepto.

**Comment by RigoFlores** [comment]
el descuento debe ir con 2 decimales me parece

**Comment by RigoFlores** [comment]
Ya con el tema del descuento corregido... que a nivel concepto debe ir a 2 decimales (que yo no creo que eso sea necesario, según la documentación del SAT), ahora marca lo del schema locations.
Al igual que en CCE, deben de ir en el header.
Así los tenemos en producción.
