### ISSUE TITLE
PROBLEMAS CON KEY GENERATOR WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#191]
a) No permite incluir plugines
b) No corre en Windows explorer (la versión anterior si). El tema es visual, no se acomodan ni despliegan bien los controles, o la información.

**Comment by jccastillo0007** [comment]
lo de los plugins ya esta listo
lo de IE, no maaaaaa usalo en chrome hasta se ver mejor lol

Falta agregarle la funcionalidad para que puedas editar datos de clientes existentes, asi como agregar folios... la sig semana espero que ya lo terminen.

**Comment by jccastillo0007** [comment]
Ya esta listo el keygen... solo falta ver lo de IE...

**Comment by RigoFlores** [comment]
lo del IE realmente no es tanto problema. Lo que me preocupa es que la aplicación final en web, presente este comportamiento. Recuerdo que Edú, tuvo que hacer algo particular para que jalara en IE.
Lo importante es no descuidar el punto en el ERP. Para el keygenerator, no hay pexcado.
