### ISSUE TITLE
CFDI 4.0 - Uso de CFDI web y escritorio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1910]
En web aplica en pantalla de facturación y en catálogo de clientes.
En escritorio, solo en la pantalla de facturación.

**Desaparece:** 
P01 Por definir

**Se agregan:**
S01	Sin efectos fiscales.  
CP01	Pagos
CN01	Nómina

**Comment by jccastillo0007** [comment]
ya esta listo en web, para standalone hay que crear otro ticket, NO MEZCLAR requerimientos diferentes en el mismo ticket, y si no mal recuerdo, de entrada quedamos en no modificar standalone, hasta ver si podemos migrarlos a todos a web

**Comment by RigoFlores** [comment]
lo veo igual

**Comment by jccastillo0007** [comment]
Recuerda usar siempre para todo la versión cfdi4 de efacturat, chiaa

**Comment by RigoFlores** [comment]
pues si, el user es IVD... y no, no está actualizado, sigue con lo anterior.

**Comment by RigoFlores** [comment]
ya vi, falta eliminar el P01, por definir

**Comment by jccastillo0007** [comment]
listo
