### ISSUE TITLE
CFDI 4.0 - catálogo objImp y catálogo de exportación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1911]
Para catálogo objI,p ahora mismo, se envía me parece 02. En la pantalla de facturación, hay que agregar este catálogo con el 02 como valor por omisión. Que lo elijan de una lista.

01	No objeto de impuesto.
02	Sí objeto de impuesto.
03	Sí objeto del impuesto y no obligado al desglose.

Para exportacion:

01	No aplica - cuando no incluya el CCE, se deberá enviar 01
02	Definitiva
03	Temporal

Para el caso del CCE, deberemos agregar un dato adicional en el XML de configuración, donde se indique el valor, que podrá ser 02 o 03. Entonces este dato quedará fijo a 01 para todo CFDI4.0, excepto para el complemento de comercio exterior.

**Comment by RigoFlores** [comment]
Eso es para el catálogo de ObjImp y Exportación.
Si ponemos las 2 listas en la pantalla de facturación y por default lo que mas se ocupa. 

En ambos el caso 03, desconozco cuándo aplica?

**Comment by RigoFlores** [comment]
lo de importación ya se definió que se enviará 01 siempre, excepto cuando se incluya el CCE. El 03, lo trabajaremos "cuando lo pidan".

Para el caso de objImp, creo que en lugar de ID, se puede mostrar el catálogo. 
Valor por omisión 02

**Comment by jccastillo0007** [comment]
pues yo creo que no es necesario ahorita, ya se manda 01 o 02 según sea el caso de que el concepto tenga o no impuestos... y como no sabemos para que es el 03, hay que esperar a que alguien lo pida

**Comment by RigoFlores** [comment]
ahí para que veas, si estamos tomando decisiones que eventualmente pueden influir en el pago de impuestos...
lo podemos dejar así por lo pronto, pero no lo veo para nada adecuado.
Investigaré cuándo aplica la opción 3, para ver si lo automatizamos

**Comment by jccastillo0007** [comment]
o cuando un cliente lo pida

**Comment by RigoFlores** [comment]
es que no es que lo pida, es parte del estándar de cfdi 4.0
pero ya, salimos así en lo que investigo que pex
