### ISSUE TITLE
Pendientes generales para la actualización de cfdi, nómina, pagos, cancelación, retenciones, conector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1912]
Pendientes generales de la actualización

Cancelación 2022
1) cancelación con otros pacs
2) Complementar acuse de recibo (con motivo y UUID relacionado, cuando aplique)
3) Implementar esquema de cancelación en escritorio.

CFDI4.0
Implementar Factura Global
Implementar Exportación (realmente afecta en la pantalla de captura del CCE)
objetoImp - agregar el droplist catálogo en la pantalla de facturación
Base retenciones - validar si es necesario o no, guardar el resumen de impuestos retenidos a nivel cfdi, para propósitos del complemento de pago

Nómina:
todo los cambios pendiente

Pago2.0:
En proceso

CCE
Validar que se genere, y además agregar el parámetro de Exportacion en el XML de configuración.

Conector:
Validar el layout definitivo
Definir el layuoy de nómina
Definir el layout de pagos
Layout Cancelación
Cancelación en pantalla

Conector Españoles:
CFDI
Pagos

Conector Optibelt:
CFDI
CCE

Conector Abastos:
Pantallas de faturación.

Documento de retenciones 2.0
Falta todo

**Comment by RigoFlores** [comment]
Cancelación 2022 - subí un acuse tipo lo que entrega el sat, para que lo tengas de referencia.
Pregunté a FHoy, que pex con la cancelación de otros PAC's

CFDI4.0
Factura Global, ya subí las descripciones de los catálogos.
ObjetoImp y Exportacion, se subió la descripción de estos catálogos.

**Comment by jccastillo0007** [comment]
puedes actualizar el primer comentario, para ver que ya esta y que falta?

**Comment by RigoFlores** [comment]
eliminé de  la lista lo que ya está.

Cancelación 2022

1. Cancelación con otros PACS
2. Complementar acuse de recibo (con motivo y UUID relacionado, cuando aplique)
3. Implementar esquema de cancelación en escritorio.

CFDI4.0
Implementar Factura Global . se agregaron los campos, pero no se envían al XML.
objetoImp - agregar el droplist catálogo en la pantalla de facturación - 

Nómina:
todo los cambios pendiente - 

Pago2.0:
En proceso, HEMOS AVANZADO EN LOS ESCENARIOS QUE DEBEN CUBRIR EL 80% DE LOS CASOS, PERO FALTAN LOS AJUSTES FINOS.

Faltan los ajustes para los PDF.

DE AQUÍ HACIA ABAJO, FALTA TODO.

Conector:
Validar el layout definitivo
Definir el layuoy de nómina
Definir el layout de pagos
Layout Cancelación
Cancelación en pantalla

Conector Españoles:
CFDI
Pagos

Conector Optibelt:
CFDI
CCE

Conector Abastos:
Pantallas de faturación.

Documento de retenciones 2.0
Falta todo

**Comment by jccastillo0007** [comment]
Cancelación 2022

Escenarios de cancelación:

Web
CFDi 3.3 timbrado por facture hoy // Se queda en la versión 3.3 de efacturat
CFDi 3.3 timbrado por finkok // Se queda en la versión 33 de efacturat

CFDi 4.0 timbrado por facture hoy // DONE
CFDi 4.0 timbrado por finkok

Complementar acuse de recibo (con motivo y UUID relacionado, cuando aplique) DONE <falta agregar esos datos a la plantilla>

Standalone conector y pantalla
CFDi 3.3 timbrado por facture hoy // Se queda en la versión 3.3 de efacturat
CFDi 3.3 timbrado por finkok // Se queda en la versión 3.3 de efacturat

CFDi 4.0 timbrado por facture hoy - DONE
CFDi 4.0 timbrado por finkok
Complementar acuse de recibo (con motivo y UUID relacionado, cuando aplique) DONE <falta agregar esos datos a la plantilla>

Conector:
Timbrado de nómina
Timbrado de pagos 

Conector Españoles (Ya no se va usar, se implementará un web service)

Conector Optibelt 
CFDI
CCE

Abastos:
No hay cambios en conector
Actualizar Pantallas de facturación al instante, facturación normal, Registro y mi perfil en el DescargaT

DescargaT, soportar CFDi 4.0
Documento de retenciones 2.0, terminar pruebas

**Comment by jccastillo0007** [comment]
Cancelación 2022

Escenarios de cancelación:

Web
CFDi 4.0 timbrado por finkok

Connector
CFDi 4.0 timbrado por finkok


Conector:
Timbrado de pagos

Conector Optibelt
CFDI
CCE

Abastos:
No hay cambios en conector
Actualizar Pantallas de facturación al instante, facturación normal, Registro y mi perfil en el DescargaT

DescargaT, soportar CFDi 4.0
Documento de retenciones 2.0, terminar pruebas

**Comment by RigoFlores** [comment]
A ver, creo que falta todo esto:

**conector - pago:**


Pagos en MXN a factura emitidas en USD u otra moneda:
Pago total a 1 factura con IVA
Pago total a n facturas con IVA
Pago total a 1 factura con IVA y retenciones
Pago total a n facturas con IVA y retenciones
Pago parcial a 1 factura con IVA
Pago parcial a n facturas con IVA
Pago parcial a 1 factura con IVA y retenciones
Pago parcial a n facturas con IVA y retenciones

**Conector de Optibelt** Parsear los 2 nuevos datos del cliente, el resto permanece igual en el layout.
**Conector de IP Ingeniería** (los españoles; realmente es un Web Service)
**Rest Service ASUC** (Universidad de Arkansas). Son 6 servicios a desarrollar.


**DescargaT**- Abastos  (agregar el régimen y el código postal)
Pantalla de Pefil
Pantalla de Registro
Pantalla de Factura al Instante

**Cancelación**
4.0 con otros PAC's


**Versión de Escritorio**
Catálogo de Clientes
Timbrado en 4.0
Cancelación desde consultas

**Comment by jccastillo0007** [comment]
Estos escenarios, me parece que ya estan jalando

Cancelación
3.3 con otros PAC's

conector - pago:
MXN
Pago parcial a 1 factura con IVA

**Comment by RigoFlores** [comment]
ya actualicé el status, eliminé lo de pagos parciales en MXN a facturas en MXN.
Agregué los servicios para ASUC. Por confirmar, ya ves que esperaban que estuviera timbrando.

**Comment by jccastillo0007** [comment]
todo esto ya esta jalando?

conector - pago:

Pagos en MXN a factura emitidas en USD u otra moneda:
Pago total a 1 factura con IVA
Pago total a n facturas con IVA
Pago total a 1 factura con IVA y retenciones
Pago total a n facturas con IVA y retenciones
Pago parcial a 1 factura con IVA
Pago parcial a n facturas con IVA
Pago parcial a 1 factura con IVA y retenciones
Pago parcial a n facturas con IVA y retenciones

**Comment by jccastillo0007** [comment]
Puedes probar lo de optibelt con la versión que subí hoy.
Probé con este archivo
[MXRE221112772.TXT](https://github.com/jccastillo0007/eFacturaT/files/8820304/MXRE221112772.TXT)
:

**Comment by jccastillo0007** [comment]
Esto ya esta listo.

Versión de Escritorio
Catálogo de Clientes
Configuración del Emisor
Timbrado en 4.0

Probado con un cfdi normalito

**Comment by RigoFlores** [comment]
voy a cerrar este issue, y me abriré issues individuales para lo que vaya faltando.
La referencia es y será el documento de excel.
Cada pendiente en excel, debe tener un issue en github para que empate...
