### ISSUE TITLE
Implementar nuevo esquema de cancelación, con otros PAC's

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1913]
Ya mandó la info FHoy.
Además de la cancelación con otros PAC's, revisar lo del formato PDF del acuse de cancelación.
Debe parecerse a esto (de hecho le faltaría motivo de cancelación y UUID relacionado, cuando aplique):

[Verificación de Comprobantes Fiscales Digitales por Internet.pdf](https://github.com/jccastillo0007/eFacturaT/files/7999207/Verificacion.de.Comprobantes.Fiscales.Digitales.por.Internet.pdf)

**Comment by jccastillo0007** [comment]
aqui hay un tema, no se puede probar, solo en producción, pero saldría hasta que liberemos la versión cfdi4.0

**Comment by jccastillo0007** [comment]
ya están los cambios de código, incluso para mandar el motivo y los cfdi relacionados al jasper.

Pásame el nuevo template, aunque no lo podemos probar por ahora

**Comment by RigoFlores** [comment]
en cuáles variables envías el motivo y los cfdis relacionados?
para agregarlos a la plantilla...

**Comment by jccastillo0007** [comment]
cierto, se llaman :  

	private String motivo;
	private String cfdiRelated;

**Comment by RigoFlores** [comment]
Aquí está la platilla modificada, cómo la probamos?
Quieres que cancele una factura en producción de la tia?

[cfdi_AcuseCancelacion.jrxml.txt](https://github.com/jccastillo0007/eFacturaT/files/8146990/cfdi_AcuseCancelacion.jrxml.txt)

**Comment by jccastillo0007** [comment]
Hasta que se libere la versión de facturat cfdi4.0
