### ISSUE TITLE
Implementar Retenciones 2.0 - urls y cambios en nombres de atributos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1914]
Hay que tomar en cuenta los nuevos url de schema location, namespace, etc. para la versión 2.0

Adicionalmente, cambian los nombres de los siguientes atributos:

Anterior  - nuevo
NumCert  -  NoCertificado
Cert  -  Certificado
RFCEmisor  -  RfcE
RFCRecep  -  RfcR
CURP  -  CurpR

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
ok, lo de la curp no lo pude validar, ya que en pru, tenemos persona moral.
