### ISSUE TITLE
Retenciones 2.0 , implementar lo nuevo.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1915]
Aquí expongo una tabla con los cambios, mencionando el nodo y el nombre del atributo.

existen 2 nodos nuevos. Para cuando el receptor es extranjero, y para cuando se requiere relacionar un cfdi con otro.
Para el receptor extranjero, pues hay que poder elegir del catálogo de clientes por rfc. Si el RFC es XEXX010101000, entonces dar la opción para elegir el nombre alterno. En otro caso se elige como hoy, el RFC nacional

NODO - ATRIBUTO - COMENTARIO
header - LugarExpRetenc - Código postal del emisor
header - DescRet - descripción de la retención; se toma del catálogo
header - CfdiRetenRelacionado - nodo nuevo para poder relacionar a otro UUID. Debe buscar UUID de tipo retención
CfdiRetenRelacionado - tipoRelacion - es el catálogo de tipos de relación
CfdiRetenRelacionado - UUID
Emisor - RegimenFiscalE - se agrega la clave del régimen fiscal, se toma de la configuracion
Receptor-Nacional - DomicilioFiscalR - código postal del receptor; se toma del cátolo de clientes.
Receptor - Extranjero - es un nodo nuevo; se agrega al catálogo de clientes; se elige como cualquier otro cliente.
Receptor-Extranjero - NumRegIdTribR - se agrega al catálogo de clientes, es el equivalente al RFC en el extranjero
Receptor-Extranjero - NomDenRazSocR - se agrega al catálogo de clientes, es el nombre del cliente en el extranjero.
Totales - UtilidadBimestral - se agrega a la pantalla de captura
Totales - ISRCorrespondiente - se agrega a la pantalla de captura

**Comment by jccastillo0007** [comment]
tienes la definición del schema de retenciones 2.0 ?

**Comment by RigoFlores** [comment]
de esta liga puedes llegar a él...

https://www.sat.gob.mx/consultas/43074/actualizacion-factura-electronica---reforma-fiscal-2022-

y aquí lo tienes...

[Pagos20.xsd.zip](https://github.com/jccastillo0007/eFacturaT/files/8073795/Pagos20.xsd.zip)

**Comment by jccastillo0007** [comment]
me confunde que se refieran a retenciones e información de pagos, y por otro lado esta lo de CCP 2.0

como esta el pedo ahi?

**Comment by RigoFlores** [comment]
chiaaaa....
nombre completo... _**Constancia de retenciones e información de pagos**_. La nueva versión será la 2.0.
Coincide con la nueva versión del CFDI con complemento de pago.

El menú donde se emite es este:
<img width="704" alt="retencionesypagos" src="https://user-images.githubusercontent.com/2912775/154336910-ccea16ac-6ed8-4180-93b3-b06af98d6880.PNG">

**Comment by jccastillo0007** [comment]
ok, pero no tienen nada que ver com pagos

**Comment by RigoFlores** [comment]
no, nada que ver...

**Comment by jccastillo0007** [comment]
wey, porque me pusiste el schema de pagos en este ticket? estas viendo y no ves... de por si estaba confundido

**Comment by jccastillo0007** [comment]
wey, porque me pusiste el schema de pagos en este ticket? estas viendo y no ves... de por si estaba confundido

**Comment by RigoFlores** [comment]
[CFDI_Retencionv20.xsd.zip](https://github.com/jccastillo0007/eFacturaT/files/8145644/CFDI_Retencionv20.xsd.zip)


tssss, chiaaalesss... eso fue hace 10 días
jajaja

**Comment by jccastillo0007** [comment]
ya están implementados los cambios, y también los cambios para la cadena original.

Marca el error que decias :   

 update status : 124 : 300 - El XML no tiene codificación UTF-8

Verifiqué el xml con finkok, y manda esto :  


Reten20101 El resultado de la digestión debe ser igual al resultado de la desencripción del sello.


Total que no sé por donde revisar, puedes hacer una prueba para ver si ves algo que estoy haciendo mal, ni idea porque facture hoy dice que no esta en UTF-8

**Comment by RigoFlores** [comment]
te mandé un correo, con los comentarios de fhoy.
Eso lo tenemos sin funcionar desde hace un buen rato.

**Comment by RigoFlores** [comment]
Marcó error con fhoy. Como mencionaste, espera la versión 1.0 
Pero no hay implementado nada de lo nuevo.
Se mandó tal cual lo tenemos ahora mismo. es decir, los cambios solicitados no están implementados en el XML

**Comment by RigoFlores** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<retenciones:Retenciones xmlns:retenciones="http://www.sat.gob.mx/esquemas/retencionpago/2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="2.0" FolioInt="RET1" Sello="BdU0AfoYSIyhNi5InJAX3gQ7ZzngXhg3VTVEkDNTImvDyR49KK/77F2iraXSy84ZxwVrK0hED3zlOxwf1tQjAEzVIElTkv6WBJaxHwYsdfZqoYUp84td+2E11wg3PXEL8neaHUX/qRkCajSahwlL/WhTH/MXRvZTOX7w0Gb+uQ5QHnKdkAVa7FSJn39lxJSqt2J+1yf4WJAwA76rPfoOI6kdCWPeLVRROle7b3IAqOULph1d0aFg60HnrR+A8QnBS7nE7n8az71Ge7CH/ycrdukXODqRj48dnESy56ZQPNPrAGhd6bl1DS8hOtGPSIEk5VqBlxcsPJ5YEzV5h4so+g==" NoCertificado="30001000000400002438" Certificado="MIIF0jCCA7qgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDI0MzgwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNjE3MjAwNDEyWhcNMjMwNjE3MjAwNDEyWjCB+TEpMCcGA1UEAxMgSU5OT1ZBQ0lPTiBWQUxPUiBZIERFU0FSUk9MTE8gU0ExKTAnBgNVBCkTIElOTk9WQUNJT04gVkFMT1IgWSBERVNBUlJPTExPIFNBMSkwJwYDVQQKEyBJTk5PVkFDSU9OIFZBTE9SIFkgREVTQVJST0xMTyBTQTElMCMGA1UELRMcSVZEOTIwODEwR1UyIC8gS0FITzY0MTEwMUIzOTEeMBwGA1UEBRMVIC8gS0FITzY0MTEwMUhOVExLUzA2MS8wLQYDVQQLFCZJTk5PVkFDSdNOIFZBTE9SIFkgREVTQVJST0xMTyBTQSBERSBDVjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIKn3U4zMIEGfAICsDCSD4EQwQbabWJOdQpXdnAeCqwIH/vAbnv4t7Rc1NFMJg2OeCK5L6g+Pj/DlWftOeqRo8KIzW04xtq6rWSxXXuhGDm9hdRF15JEoxJnpDmkqKLEpbLJqZ4mOdKOHdmEdQ4O3dd0njeNGdjhU5+Vl4J9rHVjA4BoJpsP75BQeIwDdFIVxcb60sKna0mG58lMq5tNK6CtozeyrC94IED9GARG0gKuXlswTrWrI1N3/VOI7jjZY6YeIeO5jcbXrCiqGxGduJrGHqyrxGPTIXlZ7iW8zMT1G8QRF5rWutg4+MysIsjrcFrexbP5TMaRBYyASeBd94kCAwEAAaMdMBswDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCBsAwDQYJKoZIhvcNAQELBQADggIBAJVqgdQ+NOSIBKbWBBSARmX5C0wiq0BfRz4Ub7dVGguHoPAB4dJAtL540b3Klid90EwtNSCCFSc9OPQ0mWVRkCz0OtceLKAXzKqzVOcXrxmydlbT0brNBkULDV54Gdup1B42mmCh0hoRaNvr0QkJnKEMTmHt3m47xnV9XfOeUcSDciCTMV4wRns3JdCr7g0PMyWpV5yRLJNr8w9YCm6YesSqCJLZIvWbFGRuDhHfgsyImtMuTNbclbI7XFue2B4awi3a9H8yfgf33bGgeLhVCAbILd63LQv67zGdt3H8s2Xe4umQmh+9gyJG4fmbZmUd3wFl/fY9kmdTxZfufqPbdyV/G7g0Hq3mmzS1TuRG2Hj+y4lVzLOV6RXJjIQ+Qp+5ePKl4d/oeAIsTzmWsZc0c+yJ1MMbCn6CHTlNvdwROOhpanNjEHJ2kLwh5nhoVSRbRF/owuBreO5FbJKZE+L+8mzYEIhKUiD03WW03BOPCCQFFvBFC0AoN7wS0zFm1g2gNV95pgZwp1LsqlwBSAVF9SS/MKiE7Mv0UryWEBYllo66XY8VMFzZYAjSuEudoK3xSsCdjaA/Wjx85/3RCEV3J7LO5m6mwYgrQIaTwuYWuCTUE8XKxj7cjNo1UF6LbL77nzbYmS3sUXE4Jly8xxOYsyDX8B+8TNW++g1mB3bt+OHv" FechaExp="2022-03-02T17:59:08-06:00" CveRetenc="01" xsi:schemaLocation="http://www.sat.gob.mx/esquemas/retencionpago/2 http://www.sat.gob.mx/esquemas/retencionpago/2/retencionpagov2.xsd">
    <retenciones:Emisor RfcE="IVD920810GU2" NomDenRazSocE="INNOVACION VALOR Y DESARROLLO"/>
    <retenciones:Receptor NacionalidadR="Nacional">
        <retenciones:Nacional RfcR="FOPR681125BQ0" NomDenRazSocR="RIGOBERTO MISAEL FLORES DE LA PAZ"/>
    </retenciones:Receptor>
    <retenciones:Periodo MesIni="1" MesFin="2" Ejercicio="2020"/>
    <retenciones:Totales MontoTotOperacion="100.0" MontoTotGrav="200.0" MontoTotExent="0.0" MontoTotRet="10.0">
        <retenciones:ImpRetenidos BaseRet="100.0" ImpuestoRet="01" MontoRet="10.0" TipoPagoRet="Pago definitivo"/>
    </retenciones:Totales>
</retenciones:Retenciones>

**Comment by RigoFlores** [comment]
este es el ticket de retenciones

**Comment by jccastillo0007** [comment]
Campos adicionales

NODO - ATRIBUTO - COMENTARIO
header - LugarExpRetenc - Código postal del emisor
header - DescRet - descripción de la retención; se toma del catálogo
header - CfdiRetenRelacionado - nodo nuevo para poder relacionar a otro UUID. Debe buscar UUID de tipo retención
CfdiRetenRelacionado - tipoRelacion - es el catálogo de tipos de relación
CfdiRetenRelacionado - UUID
Emisor - RegimenFiscalE - se agrega la clave del régimen fiscal, se toma de la configuracion
Receptor-Nacional - DomicilioFiscalR - código postal del receptor; se toma del cátolo de clientes.
Receptor - Extranjero - es un nodo nuevo; se agrega al catálogo de clientes; se elige como cualquier otro cliente.
Receptor-Extranjero - NumRegIdTribR - se agrega al catálogo de clientes, es el equivalente al RFC en el extranjero
Receptor-Extranjero - NomDenRazSocR - se agrega al catálogo de clientes, es el nombre del cliente en el extranjero.
Totales - UtilidadBimestral - se agrega a la pantalla de captura
Totales - ISRCorrespondiente - se agrega a la pantalla de captura

**Comment by jccastillo0007** [comment]
Campos que faltan 

header - CfdiRetenRelacionado

**Comment by jccastillo0007** [comment]
Rijo.

1. El campo para extranjero de NumRegIdTrib, se puede seguir manejando como RFC, para no agregar otro campo... ?
2. Podemos salir sin CFDIRelacionados ?

**Comment by jccastillo0007** [comment]
ya están los cambios en PRU, genera un XML como este:
[retenciones.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8367848/retenciones.xml.txt)

**Comment by jccastillo0007** [comment]
Puedes probar en producción ?

**Comment by RigoFlores** [comment]
ya probé en producción y marcó error.
Le estoy preguntando a FHoy que me comente por donde va el problema.
Ya está abierto el ticket con ellos.
