### ISSUE TITLE
Nómina 1.2 + CFDI 4.0 - no incluir forma de pago, y respetar el tipo de régimen del trabajador

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1917]
Finkok espera que ya no se incluya la forma de pago.
Por otro lado solicité que el **régimen fiscal del receptor** (conforme al CFDI 4.0), se dejara fijo a 605. Eso está bien.

<cfdi:Receptor Rfc="FOPR681125BQ0" Nombre="RIGOBERTO MISAEL FLORES DE LA PAZ" DomicilioFiscalReceptor="76090" **RegimenFiscalReceptor="605"** UsoCFDI="CN01"/>
   

Lo que está mal y NO SE SOLICITÓ, es que el tipo de régimen del trabajador se deje fijo. Ese debe ser el que se seleccione de la lista:

<nomina12:Receptor Antigüedad="P844W" ClaveEntFed="QUE" Curp="FOPR681125HDFLZG09" FechaInicioRelLaboral="2005-11-07" NumEmpleado="001" NumSeguridadSocial="12345678" PeriodicidadPago="04" RiesgoPuesto="1" SalarioBaseCotApor="100.0" SalarioDiarioIntegrado="120.0" Sindicalizado="No" TipoContrato="01" TipoJornada="01" **TipoRegimen="605"**/>

El tipo de régimen por ejemplo es Sueldos y Salarios (clave 02, me parece).

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
marca error, pero ya es otra cosa, checaré con finkok.

**Comment by RigoFlores** [comment]
sigue incluyendo forma de pago, eso NO debe existir

**Comment by jccastillo0007** [comment]
fixed
