### ISSUE TITLE
CFDI 4.0 + CCE, varios puntos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1918]
aquí algunos de los detalles por los que marca error. Unos quizás ya están implementados

**A NIVEL CFDI 4.0 (APLICA PARA TODOS LOS CFDIS)**

1. SI LA MONEDA DEL CFDI ES MXN, EL TIPO DE CAMBIO ES '1'. (sin punto ni decimales)

**NODO RECEPTOR:**

1. CUANDO EL RFC SEA XEXX010101000 EL DOMICILIO FISCAL DEL RECEPTOR, DEBE SER IGUAL AL DEL EMISOR (código postal). ESTO TIENE QUE HACERSE POR CÓDIGO, YA QUE EL CP DEL DOMICILIO FISCAL (CATÁLOGO DE CLIENTES), SE OCUPA EN EL CCE.
2. RESIDENCIA FISCAL Y NumRegIdTrib SOLO APLICA CUANDO EL RECEPTOR SEA XEXX010101000. (HOY LO ESTÁ REPORTANDO AUNQUE SEA UN RFC NACIONAL).

**A NIVEL COMPLEMENTO**

1. RECEPTOR, INCLUIR EL NumRegIdTrib CUANDO EL RFC DEL RECEPTOR SEA XEXX010101000. APARENTEMENTE ANTES NO SE INCLUÍA.

HAY QUE ATENDERLO ASÍ, Y YA SI ES NECESARIO ABRIMOS TICKETS PARA CUALQUIER TEMA, DE MANERA INDIVIDUAL.
HOY AL MENOS POR TODO ESTO, MARCA ERROR NO CLASIFICADO.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
nop

 LugarExpedicion="**61957**" xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd">
    <cfdi:Emisor Rfc="IVD920810GU2" Nombre="INNOVACION VALOR Y DESARROLLO" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="XEXX010101000" Nombre="OMEGA TOOL CORP" DomicilioFiscalReceptor="**52142**

cuando el receptor es XEXX, su domicilio fiscal debe ser (en jarcoud) el mismo código postal que el lugar de expedición.
Ya que el código postal capturado en catálogo de clientes, se ocupará en el complemento de carta porte

**Comment by jccastillo0007** [comment]
chiaaa, habias dicho que debe ser igual al zip code del emisor, mas no al lugar de expedición, ahi algo esta chueco... ya lo cambie haber si asi es lo correcto.

**Comment by RigoFlores** [comment]
Código postal del emisor = domicilio fiscal emisor. Es lo mismo.

**No se atendió este punto, QUE ES A NIVEL COMPLEMENTO.**

**A NIVEL COMPLEMENTO**

NODO RECEPTOR, INCLUIR EL NumRegIdTrib CUANDO EL RFC DEL RECEPTOR SEA XEXX010101000. APARENTEMENTE ANTES NO SE INCLUÍA.

Así se está entregando:

           **<cce11:Receptor>**
                <cce11:Domicilio Calle="FRAY LUIS DE LEON 3051 CONDOMINIO" CodigoPostal="52142" Estado="AB" Pais="CAN"/>
            </cce11:Receptor>

Igual no se está timbrando por otra razón, que voy a investigar..

**Comment by RigoFlores** [comment]
Ahorita ya revisé, lo del tipo de cambio va a ser un gran pedo. Pero bueno, ya me pasaron el tipo de cambio correcto y ya avanzó, pero efectivamente marcó error en lo que indiqué arriba del nodo receptor dentro del complemento. Le falta el NumRegIdTrib, que es de los puntos iniciales que se solicitaron.

**Comment by jccastillo0007** [comment]
ok, ya esta poniendo el NumRegIdTrib en el nodo receptor del CCE, lo esta tomando de los datos extras enviados, y en tu ejemplo se supone que es 12345678, pero marca error:

CFDI40156 : El campo NumRegIdTrib no cumple con el patrón correspondiente. 


Si es ese dato? o de donde se supone que se debe tomar?

**Comment by RigoFlores** [comment]
Si, estás bien tu.
Hay que cumplir con el formato, estoy en eso.
Pinche CCE es un pedo, cuadra un chingo de cosas, pero bueno... deja ver

**Comment by RigoFlores** [comment]
aún no timbra, pero ya se lo pasé a finkok.
necesitamos cachar sus otros mensajes de error, para poder avanzar mas rápido sin depender de sus respuestas.

ya nos comentaron donde podemos cachar info adicional de los errores
