### ISSUE TITLE
en la pantalla de nómina solicita como requerido la fecha de inicio laboral

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#192]
esta es opcional (tal como lo marca la spec). 
De hecho el error se presenta al momento de tratar de salvar el registro, sin este dato capturado.
Se verificó este comportamiento en el conector, ya que ahí no se incluye este dato, y no marca ningún error al momento de timbrado.

**Comment by jccastillo0007** [comment]
Fixed.
