### ISSUE TITLE
CFDI 4.0 + CCP , no está generando el complemento de carta porte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1922]
Probé en pru con IIA, es el RFC que está configurado para la emisión del CCP.
El PDF si lo genera aparentemente bien, pero en el XML no se está incluyendo el complemento.

**Comment by jccastillo0007** [comment]
fixed.

IIA estaba configurado para CCE igual que IVD

**Comment by RigoFlores** [comment]
oye, pero no puedo generar el complemento de carta porte en 3.3.
ya no es posible???
