### ISSUE TITLE
Complemento de pago - Monto total de pago incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1923]
El monto total de pago se calcula:

MontoTotalPagos = sumatoria de Cada Pago (Monto * Tipo de Cambio)

Pero en este ejemplo, de la factura 121, no está realizando el cálculo correctamente.
La factura 121 se emitió en USD, y se pagó en MXN. Entonces ahí aplicando la operación, el monto (del pago) x el tipo de cambio (1), pues debe dar exactamente la cantidad pagada, ya que está en MXN.
Incorrecto:  MontoTotalPagos="15146.85"
Correcto: MontoTotalPagos="15147.00"

    <cfdi:Complemento>
        <pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="15146.85" TotalRetencionesISR="165.00" TotalTrasladosBaseIVA16="13199.87" TotalTrasladosImpuestoIVA16="2111.98"/>
            <pago20:Pago FechaPago="2022-02-16T17:51:42" FormaDePagoP="03" MonedaP="MXN" Monto="15147.00" NumOperacion="fact121" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="0.045455" Folio="122" IdDocumento="17F2E220-7199-52D0-990E-F44E08BD0447" ImpPagado="688.50" ImpSaldoAnt="688.50" ImpSaldoInsoluto="0.00" MonedaDR="USD" NumParcialidad="1" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:RetencionesDR>
                            <pago20:RetencionDR BaseDR="600.000000" ImporteDR="7.5" ImpuestoDR="001" TasaOCuotaDR="0.012500" TipoFactorDR="Tasa"/>
                        </pago20:RetencionesDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="600.000000" ImporteDR="96.0" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:RetencionesP>
                        <pago20:RetencionP ImporteP="164.998350" ImpuestoP="001"/>
                    </pago20:RetencionesP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="13199.868001" ImporteP="2111.978880" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>
        </pago20:Pagos>
    </cfdi:Complemento>

**Comment by jccastillo0007** [comment]
es un tema del calculo de la equivalencia, y los 6 decimáles

0.045455 da un resultado diferente si fuera 0.45454

ahi nos esta pegando el redondeo

**Comment by jccastillo0007** [comment]
de hecho no me da el número cerrado 15147.00, cómo lo sacaste tu?

**Comment by RigoFlores** [comment]
Checa en el excel, chiaaaa...

El cálculo es la sumatoria para cada pago (en este caso, estamos soportando solo un pago y no varios) de:
monto (pagado) x tipo de cambio = 15147 x 1 = 15147

Esto en automático da la misma cantidad pagada.

<pago20:Pago FechaPago="2022-02-16T17:51:42" FormaDePagoP="03" MonedaP="MXN" Monto="15147.00" NumOperacion="fact121" TipoCambioP="1">

**Comment by jccastillo0007** [comment]
fixed, ya timbré el pago de la factura de prueba

**Comment by RigoFlores** [comment]
eliminé el pago que hiciste y repetí la prueba, con otra cantidad (finalmente cada quien se pinches inventa su tipo de cambio), y marcó error...
No veo que sea de nuestro lado, creo que es de finkok... pero bueno, ya levanté el ticket.

Dependiendo lo que diga, ya veo si reabro este issue.
