### ISSUE TITLE
Complemento de pago - no permite montos menores a los importes de las facturas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1924]
Ejemplo, quiero pagar una factura de 116 pesos.
Me la pagaron en USD, a un tipo de cambio de 21, entonces el pago sería 5.53

Si intento registrar ello, me marca que importe no suficiente.

Creo que ese mensaje lo genera el sistema. No se ve que llegue al PAC.
Debemos permitir este tipo de pagos. 
Finalmente los totales se reportan en MXN, esto sería MontoTotalPagos= 5.53*21=116.13

**Comment by jccastillo0007** [comment]
done, checale...

**Comment by RigoFlores** [comment]
sigue igual...

**Comment by jccastillo0007** [comment]
el error es diferente, para variar, va a estar complicado cuadrar las cifras, pero ya permite el intento de timbrado
![Screen Shot 2022-02-21 at 22 26 17](https://user-images.githubusercontent.com/2245679/155063131-8425f3a7-d912-44e5-a860-6cabdc0ff1f5.png)

**Comment by RigoFlores** [comment]
ahora lo voy a cerrar, pero ahí tenemos un tema.
Será motivo de otro issue.
