### ISSUE TITLE
CFDI 4.0, factura (ingreso) con tipo de factor = Exento, no reporta los impuestos a nivel general

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1925]
Lo reporta a nivel de producto, pero no a nivel cfdi. Este es el caso, IVA trasladado con tipo de factor = "exento".

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="01" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="producto de prueba 1" ValorUnitario="100.000000" Importe="100.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="100.000000" Impuesto="002" TipoFactor="Exento"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>

marca este error:

 El valor del campo TotalImpuestosTrasladados no es igual a la suma de los importes registrados en el elemento hijo Traslado

**Comment by jccastillo0007** [comment]
cómo lo puedo reproducir,?

**Comment by RigoFlores** [comment]
Pru, usuario IVD, ya dejé uno de los 2 IVA trasladados, el que dice 0... ton el valor de exento.
Tons al agregar producto, elige el IVA trasladado 0 que dice ahhí. Ya se iría como exento.

**Comment by jccastillo0007** [comment]
hice la prueba y lo reportó como tipo factor = taza y si lo timbró, chiaaaa

te falto cambiar el tipo factor en el catálogo

**Comment by jccastillo0007** [comment]
Listo, ya hace lo que dices que debe hacer, 

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="01" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="producto de prueba 1" ValorUnitario="100.000000" Importe="100.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="100.000000" Impuesto="002" TipoFactor="Exento"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="0.00">
        <cfdi:Traslados>
            <cfdi:Traslado Base="100.0" Impuesto="002" TipoFactor="Exento" TasaOCuota="0.000000" Importe="0.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>


Pero marca error : CFDI40212 : Debe existir el campo TotalImpuestosTrasladados.

**Comment by RigoFlores** [comment]
No se si esto se vea en el xsd, o si no lo estás heredando del cfdi3.3, pero los impuestos a nivel de concepto cuando es exento están bien, no así a nivel comprobante. 
Se requiere lo mismo que a nivel concepto:

**En el caso de que sólo existan conceptos con TipoFactor Exento, en este nodo solo deben
existir los atributos Base, Impuesto y TipoFactor.**

Cuando en los conceptos ÚNICAMENTE EXISTA EL TRASLADO CON TIPO FACTOR Exento, en ese caso:

Incorrecto:
<cfdi:Impuestos TotalImpuestosTrasladados="0.00">
    <cfdi:Traslados>
        <cfdi:Traslado Base="100.0" Impuesto="002" TipoFactor="Exento" TasaOCuota="0.000000" Importe="0.00"/>
    </cfdi:Traslados>
</cfdi:Impuestos>


Correcto:
<cfdi:Impuestos TotalImpuestosTrasladados="0.00">
    <cfdi:Traslados>
        <cfdi:Traslado Base="100.0" Impuesto="002" TipoFactor="Exento"/>
    </cfdi:Traslados>
</cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
ninguna de las dos, ni veo el xsd ya que ahi no se define funcionalidad, y tampoco se esta heredando de cfdi3.3, lo implemento de acuerdo a tus requerimientos
