### ISSUE TITLE
CFDI 4.0 + complemento de pago v2.0, marca error cuando la tasa de iva trasladado enla factura es 0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1926]
Cuando intentas generar un pago, con una factura con tasa de iva trasladado = 0, marca error.

Puedes reproducir, intentando el pago con la factura 125 del rfc IVD, en pruebas 4.0

**Comment by jccastillo0007** [comment]
que onda con este error 
CRP20204 : El valor del campo TotalTrasladosBaseIVA16 no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos BaseP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y en TasaOCuotaP el valor 0.160000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.


se supone que ya corregi este defecto, pero finkok manda eso

**Comment by RigoFlores** [comment]
Si, está incorrecto en este sentido. 
La factura 125 tiene una tasa del IVA trasladado = 0.
Existen varios atributos a nivel de totales, donde reportar los impuestos. Dependerá de la tasa. Para traslado son los siguientes, y en este caso de IVA tasa 0, te los resalto en negritas:

TotalTrasladosBaseIVA16
TotalTrasladosImpuestoIVA16
TotalTrasladosBaseIVA8
TotalTrasladosImpuestoIVA8
**TotalTrasladosBaseIVA0
TotalTrasladosImpuestoIVA0**
TotalTrasladosBaseIVAExento

y nosotros estamos reportando la tasa 0, en atributos que corresponden a la tasa 16. Ahí está el pedo.

    <cfdi:Complemento>
        <pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="100.00" **TotalTrasladosBaseIVA16="100.00" TotalTrasladosImpuestoIVA16="0.00"**/>
            <pago20:Pago FechaPago="2022-02-19T09:34:33" FormaDePagoP="03" MonedaP="MXN" Monto="100.00" NumOperacion="fact125" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="125" IdDocumento="B80EDCE9-E052-5C6C-B5D1-0C7EE14E096B" ImpPagado="100.00" ImpSaldoAnt="100.00" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="1" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="100.000000" ImporteDR="0.0" ImpuestoDR="002" TasaOCuotaDR="0.000000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="100.000000" ImporteP="0.000000" ImpuestoP="002" **TasaOCuotaP="0.000000"** TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>
        </pago20:Pagos>
    </cfdi:Complemento>

**Comment by jccastillo0007** [comment]
ya. timbró el pago de la factura 125
