### ISSUE TITLE
CFDI 4.0 + CCE, nodo concepto-valor unitario, debe ir máximo con 4 decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1927]
La verdad esto está medio cabrón, es decir es una mamada.
Pero bueno, el punto es que cuando el CFDI4.0, lleve el CCE, entonces el valor unitario debe ir máximo a 4 decimales. Hoy lleva 6.

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="USD" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="PRODUCTO EN USD" **ValorUnitario="100.000000"** Importe="100.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="100.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.000000" Importe="0.000000"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>

**Comment by jccastillo0007** [comment]
checale haber si el parche chacarron quedo bien

**Comment by RigoFlores** [comment]
si quedó... tssss.
No me late mucho eso de los parches, pero ni pedo... ojalá no pegue en otro lado.
