### ISSUE TITLE
Carta Porte - enviar en otro subreporte el listado de los orígenes y destinos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1928]
Nombre subreporte: origenDestino.jasper
Contendrá los n orígenes y destinos del carta porte. Iniciando siempre con los orígenes y luego los destinos.

Con este formato, cada origen, o destino:

Origen1 (ID: aquí va el id origen o destino )- TIA101020BP4  Tecnologias de Informacion Aplicada SA de CV 
AV UNIVERSIDAD, 361, Centro Sur Queretaro, QUERETARO, 76090, MEX Fecha Hora Salida: 01/02/2022

Se nos están complicando algunos requisitos de formato con los clientes, pero con este, creo que quedaría muy flexible.
Los datos los pueden enviar desglosados, o por ejemplo linea1OD y linea2OD, podrían llamarse las 2 variables para ese subreporte.

cómo la besibol?

**Comment by jccastillo0007** [comment]
es mejor mandar los datos por separados... asi quedaron las variables

	private String id = "";
	private String rfc = "";
	private String razonSocial = "";
	private String calle = "";
	private String noExt = "";
	private String colonia = "";
	private String municipio = "";
	private String estado = "";
	private String codigoPostal = "";
	private String pais = "";
	private String fechaSalida = "";

La lista de items del subreporte quedo con el nombre de ubicaciones

**Comment by jccastillo0007** [comment]
Ojo, los datos extra 1 y 2, se mandarán vacíos

**Comment by RigoFlores** [comment]
falta un dato, que indique si es origen y destino, y su número...
por ejemplo alias: Origen1, Destino2, etc

**Comment by RigoFlores** [comment]
Datos extra??

**Comment by RigoFlores** [comment]
ya subí el nuevo subreporte, pero marca esto:

2022-02-26 11:38:59,241 DEBUG [http-nio-8080-exec-91] (FileService.java:130) - Looking for this file (NEW PATH) : /eFacturaT/CFDI/20220226/393_IIA040805DZ4_TIA101020BP4_26Feb2022_113858.pdf
2022-02-26 11:38:59,280 ERROR [http-nio-8080-exec-91] (CFDCreatorImpl.java:125) - java.lang.NullPointerException
java.lang.NullPointerException
        at com.efacturat.core.util.jasper.beans.JasperCFDBean.setup(JasperCFDBean.java:915)
        at com.efacturat.core.util.jasper.beans.JasperCFDBean.<init>(JasperCFDBean.java:398)

estos son los reportes.
[complementocartaporte.zip](https://github.com/jccastillo0007/eFacturaT/files/8147161/complementocartaporte.zip)

**Comment by jccastillo0007** [comment]
listo... 

 El nuevo parámetro para definir el consecutivo de origen o destino es:  
 	private String type = "";

**Comment by RigoFlores** [comment]
marca el mismo error que cuando agregamos el 2o subreporte. No se cómo corregirlo, dime que hacer o tu corrígelo, pero sería bueno saber donde está el pedo.

Error retrieving field value from bean : ubicaciones
net.sf.jasperreports.engine.JRException: Error retrieving field value from bean : ubicaciones

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
marca error al generar el PDF, o algo así.
Parte del catalina es...
Caused by: java.lang.NoSuchMethodException: Unknown property 'unidad' on class 'class com.cfd.shared.utils.jasper.JasperOrigenDestinoBean'

Ya me traje el subreporte ubicaciones del servidor de pruebas, y no tiene ninguna mención a unidad. Pensaría que el error está en otro lado.
