### ISSUE TITLE
CFDI 4.0 - cuando TipoFactor="Exento", TotalImpuestosTrasladados no debe existir en el nodo Impuestos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1929]
Cuando en un CFDI, únicamente se incluyen impuestos con tipo de facto exento, entonces el total de impuestos trasladados, no debe existir. Ejemplos:

Incorrecto:

    <cfdi:Impuestos TotalImpuestosTrasladados="0.00">
        <cfdi:Traslados>
            <cfdi:Traslado Base="100.0" Impuesto="002" TipoFactor="Exento"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

Correcto:
    <cfdi:Impuestos >
        <cfdi:Traslados>
            <cfdi:Traslado Base="100.0" Impuesto="002" TipoFactor="Exento"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
listo , pero manda este error 
CFDI33183 : El valor del campo TotalImpuestosTrasladados no es igual a la suma de los importes registrados en el elemento hijo Traslado (3)

**Comment by RigoFlores** [comment]
es que ahora ya no envía en nodo de impuestos a nivel general, solamente lo envía a nivel de concepto... y eso es lo que está mal. Solo debía eliminar el atributo totalImpuestosTrasladados, pero no todo el nodo

**Comment by jccastillo0007** [comment]
a chinga, si es cierto, y no se porque

**Comment by jccastillo0007** [comment]
oye, hay un caso muy raro al momento de crear el xml, resulta que si no va el total de impuestos trasladados, asume que no hay impuestos, y por eso no agrega el nodo, apesar de que si hay un nodo de impuestos... estas totalmente seguro que debe ir asi?

**Comment by RigoFlores** [comment]
así me lo indicó finkok...
a ver voy a revisar, y te confirmo...

**Comment by RigoFlores** [comment]
pues basado en el estándar y en las validaciones, si al parecer para exento no debe ir.
Lo que dicen las validaciones es que TotalImpuestosTrasladados va de la mano con importe, es decir si aparece uno va el otro.
Entonces, si para el caso de exento, no existe el importe de los impuestos, pues por correspondencia totalImpuestosTrasladados tampoco va.

en resumen, es correcto, no va para el caso de exento, así como no va el importe y la tasa.

**Comment by RigoFlores** [comment]
hay un caso, donde no lleva ningún impuesto... ni a nivel concepto, ni a nivel general...
eso es con el IVA trasladado con tasa N/A (eso fue solución ingeniosa de nuestra parte)... no será que aquí cae el caso que detectaste?
<img width="510" alt="sinIva" src="https://user-images.githubusercontent.com/2912775/155248921-6253c4d5-fa42-4323-9234-8d042a7b296c.PNG">

**Comment by jccastillo0007** [comment]
no, no esta relacionado con el impuesto N/A, este problema que te digo, es al momento de crear el xml, que esta relacionado con el schema, por eso creo que hay alguna validación por ahi que hace que no agregue el nodo impuestos.

Entonces, ya no hay nada que hacer aqui?

**Comment by RigoFlores** [comment]
si, corregirlo... jajaja

Pues está el caso abierto, que cuando todos los conceptos de la factura son iva exento, entonces pues no tiene que enviar el atributo ese TotalImpuestosTrasladados

**Comment by jccastillo0007** [comment]
pero dijiste que: 

Entonces, si para el caso de exento, no existe el importe de los impuestos, pues por correspondencia totalImpuestosTrasladados tampoco va.

pero el nodo de impuestos si debe ir... ok, ya entendí, no tengo ni idea de por donde buscar corregir este defecto

**Comment by RigoFlores** [comment]
Yo pensaría que así:
cuando dentro del nodo de impuestos, para la parte de traslados, no existe ningún nodo traslado que incluya importe, entonces pues no lleva ese atributo. 

El ejemplo claro es, para exento, ese nodo no lleva importe y no existe ningún nodo traslado que si lleve importe... tons en ese caso no lleva totalImpuestosTrasladados

cfdi:Impuestos 
      cfdi:Traslados
          **cfdi:Traslado Base="100.0" Impuesto="002" TipoFactor="Exento"/>** 
      cfdi:Traslados>
cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
Es que eso ya esta claro, y el código ya funciona asi, de hecho en el log se ve bien, pero al crear el XML deja fuera el nodo impuestos

**Comment by jccastillo0007** [comment]
chiaaa , me encontré con una validación, donde si los totales de impuestos están vacíos, entonces borraba el nodo impuestos... chiaaaa, si estaba de este lado... ya esta corregido.

Peeeero, esa validación viene desde la 3.3 , asi que no sé si hay otros escenarios raros donde vaya a romperse algo
