### ISSUE TITLE
ERP - CARTA PORTE - tipo de documento por omisión incorrecto.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#193]
no coloca por omisión, el traslado-cartaporte, como tipo de documento a elaborar.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
ESTOY VALIDANDO CARTA PORTE CON EL USUARIO XEXX010101000, y sigue igual, sin presentar este documento por omisión.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
NO, QUE NO.
SIGUE EL PROBLEMA. ES EL MISMO QUE CORREGISTE LA SEMANA PASADA EN PRO. QUE NO RECONOCE LOS PLUGUINES DE CARTA PORTE NI DATOS EXTRA.

**Comment by jccastillo0007** [comment]
fixed.
