### ISSUE TITLE
CFDI 4.0 + CCE - cuando la moneda del CFDI es MXN, marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1930]
Cuando la moneda del CFDI es MXN, el complemento se sigue reportando en USD.
Entonces, dentro del complemento el tipoCambioUSD se debe tomar del catálogo de monedas (hay un issue, para que se tome del servicio de banxico, pero por lo pronto se toma del catálogo).
Y los atributos ValorDolares y ValorUnitarioAduana, se debe hacer la conversión a USD, dependiendo del tipo de cambio.

Ahora mismo, si la moneda del CFDI es MXN, a nivel de complemento, reporta las cantidades iguales, es decir como si fueran MXN.

Ejemplo:

    <cfdi:Emisor Rfc="IVD920810GU2" Nombre="INNOVACION VALOR Y DESARROLLO" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="XEXX010101000" Nombre="OMEGA TOOL CORP" DomicilioFiscalReceptor="61957" ResidenciaFiscal="CAN" NumRegIdTrib="123456789" RegimenFiscalReceptor="616" UsoCFDI="S01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="01" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="producto de prueba 1" ValorUnitario="1000.0000" Importe="1000.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="1000.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="160.000000"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="160.00">
        <cfdi:Traslados>
            <cfdi:Traslado Base="1000.0" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="160.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
    <cfdi:Complemento>
        <cce11:ComercioExterior CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="DAP" Subdivision="0" TipoCambioUSD="1.0" TipoOperacion="2" TotalUSD="1000.00" Version="1.1">
            <cce11:Emisor>
                <cce11:Domicilio Calle="FRAY LUIS DE LEON 3051 CONDOMINIO" CodigoPostal="61957" Estado="MIC" Pais="MEX"/>
            </cce11:Emisor>
            <cce11:Receptor NumRegIdTrib="123456789">
                <cce11:Domicilio Calle="AV UNIVERSIDAD" CodigoPostal="A1B 2C3" Estado="AB" Pais="CAN"/>
            </cce11:Receptor>
            <cce11:Mercancias>
                <cce11:Mercancia CantidadAduana="1.0" FraccionArancelaria="6203429191" NoIdentificacion="01" UnidadAduana="06" ValorDolares="1000.00" ValorUnitarioAduana="1000.00"/>
            </cce11:Mercancias>
        </cce11:ComercioExterior>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by RigoFlores** [comment]
Entonces en el complemento, todo va en USD... si la moneda del CFDI, entonces se hace la conversión a USD.

**Comment by jccastillo0007** [comment]
done
