### ISSUE TITLE
CFDI 4.0 + Nómina - Agregar el campo para capturar el domicilio fiscal del empleado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1931]
Lo único que se ocupa es el código postal.
Entonces agregarlo. Ahorita lo que timbra tiene en hardcoud el CP.

**Comment by jccastillo0007** [comment]
oye, cuando das de alta un empleado, no hay campos para capturar su domicilio, pero al momento de facturar si se toma de un domicilio del empleado, y de hecho si existe el código postal... pero no sé o no recuerdo como se dan de alta?

**Comment by RigoFlores** [comment]
Pues estrictamente hablando, solo se dan de alta en la pantalla de nomina - recibo de nomina.
Ahí se requiere agregar un campo para capturar el CP del empleado, pero es todo.
Hasta donde entiendo, el CP que envía ahora, está en jarcoud. 
no lo está tomando de la BD, ya que en el catálogo de clientes, modifiqué el CP y no tomó ese cambio.

Así que lo que se requiere es agregar ese campo. Podría agregarse a la derecha de uno de estos campos.
La etiqueta sería "C.P. Empleado"

No. de días pagados
Régimen

**Comment by jccastillo0007** [comment]
No esta hardcoded , se toma de la base de datos, pero no sé como llego ahi,
ya que no hay donde capturarlo, acaso antes si teniamos datos para la
dirección y luego los quitamos ?
Saludos.
JC.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
yo creo que nómina ya está listo.
Claro faltará enviar al PDF la info, eso ya es oootra historia.
