### ISSUE TITLE
Documento de pago 2.0 - Cálculo de equivalenciaDR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1932]
La equivalenciaDR en el documento de pago, es diferente a 1, cuando la moneda del DR y del pago, son distintas.
Ejemplo:
Si la factura era de 688.5 USD, y la pagaron completa en MXN, por ejemplo 14,458.5 MXN

El cálculo actual de la equivalenciaDR = montoDR / importePagado = 688.5 / 14458.5 = 0.0476190476190476

Ahora al cálculo actual, hay que multiplicarlo * 1.000001 esto es:
equivalenciaDR = (montoDR / importePagado) * 1.000001= (688.5 / 14458.5) * 1.000001 = 0.0476195238095238

Realmente se trunca o redondea a 6 decimales, pero se hace necesario ese pequeño ajuste, para evitar muuuchos problemas, jeje. 
Es el tema de las conversiones.

**Comment by jccastillo0007** [comment]
ya se esta redondeando a 6 decimales, pero aún asi le agregué la multiplicación
