### ISSUE TITLE
Subir CFDI externos, no jala

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1933]
revisar en producción porqué no jala lo de subir cfdis externos.
principalmente para registrar pagos asociados a cfdis "foráneos"

**Comment by jccastillo0007** [comment]
Te refieres a registrar cfdi exsternos en ventas o compras ?

**Comment by RigoFlores** [comment]
solo existe en ventas.
Me refiero a ventas. Es para registrar facturas emitidas en otros sistemas.

**Comment by jccastillo0007** [comment]
también hay una opción en compras

**Comment by jccastillo0007** [comment]
cómo le haciamos para probar esta funcionalidad ? yo no tengo facturas timbradas por fuera y que si existan en el sat y tu?

**Comment by jccastillo0007** [comment]
listo... probé la funcionalidad con los cfdi de covemaq... solo no se están validando con el sat

**Comment by RigoFlores** [comment]
no tengo forma de probar, no te quedó alguno por ahí suelto?... jajaja
Y que versión fue, 3.3 o 4.0?

**Comment by RigoFlores** [comment]
tienes razón, en compras también existe la opción.
Lo puedes implementar ahí también.

Y no respondiste a la pregunta, si son de la 3.3. o 4.0?

**Comment by jccastillo0007** [comment]
soporta ambos, primero intenta 3.3 y luego 4.0, lo mismo voy hacer en la cancelación.

**Comment by RigoFlores** [comment]
yo lo probé en pro, que es donde puedo subir CFDI's externos a nosotros, y la TIA es el receptor...
Y ahí no jaló, si está en pro???

**Comment by jccastillo0007** [comment]
es que esta tratando de:

1. validar con FactureHoy
2. Aún debo modificar para que acepte 3.3 o 4.0, ahorita en compras soportaría solo 4.0, pero fallaría por el punto anterior

**Comment by jccastillo0007** [comment]
listo... ya subi el cambio para la opción de subir cfdi externos en compras... aunque no lo pude probar, pues no tengo facturas mias para subir en esa opción

**Comment by RigoFlores** [comment]
Validé en producción URL de la 4.0, menú de compras y al menos la versión 3.3 no lo está aceptando.

**Comment by jccastillo0007** [comment]
tienes XML con los que pueda probar? en producción

**Comment by RigoFlores** [comment]
[finkok.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8735246/finkok.xml.txt)
[facturehoy.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8735247/facturehoy.xml.txt)
[A118 Factura T pago 2.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8735248/A118.Factura.T.pago.2.xml.txt)


a ver si estos sirven...
