### ISSUE TITLE
Complemento de pago 2.0 - No está enviando en los totales, los impuestos trasladados (IVA)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1934]
aquí tienes el ejemplo para pru usuario IVD.
Es la factura 122 en USD, y el pago es por "14458.50" MXN.

Con eso lo reproduces.

[traslados.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8121886/traslados.xml.txt)

**Comment by jccastillo0007** [comment]
en mis pruebas, ya los envía , pero no cuadran

 <pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="14458.50" TotalRetencionesISR="157.50" TotalTrasladosBaseIVA16="264589.42" TotalTrasladosImpuestoIVA16="42334.31"/>
            <pago20:Pago FechaPago="2022-02-23T18:08:53" FormaDePagoP="03" MonedaP="MXN" Monto="14458.50" NumOperacion="1111" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="0.047620" Folio="122" IdDocumento="17F2E220-7199-52D0-990E-F44E08BD0447" ImpPagado="688.50" ImpSaldoAnt="688.50" ImpSaldoInsoluto="0.00" MonedaDR="USD" NumParcialidad="1" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:RetencionesDR>
                            <pago20:RetencionDR BaseDR="600.000000" ImporteDR="7.5" ImpuestoDR="001" TasaOCuotaDR="0.012500" TipoFactorDR="Tasa"/>
                        </pago20:RetencionesDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="600.000000" ImporteDR="96.0" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:RetencionesP>
                        <pago20:RetencionP ImporteP="157.496850" ImpuestoP="001"/>
                    </pago20:RetencionesP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="12599.748005" ImporteP="2015.959681" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>
        </pago20:Pagos>


003 : CRP20204 : El valor del campo TotalTrasladosBaseIVA16 no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos BaseP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y en TasaOCuotaP el valor 0.160000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.

**Comment by RigoFlores** [comment]
Esta sección de totales se reporta en MXN.
<pago20:Totales MontoTotalPagos="14458.50" TotalRetencionesISR="157.50" TotalTrasladosBaseIVA16="264589.42" TotalTrasladosImpuestoIVA16="42334.31"/>
Donde:

MontoTotalPagos = Monto * TipoCambioP = 14458.50  * 1 = 14458.50    (estamos OK)

TotalRetencionesISR = sumatoria de los distintos nodos de retenciones (  ImporteP* TipoCambioP )= 157.496850  (estamos OK)


TotalTrasladosBaseIVA16 = para cuando TasaOCuotaP="0.160000",  el cálculo es = ( BaseP*TipoCambioP) =  12599.748005 * 1 = 12599.748005  (redondedo)... aquí está el pedo. (no estamos OK) nosotros reportamos 
TotalTrasladosBaseIVA16="264589.42"

esto ya jalaba...

**Comment by jccastillo0007** [comment]
o que la fregada con esos calculos

**Comment by RigoFlores** [comment]
la neta, están super simples
abre el excel en una windows para que los veas

**Comment by jccastillo0007** [comment]
ya quedo... el pedo es que para calcular los impuestos a nivel cfdi, se debe contemplar la equivalencia... pero para los totales ya no... yo lo estaba duplicando

**Comment by RigoFlores** [comment]
Para los totales, los cálculos además de incluirse en el excel, los comenté aquí...
Ya le partimos la mami a las retenciones....

MontoTotalPagos = Monto * TipoCambioP = 14458.50 * 1 = 14458.50 (estamos OK)

TotalRetencionesISR = sumatoria de los distintos nodos de retenciones ( ImporteP* TipoCambioP )= 157.496850 (ahora ya le partimos su mami a este cálculo)

TotalTrasladosBaseIVA16 = para cuando TasaOCuotaP="0.160000", el cálculo es = ( BaseP*TipoCambioP)
al parecer ya quedó bien.

es importante que se haga el cálculo considerando el tipo de cambio, aunque el tipo de cambio sea 1. No consideres la moneda, considera el tipo de cambio, ya que eso en automático nos dará el resultado correcto para cualquier tipo de moneda.
Los totales se reportan en MXN, tons hay que calcularlos con el monto x tipo de cambio.

**Comment by jccastillo0007** [comment]
Este fue un error de dedo, ya quedo

**Comment by RigoFlores** [comment]
OK, ese factor de ajuste, jaló bien. Probaré mas escenarios, pero se ve bastante bien.
