### ISSUE TITLE
Complemento de pago 2.0 - para facturas con impuesto solo exento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1935]
Cuando se registra un pago a una factura o facturas, donde solamente se incluya impuesto trasladado con tipoFactor = Exento, 

No se deben registrar los campos TasaOCuotaDR ni ImporteDR   (a nivel documento relacionado)

No se deben registrar los campos TasaOCuotaP ni ImporteP  (a nivel pago)

ahora mismo si las envía y marca error...
Si el valor registrado en el campo TipoFactorDR es Exento no se deben registrar los campos TasaOCuotaDR ni ImporteDR.

**Comment by RigoFlores** [comment]
Así lo manda actualmente. Puedes probar con la factura 138 de pruebas.

        <pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="100.00" TotalTrasladosBaseIVA0="100.00" TotalTrasladosImpuestoIVA0="0.00"/>
            <pago20:Pago FechaPago="2022-02-24T11:37:26" FormaDePagoP="03" MonedaP="MXN" Monto="100.00" NumOperacion="fact138" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="138" IdDocumento="6546D20E-C9CB-55D3-A338-034F67ABAEC3" ImpPagado="100.00" ImpSaldoAnt="100.00" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="1" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="100.000000" ImporteDR="0.0" ImpuestoDR="002" TasaOCuotaDR="0.000000" TipoFactorDR="Exento"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="100.000000" ImporteP="0.000000" ImpuestoP="002" TasaOCuotaP="0.000000" TipoFactorP="Exento"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>
        </pago20:Pagos>

**Comment by jccastillo0007** [comment]
listo.

Nuevo error:

 CRP20208 : El valor del campo TotalTrasladosBaseIVA0 no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos BaseP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y en TasaOCuotaP el valor 0.000000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.


<pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="100.00" TotalTrasladosBaseIVA0="100.00" TotalTrasladosImpuestoIVA0="0.00"/>
            <pago20:Pago FechaPago="2022-02-24T17:38:58" FormaDePagoP="03" MonedaP="MXN" Monto="100.00" NumOperacion="1111" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="138" IdDocumento="6546D20E-C9CB-55D3-A338-034F67ABAEC3" ImpPagado="100.00" ImpSaldoAnt="100.00" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="1" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="100.000000" ImpuestoDR="002" TipoFactorDR="Exento"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="100.000000" ImpuestoP="002" TipoFactorP="Exento"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>
        </pago20:Pagos>

**Comment by RigoFlores** [comment]
si, ya vi donde está el otro pedo... chiaaaa...

es que hay distintos tipos de impuestos trasladados.
TotalTrasladosBaseIVA16   TotalTrasladosImpuestoIVA16
TotalTrasladosBaseIVA8   TotalTrasladosImpuestoIVA8
TotalTrasladosBaseIVA0   TotalTrasladosImpuestoIVA0

Pero el exento, tiene su propio atributo, que además NO LLEVA el totalTraslados, solo lleva:

TotalTrasladosBaseIVAExento, y en el se reporta la base de la suma de los impuestos cuyo tipoFactor = Exento.
Para este caso:

Incorrecto:
TotalTrasladosBaseIVA0="100.00" TotalTrasladosImpuestoIVA0="0.00"

Correcto:
TotalTrasladosBaseIVAExento="100.00"

**Comment by RigoFlores** [comment]
insisto, en el excel, hay comentarios donde se menciona todo esto
pero bueno, en cuanto a traslados de IVA, son todos los casos

no se reportan traslados de IEPS, checaré de ISR

**Comment by RigoFlores** [comment]
para las retenciones en los totales se pueden reportar, voy a generar las facturas para probar esos escenarios:
TotalRetencionesIVA
TotalRetencionesISR
TotalRetencionesIEPS

**Comment by jccastillo0007** [comment]
listo
