### ISSUE TITLE
Pagos parciales, reportar correctamente las bases e importes, en DR, Pago y Totales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1937]
Cuando una factura se paga por ejemplo al 50%, entonces debemos reportar que los impuestos se pagan igual a la mitad.
Si no lo hacemos así, entonces en el 2o pago se reportan los mismo impuestos pagados, duplicando el monto. Y ahí te cuento... jajaja.
La spec dice que se reportan sobre EL PAGO RECIBIDO. 
Aquí entra en juego ya, el % del pago.

Anexo un XML, con comentarios de cómo lo timbra hoy (reportando el total de la factura) y cómo debe reportarlo.

Si los cálculos se hicieron todos correctamente, solo se hace un pequeño ajuste a nivel de DR, ya que a nivel pago.
Pero depende de cómo se implementó.
[PAGO PARCIAL BASICO.xml.TXT](https://github.com/jccastillo0007/eFacturaT/files/8137738/PAGO.PARCIAL.BASICO.xml.TXT)

**Comment by RigoFlores** [comment]
Jajaja, aquí el pinche SAT no respinga si alguien dice que le pagaron mas impuestos de los que realmente aplican, que cabrón!!!
aqui no mandas sus pinches errores...permite pasar los errores...

**Comment by jccastillo0007** [comment]
pues hice ese peque;o ajuste a nivel de DR, y si jalo, y si timbro... algo debe estar mal chiaaa

**Comment by RigoFlores** [comment]
ya levanté otros issues.
