### ISSUE TITLE
Nuevas Variables para CFDI 4.0 (para jasper)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1938]
Estas nuevas variables, se tendrán que enviar en todo tipo de CFDI: I, E, N, T y P.

exportacion (se envía la clave y descripcion)
Para FacturaGlobal se deben enviar las 3 variables:
-periodicidad
-año
-mes
CP receptor (ya tenemos la variable, se llama cpReceptor; solo hay que reutilizarla)
regimenReceptor  (se envía la clave y descripción)
objetoImp  (se envía la clave y descripción)

Hoy tenemos estas variables a nivel general. Solo me aseguraré que si se esté enviando la info de la base.
	<field name="baseTrasladoIva1" class="java.lang.String"/>
	<field name="baseTrasladoIva2" class="java.lang.String"/>
	<field name="baseTrasladoIva3" class="java.lang.String"/>
	<field name="baseTrasladoIeps1" class="java.lang.String"/>
	<field name="baseTrasladoIeps2" class="java.lang.String"/>
	<field name="baseTrasladoIeps3" class="java.lang.String"/>

**Comment by jccastillo0007** [comment]
No entiendo a que te refieres, el xml ya esta bien formado y timbrado, porque dices que faltan?

**Comment by RigoFlores** [comment]
son para el PDF, para jasper.

**Comment by jccastillo0007** [comment]
Nuevas variables a nivel cfd

globalPeriodo
globalMes
globalAnio
regimenReceptor

Variable a nivel producto

objImp

**Comment by RigoFlores** [comment]
**_Está faltando la variable para exportacion._**

Por otro lado, al intentar validar las variables par global, marca el error:

El campo Rfc del nodo receptor debe contener valor "XAXX010101000" y el valor del campo Nombre del nodo Receptor debe contener el valor “PUBLICO EN GENERAL”.


Pero si se está enviando.

    <cfdi:Receptor Rfc="XAXX010101000" Nombre="PUBLICO EN GENERAL" DomicilioFiscalReceptor="61957" RegimenFiscalReceptor="616" UsoCFDI="S01"/>

Lo que noté que ya no se envía, es **_la información global precisamente, en el XML ya no aparece_**. Creo que ahí está el problema.

**Comment by jccastillo0007** [comment]
la variable de exportacion es exportacion, pero ahorita solo se manda la clave

**Comment by jccastillo0007** [comment]
Si esta mandando la info de factura global, claro, si es que capturas algo 

 <cfdi:InformacionGlobal Periodicidad="01" Meses="01" Año="2022"/>
    <cfdi:Emisor Rfc="IVD920810GU2" Nombre="INNOVACION VALOR Y DESARROLLO" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="XAXX010101000" Nombre="PUBLICO EN GENERAL" DomicilioFiscalReceptor="61957" RegimenFiscalReceptor="616" UsoCFDI="S01"/>


igual en el jasper:   

globalPeriodo=01 Diario,globalMes=01 Enero,globalAnio=2022,exportacion=01

**Comment by RigoFlores** [comment]
ya vi que si las mandó. SI dices que no hiciste nada, tenemos un issue que no puedo reproducir.
Lo que si noté es que si eliges cualquier cliente distinto a "PUBLICO EN GENERAL", elimina de pantalla las variables, pero si eliges ahí mismo PUBLICO EN GENERAL, ya no las muestra de regreso.
Es decir, una vez que desaparecen, ya no se les volverá a ver, a menos que te salgas y vuelvas a entrar.

Esas variables se deben **mostrar siempre que el receptor sea XAXX010101000 Y nombre PUBLICO EN GENERAL**.

**Comment by RigoFlores** [comment]
Ya se como reproducirlo.
Justo eligiendo otro rfc y luego regresando al XAXX.
Si timbras, marcará el error.
Entonces, si se hace necesario que cuando se elija el **RFC y Nombre** (validar ambos), aparezcan las opciones de captura para global.

Y si, ya está enviando exportación, pero falta la descripción.

**Comment by jccastillo0007** [comment]
hay que levantar un defecto , para el tema de factura global cuando cambian de rfc, chiaaa,
