### ISSUE TITLE
ERP - NOMINA EMPRESARIAL - SIMULADOR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#194]
GENERAR UN REPORTE, EN EL FORMATO DE FACTURA ESTANDAR, DONDE SE INCLUYA:
A) LISTADO DE EMPLEADOS HABILITADOS
B) LISTADO DE EMPLEADOS DESHABILITADOS
C) TOTAL PERCEPCIONES, TOTAL DEDUCCIONES (SIN CONSIDERAR ISR, ES DECIR EL DESCUENTO) Y EL ISR, POR CADA EMPLEADO HABILITADO
D) TOTAL DE LA NÓMINA.

**Comment by jccastillo0007** [comment]
Cual es el formato de factura estándar?

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
el reporte, solo incluirá a los empleados habilitados.
lo mandé por correo.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
los totales del reporte están incorrectamente calculados.

**Comment by RigoFlores** [comment]
no quitar el resumen que ya se mostraba:
No empleados habilitados
No empleados deshabilitados
Total a pagar.

**Comment by jccastillo0007** [comment]
Fixed.
