### ISSUE TITLE
Conector 4.0 - Factura Global, no está tomando el uso del CFDI del archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1940]
No sé porque no lo toma, para este archivo que anexo.

[2 productosyGlobal .txt](https://github.com/jccastillo0007/eFacturaT/files/8173048/2.productosyGlobal.txt)

**Comment by jccastillo0007** [comment]
Listo..

Con estos datos 
 <cfdi:Emisor Rfc="IVD920810GU2" Nombre="INNOVACION VALOR Y DESARROLLO SA" RegimenFiscal="626"/>
    <cfdi:Receptor Rfc="XAXX010101000" Nombre="PUBLICO EN GENERAL" DomicilioFiscalReceptor="76160" RegimenFiscalReceptor="616" UsoCFDI="S01"/>

Siempre recibo el error 

El campo Nombre del emisor, debe encontrarse en la lista de RFC inscritos no cancelados en el SAT.

Cual es el nombre correcto?

Lo relacionado con este defecto, ya esta arreglado
