### ISSUE TITLE
Conector 4.0 - implementar nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1941]
Los requisitos, son los mismos que en web:

1. Actualizar los URLS, esquemas, location etc...
2. Exportación - valor fijo 01
3. InformaciónGlobal - no debe existir
4. Régimen fiscal receptor - valor fijo "605"   
5. Incluir el domicilio fiscal del receptor
6. uso de CFDI - valor fijo "CN01"  
7. ObjetoImp - valor fijo "01" 
8. los atributos FechaPago, FechaInicialPago, FechaFinalPago y FechaInicioRelLaboral se homologa la forma de expresión del formato fecha, esto es: AAAA-MM-DD
9. Descuento e importes a 2 decimales

**Comment by RigoFlores** [comment]
[nomina12.txt](https://github.com/jccastillo0007/eFacturaT/files/8173519/nomina12.txt)

este es un archivo. El uso del CFDI, antes era otra clave en 3.3. 
Entonces no está enviando el correcto uso de CFDI. Pero bueno, revisa todo pls...

**Comment by jccastillo0007** [comment]
según mi prueba ya esta todo
