### ISSUE TITLE
Conector 4.0 - complemento de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1942]
Partiendo del mismo layout para versión 3.3, implementar el complemento de pago, con todo lo que se ha implementado en web

**Comment by RigoFlores** [comment]
Es decir, no cambiaría el layout del complemento.
Solo la parte del CFDI estándar que ya tenemos... por ejemplo para el régimen fiscal del receptor, el domicilio fiscal.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
espántame panteón... ora que subas la versión para probar...

**Comment by RigoFlores** [comment]
jajaja, no manches, no tiene todo lo nuevo... es el detalle de los impuestos, chiaaaaa
Fingiré que no le cambiaste el status al issue.
Aquí un archivo de prueba. Si lo procesó para 3.3, y ajusté el emisor para 4.0


[PagoEfectivoCompletoMXN_PUE.txt](https://github.com/jccastillo0007/eFacturaT/files/8189594/PagoEfectivoCompletoMXN_PUE.txt)

**Comment by jccastillo0007** [comment]
a cabrón cierto... chiaa es que es medio confuso, pero ahorita muevo lo de web a standalone

**Comment by jccastillo0007** [comment]
Puedes iniciar pruebas... yo no logre timbrar... pero el XML se ve bien.

**Comment by RigoFlores** [comment]
ya generó el XML, pero no genera el PDF.
ni con pagos ni con ningún tipo de CFDI de los que ya jalaban,

**Comment by RigoFlores** [comment]
[PagoCheque.txt](https://github.com/jccastillo0007/eFacturaT/files/8544207/PagoCheque.txt)
[SINRETENCION.txt](https://github.com/jccastillo0007/eFacturaT/files/8544208/SINRETENCION.txt)


El archivo sinretencion genera la factura.
una vez generada, ahora podrás generar el pago, cambiando el UUID de la factura en el archivo pagocheque. También será necesario cambiar el folio de la factura en este archivo.

**Comment by jccastillo0007** [comment]
ya tengo el fix de esto... ya esta el pdf de ambos, la factura y el pago
