### ISSUE TITLE
Conector 4.0 - no procesa el complemento de carta porte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1944]
Estoy intentando procesar este archivo..

[ccp_Ingreso 2.0.txt](https://github.com/jccastillo0007/eFacturaT/files/8188759/ccp_Ingreso.2.0.txt)

**Comment by jccastillo0007** [comment]
chiaaa, la llave que me pasaste , y que estas usando, no tiene configurado el plugin de carta porte, por eso no lo procesa

**Comment by RigoFlores** [comment]
después le agregué el plugin de carta porte, y de todos modos no lo generó

**Comment by jccastillo0007** [comment]
mándame la llave corregida, yo creo que es eso

**Comment by RigoFlores** [comment]
[facturaT_IVD920810GU2.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/8190973/facturaT_IVD920810GU2.cfdi.txt)

**Comment by RigoFlores** [comment]
pues ya probé con esa llave y no jaló

**Comment by jccastillo0007** [comment]
listo... no sé porque o si asi se pidió originalmente.... pero CCP estaba habilitado solo para multi rfc, no para single rfc

**Comment by RigoFlores** [comment]
y quedó para ambos?
