### ISSUE TITLE
Conector CFDI4.0 - definir el nombre de las plantillas por omisión y enviar las variables correspondientes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1945]
Ahora mismo, tienen por ejemplo cfdi_base33.jrxml.
Hay que cambiarlas a:

cfdi_base40.jrxml  
cfdi_nomina40.jrxml  
cfdi_AcuseCancelacion22.jrxml
complementocartaporte20.jrxml
cfdi_pago40.jxml

Adicionalmente, hay que enviar ya, las nuevas variables que se están enviando en web.

**Comment by jccastillo0007** [comment]
cuales son las nuevas variables ? tienes una lista de cada template ?

**Comment by RigoFlores** [comment]
para CFDI, nómina, CCP:

	<field name="globalPeriodo" class="java.lang.String"/>
	<field name="globalMes" class="java.lang.String"/>
	<field name="globalAnio" class="java.lang.String"/>
	<field name="regimenReceptor" class="java.lang.String"/>
	<field name="exportacion" class="java.lang.String"/>

Acuse de Cancelación:

	<field name="motivo" class="java.lang.String"/>
	<field name="cfdiRelated" class="java.lang.String"/>

Falta definir las variables para el complemento de pago.

**Comment by jccastillo0007** [comment]
listo... 

también cambio el template de cfdi_notacredito40.jrxml

**Comment by jccastillo0007** [comment]
Aún no tenemos cancelación en standalone, pero ya agregué las variables jojojo
