### ISSUE TITLE
Pago 2.0 - en pago parcial, manejar hasta 6 decimales en importes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1946]
En particular lo vi, en importeDR, que le puso pinche mil decimales.

Anexo la evidencia.

Esto causó el error de XML, mal formado.
Factura 115. Primer pago parcial que intentaba registrar, 106.00
[decimalesImporteDR.txt](https://github.com/jccastillo0007/eFacturaT/files/8208936/decimalesImporteDR.txt)

**Comment by jccastillo0007** [comment]
Pero esto aplicaria para todos los pagos, no solo para parciales

**Comment by RigoFlores** [comment]
ninguna importe en el mundo de cfdis, se permite con mas de 6 decimales.
Así que en principio no debe marcar error, salvo que existan casos especiales.

Pero para este parámetro, seguro no.

**Comment by jccastillo0007** [comment]
done
