### ISSUE TITLE
Pagos 2.0, no reporta correctamente los datos en el 3er pago parcial

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1947]
No estoy seguro cómo lo hace, pero aquí está la evidencia:
Factura 115
pago 1: 58   (todo OK)
pago 2: 29   (todo OK)
pago 3: 29   (aquí la base y los impuestos ya los reportó chueco). La base no es 100, ni el impuesto 16.

Anexo la evidencia de los XML, y también la sección de XML donde aparece el error...

[3erpagoparcialMal.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/8209215/3erpagoparcialMal.zip.txt)

            <pago20:Totales MontoTotalPagos="29.00" TotalTrasladosBaseIVA16="100.00" TotalTrasladosImpuestoIVA16="16.00"/>
            <pago20:Pago FechaPago="2022-03-08T12:22:19" FormaDePagoP="03" MonedaP="MXN" Monto="29.00" NumOperacion="fact115-3" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="115" IdDocumento="BDF49971-7589-5805-99BE-8D85A2B52627" ImpPagado="29.00" ImpSaldoAnt="29.00" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="3" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="100.000000" ImporteDR="16.0" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="100.000000" ImporteP="16.000000" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>

**Comment by jccastillo0007** [comment]
hmmm aqui como funcionaría tu excel chacarron... el tema es..

Primer pago de 58, sobre el total de 116, el porcentaje pagado es de 50%
Segundo pago de 29, sobre el restante 58, el porcentaje pagado es de 50%
Tercer pago de 29,  sobre el restante de 29, el porcentaje pagado es el 100% (del restante), tons por eso reporta asi la base y el importe de los impuestos...

ahi como que procede ?

**Comment by RigoFlores** [comment]
Un pago parcial, es una proporción DEL TOTAL.
Por ejemplo, pagan 29 pesos, del total 116, la proporción es 29 / 116 = 25%.
Entonces la base es 25% (la proporción calculada) del total de la base en la factura, en este caso, serían 25.
El impuesto, pues igualmente el 25% de 16, es decir 4.

Que el saldo insoluto sea 0, no quiere decir en todo caso que el importe pagado fue del 100%. 
Y menos en pagos parciales, ya que en este caso, indica que ya se liquidó la factura completamente, pero no que se hizo uno solo pago por el total.

**Comment by jccastillo0007** [comment]
Entonces, bajo ese entendido, la segunda factura realizada por 29 pesos, tampoco estaba bien

**Comment by RigoFlores** [comment]
si está bien, checa los XML

**Comment by jccastillo0007** [comment]
no, porque la baseP del segundo pago no debe ser 50, ya que  el pago fue de 29 que es el 50% de 58, pero es el 25% de 116, y no es proprocional contra los 100 que es la base original... 

tus reglas o deducciones ya no están aplicando a estos escenarios

**Comment by RigoFlores** [comment]
cierto, lo acabo de revisar... el 2o pago, es incorrecto
me confundo con tantas pruebas

**Comment by RigoFlores** [comment]
las reglas están bien... lo que indiqué arriba, lo repito aquí...

Un pago parcial, es una proporción DEL TOTAL.
Por ejemplo, pagan 29 pesos, del total 116, la proporción es 29 / 116 = 25%.
Entonces la base es 25% (la proporción calculada) del total de la base en la factura, en este caso, serían 25.
El impuesto, pues igualmente el 25% de 16, es decir 4.

Que el saldo insoluto sea 0, no quiere decir en todo caso que el importe pagado fue del 100%.
Y menos en pagos parciales, ya que en este caso, indica que ya se liquidó la factura completamente, pero no que se hizo uno solo pago por el total.

**Comment by RigoFlores** [comment]
El problema sigue siendo que no quieres revisar el excel. Con que le demos una hora ahí está todo.

Primero se debe calcular el % pagado.
En una factura de 116, la base son 100 y el importe del impuesto son 16.  (es decir, 100 + IVA)
Si a esa factura de 116, te dicen que el pago fue de 29, entonces el % pagado sobre el toral de la factura es 25%. Así sea el pago 1, 2 o el que sea.

Para el documento de pago.
La baseDR, es el 25% de la base del XML. En este ejemplo 25
El importeDR es el 25% del impuesto correspondiente en el XML. En este ejemplo 4.

Y a partir de esos datos a nivel DR, se calculan a nivel pago.
Si todo es en MXN, y es una sola factura. Entonces la info a nivel pago y a nivel general es la misma.

**Comment by jccastillo0007** [comment]
listo, ya quedo este escenario

**Comment by RigoFlores** [comment]
Esssooooo tilín...!!!
Ahora si quedó shido...

Tssss, ahora viene la prueba con mas de 1 factura, pagos parciales...
