### ISSUE TITLE
Pagos 2.0 -  Parcial en MXN de factura original en USD, no reporta bien la baseP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1948]
La factura 121. Total 116 USD.
El pago parcial fue de 1218.00 MX, correspondiente a 50 USD.
No calculó bien la equivalenciaDR, ya que debe ser 50/1218.

Y no se si por esa razón también, el nodo de impuestosP, está chueco.
En el excel original, que me costó un huevo hacerlo, vienen todos estos cálculos, pero no lo quieres revisar.

Anexo evidencia.

[pagoParcialUSD.txt](https://github.com/jccastillo0007/eFacturaT/files/8209285/pagoParcialUSD.txt)

**Comment by jccastillo0007** [comment]
Listo, ya están bien los calculos, pero una vez mas tenemos problemas de redondeo..

<pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="1218.00" TotalTrasladosBaseIVA16="1050.00" TotalTrasladosImpuestoIVA16="168.00"/>
            <pago20:Pago FechaPago="2022-03-08T21:45:51" FormaDePagoP="03" MonedaP="MXN" Monto="1218.00" NumOperacion="2222" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="0.041051" Folio="121" IdDocumento="46B28423-6625-597B-A063-5CA8D900D4E5" ImpPagado="50.00" ImpSaldoAnt="116.00" ImpSaldoInsoluto="66.00" MonedaDR="USD" NumParcialidad="1" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="43.103448" ImporteDR="6.896552" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="1049.997490" ImporteP="167.999604" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>
        </pago20:Pagos>


CRP20268 : El campo BaseP que corresponde a Traslado, no es igual a la suma de los importes de las bases registrados en los documentos relacionados donde el impuesto del documento relacionado sea igual al campo ImpuestoP de este elemento y la TasaOCuotaDR del documento relacionado sea igual al campo TasaOCuotaP de este elemento.

**Comment by RigoFlores** [comment]
Pues fíjate que ahí creo que estamos mal nosotros.
La baseP debe calcularse así (para el mismo impuesto trasladado-tasa; por ejemplo IVA del 16%):  
sumatoria( baseDR  / equivalenciaDR )= 43.103448 / 0.041051 = 1049.997515

lo cual es distinto a lo reportado ( 1049.997490 ), por ello marca el error.
Aquí dejo el archivo con las observaciones:
[baseP_incorrecto.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8218449/baseP_incorrecto.xml.txt)

**Comment by jccastillo0007** [comment]
listo, ya esta este escenario.

Según yo los cálculos ya están como en el excel... solo que había problemas de redondeo..

**Comment by RigoFlores** [comment]
ya jala, solo los cálculos que manda al xml no coinciden con el excel del todo todo... seguirá en observación
