### ISSUE TITLE
cancelacion de otros PACS no funciona

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1949]
Ya tengo el escenario en pro de intentar cancelar una factura de otro PAC.
RFC: MERA9605213W1
Factura: A-4190
Motivo: 02

Marca error, algo así como que no encuentra la factura. Pero el portal del sat si la tiene. Anexo evidencias.

<img width="666" alt="cancelable" src="https://user-images.githubusercontent.com/2912775/157332741-fdba7ae0-3014-492a-9f29-55b4e647f22a.PNG">

[error de cancelacion.txt](https://github.com/jccastillo0007/eFacturaT/files/8209908/error.de.cancelacion.txt)

**Comment by jccastillo0007** [comment]
y no va a funcionar hasta que se libere la version 4.0, ve el ticket 1913

**Comment by RigoFlores** [comment]
no maaaa... pues hay que apurarnos con lo que falta.

**Comment by RigoFlores** [comment]
pues no, no funciona de todos modos...

**Comment by RigoFlores** [comment]
te mandé un correo de facture hoy, que en su momento nos respondió.
Ahí viene la liga de cancelación para otros pacs

**Comment by RigoFlores** [comment]
Para cancelación de otros PAC's tenemos 2 escenarios:

CFDI 3.3
CFDI 4.0

**Comment by jccastillo0007** [comment]
Recuarda que cancelacion 3.3 , se queda en la versión de efacturat 3.3

**Comment by jccastillo0007** [comment]
La factura que pusiste hasta arriba es 3.3, necesito una factura 4.0

Igual y cuando ya liberemos todos los pendientes de la 4.0, veo como hacerle para poder cancelar 3.3 desde la 4.0

**Comment by RigoFlores** [comment]
OK, la cancelación con otros PAC's, ya sea 3.3 o 4.0 no jala...

**Comment by jccastillo0007** [comment]
Buenas noticas.

La factura de arriba:
RFC: MERA9605213W1
Factura: A-4190

Ya se cancelo satisfactoriamente, es una factura 3.3.

La otra buena noticia, es que ya funciona cancelación otro pac de 3.3

La mala noticia, es que el template del acuse de cancelación, no salio bien... al jasper se mandan los datos del archivo anexo, pero el acuse no muestra todo el sello de cancelación.

**Comment by jccastillo0007** [comment]
[jasper acuse de cancelacion.txt](https://github.com/jccastillo0007/eFacturaT/files/8645299/jasper.acuse.de.cancelacion.txt)

**Comment by RigoFlores** [comment]
Está faltando la cancelación de otros pacs, con la v4.0

**Comment by RigoFlores** [comment]
para cerrar el tema de cancelación en web, falta este punto de otros pacs en 4.0
y luego llevarlo a escritorio...

faltan un buen de temas..
