### ISSUE TITLE
ERP-CARTA PORTE- NO PERMITE LA CAPTURA DE DATOS EXTRA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#195]
EN TEORÍA SI TIENE LOS DATOS EXTRA, PERO NO PERMITE CAPTURARLOS.
USUARIO/PWD = XEXX010101000

**Comment by jccastillo0007** [comment]
????

**Comment by RigoFlores** [comment]
como te platiqué ayer, según yo configuré el usuario XEXX010101000, con un perfil de carta porte, de hecho consultando en la BD del ERP, me arroja el siguiente resultado:
mysql>      Select \* from ClientPlugins where owner = 'XEXX010101000';
+----+------------------------------------------------+---------------+
| id | features                                       | owner         |
+----+------------------------------------------------+---------------+
|  2 | ["EXTRA_DATA_IN_CFD","CARTA_PORTE","ADDENDAS"] | XEXX010101000 |
+----+------------------------------------------------+---------------+
1 row in set (0.00 sec)

es decir, por BD tiene los pluguines, según yo. 
Pero ya en pantalla, no permite capturar los datos extra.

**Comment by RigoFlores** [comment]
de hecho en la pantalla inicial, únicamente marca adendas como pluguin habilitado
el tema supongo que es de configuración pero ya no entendí ni madre.
