### ISSUE TITLE
Conector CFDI 4.0 - CCP marca error con la plantilla por omisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1950]
Si la busca, si la jala.
Ya puse las plantillas que tenemos en pru, pero el mensaje de error es muy similar a lo que teníamos en su momento:

2022-03-08 17:24:20,195 ERROR [pool-2-thread-1] (JasperCreatorImpl.java:176) - net.sf.jasperreports.engine.JRException: Error retrieving field value from bean
 : ubicaciones
net.sf.jasperreports.engine.JRException: Error retrieving field value from bean : ubicaciones

**Comment by jccastillo0007** [comment]
y las nuevas plantillas apa ?

**Comment by jccastillo0007** [comment]
solo bajo lo de pru y le cambio el nombre cierto

**Comment by RigoFlores** [comment]
si, del servidor... de ahí la tomas

**Comment by RigoFlores** [comment]
ya bajé la plantilla del server de pruebas, y sigue marcando el mismo error. Si timbra, pero no genera el PDF.

Ahora, otra cosa que identifiqué es... después que marca error cuando timbra un carta porte, ya no puede timbrar una factura o nota de crédito. Como que se queda con algo en memoria, y cada archivo que intenta procesar, lo "ve" como carta porte.

Aquí están los archivos con los que probé. Si intentas timbrar ccp, después del error... ya no podrá timbrar factura o nota de crédito..

[notaCredito.txt](https://github.com/jccastillo0007/eFacturaT/files/8236268/notaCredito.txt)
[CartaPorte_Ingreso 2.0.txt](https://github.com/jccastillo0007/eFacturaT/files/8236269/CartaPorte_Ingreso.2.0.txt)
[cfdi40.txt](https://github.com/jccastillo0007/eFacturaT/files/8236270/cfdi40.txt)

**Comment by jccastillo0007** [comment]
fixed, no ma... no habia hecho nada de esos cambios
