### ISSUE TITLE
Conector CFDI 4.0 - la llave con el plugin de carta porte, marca errror al procesar una nota de crédito

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1951]
Utilizando la llave que tiene pinche mil plugines, cuando le pongo que procese una nota de crédito, marca error.

2022-03-08 17:26:57,302  INFO [pool-2-thread-1] (CFDiWSClient.java:77) - FacturaTi ack : com.facturati.ws.binding.jaxb.Ack@1c2eaa4[code=003,description=738 :
Errores con schemaLocations, namespaces y prefijos]

Anexo la llave y el archivo de texto.

[facturaT_IVD920810GU2.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/8210391/facturaT_IVD920810GU2.cfdi.txt)
[notaCredito.txt](https://github.com/jccastillo0007/eFacturaT/files/8210393/notaCredito.txt)

**Comment by jccastillo0007** [comment]
acabo de timbrar el txt que enviaste y con la llave, chiaaa


<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:leyendasFisc="http://www.sat.gob.mx/leyendasFiscales" Version="4.0" Folio="19" Fecha="2022-03-09T19:21:04" Sello="HijLh7brfZywVKwthEL0wMzR3pt0vq6pvH2JT9ulDIOOfbBKGtoSVe9cVuByYFdZ7R8iAHuFnYnMfRIccXn3oDtJTiqykYeJnDEamRt7i0ediZPsFU4BVz1ZZKOm3K7fyNv+2Pz/PITVPvHI2Dg6AHnCeRK5ai4LvHbjNl50Wkc24NebW5xdq1UJh4XfzlJlXzfn2wOZsBmMvticOSO3Di3GZqnI780tacuj9oKfpl4esPu0kHG98EPCS5Bd4M4xCUflBWKZF+ehkf5I9H1S89S7GNJLry8BkUNf+hkgzr/LzGkskF7kC8bU0ZErrI4Vf1932sdiyzD8Ta8rgH0THw==" FormaPago="99" NoCertificado="30001000000400002438" Certificado="MIIF0jCCA7qgAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDI0MzgwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNjE3MjAwNDEyWhcNMjMwNjE3MjAwNDEyWjCB+TEpMCcGA1UEAxMgSU5OT1ZBQ0lPTiBWQUxPUiBZIERFU0FSUk9MTE8gU0ExKTAnBgNVBCkTIElOTk9WQUNJT04gVkFMT1IgWSBERVNBUlJPTExPIFNBMSkwJwYDVQQKEyBJTk5PVkFDSU9OIFZBTE9SIFkgREVTQVJST0xMTyBTQTElMCMGA1UELRMcSVZEOTIwODEwR1UyIC8gS0FITzY0MTEwMUIzOTEeMBwGA1UEBRMVIC8gS0FITzY0MTEwMUhOVExLUzA2MS8wLQYDVQQLFCZJTk5PVkFDSdNOIFZBTE9SIFkgREVTQVJST0xMTyBTQSBERSBDVjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIKn3U4zMIEGfAICsDCSD4EQwQbabWJOdQpXdnAeCqwIH/vAbnv4t7Rc1NFMJg2OeCK5L6g+Pj/DlWftOeqRo8KIzW04xtq6rWSxXXuhGDm9hdRF15JEoxJnpDmkqKLEpbLJqZ4mOdKOHdmEdQ4O3dd0njeNGdjhU5+Vl4J9rHVjA4BoJpsP75BQeIwDdFIVxcb60sKna0mG58lMq5tNK6CtozeyrC94IED9GARG0gKuXlswTrWrI1N3/VOI7jjZY6YeIeO5jcbXrCiqGxGduJrGHqyrxGPTIXlZ7iW8zMT1G8QRF5rWutg4+MysIsjrcFrexbP5TMaRBYyASeBd94kCAwEAAaMdMBswDAYDVR0TAQH/BAIwADALBgNVHQ8EBAMCBsAwDQYJKoZIhvcNAQELBQADggIBAJVqgdQ+NOSIBKbWBBSARmX5C0wiq0BfRz4Ub7dVGguHoPAB4dJAtL540b3Klid90EwtNSCCFSc9OPQ0mWVRkCz0OtceLKAXzKqzVOcXrxmydlbT0brNBkULDV54Gdup1B42mmCh0hoRaNvr0QkJnKEMTmHt3m47xnV9XfOeUcSDciCTMV4wRns3JdCr7g0PMyWpV5yRLJNr8w9YCm6YesSqCJLZIvWbFGRuDhHfgsyImtMuTNbclbI7XFue2B4awi3a9H8yfgf33bGgeLhVCAbILd63LQv67zGdt3H8s2Xe4umQmh+9gyJG4fmbZmUd3wFl/fY9kmdTxZfufqPbdyV/G7g0Hq3mmzS1TuRG2Hj+y4lVzLOV6RXJjIQ+Qp+5ePKl4d/oeAIsTzmWsZc0c+yJ1MMbCn6CHTlNvdwROOhpanNjEHJ2kLwh5nhoVSRbRF/owuBreO5FbJKZE+L+8mzYEIhKUiD03WW03BOPCCQFFvBFC0AoN7wS0zFm1g2gNV95pgZwp1LsqlwBSAVF9SS/MKiE7Mv0UryWEBYllo66XY8VMFzZYAjSuEudoK3xSsCdjaA/Wjx85/3RCEV3J7LO5m6mwYgrQIaTwuYWuCTUE8XKxj7cjNo1UF6LbL77nzbYmS3sUXE4Jly8xxOYsyDX8B+8TNW++g1mB3bt+OHv" CondicionesDePago="60 DIAS FECHA FACTURA" SubTotal="1000.00" Moneda="MXN" TipoCambio="1" Total="1040.83" TipoDeComprobante="E" Exportacion="01" MetodoPago="PPD" LugarExpedicion="76160" xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd http://www.sat.gob.mx/leyendasFiscales http://www.sat.gob.mx/sitio_internet/cfd/leyendasFiscales/leyendasFisc.xsd">
    <cfdi:InformacionGlobal Periodicidad="04" Meses="02" Año="2022"/>
    <cfdi:Emisor Rfc="IVD920810GU2" Nombre="INNOVACION VALOR Y DESARROLLO" RegimenFiscal="626"/>
    <cfdi:Receptor Rfc="MASO451221PM4" Nombre="MARIA OLIVIA MARTINEZ SAGAZ" DomicilioFiscalReceptor="80290" RegimenFiscalReceptor="626" UsoCFDI="G03"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="78101800" NoIdentificacion="ART-001" Cantidad="1.00" ClaveUnidad="E48" Unidad="SERVICIO" Descripcion="FLETE PRUEBA REGIMEN SIMPLIFICADO" ValorUnitario="1000.000000" Importe="1000.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="1000.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="160.000000"/>
                </cfdi:Traslados>
                <cfdi:Retenciones>
                    <cfdi:Retencion Base="1000.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.106670" Importe="106.670000"/>
                    <cfdi:Retencion Base="1000.000000" Impuesto="001" TipoFactor="Tasa" TasaOCuota="0.012500" Importe="12.500000"/>
                </cfdi:Retenciones>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosRetenidos="119.17" TotalImpuestosTrasladados="160.00">
        <cfdi:Retenciones>
            <cfdi:Retencion Impuesto="002" Importe="106.67"/>
            <cfdi:Retencion Impuesto="001" Importe="12.50"/>
        </cfdi:Retenciones>
        <cfdi:Traslados>
            <cfdi:Traslado Base="1000.0" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="160.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
    <cfdi:Complemento>
        <leyendasFisc:LeyendasFiscales version="1.0">
            <leyendasFisc:Leyenda textoLeyenda="Impuesto retenido de conformidad con la ley del impuesto al valor agregado"/>
        </leyendasFisc:LeyendasFiscales>
        <tfd:TimbreFiscalDigital xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" FechaTimbrado="2022-03-09T19:21:13" NoCertificadoSAT="30001000000400002495" RfcProvCertif="CVD110412TF6" SelloCFD="HijLh7brfZywVKwthEL0wMzR3pt0vq6pvH2JT9ulDIOOfbBKGtoSVe9cVuByYFdZ7R8iAHuFnYnMfRIccXn3oDtJTiqykYeJnDEamRt7i0ediZPsFU4BVz1ZZKOm3K7fyNv+2Pz/PITVPvHI2Dg6AHnCeRK5ai4LvHbjNl50Wkc24NebW5xdq1UJh4XfzlJlXzfn2wOZsBmMvticOSO3Di3GZqnI780tacuj9oKfpl4esPu0kHG98EPCS5Bd4M4xCUflBWKZF+ehkf5I9H1S89S7GNJLry8BkUNf+hkgzr/LzGkskF7kC8bU0ZErrI4Vf1932sdiyzD8Ta8rgH0THw==" SelloSAT="jwYcQn+kJsv2qdr0b+ci9tE7LspdlYNnBD0UK6ftymQDfyOqi3vYE69Gd/8cT0Gnh+EYuV2y7Tiv3aK3wdvIRDxmrt17SaHYes6gUvgHzigluVdRY2OS2Dtq7dh4SPHCgUgDtcImx94IPI8DAaxKXtI+6LIUx7Nlvg3vE3x5rg8KpH3pBom0Tdb7KpcnUSdgjybMiNtwWLTaEc3Nj4bHwg9qdDflQEs5RdvnSvF8V4uwNJoH2spsIlWNKLPZUWpZdQpbm9Q+FNHk5fsluM/ZKWjZife7LAR+JUOEYtB2aSFzyM0ElCoFBLowHz7urRjhK9rBjeoHOqTS3OvVw8SanA==" UUID="D9265406-0B77-593F-8FDE-CB8FEA5B1180" Version="1.1" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigitalv11.xsd"/>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by RigoFlores** [comment]
si, seguro me hice pelotas... ya vi que jala la versión que yo tengo
