### ISSUE TITLE
Pago 2.0 - no reporta correctamente los totales, cuando existe traslado IVA 16 junto con IVA exento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1952]
Se pagan 2 documentos, uno incluye IVA 16 y el otro IVA exento.
factura 138 iva exento, total = $100.
factura 145, iva 16%, total= $116
Pago = $226.

En los totales reporta como si fuera IVA tasa 0 (base e importe), en lugar de solo reportar los totales de base exenta.
A nivel de pago, también incluye 2 atributos que no aplican para exento.

Aquí el como es correcto e incorrecto...

[PAGO IVA 16yEXENTO.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8219194/PAGO.IVA.16yEXENTO.xml.txt)

**Comment by jccastillo0007** [comment]
fixed
