### ISSUE TITLE
Pago parcial de 2 facturas USD realizado en MXN no calcula correctamente...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1953]
Realicé pruebas de pagos parciales con mas de 1 factura en MXN y jaló bien.

Ahora realicé prueba de pago parcial de mas de 1 factura en USD, realizando el pago en MXN.

Marcó error:
La suma de los valores registrados en el campo ImpPagado de los apartados DoctoRelacionado no es menor o igual que el valor del campo Monto.

En el XML que estoy anexando, te voy marcando lo incorrecto y correcto, pero ahora numerado para que puedas ver cómo va el flujo de los cálculos. Inicia del (1) al (5) 
Todo inicia con el cálculo de la equivalenciaDR. Esta es una sola, es la misma, para todas las facturas involucradas. Ya que el monto pagado en MXN, y la suma en USD de lo indicado como pagado, pues de ahí se calcula la equivalencia.
Y de ahí sigue para todo lo demás.

[pagoParcialMXN 2 factUSD.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8228415/pagoParcialMXN.2.factUSD.xml.txt)

**Comment by jccastillo0007** [comment]
fixed, aunque tus calculos chacarrones de la equivalencia, estaban mal. ya se timbro este escenario

**Comment by RigoFlores** [comment]
si, el cálculo que hoy hice, tiene una variación de 50 centavos en el monto, por ello da ligeramente distinto.
Ahora marca error de timbrado con el PAC, pero esperaré... creo que eso es de finkok
