### ISSUE TITLE
Pago 2.0 - no está diferenciando correctamente entre IVA tasa 0 y el IVA exento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1954]
En el nodo de ImpuestoP, donde se resumen los impuestos trasladados y retenidos.

Cuando se trata de IVA, exento... así se reporta:
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="900.000000" ImpuestoP="002" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>

Cuando se trata de IVA, tasa 0... así se reporta:
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="900.000000" ImporteP="0.0" ImpuestoP="002" TipoFactorP="Tasa" TasaOCuotaP="0.0"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>

Ahorita hice una prueba con tasa 0, y lo reporta como si fuera exento, y marca error.
es un escenario super básico.

Pago de 900 USD a las factura 147 y 148. Esto es el total de ambas. Ambas facturas tienen tasa 0 del IVA.

**Comment by jccastillo0007** [comment]
listo
