### ISSUE TITLE
Pagos 2.0  con Iva Exento e Iva tasa 0, lo procesa todo como tasa 0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1956]
El pago de $200.00 se realiza a 2 facturas :
factura 127: 100.00 tasa IVA 0
factura 127: 100.00 tasa IVA Exento

Entonces debe reportar por separado los distintos tipos de tasa, pero los está reportando como si ambos fueran tasa 0.
Aquí lo correcto e incorrecto del caso.

[extento y tasa0.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8248261/extento.y.tasa0.xml.txt)

**Comment by jccastillo0007** [comment]
chiaaa, peque;o detalle
