### ISSUE TITLE
Pagos 2.0 - Incluir el factor de ajuste en el cálculo de la equivalenciaDR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1957]
EquivalenciaDR, aplica solo cuando se paga con moneda distinta a la moneda del DR.

Su cálculo es: (sumatoria ImportesPagados a nivel DR ) / monto.
A este cálculo, hay que aplicarle (multiplicar) un factor de ajuste, que ya lo pedí anteriormente pero no lo está incluyendo, entonces marca error.
ese factor es 1.000002.

Con ello, se eliminarán muchos errores bajo este escenario.

**Comment by jccastillo0007** [comment]
done
