### ISSUE TITLE
Pagos 2.0 - cálculo de BaseP, ImporteP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1958]
tanto la baseP como ImporteP, son parámetros (es correcto llamarles así?), que se calculan.
Su cálculo es muy simple.
Son las sumatorias de las Bases e Importes de los DR, que correspondan a la misma tasa, impuesto, etc.

Cuando todo es con la misma moneda, no hay cálculos que hacer. O lo que es lo mismo, equivalenciaDR = 1.

Cuando la moneda del DR es distinta a la moneda de pago, entonces la BaseP = Sumatoria de BasesDR / equivalenciaDR.
Lo mismo para ImporteP= Sumatoria de los importes de impuestos a nivel DR / equivalenciaDR

Hoy en día no se que haga, pero una factura original en USD, fact 121, 116 USD la pagué con 105 Euros.. y se hizo pelotas.
No será un escenario común, pero si lo he visto con los españoles. 
Los cálculos son los mismos siempre. Sumatorias (base o impuestos) / equivalenciaDR

Si la equivalenciaDR = 1, por ser la misma moneda, pues se puede hacer el mismo cálculo. Será transparente.

**Comment by jccastillo0007** [comment]
si esta bien llamarlos asi, ya estoy familiarizado...

No ma USD vs Euros?

**Comment by jccastillo0007** [comment]
pasame el xml de cómo debe quedar, 

Pregunta: es normal que el pago en Euros, es decir, los 108 euros, los reporta a nivel header en pesos ?

**Comment by RigoFlores** [comment]
No solo es normal, es un requisito del SAT.
Header en MXN (es el resumen total, le interesa en MXN).
A nivel Pago (en moneda del pago)
A nivel DR (en la moneda original del CFDI pagad).



Chiaaaaaaa

**Comment by RigoFlores** [comment]
[usd-eur-mxn.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8249875/usd-eur-mxn.xml.txt)


así debe quedar...

**Comment by jccastillo0007** [comment]
Ya está corregido el problema que originó este issue, sin embargo, esta tratando de validar el tipo de cambio, el cual no lo pelamos en ninguna operación, dado que nos manejamos con la equivalencia.. y marca el siguiente error

El valor del campo TotalTrasladosBaseIVA16 no es igual al redondeo de la suma del resultado de multiplicar cada uno de los importes de los atributos BaseP de los impuestos trasladados registrados en el elemento TrasladoP donde los atributos contengan en ImpuestoP el valor IVA, en TipoFactorP el valor Tasa y en TasaOCuotaP el valor 0.160000, por el valor registrado en el atributo TipoCambioP de cada nodo Pago.

**Comment by jccastillo0007** [comment]
que dice el excel del tipo de cambio ?

**Comment by RigoFlores** [comment]
pues ya se ha comentado. A nivel te totales, se toma el monto pagado y se multiplica por el tipo de cambio. Cuando es MXN, pues es igual, es el mismo monto, ya que se multiplica por 1.

Cuando la moneda de pago, no es MXN, entonces pues igual se toma el monto (que es a nivel de pago) y se multiplica por el tipo de cambio.
Para todas las bases e impuestos involucrados, se toman los datos del nodo impuestos y se multiplican por el tipo de cambio.

**Comment by jccastillo0007** [comment]
no ma... siempre lo he hecho con la equivalencia, incluso habias dicho que el tipo de cambio no importa, 

yo te habia dicho que el monto pagado calculado con el tipo de cambio no cuadraba con lo que se estaba pagando, pero dijiste que me basara en la equivalencia, y asi ya cuadra

**Comment by RigoFlores** [comment]
no, lo que se comentó es así tal cual... se toma el monto (pagado)... y se multiplica por el tipo de cambio... con eso te dará el total de pago  (a nivel header del complemento)... 
Pra las bases e impuestos es lo mismo, pero no se toma el monto pagado, se toma del nodo impuestos, las distintas bases e impuestos pagados, y se les multiplica por el tipo de cambio.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ora si, ya se le ve forma a todo esto de pagos.
Voy a tener que repetir tooodas las pruebas, pero esta quedó muy bien... chida..
