### ISSUE TITLE
Conector 4.0 - después de procesar carta porte, marca error en todo lo que no sea cartaporte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1959]
Procesa bien facturas, notas de crédito. Pero le meto complemento de carta porte y se apendeja. Si la procesa bien. Pero al intentar procesar facturas normales, ya no puede. 
Se tiene que reiniciar para que se desatore. 

Le mete esto al final:

    <cfdi:Complemento>
        <cartaporte20:CartaPorte/>
        <leyendasFisc:LeyendasFiscales xmlns:leyendasFisc="http://www.sat.gob.mx/leyendasFiscales" version="1.0">
            <leyendasFisc:Leyenda textoLeyenda="Impuesto retenido de conformidad con la ley del impuesto al valor agregado"/>
        </leyendasFisc:LeyendasFiscales>
    </cfdi:Complemento>

Y pues ya siempre genera el error de :

2022-03-15 11:41:53,931  INFO [pool-2-thread-1] (CFDiWSClient.java:77) - FacturaTi ack : com.facturati.ws.binding.jaxb.Ack@1014111[code=003,description=738
Errores con schemaLocations, namespaces y prefijos]

**Comment by jccastillo0007** [comment]
fixed
