### ISSUE TITLE
ERP - CARTA PORTE - CON PRECIO UNITARIO =0, MARCA IMPORTE = 1

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#196]
LA DESCRIPCION DE LA CARGA, TIENE UN PRECIO UNITARIO =0, YA QUE NO INTERVIENE EN EL TOTAL DE LA FACTURA.
TIENE UN PRECIO DE 1.00 ALMACENADO, AL CAMBIARLO A 0.00 EN LA PANTALLA CUANDO SE AGREGA EL PRODUCTO, QUEDA: CANTIDAD = 1, PRECIO UNITARIO = 0, IMPORTE = 1.0
ES DECIR, NO ESTÁ CALCULANDO EL IMPORTE CORRECTAMENTE CUANDO EL PRECIO ES 0.0

**Comment by jccastillo0007** [comment]
No es que no te crea... pero no pude reproducirlo...

Checa la factura que genere.

JC.

Saludos.
JC.

**Comment by RigoFlores** [comment]
YA LO REVISÉ, Y YA NO SE PRESENTA LA SITUACION. LO MANTENEMOS EN OBSERVACION
