### ISSUE TITLE
pago 2.0 - factura emitida y pagada en USD, no jala... no maa

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1960]
Este es un escenario super básico.
Yo creo que ya lo había probado anteriormente y si jalaba.

Solo creo que no se ha entendido como debe quedar el complemento de pagos.
Tooooodo lo que va en el header, se reporta en MXN. Independientemente de la moneda de pago.

Entonces si el pago fue en USD o la moneda que sea, solo debe hacerse la conversión multiplicando la data del nodo de  pago (bases e importes, para los distintos tipos de impuestos y taasas) por el tipo de cambio.

**Comment by jccastillo0007** [comment]
datos de prueba ?

**Comment by jccastillo0007** [comment]
se supone que usamos el campo equivalencia para todas las conversiones que no?

En este caso la equivalencia da 1.0, y por eso no se calculan bien los datos...  se reporta el pago en pesos, pero los impuestos estan mal... 

cuando se usa el tipo de cambio y cuando es suficiente con la equivalencia... eso no viene en el excel ....

**Comment by RigoFlores** [comment]
El excel es claro al respecto. Cuando la moneda es la misma, todos los cálculos dan directos, ya que equivalencia y tipo de cambio es 1. Eso no querría decir que no se hicieran los cálculos. Pero bueno, se pueden obviar solo en caso que todo sea MXN.

La equivalencia que se reporta a  nivel DR, se utiliza para pasar los números de bases y impuestos, de DR a Pago.

El tipo de cambio se utiliza para pasar de Pago a Totales (ya que totales se reporta en MXN).


Chiaaaaaa

**Comment by RigoFlores** [comment]
datos de prueba, factura 121 o 122, ambas son en USD

**Comment by jccastillo0007** [comment]
fixed
