### ISSUE TITLE
Pagos 2.0 - importe del cobro no suficiente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1961]
intenté pagar en USD la factura 115, que es de 116 MXN
en USD, le indiqué 5.71.

Moneda DR - MXN
Moneda pago - USD
Moneda totales - MXN

Pero ni siquiera lo intenta, ya había levantado este issue y se había cerrado, pero vuelve nuevamente.

el mensaje de error, sin nisiquiera intentar el timbrado es:

Importe del Cobro no suficiente.

Estrictamente hablando, deberíamos hacer conversiones para llegar a comparar peras con peras... si es que queremos validar ello.

Quizás para no clavarnos en el cálculo, bastaría que esta validación NO APLIQUE, cuando la moneda de pago, no sea MXN.

**Comment by jccastillo0007** [comment]
se supone que cuando capturaste que la moneda es USD, hizo la conversión a pesos de acuerdo al tipo de cambio, talvez aún con la conversión no alcanzaba para los 116 MXN... checa el tipo de cambio que tienes para la moneda USD

**Comment by RigoFlores** [comment]
no puedo checar nada, no llegó siquiera al XML.
Yo ocupé un tipo de cambio de 4 decimales, pero el pago se debe reportar en 2 decimales.
Es probable que por ahí vaya, pero tendría que ser el SAT quién lo defina, no nosotros.

**Comment by jccastillo0007** [comment]
El tipo de cambio que tienes capturado es 20.3063 por 5.71 USD = 115.9489 chiaaaa , pues no alcanza para 116

**Comment by RigoFlores** [comment]
no, aquí quedó chueco. Ya no marca el error de importe no suficiente, ese ya entendí porque lo marcaba.

equivalenciaDR, se utilizará SIEMPRE que la moneda de la factura (DR) sea DISTINTA a la moneda de pago.
En el caso de la factura 115, se emitió por 116 MXN.
Pero el pago se realizará con USD, esto es 5.73 USD.
Entonces aquí se calcula la equivalencaDR, misma que se utilizará para reportar ImpuestosP, en la moneda de pago, esto es en USD. Aquí no entra en juego el tipo de cambio, aquí solamente la equivalencia.

Finalmente para el header que se reporta en MXN, el cálculo de total pagado es el monto pagado (5.72) x tipo de cambio (el que se reporte en el XML, o lo que es lo mismo, el que exista en la BD).
Para el caso de las bases e impuestos a nivel header, se toman del nodo ImpuestosP, y se multiplican por el tipo de cambio.

Eso ya lo hiciste para factura en USD, pago en EUR. Ahí jaló bien, pero este escenario que es mas simple, no entiendo porque no jaló.

**Comment by jccastillo0007** [comment]
fixed, esta fue otra validación chacarrona que se quedo por ahi, pero no se cambio nada en los calculos
