### ISSUE TITLE
Pagos 2.0 - Pago Parcial en USD de factura emitida en MXN

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1962]
Factura 115 - total 116.00 MXN
Quiero hacer un pago parcial de $50.00 MXN, pero en USD
El tipo de cambio en el sistema es 20.3063

Entonces el monto es de $2.47 USD, para pagar $50.00 MXN de la factura.  (lo cuál daría $50.16 MXN)

Pero no, dice que el importe no es suficiente.

Entiendo que pasaría lo mismo en mas de una factura MXN, pagadas parcialmente en USD.

**Comment by jccastillo0007** [comment]
fixed
