### ISSUE TITLE
Pagos 2.0 - enviar las variables de la nueva data, y actualizar lo anterior

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1963]
Hay que cambiar los datos actuales a nivel DR, ya que está ocupando las variables de los productos... chiaaaaa

VARIABLES HEADER   (SOLO SON UN GRUPO DE VARIABLES)

TotalRetencionesIVA
TotalRetencionesISR
TotalRetencionesIEPS
TotalTrasladosBaseIVA16
TotalTrasladosImpuestoIVA16
TotalTrasladosBaseIVA8
TotalTrasladosImpuestoIVA8
TotalTrasladosBaseIVA0
TotalTrasladosImpuestoIVA0
TotalTrasladosBaseIVAExento
MontoTotalPagos

VARIABLES DOCTO RELACIONADO.  (AQUÍ ES EL SUBREPORTE, Y PUEDEN SER DE 1 A N)
EquivalenciaDR
Folio
IdDocumento
ImpPagado
ImpSaldoAnt
ImpSaldoInsoluto
MonedaDR
NumParcialidad
ObjetoImpDR
retBaseDR
retImporteDR
retImpuestoDR
retTasaOCuotaDR
retTipoFactorDR
retBaseDR2
retImporteDR2
retImpuestoDR2
retTasaOCuotaDR2
retTipoFactorDR2
traBaseDR
traImporteDR
traImpuestoDR
traTasaOCuotaDR
traTipoFactorDR

VARIABLES PAGO  (CÓMO SOPORTAMOS UNO SOLO PAGO Y NO VARIOS PUES SERÁ UN GRUPO DE VARIABLES; EVENTUALMENTE QUIZÁ TENGAMOS QUE CAMBIAR )

retImporteP001   (ISR)
retImpuestoP001
retImporteP002    (IVA)
retImpuestoP002
retImporteP003    (IEPS)
retImpuestoP003

traBaseP1
traImporteP1
traImpuestoP1
traTasaOCuotaP1
traTipoFactorP1

traBaseP2
traImporteP2
traImpuestoP2
traTasaOCuotaP2
traTipoFactorP2

**Comment by RigoFlores** [comment]
OJO, son datos adicionales a lo que ya se envía hoy...

**Comment by RigoFlores** [comment]
Estas son las variables del subrepote que se llama pago_products.jasper

	<field name="EquivalenciaDR" class="java.lang.String"/>
	<field name="Folio" class="java.lang.String"/>
	<field name="Serie" class="java.lang.String"/>
	<field name="IdDocumento" class="java.lang.String"/>
	<field name="metodoPago" class="java.lang.String"/>
	<field name="numeroPago" class="java.lang.String"/>
	<field name="ImpPagado" class="java.lang.String"/>
	<field name="ImpSaldoAnt" class="java.lang.String"/>
	<field name="ImpSaldoInsoluto" class="java.lang.String"/>
	<field name="MonedaDR" class="java.lang.String"/>
	<field name="tipoCambioDR" class="java.lang.String"/>
	<field name="NumParcialidad" class="java.lang.String"/>
	<field name="ObjetoImpDR" class="java.lang.String"/>
	<field name="retBaseDR" class="java.lang.String"/>
	<field name="retImporteDR" class="java.lang.String"/>
	<field name="retImpuestoDR" class="java.lang.String"/>
	<field name="retTasaOCuotaDR" class="java.lang.String"/>
	<field name="retTipoFactorDR" class="java.lang.String"/>
	<field name="retBaseDR2" class="java.lang.String"/>
	<field name="retImporteDR2" class="java.lang.String"/>
	<field name="retImpuestoDR2" class="java.lang.String"/>
	<field name="retTasaOCuotaDR2" class="java.lang.String"/>
	<field name="retTipoFactorDR2" class="java.lang.String"/>
	<field name="traBaseDR" class="java.lang.String"/>
	<field name="traImporteDR" class="java.lang.String"/>
	<field name="traImpuestoDR" class="java.lang.String"/>
	<field name="traTasaOCuotaDR" class="java.lang.String"/>
	<field name="traTipoFactorDR" class="java.lang.String"/>

**Comment by RigoFlores** [comment]
Y estas variables se agregaron a la plantilla de pago principal...

	<field name="regimenReceptor" class="java.lang.String"/>
	<field name="TotalRetencionesIVA" class="java.lang.String"/>
	<field name="TotalRetencionesISR" class="java.lang.String"/>
	<field name="TotalRetencionesIEPS" class="java.lang.String"/>
	<field name="TotalTrasladosBaseIVA16" class="java.lang.String"/>
	<field name="TotalTrasladosImpuestoIVA16" class="java.lang.String"/>
	<field name="TotalTrasladosBaseIVA8" class="java.lang.String"/>
	<field name="TotalTrasladosImpuestoIVA8" class="java.lang.String"/>
	<field name="TotalTrasladosBaseIVA0" class="java.lang.String"/>
	<field name="TotalTrasladosImpuestoIVA0" class="java.lang.String"/>
	<field name="TotalTrasladosBaseIVAExento" class="java.lang.String"/>
	<field name="MontoTotalPagos" class="java.lang.String"/>
	<field name="retImporteP001 " class="java.lang.String"/>
	<field name="retImpuestoP001" class="java.lang.String"/>
	<field name="retImporteP002 " class="java.lang.String"/>
	<field name="retImpuestoP002" class="java.lang.String"/>
	<field name="retImporteP003 " class="java.lang.String"/>
	<field name="retImpuestoP003" class="java.lang.String"/>
	<field name="traBaseP1" class="java.lang.String"/>
	<field name="traImporteP1" class="java.lang.String"/>
	<field name="traImpuestoP1" class="java.lang.String"/>
	<field name="traTasaOCuotaP1" class="java.lang.String"/>
	<field name="traTipoFactorP1" class="java.lang.String"/>
	<field name="traBaseP2" class="java.lang.String"/>
	<field name="traImporteP2" class="java.lang.String"/>
	<field name="traImpuestoP2" class="java.lang.String"/>
	<field name="traTasaOCuotaP2" class="java.lang.String"/>
	<field name="traTipoFactorP2" class="java.lang.String"/>

**Comment by RigoFlores** [comment]
[pago_products.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/8320038/pago_products.zip.txt)

y este es el reporte y subreporte

**Comment by jccastillo0007** [comment]
ya implementé todas las variables a nivel general, solo me falta lo de pago_products

Pásame también la nueva plantilla a nivel general, ya con el nuevo nombre y con el uso de pago_products

**Comment by jccastillo0007** [comment]
done
