### ISSUE TITLE
Addenda MABE, cuando se factura en USD no manda la moneda correcta a la addenda

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1964]
Si la factura se emitió en USD, a la addenda le manda USD.

**Comment by jccastillo0007** [comment]
web o standalone ?

y no entendi, que debe mandar ?

**Comment by RigoFlores** [comment]
En WEB se detectó.
La addenda tiene un campo moneda... y ahí reporta MXN, aún cuando la factura se emitió en USD.
Debe mandar la misma moneda del CFDI.

<mabe:Moneda tipoMoneda="MXN"/>

Aquí un ejemplo de cómo lo genera.

[addenda mabe USD incorrecta.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8343949/addenda.mabe.USD.incorrecta.xml.txt)

**Comment by jccastillo0007** [comment]
El problema es que el CFD tiene moneda USD, pero tipo de cambio = 1

TipoCambio="1"

Eso supongo es un error de datos de la moneda configurada, chiaaa
