### ISSUE TITLE
Inicializar las nuevas variables del PDF a ""

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1965]
Se requiere así para hacer validaciones.
Ahora mismo llegan como null

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
las variables globales, siguen llegando a null...
<img width="290" alt="global" src="https://user-images.githubusercontent.com/2912775/160251916-a991dd52-e133-4a91-a257-5d5e0c780347.PNG">

**Comment by jccastillo0007** [comment]
chiaaaa, pues crei que eran la de pagos nada mas

fixed
