### ISSUE TITLE
Pagos 2.0 - En las variables de la plantilla de pago, eliminar el signo de $

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1966]
Tanto para el reporte global, como para el subreporte, eliminar los $ de las cantidades, aunque algunos sean importes. Mejor si se necesita el signo, lo manejamos en la plantilla.

En particular estas variables, mandarlas como se mandan al XML, porque se mandan como si fueran importe y son porcentajes:
$F{traTasaOCuotaDR}
$F{retTasaOCuotaDR}
$F{retTasaOCuotaDR2}

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
pues no, acabo de emitir uno y aquí en amarillo todos los signos que aparecen...
<img width="536" alt="pagos2" src="https://user-images.githubusercontent.com/2912775/159970222-f1b1125a-1364-4070-ba32-d2b0a58bd522.PNG">
<img width="639" alt="pagos" src="https://user-images.githubusercontent.com/2912775/159970224-e3b7acbd-aa8d-4de3-adb9-e37931ebe5e5.PNG">

**Comment by jccastillo0007** [comment]
fixed, no sé porque no se había reflejado

**Comment by RigoFlores** [comment]
ahora no puedo generar el pago, por ooootro issue...
