### ISSUE TITLE
CFDI 4.0 - exportación y régimen. Enviar clave y descripción al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1967]
Ahora mismo solo envía la clave, y se requiere la descripción también.
En general para todos los datos que son claves, enviar al PDF la descripción.

**Comment by jccastillo0007** [comment]
No todas las descripciones se tienen disponibles al momento de crear el PDF... ya que algunas se agregan la momento de crear el XML unicamente... 

Además, no me ayuda eso de que "en general", necesito saber exactamente cuales son...

**Comment by jccastillo0007** [comment]
ya quedo el régimen

Me puedes pasar las descripciones posibles de exportación, solo tengo las claves

**Comment by RigoFlores** [comment]
Pues no, ahora quedó mal.
La descripción del régimen, solo se envía al PDF. por ejemplo "626. Regimen Simplificado de Confianza"
Pero al XML se le envía la clave únicamente. Y ahora está enviando al descripción al XML en lugar de la clave, jaja.


<cfdi:Receptor Rfc="FOPR681125BQ0" Nombre="RIGOBERTO MISAEL FLORES DE LA PAZ" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="Regimen Simplificado de Confianza" UsoCFDI="G03"/>

En cuanto a las descripciones de exportación, aquí las tienes:

01	No aplica
02	Definitiva
03	Temporal

**Comment by jccastillo0007** [comment]
fixed
