### ISSUE TITLE
CFDI 4.0 - Ingreso nodo traslados, reportar base e importe a 2 decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1969]
Lo correcto es decir a los decimales que soporta la moneda, pero casi todas las monedas son a 2 decimales.

La diferencia con todas las pruebas realizadas anteriormente, es el precio unitario, este para este caso es de 702.586207
Con todo y el IVA del 16%, da un aprox de $815.00

Fhoy arroja este mensaje:
El valor del campo Base correspondiente a Traslado debe tener hasta la cantidad de decimales que soporte la moneda.

Finkok lo maneja así:
El valor del campo Importe correspondiente a Traslado debe tener hasta la cantidad de decimales que soporte la moneda.

En el XML se muestra así:

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="43232300" NoIdentificacion="TIA-CFDI-100" Cantidad="1.00" ClaveUnidad="C62" Unidad="PAQUETE" Descripcion="100 FOLIOS CFDI CON VIGENCIA DE 12 MESES." ValorUnitario="702.586207" Importe="702.59" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="702.586207" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="112.413793"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="112.41">
        <cfdi:Traslados>
            <cfdi:Traslado Base="702.586207" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="112.41"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

Estaba a punto de liberar, ya tengo todo listo, hasta cambié algunos nombres de los clientes, chiaaaa

**Comment by RigoFlores** [comment]
comparando con la v 3.3, creo que el error se refiere a la sección de total de impuestos del CFDI (no a nivel de concepto)

<cfdi:Impuestos TotalImpuestosTrasladados="112.41">
    <cfdi:Traslados>
        <cfdi:Traslado Base="702.586207" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="112.41"/>
    </cfdi:Traslados>
</cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
ajuste la base a dos decimales... ya esta en pru y pro
