### ISSUE TITLE
NOMINA - DATOS REQUERIDOS Y OBLIGATORIOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#197]
Está solicitando como requeridos el estado, país y CP en el domicilio del empleado.
Aquí existen varios temas:
a) el domicilio del receptor, es opcional en el XML base del sat (anexo 20).
b) OK, si decides incluir el domicilio del receptor, entonces el único dato requerido es PAIS. (corregir este punto).

Aquí debemos tomar la decisión de cómo manejar el asunto.
a) eliminar totalmente la posibilidad de capturar el domicilio.
b) Dejarlo vacío totalmente como opcional.
c) Dejarlo como está ahora mismo, pero solicitando únicamente el país como obligatorio, amén de agregar MEXICO como dato por omisión, y con opción de cambiarlo.

El mejor para el usuario es el punto (a), porque hacemos mas simple la captura. Finalmente el domicilio es opcional, pero ya no le daríamos oportunidad al cliente de poder capturar dicho domicilio en caso que lo requiera. Hoy en día, ese dato no aparece en los recibos de nómina.

El deber ser, es el punto (B), es decir dar la opción de capturar el domicilio, pero cuando capturen algún dato, asegurarse que el país es incluido.

La mas simple de implementar es el punto (c), enviar siempre el país como único dato obligatorio dentro del domicilio del receptor.

Para diferenciarnos y por simplicidad para NOSOTROS, quizás el punto (c), y como mencioné dejando precargado MEXICO como valor por omisión.

**Comment by FraQue0693** [comment]
Se eligiio la Opcion C. 

Se cargo por defecto en el campo pais el valor MEXICO y se quito como campos obligatorios el CP y el EDO
