### ISSUE TITLE
Inicializar las variables de factura global a ""

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1970]
Ya se había comentado, pero bueno siguen llegando a null... son estas. 
Entiendo que si se inician a "", aplicará para todos los reportes donde lleguen, es correcto?

globalPeriodo
globalMes
globalAnio

**Comment by jccastillo0007** [comment]
es correcto, pero puede darse el caso de que ya están inicializadas, y se les asigna null, si no seleccionaron nada en la pantalla de facturación... ya corregí este caso

**Comment by RigoFlores** [comment]
sigue igual, ya estoy trabajando en cfdi4.0 con la tia, y sigue enviando null a la pantalla.
Necesito "", para comparar y no mostrar esa info...

**Comment by jccastillo0007** [comment]
Este fix solo esta en PRU, no en PRO, ma;ana voy a subir un release a prod, para ver lo de retenciones... y ya se va a ir este fix

**Comment by jccastillo0007** [comment]
ya se fue a prod
