### ISSUE TITLE
Permitir cancelar los CFDI 3.3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1971]
Se require cancelar los CFDI 3.3, todavía por un buen rato.
Esto se validó en su momento y jalaba.

No se que pasó.

**Comment by RigoFlores** [comment]
aquí tenemos unas facturas de la tia en pro, donde puedes probar

18/03/2022	16	FHOY	3.3
18/03/2022	14	FHOY	3.3
18/03/2022	15	FHOY	3.3
18/03/2022	16	FHOY	3.3
29/03/2022	7117	FINKOK	4.0
31/03/2022	7127	FINKOK	4.0
31/03/2022	7129	FHOY	4.0
31/03/2022	7130	FHOY	4.0
02/04/2022	7136	FINKOK	4.0

**Comment by jccastillo0007** [comment]
Estas facturas ya están canceladas:

31/03/2022 7129 FHOY 4.0
31/03/2022 7130 FHOY 4.0

En el acuse de cancelación ya se mandan los nuevos datos.
motivo=02,cfdiRelated=

Falta actualizar el jasper de acuse de cancelación , para que agregue esos datos...

**Comment by jccastillo0007** [comment]
Para cancelar una factura de otro PAC, estoy recibiendo el mensaje de Facture Hoy

 CA4.2 - El XML contiene una estructura no válida para CFDI, revise sus parámetros

Es posible que la URL que estoy usando, no soporte CFDi4.0
https://cancelacion.facturehoy.com/CancelacionCFDI33/WsCancelacionCFDIOtroPAC33?wsdl

Ya que tiene el número 33 en la URL, sin embargo, es la URL que nos dieron, por eso digo que es mejor tener un documento formal de ellos donde especifiquen la URL de cada servicio

**Comment by jccastillo0007** [comment]
Oye, podemos dejar cancelación de CFDi 3.3 en la versión de efacturat 3.3 ? para no meter mas complejidad a la versión 4.0 ?

**Comment by RigoFlores** [comment]
Pues si, podría ser... solo que se ocupará por el resto del año quizás.
Tendremos ambos ambientes arriba, solo por la cancelación?

**Comment by jccastillo0007** [comment]
Si, creo que eso es mejor, para no meterle basura a la versión 4.0 ... que después habrá que quitar

De hecho a partir de Junio puedo deshabilitar todas las opciones de facturación en efacturat 3.3 y solo dejar la opción de cancelación

**Comment by RigoFlores** [comment]
ok, pues así hay que hacerle entonces.
La cancelación en 3.3 si está jalando?

**Comment by RigoFlores** [comment]
si, ya vi que la 3.3 si cancela.
Si acaso me faltaría validar que la 3.3 cancele de otros PAC's. Pero para validar ese escenario no tengo XML's
