### ISSUE TITLE
CCP + CFDI 4.0 - Habilitar el Layout de FT (archivo csv) para todos los clientes.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1973]
Para el caso de tener muchas mercancías en el carta porte, y cuando existen errores, la corrección hasta que timbre, puede ser muy costosa. 
Algo que puede ayudar, es que todo lo de mercancías, lo tomen del archivo con el layout de nosotros y ahí lo suban.

Eso nos daría un plus para que nos recomienden, y además ya lo tenemos hecho.

**Comment by jccastillo0007** [comment]
Este ya esta habilitado en PRU

**Comment by RigoFlores** [comment]
no jala, puse el último archivo  que estaba en el oootro issue.
Que es este, a menos que no sea la última versión.

[ejemploFT.txt](https://github.com/jccastillo0007/eFacturaT/files/8455667/ejemploFT.txt)

**Comment by jccastillo0007** [comment]
listo... por ahora le agregue un msg a cada opción para no confundirme...

**Comment by RigoFlores** [comment]
sigue sin reconocer el contenido del archivo.
Con cuál probaste?

**Comment by jccastillo0007** [comment]
con archivo que pusiste arriba, ojo, después de seleccionar el archivo, debes darle click en el ícono que esta a la derecha

chiaaa

**Comment by RigoFlores** [comment]
no estaba actualizado pru.
Ahora si, ya lo subiste y ya jaló.
