### ISSUE TITLE
Enviar variables al jasper de retenciones 2.0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1975]
Son a nivel general:

Estas ya existen, pero no llegan con info y se necesita desplegarlas en el PDF:
regimenReceptor  (clave y descripción)
cpReceptor  

Y en estas otras se debe enviar (son datos nuevos para retención 2.0, pero ya se captura en pantalla y todo):
datoExtra12 - Utilidad Bimestral
datoExtra13 - ISR Correspondiente

estas variables en el equiemel son:

 UtilidadBimestral="200.0" ISRCorrespondiente="50.0"

**Comment by jccastillo0007** [comment]
Oye, estas variables 
datoExtra12 - Utilidad Bimestral
datoExtra13 - ISR Correspondiente

Moverían en dos posiciones las variables que se usan para dividendos... esta bien?

**Comment by RigoFlores** [comment]
no vi eso, pero no.
Estas nuevas, mándalas al final pls y me dices en cuál posición quedaron.

**Comment by jccastillo0007** [comment]
quedaron en posiciones 21 y 22.

**Comment by jccastillo0007** [comment]
según esto ya esta

**Comment by RigoFlores** [comment]
pues no, marca error.
Nosotros teníamos solo hasta el datoExtra20.
De hecho, ya revisé y esa plantilla de retenciones, ocupa hasta el datoExtra13.
Es decir, debería corresponder estos datos, enviarlos al datoExtra14 y 15.
No veo caso agregar mas variables, a las tantas que ya tenemos.

**Comment by RigoFlores** [comment]
tampoco veo que lleguen los datos del CP y régimen del receptor.

**Comment by jccastillo0007** [comment]
Listo. :

datoExtra21=10.0,datoExtra22=10.0
cpReceptor=76090
regimenReceptor=Personas Fisicas con Actividades Empresariales y Profesionales
