### ISSUE TITLE
Conector CFDI 4.0 - Nomina, invocar a la plantilla correspondiente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1976]
Ahora mismo, cuando timbra la nómina jala la  plantilla cfdi_base33.jrxml.
En web el nombre quedó como cfdi_nomina40.jrxml
Yo creo que lo manejamos igual en el conector, no?

**Comment by jccastillo0007** [comment]
listo, este es el nombre homologado con web:

cfdi_nomina40.jrxml
