### ISSUE TITLE
Soporte a Complemento de pago con factoraje financiero

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1977]
Si entendí bien el mensaje, en el segundo nodo de pago, está pidiendo el tipo de cambio.

La vedad no está clara la spec para este escenario, pero anteriormente se incluían 2 nodos de pago.
ahora también deben incluirse, pero no se si sean 2 nodos de pago, con todo el pinche desglose de impuestos.

Mira, aquí un ejemplo de cómo lo hace en la 3.3

[PAGO112_MPB041122H93_HMI950125KG8_10Feb2022_220015.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8477035/PAGO112_MPB041122H93_HMI950125KG8_10Feb2022_220015.xml.txt)

**Comment by RigoFlores** [comment]
alguna niu?

**Comment by jccastillo0007** [comment]
not yet, ya termine lo de cargar cfdi externos... 
queria iniciar con el descargat para los de abastos... quieres que haga este ticket primero ?

**Comment by RigoFlores** [comment]
pues del conector falta lo de pagos. Apenas cubrimos el escenario mínimo básico. 
documenté que sería concluir lo básico de pagos. Entonces eso sigue.
Y enseguida, creo que abastos.
La cancelación ha sido un dolor de cabeza, me demanda una buena parte de mi tiempo.
Y luego este, pero si necesitamos meterle pedal.

**Comment by jccastillo0007** [comment]
Este esta duplicado con el ticket 2059
