### ISSUE TITLE
Enviar las variables nuevas a las plantillas del conector, y nombrarlas de acuerdo a CFDI 4.0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1978]
Necesitamos homologar los nombres de las plantillas y enviar las variables correspondiente.

cfdi_base40.jrxml
cfdi_nomina40.jrxml
cfdi_AcuseCancelacion22.jrxml
cfdi_pago40.jxml
cfdi_notacredito40.jrxml
complementocartaporte20.jrxml

variables nuevas CFDI, Nota de Crédito, Carta Porte:
	<field name="globalPeriodo" class="java.lang.String"/>
	<field name="globalMes" class="java.lang.String"/>
	<field name="globalAnio" class="java.lang.String"/>
	<field name="regimenReceptor" class="java.lang.String"/>
	<field name="exportacion" class="java.lang.String"/>

A nivel producto:
	<field name="objImp" class="java.lang.String"/>

Acuse de Cancelación:
motivo
cfdiRelated

COMPLEMENTO DE PAGO:
A nivel general
regimenReceptor
TotalRetencionesIVA
TotalRetencionesISR
TotalRetencionesIEPS
TotalTrasladosBaseIVA16
TotalTrasladosImpuestoIVA16
TotalTrasladosBaseIVA8
TotalTrasladosImpuestoIVA8
TotalTrasladosBaseIVA0
TotalTrasladosImpuestoIVA0
TotalTrasladosBaseIVAExento
MontoTotalPagos
retImporteP001 
retImpuestoP001
retImporteP002 
retImpuestoP002
retImporteP003 
retImpuestoP003
traBaseP1
traImporteP1
traImpuestoP1
traTasaOCuotaP1
traTipoFactorP1
traBaseP2
traImporteP2
traImpuestoP2
traTasaOCuotaP2
traTipoFactorP2

A nivel de productos:
EquivalenciaDR
Folio
Serie
IdDocumento
metodoPago
numeroPago
ImpPagado
ImpSaldoAnt
ImpSaldoInsoluto
MonedaDR
tipoCambioDR
NumParcialidad
ObjetoImpDR
retBaseDR
retImporteDR
retImpuestoDR
retTasaOCuotaDR
retTipoFactorDR
retBaseDR2
retImporteDR2
retImpuestoDR2
retTasaOCuotaDR2
retTipoFactorDR2
traBaseDR
traImporteDR
traImpuestoDR
traTasaOCuotaDR
traTipoFactorDR

**Comment by jccastillo0007** [comment]
Estoy homologando lo que esta en web y lo que esta en standalone.

Estas dos las tienes incorrectas
cfdi_AcuseCancelacion22.jrxml
complementocartaporte20.jrxml

debe ser 
cfdi_AcuseCancelacion.jrxml
complementocartaporte40.jrxml

**Comment by RigoFlores** [comment]
Hice una prueba de factura, el básico y pues no está requiriendo el cfdi_base40.jrxml, todavía invoca al 33.
Solo probé anteriormente lo de nómina, chiaaaa

**Comment by jccastillo0007** [comment]
se me hace que no estas usando la última versión

**Comment by RigoFlores** [comment]
último jar del 15 de abril

**Comment by RigoFlores** [comment]
falta enviar la descripción del régimen fiscal del receptor, y la descripción de exportación.

**Comment by jccastillo0007** [comment]
checale, con la versión de hoy

**Comment by RigoFlores** [comment]
pues no, ahora ya no genera el PDF. Marca error... en la consola se ve así...

00,traImporteP2=160.00,traImpuestoP2=002,traTasaOCuotaP2=0.16,traTipoFactorP2=TASA,pago_dr=[com.cfd.shared.utils.jasper.JasperPagoProductsBean@a39d6d],mode
rvice=<null>,globalPeriodo=<null>,globalMes=<null>,globalAnio=<null>,exportacion=<null>,regimenReceptor=626 Regimen Simplificado de Confianza]
2022-04-22 16:22:18,172 ERROR [pool-2-thread-1] (FacturaTiCreator.java:1343) - java.lang.NullPointerException
java.lang.NullPointerException
        at com.facturat.controller.CFD.creator.FacturaTiCreator.getJasperPrint(FacturaTiCreator.java:313)
        at com.facturat.controller.CFD.creator.FacturaTiCreator.createCFD(FacturaTiCreator.java:225)
        at com.facturat.controller.CFD.creator.FacturaTiCreator.createCFD(FacturaTiCreator.java:1281)

**Comment by jccastillo0007** [comment]
listo
