### ISSUE TITLE
Actualizar liga de catálogo del Complemento de carta porte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1979]
Lo actualizaron el 31 de marzo.
Esta es la liga:

http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/CatalogosCartaPorte20.xls

**Comment by jccastillo0007** [comment]
esa es la liga que esta configurada, chiaaa

**Comment by RigoFlores** [comment]
ok, entonces es la misma liga, pero actualizaron el contenido.
