### ISSUE TITLE
ERP- no asignar serie-folio, ni tipo de comprobante en cotizacion, pedido y remisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#198]
Cuando consultamos por cotización, pedido o remisión, aparece una serie, folio y nombre de comprobante fiscal. Esto confunde mucho, ya que eventualmente a una remisión le puede corresponder otro número de serie y folio. 
Estos 3 documentos, no deben mostrar información como si fuera factura.

**Comment by jccastillo0007** [comment]
Fixed.
