### ISSUE TITLE
Conector 4.0 - documento de pago, soporte a mas de 1 factura.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1980]
Ahora mismo solo soporta pago total a 1 factura.

Faltan algunos escenarios **BÁSICOS** (con solo IVA trasladado del 16% y en MXN):
a) pago total de 2 o más facturas
b) pago parcial de 1 factura
c) pago parcial de 2 o más facturas

**Comment by jccastillo0007** [comment]
por conector , no podemos soportar pagos parciales, ya que no hay forma de acumular los pagos y calcular el remanente.

A menos que en el layout informen el saldo remanente y todos los datos para pagos parciales?

**Comment by jccastillo0007** [comment]
Ya puede soportar pagos totales a mas de una factura...

El problema con pagos parciales, es el calculo de intereses parcialmente pagados

**Comment by RigoFlores** [comment]
Vámonos por partes.
Primero, en pago totales a mas de 1 factura, no está jalando. 
Probé pago a 2 facturas.
Marca que no encuentra la segunda factura. 

Aún cuando la segunda factura sea la misma que la primera...

O incluso, jala para una factura. Por ejemplo la F83.
Si esa misma F83 la pongo como una segunda factura en un archivo, dice que no la encuentra...

**Comment by jccastillo0007** [comment]
algo mal debes tener en el txt, yo probé con este archivo y si funciona
[PagoCheque2.txt](https://github.com/jccastillo0007/eFacturaT/files/8608107/PagoCheque2.txt)

**Comment by RigoFlores** [comment]
Listo el escenario A.
Creo que modificaste el layout anterior, chiaaaa... ahora no lleva comas (,), entre un DR y el otro.

**Comment by RigoFlores** [comment]
Escenario B:
En el pago parcial, hice una prueba y lo timbró, jajajaja... solo que tiene unos datos mal reportados.
Aquí tienes el XML, con lo correcto y lo incorrecto, jajajaja.

También anexo el archivo de texto que generó ese XML. Recuerda que hay que modificar el UUID, Folio, Serie, Monto.
[parcialChueco.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8633420/parcialChueco.xml.txt)

[PagoParcial.txt](https://github.com/jccastillo0007/eFacturaT/files/8633421/PagoParcial.txt)

**Comment by jccastillo0007** [comment]
listo el escenario B de pago parcial

**Comment by RigoFlores** [comment]
no hay nueva versión en el drot bots

**Comment by RigoFlores** [comment]
validados los 3 escenarios mencionados
