### ISSUE TITLE
CFDI 4.0 + Nomina - Web y Conector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1981]
Eliminar el atributo TipoCambio a nivel header del CFDI.
Hasta hace unos días lo aceptaba, ahora ya no.
Me refiero a este...

TipoCambio="1"

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
No veo ninguna nueva versión del conector
En web pru, si quedó.
