### ISSUE TITLE
Retenciones 2.0 Catálogo de Tipo de pago.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1982]
Hasta apenas voy conociendo el catálogo de tipos de pago. Te acuerdas que no lo encontraba. Bueno, lo mandó Finkok.

c_TipoPagoRet	Descripción			Tipo impuesto
01	Pago definitivo IVA					002
02	Pago definitivo IEPS				003
03	Pago definitivo ISR Plataformas		001
04	Pago provisional ISR				001

Pero no solo esto, cuando eliges algunas de las opciones, la clave de impuesto correspondiente es la columna tipo impuesto.
Es decir, dependiendo de el tipo de pago, se deberá reportar la clave de impuesto correspondiente...
Por ejemplo, aquí que marcó error:
        <retenciones:ImpRetenidos BaseRet="0.0" ImpuestoRet="02" MontoRet="47619.05" TipoPagoRet="02"/>

Correcto:
        <retenciones:ImpRetenidos BaseRet="0.0" ImpuestoRet="003" MontoRet="47619.05" TipoPagoRet="02"/>

Es decir el tipo de impuesto, pues entiendo que ya no es necesario que lo seleccionen, ya que está amarrado al tipo de pago. Habría que ocultarlo de la pantalla, o mejor mostrarlo en modo solo lectura, dependiendo del tipo de  pago seleccionado.

<img width="749" alt="retenciones" src="https://user-images.githubusercontent.com/2912775/166337773-82641215-0bc1-42b6-80c5-65bc3cb66419.PNG">

**Comment by jccastillo0007** [comment]
listo, ya esta en prod
