### ISSUE TITLE
Complemento de pago 4.0, en USD y pagos parciales con problemática

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1984]
Tenemos el siguiente escenario:

R.F.C.   GIM 140225NB0

Datos del depósito:

PASO 1
Fecha: 6 de mayo de 2022
hora: 18:37:33
Importe del cobro:  $142,280 pesos
Referencia:  085900023700312621

PASO 2.
Razon social:  INDUSTRIAS CORRUBOX
- poner la lupa para que se desplieguen las facturas, con ese depósito están pagando las siguientes facturas:

FACTURA  1101  POR $3,769.11  DÓLARES  (2A. PARCIALIDAD Y PAGO FINAL)
FACTURA  1106  POR $3,266.86 DÓLARES (1A. PARCIALIDAD, PAGO A CUENTA)

PASO 3.
Seleccionar -- Incluir CFDi Pago
Forma de pago: 03 Trasferencia electrónica de fondos
cuenta origen
Banco cuenta:  BANCO NACIONAL DE MEXICO, SA.:002180434400082413
cuenta destino
Nombre del banco: BBVA BANCOMER:012180001958200225

**Comment by RigoFlores** [comment]
Viendo las facturas, tenemos y el primer documento de pago, todos están en la versión 3.3
Este cliente ya migró a 4.0, pero ahora que quiere hacer el pago, no lo hace.
la fácil es decirle que lo emita en 3.3, pero si me gustaría que le echaras un vistazo, ya que para Julio no existirá mas la 3.3 pero si este escenario y otros similares.

[pago parcial.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/8655829/pago.parcial.zip.txt)
o

**Comment by jccastillo0007** [comment]
Pues no sé cual era el error, no pusiste nada de esa info... lo reproduje con los datos que indicaste arriba y si generó el xml y pdf... espero haber capturado todo bien, porque lo hic
[PAGO392_GIM140225NB0_ICO990202Q17_13May2022_191214.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8691867/PAGO392_GIM140225NB0_ICO990202Q17_13May2022_191214.xml.txt)
e con la cuenta del cliente, chiaaaa
[PAGO392_GIM140225NB0_ICO990202Q17_13May2022_191214.pdf](https://github.com/jccastillo0007/eFacturaT/files/8691868/PAGO392_GIM140225NB0_ICO990202Q17_13May2022_191214.pdf)

**Comment by RigoFlores** [comment]
pues al parecer si, todo está bien.
Excepto la fecha de pago, chiaaaaa

Pero no hiciste nada para corregirlo??
