### ISSUE TITLE
Complemento de pago 2.0 con CFDI 4.0, en facturas 3.3 emitidas desde escritorio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1985]
Bueno, al menos ese es el escenario. No estoy seguro que sea obligatorio que sean facturas desde escritorio.

Las facturas todas son 3.3
Se emitieron desde escritorio.
Ahora se intenta hacer el complemento con los datos siguientes:
Emisor :HERJ610106BV2

Datos del complemento:

<img width="405" alt="pago1" src="https://user-images.githubusercontent.com/2912775/167675889-daaed04b-ba1a-410f-a0b1-fd7f53904e9a.PNG">

<img width="490" alt="pago2" src="https://user-images.githubusercontent.com/2912775/167675928-999321c5-6258-467c-b561-1a28682cdd87.PNG">

Y lo que marca de error es lo siguiente:  (al final finkok lo reporta como no clasificado).

[TASA.TXT](https://github.com/jccastillo0007/eFacturaT/files/8663298/TASA.TXT)

Lo que se envía a timbrar es esto:

[pagoIncompleto.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/8663339/pagoIncompleto.xml.txt)

**Comment by RigoFlores** [comment]
Ya lo pude reproducir en pruebas:
Emisor: IIA040805DZ4
Receptor: TIA101020BP4
Facturas: F6 y F7.

Intenta generar un pago para ambas facturas, y el error se reproduce sin pedos..

**Comment by jccastillo0007** [comment]
ya quedo arreglado el error que salia, pero ahora sale otro con la tasa, lo sigo revisando

**Comment by jccastillo0007** [comment]
listo ya quedo... 

si  es lo que te decía, antes guardábamos datos con diferente formato, y al parecer no impactaba... ahorita ya lo están validando...

**Comment by RigoFlores** [comment]
no es que no impactara, la leyenda siempre ha sido "Tasa", lo que pasa es que antes no se enviaba esa info al SAT.
Recuerda que esto de los impuestos es nuevo para el pago 2.0

**Comment by RigoFlores** [comment]
ya está en pro, veldá?
