### ISSUE TITLE
Conector 4.0 - Pagos en moneda distinta al CFDI pagado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1986]
Vamos a atender los siguientes escenarios nivel medios:
Moneda de Pago: MXN.
Facturas emitidas en USD o cualquier otra moneda
1) Pago total de 1 factura
2) Pago total de n facturas
3) Pago parcial de 1 factura
4) Pago parcial de n facturas

Aquí se debe calcular el tipo de cambio del DR, que se llama EquivalenciaDR. Por ejemplo. Se paga el total de una factura:
Monto (pagado): $21,000.00 MXN
Factura (total): $1,000.00 USD
EquivalenciaDR = (1000 / 21,000 ) * 1.000002  = 0.047619
Recordemos que ese factor de ajuste, se identificó para evitar muuchos problemas por el tema de los decimales permitidos.

Impuestos a nivel DR, se reportan en la moneda original del CFDI. Eso ya lo hacemos.

Impuestos a nivel Pago (ImpuestosP), se reportan en la moneda de pago. Es decir, se realiza la suma de las base y de impuestos del o los DR, y se divide entre EquivalenciaDR. En el ejemplo de arriba BaseP = 10000 / 0.047619 = 21,000.02
El impuesto , se calcula igual. Aunque en el ejemplo, el IVA es tasa 0. Pero si no lo fuera, pues se calcula igual, sumando los impuestos del mismo tipo de las facturas involucradas, y se reporta con la misma división.

Y finalmente los totales, serán un reflejo del nodo ImpuestoP, ya que la moneda de pago es MXN. Y totales se reporta en MXN

**Comment by jccastillo0007** [comment]
Listo, yo probé con pagos totales y parciales con iva y retenciones con una factura

Te toca probar para n facturas.

**Comment by RigoFlores** [comment]
pues no, no jala... sube el o los archivos con los que probaste, seguramente el layout que tengo algo está mal...

**Comment by jccastillo0007** [comment]
[PagoChequeusd.txt](https://github.com/jccastillo0007/eFacturaT/files/8712587/PagoChequeusd.txt)
yo probé con este

**Comment by RigoFlores** [comment]
Escenario 1 - OK
Escenario 2 - Creo que todo radica en que no está haciendo bien el cálculo de EquivalenciaDR, y de ahí vale madres todo.
Anexo archivo de lo correcto e incorrecto.
[2facturas.xml.TXT](https://github.com/jccastillo0007/eFacturaT/files/8712759/2facturas.xml.TXT)

**Comment by RigoFlores** [comment]
Escenario 3 - OK
Escenario 4 - no jala, mismo comportamiento del escenario 2. Según yo, arreglándose la equivalenciaDR, ya quedarían los 4

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
ok, ya quedaron cubiertos estos escenarios.

Creo que por lo pronto, aquí cerraremos los pagos del conector.
No creo que haya casos mas complejos. 
Chingón, quedó chingón...

**Comment by RigoFlores** [comment]
Según la lista, falta lo de pagos de facturas con retención emitidas en USD y pagadas en MXN.
Yo creo que si se presenta ese escenario, entonces ya lo revisamos.
Ahora probé este escenario, y según yo todo está bien, pero marca error.
Tendré que escalarlo con finkok.

**Comment by RigoFlores** [comment]
Hola buenas tardes estimado Rigoberto,

El error que presenta es debido a que dentro de los importesP de retenciones, se pide se trunquen los valores a 2 decimales  
Quedando de la siguiente manera: 


Ya me respondieron los de finkok, según que los importes en los impuestos retenidos, deben ir a 2 decimales.
No me hace mucho sentido, ya que los importes en los trasladados, si los están aceptando a 6 decimales, que no mamen.

Incorrecto:
[ImporteP retencion.xml,txt](https://github.com/jccastillo0007/eFacturaT/files/8721263/ImporteP.retencion.xml.txt)

Correcto:

 <pago20:RetencionP ImporteP="311.02" ImpuestoP="001"/>
                        
<pago20:RetencionP ImporteP="2654.14" ImpuestoP="002"/>
