### ISSUE TITLE
Considerar el Factor de ajuste, en el cálculo de la equivalenciaDR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1988]
Aplica cuando el pago se realiza en moneda distinta a la moneda del DR.
Por ejemplo: 
Importe Factura: 6.78 USD
Pago: 150.50 MXN

EquivalenciaDR = ( 6.78 / 150.00 ) * 1.000002 

Donde el resultado debe ser truncado a 6 decimales, pero no redondeado.

**Comment by RigoFlores** [comment]
En pru, tenemos este caso, que no jala (está redondeando, en lugar de truncar a 6 decimales):

Emisor: IIA
Receptor: la tia
Pago: 413,193.92  MXN
Facturas: 411 a 414, son 4 facturas pagadas totalmente,  en total suman 21,085.08 USD
La equivalencia que calcula ahora mismo el sistema es: 0.051030

sin embargo el cálculo dice: ( 21085.08 / 413193.92 ) * 1.000002 = 0.0510296041... que TRUNCADO A 6 DECIMALES, se obtiene: 0.051029

Pues ese pinche 6° decimal la hace de a pedo, y marca error...

**Comment by RigoFlores** [comment]
que hay con este issue?

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
jaja, se tuvo que levantar otro para que se atendiera este... básicamente se refería a truncar en lugar de redondear.
Sigue sin jalar, pero pues ya le seguimos por el otro issue.
