### ISSUE TITLE
Unificar en uno solo, el servidor de migración

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1989]
Entiendo que ahora mismo tenemos 2, es decir, nos estará costando el doble del precio,

**Comment by RigoFlores** [comment]
Este tiene su prioridad y dependerá un poco de cuánto nos está costando... por ello requiero el costo actual del servidor alterno.

**Comment by RigoFlores** [comment]
pues nos estará costando unos 1200 pesos anuales, no sé si sea lo que ese cliente consume, jeje
Que se requiere para traer lo de producción aquí, y que implica?

**Comment by jccastillo0007** [comment]
hmmm como asi, son 3 USD por mes, van a ser como 700 pesos, porque 1200 ?
Para migrar, se va a requerir de un fin de semana estar fuera de linea, y a reserva de ver si se puede usar el mismo certificado, tal vez si, porque es el mismo dominio, pero debo checar eso...

**Comment by jccastillo0007** [comment]
este ya no aplica, ya que con eft2, vamos a usar los dos servers... mientras actualizamos el ui para todos

**Comment by RigoFlores** [comment]
no entendí.
Porque cuando se libere ft20, no aplicará el UI para todos los clientes???
Será como un switch, no?
o cómo lo estás pensando?

**Comment by jccastillo0007** [comment]
la idea es desacoplar el UI del backend, y así podemos llegar a escalar uno de los dos , si tenemos problemas... 
A como estamos ahorita, solo podemos tener un servidor muuuuy grande, en lugar de dos pequeños o medianos.

Poder escalar sale más barato cuando esta desacoplado .

**Comment by RigoFlores** [comment]
No entendí, seguimos operando ahora mismo con 2 servidores, donde 1 de ellos solo sirve para lo de pepsi???
