### ISSUE TITLE
ERP- En criterios de consulta, falta poder elegir facturas pagadas y cxc

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#199]
No hallé la forma de filtrar por las facturas pagadas, o las facturas por cobrar (cuentas por cobrar)

**Comment by jccastillo0007** [comment]
La idea es generar un reporte por ejemplo de facturas y en la consulta se despliega el monto pagado, pueden exportar esa informacion a excel y jugar con ella.... 

Aun asi se ocupa el filtro de pagada / cuentas por cobrar ?
