### ISSUE TITLE
DescargaT 4.0 - Pantalla Mi Perfil

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1990]
Se requiere actualizar los datos del receptor.
No tiene botón de editar, entiendo que directamente se teclea y cambia todo.
Al momento de dar guardar, marca internal error y no guarda los cambios.

**Comment by RigoFlores** [comment]
prueba con el usuario de la tia, ya que con otro usuario si permitió hacer cambios.

**Comment by jccastillo0007** [comment]
fixed.

El problema es que hay dos usuarios de la TIA, no se estaba validando ese escenario, que si puede ser común.
