### ISSUE TITLE
Versión de Escritorio - no incluye en el XML los datos de la factura global

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1994]
De hecho no he logrado timbrar porque marca error en el nombre del rfc XAXX010101000, pero el nombre está bien.
Lo que noté cuando estaba a punto de mandar el equiemel a finkok, es que no está incluyendo la info de la factura global.

Una vez que se incluya esa info, quizá ya timbre la factura global.

**Comment by jccastillo0007** [comment]
fixed
