### ISSUE TITLE
Escritorio 4.0 - en la cancelación no se puede capturar el campo del CFDI relacionado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1995]
Aunque no está jalando eso en el SAT, cuando se desatore, se requerirá.
Es una caja de texto "larga", donde capturen el UUID del cfdi relacionado.

**Comment by jccastillo0007** [comment]
chiaaaaa

ya que eliges alguna opción que lleva un cfdi relacionado, y le das OK, te abre otro diálogo para capturar el UUID...
