### ISSUE TITLE
Complemento de carta porte - refactoring 1, rumbo al carta porte mas gaver de méxico...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1997]
1) Generar el catálogo de remolques. ID, Subtipo y placas. Validar que son datos obligatorios los 3. El catálogo se deberá llenar con los registros que actualmente se tiene capturados en transporte. El ID, sería el número de placa.

2) En el catálogo de transporte, incluir el seguro de responsabilidad civil: Aseguradora y póliza (datos obligados).

3) En el catálogo de transporte, se podrá o no, asociar 1 o 2 remolques al transporte. Se eligen por su ID (del catálogo de remolques).

4) En la pantalla de captura (addenda), quitar la captura del seguro de responsabilidad civil (ya que se capturará ahora en el catálogo de transportes)

5) En la pantalla de captura (addenda), dar la opción de capturar 1 o 2 remolques. Si el transporte elegido ya tiene asociado algún remolque, mostrarlo con la opción de cambiarlo solo para ese carta porte.

**Comment by jccastillo0007** [comment]
Listos los puntos 1, 2, 3 y 4

**Comment by jccastillo0007** [comment]
listo, ya están los 5 puntos

**Comment by RigoFlores** [comment]
A cómo quedó el catálogo de transportes, los únicos datos que no son obligatorios son los remolques.
Todos los demás los deben capturar, pero ahora mismo no se valida que se capturen el año, el seguro, el número de póliza. Queremos evitar errores, entonces indicarle al usuario cuando le esté faltando un dato.

Falta incluir el catálogo de claves de permiso. Está de libre captura, pero debe ser el catálogo.

Finalmente, se deben migrar todos los remolques capturados para cada cliente (en transportes), al catálogo de remolques, manteniendo los remolques actuales en los transportes.

**Comment by jccastillo0007** [comment]
Este item esta fuera de este ticket:

Falta incluir el catálogo de claves de permiso. Está de libre captura, pero debe ser el catálogo.

La migración, la tendré que hacer cuando liberemos esta versión a prod, serán queries mágicos

**Comment by RigoFlores** [comment]
Pendientes de este issue:

Hay que validar que se capturen el año, el seguro (responsabilidad civil), el número de póliza, ya que son datos obligatorios.

En cuanto a los cueries mágicos, solo hay que considerar lo siguiente... cuando nos vayamos a producción con estos cambios debemos:
i) Llenar los catálogos de remolques de cada cliente, con lo que tienen capturado actualmente.
ii) En el catálogo de transporte mantener los remolques que ahora se tienen capturados. Por su ID.

En cuanto a elegir los remolques dentro del catálogo de transportes, no existe la opción para "borrarlos", es decir "no elegirlos", el famoso "seleccione uno" o vacío de la lista desplegada. En la pantalla de captura del complemento (addenda), ahí si que existe la opción de "no elegir" para los remolques.

**Comment by jccastillo0007** [comment]
listo, checale
