### ISSUE TITLE
Complemento de carta porte - refactoring 2 Catálogo de Mercancías, rumbo al ccp mas gaver de México

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#1998]
Para mercancías podemos mejorar mucho:
a) Cargar el catálogo de c_ClaveProdServCP en una tabla de referencia del sistema. Con los campos de c_ClaveProdServ, Descripción y Material Peligroso. Considerar que esta tabla se debe actualizar cada cierto tiempo a partir de un excel, entonces hacer una pantalla del administrador para subir las actualizaciones.

b) Cuando el cliente capture la clave del sat, validar que: (1) existe en el catálogo, (2) si el campo material peligroso tiene '0,1', entonces colocar **No**, en el campo Material Peligroso (de la pantalla). El cliente lo podría cambiar en caso que si sea material peligroso.

c) Si la clave de producto capturada no existe en el catálogo del sat, indicarlo en pantalla. 

d) Validar que si capturan valor deben capturar moneda y viceversa. Son opcionales, pero van juntos.

e) Si capturan el peso (agregar label en Kgs), llevar ese peso a la pantalla de captura, considerando la cantidad transportada. Por ejemplo, si transportan 5 refrigeradores y pesan 120 kg c/u... en la pantalla de captura del complemento, poner ese dato ya calculado, es decir 120 x 5 = 600 kgs.

f) Al capturar la clave de producto válida, poner la descripción del catálogo correspondiente en el campo descripción de la pantalla. Es sugerido, el usuario lo podrá editar.

g) Incorporar los catálogos de clave de material peligroso y clave de embalaje. Validar si es funcional desplegarlos o, seguir la estrategia del punto (a), es decir tenerlos en catálogos de referencia y validar que si existan las claves cuando éstas se capturen manualmente.

i) Si capturan clave de material peligroso, validar que capturen clave de embalaje y viceversa.

**Comment by jccastillo0007** [comment]
En el punto a)

a) Cargar el catálogo de c_ClaveProdServCP en una tabla de referencia del sistema. Con los campos de c_ClaveProdServ, Descripción y Material Peligroso. Considerar que esta tabla se debe actualizar cada cierto tiempo a partir de un excel, entonces hacer una pantalla del administrador para subir las actualizaciones.

Y tu nieve de que sabor, la actualización será por queries, no maaaa

**Comment by RigoFlores** [comment]
Chiaaaaa...
cuando detectemos que cambió el catálogo, en putiza hay que cambiarlo... tons dejar documentados los cueries...
chiaaaaa

**Comment by jccastillo0007** [comment]
listos los puntos 
a) sin la pantalla solicitada, para actualizar los productos, hay que formatear el excel con cara de query.... ya lo hice en el excel que tenemos, pero creo que eso debo hacerlo yo
b)
c)
f)

**Comment by RigoFlores** [comment]
Punto (c).
Está permitiendo guardar el registro aún cuando no exista el producto en el catálogo del SAT. No debe guardarlo porque al incluirlo en el carta porte seguro marcará error..

**Comment by jccastillo0007** [comment]
Listos:
a
b
c
d
f
i

chiaaaa, todo por usar un ticket para mas de un cambio

**Comment by RigoFlores** [comment]
si, es que es atómico, para que no se me vaya la visión del todo... ya se que es mas complicado, hasta para probarlo...
pero bueno, ya quedará solo lo de llevar el peso a la pantalla de captura, y por otro lado multiplicarlo por la cantidad.

**Comment by jccastillo0007** [comment]
listo, ya están todas las letras cubiertas
