### ISSUE TITLE
EL CBB SE BRINCA LOS FOLIOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2]
CON LA LLAVE CBB, AL DAR UN PREVIEW A LA FACTURA. SI NO GENERAS LA FACTURA EN ESE MOMENTO SE BRINCA UN FOLIO. POR EJEMPLO SI DESPUÉS DEL PREVIEW LE DAS LIMPIAR O TE CAMBIAS DE VENTANA, ENTONCES ES CUANDO SE BRINCA UN FOLIO

**Comment by jccastillo0007** [comment]
Fixed release 6.2.7

Solo pasaba en CBB.

**Comment by RigoFlores** [comment]
NO SE PUEDE LEVANTAR EL SISTEMA CON EL EXE.
SOLO ACEPTA EL BAT, PERO ESO NO ES PRÁCTICO PARA CLIENTES EN WINDOWS.
CON EL EXE, SE QUEDA CON LA VENTANA NEGRA INICIAL, Y DE AHÍ NO PASA
