### ISSUE TITLE
CATALOGO DE CLIENTES - NO VALIDA LONG DEL RFC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#20]
NO VALIDA LA LONGITUD MÍNIMA DEL RFC.
REALMENTE VOLVER A PROBAR TOOOODO LO QUE YA SE HIZO EN SU MOMENTO CON LA VERSIÓN STAND ALONE, ES MUY COMPLICADO. ES RETOMAR TOOOODAS LAS PRUEBAS DESDE EL INICIO, SIENDO QUE ESTA VERSIÓN DEBERÍA CONTAR CON TODAS LAS VALIDACIONES DE LA VERSIÓN ACTUAL. NO SÉ CUANTO TIEMPO TOME PODER LLEGAR AL ESTADO DE ARTE QUE ALCANZAMOS EN 2 AÑOS CON EL FACTURAT ACTUAL

**Comment by jccastillo0007** [comment]
Done.

Es curioso ver que el error lo describes en el titulo o en una linea, y luego te avientas todo un choro mareador de varios renglones, chaaaaaaaaaaaaaaaaaaa

**Comment by RigoFlores** [comment]
SIN PODER VALIDAR POR NO PERMITIR GUARDAR REGISTROS DE CLIENTES

**Comment by RigoFlores** [comment]
OK, LO VALIDA, PERO SOLO HASTA QUE LO QUIERES ALMACENAR.
LO IDEAL ES QUE:
A) NO PERMITA CONTINUAR SI NO CAPTURASTE DE 12 A 13 CARACTERES
B) NO PERMITA CAPTURAR MAS DE 13 CARACTERES
C) SOLO PERMITE LETRAS, NÚMEROS Y EL SÍMBOLO &.
CON ELLO QUEDARÍA OK, ESTE DEFECTO
