### ISSUE TITLE
ERP - COTIZACIÓN ELIMINAR/OCULTAR INFORMACIÓN NO REQUERIDA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#200]
EN LA COTIZACIÓN NO SE OCUPA (HAY QUE OCULTARLOS):
LUGAR DE EXPEDICIÓN
FORMA DE PAGO
METODO DE PAGO
CUENTA O TARJETA
CFDI
PAGADA
FECHA DE PAGO
SERIE
FOLIO

ADEMAS, AL MOMENTO DE SELECCIONAR COTIZACION, EN VEZ DE QUE EL BOTON MUESTRE "GENERAR FACTURA",  SEA "GENERAR DOCUMENTO".

Y OCULTAR LOS BOTONES DE  "ADDENDA" Y "DATOS EXTRAS".

LA INFORMACIÓN QUE NO SE OCUPA AL MOMENTO, SIEMPRE CONFUNDIRÁ AL CLIENTE, CON LAS LLAMADAS CONSECUENTES A SOPORTE TÉCNICO.
VAMOS SACANDO LIMPIAS LAS PANTALLAS

**Comment by jccastillo0007** [comment]
Mmm eso si esta muy cabron... es la misma pantalla para todos los tipos 
de documentos... lo cual es su fortaleza y su debilidad... algunos 
campos como serie y folios puedo ver la manera de validarlo, pero 
ocultar tantos campos, se va a volver algo engorroso, no mantenible...  
es como tener una pantalla reutilizable, donde tienes todas las opciones 
que ocupas en una sola pantalla, pero que le cambies toda la 
funcionalidad...

Saludos.
JC.

**Comment by FraQue0693** [comment]
Inicio de solucion

**Comment by FraQue0693** [comment]
Ya se encontro la solucion.

Dando los ultimos detalles, hoy 29/Julio/2014 termino.

**Comment by FraQue0693** [comment]
Es similar a la #257 , solo es recodificar el check de "PAGADA"

**Comment by FraQue0693** [comment]
LISTO
