### ISSUE TITLE
Carta porte 1 - hijo del refactoring 1, incluir el catálogo de claves de permiso, desplegando la descripción en transportes.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2000]
Chiaaa, ya estaba mencionado en el otro, para que generar mas contaminación?

En el catálogo de transportes, incluir el catálogo de claves de permiso del SAT. 
Con ello, estaremos evitando que el usuario se equivoque al teclear dicha clave.

**Comment by RigoFlores** [comment]
y este apá?

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
oye, pero no despliega la descripción, faltaría agregarla...
las claves solitas no dicen nada...

**Comment by RigoFlores** [comment]
3 days ago, comenté que falta la descripción.

**Comment by jccastillo0007** [comment]
que pues, primero no pides la descripción, y luego no actualizas los labels del ticket, no soy adivino

**Comment by RigoFlores** [comment]
Si, debió ser la descripción, mas que la clave... 
Lo que pasa es que ellos capturaban manualmente la clave, y me fui por ahí.
Pero realmente para que les ayude, en lugar de la clave, debe desplegar las descripciones.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
no seas cabrón, acomódalo para que no se vea tan ancho....
yo diría dejar en un solo renglón ese dato, pero además si se puede que en ese particular el font sea mas chirris, mejor aún.

**Comment by RigoFlores** [comment]
si, con bajar el número de permiso ya se vería mejor.
El tipo de vehículo es mas ancho, así que no afectará.

Y dar un poco de espacio entre los datos de aseguradora y póliza, con los remolques. Están pegados. Darles la misma distancia de toda la pantalla entre los renglones

**Comment by jccastillo0007** [comment]
listo
