### ISSUE TITLE
En los totales redondear y no truncar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2001]
Estoy revisando un problema con un cliente, donde me doy cuenta que el total de un CFDI = importe + traslados - retenciones, lo está truncando.

Aparentemente, el cálculo del total lo hace con todos los decimales disponibles, pero al final lo trunca... en lugar de redondearlo... y eso causa ciertos problemas.

los totales a nivel global: subtotal, traslados, retenciones, total.. que se calculan a partir de los conceptos con hasta 6 decimales, yo creo que todos se deben redondear...para evitar problemas

**Comment by jccastillo0007** [comment]
no truncamos los totales, siempre se redondean, a penas lo ibamos hacer en complemento de pago, pero ya vimos que no era ese el problema

**Comment by RigoFlores** [comment]
no, es al contrario... en el complemento de pago lo redondeaba y se pedía truncar.
Ya ni sé cuál era el cliente y el problema, chiaaaa... esto tiene desde el 11 de julio.
Yo creo que se resolvió de otra manera, pero tendremos que estar muy pendientes de lo que vaya ocurriendo con este tema. Los redondeos en algún momento, pueden provocar que se "suba" la cifra, y entonces ya no cuadre, pero ya veremos algún caso particular en su momento.
