### ISSUE TITLE
Carta Porte - Mercancías, si ya tiene datos capturados de material peligroso, no puedo eliminarlos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2002]
Si una mercancía originalmente se capturó como material peligroso, y luego se quiere modificar eliminando toda la info de material peligroso: clave material, clave de embalaje, descripción embalaje. 
Aunque en apariencia lo elimina en pantalla, al momento de dar guardar, no permite ya que indica :

Al capturar la clave de embalaje, se requiere la clave de material peligroso

**Comment by jccastillo0007** [comment]
fixed
