### ISSUE TITLE
Carta Porte - mercancías... si se captura el valor unitario a nivel de mercancía, reflejarlo en el XML de acuerdo a la cantidad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2003]
Básicamente se trata lo mismo del peso en KG.
SI la mercancía pesa 10KG y son 10 piezas el peso en KG será 100kg

lo mismo pasa con el valor (en el catálogo de mercancías).. si el valor son 150 y la cantidad son 10, entonces se reporta como ValorMercancia, valor x cantidad = 1500.00.

Bueno, pero para ello debieron capturar valor y moneda en el catálogo de mercancías. Si no lo capturaron, pues entonces no aplica lo aquí mencionado.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
eeeesssoooo tilín...!!!
