### ISSUE TITLE
Carta Porte - captura de complemento (addenda), actualizar los datos de la mercancía, cuando ésta cambia.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2004]
En la pantalla de captura del complemento (addenda).
Si elijo la mercancía1, con peso 10 y cantidad 5, entonces envía al XML PesoEnKg = 50. Muy bien hasta ahí.

Si el usuario se equivocó de mercancía, y la cambia, ahora elige la mercancía2 con peso = 20, entonces lo que sucede es que cambia la mercancía, y también cambia el peso (lo pone a 20), pero siendo la cantidad 5, el peso debió ser 100 y no 20. 

Es decir al cambio de mercancía, debe actualizar el PesoEnKg, tomando en cuenta la cantidad capturada en ese momento. Si no existe cantidad capturada, entonces si muestra el peso (unitario, capturado en el catálogo de mercancías).

En todo momento, PesoEnKg = peso  x cantidad.

Por si acaso, lo mismo debe actualizarse en caso que se tenga capturado

**Comment by jccastillo0007** [comment]
fixed
