### ISSUE TITLE
Carta Porte - Misceláneos filtrar por tipo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2005]
Cuando entras a la pantalla de misceláneos, por omisión tiene elegido origen.

Para hacerlo mas funcional:
a) Subir la sección de filtros, hasta arriba.
b) Dejar por default origen.
c) Si el usuario consulta algo, en ese momento solo listará origen. Es decir, ese filtro que puede ser uno o varios simultáneos, servirá para que en las consultas solo se muestren los registros que corresponda. El usuario podrá agregar o quitar filtros en cualquier momento. 
d) En el caso de darle agregar registro, entonces el filtro desaparece, forzando al usuario a definir qué tipo de registro estará guardando.

**Comment by jccastillo0007** [comment]
Peque;o detalle, esa sección que le llamas filtros, no son filtros, solo son una categoría para los misceláneos que se van a revisar o agregar... no tiene funcionalidad de filtros

**Comment by RigoFlores** [comment]
Si, justo eso.
Esa parte de la captura hacerla doble función. 

Cuando consultas, utilizarlo como filtro, ya que así podemos consultar los orígenes/destinos, operadores, transportes. 

Por otro lado, al dar de alta o modificar un registro, pues indicar cuál es el tipo de registro.

Si eso no es posible, pues entonces agregar un filtro para elegir : origen y/o destino (puede ser origen, destino o ambos), operador, transportes.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Me está permitiendo guardar un registro, sin filtro. Su ID fue BORRAME. Habrá quedado en el limbo, porque no hay forma de consultarlo.
Es decir, en el caso de un nuevo registro, el filtro (que en este caso es el tipo), es obligatorio. Si no se captura, NO se puede permitir guardar.

De preferencia, mantener el último filtro capturado, en particular en consultas.
Por ejemplo, quiero buscar algo en un operador, pero no recuerdo en cuál... elijo el filtro operador, y selecciono el primer operador de la lista y veo que ahí no está lo que busco. Le doy cancelar para buscar otro. Pero tengo que volver  capturar el filtro, ya que lo borró. Tons sería bueno que mantenga el último filtro en memoria cuando se están haciendo consultas.

Borrar el filtro, solo cuando se trata de un nuevo registro.

**Comment by jccastillo0007** [comment]
el issue reportado ya esta arreglado.

la preferencia esta rechazada, hasta que cambiemos de framework en el UI

**Comment by RigoFlores** [comment]
pero hay un error. Está permitiendo guardar sin haber definido el tipo de registro... o cómo??

**Comment by jccastillo0007** [comment]
chiaaaa: el issue reportado ya esta arreglado.

**Comment by RigoFlores** [comment]
pero no era issue, era mejora. Y dentro de la mejora, tiene un error. 
Permite guardar sin haber definido el tipo de registro, y con ello se queda en el limbo ese registro, y el usuario jamás se da cuenta.

**Comment by jccastillo0007** [comment]
chiaaaa: el issue reportado ya esta arreglado.
