### ISSUE TITLE
Carta Porte Misceláneos, mejoras varias rumbo al ccp mas gaver 3,

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2006]
Cuando se le da agregar o editar un registro, dependiendo del filtro seleccionado (se debió atender el ticket 2005), se podrán editar o agregar ciertos registros:

a) Para origen y destino, solo los datos correspondientes a domicilio. Los demás campos quedan deshabilitados.
b) Para operador, además de (a), se activa el número de licencia.
c) Solo en el caso de propietario o arrendatario se activarán los campos además de (a, OJO el b no aplica aquí), el de parte transporte, No Registro y residencia fiscal. 
d) Cuando se consulta, se podrán elegir todos los filtros.
e) Cuando se le da agregar un nuevo registro, esté podrá ser: origen y/o destino, operador, arrendatario, propietario. Así, mutuamente excluyentes. Es decir, un mismo registro no podrá ser origen y operador simultáneamente. Un registro podrá ser origen y/o destino (único caso, donde puede ser 2 tipos un mismo registro), operador, propietario, arrendatario. únicamente.
f) Eliminar de la pantalla del catálogo y de la addenda, el campo notificado. Ese no aplica para autotransporte. Así que lo dejamos fuera de la captura.

**Comment by jccastillo0007** [comment]
El punto d, quedo atendido en el ticket 2005, chiaaa

**Comment by jccastillo0007** [comment]
El punto e, no es posible, ya que se ha solicitado que en los filtros se puedan seleccionar varias opciones, en este caso, cuando están editando o agregando, se usa el mismo componente, chiaaa

**Comment by jccastillo0007** [comment]
El punto f, ya esta listo

**Comment by RigoFlores** [comment]
Puntos pendientes:

a) Para origen y destino, solo los datos correspondientes a domicilio. Los demás campos quedan deshabilitados.
b) Para operador, además de (a), se activa el número de licencia.
c) Solo en el caso de propietario o arrendatario se activarán los campos además de (a, OJO el b no aplica aquí), el de parte transporte, No Registro y residencia fiscal.

**Comment by RigoFlores** [comment]
Es que el filtro no tiene mucho sentido cuando le das agregar un nuevo registro. Ahí no aplica un filtro.
Ahí es propiamente un dato de captura. 
Se lo podemos dejar al usuario, pero ya veremos si no causa muchos problemas.

**Comment by jccastillo0007** [comment]
listos a, b y c

**Comment by RigoFlores** [comment]
Ahorita que lo chequé, se me pasó algo. Sorry.

En caso de operador, arrendatario y propietario.
Si capturan RFC, entonces número de registro y residencia fiscal, se inhiben. (recuerda que estamos tratando de evitar errores humanos de captura).
Si NO capturan RFC, entonces registro y residencia fiscal se habilitan. Lo que sería lo mismo si RFC está vacío, se activan. SI RFC está capturado, se inhiben.

Registro y residencia fiscal, se ocupan para el escenario de que la figura transporte sea extranjero, es decir que no cuentan con rfc nacional. En este caso RFC queda vacío y se llenan registro y residencia fiscal.

**Comment by jccastillo0007** [comment]
ya no entendí, en el caso de operador, registro y residencia fiscal no están habilitados..

**Comment by jccastillo0007** [comment]
listo para propietario y arrendatario

**Comment by RigoFlores** [comment]
Ya volví a revisar el estándar... para operador, propietario y arrendatario. Pueden capturar RFC o en su lugar número de registro y residencia fiscal. Es que para los 3 casos, o es nacional (RFC) o es extranjero (registro y residencia fiscal). Por ello es que son mutuamente excluyentes.
Si capturan RFC, se inhibe (y borra en caso de tener datos) el registro y al residencia.
Si RFC no está capturado, se podría capturar registro y residencia fiscal. Es decir se habilitan.

Eso para operador, arrendatario y propietario.
Pero hay otra cosa, está permitiendo guardar un registro sin RFC, sin registro ni residencia. Lo que tiene que validar para esos 3 tipos al momento de guardar, además de las validaciones que ya tiene, es que o capturan RFC o capturan registro/residencia.

**Comment by jccastillo0007** [comment]
chiaaa, listo
