### ISSUE TITLE
Validaciones de misceláneo, dependiendo del tipo de registro.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2007]
Una vez atendido ticket 2005 y 2006, vienen las validaciones según el tipo de registro:

a) Para origen y destino, datos obligados: tipo, rfc, nombre, ID, tipo. Domicilio, únicamente estado, país y CP. 
Datos opcionales, el resto de datos del domicilio.

b) Para operador, los datos obligados son: rfc, nombre, ID, # licencia, tipo.
Datos opcionales: Domicilio pero no estaría mal inhibirlo, realmente no es necesario, se podría inhibir..

c) Para propietario o arrendatario, datos obligados: ID, nombre, RFC, parte transporte, Tipo
Datos opcionales: Domicilio.

Los datos que no se mencionen como obligatorios u opcionales, para los 4 tipos de registro (origen/destino, operador, propietario, arrendatario), se deben inhibir.

**Comment by jccastillo0007** [comment]
listo... 

verifica las validaciones de campos con lo que se pidio en los tickets 2005 y 2006 , ya que hay contradicciones respecto al domicilio

**Comment by RigoFlores** [comment]
Punta (a) OK.

b y c, el domicilio es opcional. Lo pide a huevo para operador y para propietario/arrendatario lo inhibe.

Adicionalmente, para operador, propietario y arrendatario existe una condición excluyente: Si capturan RFC, entonces número de registro y residencia fiscal, se inhiben. SI no capturan RFC, deben capturar los datos ambos, registro y residencia fiscal.

**Comment by jccastillo0007** [comment]
en el ticket 2006, pediste que el domicilio si se habilite para operador, y entiendo que del domicilio los datos de pais, estado y código postal son obligatorios.

Cómo queda para operador, propietario y arrendatario, agrega todas las condiciones que aplican, ya sin fijarse en los otros tickets, y sin ahorrarse palabras, hay que escribir todo para evitar confusiones, ya que la manera que manejas los tickets es muy confuso

**Comment by jccastillo0007** [comment]
Esto "Adicionalmente, para operador, propietario y arrendatario existe una condición excluyente: Si capturan RFC, entonces número de registro y residencia fiscal, se inhiben. SI no capturan RFC, deben capturar los datos ambos, registro y residencia fiscal."

lo pediste en otro ticket, chiaaaa

**Comment by RigoFlores** [comment]
Si, está medio revuelto todo. Y algunas cosas, las tengo que estar checando con los PACs.
Esto es por haber puesto en una sola pantalla 5 catálogos. La base es muy parecida entre ellos, pero bueno... por ello las confusiones.

Quieres que ponga las validaciones en una tabla, para que queden mas claras...???

**Comment by RigoFlores** [comment]
De lo que falta respecto al documento de excel. Le estoy dando agregar un registro nuevo. Es decir, para edición no sé como funcione, jeje.

Para origen y destino, el RFC será excluyente con registro y residencia fiscal.

Para operador, arrendatario y propietario, el domicilio es opcional. Pero si capturan domicilio, al menos deberá ser país, estado y cp.

El operador no lleva parte transporte, se debe inhibir.

**Comment by RigoFlores** [comment]
Jejeje. Este punto, no está:
Para origen y destino, el RFC será excluyente con registro y residencia fiscal. (si capturas RFC se inhiben los otros dos; si no hay RFC capturado, están habilitados los otros dos para captura; si capturas los otros 2, el RFC queda inhibido. Chiaaaaa)

De este otro punto:
Para operador, arrendatario y propietario, el domicilio es opcional. Pero si capturan domicilio, al menos deberá ser país, estado y cp.  (ESTÁ JALANDO BIEN PARA OPERADOR, NO ASÍ PARA PROPIETARIO Y ARRENDATARIO).

Este tercer punto, tampoco está  listo:
El operador no lleva parte transporte, se debe inhibir.

**Comment by RigoFlores** [comment]
Resumen. Ninguno de los 3 puntos que estaban faltando están atendidos.

**Comment by RigoFlores** [comment]
Y algo raro está haciendo ahora mismo, con destino y origen extranjero, entonces ya que se entregue esta corrección se validará.
Le está poniendo en "automático" el número de registro y la residencia fiscal.
Pero bueno, nos esperamos a la corrección de este issue.

**Comment by jccastillo0007** [comment]
este caso ya esta listo: El operador no lleva parte transporte, se debe inhibir.

**Comment by jccastillo0007** [comment]
para arrendatario y propietario , se había pedido inhibir el domicilio, lo dejamos asi?

**Comment by RigoFlores** [comment]
OK, lo dejaremos inhibido para propietario y arrendatario, aún conociendo que si se podría capturar. 
Ojalá que mas adelante, no se nos presente un problema por ello.

**Comment by RigoFlores** [comment]
tons faltaría este, que no?


_**Para origen y destino, el RFC será excluyente con registro y residencia fiscal. (si capturas RFC se inhiben los otros dos; si no hay RFC capturado, están habilitados los otros dos para captura; si capturas los otros 2, el RFC queda inhibido. Chiaaaaa)**_

**Comment by jccastillo0007** [comment]
listo
