### ISSUE TITLE
Homologar el uso del número de decimales a nivel concepto (incluyendo impuestos trasladados y retenidos)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2008]
Ahora mismo, estamos reportando el importe ( = cantidad x precio unitario) con 2 decimales (aparentemente redondea a 2 decimales, aunque rellena de 0s hasta los 6 decimales).

La base del impuesto a nivel concepto generalmente es igual al importe (a menos que haya descuentos, o que los impuestos no apliquen al 100% del importe, entonces la base sería distinta). La base si se reporta con todos los decimales. Al sumar las bases de los conceptos dentro de una factura, esta sumatoria puede diferir de la suma de importes, y ahí es donde marca errores de las cantidades que no coinciden.

Mi propuesta es que todo se maneje a 6 decimales por omisión, pero que el usuario pudiera elegir cuántos decimales quiere manejar.  Por ejemplo en la ventana de agregar producto, ahí podría decir manejar 6,5,4,3,2 decimales. 

Que realmente la spec del SAT, indica que es hasta 6 decimales todo a nivel concepto.

**Comment by jccastillo0007** [comment]
listo, checale.... 

a nivel impuestos generales de la factura, se están manejando a 2 decimales, ahi no le movi.... se queda igual o que petch?

**Comment by RigoFlores** [comment]
ok, por lo pronto, creo que está bien así como quedó.
Pero se están presentando diversas problemáticas, que bueno, por lo pronto, creo que no tiene mas que ver con este issue.
