### ISSUE TITLE
No está leyendo correctamente la tasa del IVA en un documento de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2009]
Te mandé un correo... esto está pasando en producción.

[A7145_SIM020420L55_CIN0707314P9_26May2022_112740.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/9115596/A7145_SIM020420L55_CIN0707314P9_26May2022_112740.xml.txt)

Está raro, este complemento de pago, involucra 5 facturas, todas ellas con IVA de 8%, ya que se emitió en la frontera.
Pero de las 5, una de ellas la reporta como tasa 0, y se arma el desmadre, ya que el monto de IVA si lo reporta correctamente, y pues ahí no coinciden las cantidades de IVA reprotados.

Te anexo el XML de pago que generó donde está el error, y también la factura que “lee” chueca.

[xmlTasa8como0.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/9115595/xmlTasa8como0.xml.txt)

**Comment by jccastillo0007** [comment]
ya corregí la tasa en la base de datos, lo puedes intentar?

**Comment by RigoFlores** [comment]
si lo intentamos, y marcó error... sigue colocando el IVA con tasa 0, cuando debe ser tasa 8

                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="7145" IdDocumento="6ed507f7-ba71-49c5-affd-8a6a59c6b8f8" ImpPagado="2687.04" ImpSaldoAnt="2687.04" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="1" ObjetoImpDR="02" Serie="A">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="2488.000000" ImporteDR="199.040000" ImpuestoDR="002" TasaOCuotaDR="0.000000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>

**Comment by RigoFlores** [comment]
se hecho en el primer comentario de este ticket, aparecen los datos de captura del complemento, por si tu gustas validarlo.

**Comment by RigoFlores** [comment]
ahorita lo volví a intentar, yo personalmente, ya que antes lo hizo el cliente, pero no... sigue igual.
En la factura 7145, el IVA lo está reportando con tasa 0, en lugar de tasa 8

                pago20:DoctoRelacionado>
                pago20:DoctoRelacionado EquivalenciaDR="1" Folio="7145" IdDocumento="6ed507f7-ba71-49c5-affd-8a6a59c6b8f8" ImpPagado="2687.04" ImpSaldoAnt="2687.04" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="1" ObjetoImpDR="02" Serie="A">
                    pago20:ImpuestosDR>
                        pago20:TrasladosDR>
                            pago20:TrasladoDR BaseDR="2488.000000" ImporteDR="199.040000" ImpuestoDR="002" **TasaOCuotaDR="0.000000"** TipoFactorDR="Tasa"/>
                        pago20:TrasladosDR>
                    pago20:ImpuestosDR>
                pago20:DoctoRelacionado>

**Comment by jccastillo0007** [comment]
listo, lo puedes volver a correr, creo que actualicé una que no era jojojo

**Comment by RigoFlores** [comment]
pues desde entonces el cliente no responde.
Hoy le volví a pedir que nos diga si ya lo hizo o nó...

Si no responde, lo tendré que hacer yo, pero la verdad es mejor que lo haga el mismo cliente.

**Comment by RigoFlores** [comment]
pues ya generó el documento de pago.
Eso implica que para propósitos del cliente, ya es resolvió.
De nuestra parte, quedará abierto algo que no sabemos como se produjo o no sé si ya tuviste chance de revisar lo que pasó?
