### ISSUE TITLE
CAMBIAR ETIQUETA DE FACTURAS POR VENTAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#201]
ESA PANTALLA YA NO ES DE FACTURAS SOLAMENTE, AHORA SON VENTAS.

**Comment by RigoFlores** [comment]
BUENO, REALMENTE EL MENÚ DE VENTAS DEBE INCLUIR:
CATÁLOGO DE CLIENTES, DE PRODUCTOS, COTIZACIÓN, PEDIDO, REMISIÓN, FACTURAS, Y CONSULTAS.

**Comment by jccastillo0007** [comment]
Oye... antes de seguir con estos cambios... necesito cerrar esta version 
y liberarla... porque me esta causando mucho retrabajo.

Esta bien que levantes estas fichas para que se atiendan.. pero lo 
primero ahorita o mas bien lo que urge es que este funcional y haga las 
cosas bien...  para poderlo liberar.

Aun seguimos con el defecto de que elimina los impuestos al editar la 
factura... se esta poniendo muy romantico ese issue... pero una vez 
resuelto eso, buscaria ya liberarlo.

Saludos.
JC.
