### ISSUE TITLE
Conector 4.0, no está procesando correctamente la base IEPS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2010]
te mandé un correo..

Este archivo marca error cuando lo procesa el conector.

No está respetando la base del IESP (impuesto 003), ya que en el archivo se indica 435.60 como base, pero en el XML envía 15681.60
Y acabo de darme cuenta que esa base de IEPS que envía al XML, realmente es el dato del archivo y la multiplica por la cantidad, en este caso 36 (435.60 x 36).

Vamos, no está respetando lo que se reporta en el archivo para la base del IEPS. Lo del IVA si lo respeta.

    <cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="626"/>
    <cfdi:Receptor Rfc="MASO451221PM4" Nombre="MARIA OLIVIA MARTINEZ SAGAZ" DomicilioFiscalReceptor="80290" RegimenFiscalReceptor="626" UsoCFDI="G03"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="50202200" NoIdentificacion="7501032485016" Cantidad="36.00" ClaveUnidad="XBX" Unidad="CAJA" Descripcion="CARIBE COOLER D
URAZNO 300 ML" ValorUnitario="12.100000" Importe="435.60" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="435.600000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="106.640000"/>
                    <cfdi:Traslado Base="15681.600000" Impuesto="003" TipoFactor="Tasa" TasaOCuota="0.530000" Importe="230.870000"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="337.51">
        <cfdi:Traslados>
            <cfdi:Traslado Base="15681.60" Impuesto="003" TipoFactor="Tasa" TasaOCuota="0.530000" Importe="230.87"/>
            <cfdi:Traslado Base="435.60" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="106.64"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

[lasBarricasIEPS.txt](https://github.com/jccastillo0007/eFacturaT/files/9124187/lasBarricasIEPS.txt)

**Comment by RigoFlores** [comment]
Este problema lo tenemos que entregar a la brevedad posible, ya que es para lo del nuevo cliente del conector. El otro "figueacero". Para que lo vayas ubicando se llama LAS BARRICAS.

No podemos timbrar, ya que la base del IEPS  en lugar de reportarlo como viene en el archivo de texto, lo calcula y lo envía al XML = base (del archivo) x cantidad.

En teoría con este archivo ya debería jalar, claro que no lo puedo validar. Pero ya tiene todo para que jale.

[lasBarricasIEPS_CantidadMayorA1.txt](https://github.com/jccastillo0007/eFacturaT/files/9133943/lasBarricasIEPS_CantidadMayorA1.txt)

**Comment by jccastillo0007** [comment]
fixed
