### ISSUE TITLE
Conector 4.0 - complemento de pago, no está tomando en cuenta el primer pago, en una factura.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2011]
Se trata de este cliente: MCL0802254N3 (es de conector)
Hay que darlo de alta en web, ya que es de los clientes iniciales y no se creaba su cuenta en es entonces. Creo que era el quiyenereitor de escritorio, jeje.

Bueno, el punto es que se intenta timbrar un pago de 5 facturas, pero una de ellas, ya tenía un pago asociado. Ese pago se registró en cfdi 3.3, complemento de pago 1.2.
Pero ahora que se intentó generar el pago, incluyendo la liquidación (pago 2) de esa factura, no jaló. NO tomó en cuenta el primer pago y por ello no coinciden las cantidades.

Aquí un archivo zip, con la factura, una imagen de los abonos asociados a las facturas, el log de facturat y el archivo de texto que se envió. Falta la bd, ya la solicité.

[ticket2010.zip.TXT](https://github.com/jccastillo0007/eFacturaT/files/9124515/ticket2010.zip.TXT)

**Comment by jccastillo0007** [comment]
wey, la factura que me mandaste en el zip, no tiene nada que ver con este reporte chiaaaaa

**Comment by jccastillo0007** [comment]
ya subí la versión 12.0.21 y di de alta el cliente. MCL0802254N3.

**Comment by RigoFlores** [comment]
el cliente ya probó, y dice que sigue igual.
Voy a cachar el log de esa prueba y veo si es lo mismo, o ya es otro problema.

**Comment by RigoFlores** [comment]
si, al parecer ya es otro el problema, lo estoy checando con el PAC.
Lo mantendré abierto, para no perderme con este ticket.
