### ISSUE TITLE
Conector 4.0 - Documento de pago, no está calculando correctamente los importeDR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2012]
Finkok dice que tenemos una cierta variación, y por eso lo rechaza. (Fhoy igual lo rechazó).

Aquí te dejo el XML que se generó desde el conector.
En un excel pongo únicamente las baseDR y los importesDR que se reportan al XML (en amarillo). 
En ese mismo excel, pongo en verde el cálculo de tomar la base y multiplicarlo por la tasa del iva, en este caso 0.08. Y también una columna indicando al diferencia. Pues es muy leve, pero el PAC (ambos) lo rechazan. 

Hay que revisar el cálculo del importeDR, cómo sale?

[fixSabadoSergio.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/9135963/fixSabadoSergio.xml.txt)
[fixSabadoSergio.xlsx.txt](https://github.com/jccastillo0007/eFacturaT/files/9135964/fixSabadoSergio.xlsx.txt)

**Comment by jccastillo0007** [comment]
necesito mas bien, los archivos para reproducirlo y arreglarlo

**Comment by jccastillo0007** [comment]
la base y el importeDR se acumulan de los productos reportados, no se calculan, probablemente por ahi viene el error, pero hay que tener todos los datos para poder analizarlo y reproducirlo

**Comment by RigoFlores** [comment]
ok, estoy en eso...

**Comment by RigoFlores** [comment]
Según yo, el asunto, es el mismo de los decimales. Si la baseDR de los impuestos se reporta a 6 decimales, entonces el importeDR queda con un rango muy limitado. Y en algunos casos de este caso de la vida rial, se está reportando redondeado a 2 decimales. Son 11 facturas involucradas.

Ese es el pedo.

Aquí tienes la BD, y el archivo de texto del pago. También la llave de prueba del conector.

[facturat_dbConector.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/9245699/facturat_dbConector.zip.txt)
[Pago_327.TXT](https://github.com/jccastillo0007/eFacturaT/files/9245700/Pago_327.TXT)

[facturaT_IIA040805DZ4.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/9245705/facturaT_IIA040805DZ4.cfdi.txt)

**Comment by RigoFlores** [comment]
alguna avance de este tema?
Me acaban de volver a preguntar...

**Comment by jccastillo0007** [comment]
fixed.

El secreto fue, no pelar los importesDR de los productos, mas bien, se acumula la base, y el importeDR se calcula al final.

**Comment by RigoFlores** [comment]
la prueba de fuego no ha pasado.
Con las barricas, veremos como calcula las bases, ya que ellos manejan 2 impuestos trasladados. Ahí si estará cabrón.

**Comment by RigoFlores** [comment]
no está bien, el uso del CFDI lo envía incorrecto.
Para pago debe ser CP01.

**Comment by jccastillo0007** [comment]
fixed
