### ISSUE TITLE
Conector 4.0 - no está enviando correctamente el datoextrapro2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2013]
ya lo ví en la consola y no está enviando el dato que se incluye en el archivo.
Lo raro es que el dato extra pro1 y pro3 si lo envía bien.
Este es el archivo:

[lasBarricasIEPS_CantidadMayorA1.txt](https://github.com/jccastillo0007/eFacturaT/files/9136644/lasBarricasIEPS_CantidadMayorA1.txt)

y esto se alcanza a ver en la consola...

2022-07-18 20:05:24,216 DEBUG [pool-2-thread-1] (FacturaTiCreator.java:314) - com.cfd.shared.utils.jasper.JasperProductBean@f0cd6d[objImp=02,unidad=CAJA,idPro
ducto=7501032485016,descripcion=CARIBE COOLER DURAZNO      300 ML,valorUnitario=12.707264,importe=457.461538,cantidad=36.00,numeroItem=1,descripcionComplement
aria=,numeroAduana=,cuentaPredial=,datoExtraPro1=12.0000,**_datoExtraPro2=432.0000_**,datoExtraPro3=773.1099,datoExtraPro4=,datoExtraPro5=,datoExtraPro6=,datoExtraP
ro7=,datoExtraPro8=,datoExtraPro9=,datoExtraPro10=,precioUCD=12.707264,importeCD=457.461538,productoSAT=50202200,unidadSAT=XBX,descuentoPro=0.00,baseIVA=457.4
61538,impuestoIVA=002,tipoFactorIVA=Tasa,tasaCuotaIVA=16.0000,montoIVA=73.1938,baseIEPS=457.4615,impuestoIEPS=003,tipoFactorIEPS=Tasa,tasaCuotaIEPS=53.0000,mo
ntoIEPS=242.4546,baseRetIVA=,impuestoRetIVA=,tipoFactorRetIVA=,tasaCuotaRetIVA=,montoRetIVA=,baseISR=,impuestoISR=,tipoFactorISR=,tasaCuotaISR=,montoISR=,objI
mpl=01]

**Comment by jccastillo0007** [comment]
se tiene esta condición

		if (!StringUtils.isEmpty(datoExtraPro1) && emisor.compareToIgnoreCase("CME211202K45") != 0) {
			datoExtraPro2 = (datoExtraPro1 * cantidad);
		}

una de esas condiciones que pediste , pensando que a nadie le iba a afectar... 

se la quito ?

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
La pregunta es, porque no aplicó la condición?
Ese RFC es de la empresa de tus parientes, COVEMAQ DE MEXICO.
No sé porqué se pidió esa condición, no lo recuerdo.

**Comment by jccastillo0007** [comment]
si aplico la condición... por eso modifico el valor del dato extra prod2, o como asi?

chiaaa

**Comment by RigoFlores** [comment]
no la condición solo debería aplicar cuando el emisor sea el rfc de covemaq???
