### ISSUE TITLE
Conector 4.0 - manejar a 6 decimales, importes a nivel de concepto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2014]
Precio Unitario, Importe, Descuento.
En impuestos trasladados: Base e Importe.

A nivel general: Sumar todos los impuestos trasladados o retenidos, redondearlos a 2 decimales y así reportarlos.

**Comment by RigoFlores** [comment]
Ahora mismo, por ejemplo en los traslados a nivel concepto...
Se realiza el cálculo (base por la tasa), pero el resultado se reporta a 2 decimales, y eso provoca problemas, ya que si el redondeo va hacia arriba, ya se salió de los límites superior e inferior.

**Comment by RigoFlores** [comment]
Incorrecto:
 
Base= 64.81000
Traslados 8% IVA: 5.19  (lo redondea, incrementan su valor y ahí el SAT no acepta)

Correcto:
Base= 64.81000
Traslados 8% IVA: 5.1848

**Comment by jccastillo0007** [comment]
me puedes pasar un txt donde pueda reproducir el problema de los cálculos... no encontré donde se puede estar haciendo el redondeo...

**Comment by RigoFlores** [comment]
Ya retomé a detalle el problema aquí. Este issue nos reportaron cuando había 4 issues parecidos simultáneamente abiertos. Realmente había confusión entre todos.

El asunto es que muchos ERP's manejan sus importes a 2 decimales.
Con ello, el IVA a nivel producto lo reportan a 2 decimales.
En la 4.0, aparece el atributo base dentro del nodo impuestos a nivel concepto; y es justamente la base para el cálculo del IVA, y aquí es donde truena. Porque igualmente manejan la base a 2 decimales, y luego el IVA también a 2 decimales, y en muchos casos no pasa la validación.

El claro ejemplo es OPTIBELT, pero ese problema está en todos los ERP's. O ellos lo modifican o nosotros hacemos algo para que se procesen los archivos.
Y hacer algo para que se procesen los archivos, es justamente reportar los impuestos a 4 o 6 decimales, a nivel concepto. 

Algo medio raro, es que los archivos que aquí de comparto, se generaron en versión 4.0, me dice el cliente. Tengo mas archivos, pero con que proceses el primero se dará el problema.
Yo hice los cálculos en excel, a 4 decimales, y si difiere un poco.... como lo indico al inicio de este ticket.

[ERROR_A_12782.TXT](https://github.com/jccastillo0007/eFacturaT/files/9213414/ERROR_A_12782.TXT)

[ERROR_A_12940.TXT](https://github.com/jccastillo0007/eFacturaT/files/9213417/ERROR_A_12940.TXT)

**Comment by jccastillo0007** [comment]
oye, revisando el código, no se hace ningún redondeo... se reporta tal cual viene en el archivo....
si estas pidiendo que se hagan cálculos y se cambien cifras, puedes estar abriendo la caja de pandora... 

yo creo que lo deben ajustar de su lado

**Comment by RigoFlores** [comment]
No hay delito que perseguir.

ok, para clarificar, en resumen:

Archivos de texto plano que si procesaba en la 3.3, ahora ya no los procesa en la 4.0
Entonces, los desarrolladores deben manejar sus IVAs a nivel concepto a 4 decimales (por lo menos).
Con ello, timbrará sin mayor problema.

eso es todo.
Para optibelt, hay que platicar con ellos.
