### ISSUE TITLE
Para este RFC TRA8402225G0, en modalidad de conector. Descontar los folios por cada XML cancelado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2015]
Inicialmente arrancaremos con cancelaciones con motivo 02 sin relación.
Eso quiere decir, que todo XML timbrado que pongamos en la carpeta conector, será cancelado.
Por cada XML que se envíe a cancelar, se debe descontar un folio para este RFC emisor.

Aquí será importante conocer el status de la cancelación. No sé, de alguna manera. Hoy es un archivo de texto por cada XML que no cancele. No se podrá guardar un status o algo similar por cada XML no cancelado para su posterior consulta?

**Comment by RigoFlores** [comment]
Hice una prueba básica, y resulta que tiene XML de la 3.3
Pero también serán eventualmente de la 4.0

Entonces, en este caso (y en general para todos), la cancelación debe soportar XML's de la 3.3. y 4.0

**Comment by jccastillo0007** [comment]
serviría un reporte mensual  en formato csv con el estatus de cancelación de todas las facturas, asi ellos pueden filtrar y ver que archivos no se cancelaron... de igual forma, podemos mover los xml no cancelados a alguna carpeta para que ellos vean cuales son, y puedan reintentarlos... cómo ves ?

**Comment by jccastillo0007** [comment]
subí una versión que en teoría ya soporta cfdi 3.3, el zip se llama ahora Cancelator e incrementé la versión para iniciar con 13.0.1

Hay que preparar cfdi de pruebas, no les puedes pedir unos 100, para hacer pruebas directamente en prod? y que sean de diferentes meses, para ver como generar los reportes

**Comment by RigoFlores** [comment]
Primero lo primero, la cancelación.
NO jala porque esos XML vienen con folio alfanúmerico y yo croe que nosotros solo soportamos números.
Por otro lado, poner en una carpeta aparte los que no pudo cancelar, también ya lo había pensado. Eso es algo simple, y muy informativo.

El reporte puede ser en rango de fechas de emisión de la factura, o en rango de fechas de la cancelación

**Comment by RigoFlores** [comment]
ese es el mensaje en la consola...

<img width="784" alt="folio" src="https://user-images.githubusercontent.com/2912775/180694843-010b4ea8-8d9b-45cb-9bb6-4b93ede02fc1.PNG">

**Comment by jccastillo0007** [comment]
subi una versión a PRU de efacturat, en ella se incluye:
guardar un registro en la tabla CancelCFDiDetail, donde se almacena cada request de cancelación, ahi se guardará el estatus de la cancelación... Pregunta: Nos interesa saber si el cfdi cancelado es 3.3 o 4.0 ?

Una vez que se cancela, si es exitoso, se descuenta un folio de la cuenta del cliente... ojo, aqui hay un peque;o riesgo... ya que si el cliente se queda sin folios, de todos modos ya se canceló el cfdi... esta complicado hacerlo antes de....

**Comment by jccastillo0007** [comment]
listo, ya esta liberado en el servidor de gepp.

Hay que checar la tabla CancelCFDiDetail y los folios para ver que se estén descontando, conste que no se probó en pru

**Comment by RigoFlores** [comment]
Después que ya se envia la petición de cancelación, marca error en la consola, igualmente con el tema del folio alfanumérico.
Este es el mensaje:

2022-07-27 11:59:34,516 DEBUG [pool-2-thread-1] (Connector2Cancel.java:125) - Propety received : STATUS_PAC value : Cancelaci├│n enviada al SAT satisfactoriam
ente
2022-07-27 11:59:34,527 ERROR [pool-2-thread-1] (ModelService.java:73) - java.lang.NumberFormatException: For input string: "LZC1032446"
java.lang.NumberFormatException: For input string: "LZC1032446"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
        at java.lang.Long.parseLong(Long.java:410)


Adicionalmente, en el acuse de cancelación, no está enviando el dato del motivo de cancelación, ni del status del CFDI

**Comment by RigoFlores** [comment]
Descontar folios por cada cancelación: OK
Incluir el status del CFDI en el acuse: OK

**Incluir el motivo de cancelación en el acuse: Not Yet**

Faltará la implementación cuando hagamos lo de soporte a documentos relacionados.

**Comment by RigoFlores** [comment]
Listo, por lo pronto ya quedó.
