### ISSUE TITLE
Refactoring 4 - Pantalla de captura del complemento, rumbo al ccp mas gaver de méxico

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2016]
En la pantalla de captura, el seguro de medio ambiente y el seguro de mercancía son poco utilizados.
Mandarlos a la parte inferior debajo de arrendatario.

Así quedarán hasta abajo: Propietario, arrendatario, seguro de medio ambiente y seguro de mercancía.

Otra cosa para optimizar, es replicar los botones que están arriba, igualmente abajo. Guardar, Cancelar, Incluir Contrato, Reemplazar productos en CFDI. Con ello no tenemos que estar subiendo y bajando la pantalla de captura

**Comment by jccastillo0007** [comment]
done.

Las opciones de reemplazar productos e incluir contrato, no se pueden duplicar, ya que están directamente ligados a atributos de la addenda, y no se pueden repetir
