### ISSUE TITLE
Complemento de carta porte - Asignar automáticamente el ID del origen y destino

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2017]
Aquí veo 2 opciones:

1) Que en la BD se asigne un consecutivo a cada origen y destino que se haya capturado. OR00001, DE00001, etc.
Ese campo aparecería hasta abajo en la captura, y se sugeriría para que el usuario lo cambie si así lo desea.

En esta caso, desaparecerían los ID de la pantalla de captura.

2)
Que en la pantalla de captura, al agregar orígenes y destinos, se sugiera el consecutivo de esa captura. No importa que sean solo 1 origen y 1 destino, que se incluyan y no pasaría nada (sugeridos, los podrían borrar). No marca error si van. 
Estos datos si que son obligatorios para cuando hay mas de 1 origen y/o destino.

Cómo la besibol, cuál te parece mejor opción?

**Comment by jccastillo0007** [comment]
opción 2, listo

**Comment by RigoFlores** [comment]
jajajaja.... si lo pone, pero no como deben ir...

Incorrecto: OR1, DE1
Correcto: OR000001, DE000001

Es decir, el formato que pide el SAT son 6 dígitos después del OR y DE

**Comment by RigoFlores** [comment]
ahora, si yo los compongo y le tecleo el ID origen y destino, no jala marca error. No manda las ubicaciones al XML.

De hecho otro error que tiene, es que cuando elijo transporte, vuelve a poner el origen y destino que propuso inicialmente (el que está mal), aún cuando ya lo había borrado o tecleado correctamente. Eso genera un error ya que el usuario no se da cuenta de ello.

**Comment by jccastillo0007** [comment]
chiaaaa, no sabía del formato..

**Comment by jccastillo0007** [comment]
fixed
