### ISSUE TITLE
Carta porte 2.0 - si incluyes 2 operadores en la captura, repite los datos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2018]
En algunos casos, se requiere capturar 2 operadores. Ya lo han mencionado algunos clientes. Entiendo que en viajes muy largos.

La plataforma si permite capturar 2 operadores, pero al momento de generar el XML, repite el 2o operador capturado. Es decir, el primero lo ignora y repite el segundo. Hay que corregir este escenario.

Por otro lado, a PDF solo envía 1 operador.

Entonces cuando se trate de mas de 1 operador, enviarlo en la variable correspondiente al PDF. Si hoy envía 1 operador, ahí mismo pegar el operador 2, operador 3, etc.
Hoy lo envía así al PDF:

Operador: JUAREZ MENDEZ EDGAR, RFC: JUME890620KB3, Licencia: LIC1234FEDERAL

Ideal si se pudiera poner operador1, en un renglón abajo, operador2, y así si hubiera más operadores.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
no puedo probar, marca internal error cuando intento timbrar un carta porte.

**Comment by RigoFlores** [comment]
al parecer si lo hace ya, pero no puedo validarlo ya que marca el internal error al intentar timbrar.

**Comment by RigoFlores** [comment]
el PDF no está enviando los 2 operadores, solamente 1.

**Comment by RigoFlores** [comment]
aquí hay que elegir los 2 primero operadores de la lista.

**Comment by jccastillo0007** [comment]
fixed
