### ISSUE TITLE
Carta Porte Misceláneos - no está almacenando registro ni país

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2019]
si permite capturarlos, pero al momento de guardarlos y luego consultarlos, resulta que no los guarda.
Para ninguno de los 5 tipos.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
no puedo probar, marca internal error cuando intento timbrar un carta porte.

**Comment by RigoFlores** [comment]
bueno, lo de almacenar si lo está guardando ya.
Lo que no se puede hacer, es que si quiero editar, no hay forma de ponerle el país de residencia a "nada" (el clásico, seleccione uno o un registro vacío).

**Comment by jccastillo0007** [comment]
ese es ooootro problema
