### ISSUE TITLE
Carta Porte Misceláneos - habilitar RFC, Registro y País de residencia

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2021]
He estado haciendo pruebas, pero no me queda muy claro cuándo si los lleva y cuándo no.
En el conector, no está jalando esa parte.

Entonces, para definirla bien, por favor activar la captura simultánea de RFC, número de registro y país de residencia.
Una vez que concluya las pruebas y verificaciones, ya se establecerá cómo queda.

**Comment by jccastillo0007** [comment]
chiaaaa

done

**Comment by RigoFlores** [comment]
no puedo concluir mis pruebas, ya que si el origen no incluye el RFC no lo envía al XML.
Es decir, un origen que en lugar de rfc incluye registro y país de residencia, no lo envía al XML.
Seguro para el destino igual.

En caso de operador, si lo envía

**Comment by jccastillo0007** [comment]
Ese es otro defecto, lo puedes crear
