### ISSUE TITLE
Complemento de pago - pago en mxn de facturas en usd, marca error en caso aislado (dirían los políticos)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2022]
Este caso es muy común pago en MXN de facturas en usd; pero hasta hoy apareció una condición donde no se cumple todo lo que hemos implementado.
Creo yo, y eso habría que probarlo (validarlo), es porque el cálculo de equivalenciaDR, que es a 6 decimales, se redondea en lugar de truncarlo.
Creo que si lo truncamos, ya no marcaría error. Es solo una teoría. La verdad, es que para este caso, aparentemente se ocuparían mas decimales en la equivalenciaDR.

Ya revisé el XML, y lo genera bien, de acuerdo a los cálculos solicitados. Lo único que vi, es que el cálculo de la equivalencia DR, lo redondea, y posiblemente eso cause el error (ya que se va mas alto). Podrías ponerlo a que lo trunque a 6 decimales, y hago la prueba?

Aquí está el XML, pero no sirve de mucho, ya que como mencioné, todo lo hace de acuerdo a lo solicitado.

[pagoMatsa.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/9255558/pagoMatsa.xml.txt)

El mensaje de error es:

**_El campo ImporteP que corresponde a Traslado, no es igual a la suma de los importes de los impuestos registrados en 
el documento relacionado donde el impuesto del documento relacionado sea igual al campo ImpuestoP de este elemento 
y la TasaOCuotaP del documento relacionado sea igual al campo TasaOCuotaP de este elemento._**

**Comment by jccastillo0007** [comment]
me puedes pasar el excel que preparaste, o en su defecto, solo el cálculo de como se obtienen la equivalencia DR? para poder modificar y ver que por código ya se esta truncando... 
Con el XML no puedo ver la info de como se hizo el cálculo

**Comment by RigoFlores** [comment]
el cálculo de la equivalenciaDR = ( sumatoria montos pagados en cada factura (moneda original del CFDI) / importe pagado (moneda de pago) ) * 1.000002

ese dato lo calcula bien, pero lo está redondeando. La petición es truncarlo

**Comment by jccastillo0007** [comment]
eso ya lo se, pero quiero reproducirlo... en el xml viene el dato de importe pagado, pero no el de la sumatoria de montos pagados en cada factura... chiaaaaa

**Comment by RigoFlores** [comment]
pues pediste el cálculo, la verdad no entiendo que requieres.
Pero en este excel vienen los calculos de ese complemento de pago...

[calculos compPago 2.0.xlsx.TXT](https://github.com/jccastillo0007/eFacturaT/files/9271005/calculos.compPago.2.0.xlsx.TXT)

**Comment by RigoFlores** [comment]
de hecho, si tomas los datos del XML y les aplicas la equivalenciaDR, te arroja otros resultados
no estoy entiendo bien, lo que está haciendo...

**Comment by jccastillo0007** [comment]
Porque dices esto:

de hecho, si tomas los datos del XML y les aplicas la equivalenciaDR, te arroja otros resultados
no estoy entiendo bien, lo que está haciendo...


Con la equivalencia del xml , realicé las operaciones inversas, y llegue al mismo resultado... 

La equivalencia que esta en el xml es 0.048539, con lo que pides se convertirá a 0.048538

es correcto lo que pides ?

**Comment by jccastillo0007** [comment]
Pregunta... vale la pena seguir haciendo la multiplicación por 1.000002 ?

Justo en este ejemplo se nota que no sirve de nada....

**Comment by jccastillo0007** [comment]
ya subi una versión a pru que trunca el valor de equivalencia en 6 decimales

**Comment by RigoFlores** [comment]
Voy a revisar... si no multiplicamos por el factor mágico, los casos similares a este, serían prácticamente todos...
Este es el primer caso que se reporta que no cumple. Y lo importante es revisar porqué no lo hace.
Voy a probar con este ajuste, y si no se corrige, vamos a ver que otra cosa se puede hacer.

**Comment by RigoFlores** [comment]
Truncando, el factor si cambió un poco, casi nada. Ahora es: 0.048538
Sin embargo, haciendo todas las operaciones, en el nodo de ImpuestosP, se reporta algo un poco distinto, y no se de donde sale. La sumatoria en USD, pues no se reporta en el XML, pero al convertirlo a la moneda de pago, en este caso MXN, pues tiene una ligera variación.
Mira:
<img width="313" alt="matsa" src="https://user-images.githubusercontent.com/2912775/183468985-922bc515-abda-47e6-a32c-1b746ffe849f.PNG">

**Comment by RigoFlores** [comment]
Aquí te dejo el excel con esos cálculos.

[calculos compPago 2.0.xlsx.txt](https://github.com/jccastillo0007/eFacturaT/files/9283565/calculos.compPago.2.0.xlsx.txt)

**Comment by RigoFlores** [comment]
en pru, con emisor IIA, ya está el escenario de pruebas, las facturas son las 444, 445 y 446  con el receptor CMA1408

**Comment by jccastillo0007** [comment]
y luego? pues hay que analizar que falla...

**Comment by RigoFlores** [comment]
pues ya te estoy diciendo que no está haciendo los cálculos correctamente,  o que mas necesitas saber.
Te estoy indicando lo que está calculando un  poco distinto.
El asunto es la parte donde dice lo que reporta al XML y lo que resulta el cálculo, ahí está la diferencia.

**Comment by RigoFlores** [comment]
De acuerdo a tu revisión, el asunto se deriva inicialmente, de que los importes de las facturas al momento de guardarse en la BD, no coinciden con el XML.
Entonces por lo pronto, para este caso, hay que igualarlos para seguir adelante, y revisar si eso es lo único que hay que atender o surge alguna otra cosa.

**Comment by RigoFlores** [comment]
Igualando los importes del XML con la BD, sin hacer ningún otro cambio, se pudo timbrar el XML.
La diferencia de importes al momento de guardar en BD, puede llegar a provocar este problema, que la verdad es muy muy raro.
Aunque pensándolo bien, algunas veces este problema, se ha resuelto variando el tipo de cambio... quizás es distinto el escenario, pero para el caso, me parece que tiene el mismo efecto.
