### ISSUE TITLE
Carta Porte - Misceláneos, no envía la ubicación cuando no se incluye el RFC origen o destino

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2023]
no puedo concluir mis pruebas, ya que si el origen no incluye el RFC no lo envía al XML.
Es decir, un origen que en lugar de rfc incluye registro y país de residencia, no lo envía al XML.
Seguro para el destino igual.

**Comment by RigoFlores** [comment]
chiaaa, me haces levantar otro issue, siendo parte del otro, pero bueno...
necesito identificar cuándo si se puede enviar el registro y la residencia fiscal únicamente. Con el operador si se pudo.
Pero falta validar el origen y destino, pero no lo está incluyendo al XML cuando no se captura el RFC

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
no puedo probar, marca internal error cuando intento timbrar un carta porte.

**Comment by RigoFlores** [comment]
Sigue igual, con el origen "Alemania", no lo envía.
Ese registro no tiene capturado RFC, únicamente registro y país de residencia.

**Comment by RigoFlores** [comment]
Origen "SIN RFC CON REGISTRO"
Destino, LA TIA (gdl o qro)
Mercancía "FRACC_Y_PEDIMENTO"
transporte, cualquiera
operador, el primero de la lista.

**Comment by jccastillo0007** [comment]
fixed
