### ISSUE TITLE
Conector 4.0 - No está enviando correctamente las bases de los impuestos IEPS e IVA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2024]
Aquí tienes el XML y el PDF correspondientes.
En uno de los cuadros inferiores, se muestra el impuesto, con su tasa y la base.
Para el IVA y para el IEPS 53% no está enviando correctamente las bases al PDF. 
El XML está correcto.

    <cfdi:Impuestos TotalImpuestosTrasladados="7792.90">
        <cfdi:Traslados>
            <cfdi:Traslado Base="2281.23" Importe="604.52" Impuesto="003" TasaOCuota="0.265000" TipoFactor="Tasa"/>
            <cfdi:Traslado Base="6159.24" Importe="3264.40" Impuesto="003" TasaOCuota="0.530000" TipoFactor="Tasa"/>
            <cfdi:Traslado Base="24524.88" Importe="3923.98" Impuesto="002" TasaOCuota="0.160000" TipoFactor="Tasa"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

Pero el PDF nop.

Aquí tienes los archivos, junto con el archivo de texto que da origen a esa factura y la plantilla para que puedas probar.

[problemaIVAeIEPS.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/9274982/problemaIVAeIEPS.zip.txt)

[TPPM022132.TXT](https://github.com/jccastillo0007/eFacturaT/files/9274984/TPPM022132.TXT)

[plantillaBarricas.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/9274987/plantillaBarricas.zip.txt)

**Comment by jccastillo0007** [comment]
fixed.

este si estuvo tricky, se me hace muy raro que nadie mas lo ha reportado... ya que es un caso que en teoría es común...

**Comment by RigoFlores** [comment]
No, no es nada común.
En 12 años de la tía, es la primera ocasión que se require por conector... eso de varias tasas de IEPS, no, nunca.
Si hubo o hay uno por ahí, que es IVA e IEPS, pero no varias tasas.
total que ya quedó, a ver como se va dando esto.

Viene el complemento de pago, y con tantas tasas e impuestos, a ver como nos va... jeje
