### ISSUE TITLE
Misceláneos - no envía el registro y país en arrendatario y propietario

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2025]
Cuando no se captura RFC, pero si se captura registro y país de residencia, éstos últimos no los envía al XML.
Lo que estoy tratando de validar es cuándo si se ocupa RFC y cuándo no, para los distintos misceláneos.

En operador, es el único que jala hasta el momento.

**Comment by RigoFlores** [comment]
el arrendatario y/o propietario en este caso tienen alias "SIN RFC CON REG Y PAIS"
Los datos para el complemento son origen y destino, LA TIA 
Mercancía computadora dell
transporte, cualquiera
operador, el primero de la lista.

**Comment by jccastillo0007** [comment]
fixed
