### ISSUE TITLE
Misceláneos - no envía el rfc a XML del propietario o arrendatario, cuando es extranjero

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2027]
No manda al XML el rfc capturado (XEXX010101000) en el registro del propietario o arrendatario CON RFC, REG Y PAIS
origen y destino LA TIA
mercancía - computadora dell
transporte  y operador - el primero

Propietario o arrendatario: CON RFC, REG Y PAIS

**Comment by jccastillo0007** [comment]
si lo manda...
<cartaporte20:FiguraTransporte>
                <cartaporte20:TiposFigura NombreFigura="RIGOBERTO FLORES" NumLicencia="FED123" RFCFigura="FOPR681125BQ0" TipoFigura="01"/>
                <cartaporte20:TiposFigura NombreFigura="MISAEL FLORES" NumRegIdTribFigura="12234" RFCFigura="XEXX010101000" ResidenciaFiscalFigura="DEU" TipoFigura="03">
                    <cartaporte20:PartesTransporte ParteTransporte="PT01"/>
                </cartaporte20:TiposFigura>
                <cartaporte20:TiposFigura NombreFigura="MISAEL FLORES" NumRegIdTribFigura="12234" RFCFigura="XEXX010101000" ResidenciaFiscalFigura="DEU" TipoFigura="02">
                    <cartaporte20:PartesTransporte ParteTransporte="PT01"/>
                </cartaporte20:TiposFigura>
            </cartaporte20:FiguraTransporte>
