### ISSUE TITLE
Guardar CFDI en las BD de Factura-T, de acuerdo a lo que se reporta en el XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2028]
Para evitar problemáticas en los complementos de pago de web y conector, hay que almacenar en las bases de datos los mismos importes que se reportan en el XML

**Comment by jccastillo0007** [comment]
si k, no ma, esto es justo el efacturat 2.0,
por un lado, creo que ya le estas viendo el beneficio de hacerlo... por otro... como que no quieres dejar de lado la tecnología obsoleta del standalone...

**Comment by RigoFlores** [comment]
jajaja, creo que este comentario no aplica aquí.
De lo que se trata, con la tecnología que sea, es que en la BD se almacene la información tal cual se reporta en el XML. 

Esto es si en los totales se reporta a 2 decimales en el XML, así mismo en la BD.

Ya vimos que eso puede llegar a ser problema.
De hecho es muuuy común que el cliente cuando captura un pago, vea en la columna cobro 3 decimales. Ya se la saben borran uno o simplemente no les causa problema por ser 1 factura. Pero la realidad de las cosas, es que eso no está bien.

**Comment by jccastillo0007** [comment]
esto lo vamos a implementar en eft2.0

**Comment by RigoFlores** [comment]
pues hay que sacarlo pronto, porque se están reportando problemas con ello
