### ISSUE TITLE
Almacenar la BD del conector en WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2029]
Los conectores que procesan muchos archivos de texto, se saturan y ya no jalan.
En Figueacero, cada cierto tiempo, tengo que depurar a manita su BD.

Entonces la petición es que la BD se almacene en el servidor, y todo el procesamiento sea local.
Los XML y PDF, estarían en ambos lados, o quizá solo en el servidor, siempre y cuando, se puedan consultar y descargar desde el escritorio.

No sé si esto es precisamente el proyecto de migrar a angular el facturat de web. 
El comportamiento en escritorio, tendría que ser muy similar, sobre todo el conector.
Aspectos importantes son la facilidad de instalación... el debugueo de lo que está pasando en la app... el procesamiento de archivos y su movimiento y manipulación en los directorios locales...

**Comment by jccastillo0007** [comment]
si k, no ma, esto es justo el efacturat 2.0, 
por un lado, creo que ya le estas viendo el beneficio de hacerlo... por otro... como que no quieres dejar de lado la tecnología obsoleta del standalone...

**Comment by jccastillo0007** [comment]
y web con wicket

**Comment by RigoFlores** [comment]
jaja, claro que quiero actualizar la tecnología.
Lo que no me gustaría mucho es hacer cosas como medio chacarronas... esto es "hagamoslo para web, pero no hay pedo, jala igual en escritorio"... eso me parece muy chaca. Creo que las tecnologías están para aplicarse donde debe ser.
Por ejemplo, en móvil, tiene su propia tecnología. OK, pero si ejecutas un desarrollo web, si le puedes dar una apariencia tipo APP, con los estilos y lo que se hizo para descargaT, que ya ni me acuerdo como se llama el concepto, jaja.

Pero en escritorio, las aplicaciones tienen su propio look and feel, y si ese l&f de lo podemos dar a una aplicación web, pues va, está chido. Si no, estaríamos ocupando una tecnología web, para algo que sería escritorio. Eso es lo que no me hace sentido. 
En tal caso, la actualización propiamente del conector actual a una tecnología reciente, sería manejar el java la última versión o algún otro lenguaje que sea exprofeso para escritorio.

Y wicket, que te digo, si desde el principio ha estado muy limitado con algunas funciones que considero básicas... como por ejemplo poder capturar una factura en un grid, poder hacer las búsquedas en las listas con solo teclear parte del texto, etc... esas 2 por mencionar unas, son super poderosas y no lo podemos hacer... pero bueno, nos ha resultado bien. 
Y actualizar la tecnología web, pues si, si me late como no.

**Comment by jccastillo0007** [comment]
Esto ya no aplica, se resolverá con la versión 2.0
