### ISSUE TITLE
Conector - no toma en cuenta el dato de total de impuestos trasladados (y no lo calcula bien).

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2031]
Realmente tenemos un doble problema, o un problema que provoca dos situaciones:

a) En el archivo de texto, se incluye un dato que se llama totalImpuestosTrasladados, pero no lo está tomando en cuenta.
b) Quiere decir, que en su lugar, está haciendo cálculos. No está mal que los haga. Pero entonces los cálculos que debería realizar son:
totalImpuestosTrasladados = suma de los importes de cada tipo de impuesto trasladado, reportado en ese nodo general de impuestos.

Hay un caso que será común para el cliente de las barricas, ya que ellos manejan 2 impuestos trasladados, ya ahí es donde se puede presentar el asunto, ya que el problema se potencia cabrón. 
Mira, por ejemplo la sumatoria de los impuestos de los distintos productos, hasta 6 decimales, es:

Monto IEPS 53% : 7491.0836
Monto IVA 16% : 3460.032576
Suma aritmética de ambos: 10951.116176

ahí todo normal.
Al XML, se reporta en 2 decimales dentro del nodo TotalImpuestosTrasladados. Se reporta así:

Monto IEPS 53% : 7491.08
Monto IVA 16% : 3460.03
TotalImpuestosTrasladados: 10951.12

Entonces, aquí si revisas con cuidado, la suma de los 2 impuestos reportados en ese nodo, debería ser 10951.11
Pero lo que se reporta ahí termina en .12, entiendo yo porque sumó los 2 impuestos trasladados con sus 6 decimales.

La regla del SAT dice que a nivel de este nodo (totalImpuestosTrasladados), se debe reportar a 2 decimales todos los importes (realmente dice los decimales que soporta la moneda, es decir 2).
Entonces,  primero se reportan los impuestos individuales a 2 decimales (IVA e IEPS en este caso). Eso lo hace bien. Toma las sumatorias y lo redondea, eso está bien.
Luego a nivel total, debe ser la suma de esos impuestos reportados a 2 decimales. Aquí es donde no lo está haciendo bien.

Ya que ese totalImpuestosTrasladados, lo está redondeando a 2 decimales, de la suma de impuestos individuales a 6 decimales, y como podrás ver en el ejemplo, no siempre coincidirán.
Así que todo lo de impuestos funciona de maravilla, está super bien las sumas y todo. Solo ese total de impuestos trasladados, hay que recalcularlo bien. O la otra es tomarlo del archivo. Cómo gustes.

**Comment by RigoFlores** [comment]
Reproduje el error en web, y no es solo del conector. 
También en web, tenemos ese problema.

Lo que se reporta a nivel del nodo **_Impuestos_**, debe ser la suma de los impuestos reportados al interior.
El total, debe ser la suma de los importes + impuestos trasladados - impuestos retenidos.

Mira, la suma de los impuestos reportados dentro del nodo, es 10951.11, y aquí marca el error.

    <cfdi:Impuestos TotalImpuestosTrasladados="10951.12">
        <cfdi:Traslados>
            <cfdi:Traslado Base="21625.20" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="3460.03"/>
            <cfdi:Traslado Base="14134.12" Impuesto="003" TipoFactor="Tasa" TasaOCuota="0.530000" Importe="7491.08"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

Si quieres ver cómo fue, está en pru...

2022-08-15 11:08:24,349 DEBUG [http-nio-8080-exec-22] (SealerPACProcess.java:557) - El valor del campo TotalImpuestosTrasladados no es igual a la suma de los importes registrados en el elemento hijo Traslado.

**Comment by jccastillo0007** [comment]
fixed
