### ISSUE TITLE
Conector Las Barricas - manejar todos los importes a 2 decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2032]
Ellos lo piden así.
Me enviaron el XML timbrado anexo y está a 2 decimales.
Hasta ahora me va cayendo el 20 de que he tenido que corregir los archivos de optibelt, porque todo lo mandamos a 6 decimales.
La verdad no recuerdo cuando se agegó esa calculadera  6 decimales, no sé. Quizá fue que alguien pidió que se llegara a una cantidad exacta, eso pudo ser.
Los 6 decimales, si se requieren, cuando quieres alcanzar un total preciso, exacto. 
Si no te interesa que el total se salga por unos centavos, pues si se pueden ocupar 2 decimales.

Recordemos, que entre mas precisión se requiera, mas decimales en los importes a nivel concepto. 
Y entre mas decimales, mas se cierra el margen de error que el SAT otorga.

Total, que para mi la solución ideal del conector, sería que ese parámetro de número de decimales, fuera configurable.
La otra solución, es revisar las cantidades, y enviarlas solo con los decimales reportados. Por ejemplo si en el archivo de texto se indica importe 10.20, pues enviarlo así. Hoy enviamos 10.200000

Aquí te dejo 2 archivos de texto con la misma info, solo que uno está a 2 decimales (no lo podemos timbrar) y el otro a 6 decimales, si lo timbra. Al final el total es el mismo en los 2, pero yo pienso que eso varia. Es un poco aleatorio, en el sentido que si redondeas a 2 decimales, algunas ocasiones sumarás de más, o en otras restarás mas... pero no es una regla que de el mismo resultado; en este caso si, pero no siempre.

Anexo el zip con todo:

Está el XML timbrado a 2 decimales, nos lo entregó el cliente. Lo timbró otro pac.
El XML timbrado en pru, a 6 decimales por nosotros. 
El Excel con los cálculos a 6 decimales, comparado con los 2 decimales del XML.
Y 2 archivos de texto plano, uno a 6 decimales (que si lo timbra), y el de 2 decimales que no timbra. 

[LASBARRICAS.zip.TXT](https://github.com/jccastillo0007/eFacturaT/files/9353140/LASBARRICAS.zip.TXT)

**Comment by jccastillo0007** [comment]
chiaaaa, y luego otro cliente va a pedirlo a 3 decimales.... si quiera este cliente vale la pena darle gusto... el que lo pidió a 6 decimales, quien fue? acaso sigue con nosotros...

Total que el desmadre es solo en impuestos y totales cierto? según el excel es ahí donde hay diferencias...

**Comment by RigoFlores** [comment]
Como te mencioné en el audio, básicamente lo de 6 decimales, seguramente se hizo para poder alcanzar cifras cerradas en los totales. Entonces ahí, el precio unitario se manda hasta 6 decimales. 
El problema es cuando el precio es por ejemplo 10.73, y se reporta como 10.730000... todo empieza ahí.

Por otro lado ningún cliente pide que sea a 3,4 6 decimales. Piden que se alcancen las cifras.
Particularmente las barricas si pidió todo a 2 decimales, y ya nos mostró que si es posible con un XML 4.0, timbrado y todo a 2 decimales. La cifra final no cierra a .00, pero bueno eso ellos ya lo asumirían.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ya quedó claro todo.
El precio unitario, si se reporta a 6 decimales, reduce el rango variación entre el límite inferior y superior para el importe.
Peeeeero, si el importe se reporta a 2 decimales, entonces el límite inferior es trunca a 2 decimales, y el límite superior se redondea a 2 decimales. Con ello, difícilmente se podrá generar la condición de error.

Resumen, la clave está en el número de decimales que reporta EL IMPORTE.
