### ISSUE TITLE
WEB CFDI 4.0 - marca error 115 con la addenda mabe.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2033]
Yo recuerdo que esta parte ya la había validado y jalaba bien.

Hoy intenté hacer una prueba, y marcó error. El cliente en pro la reportó
En pru, con el emisor IVD, y receptor CONTROLADORA MABE.
concepto: producto de prueba 1

Datos de Addenda: 
pedido: 9500790523
referencia1: 123456
referencia 2: (no se captura, vacío)
Número de proveedor e ID planta, ya están precargados.

Al final de la pantalla de captura de addenda, pone 2 datos que no debería, quizás sea por el plugin de CCE. Pero en pro no los pone y marca el mismo error.

**Comment by jccastillo0007** [comment]
fixed
