### ISSUE TITLE
Al borrar un cobro, no siempre pone todas las facturas a "Vigente", algunas las deja "Pagadas"...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2035]
Según yo, esto sucede porque el mismo RFC emisor, tiene trackingID repetidos dentro de su historial.

Desde hace mucho sucede esto, pero tenemos un cliente que está muy encabronado... ya que cuando cancela un documento de pago y luego borra el cobro, es común que no se le actualicen todas sus facturas a "Vigente".
Yo hace mucho pedí, incluir la fecha en el trackingID, con ello será casi imposible que presente este asunto... la otra es buscar por el folio también, o que se yo... jeje

Acaba de pasar con el folio 7202 y 7204 que están involucrados en el complemento de pago 516 del cliente abajo mencionado.
Esas 2 facturas que son las que reportó el cliente, tienen su trackingId repetido para ese cliente.

Busqué en otras facturas dentro del mismo complemento, y la diferencia es que en esos otros que si puso a "Vigente", no se repetía el trackingID.

mysql> select id, folio, sourceRFC, date, targetRFC, CxCStatus, trackingId from CFD where sourceRFC = "RIRV780214CA6" and ( trackingId = 121515  or trackingId =  121916 );
+---------+-------+---------------+---------------------+--------------+-----------+------------+
| id      | folio | sourceRFC     | date                | targetRFC    | CxCStatus | trackingId |
+---------+-------+---------------+---------------------+--------------+-----------+------------+
|  726270 |  2894 | RIRV780214CA6 | 2018-11-22 12:25:47 | NTA931214IJ6 | Pagada    | 121916     |
| 2051146 |  6207 | RIRV780214CA6 | 2021-07-26 12:15:15 | NTA931214IJ6 | Vencida   | 121515     |
| 2996035 |  7202 | RIRV780214CA6 | 2022-08-03 12:15:15 | NTA931214IJ6 | Vigente   | 121515     |
| 2996039 |  7204 | RIRV780214CA6 | 2022-08-03 12:19:16 | NTA931214IJ6 | Vigente   | 121916     |
+

**Comment by jccastillo0007** [comment]
chiaaaa
fixed

**Comment by RigoFlores** [comment]
Y como fue la corrección? Enviado desde mi Huawei de Telcel.-------- Mensaje original --------De: JC ***@***.***>Fecha: mié., 24 de agosto de 2022 18:25Para: jccastillo0007/eFacturaT ***@***.***>CC: RigoFlores ***@***.***>, Author ***@***.***>Asunto: Re: [jccastillo0007/eFacturaT] Al borrar un cobro, no siempre pone todas las facturas a "Vigente", algunas las deja "Pagadas"... (Issue #2035)
chiaaaa
fixed

**Comment by jccastillo0007** [comment]
pues, se revisa el tracking id, que no sé porque no tiene milésimas de segundos... y si hay mas de dos, se valida que sea parte del pago

**Comment by RigoFlores** [comment]
si, al final lo que se necesita es que no se repita, y lo último que yo sabía, es que se iba a incluir la fecha - hora - milésimas, como parte del trackingid.
La otra opción, es ocupar el mismo ID irrepetible que ya entrega la base de datos.... chiaaaaa....

Estamos validando algo, que se puede manejar por código sin necesidad de agregar mas y mas lógica al procesamiento. 
Pero bueno....

**Comment by RigoFlores** [comment]
Pues tenemos el problema para la versión 3.3, ahí no se corrigió supongo??

mysql> select id, folio, sourceRFC, date, targetRFC, CxCStatus, trackingId from CFD where sourceRFC = "CRE9502072DA" and folio = 2613;
+---------+-------+--------------+---------------------+--------------+-----------+------------+
| id      | folio | sourceRFC    | date                | targetRFC    | CxCStatus | trackingId |
+---------+-------+--------------+---------------------+--------------+-----------+------------+
| 2996862 |  2613 | CRE9502072DA | 2022-08-04 13:15:48 | CID120207FY0 | Pagada    | 131548     |
+---------+-------+--------------+---------------------+--------------+-----------+------------+
1 row in set (1.44 sec)

mysql> select id, folio, sourceRFC, date, targetRFC, CxCStatus, trackingId from CFD where sourceRFC = "CRE9502072DA" and trackingId = 131548;
+---------+-------+--------------+---------------------+--------------+-----------+------------+
| id      | folio | sourceRFC    | date                | targetRFC    | CxCStatus | trackingId |
+---------+-------+--------------+---------------------+--------------+-----------+------------+
| 2880542 |  2545 | CRE9502072DA | 2022-06-06 13:15:48 | CID120207FY0 | Pagada    | 131548     |
| 2996862 |  2613 | CRE9502072DA | 2022-08-04 13:15:48 | CID120207FY0 | Pagada    | 131548     |
+---------+-------+--------------+---------------------+--------------+-----------+------------+
2 rows in set (0.03 sec)
