### ISSUE TITLE
facturas emitidas desde conector, las registra con tasa 0 en lugar de 8, y arma el desmadre

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2037]
Lo mandé por correo y no se ha atendido. Checa el correo del día 17 de agosto. Así dice el correo...

**Ya vi que es el mismo problema del otro issue, que no se ha resuelto. Solo se corrigió, pero no se resolvió.

Facturas que incluye el pago, están emitidas desde el conector con tasa IVA 8.
Pero en la BD (supongo), lo registra con tasa 0, o al menos así lo reporta en el documento de pago, y pues se hace el cagadero.

Ahí está el documento de pago XML que marcó error (donde varias facturas las incluye con tasa 0)
Anexo una de las facturas que la incluye como tasa 0, cuando realmente tiene tasa 8 del IVA.**

**Comment by RigoFlores** [comment]
[sergioTasa8reportada.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/9419805/sergioTasa8reportada.zip.txt)

Aquí va el XML que intentó timbrar, donde algunos DR les pone tasa 0.
También va una de las facturas timbradas donde se muestra que la tasa es 8.
Y finalmente la pantalla para capturar el documento de pago, si quieres validar.


OJO, la "aspirina" es cambiar la tasa en la BD.
Pero el problema de fondo, sigue sin resolverse.

**Comment by jccastillo0007** [comment]
fixed... chiaaaa

cuando liberamos una nueva versión a prod... ya hay muchos cambios almacenados

**Comment by RigoFlores** [comment]
el siguiente miércoles liberamos a pro.
Esto es para que desde hoy y hasta el martes, los clientes de carta porte, puedan familiarizarse con los cambios.
Ya les envié la información por correo también.

**Comment by RigoFlores** [comment]
no tengo forma de validar esta corrección, ya que no se cómo reproducirla.
cerraré el issue, y pues estaré pendiente, después de la liberación a producción.
Mientras tanto, pon aquí el cueri para cambiar las tasas de las facturas, si es que vuelve a suceder...
