### ISSUE TITLE
Lo que faltó para hacer el Carta Porte mas gaver de México - Validación en la pantalla de captura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2038]
Estoy identificando que se me pasó solicitar la validación de datos obligatorios en la pantalla de captura (addenda).
Validar lo siguiente:

Origen(es): seleccionar origen y fecha de salida.
Destino(s): seleccionar destino, distancia recorrida y fecha probable de entrega
Mercancía(s): seleccionar mercancía, cantidad y peso. (el peso se pone en automático, si se capturó en el catálogo)
Transporte: transporte (haber seleccionado un transporte)
Operador: operador (al menos 1).

No permitir guardar, si no supera la validación.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
NO está validando que el peso exista. 
Lo borré, le di guardar y si permitió guardarlo.

De lo demás, ya todo quedó chido

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
listo, hay que subirlo a producción.
