### ISSUE TITLE
ERP - NOMINA, NO ALMACENA NUEVOS EMPLEADOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#204]
ESTUVE TRATANDO DE REPRODUCIR EL PROBLEMA QUE BORRA LAS PERCEPCIONES Y DEDUCCIONES CAPTURADAS.
GENERALMENTE LE SUGIERO HACERLO EN 3 PARTES: PRIMERO LOS GENERALES DEL EMPLEADO, QUE LLEGA A ESTADO, PAIS Y CP, Y GUARDAN REGISTRO.
EN SEGUIDA LAS PERCEPCIONES Y GUARDAN
FINALMENTE DEDUCCIONES Y GUARDAN.
BUENO, PUES DESDE LA PRIMERA ETAPA NO ESTÁ ALMACENANDO EL REGISTO. CAPTURO TODOS LOS OBLIGATORIOS, INDICA QUE SE ALMACENÓ EXITOSAMENTE, PERO NO LO ESTÁ HACIENDO.

**Comment by RigoFlores** [comment]
LO PROBÉ EN PRU, Y TIENE EL MISMO COMPORTAMIENTO.
SEGÚN YO, EXISTE SE HACE UN DESMADRE, CUANDO BORRO REGISTROS, Y EMPIEZA A MEZCLAR LA INFORMACIÓN DE UNOS REGISTROS CON OTROS.
EN AMBOS CASOS (PRU Y ERP), EL CASO SE PRESENTÓ CUANDO BORRÉ PREVIAMENTE ALGUNS REGISTROS.PARTE DE LA INFORMACIÓN DE LOS REGISTROS BORRADOS, SE MEZCLÓ CON OTROS.

**Comment by jccastillo0007** [comment]
Oye, este issue esta muy fumado... que explorador estas usando... yo 
acabo de hacer algunas pruebas con chrome y firefox y funciono 
correctamente...

No pude reprodcucir este error, puedes checar otra vez en otra maquina o 
en otro explorador que no sea el de default, para tratar de aislarlo.

Saludos.
JC.

**Comment by jccastillo0007** [comment]
Estuve haciendo este tipo de pruebas en el ERP y no lo pude reproducir del todo... pero si encontré un detalle, que no estoy seguro era el defecto que levantaste... pero hay que seguir probando.
