### ISSUE TITLE
Carta Porte - Catálogo de Mercancías.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2041]
Cuando capturas la clave del SAT, dice que es inválida, aún cuando sea correcta.
Además para material peligroso, no despliega la lista (catálogo) de claves de embalaje.

**Comment by jccastillo0007** [comment]
que clave no encuentra ?

**Comment by RigoFlores** [comment]
la clave de mercancía del sat, cualquiera dice que no existe por ejemplo: 15101515 que corresponde a gasolina premium
y la lista de clave de embalaje, está vacía.

**Comment by jccastillo0007** [comment]
si ya vi, no existe el catálogo en prod

**Comment by jccastillo0007** [comment]
done
