### ISSUE TITLE
PARA LO DE PEPSI, NO ESTÁ RESPETANDO EL USO DE CFDI ELEGIDO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2043]
Te mandé un correo donde el uso de CFDI no está coincidiendo el uso de CFDI en el PDF con el XML.
Ellos eligen I08 y lo incluye en el PDF, pero en el XML lo pone distinto.

**Comment by RigoFlores** [comment]
También si eligen 603, se le coloca el G01.

**Comment by jccastillo0007** [comment]
fixed
