### ISSUE TITLE
Conector Figueacero - hacer lo mismo que con las barricas, fijarte en el ticket 2032

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2046]
Se refiere a manejar todo a 2 decimales.
Ya está hecho para las barricas, entonces esas mismas condiciones aplicarlas para Figueacero en producción.
Este es su RFC FIG881205GG2

**Comment by RigoFlores** [comment]
JC, en pru, el rfc que tiene el comportamiento como las barricas es XIQB891116QE4

**Comment by jccastillo0007** [comment]
done
