### ISSUE TITLE
Nomina 1.2 + CFDI 4.0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2047]
Está incluyendo el atributo de riesgo de trabajo, cuando no se ha capturado.
Ver el único empleado en pru, para el RFC emisor IIA.

**Comment by RigoFlores** [comment]
[sergio.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/9855281/sergio.xml.txt)


aquí está la evidencia

**Comment by RigoFlores** [comment]
Y no estoy seguro, pero posiblemente ocurra lo mismo para el conector, ya que es ahí donde se originó la investigación de este tema.

**Comment by jccastillo0007** [comment]
te refieres al campo RiesgoPuesto="1" ? 
porque no encontré Riesgo de Trabajo

**Comment by RigoFlores** [comment]
si

**Comment by jccastillo0007** [comment]
Listo.. ya esta en pru.
El problema era propio de web, hay que probar desde el conector
