### ISSUE TITLE
Las Barricas - Mejora 4 envío de correo personalizado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2048]
Al igual que se hizo para FIgueacero, se requiere que el envío del correo desde el coenctor, cuando se timbra lo de las barricas, sea personalizado.

Es decir con sus datos, su logo, sus colores.

Y otra cosa, es incluir como parte del cuerpo del correo, una imagen en el formato y tamaño que definamos para que se incluyan las promociones.
yo creo que de entrada podría ser de 550 pixeles de ancho x unos 500 de alto. Ese tamaño quizá cambiaría adelante muy posiblemente. O ya que vean el diseño, igual piden cambio.

Qué necesitas para implementar este primer cambio?

**Comment by RigoFlores** [comment]
<img width="222" alt="LogoCompuesto" src="https://user-images.githubusercontent.com/2912775/198749980-257a4309-ffbe-4067-aba9-ceec58da5d1d.png">

Aquí está el logo de las barricas.

**Comment by RigoFlores** [comment]
aquí está una imagen a incluir, es propuesta de dimensiones.
el contenido estará cambiando.
lo importante es que se llame igual y lo busque en la misma ruta, la que indiques tu.
<img width="300" alt="any" src="https://user-images.githubusercontent.com/2912775/198750294-d4438d24-3b42-4b05-8d99-d1e12f775a14.png">

**Comment by jccastillo0007** [comment]
oye, necesitamos definir las medidas del logo y la publicidad, no pueden enviar imágenes tan grandes
El logo debe ser de 180x227
y la publicidad, debe ser del tamaño que tienes en la imagen aquí en el ticket

**Comment by RigoFlores** [comment]
Pues le paso la spec del logo
lo de la imagen, ellos nos lo pasaron. Yo revisé las dimensiones, y no me parecieron fuera de lugar.
Si son grandes pero no tanto, en todo caso, dependerá de la resolución si la imagen es "pesada" o nó.

Yo creo que estamos cerrándonos a algo que ni siquiera hemos intentando.
No he visto un solo correo, con la imagen que te mandé (es decir la que me pasaron ellos), para poder decir si es grande o no. Simplemente no se tomó en cuenta.

**Comment by jccastillo0007** [comment]
Es que en el correo se debe definir el tamaño de la imagen... compara la del ticket con la que enviaste por whatsapp, solo tienes que abrirlas para que veas la diferencia

**Comment by RigoFlores** [comment]
Ya vi un correo que llegó y no se ve mal.
Aquí lo que se requiere es mantener la relación de aspecto, respecto al ancho. (para que no se distorsione).
Eso es todo.

**Comment by jccastillo0007** [comment]
Eso depende de la imagen, deben ajustar el logo

**Comment by RigoFlores** [comment]
OK, la spec que le pasaré es en pixeles:

                ancho   alto
logo:        230        180
publicidad:   600     800

Yo creo que la publicidad podría variar en el alto, siempre que respeten el ancho... cómo ves?

**Comment by jccastillo0007** [comment]
ya esta implementado con las medidas de arriba... chécale

**Comment by RigoFlores** [comment]
Si, lo de las medidas ya quedó.
Tengo las siguientes observaciones (internas, ya que aún faltarían las observaciones del cliente).

1) Por favor esta sección del asunto, cambiar en lugar de “LAS BARRICAS”, en el asunto, sería “Distribuidora Las Barricas”
2) Eliminar la información nuestra, tanto de redes sociales como los teléfonos de contacto.
Si acaso dejar lo de “Correo electrónico enviado por Factura-T” y en Factura-T asociarle el link de nuestra página web www.facturat.com

3) Ahora tomaremos el nombre del archivo del texto, indicando la ruta completa dentro del server:

imgPromocion=c:\lasbarricas\promociones\promoNoviembre2022-001.png

o tu indícame cuál es el formato adecuado para el nombre del archivo.

**Comment by jccastillo0007** [comment]
si, pero hay que recabar el feedback, para implementar todos los comentarios juntos.

**Comment by RigoFlores** [comment]
marca error, no he podido validarlo...

2022-11-09 13:10:56.0797 ERROR pool-2-thread-1 com.facturat.controller.CFD.creator.FacturaTiCreator CFD does not exist : C:\Conector4.0\FACTURAS\nov2022\PDF\PPM25858_MASO451221PM4_09nov2022_131042.pdf

Acabo de repetir el timbrado, y mismo problema.

**Comment by jccastillo0007** [comment]
puedes checar con la versión 12.0.5

**Comment by RigoFlores** [comment]
sigue igual, ahora marca este error:

2022-11-11 08:22:20,306 ERROR [pool-2-thread-1] (FacturaTiCreator.java:355) - CFD does not exist : C:\Conector4.0\FACTURAS\nov2022\PDF\PPM25858_MASO451221PM4_
11nov2022_082205.xml

Si te das cuenta está buscando un XML en la carpeta del PDF.

**Comment by RigoFlores** [comment]
chiales, parece un juego macabro. Ahora está pior, este es el mensaje. Busca un archivo con extensión .xml.xml, jeje

2022-11-12 07:38:05,246 ERROR [pool-3-thread-1] (FacturaTiCreator.java:355) - CFD does not exist : C:\Conector4.0\FACTURAS\nov2022\XML\PPM25858_MASO451221PM4_
12nov2022_073750**.xml.xml**


Aquí te dejo algunos archivos de texto para las barricas.

[TPPM025819.TXT](https://github.com/jccastillo0007/eFacturaT/files/9995071/TPPM025819.TXT)
[TPPM025662.TXT](https://github.com/jccastillo0007/eFacturaT/files/9995072/TPPM025662.TXT)
[TPPM025858.TXT](https://github.com/jccastillo0007/eFacturaT/files/9995073/TPPM025858.TXT)

**Comment by jccastillo0007** [comment]
listo, ya probé con el csd correcto

**Comment by RigoFlores** [comment]
OK, ya lo envía, pero no se ha atendido esto:

En la sección del asunto, cambiar en lugar de “LAS BARRICAS”, en el asunto, sería “Distribuidora Las Barricas”

Eliminar la información nuestra, tanto de redes sociales como los teléfonos de contacto.
Si acaso dejar lo de “Correo electrónico enviado por Factura-T” y en la palabra "Factura-T" asociarle el link de nuestra página web [www.facturat.com](http://www.facturat.com/)

Indicar cómo quedará el tema del archivo, es decir su nombre y ubicación. Ellos evidentemente no tienen acceso a nuestro server para cambiar ahí la imagen, entonces debe ser en el equipo donde está ejecutando el conector, donde se coloque la imagen a enviar.
