### ISSUE TITLE
PERMITE 'GRABAR' EL MISMO RFC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#205]
Aunque propiamente no lo almacena, tampoco notifica que algún rfc ya existe al momento de capturarlo.
Se requiere que al momento de capturar el RFC, si éste ya existe, cargue entonces el registro correspondiente y/o notifique al usuario de que ya existe el registro.

**Comment by jccastillo0007** [comment]
Estas hablando del keygenerator, o cuando das de alta un cliente en la version web / erp?

**Comment by RigoFlores** [comment]
perdón, se refiere a la nómina

**Comment by jccastillo0007** [comment]
fixed.

just kidding, not yet...

**Comment by jccastillo0007** [comment]
ahora si, fixed.
