### ISSUE TITLE
Las Barricas - Mejora 1

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2050]
En el conector de cada RFC emisor de las barricas se requiere lo siguiente.

Cuando se presente una situación de error en el intento de timbrado, que es cuando se renombra el archivo de texto:

a) Enviar un correo, indicando que se presentó el error mencionando: Fecha, Hora, Emisor, Receptor, total, Nombre de Archivo, motivo del error.
Las direcciones de correo a donde se enviará el correo, se tomarán de la siguiente etiqueta:
eMailError=correo1|correo2|correo3

Si ayuda mover esos archivos con condición de error, a una carpeta distinta, por ejemplo "ProcesadosError", estaría bien.

**Comment by jccastillo0007** [comment]
hmmm algo no me cuadra...
la pantalla es una opción mas de facturat, cada instancia que esta configurada con una llave de factura, podrá editar los archivos del rfc emisor, pero no los de los otros 2...

y, debe hacerse en la instancia que corre en el servidor, pues ahi es donde están los archivos de texto, en un folder específico, si hablamos de lo mismo ?

**Comment by RigoFlores** [comment]
Asunto. Se presentó un error al procesar el archivo XXXX.txt

Cuerpo del mensaje:

Fecha: 
Hora:
Nombre de Archivo:
Motivo del error:
Nombre del Emisor: 
RFC del Emisor:
Nombre del Receptor:
RFC Receptor:
CP Receptor:
Régimen Fiscal Receptor:

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
oyes, podrías poner la descripción del régimen fiscal?, es que el número pues no ayuda mucho que digamos.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
chiaaaaa----
mantener el número y la descripción.... pero bueno, pues la descripción ya dice algo.
