### ISSUE TITLE
Las Barricas - Mejora 2

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#2051]
b) Entregar una pantalla (aplicación) donde el usuario pueda editar los siguientes campos del archivo de texto, correspondientes al receptor:
Nombre, RFC, régimen fiscal y CP

En esa pantalla, el usuario deberá ELEGIR EL RFC EMISOR de una lista (de los 3 que existen para las barricas) y capturar el nombre del archivo, para luego tener posibilidad de editar los datos arriba mencionados y salvarlos.
Igualmente en esa pantalla, el usuario tendrá la opción para dar click en un botón de reprocesar el archivo de texto ya modificado (o incluso sin modificar). Esto causará que el archivo recién corregido (editado), sea colocado en la carpeta configurada del conector para dicho fin.

NOTA:
Esta pantalla creo que debe ser independiente a las pantallas actuales, ya que las instancias del conector para cada RFC emisor estarán en ejecución, y sus ventanas (GUI) no estarán disponibles mas que para el administrador del servidor.
Y el encargado de corregir estos datos, no será el administrador del servidor, sino alguien de contabilidad.

**Comment by jccastillo0007** [comment]
hmmm algo no me cuadra...
la pantalla es una opción mas de facturat, cada instancia que esta configurada con una llave de factura, podrá editar los archivos del rfc emisor, pero no los de los otros 2...

y, debe hacerse en la instancia que corre en el servidor, pues ahi es donde están los archivos de texto, en un folder específico, si hablamos de lo mismo ?


Hay que terminar de definir como va a funcionar esta pantalla

**Comment by RigoFlores** [comment]
ya lo platicamos, hace falta algo?

**Comment by jccastillo0007** [comment]
que acepten el funcionamiento y paguen

**Comment by RigoFlores** [comment]
Ya está platicado. El mismo usuario que levantará el sistema, será el que reprocese los archivos.
Así que está bien, una ventana adicional dentro de la misma aplicación actual.

Adelante con esto.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
No se donde está este ticket… desapareció..

 

 

De: JC ***@***.***> 
Enviado el: martes, 22 de noviembre de 2022 08:56 p. m.
Para: jccastillo0007/eFacturaT ***@***.***>
CC: RigoFlores ***@***.***>; Assign ***@***.***>
Asunto: Re: [jccastillo0007/eFacturaT] Las Barricas - Mejora 2 (Issue #2051)

 

listo

**Comment by RigoFlores** [comment]
si, el tema era la versión de java
con la versión 7 ya jaló
