### ISSUE TITLE
En web las tasas de los impuestos se anteponen con un signo de $

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2052]
por ejemplo así manda el IVA

IVA **$**16.00 %

ese signo $ no debe ir en ningún impuesto.

**Comment by jccastillo0007** [comment]
esto es en el pdf o en pantalla ?

**Comment by jccastillo0007** [comment]
fixed, se nota que nadie usa o le presta atención a este tipo de información en el pdf... chiaaa

**Comment by RigoFlores** [comment]
Si, detalles que se pasan por alto. Pero ya está.

**Comment by RigoFlores** [comment]
Oye, también modificaste las variables de los impuestos a nivel producto?
Según yo, también cambió ahí.
