### ISSUE TITLE
En web, no se está enviando el dato de la base IEPS cuando se incluye este impuesto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2053]
El IEPS, puede ser un impuesto trasladado o retenido.
Pero bueno, para la facturación de bebidas alcohólicas, es de tipo traslado.
Estoy haciendo pruebas en web, y a nivel general, la base de impuesto IEPS trasladado, la envía vacía...

reTotal=$804.25,baseTrasladoIva1=,baseTrasladoIva2=,baseTrasladoIva3=,tasaTrasladoIva1=$16.00,tasaTrasladoIva2=,tasaTrasladoIva3=,montoTrasladoIva1=$78.40,montoTrasladoIva2=,montoTrasladoIva3=,**baseTrasladoIeps1=,baseTrasladoIeps2=,baseTrasladoIeps3**=,tasaTrasladoIeps1=$26.50,tasaTrasladoIeps2=$53.00,tasaTrasladoIeps3=,montoTrasladoIeps1=$23.85,montoTrasladoIeps2=$212.00,montoTrasladoIeps3=,baseRetencionIva1=,baseRetencionIva2=,

si te das cuenta no envía la base de traslado IEPS, pero si la tasa o el monto de traslado IEPS.
(ahí puedes ver que a la tasa le antepone un $) Ese es oootro issue ya levantado.

**Comment by jccastillo0007** [comment]
pssss no esta enviando la base de ningún impuesto, no ma

**Comment by jccastillo0007** [comment]
Esta funcionalidad esta solo en standalone, no se solicitó para web, por lo cual no es un defecto

**Comment by RigoFlores** [comment]
no es un defecto, es un pinche defectote.
Mira hasta ahora no se ha ocupado.
Yo lo identifiqué con el demo que presenté ayer para otros clientes que venden bebidas con alcohol.

Quizá se necesite, quizás no.

Lo que es un hecho, es que la aplicación debería funcionar como maquinita, si existen esas variables debería llenarlas.

Pero bueno, por lo pronto no es imperativo atender este punto. Ahora si no cuesta mucho esfuerzo, podríamos atenderlo.
