### ISSUE TITLE
Las Barricas - Mejora 4 - Revisión 2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2054]
Primeros comentarios del cliente:

- El logo tendrá estas dimensiones: 230 px ancho x 78 px alto  (anexo el logo a este ticket)
- La imagen se reducirá al 65% para que se vea completa, esto es: 390 ancho x 520 px alto
- Eliminar toda la información desde donde dice "Estimado _nombre del receptor_" hasta donde indica "Fecha de Emisión"
- Eliminar donde dice "Correo electrónico enviado por FACTURA-T", así como los teléfonos de contacto y redes sociales  (chiaaa, te lo dije).
- 

Por lo pronto, esas son las observaciones.

![logoBarricas](https://user-images.githubusercontent.com/2912775/201759026-c54ac4a8-8b52-4c0b-96b9-242768c0a2cd.jpg)

**Comment by jccastillo0007** [comment]
necesito el logo del tamaño acordado, chiaaa

**Comment by jccastillo0007** [comment]
Oye esto esta medio raro:

Eliminar toda la información desde donde dice "Estimado nombre del receptor" hasta donde indica "Fecha de Emisión"

Sería quitar todos los detalles de la factura, es correcto?

**Comment by RigoFlores** [comment]
Es que en el código se define el tamaño de esa imagen, y que mantenga la relación de aspecto. Es como lo que hiciste con la imagen del promo.
No es estrictamente necesario que el logo tenga esas dimensiones, pero si esas proporciones (para que no se deforme). Si quieres yo lo hago mas chico, pero realmente según yo, no es necesario.

Y si, falta eliminar toda la información general de la factura. Así lo pidieron.

**Comment by RigoFlores** [comment]
en ambas imágenes, la spec del tamaño se gestiona desde el código.
Ahora mismo tienen unas dimensiones definidas, por eso el logo se ve chueco y la promo no cambió de tamaño.

El cambio es justo ese, modificar las dimensiones de ambos.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
la imagen de la promo, la veo igual.
No se ha reducido. 390 ancho x 520 px alto

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Aquí comentarios adicionales a nivel 2 todavía..

Se ve bien solo el espacio en blanco que existe entre la línea y la Leyenda “ Para mayor Inf….” Debe de ser menor y el espacio entre “*Anexo Encontrara ….” Y la promoción debe de ser mayor

Yo creo que debe quedar un espacio idéntico en ambos casos. 
Que sea el mismo que existe actualmente entre FAX... y ANEXO... que me parece es "un renglón"

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
![las barricas](https://user-images.githubusercontent.com/2912775/209586059-3d18fd9f-3a07-405b-a4de-9d4d635c8fbf.jpeg)
 

imagen de las barricas
