### ISSUE TITLE
Las Barricas - Mejora 3 Generación automática de un reporte diario.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2055]
Desde las pantallas del conector, hoy se puede obtener un reporte en formato cvs,
El menú es Consultas - Facturas.

Aquí lo que se requiere es generar automáticamente ese MISMO reporte de manera cotidiana.
Esto es, todos los días a las 23:55 hrs, se genera el reporte del día actual, o podría ser por ahí de las 02:00 (dos de la mañana) generar el reporte del día anterior.
El nombre del archivo debe distinguir la fecha a la que corresponde la información, y podría mantenerse en la carpeta actual de Reportes.

**Comment by jccastillo0007** [comment]
puedes checar la versión de hoy... va a generar un reporte cada minuto... es solo una prueba... checa si el reporte esta bien...
Mañana voy hacer lo necesario para que se genere una vez al día

**Comment by RigoFlores** [comment]
revisé el contenido del reporte.
Es igual al reporte que solicitas en la pantalla, entonces ahí está cumpliendo.
Del contenido no me clavé a revisar, pero la petición es que fuera el mismo y si, si es el mismo.
Ahora yo creo que hay que definir un horario para generarlo (00:30 hrs del nuevo día), así como una nomenclatura.

Que al leer el nombre del reporte, se conozca la fecha de su contenido. 

por ejemplo: Facturacion_17Nov2022.cvs

nos indica que es el reporte de facturación del 17 de noviembre del 2022

**Comment by jccastillo0007** [comment]
done.
La hora puede variar, depende de cuando levanten el facturat, y sobre todo si lo tiran y vuelven a levantar, pero no pasaran mas de 2 horas antes de que se genere el reporte del día anterior
