### ISSUE TITLE
Error en docto de pago - El valor del campo ImporteDR o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2057]
Ya revisé el problema con el documento de pago del cliente grupo cosh.
El mensaje lo que indica, es que el IVA reportado a nivel de alguna de las facturas pagadas, no corresponde con la base reportada.

Aquí todo se complica, porque son pagos parciales a las n facturas involucradas, entonces la base reportada de acuerdo al % pagado en cada factura, no se de donde está saliendo.

Necesitamos revisar cómo se calculan o se obtienen las bases reportadas en cada factura involucrada en el docto de pago.
Yo generé un excel, mismo que te dejaré aquí, junto con el XML que intentó timbrar.
En el excel te pongo varias columnas, entre ellas el % pagado en cada factura, con base a es % se calcula una base y un IVA.
Bueno pues esos cálculos son distintos a los que se reportan, entonces posiblemente por ahí va el error.

insisto, lo primero a revisar, es de donde o cómo se obtiene la base y el IVA de cada factura, cuando se trata de pagos parciales.

[ErrorDoctoPgo.xlsx.txt](https://github.com/jccastillo0007/eFacturaT/files/10061702/ErrorDoctoPgo.xlsx.txt)
[Pago Grupo Cosh.xml..txt](https://github.com/jccastillo0007/eFacturaT/files/10061703/Pago.Grupo.Cosh.xml.txt)

**Comment by RigoFlores** [comment]
Bueno, este issue tiene que ver ya con la forma en que el importeDR se está reportando.
De acuerdo a lo indicado, lo tomas de la BD y le aplicas el % del pago. No está mal, pero por manejar 6 decimales, el resultado no es lo preciso que se requiere.
Como ya se mencionó, este issue tiene dos soluciones o la combinación de ambas:

1)  El importeDR se calculará, tomando la baseDR, y multiplicándo por la tasa. Hoy en día haces sumatorias independientes de cada uno, y por ahí se va el error.
2) Manejar importeDR y baseDR, ambos con redondeo a 2 decimales.
3) Con la combinación de los 2 anteriores, se asegura todo, y creo que hasta el factor de ajuste se podría eliminar.

OJO, MUCHO OJO:
Para cada documento relacionado (factura pagada), se tomará la baseDR para TRASLADOS Y RETENCIONES de las combinaciones existentes de:
Impuesto - Tasa -TipoFactor 
Por ejemplo:   002 - 0.16 - Tasa  (es decir IVA con Tasa del 16%)
Pueden incluir varios IVAs, IEPS, o cualquier otro impuesto con distinta tasa en la misma factura (caso barricas). Entonces así se debe ir agrupando para el documento de pago

**Comment by jccastillo0007** [comment]
Esto es lo que ya se arreglo o cómo?

**Comment by RigoFlores** [comment]
cuando esté en pro

**Comment by RigoFlores** [comment]
en teoría ya está corregido con lo que se hizo
pero necesitamos subirlo a pro, y pedirle al cliente que emita. Hoy precisamente me volvió a preguntar

**Comment by RigoFlores** [comment]
oye, esto se subió a pro???

**Comment by jccastillo0007** [comment]
listo
