### ISSUE TITLE
documento de pago, datos origen para su correcto cálculo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2058]
Ya revisé el excel que inicialmente se planteó.
Y ahí se mencionan todos los cálculos correctamente.
Pero se parte de contar con lo siguiente para cada documento relacionado (factura pagada):

    <cfdi:Impuestos TotalImpuestosTrasladados="84277.71">
        <cfdi:Traslados>
            <cfdi:Traslado Base="22593.30" Importe="5987.22" Impuesto="003" TasaOCuota="0.265000" TipoFactor="Tasa"/>
            <cfdi:Traslado Base="86762.25" Importe="45983.99" Impuesto="003" TasaOCuota="0.530000" TipoFactor="Tasa"/>
            <cfdi:Traslado Base="12783.88" Importe="3835.16" Impuesto="003" TasaOCuota="0.300000" TipoFactor="Tasa"/>
            <cfdi:Traslado Base="177945.80" Importe="28471.34" Impuesto="002" TasaOCuota="0.160000" TipoFactor="Tasa"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

Siempre pregunté de donde se tomarían, si del XML o de la BD. NO importa de donde, siempre que se reflejen igualito.
En el XML, los datos de impuestos se reportan todos a 2 DECIMALES, entonces ¿en que momento se pasaron los cálculos a 6 decimales para el documento de pago???
Total, que no importaría que el IVA se calcule o no con base IEPS en la factura original ya que se tiene el resumen de impuestos en el XML. De ahí se tomarían los datos, que sirven para calcular en el documento de pago.

Anexo el XML que incluye el nodo de impuestos arriba mencionado.
SI fuera solo esa factura pagada al 100%, pues ahí están los datos de lo que se tendría que reportar en el documento de pago.

Si fuera parcial, pues aplica un porcentaje de ello.
y así con el resto de cálculos.

Ahora mismo, esa información reportada a nivel documento relacionado, NO ES LA MISMA QUE EN EL XML.
Creo que de ahí, se derivan el resto de problemas.

[PPM25662_MASO451221PM4_22nov2022_162041.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10071844/PPM25662_MASO451221PM4_22nov2022_162041.xml.txt)

Que solicita este issue???
Pues que los datos de impuestos reportados para cada documento relacionado, reflejen lo que su XML original reporta.

**Comment by jccastillo0007** [comment]
Esto es en base a la factura 1987, e ingresando el pago de esa
      factura: 590,747.22

total = 662907.39
pago de 590747.22
impuuesto iva de 91435.5
porcentaje del pago calculado = 0.8911459261300435
porcentaje del pago truncado =  0.891145
saldo insoluto = 72160.17
base de impuesto = 571471.89 // esta es la misma base que se uso en la factura original
se calcula el monto total de impuestos, de acuerdo al porcentaje pagado = iva de 91435.5 * porcentaje pagado de 0.891145 = 81482.2886475
se calcula la base del impuesto, de acuerdo al porcentaje pagado = base original de = 571471.89 * porcentaje pagado de 0.891145 = 509264.31741405

**Comment by RigoFlores** [comment]
en esta línea:
INCORRECTO
se calcula el monto total de impuestos, de acuerdo al porcentaje pagado = iva de 91435.5 * porcentaje pagado de 0.891145 = 81482.2886475

CORRECTO: TOMANDO LA BASE YA CALCULADA, CALCULAR EL IVA CON BASE A SU TASA. SI SE TOMA DEL XML Y SE LE APLICA EL % DEL PAGO, SE SALE DE RANGO.

la diferencia es menor, pero al utilizar 6 decimales, el margen de error es nada prácticamente.
Límite inferior: 81482.290626
Límite superior: 81482.290946

**Comment by RigoFlores** [comment]
a mi el excel me arroja:
e calcula el monto total de impuestos, de acuerdo al porcentaje pagado = iva de 91435.5 * porcentaje pagado de 0.891145 = 81482.290786

**Comment by RigoFlores** [comment]
si se calcula el impuesto a partir del IVA, no marcará error, así lo indica el excel.
Si se toma del XML, debería ser igual, pero por alguna razón, tiene un pequeño margen de diferencia, que hace que se salga de rango permitido.

**Comment by RigoFlores** [comment]
la solución puede irse por 2 caminos, o por la combinación de ambos.

1)  El importeDR se calculará, tomando la baseDR, y multiplicándo por la tasa. Hoy en día haces sumatorias independientes de cada uno, y por ahí se va el error.
2) Manejar importeDR y baseDR, ambos con redondeo a 2 decimales.
3) Con la combinación de los 2 anteriores, se asegura todo, y creo que hasta el factor de ajuste se podría elimiar.

OJO, MUCHO OJO:
Para cada documento relacionado (factura pagada), se tomará la baseDR para TRASLADOS Y RETENCIONES de las combinaciones existentes de:
Impuesto - Tasa -TipoFactor 
Por ejemplo:   002 - 0.16 - Tasa  (es decir IVA con Tasa del 16%)
Pueden incluir varios IVAs, IEPS, o cualquier otro impuesto con distinta tasa en la misma factura (caso barricas). Entonces así se debe ir agrupando para el documento de pago.

**Comment by RigoFlores** [comment]
El excel original, considera la solución con el punto 1. Esta planteado a 6 decimales, considerando que tenía que ser muy preciso.
El punto 2, nos da un excelente margen de maniobra, y desde el inicio todo se manejaría a 2 decimales.
La combinación de ambos, sería la gran solución. Peo bien podemos irnos por el punto 1 o por el punto 2 o por ambos.

**Comment by RigoFlores** [comment]
Pues al parecer si ya quedó.
Hay que ponerlo en producción pls...
