### ISSUE TITLE
Complemento de pago con Factoraje.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2059]
Existen algunos puntos importantes a considerar.
Básicamente antes solo existía un nodo de pagos, ahora se reportan los pagos a 3 niveles:
A nivel de documento relacionado
A nivel de pago
A nivel general  (puede incluir 1 o mas pagos. Hoy en día, el complemento normal, solo soportamos 1 solo nodo de pago. Para factoraje, desde la versión 3.3 se incluye un segundo nodo. Para la versión 4.0 se hará una copia del primer nodo de pagos)

a) El nodo pago a nivel general, debe incluir el monto pagado en el nodo principal y el nodo del factoraje. Este es nodo nuevo.
b) El nodo de factoraje debe ser una copia del nodo principal, pero de manera proporcional al pago. Hoy ya se maneja esa proporcionalidad, pero lo que no se incluye es todo el detalle de los impuestos. Bueno todo ese detalle, será proporcional al nodo principal. Aquí estoy anexando un ejemplo donde en el nodo principal pagaron 1100 y en el nodo de factoraje, pagaron 60.
Entonces todo se repite, pero de manera proporcional.

En este ejemplo solo se incluye el IVA, pero pues también se podría incluir cualquier otro impuesto, trasladado o retenido. En particular para el cliente en cuestión, sería ISR retenido.

**Comment by RigoFlores** [comment]
[xml_procesado_demo.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10079846/xml_procesado_demo.xml.txt)

Aquí el ejemplo ya timbrado. Este es el famoso segundo nodo. Mas o menos este primer bloque es el que ya se soporta ahora mismo. Digo mas o menos, porque tiene sus ajustes para la 4.0 como el tipoCambioP (obligatorio), objetoImpDR (no existía), y métododepago (ya no aplica).

			**pago20:Pago FechaPago="2022-11-23T13:24:01" FormaDePagoP="17" MonedaP="MXN" Monto="60.00" NumOperacion="factoraje" TipoCambioP="1">
				pago20:DoctoRelacionado EquivalenciaDR="1" Folio="477" IdDocumento="6AA09AC0-1B16-5DB2-8D4B-F20B299E559F" ImpPagado="60.00" ImpSaldoAnt="60.00" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="2" ObjetoImpDR="02">**

Esto es lo nuevo, lo que hay que hacer proporcional al pago. Una copia del primer nodo de pago, pero proporcional.

					<pago20:ImpuestosDR>
						<pago20:TrasladosDR>
							<pago20:TrasladoDR BaseDR="51.724000" ImporteDR="8.275840" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
						</pago20:TrasladosDR>
					</pago20:ImpuestosDR>
				</pago20:DoctoRelacionado>
				<pago20:ImpuestosP>
					<pago20:TrasladosP>
						<pago20:TrasladoP BaseP="51.724000" ImporteP="8.275840" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
					</pago20:TrasladosP>
				</pago20:ImpuestosP>
			</pago20:Pago>

**Comment by jccastillo0007** [comment]
De donde se obtiene o se define:
EquivalenciaDR="1"
ObjetoImpDR="02"

**Comment by RigoFlores** [comment]
Es una copia del nodo de pago original.
Es exactamente una copia, solo que el segundo nodo será un % del primero.
De ahí en juera es lo mismo

**Comment by jccastillo0007** [comment]
Listo, ya se esta generando el segundo nodo de pagos.. puedes probar con IIA y pagando una factura de 1160 a nombre de la TIA, el 21 de Diciembre.. ese pago me generó este XML
[PAGO15_IIA040805DZ4_TIA101020BP4_26Dec2022_192301.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10305530/PAGO15_IIA040805DZ4_TIA101020BP4_26Dec2022_192301.xml.txt)

Hay que correr toda tu suite de pruebas de pagos, porque cambié la forma de acumular los totales... checa pagando varias facturas y en varias monedas...

**Comment by RigoFlores** [comment]
No quedó jalando (factoraje) para facturas en USD y pago en MXN, pero creo que no tenemos ese escenario.

De otros escenarios que antes jalaban y ya no, he levantado tickets para que se atiendan.
