### ISSUE TITLE
ERP - NO SE PUEDE GENERAR RECIBO DE NÓMINA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#206]
Marca este error al momento de generar el recibo de nomina:
cvc-complex-type.4: Attribute 'pais' must appear on element 'cfdi:ExpedidoEn'.
cvc-complex-type.4: Attribute 'pais' must appear
 on element 'cfdi:ExpedidoEn'. (301)

**Comment by jccastillo0007** [comment]
fixed
