### ISSUE TITLE
Barricas - Impresión automática del PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2060]
En el servidor donde corre el conector, se darán de alta n impresoras, que físicamente se ubican en las distintas tiendas.
En el archivo de texto, vendrá el nombre de la impresora.
Cuando el nombre de la impresora se incluya, entonces que se mande a imprimir el PDF a esa impresora. Si el nombre no se incluye en el archivo, pues no hará nada de impresión.

en el layout sería:

impresora="brother alamos"

la nomenclatura, tu me la indicas.

Ahora mismo, le podemos indicar a la versión de escritorio, que imprima el PDF una vez que lo timbre. No se como haga eso, pero lo hace.

**Comment by jccastillo0007** [comment]
no tengo forma de probar este requerimiento, si acaso voy a tratar de agregar impresoras virtuales, y ver si funciona bien... 
tu tienes acceso a sus servidores para probar ahi? o tu tienes varias impresoras en la oficina?

**Comment by RigoFlores** [comment]
si tengo acceso al servidor de producción de ellos. Podría ver ahí de que se trata.
no tengo varias impresoras en la oficina. Solo una.

**Comment by jccastillo0007** [comment]
ok, te voy a pasar una versión del. conector, para correrla y ver que identifica como impresoras...

**Comment by jccastillo0007** [comment]
Puedes probar con la versión de hoy, creo que encontré el detalle de porque no salían en tu máquina y en el server

**Comment by RigoFlores** [comment]
Si, ya está apareciendo esta información (tomada de su servidor).

[FacturaT.log.txt](https://github.com/jccastillo0007/eFacturaT/files/10211147/FacturaT.log.txt)

**Comment by jccastillo0007** [comment]
Necesito saber que impresora podemos usar para hacer pruebas.

**Comment by RigoFlores** [comment]
Me comentan que para el servidor de ellos, esta: PaynoFacturasIP

No sería bueno, probar primero yo aquí en la impresora de la oficina? La de aquí sería esta:
2022-12-13 12:13:03.0011 DEBUG main com.facturat.view.Mainframe Printer info : sun.print.Win32PrintService@5b456a1f[printer=BROTHER ALÁMBRICA,name=<null>,port=<null>,mediaSizeNames=<null>,mediaPrintables=<null>,mediaTrays=<null>,printRes=<null>,mpaMap=<null>,nCopies=0,prnCaps=0,defaultSettings=<null>,gotTrays=false,gotCopies=false,mediaInitialized=false,mpaListInitialized=false,idList=<null>,mediaSizes=<null>,isInvalid=false,docPropertiesUI=<null>,uiFactory=<null>]

**Comment by jccastillo0007** [comment]
Ok, con el release 12.0.3, va a buscar la impresora BROTHER ALÁMBRICA", si la encuentra la va a tratar de utilizar
Te va a salir un mensaje cuando levantes facturat, y otro al imprimir, para que veas si logra identificar la impresora.
Dado que el nombre tiene un acento, vamos a ver si no genera problemas.
Ahorita esta hardcoded, si todo funciona bien, ya la parametrizo.
Ojo, de preferencia genera factura por conector, y luego por pantalla para ver si aplica en ambos.... según yo si.

**Comment by RigoFlores** [comment]
Si, ya jaló por conector. 
Ahora hay que hacer que lea el parámetro del archivo de texto. La etiqueta sugerida es:

impresora="brother alamos"

si va entre comillas dobles, sencillas, sin comillas, etc. Tu defines cómo queda.

**Comment by jccastillo0007** [comment]
checa con el release de hoy... aún no esta parametrizádo, pero ya esta buscando la impresora : PaynoFacturasIP checa si imprime en el servidor

**Comment by jccastillo0007** [comment]
Tienes razón, si se mando a imprimir... te mando estos mensajes para que puedas analizar el log


Aviso de que si se envía a imprimir

2022-12-15 08:41:02.0238 DEBUG pool-3-thread-1 com.facturat.controller.CFD.jasper.creator.JasperFacturaTi It is being sent to print 

Aviso de impresora default y de que impresora se intenta usar

2022-12-15 08:41:02.0255 DEBUG pool-3-thread-1 com.facturat.controller.CFD.jasper.creator.JasperFacturaTi Default printer is : PACHUCAANGOFI 
2022-12-15 08:41:02.0255 DEBUG pool-3-thread-1 com.facturat.controller.CFD.jasper.creator.JasperFacturaTi looking for printer : PaynoFacturasIP 

Aviso de que SI se encontró la impresora

2022-12-15 08:41:02.0255 DEBUG pool-3-thread-1 com.facturat.controller.CFD.jasper.creator.JasperFacturaTi Printer info : PaynoFacturasIP 
2022-12-15 08:41:02.0255 DEBUG pool-3-thread-1 com.facturat.controller.CFD.jasper.creator.JasperFacturaTi Printer found : PaynoFacturasIP 


La impresora en cuestión si se identificó, y en teoría si se mando a imprimir...  voy a parametrizar el nombre de la impresora para hacer pruebas con varias impresoras... no hay ningún mensaje de error, en teoría si se imprimió sin problemas

**Comment by jccastillo0007** [comment]
listo, ya esta parametrizado desde el archivo de texto:

impresora=patito

checa con impresoras que existan y que no existan... si no existen, se va por la configurada default.

**Comment by RigoFlores** [comment]
Mmmmmhhhh, nop. 
Si no llega ese parámetro en el texto, no debe intentar imprimir. 
Y si llega, solo intentará en la indicada, no en otras.

**Comment by jccastillo0007** [comment]
Si, esta bien, eso se lo puedo quitar al final, ahorita quiero que imprima en la default, para ver que facturat no tiene problemas para imprimir, aún si no encuentra la configurada.

**Comment by RigoFlores** [comment]
si jaló aquí en la oficina.
Estoy en espera que me confirme alguien allá (servidor de las barricas, en CDMX), para poder realizar las pruebas en conjunto.

**Comment by jccastillo0007** [comment]
que petch con estas pruebas ?

**Comment by RigoFlores** [comment]
se han ejecutado "casi" bien.
Resulta que se imprime en casi todas las impresoras, excepto en 1 de ellas. (precisamente la que nos dieron para probar nosotros, jejeje.) Esa nunca jaló, pero probaron con otras y si.

Entonces está medio raro, ya que dicen que puede estar de nuestro lado, pero pues ya les he dicho que busquen en la configuración de esa impresora, ya que es la única que no jala.

En esas estamos, por lo pronto cerraré este issue, y vamos viendo.
