### ISSUE TITLE
Las barricas - Subir los CFDIs (XML) versión 3.3, al conector 4.0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2061]
Se deben llenar las tablas correspondientes a las facturas (CFD, CFD_detail, etc) en la BD del conector.
Esto es para que se puedan emitir los complementos de pago, asociados a esas facturas 3.3

La intención es poner los XML ya timbrados en algún directorio que tu indiques, y que el conector suba esa info a su base de datos

**Comment by jccastillo0007** [comment]
Estoy trabajando en este requerimiento, esta semana ya debe quedar, la idea es agregar los XML a la base de datos actual que tengan, para evitar tener problemas de ids.
Miércoles o Jueves te la paso, para que pruebes, incluso poder generar el complemento de pago, que al final, es lo que necesitan

**Comment by jccastillo0007** [comment]
Puedes solicitar una muestra de XML, para hacer pruebas

**Comment by RigoFlores** [comment]
ok

**Comment by RigoFlores** [comment]
pedí bajar los xml de las barricas, del portal del sat
aquí están
no los procesa

**Comment by RigoFlores** [comment]
[3xml las barricas del SAT.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/10137092/3xml.las.barricas.del.SAT.zip.txt)

**Comment by jccastillo0007** [comment]
Listo, subí un nuevo release que ya procesa los archivos del zip... esos archivos no incluían el tipo de cambio, y marcaba error.

**Comment by RigoFlores** [comment]
oye, revisé los otros XML que sigue sin procesar.
Lo que vi, es que incluyen el nodo de addenda.
Y dentro de ese nodo, como que viene un desmadre de info, pero al final, pues eso no es parte del XML.

Porqué se está analizando la parte de addenda, cuando eso no es parte del XML que llega al SAT?

**Comment by RigoFlores** [comment]
Estoy tomando los XML que bajó del SAT. En particular una factura, la 3981.

[PPM 3981.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10142320/PPM.3981.xml.txt)

Si los sube, pero los impuestos al momento de emitir el complemento de pago, están chuecos.
Este es el archivo de texto del pago, solo hay que cambiar el UUID.

[pagoPPM_3981.txt](https://github.com/jccastillo0007/eFacturaT/files/10142326/pagoPPM_3981.txt)



En cuanto a impuestos, el XML contiene lo siguiente:

<img width="364" alt="traslados 3981" src="https://user-images.githubusercontent.com/2912775/205329494-2c77bcfa-dbaa-4c59-b8fd-a04c6dd8d538.PNG">

El documento de pago, no requiere reportar el IEPS a nivel general (003 ). Solo a nivel docto relacionado y a nivel trasladosP.

Entonces solo debería reportar el IVA (002), que en este caso de acuerdo al XML original, todo es del 16% y corresponde a $33,948.34.

El documento de pago generado desde el conector reporta lo siguiente:

![image](https://user-images.githubusercontent.com/2912775/205331780-daf01116-a4b9-448c-9fbb-6ab6a04c3501.png)


pero ese XML no incluye 3 tasas de IEPS, solamente 2. Aquí también se puede observar eso...

<img width="623" alt="ieps 3981" src="https://user-images.githubusercontent.com/2912775/205332120-31b6d92c-161f-4aca-ab5a-2b31f1657d72.PNG">

**Comment by RigoFlores** [comment]
La factura siguiente tiene 2 tasas de IEPS y 2 tasas de IVA diferentes. También se hace pelotas ahí.

[PPM 3983.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10142651/PPM.3983.xml.txt)

**Comment by jccastillo0007** [comment]
Pues si había varios errores en la importación del xml.. ya lo corregí con la versión que estoy subiendo, ya generó el xml de pago.
[PAGO327_MASO451221PM4_03Dec2022_210949.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10147791/PAGO327_MASO451221PM4_03Dec2022_210949.xml.txt)
