### ISSUE TITLE
Conector 4.0, no es posible emitir un complemento de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2062]
Aparentemente "se descompuso" o no sé porqué lo que antes jalaba ahora ya no.
Aquí dejo un par de archivos, uno para generar la factura de las barricas y el otro el complemento de pago.
Con ello podrás reproducir el problema, pero si hay que cambiar el UUID del archivo de texto, para el pago.

[pagoPPM25819.txt](https://github.com/jccastillo0007/eFacturaT/files/10118555/pagoPPM25819.txt)
[TPPM025819.TXT](https://github.com/jccastillo0007/eFacturaT/files/10118558/TPPM025819.TXT)

**Comment by jccastillo0007** [comment]
corrí la prueba con los archivos de arriba, y marco un error del receptor

CFDI40144 : El campo Nombre del receptor, debe encontrarse en la lista de RFC inscritos no cancelados en el SAT.

Este es el XML generado

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pago20="http://www.sat.gob.mx/Pagos20" Version="4.0" Serie="PAGO" Folio="327" Fecha="2022-11-29T20:14:12" Sello="nlBkO5fDUZ9uao4M/mzt/E8ZZARjK4y24ZgLMTrOSRhJwohCs1D8P7kqypqtJHagT2aq3X08N8AXFYFYpWUVvVBQ6cwqPvFPskjJH2h8NdhzlvAxL/AIgHcHYyFRNajDReSZSgc9EXSMVZ/xVK5KRkqUz7BexEATAcFrqXyj/C8njabuuZuqePCbaWYvSqathCDaUHHgiKbWKmjEf8Gpv1SV4PcltLsbigMW4wiS5V7wyHUj0WoyGx0Q+WlNLbsewxyLDMUgVcd86wsLXM6bfwabbdQlyN6bfpspQwvRsJwlyMgIwo/RikO3JGtj8q+zwHBlMXkW8khqjn3ZYF4z1A==" NoCertificado="30001000000400002336" Certificado="MIIFjjCCA3agAwIBAgIUMzAwMDEwMDAwMDA0MDAwMDIzMzYwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWRpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMTkwNTI5MTk1MjQyWhcNMjMwNTI5MTk1MjQyWjCBtTEeMBwGA1UEAxMVQkVSRU5JQ0UgWElNTyBRVUVaQURBMR4wHAYDVQQpExVCRVJFTklDRSBYSU1PIFFVRVpBREExHjAcBgNVBAoTFUJFUkVOSUNFIFhJTU8gUVVFWkFEQTEWMBQGA1UELRMNWElRQjg5MTExNlFFNDEbMBkGA1UEBRMSWElRQjg5MTExNk1HUk1aUjA1MR4wHAYDVQQLExVCRVJFTklDRSBYSU1PIFFVRVpBREEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCp6FMIaf6NrmG278bVeJIlOEx3c7FepPkVLLbic9z28ws49OpajLa0xlmIb17lcPZWfm8VGRbRWHa6PY8KxbuBtN+k2/KjpVztGh3PPyHIVT6QoXJczzQaNMcuN3W+KoHGa4EvAqG8MchtTqhXX8U8Lds83pSRiPJKNCJ3x/CfnAK6LlxFi3NdIHYVRqNE/R4TPe38VbGVR/9wLsgGQhrhhQwWXnUcPBF5WB/myQEJJq/esuKWYlLugzJfZjklUs2ThrjSZM6YvBujmFqCz4t3fJU0lYEDNI8rT1PHy9LFdiXNeUZQf5c+1TfTdhdGQmYUWLdkyRSdF3tIkPb2+exHAgMBAAGjHTAbMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQDAgbAMA0GCSqGSIb3DQEBCwUAA4ICAQAqYMNNHiDbDCrIGsNKpeT24HZVJ2gIJ8PuB/DdKxAFBANTp6KRQFb+7FoyVhP29H55DRre4Cyfrr0Bi5ZwGEaAv+D6/41N9M4/2TClgyZp4ppXPYZy0+AVM3ySsFwUfdancTeZjy0X9ETFcjj190x5W6FA63FaaX+YpuCgougKhi/cXT6HiFvi+STeMdsygJNyCuVXgC3hGnwYnBDheLp2HFuVI0ugF/zRnPaMFcRB1IL8Zi1wtg451E0YeGLm2x+WhWSZdzJoz+0NK+bC3+13JVUjj7wypfXMVwC5/x4H50pFbNnVp+jcgKvP9k+DQ2Qibe6kSrmKF57sndO/PtnK2g8ukKJmShDTfZJlSSf+xBZwbJ6yqYvmGuxtSd2kr4UFJ4jjFS7WeqCZ0TyVZ+sdQ6SJk2ed64YgSHsPHqmIPIn9acrLt/B+ycEACIC8Wb1AbvztKnb0dxCuuU2XfszSG08XHs2RA7hVmbe1d58lhIX7b32YUH5VmgOsSezUF4ji46Blci86l4nb9VbxAmrXAQtRWEiBAK+TR3k33MhCom/Dub7Xo16HJuJkEjleFdhmwCDpqs9/XFcfGybvKXTkd1OjaMkJ1XKzsNGQfKpXsFVl+O4vGsFMNmyU8c2YbPK+D2XwMJSeHjYFs6Oyc/TljED+/577EBElcF5Diu1vTw==" SubTotal="0" Moneda="XXX" Total="0" TipoDeComprobante="P" Exportacion="01" LugarExpedicion="72990" xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd http://www.sat.gob.mx/Pagos20 http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos20.xsd">
    <cfdi:Emisor Rfc="XIQB891116QE4" Nombre="BERENICE XIMO QUEZADA" RegimenFiscal="626"/>
    <cfdi:Receptor Rfc="MASO451221PM4" Nombre="MRIA OLIVIA MARTINEZ SAGAZ" DomicilioFiscalReceptor="80290" RegimenFiscalReceptor="626" UsoCFDI="CP01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago" ValorUnitario="0" Importe="0" ObjetoImp="01"/>
    </cfdi:Conceptos>
    <cfdi:Complemento>
        <pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="18929.89" TotalTrasladosBaseIVA16="11163.26" TotalTrasladosImpuestoIVA16="1786.12"/>
            <pago20:Pago CtaBeneficiario="036680500105247319" CtaOrdenante="1234567890" FechaPago="2017-07-10T12:00:00" FormaDePagoP="03" MonedaP="MXN" Monto="18929.89" NumOperacion="REF. 123" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="25819" IdDocumento="FBED4F0D-9BC2-5519-9B02-4633BA34741D" ImpPagado="18929.89" ImpSaldoAnt="18929.89" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="1" ObjetoImpDR="02" Serie="PPM">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="1967.390000" ImporteDR="521.358350" ImpuestoDR="003" TasaOCuotaDR="0.265000" TipoFactorDR="Tasa"/>
                            <pago20:TrasladoDR BaseDR="8518.680000" ImporteDR="4514.900400" ImpuestoDR="003" TasaOCuotaDR="0.530000" TipoFactorDR="Tasa"/>
                            <pago20:TrasladoDR BaseDR="397.880000" ImporteDR="119.364000" ImpuestoDR="003" TasaOCuotaDR="0.300000" TipoFactorDR="Tasa"/>
                            <pago20:TrasladoDR BaseDR="11163.260000" ImporteDR="1786.121600" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="11163.260000" ImporteP="1786.121600" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                        <pago20:TrasladoP BaseP="397.880000" ImporteP="119.364000" ImpuestoP="003" TasaOCuotaP="0.300000" TipoFactorP="Tasa"/>
                        <pago20:TrasladoP BaseP="1967.390000" ImporteP="521.358350" ImpuestoP="003" TasaOCuotaP="0.265000" TipoFactorP="Tasa"/>
                        <pago20:TrasladoP BaseP="8518.680000" ImporteP="4514.900400" ImpuestoP="003" TasaOCuotaP="0.530000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>
        </pago20:Pagos>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by RigoFlores** [comment]
con ese receptor hago mis pruebas. Acabo de generar la factura con ese archivo. Ta recién salida del horno


[PPM25819_MASO451221PM4_29nov2022_203919.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10118885/PPM25819_MASO451221PM4_29nov2022_203919.xml.txt)

**Comment by jccastillo0007** [comment]
si, yo también generé la factura sin problemas, pero en el pago marcó el error del nombre del receptor, tal vez sea otra cosa, luego finkok no muestra bien los errores, habrá que checar con ellos

**Comment by RigoFlores** [comment]
el archivo que subí aquí para generar el pago, si tenía mal el nombre, jeje.
Y es que con ese archivo, estuve haciendo pruebas de edición de archivo.
