### ISSUE TITLE
Plataforma en Línea - Cuando se selecciona el impuesto IVA - NA, no enviar nodo de impuestos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2063]
Ahora mismo cuando eligen impuesto trasladado IVA - NA, es decir no es exento, ni tasa 0, manda esto al XML.

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84101600" NoIdentificacion="DON-EFE" Cantidad="1.00" ClaveUnidad="M4" Unidad="M4" Descripcion="Financiación de Ayudas Donativo en Efectivo" ValorUnitario="9757.240000" Importe="9757.240000" ObjetoImp="01"/>
    </cfdi:Conceptos>
    <cfdi:Impuestos/>

EL PAC dice que no debe ir el nodo de impuestos vacío. Es decir no debe existir esta línea:       <cfdi:Impuestos/>

**Comment by RigoFlores** [comment]
[ERROR NO CLASIFICADO.XML.txt](https://github.com/jccastillo0007/eFacturaT/files/10127419/ERROR.NO.CLASIFICADO.XML.txt)

Aquí el XML que se intentó timbrar.

**Comment by jccastillo0007** [comment]
subí un posible fix a pru

**Comment by RigoFlores** [comment]
sabes que pasa... que facture hoy lo acepta como está ahora mismo y finkok no.
Ayer que se presentó este problema facturehoy marcó el error raro (el que dices que debió presentarse en todos los casos), y extrañamente si reintentó por finkok.

entonces, yo creo que lo dejamos como estaba antes. 
El error se dió por el primer problema que ya se resolvió.

Me confirmas que ya lo regresarás???

**Comment by RigoFlores** [comment]
y si, ya revisé en pruebas y ya lo timbró, pero es mejor que lo timbre fhoy que finkok.
Chiaaa, ni entre los putos pacs se ponen de acuerdo.

Si, hay que regresarlo pls.

**Comment by jccastillo0007** [comment]
ok, como quiera, nunca se liberó a prod

**Comment by RigoFlores** [comment]
así es, no se liberó a pro, pero hay que asegurar que no se inyecte a producción en el siguiente rilís...

te puedes asegurar por favor?

**Comment by jccastillo0007** [comment]
si, ya eliminé esa validación

**Comment by RigoFlores** [comment]
ya
