### ISSUE TITLE
Las Barricas - Documento de pago, no reporta correctamente el IVA del 16%

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2065]
No está reportando correctamente el importe del IVA del 16% en el documento de pago.
Si checas los documentos anexos, que son la factura y su pago correspondiente, notarás diferencias en la sección de los impuestos.

El XML dice:
<cfdi:Impuestos TotalImpuestosTrasladados="97650.82"
<cfdi:Traslados
<cfdi:Traslado Importe="18304.31" Impuesto="003" TasaOCuota="0.265000" TipoFactor="Tasa" /
<cfdi:Traslado Importe="44713.57" Impuesto="003" TasaOCuota="0.530000" TipoFactor="Tasa" /
<cfdi:Traslado Importe="34632.94" Impuesto="002" TasaOCuota="0.160000" TipoFactor="Tasa" /
</cfdi:Traslados
</cfdi:Impuestos

El documento de pago, por su lado dice:

                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="69072.840000" ImporteDR="18304.302600" ImpuestoDR="003" TasaOCuotaDR="0.265000" TipoFactorDR="Tasa"/>
                            <pago20:TrasladoDR BaseDR="84365.230000" ImporteDR="44713.571900" ImpuestoDR="003" TasaOCuotaDR="0.530000" TipoFactorDR="Tasa"/>
                            <pago20:TrasladoDR BaseDR="153438.070000" ImporteDR="24550.091200" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="153438.070000" ImporteP="24550.091200" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                        <pago20:TrasladoP BaseP="69072.840000" ImporteP="18304.302600" ImpuestoP="003" TasaOCuotaP="0.265000" TipoFactorP="Tasa"/>
                        <pago20:TrasladoP BaseP="84365.230000" ImporteP="44713.571900" ImpuestoP="003" TasaOCuotaP="0.530000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>

Si revisas el iva del 16%, es incorrecto.

Aquí tienes el XML original, el archivo de texto con su pago y el xml de pago generado.

[PPM 3982.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10159297/PPM.3982.xml.txt)

[pagoPPM_3982.txt](https://github.com/jccastillo0007/eFacturaT/files/10159298/pagoPPM_3982.txt)

[PAGO6_MASO451221PM4_05dic2022_174227.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10159299/PAGO6_MASO451221PM4_05dic2022_174227.xml.txt)

**Comment by jccastillo0007** [comment]
no maaaa, o estoy bien wey, o acabo de descubrir algo muy raro... checa el primer producto del xml que enviaste

		<cfdi:Concepto Cantidad="6" ClaveProdServ="50202200" ClaveUnidad="XBX" Descripcion="RON HAVANA CLUB AÑEJO ESPECIAL 700 ML" Importe="6657.78" ValorUnitario="1109.63">
			<cfdi:Impuestos>
				<cfdi:Traslados>
					<cfdi:Traslado Base="10186.40" Importe="1629.82" Impuesto="002" TasaOCuota="0.160000" TipoFactor="Tasa" />
					<cfdi:Traslado Base="6657.78" Importe="3528.62" Impuesto="003" TasaOCuota="0.530000" TipoFactor="Tasa" />
				</cfdi:Traslados>
			</cfdi:Impuestos>
		</cfdi:Concepto>

la base del iva lo tiene como 10186.40, peeeeero de donde sale ese número... si el importe del producto dice 6657.78, e incluso coincide con la base del impuesto 003... 

por eso no cuadran las cifras en el documento de pago... el proceso de facturat toma el importe para ir acumulando la base de cada impuesto-tasa... 

chiaaaa

**Comment by RigoFlores** [comment]
No está nada raro. Digamos que lo distinto, es que ellos calculan el IVA base IEPS.
Eso que significa, que al importe le calculan el IEPS.
Y el IVA base IEPS, se calcula con la base de importe + IEPS, por ello da los números que tu estás indicando.

Por ello, la documentación, y la petición era ir tomando la base de los Impuestos del XML. 
En el caso de muchos productos, para cada tipo de traslado o retención, en la combinación de tipo - tasa - tasaCuota, ir acumulando las bases.

si quieres lo platicamos, porque esto es un tema que si debe quedar clarito.

**Comment by jccastillo0007** [comment]
ok, al rato te marco, como a las 5

**Comment by jccastillo0007** [comment]
Listo, subi el fix al dropbox

**Comment by RigoFlores** [comment]
Listo, ya quedó bien.
Este era un tema delicado, pero al modificar únicamente el origen de la base, y mantener todo lo demás igual, eso fue la clave para que funcionara sin problema.
Ya hice varias pruebas... una factura, varias facturas, varios impuestos, pago total, pagos parciales, todas ellas en MXN y funciona.
No haré las de USD, porque creo que ahí no aplica lo del IEPS, pero igual en un rato que tenga libre, puedo revisar ese punto.

Aquí la pregunta, para el tema de la base del IVA y del IEPS, tendríamos el mismo problema en WEB????

**Comment by jccastillo0007** [comment]
Si, en web es igual que como estaba en standalone, pero ya lo ajuste

**Comment by jccastillo0007** [comment]
falsa alarma, en web al parecer no se tiene ese problema
