### ISSUE TITLE
Web - Documento de pago incorrecto, cuando las facturas no incluyen IVA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2066]
Te mandé el correo.

SI QUIERES EMITIR UN DOCUMENTO DE PAGO, CUBRIENDO EL 100% DE ESTAS 2 FACTURAS MARCA ERROR.
EL ASUNTO ES QUE ESTAS 2 FACTURAS NO CONTIENEN IVA.
UNA FACTURA SOLO CONTIENE IEPS DE 0% Y LA OTRA TIENE IEPS CON TASA 6% Y TAMBIÉN CON TASA 0%.
EL ESTÁNDAR INDICA QUE A NIVEL GENERAL DEL PAGO, NO SE REPORTA EL IEPS. SOLO A NIVEL DE DOCTO RELACIONADO Y DE PAGO.

EL CHISTE ES QUE NO INCLUYE IVA, PERO EN EL DOCUMENTO DE PAGO SI LO ESTÁ REPORTANDO (A NIVEL GENERAL).

[soloIEPS.txt](https://github.com/jccastillo0007/eFacturaT/files/10169897/soloIEPS.txt)

[A1096_ANQ940906TJ9_GPX080128BU1_06Sep2022_104926-4.pdf](https://github.com/jccastillo0007/eFacturaT/files/10169898/A1096_ANQ940906TJ9_GPX080128BU1_06Sep2022_104926-4.pdf)
[A1094_ANQ940906TJ9_GPX080128BU1_23Aug2022_115621-1.pdf](https://github.com/jccastillo0007/eFacturaT/files/10169899/A1094_ANQ940906TJ9_GPX080128BU1_23Aug2022_115621-1.pdf)

**Comment by RigoFlores** [comment]
ya me están presionando con esto...

**Comment by jccastillo0007** [comment]
Esto no es cierto:

"EL CHISTE ES QUE NO INCLUYE IVA, PERO EN EL DOCUMENTO DE PAGO SI LO ESTÁ REPORTANDO (A NIVEL GENERAL)."

El archivo soloIEPS.txt solo tiene impuestos IEPS, no IVA.... tons cual es el pedo?

**Comment by jccastillo0007** [comment]
O te refieres a los totales:

"TotalTrasladosBaseIVA0="23050.24" TotalTrasladosImpuestoIVA0="0.00""?

**Comment by RigoFlores** [comment]
si, claro. Ahí se menciona un IVA que no existe en la factura.

**Comment by RigoFlores** [comment]
Nivel general, es el nodo de mas alto nivel, es el resumen del pago.

            <pago20:Totales MontoTotalPagos="33534.91" TotalTrasladosBaseIVA0="23050.24" TotalTrasladosImpuestoIVA0="0.00"/>

**Comment by jccastillo0007** [comment]
fixed.. hay que probarlo en pru primero

**Comment by RigoFlores** [comment]
liste and validated
