### ISSUE TITLE
LAS BARRICAS - En general aplica para todo el conector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2067]
Si un archivo de texto es procesado correctamente, y en el directorio de procesados existía un archivo de error.log correspondiente al archivo ya procesado, eliminarlo para evitar confusiones.

Esto es:

En las barricas, si un archivo falla en su procesamiento, 
1) en el directorio de procesados se genera un .error.log
2) el archivo que no se procesó, se mueve a reintenteMasTarde

Si el archivo que se movió a reintenteMasTarde, se edita y se arregla y se manda a procesar, entonces la pasará finalmente a procesados. Peeeeeero, deberá borrar entonces el archivo que se generó en el punto (1) arriba mencionado. Ello para evitar confusiones.

**Comment by jccastillo0007** [comment]
fixed, con el release de hoy

**Comment by RigoFlores** [comment]
ya probé con la versión de hoy, y no jaló.
mantiene el archivo .error.log

**Comment by jccastillo0007** [comment]
Fixed... con el release de hoy.

Ojo, excepto para la Barricas, cuando un archivo falla, se mueve a Procesados con el prefijo ERROR_file.txt... para que funcione el tema de borrar el log, la siguiente vez que se procese el archivo de forma correcta, deben quitarle el prefijo ERROR_ de lo contrario no encontrará el archivo de log a borrar.

**Comment by RigoFlores** [comment]
No, hacerlo manual así como dices, no lo harán.
Yo creo que en las barricas, debe manejarse igual con el prefijo de error, el archivo .log.
Por que se cambió esa nomenclatura para las barricas?

**Comment by jccastillo0007** [comment]
Para las barricas no se cambia el nombre, ya que los archivos con error se mueven a un folder diferente, para los otros casos se mueven a procesados con prefijo de ERROR_, de ahi viene este problema. Se deben renombrar con el prefijo ERROR_ porque ahi se mueven los que tuvieron errores y los que no...

**Comment by RigoFlores** [comment]
pues lo cerramos porque quedó para las barricas, pero realmente para el conector, no quedó, porque nadie renombrará los archivos log
