### ISSUE TITLE
LAS BARRICAS - Edición de archivos de texto, al momento de almacenarlos les trunca el contenido.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2068]
Cuando editas algunos archivos, y los guardas, los "mocha", es decir los guarda incompletos y pues al intentar reprocesarlos, truena al no contar con toda la info del layout.

Aquí te dejo algunos de los archivos (originales), que al menos en windows (tanto en el servidor, como en mi compu), los truncó después de haberlos editado desde el menú de las barricas, en facturat conector.

[TPPM026738CopiaBAD.txt](https://github.com/jccastillo0007/eFacturaT/files/10188751/TPPM026738CopiaBAD.txt)
[TPPM026737CopiaBAD.txt](https://github.com/jccastillo0007/eFacturaT/files/10188752/TPPM026737CopiaBAD.txt)
[TPPM026732CopiaBAD.txt](https://github.com/jccastillo0007/eFacturaT/files/10188753/TPPM026732CopiaBAD.txt)
[TPPM026729copiaBAD.txt](https://github.com/jccastillo0007/eFacturaT/files/10188754/TPPM026729copiaBAD.txt)
[TPPM026727copiaBAD.txt](https://github.com/jccastillo0007/eFacturaT/files/10188755/TPPM026727copiaBAD.txt)
[TPPM026725CopiaBAD.txt](https://github.com/jccastillo0007/eFacturaT/files/10188756/TPPM026725CopiaBAD.txt)
[TPPM026739CopiaBAD.txt](https://github.com/jccastillo0007/eFacturaT/files/10188757/TPPM026739CopiaBAD.txt)

**Comment by RigoFlores** [comment]
Estos son ejemplos de archivos que SI edita y guarda correctamente.

[TPPM026726copia.txt](https://github.com/jccastillo0007/eFacturaT/files/10188769/TPPM026726copia.txt)
[TPPM026728copia.txt](https://github.com/jccastillo0007/eFacturaT/files/10188770/TPPM026728copia.txt)
[TPPM026730copia.txt](https://github.com/jccastillo0007/eFacturaT/files/10188771/TPPM026730copia.txt)
[TPPM026731Copia.txt](https://github.com/jccastillo0007/eFacturaT/files/10188772/TPPM026731Copia.txt)


Hay otro caso, que no he podido reproducir, donde de plano el archivo se guarda con 0bytes, es decir se borra completamente la info.

**Comment by jccastillo0007** [comment]
fixed
