### ISSUE TITLE
Las Barricas - Reporte Automático de facturación, detalles

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2069]
Nos están pidiendo lo siguiente:

a) Que el archivo se guarde en una ruta fija. Propongo que sea tomada del último parámetro de la pantalla de configuración del conector. (Directorio para generación del PDF). La otra es definir un directorio fijo, debajo de Factura-T, por ejemplo reporteDiario.
b) Que tenga un nombre fijo. Ya le hice ver el riesgo de este cambio. El nombre solicitado es FACTURAS.cvs
c) Eliminar el encabezado de las columnas.
d) Generarlo a una hora fija. 10:00 PM

**Comment by jccastillo0007** [comment]
a) quedo usando el path configurado en "Directorio para generación del PDF"
b) done, ojo, se va a reemplazar cada día, no se acumula
c) done
d) se va a generar entre 10 y 10:30 pm
