### ISSUE TITLE
ERP - NO ALMACENA EMPLEADOS EN NOMINA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#207]
AUNQUE INDICA QUE FUE EL REGISTRO FUE ALMACENADO CON EXITO, NO LO ESTÁ ALMACENANDO.
ECHARLE UNA REVISADA, YA QUE ANTERIORMENTE SE HABÍA LEVANTADO, Y NO SE LLEGÓ A NADA.

**Comment by jccastillo0007** [comment]
favor de detallar mas el escenario, rfc, datos capturados, fecha y hora , etc... algo que me de mas idea de como reproducirlo o detectarlo en el log.
