### ISSUE TITLE
Las Barricas - Imagen a incluir en los correos, tomarla del servidor.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2070]
Pues si, tal cual te comenté en su momento, lo que requieren es que se tome del servidor, para que ellos la cambien a placer.
Se podría tomar y actualizar una vez al día.
O en el servidor un cron que se traiga la imagen.

Lo que aún no me quedó claro, porqué en Figueacero si podríamos hacer eso, claro era un PDF, pero igual se tomaba del equipo donde corre el conector. De hecho con base a esta feature que ya tenemos, fue que consideré implementar este requierimiento.

De hecho, para eso existe este parámetro en el properties:
#para enviar un PDF adicional en el correo
defaultPDF=C:\\nada\\ofertas.pdf

Porqué no puede ser igual?

**Comment by RigoFlores** [comment]
Les pedí una URL pública, pero ellos no manejan eso...

**Comment by jccastillo0007** [comment]
Esto no existe:

"De hecho, para eso existe este parámetro en el properties:
#para enviar un PDF adicional en el correo
defaultPDF=C:\nada\ofertas.pdf"

**Comment by jccastillo0007** [comment]
dado que el email se manda como html, para darle el formato visual adecuado, en html no se puede agregar una imagen desde una ubicación local... solo desde una url...
La opción es agregar la imagen como un attachement, te mandé un correo desde facturat como ejemplo, dime si eso funciona?

La otra opción es nosotros controlar las imágenes

**Comment by RigoFlores** [comment]
realmente la imagen en html, si se puede tomar de una ubicación local. Todas las pantallas que trabajé, así lo hacen. Igual puede ser de una url pública, pero igual local. Lo que si, es que local, significa eso, tendría que estar en nuestro servidor, a menos que el HTML se arme en el servidor de ellos, entonces si se puede como lo quieren.

La pregunta es, donde se arma ese HTML?

**Comment by jccastillo0007** [comment]
son cosas diferentes, cuando creas un html y haces referencia a un archivo local, y abres tu html de forma local si funciona, pero si ese html se lo mandas a alguien y lo abre, no va a ver la imagen que tienes tu de forma local..., en aplicaciones web, funciona porque las aplicaciones están deployadas en un servidor, y de ahi toma la imagen.
En el caso de correos, se arman en facturat, pero cuando llega al inbox de X persona, la única forma de ver la imagen es con una URL pública o en attachement.

**Comment by RigoFlores** [comment]
Ellos nos facilitarán la imagen y nosotros la pondremos en nuestro servidor.
Prefieren eso en lugar de que vaya como adjunto.

Tons, pls libera la versión que considere este punto
