### ISSUE TITLE
LAS BARRICAS - ya no está enviando el correo desde windows

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2072]
He recibido correos de pruebas de figueacero, y creo tuyas también.
Pero desde windows, en mi lap o en el server, no están enviándose.

Aquí te dejo el log, y un archivo básico de pruebas con el que probé. 
Creo que dejó de funcionar, cuando se agregó la pantalla de las barricas, la de edición de archivos.

[FacturaT.log](https://github.com/jccastillo0007/eFacturaT/files/10198157/FacturaT.log)
[facturaBasica.txt](https://github.com/jccastillo0007/eFacturaT/files/10198158/facturaBasica.txt)

**Comment by jccastillo0007** [comment]
hoy hice el setup en una laptop windows... desde ahi mandé algunos correos al momento de tener fallas en la facturación... habrá que tener acceso a su servidor para ver porque no salen los correos

**Comment by RigoFlores** [comment]
Probé con el conector 3.3 y si lo envía.
Entonces pues si hay un problema, pero no se como resolverlo.

**Comment by RigoFlores** [comment]
Listo. Se agregó el email para notificaciones, y ya jaló.

Según yo, en código cambió el correo que toma en cuenta para enviar las facturas.
En la pantalla de creación de llave o licencia de los clientes, existen 2 correos:
Email
Email para notificaciones

La llave que estaba ocupando no tenía el de notificaciones, pero si el otro. 
Según yo, cambió esa parte en el código, porque esa misma llave había estado trabajando desde hace mucho, y apenas empezó a "dejar de enviar".
