### ISSUE TITLE
Cancelator - no está jalando. 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2073]
Tengo instalada la aplicación de cancelaciones, que vendimos por ahí de Julio/Agosto. Es el facturat de escritorio. El jar mas reciente de esa aplicación, es del 27 de Julio del 2022.
Al parecer no la han utilizado mucho y ahora están retomando.
Revisé los XML que cancelamos en su momento (cuando entregamos) y son cfdi 3.3.
Realmente debe cancelar 3.3 o 4.0, pero ahora mismo, no está jalando para el 3.3
Arroja estos errores a la consola:

- No es posible leer el XML, revise sus par├ímetros]
2022-12-09 16:54:09,741 DEBUG [pool-2-thread-1] (Connector2Cancel.java:127) - Cancel process result : 012 description : CA1.0 - No es posible leer el XML, revise sus par├ímetros
2022-12-09 16:54:09,742 ERROR [pool-2-thread-1] (Connector2Cancel.java:143) - Error en proceso de cancelaci├│n : 012 description : CA1.0 - No es posible leerel XML, revise sus par├ímetros

Mira, aquí dejo el log que genera, la llave, el CSD, y 3 XML 3.3 que no puede cancelar:

[FacturaT.log](https://github.com/jccastillo0007/eFacturaT/files/10198639/FacturaT.log)
[CSD.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/10198640/CSD.zip.txt)
[facturaT_TRA8402225G0.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/10198642/facturaT_TRA8402225G0.cfdi.txt)

[XML 3 cancel.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/10198647/XML.3.cancel.zip.txt)

**Comment by RigoFlores** [comment]
yo creo que si se debe ajustar algo en el código del conector, no será?
Aquí está el log, de cuando si jaló, por si sirve de algo.


[FacturaT.log.2022-07-27.txt](https://github.com/jccastillo0007/eFacturaT/files/10198723/FacturaT.log.2022-07-27.txt)

**Comment by jccastillo0007** [comment]
En el ambiente de pruebas de facturehoy, ya quitaron el método utilizado para cancelar CFDi, hay que probar en producción...

**Comment by jccastillo0007** [comment]
ya generé 2 facturas con mi RFC, y las cancelé desde el conector... voy a intentar cancelar las del cliente

**Comment by jccastillo0007** [comment]
Con los XML que enviaste , se obtiene el error :

message : CA06 - No existe la factura a cancelar

después intenta ejecutar la opción de cancelar por otro pac, y es ahí donde manda el error

CA1.0 - No es posible leer el XML, revise sus par├ímetros

**Comment by jccastillo0007** [comment]
Consigue algunas facturas que si existan en el SAT y estén vigentes

**Comment by RigoFlores** [comment]
las facturas que subí, están vigentes y están timbradas por otro PAC. 
Lo que nos contrataron fue el cancelator, donde los XML no los timbramos nosotros.

Aquí tienes la evidencia del registro del SAT de las 3 facturas.
Entonces, lo que cambió sería el método de cancelación para otros PAC's?

[registroSAT_Facturas.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/10203091/registroSAT_Facturas.zip.txt)

**Comment by jccastillo0007** [comment]
Oye, me puedes pasar la versión que le llamas 3.3 del standalone, quiero probar la cancelación de otros PACs ahi...

**Comment by RigoFlores** [comment]
subí un zip al rilises chacarrones... se llama Jars 3.3 LastVersionResico.zip

son los últimos jars que se generaron de la v3.,3

**Comment by jccastillo0007** [comment]
fixed 
ya esta en prod

**Comment by RigoFlores** [comment]
oye, este cambio que hiciste, sirve para las cancelaciones desde web para los cfdis timbrados por finkok?

Y para el conector en general, también funciona así?
