### ISSUE TITLE
Complemento de pago, a factura con iva base ieps, no reporta correctamente la base de IVA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2075]
Si en el CFDI original, se incluye el IVA con base IEPS, entonces la base de iva y la base del ieps son distintas.
En el documento de pago, lo reporta incorrectamente. (reporta la misma base).

En pruebas, puedes checarlo con la factura 485 del RFC IIA040805DZ4.
El pago asociado a esa factura es el pago 17.

Ambos son de hoy, 27 de dic del 2022

**Comment by jccastillo0007** [comment]
ya corregí la forma de reportar el iva base ieps... peeero marca error no clasificado...
