### ISSUE TITLE
Complemento de pago, con IVA tasa 0, no lo reporta a nivel global

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2076]
Solo lo reporta a nivel documento relacionado y a nivel pago, pero no a nivel general.
Se genera este error:

 Link/Ruta Acuse Recepcion SAT: CRP20267 - Debe existir al menos uno de los campos TotalTrasladosBaseIVA16 y/o y/o TotalTrasladosBaseIVA8 y/o TotalTrasladosBaseIVA0 y/o TotalTrasladosBaseIVAExento.

Este es el xml, donde está faltando reportar el IVA tasa 0 a nivel general.
[complemento de pago IVA tasa 0.txt](https://github.com/jccastillo0007/eFacturaT/files/10316194/complemento.de.pago.IVA.tasa.0.txt)

**Comment by jccastillo0007** [comment]
fixed, aunque si datos de prueba
