### ISSUE TITLE
Complemento de pago en MXN para una factura en USD, ya no jala

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2077]
Para pruebas en RFC IIA, tenemos lo siguiente:
la factura se emitió en USD, y el pago es en MXN

<img width="731" alt="pago MXN a USD" src="https://user-images.githubusercontent.com/2912775/209874665-8f5f439a-88f4-4ebd-aec7-f7a29b701965.PNG">

    <cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="601" UsoCFDI="CP01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago" ValorUnitario="0" Importe="0" ObjetoImp="01"/>
    </cfdi:Conceptos>
    <cfdi:Complemento>
        <pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="46.4" TotalTrasladosBaseIVA16="797.42" TotalTrasladosImpuestoIVA16="127.59"/>
            <pago20:Pago FechaPago="2022-12-28T15:28:08" FormaDePagoP="03" MonedaP="MXN" Monto="46.40" NumOperacion="fact 487" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="0.050162" Folio="487" IdDocumento="5D2E5993-E084-556C-8A28-0778964C327A" ImpPagado="46.40" ImpSaldoAnt="46.40" ImpSaldoInsoluto="0.00" MonedaDR="USD" NumParcialidad="1" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="40.000000" ImporteDR="6.400000" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="797.416371" ImporteP="127.586619" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>
        </pago20:Pagos>
    </cfdi:Complemento>
</cfdi:Comprobante>

Está reportando el valor de monto en USD, pero ahí que son los datos globales del pago, siempre van en moneda nacional.

**Comment by jccastillo0007** [comment]
![Screen Shot 2022-12-29 at 9 56 25](https://user-images.githubusercontent.com/2245679/209978020-9f90f0dd-ad6d-4504-bcbd-c94175ba672e.png)
 
Asi se generó el XML

    <cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="601" UsoCFDI="CP01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago" ValorUnitario="0" Importe="0" ObjetoImp="01"/>
    </cfdi:Conceptos>
    <cfdi:Complemento>
        <pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="925.0" TotalTrasladosBaseIVA16="797.42" TotalTrasladosImpuestoIVA16="127.59"/>
            <pago20:Pago FechaPago="2022-12-29T09:53:57" FormaDePagoP="03" MonedaP="MXN" Monto="925.00" NumOperacion="1111" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="0.050162" Folio="487" IdDocumento="5D2E5993-E084-556C-8A28-0778964C327A" ImpPagado="46.40" ImpSaldoAnt="46.40" ImpSaldoInsoluto="0.00" MonedaDR="USD" NumParcialidad="1" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="40.000000" ImporteDR="6.400000" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="797.416371" ImporteP="127.586619" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>
        </pago20:Pagos>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by RigoFlores** [comment]
pues lo veo bien, ya hice una prueba.
Ya lo mandé a finkok.
Quizá sea el tema de los 6 decimales, pero veamos que dicen ellos.

**Comment by jccastillo0007** [comment]
ok

**Comment by RigoFlores** [comment]
Sigue fallando.
Creo que ya vi el tema.
Con los 2 decimales que se redondean, en algunos casos esa cantidad será mayor que la real. Por ejemplo: 5.2589 al redondear es 5.26. Al final esa "pequeña" diferencia implica que el monto del pago total, sea menor a la suma de bases mas impuestos trasladados.
OK, cómo creo que debe resolverse?
Que a nivel del nodo de ImpuestosP, en lugar de redondear a 2 decimales, se trunque... puede haber igual diferencia, de hecho habrá diferencia, pero será hacia abajo y así no generará el error.

cómo ves?

**Comment by jccastillo0007** [comment]
ok, pero a que campo te refieres para ser truncado?

**Comment by jccastillo0007** [comment]
ahora si ya quedo, cierto?

**Comment by RigoFlores** [comment]
No, no ha quedado.
Aquí te pongo el XML generado, junto con lo comentarios. El asunto es exactamente lo mismo, a nivel de impuestosP, hay que truncar en lugar de redondear. Te lo señalo directamente en el XML que anexo aquí.
[pagoMXN a FactUSD.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10348080/pagoMXN.a.FactUSD.xml.txt)

**Comment by jccastillo0007** [comment]
ya vi, es que dejamos el truncado a nivel DR, pero aqui se hace la equivalencia, y hay que truncar otra vez...

voy hacerlo, haber si no se descompone lo anterior

**Comment by RigoFlores** [comment]
Chiaaa, pues eso fue lo que dije en mi comentario.
No creo que le pegue a otra cosa, ya que esto SOLO SE DEBE APLICAR CUANDO LA MONEDA DE PAGO ES DISTINTA A LA MONEDA DE LA FACTURA.
(me refiero al "doble truncamiento").

**Comment by jccastillo0007** [comment]
fixed.
