### ISSUE TITLE
Las Barricas - reporte diario, cambiar la fecha del reporte de ayer a hoy.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2079]
Se configuré para que entre 10:00 y 10:30 PM genere el reporte automático de facturación del día anterior.
Se solicita que el reporte no sea del día anterior, sino que sea del dia actual.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
la verdad no tengo forma de validarlo, pero lo subí al servidor y le pedí al cliente que lo valide.
