### ISSUE TITLE
Addendador Pilgrims - Ajustarlo al CFDI 4.0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2081]
Tomar como referencia este issue 1248, que en su momento fue la migración de cfdi 3.2 a 3.3

**Comment by jccastillo0007** [comment]
datos de prueba ?

**Comment by RigoFlores** [comment]
la addenda lleva estos datos:

    <cfdi:Addenda>
        <Pilgrims>
            <Proveedor>414439</Proveedor>   DATO FIJO
            <Proceso>01</Proceso>  DATO FIJO
            <Partida Pedido="4201122538" Posicion="10">  SE CAPTURA 1 POR CADA PRODUCTO EN LA FACTURA
                <Cantidad>1.0</Cantidad>   CANTIDAD DEL PRODUCTO
                <Precio>10800.0</Precio>  PRECIO ANTES DE IMPUESTOS DEL PRODUCTO
                <Referencia>6999</Referencia>  ES EL FOLIO DE LA FACTURA
            </Partida>
        </Pilgrims>
    </cfdi:Addenda>

**Comment by RigoFlores** [comment]
mandé un correo con ejemplos de XML con addenda

**Comment by jccastillo0007** [comment]
fixed.
Calale...

**Comment by RigoFlores** [comment]
listo, pásalo a pro por favor.
