### ISSUE TITLE
Complemento de carta porte - en pantalla de captura, si seleccionas un transporte sin remolque, marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2082]
Al parecer, cuando seleccionas un transporte que no tiene asociado un remolque, marca error.  (NO SE HA SELECCIONADO TRANSPORTE).
El remolque es un dato opcional.

Creo que es parte de las validaciones que se metieron.
Debe validar que se elija un transporte.
Pero no debe validar si el transporte tiene o no remolque... o en dado caso, esa validación si se puede meter pero en el catálogo de transportes, pero eso ya es oooootra historia.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
hay que llevarlo a pro, pls...
