### ISSUE TITLE
Compras - Registrar CFDI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2083]
No está funcionando el registro del CFDI externo en esta sección.
Entendería que es lo mismo para el menú de proveedores.
Aplicaría 3.3 y 4.0

**Comment by jccastillo0007** [comment]
fixed.

Hay una validación con el SAT de que el CFDI exista, pero no esta funcionando con FactureHoy, por ahora quite la validación.

**Comment by RigoFlores** [comment]
si, pero solo acepta 4.0, y debe aceptar ambos. (3.3 y 4.0)

**Comment by jccastillo0007** [comment]
hmmm noup, yo lo probé con una factura 3.3, de hecho no probé la 4.0
Si no te funciona, necesito datos de prueba

**Comment by RigoFlores** [comment]
cuando registras cfdi en el menú de compras, ya vi. Si acepta ambas versiones.
Cuando consultas, solo muestra la 4.0
Las consultas de los xml 3.3 no se muestran

**Comment by RigoFlores** [comment]
creo que eso lo arreglaremos si se da el proyecto.
