### ISSUE TITLE
Complemento de Pago con factoraje - ya se descompuso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2085]
Antes de toda la movedera, ya había timbrado 1 xml.
ahora nuevamente tiene un error.
al parecer solo es en el monto total del pago, que debe ser la suma de los pagos de los 2 nodos.

así está generando y este archivo tiene los comentarios..

[factoraje.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10363288/factoraje.xml.txt)

**Comment by jccastillo0007** [comment]
fixed, pero ahora marca otro error

**Comment by RigoFlores** [comment]
Yo creo que se debe a que en el segundo nodo de pagos, el Monto lo pone como 1100, pero debería ser 60. 


            <pago20:Pago FechaPago="2023-01-18T09:48:22" FormaDePagoP="17" MonedaP="MXN" **Monto="1100.00"** NumOperacion="fact 484" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="484" IdDocumento="A3092F37-68FF-5C60-B52C-BD2592A49848" ImpPagado="60.00" ImpSaldoAnt="60.00" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="2" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="51.72" ImporteDR="8.27" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="51.72" ImporteP="8.27" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>
            </pago20:Pago>

**Comment by jccastillo0007** [comment]
tienes un xml con factoraje que si se timbro correctamente? de hace como 1 mes o algo asi?

**Comment by RigoFlores** [comment]
Pues si, esta en el otro issue de factoraje, chiaaa... 2059

aquí lo vuelo a poner, pero allá estaba... necesitamos cobrar esa lana, y este tema aún no queda.


[xml_procesado_demo.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10480849/xml_procesado_demo.xml.txt)

**Comment by jccastillo0007** [comment]
creo que ya quedo... hay que probar bien

**Comment by RigoFlores** [comment]
este ya lo genera, tendré que correr pruebas que son un chingo para ver si no se descompuso de otro lado
