### ISSUE TITLE
Las Barricas - está mandando a imprimir a la impresora por default

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2087]
Si la leyenda no aparece o viene vacía o viene comentada, no debe mandar a imprimir a ninguna impresora:

#impresora=BrotherAlambrica   (comentada)

impresora= (vacía)

y si está mandando a imprimir, al parecer a la impresora por omisión. Es que se queda código que no debe aplicar y a la hora, se convierte en una falla.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
cuando viene vacío o no viene esa etiqueta en el archivo, sigue enviando a imprimir...
solo que ahora lo imprime vertical y truncado, pero sigue imprimiendo.

**Comment by jccastillo0007** [comment]
fixed.
Ojo...  además de probar con el rfc XIQ... prueba ambos casos:
 impresión normal (vertical) con otro rfc
No impresión  con otro RFC 

No vaya ser que por ahi hay un caso raro , por eso es que no funciono el fix de ayer...

**Comment by RigoFlores** [comment]
OK, solo que desde el conector, esto antes no existía.
Solo se imprimía desde pantalla, ¿esto tendría afectación?
