### ISSUE TITLE
Las Barricas - llenar con 0 a la izquierda del número de folio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2088]
longitud del número de folio, es 7 dígitos.
Llenar con 0's a la izquierda, tanto para el XML como para el PDF.

Ejemplo, si el folio es 2345, deberá formatearse así 0002345, y así enviarse al XML y al PDF.

**Comment by jccastillo0007** [comment]
fixed
calale... con un super parche...
