### ISSUE TITLE
Conector con CCE - no está tomando el dato de NumRegIdTrib para el nodo receptor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2089]
Cuando es trata de un receptor extranjero para un CFDI con complemento de comercio exterior (CCE), en el nodo receptor dentro del CCE, debe incluirse el NumRegIdTrib, que es el equivalente al RFC, pero de su país.

Aquí tienes un archivo de texto, que si incluye el dato, pero no lo está tomando.
De hecho, ese dato lo incluye en el archivo de texto, tanto en la información del receptor estándar, como dentro del receptor a nivel de cce.

receptor=XEXX010101000|VOLKSWAGEN||||||||||57319|soporte@factura-t.com.mx|DEU|**1234567**|616

CCER=**1234567**|5 Zum Heilbach, Bad Berleburg Aue||||01|||Nordrhein-Westfalen|DEU|57319

[CCE40_USD.txt](https://github.com/jccastillo0007/eFacturaT/files/10451307/CCE40_USD.txt)

**Comment by jccastillo0007** [comment]
fixed.
Ojo, precisamente esa instrucción de enviar el NumRegIdTrib estaba comentada, supongo que en algún momento causo otros problemas, así que hay que probar todos los escenarios.

**Comment by RigoFlores** [comment]
pues mira, hoy no me dejaba timbrar sin ese dato, y hace algunos años la misma versión del complemento, timbrada por el mismo pac, si lo aceptaba. 
No sé si hay alguna otra validación especial. Seguiré investigando. 

Mira como antes si, y ahora no. El de antes es de producción. El de ahora es en pru.

[ahora.txt](https://github.com/jccastillo0007/eFacturaT/files/10515097/ahora.txt)
[antes.txt](https://github.com/jccastillo0007/eFacturaT/files/10515098/antes.txt)
