### ISSUE TITLE
NO ENVIA LOS DATOS DE LA SUCURSAL AL PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#209]
TIENE QUE ENVIAR EL NOMBRE DE LA SUCURSAL, ASÍ COMO LA INFO DE EXPEDIDO EN AL MOMENTO DE ELEGIR UNA SUCURSAL PARA FACTURAR. AL XML SI LO ENVIA

**Comment by jccastillo0007** [comment]
fixed
