### ISSUE TITLE
Complemento de pago a factura con solo IEPS trasladado, tasa 0 y tasa 6% no se comporta igual en pro que en pru.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2090]
El escenario de error, es cuando se trata de hacer un complemento de pago a una factura que únicamente incluye impuesto trasladado IEPS, con tasa 0 y tasa 6%. Yo creo que no influyen tanto las tasas, sino que solo es IEPS, es decir, sin IVA trasladado o algún otro impuesto retenido.

OK, en producción está generando el XML sin el nodo de pagos. Es la factura A1090 del cliente ANQ940906TJ9. Cuando intenté pagar, me generó este XML.

[PRO pago solo IEPS.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10494744/PRO.pago.solo.IEPS.xml.txt)

por otro lado en pru, con el RFC IIA y el receptor la tia, factura 501, según yo es el mismo escenario solo IEPS con tasa 0 y tasa 6%, y ahí si genera el XML según yo, casi bien. Entonces, el primer problema, es que no está comportándose igual producción que pruebas para este escenario.
Este es el XML generado en pru... quizá solo el nodo ImpuestosP es el que esté sobrando. Pero de lo demás lo veo bien. Lo reportaré a finkok, a ver que dicen ellos.

[PRO pago solo IEPS.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10494745/PRO.pago.solo.IEPS.xml.txt)

**Comment by jccastillo0007** [comment]
chiaaa, subiste el mismo archivo dos veces, así como?

**Comment by jccastillo0007** [comment]
la factura que dices ya aparece como pagada, del cliente ANQ940906TJ9, hay que generar el caso de error en pro con la tia u otro rfc

**Comment by RigoFlores** [comment]
en pruebas, con la factura 501 es donde puedes hacerla...

[PRU pago solo IEPS.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10541859/PRU.pago.solo.IEPS.xml.txt)

Si no se incluye el nodo de ImpuestosP, no se que vaya a marcar finkok. 
Pero yo pienso que FactureHoy si lo pasará (así lo ha hecho en el escenario cuando no se reporta IVA alguno).

Sin embargo, finkok dice que en ese nodo para el caso de los traslados, se deben reportar los impuestos. En este caso los del IEPS. Lo comentaron "no muy seguros" de lo que decían, ya que escribieron "siguiendo esta lógica.. bla bla bla"
Por otro lado, el SAT dice que cuando se reportan impuestos trasladados en el nodo de ImpuestosP, al menos debe existir un tipo de IVA, lo cual no  es este caso.

Total, que lo que se solicita aquí, es no reportar el nodo ImpuestosP, y vemos que pasa.
Será un poco a prueba y error.

**Comment by jccastillo0007** [comment]
listo, ya probé en PRU y ya no genera el nodo ImpuestosP, checale

**Comment by RigoFlores** [comment]
pues no, no lo acepta finkok en pru.
Tons la solución es agregar el nodo ImpuestosP, junto con los traslados o retenidos, según sea el caso.
En este caso, solo el IEPS trasladado, aún cuando no se reporte en la parte global.

**Comment by jccastillo0007** [comment]
ok, en los totales sigue igual, pero hay que mostrarlo en impuestosP, esto es para todos los casos cierto? es decir, ya no se debe evitar mostrar ningún impuesto en impuestosP?

**Comment by RigoFlores** [comment]
Si, ahí existe una omisión en el estándar.
Por un lado dice la guía de llenado dice, que en ImpuestosP, en traslados, al menos debe reportarse algún IVA con su tasa correspondiente o incluso exento.
Por otro lado, para este caso específico, donde solo se reportaría IEPS, pues no se que vaya a marcar finkok.

Total, la respuesta es si. Hay que reportar el IEPS ahí, para este caso específico donde no incluyen IVA las facturas. 

Yo pienso que en el llenado de las facturas, debería llevar IVA exento, pero pues no lo sé. Solo un fiscalista.

**Comment by jccastillo0007** [comment]
esto me confunde : 
"Total, la respuesta es si. Hay que reportar el IEPS ahí, para este caso específico donde no incluyen IVA las facturas."

Estaría mostrando el IEPS siempre, con o sin IVA u otro impuesto, correcto?

O solo el IEPS cuando no exista IVA u otro impuesto?

**Comment by RigoFlores** [comment]
Esto sería...

**Estaría mostrando el IEPS siempre, con o sin IVA u otro impuesto, correcto? AFIRMATIVO**

**Comment by RigoFlores** [comment]
actualmente incluye el IEPS cuando va con IVA...  
Esta prueba que hice fue un pago a una factura con base IEPS.


[pagobaseieps.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10574189/pagobaseieps.xml.txt)

**Comment by RigoFlores** [comment]
No jaló. No hay tanto problema por mantener esa versión ahí en pro. Finalmente no es un caso común, y lo que estoy haciendo mientras se pueda, es irme a la 3.3 a timbrar estos casos que tenemos que atender.

Realmente la prueba en pro era dejar el nodo de ImpuestoP, vacío, como originalmente estaba.
Ahí estoy seguro que Finkok no lo acepta
Para el caso de FHoy, acepta un nodo vacío en el CFDI estándar, cuando no lleva ningún IVA. 
Por eso quería probar en pro lo del nodo vacío.

Pero podemos seguir probando o ya de plano agregarle el IEPS en el nodo ImpuestosP, aunque ésto no se reporte a nigle global. Esto sabemos que Finkok si lo acepta.

**Comment by jccastillo0007** [comment]
puedes agregar el xml que generó en pro

**Comment by RigoFlores** [comment]
[no clasificado.txt](https://github.com/jccastillo0007/eFacturaT/files/10593849/no.clasificado.txt)


error no clasificado


2023-02-03 07:44:11,595 DEBUG [https-jsse-nio-8443-exec-10] (SealerPACProcess.java:349) - Link/Ruta Acuse Recepcion SAT: CRP20999 -  Error no clasificado.

**Comment by jccastillo0007** [comment]
ok, ya subí a pro la versión que deja el nodo impuestoP vacío, checale

**Comment by RigoFlores** [comment]
Chiaaaa, pues esta es la que marcó error no clasificado.

La solución si será llenar el nodo ImpuestosP, con los trasladados IVA, IEPS o ambos.
Aún cuando en los globales no se reporte el iEPS

**Comment by jccastillo0007** [comment]
y esto que significaba entonces:

"Realmente la prueba en pro era dejar el nodo de ImpuestoP, vacío, como originalmente estaba.
Ahí estoy seguro que Finkok no lo acepta
Para el caso de FHoy, acepta un nodo vacío en el CFDI estándar, cuando no lleva ningún IVA.
Por eso quería probar en pro lo del nodo vacío."

**Comment by RigoFlores** [comment]
Pues justo eso, que queríamos validar que Fhoy aceptaría el nodo vacío, igual que lo hace con las facturas sin impuestos trasladados. Esto para ya no moverle al código. Pero no, no jaló.

Así que tenemos que incluir los traslados de IVA o IEPS o el impuesto trasladado que incluya el CFDI.
Aún cuando en los totales, el IEPS no se reporta.

**Comment by jccastillo0007** [comment]
parece que ya quedo, esta en pru

**Comment by RigoFlores** [comment]
ok, si ya lo hizo.
Los cambios en pagos, me ponen a temblar, porque se compone algo y luego se mueve de otro lado.

Pero ni hablar.
