### ISSUE TITLE
Complemento de pago - pago en MXN de una factura en USD hace cosas raras

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2091]
Lo documentaré por lo pronto
Mañana intentaré reproducirlo.

Lo que vi hoy en producción para la versión 4.0, es que capturas la cantidad pagada en MXN de una factura emitida en USD.
Marca error al timbrar, pero en el XML que intentó timbrar, el monto pagado lo pasa a USD en lugar de mantenerlo en MXN como originalmente se capturó.

[pagoMXN a factura en USD.txt](https://github.com/jccastillo0007/eFacturaT/files/10552152/pagoMXN.a.factura.en.USD.txt)

el error es...

El valor del campo MontoTotalPagos no es igual al redondeo de la suma del resultado de multiplicar cada uno de los atributos Monto por el valor registrado en el atributo TipoCambioP de cada nodo Pago.

**Comment by RigoFlores** [comment]
ya hoy lo reportó otro cliente, pero en producción.

**Comment by RigoFlores** [comment]
Ya tiene un rato de este issue... el cliente espera, jeje.

**Comment by jccastillo0007** [comment]
Esto es en web o conector? como lo reproduzco ?

**Comment by RigoFlores** [comment]
Es en web.
RFC emisor IIA:
Trata de pagar la factura 497.  Es factura en USD y el pago en MXN. Recuerda que si la factura es de 10 USD, el pago por ejemplo sería de 200 pesos.

**Comment by jccastillo0007** [comment]
Fixed, puedes hacer varias pruebas con moneda nacional y usd, y varios pagos..., esta bien pinche raro porque algunos escenarios derrepente fallan

**Comment by RigoFlores** [comment]
No, no es raro.
Cuando el parámetro EquivalenciaDR, por manejarlo a 6 decimales, se trunca... pues algunas veces funcionará y otras no.
estaba viendo lo del factor de ajuste, que estamos multiplicando por 1.000002...  pero igual no jala...
Y ya vi como puede solucionarse, el factor de ajuste para cuando la moneda de pago sea distinta a la moneda de la factura, no es multiplicación, sino suma... sumarle 0.000001 a la equivalencia.
