### ISSUE TITLE
CFDI 4.0 + CCE 1.1, receptor nacional, y 2 productos o más en MXN, marca error.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2093]
Para el caso de un receptor nacional, y una factura con 2 o mas productos en MXN, que incluye el CCE, el atributo de TipoCambioUSD dentro del CCE lo pone con el valor incorrecto (la última fracción arancelaria, en lugar del tipo de cambio capturado en el catálogo).

En pruebas puedes usar emisor XIQB891116QE4, receptor la tia.
Productos, los 2 que existen. Cantidad 1 para no meterte en mas lío.

Captura del CCE:
Fracción arancelaria para ambos productos: 9031809901
Unidad: 06

(es lo único que se captura del CCE, en este caso).

Lo que está haciendo cuando capturas 2 o mas productos, cambia el tipo de cambio. Si prestas atención, ese tipo de cambio que pone, es de la fracción arancelaria (según yo del último producto capturado):

cce11:ComercioExterior CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="EXW" Subdivision="0" **TipoCambioUSD="9031809901"** TipoOperacion="2" TotalUSD="0.00" Version="1.1"

y pues a partir de ahí, los cálculos dentro del CCE lo pone todo a cero.

Si todo esto lo haces con un solo producto, lo hará bien, pero en pruebas no timbra por las claves de municipio del emisor.
En producción si lo hace bien, pero con un solo producto. El cliente de ayer, necesita meter 50 productos en una misma factura,

**Comment by RigoFlores** [comment]
mismo caso con el receptor extranjero.

Con mas de 2 productos, se hace pelotas y envía en el tipo de cambio, dentro del complemento, la última fracción arancelaria capturada.

**Comment by jccastillo0007** [comment]
fixed, (ese error ha estado ahí por mucho tiempo, solo en el caso de mas de un producto)

**Comment by RigoFlores** [comment]
pues no sé, no creo que solo hicieran facturas con un solo producto.
Cerraré este ticket, pero ahora no jala por otra cosa, para lo que abriré un nuevo ticket.
