### ISSUE TITLE
CFDI 4.0 + CCE 1.1 - no está enviando el dato de NumRegIdTrib cuando el receptor es XEXX

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2094]
Pues el complemento que timbraba antes, ya revisamos hace poco que no lo hace ya.
Entonces, en web, para cuando el receptor es XEXX, el NumRegIdTrib se captura al capturar la addenda.

Este dato, lo debe incluir en la parte del receptor del cfdi estándar, y además en el nodo receptor del CCE (solo en el caso de receptor = XEXX).

Ahora no lo incluye ni en uno, ni en otro.
Este es el emisor de pruebas. Ahorita fue mi primera prueba básica para receptor extranjero y no jaló, así que le voy a dar una repasada a todo, solo que si necesito que se corrijan los 2 tickets de hoy, de CCE

cfdi:Emisor **Rfc="IVD920810GU2**" Nombre="INNOVACION VALOR Y DESARROLLO" RegimenFiscal="601"

cfdi:Receptor Rfc="XEXX010101000" Nombre="OMEGA TOOL CORP" DomicilioFiscalReceptor="61957" ResidenciaFiscal="CAN" **NumRegIdTrib=""** RegimenFiscalReceptor="616" UsoCFDI="S01"

            **cce11:Receptor**
                cce11:Domicilio Calle="AV UNIVERSIDAD" CodigoPostal="A1B 2C3" Estado="AB" Pais="CAN"
            cce11:Receptor

**Comment by jccastillo0007** [comment]
Los datos de addenda deben ser (en este orden):
Motivo traslado
NumRegIdTrib propietario
Residencia fiscal propietario
Incoterm
Subdivision
NumRegIdTrib receptor
Certificado origen
Num Certificado origen
Nombre destinatario
NumRegIdTrib destinatario
Calle
Estado
Pais
Código Postal
Empty
Empty
Valor de conversión para el precio.


Si estas enviando todos bien?

**Comment by RigoFlores** [comment]
ya lo está enviando.
