### ISSUE TITLE
CFDI 4.0 + CCE 1.1 + Finkok, nodo del domicilio del receptor, incluir la localidad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2095]
Tomar algún campo de los existentes del catálogo de clientes, y enviarlo al nodo del domicilio del receptor como localidad.
Solo finkok lo pide, facture hoy, no lo solicita.

Entonces este dato se puede capturar en el campo de número interior, contacto, curp. del catálogo de clientes.

            cce11:Receptor NumRegIdTrib="1234567"
                cce11:Domicilio Calle="5 Zum Heilbach, Bad Berleburg Aue" CodigoPostal="57319" Estado="Nordrhein-Westfalen" **Localidad="01"** Pais="DEU"
            cce11:Receptor

**Comment by jccastillo0007** [comment]
y si facturehoy si lo acepta, para que le movemos?

**Comment by jccastillo0007** [comment]
como quiera , ya lo configuré para que el num ext (que no se usaba) lo ponga como localidad, lo subí a pru y pro

**Comment by RigoFlores** [comment]
ya lo está mandando, pero aún no timbra.
Seguiré en la revisión.

**Comment by RigoFlores** [comment]
creo que se ocupa mas el número exterior, que el interior.
Incluso en el número exterior, puedes incluir el exterior, ejemplo  Edificio 1, Piso 2, Departamento 3

Tons hay que invertirlos.

**Comment by jccastillo0007** [comment]
antes no enviaba el num exterior, no se ocupaba como lo comenté arriba, así que ese no es el problema

**Comment by RigoFlores** [comment]
No fui claro.
Ya timbra, esto está bien.
Lo único que se pide es que en lugar de ocupar el número exterior (para la localidad), se ocupe el número interior.

No porque se envie, sino porque algunos clientes si ocupan todos los datos del domicilio en sus plantillas a la medida. Eso es la razón por únicamente pedir que la localidad se envíe por el número interior, en lugar del número exterior

**Comment by jccastillo0007** [comment]
done
