### ISSUE TITLE
Las Barricas - Estabilización, no guarda ni procesa los archivos corregidos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2096]
En la pantalla para corregir los 4 datos del receptor, en las barricas, si en el archivo de texto, no se incluye el régimen, marca error.
No almacena el archivo, y al enviarlo a reprocesar, pues sigue con el error original, al no guardarse.

No se si solo para el régimen, o para cualquier otro dato dentro del archivo.

Puedes probar con este archivo.

[facturaBasica.txt](https://github.com/jccastillo0007/eFacturaT/files/10680067/facturaBasica.txt)

**Comment by jccastillo0007** [comment]
fixed
