### ISSUE TITLE
Las Barricas - mandar la impresión del PDF 2 veces (original y copia).

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2097]
Este cliente tiene varios requisitos poco comunes.
Ahora uno más.

Para algunas tiendas, se requiere mandar a imprimir 2 ocasiones el PDF.
En una con la leyenda original y la otra con la leyenda copia  (si, así, jejeje).

**Comment by jccastillo0007** [comment]
Oye Rijo, si se puede enviar a imprimir dos veces una factura, pero en realidad no es lo que se pide ya que quieren la leyenda "COPIA" en la segunda impresión, entonces en realidad estamos hablando de dos impresiones diferentes, puedes hacer el jasper template de la segunda con la leyenda COPIA y me la mandas...
En el TXT hay que agregar el parámetro al campo Impresora:
impresora=BrotherAlambrica|copia

**Comment by RigoFlores** [comment]
para no manejar tantos formatos para las barricas, puede ser mejor que me envíes una variable donde se indique si es copia?
estas variables ya no se ocupan. Puede ser la primera...

	<field name="imagenAlterna" class="java.lang.String"/>


	<field name="nombreExpedidoEn" class="java.lang.String"/>
	<field name="calleExpedidoEn" class="java.lang.String"/>
	<field name="noExteriorExpedidoEn" class="java.lang.String"/>
	<field name="noInteriorExpedidoEn" class="java.lang.String"/>
	<field name="coloniaExpedidoEn" class="java.lang.String"/>
	<field name="localidadExpedidoEn" class="java.lang.String"/>
	<field name="referenciaExpedidoEn" class="java.lang.String"/>
	<field name="municipioExpedidoEn" class="java.lang.String"/>
	<field name="estadoExpedidoEn" class="java.lang.String"/>
	<field name="paisExpedidoEn" class="java.lang.String"/>
	<field name="cpExpedidoEn" class="java.lang.String"/>

	<field name="motivoDescuento" class="java.lang.String"/>

**Comment by jccastillo0007** [comment]
ok, pero no es bueno reusar variables que no tienen nada que ver, luego no nos vamos a acordar.
hay que usar una que se llame imprimeCopia o algo asi

**Comment by jccastillo0007** [comment]
con el release de hoy y con la leyenda en el txt:
impresora=BrotherAlambrica|copia

puedes probar que imprima dos veces, si no dice copia no imprimirá dos veces...

**Comment by RigoFlores** [comment]
si, se imprimió 2 veces.

**Comment by jccastillo0007** [comment]
listo, además del parámetro copia en el renglón de impresora...
se agregó esta variable al jasper: imprimirEnCopia
Será 1 si es copia y 0 si es el original

**Comment by jccastillo0007** [comment]
puedes hacer varias pruebas porque hice varios cambios...
