### ISSUE TITLE
LAS BARRICAS - ESTABILIZACIÓN, no muestra correctamente la Ñ en la edición de los archivos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2098]
Cuando estás editando un archivo de las barricas, y éste contiene la letra Ñ en el nombre (por ejemplo MUÑOZ), no muestra correctamente la Ñ, aunque al momento de almacenar, si la guarda bien.

En la 4.0, ya no se incluyen acentos. 
Regularmente los nombres son mayúsculas. (no he visto en minúsculas).
Probé con & y ", que son caracteres que he visto en los nombres, y si los muestra bien.

**Comment by jccastillo0007** [comment]
fixed
