### ISSUE TITLE
LAS BARRICAS - ESTABILIZACIÓN, no está enviando el correo personalizado, ni con el banner

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2099]
pues si, al ser en el servidor este tema, es un problema.

Pero bueno, ahora mismo no está enviando el correo que personalizamos para las barricas. 
En pruebas si lo hacía, pero ya para producción no.

**Comment by jccastillo0007** [comment]
lo manda en tu laptop, con sus rfcs?

**Comment by RigoFlores** [comment]
No puedo probarlo aquí, ya que no tengo su ambiente de producción.
En pruebas no acepta sus rfcs emisores.

Quizá tenga que solicitar hacer algunas pruebas en pro... a menos que la prueba fuera únicamente reenviar una factura, funcionaría para validar este comportamiento???

**Comment by jccastillo0007** [comment]
Solicita el acceso a pro, de otra forma estamos a ojos cerrados

**Comment by RigoFlores** [comment]
ya lo validé apuntando a producción, en una instalación de mi laptop y efectivamente no es personalizado el correo.
ya te envié copia del mismo
rfc emisor DBA990304SP4

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ya lo validé correctamente para el rfc de las barricas.
Para los otros 2 rfcs de ellos, igual quedó?

**Comment by jccastillo0007** [comment]
si, solo había un error de dedo
