### ISSUE TITLE
CATALOGO DE CLIENTES - NO SE PUEDE EDITAR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#21]
DEFINITIVAMENTE, LA REVISIÓN INICIAL LA TIENE QUE HACER EL PROGRAMADOR COMPARANDO CON LA FUNCIONALIDAD ACTUAL
NO ES POSIBLE LEVANTAR FALLAS TAN ELEMENTALES

**Comment by jccastillo0007** [comment]
Que es lo que no se puede editar o como asi?
Hay un boton para editar los datos del cliente, todo excepto el RFC.

Seria bueno tener mas descripción del error en lugar de otro tipo de comentarios que no me ayudan a corregir los problemas.

**Comment by RigoFlores** [comment]
NO PRESENTABA LA OPCIÓN DE EDITAR
