### ISSUE TITLE
EN LA NÓMINA BORRA LOS GENERALES DEL EMPLEADO AL ELEGIR PERCEPCIONES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#210]
CUANDO CAPTURAS 'DE CORRIDO', PRIMERO CAPTURAS LOS GENERALES DEL EMPLEADO, Y CUANDO INICIAS CAPTURANDO LAS PERCEPCIONES, BORRA TODOS LOS DATOS PREVIOS DEL EMPLEADO

**Comment by FraQue0693** [comment]
Subi cambios donde no se borra los datos generales al momento de seleccionar percepciones ,deducciones,incapacidades o horas extras.
