### ISSUE TITLE
Conector 4.0, cuando cancelas desde la pantalla, no genera acuse de cancelación, ni cambia el status

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2100]
Si envía la petición de cancelación al SAT, incluso muestra el resultado de que se envio la petición.
Pero el estado de la factura sigue activa y no genera el acuse de cancelación.

Se debe cambiar el status a cancelado y generar el acuse de cancelación

**Comment by jccastillo0007** [comment]
Puedes probar con una factura generada desde facturat standalone, no conector

**Comment by RigoFlores** [comment]
Ya lo hice, generando la factura desde pantalla y cancelando igual desde la pantalla de escritorio (una vez que ya aparecía registrada en el SAT), y aunque si la envió a cancelar, no generó acuse, ni de PDF ni XML

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
pues no, no veo versión nueva con fecha de hoy 13 de febrero
