### ISSUE TITLE
Las Barricas - Agrupar las carpetas por tipo de CFDI y almacenar PDF y XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2101]
Piden lo siguiente:

Que cada tipo de CFDI se almacene en distinta carpeta. Ingreso, Egreso, Pago.
En cada carpeta, se almacene ahí mismo el PDF y XML. 

Esto ya lo hacíamos para los españoles, separar el PAGO en otra carpeta.
Y juntar PDF y XML, también ya lo hemos hecho, pero no recuerdo en cuál cuenta.

**Comment by jccastillo0007** [comment]
no ma

**Comment by RigoFlores** [comment]
Me dicen que lo detenga, chiaaaa....
