### ISSUE TITLE
cfdi 4.0 + cce 2.0 - receptor nacional y moneda en USD, hace cálculos chuecos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2102]
Con el RFC de pruebas IVD.
Eliges al cliente la TIA para cliente nacional. También puede ser con XEXX si es cliente extranjero. 
La factura la eliges con la moneda USD. (recordar que el tipo de cambio debe ser del día de ayer, publicado en el DOF).
Capturas 1 producto.
Le indicas que incluirá el CCE
Capturas el CCE. Para cliente nacional, únicamente la fracción arancelaria (9031809901) y la unidad (06). Si es cliente extranjero, además capturas el Número de Registro Receptor (123456789) 

Casualmente puede llegar a timbrarlo, peeeeero el pedo es que en el CFDI estándar, todo está bien reportado en USD.
A nivel de CCE, aplica los cálculos para convertir USD a USD!!!

Checa este XML, no maaaa...

[218_IVD920810GU2_TIA101020BP4_13Feb2023_181911.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10727417/218_IVD920810GU2_TIA101020BP4_13Feb2023_181911.xml.txt)

**Comment by RigoFlores** [comment]
[219_IVD920810GU2_TIA101020BP4_13Feb2023_182916.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10727442/219_IVD920810GU2_TIA101020BP4_13Feb2023_182916.xml.txt)

otro ejemplo...

**Comment by jccastillo0007** [comment]
fixed.

No hace "cosas raras", simplemente estaba aplicando el tipo de cambio a USD, cuando ya no era necesario.
Este error ha estado ahí desde el inicio, pues no había ninguna validación...

**Comment by RigoFlores** [comment]
No pues ya quedó pior....
En el CCE, debe incluirse el tipo de cambio de USD, publicado en el DOF del día anterior, eso es de cajón.
Ahora, en el detalle del CCE, las mercancías, productos o conceptos se expresan en USD también.
Si la factura estándar se emite en USD, los precios unitarios e importes de la factura se trasladan idénticos al CCE.
En el caso de este issue, la factura estándar se emite en USD.

Lo que hizo ahora, estuvo bien, excepto que en el CCE no está colocando el tipo de cambio de USD

        <cce11:ComercioExterior CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="EXW" Subdivision="0" TipoCambioUSD="1.0" TipoOperacion="2" TotalUSD="100.00" Version="1.1">
            <cce11:Emisor>
                <cce11:Domicilio Calle="calle huetamo, michoacan" CodigoPostal="61957" Estado="MIC" Municipio="038" Pais="MEX"/>
            </cce11:Emisor>
            <cce11:Receptor>
                <cce11:Domicilio Calle="Fray Luis de León" CodigoPostal="76090" Estado="QUE" Localidad="01" Municipio="014" Pais="MEX"/>
            </cce11:Receptor>
            <cce11:Mercancias>
                <cce11:Mercancia CantidadAduana="1.0" FraccionArancelaria="9031809901" NoIdentificacion="01" UnidadAduana="06" ValorDolares="100.00" ValorUnitarioAduana="100.00"/>
            </cce11:Mercancias>
        </cce11:ComercioExterior>


Aquí debe incluir el tipo de cambio del USD, pero en lugar de esto, le incluye 1 como tipo de cambio, jejeje.

cce11:ComercioExterior CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="EXW" Subdivision="0" **TipoCambioUSD="1.0"**

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
sigue colocando el tipo de cambio dentro del CCE = 1.0

 <cce11:ComercioExterior CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="EXW" Subdivision="0" TipoCambioUSD="1.0" TipoOperacion="2" TotalUSD="100.00" Version="1.1">

**Comment by jccastillo0007** [comment]
sorry, no subí el release ayer, prueba mañana temprano todo lo que este en fixed
