### ISSUE TITLE
LAS BARRICAS - ERROR CUANDO EL NOMBRE CONTIENE Ñ

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2103]
No está procesando correctamente el nombre cuando contiene Ñ.
Así se ve en el catalina...

    <cfdi:Emisor Rfc="DBA990304SP4" Nombre="DISTRIBUIDORA LAS BARRICAS" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TAME780817SD8" Nombre="EDITH TAPIA MUÃ‘OZ" DomicilioFiscalReceptor="57000" RegimenFiscalReceptor="612" UsoCFDI="G03"/>

Este es el archivo.

[LVF002059.txt](https://github.com/jccastillo0007/eFacturaT/files/10728681/LVF002059.txt)

**Comment by jccastillo0007** [comment]
fixed, chécale en windows, porque en mac si jalo...

**Comment by RigoFlores** [comment]
no, no veo una versión nueva para validar.
Recuerda que ellos tienen su servidor en windows.

**Comment by RigoFlores** [comment]
Chiaaaa... también en el documento de pago se presenta el problema, y yo creo que en la nota de crédito igual...
esta corrección aplica a nivel nombre dentro de todo el universo de CFDI... chiaaaa

Es el conector barricas, pero pues yo creo que afecta a todos, no???

**Comment by RigoFlores** [comment]
pues como que se volvió a inyectar el error
para todo tipo de CFDI, no solo pagos.

**Comment by jccastillo0007** [comment]
no lo pude reproducir, me procesa correctamente el archivo... anexo xml recién generados... 
Espero que no estes viendo el log, porque ahí no importa como lo muestra...
[LVF2059_TAME780817SD8_23Feb2023_213230.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10820426/LVF2059_TAME780817SD8_23Feb2023_213230.xml.txt)

**Comment by RigoFlores** [comment]
No, pues a partir del log no se levantan tickets.

Es un mensaje de error al intentar timbrar, que se les presenta a ellos y a mi también.
Ya había pasado, y lo habías resuelto pero pues se inyectó el bug nuevamente.

En mac si jala, en windows no. Recordar que el servidor del cliente es windows.

**Comment by RigoFlores** [comment]
así se ve en el catalina ahora mismo.

    <cfdi:Emisor Rfc="XIQB891116QE4" Nombre="BERENICE XIMO QUEZADA" RegimenFiscal="626"/>
    <cfdi:Receptor Rfc="TAME780817SD8" Nombre="EDITH TAPIA MUÃ‘OZ" DomicilioFiscalReceptor="57000" RegimenFiscalReceptor="612" UsoCFDI="G03"/>
