### ISSUE TITLE
Optibelt - emisión de CFDI 4.0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2104]
Para timbrar en 4.0, lo único que nos pasará Optibelt como dato nuevo, será la clave del régimen fiscal en el campo H4.15

El resto de campos nuevos que se incluyen para el cfdi 4.0:

CP del receptor, ya se incluía en el H4.14
Factura Global (no aplican estos datos)
Importación: Si cuando el CFDI incluya el CCE
Objeto de Impuestos: siempre que se incluyan impuestos trasladados.
La base de los trasladados, será igual al importe, menos el descuento. Creo que ellos no manejan descuento.

**Comment by jccastillo0007** [comment]
revisando el conector optibelt, ya se incluye el campo H4.15 con el régimen  y el H4.14 con el código postal... puedes probar timbrar

**Comment by RigoFlores** [comment]
Cuál es el rfc emisor de pruebas, que tiene un comportamiento "como optibelt"?

**Comment by RigoFlores** [comment]
IVD920810GU2 es el rfc de pruebas que tiene el comportamiento optibelt.
Ya recordé que este issue, se pidió el año pasado, donde supuestamente solo cambiaríamos el campo, en caso que no aceptaran el H4.15 para el régimen.
Tanto tiempo lo han prolongado, que ni lo recordaba, pero ya... ya está.

**Comment by RigoFlores** [comment]
Hay un pequeño ajuste, ya que los alemanes mandaron el régimen "un campo mas adelante", es decir H4.16.
Para mayor referencia, queda el CP, un espacio vacío y luego el régimen... chiaaaa.
Así lo están generando:

H4|Rodamientos y Accesorios SA de CV|RAC870406P40||Av Nogalar Sur 107|||Col Cuauhtemoc|||Monterrey|Nuevo León|MEXICO|66450||601|||||||||||

**Comment by jccastillo0007** [comment]
fixed
