### ISSUE TITLE
Las Barricas - complemento de pago, no está reportando el total de la base IVA, ni el importe IVA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2105]
No creo que sea solo de las barricas, pero bueno, en las barricas se presenta el caso de que tienen impuesto IEPS e IVA (calculado en base IEPS).
No está reportando correctamente la base IVA, y tampoco el importe IVA de la factura en el complemento de pago.
Al mero principio de esta historia, yo sugerí que esos datos se agregaran en una tabla. La respuesta fue que era muy simple su cálculo o algo así parecido, de tal manera que no era importante guardarlos (se iba a duplicar la info).
Al paso se los meses, pareciera que si era una opción, guardar todo el tema del resumen de impuestos, pero bueno.

Total, que ahora mismo, ese es el punto. No está generando correctamente el complemento de pago.

aquí los 2 xml correspondientes.

[PPM32069_MAF121022532_02feb2023_132541.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10739101/PPM32069_MAF121022532_02feb2023_132541.xml.txt)
[PAGO2031989_MAF121022532_13feb2023_115838.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10739102/PAGO2031989_MAF121022532_13feb2023_115838.xml.txt)

**Comment by RigoFlores** [comment]
con estos archivos puedes reproducir el problema. 
La factura genera el XML con 3 tasas de IEPS y 1 de IVA (para las barricas, esto es común de 1 a 3 distintas tasas de IEPS en la misma factura).
El pago, hay que modificar el UUID una vez que ya se timbró.

En los datos de los impuestos del XML de pago, podrás ver que la base y el monto del IVA no coinciden.

[TPPM025820.txt](https://github.com/jccastillo0007/eFacturaT/files/10744255/TPPM025820.txt)
[pagoPPM25820.txt](https://github.com/jccastillo0007/eFacturaT/files/10744256/pagoPPM25820.txt)

**Comment by RigoFlores** [comment]
[2031989  .txt](https://github.com/jccastillo0007/eFacturaT/files/10746417/2031989.txt)
[PPM032069.txt](https://github.com/jccastillo0007/eFacturaT/files/10746418/PPM032069.txt)


aquí otra pareja de archivos para reproducir.  PPM032069.txt es la factura. 2031989  .txt es el pago.

**Comment by jccastillo0007** [comment]
acabo de hacer la prueba con los archivos con folio 25820, y si lo hizo bien, anexo el xml generado..
Ojo... le cambié el folio a 25821
[PAGO328_MASO451221PM4_15Feb2023_202644.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10751532/PAGO328_MASO451221PM4_15Feb2023_202644.xml.txt)

voy hacer la prueba con los otros archivos que subiste

**Comment by jccastillo0007** [comment]
también funcionó con los segundos archivos que subiste
[PAGO2031989_MAF121022532_15Feb2023_203322.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10751552/PAGO2031989_MAF121022532_15Feb2023_203322.xml.txt)

**Comment by RigoFlores** [comment]
De los primeros ejemplos que subí, los XML ya timbrados... el que corresponde a la factura, tiene este resumen de impuestos:

    <cfdi:Impuestos TotalImpuestosTrasladados="813.30">
        <cfdi:Traslados>
            <cfdi:Traslado Base="1049.68" Importe="556.33" Impuesto="003" TasaOCuota="0.530000" TipoFactor="Tasa"/>
            <cfdi:Traslado Base="1606.01" Importe="256.97" Impuesto="002" TasaOCuota="0.160000" TipoFactor="Tasa"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

Y el pago, que liquidó totalmente a la factura lo reporta así.  Podemos revisar que tanto el IVA como el IEPS en el pago, lo está reportando incorrectamente.

                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="640.500000" ImporteP="102.480000" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                        <pago20:TrasladoP BaseP="418.630000" ImporteP="221.873900" ImpuestoP="003" TasaOCuotaP="0.530000" TipoFactorP="Tasa"/>                    
</pago20:TrasladosP>                
</pago20:ImpuestosP>            

en la sección de totales del pago, igual reporta mal el IVA:

            <pago20:Totales MontoTotalPagos="1862.98" TotalTrasladosBaseIVA16="640.50" TotalTrasladosImpuestoIVA16="102.48"/>

**Comment by jccastillo0007** [comment]
fixed
