### ISSUE TITLE
Optibelt - CFDI + CCE, convertir piezas a KG para propósitos del CCE.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2107]
Para el tema de piezas a kg, en el complemento de comercio exterior (CCE).
Integraremos una tabla de conversión, donde se contendrá lo siguiente:

ID producto – Peso en Kg

Es decir el identificador de producto y su peso en KG. El identificador debe ser único para cada producto, y es el mismo que aparece en el archivo de texto. Según yo este es el identificador, que es el que se reporta en el XML estándar como NoIdentificacion="4014486081336-2"

D|**_4014486049459_**|40103900|                   5M   200077ZA  optibelt OMEGA||2.00|Pz||498.70||||||||||||||||498.70|16.00|||A|11/03/22|228133342000631||||||997.40|997.40|159.584||

Cuando en la factura se incluya un producto, que exista en esa tabla y además se requiera el CCE, entonces se calculará lo siguiente para el CCE:
a)	Unidad = le asignará la que corresponda a KG, es decir **01**
b)	Cantidad = número de piezas * peso en Kg
c)	Total = es el mismo de la factura estándar, expresado en USD porque así lo pide el SAT.
d)	Precio unitario = Total / cantidad

La fracción arancelaria que corresponda a la unidad de kg, se deberá incluir en el archivo de texto, tal cual se incluye ahora mismo.
La tabla, será un archivo de texto plano con el formato arriba mencionado:

Ejemplo (si se les va un espacio junto al guión del lado izquierdo o derecho, hay que ignorarlo.

4014486081336-0.30
4014486081334-0.25

**Comment by jccastillo0007** [comment]
archivos de prueba, y salida esperada ???? y el archivo o tabla de productos vs peso en kg, donde se va a almacenar ? esa parte no recuerdo como dijimos que quedaría

**Comment by jccastillo0007** [comment]
ya tengo el código para implementar el cambio de kg, ahorita le puse kg = 2.0, mientras vemos lo de las pruebas y la tabla/archivo

**Comment by RigoFlores** [comment]
ok, tu me indicas cuándo pueda probarlo...

**Comment by RigoFlores** [comment]
El archivo de la tabla, lo podemos poner en el mismo directorio de Factura-T, es decir donde se encuentra la llave.

**Comment by RigoFlores** [comment]
No jaló, excepto para la cantidad a nivel de CCE. Es decir, si multiplicó la cantidad en el cfdi estándar, por 2 y lo reflejó como cantidad a nivel CCE.

Ya tengo ejemplos concretos del CCE convertido de piezas a kgs...
Por lo pronto nos basaremos en este.

**Comment by RigoFlores** [comment]
Moneda CFDI: EUR, Tipo de cambio: 20.4863
USD, tipo de cambio: 18.9257
Este producto, tendría la equivalencia en peso de 1.2216
No tenemos archivo de texto, ya que ellos están timbrando con otro proveedor estos XML, pero yo creo que ya no se arreglaron para seguir o que se yo...



[OME111223UN4_231120543E.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10797098/OME111223UN4_231120543E.xml.txt)

**Comment by RigoFlores** [comment]
Para el CCE:

a) Unidad = le asignará la que corresponda a KG, es decir 01
b) Cantidad = cantidad CFDI estándar * peso en Kg = 18 * 1.2216 = 21.99 (o casi 22)
c) Total = es el mismo de la factura estándar, expresado en USD porque así lo pide el SAT. 
Pero como el total está en EUR, entonces el cálculo es total CCE = Total CFDI estándar ( TC EUR / TC USD) = 581.58 * ( 20.4863 / 18.9257 ) = 629.54
d) Precio unitario = Total / cantidad = 629.54 / 21.99 = 28.63

**Comment by RigoFlores** [comment]
OJO, con este cálculo...

c) Total = es el mismo de la factura estándar, expresado en USD porque así lo pide el SAT. 
Pero como el total está en EUR, entonces el cálculo es total CCE = Total CFDI estándar ( TC EUR / TC USD) = 581.58 * ( 20.4863 / 18.9257 ) = 629.54

Si te das cuenta, es lo mismo para MXN, ya que si la factura se hubiera emitido en MXN, el cálculo de arriba sería:

total CCE = Total CFDI estándar ( TC MXN / TC USD) = 581.58 * ( 1 / 18.9257 ) = 30.73

Esto lo comento, ya que con este simple cálculo para el CCE, no importa la moneda de emisión, el total se calculará siempre igual...

**Comment by RigoFlores** [comment]
El producto se pasará de piezas a kg, SIEMPRE Y CUANDO, ÚNICAMENTE, si el ID del producto, existe en el archivo...

**Comment by RigoFlores** [comment]
Oye, por cierto, ese archivo se tiene que abrir y consultar, en modo compartido, que no?
Por si hay varios threads accediendo al mismo

**Comment by jccastillo0007** [comment]
No, porque en el conector no hay threads... es síncrono, archivo por archivo

**Comment by jccastillo0007** [comment]
necesito archivo txt de pruebas, hay varias cosas a considerar y no quiero asumir nada...

Por ejemplo, en un archivo txt que tenía, vi que la información de un producto, trae información a utilizar para el cce

D|4014486286175|84835099|               3VX KB   112077XA  optibelt SUPER KBX-POWER||3.00|Pz||868.62||||||||||||||||868.62|0.00|||A|19/11/15|158133345006304||||||2605.86|2605.86|0.00||||01|0.001|2605860.00|||||||||||||||||||||||||||||

Los datos 43, 44 y 45 se usan para CCE, entonces, no es consistente que se recalculen la cantidad , total y costo unitario, entonces esos datos ya no se usarán ? o se ignoran o como ?

**Comment by RigoFlores** [comment]
Tssss.... creo que no estamos comprendiendo el tema.
Este requisito lo que solicita es que cuando se trate de una factura con CCE, y el o los productos dentro de la factura, se encuentren en el archivo de conversión, para este caso... se convierta piezas a kilos, ÚNICAMENTE PARA EL COMPLEMENTO DE COMERCIO EXTERIOR. Para el caso de CFDI estándar, se mantiene en piezas, normalito, como aparece en el archivo de texto.

Aquí está el excel de como se pasa de uno a otro. La verdad es que está super simple.

[Pz2Kg.xlsx.txt](https://github.com/jccastillo0007/eFacturaT/files/10831806/Pz2Kg.xlsx.txt)

**Comment by RigoFlores** [comment]
El archivo puede ser cualquiera con CCE. 
Aquí te dejo uno. Si haces pruebas hoy, el tipo de cambio del USD debe ser el de un día anterior publicado en el DOF, es decir del jueves, ya que hoy no es día hábil. En este caso 18.3483, que es el del 23 de febrero.

[MXRE211101396 Bartlett.txt](https://github.com/jccastillo0007/eFacturaT/files/10831852/MXRE211101396.Bartlett.txt)


Aquí solo faltaría el archivo con la equivalencia, por ejemplo lo puedes hacer con este contenido, ya que es el EAN que aparece en el archivo. Ese producto, para este ejemplo pesa 0.25 Kg

4014486685565 - 0.25

OJO, no pude timbrar el archivo de ejemplo, por que el parámetro de exportación lo está poniendo a 01, y cuando el CFDI lleva CCE debe ir ese parámetro = 02.

**Comment by jccastillo0007** [comment]
entonces cuando el producto se encuentre en el archivo, se deben ignorar los datos 43, 44 y 45 cierto?

**Comment by jccastillo0007** [comment]
lo del parámetro de exportación que pone en 01, pero debe ser 02, es otro cambio ?

**Comment by jccastillo0007** [comment]
haber checale con el release de hoy... se esta asumiendo un tipo de cambio EUR = 21 y USD = 19
 con este archivo de productos 
[optibelt_productos.txt](https://github.com/jccastillo0007/eFacturaT/files/10832765/optibelt_productos.txt)

**Comment by RigoFlores** [comment]
> entonces cuando el producto se encuentre en el archivo, se deben ignorar los datos 43, 44 y 45 cierto?

No, seguimos sin entender. Sin esos datos, no se podría calcular la información para el CCE expresado en términos de Kg.


> lo del parámetro de exportación que pone en 01, pero debe ser 02, es otro cambio ?

Pues no es cambio, es que el requisito de ese parámetro "exportacion" desde que se solicitó, es que va fijo a 01, excepto cuando el cfdi lleve CCE. Eso yo lo validé en web, pero aquí es la primera ocasión que se presenta.



> haber checale con el release de hoy... se esta asumiendo un tipo de cambio EUR = 21 y USD = 19 con este archivo de productos [optibelt_productos.txt](https://github.com/jccastillo0007/eFacturaT/files/10832765/optibelt_productos.txt)

no se deben asumir esos datos. Se toman del catálogo. Además el tipo de cambio de USD, debe corresponder al publicado el día anterior en el DOF. Si la factura se emite en sábado o domingo, se toma el tipo de cambio del jueves.

**Comment by RigoFlores** [comment]
Aquí te dejo el archivo de prueba, junto con el XML que intentó timbrar, mismo que va comentado en cuanto a los detalles encontrados. Al archivo de prueba, le modifiqué el uso, así que este es el que tienes que ocupar.

[optibleCCE-pz2kg.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10834081/optibleCCE-pz2kg.xml.txt)

[MXRE211101396.Bartlett.txt](https://github.com/jccastillo0007/eFacturaT/files/10834085/MXRE211101396.Bartlett.txt)


OJO, el archivo de equivalencia pieza vs peso en kg, no puede ser así:

4014486685565-1=1.5

ya que el guión, se lo ponemos nosotros porque el CCE no aceptaba (no se ahora) que se repitan identificadores, por eso le agregamos ese guión, pero el archivo debería ir así:

4014486685565=1.5

**Comment by jccastillo0007** [comment]
Aún en tu ejemplo, no haces uso de los datos extra 43, 44 y 45, entonces no entiendo porque dices que no se ignoran, si todo se calcula a partir de los datos del producto original y los tipos de cambio... hay que hablarlo

**Comment by RigoFlores** [comment]
No había identificado esos datos en el detalle. Pensé que se trataba de los datos del producto estándar en el CFDI.
Esos datos que mencionas, donde se ocupan en el CCE? 
Así a simple vista, parece la unidad el primer dato, pero los demás, no sé. 
Coméntame pls..

01|0.001|2605860.00

**Comment by jccastillo0007** [comment]
haber chécale...

**Comment by RigoFlores** [comment]
no hay nueva versión...

**Comment by RigoFlores** [comment]
Se ve ya muy completo, lo que le falta es dentro del CCE, nodo receptor, el parámetro del "NumRegIdTrib".
En la 3.3 ya no se pedía, ahora lo vuelven a pedir. Dentro del nodo receptor estándar se incluye, y también en el nodo receptor del CCE.

cce11:Receptor **NumRegIdTrib=""**
  cce11:Domicilio Calle="1580 W Stearns Rd" CodigoPostal="60103" Estado="IL" Pais="USA"
cce11:Receptor

Estoy ya lo había pedido para el conector estándar con CCE y se corrigió. 
¿No es el mismo código cuando se arma el XML con CCE para el conector estándar que para el de optibelt?


El archivo con las equivalencias no lo cambié, esto es sigue con el guión. Pero ¿ya está atendido el tema que lo lea sin el guión?

4014486685565-1=1.5

**Comment by RigoFlores** [comment]
Aquí ya me indican que hay un ajuste para el tema del peso, y creo que nos conviene para no batallarle con el asunto del guión en el archivo.
El cambio es el siguiente. En lugar de tomar el peso por pieza en el archivo de equivalencias (el independiente), se tomará el peso total de las piezas, en el mismo layout de ellos. Este ajuste cambia en:

Para el CCE **(lo UNICO que cambia es el punto b**):

a) Unidad = le asignará la que corresponda a KG, es decir 01
**b) Cantidad = se toma del campo D.12 del archivo**
c) Total = es el mismo de la factura estándar, expresado en USD porque así lo pide el SAT.
Pero como el total está en EUR, entonces el cálculo es total CCE = Total CFDI estándar ( TC EUR / TC USD) = 581.58 * ( 20.4863 / 18.9257 ) = 629.54
d) Precio unitario = Total / cantidad = 629.54 / 21.99 = 28.63

Ejemplo del archivo de texto con este cambio:

[MXRE231121829.TXT](https://github.com/jccastillo0007/eFacturaT/files/10865621/MXRE231121829.TXT)

Sería el campo en negritas:

D|4014486033014|40103200|    A   52         13   13207700  optibelt VB||2.00|Pz||71.97|||**0.286**|||||||||||||71.97|16.00|||A|14/02/23|238133343000315||||||143.94|143.94|23.03|||||||||||||||||||||||||||||||||||

**Comment by jccastillo0007** [comment]
o que la... ahora debo quitar todo el tema de la lectura del archivo, chiaaa, puro retrabajo por no definir bien las cosas... y luego dicen que les urge

**Comment by jccastillo0007** [comment]
checale con la versión de hoy... ese campo lo usaban para el descuento... supongo que nunca lo usaron... pero luego asi empiezan las inconsistencias..

**Comment by jccastillo0007** [comment]
Duplicado con 2115
