### ISSUE TITLE
Documento Relacionado - a nivel ImpuestosP, no envía todos los traslados al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2108]
Actualmente tenemos estas variables:

	field name="traBaseP1" class="java.lang.String"
	field name="traImporteP1" class="java.lang.String"
	field name="traImpuestoP1" class="java.lang.String"
	field name="traTasaOCuotaP1" class="java.lang.String"
	field name="traTipoFactorP1" class="java.lang.String"
	field name="traBaseP2" class="java.lang.String"
	field name="traImporteP2" class="java.lang.String"
	field name="traImpuestoP2" class="java.lang.String"
	field name="traTasaOCuotaP2" class="java.lang.String"
	field name="traTipoFactorP2" class="java.lang.String"

Pero cuando el pago incluye impuestos trasladados IEPS, no envía TODOS los traslados. Solo envía el IVA.
Se requieren 2 cosas... 
(1) - enviar toda la información de traslados a estas variables  (que son los mismos que se reportan en el nodo ImpuestosP).
(2) - incrementar hasta 4 grupos de estas variables (ahorita solo tenemos 2).

Todo esto surge a partir de los pagos de las barricas, que pueden incluir en el mismo pago hasta 3 distintas tasas de IEPS en los traslados, además del traslado del IVA estándar (16%).

**Comment by jccastillo0007** [comment]
no importa el orden?

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Oye, olvidé mencionar explícitamente que era para el conector.
Si mencioné que era para las barricas, pero no mencioné el conector.
¿Si se atendió en el conector?

**Comment by jccastillo0007** [comment]
si

**Comment by RigoFlores** [comment]
ok, en la última versión disponible del conector, ahí ya está atendido esto???
