### ISSUE TITLE
Conector 4.0 Documento de Pago Jasper - a nivel docto relacionado, incrementar y enviar las tasas de traslado correspondientes.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2109]
Cuando definimos este documento, solo se consideró un impuesto trasladado y 2 retenciones.
Eso consideraba los escenarios conocidos.

Ahora con las barricas, surge la necesidad de incrementar hasta 4 traslados en una misma factura.
Las variables que existen ahora son:

	<field name="traBaseDR" class="java.lang.String"/>
	<field name="traImporteDR" class="java.lang.String"/>
	<field name="traImpuestoDR" class="java.lang.String"/>
	<field name="traTasaOCuotaDR" class="java.lang.String"/>
	<field name="traTipoFactorDR" class="java.lang.String"/>

Esas hay que incrementarlas hasta 4, por ejemplo: traBaseDR2, traBaseDR3 y traBaseDR4. Y así para cada una de las 5.

Y por supuesto, enviar los datos que corresponda.

**Comment by jccastillo0007** [comment]
Done
