### ISSUE TITLE
Complemento de pago Web - cuando la moneda de pago es distinta a la moneda de la factura, aplicar el factor de ajuste

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2110]
El caso más recurrente es cuando la factura se emitió en USD y la pagan en MXN. Tu ya viste que aveces jala y otra no. Finalmente me entenderás porqué es necesario el factor de ajuste. Para forzar a que siempre jale, jeje.

En este caso la equivalenciaDR se calcula = total factura USD / importe pagado MXN  (o parcal, si es el caso).
Esto arrojará un dato de 6 decimales.

A este dato, el factor de ajuste no será más una multiplicación * 1.000002, sino mas bien será una suma. Se le sumará 0.000001 
Ejemplo:
Factura: $3712.00 USD
Pago:  $72,384.00  MXN
EquivalenciaDR = 3712/72384 = 0.051282
con el factor de ajuste: EquivalenciaDR = 0.051282 + 0.000001 = 0.051283

Y con esto ya no marcará el error.
OJO este factor de ajuste, solo aplicará para el caso en que las monedas de pago y de la factura, sean distintas.

**Comment by jccastillo0007** [comment]
hmmmmta, se va a romper todo otra vez.... estas seguro ....

**Comment by RigoFlores** [comment]
pues el factor anterior, tenía exactamente esa intención, solo que no siempre alteraba al equivalencia... al sumarle ese factor, aseguramos que se altere la equivalencia... por muy poco, esto es 0.000001, pero eso alcanza para que no esté marcando ese error.

OJO, solo cuando las monedas sean distintas, será necesario.

Lo que no estoy seguro, que pasa si pagan en USD una factura emitida en MXN, yo no he visto ese caso, es más, según yo no lo acepta el SAT... el factor trabajará bien, siempre que la moneda de pago sea MXN y la otra USD, EUR, o cualquier otra con denominación mas alta que el peso mexicano.

**Comment by RigoFlores** [comment]
Oye, sigue el cliente esperando esta solución

**Comment by jccastillo0007** [comment]
done, hay que probar tooooodos los posibles escenarios.

**Comment by RigoFlores** [comment]
OK, tengo una batería de pruebas.
Pregunta, si quedó únicamente para cuando la moneda del pago es distinta a la moneda de documento relacionado???
