### ISSUE TITLE
LAS BARRICAS - PDF DEL COMPLEMENTO DE PAGO, NO LO ALMACENA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2111]
Está muy raro.
Genera el XML
Genera la imagen del CBB
Arroja a la pantalla, la vista del PDF timbrado (en el conector se puede indicar que cada timbre, lo presente en pantalla en su equivalente en PDF).

Pero cuando voy a buscarlo a la carpeta de Feb2023\PDF... no existe el PDF, solo el PNG...

que será tu??

**Comment by jccastillo0007** [comment]
fixed.

Puedes hacer pruebas de:
No impresión
Impresión default
Impresión es una impresora específica, sin copia
Impresión es una impresora específica, con copia

**Comment by RigoFlores** [comment]
Se validó lo siguiente:

a) Sin ninguna leyenda de impresión
b) impresora=
c) impresora=BrotherAlambrica
d) impresora=BrotherAlambrica|copia

a y b, no imprimen OK
c imprime 1 
d imprime 2

esto está bien, a que le llamas default???
