### ISSUE TITLE
Cómo se obtiene la forma de pago en Optibelt?

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2112]
He identificado algunas inconsistencias cuando se procesan algunos archivos de optibelt, pero en particular con la forma de pago.
Me parece que tiene que ver con la manera en que se define la forma de pago para el XML.

¿me indicas cómo se obtiene dicha forma de pago y también el método de pago?

**Comment by jccastillo0007** [comment]
Renglón H1, posición 8, de derecha a izquierda, 
se toman las posiciones 1 y 2 para el uso de cfdi, pero si es nota de crédito, el uso de cfdi se fija en G02
se toman las posiciones 3 y 4 para forma de pago 
el método de pago, primero se fija en NA
de la posición 31
si dice cheque, se pone PPD
si dice recibo, se pone PUE

**Comment by RigoFlores** [comment]
listo, gracias
