### ISSUE TITLE
Conector de Optibelt - el tema de los decimales en la base y el importe de los impuestos. Genera errores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2113]
En el archivo de texto de optibelt, el importe y el IVA, viene a 2 decimales.
En el XML, se reporta a 6 decimales, y es el pedo de siempre, perdemos rango de holgura y es muy común que marque error.
Tenemos de 2 sopas:

a) Manejar las bases e importes reportados a 2 decimales (justo como las barricas y figueacero) y así mandarlos al XML ó
b) Recalcular el IVA y reportarlo a 4 decimales, amén de sumar todos los IVAs y recalcular el traslado total (sumatoria de IVAs parciales, redondeado a 2 decimales) y el total de la factura.

Con este archivo puedes reproducir el problema.

[optibeltEjemplo.TXT](https://github.com/jccastillo0007/eFacturaT/files/10809265/optibeltEjemplo.TXT)

Este archivo, es el mismo que el anterior pero con 4 decimales en el IVA a nivel producto, y ahí si lo timbra. 
No es suficiente pasar los IVAs a 4 decimales, hay que sumarlos todos y reportar su redondeo a nivel general. Si varía 1 o más centavos con respecto al IVA en el archivo, pues hay que cambiarlo y el total también ya se afectó.

[MXRE231121489.txt](https://github.com/jccastillo0007/eFacturaT/files/10809275/MXRE231121489.txt)

**Comment by jccastillo0007** [comment]
duplicado
