### ISSUE TITLE
complemento de pago - factoraje, no soporta mas de 1 factura pagada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2114]
Creo que el complemento de pago, ya está bastante bien.
No había probado el tema de factoraje con más de 1 factura, y ahora que lo probé, no genera el complemento. 
Marca error no clasificado, por que además del header, solo genera lo siguiente, es decir deja fuera todo el nodo de complemento.

    <cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="CMA140408LM6" Nombre="COMERCIALIZADORA MATSA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="601" UsoCFDI="CP01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago" ValorUnitario="0" Importe="0" ObjetoImp="01"/>
    </cfdi:Conceptos>
</cfdi:Comprobante>

**Comment by jccastillo0007** [comment]
datos de prueba ?

**Comment by RigoFlores** [comment]
Emisor: IIA
Receptor: La TIA

Facturas y montos a pagar:
484 $1,100.00
492: $1,070,000.00

El saldo insoluto (restante) de cada factura, se suma y debe aparece en la sección de factoraje.
Con una factura trabaja bien, pero con 2, ya no incluye siquiera el nodo del complemento de pago.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Si, ya formó el XML, pero si trae algunos detalles, mismos que indico en el XML que intentó timbrar y que estoy anexando aquí.

[factoraje.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10851625/factoraje.xml.txt)

**Comment by jccastillo0007** [comment]
me parece que todos los detalles son por el total del segundo nodo, no lo esta haciendo bien..

**Comment by RigoFlores** [comment]
Pues es probable, no quise asumir nada, solo mencioné todo donde encontré datos incorrectos.

**Comment by RigoFlores** [comment]
Ya hice la prueba, y parece que está igual:

con el mismo escenario de prueba, te dejo aquí el xml comentado

[factoraje.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10884679/factoraje.xml.txt)

En el paso 4, de factoraje, se ve el importe pagado del 2o nodo así como los pagos a cada factura. Eso no se refleja en el nodo 2.

<img width="806" alt="nodo2Factoraje" src="https://user-images.githubusercontent.com/2912775/222785876-557b35d2-c5ed-4fd4-a3ab-3de2290eb2dd.PNG">

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Vientos, ya hice un pago con 5 facturas y factoraje, y lo hizo bien.
Hasta el momento, solo serán facturas con solo IVA. Eso lo consulté con el cliente.

De este punto, no hay plugin veldá???
