### ISSUE TITLE
Conector Optibelt - CCE, conversión de EUR a USD, conversión de Piezas a KG

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2115]
Lo que ya jalaba, otra vez dejó de jalar, casi todo. 
El tema es de conector de Optibelt, cuando incluye CCE.
Inicialmente el tema de conversión de moneda, ya que el CCE se reporta en USD (TC 18.3448) y el CFDI estándar en cualquier moneda, en este ejemplo EUR (TC 22.00), pero puede ser MXN o cualquier otra.

Factor de Conversión Moneda (FCM) = (Tipo de cambio moneda CFDI / Tipo de Cambio USD ) = 22 / 18.3448 = 1.199249

Implementación del CCE:

a) Unidad = le asignará la que corresponda a KG, es decir 01
b) Cantidad = se toma del campo D.12 del archivo
c) ValorDolares= es el mismo de la factura estándar (importe), expresado en USD porque así lo pide el SAT.
Pero como el total está en EUR, entonces el cálculo es total CCE = Total CFDI estándar * FCM = 581.58 * 1.199249 = 697.459233
d) ValorUnitarioAduana = Total / cantidad = 629.54 / 21.99 = 28.63
e) Incluir el NumRegId en el nodo receptor
f) Poner en el parámetro de exportación = '02'

**Comment by jccastillo0007** [comment]
hay que definir que no esta jalando y como debe ser

**Comment by RigoFlores** [comment]
OK, te dejo el archivo de texto, y también el XML generado con comentarios.

[Optibelt_CCE_USD-EUR.txt](https://github.com/jccastillo0007/eFacturaT/files/10877645/Optibelt_CCE_USD-EUR.txt)

[cce_eur2usd.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10876413/cce_eur2usd.xml.txt)

**Comment by RigoFlores** [comment]
Si tienes alguna duda, lo platicamos.

**Comment by RigoFlores** [comment]
Me había equivocado en el archivo. Tenía la cantidad (2.0) en la posición D11, y debía ser en la D.12.
Chiiiia, perdón. El pedo de editar a manopla entre tantos putos pipes.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
OK, lo de aquí ya todo quedó atendido.
