### ISSUE TITLE
Conector Las Barricas - Tomar cada concepto en 1 solo renglón

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2116]
En lugar de una cadena larga larga, que se agrupe en varios renglones.
1 producto por renglón.

Tú me dices si mantiene el mismo formato, es decir:

concepto={31162800|A00200024 31162800|1|H87|PZA|31162800|...} 
concepto={31162800|A00200024 31162800|1|H87|PZA|31162800|...} 
concepto={31162800|A00200024 31162800|1|H87|PZA|31162800|...} 

o si queda mejor así (solo agregando enters para no cambiarle demasiado).

concepto={31162800|A00200024 31162800|1|H87|PZA|31162800|...},
{31162800|A00200024 31162800|1|H87|PZA|31162800|...},
{31162800|A00200024 31162800|1|H87|PZA|31162800|...},

**Comment by jccastillo0007** [comment]
listo... no logre timbrar ningún archivo, pero si reconoce muchos renglones concepto

**Comment by RigoFlores** [comment]
dime cómo deben ir los renglones...

**Comment by jccastillo0007** [comment]
[cfdi40.txt](https://github.com/jccastillo0007/eFacturaT/files/10947544/cfdi40.txt)

como este archivo

**Comment by RigoFlores** [comment]
solo está incluyendo en el XML, el último producto.
Aquí el archivo con cifras consistentes.

[variosRenglones.txt](https://github.com/jccastillo0007/eFacturaT/files/10947571/variosRenglones.txt)

**Comment by jccastillo0007** [comment]
Probaste con el archivo que subí? cfdi40.txt

y cual es la diferencia con tu archivo?

**Comment by RigoFlores** [comment]
Lo he mencionado n veces.
El archivo que yo subí, es uno que se timbra bien, con varios productos en un solo renglón.
Lo tomé y desglosé cada producto en un renglón. 

A diferencia del tuyo, que solo replicaste n veces el mismo producto, sin tomar en cuenta los totales, y toda la afectación que implica, el incrementar el número de productos.

**Comment by jccastillo0007** [comment]
pero habías mencionado que no incluia multiples productos, solo el último.. ese es un problema diferente a los totales ?

hay que ser bien específico y claro en los comentarios para no estar revisando cosas diferentes...

**Comment by RigoFlores** [comment]
Si, el error que mencioné es que solo toma el último producto del archivo, eso lo reporté. Ahí mismo mencioné que ese archivo que yo subí, tenía los números consistentes, para poder hacer prueba de timbrado.

Por otro lado, aparte, independiente al error reportado,  respondí a la pregunta específica, de cuál era la diferencia entre tu archivo y el que subí yo?
