### ISSUE TITLE
Optibelt - CCE + EUR + conversión a KG

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2117]
Le encontré 2 detalles:

a) No está incluyendo el régimen fiscal del receptor en el CFDI estándar
b) si el archivo incluye mas de 1 producto, no está reflejando el segundo producto en el CCE.
En este caso, por cada producto en el CFDI estándar, existe una mercancía que se procesa igualito a lo como ya lo hace.
La única diferencia es que a nivel de header del CCE, el TotalUSD = sumatoria de los ValorDolares de cada mercancía

Aquí te dejo un archivo con 2 productos.

(SE ELIMINÓ EL ARCHIVO Y ABAJO YA SE COLOCÓ EL BUENO)...

**Comment by jccastillo0007** [comment]
a) se espera en la posición 16, pero lo enviaste en la posición 15, cuál es la correcta?

**Comment by RigoFlores** [comment]
Nuevamente la regué al editarlo manualmente.
Ya revisé, y lo que ellos enviaron (lo que ya genera su sistema), fue en la posición 16, aunque nosotros la habíamos solicitado en la posición 15 originalmente.

Aquí el archivo corregido.

[Optibelt_CCE_USD-EUR-2.txt](https://github.com/jccastillo0007/eFacturaT/files/10891992/Optibelt_CCE_USD-EUR-2.txt)

**Comment by RigoFlores** [comment]
Lo del régimen fiscal, si lo atiende correctamente. Ese ya está OK

El detalle que si le queda, es que con mas de 1 producto en la factura, solo envía 1 mercancía al CCE.  Y deben ser tantas como productos, ya que es un espejo de las mismas. Si hoy hicieras tus pruebas con los archivos, el tipo de cambio para USD debe ser 18.126

Aquí un archivo con 2 productos:

[Optibelt_CCE_USD-EUR-2.txt](https://github.com/jccastillo0007/eFacturaT/files/10892104/Optibelt_CCE_USD-EUR-2.txt)

Algo curioso, es que no "amarra" los productos de la factura con las mercancías, y aunque solo reporta una mercancía, si lo timbra, jejeje. Eso es un error del SAT, pero bueno. Nosotros nos enfocamos a lo correcto.
Tantos productos en el CFDI estándar, entonces serán igual número de mercancías en el CCE.
