### ISSUE TITLE
Conector - cuando el archivo de texto tiene la extensión en mayúsculas, se lo chuta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2118]
Anteriormente era indistinto si la extensión del archivo de texto se generaba con mayúsculas o minúsculas.

Ahora si la extensión viene con mayúsculas, si lo procesa, pero ya no lo mueve a procesados, simplemente lo desaparece.

Al menos en optibelt, lo generan con mayúsculas. Quizá alguno que otro cliente también.

Hay que dejarlo como estaba antes, es decir que no le afecte que la extensión sea mayúsculas o minúsculas.

**Comment by jccastillo0007** [comment]
no lo pude reproducir, no veo porque no funcionaría....

**Comment by jccastillo0007** [comment]
al menos en caso de error los mueve bien

**Comment by jccastillo0007** [comment]
probé con las barricas y también lo procesa bien en caso de error y de éxito

**Comment by RigoFlores** [comment]
aquí hablamos de optibelt. Las barricas es otra cosa.

cuando el archivo tiene la extensión TXT en mayúsculas y lo procesa bien, entonces es cuando lo borra. Es decir, ya no aparece en procesados, ni en el directorio configurado para leer los archivos planos.

Y optibelt, genera todos sus archivos con extensión en TXT

**Comment by RigoFlores** [comment]
Con el jar que me pasaste, ya no se come los archivos con extensión TXT, ya los pasa bien a procesados.

Sin embargo, cuando ese archivo TXT tiene un error, no está generando el log ni lo pasa a procesados. Entonces se puede quedar en un loop.

con los archivos con extensión .txt, no hay problema.

**Comment by jccastillo0007** [comment]
haber , checale ...

**Comment by jccastillo0007** [comment]
lo malo es que por ahora, no va a eliminar los archivos log, cuando el archivo se vuelva a procesar y lo haga correctamente..

**Comment by RigoFlores** [comment]
Ya vi, esta versión solamente será para optiblet, aunque relamente eso de que borre el log cuando ya se procesa correctamente, me parece que es una función que a todo conector le servirá.

Así que levantaré otro ticket para esto, porque al menos la versión de anoche, no funcionaría para las barricas.
