### ISSUE TITLE
Optibelt + CCE, no trabaja con MXN o USD como moneda original

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2119]
Para EUR quedó bien, pero si la moneda original del CFDI es MXN o USD, entonces no trabaja bien.

En el caso de MXN, de plano marca error, porque el tipo de cambio que envía al CCE es 0.0
En el caso de USD, pareciera que lo toma como si fuera EUR.

Recordar que para el CCE, se debe reportar en USD, y para convertir el ValorDolares a USD, se aplica la siguiente fórmula, que **ES INDEPENDIENTE DE LA MONEDA ORIGEN**:

ValorDolares = Importe * (TC moneda original CFDI / TC de USD).
Pensemos que el importe es = 100.00 y el TC de USD = 18.126

SI fueran MXN:
ValorDolares = 100.00 * (1.0 / 18.126 ) = 100 * 0.055169 = 5.52

SI fueran USD:
ValorDolares = 100.00 * (18.126  / 18.126 ) = 100 * 1 = 100.00

Y así aplica para cualquier moneda. Pareciera que quedó en hardcode para EUR.

Aquí te dejo un archivo en USD, otro en MXN y EUR. Son iguales, solo cambia la moneda del CFDI
El de EUR lo procesa correctamente.

El de MXN marca error.
El de  USD creo que si lo timbra, pero los cálculos son incorrectos (la conversión arriba mencionada). Al parecer lo toma como si la moneda fuera EUR, jeje.

[MXRE231120967-USD.txt](https://github.com/jccastillo0007/eFacturaT/files/10903910/MXRE231120967-USD.txt)
[MXRE231120967-MXN.txt](https://github.com/jccastillo0007/eFacturaT/files/10903911/MXRE231120967-MXN.txt)
[MXRE231120967-EUR.txt](https://github.com/jccastillo0007/eFacturaT/files/10903912/MXRE231120967-EUR.txt)

**Comment by jccastillo0007** [comment]
Para el archivo MXN:
Por las validaciones realizadas cuando la moneda era EUR, efectivamente no se estaba leyendo el valor de USD.
Eso ya esta corregido... 

Para el archivo USD
Mismo caso, no pude probar porque no sé cuales eran los cálculos correctos, y no pude comprobar con el de EUR, porque no me esta timbrando dado el tipo de cambio de USD, es decir, no tengo datos de prueba completos

**Comment by RigoFlores** [comment]
El tipo de cambio, como lo he comentado desde siempre, es el publicado el día anterior en el DOF. Esto es 18.126 hasta las 12 de la noche de hoy.
Aquí está el XML generado con la moneda USD.

Es muy simple, la conversión de USD a USD, no existe, es directa... el factor de conversión es 1.

Aquí podrás ver que los valoresunitarios y valores en dolares del CCE, son distintos a los del CFDI estándar, siendo que ambos están en USD.

[231120967_XEXX010101000_06mar2023_221243.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10905359/231120967_XEXX010101000_06mar2023_221243.xml.txt)

**Comment by RigoFlores** [comment]
Procesé el archivo que la moneda original está en MXN, y si lo hace bien

**Comment by RigoFlores** [comment]
Tons el detalle, sigue estando cuando la moneda original está en USD

**Comment by RigoFlores** [comment]
Si quieres hacer pruebas hoy, le corresponde el tipo de cambio 18.0123.
ahí lo procesará y podrás notar que para USD, realmente está tomando la moneda original como si fuera EUR. Ya lo validé y los cálculos que resultan, son como si la moneda fuera EUR con el tipo de cambio que tiene capturado, en mi caso 22.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
listo, quedó chingón.
