### ISSUE TITLE
ERP- ADDENDA EUM NO REPORTA LOS IMPUESTOS RETENIDOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#212]
NO REPORTA LOS IMPUESTOS RETENIDOS EN EUM

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
HICE UNA PRUEBA Y EL IMPUESTO RETENIDO EN TOTAL ERA 80 PESOS, Y EN EL NODO DE RETENCIÓN REPORTÓ, '0.08'. LO CUAL ES INCORRECTO.
AHORA POR OTRO LADO, LO QUE REALMENTE SE DEBE INCLUIR EN ESTE NODO ES:
MONTO DEL IMPUESTO RETENIDO, ES DECIR YA NO ES LA TASA, SINO AHORA EL MONTO DEL IMPUESTO RETENIDO

**Comment by jccastillo0007** [comment]
Fixed.

Por alguna razón creía que era el total entre 100...
