### ISSUE TITLE
Conector Optibelt + CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2120]
Hay algunos detalles...

a) Cuando el RFC del cliente sea XEXX y se incluya el CCE, el uso de CFDI queda fijo a S01 y el régimen fiscal queda fijo a 616 (son reglas para este caso).

c) Cuando se incluye Cheque como forma de pago (en el texto), entonces la forma de pago es 99 (por definir y el método de pago es PPD). En otro caso (distinto a cheque), la forma de pago será 03 y el método de pago será PUE.

**Comment by jccastillo0007** [comment]
yo creo que esos datos deben ir en el txt, no podemos llenar el código de tantas cosas hardcode, porque luego pueden cambiar y tendremos que regresar a combar las condiciones... 
ellos deben enviar los datos adecuados, pásale a ellos todas esas condiciones

**Comment by RigoFlores** [comment]
OK, forma de pago igual a 03, cuando se indique Transferencia, transferencia electronica, payment in advance (case insentive) y método de pago igual a PUE.

Cuando la se indique cheque, la forma de pago es 99 y método de pago PPD (eso ya está)

El uso de CFDI lo pidieron como cambio el día de hoy, cuando se trate de CCE, el uso será S01

El régimen, pediré que lo incluyan en el archivo

**Comment by jccastillo0007** [comment]
Listo... solo falta que informen bien el regimen
