### ISSUE TITLE
Conector 4.0 con CCP tipo Traslado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2122]
Creo que esto no lo había validado

Este archivo no lo procesa.
Es complemento carta porte tipo traslado. Parece que no reconoce el tipo de comprobante.
puedes revisar por favor, si estamos soportando el tipo traslado con complemento de carta porte?

[cartaPorte.txt](https://github.com/jccastillo0007/eFacturaT/files/10926645/cartaPorte.txt)

**Comment by jccastillo0007** [comment]
Si lo soportamos... en el archivo de texto estas incluyendo el emisor, lo cual significa que es una licencia multirfc, y lo cual significa que se deben tener los archivos de seguridad de ese rfc... no se toman del key o de la base de datos.

o incluyes los archivos de ese rfc en el path correcto, o elimina el emisor del archivo.

Había otro error por lo cual no sabías que pasaba y no generaba el error.log... ya lo corregí.

**Comment by RigoFlores** [comment]
Yo creo que no había validado CCP con CFDI 4.0.
Ya hice los ajustes y marcó error. Finkok me dice que está faltando esto:

<img width="526" alt="namspaces" src="https://user-images.githubusercontent.com/2912775/224074970-ce967a74-45e3-4dd5-ac15-35b426790a30.PNG">

**Comment by jccastillo0007** [comment]
con que archivo pruebo? el de arriba aún quitando el emisor no jala

**Comment by RigoFlores** [comment]
Pues precisamente, quitando lo del emisor, al intentar timbrarlo marca error de los locations. Hasta ahí es que puedo avanzar.
La imagen es la respuesta de Finkok, ya que yo no sabía por donde estaba el asunto.

Este es el archivo que marca error...

[cartaPorte.txt](https://github.com/jccastillo0007/eFacturaT/files/10943585/cartaPorte.txt)

**Comment by jccastillo0007** [comment]
chiaaa , pues si lo genera bien con los schema location... 

[temp.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10947277/temp.xml.txt)

cómo te lo genera a ti?

**Comment by jccastillo0007** [comment]
compáralo con uno que se genera desde web

El validador de finkok, marco error en el nombre del receptor, pero no dijo nada de los schema location

**Comment by RigoFlores** [comment]
En producción, si se incluye lo que está pidiendo finkok, respecto a los locations. 
Y en el conector 4.0, no se incluye este tema de los locations.

Aquí está un XML con CCP.

[FE343_STR100119524_PCA190530BD0_04Mar2023_145819.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10958567/FE343_STR100119524_PCA190530BD0_04Mar2023_145819.xml.txt)

**Comment by jccastillo0007** [comment]
el que yo genere si incluye los schema location... y lo hice con el conector

No lo revisaste?

**Comment by RigoFlores** [comment]
No se donde lo estás viendo, pero en el catalina.log ahí marca el error, y si le falta los locations del complemento de carta porte.

En la consola, ahí si aparecen los locations en alguna parte. Mira la imagen. Tons ya no entendí.

<img width="796" alt="catalina" src="https://user-images.githubusercontent.com/2912775/224845260-7f723b83-70ca-4fa5-bf65-7488cb5f9f52.PNG">

**Comment by jccastillo0007** [comment]
ok, el error de schemas location ya quedo arreglado... 
ahora manda este error :

El valor del atributo "Comprobante:TipoDeComprobante" es diferente de "T" y el valor registrado en el atributo "Comprobante:Receptor:Rfc" es diferente al  registrado en "Comprobante:Emisor:Rfc".
