### ISSUE TITLE
Conector Optibelt - en facturas SIN CCE, no parsea ni incluye el régimen fiscal del receptor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2123]
Se me ocurrió hacer pruebas con textos de facturas sin el complemento de comercio exterior, y ya no parsea el régimen fiscal del receptor.

Este es el archivo de ejemplo, lo tengo en la batería de datos que ya estaba validada.

[MXRE231121829.txt](https://github.com/jccastillo0007/eFacturaT/files/10935480/MXRE231121829.txt)

**Comment by jccastillo0007** [comment]
si lo parsea
[temp.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10938051/temp.xml.txt)
