### ISSUE TITLE
Conector Optibelt - está enviando exportacion = 02, cuando no se incluye el CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2124]
Cuando inició lo del CCE en optibelt, hace años, recuerdo que las condiciones para saber que se iba a incluir el CCE eran:

a) RFC receptor = XEXX010101000  (EXTRANJERO)
b) Se incluía el dato del RegIdTrib (es el equivalente del RFC en el país extranjero). Este dato, según yo viene justo después del rfc receptor en el archivo de texto de optibelt (abajo en negritas).

H4|Optibelt USA Corporation|**XEXX010101000**|**362907489**|1580 W Stearns Rd||||||Bartlett|IL|USA|60103|616||||||||||||

Cuando se incluye CCE, exportacion = 02, en otro caso = 01.

Ahora mismo, ya no sé cuáles son las condiciones que está tomando para considerar que se trata del CCE, pero a este archivo le está reportando que Exportacion=02, y no contiene la info para el CCE

[MXRE231121829.txt](https://github.com/jccastillo0007/eFacturaT/files/10935576/MXRE231121829.txt)

**Comment by RigoFlores** [comment]
Creo que ya identifiqué:  si incluye el peso en kgs, considera que lleva CCE.
Y no, no es el caso.
Según yo la condición si es la arriba mencionada.

**Comment by jccastillo0007** [comment]
Esto es lo que pasa por estar metiendo nosotros los datos, y no que ellos lo informen en su txt... no debemos hacer esto porque siempre hay cambios, y luego ya ni nos acordamos porque.

fixed

**Comment by RigoFlores** [comment]
Si, la historia con ellos, es que es complicado modificar su ERP, ya que eso se hace desde Alemania.
De ahí que ellos hayan decidido que nosotros les resolvamos varios temas de la facturación.
No es lo óptimo, pero pues es lo que tenemos que hacer para resolverles.

Yo creo que ellos, en algún momento van a migrar a SAP, y de ahí pues no tenemos de un conector o similar.
Creo que ya tenemos que ir metiéndonos en ese tema, para este y otros clientes que pudieran requerirlo.
