### ISSUE TITLE
Conector - Complemento de Pago, parsear los impuestos a nivel nodoDR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2125]
Ya platicamos que se está haciendo un desmadre con los impuestos, cuando a una factura le quieren "descontar" una nota de crédito, a nivel de producto y pues con la afectación en los impuestos que corresponda. 
Por mencionar un ejemplo, si ese producto era el único que tenía IEPS a 53%, pues ese impuesto desaparece al momento del pago. Complicado el asunto.

Entonces ahora quedaría de la siguiente manera. 

Estoy subiendo el archivo de texto de la factura, la factura generada y el texto del pago con el nuevo layout, que incluye la información del desglose de impuestos a nivelDR.
Si el pago ampara varias facturas, pues sería un renglón por cada factura pagada.

[PPM032069.txt](https://github.com/jccastillo0007/eFacturaT/files/10947316/PPM032069.txt)

[PPM32041_VVI2009173H6_10mar2023_194008.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/10947322/PPM32041_VVI2009173H6_10mar2023_194008.xml.txt)

[PPM032069_PAGO_NEW.txt](https://github.com/jccastillo0007/eFacturaT/files/10947325/PPM032069_PAGO_NEW.txt)

**Comment by jccastillo0007** [comment]
ok,  eso sirve, pero genera un ejemplo real con varios DR y varios impuestos por DR

**Comment by RigoFlores** [comment]
si, aguanta.
Están chuecos estos archivos.

**Comment by RigoFlores** [comment]
Aquí está uno con 2 documentos relacionados.
Estoy subiendo los 2 archivos que generan las facturas. 
Las facturas únicamente nos servirán para validar que los totales, bases y impuestos son tal cual se incluyen en el archivo de texto de pagos. 
Con este nuevo approach, ya no es necesario que existan las facturas en la BD.

Entonces, estos 2 archivos, generarán las facturas. Ahí corroboramos que las cantidades en el archivo de texto plano de pago, son correctas. Ya solo falta ponerle los corchetes al archivo de pago

[PAGO_032041y32072_NEW.txt](https://github.com/jccastillo0007/eFacturaT/files/10947552/PAGO_032041y32072_NEW.txt)

[PPM032041.txt](https://github.com/jccastillo0007/eFacturaT/files/10947555/PPM032041.txt)
[PPM032072.txt](https://github.com/jccastillo0007/eFacturaT/files/10947556/PPM032072.txt)

**Comment by jccastillo0007** [comment]
este cambio no es sencillo, sugiero terminar todo lo demás, porque varias cosas se van a romper...

hay que soportar ambos layouts cierto?

**Comment by RigoFlores** [comment]
si, porque esto solo aplica para las barricas... y quizás después se le ocurra a figueacero

**Comment by RigoFlores** [comment]
La verdad, no sé como esté implementado.
Pero todo parte de esos datos que ya estarán enviando por cada documento relacionado.

Actualmente, de alguna manera se leen o calculan dichos datos. Después de ello, ya todo el procesamiento debe ser igual a lo que hoy tenemos.

**Comment by jccastillo0007** [comment]
que corchetes del archivo de pago dices ?

**Comment by jccastillo0007** [comment]
este cambio si esta cañon... voy a tener que hacer un connector específico para las barricas, ya son demasiadas cosas específicas para ellos, y el conector genérico, se esta haciendo muy muy grande

**Comment by RigoFlores** [comment]
> que corchetes del archivo de pago dices ?

Comentaste, que como cada DR puede tener uno o varios impuestos trasladados, entonces tendría que ir en corchetes.
Voy a revisar ese correo y ya actualizo los archivos.

**Comment by RigoFlores** [comment]
Aquí está el archivo de pago, ya actualizado con los corchetes que indicaste por correo... los archivos de las facturas permanecen sin cambio..

[PAGO_032041y32072_NEW.txt](https://github.com/jccastillo0007/eFacturaT/files/11002536/PAGO_032041y32072_NEW.txt)
[PPM032041.txt](https://github.com/jccastillo0007/eFacturaT/files/11002545/PPM032041.txt)
[PPM032072.txt](https://github.com/jccastillo0007/eFacturaT/files/11002546/PPM032072.txt)

**Comment by jccastillo0007** [comment]
oye, de cada documento de pago falta informar:
la moneda de la factura pagada
el total de la factura pagada

**Comment by RigoFlores** [comment]
A NIVEL GENERAL, AQUÍ ESTÁ LA MONEDA EN QUE SE PAGÓ Y EL PAGO REALIZADO A TODAS LAS FACTURAS:

pago=2023-02-13|03|MXN||53807.31|02022023||||||||||

A NIVEL DOCTO RELACIONADO, AQUÍ ESTÁ LA MONEDA EN QUE SE EMITIÓ. ASÍ COMO EL PAGO REALIZADO.
EL PAGO REALIZADO VIENE JUSTO ANTES DE LA LEYENDA TrasladosDR, en este orden: SALDO ANTERIOR, IMPORTE PAGADO, SALDO INSOLUTO.


documentoRelacionado={MAF121022532|D8174464-71F1-55AA-BB7E-1D6EB0A839E2|PPM|0032041|MXN|PPD|1|51944.33|51944.33|0.00}TrasladosDR{482.10|127.76|003|0.265|Tasa}{25020.89|13261.07|003|0.530|Tasa}{4529.07|1358.72|003|0.300|Tasa}{44779.61|7164.72|002|0.160|Tasa}RetencionesDR{||||}

documentoRelacionado={MAF121022532|D8174464-71F1-55AA-BB7E-1D6EB0A839E2|PPM|0032072|MXN|PPD|1|1862.98|1862.98|0.00}TrasladosDR{1049.68|556.33|003|0.530|Tasa}{1606.01|256.97|002|0.160|Tasa}RetencionesDR{||||}

**Comment by jccastillo0007** [comment]
para la moneda de la factura pagada, cierto, ya estamos ok.

Pero para hacer el calculo chacarron de equivalencia, se necesita el total de la factura, mas no SALDO ANTERIOR, IMPORTE PAGADO, SALDO INSOLUTO

**Comment by jccastillo0007** [comment]
No, en realidad no se ocupa el factor, ya que no haremos cálculos , ellos deben de entregar los impuestos ya con los cálculos requeridos...

Subí una versión para probar.

**Comment by RigoFlores** [comment]
Ya vi, y si lo hace bien, solo que volvemos a caer en lo mismo del los importesDR e ImportesP, se tienen que reportar a 2 decimales. Si es posible, la base también.
Ahorita se reporta así, y marca errores, pero son por los límites inferior y superior:

BaseDR="44779.610000" ImporteDR="**_7164.720000"_**

 BaseP="46385.620000" _**ImporteP="7421.690000"**_ ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"

**Comment by RigoFlores** [comment]
Como bien comentas, en el otro esquema, nosotros reportamos la base y los importes a 6 decimales, ya que esos datos se toman de la base de datos,  y de ahí todo se reporta a 6 decimales.

Y volvemos a caer en lo que yo propuse desde el inicio hace mas de 1 año; que lo que se reportaba en el nodo resumen de impuestos en el CFDI timbrado, que eso se almacenara. Yo creo que con ello, no estaríamos pasando tanto problema con el tema de los decimales.

El punto, es que algunos clientes muy especiales, quieren sus XML y todo a 2 decimales. A la mayoría no le importa.

Para recordarte cómo es la afectación de los decimales en los importes:

Esta base del IVA a 16%, 1606.010000, a 6 decimales sus límites inferior y superior son: 256.96144 y 256.96176
El margen de holgura es de 0.00032, casi nada.

Esa misma base a 2 decimales 1606.01, a 2 decimales sus límites inferior y superior son: 256.9456 y 256.98
El margen de holgura es de 0.0344, lo cual son mas de 3 centavos!!!!

**Comment by RigoFlores** [comment]
La regla sería... que si la cantidad la tenemos a 2 decimales, pues se reporte a 2, si la tenemos a 3 se reporta a 3, y así sucesivamente.
Esa sería la regla que aplicaría para todos.

Pero si no es posible, entonces si se tiene que calcular el importe a partir de la base que sea, el importe resultante se truncaría a 2 decimales a nivel de documento relacionado. Aplica para ImporteDR y para ImporteP

**Comment by jccastillo0007** [comment]
ya puedes probar el cambio de importeDR e importe P

**Comment by RigoFlores** [comment]
Si lo timbró.
Es un cambio únicamente para las barricas, o quedó para el conector y CFDI tipo pago?

**Comment by RigoFlores** [comment]
Durante mis pruebas, noté algo muy raro.
Si copio las cifras de bases e importes, idénticos a como aparece en el XML original (timbrado por finkok), no lo timbra, porque las cifras no coinciden. Varía por 1 centavo. Al modificarlas ya jaló.
Ese punto podría repetirse n veces, por ello estoy sugiriendo a las barricas, que únicamente tomen la base y de ahí se sigan para adelante haciendo los cálculos. A ver como resulta.

Me es muy complicado identificar si esa variación en las cifras, viene de origen o nosotros la estamos inyectando. Las facturas de Las barricas, tienen muchos productos y con varios impuestos, tons hay que ir tomado uno por uno, y todos sus datos para ver donde se origina el pedo. Pero bueno, ahorita por lo pronto, así lo dejaremos, pero estaremos pendientes de cómo se comporta.

Te preguntaba si el cambio a 2 decimales para los importes, solo quedó para barricas o en general para todo el conector???

**Comment by jccastillo0007** [comment]
no, no solo barricas, para todos.

**Comment by RigoFlores** [comment]
no, pero los demás clientes "qué culpa tienen?"... no les podemos partir la mami de esa manera.
Barricas porque tiene escenarios que se salen de nuestro alcance, pero los demás no... y eso está muy cabrón.

**Comment by jccastillo0007** [comment]
no se puede aislar a un solo cliente, hay que probar con otros escenarios, no creo que se tenga problema, de hecho esta mas exacto no?
