### ISSUE TITLE
Conector con CCP - cuando no incluye remolques, marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2127]
Conector, en ambiente de pruebas, con complemento de carta porte CFDI 4.0
Este archivo con esta llave, marca error al generar el PDF.

SI timbra y genera el XML , pero en el PDF marca error, según yo porque no incluye remolques y los espera de alguna manera.

[facturaT_IIA040805DZ4.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/10974582/facturaT_IIA040805DZ4.cfdi.txt)

[XX013.txt](https://github.com/jccastillo0007/eFacturaT/files/10974583/XX013.txt)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
si tuve que actualizar la versión, ya que el problema era local, no generaba el PDF
