### ISSUE TITLE
Conector - tiene problemas con la Ñ

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2128]
Este punto no debía ser solo de las barricas.
Para el nombre del receptor, en todo tipo de conector o en sí la versión de escritorio, no debe tener problema con la Ñ.

Aquí te dejo el archivo de texto y la llave para reproducir el problema; igualmente parte del catalina donde se observa el detalle...

[TABACHINES.txt](https://github.com/jccastillo0007/eFacturaT/files/10994808/TABACHINES.txt)

[facturaT_IIA040805DZ4.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/10994813/facturaT_IIA040805DZ4.cfdi.txt)

Esto es lo que arroja el catalina.out

    **_<cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="626"/>
    <cfdi:Receptor Rfc="SACG660626E17" Nombre="GUILLERMO SALGADO CASTA�EDA" DomicilioFiscalReceptor="62450" RegimenFiscalReceptor="611" UsoCFDI="S01"/>_**

**Comment by jccastillo0007** [comment]
El nombre no aparece correcto en el txt, chiaaaa

**Comment by RigoFlores** [comment]
no entiendo a que te refieres.
Mira, así lo veo yo... 

<img width="786" alt="tabachines" src="https://user-images.githubusercontent.com/2912775/225930391-48385587-6a65-44e4-b47d-87d9d515fdf5.PNG">

**Comment by RigoFlores** [comment]
Aquí te dejo un archivo que no jala y otro que si jala. para las barricas. 
no jala
[PJV004927_Ñnojala.txt](https://github.com/jccastillo0007/eFacturaT/files/11217475/PJV004927_Nnojala.txt)

si jala
[LVF002059_llevaÑ.txt](https://github.com/jccastillo0007/eFacturaT/files/11217478/LVF002059_llevaN.txt)

Este no jala para figueacero:
[figueaceroÑ no jala.txt](https://github.com/jccastillo0007/eFacturaT/files/11217488/figueaceroN.no.jala.txt)

llave de las barricas

[facturaT_XIQB891116QE4.cfdi.LasBarricas.txt](https://github.com/jccastillo0007/eFacturaT/files/11217491/facturaT_XIQB891116QE4.cfdi.LasBarricas.txt)

**Comment by jccastillo0007** [comment]
hay un problema con el encoding del archivo, mira

jccastillo ~/JC/IT/FacturaT/runtime/flatfiles/reintenteMasTarde$ file LVF002059_llevaN.txt 
LVF002059_llevaN.txt: **Unicode text, UTF-8 text,** with very long lines (483), with CRLF line terminators
jccastillo ~/JC/IT/FacturaT/runtime/flatfiles/reintenteMasTarde$ file PJV004927_Nnojala.txt 
PJV004927_Nnojala.txt: **ISO-8859 text,** with CRLF line terminators
jccastillo ~/JC/IT/FacturaT/runtime/flatfiles/reintenteMasTarde$ file figueaceroN.no.jala.txt 
figueaceroN.no.jala.txt: **ISO-8859 text**, with very long lines (1479), with CRLF line terminators

Por eso el primero jala y el otro no

**Comment by jccastillo0007** [comment]
Por eso uno jala y el otro no

**Comment by jccastillo0007** [comment]
ya sea ellos o tu al momento de generar el archivo, deben asegurarse que sea UTF-8

**Comment by RigoFlores** [comment]
en términos mas entendibles, ¿qué les debo pedir a ellos?
y/o con qué herramientas puedo demostrarles eso del enconding?

Checa en windows como puedes ver el encoding de un archivo, para ver que no sea cosa de MAC
