### ISSUE TITLE
No está sumando correctamente las retenciones en un pago con factoraje

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2129]
Este cliente fue el que pagó por el factoraje.
No puedo copiar el XML del catalina. está algo largo. El llega a ocupar hasta 200 facturas en un solo pago, chiaaaa...

Lo que si te puedo dar, es la referencia del catalina.out donde justo inicia ese XML que no se pudo timbrar. Es después de esta línea.

2023-03-17 17:16:30,766 DEBUG [https-jsse-nio-8443-exec-34] (JaxbXMLProvider.java:112) - marshall XML

Te dejo un excel donde capturé las bases y los importes de las retenciones del IVA del 4% de los 2 nodos.
El nodo 1 está todo bien.
El nodo 2 tiene una variación de 1 centavo, y por ello no timbra. Si se realiza la suma aritmética simple de las retenciones, en el nodo 2, no se porqué, pero reporta un centavo de menos.
Marca lo siguiente:

 **_El campo ImporteP  que corresponde a Retención, no es igual a la suma de los importes de los impuestos retenidos registrados en el documento relacionado donde el impuesto sea igual al campo ImpuestoP de este elemento._**

[factorajeretenciones.xlsx.TXT](https://github.com/jccastillo0007/eFacturaT/files/11007216/factorajeretenciones.xlsx.TXT)

**Comment by jccastillo0007** [comment]
pues son tus cálculos chacarrones y factor de no se que madres jajaja

**Comment by RigoFlores** [comment]
los cálculos son una suma aritmética, básica.
el factor de ajuste, aplica ÚNICAMENTE, cuando la moneda de pago es distinta a la moneda del DR, lo cual aquí no es el caso

**Comment by jccastillo0007** [comment]
cómo lo reproduzco ?

**Comment by RigoFlores** [comment]
Pues en teoría te puse la referencia en el catalina, para que de ahi, pudieras copiar el XML que intentó timbrar, y con ello, reproducir el problema.
Cabe mencionar que este cliente no ha tenido problema alguno con otros pagos emitidos, igual con factoraje.
Solo fue este caso.
Como le urge, le pedí que lo emitiera en 3.3, y que me enviara el XML para que de ahí, tomemos el escenario que genera el problema. Son varias facturas, en total 21, así que bueno, sencillo no será, pero ya te daré todos los datos para que puedas reproducirlo.

**Comment by RigoFlores** [comment]
Ya se le volvió a presentar.
El primer pago lo hace todo bien.
De el primer pago se queda un saldo insoluto, cuya sumatoria (de los saldos insolutos de cada DR) es precisamente el importe pagado del segundo nodo de pago.
Ahí es donde está chafeando.

mira aquí está el XML que marcó el error, y un excel con los datos de los importes anterior, pagados e insolutos, así como sus sumatorias.
Hay una diferencia de 2 centavos en este caso, y por ello marca el error. Este es el encabezado del segundo nodo. El monto dice **3568.67**, pero la sumatoria de los importes pagados de ese segundo nodo, es **3568.69**

<pago10:Pago FechaPago="2023-03-31T12:00:00" FormaDePagoP="17" MonedaP="MXN" Monto="3568.67" NumOperacion="PAGO3103HSBC">

¿Cómo lo puedes reproducir?, pues capturando ese pago en producción.
La otra es revisar cómo se genera el dato de Monto, en ese segundo nodo de pago. Ahí creo que está el detalle.


[FACTORAJE_iNCORRECTO.xlsx.txt](https://github.com/jccastillo0007/eFacturaT/files/11125627/FACTORAJE_iNCORRECTO.xlsx.txt)
[FACTORAJE_ERROR.XML.txt](https://github.com/jccastillo0007/eFacturaT/files/11125628/FACTORAJE_ERROR.XML.txt)

**Comment by jccastillo0007** [comment]
ya no me salen esas facturas en producción, no lo puedo reproducir...
necesito ver en que momento se hacen mal los cálculos... seguramente son los decimales en la base de datos... 
pero no puedo verlo

**Comment by RigoFlores** [comment]
pues si, si se puede ver si revisas los documentos que subi...

 select id, total from CFD_FinancialDetails where id in  ( select financialDetails_id  from CFD where sourceRFC = 'MPB041122H93' and  serie = "CPI" and folio in ('3175','3176','3177','3178','3179','3180','3181','3183','3184', '3185','3186','3187','3188','3189','3190','3191','3192','3193', '3194','3195','3196','3197','3198','3199','3200','3201') );

**Comment by RigoFlores** [comment]
+----------+--------------------+
| id       | total              |
+----------+--------------------+
| 14418913 | 25748.800000000003 |
| 14418430 |          1867.8688 |
| 14416959 | 13182.400000000001 |
| 14416848 |         15412.0288 |
| 14416713 |          1425.0768 |
| 14416652 |          1867.8688 |
| 14416648 |         15412.0288 |
| 14416632 |          3176.0736 |
| 14415892 |          1425.0768 |
| 14413746 |               9912 |
| 14413296 | 7611.2735999999995 |
| 14410886 | 13182.400000000001 |
| 14410426 |              35728 |
| 14410420 | 25748.800000000003 |
| 14410177 |          3396.2768 |
| 14410057 |          3839.0688 |
| 14408846 | 13182.400000000001 |
| 14408405 |         15412.0288 |
| 14407094 |          1867.8688 |
| 14407082 |          1425.0768 |
| 14407070 |  5555.200000000001 |
| 14407060 |          5547.3936 |
| 14407039 |            41283.2 |
| 14404990 |            38623.2 |
| 14404204 |              45220 |
| 14419631 |         15412.0288 |
+----------+--------------------+
26 rows in set (0.14 sec)

**Comment by RigoFlores** [comment]
En ooootro issue que abri, mencionaste y cerraste, que ya se guardaba la informacion igual que como se manda en el XML, y estoy viendo que no fue asi

**Comment by jccastillo0007** [comment]
fixed (creo)

**Comment by RigoFlores** [comment]
creo que solo lo puedo probar en producción
lo puedes validar la solución?

**Comment by RigoFlores** [comment]
pues ya generé todas las facturas en pru, para que lo timbres...
estos son los datos de prueba... el resultado que buscamos, es que timbre exitosamente. jeje

[factorajePru.xlsx.txt](https://github.com/jccastillo0007/eFacturaT/files/11206384/factorajePru.xlsx.txt)


archivo actualizado.

**Comment by jccastillo0007** [comment]
fixed... al menos con las facturas de factorajePru.xlsx

**Comment by RigoFlores** [comment]
si, probé con otro y jaló.
solo 2 pinches hora me tomó la prueba, generando inicialmente 37 facturas, no maaaa....
