### ISSUE TITLE
ERP - ADDENDA MABE SOLO JALA CON ELADDENDADOR Y NO DESDE CERO LA FACTURA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#213]
CREO QUE ASÍ ESTÁ EN PRODUCCIÓN, PERO SI HABRÍA QUE CORREGIR

**Comment by jccastillo0007** [comment]
Si este lo detectaste en el ERP, entonces no esta en Produccion, ya que si habiía un problema en el ERP que ya fué corregido.

**Comment by RigoFlores** [comment]
OK, EN PRODUCCIÓN NO SE PUEDE HACER UNA FACTURA DESDE CERO + ADDENDA.
SOLO FUNCIONA EN 2 PASOS, FACTURA + ADDENDADOR.
EN EL ERP YA FUNCIONAN AMBAS.
