### ISSUE TITLE
Web Service SAP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2130]
Desarrollo del API para SAP, para recibir el XML tal cual sin compresión ni encriptación.
Es en ambiente de pruebas, para propósitos de demo.

Será el XML para timbrado tipo ingreso, egreso y pago

**Comment by RigoFlores** [comment]
Le comenté que estaría listo para el lunes 27, ojalá sea buen tiempo aún para ellos.

**Comment by jccastillo0007** [comment]
listo, ya esta con el sellado en pruebas.
Solo funciona para el rfc IVD....

**Comment by RigoFlores** [comment]
OK, ya se lo comenté a Jaime.
Puede hacer pruebas con el emisor IVD pero sin el complemento del concepto.
Vamos a ver que dice..
Si surgen fichas las abrimos en otro ticket
