### ISSUE TITLE
Las Barricas WEB, no está enviando los XML al web.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2131]
Las barricas, ya sabemos que usan conector.
No nos han pedido que almacenemos los XML, pero pues todo cliente nuestro de conector, cuenta con sus XML en web.
Para el caso de las barricas, no lo está almacenando.

**Comment by jccastillo0007** [comment]
hmmmm neta, en las pruebas cuando usas el rfc XIQ... si lo almacena en web? no veo porque con los RFC oficiales no los almacene... me puedes pasar los datos de alguna factura de producción de ellos para ver los logs...

**Comment by RigoFlores** [comment]
Tanto en pruebas como en producción, solo almacena el documento de pago. 
Las facturas y notas de crédito, no las almacena ni en pruebas, ni en producción.

Aquí te dejo el reporte de facturación de ayer. Si está almacenando la data, pero lo que no almacena son los XML.
[Reporte_28Mar2023_063853.csv.txt](https://github.com/jccastillo0007/eFacturaT/files/11089439/Reporte_28Mar2023_063853.csv.txt)

**Comment by jccastillo0007** [comment]
Si lo esta almacenando, pero no se muestra en pantalla por el parche chacarron que se hizo de agregarle 00 al folio... como esta factura:
PFM0010743_DBA990304SP4_XAXX010101000_27Mar2023_093344.xml
En base de datos se tiene el folio 10743, pero el archivo tiene 0010743

**Comment by RigoFlores** [comment]
ok, entonces que procede?

**Comment by jccastillo0007** [comment]
1. Cerrar este ticket - DONE
2. Decirle a las barricas la razón por la cual no se ven sus xml
3. Cobrarles 5k para resolverlo
