### ISSUE TITLE
PDF - Complemento de pago CFDI 4.0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2132]
Dejó de enviar un chingo de variables al jasper... identificadas al momento:
Llegan vacías = ""

totalTrasladosBaseIVA16
totalTrasladosBaseIVA8
totalTrasladosBaseIVA0
totalTrasladosBaseIVAExento
totalTrasladosImpuestoIVA16
totalRetencionesISR
totalRetencionesIVA

montoTotalPagos

traImporteP1
traImporteP2

a nivel documento relacionado:

traTasaOCuotaDR para el IVA es incorrecta. Envía 0.
traImporteDR para el IVA es incorrecto, envía 0

**Comment by jccastillo0007** [comment]
web o standalone?

**Comment by RigoFlores** [comment]
En Web

**Comment by jccastillo0007** [comment]
listo, se movió todo por la forma de calcular los totales... después de varios cambios que se hicieron para hacer que cuadre... o forzar a que cuadre jajaja

**Comment by RigoFlores** [comment]
lo veo igual, es decir, no veo la corrección al problema. Mira este es el PDF que acabo de generar. Es una factura simple, de 1000 mas IVA


[PAGO97_IIA040805DZ4_TIA101020BP4_29Mar2023_073049.pdf.txt](https://github.com/jccastillo0007/eFacturaT/files/11101991/PAGO97_IIA040805DZ4_TIA101020BP4_29Mar2023_073049.pdf.txt)

**Comment by RigoFlores** [comment]
???

**Comment by RigoFlores** [comment]
Esto ya está haciendo crisis.
El PDF que genera el sistema, no muestra todo lo que tiene que mostrar.

Dos meses desde que se levantó el ticket

**Comment by jccastillo0007** [comment]
listo, puedes probar en pru

**Comment by jccastillo0007** [comment]
totalRetencionesIVA=50.00,totalRetencionesISR=12.50,totalRetencionesIEPS=,totalTrasladosBaseIVA16=1000.00,totalTrasladosImpuestoIVA16=160.00,totalTrasladosBaseIVA8=,totalTrasladosImpuestoIVA8=,totalTrasladosBaseIVA0=,totalTrasladosImpuestoIVA0=,totalTrasladosBaseIVAExento=,montoTotalPagos=1362.50,retImporteP001=12.50,retImporteP002=50.00,retImporteP003=,traBaseP1=1000.00,traImporteP1=160.00,traImpuestoP1=002,traTasaOCuotaP1=0.16,traTipoFactorP1=TASA,traBaseP2=1000.00,traImporteP2=0.00,traImpuestoP2=003,traTasaOCuotaP2=0.00,traTipoFactorP2=TASA

**Comment by jccastillo0007** [comment]
retBaseDR=1000.00,retImporteDR=12.50,retImpuestoDR=001,retTasaOCuotaDR=0.01,retTipoFactorDR=TASA,retBaseDR2=1000.00,retImporteDR2=50.00,retImpuestoDR2=002,retTasaOCuotaDR2=0.05,retTipoFactorDR2=TASA,traBaseDR=1000.00,traImporteDR=0.00,traImpuestoDR=003,traTasaOCuotaDR=0.00,traTipoFactorDR=TASA

**Comment by RigoFlores** [comment]
cerca la bala, justo en lo que pegaste arriba, se nota que a nivel documento relacionado, no está enviando el importe del impuesto, mas bien, lo manda en 0.00. La tasa también la envia en 0.00. Son los 2 datos a nivel DR que están mal todavía.

Checa el PDF.

[PAGO116_IIA040805DZ4_TIA101020BP4_27May2023_191326.pdf.txt](https://github.com/jccastillo0007/eFacturaT/files/11583599/PAGO116_IIA040805DZ4_TIA101020BP4_27May2023_191326.pdf.txt)

**Comment by RigoFlores** [comment]
Hoy surgió este problema, el PDF es incorrecto a nivel de DR, el importe no lo está enviando.
