### ISSUE TITLE
Optibelt - Conector con CCE en EUR, no calcula correctamente el ValorDolares

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2133]
En general está trabajando correctamente, pero este archivo en particular no lo procesa bien.

[MXRE231122373.TXT](https://github.com/jccastillo0007/eFacturaT/files/11035248/MXRE231122373.TXT)

Le veo 2 detalles:

1) En esta mercancía está calculando mal el total, y por consecuencia el valor unitario:

cce11:Mercancia CantidadAduana="29.94" FraccionArancelaria="4010399901" NoIdentificacion="4014486351927-1" UnidadAduana="01" **ValorDolares="73.87"** ValorUnitarioAduana="2.47"/
 
el ValorDolares = Importe*FCM = 62.08 *( 22.5 / 18.9095 ) = 62.08 * 1.18987810359872 = 74.7243449059996.
redondeado, debía ser 74.72. Si te das cuenta lo está reportando como 73.87. De ahí, el valor unitario aduana, pues lo calcula incorrectamente.
Hay que revisar porqué lo calculo incorrectamente. 
En el producto 2, si hizo bien todos los cálculos.

Así lo generó:

[CCEOPTIBELT.XML.txt](https://github.com/jccastillo0007/eFacturaT/files/11035271/CCEOPTIBELT.XML.txt)

**Comment by jccastillo0007** [comment]
duplicado con 2134

**Comment by RigoFlores** [comment]
no, no está duplicado, es problema distinto.
Esperaré a que el 2134 esté resuelto para retomar este otro issue.
Si ya quedó, pues está OK.
Si no, lo reabrimos
