### ISSUE TITLE
Optibelt - CCE en EUR, en algunos casos valorUnitarioAduana * cantidad es mayor que valorDolares.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2134]
Dadas las conversiones que tenemos que hacer, y debido a que se manejan solo 2 decimales a nivel del nodo de complemento exterior, se están perdiendo algunas cifras que llegan a provocar errores.
Este archivo, no lo timbra precisamente por esos errores:

[MXRE231122373.TXT](https://github.com/jccastillo0007/eFacturaT/files/11035277/MXRE231122373.TXT)

Cuando se calcula el valorunitarioaduana, (valorDolares/cantidad), este resultado se redondea. 
Eso provoca que la validación que entiendo aplica el SAT, de cantidad * precio unitario, pueda llegar a ser mas alto que el ValorDolares. 
¿Porqué? pues si se redondea hacia arriba, en automático, será mas alto ese resultado y el SAT no permite que pase.

Entonces, el primer enfoque que trabajaremos para ver si solventamos este escenario, es que el cálculo del valorunitarioaduana NO SE REDONDEE, SINO QUE EN SU LUGAR SE TRUNQUE.
Yo creo que con ello puede resolverse el problema.

En caso que no, se haría una operación adicional, pero esperemos a ver cómo se comporta así con este approach.

**Comment by RigoFlores** [comment]
OK, ya truncándose valorunitarioaduana, el resultado de  ( cantidad * valorUnitarioAduana ), siempre es menor que ValorDolares, pero aún así no está funcionando del todo. Todo esto es una mamada, pero bueno.

Falta hacer un último paso. Volver a calcular la cantidad pero ahora a 3 decimales.

Una vez que ya tenemos ValorDolares y ValorUnitarioAduana, es decir, así como estamos ahora mismo ya. Hasta ahí todo bien.

Se requiere una operación adicional, recalcular cantidad:

cantidadAduana = ( ValorDolares / ValorUnitarioAduana ), truncado a 3 decimales... es decir se recalcula a 3 decimales, para darle mayor resolución al margen que otorga el SAT. Ya hice prueba con uno y si jaló.

Probaré con 2 ejemplos mas para asegurar que este approach si jalará bien.

**Comment by RigoFlores** [comment]
Si, validé otros 2 ejemplos, y si jala así...
Entonces hay que proceder y ver que pasa con los archivos que contienen decenas de conceptos y mercancías. Ahí quizá podría haber problemas, pero hoy no lo sabemos.

**Lo solicitado, es que además de lo que se tiene hoy, se recalcule para cada mercancía, truncado a 3 decimales, la cantidad a partir de:**

**_cantidadAduana = ( ValorDolares / ValorUnitarioAduana )_**

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Negativo, la cantidad reportada es la misma que aparece en el archivo.
Lo que debemos considerar cuando recalculamos, es que  ValorDolares debe ir en 2 decimales dividido por  valorUnitarioAduana igual en 2 decimales (a eso me refería a "con lo que ahora tenemos"). Pero si estamos recalculando con tooodos los decimales, pues entonces quizá por ello el resultado es el mismo.

Quizás se está haciendo la operación, pero sin haber truncado o redondeado antes... y pues así, no se verá reflejado el cambio... el punto es que cuando truncas o redondeas, la cantidad se debe recalcular. Solo así se verá un parámetro "cantidadAduana" distinto.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Esto se llama ingeniería de software y no damamas... jejeje
