### ISSUE TITLE
En producción web, dupliqué por error del cliente este RFC GCI900710E94

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2136]
Puedes eliminar uno de los dos registros, en las tablas correspondientes?

**Comment by jccastillo0007** [comment]
no sé si tu lo borraste, o realmente no lo duplicaste, pero solo había un registro de ese cliente, chiaaaaa

**Comment by RigoFlores** [comment]
No maaaaa... me equivoqué, no era ese... sino este...GCI900710E94
Ud disculpe.

**Comment by jccastillo0007** [comment]
fixed
