### ISSUE TITLE
Conector las Barricas - documento de pago con una sola factura no jala

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2137]
Con 2 facturas involucradas en el pago si timbra.
Con 1 sola, aparentemente está buscando el esquema anterior y no jala...
Aquí los archivos, uno con 2 facturas y el otro con 1 factura únicamente.

[PAGO_032041NEW.txt](https://github.com/jccastillo0007/eFacturaT/files/11105644/PAGO_032041NEW.txt)
[PAGO_032041y32072_NEW.txt](https://github.com/jccastillo0007/eFacturaT/files/11105643/PAGO_032041y32072_NEW.txt)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Pues no quedó. 
Aparentemente si lo timbra, es decir, si lo pusiéramos en producción si lo registraría en el SAT, pero en la aplicación truena.
Lo comento porque se alcanza a ver el mensaje de "proceso exitoso", pero el error posterior, provoca que no se genere el XML y mucho menos el PDF. 
Probé con los 2 archivos que subí a este ticket, y con los 2 marcó lo mismo.


<img width="796" alt="pagoOptibelt" src="https://user-images.githubusercontent.com/2912775/228866504-4859fdf2-a562-4993-86dc-d8d92b963922.PNG">

**Comment by RigoFlores** [comment]
Ya revisé bien. Si está timbrando. En el catalina, se nota que si timbró, pero no se refleja en el conector... es decir no se generan los archivos XML ni PDF, y envía el error arriba mostrado en la consola.
Esta es la pantalla del catalina:

<img width="949" alt="pagoBarricas" src="https://user-images.githubusercontent.com/2912775/228890373-5e2777ca-46f9-4c3b-80b2-dce19960bfb2.PNG">

**Comment by jccastillo0007** [comment]
fixed
