### ISSUE TITLE
Conector Estándar, no está enviando los valores de clf1 al clf3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2138]
Es un caso particular.
Se trata del complemento de leyendas fiscales. El complemento SI lo incluye en el XML. Ahí no hay pex.
Pero no envía las variables al jasper. Aparecen así en el factura.log:

clf1=<null>,clf2=<null>,clf3=<null>,

Anexo el archivo de texto plano así como la llave con la que se prueba.

[facturaT_IIA040805DZ4.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/11116929/facturaT_IIA040805DZ4.cfdi.txt)

[CFD_B_13464.txt](https://github.com/jccastillo0007/eFacturaT/files/11116930/CFD_B_13464.txt)

**Comment by jccastillo0007** [comment]
fixed.
