### ISSUE TITLE
Escritorio en Windows 10 Pro, se adelanta una hora y marca error al intentar timbrar por fuera de horario

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2139]
Está sumamente raro.
Lo que es un hecho, que tiene que ver con el cambio de horario del sábado, que bueno en México no se hizo, pero que en otros lados si.
El punto es que el reloj de la compu, marcaba una cierta hora y el reloj de la pantalla de facturación, marcaba una hora adelante.
Esto lo vi en 4 casos hoy.

No se si tenga que ver en cómo estamos obteniendo la hora o que pasa.
De hecho, desde que inicia en la consola, el timestamp de la bitácora, ya está adelantado una hora también... desde ahí se ve que no jalará...

Qué crees que pueda ser?

**Comment by RigoFlores** [comment]
por lo pronto, cambiando el timezone, creo que podremos librarla

**Comment by jccastillo0007** [comment]
Este defecto es para Microsoft
