### ISSUE TITLE
ERP ADDENDADOR - MARCA ERROR AL GENERAR CFD (115) CON EL USUARIO VAAT2203316P2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#214]
TOMÉ EL ÚLTIMO XML QUE 'ADDENDÓ' CORRECTAMENTE, PERO AHORA MARCA ESTE ERROR 115.

**Comment by RigoFlores** [comment]
TAMBIÉN CON ESTE OTRO USUARIO PROBÉ. AEPJ801112PZ1
PARECE QUE ES EL ADDENDADOR PARA MABE

**Comment by jccastillo0007** [comment]
Fixed.
