### ISSUE TITLE
Optibelt, el importe a nivel concepto - nodo impuestos, lo reporta a 6 decimales y no lo acepta el SAT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2140]
Hice una prueba con 72 archivos de producción de ellos, y solo procesó bien 4 archivos.
Tenemos que corregir esa parte que tengo meses pidiendo.
El importe a nivel nodo de concepto - impuestos, manejarlo a 2 decimales... 

Aquí te dejo algunos de los de archivos que fallaron para optibelt

[ERROR_MXRE231122940.TXT](https://github.com/jccastillo0007/eFacturaT/files/11153878/ERROR_MXRE231122940.TXT)
[ERROR_MXRE231122939.TXT](https://github.com/jccastillo0007/eFacturaT/files/11153879/ERROR_MXRE231122939.TXT)
[ERROR_MXRE231122938.TXT](https://github.com/jccastillo0007/eFacturaT/files/11153880/ERROR_MXRE231122938.TXT)
[ERROR_MXRE231122937.TXT](https://github.com/jccastillo0007/eFacturaT/files/11153881/ERROR_MXRE231122937.TXT)
[ERROR_MXRE231122936.TXT](https://github.com/jccastillo0007/eFacturaT/files/11153882/ERROR_MXRE231122936.TXT)
[ERROR_MXRE231122935.TXT](https://github.com/jccastillo0007/eFacturaT/files/11153883/ERROR_MXRE231122935.TXT)
[ERROR_MXRE231122943.TXT](https://github.com/jccastillo0007/eFacturaT/files/11153884/ERROR_MXRE231122943.TXT)
[ERROR_MXRE231122942.TXT](https://github.com/jccastillo0007/eFacturaT/files/11153885/ERROR_MXRE231122942.TXT)
[ERROR_MXRE231122941.TXT](https://github.com/jccastillo0007/eFacturaT/files/11153886/ERROR_MXRE231122941.TXT)

**Comment by RigoFlores** [comment]
está repetido con este ticket que no se ha atendido, pero hoy hizo crisis...

Conector de Optibelt - el tema de los decimales en la base y el importe de los impuestos. Genera errores #2113

**Comment by jccastillo0007** [comment]
fixed.
Aplica para todos no solo optibelt.

Por cierto, al arranque de facturat, agregué un mensaje para identificar el timezone seleccionado.

Busca algo como:

Current TimeZone :
