### ISSUE TITLE
No está funcionando el addendador MABE para la versión 4.0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2141]
Anexo un archivo que contenía la addenda mabe y se la quité para validar en producción.
Y si, vi que marca el error 115 con el addendador de mabe.
Lo reportó un cliente de addendador.

puedes revisarlo pls?

[AddendaMABE.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/11182825/AddendaMABE.xml.txt)

**Comment by jccastillo0007** [comment]
checale en pru
