### ISSUE TITLE
WEB -La sumatoria de los importes de impuestos retenidos, llega a ser incorrecta y marca errores.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2142]
Como ya se comentó, ahora mismo estamos ya reportando los importes de impuestos trasladados y retenidos a 2 decimales.

Entonces la petición es que la sumatoria de los importes reportados a nivel del nodo general de impuestos, sea la suma aritmética de los importes a nivel concepto, reportados a 2 decimales.

**Comment by RigoFlores** [comment]
hoy se presentó un caso también con los impuestos trasladados.

**Comment by RigoFlores** [comment]
Lo que se requiere, es lo que ya hemos comentado.

Que en el nodo de Impuestos a nivel general, los importes de los impuestos trasladados y retenidos, sean precisamente la suma de los importes **REPORTADOS EN EL XML A NIVEL CONCEPTO**, donde se reportan a 2 decimales.

Ahora mismo, esa suma no se hace con lo reportado a nivel XML, sino el resultado de las operaciones a 4 decimales, y eso es lo que llega a variar.

**Comment by jccastillo0007** [comment]
checale en pru

**Comment by RigoFlores** [comment]
ok, si ya jaló
para subirlo a pro, debemos atender lo de factoraje, porque ahorita se hizo un desmadre

**Comment by RigoFlores** [comment]
Se resolvieron la mayoría, pero tenemos este caso... la primera columna, corresponde al importe de cada producto. Las otras 2 columnas son informativas de cómo se reporta el IVA y el ISR de cada producto.
Al final se incluye la suma de todo, y en el XML que se intenta timbrar no coincide la suma de retenciones.

Todos los productos llevan IVA trasladado del 16% e ISR RETENIDO de 1.25%.

	20710	3313.6	258.88							
	11699.25	1871.88	146.24							
	10212.5	1634	127.66							
	15675	2508	195.94							
	7077.5	1132.4	88.47							
	16606	2656.96	207.58							
	7410	1185.6	92.63							
	13727.5	2196.4	171.59							
	10307.5	1649.2	128.84							
	13727.5	2196.4	171.59							
	2417.75	386.84	30.22							
	13775	2204	172.19							

										
	143345.5	22935.28	1791.83

**Comment by jccastillo0007** [comment]
hice ya el refactor para generar los totales de impuestos, a partir  de los impuestos de los conceptos del xml...

Este cambio aplica tanto para web como standalone... generé una versión standalone de PRUEBAS unicamente, para que me ayudes a probar si esta todo bien..

**Comment by RigoFlores** [comment]
Al parecer las sumatorias están ya bien, pero en el resumen de impuestos trasladados, le está metiendo el ISR.
Este ejemplo, lleva en todos los productos IVA del 16%  y retención ISR 1.25%.
El nodo resumen de retenciones, se reporta correctamente.
El nodo resumen de traslados, le está incluyendo el ISR, además chueco.

Aquí te dejo el XML que generó, y con el comentario donde está la línea sobrante. El cliente tiene mas de una semana esperando la solución de este punto.

[CFDI traslados y retenciones con error Pru.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/11274539/CFDI.traslados.y.retenciones.con.error.Pru.xml.txt)

**Comment by jccastillo0007** [comment]
fixed
