### ISSUE TITLE
Documento de pago - pago parcial en MXN, se reporta una baseDR incorrecta, y por ende un importeDR igual incorrecto.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2143]
Un cliente detectó unas diferencias con respecto al cálculo de la base y del importe del IVA, en un pago parcial.
Te envié correo.

Por favor responde, para saber que procede.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ES-MX style='tab-interval:35.4pt;word-wrap:break-word'>

<p class=MsoNormal><span style='font-size:14.0pt;color:black'>Monto pagado: </span><span
style='font-size:14.0pt;font-family:"Helvetica",sans-serif'>372,047.79<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:14.0pt;color:black'>SI CALCULAMOS LA
BASE Y EL IVA, NOS DARÍA LO SIGUIENTE:<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:14.0pt;color:black'><o:p>&nbsp;</o:p></span></p>

IMPORTE PAGADO | BASE | IVA
-- | -- | --
$     372,047.79 | $   320,730.85 | $   51,316.94

<p class=MsoNormal><span style='font-size:14.0pt;color:black'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:14.0pt;color:black'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:14.0pt;color:black'>EN EL XML DE
PAGO, SE REPORTÓ LO SIGUIENTE, ES DECIR EXISTE UNA PEQUEÑA VARIACIÓN, QUE PARA
VARIAR UNOS CLIENTES YA LA HICIERON DE A PEDO.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:14.0pt;color:black'>RECUÉRDAME CÓMO
SE OBTIENE LA BASE Y EL IVA EN ESTE CASO.<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='color:black'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:Pagos Version=&quot;2.0&quot;&gt;<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:Totales <span style='background:yellow;mso-highlight:yellow'>MontoTotalPagos=&quot;372047.79&quot;
TotalTrasladosBaseIVA16=&quot;320729.78&quot;
TotalTrasladosImpuestoIVA16=&quot;51316.76</span>&quot;/&gt;<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:Pago FechaPago=&quot;2023-04-10T12:00:00&quot;
FormaDePagoP=&quot;03&quot; MonedaP=&quot;MXN&quot; Monto=&quot;372047.79&quot;
NumOperacion=&quot;100423&quot; TipoCambioP=&quot;1&quot;&gt;<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:DoctoRelacionado EquivalenciaDR=&quot;1&quot; Folio=&quot;1069&quot;
IdDocumento=&quot;0ad3420a-421c-4b8d-8424-37ae91ecb035&quot;
ImpPagado=&quot;372047.79&quot; ImpSaldoAnt=&quot;1240159.31&quot;
ImpSaldoInsoluto=&quot;868111.52&quot; MonedaDR=&quot;MXN&quot;
NumParcialidad=&quot;1&quot; ObjetoImpDR=&quot;02&quot;&gt;<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:ImpuestosDR&gt;<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:TrasladosDR&gt;<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:TrasladoDR <span style='background:yellow;mso-highlight:yellow'>BaseDR=&quot;320729.78&quot;
ImporteDR=&quot;51316.76&quot;</span> ImpuestoDR=&quot;002&quot;
TasaOCuotaDR=&quot;0.160000&quot; TipoFactorDR=&quot;Tasa&quot;/&gt;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/pago20:TrasladosDR&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;/pago20:ImpuestosDR&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;/pago20:DoctoRelacionado&gt;<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:ImpuestosP&gt;<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:TrasladosP&gt;<o:p></o:p></span></p>

<p class=MsoNormal><span style='color:black'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;pago20:TrasladoP <span style='background:yellow;mso-highlight:yellow'>BaseP=&quot;320729.78&quot;
ImporteP=&quot;51316.76&quot;</span> ImpuestoP=&quot;002&quot;
TasaOCuotaP=&quot;0.160000&quot;
TipoFactorP=&quot;Tasa&quot;/&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;/pago20:TrasladosP&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;/pago20:ImpuestosP&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;/pago20:Pago&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;/pago20:Pagos&gt;<o:p></o:p></span></p>

</body>

</html>

**Comment by RigoFlores** [comment]
Subí la factura de producción a pruebas. Solo le cambias datos del emisor y ya para que acepte. Ves que ya no valida en el sat que si exista.

OK, entonces, al intentar generar un pago parcial a esa factura: rfc emisor: IIA, receptor 372047.79, factura 1069. Pago parcial por 372047.79.
La aplicación marcó error no clasificado, y eso está cabrón porque se sale de los escenarios que finkok valida, jajaja.
Bueno, pero ya comparé el XML que intentó timbrar y lo que pasó es que no incluyó el nodo de impuestosP, dentro del documento de pago que intentó timbrar.

veré si no es un error producido por haber cargado el cfdi externo.
es decir voy a generar ahora la factura en ambiente nativo de pru

**Comment by RigoFlores** [comment]
Generando la factura desde la plataforma si procesa el pago, es decir si genera el XML. emisor IIA, Receptor la tia, factura 542.
OK, ahora el punto es el origen de este issue...
¿En un pago parcial, cómo se calcula la base?

porque los números que arrojó, son casi los mismos de producción actualmente.

Si el pago parcial fue de 372047.79, entonces calculando la base, es ese número / 1.16 = **320730.85, y el IVA sería 51316.94**

lo que arroja la aplicación es: base = **320729.79; IVA = 51316.77**

la base tiene una variación de casi 1 peso, y el IVA pues el proporcional al 16%.
Y el cliente es lo que pregunta, porque no le aceptan el pago en el gobierno.

**Comment by jccastillo0007** [comment]
1. se calcula el porcentaje de pago = total del pago / total de la factura
2. se redondea el porcentaje de pago a seis decimales
3. se multiplica el total de la base acumulada de cada impuestos por el porcentaje de pago

**Comment by RigoFlores** [comment]
OK, el procedimiento descrito es como se solicitó inicialente, pero los cálculos no cuadran... mira punto por punto:

1. % pagado = total / pago parcial = 1240159.31 / 372047.79 = 0.3
2. 0.3
3. base acumulada (en este caso hay un solo concepto con únicamente IVA del 16% en la factura): 1069102.85 * 0.3 = 320730.85

entonces, nosotros estamos reportando esa base inicial como base = 320729.79; IVA = 51316.77
Ahí es donde está la diferencia, y entonces hay que buscar porqué de esa diferencia de poco mas de un peso.

Yo insisto desde siempre. Si la base reportada en los XML y sus importes de impuestos clasificados (básicamente el nodo impuestos de cada XML), se almacena en una tabla de bases y de impuestos, creo que mucho de estas cuestiones se resolvería.
Yo se que ese nodo de impuestos se calcula cuando se timbra la factura, claro. Pero no estamos llegando a los mismos números por este otro camino. Según yo tooodo es tema de redondeos.

Pero bueno, tu me dirás porqué es diferente.

Para reproducir en pruebas con el emisor IIA, esta factura es la 542 con fecha del 17 de abril. El pago parcial inicial es 372047.79.

**Comment by RigoFlores** [comment]
Volví a capturar el pago parcial y tiene las mismas diferencias. Ya borré el pago parcial de esa factura.
Para reproducirlo es con el emisor IIA, receptor la tia, factura 542, pago parcial 372047.79

El problema es la diferencia en el cálculo de la baseDR y por ende del importeDR del IVA pagado.

**Comment by RigoFlores** [comment]
Tsss, acaba de hablar el cliente de este issue...

**Comment by RigoFlores** [comment]
En la mañana te comentaba de este issue.
En un pago parcial. Se puede reproducir en pru. Emisor IIA, receptor la tia, factura 542, pago parcial:  372047.79

ya tenemos semanas con este punto, se ha explicado, pero no se porqué estamos calculando la base chueca. Varía por un peso aprox, y con eso el cliente no le aceptan su complemento de pago.

**Comment by jccastillo0007** [comment]
Así es como se obtiene ese resultado.

1. % pagado = total / pago parcial = 1240159.31 / 372047.79 = 0.2999999985485735
2. redondeado a 6 decimales = 0.299999
3. base acumulada 1069102.85
4. base por porcentaje de pago : 1069102.85 * 0.299999 = 320729.785897
5. redondeado = 320729.78
5 iva = 320729.78 * 0.16 = 51316.76

dónde le muevo ?

**Comment by jccastillo0007** [comment]
quieres que redondee el porcentaje de pago ? a cuantos decimales ? y ya sabes que todo se puede descomponer por ajustar eso...

**Comment by RigoFlores** [comment]
Ya vi donde está la diferencia.

Para que den los mismos números, el % pagado no debería truncarse o redondearse.
Ese número  ( 0.2999999985485735 ), no se va a ningún lado o sí?
Se obtiene para hacer cálculos, pero ese dato propiamente, no va al XML. De hecho el puto excel, lo pone justo como 0.3

La diferencia de los cálculos que pusiste arriba con respecto a lo que el cliente plantea, es precisamente que si ocupamos el resultado del % pagado, completo, sin redondear, ni nada  (0.2999999985485735)... entonces ahí la base acumulada si resulta en lo que dice el cliente.

Cómo ves?

Donde le movemos? pues solo ocupar ese % pagado completo, ya que no se va al XML, solo es un número intermedio.

**Comment by jccastillo0007** [comment]
si puedo hacer eso... peeeero por algo lo estamos truncando... lo hago y lo subo para que pruebes vale

**Comment by RigoFlores** [comment]
Yo creo que lo truncábamos porque 6 decimales es suficiente para el 99.9% de casos.

Pero para facturas con importe con 7 dígitos enteros (arriba de un mega), ya te imaginarás que esos 6 decimales pues si afectan... 
Ponlo a pru y lo reviso, casi seguro que ya quedaría, pero veamos.
Ese % de pago, únicamente se ocupa para calcular la base... para nada más... o tu dime si lo ocupas en algo más..

**Comment by RigoFlores** [comment]
quedó todo bien, excepto que el importeDR, lo truncamos y otros lo redondean... jajaja
buscaré si hay regla al respecto, pero por lo pronto se ve bien.
probé con otros escenarios y bien
