### ISSUE TITLE
CONECTOR DE PRUEBA - No está calculando bien la base de impuestos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2146]
Probé con la llave de optibelt, inicialmente...
y ahí no está generando correctamente la base. 
La sumatoria de traslados, la hizo impecable, pero la base, se alocó gacho.

[ERROR_MXRE231122942.TXT](https://github.com/jccastillo0007/eFacturaT/files/11240524/ERROR_MXRE231122942.TXT)
[ERROR_MXRE231122944.TXT](https://github.com/jccastillo0007/eFacturaT/files/11240525/ERROR_MXRE231122944.TXT)
[ERROR_MXRE231122943.TXT](https://github.com/jccastillo0007/eFacturaT/files/11240526/ERROR_MXRE231122943.TXT)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
pues no, no veo una nueva versión...

**Comment by jccastillo0007** [comment]
shit.... no la subí, pero supongo que apenas la ibas a probar, si no, me hubieras dicho desde hace rato 

ahorita la subo
