### ISSUE TITLE
Documento de pago en MXN para facturas en USD, no trabaja en pru

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2147]
Marca error en los importes, y simplemente no lo timbra en pru.

Emisor IVD
Receptor la tia
Monto del pago en MXN: 309294.82
facturas en USD pagadas EN SU TOTALIDAD: 300,301, 302 Y 303.

**Comment by jccastillo0007** [comment]
oye, pues hay que revisar que cálculo esta mal... ya genera el xml... pero si marca error en el total : 

El campo Total no corresponde con la suma del subtotal, menos los descuentos aplicables, más las contribuciones recibidas (impuestos trasladados - federales o locales, derechos, productos, aprovechamientos, aportaciones de seguridad social, contribuciones de mejoras) menos los impuestos retenidos y/o locales.


Pero pues como es un pago en pesos, de facturas en USD, no recuerdo que tantos cálculos se deben hacer, tienes tu famoso excel con las cifras que son correctas ?

**Comment by RigoFlores** [comment]
el error está en el total del cfdi estándar. Lreporta como 0.00, y solo debe ir 0
Incorrecto:
 SubTotal="0" Moneda="XXX" **Total="0.00"** 

Correcto:
 SubTotal="0" Moneda="XXX" **Total="0**"

**Comment by jccastillo0007** [comment]
ya corregí lo del total=0
 
pero marca error en la base 

CRP20268 : El campo BaseP que corresponde a Traslado, no es igual a la suma de los importes de las bases registrados en los documentos relacionados donde el impuesto del documento relacionado sea igual al campo ImpuestoP de este elemento y la TasaOCuotaDR del documento relacionado sea igual al campo TasaOCuotaP de este elemento. (3)

**Comment by jccastillo0007** [comment]
[temp.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/11268151/temp.xml.txt)

Subo el xml generado, por si sirve de algo

**Comment by RigoFlores** [comment]
tengo otro ejemplo:

Emisor IVD
Receptor la tia
Monto del pago en MXN: 140703.03
facturas en USD pagadas EN SU TOTALIDAD: 306, 307 y 308

Equivale a documento de pago de producción PAGO215_CAPC580324HD1_MME921204HZ4_11Apr2023_160618.xml

el primer ejemplo, es la réplica del PAGO212_CAPC580324HD1_MME921204HZ4_11Apr2023_150159.xml

para que no se me olvide cuando tenga que comparar resultados... esos están timbrados en pro.

**Comment by RigoFlores** [comment]
Estoy revisando con Finkok este punto, porque pues o se redondea o se trunca, pero no se puede hacer ambos, jajajaja

**Comment by RigoFlores** [comment]
Pues finkok dice que la sumatoria de BaseP y la sumatoria de ImporteP, en el nodo ImpuestosP del documento de pago, deben ser truncados.

Red cofidi lo rendondeo hacia arriba.

Honestamente, esa regla no existe en ningún lado, pero bueno, el cálculo se tiene que hacer de una u otra manera, es decir, o se redondea o se trunca.

En este caso, si nos apegamos a Finkok, tendremos que truncar esas sumatorias.

**Comment by RigoFlores** [comment]
La otra es que el BaseP y el ImporteP, son del tipo t_Importe, entonces aceptan mas decimales, pero pues no se si abrir esa caja que luego nos puede traer otros problemas.

**Comment by jccastillo0007** [comment]
se supone que acabamos de bajar los decimales a 2....
no ma....

pero el punto es que si se puede timbrar pero el cliente no lo acepta, o realmente no se puede timbrar por esa diferencia?

**Comment by RigoFlores** [comment]
ambas 2...

En producción si timbra por facturehoy, pero pinche red cofidi no lo acepta. Pide redondear arriba de 0.05
En pru, no timbra con finkok, que porque estamos redondeando y ellos piden que se trunque... jajaja

Creo que hay que hacer que timbre en pru, con el refactor...

**Comment by jccastillo0007** [comment]
truncando solo el resultado de la suma de importes y bases , no funciono

habrá que truncar todas las bases e importes a nivel impuestosP ?

**Comment by jccastillo0007** [comment]
lo que ha hecho falta para poder aclarar el issue, es que me entregues un excel con los cálculos que deberían suceder vs los cálculos de la app, para ver donde esta la diferencia

**Comment by RigoFlores** [comment]
ya no me ha dicho nada la clienta.
o ya se fue, o lo hizo en el sat o no se que pex.

deja preguntarle
