### ISSUE TITLE
CFDI con CCE en WEB - Convertir piezas a KG

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2148]
Ahora mismo en web, cuando se genera un CFDI con CCE tomamos los siguientes datos de cada concepto: 

NoIdentificación, cantidad, precio unitario, importe 

y lo llevamos a la sección del complemento:

NoIdentificación, cantidadAduana, ValorUnitarioAduana, ValorDolares

a nivel de cada producto contenido en la factura, en la pantalla de addenda, se captura la fracción arancelaria y la unidad de medida.

OK, necesitamos agregar en la pantalla de captura de la addenda un campo, que indique "Convertir Piezas a Kgs". Su valor sería SI o NO. Es decir, agregaríamos un campo en el XML de la addenda.

Cuando el valor sea SI, entonces la unidadAduana, será siempre 01 para el CCE, que corresponde a KG.
En lugar de que capturen la unidad en la pantalla de addenda, en su lugar capturarán el peso en Kgs de todas las piezas incluidas en cada concepto. 
Es decir, capturarán fracción arancelaria y peso (de todas las piezas de cada concepto). Este será el dato de cantidadAduana inicial.

Con ello, podremos calcular:
ValorUnitarioAduana= ValorDolares / cantidadAduana.
Y luego recalcularemos redondeado a 3 decimales cantidadAduana: ValorDolares / ValorUnitarioAduana

Con ello ya tendremos cantidadAduana y ValorUnitarioAduana convertido de pz a kg.
ValorDolares no se modifica. Ese es el mismo.
NoIdentificacion no se modifica.
FraccionArancelaria se captura.

Queda el nodo de mercancía (por ejemplo así):

<cce11:Mercancia CantidadAduana="1.0" FraccionArancelaria="9031809901" NoIdentificacion="01" UnidadAduana="01" ValorDolares="5.28" ValorUnitarioAduana="5.28"/>

**Comment by RigoFlores** [comment]
[CCE_Addenda20.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/11277951/CCE_Addenda20.xml.txt)

Así quedaría el nuevo XML de configuración, con un dato más.
Se ese campo Convertir Pz a Kg es NO, todo funciona como ahora mismo.
Si es si, entonces se aplica la conversión.

**Comment by RigoFlores** [comment]
este punto también creo que puede ser importante para los clietnes, sobre todo optibelt.

**Comment by jccastillo0007** [comment]
Yo creo que esto no es buena idea... será confuso y se nos va a olvidar:
"En lugar de que capturen la unidad en la pantalla de addenda, en su lugar capturarán el peso en Kgs de todas las piezas incluidas en cada concepto."

sería mejor agregar otro campo

**Comment by jccastillo0007** [comment]
Aqui tampoco le entiendo:
"Es decir, capturarán fracción arancelaria y peso (de todas las piezas de cada concepto). Este será el dato de cantidadAduana inicial."

Cual es la cantidadAduana? es el peso ?

**Comment by RigoFlores** [comment]
> Yo creo que esto no es buena idea... será confuso y se nos va a olvidar: "En lugar de que capturen la unidad en la pantalla de addenda, en su lugar capturarán el peso en Kgs de todas las piezas incluidas en cada concepto."
> 
> sería mejor agregar otro campo

OK, entonces ahora habría que agregar automáticamente a la pantalla de captura, 3 campos en lugar de 2 (que ahora mismo se agregarn), por cada concepto capturado en CFDI estándar.
Fracción Arancelaria  (ya se tiene)
Unidad  (ya se tiene)
CantidadAduana (sería el nuevo. Por omisión la misma cantidad que aparece en el nodo concepto del CFDI. Esta omisión es para hacer lo mismo que hoy ya se hace, que es trasladar ese dato del CFDI al complemento).

Yo sugería que se tomara el mismo para no agregar más. Pero si podría ser confuso para el usuario y a nosotros mismos.

**Comment by RigoFlores** [comment]
> Aqui tampoco le entiendo: "Es decir, capturarán fracción arancelaria y peso (de todas las piezas de cada concepto). Este será el dato de cantidadAduana inicial."
> 
> Cual es la cantidadAduana? es el peso ?

Esto ya lo hicimos en optibelt. Debe quedar claro cuál es la intención.
En el CFDI estándar ser reporta como unidad pieza, la cantidad, el precio unitario y el importe.
Nosotros eso nos lo llevamos tal cual al complemento.

Lo que se pide aquí es convertir pieza a KG (unidadAduana es decir, la clave pasa de 06 a 01), cantidad de piezas  a cantidad de kgs (eso lo capturarán, será el nuevo campo). Teniendo la cantidad y el importe total, se hacen recálculos del precio unitario, mismo que se va a 6 decimales. Y posteriormente, si es necesario recalcular el valorDolares a 4 decimales.

yo creo que con tener el valorUnitario a 6 decimales, ya no será necesario manejar 4 en el valorDolares

**Comment by jccastillo0007** [comment]
hoy en día el valor unitario aduana y el valor dólares se está enviando a 2 decimales... lo quieres cambiar ?

**Comment by jccastillo0007** [comment]
Listo, ya subí una versión a pruebas... puedes probar ?
Si no funciona, que es lo más seguro... puedes extraer el xml y definir que cálculos son incorrectos y cómo deberían ser...

Estas pidiendo redondeos diferentes a los que se tenían... así que eso puede disparar muchas fallas

**Comment by RigoFlores** [comment]
Si, llegando a la ofis lo pruebo.
Justo ese cambio es uno de los que se solicitan en la versión 2.0 del CCE.
En su momento, nosotros lo resolvimos para optibelt con "el recálculo" de ValorDolares. Somos unas verdaderas reatas paradas. 

Ahora, seguro esa misma situación se presentó en facturas emitidas en MXN, donde 2 decimales no eran suficientes para una conversión simple. Tons la salida simple, fue subir la resolución de los importes... (seguimos siendo unas reatas paradas!!!!).

Según yo por esa razón, ahora ya abrieron la resolución de valorunitario a 6 decimales ,y valor dolares a 4 decimales.
Lo que no me fijé, es a nivel de header del complemento, cómo queda el total en USD.

**Comment by RigoFlores** [comment]
Casi se cumplió todo, excepto lo de los 6 decimales en valorUnitario y lo de los 4 decimales en el cálculo del valordolares.
Aunque si lo timbra, no descarto la posibilidad que marque error, justo por esta razón lo tuvimos que recalcular en optibelt.

Yo creo que ya para cerrar este punto, con únicamente cambiar el valor unitario a 6 decimales, ya quedaría...dejando el valordolares con 2 decimales

Ejemplo, 
El valor en dolares ya lo tenemos desde el CFDi estándar. Ejemplo: 3200
La nueva cantidad, ellos la teclearán... quedó tan chingona esta opción que creo que no solo servirá para convertir piezas a KG, sino prácticamente cualquier unidad a otra. Ejemplo: 6.77

Entonces solo se calcularía el nuevo valor unitario: 3200/6.77 = 472.673559
Con esto ya quedaría casi sin lugar a fallas.

**Comment by jccastillo0007** [comment]
done
