### ISSUE TITLE
Web-  No procesa correctamente el IVA exento trasladado y marca error...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2149]
Marca error con ese tipo de impuesto.
Lo extraño es que en pru, si lo hace, pero le coloca clave de impuesto 003, que según yo es el IEPS.

100 : Error al crear XML

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ahora marca este otro mensaje.

 Si el valor registrado en el campo TipoFactor que corresponde a Traslado es Exento no se deben registrar los campos TasaOCuota ni Importe.

A nivel del producto, cuando el iva es exento, no debe llevar esos campos. Pero si los está incluyendo:

        <cfdi:Concepto ClaveProdServ="01010101" NoIdentificacion="PROD-TEST" Cantidad="1.00" ClaveUnidad="H87" Unidad="PZA" Descripcion="PRODUCTO DE PRUEBAS" ValorUnitario="100.0000" Importe="100.000000" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="100.000000" Impuesto="002" TipoFactor="Exento" TasaOCuota="0.0" Importe="0.0"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos>
        <cfdi:Traslados>
            <cfdi:Traslado Base="100.0" Impuesto="002" TipoFactor="Exento"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
