### ISSUE TITLE
ERP - NO GENERA ADDENDA PEPSICO - USR ROSG790930SG8

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#215]
ESTA CLIENTE CAPTURA LA ADDENDA AL MOMENTO DE FACTURAR, PERO NO LO ESTÁ HACIENDO.
ESTO LO ASUMO YA QUE LOS XML CON ADDENDA APARECEN EN CONSULTAS, PERO SI ME VOY AL MENÚ DE ADDENDAS, AHÍ NO APARECE NINGÚN XML.

**Comment by jccastillo0007** [comment]
En el menú Addendas solo aparecen las addendas generadas desde el Addendador, si una addenda se genera desde la factura, no aparece en el menú addendas.

//ESTE CLIENTE NO GENERA ADDENDAS CON EL ADDENDADOR, SINO DESDE FACTURAS
mysql> select \* from ClientAddenda where emisor  = 'ROSG790930SG8'
Empty set (0.00 sec)

// ESTOS CLIENTES SON DESDE EL ADDENDADOR
mysql> select count(_), emisor from ClientAddenda group by emisor limit 10;
+----------+---------------+
| count(_) | emisor        |
+----------+---------------+
|        2 | AEPJ801112PZ1 |
|        2 | BMC9511283I3  |
|       10 | GHI0405279G0  |
|        6 | IDE130725764  |
|       10 | ISP1202204T2  |
|        1 | SORM841103GU8 |
|      777 | TME080527TY3  |
|        4 | VAAT2203316P2 |
+----------+---------------+
8 rows in set (0.00 sec)

**Comment by jccastillo0007** [comment]
Ya probé ambas, addendador y factura + addenda, estan trabajando bien.
