### ISSUE TITLE
Barricas - Mayo 2 - Desacoplar la edición del archivo de Factura-T para ser editado desde varios lugares

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2153]
Como decía el comercial... "te lo diiiijeeee..." (con voz de tenor).
Se requiere que el archivo que se pasa a ProcesarMasTarde (cuando tiene errores), pueda ser editado por distintas personas, es decir desde distintas computadoras.

Una solución, es mover (sacar de facturat) la pantalla de edición. Sería una aplicación de 1 sola pantalla, donde se configuran las rutas de leer el archivo y donde regresarlo.
Estas rutas, las pretenden configurar para ser remotas, a través de la red.
Así cada supervisor, desde su compu, podría editar el archivo, editarlo y volverlo a procesar.

Si encuentras otra alternativa, pues es bienvenida.

**Comment by jccastillo0007** [comment]
Me parece que esa es la solución más adecuada y menos compleja.
Las rutas es algo que ellos tendrán que ingresar en pantalla, tanto la de archivos por corregir como la de enviar a procesar
Solo se podrá trabajar con una ruta a la vez, si quieren cambiar de ruta tendrán que ingresarla en la pantalla
No se almacenará ninguna ruta en memoria, tal vez la última usada pero no todas las que han usado
Veremos que tantos problemas salen por concurrencia o accesos a los servidores remotos
Estimo unos 20k

**Comment by RigoFlores** [comment]
Esta aplicacion, será la misma en cada computadora diferente de cada supervisor.
Se configurará o capturará la ruta, será una sola vez, porque eso no cambiará. O se puede dejar en un archivo de configuración. No se supone que esté cambiando a cada rato. De hecho al inicio y muy rara ocasión después.

No se esperaría que hubiera concurrencia en los archivos, ya que precisamente cada supervisor tiene sus propios archivos que atenderá... bueno, eso es lo que creo. Hay que confirmarlo con ellos.

El acceso y configuracion de las carpetas remotas, ellos lo configurarán. No es tema nuestro.

Les cotizaré, pero creo que no 20k. Hay que ver todo junto y te voy diciendo.

Este requerimiento apenas lo voy a cotizar.

**Comment by jccastillo0007** [comment]
ok, no se que falte... yo solo analicé este requerimiento... capaz que no estoy entendiendo bien el tema de los folders remotos por cada supervisor... 
hay algún cambio en el funcionamiento actual de facturat ? respecto al manejo de los archivos?
