### ISSUE TITLE
Nueva instancia del AutoFactura-T ->  Requisitos generales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2154]
Para que los vayas conociendo....

1. Plataforma en línea, donde los clientes puedan ingresar los datos de su(s) ticket(s) para generar sus propias facturas.  (NUEVA INSTANCIA DEL AUTOFACTURA-T)

2. La información de las facturas a generar, se enviará en el formato actual del archivo plano.  (ADOPTAR EL LAYOUT DEL CLIENTE)

3. La codificación del archivo de texto plano debe ser en UTF-8.   (GENERADO POR EL SISTEMA ACTUAL)

4. Algunos productos de las facturas, podrán incluir impuestos locales (ISH).  (COMPLEMENTO DE IMPUESTOS LOCALES)

5. En algunos casos se deberá incluir el complemento INE en la factura, cuya contenido igualmente se incluirá en el archivo de texto plano.  (COMPLEMENTO DEL INE. OJO, EN ESTE CASO SE INCLUIRÍAN HASTA 2 COMPLEMENTOS EN LA MISMA FACTURA)

6. La solución permitirá emitir la factura global, de acuerdo a las necesidades del hotel. Se considerarán los tickets no facturados. (ACTUALMENTE NO CONTAMOS CON ESTA FACILIDAD)

7. El emisor de las facturas, tendrá una cuenta de administrador para acceder a la plataforma y poder emitir, consultar, descargar, reenviar por correo y cancelar las facturas emitidas.  (ESO YA LO TENEMOS, ES LA PLATAFORMA DE FACTURACIÓN ESTÁNDAR)

8. La plataforma de autofacturación será personalizada, con el nombre del hotel, logo y datos de contacto. (AJUSTAR EL TEMA DE ESTILOS PARA LA NUEVA INSTANCIA)

9. Se entregará una aplicación, con la cual se transferirán los archivos de texto, hacia la plataforma.  (TAL COMO SE HIZO EN ABASTOS, SE ENTREGARÁ UNA VERSIÓN DE ESCRITORIO, ENCARGADA DE PARSEAR Y ENVIAR LA INFO A LA PLATAFORMA PARA QUE ESTÉ DISPONIBLE PARA FACTURAR. VA DE LA MANO CON EL PUNTO 2)

**Comment by jccastillo0007** [comment]
Ya esta aprobado este proyecto ?

**Comment by jccastillo0007** [comment]
listo para pruebas , yo creo que nos seguimos en este ticket, porque los otros tickets que abriste están muy ambig˜uos respecto a levantar una instancia de descargat en pru...


 ojo, hay que empatar bien los domiciliios del emisor y los receptores, de lo que se recibe en el txt vs lo que se tiene en la llave de facturat y en la base de datos del receptor

**Comment by RigoFlores** [comment]
No entendí el tema este de que empatar los datos del receptor.
Del archivo, de hecho, no se toman los datos del receptor... según yo se tienen que ignorar.
Estamos hablando que en el AutoFacturaT el receptor tiene que capturar sus datos y buscar los tickets a facturar.

En qué momento, se debe tomar la info del receptor, a partir del archivo???
Nosotros para garantizar la consistencia de datos, se debe tomar de una sola fuente, esto es en la base de datos del autofacturat, que no se si sea la misma que el facturat.

Importante que comentes que estás viendo aquí con eso de "empatar los datos del receptor"

**Comment by RigoFlores** [comment]
Por otro lado este ticket, es como un panorama general del alcance.
Cada punto se agregará en un ticket independiente.
