### ISSUE TITLE
AutofacturaT(1) -  Layout del cliente -> Llevarlo a la plataforma de FacturaT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2155]
Aquí tienes la descripción del layout del archivo de texto, que tendrá la extensión que ya habíamos platicado (spf), pero es texto plano.
Este layout es el que debemos llevar a la plataforma para ser facturado desde el AutoFactura-T

[Layout TXT File.docx.txt](https://github.com/jccastillo0007/eFacturaT/files/11411089/Layout.TXT.File.docx.txt)

[C33_NPG_19958.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/11411096/C33_NPG_19958.spf.txt)

**Comment by RigoFlores** [comment]
Todo lo de AutoFacturaT ya está con anticipo. Este desarrollo ya hay que arrancarlo.

**Comment by jccastillo0007** [comment]
Rijo... ya tengo el parseo del archivo, pero algunos datos no sé. cómo interpretarlos... te falto hacer el mapeo entre sus datos y los datos que manejamos nosotros para la factura.
Ejemplo, el primer dato CFD que tiene el valor 601,... y asi hay varias.

**Comment by RigoFlores** [comment]
Le agregué algunos comentarios en los campos o en el bloque de datos.

Si faltan, dime cuáles y los investigo.

[Layout TXT File.docx (2).txt](https://github.com/jccastillo0007/eFacturaT/files/11465795/Layout.TXT.File.docx.2.txt)

**Comment by RigoFlores** [comment]
Anexo un archivo de texto original, otro con las notas de cada campo, el PDF y XML generado a partir de dicho texto.

[hotel.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/11472871/hotel.zip.txt)

**Comment by jccastillo0007** [comment]
Ya casi esta listo... ya estoy parseando los archivos y enviándolos al server.
eFacturaT los recibe y almacena correctamente
Solo me falta habilitar la otra instancia de DescargaT con el RFC IIA como emisor, para que puede empezar a facturar

**Comment by jccastillo0007** [comment]
Comentarios:

Todos los productos DEBEN iniciar con "No aplica"

Pregunta:
El orden de los campos del archivo de ejemplo, siempre será asi?
Tengo dudas de que datos serán obligatorios y cuales son opcionales?

**Comment by RigoFlores** [comment]
Ya estoy pidiendo confirmación.
Al igual que el el layout nuestro, si el dato no se incluye, no se debe integrar al XML.

O a que te refieres con los datos obligatorios y opcionales?

**Comment by jccastillo0007** [comment]
Me refiero a saber cuales son los obligatorios, para que si esta mal el archivo, no enviarlo al servidor, y estar acumulando basura

**Comment by RigoFlores** [comment]
deja revisar, eso no está tan fácil.
Tengo el mapeo de los obligatorios en CFDI 4.0
Pero ahora tengo que hacer el mapeo a ese layout.

en cuanto lo tenga, te lo mando.

**Comment by RigoFlores** [comment]
aquí está indicando los obligatorios. El resto serán opcionales, Si se incluyen, se envían al XML y/o PDF.

[C33_NPG_19958-Comentado.spf (2).txt](https://github.com/jccastillo0007/eFacturaT/files/11513119/C33_NPG_19958-Comentado.spf.2.txt)

**Comment by jccastillo0007** [comment]
Si todo va bien, el lunes ya estaría listo

**Comment by jccastillo0007** [comment]
Listo.. se debe usar el rfc IIA040805DZ4 como emisor, hay que modificar el archivo...

Siento como que faltan validaciones antes de enviar la info al servidor

**Comment by RigoFlores** [comment]
Aún no tengo forma de validarlo

**Comment by jccastillo0007** [comment]
listo para pruebas , yo creo que nos seguimos en este ticket, porque el otro que abriste es muy ambig˜uo respecto a levantar una instancia de descargat en pru... ojo, hay que empatar bien los domiciliios del emisor y los receptores, de lo que se recibe en el txt vs lo que se tiene en la llave de facturat y en la base de datos del receptor

**Comment by RigoFlores** [comment]
oye, si comento que aún no era posible validarlo, porqué lo cerraste?

**Comment by RigoFlores** [comment]
Está tomando datos del receptor que no debe llevar a la plataforma. Estos se capturan al momento del registro del cliente o de la factura al instante:

1. RFC
2. Nombre
3. Régimen Fiscal
4. Código Postal
5. Uso CFDI

Aún con ello, los últimos 4 datos, no se de donde los está tomando, ya que en el archivo vienen otros datos.
Ahora mismo intenta timbrar con esto:

 <cfdi:Receptor Rfc="XAXX010101000" Nombre="PUBLICO EN GENERAL NACIONAL" DomicilioFiscalReceptor="76160" RegimenFiscalReceptor="616" UsoCFDI="G03"/>

y en el archivo viene:
Nombre Publico en general, Régimen 616, CP 11510, UsoCFDI S01.

Total, hay que ignorarlos.
