### ISSUE TITLE
AutofacturaT (2) - Levantar la nueva instancia para AutofacturaT en pruebas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2156]
Validaremos que podremos tener una segunda instancia del AutofacturaT, donde se podrá facturar lo que llegue del conector de ellos. 
Su nombre podría ser "AltezaPolanco", como parte del dominio... o "FortalezaPolanco"..

Lo que validaré es que en una URL distinta al descargaT de pruebas, pueda consultar los tickets de FortalezaPolanco

**Comment by RigoFlores** [comment]
no se porqué no veo tus comentarios aquí, ya que me llegó por correo una pregunta.
La respuestas es si, ya está autorizado este proyecto, dieron el anticipo

**Comment by jccastillo0007** [comment]
jajaja, es que la pregunta la hice en el otro ticket, uno general que levantaste

**Comment by jccastillo0007** [comment]
Done: http://efacturat-stagging.com.mx:8080/DescargaTuCFDi-Alteza

Se debe usar el RFC IIA040805DZ4, como emisor

**Comment by RigoFlores** [comment]
La búsqueda de la factura, será por lo pronto por el folio que aparece en el archivo. Ese será el ID.
El total, que sea el del XML, aunque muy probablemente pidan que sea el ooootro total, el que incluye propinas y otros no facturables...

**Comment by RigoFlores** [comment]
Oyes, en la personalización del nombre, solo hay que poner el nombre de ellos... o algo que ofrezca mas idea, por ejemplo

http://efacturat-stagging.com.mx:8080/FacturacionAlteza

**Comment by RigoFlores** [comment]
No se desplegaba la información del ticket, entonces no esta completo aún.
Tengo que validarlo

**Comment by RigoFlores** [comment]
Tenemos algunos detalles:
a) La plataforma que se levantó es dela versión 3.3 . Por lo tanto en la edición del perfil no se puede editar ni el código postal ni el régimen fiscal del receptor.

b) Solo puede encontrar el ticket, si lo busco con registro. En Factura al Instante no lo encuentra (ya sabemos que es porque se está asociado un ticket al rfc receptor, lo cual por lo pronto, no está bien... no sé si después nos pidan que así sea).

**Comment by RigoFlores** [comment]
Detalles:

1. NO está tomando el régimen fiscal de lo capturado en pantalla.
2. Sigue sin encontrar el ticket desde factura al instante. Solo desde la pantalla de registro.
3. El identificador único de la factura, será el campo Ppers5, en la sección personalizado.
4. El total que va a capturar el cliente será VlrPagar en la sección de totales.

OJO en el punto 4, no sé cómo afecte en la base de datos, ya que ese total no corresponde al total del XML.

**Comment by jccastillo0007** [comment]
http://efacturat-stagging.com.mx:8080/FacturacionAlteza/

**Comment by jccastillo0007** [comment]
1. NO está tomando el régimen fiscal de lo capturado en pantalla.
JC. RegimenFiscalReceptor="616" esto pone en el xml y es lo capturado en el perfil del usuario

**Comment by jccastillo0007** [comment]
3.El identificador único de la factura, será el campo Ppers5, en la sección personalizado.
JC. Ppers5        47185424-1 
No puede ser ese datos, ya que es alfanumérico, debe ser numérico, acuérdate del desmadre de las barricas

**Comment by RigoFlores** [comment]
Se me olvidó comentar. Es sin guión. Es ese dato, sin guion. Enviado desde mi Huawei de Telcel.-------- Mensaje original --------De: JC ***@***.***>Fecha: sáb., 27 de mayo de 2023 11:10Para: jccastillo0007/eFacturaT ***@***.***>CC: RigoFlores ***@***.***>, State change ***@***.***>Asunto: Re: [jccastillo0007/eFacturaT] AutofacturaT (2) - Levantar la nueva instancia para AutofacturaT en pruebas. (Issue #2156)
3.El identificador único de la factura, será el campo Ppers5, en la sección personalizado.
JC. Ppers5        47185424-1
No puede ser ese datos, ya que es alfanumérico, debe ser numérico, acuérdate del desmadre de las barricas

**Comment by RigoFlores** [comment]
> 1. NO está tomando el régimen fiscal de lo capturado en pantalla.
>    JC. RegimenFiscalReceptor="616" esto pone en el xml y es lo capturado en el perfil del usuario

Chiaaaa... la cagué, no era el régimen, era el uso de CFDI. El uso de CFDI no lo está tomando de lo que captures en pantalla. Siempre le pone G03.

y por el lado del ID único, si es el dato que te comenté, pero olvidé mencionar que se capturará sin el guión. Incluso, podría ser sin guión y el número después del guión.

Por ejemplo, este dato 47012236-1, se puede almacenar como ID 47012236  (sin el guión y sin el 1)

**Comment by jccastillo0007** [comment]
ok, el uso de cfdi ya esta corregido... ojo, ese error esta en abastos también.

Para lo del id, ellos van a enviar el valor ya sin el guion ?

**Comment by RigoFlores** [comment]
No, ellos lo enviarán asi como está. Nosotros eliminamos el -1, o solo el guión. Enviado desde mi Huawei de Telcel.-------- Mensaje original --------De: JC ***@***.***>Fecha: sáb., 27 de mayo de 2023 23:28Para: jccastillo0007/eFacturaT ***@***.***>CC: RigoFlores ***@***.***>, State change ***@***.***>Asunto: Re: [jccastillo0007/eFacturaT] AutofacturaT (2) - Levantar la nueva instancia para AutofacturaT en pruebas. (Issue #2156)
ok, el uso de cfdi ya esta corregido... ojo, ese error esta en abastos también.
Para lo del id, ellos van a enviar el valor ya sin el guion ?

**Comment by RigoFlores** [comment]
Nosotros tendremos que eliminar el guion o eliminamos el guión y el número ... como sea mas simple.
Yo creo que mejor sin el guión y el número.

**Comment by RigoFlores** [comment]
En cuanto al tema de abastos, no recuerdo si así lo pidieron. Veo muy probable que si.
De cualquier manera, la solución puede ser dejar GastosEnGeneral como opción por default. Y si el cliente quiere cambiar, pues que lo cambie.

**Comment by RigoFlores** [comment]
Detalles (los mismos):

2. Sigue sin encontrar el ticket desde factura al instante. Solo desde la pantalla de registro.
3. El identificador único de la factura, será el campo Ppers5, en la sección personalizado. (nosotros le eliminamos el guión y el número delante del guión).
4. El total que va a capturar el cliente será VlrPagar en la sección de totales.
 

OJO en el punto 4, no sé cómo afecte en la base de datos, ya que ese total no corresponde al total del XML.

**Comment by RigoFlores** [comment]
Ya documenté individualmente, ya que veo que así te confunde y no se atienden los tickets
