### ISSUE TITLE
ERP - AGREGAR FILTRO DE FECHA EN ADDENDADOR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#216]
CHECA AL CLIENTE CON RFC TME080527TY3, TIENE LA ADDENDA HOME DEPOT Y CON 26 PÁGINAS PARA BÚSQUEDA.
QUIZÁS CONVENGA DEFINIR UN FILTRO DE FECHA, PARA NO MOSTRAR TANTA INFORMACIÓN QUE FINALMENTE NO LES SIRVE AL MOMENTO DE LA CONSULTA.

PUEDE SER ABIERTO, COMO ESTÁ AHORA, U OPCIONALMENTE COLOCAR EL FILTRO DE FECHA.

**Comment by jccastillo0007** [comment]
Hay que agregar una pantalla de Consultas, unicamente para facturas procesadas por el addendador... checa la pantalla de consultas para Compras.

**Comment by jccastillo0007** [comment]
Fixed.
