### ISSUE TITLE
Optibelt - No envía por correo las facturas a este cliente, pero si los documentos de pago.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2160]
Los correos a los clientes de optibelt, se envían desde el servidor web.
Este cliente, tiene capturados los correos destino.

<img width="611" alt="optibelt" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/83f6c979-bc3a-41d6-9096-a7dfa869d02e">

Cuando se trata de un documento de pago (que capturan y generan en web directamente), si se envían los correos.
Cuando se trata de facturas y notas de crédito, que se generan en el conector, no envía los correos.

Si en consultas web, tomas una factura y le das reenviar por correo, no aparece ningún correo.

<img width="611" alt="optibelt2" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/265eeeaf-ad41-4aae-a3e3-0477dee66825">

Si haces lo mismo para un pago, si aparecen los correos.

<img width="379" alt="pagoOptibelt" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/18cbc4b5-7944-4972-9718-97f896cb8137">

**Comment by jccastillo0007** [comment]
El problema es que ese cliente EIS991116GC4 no tiene asignado un número de cliente, de acuerdo al código, se valida el número de cliente al momento de obtener los emails de la base de datos... por esa razón no se manda los correos

**Comment by RigoFlores** [comment]
ok, lo reviso con ellos.
Solo es capturar el número de cliente y con eso en teoría ya jalaría?
