### ISSUE TITLE
Alteza - la tasa del impuesto local se debe reportar a 2 decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2163]
En el archivo de ejemplo viene así: 0.035 ... 
El SAT lo pide a 2 decimales únicamente para es dato del complemento de impuesto local.

Se requiere truncar a 2 decimales (0.03) ... o se envía al XML como 3.5.

En el ejemplo timbrado que ellos enviaron, lo truncan a 2 decimales. 
Yo creo que si lo mandamos como 3.5 no debe haber problema...

**Si el SAT define que el formato es a 2 decimales máximo, y si las tasas pueden ser de 3.5%... entonces no debería ir como 0.03, mas bien debería ir como 3.5...**

**Comment by jccastillo0007** [comment]
ya lo esta enviando así TasadeTraslado="0.03" y si se timbró... no hay que moverle para adivinar

**Comment by RigoFlores** [comment]
lo mandó así, porque yo modifiqué el archivo (para avanzarle).

Se requiere truncar a 2 decimales, o multiplicar esa tasa por 100 y como quiera, reportarla a 2 decimales.

**Comment by RigoFlores** [comment]
estos son los archivos de prueba modificados, donde se envía la tasa a 2 decimales.
Así si jala, pero no porque la aplicación "ya lo mande así", jejeje

[alteza.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/11606767/alteza.spf.txt)
[alteza.spfLATIA.txt](https://github.com/jccastillo0007/eFacturaT/files/11606768/alteza.spfLATIA.txt)

**Comment by jccastillo0007** [comment]
listo, fue más fácil truncarlo a 0.03.

**Comment by RigoFlores** [comment]
Tomé la versión de hoy 03 de Junio, y en los archivos se incluye la tasa del impuesto local a 3 decimales.
Pero no, no lo truncó.
Cuando intenté timbrarlo, marcó XML mal formado, precisamente porque el impuesto local lo reporta a 3 decimales.

            <implocal:TrasladosLocales ImpLocTrasladado="Hospedaje" Importe="87.50" TasadeTraslado="0.035"/>

Estos son los archivos de prueba que incluyen el impuesto local a 3 decimales.

[alteza.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/11644549/alteza.spf.txt)
[alteza.spfLATIA.txt](https://github.com/jccastillo0007/eFacturaT/files/11644550/alteza.spfLATIA.txt)

**Comment by jccastillo0007** [comment]
fixed.
Se esta reportando el impuesto dos veces, la primera a nivel producto, y la segunda con las variables :
TipoImp1      002            IVA
TasaImp1      0.160000       Tasa   
MontoImp1     1623.67        // FIN NODO IMPUESTOS
TipoImp2      1.0            ISH  //INICIO IMPUESTOS LOCALES. IMPUESTO LOCAL
TasaImp2      0.035       Tasa  // TASA DE IMPUESTO LOCAL A 2 DECIMALES
MontoImp2     87.50    //MONTO IMPUESTO LOCAL . FIN DE IMPUESTOS LOCALES
Base1         10147.93   //BASE DE IMPUESTO TRASLADADO 

Anteriormente solo se estaba redondeando uno de ellos.

Para probar, hay que volver a subir archivos procesados con la versión de hoy de facturat 13.0.3
