### ISSUE TITLE
Alteza - El uso de CFDI lo regresa a gastos en general, cuando se agrega un ticket

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2164]
Si el usuario ya capturó uno o varios tickets, y luego captura el uso de cfdi y luego regresa a capturar otro ticket, entonces el uso de cfdi lo regresa a gastos en general.

Debe mantener el uso que se haya capturado, independientemente del orden de captura.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
falta validar en factura al instante, ya que ahí no está encontrando el ticket.

**Comment by RigoFlores** [comment]
En factura al instante, hace lo mismo, lo regresa.

**Comment by jccastillo0007** [comment]
Noup, no lo pude reproducir

**Comment by jccastillo0007** [comment]
Hay 4 remisiones del día de hoy, por si quieres probar con esas

**Comment by RigoFlores** [comment]
Te mandé el video por whatsup de cómo reproducirlo

**Comment by jccastillo0007** [comment]
fixed.
