### ISSUE TITLE
Alteza - No encuentra el ticket desde factura al instante

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2165]
Solo si está registrado el receptor lo encuentra.
De hecho, el archivo lo está amarrando a un RFC receptor, ya que así viene en el archivo, pero eso es incorrecto.
NO debe relacionar el archivo a ningún rfc receptor.

**Comment by jccastillo0007** [comment]
Fixed

**Comment by RigoFlores** [comment]
no lo encuentra, dice que total inválido.
Y lo estoy copiando igual que cuando ingresas con usuario registrado.

**Comment by jccastillo0007** [comment]
probé con los últimos 4 remisiones que están en efacturat del día de hoy, todas con importe 11859.1, todas las encontró correctamente, aún sin capturar datos del receptor

**Comment by RigoFlores** [comment]
Seguro estamos validadando distinto.
Te mandé un video por el whatsapp donde te muestro como no lo puede encontrar, ya que marca que el monto del ticket es inválido, y de ahí no pasa.
En factura al instante, yo me voy directo a buscar el ticket, no le estoy capturando ningún dato de la factura.
Ahora, si tiene que estar capturado algo, pues no, no debe se una condición.

**Comment by jccastillo0007** [comment]
checa el video que esta en dropbox, en release chacarrones, con nombre: Screen Recording 2023-05-31

**Comment by RigoFlores** [comment]
Si, ya lo vi.
Con ello, hice la prueba en mozilla y no jala.

Tons, el problema si existe, pero está asociado al navegador, en este caso el chrome, que es el que muchos clientes utilizan.

**Comment by jccastillo0007** [comment]
necesito que revises el log para ver los datos que estas mandando para obtener la remisión.

No entendí lo de los browsers, yo uso Chrome, hoy pruebo con Firefox

**Comment by RigoFlores** [comment]
Mencioné que estoy usando Chrome también.
Si lo busco cuando el usuario ingresa su usuario y contraseña, si lo encuentra.
Si eso mismo hago desde factura al instante, marca que el total es inválido.

Peeero, si en lugar de usar el punto decimal, ocupo la coma, como separador de decimales, ahí si lo encuentra.

Y es el mismo navegador. Que podrá ser?
