### ISSUE TITLE
Alteza - tomar el total del campo VlrPagar en la sección de totales.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2167]
Cuando se busca un ticket, se teclea el ID único y el total.
Bueno este total que teclea el usuario, debe ser el que aparece en ese campo VlrPagar.

OJO, este total no es el mismo total del XML, ya que este total VlrPagar, incluye propinas o algún otro cargo no facturable.

Hay que tener cuidado como se despliega en las consultas de la plataforma.
Creo que lo correcto es que en remisión indique el total VlrPagar, pero una vez timbrado, pues será el total del XML el que se muestre en las consultas.

**Comment by jccastillo0007** [comment]
done.

nota. el total real se verá en la pantalla de efacturate, y también en los datos generales del descargat... el único que conoce el total con propinas es el cliente porque lo tiene en el ticket, pero en las pantallas no se podrá ver

**Comment by RigoFlores** [comment]
OK, ya encuentra el ticket si tecleas ese total que incluye la propina.
Yo creo que el tema que no muestre ese total en la pantalla, va a generar conflicto con el cliente, pero ya veremos.
