### ISSUE TITLE
Alteza - no está enviando los datos extra al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2168]
Son hasta 14 los datos extra documentados, pero no está enviando ninguno.

[C33_NPG_19958-Comentado.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/11594591/C33_NPG_19958-Comentado.spf.txt)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ya está enviando los datos extra del 1 al 4.
No está enviando los datos extra del 5 al 14.

Anexo la spec de los datos extra dentro del archivo. Este archivo ya lo había subido antes.

[C33_NPG_19958-Comentado.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/11644571/C33_NPG_19958-Comentado.spf.txt)

**Comment by jccastillo0007** [comment]
fixed, hay que volver a subir los archivos, para probar
