### ISSUE TITLE
Alteza Conector - no debe asociar un archivo a un rfc receptor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2169]
Ahorita está amarrado el ticket al RFC receptor que viene en el archivo
Por definición del autofacturador, no debe ser así.

**Comment by jccastillo0007** [comment]
no maaaaa eso fue lo primero que arreglé

**Comment by RigoFlores** [comment]
no estaba documentado ni reportado como corregido.
