### ISSUE TITLE
ERP - AJUSTAR NOMBRE DE LOS MENUES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#217]
Nomina por 'Recibos de Nómina'
Addendas, por Addendador
Addendas Notarios, por Notarios (aún falta revisar como funcionaría esa pantalla, pero 100% seguro que no es addenda).
Admin, por Administración

**Comment by jccastillo0007** [comment]
Done.

Lo de notarios es temporal... no va a existir ese menú.

Estas seguro de Addendador... esta bien chacarron...

**Comment by RigoFlores** [comment]
OK, entonces que sea simplemente 'Addendas' como estaba anteriormente.
