### ISSUE TITLE
Conector Optibelt - agregar una pantalla de edición de archivo para agregar datos extra

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2170]
En una pantalla tipo las barricas, es decir de edición de archivos de texto en el formato de optibelt.
El cliente colocará manualmente el archivo de texto en la carpeta de **_reintenteMasTarde_**.

Se requiere capturar lo siguiente para agregarlo al archivo.

-	Clave de Incoterm (del catálogo del SAT)  (dato extra 5)
-	Peso Total de las mercancías (en Kgs):    (dato extra 6)
-	País de Origen: (del catálogo del SAT):  (dato extra 7)

Estos datos no se requieren en el XML, excepto el incoterm que es parte del Complemento de comercio exterior. Entiendo que se refiere a incluirlos en el PDF.

Se agregará una pantalla para que puedan elegir el archivo a editar de una carpeta debajo de conector. Dicha carpeta se llamará **_reintenteMasTarde_**.

Se presentarán los siguientes datos del archivo en formato solo lectura, para identificar el archivo se presentará en pantalla:
1.	Nombre Cliente
2.	RFC Cliente
3.	Folio
4.	Tipo
5.	Total
6.	Exportación

Se tendrá la posibilidad de agregar los siguientes datos al archivo. El formato del layout lo definimos nosotros.

a)	Incoterm:  (será la CLAVE de incoterm que se incluirá en el CCE. Hoy en día este dato es fijo, de acuerdo a lo solicitado en su momento)
b)	Peso:   (será el peso total de la mercancía que ampara la factura).
c)	País de Origen: (País de Origen de la mercancía).

Estos datos se deberán agregar al archivo de tal manera que Factura-T los pueda interpretar y los envíe hacia el PDF.

Se presentará un botón para guardar el archivo.
Y finalmente otro botón para procesar el archivo. 
Esto es, este archivo se colocará en la carpeta del conector de Factura-T para su procesamiento. 

El conector de optibelt, tomará esos 3 datos nuevos del layout y los enviará como datos extra.
El dato de clave de incoterm, se enviará al CCE si el archivo incluye dicho complemento.

**Comment by RigoFlores** [comment]
Por cierto, por favor indícame de donde se toman los datos extra5 al 14.
Asimismo, de donde se toma actualmente el incoterm.

**Comment by jccastillo0007** [comment]
Los datos extras se toman del renglón que inicia con H5

cfd.getExtraData().add(new Field("", values[1]));
			cfd.getExtraData().add(new Field("", values[2]));
			cfd.getExtraData().add(new Field("", values[4]));
			cfd.getExtraData().add(new Field("", values[5]));
			cfd.getExtraData().add(new Field("", values[6]));
			cfd.getExtraData().add(new Field("", values[7]));
			cfd.getExtraData().add(new Field("", values[10]));
			cfd.getExtraData().add(new Field("", values[11]));
			cfd.getExtraData().add(new Field("", values[12]));
			cfd.getExtraData().add(new Field("", values[13]));


Solo esos datos

**Comment by jccastillo0007** [comment]
Incoterm se manda el valor fijo: EXW

**Comment by jccastillo0007** [comment]
Se puede usar el mismo H5 para agregar los datos capturados en pantalla? Puedes confirmar con ellos que nunca mandan algo en el H5

**Comment by RigoFlores** [comment]
Los ocupan para clientes nacionales.
En el caso de CCE, que ahora mismo solo aplica para rfc XEXX010101000 no se ocupan... por lo pronto.

Entonces, pues podríamos tomarlos de ahí, con un riesgo. Que no lo parsée bien el sistema, ya que anteriormente debería tomar de ahí los datos extra, pero al PDF llegaba el H5 todo completo..

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Bajé la versión de hoy 03 de junio.
Si presenta la pantalla de edición.
Si le agrega los datos capturados.
Si lo manda a procesar.

Pero cuando lo pones en la carpeta del conector, ya no hace nada. No lo procesa. Solo muestra al final de la consola, esos 3 datos que se le agregaron al archivo. 

Probé con este archivo. Pero el RFC receptor no es del extranjero, ni el archivo contiene lo de CCE. Eso es condición??

[USD.txt](https://github.com/jccastillo0007/eFacturaT/files/11644567/USD.txt)

**Comment by jccastillo0007** [comment]
fixed, había un error en la validación de incoterm

**Comment by RigoFlores** [comment]
OK, ya vi que manda los datos extra. OK
Solo faltó mandar el incoterm capturado al CCE, en lugar de dejarlo fijo.

**Comment by jccastillo0007** [comment]
ya debería mandarlo, con que archivo puedo probar, y que si se timbre?

**Comment by RigoFlores** [comment]
[xmlCCE-EUR-USD.txt](https://github.com/jccastillo0007/eFacturaT/files/11653447/xmlCCE-EUR-USD.txt)

Este archivo timbra, solo recuerda que tienes que colocar el tipo de cambio del día de ayer... si fuera hoy, sería el del viernes.
