### ISSUE TITLE
Alteza - no toma todos los productos de una segunda factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2171]
Le estoy agregando un ticket con n productos inicialmente, y lo carga bien.
Cuando le agrego un segundo ticket igual con n productos si lo incluye, pero solamente toma el primer producto y ese es lo único que agrega a la factura que se muestra en pantalla.

Total, que no está cargando todos los n productos de un segundo ticket. Solo agrega el primero. Si lo timbra, pero solo todos los productos del primer ticket y el producto 1 del segundo ticket.

Intenté con 3 tickets , y hace lo mismo del 2o y 3er ticket, solo agrega el 1er producto. 

Pero marca toda la factura (2a  y 3a ) como pagada, cuando se factura.

**Comment by jccastillo0007** [comment]
Puedes pedir tickets con 2 productos para poder probar, no sé como te diste cuenta de eso, si tienen un montón de productos.

**Comment by RigoFlores** [comment]
En el issue 2163 subí 2 archivos.
Aunque realmente es el mismo archivo, con distinto nombre y los datos del receptor (que se ignoran) diferentes.
Cómo me doy cuenta????, chiaaaaa. 
Cuando los cargo ambos, solo muestra en pantalla el primer producto del segundo archivo y el total de la factura no es por la suma de los 2 totales, sino es el total de una factura, mas el monto del primer producto del segundo archivo.

Tu quieres que pida 2 archivos que contengan 2 productos o digamos pocos productos para probar?

**Comment by jccastillo0007** [comment]
Si

**Comment by RigoFlores** [comment]
ok, lo pediré, pero si puedes checarlo enviando los dos archivos que subí.
Ya que cuando si procesa los 2 completos, el total se debe ir al doble. Y eso es justo lo que no pasa.

**Comment by RigoFlores** [comment]
No sé porqué le pones bloqueado, si es muy fácil notar que solo carga un producto de la segunda factura.
No considero que sea un bloqueo esto.

**Comment by jccastillo0007** [comment]
No es fácil hacer el debug con tantos productos... necesito poder hacerlo

**Comment by RigoFlores** [comment]
[C33_NPG_20660.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/11748976/C33_NPG_20660.zip.txt)


5 archivos de ejemplo

4 contienen 2 productos y 1 de ellos con 3 productos.
