### ISSUE TITLE
Conector Optibelt - Cuando trabaja una factura en EUR, manda en la cantidad con letra "pesos M.N."

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2172]
Eso yo lo vi en la computadora del cliente.
Ellos tienen windows 10 pro.

Lo intenté reproducir en mi compu con windos 8.1 y aquí si trabaja bien.
Es el tema aquel, que te comenté que tenía distinto comportamiento.

ok, pues este es oootro de esos comportamientos raros.

tu puedes validar en una compu con windows 10 pro?

O qué otra cosa podría ser???

**Comment by jccastillo0007** [comment]
no tengo windows 10, pero no creo que esto dependa de windows... checa el classpath, tal vez esta cargando una versión diferente a la que debe, el java classloader carga y ejecuta la primer clase que encuentra en el classpath

**Comment by RigoFlores** [comment]
ok, aquí el enfoque para atender el problema, es revisar si el java que está ejecutando no es el 8.
O cuál versión de java debería ser?

Donde checo la configuración que tiene de Java?

**Comment by jccastillo0007** [comment]
puedes verlo con java -version, en la misma ventana donde corre facturat, pero ese tampoco será el problema, ya que ni java ni windows pueden decidir sobre la lógica de la aplicación...

mas bien, en la ventana donde corre facturat, checa el classpath y el path, creo que con echo %classpath% te lo despliega

y en esas dos variables, checa que no tenga configurado un jar de facturat diferente al que se supone se esta ejecutando

**Comment by RigoFlores** [comment]
Finalmente, aquí está como reproducirlo. Ya que llevé el ambiente de pruebas a la compu del clietne y lo hizo bien.
Entonces me traje la bd de optibelt y logré reproducirlo en mi computadora.


Aquí dejo la BD y el archivo de texto.
Configura la BD de acuerdo a tu ambiente, y no olvides configurar un logo, ya que si no tiene marca error.

[facturat_db.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/11671185/facturat_db.zip.txt)
[MXRE231124478.TXT](https://github.com/jccastillo0007/eFacturaT/files/11671186/MXRE231124478.TXT)

![BLANCO](https://github.com/jccastillo0007/eFacturaT/assets/2912775/ea23f1f9-c30f-4401-a5ad-ed8d65d4eb11)

**Comment by RigoFlores** [comment]
[facturaT_IVD920810GU2.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/11671210/facturaT_IVD920810GU2.cfdi.txt)
[optibelt_products PlantillaJasper.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/11671224/optibelt_products.PlantillaJasper.zip.txt)

Aquí la llave de optibelt, la plantilla de Jasper.

**Comment by jccastillo0007** [comment]
listo, encontré el error... 
1. En web si lo muestra bien en EUR, checa todas las facturas que genere hoy
2. En standalone, siempre lo debió mostrar ma

subí la version 12.0.9 del zip para que lo cheques

**Comment by RigoFlores** [comment]
Pues realmente no estaba mal en todo caso.
Mencioné que con la base de datos de prueba, si lo hacía bien. De hecho por ello pensé que era de la computadora del cliente.

cuando me llevé el ambiente de pruebas a esa compu, noté que lo hacía bien tambien.
Tons no quedó otra, ya que cambié jars y jdk, no quedó otra que la base de datos.
Con ella si pude reproducir el problema.

**Comment by RigoFlores** [comment]
No, pues no quedó.
Siguió haciendo lo mismo.
Probaste con la base de datos que subí????

**Comment by RigoFlores** [comment]
No mamar, creo que el problema ya lo encontré.
No se lo que corregiste, pero el asunto es que la moneda decía EURO, en lugar de EUR, no mamar....
chiaaaaa..........

**Comment by jccastillo0007** [comment]
también checa el tipo de cambio, debe ser > 1.0 de lo contrario lo pone como Pesos

**Comment by RigoFlores** [comment]
Si, lo del tipo de cambio si lo sabía, si lo revisé.
El pedo es que decía EURO no EUR, no mamar...

Y que fue lo que le moviste entonces??
