### ISSUE TITLE
Optibelt, no envía al PDF de web el domicilio del receptor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2173]
En escritorio si se manda el domicilio del receptor al PDF.

Para optibelt, el PDF se vuelve a construir en el servidor. Ese segundo PDF, no está mostrando el domicilio del receptor.
Es la misma plantilla, solo que no le llegan los datos del domicilio del receptor.

**Comment by jccastillo0007** [comment]
En web, los datos que se mandan al PDF son los mismos que al XML, si el XML no trae el domicilio, no hay forma de obtenerlo... ese puede ser el problema, tienes un ejemplo del xml

**Comment by RigoFlores** [comment]
El XML no tiene domicilio, ya que en el esquema no hay espacio para ello.
Pero en el PDF se esperan las mismas variables que se envían en el conector (escritorio).

Estoy seguro que antes si se mandaba, ya que la réplica del PDF en el servidor web, ya tiene varios años que se hace.
Ciertamente, hace relativamente poco tiempo dejó de enviar cierta info al web.

Una alternativa que se pidió desde el inicio, es que se pueda enviar el PDF generado en escritorio, al servidor. 
De esa manera no habría necesidad de nada, mas que mostrarlo y ya.

**Comment by jccastillo0007** [comment]
seguramente dejo de mostrar esos datos con la versión 4.0 que es donde ya no se usa el domicilio.

Enviar el PDF no es factible, lo mejor será que Optibelt sea uno de los primeros en usar efacturat v2.0, para resolver este problema

**Comment by RigoFlores** [comment]
Recordar que se trata de resolver para el cliente.
Que será más rápido?
Enviar el correo desde el conector o el facturat 2.0?

La verdad no recuerdo porqué no enviamos el correo desde el conector. Son varios correos para un solo cliente. Quizá tenga que ver el número de cliente, que puede tener distintos correos aunque se trate el mismo RFC...

**Comment by jccastillo0007** [comment]
Enviar el correo desde el conector, pero yo tampoco recuerdo porque lo movimos, tal vez había algún  tipo de problema con la conexión a sending blue desde el servidor de optibelt

**Comment by RigoFlores** [comment]
Pues mas bien, quizá entonces no teníamos el servicio de sendinblue.
Entonces, no se podía enviar tantos correos por nuestro servicio "estándar".

De las restricciones que veo son las siguientes:

a) El mismo rfc receptor, puede contar con varias "sucursales", que se distinguen por número de cliente.
b) Los correos, pueden ser varios (muchos) para cada número de cliente, y son  distintos aún cuando el rfc receptor sea el mismo, pero pertenezca a distinta "sucursal".

Entonces, si podemos distinguir el número de cliente, independientemente si es un rfc único o con sucursales, y tomar todo el listado de correos, creo que podríamos intentar desde el conector enviar el correo.

**Comment by RigoFlores** [comment]
Yo creo que se hizo desde web, porque en el sistema de ellos solo se puede capturar 1 correo.
