### ISSUE TITLE
el conector sigue con la problemática de la Ñ

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2174]
Ya sabemos que es un tema del encoding, pero pues el cliente desde el as400 no ha podido arreglarlo.
Y pues se trata de nuestros 2 mejores clientes, figueacero y las barricas.

Tenemos que dar una solución de alguna manera.
El cliente asegura que alguna ocasión nosotros lo corregimos en una versión y ya después volvió a fallar. 
No puedo asegurar que si o que no. Pero si, al inicio se levantó el issue y cuando lo validé, lo cerré, pero no estoy seguro que haya sido porque se corrigió. Igual y coincidió con  que edité el archivo a mano.

Aquí un archivo bueno y otro chueco.

[PJV004927_Ñnojala.txt](https://github.com/jccastillo0007/eFacturaT/files/11671452/PJV004927_Nnojala.txt)
[LVF002059_llevaÑ.txt](https://github.com/jccastillo0007/eFacturaT/files/11671453/LVF002059_llevaN.txt)

**Comment by RigoFlores** [comment]
Por si sirve de algo, el 14 de febrero reportamos que lo habíamos corregido.

**Comment by jccastillo0007** [comment]
sabes si siempre esos archivos vienen en encoding  ISO-8859  ? o no saben ni que pedo

**Comment by RigoFlores** [comment]
Todos los que yo he revisado, si son con ese encoding.

**Comment by jccastillo0007** [comment]
ya encontré una manera de leer el archivo e identificar la ñ, peeeero, necesito saber el encoding... hay manera de que ellos sepan si trae o no ñ ?

**Comment by RigoFlores** [comment]
No entendí... si supieran que contiene la Ñ, cómo nos lo harían saber?
Cómo se enteraría el conector para aplicar una u otra lógica?

**Comment by jccastillo0007** [comment]
por ejemplo, tienen una lista de clientes con este problema ?
podemos agregar un campo al txt para definir si trae ñ ?

La otra es intentar por el lado normal de utf-8, y si el timbrado falla por error en el nombre del cliente, volver a intentar con el encoding ISO-8859 peeeero este approach es muy costoso y lento, pues tendríamos que hacer todo el proceso dos veces

**Comment by RigoFlores** [comment]
Si pueden agregar un campo... por favor.

UTF8=true

**Comment by jccastillo0007** [comment]
déjame hacer unas pruebas antes de solicitar eso.

además eso de UTF8=true no es lo que debemos indicar, si no, todo lo contrario jajajaj

**Comment by RigoFlores** [comment]
No lo he solicitado.
La leyenda y su valor no están definidos aún.

Pero mencionaste que ya habías hecho pruebas, de hecho por ello les pregunté.

**Comment by jccastillo0007** [comment]
La bandera es :
codificadoISO8895=true

Si no se incluye, esta vacía o es false, se va por UTF8

**Comment by RigoFlores** [comment]
sigo en espera que me proporcionen los archivos para validar.

**Comment by RigoFlores** [comment]
Me proporcionaron apenas 1 archivo con la bandera nueva y con el encoding ISO.
Tiene un producto, pero al procesarlo el conector, le incluye (repite, duplica) 2 veces el mismo producto, y con ello truena.
Y ya puedo editarlo desde linux, mantiene el encoding.

[iso-8859-1__Editado.txt](https://github.com/jccastillo0007/eFacturaT/files/11807427/iso-8859-1__Editado.txt)
[CFD77685__ISO-8859-1.txt](https://github.com/jccastillo0007/eFacturaT/files/11807428/CFD77685__ISO-8859-1.txt)

**Comment by jccastillo0007** [comment]
fixed, versión de hoy 06/20

**Comment by RigoFlores** [comment]
Lo probé con el rfc XIQB891116QE4 de pruebas.
Lo tengo como de las barricas. Total que le puse archivos con Ñ y sin Ñ, y jaló.
Esos archivos son de Figueacero y jaló.
Entonces que seguiría???


A cuál RFC de pruebas, le corresponde Alteza?
