### ISSUE TITLE
Conector Optibelt - no incluye el Incoterm capturado en la nueva pantalla

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2175]
este archivo te sirve para probar que no se incluye el incoterm capturado en el CCE del XML generado.

[CCE EUR vida rial 2.TXT](https://github.com/jccastillo0007/eFacturaT/files/11681350/CCE.EUR.vida.rial.2.TXT)

**Comment by jccastillo0007** [comment]
fixed .... bueno probé lo de incoterm pero no pude timbrar por que no use un valor válido de incoterm

usa la version 13.0.1
