### ISSUE TITLE
Complemento de pago en Web pagando a una factura con IVA exento marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2176]
Para reproducirlo puedes hacerlo en pru, con el rfc IIA, y la factura 555.
Es una factura con IVA exento.
Capturas el pago, y lo que genera en el XML es esto (algo similar)...

    <cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="601" UsoCFDI="CP01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago" ValorUnitario="0" Importe="0" ObjetoImp="01"/>
    </cfdi:Conceptos>
</cfdi:Comprobante>

Es decir, el nodo de complemento de pago, se lo pasa por los huevos... lo omite.
Finkok marca error no clasificado... recuerda que cuando es IVA exento, solo se reportan 3 datos a nivel de impuestos DR y impuestosP

Base="1000.000000" Impuesto="002" TipoFactor="Exento"

**Comment by RigoFlores** [comment]
Me están preguntando de este tema... ya tiene una semana que se reportó.

**Comment by jccastillo0007** [comment]
Ups... ya estaba desde el miércoles...

**Comment by RigoFlores** [comment]
hay que llevarlo a producción.
Pls súbelo, ya que la cliente está presionando.
