### ISSUE TITLE
Alteza - tomar como ID el campo Folio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2177]
Hoy tuve reunión con ellos.
Y el número irrepetible en su operación es el campo Folio y no el que actualmente estamos tomando, es decir el campo Ppers5.

Para identificar de manera única el ticket, debe ser el Folio y el total con propina (este último, ya lo tenemos así).
Otra cosa, es que un archivo = 1 factura. Ya no tenemos que discriminar en un archivo que si se factura y que no. Se factura todo el contenido y punto (tal como está ahora mismo).

Otro punto importante, es que ese Folio, será el que se incluya en la factura, es decir, nosotros no llevaremos el consecutivo.
Lo tomaremos del archivo. La serie, igualmente podríamos tomarla de ahí.

Ejemplo:
Serie         A
Folio         19958

**Comment by jccastillo0007** [comment]
Utilizar el folio como id, esta fácil... 
Utilizar la serie indicada en el archivo, y quitar todas las validaciones que se hacen para el manejo consecutivo del folio / serie, no esta tan fácil.... estoy viendo como respetar el folio, pero la serie es mejor la que se obtiene del sistema DT, eso se puede ?

**Comment by RigoFlores** [comment]
Creo que en esta ocasión se puede manejar así como dices. Ya que se trata de un solo hotel.
Pero cuando el mismo RFC tiene varios hoteles, ocupan una serie para cada hotel.

**Comment by RigoFlores** [comment]
Y según ellos, este sería el primero de varios... claro, vamos al paso.
Pues ahora entonces si, podemos tomar la serie DT o FI

**Comment by jccastillo0007** [comment]
Done... si se pudo respetar también la serie del archivo...

Debes volver a subir archivos para que te funcione.
