### ISSUE TITLE
Complemento de pago a varias facturas, no reporta correctamente el ImporteP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2178]
Cuando un complemento de pago, incluye varias facturas, en el nodo de ImpuestosP, no se reporta correctamente el ImporteP.
Por ejemplo, en pru... rfc IIA, si pagas las facturas 556 y 557, así se reporta el ImpuestoP

                <pago20:ImpuestosP>
                    <pago20:TrasladosP>
                        <pago20:TrasladoP BaseP="3000.00" ImporteP="320.00" ImpuestoP="002" TasaOCuotaP="0.160000" TipoFactorP="Tasa"/>
                    </pago20:TrasladosP>
                </pago20:ImpuestosP>

Ese 320.00 reportado en ImporteP, corresponde a la segunda factura de las 2 que se intenta pagar.

es decir, no está sumando el Impuesto de todas las facturas, solo de la última.

OJO, esto ya funcionaba y muy bien. Hay que revisar con mucho cuidado la corrección que se hizo para el complmento de pago con IVA exento, ya que fue cuando se subió esta corrección, que se presentó esta problemática.

**Comment by jccastillo0007** [comment]
fixed
