### ISSUE TITLE
Alteza - Generar un reporte cvs de los tickets no facturados en un rango de fecha

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2179]
Por lo pronto, que indique:
ID
Total
Fecha

Ya daré mas detalle de los campos,  pero la logística de identificación de tickets no facturados, que ya se tenga lista.
.
Este reporte será parte de las facilidades de la  plataforma de facturación para receptores (plataforma de autofacturación).

**Comment by jccastillo0007** [comment]
Para receptores o emisores ?
"Este reporte será parte de las facilidades de la plataforma de facturación para receptores"

**Comment by jccastillo0007** [comment]
Ese reporte ya se genera en eFacturaT, que saquen el reporte de Remisiones...
Una vez que lo exporten a csv, que filtren las pagadas y listo

**Comment by RigoFlores** [comment]
checaré si eso les sirve.
