### ISSUE TITLE
ERP - NO JALA DONATARIAS, PROBÉ CON PEI950612354

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#218]
Facturación

cvc-complex-type.4: Attribute 'version' must appear on element 'donat:Donatarias'.cvc-complex-type.4: Attribute 'noAutorizacion' must appear on element 'donat:Donatarias'.cvc-complex-type.4: Attribute 'fechaAutorizacion' must appear on element 'donat:Donatarias'.cvc-complex-type.4: Attribute 'leyenda' must appear on element 'donat:Donatarias'.cvc-complex-type.4: Attribute 'version' must appear on element 'donat:Donatarias'.cvc-complex-type.4: Attribute 'noAutorizacion' must appear on element 'donat:Donatarias'.cvc-complex-type.4: Attribute 'fechaAutorizacion' must appear on element 'donat:Donatarias'.cvc-complex-type.4: Attribute 'leyenda' must appear on element 'donat:Donatarias'. (301) 

PUEDES PROBAR CON PEI950612354

**Comment by RigoFlores** [comment]
también con el otro usuario de donatarias puede ser... tampoco jala...AQI970421LG5

**Comment by jccastillo0007** [comment]
Fixed.
