### ISSUE TITLE
Hacer la Personalización de Plataforma de Alteza: logo, nombre comercial y datos de contacto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2180]
Aquí te dejo el logo.

<img width="65" alt="logoAlteza" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/6df58196-7ca0-40b5-b771-8159bcbed665">

Nombre: Hotel Alteza Polanco

Contacto: Teléfono +52 556 724 0133  eMail: reservaciones@altezapolanco.com

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
ok, quizá haya que cambiar el color azul. Ya lo veré.
El color de fondo gris, ese si lo mantendremos.
