### ISSUE TITLE
Personalización Alteza - colores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2181]
De acuerdo a los colores actuales de su factura (ya personalizada por cierto), cambiar este parámetro del css:

--azulprincipal: #3399D1;

a

--azulprincipal: #841E;

Es para el color del header y del footer

ya no será azul, pero para no cambiarle tanto, será un azul camuflajeado de oro, jeje

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Me piden el cambio que el color del header y footer sea negro. Hay que volver a cambiar la variable arriba mencionada a black;

asimismo el cambio de logo, por este que anexo.
Pls.

[altezaLogo.png.txt](https://github.com/jccastillo0007/eFacturaT/files/12030869/altezaLogo.png.txt)

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
ok, hay que llevarlo a Pro...

**Comment by RigoFlores** [comment]
si, ya quedó bien.
Solo que ahora al ser el fondo negro, en la pantallas cuando accedes con usuario y pwd, el ícono de home y de salir, son negros y ya no se ven. 
Favor de ponerlos en color blanco.

**Comment by jccastillo0007** [comment]
son iconos que me pasaste, habrá que buscar unos en color blanco

**Comment by jccastillo0007** [comment]
done

Aún no esta listo, no se ven bien los iconos

**Comment by jccastillo0007** [comment]
puedes buscar unos que se vean bien

**Comment by jccastillo0007** [comment]
ya encontré unos iconos y me parece que se ven bien

**Comment by RigoFlores** [comment]
creo que les falta su tooltip, no?
