### ISSUE TITLE
Complemento de pago a factura con solo IEPS, no lo procesa chido

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2183]
Esta factura solo tiene IEPS.
Pero en el complemento de pago, lo reporta como IVA en la sección de totales.

FACTURA:  Rfc="MFB170321TS0"  FOLIO 512

[pagoSoloIEPS.txt](https://github.com/jccastillo0007/eFacturaT/files/11919898/pagoSoloIEPS.txt)

EN LA SECCIÓN DE TOTALES NO SE REPORTA EL IEPS TRASLADADO. 
SOLO CUANDO EL IEPS ES RETENDIDO.
TONS, ENTIENDO QUE EN ESTE CASO, NO SE DEBE REPORTAR NINGÚN IMPUESTO EN LA SECCIÓN DE TOTALES.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
En el nodo totales del pago se debe omitir el IEPS trasladado. 
Lo que si se incluye en los totales es el IEPS retenido. Algo raro, no?
A nivel totales, se reportan retenciones de IVA, ISR e IEPS.
También se reportan los Traslados de IVA en sus distintas tasas (excepto el exento, donde solo se reporta la base).

A nivel de los nodos impuestoDR e ImpuestoP, si se reportan los traslados de IVA, ISR o IEPS.
Entonces ahora mismo la aplicación está generando lo siguiente, es decir el ImpuestoP vacío, y marca error.



    <cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="601" UsoCFDI="CP01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago" ValorUnitario="0" Importe="0" ObjetoImp="01"/>
    </cfdi:Conceptos>
    <cfdi:Complemento>
        <pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="14266.80"/>
            <pago20:Pago FechaPago="2023-07-04T06:44:52" FormaDePagoP="03" MonedaP="MXN" Monto="14266.80" NumOperacion="fact 563" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="563" IdDocumento="E68FE366-B7E3-53FD-968B-68851C744CA3" ImpPagado="14266.80" ImpSaldoAnt="14266.80" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="1" ObjetoImpDR="02">
                    <pago20:ImpuestosDR>
                        <pago20:TrasladosDR>
                            <pago20:TrasladoDR BaseDR="13210.00" ImporteDR="1056.80" ImpuestoDR="003" TasaOCuotaDR="0.080000" TipoFactorDR="Tasa"/>
                        </pago20:TrasladosDR>
                    </pago20:ImpuestosDR>
                </pago20:DoctoRelacionado>
                <pago20:ImpuestosP/>
            </pago20:Pago>
        </pago20:Pagos>
    </cfdi:Complemento>
</cfdi:Comprobante>
