### ISSUE TITLE
Alteza, nos solicitan un cambio para identificar el ticket.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2186]
Buenas tardes
Rigoberto

El motivo del presente correo es para comentarte y solicitarte que la validación de la emisión de la factura desde la APP sea por medio del numero de factura y el numero de la reservación, estos datos son únicos y nunca se van a repetir, en vez de que sea la validación por el numero de factura y su total, esto para que no haya confusión por parte del cliente al momento de ingresar el total de la factura ya que como lo mencionaste en la conferencia pasada, que es diferente el total a pagar que el total de la factura.

Te brindo una imagen referencia de los datos a tomar en la validación

![image](https://github.com/jccastillo0007/eFacturaT/assets/2912775/3273462d-838b-44a6-a09b-a069553db195)

**Comment by RigoFlores** [comment]
Si el guión no se puede incluir, entonces eliminemos el "-1" que está al final.

**Comment by jccastillo0007** [comment]
no es suficiente con el folio ?

en donde se guarda el Ppers5?

**Comment by RigoFlores** [comment]
El acuerdo es que no sea solamente con el folio, sino con el otro dato.
No se si se guarda ese dato, pero corresponde al datoExtra9

**Comment by jccastillo0007** [comment]
done... si quedo con el dato completo Ppers5, es importante que sea el Ppers5 y no le cambien el nombre...

Esta en PRU para que lo pruebes... ya que este todo bien, cambio el rfc

**Comment by RigoFlores** [comment]
OK, si quedó.
Lo que no entendí porqué el cambio de RFC depende de la corrección.
Seguramente necesitaremos un RFC de Alteza para pru y el otro que es de pro. Para pruebas, para validación, etc.
O ya con tantos sabores, quizá ya sea conveniente poner el rfc emisor, para que con base a ese RFC, se tenga un comportamiento específico.
