### ISSUE TITLE
Web - No está enviando la descripción de régimen fiscal del receptor al PDF.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2187]
Solo aparece la clave del régimen en el PDF.
Se requiere enviar la descripción también. Por ejemplo:

**_601. General de Ley Personas Morales_**

**Comment by jccastillo0007** [comment]
fixed. probado con una factura

**Comment by RigoFlores** [comment]
ok, validado en pru...
falta llevarla a pro...
