### ISSUE TITLE
Alteza, no está tomando los archivos con la extensión solicitada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2188]
Ellos generan los textos con extensión .spf y no los está tomando.

**Comment by RigoFlores** [comment]
aquí el archivo facturat.log, en un intento por procesar o identificar el archivo...

[FacturaT.log](https://github.com/jccastillo0007/eFacturaT/files/12054021/FacturaT.log)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
De alguna manera ya los identifica, pero ahora marca este error. Recordar que el receptor, aunque se incluye en el archivo de texto, es ignorado, ya que en la plataforma se asignarán los datos del receptor.

[FacturaT.log](https://github.com/jccastillo0007/eFacturaT/files/12061399/FacturaT.log)

[archivosEjemplo.txt](https://github.com/jccastillo0007/eFacturaT/files/12061404/archivosEjemplo.txt)

**Comment by RigoFlores** [comment]
y este issue, detiene la validación de los otros issues reportados ya como corregidos.

**Comment by jccastillo0007** [comment]
hay que usar el rfc de producción, el standalone puede en un momento dado soportar mas de un rfc, pero el servidor de timbrado, solo respeta el rfc de producción

**Comment by RigoFlores** [comment]
Pasó justo lo que comenté anteriormente.
Optibelt, tiene su rfc de pruebas y de producción.
Abastos, pues seguramente tiene o tuvo en su momento igual para ambos ambientes.
Siempre has mencionado que las pruebas no se hacen en producción, y este cambio nos ha costado 3 días de retraso.

Bueno, pues validaré en producción, ni pex.
