### ISSUE TITLE
ERP - NOMINA EMPRESARIAL E INDIVIDUAL (ENVIAR EMAIL DE ACUERDO A LA CONFIG)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#219]
RESPETAR LA CONFIGURACIÓN DE ENVIAR POR CORREO AL EMISOR Y RECEPTOR, YA QUE AHORA MISMO AUNQUE CAPTURES EL CORREO EN EL EMPLEADO, NO LO ENVÍA, AÚN CUANDO LA CONFIGURACIÓN ASÍ LO INDIQUE.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
SOLO LO ENVIA EN EL CASO INDIVIDUAL, EN EL CASO EMPRESARIAL NO LO ESTÁ ENVIANDO

**Comment by jccastillo0007** [comment]
Jajaajaja, ahora si lo descubriste justo antes de que lo arreglará, hasta pensé que te iba a ganar.

**Comment by RigoFlores** [comment]
HICE LA PRUEBA AHORA MISMO, Y SOLAMENTE LO ENVÍA AL EMISOR, AUNQUE LA CONFIGURACIÓN INDICA SIEMPRE ENVIAR AL RECEPTOR Y EMISOR.
EL EMPLEADO (RECEPTOR), SI TIENE CAPTURADO UN CORREO CORRECTO, PERO NO LO ENVIÓ.

**Comment by RigoFlores** [comment]
SOLO LO ENVIA AL EMISOR, CUANDO SE TRATA DE NOMINA EMPRESARIAL

**Comment by FraQue0693** [comment]
Listo, se subieron  cambios al proyecto donde se resuelve este issue #219, para que lo subas en pruebas JC.
