### ISSUE TITLE
Cambiar imagen y liga en la pantalla de acceso a la plataforma de facturación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2190]
Vamos a promover con nuestros clientes la plataforma de autofacturación.

![plataformaAutofacturacion](https://github.com/jccastillo0007/eFacturaT/assets/2912775/3921400b-4ce7-4699-b17a-3a9af9966618)

Esta es la liga, cuando le den click en la imagen:

https://www.facturat.com/plataforma-de-autofacturacion/

**Comment by jccastillo0007** [comment]
done
