### ISSUE TITLE
Alteza - domicilio del emisor ¿de donde lo toma? , manda caracteres raros en los acentos y omite un dato.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2191]
En el archivo de texto viene el domicilio del emisor.
Entiendo que de ahí toma los datos, pero no los envía completos al PDF.
Falta el número exterior.

Por otro lado, el estado que viene como "Ciudad de México", lo manda algo chueco, así "MÁ@xico"

Yo considero que para evitar estos problemas, ¿no sería mejor tomar el domicilio emisor de la llave de Factura-T?

**Comment by jccastillo0007** [comment]
} else if (line.startsWith("ENombre")) {
				cfd.setSourceName(line.substring(14, line.length()));
			} else if (line.startsWith("ECalle") && line.length() > 15) {
				cfd.setSourceStreet(line.substring(14, line.length()));
			} else if (line.startsWith("ENoext") && line.length() > 15) {
				cfd.setSourceNoExt(line.substring(14, line.length()));
			} else if (line.startsWith("EColon") && line.length() > 15) {
				cfd.setSourceNeighborhood(line.substring(14, line.length()));
			} else if (line.startsWith("EMunic") && line.length() > 15) {
				cfd.setSourceMunicipality(line.substring(14, line.length()));
			} else if (line.startsWith("EEdo") && line.length() > 15) {
				cfd.setSourceState(line.substring(14, line.length()));
			} else if (line.startsWith("EPais") && line.length() > 15) {
				cfd.setSourceCountry(line.substring(14, line.length()));

**Comment by jccastillo0007** [comment]
si sería mejor tomarlo de la llave, me avisas cómo debe quedar

**Comment by RigoFlores** [comment]
Pues, para evitar el error del acento, yo creo que lo tomamos de la llave.

**Comment by jccastillo0007** [comment]
DONE

**Comment by RigoFlores** [comment]
No está enviando al PDF el NoExteriorFiscal.

**Comment by jccastillo0007** [comment]
psss no puedo probar por el rfc ... chiaaaa, debo hacer algo para que funcione...

sabes si el no. ext esta en la llave de facturat? recuerda que ya se toman de ahí.

**Comment by RigoFlores** [comment]
Si, es un problema no tener el ambiente de pruebas.
Pero bueno, el punto es que si, de la llave se toma el domicilio fiscal completo.

**Comment by jccastillo0007** [comment]
si se esta enviando el num ext desde la llave, hay que asegurar que lo tenga

**Comment by RigoFlores** [comment]
Este es el nombre de la variable **_NoExteriorFiscal_**, si lo manda?
Yo vi que iba vacío.

**Comment by jccastillo0007** [comment]
según el código si
