### ISSUE TITLE
Alteza, formatear como números estos 2 datosExtra para el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2192]
Algunos de los datos extra, son importes dentro del PDF.
AL PDF todo llega como string.

Sin embargo piden que formateemos estos datos como número, es decir con separador de miles (solo cuando sea necesario).
Yo le busqué si existe alguna máscara en el Jasper, pero al parecer para string no es tan fácil.

DatoExtra1 y DatoExtra3

la petición es formatearlos como importes, es decir punto decimal, 2 decimales y separador de miles, o millones, y el signo de pesos.

**Comment by jccastillo0007** [comment]
hay que volver a importar archivos con el conector nuevo

**Comment by RigoFlores** [comment]
no los procesó, marca error. 
Aquí estoy subiendo 2 archivos de ejemplo y el facturat.log

[ERROR_C33_NPG_20961.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/12059140/ERROR_C33_NPG_20961.spf.txt)

[ERROR_C33_NPG_19958.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/12059141/ERROR_C33_NPG_19958.spf.txt)


[FacturaT.log](https://github.com/jccastillo0007/eFacturaT/files/12059144/FacturaT.log)

**Comment by jccastillo0007** [comment]
fixed
