### ISSUE TITLE
Alteza - no envía al PDF la descripción del régimen emisor, ni receptor.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2193]
Solamente está enviando la clave de los regímenes al PDF.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
esto implica actualización del código del conector?
Me parece que es solo web, no?

Ellos ya están digamos en producción... en cualquier momento inician con sus facturación.

**Comment by jccastillo0007** [comment]
correcto, solo en el servidor, avísame si quieres que lo suba... voy a tener todo listo

**Comment by RigoFlores** [comment]
Si, hay que subirlo a producción, ya que no tengo forma de probar en pru para Alteza.
Tendré que validarlo ahí.

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
OK, en cuanto hagan la primera factura.
Hoy intentaron, y creo que hubo un tema de falla de comunicación y no llegó el archivo a la carpeta correspondiente.
