### ISSUE TITLE
En el complemento de pago, la baseDR no coincide con la base de la factura original

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2195]
Tenemos el caso de este cliente.
Tiene un documento de pago, que ampara 3 facturas.
Pero la base y el importe del IVA, no coincide con las facturas.

De hecho solo varía 1 centavo, pero la cliente está haciéndola de a pedo.
Hay algo que impida que coincidan las bases y los importes de IVA?

[documento de pago.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/12090015/documento.de.pago.zip.txt)

**Comment by RigoFlores** [comment]
Yo creo que ya tenemos que pensar en que la base y los importes de impuestos, al momento de timbrar, se almacenen en un tabla. Si se toma el UUID como llave, se podrían agregar las bases y los importes de impuestos.
Con ese se consultan durante la emisión del documento de pago.

**Comment by jccastillo0007** [comment]
ya no están disponibles las facturas para probar, chiaaaa
