### ISSUE TITLE
Las Barricas, cuando no incluye ningún impuesto a nivel concepto, no debe incluir el nodo impuestos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2197]
Esto es parte de un XML timbrado, sin impuestos. Los 3 primeros productos, no llevan impuesto.
El cuarto si.

       <cfdi:Concepto Cantidad="3.00" ClaveProdServ="50202704" ClaveUnidad="XBO" Descripcion="JUGO DEL VALLE NECTAR DURAZNO 413 ML" Importe="36.000000" NoIdentificacion="032239052017" ObjetoImp="01" Unidad="BOT" ValorUnitario="12.000000"/>
        <cfdi:Concepto Cantidad="4.00" ClaveProdServ="50202301" ClaveUnidad="XBO" Descripcion="BONAFONT NATURAL 1500 ML" Importe="60.000000" NoIdentificacion="758104000159" ObjetoImp="01" Unidad="BOT" ValorUnitario="15.000000"/>
        <cfdi:Concepto Cantidad="4.00" ClaveProdServ="50202310" ClaveUnidad="XBO" Descripcion="AGUA MINERAL PE�AFIEL 1000 ML" Importe="48.280000" NoIdentificacion="7501073830028" ObjetoImp="02" Unidad="BOT" ValorUnitario="12.070000">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="48.280000" Importe="7.72" Impuesto="002" TasaOCuota="0.160000" TipoFactor="Tasa"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>

Según dice Eusebio, este lo timbró con la versión anterior, pero con la nueva versión (la corrección de la Ñ), le está incluyendo el nodo de impuestos vacío.

Este XML se timbró con este archivo de texto que anexo.
Cuando intento timbrar este archivo de texto, al XML le incluye uno nodo de impuestos vacío, y ahí marca error, que no debe existir ese nodo vacío.

        <cfdi:Concepto ClaveProdServ="50202801" NoIdentificacion="810990001112" Cantidad="1.00" ClaveUnidad="XCX" Unidad="LATA" Descripcion="CALAHUA CREMA DE COCO LATA 480 GR" ValorUnitario="3228.980000" Importe="3228.980000" ObjetoImp="01">
            <cfdi:Impuestos/>

[LVF002808.txt](https://github.com/jccastillo0007/eFacturaT/files/12155714/LVF002808.txt)

Entonces, el que si timbró, y cuando no lleva impuestos, simplemente no incluye el nodo.
Pero con la última versión, le está intentando incluir un nodo de impuestos vacío.  **_"<cfdi:Impuestos/>"_**

OJO, es a nivel concepto.

**Comment by RigoFlores** [comment]
Para reproducir el problema de Las Barricas, pues solo hay que procesar el archivo de texto que subí, y te generará el error.
Esta es la llave de las barricas.

[facturaT_XIQB891116QE4.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/12166602/facturaT_XIQB891116QE4.cfdi.txt)

**Comment by RigoFlores** [comment]
En el archivo de texto, estos son los productos que no contienen impuestos:

concepto={50202704|032239052017|3|XBO|BOT|JUGO DEL VALLE NECTAR DURAZNO     413 ML||12.00|36.00|||||Traslados[11.64|02|Tasa|||36.00|003|Tasa||]Retenciones[|||||||||]extradata[|24||12.00||36.00||Extra4||Extra5]}

concepto={50202301|758104000159|4|XBO|BOT|BONAFONT NATURAL                 1500 ML||15.00|60.00|||||Traslados[11.64|02|Tasa|||60.00|003|Tasa||]Retenciones[|||||||||]extradata[|1||15.00||60.00||Extra4||Extra5]}

concepto={50202801|810990001112|1|XCX|LATA|CALAHUA CREMA DE COCO LATA        480 GR||3228.98|3228.98|||||Traslados[25.00|02|Tasa||||003|Tasa||]Retenciones[|||||||||]extradata[|24||3228.98||3228.98||Extra4||Extra5]}

concepto={50202304|7501013122138|1|H87|PZA|JUGO JUMEX NARANJA               1000 ML||21.00|21.00|||||Traslados[20.70|02|Tasa|||21.00|003|Tasa||]Retenciones[|||||||||]extradata[|12||21.00||21.00||Extra4||Extra5]}

**Comment by jccastillo0007** [comment]
oye me pasas los nuevos certificados de finkok, para los rfc de pruebas

**Comment by RigoFlores** [comment]
[CSDsDePrueba.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/12167668/CSDsDePrueba.zip.txt)

**Comment by jccastillo0007** [comment]
fixed... versión 13.0.6
no ma..... ya se me están cuatrapeando las versiones.
