### ISSUE TITLE
CxP - Crear Catálogo de Servicios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2198]
Con los siguientes campos:

ID (nombre corto - Alias) - es llave, no se puede repetir.
Descripción del Servicio
Comentarios.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Algunos puntos pendientes:
1) No funciona el eliminar dentro del catálogo.
2) Mover este catálogo al menú de catálogos.
3) En el catálogo de proveedores, no se despliega al lista con el contenido del catálogo de servicios.

**Comment by jccastillo0007** [comment]
done

El punto 3 es parte del otro ticket

**Comment by RigoFlores** [comment]
Oye, solo falta renombrar el menú...
DIce "Catálogo de Servicios"...
Debe decir solo "Servicios", ya que ahí todos son catálogos...

**Comment by jccastillo0007** [comment]
done.. lo puedes probar hasta mañana
