### ISSUE TITLE
CxP - Ajustes a Catálogo de proveedores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2199]
Agregar los siguientes campos al catálogo de proveedores:

ID proveedor (nombre corto, alias). No se debe repetir.
Régimen fiscal. (tomado de la lista del SAT)
Servicio, ( se elegirá del nuevo catálogo de servicios).
Ocultar el botón de crear cuenta para este proveedor. Ya más adelante posiblemente se habilite, pero como un módulo adicional, que es justo para proveedores.

Quitar los campos de:
Localidad
Referencia
Saldo inicial

Los campos obligatorios son: ID, Nombre, Servicio

**Comment by jccastillo0007** [comment]
DONE.  ID proveedor (nombre corto, alias). No se debe repetir.
DONE.  Régimen fiscal. (tomado de la lista del SAT)
YA EXISTE ESTE CAMPO.  Servicio, ( se elegirá del nuevo catálogo de servicios).
DONE. Ocultar el botón de crear cuenta para este proveedor. 

Quitar los campos de:
DONE.  Localidad
DONE.  Referencia
DONE.  Saldo inicial

**Comment by RigoFlores** [comment]
Comentarios:
El ID sería el primer campo, entonces se muestra a la izquierda del RFC (invertir su colocación entre ambos).
El ancho del nombre y régimen, que sean iguales, para que se vea mas ordenada y pareja la pantalla.

Ya solo queda pendiente que el campo servicio, se tome de una lista. Esa lista, precisamente es el nuevo catálogo solicitado (issue 2198)..

**Comment by jccastillo0007** [comment]
El ancho del nombre se define de acuerdo a lo que ingresaron... si tienen nombres muy largos, el campo se ajusta.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Existen 2 campos llamados servicio.
Solo se debe mantener uno, y es con la lista del catálogo de servicios.

**Comment by jccastillo0007** [comment]
done.
Lo puedes probar hasta mañana
