### ISSUE TITLE
OBTENER FACTURA GENERADA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#22]
PARA OBTENER UNA FACTURA GENERADA:
A) CONFIGURAR EL DIRECTORIO DONDE SE DESCARGARÁ DE MANERA AUTOMÁTICA (EN CASO DE EXISTIR DICHO PARÁMETRO)
B) CONFIGURAR LA CUENTA DE CORREO DONDE LO ENVIARÁ POR OMISIÓN (EN CASO DE EXISTIR DICHO PARÁMETRO)
C) ENVIAR POR CORREO AL CLIENTE (OPCIONAL A ELECCIÓN DEL USUARIO)
D) ESTABLECER UN REPOSITORIO DE LA TÍA POR CLIENTE, DONDE SE ALMACENARÁN LOS ÚLTIMOS 3 MESES (MAS EL ACTUAL), LOS XML Y PDF
E) DESDE LA CONSULTA SE PODRÁ OBTENER LOS ARCHIVOS (EN COMBINACIÓN CON INCISO D)

YA QUE AL MOVERSE DE LA PANTALLA DE FACTURACIÓN, YA NO ES MUY CLARO COMO OBTENER LA FACTURA

**Comment by jccastillo0007** [comment]
La opcion A no aplica....   no podemos descargar y salvar en disco automaticamente, forzosamente deben dar click en el link

La opcion B se hace en el catalogo de clientes
La opcion C se resuelve en la pantalla de la factura
La opcion D ya esta implementada (faltaria solo la depuracion de cada 3 meses)
La opcion E ya esta implementada.

**Comment by RigoFlores** [comment]
LA OPCIÓN B SE REFIERE A QUE SIEMPRE ENVÍE LAS FACTURAS A UN CORREO DEL EMISOR. 
ES DECIR QUE NUESTROS CLIENTES, NOS INDIQUEN SI DESEAN QUE CADA FACTURA GENERADA, LA ENVÍE A UNA CUENTA DE CORREO DE ELLOS. 
ESTA CUENTA DE CORREO ES INDEPENDIENTE AL CORREO DEL RECEPTOR DE LA FACTURA.
OPCION C, D Y E OK.

**Comment by jccastillo0007** [comment]
OK got it.

Se implemento la opcion de "Enviar email al emisor", para que funcione, el emisor debe tener al menos un email dado de alta en la base de datos, actualmente no existe opción para modificar los correos del emisor, unicamente al crear la llave.

Hay que generar una opcion en el menu de administracion.

**Comment by RigoFlores** [comment]
POR LO PRONTO CERRARÉ ESTE ISSUE, PERO EL TEMA REAL, ES QUE EL EMISOR PUEDA DEFINIR EN CONFIGURACIÓN SU CORREO, Y ADEMÁS SI POR OMISIÓN QUIERE RECIBIR TOOOOODAS LAS FACTURAS.
HOY PUEDE HACERLO, SOLO FACTURA POR FACTURA. ASI LO DEJAMOS POR LO PRONTO.
