### ISSUE TITLE
ERP - NOMINA - CONSULTAS NO FILTRA POR NOMBRE O RFC DE EMPLEADO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#220]
NO PERMITE FILTRAR POR RFC O NOMBRE DE EMPLEADO, YA QUE NO LOS MUESTRA EN EL LISTADO COMO CLIENTES. 
DEBE PERMITIR FILTRAR POR RFC O NOMBRE LOS RECIBOS DE NÓMINA

**Comment by jccastillo0007** [comment]
Done... se agrego un combo con los RFC de los empleados.
