### ISSUE TITLE
CxP - Crear pantalla "Capturar Crédito"

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2200]
El menú se llamará, "Captura Crédito". Esta pantalla servirá para capturar una nueva cuenta por pagar. Puede o no, estar respaldada por un CFDI.

Se elimina el menú de Compras - Registrar CFDI y el de Egresos. En su lugar, quedará esta pantalla.

Campos a capturar (* obligatorios):

* Fecha
* ID Proveedor  (tomado del catálogo de proveedores).
Serie (por default EGRESO. Para el caso de registrar CFDI, la serie se toma de ahí. Si no se registra CFDI, entonces la serie será EGRESO).
* ID Documento
* Fecha a Pagar
Comentario
* Importe

Opcional, "Cargar Evidencia". Puede ser una imagen (jpg, png), un PDF o un CFDI. 

Si cargan el CFDI, en automático se llenarán los campos de: 
Fecha: fecha de emisión
ID Documento: folio
Serie: Serie
Valor: Total

La combinación Serie-ID documento, identificarán de manera única un crédito.

**Comment by jccastillo0007** [comment]
checa lo que se tiene ahorita... creo que ya esta...

**Comment by RigoFlores** [comment]
Si tiene algunos detalles.
Se solicitó que se capture por ID proveedor, y no por el nombre del proveedor.
Pero bueno, creo que buscar por una opción o la otra, está mejor. Es decir, que se elija al proveedor ya sea por ID o por nombre, ordenadas ambas listas alfabéticamente.

La etiqueta debe ser  "Fecha a Pagar", en lugar de "Fecha de Pago"

La etiqueta es "Subir Evidencia", en lugar de "Subir archivos". 

Una vez que un archivo se subió, se debe mostrar en pantalla de alguna manera (por su nombre, un ícono de archivo, etc).


Cuando se cargue un CFDI (XML), se deben llenar en automático los campos de:

Fecha: fecha de emisión
ID Documento: Corresponde al folio. Si el XML no contiene folio, entonces sería el UUID.
Serie: Serie  (dato opcional en el CFDI;  en caso que no se incluya, pues quedaría vacío).
Valor: Total

**Comment by jccastillo0007** [comment]
**Okas, listo esta parte :**
Pero bueno, creo que buscar por una opción o la otra, está mejor. Es decir, que se elija al proveedor ya sea por ID o por nombre, ordenadas ambas listas alfabéticamente.

La etiqueta debe ser "Fecha a Pagar", en lugar de "Fecha de Pago"

La etiqueta es "Subir Evidencia", en lugar de "Subir archivos".

**Estoy ya esta listo:**
Una vez que un archivo se subió, se debe mostrar en pantalla de alguna manera (por su nombre, un ícono de archivo, etc).

**Para esto, hay que darle click en la lupa:**

Cuando se cargue un CFDI (XML), se deben llenar en automático los campos de:

Fecha: fecha de emisión
ID Documento: Corresponde al folio. Si el XML no contiene folio, entonces sería el UUID.
Serie: Serie (dato opcional en el CFDI; en caso que no se incluya, pues quedaría vacío).
Valor: Total

**Comment by RigoFlores** [comment]
Todo lo veo igual (sin corrección), excepto que se llena **el total y la fecha cuando se le da click en la lupa**. Lo demás reportado como corregido, no está listo. No se está llenando la serie ni folio. Estaba pensando y creo que será mejor que no se llene la serie y folio a partir del XML. Para toda evidencia subida, la serie será  EGRESO, y el folio deberá ser consecutivo. Así evitamos el cagadero de que al subir XML de distintos proveedores, se mezclen series y folios de todo tipo.

Lo que si podemos hacer, es que en comentarios, para un XML se agregue "Serie: Folio: UUID: " del XML, así en en una sola cadena, pera tener una referencia del XML en cuestión.

**Comment by jccastillo0007** [comment]
aguanta, no lo he subido, chiaaa

**Comment by jccastillo0007** [comment]
listo, ya puedes ver los cambios

**Comment by RigoFlores** [comment]
Si hace lo que se había pedido antes, sip.

Lo que pasó, es que comentaba que quizás será mejor nosotros llevar el control de la serie y folio.
Serie: EGRESO
Folio: el consecutivo. (para cada crédito que se de de alta).

Entonces cuando se le da en la lupa a un XML, lo que se llenará será la fecha, el total y el comentario, donde comentario será igual a "Serie:   Folio:   UUID:  " con los datos que corresponda.
Así podremos tener una mejor administración de los documentos ordenados por folio.
Cómo ves? Se que había pedido otra cosa, pero así podremos buscar todos los egresos de una manera mas ordenada.

**Comment by RigoFlores** [comment]
Por cierto, si no capturas archivo manda un mensaje que el "archivo es incorrecto", y recordemos que el archivo es una evidencia opcional.

Y si capturo el XML y le doy en la lupa, y trato de guardarlo, marca internal error.

**Comment by RigoFlores** [comment]
Con un archivo PDF, no marcó error. Dijo que lo guardó exitosamente.

Entonces, en resumen hay que corregir lo de:

La serie de cada crédito capturado será EGRESO
El folio, será consecutivo controlado internamente.
El archivo es opcional, no es obligatorio. (ahorita como que lo busca a juerza)
Cuando el archivo es un XML, se llena la fecha, el total y comentario (con el folio, serie y uuid).

**Comment by jccastillo0007** [comment]
fixed.

Si te marca error en el xml, hay que revisar que sea 4.0, y si no funciona, agregarlo aqui.

**Comment by RigoFlores** [comment]
marca crédito duplicado, cuando intento capturar un crédito, ya sea sin archivo, con PDF o con XML.

**Comment by jccastillo0007** [comment]
esa es la combinación serie  + id documento...

**Comment by RigoFlores** [comment]
Si, está bien que valide ello, pero el mismo sistema debe incrementar el contador, jaja.

¿Ahora, en caso de un problema, no incrementará el contador y se podría generar una condición de error que ya no permita avanzar?

**Comment by jccastillo0007** [comment]
lo de incrementar el folio, se acaba de implementar chiaaa

no, no se incrementa el contador, a menos que sea exitoso

**Comment by RigoFlores** [comment]
OK, para el caso del XML, ya vi que valida que el nombre del emisor sea igual al nombre del proveedor.
No se solicitó, pero lo dejamos. Podría ayudar.
