### ISSUE TITLE
CxP - Ingresar Pago, ajustes a la pantalla

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2201]
Se capturará lo siguiente:

Esto ya existe, solo hay que reordenarlo:

Fecha de pago (ya existe)
Forma de Pago (ya existe, del catálogo del SAT)
Importe del Pago (ya existe)
Referencia (ya existe).

Para elegir el documento o documentos a pagar, se podrán seleccionar los siguientes criterios. (Ahora mismo se tienen los criterios de RFC o número de proveedor). Si eligen ID proveedor, se llenará el nombre y el servicio. Si eligen el nombre del proveedor, se llenará el ID y el servicio. Si eligen servicio, no se llenará ni nombre, ni ID, ya que el mismo servicio lo podrán ofrecer varios proveedores.

ID proveedor
Nombre Proveedor
Servicio

Y completar los filtros por los criterios ya existentes: vigencia (vigente, vencida, todas), rango de folios, rango de fechas.

NOTA: la vigencia será: Vigente cuando la fecha de pago capturada en "Capturar Crédito) sea mayor o igual a la fecha actual. Vencida, cuando la fecha de pago sea menor a la fecha actual.

Se despelgarán los resultados, indicando lo mismo que en CxC, es decir para cada documento, el saldo y el abono actual, y la columna para el saldo insoluto, podría llamarse la columna "A pagar", en lugar de cobro como aparece en CxC.

Se podrán hacer pagos totales o parciales, igualito que en CxC.
Mientras el saldo insoluto, no sea 0, se seguirán mostrando los resultados aquí como CxP.

**Comment by jccastillo0007** [comment]
Esto no es posible :
"Si eligen ID proveedor, se llenará el nombre y el servicio. Si eligen el nombre del proveedor, se llenará el ID y el servicio."

Ya que los servicios no están ligados a un proveedor en particular

**Comment by jccastillo0007** [comment]
Me falta revisar esto:
"Se despelgarán los resultados, indicando lo mismo que en CxC, es decir para cada documento, el saldo y el abono actual, y la columna para el saldo insoluto, podría llamarse la columna "A pagar", en lugar de cobro como aparece en CxC.

Se podrán hacer pagos totales o parciales, igualito que en CxC.
Mientras el saldo insoluto, no sea 0, se seguirán mostrando los resultados aquí como CxP."

**Comment by RigoFlores** [comment]
Para seleccionar el proveedor, puede ser por ID del Proveedor (el ID es único e irrepetible en el catálogo de proveedores). Entonces una vez identificado el proveedor, se puede mostrar el nombre y el servicio.

Lo mismo, si eligen por nombre, pues ese proveedor tendrá asociado un ID Proveedor y el Servicio correspondiente.

**Comment by RigoFlores** [comment]
Las consultas y pagos que se realicen en esta pantalla, estarán asociados a los créditos capturados en el menú Compras-Captura de Crédito.

**Comment by jccastillo0007** [comment]
**Esto no se puede, chiaaaa** 

Para seleccionar el proveedor, puede ser por ID del Proveedor (el ID es único e irrepetible en el catálogo de proveedores). Entonces una vez identificado el proveedor, se puede mostrar el nombre y el servicio.

Lo mismo, si eligen por nombre, pues ese proveedor tendrá asociado un ID Proveedor y el Servicio correspondiente.

**Los servicios no están asociados a un proveedor, entonces no hay manera de filtrarlos cuando eligen proveedor**

**Comment by RigoFlores** [comment]
Creo que estamos confundidos.
El ID del proveedor es una cosa, y el ID del servicio es otra.
Un proveedor, tiene un servicio asignado. Ese servicio, puede ser el mismo para distintos proveedores.

Lo que se pide, es que cuando se elige el proveedor, ya sea por ID o por nombre, se muestre el servicio que está prestando, eso es todo.

**Comment by jccastillo0007** [comment]
Con esto "Las consultas y pagos que se realicen en esta pantalla, estarán asociados a los créditos capturados en el menú Compras-Captura de Crédito." le diste en toda la ma... a lo que se tenía chiaaa, estoy haciendo los cambios.

**Comment by RigoFlores** [comment]
Si, es que antes estaba amarrado a los CFDI's, y eso era incorrecto.
Un crédito, es una compra, una deuda por pagar y no necesariamente está respaldado por una factura. Puede ser caja chica y con ello, ya no tiene un respaldo fiscal. Posiblemente la mayoría de los casos si tengan facturas, no lo sabemos. Pero si lo hacemos genérico, entonces ya soportaremos con y sin factura.
De ahí que los documentos anexos, sean importantes en este caso. Ya sea facturas o fotografías del gasto realizado.

Esto nos servirá más adelante para condominios, será prácticamente lo mismo.

**Comment by jccastillo0007** [comment]
fixed.

Solo me queda pendiente seleccionar el servicio asociado al proveedor... aquí tengo una duda...
No creo que un proveedor solo deba tener un servicio... pero nosotros lo estamos limitando a eso... esta bien ?

**Comment by RigoFlores** [comment]
Honestamente en este momento, no alcanzo a visualizar si nos estamos limitando por ese motivo de que un proveedor brinde un solo servicio.
Por ejemplo en TIC, telmex es proveedor de telefonía e internet.
Timbrado, los PAC nos suministran el servicio.
En un condominio, tienes proveduría de mantenimiento en general, aunque podría ser solo jardinería, plomería, albañilería, eléctrico, etc...  

Yo creo que un proveedor lo das de alta con el servicio que mejor represente lo que ofrece. Ferretería, no pues puede ofrecer un chingo de cosas, pero todo cabe dentro de ferretería. Etc, etc, etc.

Creo que nos podemos ir así de inicio, y pues que los clientes nos vayan retroalimentando.

**Comment by RigoFlores** [comment]
Pues aquí prácticamente, tienes resuelto lo de las consultas (el famoso aquel de la nieve de que sabor)...
creo que podemos agregarle también aquí, como resultado de la consulta, a la derecha de la columna a pagar, la liga para poder descargar el archivo, si es que tiene alguno asociado.

**Comment by RigoFlores** [comment]
Que pasaría si yo elijo el servicio... no se mostrará ningún ID ni nombre de proveedor.
Pero luego hago la consulta.
Y si hay facturas por pagar de ese servicio se mostrarán (de uno solo o de varios proveedores).
Y si pago alguno de los registros mostrados, pues se registra el pago, no???

es decir, pues se puede registrar un pago, aún si haber elegido el proveedor, únicamente el servicio. 
AL final, pues el pago se asocia al folio del crédito, no es así?

**Comment by RigoFlores** [comment]
Entonces, aquí está pendiente, lo de mostrar el servicio del proveedor (una vez seleccionado el proveedor).

Y también, que si se elige el servicio únicamente como filtro, que al resultado mostrado en pantalla, se pueda capturar un pago.
Incluso, si no se elige el filtro de id proveedor, nombre de proveedor o servicio. Y se busca por vigencia, rangos de fecha o folio.

**Comment by jccastillo0007** [comment]
No puedo aplicar el filtro de servicio, porque los créditos creados no están asociados a un servicio, solo a un proveedor.

**Comment by RigoFlores** [comment]
Pues yo creo que haciendo por ahí algunos cueries mágicos si se podría filtrar por servicio.
SI dices tu que no es posible, pues hay que quitarlo de los parámetros, ya no estarían dando esa función.

**Comment by jccastillo0007** [comment]
ok, ya lo quite.
