### ISSUE TITLE
CxP - Consulta de pagos, Ajustes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2202]
Se podrá consultar por la referencia del pago. El rango de fechas, por lo pronto lo podemos ocultar, ya que no se hacen consultas masivas. Mas adelante, quizás consultar por rango de fechas, por proveedor.

Al igual que en CxC, se podrá eliminar el pago capturado, si así se requiere.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
falta validar que se pueda eliminar el pago consultado, pero lo dejaré pendiente, para cuando ya se tengan datos.
Lo cerraré y en cuanto se pueda haré la prueba correspondiente
