### ISSUE TITLE
CxP - Cartera de Proveedores, ajustes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2203]
En lugar RFC o número de proveedor, se podrá buscar por ID proveedor, nombre o Servicio.
Adicional, los criterios de rangos de fecha, rango de folios y vigencia (vigente, vencida, pagada o todas).

El resultado se presentará en pantalla, y en la parte inferior un sumarizado del saldo pendiente por pagar.
Se puede exportar a excel el resultado con los siguientes campos, que son los mismos a mostrar en pantalla.

ID documento, Fecha, ID proveedor, Nombre Proveedor, Servicio, cargo, abono, saldo, vencimiento, status, referencia.

NOTA, el ID documento para los pagos será "PAGO", y estará asociado a uno o varios ID documento (igualito que en CxC). 
Referencia, solo aplicará para los pagos. No aplica para los créditos capturados (es decir las cuentas por pagar).

**Comment by jccastillo0007** [comment]
puedes generar un escenario de pruebas.. no tengo idea de como probar todo esto...

Y no entendí nada de esto:
NOTA, el ID documento para los pagos será "PAGO", y estará asociado a uno o varios ID documento (igualito que en CxC).
Referencia, solo aplicará para los pagos. No aplica para los créditos capturados (es decir las cuentas por pagar).

**Comment by RigoFlores** [comment]
OK, va de nuez.

La búsqueda debe hacerse por ID proveedor, nombre o Servicio... en lugar de los 2 campos que se tienen hoy, que es RFC o número de proveedor.
Adicionalmente, MANTENER los otros criterios para la búsqueda: rangos de fecha, rango de folios y vigencia (vigente, vencida, pagada o todas). Estos criterios YA EXISTEN AHORA. Solo se mencionan porque hay que mantenerlos.

Al realizar la consulta con los criterios capturados, se mostrará el resultado en forma similar a lo que ya se muestra ahora mismo.  Ver la imagen de abajo. Solo que en esta consulta, la mayoría de las facturas aparecen como pagadas, pero en el columna abono, no aparece el pago realizado. Falta un registro, igual que en CxC, que refleje el abono a cada factura, para que el saldo se vaya a cero cuando una factura ya está pagada.
En este resultado, falta mostrar el parte inferior de la pantalla, el sumarizado de la columna saldo, que cuando está todo bien capturado, sería lo que se tiene pendiente de pagar de esa consulta realizada.


<img width="439" alt="CxPCartProv" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/d71b1bca-4d7d-48a3-a5f1-49ce93089baf">

**Comment by RigoFlores** [comment]
Una vez presentado el resultado en pantalla, se podrá exportar a excel...
donde los campos incluidos en el reporte serán:

ID documento, Fecha, ID proveedor, Nombre Proveedor, Servicio, cargo, abono, saldo, vencimiento, status, referencia.

Incluir de ser posible, el sumarizado de la columna saldo.

**Comment by RigoFlores** [comment]
Cuando se registre un pago a una factura o a un egreso, entonces la columna clave, será PAGO.
En la imagen de arriba, NO se tiene registrado ningún pago, eso es algo que estoy analizando cómo hacerlo.

**Comment by jccastillo0007** [comment]
como se obtiene esto:
"Falta un registro, igual que en CxC, que refleje el abono a cada factura, para que el saldo se vaya a cero cuando una factura ya está pagada." 

o te refieres a que le ponga automáticamente la cantidad que pagaron ?

Para el reporte de excel... me parece que solo se pueden poner las mismas columnas que se muestran en pantalla

**Comment by RigoFlores** [comment]
Es algo muy similar, idéntico a CxC... mira este ejemplo:

<img width="530" alt="similCxC" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/2ab06359-fe9b-4891-a9c4-c5057e8190cb">


Aparece en esa consulta, la factura por un lado, y adicionalmente un registro con el cobro realizado. Se identifica por PA.

En este caso de CxP, se pide lo mismo. Primero se registra el egreso y luego el pago del mismo. A eso se refiere con que el pago se identifique con PAGO, así como en CxC es PA.

  
<img width="530" alt="similCxC" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/a670e977-f831-462d-8c69-f5971117dfa4">

**Comment by jccastillo0007** [comment]
chécale, a ver si entendí.

**Comment by RigoFlores** [comment]
Si, creo que se ve bien todo.
Excepto que falta incluir abajo, el total de los créditos, menos los pagos que se muestren en pantalla.
La idea es saber cuánto se debe, a partir de esa consulta.

**Comment by jccastillo0007** [comment]
fixed
