### ISSUE TITLE
CxP - Reporte General, ajustes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2204]
Se aplicarán los filtros de rango de fechas y de vigencia (pagada, vencida, vigente, todas).
Se generará un listado con las columnas

ID proveedor
Nombre
Total Cargos (créditos)
Total Abonos (pagos realizados)
Total Saldo

Al final mostrar la sumatoria de cada columna.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
No genera el resultado de la consulta.
Si desde el menú de cartera de proveedores, consultas a partir de la fecha 28 de julio, te arroja resultados.
Entonces, al menos esos resultados, debería presentarse en el reporte general.  (como para validar que lo está haciendo bien), pero no, no está presentando ningún resultado.

El proveedor que puedes elegir el IIA, ya que con él, hemos realizado un sin fin de pruebas.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Realmente esta es una de las últimas partes del proceso.
Por lo pronto lo cerraré, pero falta probar el flujo en sí.
Desde crear los pagos, capturarlos, etc...
