### ISSUE TITLE
Alteza - envía incorrecto la forma y el método de pago, tanto al PDF como al XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2205]
En pruebas, el RFC IIA tiene el comportamiento de alteza.
Este archivo tiene forma de pago 99 y metodo PPD.

pero lo manda fijo a 01 y PUE.

Anexo el mapeo y un archivo spf de ejemplo.

[C33_NPG_20961.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/12195680/C33_NPG_20961.zip.txt)

**Comment by jccastillo0007** [comment]
fixed
