### ISSUE TITLE
Autofacturador - cuando se genera la factura, pone el status de Pagada, en CxP.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2206]
En la plataforma de Autofacturación, cuando generas la factura de una remisión que llegó por el conector, cuando la generas, se le asigna en la tabla de CFD, el status de Pagada, para CxC y CxP también.

Si bien, cuando llega la remisión a la plataforma, ésta ya está pagada, pero es desde el punto de vista de CxC.

Entonces, la petición es que en este escenario, cuando se genera la factura desde el autofacturador, el status de CxP, no se cambie.

**Comment by jccastillo0007** [comment]
para que instancia ?

**Comment by RigoFlores** [comment]
No entendí la pregunta.
Para el RFC emisor, IIA. Cuando le pongo una remisión por conector... de Alteza.
Luego en la plataforma de Alteza, accedo con la cuenta de la TIA como receptor, y genero la factura de la remisión.

Si con la cuenta de la TIA, voy a consultar las CxP, esa factura de la prueba, aparece con status de pagada en CxC y en CxP.
Ahí es donde CxP, no debe registrarla. Solo CxC, desde la perspectiva del emisor IIA. Esa factura ya fue pagada.


Desde la perspectiva del receptor, en este caso la TIA, el status de CxP, no debe cambiarse cuando genera la factura desde el autofacturador.

**Comment by jccastillo0007** [comment]
es el descargat de alteza o de abastos ? supongo que el cambio es para ambos ?

**Comment by RigoFlores** [comment]
ahhh, lo identifiqué en Alteza, pero seguro que aplica para ambos, para todos los que usen esa plataforma... ahora solo ellos 2.

**Comment by RigoFlores** [comment]
y fíjate que realmente, el dar de alta un egreso no implicará que exista una factura involucrada.
Por ejemplo caja chica, es un egreso sin factura.
Cualquier gasto que no reciba una factura a cambio, será registrado así como egreso.
Y por ello se pide que se pueda adjuntar un CFDI, una imagen, un PDF solo como respaldo, pero no como obligatorio.

La instancia de egreso, representará una salida de dinero, pero no precisamente respaldado por un CFDI.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
no puedo validar, ya que está marcando error al buscar los tickets.
