### ISSUE TITLE
Complemento de pago por factoraje, marca error no clasificado con CFDI's externos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2207]
En pruebas para el emisor IVD, y el receptor HOME DEPOT, factura 60788.
la subí para hacer prueba de timbrar complemento de pago con factoraje de un CFDI  externo (desde la opción de subir CFDIs externos), pero al intentar timbrar el complemento de pago, lo genera con el nodo de impuestos vacío. 

    <cfdi:Emisor Rfc="IVD920810GU2" Nombre="INNOVACION VALOR Y DESARROLLO SA" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="626" UsoCFDI="CP01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111506" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago" ValorUnitario="0" Importe="0" ObjetoImp="01"/>
    </cfdi:Conceptos>
    <cfdi:Complemento>
        <pago20:Pagos Version="2.0">
            <pago20:Totales MontoTotalPagos="227.99"/>
            <pago20:Pago FechaPago="2023-08-01T15:03:41" FormaDePagoP="03" MonedaP="MXN" Monto="200.99" NumOperacion="FACT 60788" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="60788" IdDocumento="0E621180-AB15-40BE-8CE9-FE13B32488BD" ImpPagado="200.99" ImpSaldoAnt="227.99" ImpSaldoInsoluto="27.00" MonedaDR="MXN" NumParcialidad="1" ObjetoImpDR="01" Serie="4HJHHI"/>
                <pago20:ImpuestosP/>
            </pago20:Pago>
            <pago20:Pago FechaPago="2023-08-01T15:03:41" FormaDePagoP="17" MonedaP="MXN" Monto="27.0" NumOperacion="FACT 60788" TipoCambioP="1">
                <pago20:DoctoRelacionado EquivalenciaDR="1" Folio="60788" IdDocumento="0E621180-AB15-40BE-8CE9-FE13B32488BD" ImpPagado="27.00" ImpSaldoAnt="27.00" ImpSaldoInsoluto="0.00" MonedaDR="MXN" NumParcialidad="2" ObjetoImpDR="01" Serie="4HJHHI"/>
                <pago20:ImpuestosP/>
            </pago20:Pago>
        </pago20:Pagos>
    </cfdi:Complemento>
</cfdi:Comprobante>

Es decir, así:   pago20:ImpuestosP/>

Este es el XML que subí:

[TESTFACTORAJECFDISEXTERNOS.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/12234350/TESTFACTORAJECFDISEXTERNOS.xml.txt)

Creo que el issue sería que para CFDI's externos, no está guardando correctamente los impuestos, o no sé, se hace pelotas con ellos, y resulta que el complemento de pago, lo genera con el nodo de impuestos vacío.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
A ese archivo que subí le cambié el número de folio y lo intenté subir nuevamente (desde el menú de registrar CFDI's externos), pero marcó error y no lo sube.

[TESTFACTORAJECFDISEXTERNOS.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/12292337/TESTFACTORAJECFDISEXTERNOS.xml.txt)

Entonces no puedo validar la corrección.

**Comment by jccastillo0007** [comment]
no puedes usar el mismo archivo o debes cambiar el guid... porque se hace esa validación...
sourceRFC + GUID... y el archivo que estas usando ya existe, aunque ciertamente el mensaje de error esta mal.

**Comment by RigoFlores** [comment]
ok, ya le cambié el uuid, y efectivamente ya lo subió.
Ahora intento generar el complemento de pago con factoraje y marca internal error.
El folio es el 70789 y receptor la tia.

**Comment by jccastillo0007** [comment]
fixed...
