### ISSUE TITLE
No está funcionando el conector de Alteza en pruebas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2208]
Subí estos archivos, uno por uno. 3 pruebas distintas.
Desde la plataforma estándar, si aparecen las remisiones en la consultas.

Cuando le doy buscar un ticket en la plataforma de clientes (autofacturación), marca internal error.
Después vuelvo a intentar, y ya no marca internal error, pero no encuentra el ticket.

Pareciera que algo se le movió y no está jalando en pruebas...

[C33_NPG_20655.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/12251641/C33_NPG_20655.zip.txt)

**Comment by RigoFlores** [comment]
posiblemente ya con tantos tickets duplicados, ya se hace pelotas la aplicación.
Si es el caso, hay que eliminar todas las remisiones de este año para la cuenta de IIA en web...

**Comment by RigoFlores** [comment]
No, ya le cambié el número de folio a alguno de los archivo y se comportó igual.
Si hay que revisar qué está pasando

**Comment by jccastillo0007** [comment]
listo...

hay problemas de compatibilidad con efacturat v2....

Tuve que borrar todas las cfd creadas anteriormente, de todos los usuarios.

**Comment by RigoFlores** [comment]
Marca el error, porque el importe de los impuestos lo estamos reportando a 6 decimales.
Ese es un tema ya bastante viejo, que se había atendido por todos lados.
No estoy seguro si solo está reportándose nuevamente a 6 decimales para alteza únicamente o para todos.

Hay que reportar el importe de los impuestos a 2 decimales.
Anexo el XML de ejemplo donde puedes checar cómo lo reporta ahora mismo.


[valorpermitido.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/12283125/valorpermitido.xml.txt)

**Comment by jccastillo0007** [comment]
no ma... y apenas lo reportas

**Comment by RigoFlores** [comment]
Realmente aquí hay 2 temas. El primero quedó resuelto, que era el internal error.
El otro tiene poco tiempo que apareció, creo que hace 2 rilises, pero no le había hecho mucho caso, ya que en producción si jala. 
El asunto es que lo que antes jalaba, ahora ya no jala. Y tuve que apoyarme con finkok para encontrar el detalle, y justo es ese, que a partir de no se cuando, estamos reportando los impuestos a 6 decimales a nivel de concepto, con toda la problemática que esto implica, y que ya la sufrimos mucho anteriormente.

**Comment by jccastillo0007** [comment]
Ya esta arreglado el asunto de que el método de pago lo ponía como 04
