### ISSUE TITLE
ERP - NOMINA - CONSULTAS - DESCARGA MASIVA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#221]
CUANDO EN FACTURAS O NOMINA, SE REALIZA UNA CONSULTA Y SE MUESTRA EL RESULTADO EN PANTALLA, SE DEBE DAR LA POSIBILIDAD AL USUARIO DE DESCARGAR TODAS LOS CFDIS RESULTANTES DE DICHA CONSULTA.

**Comment by jccastillo0007** [comment]
Done.... cuando den click en export... se va a agenerar un zip con todos los archivos.
