### ISSUE TITLE
Guardar en las tablas correspondientes, los mismos datos que se incluyen en el XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2210]
Esto en algún momento se reportó como atendido.
No recuerdo el ticket, ni recuerdo porqué se cerró.

el hecho es que en complemento de pago, algunas facturas aparecen con 3 decimales, lo cual claramente nos indica que la información en las tablas, es distinta a lo que se va en el XML, ya que los importes en el XML son a 3 decimales.

La petición es la misma, es decir, que en la base de datos se refleje fielmente lo que se manda en el XML.

**Comment by jccastillo0007** [comment]
Esto viene con la versión 2.0

**Comment by RigoFlores** [comment]
pues en la versión 2.0, según yo no está guardando a 2 decimales. Checa este cueri, y dime si estoy en lo correcto.

mysql> select importe, subtotal, taxes, total, total_taxes_retenido, total_taxes_trasladado from CFD_FinancialDetails where id in (select financialDetails_id from CFD where sourceRFC like "BAR17%" and folio in ('473', '476', '482'));
+----------+----------+--------------------------------------------------------------------------------------------------------+----------+----------------------+------------------------+
| importe  | subtotal | taxes                                                                                                  | total    | total_taxes_retenido | total_taxes_trasladado |
+----------+----------+--------------------------------------------------------------------------------------------------------+----------+----------------------+------------------------+
|  4624.14 |  4624.14 | [{"amount":739.8624000000001,"baseTax":0,"price":16,"tax":"IVA","factor":"Tasa","type":"Trasladado"}]  |     5364 |                    0 |      739.8624000000001 |
|   5444.8 |   5444.8 | [{"amount":871.168,"baseTax":0,"price":16,"tax":"IVA","factor":"Tasa","type":"Trasladado"}]            |  6315.97 |                    0 |                871.168 |
|  5437.93 |  5437.93 | [{"amount":870.0688,"baseTax":0,"price":16,"tax":"IVA","factor":"Tasa","type":"Trasladado"}]           |     6308 |                    0 |               870.0688 |
|  18918.1 |  18918.1 | [{"amount":3026.8959999999997,"baseTax":0,"price":16,"tax":"IVA","factor":"Tasa","type":"Trasladado"}] |    21945 |                    0 |     3026.8959999999997 |
| 36185.16 | 36185.16 | [{"amount":5789.625599999999,"baseTax":0,"price":16,"tax":"IVA","factor":"Tasa","type":"Trasladado"}]  | 41974.79 |                    0 |      5789.625599999999 |
|  7567.24 |  7567.24 | [{"amount":1210.7584,"baseTax":0,"price":16,"tax":"IVA","factor":"Tasa","type":"Trasladado"}]          |     8778 |                    0 |              1210.7584 |
+----------+----------+--------------------------------------------------------------------------------------------------------+----------+----------------------+------------------------+
6 rows in set (0.03 sec)

**Comment by jccastillo0007** [comment]
creo que importe y subtotal nada mas
