### ISSUE TITLE
Compras - Consultas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2211]
Aquí se deben mostrar los créditos capturados en el menú de Compras - Captura de Crédito.

Podrás seleccionar al proveedor, ya sea por ID o por nombre, ordenados alfabéticamente.

El resultado actualmente muestra estas columnas:

Emisor	Receptor	Fecha	Serie	Folio	Estatus de Pago	Fecha de Pago	Total	PDF	XML	Enviar	Editar

Debe quedar así:
ID Proveedor    Fecha    Serie    Folio    Estatus de Pago    Fecha de Pago    Total    Evidencia

En evidencia se podrán descargar los archivos que se hayan subido en el menú de Captura de Crédito.

**Comment by jccastillo0007** [comment]
no ma... y tu nieve ?
Espero que estén pagando bien por esto...

**Comment by RigoFlores** [comment]
Cambios

Buscar en lugar de RFC como lo tiene ahora mismo, hacerlo por ID de proveedor. La búsqueda por nombre ya existe.
Ordenar alfabéticamente, es un tema que ni debería pedirse, debería darse de facto. Usabilidad de primer año.

La búsqueda se realiza sobre la tabla que almacena las capturas (Credit según he visto), anteriormente no se en cuál se guardaba, quizá la de pagos, o egresos.

El resultado, ahora mismo muestra varias columnas; pues esas columnas cambian a la nueva información, se reducen en número y se toman de la tabla que corresponda. 

Y descargar el archivo de evidencia, ya lo hacemos en otras pantallas desde hace años.


Por un lado se cobrará este desarrollo (no a un precio del mercado de las grandes corporaciones), pero por otro estamos buscando mantenernos. 
El mismo SAT ya tiene su app, y nosotros no. Cada vez, está siendo mas complicado mantenernos frente a los competidores que ofrecen mas y mas funciones y/o facilidades.

**Comment by jccastillo0007** [comment]
solo falta descargar la evidencia

**Comment by jccastillo0007** [comment]
Tienes un análisis y comparativo de funcionalidades que tiene el SAT y los competidores ?

**Comment by jccastillo0007** [comment]
done; 
tuve que borrar todos los créditos que se tenían en la base de datos

**Comment by RigoFlores** [comment]
Aqui aún está faltando la posibilidad de descargar la evidencia. No me lo permite.

Y en los filtros está faltando por rangos de fecha y rangos de folios. Quizá el de status podría ser.

**Comment by jccastillo0007** [comment]
fixed
