### ISSUE TITLE
Compras - Captura de Crédito, no almacena mas de un archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2213]
Aunque tu elijas 2 o mas archivos, y en la pantalla te indique cuántos archivos subiste, en la tabla Credit, únicamente almacena 1 ruta.

No será común (creo) almacenar mas de 1 archivo, aunque quizás para los CFDI's, si quieran guardar XML y PDF.

**Comment by jccastillo0007** [comment]
El requerimiento inicial era un archivo... esto cambia muchas cosas, chiaaa

**Comment by RigoFlores** [comment]
Cuando le damos importar CFDI's externos, podemos subir varios archivos a la vez.

Si quieres, para no detener el avance de esto, por lo pronto soportaremos 1 solo archivo. Pero en cuanto a los CFDI's, casi puedo asegurar que buscarán subir XML y PDF. La otra es nosotros generarles un PDF genérico.

**Comment by jccastillo0007** [comment]
pueden subir un zip, es lo que hacemos en cfdis externos

**Comment by jccastillo0007** [comment]
Estaba viendo como soportar mas de un archivo... pero hay otro problema, si suben varios XML, de cual se debe tomar los datos para mostrarlos en pantalla, se vuelve medio inconsistente el uso de los archivos...

**Comment by jccastillo0007** [comment]
Oye, en esta pantalla solo se muestra la opción de Proveedor, y en otras se muetra id proveedor y proveedor, esta inconsistente

**Comment by RigoFlores** [comment]
Si, según yo se solicitó inicialmente el ID proveedor. Hay que agregarlo, para tener consistencia en las pantallas de consultas.

En cuanto a los archivos, a menos que hagamos la distinción de "subir CFDI" y "subir evidencia", se podría permitir subir mas de un archivo. Subir CFDI sería exclusivo para el XML y subir evidencia, para cualquier archivo. Por ejemplo PDF y PNG, JPG, etc.

Si no se complica ahora, lo podemos hacer, sino pues salimos así y adelante es muy probable que se ocupe y/o que lo pidan.

**Comment by RigoFlores** [comment]
[0e621180-ab15-40be-8ce9-fe13b32488bd.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/12388938/0e621180-ab15-40be-8ce9-fe13b32488bd.xml.txt)

Este es el archivo que no subió. Aquí hay otro ejemplo:


[1bc92ad2-fccd-435d-8ad3-fd543b00b0f5.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/12388942/1bc92ad2-fccd-435d-8ad3-fd543b00b0f5.xml.txt)

**Comment by jccastillo0007** [comment]
fixed
