### ISSUE TITLE
CxP - Captura de Crédito - cuando ingresas 2 XML del mismo proveedor, en el 2o marca internal error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2214]
Así, en la misma sesión, sin salirte de la pantalla, lo intentas hacer, y el primero lo captura bien.
El segundo marca internal error.
Tengo que salirme de esa sesión y volver a entrar, para que acepte el 2o XML.

Puedes reproducirlo, si quieres borra la tabla de Credit, y los archivos, y luego intenta subir uno tras otro, estos archivos.

[telmex_2.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/12403246/telmex_2.zip.txt)

**Comment by RigoFlores** [comment]
Intenta hacerlo, ya que subas los 2 archivos, descarga ambos desde consultas.

Verás que uno de ellos no es el que subiste, sino otro (no se de donde lo está tomando; es el comportamiento del video que te mandé por whatsApp).

En el caso de mi última prueba, el archivo que no corresponde y que si descargó es "finkok.xml"

**Comment by jccastillo0007** [comment]
fixed
