### ISSUE TITLE
Compras - Captura de Crédito - hace un desmadre con las evidencias

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2215]
Cuando ya subes varios archivos, los está revolviendo todos... no se algo muy extraño sucede.
Eso lo puedes ver si descargas las evidencias desde Compras - Consultas.
Ahí verás que los archivos descargados no coinciden con los que subiste, al menos no en todo caso.

Intenta subir todos estos. 
Si te marca internal error, sales de la sesión y lo vuelves a hacer.

Verás que cuando logres subir todos, y los quieras descargar, son un desmadre, están revueltos de archivos que ni siquiera subiste.

[pruebasCreditos.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/12403368/pruebasCreditos.zip.txt)

**Comment by jccastillo0007** [comment]
de los 6 créditos que capturaste con la TIA, todos los archivos los baja correctamente.
