### ISSUE TITLE
CxP - Ordenar alfabéticamente las listas de las distintas pantallas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2216]
En varias pantallas, se realizan consultas a partir de las listas.
Hay que ordenar dichas listas, ya que aparecen en el orden que fueron creadas, pero hay que ordenarlas lexicográficamente.

Captura de Crédito
Consultas
Ingresar Pago
Cartera de Proveedores

**Comment by jccastillo0007** [comment]
Cartera de Proveedores = Done
Ingresar Pago = Done
Captura de Crédito = Done
Consultas = Done

Checar en la noche
