### ISSUE TITLE
Actualizar el estado de los créditos capturados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2217]
El estado del crédito puede ser vigente, vencido o pagado.

Vigente, cuando la fecha de pago que se indicó en la pantalla de captura de crédito, es mayor que la fecha actual.
Vencida, cuando la fecha de pago que se capturó, es menor que la fecha actual.
Pagada, cuando ya se registró el pago.

Entonces, hay 2 tiempos de actualización.
1) Cuando se captura el crédito, si la fecha de pago es menor que hoy, entonces el crédito "nace" como vencido.
2) Diariamente se debe correr el proceso de actualización de estados, con los créditos ya capturados.

Esto es muy importante, ya que en los reportes, se deberá conocer lo que hay que pagar ya, y lo que aún puede esperar, que al final es uno de los puntos mas importantes de CxP.

**Comment by jccastillo0007** [comment]
1. DONE

**Comment by jccastillo0007** [comment]
2. DONE pero solo en producción... necesitamos liberar todo esto, crear unos créditos y ver que se actualicen ... el cron corre a diario, pero es por fuera de facturat.

**Comment by RigoFlores** [comment]
ok, entonces vamos a llevarlo a producción.
