### ISSUE TITLE
CxP - Consulta de Pago, cuando se elimina un pago, no actualiza su status

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2218]
Si tuviste una captura chueca, incorrecta, error de dedo de un pago, pues querrás borrarlo y volver a capturalo.

En esta opción de consulta, si te muestra el resultado de la consulta. 
Si le das borrar, SI los borra de la tabla Payments.

Lo que NO hace es actualizar el status del crédito a vigente o vencido según sea el caso.

**Comment by jccastillo0007** [comment]
fixed
