### ISSUE TITLE
ERP- NOMINA INDIVIDUAL - MOSTRAR EL TOTAL CON 2 DECIMALES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#222]
EN LA PANTALLA DONDE SE CAPTURAN LOS DATOS DEL EMPLEADO, MOSTRAR EL TOTAL DE LA NÓMINA CON 2 DECIMALES, YA QUE SE LLEGA A CONFUNDIR UN POCO LA CANTIDAD

**Comment by jccastillo0007** [comment]
Done
