### ISSUE TITLE
Addenda MABE - no está incluyendo la tasa del IVA en el nodo correspondiente de la addenda

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2220]
Es probable que no incluya las tasas de traslados de otros impuestos y quizá de retenciones tampoco.

Por lo pronto del IVA de 16%, no lo está incluyendo.

Ese nodo lo incluye así actualmente:
mabe:Traslados>
    mabe:Traslado importe="1.60" **tasa="0.0"** tipo="IVA"/>            
/mabe:Traslados>

Dice mabe que tiene que ir **"16" o "0.16"**, cualquiera de los 2.

**Comment by jccastillo0007** [comment]
datos de prueba?

cómo lo replicaste?

**Comment by RigoFlores** [comment]
Lo generé en pro, porque es parte del servicio que contrataron. Lo corregí a manopla, ya que es addenda.
Pero en pru, para el emisor IIA, aquí tienes la info para replicarlo.


<img width="773" alt="mabe 1" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/fa7e8b50-0abc-40a0-a0fe-eb008e8b576b">
<img width="630" alt="mabe3" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/260a1ea4-969a-4fd3-91b8-d1992dbb8da6">
<img width="734" alt="mabe 2" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/317d1996-dbb5-4575-8b04-3d6aa3f06462">

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Favor de llevarlo a producción.
