### ISSUE TITLE
Replicar clientes y productos de un cliente a otro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2221]
OJO no es transferir, sino es replicar, copiar los catálogos de productos y clientes

Cuenta origen: IRS180509JL7

Cuenta destinto: IPM230224GF3

di de alta las mismas monedas, las mismas unidades para que los productos puedan replicarse correctamente.

**Comment by jccastillo0007** [comment]
psss eso no esta fácil... si no son muchos, es mejor hacerlo a mano

**Comment by jccastillo0007** [comment]
done.
