### ISSUE TITLE
Plataforma Alteza - cambiar residencia fiscal por "Código Postal"

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2222]
En la pantalla de captura de factura, tanto para FI como para  usuario registrado, cambiar esa leyenda, ya que al parecer les confunde un poco, y ahí teclean la localidad, municipio o estado.
Incluso, hasta estaría chido validar que fueran 5 dígitos, ya que es el formato del CP en México.

**Comment by jccastillo0007** [comment]
done.

Se fue hasta prod
