### ISSUE TITLE
v2cero -  catálogo de clientes - ajustes menores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2224]
En la pantalla inicial ordenar el listado en pantalla por nombre.
Dar la opción de ordenar por RFC o por nombre corto, cuando se le da click a la columna.

El ícono de editar, que sea similar a lo que tenemos en la plataforma anterior, es decir como forma de lápiz.

Agregar la leyenda del tool tip para los íconos de editar y de eliminar.

Mover a la izquierda la captura de la búsqueda y a la derecha el exportar a excel.

la captura de búsqueda, hacerla mas corta, al menos a la mitad de lo largo que tiene ahora mismo.

**Comment by jccastillo0007** [comment]
DONE. "En la pantalla inicial ordenar el listado en pantalla por nombre. "

**Comment by jccastillo0007** [comment]
DONE. "Dar la opción de ordenar por RFC o por nombre corto, cuando se le da click a la columna."
DONE. "Mover a la izquierda la captura de la búsqueda y a la derecha el exportar a excel."
DONE. "la captura de búsqueda, hacerla mas corta, al menos a la mitad de lo largo que tiene ahora mismo."

Solo falta lo del ícono.

Lo pongo como resolved para que lo veas

**Comment by RigoFlores** [comment]
Si quedó bien. Pero bueno yo obvié que para el nombre también sería que ordenara de la misma manera.
Eso creo que será muy funcional. Favor de agregarlo al nombre también.

y otra cosa, el estándar de búsqueda para todos los catálogos, será así... a la derecha no???

tons queda pendiente el ícono y el tooltip de los íconos de editar y borrar.

**Comment by jccastillo0007** [comment]
Ya esta lo de ordenamiento por "Nombre"

**Comment by RigoFlores** [comment]
ok, solo restan los tooltips de los íconos de editar y borrar.
Ese tooltip aplicará en cualquier pantalla donde aparezcan esos íconos?

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
en todos los catálogos que hemos revisado quedó el tooltip, excepto en folios.
Ahí faltó colocarlo.

No es genérico, que si se pone en uno ya queda para todos?

**Comment by jccastillo0007** [comment]
noup, no es genérico.

Y si esta en el catálogo de folios, pero solo en aquellos que se pueden editar o borrar, los que no se pueden modificar tienen los botones deshabilitados
