### ISSUE TITLE
v2cero - catálogo de clientes, datos obligatorios.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2226]
El país y estado no son datos obligatorios.
Mostrar el listado de países todos en mayúsculas, ya que MEXICO aparece así, pero los otros no.

**Comment by jccastillo0007** [comment]
Me puedes pasar esta lista en mayúsculas

+-----+---------------------------------------------------+
| id  | name                                              |
+-----+---------------------------------------------------+
| AFG | Afganistan                                        |
| ALA | Islas Åland                                      |
| ALB | Albania                                           |
| DEU | Alemania                                          |
| AND | Andorra                                           |
| AGO | Angola                                            |
| AIA | Anguila                                           |
| ATA | Antartida                                         |
| ATG | Antigua y Barbuda                                 |
| SAU | Arabia Saudita                                    |
| DZA | Argelia                                           |
| ARG | Argentina                                         |
| ARM | Armenia                                           |
| ABW | Aruba                                             |
| AUS | Australia                                         |
| AUT | Austria                                           |
| AZE | Azerbaiyan                                        |
| BHS | Bahamas (las)                                     |
| BGD | Banglades                                         |
| BRB | Barbados                                          |
| BHR | Barein                                            |
| BEL | Belgica                                           |
| BLZ | Belice                                            |
| BEN | Benin                                             |
| BMU | Bermudas                                          |
| BLR | Bielorrusia                                       |
| MMR | Myanmar                                           |
| BOL | Bolivia, Estado Plurinacional de                  |
| BIH | Bosnia y Herzegovina                              |
| BWA | Botsuana                                          |
| BRA | Brasil                                            |
| BRN | Brunei Darussalam                                 |
| BGR | Bulgaria                                          |
| BFA | Burkina Faso                                      |
| BDI | Burundi                                           |
| BTN | Butan                                             |
| CPV | Cabo Verde                                        |
| KHM | Camboya                                           |
| CMR | Camerun                                           |
| CAN | Canada                                            |
| QAT | Catar                                             |
| BES | Bonaire, San Eustaquio y Saba                     |
| TCD | Chad                                              |
| CHL | Chile                                             |
| CHN | China                                             |
| CYP | Chipre                                            |
| COL | Colombia                                          |
| COM | Comoras                                           |
| PRK | Corea (la Republica Democratica Popular de)       |
| KOR | Corea (la Republica de)                           |
| CIV | Cote dIvoire                                      |
| CRI | Costa Rica                                        |
| HRV | Croacia                                           |
| CUB | Cuba                                              |
| CUW | Curaçao                                          |
| DNK | Dinamarca                                         |
| DMA | Dominica                                          |
| ECU | Ecuador                                           |
| EGY | Egipto                                            |
| SLV | El Salvador                                       |
| ARE | Emiratos arabes Unidos (Los)                      |
| ERI | Eritrea                                           |
| SVK | Eslovaquia                                        |
| SVN | Eslovenia                                         |
| ESP | España                                           |
| USA | Estados Unidos (los)                              |
| EST | Estonia                                           |
| ETH | Etiopia                                           |
| PHL | Filipinas (las)                                   |
| FIN | Finlandia                                         |
| FJI | Fiyi                                              |
| FRA | Francia                                           |
| GAB | Gabon                                             |
| GMB | Gambia (La)                                       |
| GEO | Georgia                                           |
| GHA | Ghana                                             |
| GIB | Gibraltar                                         |
| GRD | Granada                                           |
| GRC | Grecia                                            |
| GRL | Groenlandia                                       |
| GLP | Guadalupe                                         |
| GUM | Guam                                              |
| GTM | Guatemala                                         |
| GUF | Guayana Francesa                                  |
| GGY | Guernsey                                          |
| GIN | Guinea                                            |
| GNB | Guinea-Bisau                                      |
| GNQ | Guinea Ecuatorial                                 |
| GUY | Guyana                                            |
| HTI | Haiti                                             |
| HND | Honduras                                          |
| HKG | Hong Kong                                         |
| HUN | Hungria                                           |
| IND | India                                             |
| IDN | Indonesia                                         |
| IRQ | Irak                                              |
| IRN | Iran (la Republica Islamica de)                   |
| IRL | Irlanda                                           |
| BVT | Isla Bouvet                                       |
| IMN | Isla de Man                                       |
| CXR | Isla de Navidad                                   |
| NFK | Isla Norfolk                                      |
| ISL | Islandia                                          |
| CYM | Islas Caiman (las)                                |
| CCK | Islas Cocos (Keeling)                             |
| COK | Islas Cook (las)                                  |
| FRO | Islas Feroe (las)                                 |
| SGS | Georgia del sur y las islas sandwich del sur      |
| HMD | Isla Heard e Islas McDonald                       |
| FLK | Islas Malvinas [Falkland] (las)                   |
| MNP | Islas Marianas del Norte (las)                    |
| MHL | Islas Marshall (las)                              |
| PCN | Pitcairn                                          |
| SLB | Islas Salomon (las)                               |
| TCA | Islas Turcas y Caicos (las)                       |
| UMI | Islas de Ultramar Menores de Estados Unidos (las) |
| VGB | Islas Virgenes (Britanicas)                       |
| VIR | Islas Virgenes (EE.UU.)                           |
| ISR | Israel                                            |
| ITA | Italia                                            |
| JAM | Jamaica                                           |
| JPN | Japon                                             |
| JEY | Jersey                                            |
| JOR | Jordania                                          |
| KAZ | Kazajistan                                        |
| KEN | Kenia                                             |
| KGZ | Kirguistan                                        |
| KIR | Kiribati                                          |
| KWT | Kuwait                                            |
| LAO | Lao, (la) Republica Democratica Popular           |
| LSO | Lesoto                                            |
| LVA | Letonia                                           |
| LBN | Libano                                            |
| LBR | Liberia                                           |
| LBY | Libia                                             |
| LIE | Liechtenstein                                     |
| LTU | Lituania                                          |
| LUX | Luxemburgo                                        |
| MAC | Macao                                             |
| MDG | Madagascar                                        |
| MYS | Malasia                                           |
| MWI | Malaui                                            |
| MDV | Maldivas                                          |
| MLI | Mali                                              |
| MLT | Malta                                             |
| MAR | Marruecos                                         |
| MTQ | Martinica                                         |
| MUS | Mauricio                                          |
| MRT | Mauritania                                        |
| MYT | Mayotte                                           |
| MEX | MEXICO                                            |
| FSM | Micronesia (los Estados Federados de)             |
| MDA | Moldavia (la Republica de)                        |
| MCO | Monaco                                            |
| MNG | Mongolia                                          |
| MNE | Montenegro                                        |
| MSR | Montserrat                                        |
| MOZ | Mozambique                                        |
| NAM | Namibia                                           |
| NRU | Nauru                                             |
| NPL | Nepal                                             |
| NIC | Nicaragua                                         |
| NER | Niger (el)                                        |
| NGA | Nigeria                                           |
| NIU | Niue                                              |
| NOR | Noruega                                           |
| NCL | Nueva Caledonia                                   |
| NZL | Nueva Zelanda                                     |
| OMN | Oman                                              |
| NLD | Paises Bajos (los)                                |
| PAK | Pakistan                                          |
| PLW | Palaos                                            |
| PSE | Palestina, Estado de                              |
| PAN | Panama                                            |
| PNG | Papua Nueva Guinea                                |
| PRY | Paraguay                                          |
| PER | Peru                                              |
| PYF | Polinesia Francesa                                |
| POL | Polonia                                           |
| PRT | Portugal                                          |
| PRI | Puerto Rico                                       |
| GBR | Reino Unido (el)                                  |
| CAF | Republica Centroafricana (la)                     |
| CZE | Republica Checa (la)                              |
| MKD | Macedonia (la antigua Republica Yugoslava de)     |
| COG | Congo                                             |
| COD | Congo (la Republica Democratica del)              |
| DOM | Republica Dominicana (la)                         |
| REU | Reunion                                           |
| RWA | Ruanda                                            |
| ROU | Rumania                                           |
| RUS | Rusia, (la) Federacion de                         |
| ESH | Sahara Occidental                                 |
| WSM | Samoa                                             |
| ASM | Samoa Americana                                   |
| BLM | San Bartolome                                     |
| KNA | San Cristobal y Nieves                            |
| SMR | San Marino                                        |
| MAF | San Martin (parte francesa)                       |
| SPM | San Pedro y Miquelon                              |
| VCT | San Vicente y las Granadinas                      |
| SHN | Santa Helena, Ascension y Tristan de Acuña       |
| LCA | Santa Lucia                                       |
| STP | Santo Tome y Principe                             |
| SEN | Senegal                                           |
| SRB | Serbia                                            |
| SYC | Seychelles                                        |
| SLE | Sierra leona                                      |
| SGP | Singapur                                          |
| SXM | Sint Maarten (parte holandesa)                    |
| SYR | Siria, (la) Republica arabe                       |
| SOM | Somalia                                           |
| LKA | Sri Lanka                                         |
| SWZ | Suazilandia                                       |
| ZAF | Sudafrica                                         |
| SDN | Sudan (el)                                        |
| SSD | Sudan del Sur                                     |
| SWE | Suecia                                            |
| CHE | Suiza                                             |
| SUR | Surinam                                           |
| SJM | Svalbard y Jan Mayen                              |
| THA | Tailandia                                         |
| TWN | Taiwan (Provincia de China)                       |
| TZA | Tanzania, Republica Unida de                      |
| TJK | Tayikistan                                        |
| IOT | Territorio Britanico del Oceano indico (el)       |
| ATF | Territorios Australes Franceses (los)             |
| TLS | Timor-Leste                                       |
| TGO | Togo                                              |
| TKL | Tokelau                                           |
| TON | Tonga                                             |
| TTO | Trinidad y Tobago                                 |
| TUN | Tunez                                             |
| TKM | Turkmenistan                                      |
| TUR | Turquia                                           |
| TUV | Tuvalu                                            |
| UKR | Ucrania                                           |
| UGA | Uganda                                            |
| URY | Uruguay                                           |
| UZB | Uzbekistan                                        |
| VUT | Vanuatu                                           |
| VAT | Santa Sede[Estado de la Ciudad del Vaticano] (la) |
| VEN | Venezuela, Republica Bolivariana de               |
| VNM | Viet Nam                                          |
| WLF | Wallis y Futuna                                   |
| YEM | Yemen                                             |
| DJI | Yibuti                                            |
| ZMB | Zambia                                            |
| ZWE | Zimbabue                                          |
| ZZZ | Paises no declarados                              |
+-----+---------------------------------------------------+
250 rows in set (0.00 sec)

**Comment by RigoFlores** [comment]
ME PUEDES PASAR ESTA LISTA EN MAYÚSCULAS
+-----+---------------------------------------------------+
| ID | NAME |
+-----+---------------------------------------------------+
| AFG | AFGANISTAN |
| ALA | ISLAS ÅLAND |
| ALB | ALBANIA |
| DEU | ALEMANIA |
| AND | ANDORRA |
| AGO | ANGOLA |
| AIA | ANGUILA |
| ATA | ANTARTIDA |
| ATG | ANTIGUA Y BARBUDA |
| SAU | ARABIA SAUDITA |
| DZA | ARGELIA |
| ARG | ARGENTINA |
| ARM | ARMENIA |
| ABW | ARUBA |
| AUS | AUSTRALIA |
| AUT | AUSTRIA |
| AZE | AZERBAIYAN |
| BHS | BAHAMAS (LAS) |
| BGD | BANGLADES |
| BRB | BARBADOS |
| BHR | BAREIN |
| BEL | BELGICA |
| BLZ | BELICE |
| BEN | BENIN |
| BMU | BERMUDAS |
| BLR | BIELORRUSIA |
| MMR | MYANMAR |
| BOL | BOLIVIA, ESTADO PLURINACIONAL DE |
| BIH | BOSNIA Y HERZEGOVINA |
| BWA | BOTSUANA |
| BRA | BRASIL |
| BRN | BRUNEI DARUSSALAM |
| BGR | BULGARIA |
| BFA | BURKINA FASO |
| BDI | BURUNDI |
| BTN | BUTAN |
| CPV | CABO VERDE |
| KHM | CAMBOYA |
| CMR | CAMERUN |
| CAN | CANADA |
| QAT | CATAR |
| BES | BONAIRE, SAN EUSTAQUIO Y SABA |
| TCD | CHAD |
| CHL | CHILE |
| CHN | CHINA |
| CYP | CHIPRE |
| COL | COLOMBIA |
| COM | COMORAS |
| PRK | COREA (LA REPUBLICA DEMOCRATICA POPULAR DE) |
| KOR | COREA (LA REPUBLICA DE) |
| CIV | COTE DIVOIRE |
| CRI | COSTA RICA |
| HRV | CROACIA |
| CUB | CUBA |
| CUW | CURAÇAO |
| DNK | DINAMARCA |
| DMA | DOMINICA |
| ECU | ECUADOR |
| EGY | EGIPTO |
| SLV | EL SALVADOR |
| ARE | EMIRATOS ARABES UNIDOS (LOS) |
| ERI | ERITREA |
| SVK | ESLOVAQUIA |
| SVN | ESLOVENIA |
| ESP | ESPAÑA |
| USA | ESTADOS UNIDOS (LOS) |
| EST | ESTONIA |
| ETH | ETIOPIA |
| PHL | FILIPINAS (LAS) |
| FIN | FINLANDIA |
| FJI | FIYI |
| FRA | FRANCIA |
| GAB | GABON |
| GMB | GAMBIA (LA) |
| GEO | GEORGIA |
| GHA | GHANA |
| GIB | GIBRALTAR |
| GRD | GRANADA |
| GRC | GRECIA |
| GRL | GROENLANDIA |
| GLP | GUADALUPE |
| GUM | GUAM |
| GTM | GUATEMALA |
| GUF | GUAYANA FRANCESA |
| GGY | GUERNSEY |
| GIN | GUINEA |
| GNB | GUINEA-BISAU |
| GNQ | GUINEA ECUATORIAL |
| GUY | GUYANA |
| HTI | HAITI |
| HND | HONDURAS |
| HKG | HONG KONG |
| HUN | HUNGRIA |
| IND | INDIA |
| IDN | INDONESIA |
| IRQ | IRAK |
| IRN | IRAN (LA REPUBLICA ISLAMICA DE) |
| IRL | IRLANDA |
| BVT | ISLA BOUVET |
| IMN | ISLA DE MAN |
| CXR | ISLA DE NAVIDAD |
| NFK | ISLA NORFOLK |
| ISL | ISLANDIA |
| CYM | ISLAS CAIMAN (LAS) |
| CCK | ISLAS COCOS (KEELING) |
| COK | ISLAS COOK (LAS) |
| FRO | ISLAS FEROE (LAS) |
| SGS | GEORGIA DEL SUR Y LAS ISLAS SANDWICH DEL SUR |
| HMD | ISLA HEARD E ISLAS MCDONALD |
| FLK | ISLAS MALVINAS [FALKLAND] (LAS) |
| MNP | ISLAS MARIANAS DEL NORTE (LAS) |
| MHL | ISLAS MARSHALL (LAS) |
| PCN | PITCAIRN |
| SLB | ISLAS SALOMON (LAS) |
| TCA | ISLAS TURCAS Y CAICOS (LAS) |
| UMI | ISLAS DE ULTRAMAR MENORES DE ESTADOS UNIDOS (LAS) |
| VGB | ISLAS VIRGENES (BRITANICAS) |
| VIR | ISLAS VIRGENES (EE.UU.) |
| ISR | ISRAEL |
| ITA | ITALIA |
| JAM | JAMAICA |
| JPN | JAPON |
| JEY | JERSEY |
| JOR | JORDANIA |
| KAZ | KAZAJISTAN |
| KEN | KENIA |
| KGZ | KIRGUISTAN |
| KIR | KIRIBATI |
| KWT | KUWAIT |
| LAO | LAO, (LA) REPUBLICA DEMOCRATICA POPULAR |
| LSO | LESOTO |
| LVA | LETONIA |
| LBN | LIBANO |
| LBR | LIBERIA |
| LBY | LIBIA |
| LIE | LIECHTENSTEIN |
| LTU | LITUANIA |
| LUX | LUXEMBURGO |
| MAC | MACAO |
| MDG | MADAGASCAR |
| MYS | MALASIA |
| MWI | MALAUI |
| MDV | MALDIVAS |
| MLI | MALI |
| MLT | MALTA |
| MAR | MARRUECOS |
| MTQ | MARTINICA |
| MUS | MAURICIO |
| MRT | MAURITANIA |
| MYT | MAYOTTE |
| MEX | MEXICO |
| FSM | MICRONESIA (LOS ESTADOS FEDERADOS DE) |
| MDA | MOLDAVIA (LA REPUBLICA DE) |
| MCO | MONACO |
| MNG | MONGOLIA |
| MNE | MONTENEGRO |
| MSR | MONTSERRAT |
| MOZ | MOZAMBIQUE |
| NAM | NAMIBIA |
| NRU | NAURU |
| NPL | NEPAL |
| NIC | NICARAGUA |
| NER | NIGER (EL) |
| NGA | NIGERIA |
| NIU | NIUE |
| NOR | NORUEGA |
| NCL | NUEVA CALEDONIA |
| NZL | NUEVA ZELANDA |
| OMN | OMAN |
| NLD | PAISES BAJOS (LOS) |
| PAK | PAKISTAN |
| PLW | PALAOS |
| PSE | PALESTINA, ESTADO DE |
| PAN | PANAMA |
| PNG | PAPUA NUEVA GUINEA |
| PRY | PARAGUAY |
| PER | PERU |
| PYF | POLINESIA FRANCESA |
| POL | POLONIA |
| PRT | PORTUGAL |
| PRI | PUERTO RICO |
| GBR | REINO UNIDO (EL) |
| CAF | REPUBLICA CENTROAFRICANA (LA) |
| CZE | REPUBLICA CHECA (LA) |
| MKD | MACEDONIA (LA ANTIGUA REPUBLICA YUGOSLAVA DE) |
| COG | CONGO |
| COD | CONGO (LA REPUBLICA DEMOCRATICA DEL) |
| DOM | REPUBLICA DOMINICANA (LA) |
| REU | REUNION |
| RWA | RUANDA |
| ROU | RUMANIA |
| RUS | RUSIA, (LA) FEDERACION DE |
| ESH | SAHARA OCCIDENTAL |
| WSM | SAMOA |
| ASM | SAMOA AMERICANA |
| BLM | SAN BARTOLOME |
| KNA | SAN CRISTOBAL Y NIEVES |
| SMR | SAN MARINO |
| MAF | SAN MARTIN (PARTE FRANCESA) |
| SPM | SAN PEDRO Y MIQUELON |
| VCT | SAN VICENTE Y LAS GRANADINAS |
| SHN | SANTA HELENA, ASCENSION Y TRISTAN DE ACUÑA |
| LCA | SANTA LUCIA |
| STP | SANTO TOME Y PRINCIPE |
| SEN | SENEGAL |
| SRB | SERBIA |
| SYC | SEYCHELLES |
| SLE | SIERRA LEONA |
| SGP | SINGAPUR |
| SXM | SINT MAARTEN (PARTE HOLANDESA) |
| SYR | SIRIA, (LA) REPUBLICA ARABE |
| SOM | SOMALIA |
| LKA | SRI LANKA |
| SWZ | SUAZILANDIA |
| ZAF | SUDAFRICA |
| SDN | SUDAN (EL) |
| SSD | SUDAN DEL SUR |
| SWE | SUECIA |
| CHE | SUIZA |
| SUR | SURINAM |
| SJM | SVALBARD Y JAN MAYEN |
| THA | TAILANDIA |
| TWN | TAIWAN (PROVINCIA DE CHINA) |
| TZA | TANZANIA, REPUBLICA UNIDA DE |
| TJK | TAYIKISTAN |
| IOT | TERRITORIO BRITANICO DEL OCEANO INDICO (EL) |
| ATF | TERRITORIOS AUSTRALES FRANCESES (LOS) |
| TLS | TIMOR-LESTE |
| TGO | TOGO |
| TKL | TOKELAU |
| TON | TONGA |
| TTO | TRINIDAD Y TOBAGO |
| TUN | TUNEZ |
| TKM | TURKMENISTAN |
| TUR | TURQUIA |
| TUV | TUVALU |
| UKR | UCRANIA |
| UGA | UGANDA |
| URY | URUGUAY |
| UZB | UZBEKISTAN |
| VUT | VANUATU |
| VAT | SANTA SEDE[ESTADO DE LA CIUDAD DEL VATICANO] (LA) |
| VEN | VENEZUELA, REPUBLICA BOLIVARIANA DE |
| VNM | VIET NAM |
| WLF | WALLIS Y FUTUNA |
| YEM | YEMEN |
| DJI | YIBUTI |
| ZMB | ZAMBIA |
| ZWE | ZIMBABUE |
| ZZZ | PAISES NO DECLARADOS |

**Comment by jccastillo0007** [comment]
DONE. "El país y estado no son datos obligatorios."

**Comment by RigoFlores** [comment]
OK, YA SOLO RESTA PASAR LOS PAÍSES A MAYÚSCULAS

**Comment by jccastillo0007** [comment]
fixed
