### ISSUE TITLE
v2cero - catálogo de folios, no permitir borrar o editar series ya utilizadas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2227]
NO DEBE PERMITIR EDITAR O BORRAR serie folios que ya se están ocupando.
Solo se deben poder borrar o editar series-folios sin uso.

Edité la serie SIN SERIE y lo permitió. Se borró y ya no puedo recuperarla.

**Comment by jccastillo0007** [comment]
Fixed
