### ISSUE TITLE
v2cero - catálogo de impuestos, permite repetir impuestos ya capturados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2229]
La llave debería ser Impuesto - tipo - factor - tasa, eso no debe repetirse.
Ahora mismo permitió repetir el IVA retenido del 4%,

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
negativo, sigue permitiendo duplicados... mira la imagen.

<img width="778" alt="iva" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/4394e5e2-bb9d-43a6-80b8-f5ee9137355e">

**Comment by jccastillo0007** [comment]
fixed
