### ISSUE TITLE
v2cero - catálogo de impuestos, manejar los impuestos estándares del SAT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2230]
Los impuestos estándares únicamente son IVA, ISR e IEPS.
Hospedaje, 5 al millar, etc, son impuestos locales.

O los seguimos manejando como ahora, es decir como si fueran productos con características bien específicas, o modificamos esta pantalla de catálogo de impuestos para incluirlos aquí.
Estos impuestos locales, se definen por: nombre, tasa, tipo. El nombre debe ser de libre captura.

Quizá una combinación de los 2... que aquí se definan los impuestos y que en la captura se pueda modificar libremente el importe del impuesto. 

¿qué opinas?

**Comment by RigoFlores** [comment]
es decir, una combinación de los 2 sería...
Que en esta pantalla pudieran capturar un impuesto local... nombre, tasa, tipo (por ejemplo: 5 al millar, 0.5, retenido)

Y que al incluirlo en un producto o servicio, se pudiera editar el cálculo del importe, ya que en gobierno hay que llegar a cantidades precisas, aunque el cálculo esté correcto, pero por centavos ellos lo pudieran variar.

**Comment by jccastillo0007** [comment]
los impuestos locales ya se incluyen en la lista también... no entiendo bien que falta? que sean editables ?

**Comment by RigoFlores** [comment]
pues es decidir cómo lo hacemos.
Deja pensarle y te propongo algo así, chingón...

**Comment by jccastillo0007** [comment]
se están mostrando los impuestos que hemos tenido por mucho tiempo, sugiero así dejarlo, y veremos si algún día nos piden un impuesto mas....

**Comment by RigoFlores** [comment]
el punto no es ese... el asunto es que excepto del IVA, ISR e IEPS, los demás son impuestos locales.
Tienen otro tratamiento.
Entonces, yo creo que mejor los manejaremos o en un menú de impuestos locales, para aquellos que lo paguen, o lo manejamos en impuestos como productos, igual para aquellos que lo paguen.

pero ahora mismo, ese gran listado, no tienen mucho sentido.

**Comment by jccastillo0007** [comment]
pero así esta en la versión actual, no veo porque hacerlo mas complejo en la v2, debería ser mas sencillo

**Comment by RigoFlores** [comment]
Si, has dado en el punto. Esta versión debe reflejar la experiencia y conocimiento.
Ahora mismo, existen esos impuestos ahí como estorbando, y además también está la solución de dar de alta los impuestos locales como productos cuyo ID es ImpLoc.

Cuando un cliente contrata este servicio (soporte a impuestos locales), el manual que le entregamos es el que se refiere a manejar los impuestos locales como productos.
Es decir, ahora mismo, ese listado está en producción, pero no se ocupa o no debería ocuparse. Ya está deprecated, jeje.

Por ello hace tiempo, preguntaba en un issue, cómo manejaremos este asunto de impuestos locales, que son un servicio especial de los que ofrecemos.

Lo menos que tenemos que hacer, para hacerlo mas simple, es manejar los impuestos locales como productos (así está hoy) y eliminar este listado chafa de aquí. 

Lo elegante, para hacerlo chingón, es otra pantalla especial para impuestos locales, activada por un plugin donde se capture el tipo, nombre, tasa. Al agregar el impuesto en el producto, ahí se podría editar el importe. Esa es la solución elegante.
La posibilidad de poder editar el importe, es porque en gobierno algunos cálculos no se de donde los hacen, pero no coinciden, entonces hay que ajustar algunos centavos para que todo cuadre y les acepten sus facturas.

**Comment by jccastillo0007** [comment]
ok, los quito para que no estorben 
Ya no manejaremos impuestos locales como un producto, eso es un super parche chacarron... en su momento, haremos una pantalla para administración del catálogo de impuestos locales... 

Me parece que es más trabajo que no sé si alguien pague por eso... pero vamos viendo.

**Comment by RigoFlores** [comment]
Este es uno de nuestros servicios premium, y si hay varios clientes que lo han pagado, claro.
Carta Porte es otro servicio premium... 
CCE, Sector Educativo, y así otros.

Claro que lo pagan.
será bueno para validar quién lo paga y cómo deben pagarlo ya.

**Comment by jccastillo0007** [comment]
fixed
