### ISSUE TITLE
v2cero - pantalla de facturación, lugar de expedición incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2234]
El lugar de expedición, es el domicilio fiscal del emisor, es decir el código postal del emisor.
Ahora mismo, muestra el código postal del receptor.

Hay algunas opciones:
a) Mostrar el CP del emisor en modo solo lectura (con la etiqueta Lugar de Expedición).
b) No mostrar ese campo
c) Mostrar el CP del receptor, junto con su régimen fiscal en modo solo lectura. (con etiqueta de domicilio fiscal y régimen fiscal)

**Comment by RigoFlores** [comment]
Si te vas por la opción b) se podría agregar el ID para que fuera otra forma de elegir al cliente.
En el listado, ya sea nombre, rfc o ID del cliente (jejeje), ordenar lexicográficamente...

**Comment by jccastillo0007** [comment]
vamos a aplicar la opción a

**Comment by RigoFlores** [comment]
aún está chueco...

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
La cagué, la opción (a) implica la leyenda "Domicilio Fiscal"... que es del emisor.
Pls hay que cambiarla.

Realmente lo chido, sería que en lugar de ello, se busque por ID del cliente... es decir un tercer criterio de búsqueda.

**Comment by jccastillo0007** [comment]
no sé que tiene que ver el domicilio fiscal con agregar otro filtro de búsqueda ?

**Comment by RigoFlores** [comment]
Lo que digo, es que mostrar ahí el domicilio fiscal del emisor, prácticamente no agrega valor alguno.
Si en lugar de mostrar el domicilio fiscal, se pone un tercer criterio de búsqueda, que sería el ID del cliente, pues eso sería lo ideal, ya que pues el nombre corto ayuda a recordar, cuando no te sabes el RFC o el nombre.

Que tienen que ver?, no nada... solo que el filtro sería de muuucho mayor utilidad que el domicilio fiscal del emisor.

**Comment by jccastillo0007** [comment]
fixed
