### ISSUE TITLE
v2cero - pantalla de facturación CFDI (nombre), ajustar a Carta Porte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2235]
Cuando el tipo es ingreso, uno de los nombres dice Carta Porte Ingreso... está redundante el ingreso, debe ser simplemente Carta Porte, así justo como se muestra cuando se trata de tipo Traslado.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ok, si ya quedó.
No había visto que en egreso aparece nómina. Esto es incorrecto.

El único CFDI de tipo egreso es Nota de Crédito (y creo que existe otro, pero ya no lo recuerdo, al parecer nota de cargo que ya no se ocupa).
Lo que es un hecho, es que nómina es del tipo nómina, y no del tipo egreso. Hay que quitarlo de esa lista de egreso.

**Comment by jccastillo0007** [comment]
fixed, aunque no pude ponerle el acento jojojo

**Comment by RigoFlores** [comment]
Oyes, pero al nómina no se va a generar desde esa pantalla, o sí??
Si se hace como ahora mismo lo tenemos, no debe aparecer nómina ahí.

C

**Comment by jccastillo0007** [comment]
cierto, deja lo quito... te dije que es mejor manejar los catálogos desde una tabla en la base de datos.

**Comment by RigoFlores** [comment]
pues no tanto que me dijeras, hace muuuchos años lo he pedido, y no entiendo porqué no está así en esta nueva versión, jejeje
