### ISSUE TITLE
v2cero - pantalla de facturación - agregar producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2236]
No coinciden los productos del catálogo con los que aparecen en la lista de agregar producto.
Pareciera que está tomando la lista de otro RFC o no se de donde...

**Comment by RigoFlores** [comment]
por ejemplo, el producto cuyo ID es **_+milCaracteres_**, no lo muestra.

**Comment by jccastillo0007** [comment]
el problema era que estábamos manejando un campo llamado name... pero que realmente no se usa... 

ya está mostrando los datos de correctos, no eran de otro cliente, solo que el campo name esta vacío
