### ISSUE TITLE
v2cero - nombre del PDF no está normalizado al descargarlo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2237]
Ni cuando se generó, ni desde la pantalla de consultas.
En el chrome no puedo probar, porque se queda en blanco la pantalla, no carga la app

**Comment by RigoFlores** [comment]
eliminé las cuquis y le di permitir ventanas emergente y con eso ya los descarga.
Pero el nombre del archivo PDF no está normalizado, son nombres tipo aleatorios.

<img width="450" alt="nombresPDF" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/129bda6c-2ff2-43a7-bf48-d5191dee5ea3">

Y el XML no lo descarga, lo muestra en el browser...

**Comment by jccastillo0007** [comment]
La v2, esta usando el GUID como nombre del archivo, le ves algún problema?

**Comment by jccastillo0007** [comment]
A mi también me muestra el xml en pantalla, en lugar de descargarlo, voy a ver si se puede cambiar eso desde el código.

**Comment by RigoFlores** [comment]
> La v2, esta usando el GUID como nombre del archivo, le ves algún problema?

jajaja, pues claro que si.
Los archivos deben identificarse por su nombre. 
Asi como ahora mismo (serie, folio, emisor, receptor, fecha y hora):

FE260_GOCE621026BE5_CMA811126AW9_21Sep2023_074938

**Comment by jccastillo0007** [comment]
Eso ya no será posible... ahora solo se pueden almacenar con GUID en lugar de fecha... tal vez podría quedar así:
FE260_GOCE621026BE5_CMA811126AW9_GUID... el tema es que el manejo de la fecha le agrega mucha complejidad para poder encontrar el archivo después.

**Comment by RigoFlores** [comment]
Y que pasará si emites varias facturas el mismo día para el mismo receptor?
No se complica la búsqueda?
el formato de fecha podría cambiar, por ejemplo:  DDMMAA_HHMMSS

eso ayuda de alguna manera?

Quizás al menos la fecha, aunque la hora no se incluya.

**Comment by jccastillo0007** [comment]
El GUID es único, por eso la idea de usarlo en el nombre, en lugar de fecha.

**Comment by RigoFlores** [comment]
pues si no hay opción...
te refieres el UUID del SAT, veldá?

Realmente ese si es irrepetible, pero poca información brinda. 
Leer uno u otro, es lo mismo, no se entiende, jejeje.
Pues entonces hagámoslo así.

y no olvidar el tema del XML

**Comment by jccastillo0007** [comment]
el formato quedo:
SERIE+FOLIO+_+EMISOR+_+RECEPTOR+_+GUID

**Comment by RigoFlores** [comment]
pues no, le sigue nombrando raro al archivo...

por ejemplo: 2rtIow9J.pdf

**Comment by jccastillo0007** [comment]
Eso va a ser tema de tu navegador... yo si logro descargarlo bien, desde chrome y firefox... a menos que sea la MAC

**Comment by RigoFlores** [comment]
en qué momento lo descargas... cuando se genera la factura o desde las consultas?
también podría ser eso...
creo que yo lo probé, cuando se genera la factura.

**Comment by jccastillo0007** [comment]
en ambos lugares se puede

**Comment by RigoFlores** [comment]
En consultas, NO lo puedo descargar. 
Si aparecen los íconos, pero no hace nada. De hecho, es como si estuvieran deshabilitados.

Y cuando se genera, si se descarga pero con otro nombre... por ejemplo la factura de ahorita que hice, lo descargó como ZjqDxyy8.pdf

**Comment by jccastillo0007** [comment]
si, hay un problema en consultas que debo revisar...
pero el nombre del archivo es un pedo de tu explorador... chiaaa

**Comment by jccastillo0007** [comment]
fixed, el problema de los archivos en consultas

**Comment by RigoFlores** [comment]
sigue lo del nombre incorrecto en el PDF y el XML no lo descarga. 
Abriré otro ticket para esos problemas.
