### ISSUE TITLE
v2cero - al intentar timbrar una factura, no incluye la clave de unidad, y marca error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2238]
Intenté agregando el producto cuyo ID es "+milCaracteres. "
La unidad es SERVICIO - E48
Además le está agregando el ID a la descripción, y son cosas independientes:
Así manda el nodo concepto, sin la unidad y agregando el ID a la descripción

cfdi:Concepto ClaveProdServ="25101503" NoIdentificacion="+milCaracteres" Cantidad="1.00" Descripcion="**+milCaracteres** lineas de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en descripción&#10;lineas de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en descripción&#10;lineas de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en descripción&#10;lineas de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en descripción&#10;lineas de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en descripción&#10;lineas de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en descripción&#10;lineas de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en descripción&#10;lineas de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en descripción&#10;lineas de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en descripción&#10;linea10de 100 caracteres para probar que pasa cuando tienes mas de 1,000 caracteres en desc" ValorUnitario="1000.000000" Importe="1000.000000" ObjetoImp="02"

**Comment by jccastillo0007** [comment]
Notaste que el problema es que al agregar el producto a la factura, no auto-seleccionó la unidad, y por eso no la manda. ese es un defecto que no estas reportando.
Si seleccionas la unidad, ya manda bien los datos, chiaaaa
Lo de la descripción es oooootro error diferente.

**Comment by RigoFlores** [comment]
Cuando agregas un producto, existe la opción de modificar la unidad.
Realmente esa opción, no se requiere, ya que EN EL CATÁLOGO DE PRODUCTOS SE DEFINE SU UNIDAD, y el cliente lo captura ahí, de manera obligatoria.

No recuerdo de donde surgió que se podía cambiar al agregar producto, pero incluso podríamos prescindir de ello.

Es decir, al agregar producto debe cargar la unidad capturada. HOY NO SE NECESITA ELEGIR LA UNIDAD DESDE LA PANTALLA DE AGREGAR PRODUCTO. Es opcional, pero no se requiere.

**Comment by RigoFlores** [comment]
ya hice la prueba, eligiendo la unidad desde la pantalla de agregar producto, y medio jaló.
Si hay que corregir eso.

Otro detalle aquí, es que al agregar producto, la aplica la retención. Recordar que solo carga por omisión, el primer IVA dado de alta.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Voy a cerrarlo con lo de la unidad, pero quedó chueco lo del impuesto.
El que debe cargar por omisión es el IVA trasladado, únicamente.

y ahora lo que hace, es que no carga el IVA trasladado, pero SI carga el impuesto retenido, es decir está al revés.
