### ISSUE TITLE
ERP - NOMINA EMPRESARIAL NO ACTUALIZA LAS FECHAS EN LOS INDIVIDUALES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#224]
CUANDO GENERAS LA NOMINA EMPRESARIAL, DEBE ACTUALIZAR LAS FECHAS DE INICIO, FIN Y DE PAGO EN LOS REGISTROS INDIVIDUALES.
CON ELLO AL CONSULTAR DE MANERA INDIVIDUAL, CONOCEREMOS LAS FECHAS DEL ÚLTIMO RECIBO GENERADO

**Comment by jccastillo0007** [comment]
Done.
