### ISSUE TITLE
v2cero - catálogo de productos, edición, no debe agregar dato extra vacío.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2240]
intenté con 2 productos, cuyo ID son:  anticipo y 01010101, pero marca error al editarlos y darle actualizar.

**Comment by RigoFlores** [comment]
igual este producto con id "COMPUTADORAS-HP"

Error: "hubo un problema al actualizar el producto"

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
negativo, ahora no habilita el botón de actualizar, aún cuando ya se capturaron los datos obligatorios.
es con la cuenta de IIA
<img width="818" alt="PRODUCTO" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/4829bacc-50bf-435e-8cdc-3b7e4ed39ce9">

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
CHIAAAA... SIGUE IGUAL...

<img width="808" alt="PRODUCTOS" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/bf08f8fd-d4b5-4be1-8abe-9fdc5803dcfd">

**Comment by jccastillo0007** [comment]
asegúrate de no tener datos extras vacíos...

los datos extras son opcionales, pero si le das agregar datos extras y no capturas nada, no te deja salvar...

**Comment by RigoFlores** [comment]
no, no le doy agregar nada, solo estoy probando con la edición de datos básico. No habilita el botón de editar.

<img width="514" alt="PRODUCTOS" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/4cbfb395-3c47-4b54-9d13-7f259520d783">

**Comment by jccastillo0007** [comment]
chiaaa, debes quitar el row de datos extras o ponerle un valor, pero no vacío...

**Comment by RigoFlores** [comment]
OK, entonces el issue se convierte ahora, en que cuando se edita un producto, NO DEBE PONER DATOS EXTRA VACÍOS POR DEFAULT, a menos que el usuario los agregue.

**Comment by jccastillo0007** [comment]
Eso no lo hace... lo que paso con ese producto, es que se agrego un dato extra cuando no se validaban... chiaaa
