### ISSUE TITLE
v2cero - después de timbrar una factura, no limpia la pantalla

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2242]
Una vez timbrada la factura, debe limpiar la pantalla, como aparece cuando se accede a ella por primera vez en la sesión

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
negativo, sigue igual.

<img width="312" alt="pantalla" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/887eb262-6c29-498b-b1a6-062862bd5eee">

**Comment by jccastillo0007** [comment]
ups, sorry, se me olvido liberar los cambios de ayer de Victor, hoy lo subo

**Comment by jccastillo0007** [comment]
ahora si, fixed
