### ISSUE TITLE
v2cero - agregar producto a la factura. ¿Cómo se captura la información complementaria?

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2243]
Por ejemplo, en este producto agregado a la factura, en donde se captura la info complementaria?

<img width="690" alt="infocomplementaria" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/0f5727e9-092c-443a-b584-168b6d7f5874">

**Comment by jccastillo0007** [comment]
que no es la descripción... me confunde mucho los campos:
producto (que no es el nombre si no como el identificador del producto)
descripción
descripción complementaria

**Comment by RigoFlores** [comment]
producto, debe cambiar a ID producto, ya que así se captura en el catálogo y para evitar confusiones.
descripción, es el parámetro de concepto del XML, es lo que se incluye en el XML.
Descripción complementaria, es información adicional que se envia al pdf a nivel producto como 	

<field name="descripcionComplementaria" class="java.lang.String"/>

, que ahora mismo se captura aparte y tenemos la opción de incluirla o no en el PDF.

<img width="749" alt="infocomplementaria" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/97383463-8d87-471d-bf9d-09d692a3ed2c">

Entonces, pues ahí está faltando donde capturar esa información.
