### ISSUE TITLE
v2cero - pantalla de facturación, al teclear el RFC no presenta coincidencias en la lista

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2244]
El cliente se selecciona por nombre o por RFC. 
Sería muy bueno agregar el ID en vez  del lugar de expedición. Lugar de expedición es del emisor, y eso no cambiará a menos que nosotros lo cambiemos. No agrega valor en esa pantalla.

Total, que si tecleas parte del nombre, después de cierto tiempo, presenta la coincidencia.
Eso mismo no está pasando con el RFC.

**Comment by jccastillo0007** [comment]
done
