### ISSUE TITLE
v2cero - facturación, agregar producto, no incluir los impuestos retenidos por default

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2245]
Como lo tenemos ahora mismo, funciona muy bien.
Solo agrega por omisión el impuesto trasladado que se haya dado de alta al inicio.
Generalmente es el IVA del 16%.

O incluso, hasta podría indicarse en el catálogo de impuestos, cuál impuesto se agrega por omisión al producto cuando se carga en la factura. Esto ya es mas sofisticado, pero quizá ayudaría.

por lo pronto, NO tiene que agregar impuestos retenidos por default al producto.

**Comment by jccastillo0007** [comment]
done
