### ISSUE TITLE
conector v2cero - si el archivo incluye serie y folio, marca error en la serie

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2247]
Ahora mismo (con el conector actual de producción), si el archivo contiene la serie y el folio, entonces NO es necesario que la serie exista en el facturaT.
En la nueva versión, si la serie no se ha capturado en la plataforma v2cero, entonces marca error de "Folios no Disponibles".

No es necesario que exista la serie, si en el archivo se incluye serie y folio.
Para el caso que solamente exista la serie, entonces si debe existir la serie en la plataforma, para saber cuál folio sigue.

La serie como dato, es requerido. El folio es opcional, ya que el cliente podrá o no llevar el control del consecutivo.

**Comment by jccastillo0007** [comment]
correcto, la serie debe existir en efacturat v2, ya que ahora ahí están todos los catálogos de los clientes, ya no hay nada en standalone
