### ISSUE TITLE
conector Galpon - envía el número de ticket en el concepto 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2251]
el concepto únicamente debe ser "CONSUMO DE ALIMENTOS".

Está incluyendo el número de ticket. Ahora mismo lo manda así (en 2 renglones):
1016
consumo de alimentos

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
sigue igual...

<img width="671" alt="ticket" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/353b9fb5-2eb8-4712-99a4-7a8c761ef3c8">

**Comment by jccastillo0007** [comment]
fixed
