### ISSUE TITLE
conector Galpon - no está enviando la variable de exportación al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2252]
Se muestra vacía.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
sigue igual...

<img width="228" alt="exportacion" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/62bcabe0-e76f-4d36-b8b3-edad9fa52a14">

**Comment by jccastillo0007** [comment]
fixed
