### ISSUE TITLE
Plataforma Galpon - el consecutivo de folios lo debe llevar la plataforma

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2254]
Así como en abastos.
Las series de FR y FI  (para factura con registro y factura al instante respectivamente).

Ahorita está tomando el folio del número de ticket, pero no todos los tickets serán facturados, entonces será un relajo la numeración de los folios de las facturas.

**Comment by jccastillo0007** [comment]
fixed, deben existir las series en el descargat
