### ISSUE TITLE
plataforma Galpón - cuando se captura un ticket o el total, borrar íconos de PDF y XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2256]
Todo inicia cuando se emite correctamente una factura.

Después se empieza a capturar los datos de ooootro ticket.
Los íconos de PDF y XML, se mantienen abajo. Si le das facturar, el usuario no sabrá si esos íconos corresponden a la nueva factura o a la anterior (en caso de error será la anterior).

Entonces, si se hizo una factura, y se quiere capturar otra, al momento de teclear el número de ticket y el total, y cuando se le da click en el ícono de agregar (+), quitar los íconos de PDF y XML de la parte inferior.

**Comment by jccastillo0007** [comment]
done
