### ISSUE TITLE
CFDI con CCE, incluye el nodo de impuestos vacío, cuando no incluye impuestos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2257]
En un CFDI estándar, cuando el IVA que se elige es NA, no debe incluir el nodo de impuestos vacío. ( <cfdi:Impuestos/> )
En este caso se trató de un CFDI con complemento de comercio exterior, pero el error se presenta a nivel del nodo concepto, es decir fuera del complemento.

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="USD001" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="PRODUCTO EN USD" ValorUnitario="100.0000" Importe="100.000000" ObjetoImp="01"/>
    </cfdi:Conceptos>
    **<cfdi:Impuestos/>**

<img width="529" alt="impuestos" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/e78d3cb9-b55c-4aed-b83e-afeda88fbe64">

**Comment by RigoFlores** [comment]
datos para la prueba...
NumRegIdTrib="123456789"
FraccionArancelaria="0101299999" UnidadAduana="06"
Receptor Rfc="XEXX010101000" Nombre="OMEGA TOOL CORP" 

el IVA es el que dice 0, que está configurado como NA.


<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cce11="http://www.sat.gob.mx/ComercioExterior11" Version="4.0" Folio="327" Fecha="2023-10-21T11:12:02"  SubTotal="100.00" Moneda="USD" TipoCambio="18.287300" Total="100.00" TipoDeComprobante="I" Exportacion="02" MetodoPago="PUE" LugarExpedicion="61957" xsi:schemaLocation="[http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd http://www.sat.gob.mx/ComercioExterior11 http://www.sat.gob.mx/sitio_internet/cfd/ComercioExterior11/ComercioExterior11.xsd](http://www.sat.gob.mx/cfd/4%20http:/www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd%20http:/www.sat.gob.mx/ComercioExterior11%20http:/www.sat.gob.mx/sitio_internet/cfd/ComercioExterior11/ComercioExterior11.xsd)">
    <cfdi:Emisor Rfc="IVD920810GU2" Nombre="INNOVACION VALOR Y DESARROLLO SA" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="XEXX010101000" Nombre="OMEGA TOOL CORP" DomicilioFiscalReceptor="61957" ResidenciaFiscal="CAN" NumRegIdTrib="123456789" RegimenFiscalReceptor="616" UsoCFDI="S01"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="73152100" NoIdentificacion="USD001" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="PRODUCTO EN USD" ValorUnitario="100.0000" Importe="100.000000" ObjetoImp="01"/>
    </cfdi:Conceptos>
    <cfdi:Impuestos/>
    <cfdi:Complemento>
        <cce11:ComercioExterior CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="EXW" Subdivision="0" TipoCambioUSD="18.2873" TipoOperacion="2" TotalUSD="100.00" Version="1.1">
            <cce11:Emisor>
                <cce11:Domicilio Calle="calle huetamo, michoacan" CodigoPostal="61957" Estado="MIC" Municipio="038" Pais="MEX"/>
            </cce11:Emisor>
            <cce11:Receptor NumRegIdTrib="123456789">
                <cce11:Domicilio Calle="AV UNIVERSIDAD" CodigoPostal="A1B 2C3" Estado="AB" Localidad="2o PISO" Pais="CAN"/>
            </cce11:Receptor>
            <cce11:Mercancias>
                <cce11:Mercancia CantidadAduana="1.0" FraccionArancelaria="0101299999" NoIdentificacion="USD001" UnidadAduana="06" ValorDolares="100.00" ValorUnitarioAduana="100.00"/>
            </cce11:Mercancias>
        </cce11:ComercioExterior>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by jccastillo0007** [comment]
con el producto que usaste si agregó impuestos... 
No sé como seleccionar un impuesto con NA

**Comment by RigoFlores** [comment]
en el primer comentario de este ticket, viene la imagen de cómo se selecciona el impuesto que tiene NA, es decir que no aplica.
Chiaaaa

**Comment by jccastillo0007** [comment]
pues no pude timbrar por problemas de datos, pero vi que el XML ya lo genera sin el nodo de impuestos
