### ISSUE TITLE
CCE - no está incluyendo los datos del destinatario en el CCE, aún cuando se capturan.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2258]
Para reproducir el escenario en pruebas:

Emisor IVD
Cliente XEXX - sucursal PERU
Moneda USD
TC USD para el día 23 oct : 18.2873; si la prueba es el 24 oct 18.2343  
Producto con ID: 55111600
impuesto trasladado: IVA 0.0 (realmente NA)

Los datos del complemento, aquí están, pero no está incluyendo el nodo de destinatario en el complemento y eso es parte de lo que necesita el cliente:

<img width="628" alt="CCE" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/a940ebb3-34c2-44e1-866a-0ce5fc6a801e">

**Comment by RigoFlores** [comment]
con la versión  3.0 del CCE, este issue renace

**Comment by jccastillo0007** [comment]
Fixed.

El destinatario estaba definido solo para tipo de documento = Traslado... ya le quite esa restricción

**Comment by RigoFlores** [comment]
En algún momento quizá existió esa restricción. 
Creo que ahora ya no.
En optibelt, me parece que no, y ellos lo estarán ocupando.
