### ISSUE TITLE
conector v2cero - reportar el importe de los impuestos a nivel concepto, con 2 decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2259]
Puede ser redondeado o mejor truncado.
este tema lo tenemos para cualquier lugar donde se calculen los impuestos trasladados. No se si solo sea del hostal, de la v2cero en general o donde está el problema, pero creo que esos impuestos deberían calcularse solo en un punto.

No se porqué aún lo reporta en este caso con 6 decimales:

                    <cfdi:Traslado Base="216.527197" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="34.644351"/>

Para reproducir, el ticket es 1918 y el importe es 258.75, es un archivo del hostal, que finalmente ya está trabajando.

**Comment by jccastillo0007** [comment]
listo, pero ya no timbra

**Comment by RigoFlores** [comment]
el asunto es que a nivel del nodo general de impuestos, se debe reportar tanto la base como el importe a dos decimales.
Mira:

    <cfdi:Impuestos TotalImpuestosTrasladados="3227.59">
        <cfdi:Traslados>
            <cfdi:Traslado Base="20172.413793" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="3227.59"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

a nivel de concepto, si soporta 6 decimales, pero a nivel del nodo impuestos, no.
Esta factura con folio FR 18 del 22 de octubre, en pruebas emisor IIA, si lo reportó a 2 decimales:

<cfdi:Impuestos TotalImpuestosTrasladados="66.95">
<cfdi:Traslados>
<cfdi:Traslado Base="418.41" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="66.95"/>
</cfdi:Traslados>
</cfdi:Impuestos>

**Comment by jccastillo0007** [comment]
fixed
