### ISSUE TITLE
Color incorrecto del header y footer en el Galpón

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2261]
No se está mostrando en la página principal, antes de firmarse o de ir a factura al instante.
Adicionalmente el logo queda muy grande, y deforma el header.

si hacemos este ajuste en el css de los estilos, se ve bien.

<img width="208" alt="img" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/9c55e743-de52-40d8-a46c-7455b0ecc9bd">

adicionalmente el color del header y footer, ya lo había solicitado, y requiere modificar en el css:

--azulprincipal: #414924;

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
No está mostrando el color correcto del header y footer

**Comment by jccastillo0007** [comment]
fixed... yo le había quitado el - por accidente
