### ISSUE TITLE
Carta Porte 3.0 - Cambios en el header

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2264]
Para la versión 3.0, estos son los cambios en el header del complemento de carta porte:
Se agregarán los siguientes parámetros.

a) Calcular el idCCP (es un UUID que se incorpora al header). Obligatorio
b) Régimen Aduanero (tomado de un catálogo)
c) RegistroISTMO (vacío o "Sí"; podría ser un checkbox)
d) UbicaciónPoloOrigen (tomado de un catálogo)
e) UbicaciónPoloDestino (tomado de un catálogo)

Los puntos b al e, son opcionales.
Si el punto c se captura, entonces d y e, se vuelven obligatorios.

Si estos cambios los hiciéramos en la pantalla actual de captura de addenda, la captura de los datos va al inicio de la pantalla.
Enviar las variables al PDF con el mismo nombre.

**Comment by jccastillo0007** [comment]
a y b listos

**Comment by RigoFlores** [comment]
Lo cerraremos, pero es probable que lo lleguen a pedir.
Y entonces lo retomamos.
