### ISSUE TITLE
Implementar Carta porte 3.0 - XSD

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2269]
Aquí el XSD

https://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd

Aquí los catálogos:

http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/CatalogosCartaPorte30.xls

**Comment by jccastillo0007** [comment]
done
