### ISSUE TITLE
Ajuste en el css del Galpón

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2272]
Seguramente aplica para todos, pero por lo pronto en el galpón.
Agregar esto al archivo de estilos:

    #form-facturacion**_,
	#opciones_**

Cambiar esta linea en el archivo de estilos, me parece se llama "styleDT.css"
AHORA MISMO DICE:

@media screen and (max-width: 640px) {
    body{
        min-width: 360px;
        max-width: 640px;
        width: 100%;
    }

   

    #contenido{
        width: 360px;
        margin-left: calc( ( 100% - 360px ) / 2 );
    }
    #form-facturacion{
        width:360px;
        margin-left: calc( ( 100% - 360px ) / 2 );
    }

Cambiarlo a:

@media screen and (max-width: 640px) {
    body{
        min-width: 360px;
        max-width: 640px;
        width: 100%;
    }

   

    #contenido{
        width: 360px;
        margin-left: calc( ( 100% - 360px ) / 2 );
    }
    #form-facturacion,
	#opciones{
        width:360px;
        margin-left: calc( ( 100% - 360px ) / 2 );
    }

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
solo en producción lo puedo validar, ya que pru no corre en el móvil...

**Comment by RigoFlores** [comment]
bueno, el AFT (AutoFaturaT) si corrió en pru en el cel de la tia, pero no en mi cel.

Ya jaló en pru... (colores y cambio de css del galpón)  hay que llevarlo a pro.
