### ISSUE TITLE
Implementar la versión base del complemento de carta porte 3.0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2273]
Será la iteración 1, que consta de lo siguiente:

1) Cambiar las URL que tengan que cambiar de acuerdo a la spec.

http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte30.xsd

2 ) Noté que en el esquema se agregó un nodo a nivel de mercancía, que hoy en día solo era un parámetro o atributo a nivel de mercancía. Es el nodo de DocumentacionAduanera. Se elimina el parámetro de pedimento a nivel mercancía y se incorpora este nodo que es opcional. Aquí hay que capturar 4 datos para este nodo. En la pantalla de mercancía, se le hace su apartado con la etiqueta de "Documentacion Aduanera". TipoDocumento, NumPedimento, IdentDocAduanero, RFCImpo. Si se captura esta sección, el tipo de documento es obligatorio.

3) A nivel de header agregar el parámetro requerido que es idCPP. Es genérico, y lo estaremos generando internamente por la aplicación.

4) A nivel catálogo de transporte, agregar el parámetro PesoBrutoVehicular en la pantalla de captura, e incluir lo en el XML.

5) Enviar los datos nuevos al PDF donde corresponda, con el mismo nombre del parámetro.

Incluso, lo básico básico, no incluiría el punto 2, ya que ese nodo es opcional, pero ahora mismo, nosotros soportamos el tema de pedimento y tenemos clientes en frontera que si ocupan esos datos, por ello lo estoy incluyendo.

Aquí te dejo un ejemplo de la versión 3.0 del carta porte básico.

[CartaPorteIngreso30.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/13393697/CartaPorteIngreso30.xml.txt)

**Comment by jccastillo0007** [comment]
que lleva aquí? idCPP

**Comment by jccastillo0007** [comment]
para el PDF, los datos de mercancías se mandan como datoextra7, y también en un objeto llamado JasperMercanciasBean, no sé cual es la diferencia en el pdf.

**Comment by RigoFlores** [comment]
Ya timbró cuando se trata de traslado de mercancías locales. Vientos.

Ahora, para probar lo del nuevo nodo de documentacionAduanera, hijo de mercancia, se debe validar lo de transportar mercancía desde un país extranjero hacia México.

Para ello, está faltando un dato a nivel del header del complemento que en el estándar dice opcional, pero me indica finkok que debe ir de acuerdo a su matriz de validaciones.
OK, entonces, SOLAMENTE en caso de que el atributo TranspInternac="Sí", debe solicitarse un dato adicional en la pantalla de captura:

**_RegimenAduanero_**, que se toma del catálogo c_RegimenAduanero. 
Para su captura, este listado se coloca debajo de destino.

http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/CatalogosCartaPorte30.xls

Si TranspInternac="No", entonces la captura de ese dato se inhibe o se oculta.

**Comment by RigoFlores** [comment]
En el header, ya en la versión completa, se deberán capturar estos 3 datos adicionales:

RegistroISTMO  (si está vacío no se envía. Unico valor permitido Si).
UbicacionPoloOrigen  (si el atributo anterior se captura con un Si, entonces se envía esta dato del catálogo c_RegistroISTMO)
UbicacionPoloDestino  (mismo caso que el anterior)

Cómo ves, si aprovechando que agregarás la captura opcional del régimenAduanero, se agregan de una vez estos 3 datos?

**Comment by jccastillo0007** [comment]
lo del ISTMO hay que moverlo al ticket de la versión avanzada o completa... para no compliar la básica, ya que son nuevos catálogos. No hay que mezclar el scope de diferente tickets

**Comment by RigoFlores** [comment]
ok

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Cuando se incluye el atributo de régimenAduanero y el nodo de documentación aduanera, no timbra.
Dice finkok que le enviemos la cadena original. Esta es su respuesta:

_**Comentarle que el error se genera porque el atributo sello no se genero de forma correcta. Esto puede deberse a que hubo un error al momento de generar la cadena original o no se utilizaron los CSD correctos. Si gusta puede compartirnos su cadena original para ayudarle a verificar.**_

**Comment by RigoFlores** [comment]
Esto falta atender para enviar a finkok lo que pide.
En pruebas, con IIA emisor, receptor la tia, producto flete.
Complemento:  el origen canadá, el destino latia qro, mercancía me parece que es la primera de la lista (que tiene llenado lo del nodo de pedimento, no puedo asegurarlo porque está abajo ahora mismo pru).

**Comment by jccastillo0007** [comment]
Cadena original:
||4.0|73|2024-01-03T09:48:54|03|30001000000500003433|0|MXN|1|0.00|I|01|PUE|65258|IIA040805DZ4|INDISTRIA ILUMINADORA DE ALMACENES|601|TIA101020BP4|TECNOLOGIAS DE INFORMACION APLICADA|76090|601|G03|0.00|002|Tasa|0.160000|0.00|0.00|3.0|CCC88AA9-3472-4718-84AB-08BBF00425F9|S??|IMD|Entrada|CAN|01|11111.0|Origen|OR000001|XEXX010101000|ORIGEN O DESTINO EN CANADA|2024-01-01T00:00:00|AB|CAN|52142|Destino|DE000001|TIA101020BP4|TI APLICADA QUERETARO|2024-01-25T00:00:00|11111.0|AV UNIVERSIDAD|361|PISO 2|0163|014|QUE|MEX|76160|2500.0|KGM|1|25101503|9BD265553M9182527 415554 RAM PROMASTER RAPID|1.0|H87|PIEZA|30/40/30cm|2500.0|500000.0|MXN|0101909900|01|23 80 1643 3001054|456|CAAJ7506072P2|TPAF15|12345678|C2R2|1500.0|ABC123|2022|AXXA|AXXA12345678|CTR003|ABC6969|CTR004|TAMO321|01|FOPR681125BQ0|FED123|RIGOBERTO FLORES||

**Comment by jccastillo0007** [comment]
sello:
LFq9/8oBVX/kC25AeMXMJZF/HKFFSL7xFpHJUSF6K2qVtTU4g5ScOlOTHlDYKr4BRkf5SalWoENHDWgnZ0wvVktYjsa7J/WfMCL9WHO/RdEtAbuhsaccvUgR384nj7RVRwEgAMmD1xBNi4P+lm/aFgXOgp3Q9K4OXNW8F3O+kZq/chMbe9h+2DdATrLVCAv7suI2pgNYdLiAQJdB2HWs7GNHxf8iCboQhZlQxRXaafThXVvBtiq3ny9/8QLiq1uG//b+X0NOE9qYajQQ5naJ/pCaaO6sgR0P5peIhaoi83QHdQ4ZmEStr7YCy7QAemRTqIKWalVrCOMYO9pc0MZgmA==

**Comment by RigoFlores** [comment]
Generé nuevamente una prueba, porque no la capturaste correctamente
y aquí está la cadena original:

2024-01-04 16:44:33,309  INFO [http-nio-8080-exec-49] (CFDManager.java:1358) - Original Stream : [||4.0|73|2024-01-04T15:44:31|03|30001000000500003433|1000.00|MXN|1|1120.00|I|01|PUE|65258|IIA040805DZ4|INDISTRIA ILUMINADORA DE ALMACENES|601|TIA101020BP4|TECNOLOGIAS DE INFORMACION APLICADA|76090|601|G03|78101800|FLETE|1.00|NA|NA|FLETE SERVICIO DE FLETE|1000.000000|1000.000000|02|1000.000000|002|Tasa|0.160000|160.00|1000.000000|002|Tasa|0.040000|40.00|002|40.00|40.00|1000.00|002|Tasa|0.160000|160.00|160.00|3.0|CCC9D61E-BFF8-43C1-9337-78ED34647F0C|S??|IMD|Entrada|CAN|01|1674.0|Origen|OR000001|XEXX010101000|ORIGEN O DESTINO EN CANADA|2021-12-01T00:00:00|AB|CAN|52142|Destino|DE000001|TIA101020BP4|TI APLICADA QUERETARO|2021-07-02T00:00:00|1674.0|AV UNIVERSIDAD|361|PISO 2|0163|014|QUE|MEX|76160|7500.0|KGM|1|25101503|9BD265553M9182527 415554 RAM PROMASTER RAPID|3.0|H87|PIEZA|7500.0|1500000.0|MXN|0101909900|01|23 80 1643 3001054|456|CAAJ7506072P2|TPAF15|12345678|C2R2|1500.0|ABC123|2022|AXXA|AXXA12345678|CTR003|ABC6969|CTR004|TAMO321|01|JUME890620KB3|LIC1234FEDERAL|JUAREZ MENDEZ EDGAR||]


en esta sección está incorrecta:

78ED34647F0C|S??|IMD|Entrada

debe ser Sí, es decir S mayúscula y la í con acento.

**Comment by RigoFlores** [comment]
Vamos a considerar la versión base, sin el tema de transporte internacional... para ello abriremos otro ticket.
