### ISSUE TITLE
Generar el FacturaT-Ticket (FTT)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2274]
El FacturaT-Ticket (FTT) es una aplicación web para enviar datos de una remisión a la plataforma de facturación.
Con ello, el receptor podrá generar sus propias facturas, aún cuando el emisor no cuente con un sistema administrativo, o incluso que no tenga computadora en sus instalaciones.

Debe ser aplicación web, responsiva. Muy importante, porque muy probablemente, lo abran en un celular o tablet.
Debe tener su usuario y contraseña, con ello conoceremos los datos del emisor.
En su versión básica, capturarán: número de ticket, total, forma de pago, y fecha (por omisión, la actual), correo electrónico y número de whatsApp.

En la plataforma de Factura-T, con la cuenta del emisor se dará de alta un producto, cuyo ID será TCKT-001, y ese será el producto que se agregará en la factura. Claro, ya en la factura se debe respectar que el ID del producto, sea el número del ticket, o en su caso se agregue al concepto.

En versión básica, solo se incluirá un producto por cada factura. Por ejemplo, la descripción de ese producto podría ser: consumo de alimentos, servicio automotriz, mantenimiento, etc.

Algo que ayudaría mucho, es que se capture un número celular, en cuyo caso por whatsApp se enviará la siguiente info:
a) Nombre comercial del Emisor
b) Número de Ticket
c) Total
d) Liga donde se puede generar la factura (la URL de la Plataforma para Clientes de ese emisor).

Cuando acceda a dicha liga, ya estará precargado el ticket. 
Con ello el usuario (receptor) solo capturará sus datos fiscales.

Si no desea dar su whatsApp, también el FTT, generará un CBB con todos los datos para ir a FI con el ticket ya precargado.

Según entiendo, se tiene casi todo en la v2cero del web, solo hay que quitar casi todo y dejar lo que se ocupa para generar esta nueva aplicación.

En versión avanzada, podrán agregar varios productos al ticket, pero eso ya sería mas adelante.

**Comment by jccastillo0007** [comment]
Esto no será posible en la versión básica... ya que no se tiene actualmente:

**Algo que ayudaría mucho, es que se capture un número celular, en cuyo caso por whatsApp se enviará la siguiente info:
a) Nombre comercial del Emisor
b) Número de Ticket
c) Total
d) Liga donde se puede generar la factura (la URL de la Plataforma para Clientes de ese emisor).

Si no desea dar su whatsApp, también el FTT, generará un CBB con todos los datos para ir a FI con el ticket ya precargado.**


Mas bien será por email.

**Comment by RigoFlores** [comment]
Podemos iniciar con el email, pero posteriormente lo haremos con wa también. Que el receptor elija cómo quiere recibirlo.

**Comment by RigoFlores** [comment]
El título de la pantalla será:

"Capturar Datos para Factura"

Los botones, serán los íconos como los del AFT... para indicar:
Nuevo
Limpiar
Enviar
Consultar

Las etiquetas que se mostrarán fuera de las cajas de captura para cada dato serán:

Fecha
ID
Total pagado
Forma de Pago ( es un listado del catálogo del SAT)
Correo Electrónico
whatsApp

Las etiquetas que se mostrarán dentro de las cajas de captura para cada dato serán:

Fecha actual (será su valor por omisión, la fecha actual).
Número de ticket, Nota de venta, Folio, etc.
No incluye propinas
Seleccione uno 
email del cliente
teléfono para whatsApp

Por etiqueta interna, me refiero a lo que es muestra en amarillo (esto es un mero ejemplo, no es la pantalla que estamos tratando aquí).  
Las etiquetas externas son las que están fuera de la caja de captura:

<img width="579" alt="etiquetas internas" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/00f6c954-0f78-41d2-9618-dcbb1001a2e4">

**Comment by jccastillo0007** [comment]
Hmmm me parece que lo estas complicando mucho... y saturando la pantalla

de estos botones:
Nuevo
Limpiar
Enviar
Consultar

Solo se ocupa el de enviar, los otros no tienen mucho sentido.. después de enviar un ticket, se quedará limpia la pantalla

La pantalla que subiste no coincide con los campos, mejor no la subas que luego eso confunde mucho.

**Comment by RigoFlores** [comment]
Lo de consulta, servirá para eliminar una captura mal realizada, o prefieres que se pueda editar?
Al final, igual se debe consultar para editar o borrar.
Para los que están corriendo todo el tiempo, los todólogos del negocio, podrán consultar si ya capturaron o no un ticket, cuando no estén seguros si ya lo hicieron.

al menos esas 2 funciones se necesitan... los otros 2 botones, ya veremos si realmente se pueden omitir.

**Comment by jccastillo0007** [comment]
las consultas las podrán hacer en la plataforma web, desde  donde quieran
recuerda que el objetivo es hacer una versión simplificada de la pantalla de facturación que se tiene hoy en día, ahí no se hacen consultas... si empezamos a modificar la funcionalidad, entonces no estará tan rápido...
de otra forma, habrá que hacer otra pantalla de consultas...

**Comment by RigoFlores** [comment]
Imagina la situación... 

El encargado de cobrar, el mesero o alguna persona, capturará el ticket si se lo piden. Pueden presentarse 10,005 distractores que le hagan perder el foco.
De repente no recordará si ya capturó el ticket o no.
Al tener la posibilidad de consultar, lo podrá conocer.

Y si, efectivamente sería otra pantalla (la de consultas), misma que también ya existe. 
"Solo hay que despelucarla".

O podría existir un panel inferior mostrando la info de los últimos 20 tickets capturados.

**Comment by jccastillo0007** [comment]
no te digo... primero la primer pantalla que es fácil y práctica... ya que lo vendas entonces si hacemos cosas nuevas

**Comment by RigoFlores** [comment]
Pues ahí está el requisito
No habrá forma de editar, de borrar, ni saber que si hicimos o que no.
