### ISSUE TITLE
Galpón PRU, reporta erroneamente la tasa del ISH, debe ser 3.5 y reporta 16

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2275]
Checa el XML generado.

[FR34_IIA040805DZ4_TIA101020BP4_20Nov2023_143229.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/13419979/FR34_IIA040805DZ4_TIA101020BP4_20Nov2023_143229.xml.txt)

**Comment by RigoFlores** [comment]
ya vi que también en pro lo reporta mal.
En el PDF lo envía bien, pero no así en el XML. 
Chiaaaa.

Aplica para el Galpón en el layout del hotel. Aquí un arhivo de pruebas.

[hostal.csv](https://github.com/jccastillo0007/eFacturaT/files/13419992/hostal.csv)

**Comment by RigoFlores** [comment]
Aplica tanto para FI como para FR.

**Comment by jccastillo0007** [comment]
fixed, hay que usar el conector con fecha/hora = 202311201930
