### ISSUE TITLE
Conector Alteza - v2cero, no reporta el ISH, y el IVA concepto lo reporta a 6 decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2277]
A nivel concepto, el importe (del IVA) se reporta a 2 decimales.
Lo hemos dicho muuuuchas veces. Bueno, aquí nuevamente lo reporta a 6 decimales y por ello marca error. No por ello en sí, sino porque se calcula a 2 decimales y se reporta a 6.

y la otra, para Alteza, no está incluyendo el impuesto local, ISH del 3.5%

probé con este archivo.

[C33_NPG_20672.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/13453312/C33_NPG_20672.spf.txt)

**Comment by RigoFlores** [comment]
Actualmente en producción para El Galpón, si está reportando el IVA a 6 decimales.
La diferencia es que en pruebas, lo reporta a 6 decimales, peeeero lo calcula con 2 decimales... es decir, los últimos 4 decimales los reporta en 0000. Por ello genera problema.

Lo podrías reportar a 6 decimales, pero completo todo el cálculo.
La otra, es igualarlo a los conectores, donde se reporta el importe a 2 decimales.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
cómo lo valido???
en pru, con IIA no jaló..
