### ISSUE TITLE
Recuperar y subir, XML y PDF a producción del 2018 para el RFC emisor SADL740901FC6

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2278]
La depurada que se platicó, tendría que mantener 5 años atrás, mas el actual... y solo mantuvo 4 años atrás.
Pero bueno, pocos clientes lo han solicitado.
Optibelt (que prácticamnte ya no está con nosotros), y este otro cliente mencionado en este issue.

Hay que subir las facturas de este cliente, y no sé que pex con los complementos de pago de dichas facturas...
Por lo pronto los PDF y XML de factuas y notas de crédito.

**Comment by jccastillo0007** [comment]
hmmmm te los puedo enviar por correo, pero a que te refieres con subirlos? ponerlos en la base de datos no creo que sea opción.

**Comment by RigoFlores** [comment]
Por lo pronto envíamelos por correo pls, los PDF y XML

**Comment by RigoFlores** [comment]
ya lo cerraré, quizá el cliente ya no esté con nosotros, con nuestros tiempos de respuesta..
