### ISSUE TITLE
ESCRITORIO Y ERP - ENVIAR LAS VARIABLES DE MONEDA Y TIPO DE CAMBIO AL PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#228]
enviar las variables tanto en escritorio como en web, al pdf

**Comment by jccastillo0007** [comment]
Done en el ERP y Standalone version 8.1.2

**Comment by RigoFlores** [comment]
wey, como se llaman?

**Comment by jccastillo0007** [comment]
Como tu me lo sugeriste

moneda
tipoDeCambio

En el log puedes observarlas también

JC@iPhone.
 Saludos.
