### ISSUE TITLE
AFT El Galpon y Hotel Séptimo, ajustar el cálculo del importe del impuesto local ISH

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2280]
El Impuesto sobre hospedaje (que es trasladado, es decir se suma), es una tasa que me parece no es fija, sino podría cambiar de entidad en entidad.
En el caso de el hotel séptimo es de 3.5% , es decir para Querétaro le toca esa tasa.
Sin embargo el importe reportado no se valida contra la tasa, de tal manera que podemos aquí ajustar el importe para que cuadre el total pagado en el hotel. Es justamente el mismo principio que utilizamos en factura de gobierno.

La petición es recalcular el ISH de esta manera:

El total de una factura del Hotel es: Total = Subtotal + IVA + ISH
IVA = 16%
ISH = 3.5%

Entonces, 
Subtotal = Total / 1.195  (Redondeado a 2 decimales.)
IVA = Subtotal * 0.16  (redondeado a 2 decimales)
ISH = Total - subtotal - IVA 
Ejemplo: Total 900.00
Subtotal = 900 / 1.195 = 753.14
IVA = 753.14 * 0.16 = 120.50
ISH = 900 - 753.14 - 120.50 = 26.36

Con ello atenderemos los casos, donde los 6 decimales que no se pueden reportar, nos parten la mami.

**Comment by RigoFlores** [comment]
Batería de pruebas para el ambiente de pruebas del galpón:

<img width="563" alt="bateriaPruebasGalpon" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/e60d3025-8ed9-4ada-8af6-ea0d620bbe10">

**Comment by jccastillo0007** [comment]
fixed... tanto para galpon y para alteza... hay que probar los dos, pero yo solo probé galpón jojojo

**Comment by jccastillo0007** [comment]
se ocupa la versión de hoy del conector
