### ISSUE TITLE
Ajustes al FTT en su versión básica elemental

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2281]
Ya vi la pantalla en la versión v2cero, lo vi en esta liga: http://alwaysthere.com.mx:4500/login
Al inicio solicita el usuario y contraseña, OK... para que se pueda identificar al emisor.

Ajustes solictados:
El titulo debe ser FacturaT - Ticket   (en lugar de Plataforma de Facturación FACTURA-T)
El subtítulo debe ser: Captura los datos del ticket  (en lugar de Facturación

El orden de los campos de arriba debe ser:
**Folio   Total  Forma de pago**

El orden de los campos de abajo debe aparecer

**fecha  correo   teléfono** 

como es la versión súper básica, no debe pedir obligatorio el teléfono.

El botón no debe decir Facturar, sino "Enviar" o "Aceptar"

Para propósitos de pruebas y de producción, sacaremos esta versión para el GALPÓN, como ticket de restaurante.
Es decir, el correo debe enviarse indicando la URL de pru o pro, del Galpón, con los datos del folio y total.

**Comment by jccastillo0007** [comment]
Esto no es posible, ya que es la misma aplicación: 
El titulo debe ser FacturaT - Ticket (en lugar de Plataforma de Facturación FACTURA-T)

**Comment by RigoFlores** [comment]
Esta aplicación si se parece mucho a PFT v2cero, pero no lo es.  Es un subconjunto de ella.

Pero se llama FTT. Ojalá que se enuentre la forma de cambiar ese jeder.

Y si no, pues ya lo otro pendiente, eso no está?

**Comment by jccastillo0007** [comment]
done
