### ISSUE TITLE
En pruebas, cuando envía el correo desde el AFT (del galpón en este caso), el asunto es ilegible.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2283]
Así viene el asunto del correo:

=?ANSI_X3.4-1968?Q?Recepci=3Fn_de_nuevo(a):FACTURA,_Emisor:_IIA040805DZ4,_Receptor:_TIA101020BP4,_Serie/Folio:_FR51?=

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ya se modificó el asunto. Ahora dice así:
Aviso de nueva :REMISION, Emisor: FacturaT, Receptor: null, Serie/Folio: SIN SERIE55

Pls cambiar a:
Has recibido una nueva XXXX,  Emisor: YYY,   Receptor: ZZZ,   Serie/Folio:  SSNNN

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
En AFT también incluye el menú de consultas - reenviar correo, y ahí sigue ilegible el asunto.
Favor de actualizar ahí también.

**Comment by jccastillo0007** [comment]
fixed
