### ISSUE TITLE
PFT v2cero - No permite generar una remisión.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2284]
Primero, pide obligatorio el RFC receptor.
Después que se lo capturas, y tratas de generar la remisión, marca: 

Error de timbrado PAC 

Es decir, no es posible generar una remisión en la v2cero.

**Comment by jccastillo0007** [comment]
Debes seleccionar la opción der guardar para después.. para que no valide el rfc... 

hay que revisar muy bien el comportamiento que debe tener, porque ya he pedido muchos cambios a Victor

**Comment by RigoFlores** [comment]
Y como diría aquél sabio filósofo llamado "don teofilito"... y le seguiremos pidiendo.

Lo que ha pasado en el galpón, es una clara muestra que al usuario actual, le gustan las aplicaciones limpias, confiables, intuitivas, simples. El mostrar datos que no se ocuparán, clics adicionales, todo ello va generando incomodidad al grado de casi dejar de usar una aplicación.

Si queremos reutilizar esa pantalla, solo por "no hacer otra casi idéntica", pero con menor alcance, pues al final eso también cuesta esfuerzo.

**Comment by RigoFlores** [comment]
Hay que subir al inicio de esa pantalla los datos de Tipo y CFDI, para que lo primero que se capture, cuando quieren hacer la remisión, precisamente sea ello. Cambiar a remisión y entonces se ocultarán los campos no requeridos, y se acomodarán los campos que si se capturarán.

Al momento de elegir remisión, se debe mostrar únicamente para su captura:

Nombre
Forma de Pago
ID remisión (es el ID interno, sugiriendo el que ya calcula, y dando opción a que ellos lo cambien).
Moneda (por omisión MXN)
Correo: opcional
Tel WhatsApp: opcional

Permitir Agregar 1 o mas productos a la remisión

Los datos de correo y whatsApp ahora no existen, pero estoy pensando ya en la opción de que en caso que se capturen, se envie la liga para la autofactura con los datos de la remisión.
