### ISSUE TITLE
Conector El Galpón - si el archivo NO cumple con el layout, no lo procesa, pero además no lo mueve a procesados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2286]
Por ejemplo, este archivo contiene comas (,,,) al inicio.
Entiendo que no lo procesa por esa razón.
Se queda ahí intentando procesarlo cada vez.

NO lo mueve a procesados. Y si debe moverlo.

Realmente, creo que debía ignorar los renglones que no cumplen con el layout, en este caso solo es uno, pero ignora el resto del archivo.

[hostal-septimo-arte_incoming_payments_2023-12-03_export.csv.txt](https://github.com/jccastillo0007/eFacturaT/files/13553592/hostal-septimo-arte_incoming_payments_2023-12-03_export.csv.txt)

**Comment by jccastillo0007** [comment]
el archivo debe cumplir con el layout acordado...

**Comment by RigoFlores** [comment]
Eso ya lo sabemos. También sabemos que no depende de nosotros, sino del cliente.

El tema es que no lo mueve a procesados, y se queda ahí ciclado reintentando cuando el archivo no cumple.
Subí un ejemplo para reproducir la falla.

**Comment by jccastillo0007** [comment]
fixed, release 14.0.4
