### ISSUE TITLE
Conector Alteza - reporta a 3 decimales la tasa de impuesto local, debe ir a 2.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2287]
Así está en El Hotel del Galpón:

TrasladosLocales ImpLocTrasladado="I.S.H." Importe="21.22" TasadeTraslado="3.5"/>

Así lo reporta en Alteza:

TrasladosLocales ImpLocTrasladado="I.S.H." Importe="222.27" TasadeTraslado="0.035"/>

son de las "chuequeces" del estandar del SAT, porque en los impuestos estándares, si se reporta por ejemplo 0.160000 para el 16% del IVA.

**Comment by jccastillo0007** [comment]
Ellos reportan la tasa así tal cual 0.035, quieres que la convierta en 3.5 ?

**Comment by RigoFlores** [comment]
consulté como se genera en pro actualmente para alteza...
y es así:
TrasladosLocales ImpLocTrasladado="Hospedaje" Importe="136.04" TasadeTraslado="0.03"/>  

lo cual es incorrecto. La tasa si habría que cambiarla a 3.5, solo en el caso de impuestos locales.

**Comment by jccastillo0007** [comment]
fixed, conector 14.0.2 de hoy 12/12

**Comment by RigoFlores** [comment]
Negativo, sigue igual... solo existe un rilís con fecha del 12 de diciembre, y este tomé. De hecho lo del asunto del email, si se corrigió para cuando se timbra la factura.

 <implocal:TrasladosLocales ImpLocTrasladado="I.S.H." Importe="222.27" TasadeTraslado="0.035"/

**Comment by jccastillo0007** [comment]
fixed, ya va caladito... release 14.0.3 de Standalone
