### ISSUE TITLE
Implementar nueva instancia AFT - Biosplash

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2288]
Implementar nueva instancia de AFT para empresa llamada Biosplash.

Se buscará por número ID remisión y total.
El origen de esos datos, serán las remisiones generadas desde PFT (web o móvil).

Para pruebas, ocupar este rfc XIQB891116QE4

**Comment by RigoFlores** [comment]
Nombre comercial: Bioplash
Datos de contacto: Tel (442) 668 2017; (442) 559 3419
correo: soporte@biosplash.com.mx

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
cómo puedo probarlo???

**Comment by RigoFlores** [comment]
ya vi, falta el subir el logo.

**Comment by RigoFlores** [comment]
El header está diferente que en el galpón. Es mucho mas angosto.
Lo inspeccioné, y hasta el código parece distinto en esa parte del header.
Hay que dejarlo igual que el Galpón.

El color del azulPrincipal ponerlo a: #CDD8E2

**Comment by jccastillo0007** [comment]
son los mismos estilos que galpon, anexo imagen de la única diferencia que tienen.
![Screenshot 2023-12-12 at 22 09 44](https://github.com/jccastillo0007/eFacturaT/assets/2245679/2d9bd403-fbb7-4e6e-a642-10d735f32e0e)

**Comment by RigoFlores** [comment]
Según yo no es tema de estilos, sino de código.
Pero como no está arriba bioplash, pues no puedo indicarte donde lo noté.  (inspeccionando la página)

**Comment by jccastillo0007** [comment]
fixec

**Comment by RigoFlores** [comment]
ok, si ya vi que es lo mismo, pero tiene otro comportamiento.
Ajustemos el css. Si quieres pásamelo y yo lo hago, o si lo haces tú, estos son los cambios:

agregar margin bottom que actualmente no tiene, en esta sección:

#encabezado h1 {
    grid-column: 2 / 5;
    color: white;
    font-size: 22px;
    text-shadow: 0px 0px 2px #ccc;
    letter-spacing: 1.3px;
    margin-right: -5%;
    margin-top: 5%;
    margin-bottom: 5%;
    text-align: center;
}

En esta otra sección, modificar el width de 36% a 95%:

#encabezado img {
    grid-column: 1 / 2;
    width: 95%;
    height: auto;
    margin-left: 10%;
}

Finalmente el color de azul principal, hay que cambiarlo, ya que se pierde un poco el texto. Así quedaría:

:root {
    --azulprincipal: #3399D1;
    --grisprincipal: #B9B9B9;
    --azuloscuro: #478aa8;
    --grismedio: #c9c9c9;
    --grisclaro: #e6e6e6;
    --grismuyclaro: #f8f8f8;
    --casinegro: #4d4747;
}

**Comment by jccastillo0007** [comment]
[stylesDT.css.txt](https://github.com/jccastillo0007/eFacturaT/files/13688114/stylesDT.css.txt)

**Comment by jccastillo0007** [comment]
Ya subí el archivo

**Comment by RigoFlores** [comment]
[stylesDT.css.AJUSTADO.txt](https://github.com/jccastillo0007/eFacturaT/files/13689682/stylesDT.css.AJUSTADO.txt)

liste!!!

**Comment by jccastillo0007** [comment]
done
