### ISSUE TITLE
ERP - NOMINA - NO RESPETA EL BOTÓN DE HAB/DESHAB Y LO INCLUYE EN LOS CÁLCULOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#229]
tanto en empresarial como en individual, con el usuario de la TIA, agregué una percepción, la de PTU (utilidades que se ocupará un chingo en mayo), y la deshabilité.
En pantalla no contabiliza PTU en el total mostrado hasta abajo, pero al generar el recibo, le valió madres, SI incluyó en el recibo el monto correspondiente al PTU, aún deshabilitado..

**Comment by jccastillo0007** [comment]
Fixed.
