### ISSUE TITLE
PFT - Consultas, no da la opción para consultar remisiones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2291]
En el filtro de Tipo Factura - Nombre factura, para Ingreso, no aparece Remisión. Entonces no puedo filtrar para ver solo las remisiones.

Aprovechando el viaje, hay que cambiar las leyendas de Tipo Factura por Tipo Documento y Nombre Factura por Nombre Documento.

**Comment by jccastillo0007** [comment]
fixed

Hay que homologar los nombres con la pantalla de facturación, no estamos siendo consistentes.
Cómo deben quedar?
