### ISSUE TITLE
PFT - Pantalla de facturación, agregar producto - no calcula el IVA correctamente con descuento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2293]
Cuando en el producto le seleccionas un descuento, entonces el IVA se debe calcular sobre el resultado del ( Importe - Descuento).

Ejemplo:
Importe = $1,000.00   (el IVA sin descuento, sería 160.00 )
Descuento = $100.00
IVA = (1,000.00 - 100.00 )* 0.16 = 900.00 * 0.16 = 144.00

lo que está haciendo la aplicación, es que si recalcula el subtotal (900.00 en el ejemplo), pero el IVA lo mantiene como originalmente lo tenía, es decir 160.00 
CORRECTO:
En el ejemplo debería ser: 900.00 + 144 = 1,044.00

INCORRECTO:
Y como lo hace es: 900.00 + 160 = 1,060.00 lo cual es incorrecto

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Si lo calcula bien.
Peeero, si se te olvidó cambiar la cantidad o el precio unitario, y el descuento ya tiene por ejemplo un 10%, ya no lo recalcula correctamente. 
En cada cambio de cantidad, precio unitario, % de descuento, o monto descuento... debe calcular nuevamente el importe, el subtotal (importe - monto descuento), el IVA del subtotal (o los impuestos que apliquen) y el total.
