### ISSUE TITLE
PFT - Remisión optimización.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2294]
Cuando se selecciona remisión, solo se deben mostrar los datos referentes a Productos hacia arriba (considerando los acomodos mencionados en el issue 2290 PFT - Pantalla de Facturación, optimización

Los únicos datos obligatorios en una remisión son:
Forma de Pago
Producto(s) - pueden ser uno o varios.

Los datos opcionales son:
Nombre, RFC, condiciones de pago.

La serie, folio y ID se presentan en automático y deben mostrarse en pantalla.

El resto de datos, no se ocupan en remisión. Lo ideal sería ocultarlos, de ser posible.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Si se capturan los únicos datos obligatorios en la remisión (mencionados arriba), no se habilita el botón de "Facturar".

De hecho el botón debe cambiar de nombre, cuando se elige la remisión. "Generar", "Generar remisión" por ejemplo sería el nombre del botón.

**Comment by jccastillo0007** [comment]
si, ya lo reporté, no esta seleccionando la opción de guardar para después, debe suceder en automático
El nombre del botón será solo Guardar, ya que aplica para cualquier tipo de CFDi

**Comment by RigoFlores** [comment]
OK... entonces, el botón quizá deba tener 2 nombres:
a) Generar (en lugar de facturar), ya que se puede generar una factura, cotización, remisión. 
b) Guardar  (será el caso únicamente para la prefactura, es decir cuando en la pantalla captura de una factura, se elija "guardar para después").

En el caso de remisión, no debería existir el guardar para después... simplemente se genera y ya.

**Comment by jccastillo0007** [comment]
ya quedo arreglado el issue de este ticket...  para remision se autoselecciona el check box de guardar para después, el usuario ni cuenta se va a dar... los botones quedaron como Facturar y Guardar, para otros cambios hay que generar otro ticket.
