### ISSUE TITLE
AFT - El Galpón (restaurante) no encuentra el ticket en FI, pero si con el registro.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2295]
Aquí te dejo un arcchivo de ejemplo.
Efectivamente, no se ve en FI, pero si en factura con registro.

[0709122023G.csv.txt](https://github.com/jccastillo0007/eFacturaT/files/13667329/0709122023G.csv.txt)

**Comment by RigoFlores** [comment]
porqué blockeado, si quieres contectarte a mi compu para que le busques... cómo ves?

**Comment by jccastillo0007** [comment]
era cuando no entendía el problema
