### ISSUE TITLE
FTT - ajustes requeridos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2296]
1. Si consultas la remisión generada desde FTT en la plataforma (la wicket), aparece como pagada, por una cantidad igual a 1,278.59
2. El producto que tome para incluirlo en la remisión, debe estar en el catálogo de productos del emisor con el ID = Prod_FTT
3. La forma de pago por omisión, que sea tarjeta de crédito.
4. Si existe la serie FTT en el catálogo de series, el sistema arrojará el folio siguiente y llevará el control interno como ya lo hace desde pantalla.
5. No está llegando el correo donde se indica la liga para emitir la factura.
6. No carga en dispositivo móvil

**Comment by jccastillo0007** [comment]
1) Si consultas la remisión generada desde FTT en la plataforma (la wicket), aparece como pagada, por una cantidad igual a 1,278.59 **FIXED**



4) Si existe la serie FTT en el catálogo de series, el sistema arrojará el folio siguiente y llevará el control interno como ya lo hace desde pantalla. "NO APLICA" LO REVISAMOS CUANDO ALGUIEN LO PIDA

**Comment by RigoFlores** [comment]
Así queda:

1. El producto que tome para incluirlo en la remisión, debe estar en el catálogo de productos del emisor con el ID = Prod_FTT
2. La forma de pago por omisión, que sea tarjeta de crédito.
3. Sugerir el folio como el mismo ID de remisión que tenemos en PFT, por ejemplo: NoIdentificacion="20231220084932676".
4. Enviar el correo donde se indica la liga para poder emitir la factura (liga AFT del emisor que corresponda), junto con los datos de la remisión.
5. No carga en dispositivo móvil

**Comment by RigoFlores** [comment]
CONTENIDO DEL CORREO:

"Para generar su factura favor de dar click en la liga siguiente: "

Link de AFT 

Capturar sus datos fiscales y teclear los siguientes datos:

Ticket:
Total:

Si tiene dudas, favor de revisar el siguiente tutorial

https://www.youtube.com/playlist?list=PLbD7cJxbHSMlI3sxDbC_dN0JWwOR3YsXz

**Comment by jccastillo0007** [comment]
Listos estos puntos:

"El producto que tome para incluirlo en la remisión, debe estar en el catálogo de productos del emisor con el ID = Prod_FTT"

Enviar el correo donde se indica la liga para poder emitir la factura (liga AFT del emisor que corresponda), junto con los datos de la remisión. //EL FORMATO SE VE MEDIO RARO

No carga en dispositivo móvil //SOLO EN PRODUCCION

**Comment by jccastillo0007** [comment]
Oye hay que hablar de los templates de jasper, hay varias cosas que hay que acordar, como el subreporte usado para productos.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Básicamente cumple con todo lo solicitado al momento.
Quizá haya que ajustar aún mas detalles, pero por lo pronto así está.
Hay que probarlo en pruebas.

Aunque la pantalla con la que accedas en el ambiente de pruebas, sea con la cuenta de la tia, quizá todos esos datos los podemos enviar hacia IIA en pruebas, que no?

**Comment by RigoFlores** [comment]
la otra opción, es crear un perfil (usuario) FTT en el la cuenta de IIA, y ahí completar la prueba de que el ticket se pueda facturar.

**Comment by jccastillo0007** [comment]
listo, usuario IIAFTT y password IIAFTT

**Comment by RigoFlores** [comment]
negativo, dice "hubo un problema al iniciar sesión" cuando intento acceder con el usuario  IIAFTT

**Comment by RigoFlores** [comment]
Al momento de darle enviar, marca "folios no disponibles".
que serie está esperando o cómo debemos entender ese mensaje?

**Comment by RigoFlores** [comment]
ya vi, está buscando el producto PROD_FTT... pero creo que ya está abajo el sistema... chiaaa

**Comment by jccastillo0007** [comment]
FTT es la serie utilizada desde la pantalla de FTT

**Comment by RigoFlores** [comment]
ahora repetí la prueba en pru, y marca CFDi inválido

**Comment by jccastillo0007** [comment]
fixed
