### ISSUE TITLE
AFT El Galpón - bajar el mensaje resultado del timbrado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2297]
Eso es algo que pedí desde sus inicios de la plataforma. Solo que ya nos acostumbramos.
Ahora los usuarios lo vuelven a pedir.

Para mi la simplicidad, es como la esencia de la aplicación. Para tí, es "que el usuario se suba, que el usuario haga esto, etc..", y no, la cosa no va por ahí.

Le están reportando problemas a nuestro cliente... ella trata de resolver, si les da un soporte básico... cuando no puede, ella nos reporta "otro nuevo problema" con la aplicación, esa es la idea que se queda. Que la aplicación tuvo otro nuevo problema.

Yo invierto tiempo en investigar el asunto, y resulta que es un error de captura.
El usuario ni siquiera puede subirse a ver el mensaje... ya que nada le indica que lo haga.

Entonces, si la palomita de timbrar está abajo, si el PDF y XML se despliegan abajo, porqué no el mensaje de error cuando este se presenta??

La petición, es bajar ese mensaje resultado del timbrado. Ya sea error o éxito.
Los mensajes previos al timbrado, dejarlos arriba.  (ticket no encontrado, ticket ya facturado).

**Comment by jccastillo0007** [comment]
No se pueden mostrar en dos lugares diferentes mensajes... voy a bajar todos

**Comment by jccastillo0007** [comment]
done

Lo hago también para Alteza y Biosplash ?

**Comment by RigoFlores** [comment]
Espera, 
¿se pueden mostrar en los 2 lugares simultáneamente?
O que solamente en condición de error, muestre una ventana modal (letras blancas, fondo rojo) en lugar de un mensaje?

En condición de éxito, la leyenda abajo en verde y font bold

**Comment by RigoFlores** [comment]
ok, se quedará en la parte superior.
