### ISSUE TITLE
PFT - Consultas - remisión, mostrar ID y descargar PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2298]
En las consultas, cuando se filtra por remisión, hace falta ver el ID que servirá como dato para AFT, cuando así se requiera.
Caso concreto para Biosplash.

Adicionalmente, dar la opción para descargar o reenviar por correo, el PDF de la remisión, ya que ese documento tiene los datos necesarios para facturar desde AFT.

**Comment by jccastillo0007** [comment]
el id se mostrará siempre, no solo para remisiones

**Comment by RigoFlores** [comment]
Pues en la factura el ID no tiene uso, pero pues es parte de reutilizar el código.
Ahí en las consultas, cambiar la etiqueta "CFDi" a "Documento"

**Comment by jccastillo0007** [comment]
done
