### ISSUE TITLE
NO PRESENTA LA OPCION DE SALIR DEL PORTAL (CERRAR SESION)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#23]
SI NOS SOLICITA USUARIO Y PWD, PERO NO PRESENTA LA OPCIÓN PARA CERRAR LA SESION.

**Comment by jccastillo0007** [comment]
La opcion esta dentro del menu Admin

**Comment by RigoFlores** [comment]
DEBERÍA TENER UN ÍCONO PARA SALIR DE LA APLICACIÓN, DESDE CUALQUIER PANTALLA.
