### ISSUE TITLE
ERP - NOMINA - NO RESPETA UN FORMATO PERSONALIZADO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#230]
Si recuerdo bien, me comentaste que buscaría primero en el directorio local la plantilla cfdi_nomina, en caso de no encontrarla entonces se iría por la estándar.
Con la cuenta de la TIA, le configuré una plantilla personalizada para nómina, y de todos modos, está tomando la plantilla general.

**Comment by jccastillo0007** [comment]
El formato de la plantilla custom debe ser :+1: 
cfdi_nomina_ + rfc + .jrxml 
por ejemplo
cfdi_nomina_TIA101020BP4.jrxml

esto se hace asi, para no tener multiples versiones de una plantilla, con el mismo nombre cfdi_nomina.

**Comment by RigoFlores** [comment]
DE ACUERDO, Y VALIDADO.
NO LO RECORDABA.
