### ISSUE TITLE
PFT - Remisión, debe generarla, incrementando el folio y generando el PDF correspondiente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2300]
Se debe poder generar la remisión, sin necesidad de darle "guardar para después".
Debe incrementar el folio de la serie REM.
Debe generar el PDF.

Es decir, tal cual lo hace actualmente en la pftv10

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
olvidé comentar.
La serie de remisiones debe ser REM, cuando se genera desde la PFT.

**Comment by jccastillo0007** [comment]
fixed
