### ISSUE TITLE
PFT - No está tomando las plantillas configuradas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2302]
En pru, para XIQ configuré la plantilla en la pantalla de configuraión de la v10, pero no la toma en la v2.0
Entonces cómo tenemos que configurarla?

**Comment by jccastillo0007** [comment]
fixed
Así está bien configurada, en Enero vamos a habilitar la pantalla de configuración en la PFTv2cero

No jala tu plantilla, marca un error muy raro

**Comment by RigoFlores** [comment]
Esa misma plantilla, en la versión 1.0 si jala.
Entonces, no se que pueda ser...

Aquí el PDF generado desde la PFTv1cero

[143_XIQB891116QE4_TIA101020BP4_26Dec2023_120233.pdf.txt](https://github.com/jccastillo0007/eFacturaT/files/13773180/143_XIQB891116QE4_TIA101020BP4_26Dec2023_120233.pdf.txt)

**Comment by jccastillo0007** [comment]
ya aclaramos este issue
