### ISSUE TITLE
AFT - pantalla de registro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2303]
Para todos los AFT cambiar la etiqueta de "Residencia Fiscal", por la de "Código Postal" en la pantalla de registro.

Uno de los clientes que si se registró, no se que tantas cosas capturó en ese cuadro de texto, en lugar del código postal.

Pero bueno, vamos puliéndolo.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Está ya en pru, faltaría llevarlo a pro.
