### ISSUE TITLE
AFT Alteza - detalles de la nueva URL 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2304]
En esta nueva URL:

https://autofacturat.com.mx/FacturacionAlteza/login?0

En FR, para timbrar requiere que exista la serie FR
Sin embargo en la liga anterior https://efacturat.com.mx/FacturacionAlteza/login?0, ahí timbra con la serie que viene en el archivo, es decir la serie A. Para alteza, se timbra con la serie del archivo.

Además, las consultas en la liga nueva, no se despliegan, pero en la anterior si.

<img width="718" alt="consultaX" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/58560d7a-47d6-4681-8336-cb351797f03b">
<img width="803" alt="consultaOK" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/de9c3c64-7e3a-4221-b78d-3101e0d2add1">

**Comment by jccastillo0007** [comment]
fixed
