### ISSUE TITLE
Nomenclatura Plantillas Jasper - PTFv20

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2305]
para las platillas personalizadas:

ingreso_RFC.jrxml
egreso_RFC.jrxml
nomina_RFC.jrxml
cartaporte_RFC.jrxml
pago_RFC.jrxml
remision_RFC.jrxml
cotizacion_RFC.jrxml
retenciones_RFC.jrxml

Los nombres de las plantilas estándares serán igual, pero sin el "_RFC". Ejemplo: ingreso.jrxml

para los subreportes, estos se llamarán (tanto para plantillas estándar o personalizadas):

producto_ingreso.jasper
producto_egreso.jasper
producto_nomina.jasper
producto_cartaporte.jasper
producto_pago.jasper
producto_remision.jasper
producto_cotizacion.jasper
producto_retenciones

**Comment by jccastillo0007** [comment]
done
