### ISSUE TITLE
Ambiente de pruebas -> Conector Nuevo -> Alteza - > AFT al momento de buscar el folio marca internal error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2306]
Esta es la liga de pruebas para alteza:

http://efacturat-stagging.com.mx:8080/FacturacionAlteza/login?0

El RFC de alteza en pruebas es IVD

El archivo que subí desde el conector fue este. 
Al parecer si lo subió, pero no estoy seguro que lo haya hecho del todo correctamente:

[C33_NPG_20672.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/13790575/C33_NPG_20672.spf.txt)

Cuando le doy buscar desde FR o FI, marca internal error.

Después del internal error, le doy regresar (con la flecha del navegador chrome) y aparecen los datos del ticket desde FR, pero no hace nada si le doy en facturar.

**Comment by jccastillo0007** [comment]
fixed.

Hay que usar el conector que subí hoy, y volver a subir remisiones
