### ISSUE TITLE
PFT - Consultas, no funciona algunos filtros

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2307]
No funcionan los filtros de 
Tipo y nombre de documento.
Serie

Le filtré por remisión y mostró facturas y remisiones.
En la cuenta de IIA.

**Comment by jccastillo0007** [comment]
Tipo y nombre de documento están mandando un valor equivocado al backend, ya lo reporté para que lo cambien.

El filtro de serie si funciona

**Comment by RigoFlores** [comment]
OK, serie si funciona.
Poner por omisión el filtro de tipo ingreso y documento factura.
No recuerdo en cuál issue, solicité que se cambia tipo de factura por tipo documento, y nombre de factura por nombre documento. No lo veo reflejado.

**Comment by jccastillo0007** [comment]
solo pediste cambiar la columna de CFDi por Documento...

**Comment by jccastillo0007** [comment]
fixed.

los nuevos cambios hay que darlos de alta en otro ticket, en este se arreglaron los filtros

**Comment by RigoFlores** [comment]
ok, listo en pru.
