### ISSUE TITLE
PFT - Consultas, ajustar etiquetas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2309]
Ajustar estas etiquetas:

Razón Social  -> Nombre o Razón Social
Tipo de Factura -> Tipo de Documento
Nombre de Factura -> Nombre de Documento

**Comment by jccastillo0007** [comment]
Los campos quedaron asi:

Razón Social
Tipo
Documento

Para ser congruentes con la pantalla de facturación y el catálogo de clientes, chiaaaa
