### ISSUE TITLE
ERP - MONEDAS - CAMBIA LAS MONEDAS EN TODOS LOS PRODUCTOS DE UN SOLO CLICK

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#231]
Si edito un producto, y le asigno una nueva moneda, la da de alta y lo acepta. 
Al darle guardar, y consultar cualquier otro producto, le cambió la moneda también. Lo mismo sucede con todos los productos del catálogo.
Es decir, si defino una moneda distinta y la asigno para algún producto, después de guardar, dicha nueva moneda se la asigna a todos los productos.

**Comment by jccastillo0007** [comment]
Fixed.
