### ISSUE TITLE
PFT - Remisión, ajustes varios ...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2310]
El botón de guardar, solo se debe activar cuando ya capturaron los datos mínimos requeridos para su emisión.

1. Forma de pago
2. Tipo de Documento (debe ser obiviamente remisión)
3. Productos (al menos agregar uno).

Ahora mismo habilita el botón de guardar, aún cuando no has capturado un producto al menos. Eso seguro marcará error mas adelante.

No activar botón de guardar, si no existe la serie REM.

Crear el perfil de usuario "REMISIÓN", para que se pueda configurar en cualquier cliente. O puede ser un plugin.

Habilitar la vista previa para la remisión.

**Comment by jccastillo0007** [comment]
Esto como para que? 
Crear el perfil de usuario "REMISIÓN", para que se pueda configurar en cualquier cliente. O puede ser un plugin.

Todos los clientes tienen acceso

**Comment by RigoFlores** [comment]
Pensaba en los vendedores que únicamente estarán capturando las remisiones, pero no estoy seguro si solo accederán a ello o a toda la plataforma.
Por lo pronto, NO hagamos caso de ese punto.
