### ISSUE TITLE
Biosplash - en producción dar de alta los productos a partir de este listado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2311]
OJO, primero hay que dar de alta la moneda, la unidad de medida para que "empate el listado".

[catalogode productosbiospalsh.xlsx.txt](https://github.com/jccastillo0007/eFacturaT/files/13824085/catalogode.productosbiospalsh.xlsx.txt)

**Comment by jccastillo0007** [comment]
done
