### ISSUE TITLE
PFTv2cero - no genera factura desde la pantalla de facturación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2312]
Para una factura estándar (simple un solo producto con IVA del 16%), en los impuestos está enviando "IVA" en lugar de la clave que corresponde.
Me parece que es "002" la correspondiente al IVA.

el mensaje de error es:
CFDI40175:El valor del campo Impuesto que corresponde a Traslado no contiene un valor del cat?logo c_Impuesto.

**Comment by jccastillo0007** [comment]
fixed
