### ISSUE TITLE
PFTv2cero - Remisión, la nomenclatura no corresponde con el estándar de las facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2313]
me parece que había quedado:
SERIE_RFCemisor_RFCreceptor_fecha

recuerdo que había un tema con agregar el timestamp después de la fecha.

**Comment by jccastillo0007** [comment]
Correcto, ya no agregamos el timestamp, ahora el formato es: 

SERIE+FOLIO+_+RFCEmisor+_+RFCReceptor+_+GUID.pdf o .xml

Para remisiones, no aplica rfc receptor ni guid.

**Comment by RigoFlores** [comment]
Recuerdo el tema de la hora, pero la fecha al menos, si es importante que se incluya.

**Comment by jccastillo0007** [comment]
negativo... es parte de la estrategia nueva de archivos...

**Comment by jccastillo0007** [comment]
duplicado con el ticket 2322
