### ISSUE TITLE
PFTv2cero - detalles en el footer

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2314]
El color del footer cambiarlo a #3399D1.

Los teléfonos son: 442 212 0347; 442 543 0863

El correo por lo pronto es : contacto@factura-t.com.mx

**Comment by jccastillo0007** [comment]
Listo los teléfonos y correo.

El color no, porque es un tono de azul diferente al header (es el azul de la v1), se ve todo chueco... al final revisamos que colores deben quedar,  chiaa
