### ISSUE TITLE
PFT - Consultas, no puedo descargar el PDF y XML de las facturas generadas desde AFT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2315]
Hice la prueba para biosplash en ambiente de pruebas.
Generé la remisión, y pues bien. Generó el PDF.
Luego me fui a AFT y si encontró la remisión. Generé la factura.

Y al final, fui a consultas desde PFT, y si muestra las remisiones y facturas generadas, pero no las puedo descargar.

**Comment by jccastillo0007** [comment]
fixed
