### ISSUE TITLE
PFT - Remisiones, si no me salgo de la pantalla, no puedo generar mas remisiones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2316]
Puedo generar una primera remisión sin problema, en este caso biosplash pruebas.
si después de generar la remisión, ahí mismo quiero capturar otra, al agregar producto no le incluye el impuesto del IVA y tampoco permite agregar el producto a la remisión.

Para poder hacer otra remisión, debo salirme de esa pantalla, es decir me cambio a otra pantalla, y al regresar ya puedo capturar otra remisión.

**Comment by jccastillo0007** [comment]
Ya lo reporte, pero para continuar, no te salgas de la pantalla, solo punte en el campo de cantidad y dale tab, y ya asigna los valores de subtotal y total que son los que faltan.

**Comment by RigoFlores** [comment]
Negativo, si le doy tab efectivamente llena los campos de sutotal y total.
El punto es que aún con ello, NO PUEDO INCLUIR EL IVA EN EL PRODUCTO (ni automático como regularmente es, ni manual)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
hay que subirlo a pro...
