### ISSUE TITLE
PFT - Remisiones, al cambiarle el ID manualmente, no lo considera y toma el que sugiere por default.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2317]
Se solicitó que se mostrara el ID de la remisión en la pantalla, ya que finalmente por ese ID se buscaría en AFT una remisión.
Ahora mismo, busca por el folio de la remisión, pero debería ser por el ID... o como dices, dar la opción de que busque por uno o por otro. Pero eso es tema de otro ticket.

El punto aquí, es que si se cambia el ID sugerido manualmente (para el caso que se quisiera capturar el folio de los tickets impresos por ejemplo), no lo está respetando. Eso lo puedo ver en consultas, donde se muestra el ID.
Ahí se ve, que coloca el mismo ID que sugiere originalmente.

**Comment by jccastillo0007** [comment]
fixed
