### ISSUE TITLE
Conector El Galpón PRU - no está encontrando los tickets

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2318]
Con el conector del 30 de diciembre.
Estos archivos son los que subí
[testHostal.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/13837311/testHostal.zip.txt)

al buscarlos en AFT de galpón, no encuentra los tickets.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
no encontré ningún nuevo rilis.
Probé con el mismo, y no... ni siquiera procesa el archivo del hostal. 
Marca en el archivo de error:

Error al procesar el archivo : C:\ConectorV2CeroPRUEBAS\Conector\testHostal.csvError duing processing file

**Comment by RigoFlores** [comment]
tu me dices cuándo queda listo el ambiente de pruebas nuevamente....
