### ISSUE TITLE
Conector Alteza en pruebas - no mueve el archivo a procesados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2319]
Generé una factura desde AFT, con el siguiente archivo en pruebas de Alteza.

[C33_NPG_20674.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/13837478/C33_NPG_20674.spf.txt)

Todo funcionó bien.
Se me ocurrió volver a procesar el mismo archivo que ya había facturado, y en la consola se alcanza a ver algo así como que "el comprobante ya ha sido emitido anteriormente, favor de revisar". Está OK.

Sin embargo, ese archivo no lo mueve a procesados y ahí se queda ciclado.

Hice la misma prueba con el galpón, y ahí no indica que el archivo ya fue procesado, y entiendo que lo vuelve a subir o al menos indica que el proceso fue exitoso y si lo mueve a procesados

**Comment by jccastillo0007** [comment]
Puedes intentarlo otra vez... lo yo lo hice y si funciono.

No hay cambios en conector, tal vez algo del server si

**Comment by RigoFlores** [comment]
hizo lo mismo, no lo mueve a procesados.
Es ambiente de pruebas, con alteza (rfc IVD) y el archivo arriba posteado.

**Comment by jccastillo0007** [comment]
hay algún error en el log... no puedo reproducirlo en mac, habrá que hacerlo en una windows

**Comment by jccastillo0007** [comment]
cuando procesas un archivo con éxito si lo mueve?

**Comment by RigoFlores** [comment]
Pues ahora repetí la prueba.
Ahora si lo procesa nuevamente y si lo mueve.
El asunto es que ahora permite repetir el folio....
y ese es un gran problema..

consulta en PTFv2.0 con el usuario IVD, y verás que la fecha de hoy 11 de enero, existen 3 remisiones idénticas.

**Comment by jccastillo0007** [comment]
compárteme ese archivo para probar

**Comment by RigoFlores** [comment]
[C33_NPG_20674.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/13914576/C33_NPG_20674.spf.txt)

aquí lo tienes... recuerda que alteza pone su propio folio en la factura... es el folio y la reserva...

**Comment by RigoFlores** [comment]
esto ya no está de nuestro lado, es el tema de los permisos del usuario soporte que es el que levanta el conector.
y quién genera los archivos, tiene otro usuario y ahí está el pex.
