### ISSUE TITLE
PFT - Agregar producto en la remisión, no permite buscar de la lista de productos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2320]
Entiendo que será igual para la factura o la remisión. Yo lo hice para remisión.

En biosplash que tiene muchos productos, quise buscar alguno de ellos, pero la lista no me da esa facilidad de buscar, tecleando algunas letras del nombre del procto

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
ya lo revisé en pru, y si, ya está ok
hay que subirlo a pro pls.
