### ISSUE TITLE
PFTv2cero - facturación, no descarga los archivos y el nombre no cumple.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2322]
Hice una factura en pruebas desde chrome y al darle click en el PDF, no lo descarga  y la nomenclatura no cumple de acuerdo a lo mencionado en el otro issue. Creo que es importante incluir al menos la fecha: YYMMDD como parte del nombre.

Actualmente el nombre solo es el UUID.
Por ejemplo:

**_f13faebc-454c-4931-8a52-29378bb6b221.pdf_**

Están regresando defectos que ya habían sido corregidos, lo cual me parece riesgoso. Esto se reportó y corrigió hace meses.

**Comment by RigoFlores** [comment]
Demos poder descargar el pdf y xml, y su nombre debe cumplir a un estándar de PFTv20... a como sea que quede, pero ahora mismo hasta a la remisión le asigna un nombre de uuid... jejeje

**Comment by RigoFlores** [comment]
Los de alteza ya reportaron este issue.
El nombre no cumple, y el que le asigna que es un UUID, no corresponde al de la factura.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Listo, hay que llevarlos a producción.
Oye, esto aplicará para todos los AFT's???

Veo que la nomenclatura de ambos archivos ya es la misma que PFTv1.0. 
Así quedará para todos??? Sería bastante bueno.

**Comment by jccastillo0007** [comment]
esto es para PFTv2, nada que ver con AFT chiaaaa

**Comment by RigoFlores** [comment]
si, está relacionado, ya que se refiere a la nomenclatura de los archivos cuando se descargan.
Lo que se mencionó es que **en PFTv2.0 la nomenclatura YA es igual a la de PFTv1.0**, lo cual está super bien (habías dicho que eso no iba a ser posible).
Ahora, cuando se genera la factura desde AFT, y se descargan los archivos, también cumple, se llaman igual.
Esta era la pregunta, si en AFT también se llamaría igual. Ya vi que si en pru para IIA.

Entonces, nuevamente la pregunta es si ¿Esta nomenclatura que probé en pru para el emisor IIA (en AFT y PFTv20), ya está lista para todos los AFT's y PFT's v2.0 en producción???

**Comment by jccastillo0007** [comment]
Esto no es correcto:
Lo que se mencionó es que en PFTv2.0 la nomenclatura YA es igual a la de PFTv1.0, lo cual está super bien (habías dicho que eso no iba a ser posible).

La nomenclatura es diferente.

**Comment by jccastillo0007** [comment]
y si, ya está todo en producción
