### ISSUE TITLE
FTT - No respeta la forma de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2323]
En la pantalla de FTT se captura la forma de pago, pero al momento de facturar esa remisión, no respeta esa forma de pago.
El método de pago, será en todo caso PUE, ya que un ticket siempre será pagado previo a facturarlo.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
sigue igual...

**Comment by jccastillo0007** [comment]
done.. lo probé con el AFT de galpon y biosplash
