### ISSUE TITLE
FTT - regular el folio & ID de la remisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2324]
Cuando capturas la remisión desde la pantalla de FTT, hay que cambiarle la leyenda de Folio a **_"ID / No. Ticket"._**

Ese será el ID de la remisión. Esta remisión tendrá un solo producto.
El folio de la remisión, será el que corresponda al consecutivo de la serie FTT del emisor. Ahora mismo NO le está asignando ningún folio a la remisión.

Cuando se busca el ticket en AFT, deberá buscar en principio por ID, y pues si después como segunda opción se busca por el folio de la remisión, pues está OK.

Cuando se facture la remisión, el ID del producto en la factura, será el ID que se capturó desde FTT.

En corto:
La numeración del **FOLIO** de la remisión, será el consecutivo de la serie FTT.
El **ID** que capturen en FTT será el **ID** de la remisión.
El **ID** que capturen en FTT será el **ID** del producto cuando se facture dicha remisión.

No se almacenarán en la PFT, tickets cuyos  **ID & Total** estén repetidos.

**Comment by jccastillo0007** [comment]
done
