### ISSUE TITLE
FTT - al enviar un ticket, reiniciar toda la pantalla, incluyendo el ID/ticket (ya que lo pone en blanco).

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2326]
Cuando se envía un ticket exitosamente, hay que reiniciar la pantalla, es decir colocar el nuevo ID / Ticket, la forma de pago por omisión, la fecha actual.

Actualmente después de enviar exitosamente, el campo de ID/ ticket se vacía, y si algún cliente utiliza esa facilidad del id sugerido, no podrá generarlo nuevamente, a menos que se salga y vuelva a entrar.

Incluso, quizá poner el botón de iniciar, para volver a poner todo lo de omisión y dejar vacío lo que tienen que capturar.

**Comment by jccastillo0007** [comment]
done
