### ISSUE TITLE
FTT - El galpon en pro, enviar el correo de la remisión también al correo del emisor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2330]
Ahora mismo me llegan todas las remisiones.
Se requiere que lleguen al correo del emisor y al correo que capturaron en la pantalla de FTT.

**Comment by RigoFlores** [comment]
hoy generé una factura en vivo desde el galpón.
Si llegó al correo de ellos.
Pero llegó a 2 correos míos...  rflores@factura-t.com.mx y rijomisael@gmail.com

Solo debe llegar al que se capturó en la pantalla de FI... no??? o cómo está ese asunto.
Creo que el que capturé ahí en AFT-FI, fue el de rflores@factura-t.com.mx

**Comment by jccastillo0007** [comment]
El email se manda al capturado en pantalla, y a los configurados del cliente, se encuentran en la tabla de clientes.

En el caso de Galpon, es: septimohostal.gerencia@gmail.com

Puedes hacer un prueba y ver exactamente a quien le llega ?

**Comment by RigoFlores** [comment]
Creo que el pex es que como emisor de facturas, la tia tiene un correo configurado.
Y si entro a AFT-FI, y tecleo ahí un correo distinto, es ahí cuando lo mandará a los 2...
Creo que así está... lo monitorearé.
