### ISSUE TITLE
AFT Biosplash - en chrome de versiones anteriores, no encuentra remisiones cuando el total incluye decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2332]
Lo mismo que pasó en el Galpón.
Hay que generalizarlo a todos los AFT's.

**Comment by jccastillo0007** [comment]
checale en pru

**Comment by RigoFlores** [comment]
sigue igual...

**Comment by jccastillo0007** [comment]
con que datos probaste?

**Comment by RigoFlores** [comment]
ID 20240111155817928	
total   179.80		

esa es de hoy ,pero  puedes capturar cualquiera en PFTv2cero de biosplash

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
hay que llevarlo en chinga a pro
