### ISSUE TITLE
PFT v2cero - Biosplash producción, no muestra resultados en consulta, cuando filtro por factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2333]
Si filtro por remisión, si muestra resultados.
Si filtro por serie, si muestra resultados.
Si filtro por fechas, si muestra resultados.
Si filtro por estado de CFDI, si muestra resultados.
Si filtro por rango de folios, si muestra resultados.

pero si filtro por tipo FACTURA, ahí no muestra resultados.

En pru, para XI, sin filtro muestra todas las facturas y remisiones.
Pero si aplico el filtro tipo factura muestra algunas, pero no todas las que existen. Por ejemplo la serie FI y FR, no las muestra.

**Comment by jccastillo0007** [comment]
fixed, en pru y pro
