### ISSUE TITLE
AFT Biosplash - las remisiones solo se podrán facturar del mes actual

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2335]
Poner estado de caducas (o similar) a las remisiones del mes pasado.
con ello no se deben poder facturar.

Unicamente se podrán facturar remisiones del mes actual.

**Comment by jccastillo0007** [comment]
Esto se va a actualizar por medio del cron que actualiza estatus en prod... ya quieres que lo active para biosplash ?

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Se le está poniendo un estado de pagada, lo cual no es correcto.
Se debe poner a Vencida, o caduca.
Pero pagada tiene un significado dentro del sistema. Cuando lo facturas, lo pone a pagada.
En algún ticket se manejaba: vigente, vencida, facturada, y caduca.

Podría quedar en vigente, facturada y caduca.

**Comment by jccastillo0007** [comment]
El status es Vencida, lo puse por query hoy, y hasta Julio aplicará a las de Junio

**Comment by RigoFlores** [comment]
Yo consulté para las de mayo, y casi todas están pagadas.
Pero encontré algunas que están como "Pendiente".
Puedes consultar en producción, RFC: BAR170213PH1.
Las remisiones 464, 449, 502, 505, 506, 507, entre otras aparecen como pendientes.

**Comment by jccastillo0007** [comment]
El status correcto es CxCStatus

**Comment by RigoFlores** [comment]
Pues entonces hay que actualizar ese estatus en las consultas no?
eso que mencioné, lo ví en la pantalla en las consultas de PFTv20

**Comment by RigoFlores** [comment]
<img width="745" alt="status" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/7c1fc95d-2612-4d11-b11c-aad569b0c61a">

así lo despliega. Y precisamente es lo que menciono en los últimos comentarios. 

Entonces los status son vigente, vencida y pagada?

Es que la remisión en teoría nace pagada. Tendría que ser facturada en lugar de pagada.
Y el filtro de status debería desplegar esas opciones de estatus, no?

**Comment by jccastillo0007** [comment]
ya se está mostrando el estatus correcto en consultas

**Comment by RigoFlores** [comment]
Me siguen apareciendo como pendiente, en las consultas. Mismo resultado.

**Comment by jccastillo0007** [comment]
checa en PRU, si todo está bien ahí lo subo a prod
