### ISSUE TITLE
Conector de LAS BARRICAS - enviar también a impresión cuando se trate de carta porte y así lo indique el archivo de texto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2337]
Ahora mismo, envía a imprimir en automático cuando se trata de factura o de nota de crédito. Claro, siempre que se incluya la instrucción en el archivo. Ejemplo:

impresora=paynobodega|copia

Pero el carta porte no lo manda a imprimir.
Hay que ajustar el código para que también lo imprima cuando así lo indique el archivo de texto.

Aquí te dejo una factura y un carta porte de ejemplo.

[FACT_PPM043245.txt](https://github.com/jccastillo0007/eFacturaT/files/13940994/FACT_PPM043245.txt)
[CP_PPM943245.txt](https://github.com/jccastillo0007/eFacturaT/files/13940995/CP_PPM943245.txt)

**Comment by jccastillo0007** [comment]
En el properties, este valor debe ser true... 
ahorita lo tienes como false

AutoPrint=false

**Comment by RigoFlores** [comment]
oye, pero no hice pruebas... no estoy haciendo pruebas de ello...
Solo fue que el cliente, en su ambiente de producción... puede mandar a imprimir las facturas, pero no el carta porte.
Yo solo mandé facturas y carta porte, para ver si veía algo en el log o en la consola.
Pero el reporte es del cliente, con esos 2 archivos que mandé.
Uno si lo imprime (la factura) y el otro no (el carta porte), con la misma configuración, leyenda, properties, etc.

No, no se trata del properties, se trata de que cuando es carta porte, se aplica una condición que impide o inhibe la impresión.

**Comment by RigoFlores** [comment]
no hay nada que indique que no se imprime.
