### ISSUE TITLE
FTT - enviar en el correo la liga a FI, incluyendo el folio y total

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2338]
Como te comentaba anteriormente, varias aplicaciones similares, incluyen un CBB que te lleva a una aplicación donde solo hay que capturar los datos fiscales.
Esto es, hay que generar la liga a FI, incluyendo el dato de ID y total, para que solo capturen sus datos fiscales.

Entonces, hay que enviarlo así... incluso, colocar un ckeckbox que indique que se almacenen esos datos para futuras ocasiones.
yo creo que esa tabla, debe estar aparte a las que tenemos, ya que solo debe incluir rfc, nombre, CP, régimen, correo, teléfono whatsApp, contraseña.

**Comment by jccastillo0007** [comment]
Ya revise este requerimiento con Victor y Martin, no será posible ya que se requiere de login antes de llegar a la pantalla de facturación... todos los usuario deben hacer login.. no es como el FI de AFT

**Comment by RigoFlores** [comment]
Justo mencioné FI... no se trata de FR... es FIFIFIFIFIFIIFIFIFI

**Comment by jccastillo0007** [comment]
todos los usuarios deben hacer login..

**Comment by RigoFlores** [comment]
ya comentamos que en FI, no se requiere el login...

**Comment by RigoFlores** [comment]
acabo de probar FTT para el tema del trackinID.
Me dí cuenta que ya no está enviando el correo, ni siquiera el que se captura en pantalla... (a menos que en brevo ya se hayan puesto locos y lo limiten a 50 correos cada media hora).

**Comment by jccastillo0007** [comment]
es solo un tema de formateo correcto del correo que tenemos en base de datos... dime de que usuarios para arreglarlo, en prod ya debe estar bien

**Comment by RigoFlores** [comment]
y cuál es el formato correcto?
Ahorita en la cuenta de IIA en pru, aparece así:

["contacto@factura-t.com.mx"]

Así tiene que ir el formato???

**Comment by jccastillo0007** [comment]
solo debe ser:

contacto@factura-t.com.mx
