### ISSUE TITLE
Ajuste en el complemento de pago, versión PFT1.0 y conector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2339]
Resulta que ahora es así (esta es la respuesta de finkok, ante la falla reportada por varios clientes):

**Cuando existan operaciones con **más de un Documento relacionado** en donde al menos uno de ellos contenga la misma moneda que la del Pago, para la fórmula en el cálculo del margen de variación se deben considerar 10 decimales en la EquivalenciaDR cuando el valor sea 1.**

Por tanto: El campo EquivalenciaDR debe contener el valor **"1.0000000000"**.  (si, leíste bien son 10 ceros, 10 decimales).

Es decir, esto únicamente aplica cuando se presentan estas 3 condiciones:
a) Moneda de pago = moneda de DR
b) Número de documentos relacionados > 1.
c) EquivalenciaDR = 1

creo que la condición c, queda cubierta con la condición a. Siempre que sean la misma moneda, la equivalenciaDR será 1.

OJO, si solo se tiene **UN solo documento relacionado, no hay cambio a lo que tenemos actualmente**. (de hecho, ahorita si timbra, no se que pasaría si le ponemos los ceros).

**Comment by jccastillo0007** [comment]
Pero es EquivalenciaDR = 1 o 1.0000000000 ?

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
falta en web, que es donde se emite el comprobante en la mayoría de los casos..

**Comment by RigoFlores** [comment]
lo probé en web y si quedó. Habría que llevarlo a pro, solo si se compone carta porte.

Solo que el carta porte no está jalando. Solo genera el XML.
Aparentemente es por el CBB o algo de una imagen es lo que marca.
