### ISSUE TITLE
NOMINA EMPRESARIAL - CAMBIAR ETIQUETA DE SIMULADOR POR VISTA PREVIA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#234]
Lo mas cercano a una vista previa de la nómina empresarial, es precisamente el reporte en Excel que genera el actual 'simulador'.
Para evitar caer en contradicciones y mantener nomenclatura estándar, se requiere cambiar la etiqueta de Simulador, por Vista Previa.

**Comment by jccastillo0007** [comment]
Done
