### ISSUE TITLE
Alteza, cuando se factura desde FR no respeta el folio que viene en el archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2340]
En FI si lo hace, es decir si toma el folio del archivo.
En FR, no lo respeta y toma el folio del consecutivo de la base de datos.

**Comment by jccastillo0007** [comment]
Este ya debe estar arreglado en pru

**Comment by RigoFlores** [comment]
no, no está... sigue igual.  Aquí ejemplos, cámbiale el folio a archivo.

[C33_NPG_20675.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/13971291/C33_NPG_20675.zip.txt)

**Comment by RigoFlores** [comment]
hoy timbramos una factura en pro, y sigue igual con lo del folio... y el tema de forma de pago y método de pago...

**Comment by jccastillo0007** [comment]
done
