### ISSUE TITLE
Conector Alteza, no respeta la forma ni el método de pago del archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2343]
cadenas dentro del layout

Forma: 
MedioPago     04

Método:
Pago          PUE

archivo 20675.spf

[C33_NPG_20675.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/13971294/C33_NPG_20675.zip.txt)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
otra vez algo pasó con este asunto... se inyectó el problema en producción nuevamente...

**Comment by RigoFlores** [comment]
en pruebas no se presenta ese problema.
estoy confirmando con ellos que en pro, si está presentándose...

**Comment by RigoFlores** [comment]
pues dicen que "por el momento está bien", chiaaaaaa....
