### ISSUE TITLE
Complemento de comercio exterior 2.0 - versión básica indispensable

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2346]
Pues ahora si nos sorprendió el SAT. El pasado 19 de dic publicó el estándar de esta nueva versión y al 18 de enero ya es la única aceptada en producción.
OK, la versión que tenemos en producción actualmente, igual es como la básica, entonces estos cambios que aquí menciono, serán los que soporten esa misma condición de básico. Para llevarla a la versión completa documentaré otro ticket, pero por lo pronto a esta hay que darle prioridad.

liga del XSD:
http://www.sat.gob.mx/sitio_internet/cfd/ComercioExterior20/ComercioExterior20.xsd

liga para consulta del complemento: catálogos, estándar.
http://omawww.sat.gob.mx/tramitesyservicios/Paginas/complemento_comercio_exterior.htm

Cambios:
Las URLs que correspondan, deben actualizarse a la nueva versión de acuerdo al estándar o xsd.

Header:
Version: 2.0
TipoOperacion - se elimina
Subdivision - se elimina

Por lo pronto, son los cambios que alcanzo a identificar como mínimos requeridos.

**Comment by jccastillo0007** [comment]
También eliminaron:
Tipo Operación
Subdivision

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
negativo, sigue mandando las ligas de la versión 1.1 en el header... schema y esas cosas...

**Comment by jccastillo0007** [comment]
lo probaste desde web verdad?

**Comment by RigoFlores** [comment]
Pues el único lugar donde se puede probar es en PFTv1.cero (es decir, si desde web).
Podría ser el conector 1.0, pero no hemos llegado ahí siquiera.

**Comment by RigoFlores** [comment]
Datos para reproducir en pruebas con un CCE básico:
Emisor: IVD
Receptor: la tia
moneda: USD
tipo de cambio: el del diario oficial del día anterior. 
producto: test
precio unitario: 100
cantidad: 1
check en checkbox de incluir el CCE
Datos del complemento (cuando se le da click en addenda):
fracción arancelaria: 9031809901
unidadaduana: 06


La parte de los esquemas la manda así en el header del XML que intenta timbrar:

 xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd **http://www.sat.gob.mx/ComercioExterior11 http://www.sat.gob.mx/sitio_internet/cfd/ComercioExterior11/ComercioExterior11.xsd"**

**Comment by jccastillo0007** [comment]
listo, chécale
Ya pone bien todos los schemas , pero no timbra
