### ISSUE TITLE
Cuando se agrega un XML externo, si no contiene el atributo de folio, se lo pone como 0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2348]
Este XML factorajetest.xml, no contiene folio ya que es un dato opcional y no se porque no se lo incluyó una nueva cliente o mas bien prospecto de cliente.
Entonces lo exporto a la plataforma, porque hay que generar un complemento de pago por factoraje.
En ese proceso, le agrega folio="0" creo yo en la base de datos.
Al emitir el complemento de pago de esa factura, pues le incluye el folio="0" y yo creo que eso se lo regresará el banco, son muy quisquillosos.

Aquí te incluyo el XML que importé y el XML de pago por factoraje que generó.

lo que debe, es simplemente no incluir el atributo folio cuando se importe, y tampoco en el cfdi de pago.

[PAGO138_IIA040805DZ4_BBA830831LJ2_20Jan2024_141238.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/13999244/PAGO138_IIA040805DZ4_BBA830831LJ2_20Jan2024_141238.zip.txt)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
listo, validado.
Lo podemos llevar a producción?
Qué pasaría con lo que no está jalando ahora mismo de PFTv1.0... lo que está a medias?
Carta porte 3.0 o CCE2.0?
