### ISSUE TITLE
ESCRITORIO Y WEB, AGREGAR COMPLEMENTO DE LEYENDAS FISCALES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#235]
POR LO PRONTO APLICARÁ SIEMPRE QUE ELIJAN RETENCIÓN DE IMPUESTO DEL IVA.
EL CLIENTE NOS ESTÁ ESPERANDO DE HACE RATO, EL TIENE ESCRITORIO Y CARTA PORTE.
"Impuesto retenido de conformidad con la ley del impuesto al valor agregado"

**Comment by jccastillo0007** [comment]
Este complemento ya esta listo desde hace rato, checalo pero ya esta liberado chaaaa

Checa el google doc para que veas en que ambientes esta disponible o checalo directamente en el erp

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
PRECISAMENTE LO VALIDÉ EN ESCRITORIO, QUE ES LO QUE TIENE LA CLIENTE, Y NOMÁS NO LO INCLUYE.
LA REGLA ES QUE CUANDO SE RETENGA EL IVA, SE INCLUYA ESE COMPLEMENTO DE LEYENDAS APLICANDO LA LEYENDA AQUÍ DOCUMENTADA

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
NO, LO ACABO DE VERIFICAR. GENERÉ UN RECIBO DE HONORARIOS CON LA CUENTA DE LA TIA (FOLIO 49 EN WEB), Y NO INCLUYE LA LEYENDA CORRESPONDIENTE A LA RETENCIÓN DEL IVA.

**Comment by RigoFlores** [comment]
no recordaba el issue, digo después de 2 años, ta cañón...
pero siempre que se retenga iva, se debe aplicar la leyenda de "Impuesto retenido de conformidad con la Ley del Impuesto al Valor Agregado"

**Comment by jccastillo0007** [comment]
mmmmm entonces estaba bien ?, no tengo el código ahorita a la mano para ver
si la leyenda si se agregaba o solo el schema ?

Saludos.
JC.

**Comment by RigoFlores** [comment]
No, este issue nunca se concluyó... solo apareció el schema, pero nunca se incorporó la leyenda.
Lo que en su momento se solicitó, es que siempre que se retuviera IVA se incorporara dicha leyenda, pero nunca se terminó... de ahí que siga abierto después de 2 añejos...

**Comment by jccastillo0007** [comment]
Ah ok, supongo nadie lo ha usado y/o nadie lo ha solicitado, después de dos
años

Saludos.
JC.

**Comment by RigoFlores** [comment]
En este tiempo, lo solicitó una cliente (de aquí surgió este issue)... me la recordó unas 3-4 ocasiones distintas... hasta que supongo se cansó y me dejó de pedir esto... no sé si aún está con nosotros, pero en definitiva, cuando se retiene el IVA, la leyenda indicada arriba, aplica...

**Comment by jccastillo0007** [comment]
Listo.... ya agrega la leyenda en el release de hoy... en escritorio...

Pero me faltan estos valores por default :   

DisposicionFiscal
Norma

En la versión original, se tiene configurado un archivo de datos extras para dicha addenda o complemento, pero si lo quieres por default, necesito la disposición y la norma.

**Comment by RigoFlores** [comment]
OK, dame chance de investigar y te digo. Si se puede en un archivo XML en escritorio mejor. En web como sería el equivalente?

**Comment by jccastillo0007** [comment]
El archivo XML tiene esta estructura...

<addenda-data-definition>
    <fields>
        <field>
            <tag>disposicion</tag>
            <name>disposicion</name>
            <type>STRING</type>
            <length>10</length>
            <value>disposicion</value>
        </field>
        <field>
            <tag>norma</tag>
            <name>norma</name>
            <type>STRING</type>
            <length>10</length>
            <value>norma</value>
        </field>
        <field>
            <tag>text</tag>
            <name>texto</name>
            <type>STRING</type>
            <length>10</length>
            <value>texto</value>
        </field>
    </fields>
</addenda-data-definition>

No se quien lo use, pero supongo ya alg[un cliente lo usa, pues asi fué desarrollado, te mando por correo el archivo.

**Comment by RigoFlores** [comment]
Oye,  existe oootra leyenda que se deberá incorporar, pero ahora no es cuando se retenga IVA, sino simplemente que el cliente indique que quiere incluir la leyenda.
Entonces... lo podemos hacer tipo addenda, para que cuando le den OK a la pantalla de los datos, simplemente que los incluya. No aplicaría para algún RFC en particular, ya que puede ser cualquiera el receptor... como la beisbol?

**Comment by jccastillo0007** [comment]
mmm creo que mejor agregamos un checkbox para cuando el cliente quiera agregar la leyenda.
Que leyenda es ? ocupa datos extras ? es con el mismo schema del complemento de leyendas fiscales?

**Comment by jccastillo0007** [comment]
pero seria solo en web, porque en standalone ya no hay lugar paraponer ese checkbox

**Comment by RigoFlores** [comment]
Una cosa es el checkbox, y la otra es la leyenda que se incluirá...lo podemos hacer con datos extra o con un XML tipo addenda?. La leyenda puede cambiar, no se asignará a un rfc receptor en particular.
Si lo capturamos como datos extra, y le damos al check box, entonces que la incluya.
En escritorio sería similar, pero con el checkbox en la sección de checkboxes, es decir donde está el envío de correo, autoimpresión.

**Comment by RigoFlores** [comment]
Te envié un correo, tratando de clarificar este issue

**Comment by jccastillo0007** [comment]
ok, ya entendi la necesidad del complemento de leyendas fiscales bajo demanda y el tema de los datos extras a nivel producto.

Pregunta. Si usamos los datos extras de addendas para obtener la leyenda a agregar, que pasaría si un cliente en particular usa otra addenda y este complemento?

Por cierto, este complemento no estaba en web, apenas lo voy a agregar.... seguro que el cliente lo quiere en web o en standalone? que raro.... incluso con impuesto iva retenido no genera el complemento, nadie lo ha solicitado en web?

**Comment by RigoFlores** [comment]
OK, respuesta1: Si se podría presentar el escenario, y tendríamos que resolverlo. Quizás entonces, se podría manejar con datos extra a nivel general (en lugar de ocupar los datos de addenda building). También nos enfrentaríamos al combinar datos extra generales, con datos extra del complemento, pero es una opción. Al menos con este cliente, creo que no se presentaría lo de complemento y otra addenda.

respuesta 2: Este complemento solo estaba en escritorio. La cliente está en escritorio, pero entonces no podríamos resolver el tema de datos extra a nivel producto. Por ello, le tendré que pedir que emita desde web, donde ya emite nómina. Ahora si me dices que lo de datos extra a nivel producto, lo podemos resolver en escritorio sería mejor, pero si no hay otra, nos vamos al web. Se ocuparían unos 8 datos extra a nivel producto aproximadamente.

**Comment by jccastillo0007** [comment]
Done.

**Comment by jccastillo0007** [comment]
Too much time as resolved

**Comment by RigoFlores** [comment]
Quedó en web, mas no en escritorio.
