### ISSUE TITLE
Conector Alteza - marca un error con este archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2350]
AL menos el asunto es que el subtotal lo está reportando mal. 
Debe ser 18673.10 y lo está reportando como 18673.09
El Subtotal es la suma los importes, es decir:

 $2,273.10  +  $16,400.00 = $18,673.10

aquí no hay ni siquiera lugar a dudas en la suma. Incluso, esos datos ya vienen en el archivo. 
No se están tomando de ahí, y seguramente se están calculando, ¿no?

[C33_NPG_23890.spf.txt](https://github.com/jccastillo0007/eFacturaT/files/14015871/C33_NPG_23890.spf.txt)

el archivo lo procesé en pru, y ya se encuentra en la plataforma de pru (igual en pro).
Ellos no pueden hacer esa factura en pro por lo mismo.

Marca este error:
CFDI40108
2024-01-22 15:38:46,214 DEBUG [http-nio-8080-exec-68] (SealerPACProcess.java:373) - El TipoDeComprobante es I,E o N, el importe registrado en el campo no es igual al redondeo de la suma de los importes de los conceptos registrados.

**Comment by jccastillo0007** [comment]
la diferencia esta en el iva y el total... cuanto debería ser ?

**Comment by jccastillo0007** [comment]
fixed....
quieres que corrija la remision en prod para que la puedan facturar ? o reprocesan el archivo

**Comment by RigoFlores** [comment]
corrije la bd en pro, y yo les comento que lo intente nuevamente.

**Comment by jccastillo0007** [comment]
listo...

**Comment by RigoFlores** [comment]
yo pedí que validaran y no me han respondido.
si me reportan error, volveré a abrir el ticket
