### ISSUE TITLE
Ajustes a las remisiones para PFTv20, FTT y conector 2.0 - Series

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2351]
Creo yo que ya estamos confundidos con las remisiones.  Y sobre todo el cliente ya se confundió.

**SERIES:**
Las remisiones originalmente llevan la serie REM, cuando se generan desde la misma plataforma PFT.
Esa misma serie se había mantenido cuando se generaban desde conector.
Creo que podríamos modificar la serie de esas remisiones a CREM o CON. Siempre que no se afecten las consultas de remisiones.

Ahora, la nueva serie FTT solo aplica para remisiones desde FTT precisamente.

Pero que pasa, que la serie FTT ahora también se está utilizando para los tickets (o remisiones) desde el conector, y eso ya confunde a todos, principalmente al cliente.

**Comment by jccastillo0007** [comment]
Es suficiente si usamos la serie REM desde el conector cierto?,  y dejamos la serie FTT para los tickets desde PFTv2. No creo que se requiera otra serie

**Comment by RigoFlores** [comment]
OK, finalmente el cliente que ocupa conector para remisiones, difícilmente generará también remisiones desde la PFT

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
ahora para todos los casos ocupa la serie REM.
Acordamos que para FTT, la serie utilizada será FTT.

**Comment by jccastillo0007** [comment]
listo
