### ISSUE TITLE
Ajustes a las remisiones para PFTv20, FTT y conector 2.0 - envio de correo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2352]
**ENVÍO DE CORREO:**

La remisión solo se debe enviar por correo, cuando se genera desde FTT, ya que la intención es que el receptor genere su factura con esa información. Aquí se tiene que enviar al emisor y receptor.

En conector no, porque solo se están subiendo los tickets y no hay un receptor específico. Ahora mismo si se envia al emisor y no tiene caso creo yo. De hecho el usuario del hostal, ya se confundió.

En PFT-Remisiones, si se podría enviar, dependiendo de la configuración (enviar siempre al emisor o con el checkbox correspondiente). Quizá agregar un checkbox para las remisiones específicamente.
Ahora al capturar una remisión, creo que sería importante capturar un correo para enviarla(tipo FTT). Si se captura, se envía a ese correo independientemente de los checkboxes y configuración.

**Comment by jccastillo0007** [comment]
Serie REM no manda correo
Serie FTT si lo manda

**Comment by RigoFlores** [comment]
Ahorita todos se generan con la serie REM, hay que corregir eso. 
Remisiones desde Conector, FTT y PFT

El requerimiento es que 
Envíe correo siempre cuando la remisión se genera desde FTT (emisor y correo capturado en pantalla; ahora mismo NO lo está enviando). 
Desde conector, nunca (ahora mismo, si que lo envía, recibí muchas de una prueba que acabo de hacer).
Desde PFT, dependiendo de la configuración. Como ahorita no hay configuración, solo lo enviará con base al checkbox. Ahora mismo no envía nada.

**Comment by RigoFlores** [comment]
ahora no envía ningún correo,  desde ningún lado, jajajaja

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
Llegó desde FTT al emisor y al capturado en pantalla.
Desde PFT-Remisiones, NO llegó al emisor.
Desde conector, no llegó a ninguno.

Es decir, solo falta el tema del PFT.

**Comment by jccastillo0007** [comment]
fixed el envío de correo al emisor... hay un problema en el formato como se guardan los emails en pft 1 y pft 2, habrá que ir arreglando eso conforme se muevan usuarios

aún falta desde pftv2

**Comment by RigoFlores** [comment]
Si, veo que desde PFTv2.0, no envía el correo al emisor.
Desde FTT, ya envía el correo al emisor, OK...

**Comment by RigoFlores** [comment]
para probar el envío de correo desde FTT, para la cuenta de IIA en pruebas, debería enviarlo a contacto@factura-t.com.mx

y no, lo envía fijo a tu correo y al mío, además al que se configura. Entonces realmente está faltando el envío de correo desde FTT al emisor.

**Comment by jccastillo0007** [comment]
fixed
