### ISSUE TITLE
Ajustes a las remisiones para PFTv20, FTT y conector 2.0 - asunto del correo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2353]
**ASUNTO DEL CORREO:**
Finalmente, el asunto del correo de remisiones, debe ser :

Has recibido una nueva :REMISION, Emisor: XIQB891116QE4, Folio: ID TICKET
Emisor, sería el rfc del emisor
El folio sería el ID en este caso. (también llamado como trackin ID, es decir lo que tienen que teclear para buscar la remisión en AFT).

**Comment by jccastillo0007** [comment]
done
