### ISSUE TITLE
Demo en pruebas para cliente nuevo VIRTUAL HOMES- CFT - AFT - PFT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2354]
Este cliente quiere corroborar  que nuestra solución atiende sus requisitos. Estos serían los puntos a atender:

**Para demo:**
El layout será similar al del Hostal, ellos lo pueden generar así.
El concepto cambia de hospedaje a arrendamiento
Cambiar el logo, nombre comercial  (Virtual Homes) y datos de contacto  (reservas@virtualhomes.mx  +52 722 458 3146)
El color del header y del footer cambia #88963a
**PDF con datos y colores de ellos.  (ya lo tengo)**

**Que no haríamos para demo:**
Agregar los nuevos campos del layout (departamento, fecha de inicio, fecha de fin, nombre de huésped) para incluirlos en la factura como información complementaria
Que capturen la forma de pago en la pantalla de AFT

Integrarnos a su sistema mediante un web service, rest service o conexión a base de datos (alcance para etapa 2)

**Pendientes PFT:**
Cancelación de facturas
Completar info del reporte de excel, generado desde las consultas
Pantala de configuración

**Comment by jccastillo0007** [comment]
listo

http://efacturat-stagging.com.mx:8080/FacturacionVirtualHomes/login?0

Con el conector que acabo de subir y el RFC MISC
