### ISSUE TITLE
Complemento de pago por confirming

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2355]
Este esquema de complemento de pago, es nuevo.
Es idéntico idéntico a lo que tenemos; lo único distintos es que el receptor será distinto al receptor de las facturas pagadas.

Con ello, se me ocurren soluciones como:
a) Que una vez que ya han seleccionado la factura y el saldo disponible para facturar sea 0.0, ahí tengan chance de cambiar el receptor, sin mover ya nada de los pagos capturados (ya sea totales o parciales).

b) Hacerlo como complemento de pago por factoraje, pero al revisar que el saldo insoluto para pago es 0, entonces que solo considere el nuevo receptor, tomado de esa pantalla.

c) Hacer el paso 5, por confirming, para que únicamente elijan el nuevo receptor... sería paso 4 excluyente del paso 5.

d) alguna otra opción que se te ocurra.

**Comment by jccastillo0007** [comment]
la opción c es lo adecuado

**Comment by RigoFlores** [comment]
Si, coincido que ese sería lo adecuado.
Las otras opciones son para no modificar pantallas.

OK, entonces si se captura el paso 5... el paso 4 se inhibe o se ignora. Ya que aplica uno u otro.
En el paso 5, únicamente se elige al nuevo receptor, tomado del catálogo de clientes. Los datos serán los requeridos por el receptor: rfc, nombre, régimen y CP.

**Comment by RigoFlores** [comment]
tons, pos hay que implementarlo.
El cliente ya pagó.

**Comment by jccastillo0007** [comment]
estamos hablando del receptor del cfdi, en el xml normal? pero no los datos del pago como: Rfc emisor

**Comment by RigoFlores** [comment]
Correcto, es el receptor del CFDI estándar, sin considerar nada del complemento, que de hecho si mal no recuerdo, ahí no se incluyen esos datos. Pero como quiera, es independiente.

Se trata únicamente de cambiar los datos del RECEPTOR del CFDI estándar. SI.

**Comment by jccastillo0007** [comment]
done en pru

**Comment by RigoFlores** [comment]
Si, únicamente cambiar la etiqueta a "Esquema Confirming" y llevarlo a producción.
