### ISSUE TITLE
Conector galpon - Cuando el total, viene en 0, interrumpe el procesamiento del archivo.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2356]
Tenemos este contenido en un archivo del galpón:

**7765,0.00,0.00,0.00,0.00,0.00**
7766,240.00,240.00,0.00,0.00,0.00
7767,240.00,0.00,264.00,0.00,0.00
7768,485.00,485.00,0.00,0.00,0.00
7769,1005.00,0.00,1105.50,0.00,0.00

con el primer registro, se interrumpe el procesamiento del todo lo que está debajo de él.
El usuario ni se entera, ni lo sabe. 
Yo creo que hay que poner la validación en el server, que si el total es 0, no lo agregue a la bd, simplemente que lo ignore.

**Comment by jccastillo0007** [comment]
mejor en el conector, para que enviar basura ?

**Comment by jccastillo0007** [comment]
fixed
