### ISSUE TITLE
Conector v2.0 vs FTT, permite ticket duplicados (ID+Total) cuando primero lo cargas desde FTT y después desde el conector.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2358]
En particular del galpón, pero en general para todo cliente que llegue a tener el servicio desde ambos puntos.

Si tu cargas **PRIMERO tickets desde el conector,** y ese mismo ID y total, lo intentas cargar **DESPUES** desde FTT, NO lo permite, lo cuál está OK.

Pero si al contrario, como sería quizá LO mas común... **PRIMERO cargar un ticket desde FTT** para que se emita en el momento, y luego en la noche o **mas tarde lo cargas nuevamente desde el conector,** ahí si lo permite cargar... aún con serie distinta, pero el ID y el total que son los que se validan para ubicar de manera única un ticket, eso si permite duplicarlo...

<img width="809" alt="ticketduplicado" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/cb12631c-8457-4c41-b9f9-1ca9243e8983">

**Comment by RigoFlores** [comment]
el tema es que en el galpón, podrían emitir desde FTT remisiones que pidan en el momento del pago...
pero al final del día o de la semana, cargarán todo el archivo con toodos los tickts, sin distinción si ya fueron facturados o no.

**Comment by jccastillo0007** [comment]
listo... tuve que quitar la serie de la validación

**Comment by RigoFlores** [comment]
pls súbelo a pro, para comentarle al Galpón...
