### ISSUE TITLE
PFTv2.0 - Remisiones, no actualiza el IVA cuando se hace algún cambio en precio unitario o cantidad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2359]
Cuando estás capturando una remisión (supongo que una factura igual), le das agregar producto.
Ahí cambias cantidad o precio unitario, y enseguida le das click al botón de agregar, **entonces SI toma el nuevo dato de cantidad o precio unitario, pero mantiene el IVA anterior.**

Es decir, antes de aceptar el click en agregar, habría que actualizar todos los datos que apliquen.

**Comment by jccastillo0007** [comment]
fixed
