### ISSUE TITLE
AFT - al timbrar, a nivel de concepto, maneja el importe a 6 decimales.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2361]
A nivel de concepto, el importe que es precio unitario * cantidad, lo hemos manejado a 2 decimales, para que las sumas finales no tengan pex.
Los 2 decimales del importe deberían estar trucados.

**Comment by jccastillo0007** [comment]
fixed... lo puedes probar en biosplash, pero luego habría que subir un release de galpon y alteza y probar también

**Comment by RigoFlores** [comment]
Si, ya quedó. 
Una pregunta, por ejemplo esta parte del código es independiente para cada instancia??
O cuáles serán las partes de código que apliquen para todas las instancias. ¿Existen bibliotecas de código que son comunes a todos??
