### ISSUE TITLE
PFTv2.0 - remisión, cuando agregar producto y cambias varias veces la cantidad y/o precio unitario se bate la info

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2362]
Capturo una remisión con cualquier producto.
le modifico 2-3 veces la cantidad y el precio unitario. Al final lo que quede, aparentemente están bien los números.

EL PDF generado, está bien también en apariencia.
Pero no se que haga en la BD, que cuando buscas ese ticket, ya presenta otros datos.
Aquí el ejemplo de lo mencionado:

[remision ok.pdf.txt](https://github.com/jccastillo0007/eFacturaT/files/14149350/remision.ok.pdf.txt)

en pantalla se ve esto, que es lo que trata de timbrar

<img width="501" alt="remisión pantalla" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/2f55305b-47f5-40aa-9aa0-3f3f7cc96a78">

**Comment by RigoFlores** [comment]
Lo que ya logré reproducir, identificar es que en el XML a nivel impuestos del producto, la base la reporta como cantidad x importe. 

Importe = (cantidad x precio unitario) 
Sin embargo, la base debe ser = importe - descuentos
Si el descuento es cero, entonces base = importe.

pero como lo está haciendo es que reporta la base = importe x cantidad... que al final sería igual a cantidad x cantidad x precio unitario.

OJO, cuando ya generó una remisión, y quieres capturar una nueva, al agregar el primer producto, muestra un IVA, que es el IVA de la remisión anterior. No se si eso tenga relación con el tema de la base.
entonces, lo que hace es reportar esa base como

**Comment by RigoFlores** [comment]
En este comportamiento, si la cantidad al final de los cambios de precios y cantidades, queda en 1, no fallará.

**Comment by RigoFlores** [comment]
los cálculos correctos a nivel producto son:
importe = cantidad x precio unitario
base = importe - descuento

si el descuento lo capturan en %, será calculado respecto al importe.... si el descuento lo teclean como cantidad, pues simplemente se restará como indica la fórmula de arriba

**Comment by jccastillo0007** [comment]
Ya corregí esto a nivel producto / impuestos:

pero como lo está haciendo es que reporta la base = importe x cantidad... que al final sería igual a cantidad x cantidad x precio unitario.

El resto estaba bien... hay que checar bien con diferentes combinaciones

**Comment by jccastillo0007** [comment]
fixed... lo puedes probar en biosplash, pero luego habría que subir un release de galpon y alteza y probar también

**Comment by RigoFlores** [comment]
ok, ya está listo.
En el galpón y hostal, la cantidad siempre es 1.
En Alteza, las cantidades y cifras ya vienen en el archivo.
En abastos la cantidad siempre es 1.

en ninguno de los anteriores aplica lo de remisiones capturadas desde la pantalla de PFTv2.0
Cómo puedo validar que este cambio les afecta o no???
