### ISSUE TITLE
PFTv2.0 remisiones, cantidad no acepta decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2363]
La cantidad y el precio unitario, deberían aceptar hasta 6 decimales.
Ya en el XML, el importe que es cantidad x precio unitario, ahí se trunca a 2 decimales.

Pero al menos, la cantidad si debería aceptar decimales, y maneja únicamente enteros.

**Comment by jccastillo0007** [comment]
fixed
