### ISSUE TITLE
PFTv2.0 - remisiones, no envía al PDF los datos correctos de importe, y base IVA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2364]
A nivel del subreporte de productos

El $F{importe} es igual a cantidad x precio unitario, pero está enviando con el IVA incluído, eso no está bien.

Y la $F{baseIVA} no la está enviando correctamente. La esá enviando como 0.00
Base IVA es = (cantidad * precio unitario) - montoDescuento.

**Comment by jccastillo0007** [comment]
fixed, esto lo tienes que checar en facturas también, no solo remisiones

**Comment by RigoFlores** [comment]
OK, en remisiones si quedó.
En facturas manda chueca la info al PDF (importe y base).

Para reproducir, emisor XI, receptor la tia.
Producto prod-test, cantidad 6, precio unitario 300, descuento, 300 ...
Así debe ser:
Importe = cantidad x precio unitario = 1800  
BaseIVA = importe - descuentos = 1800 -300 = 1500.00

y está mandando importe = 1500 y base = 1200

Hay que subir lo de remisiones a pro.

**Comment by jccastillo0007** [comment]
ya pude reproducirlo... para arreglarlo, debo hacer algunos cambios, espero que no se rompa nada k

**Comment by RigoFlores** [comment]
No entendí, ya puedo probarlo o no?

**Comment by jccastillo0007** [comment]
fixed.

Hay que probar muchos escenarios y desde los AFT también

**Comment by RigoFlores** [comment]
Pues apenas inicié probando en biosplash. En pru.
Las básicas si las hizo bien, remisiones y facturas.
Pero remisiones con descuento, ahí lo hizo chueco.
Mira esto:
El total debió ser 34800, pero aparentemente le restó el descuento. Siendo que el descuento se aplica a nivel de base.

Aquí la parte a nivel concepto está bien. Precio unitario, cantidad, descuento, importe, todo eso OK
A nivel de impuestos también está bien.

**SubTotal="30000.00" Descuento="10000.00" Moneda="MXN" TipoCambio="1" Total="24800.00"** TipoDeComprobante="I" Exportacion="01" MetodoPago="PUE" LugarExpedicion="57424" xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd">
    <cfdi:Emisor Rfc="XIQB891116QE4" Nombre="BERENICE XIMO QUEZADA" RegimenFiscal="612"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="626" UsoCFDI="G03"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="01010101" NoIdentificacion="test1" Cantidad="20.00" ClaveUnidad="E48" Unidad="SERVICIO" Descripcion="PRODUCTO DE PRUEBA 1" ValorUnitario="2000.000000" Importe="40000.00" Descuento="10000.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="30000.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="4800.00"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="4800.00">
        <cfdi:Traslados>
            <cfdi:Traslado Base="30000.00" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="4800.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
</cfdi:Comprobante>
