### ISSUE TITLE
PFTv2.0 remisiones - producto con descuento, hace cálculos chuecos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2365]
En este caso, reporta incorrectamente el importe y la base.

Los cálculos son como sigue:

Importe = cantidad x precio unitario
Base = importe - descuento
IVA = Base * tasa

El descuento si lo teclean como %, se calcula respecto al importe  (es decir, un porcentaje de cantidad x precio unitario).
El descuento si lo teclean directamente como una cantidad, entonces el % será = (monto descuento / importe )

Esto es la base elemental de toda la facturación... no pensé que tuviéramos que revisarla nuevamente, pero bueno, ahí está. Desde mero abajo hay que revisarlas. 
Lo bueno que todo lo que se haga en remisiones, aplicará en automático para las facturas.

**Comment by jccastillo0007** [comment]
done
