### ISSUE TITLE
Folio & trackingID de una remisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2366]
En PFTv2.0, la remisión es lo que se genera para posteriormente buscarla en AFT.

**La remisión al igual que la factura, tiene una serie y un folio consecutivo que se toma de la BD del sistema.**

Para el conector y la pantalla de remisiones, esa serie es REM
Para la pantalla de FTT, la serie es FTT.

**EL trackingID, es lo que teclea el usuario en la pantalla de AFT para buscar un ticket o remisión.**

Para los conectores que trabajan con AFT: Abastos, Alteza, Galpón, VirtualHomes... ese trackingID viene en el archivo. De ahí se toma.
Para la pantalla de remisiones, ese trackingID se sugiere en pantalla y el usuario lo puede cambiar. Esto aplica para Biosplash.
Para la pantalla de FTT, ese trackingID se sugiere en pantalla y el usuario lo puede cambiar.

Entonces, una remisión tiene una serie, un folio y un trackingID... la serie y folio son para identificar la remisión en específico dentro del sistema, reportes, etc.
El trackingID, para buscar en AFT la remisión. 
El trackingID  junto con el total, identifican de manera única una remisión para cualquier emisor.

Así debe funcionar, así funciona actualmente en PFTv1.0, y dadas las condiciones de los conectores, me parece que está bien.

**Comment by RigoFlores** [comment]
Lo que está haciendo ahora para remisioines de PFT y me parece que en FTT también, es que el trackingID no lo toma de la pantalla, sino del folio consecutivo. Eso es lo que es incorrecto.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
En PFT, ya está tomando el trackingID correcto.

En FTT ya está tomando el trackingID correcto, pero no está enviando el correo, ya ni siquiera el capturado en pantalla.
