### ISSUE TITLE
Biosplash - no respeta el ID del primer producto dentro de la factura generada (NoIdentificacion)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2367]
Para el galpón, para abastos... que solo llevan un producto en cada factura, el ID de ese producto es el número de ticket, o lo que es lo mismo el trackinID.
En Alteza no recuerdo cómo este asunto.

Pero bueno, en biosplash es un caso distinto, ya que su remisión se genera desde pantalla y puede incluir varios productos.
Entonces en al primer producto le asigna el ID igual al trackinID, y al resto de productos les asigna el ID que les corresponde.

Lo que hay que que hacer, es que a todos los productos en la remisión les respete su ID, y a la factura en sí, le asigne el mismo trackingID de la remisión. Con ello podríamos conocer qué factura le corresponde a qué remisión.
En este ejemplo, el  primer producto y el tercero son el mismo producto, pero ahí se nota como les asignó distinto ID.

ClaveProdServ="73152100" **NoIdentificacion="247"** Cantidad="1.20" ClaveUnidad="H87" Unidad="PZA" Descripcion="PROD-TEST" ValorUnitario="2000.000000" Importe="2400.00" ObjetoImp="02"

ClaveProdServ="73152100" **NoIdentificacion="XYZ"** Cantidad="5.00" ClaveUnidad="E48" Unidad="SERVICIO" Descripcion="producto de prueba 222" ValorUnitario="1000.000000" Importe="5000.00" ObjetoImp="02">

ClaveProdServ="73152100" **NoIdentificacion="PROD-TEST"** Cantidad="1.00" ClaveUnidad="H87" Unidad="PZA" Descripcion="PROD-TEST" ValorUnitario="400.000000" Importe="400.00" ObjetoImp="02">

La remisión de Biosplash y la factura, ahora mismo tienen distinto trackinID. Hay que asignarles el mismo, ahora que ya se corrija también ese tema.

<img width="788" alt="trackinID" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/5477a9ce-2278-4949-a40c-4ee639db2514">

**Comment by RigoFlores** [comment]
Esto nos sigue pegando, y para el reporte que quieren será muy necesario.
El ID producto que se incluye en cada concepto de la factura, debe ser el que se capturó en el catálogo de productos.

**Comment by jccastillo0007** [comment]
fixed

**Comment by jccastillo0007** [comment]
Ojo, algún otro AFT lo pidió así, o así lo definiste porque se hacía a propósito

**Comment by RigoFlores** [comment]
Este ticket aplica para Biosplash.
Para el galpón, para el hostal, para virtual homes, para abastos aplica el # de ticket como ID. Ya que se maneja un solo producto.

En alteza se manejan varios productos, revisaré como se arma el ID producto porque no se incluye en el archivo.

Aquí en Biosplash, es MUY importante el tema del ID, para propósitos del reporte que pidieron.
En resumen, este ticket por lo pronto aplica ÚNICAMENTE para Biosplash.
