### ISSUE TITLE
AFT - el subtotal mostrado en pantalla, es incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2368]
Me di cuenta hasta que capturé remisiones con descuento en biosplash.
El XML no tiene afectación, es solo lo que se muestra en pantalla.

Importe= cantidad x precio unitario, es decir no intervienen los descuentos.
El subtotal es igual a la suma de importes de cada producto, es decir tampoco refleja los descuentos.

Cuando existen descuentos, lo que muestra en pantalla es esto, es decir el subtotal presentado es incorrecto (resaltado en amarillo).

<img width="728" alt="subtotalesAFT" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/fb4ab31b-0e15-451d-b528-605068dc5839">

Es el ticket 20240205133918339 con subtotal 6,472.80, en AFT de biosplash.

**Comment by jccastillo0007** [comment]
fixed en alteza... chécale, si es lo correcto me dices para ponerlo en galpón y biosplash

**Comment by RigoFlores** [comment]
es muy complicado validarlo en alteza, ya que las cifras ahí ya vienen en el archivo.
Esto lo puedo validar fácilmente en biosplash... mejor ahí ponlo, ya que ahí puedo poner descuentos...

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
si funcionó bien en biosplash, tons hay que llevarlos a todos los AFTs
