### ISSUE TITLE
PFTv1.0 - nómina, el tipo de cambio no debe existir

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2369]
No sé de cuándo se hizo ese cambio, pero ahora en producción se inyectó este error.
Tipo de cambio no debe incluirse para el CFDI tipo nómina.

Revisé unos timbrados a inicio de mes y no lo incluía.
Ahora, con la versión que subimos ayer, ya lo incluye.

[NOM2191_ROPN540415IL6_HARP570408NA0_02Feb2024_101741.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/14184594/NOM2191_ROPN540415IL6_HARP570408NA0_02Feb2024_101741.xml.txt)

SubTotal="6227.76" Descuento="1120.92" Moneda="MXN" **TipoCambio="1"** Total="5106.84" TipoDeComprobante="N" Exportacion="01" MetodoPago="PUE" LugarExpedicion="87300"

**Comment by jccastillo0007** [comment]
el xml que subiste no tiene el tipo de cambio, es el bueno o es el malo ?

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
> el xml que subiste no tiene el tipo de cambio, es el bueno o es el malo ?

es el bueno, está timbrado.
Cuando lleva tipo de cambio, no lo timbra.
