### ISSUE TITLE
web - no cancela las facturas y lo reporta como que si lo hizo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#237]
El botón de cancelar, debe regresar a su anterior posición, y simplemente abrir una ventanita con la info al igual que en escritorio, con la info básica preva a la cancelación.
Hoy en día abre una ventana con todo el detalle de la factura, y con muuuchos botones que pueden provocar fallas o errores de dedo, cuando lo único que se requiere es cancelar una factura.

**Comment by jccastillo0007** [comment]
Fixed.
