### ISSUE TITLE
Conector Alteza, la serie y folio de las remisiones las debe tomar del archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2373]
Esto ya lo habíamos arreglado.
La serie si la toma del archivo, es la serie A.
Pero el folio no lo toma del archivo.

**Comment by jccastillo0007** [comment]
aqui mas que el folio es el tracking Id ? eso decía el ticket que creaste de series, folios y tracking Id

No sé cual es el problema, checaste en la base de datos que valor tiene el folio y el tracking Id ?

**Comment by RigoFlores** [comment]
Estoy en espera de la respuesta de cómo requieren los folios de las remisiones y de las facturas, ya que me perdí en eso.

**Comment by RigoFlores** [comment]
Acabo de platicar con ellos...
REMISIONES:
Serie: REM
Folio & trackingID -> tomado del archivo.

FACTURAS:
Serie: Tomada del archivo
Folio: el mismo del archivo... es decir, igual al folio y trackingID de la remisión que da origen a la factura.
TrackingID: no es relevante para ellos, puede ser el número grande que ya debemos adoptar como trackingID para los otros sistemas, como por ejemplo el FTT. Ese trackingID además de irrepetible, nos indica la fecha y hora que se timbró esa factura.

**Comment by jccastillo0007** [comment]
Listo... quedo tal como lo pediste

**Comment by RigoFlores** [comment]
Desde FR, el trackingID lo pone como un ID interno, pero no es el número largo, es el cortito... chiaaaa
Desde FI, el trackingID lo pone como el folio.

Entonces cómo quedará???... como sea, pero homologado.

**Comment by RigoFlores** [comment]
<img width="811" alt="foliosAlteza" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/7ee6cc6b-cb27-4e48-b798-b93fae1a4494">

**Comment by jccastillo0007** [comment]
fixed, se queda el mismo folio

**Comment by RigoFlores** [comment]
ya está en pro???

**Comment by jccastillo0007** [comment]
noup

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
en pro no ha quedado...
esto es de hoy...

<img width="896" alt="foliosAlteza" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/7f7292d7-676d-45b9-b1cf-0efe40c1fbbc">

**Comment by jccastillo0007** [comment]
ahora si ya debe estar bien...
