### ISSUE TITLE
PFTv1.0 - la suma de los importes de impuestos no es correcta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2375]
Este problema es recurrente de meses, no puedo entender que pasa.
Cuando se reporta el nodo de impuestos general, debe SER LA SUMATORIA DE LOS IMPORTES DE IMPUESTOS A NIVEL CONCEPTO.

Entiendo que esos importes se reportan a 2 decimales, pero la suma a nivel general la hacen con 6 decimales, o que puede pasar?

    <cfdi:Emisor Rfc="SIA070522N68" Nombre="SERVICIOS INTEGRALES DE ARRENDAMIENTOS" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="MME920427EM3" Nombre="METLIFE MEXICO" DomicilioFiscalReceptor="03920" RegimenFiscalReceptor="601" UsoCFDI="G02"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84131602" NoIdentificacion="DESCUENTO POR CONVENIO" Cantidad="1.00" ClaveUnidad="E48" Unidad="UNO" Descripcion="DESCUENTO POR CONVENIO DESCUENTO" ValorUnitario="12474.210000" Importe="12474.21" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="12474.210000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.080000" Importe="997.94"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
        <cfdi:Concepto ClaveProdServ="85101503" NoIdentificacion="COASEGURO" Cantidad="1.00" ClaveUnidad="E48" Unidad="UNO" Descripcion="COASEGURO PAGO REALIZADO POR ASEGURADO" ValorUnitario="11550.210000" Importe="11550.21" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="11550.210000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.080000" Importe="924.02"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="1921.95">
        <cfdi:Traslados>
            <cfdi:Traslado Base="24024.42" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.080000" Importe="1921.95"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>

aquí presenta una variación de un centavo en el nodo de impuestos totales,  por lo tanto en el total también.
Cuando se reporta a 2 decimales el importe a nivel concepto, si se redondea, es probable que se presente esta situación.

lo importante es que el importe a nivel general, debe ser la suma de los importes reportados a 2 decimales, a nivel concepto.

**Comment by RigoFlores** [comment]
lo mismo aplica para las retenciones.
Al final quizá no es tan tan relevante que redonde o trunque a nivel concepto, peeeero lo realmente importante, es que la suma en el nodo de generales de traslados y retenciones, sea la suma de importes de impuestos de los conceptos dentro del cfdi.

y por supuesto el total, que es la suma de los importes... mas la suma de los traslados... menos la suma de las retenciones..

chaaaa, todo eso es super elemental... no se porque vuelve y vuelve eso..

**Comment by jccastillo0007** [comment]
porque acabas de pedir que el importe se trunque a 2 decimales, antes estaba a 6

**Comment by jccastillo0007** [comment]
fixed, no se estaba redondeando antes de acumular los totales

**Comment by RigoFlores** [comment]
si, al parecer ya quedó, ojalá no tenga efectos colaterales...
ahora ya tiemblo con cada cambio...

**Comment by RigoFlores** [comment]
Pues nuevamente se reabre este issue.
En las retenciones, se deben sumar los importes individuales reportados a nivel concepto (a dos decimales).
En su lugar reporta la suma de los importes de las retenciones con todos los decimales.

Ejemplo:

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="31391500" NoIdentificacion="mp1" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="610960/01 Bracket Project: M-5600001" ValorUnitario="1350.000000" Importe="1350.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="1350.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="216.00"/>
                </cfdi:Traslados>
                <cfdi:Retenciones>
                    <cfdi:Retencion Base="1350.000000" Impuesto="001" TipoFactor="Tasa" TasaOCuota="0.012500" Importe="16.88"/>
                </cfdi:Retenciones>
            </cfdi:Impuestos>
        </cfdi:Concepto>
        <cfdi:Concepto ClaveProdServ="31391500" NoIdentificacion="mp2" Cantidad="1.00" ClaveUnidad="H87" Unidad="PIEZA" Descripcion="610882/01 Bracket Project: M-5600001" ValorUnitario="1350.000000" Importe="1350.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="1350.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="216.00"/>
                </cfdi:Traslados>
                <cfdi:Retenciones>
                    <cfdi:Retencion Base="1350.000000" Impuesto="001" TipoFactor="Tasa" TasaOCuota="0.012500" Importe="16.88"/>
                </cfdi:Retenciones>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosRetenidos="33.75" TotalImpuestosTrasladados="432.00">
        <cfdi:Retenciones>
            <cfdi:Retencion Impuesto="001" Importe="33.75"/>
        </cfdi:Retenciones>
        <cfdi:Traslados>
            <cfdi:Traslado Base="2700.00" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="432.00"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
En este caso las retenciones son iguales para los 2 conceptos, es decir 16.88, como son 2 productos el total de retenciones debería sumar 33.76. 
En su lugar se reporta 33.75  (1 centavo abajo), que resulta de la suma de los importes de las 2 retenciones utilizando todos los decimales.

En el catalina lo encuentras justo arriba de esta línea:

**2024-02-16 09:02:59,932 DEBUG [https-jsse-nio-8443-exec-49] (CFDBusinessLogicProvider.java:357) - Calling FacturaTi**

**Comment by jccastillo0007** [comment]
fixed, checale en pru

**Comment by RigoFlores** [comment]
Ayer ya se subió a producción, que no?
