### ISSUE TITLE
AFT - la suma de los importes de impuestos a nivel concepto, no es igual a la reportada a nivel general

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2376]
Lo mismo de ayer en PFT1.0

El importe de los impuestos a nivel conceptose reporta a 2 decimales, OK (se redondea).
La suma de los importes, no se está realizando con esas cifras a 2 decimales, sino se realiza con 6 decimales, entonces dependiendo de la combinación de cifras, así como ayer, puede variar y tronar.

El importe de impuestos trasladados o retenidos a nivel global, debe de calcularse con la suma de los importes a 2 decimales que se reporta a nivel concepto.

Lo vi en biosplash, pero no sé si en todos los AFT está igual...

**Comment by jccastillo0007** [comment]
fixed.

solo es cuestión de volver a liberar todos los AFT para que apliquen el mismo fix de ayer en pftv1

**Comment by RigoFlores** [comment]
ayer, tuve que modificar los precios a 2 decimales (redondeados) y con ello esa variación ya no afectó.
Pero si, se requiere hacer esos cambios... tu me dices cuando los subas a pru, para que pueda hacer esas validaciones...

**Comment by jccastillo0007** [comment]
Por eso le puse el label de resolved ayer... chiaaa

**Comment by RigoFlores** [comment]
pues dijiste que era cuestión de volver a liberar, tons eso lo entendí que aún no se liberaba.
Lo validaré entonces...

**Comment by RigoFlores** [comment]
ok, ya está validado en biosplash... si así quedó ya en todos, está bien...
en cuanto tenga chance, iré validando en los otros AFT's..

pero esta sección del código, no es común para todos???
