### ISSUE TITLE
AFT Biosplash y Alteza, marca el error de digestion

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2377]
Cuando algún dato del XML incluye un caracter especial tipo acento o ñ.

En alteza fue en el nombre del cliente. Aquí no podemos cambiar la Ñ, por ejemplo de NUÑEZ.
En biosplash fue en el nombre de producto... este podemos eliminar el acento.

Entiendo que este problema, se puede presentar en cualquier AFT, PFT2.0 o no sé, si incluso en la PFTv1.0

**Comment by RigoFlores** [comment]
Ya vimos que en PFTv1.0 no se presenta
Solo es en AFT,  o PFTv2.0

**Comment by jccastillo0007** [comment]
Negativo, pftv1 también lo tiene en pru

**Comment by RigoFlores** [comment]
Si, yo me refería a PFTv1.0 en producción. Afortunadamente ahí está funcionando.

El asunto según entiendo, se presenta en el ambiente de pruebas, así como en el servidor nuevo de producción.
Algo tienen en común esos ambientes.
En teoría el código en pruebas de PFTv1.0, es el mismo que en producción, quizá por ahí no va el asunto.

Pero bueno, pues yo desconozco el detalle.
