### ISSUE TITLE
PFTv2.0 - Consultas, poder enviar el correo a donde se requiera

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2379]
En particular en Alteza.
Ellos entraban a PFT1.0, y desde consultas le daban reenviar la factura... se abre la ventana donde pueden teclear el correo que quieran. OK, hasta ahí, todo bien.

Luego, al moverlos al conector v2.0, ya no pueden consultar sus facturas en PFTv1.0

En su lugar, les indicamos que ahora será desde la PFTv2.0, solo que hay un detalle, el reenvío de facturas ya no lo pueden hacer igual. Si no existe dado de alta el registro del cliente (receptor de la factura) con un email capturado, no envía nada.
Ellos quieren contar con la misma función que tenían en pft1.0

Es decir, que al reenviar la factura, puedan capturar el correo. Puede ser una ventana así como en pftv1.0, que sería lo ideal, o pues al menos que puedan capturar el correo a un lado del ícono del correo.

**Comment by jccastillo0007** [comment]
fixed
