### ISSUE TITLE
NO REALIZA LOS CÁLCULOS CORRECTAMENTE EN LA FACTURA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#238]
CUANDO CAPTURAS UNA FACTURA Y TIENES LA NECESIDAD DE EDITAR UN PRODUCTO, PARA CAMBIAR POR EJEMPLO LA CANTIDAD DEL MISMO, NO ACTUALIZA LOS IVAS, Y LOS REPORTA CHUECOS EN EL XML Y PDF.
PARA MUESTRA VER LA FACTURA 35 DE LA TIA EN WEB, CON FECHA DE HOY.

**Comment by RigoFlores** [comment]
EL PROBLEMA SE PRESENTA AL EDITAR UN PRODUCTO DE LA FACTURA, Y MODIFICAR O EL IVA, O EL PRECIO O LA CANTIDAD. ES DECIR, MODIFICAR EL TOTAL DE LA FACTURA.

**Comment by jccastillo0007** [comment]
Lo bueno... Ya esta corregido el tema de los calculos...

Lo malo... hay otro pedo.... si entran a editar un producto, le hacen cambios.... pero al final cancelan la edicion... de todos modos aplica dichos cambios a la factura.... estoy sobre esto...
