### ISSUE TITLE
AFT Virtual Homes - marca error al timbrar un ticket:  401 : Fecha y hora de generación fuera de rango (3)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2381]
Este es un ejemplo de los tickets que están arriba y no timbran:

[VirtualHomesTest.csv.txt](https://github.com/jccastillo0007/eFacturaT/files/14225919/VirtualHomesTest.csv.txt)

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ahora marca lo mismo para el galpón en producción...
Hay que corregirlo en producción para todos los AFTs: Abastos, Alteza, Galpón, Biosplash

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
acabo de intentar en pru, del galpón y marcó el error... chiaaaa
Necesitamos hacer los cambios juntos, por eso luego se inyectan defectoss... ahorita porque se me ocurrió probar con las remisioes que ya estaban de antes... sino, pues simplemente se va el defecto a pro nuevamente...

**Comment by jccastillo0007** [comment]
listo, ya lo subi a pru
