### ISSUE TITLE
Virtual Homes - no actualiza el status de las remisiones cuando ya han sido facturadas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2382]
De hecho el status debería ser Facturada, en lugar de pagada... cuando una remisión ya ha sido facturada.

Ahora mismo, lo pone a pagada.
Pero en virtual homes (pru), no actualiza dicho status de LA REMISIÓN.

**Comment by jccastillo0007** [comment]
si lo hace, pero si hay facturas duplicadas con el mismo folio, solo actualiza la primera.... 
con ellos aún no tenemos mecanismo para no aceptar duplicados... lo implementamos ya que paguen

**Comment by jccastillo0007** [comment]
con folios no duplicados funciona bien

**Comment by RigoFlores** [comment]
Si, ya vi y validé lo que mencionas.

Oye, pero yo creo que eso debe ser la regla. No duplicados para la combinación de:

**_RFC Emisor - trackingID - Folio_**, o el equivalente... por ejemplo en alteza, no es folio, sino número de reserva.

He estado pensando, y si, creo que debe ser una regla... y cuando no aplique se notificaría para casos excepcionales.
