### ISSUE TITLE
Alteza AFT - colocar 2 correos de envío automático al emisor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2383]
envío automático a 2 correos desde AFT del Alteza...

contabilidad@condesahotels.com
reservaciones@altezapolanco.com

Esto es el paliativo para el tema de envío de correo desde PFTv2.0 Consultas-Envio de correo

**Comment by jccastillo0007** [comment]
oye, desde el AFT si debe funcionar enviar el email a dos correos... ya lo probaste ?

**Comment by RigoFlores** [comment]
los colocaré en producción.
SI jaló en AFT de pruebas para el galpón

**Comment by jccastillo0007** [comment]
si, también lo probé desde alteza
