### ISSUE TITLE
PFTv1.0 (producción) - no reporta correctamente la base del IVA cuando se calcula en BASE IEPS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2384]
Cuando el IVA se calcula en base IEPS, primero se toma el importe., se le calcula el IEPS y se le suma al importe.
Para el cálculo del IVA, la base es el (cantidad * precio untario - descuentos)  + monto del IEPS.

Eso ha trabajado así desde siempre.
Yo creo que los cambios últimos le pegaron a esto.

Ejemplo:
cantidad: 2
Precio unitario: 200 
IEPS: 2.5%
IVA: 16%

importe = cantidad x precio unitario = 2*200=400
base:  importe - descuentos = 400
Importe IEPS: 10

Base IVA = base + importe IEPS= 410.
Importe IVA = 65.60

Total = base + importe IEPS + importe IVA = 400 + 10 + 65.60 = 475.60

Así lo estaba haciendo antes.

[FE720_MFB170321TS0_MOC170322PM1_11Jan2024_145407.xml.txt](https://github.com/jccastillo0007/eFacturaT/files/14251818/FE720_MFB170321TS0_MOC170322PM1_11Jan2024_145407.xml.txt)

Pero ahora intenta hacer esto:

        <cfdi:Concepto ClaveProdServ="78101800" NoIdentificacion="FLETE" Cantidad="10.00" ClaveUnidad="E48" Unidad="SERVICIO" Descripcion="FLETE SERVICIO DE FLETE" ValorUnitario="528.000000" Importe="5280.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="5280.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="865.08"/>
                    <cfdi:Traslado Base="5280.000000" Impuesto="003" TipoFactor="Tasa" TasaOCuota="0.024000" Importe="126.72"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="991.80">
        <cfdi:Traslados>
            <cfdi:Traslado Base="5280.00" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="865.08"/>
            <cfdi:Traslado Base="5280.00" Impuesto="003" TipoFactor="Tasa" TasaOCuota="0.024000" Importe="126.72"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
</cfdi:Comprobante>

**Comment by jccastillo0007** [comment]
este ya quedo a nivel producto, pero falta a nivel general

**Comment by RigoFlores** [comment]
El cliente ya tiene 2 días detenido.

Si vi que ya quedó a nivel de cada producto... 
Creo que solo falta hacer bien la suma de las bases de cada tipo de impuesto, en este caso el IVA, ya que esa base es distinta a la base IEPS.

Me preocupa un poco, todos estos detalles que hemos ido reinyectando... porqué o de donde aparecieron?

**Comment by jccastillo0007** [comment]
checale...

**Comment by RigoFlores** [comment]
Lo trabaja bien cuando un solo producto de la factura contiene el IVA calculado con base IEPS.
Pero si a una factura, le agregas varios productos y 2 o mas productos les incluyes IVA con base IEPS, no lo hace bien. Solo considera el primer producto en la suma de las bases de IVA.

Lo puedes trabajar en emisor IIA, receptor la tia, cfdi FACTURA, productos: flete, PC y prod_FTT colocándoles a todos el IEPS y con cálculo de IVA base IEPS.

**Comment by jccastillo0007** [comment]
checale

**Comment by RigoFlores** [comment]
listo, ya lo hace bien.
Pls, subirlo a pro...
