### ISSUE TITLE
Conector 1.0 - carta porte traslado debe reportar subtotal=total=0, es decir sin decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2386]
Aquí tienes un archivo para reproducir la falla, ya que está reportando como 0.00 ambos atributos.

En teoría debe timbrar este archivo una vez corregida esa falla.

[CP_BARRICAS.txt](https://github.com/jccastillo0007/eFacturaT/files/14274599/CP_BARRICAS.txt)

con esta llave.

[facturaT_XIQB891116QE4.cfdi.txt](https://github.com/jccastillo0007/eFacturaT/files/14274601/facturaT_XIQB891116QE4.cfdi.txt)

**Comment by RigoFlores** [comment]
Estuve probando con la versión del 26 de julio 2023, que es la que tienen en las barricas.
Y de hecho, la última que se instaló para esa versión.
Hubo una que corregía forma de pago y método de pago en alteza, pero pues esa ya quedó obsoleta. En Alteza tienen el nuevo conector 2.0

**Comment by jccastillo0007** [comment]
Este ya se corrigió , pero se subió directo a prod...
puedes checar en pru, ya subí la corrección ahí.

**Comment by RigoFlores** [comment]
esta no requiere de actualización del conector entonces?
