### ISSUE TITLE
Conector 1.0 - implementar carta porte ingreso.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2387]
Hasta donde tengo documentado, no tenemos este tipo de CFDI por conector.
Es una combinación de

tipoDeComprobante=0   (que es factura, es decir tipo ingreso) y
tipoDeComprobante=6  (que le corresponde carta porte tipo traslado)

Cuál sería el tipo de comprobante para carta porte tipo ingreso?

aquí dejo un archivo de prueba que en teoría debía jalar...

[CARTA PORTE INGRESO.txt](https://github.com/jccastillo0007/eFacturaT/files/14274622/CARTA.PORTE.INGRESO.txt)

**Comment by jccastillo0007** [comment]
En teoría ya se soporta, es el tipo de documento 99
