### ISSUE TITLE
Eliminar histórico de remisiones para abastos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2388]
Borrar todas las remisiones cuyo folio < 2,006,747  (es decir borrar mas de 2 millones de registros de remisiones de abastos)

Serie: REM
sourceRFC:  AMA131218E12
Fecha: 2023-08-07  (todas las remisiones con fecha menor a esta)

lo ideal es borrarlas, pero si reasignas el sourceRFC que sea "aAMA131218E12"  (le anteponemos la primera letra del RFC, pero en minúscula)

**Comment by jccastillo0007** [comment]
deleted

**Comment by RigoFlores** [comment]
reportaron que ya se tardaba mucho la búsqueda de ticket.
ya revisé y si redujo el tiempo de búsqueda
