### ISSUE TITLE
PFTv1.0 - CCE 3.0 , cuando se emite en EUR, no reporta correctamente en USD

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2389]
El CFDI estándar se emite en EUR, con su respectivo tipo de cambio.
En el complemento se debe reportar en USD.

Entonces, los productos en el CFDI estándar tienen un importe en EUR.
La correspondencia para reportarlo en el CCE es calcular el valorDolares y valorUnitarioAduana en USD:

ValorDolares = (Importe en EUR ) * (TC EUR / TC USD)
ValorUnitarioAduana = ValorDolares / Cantidad

**Comment by RigoFlores** [comment]
Esto aplica, siempre que la moneda del CFDI, sea distinta a MXN.
En ese caso, el cálculo se realizará igual con con los EUR.

**Comment by jccastillo0007** [comment]
Esto ya funcionaba ?
Que es exactamente lo que hace mal?
Cómo se reproduce ?

**Comment by RigoFlores** [comment]
_No estoy seguro que esto ya funcionara en web, me parece que si. Con optibelt, seguro que si._

**Lo que no hace bien, es la conversión de euros (la moneda original del CFDI que es distinta a MXN) a USD, que es la moneda que se reporta en el CCE.**

Para reproducirlo:
Emisor: IVD
Receptor: XEXX
Tipo de cambio USD: el del día de ayer publicado en el DOF (para hoy viernes 16 de feb, ya capturé el de ayer 15)
Producto: TEST, precio unitario 100 EUR.
Check en cajita de incluir CCE

Datos del CCE:  (únicamente capturar estos datos, los que muestra por default, así se quedan).
Número de Registro Receptor: 123456789
Fracción arancelaria: 6802100100
Unidad: 01

De hecho va a timbrar el XML, pero lo que está incorrecto es como reporta los importes en el CCE:

Partimos de calcular el ValorDolares, de cada producto, de ahí el valorUnitarioAduana y finalmente el ValorTotalDolares.
Cálculos Correctos:

ValorDolares = (Importe en EUR ) * (TC EUR / TC USD)
ValorUnitarioAduana = ValorDolares / Cantidad

Y el TotalUSD que se reporta en el header del CCE, es la suma de ValorDolares de cada producto.


**Hoy lo que hace mal, según yo es que el cálculo de valorDolares de cada producto cuando la moneda es distinta a MXN**
Lo toma como si la moneda fuera MXN, es decir lo calcula como se muestra aquí abajo, con un tipo de cambio 1 en lugar de la moneda que corresponda, que es distinta a MXN:
ValorDolares = (Importe en EUR ) * ( 1 / TC USD)


según yo, todo se reduce a colocar el tipo de cambio de la moneda original en el cálculo del ValorDolares

**Comment by jccastillo0007** [comment]
checale en pru... me parece que ya está haciendo los cálculos correctos... 

te aviso que la fórmula que definiste para valor dólares y valor unitario aduana, es completamente diferente a lo que se tenía antes... cuando era solo dólares... habría que probar todo eso

**Comment by RigoFlores** [comment]
Ya revisé, si hizo bien los cálculos para ValorDolares, y valorUnitarioAduana 
Acabamos de solicitar que el valorUnitarioAduana se reporte a 6 decimales y ya se está reportando a 2 decimales. Es justo el cambio que se pidió para CCE 3.0 y ya se regresó. No maaaa....

Retomando el tema.
En este ejemplo que intenté timbrar con IVD, la tia, dos productos cualquiera en EUR :
        <cce20:ComercioExterior CertificadoOrigen="0" ClaveDePedimento="A1" Incoterm="EXW" TipoCambioUSD="1.075697" TotalUSD="1301.48" Version="2.0">
            <cce20:Mercancias>
                <cce20:Mercancia CantidadAduana="5.0" FraccionArancelaria="6802100100" NoIdentificacion="TEST" UnidadAduana="01" ValorDolares="1075.70" ValorUnitarioAduana="215.14"/>
                <cce20:Mercancia CantidadAduana="4.0" FraccionArancelaria="6802100100" NoIdentificacion="baseIVA01" UnidadAduana="01" ValorDolares="430.28" ValorUnitarioAduana="107.57"/>
            </cce20:Mercancias>
        </cce20:ComercioExterior>

En este ejemplo, hizo bien el cálculo de ValorDolares y ValorUnitarioAduana (excepto que tiene que ir a 6 decimales). Esta es la clave de todo y está bien.

ValorDolares = Importe EUR ( TC EUR / TC USD) = 400 * ( 18.36 / 17.068 ) = 400 * 1.075697 = 430.28    OK
ValorUnitarioAduana = ValorDolares / cantidad = 430.28 / 4 = 107.57    este cálculo está bien, pero ya se eliminó que fuera a 6 decimales.

El totalUSD está mal reportado, ya que es la suma de los ValorDolares = 1075.70 + 430.28 = 1505.98
En su lugar está reportando 1301.48 no se de donde saca este valor.
Finalmente en el complemento, se está reportando incorrectamente el tipo de cambio USD, no sé porqué tuvo que modificarse, ya que el tipo de cambio se toma del catálogo. En este caso debió reportar como 17.068

**Comment by jccastillo0007** [comment]
done. valorUnitarioAduana se reporte a 6 decimales  //copy paste del ajuste de valor dólares
done. total USD
done. tc USD

**Comment by RigoFlores** [comment]
no quedó cuando la moneda origen es MXN.

OJO, el valorUnitarioAduana, se reporta a 6 decimales SIGNIFICATIVOS, es decir no solo se rellena de ceros, porque entonces no tiene sentido.
La regla dice que se puede reportar HASTA 6 decimales, entonces de ahí nos tomamos para no recalcular nuevamente el ValorDolares, como lo hacíamos antes, precisamente porque 2 decimales no eran suficientes para cuadrar las cifras
