### ISSUE TITLE
PFTv1.0 - Emisión de nómina, el total es incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2390]
Nómina es un complemento.
En el CFDI estándar, únicamente se reporta 1 concepto, similar a esto (no lleva nodo impuestos):

    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="84111505" Cantidad="1" ClaveUnidad="ACT" Descripcion="Pago de nómina" ValorUnitario="2624.230000" Importe="2624.23" Descuento="68.40" ObjetoImp="01"/>
    </cfdi:Conceptos>

A nivel header del CFDI los cálculos son estándares, igual que todo CFDI:
subtotal = sumatoria de importes
Total =  subtotal - descuentos + traslados - retenciones

Ahora mismo no está descontando el descuento, por lo que el total y el subtotal los reporta igual.

SubTotal="2624.23" Descuento="68.40" Moneda="MXN" Total="2624.23" TipoDeComprobante="N" 

Este es el XML que intenta timbrar, pero marca error justo porque no se resta el descuento:

[nominachueca.txt](https://github.com/jccastillo0007/eFacturaT/files/14315255/nominachueca.txt)

**Comment by jccastillo0007** [comment]
checale en pru

**Comment by RigoFlores** [comment]
mismo caso que la factura global. Error de digestionblablabla

La descripción del concepto en el rescibo de nómina ya está definida y contiene acento.
Y por esa razón no puede timbrar en pru.

**Comment by RigoFlores** [comment]
ok, ya quedó en pro... tssss
