### ISSUE TITLE
PFTv1.0, los datos de la factura global los envía incorrectos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2391]
Le seguimos pegando a lo que ya estaba jalando. Está ya preocupante el asunto, no sé como está el control de versiones, pero pues se está generando una molestia en los clientes, y un retrabajo para nosotros, impresionante.

Ahora pegó en los datos cuando se captuara la sección de factura global.

_INCORRECTO Está mandando algo así como esto:

<cfdi:InformacionGlobal Periodicidad="04 Mensual" Meses="02 Febrero" Año="2024"/>_

**CORRECTO: Pero en periodicidad y meses, solo debe mandar las claves, es decir:

<cfdi:InformacionGlobal Periodicidad="04" Meses="02" Año="2024"/>**

**Comment by jccastillo0007** [comment]
fixed en pru

**Comment by RigoFlores** [comment]
No hay forma de validarlo.
Esta factura incluye un atributo "Año", y no puede timbrar con caracteres especiales... acentos, ñ's son los que al menos tengo identificados.
Y según recuerdo en producción, bajo ciertos escenarios, se presenta este problema.

Quizá haya que probarlo en producción... 
pero necesitamos arreglar este asunto... yo creo que deberías escribirles directamente a Finkok.
