### ISSUE TITLE
PFTv1.0 - CARTA PORTE TIPO TRASLADO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2392]
El subtotal y el total para el CFDI con complemento de carta porte tipo traslado, debe ser '0' en ambos casos.
Lo está mandando como 0.00

Qué onda con el control de cambios?
Corregimos 1, y se descomponen 5.... no maaaa

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
En pruebas ya timbró.
No estoy seguro si ahí se podría reproducir el problema.

Hay que subirlo a producción en chinga, ojalá que no le peguemos a otra cosa.
