### ISSUE TITLE
PFTv1.0 - CFDI con complemento de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2393]
Mismo caso que el carta porte tipo traslado. 
Es decir en el header del CFDI estandar, se debe reportar así:

SubTotal="0" Moneda="XXX" Total="0"

y se está reportando así:

 SubTotal="0.00" Moneda="XXX" Total="0.00"

Otro defecto inyectado.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
En pruebas ya timbró.
No estoy seguro si ahí se podría reproducir el problema.
Y pues creo que no puedo estar validando todos los escenarios que existen, que son muchos.

Hay que subirlo a producción en chinga, ojalá que no le peguemos a otra cosa.
