### ISSUE TITLE
PFTv1.0, no está sumando los impuestos trasladados locales en las facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2394]
Pues acaba de surgir otro problema de esos reinyectados. Algo que desde hace muuuuchos años venía funcionando.

En facturas con impuestos locales... no está sumando los traslados de impuestos locales... y me imagino que tampoco restaría las retenciones locales. No tardan en reportarme lo de retenciones

**Comment by jccastillo0007** [comment]
fixed
