### ISSUE TITLE
PFTv1.0 - Marca error al intentar timbrar con IVA trasladado exento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2395]
Otra afectación de lo que ya jalaba.

Cuando eliges IVA exento para un producto dentro de la factura, no timbra la factura.

Para reproducir en pru, emisor IVD, receptor la tia, producto TEST (dejar cantidad y precio unitario sin cambio).
 
Elegir IVA 0, que está configurado como exento.

**Comment by jccastillo0007** [comment]
fixed
