### ISSUE TITLE
AFT - Virtual Homes, agregar que capturen la forma de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2397]
Emisor en pru: MISC

Veo 2 opciones:

a) Agregarlo únicamente para Virtual Homes, con el default de Transferencia

b) Agregarlo para todos, con el default igual a la forma de pago que corresponda dependiendo del emisor-conector.

Lo ideal es (a), pero si le pega menos, pues entonces (b)

Cómo vex???

**Comment by jccastillo0007** [comment]
pegas mas la b, ya que todos son proyectos diferentes

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Al timbrarlo no está respetando la forma de pago capturada en pantalla.
En su lugar incluyó en el PDF y XML forma de pago 99, y yo capturé 04. tarjeta de crédito.

validé con remisiones previamente capturadas, que en su momento tenían transferencia me parece.

**Comment by jccastillo0007** [comment]
checa las facturas con folio 7111 y 7222, ahí lo probé y si funciono

**Comment by RigoFlores** [comment]
hice una  prueba con un ticket nuevo, y ese si lo procesó correctamente.
Por cierto, en la pantalla principal, aparece algo en el extremo inferior izquierdo caption algo, del 1 al 3...
