### ISSUE TITLE
AFT - Virtual Homes, agregar la funcionalidad para mostrar un carrusel de imágenes en la pantalla principal del AFT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2398]
Inicialmente lo podemos hacer para 3 imágenes. 
Lo ideal es que puedan ser n.

Las imágenes se cambiarán cada mes. En este caso, pues hay que cambiarlas manualmente, pero si pensar en algo así como un chel automático. 

Incluso, lo ideal ideal (lo mas verch) es que el conector de virtual homes, pueda tomar las imágenes y enviarlas a la plataforma, para que sea automático el pedo. Cómo la beisbol?

O una tercera opción, sería configurarlas desde una pantalla de configuración.

Esto podría llegar a ser algo muy común en el AFT. Vamos nutriendo esa funcionalidad.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
oye, comentamos que moveríamos hacia la izquierda los datos de usuario y contraseña y a la derecha se mostraría el carrusel.
Hay que definir cuáles serían las medidas mas adecuadas de las imágenes.

**Comment by jccastillo0007** [comment]
así  como está es lo más adecuado
el tamaño de las imágenes lo puedes definir tu

**Comment by RigoFlores** [comment]
es que lo adecuado para una promoción me parece, es que cuando entres, veas es información.
Si se queda abajo, no la verán, será como si no existiera, lo cual no tiene caso.
Quizá se pueda acomodar por css... quieres que lo intente?
Sería cosa que me pases el HTML de esa página...
