### ISSUE TITLE
NOMBRE ALTERNO LO COMBINA CON SUCURSAL Y NO JALA UNA NI OTRA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#24]
EN EL CATALOGO DE CLIENTES, UN TEMA ES SUCURSAL Y OTRO ES NOMBRE ALTERNO. ENTIENDO QUE LO QUISIERON MEZCLAR CUANDO SON 2 COSAS DISTINTAS, QUE INCLUSO ESTÁN EN DISTINTO CATÁLOGO PARA EL STAND ALONE. SUCURSAL, SIRVE PARA LLENAR LOS DATOS DE EXPEDIDO EN. NOMBRE ALTERNO SIRVE PARA LLENAR OPCIONALMENTE LOS DATOS DEL EMISOR. 
INSISTO QUE LLEGAMOS AL ESTADO DEL ARTE EN ESTÁNALON, Y AQUÍ QUEREMOS REINVENTAR COSAS, QUE YA TIENEN 2 AÑOS DE MADUREZ.

SON 2 CATÁLOGOS INDEPENDIENTES: SUCURSAL Y NOMBRE ALTERNO.
EN AMBOS CASOS, SERÁ OPCIONAL ELEGIRLOS COMO TALES (PARA LLENAR DATOS DE EXPEDIDO EN O EMISOR RESPECTIVAMENTE)

**Comment by jccastillo0007** [comment]
Este defecto mejor que quede deprecated porque no entendi ni ma.....

Me quedo con la explicación del correo que me enviaste y con el antecedente de que por ahora, no soportamos sucursales, unicamente nombres alternos....

En el fondo, me parece que seria lo mismo, un nombre alterno o una sucursal, la diferencia radica unicamente en que si es la sucursal del emisor o receptor... 

pero lo platicamos vale.

**Comment by RigoFlores** [comment]
YA QUEDÓ FUNCIONANDO OK EL NOMBRE ALTERNO.
PODRÍA NO SER SUCURSAL DEL RECEPTOR, ESO NO LO SABEMOS. POR ELLO LO MANTENDREMOS COMO NOMBRE ALTERNO.
POR EJEMPLO EN MABE, QUE PARA EL MISMO RFC, OCUPAN MISMO NOMBRE, PERO DOMICILIO DISTINTO, ESTÁ MUY CLARO QUE NO SON SUCURSALES.
EN EL CASO DEL TEC DE MONTERREY, CADA CAMPUS PODRÍA O NO SER UNA SUCURSAL, (CREO QUE NO)
TOTAL, QUE ASÍ COMO QUEDÓ, ESTÁ MAS QUE BIEN.
VIENTOS....
