### ISSUE TITLE
cuando no calculas percepciones o deducciones gravadas, marca error 301

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#240]
SE PRESENTA EL SIGUIENTE ERROR, CUANDO ALGUNA PERCEPCIÓN O DEDUCCIÓN, QUEDA = 0, EN LA PARTE DE GRAVADOS, ES DECIR TODO SE CAPTURA EN EL LADO DE EXENTO.
EJEMPLO EN PRU CON EL USUARIO TIA101020BP4, EMPLEADO JUAREZ MONTES ERNESTO

cvc-complex-type.4: Attribute 'TotalGravado' must appear on element 'nomina:Percepciones'.cvc-complex-type.4: Attribute 'TotalExento' must appear on element 'nomina:Percepciones'.cvc-complex-type.4: Attribute 'TotalGravado' must appear on element 'nomina:Percepciones'.cvc-complex-type.4: Attribute 'TotalExento' must appear on element 'nomina:Percepciones'. (301)

**Comment by jccastillo0007** [comment]
fixed... las validaciones estaban bien, solo habia un error de dedo...

Solo se presentaba en el caso que el gravado de percepcioens fuera 0, en cualquier otro caso no habia problemas.... pero ya esta corregido.
