### ISSUE TITLE
Conector Hostal - El Galpón gestión de tickets duplicados.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2402]
Para el Hostal... en el conector, se debe permitir la combinación de folio - total.

Ahora mismo, permite la repetición del folio, pero no del total... 

Son 2 peticiones:
1) Que únicamente en el caso del hostal, permitir duplicados en la combinación de ID-Total
2) Cuando un ticket se busque en AFT, y si ese ticket tiene duplicados, entonces el total a buscar, debe ser la suma de todos los tickets duplicados.

Ejemplo:
EL ticket 10350 se ha subido 3 veces con los siguientes totales: 300, 300, 600.

Entonces en AFT del Hostal, cuando el usuario teclee el ticket 10350, entonces buscará el total de 1,200.00, es decir la suma de todos los totales del ticket repetido.

Esto sucede cuando un huésped, realiza varios pagos durante su estancia en el hotel.

Así es como acordamos inicialmente que trabajaría, es decir... esta es la opción 1

**Comment by RigoFlores** [comment]
Existe otra opción que quizá pudiera ser mas sencilla... 
Que en el FTT, se pudieran enviar folios, tanto para el galpón (solo con IVA), o para el hostal (IVA e Impuesto sobre hospedaje).

Por ejemplo, 
Si el número de ticket inicia con G o H, sería un folio con comportamiento para galpón u hostal, respectivamente.
Este se ocuparía en lugar de estar haciendo las sumas de los folios repetidos para los registros del hostal.

cómo la beisbol???

**Comment by jccastillo0007** [comment]
no FTT, en este caso le agrega mas trabajo al usuario, que es lo que no queremos

**Comment by jccastillo0007** [comment]
Ya está el punto 1.

Para el punto 2, en AFT, cómo se puede saber que es un folio del hostal ?

**Comment by RigoFlores** [comment]
Del punto 2, pues de la misma manera que hoy se hace.
Hoy podemos distinguir folios cuyo origen es hostal o el galpón. 
Bueno, mas bien, si entiendo bien, es al momento de almacenarse en BD donde se hace la distinción, ya que se desglosa el impuesto sobre hospedaje para el hostal, pero para el restaurante (es decir, el galpón) solo es el IVA.

**Comment by jccastillo0007** [comment]
está mucho mas complicado... porque ahora hay que acumular no solo el total, si no, todas las cifras y productos de cada folio

**Comment by RigoFlores** [comment]
Sugiero lo siguiente...
Tener un registro base... ese se va actualizando cada ocasión que llegue un registro repetido. Con ello los impuestos del hostal, siempre estarán actualizados, tomándolos igual que cualquier otro registro que no tiene repetición.

Llevar un histórico de repetidos, agregando al final del número de folio, el -01, -02, -03, etc... 

la otra es retomar el tema FTT, que de una vez, se registra todo.

**Comment by jccastillo0007** [comment]
crea un ticket para el FTT , ya que es la mejor y más rápida
