### ISSUE TITLE
Hostal - agregar su funcionalidad al FTT del Galpón

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2403]
Ahora mismo, tenemos FTT para el Galpón.
Eso quiere decir, que al total, le desglosamos el IVA.

OK, ahora eso mismo, hay que agregarlo para soportar el Hostal.
Mi sugerencia, es al folio, anteponerle una letra H (de hostal) y el total a facturar ellos lo capturan.
De esta manera, al total se le desglosa el IVA y el Impuesto sobre hospedaje, DE LA MISMA MANERA QUE SE HACE AHORA MISMO PARA EL CONECTOR, con el layout del Hostal.

Con ello, cuando tengan esta necesidad, solo capturan el folio (con su prefijo H) y el total desde FTT, se almacena como tipo Hostal y asunto resuelto.

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
Listo, puedes probarlo
