### ISSUE TITLE
Contabilizar cada petición de cancelación atendida, como un folio consumido para este RFC TRA8402225G0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2404]
No si si lleguen a pagar.
Necesitamos que cada cancelación se consuma un folio. Y si ya no tienen folios, pues que no cancele, jeje.

Por lo pronto ya moví su certificado de las carpetas correspondientes en el servidor, para que ya no puedan cancelar.

A ver si en algún momento requieren pagar lo que ellos nos digan, ya que nosotros ya no tenemos forma de saber de manera mas fehaciente.
A menos que le preguntemos a FactureHoy, lo cual pudiera ser contraproducente, ya que ese servicio nos lo cobraban aparte. Creo que solo teníamos hasta 2,000 cancelaciones de PAC externos.

Nuestra estimación anda en esto:

**1. Los números que ellos nos dieron del 2022, son 16,043 cancelaciones.
2. En febrero del 2024, cuando nos solicitaron actualizar el csd, cancelaron en un solo día 7,000.
3. Se solicitaron 10,000 folios en julio 2022, mismos que se consumieron en su totalidad en Diciembre 2022. Esto es, un consumo promedio de 2,000 folios mensuales para la cancelación. (lo cual no se puede tomar realmente así, ya que ellos envían a cancelar miles de CFDI en ciertos días que seguramente no son constantes).**

Si tomamos éste último promedio, a febrero del 2024 se habrán consumido 28,000 folios adicionales (cancelaciones en este caso).
Los números que nos dieron para el 2022, fueron como ya se mencionó arriba, de 16,000... lo cual en promedio serían 1,350 folios mensuales.

Lo anterior arroja un promedio entre 1,350 y 2,000 folios mensuales, lo cuál tiene una variación muy alta, pero bueno es lo que hay.
Es decir entre 18,900 y 28,000 folios que no han pagado. 
Promedio entre rango alto y bajo: 23,450 folios pendientes de pago.

**Comment by jccastillo0007** [comment]
Esto aplica solo para este rfc : TRA8402225G0  ? 
Antes lo hacía para todos los rfc, ahorita lo deje solo para ese...

**Comment by RigoFlores** [comment]
jaja, no manches... las cancelaciones nunca se habían descontado de los folios.
únicamente para este rfc... tssss...
 y no funcionó... jajaja

bueno, pues hay que subirlo a pro, de todos modos ahorita no está su certificado de sello digital en los directorios donde los busca la aplicación

**Comment by jccastillo0007** [comment]
listo, ya está en prod

**Comment by RigoFlores** [comment]
Validaré los 3 escenarios:
a) que con una cancelación exitosa, descuente folio
b) que con una cancelación NO existosa, NO descuente el folio
c) si ya no tienen folios disponibles, que no cancele.

Ayer hablé con ellos finalmente... y eso fue seguramente porque moví el CSD y ya no podían cancelar... me dieron unos números, no tengo forma de refutarlos y por lo pronto los acepté... 

Estoy en espera que manden XML para validar el comportamiento y también que paguen los pasados y los nuevos XMLs
