### ISSUE TITLE
El RFC de abastos se está yendo a timbrar por Finkok

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2405]
Parece que este RFC AMA131218E12 se va de todas-todas, o al menos la gran mayoría de ocasiones, a timbrar por finkok.
Ya que cuando intenta por fhoy marca lo siguiente:

2024-03-12 09:45:54,181 ERROR [https-jsse-nio-8443-exec-11] (FactureHoyService.java:137) - org.springframework.ws.client.WebServiceTransportException: 404 [404]
org.springframework.ws.client.WebServiceTransportException: 404 [404]

Le estamos pagando a ese cliente, el timbrado por finkok.

**Comment by jccastillo0007** [comment]
si, esta mal la url, ya la actualicé, en la noche reinicio el server

**Comment by jccastillo0007** [comment]
ya está en prod

**Comment by RigoFlores** [comment]
lo podré validar hasta que facturen,.
Entré al server y no facturas desde el 2-3 de marzo.
La siguiente semana me vuelvo a asomar.

**Comment by RigoFlores** [comment]
hasta hoy se pudo validar la solución, pero bueno ya estaba cerrado este ticket.
