### ISSUE TITLE
Conector Virtual Homes, ajustes en su layout... 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2406]
No maaaa, no lo subí... esto lo hice desde la semana pasada.
Pero si mandé un correo

[RESERVAS ENERO .xlsx.txt](https://github.com/jccastillo0007/eFacturaT/files/14591604/RESERVAS.ENERO.xlsx.txt)
.

EN FORMATO CVS
COLUMNAS:
A-	ID FOLIO
B-	INMUEBLE
C-	FECHA INICIAL
D-	FECHA FINAL
E-	TOTAL A FACTURAR (SOLO CON IVA)
F-	NO APLICA
G-	NOMBRE

DESCRIPCIÓN FIJA:
ARRENDAMIENTO DE INMUEBLE “columna B” DESDE “columna C” A “columna D”. NOMBRE DEL HUÉSPED: “columna G” 

SOLO LLEVA IVA
LA FORMA DE PAGO SE DEBE ELEGIR EN PANTALLA.

**Comment by jccastillo0007** [comment]
done...
nota. hay que quitar la primer línea o agregarle un // para que sea ignorada

**Comment by RigoFlores** [comment]
para el XML la descripción está ok. En el PDF igual, así se pidió.

Peero, para el PDF podrías mandarla así para mejor legibilidad (es decir en 3 renglones distintos)??

ARRENDAMIENTO DE INMUEBLE “columna B” 
DESDE “columna C” A “columna D”. 
NOMBRE DEL HUÉSPED: “columna G”

**Comment by jccastillo0007** [comment]
noup, porque la descripción se arma desde el conector, y no puedo desmenuzarla solo para el pdf después del timbrado

**Comment by RigoFlores** [comment]
OK, entonces hacer este pequeño ajuste, es decir dar mas espacios en cada sección. Para dar mayor claridad a lo que indica. Es todo pls.

ARRENDAMIENTO DE INMUEBLE “columna B”      DESDE “columna C” A “columna D”.      NOMBRE DEL HUÉSPED: “columna G”

**Comment by jccastillo0007** [comment]
a que espacios te refieres ?

**Comment by RigoFlores** [comment]
no se grabó el espacio en el comentario de arriba que cooloqué... yo creo que hace trim el github
El punto es, en lugar de los enters, colocar unos 6 espacios en blanco, para separar en lugar de renglones, que se abra un espacio.

ARRENDAMIENTO DE INMUEBLE “columna B”     DESDE “columna C” A “columna D”      NOMBRE DEL HUÉSPED: “columna G”

<img width="597" alt="virtual homes" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/4ebbaea7-403a-433c-9433-d82b0909deb2">

**Comment by jccastillo0007** [comment]
que chacarron

**Comment by RigoFlores** [comment]
si, lo chido sería con enters, pero pues no se puede

**Comment by RigoFlores** [comment]
no se si estoy haciendo algo mal, pero no encuentra los folios que le mandé.
Es en pru con el RFC facturaT_MISC491214B86.cfdi
Anexo el archivo que le envié.

[RESERVAS.ENERO nuevo.csv.txt](https://github.com/jccastillo0007/eFacturaT/files/14829269/RESERVAS.ENERO.nuevo.csv.txt)


marcó proceso exitoso durante el procesamiento del archivo.

**Comment by jccastillo0007** [comment]
Checa desde pftv1 o pftv2 los tickets que se subieron, yo lo hice y si encontré el del folio HMQTXHDW52
