### ISSUE TITLE
El galpón - forma de pago con tarjeta, ajuste personalizado.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2407]
Cuando se detecte que la forma de pago sea con tarjeta de crédito, (que de hecho si pagaron con tarjeta de débito, será la misma columna en el archivo), se requiere que en la pantalla de AFT, el cliente tenga la posibilidad de elegir si la forma de pago fue tarjeta de débito o tarjeta de crédito (solo esas 2 opciones). Por omisión, tarjeta de crédito.

**Comment by jccastillo0007** [comment]
Ya está la opción de seleccionar la forma de pago en FR, solo me falta validar que ponga por default la que recibió por archivo, habíamos dicho que dejaríamos pago en efectivo, débito o crédito verdad, mostrando lo que se recibió por archivo

**Comment by RigoFlores** [comment]
Están bien esas 3 formas de pago, pero faltó transferencia.
Es decir, son en realidad 4 formas de pago: transferencia, efectivo, tarjeta de crédito y tarjeta de débito.

**Comment by jccastillo0007** [comment]
done.

Para ser consistentes con el hostal, tuve que agregar la forma de pago de vales de despensa...

**Comment by RigoFlores** [comment]
No, esa forma de pago (vales de despensa) no aplica ni para el hostal ni para el galpón.
Se pidió que la forma de pago que venga en el archivo se cargue por omisión en las pantallas de facturación.
EL usuario cuando pague con tarjeta... podrá seleccionar si fue tarjeta de crédito o de débito.

**Comment by jccastillo0007** [comment]
En los archivos de prueba que yo tengo, viene tickets del galpón con pago vales de despensa... ese valor se interpreta dependiendo de los valores del txt... quieres que lo quite permanentemente ?

**Comment by jccastillo0007** [comment]
bueno, ya lo quite... espero que realmente no lo usen...

Hay que probar en FI y FR

**Comment by RigoFlores** [comment]
> En los archivos de prueba que yo tengo, viene tickets del galpón con pago vales de despensa... ese valor se interpreta dependiendo de los valores del txt... quieres que lo quite permanentemente ?

Tienes razón, ahora que me aventé un clavado a las formas de pago del galpón, si se ocupa vales. 
Hice prueba con ello, y no coloca vales como forma de pago en el XML. Y en la pantalla, carga tarjeta de crédito.

Tons fue una omisión de mi parte, si hay que considerar los vales como forma de pago en el galpón.
De las demás formas de pago, si las carga y si toma tarjeta de débido, si eso es lo que cambias.

Solo falta agregar vales como forma de pago y validaré que lo "precargue"

**Comment by jccastillo0007** [comment]
Este ya se fue a prod
