### ISSUE TITLE
actualizar este formato en pro y pru, es carta porte genérico

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2408]
Ya te lo había pedido, pero regresó el error.
Hoy tuve que volver a actualizarlo, ya que el cliente reportó la regresión de la falla.

[ubicaciones.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/14749592/ubicaciones.zip.txt)

**Comment by jccastillo0007** [comment]
cómo que regresó el error
esos templates no se sobre escriben, en que servidor se necesitan?

**Comment by jccastillo0007** [comment]
ya lo subí a los dos servidores

**Comment by RigoFlores** [comment]
pues se ocupa en pro, para el cliente...
pero en pru, para que no se sobreescriba... no se que pasó, pero yo lo actualicé en pro, y jaló
a ver si no se plancha nuevamente...
