### ISSUE TITLE
Deployar Virtual Homes en producción

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2409]
Este es su RFC CAD200803NRA.
Ya estoy solicitando su certificado.

Aquí están las 2 imágenes del carrusel así como su logo.

![virtualHomes2](https://github.com/jccastillo0007/eFacturaT/assets/2912775/5645156a-fcb7-408c-afe5-d726d00450e3)
![virtualHomesLogo](https://github.com/jccastillo0007/eFacturaT/assets/2912775/efbd7e34-5653-49f8-aa93-27d0e21ed9ca)
![virtualHomes1](https://github.com/jccastillo0007/eFacturaT/assets/2912775/3f345210-457d-4e22-b939-c24066fbbc54)

Aquí su formato jasper de factura.

[jasperVirtualHomes.zip.txt](https://github.com/jccastillo0007/eFacturaT/files/14749919/jasperVirtualHomes.zip.txt)

**Comment by jccastillo0007** [comment]
https://autofacturat.com.mx/FacturacionVirtualHomes
