### ISSUE TITLE
nomina web - marca como olbigatorios campos que no lo son

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#241]
al momento de guardar, únicamente con los campos obligatorios, marca el siguiente mensaje de error:

El campo 'Salario Base' es obligatorio. 
El campo 'Salario diario integrado' es obligatorio.

**Comment by jccastillo0007** [comment]
No lo pude reproducir... incluso genere un nuevo empleado con unicamente los datos requeridos y logre generar un recibo de nomina... a los dos campos en cuestion, les agregue la validacion de que si es 0 no los mande en el recibo de nómina... esperando que sea válido y que no resulte que ahora si pueden tener un salario = 0 ...

**Comment by RigoFlores** [comment]
Reproducirlo es muy simple. Le dejas vacío el espacio en la caja de texto, y al momento de guardar te manda esos mensajes que copie de la pantalla.

**Comment by jccastillo0007** [comment]
chaaaaaa

**Comment by RigoFlores** [comment]
pensé que era corrección, pero nel... sigue vigente el errour

**Comment by jccastillo0007** [comment]
Fixed en Pruebas

**Comment by RigoFlores** [comment]
se cerrará hasta que se suba a producción, que no?

**Comment by jccastillo0007** [comment]
Mmmm como asi? Este si se puede probar en pru

JC@iPhone.
 Saludos.
