### ISSUE TITLE
Last try to rescue The Hostal - formas de pago que aparecen en los archivos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2410]
Ayer me pidieron soporte técnico del hostal, pero no sé si aún lo ocupan.
La dueña dijo que ya no lo ocuparían, pero ayer me solicitó soporte su gente.
Hacer este ajuste respecto a formas de pago soportadas, creo que no nos cuesta tanto y ya lo de tickets repetidos, pos que lo manejen aparte.

Estas son las 4 formas de pago, y así mismo aparecen el archivo de texto del hostal.

Efectivo
Tarjeta de credito
Tarjeta de debito
Transferencia electronica

**Comment by jccastillo0007** [comment]
done... el default será tarjeta de crédito, y se esperan las leyendas de arriba sin acentos

**Comment by RigoFlores** [comment]
Tomé la versión de hoy del conector, y le puse el archivo que anexo aquí.

[Septimo2023-12-20.csv.txt](https://github.com/jccastillo0007/eFacturaT/files/14766430/Septimo2023-12-20.csv.txt)

Y no, no toma la forma de pago del archivo. En pantalla despliega EFECTIVO, pero en el XML y PDF regresa al viejo tema aquel de ponerle forma de pago 99. POR DEFINIR

No se si todo esto es claro.
Por una lado, este ticket es para EL HOSTAL. Lo que queremos es tomar las 4 diferentes posibilidades que se incluyen en el archivo respecto a las formas de pago (así como están escritas arriba y en el archivo de ejemplo) y enviarlas así, al PDF y XML. Eso no lo está haciendo. En su lugar envia forma de pago 99


Por otro lado, relacionado pero distinto, está el tema del layout DEL GALPON, donde se solicitó que de acuerdo a como tiene su comportamiento actual, que la forma de pago viene en distinta columna, dependiendo de la forma que se trate, el usuario tenga la posibilidad de que en pantalla, cambie la forma de pago de tarjeta de crédito y débito. (ya se que se colocarán las 4, pero bueno ellos pidieron solo para tarjeta).


me dá la impresión que ya se mezclaron las ideas, o no???

**Comment by jccastillo0007** [comment]
tal vez para ti si, porque seguido pasa lol

**Comment by RigoFlores** [comment]
Solo tomar las formas de pago del archivo con layout del HOSTAL, y ponerlas en el XML.
Incluso, aquí ni siquiera se pide que el usuario las pueda cambiar.

**Comment by RigoFlores** [comment]
Además yo lo comento por el comportamiento revuelto de la aplicación. En específico como se guarda la info en las tablas.
Creo que levantar un ticket del hostal, en paralelo con el galpón, no es tan buena idea.

**Comment by jccastillo0007** [comment]
done.

Para ser consistentes con el hostal, tuve que agregar la forma de pago de vales de despensa...

**Comment by RigoFlores** [comment]
si revisas al inicio de este ticket, se mencionan las 4 formas de pago para el hostal y el galpón, son las mismas.
En ningún momento se mencionó "vales de despensa". Hay que eliminar esa opción.

**Comment by jccastillo0007** [comment]
ok

**Comment by RigoFlores** [comment]
ya hice la prueba, y no está reconociendo la forma de pago de transferencia ni de tarjeta de debito. Les pone tarjeta de crédito

Este es el archivo con el que probé....

[Hostal 4 formas de pago.csv.txt](https://github.com/jccastillo0007/eFacturaT/files/14959394/Hostal.4.formas.de.pago.csv.txt)

**Comment by jccastillo0007** [comment]
fixed.. hay que usar el conector que subí hoy, versión 14.0.3

**Comment by RigoFlores** [comment]
borré las remisiones y ocupé el último archivo que subí aquí...
la primera prueba fue en factura al instante... si encuentra las remisiones, y si les pone su forma de pago en pantalla...
peeero al intentar timbrar, marca esto...

El campo 'txtReservationId' es obligatorio.

y no timbra... 
intentaré hacer lo mismo en factura con registro...

**Comment by RigoFlores** [comment]
Desde factura con registro, todo lo hizo correcto.
Entonces es en FI donde no jala... chiaaaa

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ok, este cambio requiere llevarse a producción en la parte web?

**Comment by jccastillo0007** [comment]
done
