### ISSUE TITLE
Carta Porte 3.0 - versión base para traslados internacionales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2411]
En la versión base de carta porte, cuando se trata de traslados internacionales, es decir:

Cuando en el atributo “CartaPorte:TranspInternac” se registre “Sí”,

(es decir cuando el origen o destino, están fuera de México).

Ahora mismo se agregó un parámetro que corresponde al régimen aduanero, sin embargo está faltando otros 2 para la versión base:

TipoMateria (tomado del catálogo correspondiente c_TipoMateria)
DescripcionMateria (libre captura de hasta 50 caracteres). No siempre se capturará, solo en caso que TipoMateria = 05 ("Otra")

Estos datos se capturarán exactamente en el mismo renglón, donde aparece el régimen aduanero ahora mismo.

<img width="906" alt="trasladoInternacional" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/a3eec04e-f5e7-4b0b-a549-d4e6111f6e7f">

**Comment by jccastillo0007** [comment]
A donde se mandan estos datos en el XML ? no están en el 3.0

**Comment by jccastillo0007** [comment]
Es en mercancia, ya las encontré

**Comment by RigoFlores** [comment]
no está incluyendo correctamente en el XML la clave de tipoMateria

TipoMateria="01:" 

le sobran esos :

**Comment by jccastillo0007** [comment]
done
