### ISSUE TITLE
Carta Porte 3.0 Traslado Internacional - enviar variables al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2413]
Cuando en el atributo “CartaPorte:TranspInternac” se registre “Sí”, es que identificamos el traslado como internacional.

Appendar en la variable datoExtra5 de complementocartaporte40.jrxml **" Régimen Aduanero:  _valor de regimenAduanero_ "**

Enviar al subreporte mercancias.jrxml las nuevas variables (por default vacías, y si incluyen datos, pues incluirlos:
TipoMateria
DescripcionMateria
** DocumentacionAduanera

** esta variable debe contener lo siguiente:
Tipo de documento:  TipoDocumento + Número de Pedimento: NumPedimento + ID Docto Aduanero: IndentDoctoAduanero + RFCImportador: RFCImpo

**Comment by jccastillo0007** [comment]
Estas variables quedaron con este formato (para ser consistentes):

mTipoMateria
mDescripcionMateria

**Comment by jccastillo0007** [comment]
DocumentacionAduanera, no existe, se mandan por separado los valores de: 

mTipoDocumento;
mDocumentoId;
mRFC;
mNumeroPedimento;

**Comment by RigoFlores** [comment]
apenas hoy probé lo de estas variables, y en mercancías no reconoce mTipoMateria... no se si tenga problemas con todas y esta es la primera que reporta el error, o solo con esa.

2024-03-30 08:08:15,934 DEBUG [http-nio-8080-exec-162] (JasperCreatorImpl.java:149) - IT IS A CARTA PORTE, will look first at : /eFacturaT/customers/IIA040805DZ4/setup/complementocartaporte40IIA040805DZ4.jrxml
2024-03-30 08:08:16,256 ERROR [http-nio-8080-exec-162] (JRFillSubreport.java:801) - Fill 1: exception
net.sf.jasperreports.engine.JRException: Error retrieving field value from bean : mTipoMateria
