### ISSUE TITLE
Virtual Homes - acepta duplicados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2416]
La dupla ID + total de cada registro subido en el archivo, debe ser única y el sistema no debe permitir que se dupliquen.
Esto es una regla del AFT, ya se ha platicado antes.
Cuando se deban permitir duplicados, se pedirá explícitamente.

Mientras no se solicite, NO DEBE PERMITIR DUPLICADOS.

Ahora mismo, si permite duplicar info.
Imagínate, ellos suben de miles de registros por mes.

**Comment by jccastillo0007** [comment]
checale en pru

**Comment by RigoFlores** [comment]
listo
