### ISSUE TITLE
Virtual Homes, ignorar cuando el total viene como 0 o vacío

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2417]
Bajo ciertas situaciones especiales, en el archivo, la columna correspondiente al total, viene como 0 o vacío.
No subiremos esos registros al servidor, pero tampoco deben parar el procesamiento del archivo.

cuando eso suceda, simplemente se ignoran esos registros y se continúa con el siguiente registro.

Por ejemplo:

HDWTW9BDL,Mariano 141 - 17 - 2 rec,31.03.2024,01.04.2024,1000,Direct,Caballero Lopez Homero Yosias
HMXYK455JS,AO 298 Roof 1 - 1 rec,01.04.2024,08.04.2024,0,Airbnb,Kelly Laurel Van Woerkom
HMS4MBAZ9D,Mariano 141 - 46 - 1 rec,01.04.2024,14.04.2024,,Airbnb,Samuel
4047186251,Sonora 11 - GH - 3 rec - Bcom,02.04.2024,03.04.2024,0,Booking.com,MONICA RESTREPO

el primer registro es correcto
el segundo y cuarto, contienen 0 en el total
el tercero viene vacío el dato del total

simplemente hay que ignorarlos.

Igualmente, creo que debe ser una regla general del AFT, ya que estos casos se pueden presentar con cualquier otro conector, ya lo hemos visto, y no debe ser motivo de que se detenga el  proceso del archivo.

**Comment by RigoFlores** [comment]
listo...

**Comment by RigoFlores** [comment]
Hay que agregar una validación adicional, cuando el total sea un número negativo, igual hay que ignorarlo.

**Comment by jccastillo0007** [comment]
done. release 14.0.2 de 04/08
