### ISSUE TITLE
Virtual Homes, modificar el correo de contacto en AFT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2418]
Este es el bueno... porfa

ventas@virtualhomes.mx

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
favor de llevarlo a pro...

**Comment by RigoFlores** [comment]
no está en pro, y ya me están reclamando...
cómo hacemos para que eso no pase????
