### ISSUE TITLE
BioSplash - no se puede recuperar el PDF de la remisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2419]
Una vez que terminan de capturar una remisión y le dan guardar, no pueden recuperar el PDF
De igual manera, si le das vista previa no recupera el PDF.

el mensaje es:

_Hubo un problema al obtener los archivos_

no se que cambió, si estaban trabajando muy bien.

**Comment by jccastillo0007** [comment]
puedes validarlo otra vez, ayer ví varias remisiones de este mes, todo parece estar bien

**Comment by RigoFlores** [comment]
si consultas las remisiones, si puede obtenerlas... (en ventas-consultas)

Este ticket, se menciona que no se puede recuperar cuando recién se generó una remisióin en la pantalla de ventas-facturación

lo acabo de hacer en pru, y sigue igual... con el error

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
OJO, cuando generas la remisión desde Ventas-Facturación, y la quieres recuperar, le **das click al PDF y SI LO DESCARGA.**

Desde ventas-consultas, consulté el misma remisión y al darle click en el ícono del PDF **TAMBIÉN LA DESCARGÓ**.

Es decir ya no lo abre el PDF en el navegador, como lo hacía hasta ayer, lo cuál está muy bien. 
No se que se hizo, pero ya lo descarga. Por aquello que decías que tenía que ver con el navegador que lo abriera en lugar de descargarlo.

Favor de poner en producción.
