### ISSUE TITLE
nomina web - si no capturas la antigüedad, le asigna el valor de 0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#242]
la antigüedad es opcional, y cuando no se captura, simplemente no debería ni asignarle un valor, ni reportarlo en el XML:

```
   <nomina:Nomina Antiguedad="0" 
```

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
SIGUE MOSTRANDO EN PANTALLA EL VALOR DE CERO, PERO YA NO LO INCLUYE EN EL XML.
ESTRICTAMENTE HABLANDO, LE ASOCIA UN VALOR EN PANTALLA. NO DEBE MOSTRARSE.

**Comment by jccastillo0007** [comment]
Pssss es un campo númerico... al final siempre le va a asignar 0 cuando lo dejen vacio.

**Comment by RigoFlores** [comment]
ENTONCES CUÁL SERÍA LA DIFERENCIA CON EL NÚMERO 0?
NO, SEGÚN YO NO DEBE APARECER NADA, SI NO HAN CAPTURADO NADA
