### ISSUE TITLE
integrar este archivo actualizado en pro y en pru, para que no se pierda en el siguiente deploy

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2420]
es de carta porte.
yo lo subí a pro y a pru

no se si hay que hacer algo más. Solo que no se vaya a perder en los deploys

[mercancias.jasper.txt](https://github.com/jccastillo0007/eFacturaT/files/14925484/mercancias.jasper.txt)

**Comment by jccastillo0007** [comment]
no, no hay nada que hacer , si lo subiste al folder genérico .. 
ese no se sobre escribe con nuevos releases
