### ISSUE TITLE
Virtual Homes (CAD200803NRA) - Solo debe considerar IVA en las facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2423]
Ejemplo de esta remisión del 30 de abril:

HMQH592QK3, total: 2,158.13

En el XML ya facturado (FI 22) está reportando: SubTotal="1805.97" Moneda="MXN" TipoCambio="1" Total="2094.93"

Es decir, no está reportando el total correcto. Y es que solo le quitaste el impuesto sobre hospedaje del XML, pero incluso del total.

Como debe ser es:  

SubTotal="1860.46" Moneda="MXN" TipoCambio="1" Total="2,158.13"

Y para acabarla de chingar, en el PDF reporta

Subtotal: $1,805.97
IVA: $288.96
Total: $2,158.13

Es decir, el total en el PDF, es incorrecto respecto al XML; pero el XML está mal... jeje

Ellos lo detectaron en el PDF, donde realmente está mal, es en el XML.

Si quieres consulta en la plataforma con este emisor: CAD200803NRA, y el folio es FI22

**Comment by jccastillo0007** [comment]
listo, subí el conector con versión 14.0.5
