### ISSUE TITLE
PFTv2.0 - Generar el reporte de consultas similar a lo que se genera en PFTv10

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2424]
Actualmente el reporte es sumamente limitado.
En la versión 1.0 se incluyen todas estas columnas:

fecha	
status SAT	
status CxC	 
status CxP	
serie	
folio	
documento	
tipo	
rfc emisor	 
razon social	
rfc receptor	
razon social	
subtotal	
descuento	
impuestos trasladados	 
impuestos retenidos	 
total	
usuario	
moneda	
tipo de cambio	 
fecha de pago	 
monto pagado	 
nombre contacto	 
correo contacto	 
telefono contacto	 
forma de pago	 
metodo de pago	 
uso cfdi	 
uuid	 
trackingId

**Comment by RigoFlores** [comment]
Lo que pidió el cliente, que según yo se queda corto... después irá pidiendo más y más, hasta llegar a lo que tenemos.
en particular, los 3 primeros campos, tienen que ver con su flujo. Primero es la remisión y luego la factura correspondiente.

Yo le agregaría el UUID al menos, ese me parece indispensable. También la serie de la remisión y de la factura.

Fecha remisión
Folio remisión
ID remisión
Fecha Factura
Folio Factura
RFC Cliente
Nombre Cliente
Subtotal
IVA
Total

**Comment by jccastillo0007** [comment]
según yo solo falta Nombre Cliente, Subtotal e IVA, y el UUID que quieres agregar.
Ojo, remisión y factura salen en diferente renglón, no en el mismo, no se puede poner en el mismo porque son diferentes CFDi o registros, sin embargo tienen el mismo Id, así los pueden ligar ellos desde el excel

**Comment by RigoFlores** [comment]
pues lo que quieren es ligarlos justamente... no sé si les funcione en distinto renglón, ojalá pudiera hacerse un merge

**Comment by RigoFlores** [comment]
generé un reporte y Faltan:

Fecha
ID remisión (ID tracking)

El RFC y folio, siguen llegando vacíos.

**Comment by jccastillo0007** [comment]
fixed

**Comment by jccastillo0007** [comment]
done
