### ISSUE TITLE
AFT Biosplash - está permitiendo facturar mas de una ocasión, la misma remisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2425]
Se ha indicado ya varias ocasiones, que a menos que se indique otra cosa, NO se deben permitir duplicados en la combinación de la llave de búsqueda... por ejemplo IDTracking + total, o el que corresponda.

Y aquí está permitiendo duplicados, me dicen que se facturon 14 facturas por doble ocasión.

Esta persona es un conocido, hasta pena me dará enviarle la factura de este mes k...
Y además el reporte de facturación...

no estamos quedando tan bien con los clientes k...

**Comment by RigoFlores** [comment]
realmente, cuando le das facturar a un ticket existente, marca error:

Error al salvar el CFD en BD (113)

sin embargo, si genera el PDF y XML, por lo que replica tantas veces quieras el mismo ticket.

**Comment by jccastillo0007** [comment]
cual es la llave de búsqueda de biosplash ?

**Comment by RigoFlores** [comment]
según yo, es el tracking id + total
no es el folio, seguro no es el folio

**Comment by jccastillo0007** [comment]
oye, biosplash no tiene conector... cómo generan sus facturas ?

**Comment by jccastillo0007** [comment]
los únicos que tienen validacion de remisiones no duplicadas son galpon, alteza, virtual homes y hostal

**Comment by RigoFlores** [comment]
Jejeje... pues ellos generan remisiones... y las remisiones una vez que son facturadas, NO deberían poder facturarse nuevamente.

**Comment by jccastillo0007** [comment]
oye, biosplash no tiene conector... cómo generan sus facturas ?

**Comment by RigoFlores** [comment]
pues ya había respondido eso... primero hacen remisiones en PFTv2.0 y luego generan las facturas desde AFT.
Acabo de hacerlo en pru, desde FI y si se puede reproducir el problema.

Creo que tu lo hiciste desde FR. En Fi seguro que no jala.
Ya confirmé, desde FR si aplica bien la validación, pero en FI no.

**Comment by jccastillo0007** [comment]
fixed
