### ISSUE TITLE
Las Barricas - Pasar los metadata del sat a un excel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2427]
Para las barricas. Son 2 o 3 RFC's emisores.
Ellos tienen el conector estándar.

Quieren que tomemos los metadata del SAT (anexo ejemplo del formato), y eso mismo lo pasemos a un excel cvs
Yo creo que lo harían desde el mismo conector , ya que ahí pondrían los archivos cada cierto tiempo de manera automática.

cómo le beisbol?

Apenas lo voy a cotizar.
Pero pareciera que es sustituir todos los ~ por ,  no?
Bueno el formato original del txt, es un zip.

[metadataSAT.txt](https://github.com/jccastillo0007/eFacturaT/files/15256049/metadataSAT.txt)

**Comment by jccastillo0007** [comment]
pero para que ? en donde usaríamos el csv ?

**Comment by RigoFlores** [comment]
No mencioné que nosotros lo usaríamos.
Mencioné que ellos quieren que lo pasemos a un archivo excel.

Input - el archivo de metadata del SAT
Output - esa misma info, pero en un excel csv.

Según yo, si tomo cualquier editor y sustituyo ~ por , ya quedaría listo.
entonces solo eso hay que hacer.
el nombre del archivo probablemente tendría que ser fijo, no lo sé. Voy a preguntar.

**Comment by jccastillo0007** [comment]
osea y porque no lo hacen ellos? 
será recurrente? quieren que sea automático? es tán fácil como dices... aunque siempre puede haber problemas si el archivo txt ya trae "," como en las cantidades o descripciones ..

**Comment by RigoFlores** [comment]
Si, será algo que se ocupa todo el tiempo.
No sé con qué frecuencia lo harán, pero quizá diariamente... se pone el archivo zip tomado del sat y lo que se tomará de regreso será el archivo csv. Esta información la utilizarán ya como insumo para reportes en el AS400.

Quizá parte del procesamiento, sea eliminar las , que existan, previo a hacer la sustitución de ~ por ,
Yo revisé el archivo, y al parecer no puede ser que aparezcan comas... pero no lo puedo asegurar. Quizá en el nombre podría ser, pero pues como lo mencioné, antes de sustituir por comas, hay que eliminar las que existan.

Sería una doble sustitución.
Primero comas por espacios
luego sustituir las ~ por comas

**Comment by RigoFlores** [comment]
en lo que confirman, lo cerraré
