### ISSUE TITLE
Se borran las facturas programadas una vez que se emiten automáticamente. En producción para este cliente SIS130211C95

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2428]
Revisé producción y el mes pasado si se hicieron automáticamente las facturas los dias 15 y 16.
Si revisas las consultas son estas facturas.
Día 15 3857 al 3861
Día 16 : 3862 al 3864

Hay que programarlas para esos días y que no tengan que volver a programarlas.

Según dice el cliente que se hizo una automáticamente el día 03 de mayo, y que después de ello, se borraron.

<img width="684" alt="programadas" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/dcd749c3-ae68-46aa-974d-fc75248b94c1">

**Comment by RigoFlores** [comment]
Hice la programación en PRU con el RFC IVD.
Programé 2 para el día 14 y 2 para el día 15.
Hoy es 14 y si se hicieron las facturas 411 y 412 

Pero si consultas la programación, ya no están programadas.

**Comment by jccastillo0007** [comment]
ya están programadas las facturas... en los próximos días se probará el fix, y estará listo para el sig mes

**Comment by RigoFlores** [comment]
OK,  hay que volver a programar estas facturas del día 15 y 16 ya que si se emitieron de forma automática pero se borraron
Además subir el fix para que ya quede listo en pro...

**Comment by jccastillo0007** [comment]
fixed

**Comment by jccastillo0007** [comment]
ya liberé el fix a prod
