### ISSUE TITLE
PFT - Configuración, no me permite configurar una plantilla personalizada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2429]
En PRU para este rfc IIA, que tiene un comportamiento tipo el galpón, no puedo ponerle su plantilla.
De hecho ahorita está generando facturas con la plantilla base, y no con la personalizada con la que hice las pruebas en su momento.

Aparentemente espera solo archivos jrxml, pero también debe aceptar jasper.
De igual manera no entiendo como se configura. O no lo permite, o no no se cómo se haga..

**Comment by jccastillo0007** [comment]
si ese es el problema, que solo acepta jrxml... deja le digo a Vic

**Comment by RigoFlores** [comment]
Oye, en que momento podremos tomar el control de estos ajustes?
Lo que yo veo, es que esto se irá muy lento.

**Comment by jccastillo0007** [comment]
uffff para eso falta muuuucho tiempo... hay que terminar pftv2 y ver si movemos los aft

Vic es rápido, normalmente el backend es el que se tarda un poco más con Martin

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
ya permite elegir un archivo jasper, pero no se como se actualiza, ya que el botón de guardar no se habilita y no se que le haga falta para que se habilite..

Este punto:

_De igual manera no entiendo como se configura. O no lo permite, o no no se cómo se haga.._

**Comment by jccastillo0007** [comment]
crap no ví eso.

**Comment by jccastillo0007** [comment]
chécale en pru

**Comment by RigoFlores** [comment]
En pruebas con el rfc XI, no jala.
Sigue igual.
