### ISSUE TITLE
URGE-URGE-URGE - NO REPORTA CORRECTAMENTE LAS FECHAS EN NOMINA EMPRESARIAL

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#243]
CUANDO ELIGES GENERAR NOMINA EMPRESARIAL, LOS AÑOS DE LAS FECHAS DE PAGO, INICIAL Y FINAL, LAS REPORTA CON AÑO '0014'.
URGE CORREGIR YAP ASAP...

**Comment by jccastillo0007** [comment]
fixed.
