### ISSUE TITLE
Conector Las barricas, el folio debe tener longitud 7, rellenando con 0's a la izquierda

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2439]
Eso es algo de lo que se hizo al principio.
La longitud debe ser de 7 dígitos.
Si el folio no tiene 7 dígitos, se rellena con 0's a la izquierda. Tanto para el XML como para el PDF.

Así lo muestra esta imagen de cómo estaba antes y cómo está ahora.

![formatoFolioBarricas](https://github.com/jccastillo0007/eFacturaT/assets/2912775/214384e9-c352-4a88-8216-1302b256a687)

**Comment by jccastillo0007** [comment]
favor de probar con la versión 15.0.2 de Junio 17
