### ISSUE TITLE
NO SOPORTA LOS IMPUESTOS LOCALES 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#244]
DESPUÉS QUE LE AGREGASTE EL NUEVO IMPUESTO LOCAL, NO PROBÉ Y SIMPLEMENTE ASUMÍ QUE ESTABA OK (FINALMENTE ENTIENDO QUE SE DA DE ALTA UN REGISTRO EN UNA TABLITA O LISTA O SIMILAR).
AHORA, CUANDO EL CLIENTE ELIGE CUALQUIER IMPUESTO LOCAL, COMO TRASLADADO, LE MARCA EL INTERNAL ERROR, Y OBVIAMENTE NO LE PERMITE FACTURAR. ESTE CASO SE PRESENTA PARA UN HOTEL QUE SIMPLEMENTE NO PUEDE EMIITR SUS FACTURAS.
SERÁ URGENTE?

**Comment by jccastillo0007** [comment]
Pinche error raro.... pero ya quedo listo.
