### ISSUE TITLE
1.- Implementar el complemento de carta porte 3.1, iniciando con el cambio de la versión y las urls

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2440]
No me quedan claros los cambios específicos todavía, quizá no apliquen para nosotros o no lo sé.

Vamos a empezar haciendo lo siguiente:

Cambiar la versión 3.1
Cambiar las urls de los esquemas.

El xsd está aquí 

http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte31.xsd

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Esto era para web, pero bueno.

En el conector, las urls si las cambió, pero no así la versión, que mantuvo la "3.0".

Además regresó aquel viejo error de la indigestión.

**Comment by jccastillo0007** [comment]
me puedes dar un archivo para probar

**Comment by RigoFlores** [comment]
aquí pongo 2 archivos. En teoría los debe timbrar, ya que no incluyen nada referente al régimen aduanero que es el otro cambio que hay que atender.

[cartaPorteTraslado30.txt](https://github.com/user-attachments/files/16169529/cartaPorteTraslado30.txt)
[CartaPorteIngreso30.txt](https://github.com/user-attachments/files/16169530/CartaPorteIngreso30.txt)

**Comment by jccastillo0007** [comment]
listo... ya los timbró.

La versión la toma del archivo, debes cambiarla ahí

Subí el release 15.0.4

**Comment by RigoFlores** [comment]
si, ya timbró. 

Ahora, hacer lo mismo para web.

**Comment by RigoFlores** [comment]
no jaló, mantuvo en el header del cfdi, las urls de 3.0
y a nivel complemento, en el header incluyó una url de 3.1, pero ahí no va ninguna.
