### ISSUE TITLE
PFTv1.0 - Complemento de Pago, no envía las variables de tasa e importe del IVA del documento relacionado al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2441]
Lo que se tiene identificado al momento es que en el XML si envía la información...

TrasladoDR BaseDR="1594.82" ImporteDR="255.17" ImpuestoDR="002" TasaOCuotaDR="0.160000" TipoFactorDR="Tasa"

<img width="651" alt="doctopago" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/4ed1f290-dcf4-4f43-9ae6-176e49b4f85b">

[PAGO334_TIA101020BP4_AIRS750326IH1_04Jun2024_163821.zip.txt](https://github.com/user-attachments/files/15893192/PAGO334_TIA101020BP4_AIRS750326IH1_04Jun2024_163821.zip.txt)

**Comment by jccastillo0007** [comment]
fixed en pru

**Comment by RigoFlores** [comment]
ya lo validé, parece que ya está ok

**Comment by jccastillo0007** [comment]
listo, ya lo liberé a prod
