### ISSUE TITLE
2.- Carta porte 3.1, eliminar regimenAduanero del header y agregar el nodo correspondiente en su lugar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2442]
regimenAduanero desaparece del header.
En su lugar se agrega el nodo **_RegimenesAduaneros_**, donde se pueden capturar desde 1 hasta 10 distintos atributos del catálogo **_RegimenAduanero_**.
Favor de revisar el xsd, ya que ahí seguro te quedará mas claro el arbol de este nodo.

Qué es lo que entiendo que pasó?
Bueno, que un solo régimen aduanero, no es suficiente en algunos casos.
Por ello, se eliminó el atributo y se agregó un nodo con soporte a varios regímenes.

Se puede mantener en pantalla la captura del régimen. Solo que únicamente permite uno. Aquí hay que agregar la función de poder ir agregando varios.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
hay que tratar de implementarlo desde web
de hecho, en el conector, creo que esto no se ocupa

**Comment by RigoFlores** [comment]
carta porte por conector
tenemos a las barricas, y a aldo conti
y ellos no importan o exportan, tons no aplica para ellos lo del régimen aduanero

**Comment by RigoFlores** [comment]
las urls están chuecas.
En el header del CFDI se mantienen las de 3.0, es decir no las cambió a 3.1
En el header del complemento, menciona una de 3.1,  pero ahí no se deben incluir.

Todas van en el header

**Comment by RigoFlores** [comment]
aparentemente el nodo del régimen si lo incluyó correctamente:

cfdi:Complemento>
ns3:CartaPorte xmlns:ns3="http://www.sat.gob.mx/CartaPorte31" EntradaSalidaMerc="Entrada" IdCCP="CCCD4411-6E43-4308-8B06-08B038CD727A" PaisOrigenDestino="CAN" TotalDistRec="1674.0" TranspInternac="Sí" Version="3.0" ViaEntradaSalida="01">
            <ns3:RegimenesAduaneros>
                <ns3:RegimenAduaneroCCP RegimenAduanero="IMD"/>
            </ns3:RegimenesAduaneros>

**Comment by RigoFlores** [comment]
Está marcando el error de las urls, pero mas adelante en el catalina.out marca otro como de índices o catálogos inexistentes. 

Yo no se si esta batería de datos va a timbrar el cfdi correctamente, pero por lo pronto con esta lo estoy intentando.

Receptor la tia
concepto flete (solo con iva)
origen: CANADA, fecha la que sea
destino: TIA QRO, distancia lo que sea, fecha lo que sea
regimen aduanero: definitivo importacion
tipo de materia: 03 
mercancia: IMPORTACION, cantidad la que sea
transporte: camión con remolque
operador: Edgar

**Comment by RigoFlores** [comment]
Para la exportación, el origen será nacional, el destino será fuera de méxico.
La mercancía será EXPORTACION.

con ello jalará.
aquí los ejemplos timbrados.

[Uploading importación.zip.txt…]()
