### ISSUE TITLE
AFT BIOSPLASH (remisiones desde PFTv2.0) - Remisiones con descuento, no se pueden facturar ya que el total es incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2443]
Lo había escrito en el otro ticket, pero mejor lo cierro ya que ese tenía otro problema origen y ya fue corregido.

Pues apenas inicié probando en biosplash. En pru. 
Las básicas si las hizo bien, remisiones y facturas.

Pero remisiones con descuento, ahí lo hizo chueco.
Mira esto:
El total debió ser 34800, pero aparentemente le restó el descuento. Siendo que el descuento se aplica a nivel de base.

Aquí la parte a nivel concepto está bien. Precio unitario, cantidad, descuento, importe, todo eso OK
A nivel de impuestos también está bien.

SubTotal="30000.00" Descuento="10000.00" Moneda="MXN" TipoCambio="1" Total="24800.00" TipoDeComprobante="I" Exportacion="01" MetodoPago="PUE" LugarExpedicion="57424" xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 [http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd">](http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd%22%3E)
<cfdi:Emisor Rfc="XIQB891116QE4" Nombre="BERENICE XIMO QUEZADA" RegimenFiscal="612"/>
<cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="626" UsoCFDI="G03"/>
cfdi:Conceptos
<cfdi:Concepto ClaveProdServ="01010101" NoIdentificacion="test1" Cantidad="20.00" ClaveUnidad="E48" Unidad="SERVICIO" Descripcion="PRODUCTO DE PRUEBA 1" ValorUnitario="2000.000000" Importe="40000.00" Descuento="10000.00" ObjetoImp="02">
cfdi:Impuestos
cfdi:Traslados
<cfdi:Traslado Base="30000.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="4800.00"/>
</cfdi:Traslados>
</cfdi:Impuestos>
</cfdi:Concepto>
</cfdi:Conceptos>
<cfdi:Impuestos TotalImpuestosTrasladados="4800.00">
cfdi:Traslados
<cfdi:Traslado Base="30000.00" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="4800.00"/>
</cfdi:Traslados>
</cfdi:Impuestos>
</cfdi:Comprobante>

**Comment by jccastillo0007** [comment]
fixed
