### ISSUE TITLE
AFT  - Hostal, no calcula bien los importes, bases, impuestos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2444]
[Hostal Transfer.csv.txt](https://github.com/user-attachments/files/15907001/Hostal.Transfer.csv.txt)

Este es el archivo, donde el total, ya viene como parte del archivo. En este caso son 500.

Pero aquí al parecer lo toma como base para impuestos, pero el total lo cambia, etc...
aquí todo parte de que el total son 500
entonces, si dividimos entre (1.195), nos dará la base del IVA
ya que para el hostal, aplica 16% de IVA y 3.5% del impuesto local, ISH

yiAexT4dwM0xMU=" SubTotal="500.00" Moneda="MXN" TipoCambio="1" Total="581.59" TipoDeComprobante="I" Exportacion="01" MetodoPago="PUE" LugarExpedicion="65258" xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd">
    <cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="626" UsoCFDI="G03"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="90101501" NoIdentificacion="110447" Cantidad="1.00" ClaveUnidad="E48" Unidad="Servicio" Descripcion="HOSPEDAJE" ValorUnitario="418.410000" Importe="500.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="500.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="66.95"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="66.95">
        <cfdi:Traslados>
            <cfdi:Traslado Base="500.00" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="66.95"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
    <cfdi:Complemento>
        <implocal:ImpuestosLocales xmlns:implocal="http://www.sat.gob.mx/implocal" TotaldeRetenciones="0.00" TotaldeTraslados="14.64" version="1.0" xsi:schemaLocation="http://www.sat.gob.mx/implocal http://www.sat.gob.mx/sitio_internet/cfd/implocal/implocal.xsd">
            <implocal:TrasladosLocales ImpLocTrasladado="I.S.H." Importe="14.64" TasadeTraslado="3.5"/>
        </implocal:ImpuestosLocales>
    </cfdi:Complemento>
</cfdi:Comprobante>

**Comment by jccastillo0007** [comment]
listo, ya logré timbrar una factura del hostal... puedes checarlo
