### ISSUE TITLE
AFT - El galpón, no calcula bien los importes de los impuestos y el total

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2445]
En el archivo ya viene el total, entonces la base del impuesto del 16% se calcula como total/1.16

pero no se que está haciendo, aparentemente está tomando el total como la base de impuestos.
En este ejemplo, el total del archivo fue 350.00
[galpon.csv.txt](https://github.com/user-attachments/files/15907202/galpon.csv.txt)

SubTotal="350.00" Moneda="MXN" TipoCambio="1" Total="398.28" TipoDeComprobante="I" Exportacion="01" MetodoPago="PUE" LugarExpedicion="65258" xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd">
    <cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="626" UsoCFDI="G03"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="90101501" NoIdentificacion="625" Cantidad="1.00" ClaveUnidad="E48" Unidad="Servicio" Descripcion="CONSUMO DE ALIMENTOS" ValorUnitario="301.724138" Importe="350.00" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="350.000000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="48.28"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="48.28">
        <cfdi:Traslados>
            <cfdi:Traslado Base="350.00" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="48.28"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
</cfdi:Comprobante>

**Comment by RigoFlores** [comment]
en virtual homes, pasa lo mismo.
el total, lo toma como base en lugar del total.
Con este archivo puedes validar.

[virtualhomesProParcial.csv.txt](https://github.com/user-attachments/files/15907305/virtualhomesProParcial.csv.txt)

**Comment by jccastillo0007** [comment]
fixed
