### ISSUE TITLE
Conector 2.0 - no procesa los archivos de alteza

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2446]
Este error es recurrente, ya se ha presentado antes.

Error al procesar el archivo : C:\ConectorV2CeroPRUEBAS\Conector\C33_NPG_20660.spf<CreateCFDiResponse><code>-427</code><description>CFDi inválido</description><linkPDF/><linkXML/><linkAcuse/></CreateCFDiResponse>

No recuerdo qué fue, pero creo que es la extensión del archivo.

[facturaT_IVD920810GU2.cfdi.txt](https://github.com/user-attachments/files/15907372/facturaT_IVD920810GU2.cfdi.txt)
[C33_NPG_19958.spf.txt](https://github.com/user-attachments/files/15907374/C33_NPG_19958.spf.txt)
[C33_NPG_20655.spf.txt](https://github.com/user-attachments/files/15907375/C33_NPG_20655.spf.txt)

**Comment by jccastillo0007** [comment]
fixed. hay que usar el nuevo conector que subí hoy.14.0.1

**Comment by RigoFlores** [comment]
no los está encontrando... 

para buscarlos se ocupa:
TOTAL:
MntBase       11859.10
ID TICKET:
Ppers5        47185424-1

**Comment by jccastillo0007** [comment]
fixed.

hay que usar folio y reservación / ppers5

**Comment by RigoFlores** [comment]
ok, listo.
