### ISSUE TITLE
Conector - PFT2 - AFT, escenarios generales de prueba (para el refactor)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2447]
Este es un documento muy general, que incluye archivos de prueba.
Dime que le voy agregando.
Servirá para probar los timbrados.
No se si para toooodos los detalles de cada layout.

[ESCENARIOS DE PRUEBA.docx.txt](https://github.com/user-attachments/files/15937264/ESCENARIOS.DE.PRUEBA.docx.txt)

**Comment by jccastillo0007** [comment]
me imaginaba algo mas estructurado, aqui voy a ir poniendo lo que ya probé.
Te falta agregar pruebas del facturaTT o ya no lo usan?

Biosplash
En la parte de remisiones de Biosplash, se puede cambiar la cantidad, el precio unitario y aplicar descuentos. Son combinaciones de estos 3 datos, los que generan las distintas pruebas a ejecutar.

Factura de remisiones desde aft y de facturas desde pftv2

**Comment by jccastillo0007** [comment]
Ya esta listo Virtual homes
