### ISSUE TITLE
AFT - FR - Biosplash, al timbrar una factura con descuento, no incluye los siguientes datos en el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2449]
Clave & descripción del método de pago. Igualmente de la forma de pago.

El importe a nivel producto, se calcula como cantidad x precio unitario (aquí no interviene el descuento), pero el importe lo envia con descuento 

No envía los datos de Base, tasa IVA, importe IVA.

**Comment by RigoFlores** [comment]
Generé una factura, a partir de una remisión con 3 productos. Los 2 primeros sin descuentos.
EL tercero con descuento.

En este caso, los datos incorrectos son los mismos arriba mencionados, excepto que a nivel de impuestos la base es incorrecta para el producto 2 y 3. El producto 1, si tiene la base correcta.
Para este caso, a diferencia de la prueba anterior, aquí si generó correctamente la tasa del impuesto y el importe del impuesto.

Tampoco envía el sello digital al PDF.


[FR61_XIQB891116QE4_TIA101020BP4_25Jun2024_113101.pdf.txt](https://github.com/user-attachments/files/15975457/FR61_XIQB891116QE4_TIA101020BP4_25Jun2024_113101.pdf.txt)

**Comment by jccastillo0007** [comment]
DONE - Clave & descripción del método de pago
DONE - Clave & descripción del forma de pago
DONE - Importe del producto
DONE - No incluye el numero de certificado del SAT
DONE - No incluye la fecha de certificación
DONE - No incluye el sello del SAT
DONE - No envía el CP del receptor
DONE - No incluye el logotipo. En su lugar envía el CBB.

a nivel producto:
DONE - Base
DONE - tasa IVA
DONE - importe IVA

a nivel general
DONE - Base
DONE - tasa IVA
DONE - importe IVA

**Comment by RigoFlores** [comment]
Acabo de hacer una prueba y solamente se corrigió el tema de impuestos a nivel producto.

**Sigue con errores:**

A nivel producto El importe es incorrecto (está enviando el total).

A nivel general, 
No envía la descripción del método de pago y forma de pago. Solo envía la clave.
No envía el CP del receptor 
No incluye el logotipo. En su lugar envía el CBB. 
El espacio donde debería aparecer el CBB, está vacío.
No incluye el numero de certificado del SAT
No incluye la fecha de certificación
No incluye el sello del SAT
