### ISSUE TITLE
Addenda Pilgrims no jala en escritorio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#245]
al menos con la última versión del Jenkins.
RFC receptor: PPR910701LEA

**Comment by jccastillo0007** [comment]
Fixed... version 8.1.4 de hoy en jenkins... ya esta caladita en windows xp.

**Comment by RigoFlores** [comment]
AHORA MARCA ERROR 301 DESDE ESCRITORIO

**Comment by jccastillo0007** [comment]
Fixed.
