### ISSUE TITLE
Biosplash - las consultas desde FR y PFTv2.0, muestran la factura duplicada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2450]
En pruebas, rfc XI (biosplash)
Hice la factura FR59 hoy, desde AFT-FR, a partir de una remisión generada en PFTv2.0

Al hacer la consulta ya sea desde AFT-FR (como receptor), o como PFTv2.0 (como emisor), muestra 2 veces la factura.
Mira:

<img width="713" alt="duplicadosBiosplash" src="https://github.com/jccastillo0007/eFacturaT/assets/2912775/1a35f55e-4a3c-4b58-9704-7d9b9d2d5fa0">

**Comment by jccastillo0007** [comment]
Este fue un problema pero ya está arreglado, checa solo las facturas que generaste ayer, yo he generado muchas y algunas se duplicaron, pero ya no debe pasar

**Comment by RigoFlores** [comment]
No hay porqué rechazarlo, si estaba pasando por ello se reportó.
y ya se corrigió
