### ISSUE TITLE
FTT - al capturar una remisión no envía los datos correctamente al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2451]
En pruebas, generé desde IIA una remisión con el FTT.  (folio FTT656)

Luego me fui a consultas desde PFT20 de IIA.
En pantalla el subtotal, aparece como 0.
Y al descargar el PDF, tiene varios datos chuecos:

El importe a nivel producto debe ser cantidad x precio unitario. En su lugar muestra el total capturado desde FTT.
En la parte de impuestos, la base es incorrecta.

En la sección de totales, el subtotal lo manda como 0

[FTT656_IIA040805DZ4.pdf.txt](https://github.com/user-attachments/files/15975267/FTT656_IIA040805DZ4.pdf.txt)

**Comment by jccastillo0007** [comment]
fixed
