### ISSUE TITLE
AFT Biosplash, en facturas donde se incluye el descuento, no manda bien el subtotal al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2454]
para el PDF... 

subtotal = sumatoria de importes
subtotalSD = subtotal - sumatoria de descuentos  (esta variable es para mostrar el subtotal - descuentos, que es la base para el IVA de la factura).

Entonces ahora mismo, está enviando el dato de subtotal, como si fuera subtotalSD.

**Comment by jccastillo0007** [comment]
fixed
