### ISSUE TITLE
Virtual Homes, la descripción en el XML y PDF es incorrecta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2456]
está enviando el NoIdentificacion, en lugar de la descripción.

ClaveProdServ="80131501" **NoIdentificacion="4118018466**" Cantidad="1.00" ClaveUnidad="E48" Unidad="Servicio" **Descripcion="4118018466"**

**Comment by RigoFlores** [comment]
por ejemplo, la remisión HMZJ38C43Q tiene esta descripción, la cual está bien formada.

ARRENDAMIENTO DE INMUEBLE NL 238 - 102 - 2 rec DESDE 10.03.2024 A 11.03.2024 NOMBRE DEL HUESPED Berenice Cruz

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
al momento de agregar el ticket para facturarlo desde AFT, ahora marca internal error.
Borré los tickets  y los volví a cargar, con el mismo resultado.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
OK, en cuanto a que ya timbra, ya lo hace.
En cuanto al error original.
En el PDF ya manda la descripción, pero le agrega al final el ID del ticket.
En el XML, sigue poniendo el idTicket como descripción.

Debe ser únicamente así en ambos casos:


ARRENDAMIENTO DE INMUEBLE Trebol 36 - 1 rec-3 pxs - Bcom DESDE 10.03.2024 A 15.03.2024 NOMBRE DEL HUESPED Marion Kofahl

**Comment by jccastillo0007** [comment]
fixed
