### ISSUE TITLE
PFTv1.0, cuando se elige el IVA exento, debe enviar objeto de impuesto = 01

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2457]
Actualmente solo envía objetoImp = 01, cuando NO existe el nodo impuestos a nivel producto.
OK, eso lo mantenemos.

Pero adicionalmente, cuando  tipo de factor = Exento, también hay que enviar 01 en objetoImp. Ahora mismo, envía el 02, que significa si objeto de impuestos.

En particular, se trata del IVA exento.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Pues no, dice Finkok que no aplica así.
Un cliente pidió que si el IVA es exento, se pongo objImp = 01, lo cual es razonable, pero finkok no lo permite.
Finkok dice que si el nodo de traslado se incluye, aún cuando sea exento, entonces objImp = 02.

son de las inconsistencias no definidas por el SAT.

Tons pues hay que dejarlo como estaba... tsss

**Comment by jccastillo0007** [comment]
chiaaaaa,

**Comment by RigoFlores** [comment]
no mucho que hacer, quizá por ello se quedó así hace años que entró la v4.0

Hay que regresarlo, ya intenté timbrar pero marca el error.

**Comment by jccastillo0007** [comment]
done
