### ISSUE TITLE
Generar el esquema de la addenda Musashi - Definición

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2460]
En la propuesta le llamamos definición a este punto:

a)	Generar la definición de la addenda Musashi
b)	Dicha definición, permitirá homologar la forma en que se incluye la información adicional requerida por Musashi, al XML estándar del SAT.
c)	Esta definición permitirá contar con los elementos informáticos para integrar la addenda en las facturas para quién solicite hacerlo.

Entregables:

1.	Archivo xsd, que define el esquema de la addenda.
2.	Ejemplos XML con addenda, con los 3 distintos escenarios que pueden presentarse.
3.	Descripción de la addenda, basada en el archivo Word con la propuesta de addenda.
4.	Listado de RFC’s receptores de la addenda (esta información será suministrada por Musashi).

Yo te pasaré los 3 distintos escenarios que se deben atender.
Voy a iniciar con las aclaraciones de los ejemplos que enviaron.

**Comment by jccastillo0007** [comment]
[Addendum Sample CFDI.docx](https://github.com/user-attachments/files/16431841/Addendum.Sample.CFDI.docx)

**Comment by RigoFlores** [comment]
Aquí está la definición de la addenda, hasta ahora.
hay que confirmar varios supositorios.

Ahí viene lo que hay que capturar en cada escenario, aunque creo yo que el escenario 1 y 3, son los mismos en cuanto al cálculo de la cantidad y que llevan un solo renglón de detalle en la addenda. Además en el caso 3, se captura un dato adicional en el header y el número de orden de compra es opcional.


[Definición Addenda.zip.txt](https://github.com/user-attachments/files/16474438/Definicion.Addenda.zip.txt)

**Comment by RigoFlores** [comment]
OK, así va la cosa.
No tengo una batería de pruebas consistente para el escenario 3, por ello no se incluye el ejemplo.

Aquí viene la definición de la addenda actualizada
Los datos a capturar que esto no sufrió cambio
Una prueba para escenario 1 y otra prueba para escenario 2. 
Para ambos escenarios está faltando un ejemplo con una factura que contenga varios conceptos.

[Definición Addenda.zip.txt](https://github.com/user-attachments/files/16516126/Definicion.Addenda.zip.txt)

**Comment by RigoFlores** [comment]
Así es como queda la addenda, en cuanto a su descripción.
Faltaría que revises si se requieren cambios en el esquema que ya habías trabajado.
A mi me preocupa el tema que entregaremos dicho esquema, pero las urls que se mencionan en los ejemplos, no existen y según yo ahí podrá haber problema. Tu dices que no, pero pues si se mencionan y no existen, yo creo que si pasa algo.

<img width="450" alt="addendaMushashi" src="https://github.com/user-attachments/assets/11b3f20a-1d0e-402d-ae18-00f0e7b20228">

**Comment by RigoFlores** [comment]
Estoy revisando el xsd que enviaste, creo que le veo 2 temas en cuanto a datos:
a) DeliveryNote es opcional
b) DeliveryNote es alfanumérico

Y de las urls, no opino porque no me queda claro eso de ponerlas así nada mas... si que estén publicadas o compartidas esas ligas.

**Comment by jccastillo0007** [comment]
va de nuevo
[musashi.xsd.txt](https://github.com/user-attachments/files/16665039/musashi.xsd.txt)

**Comment by RigoFlores** [comment]
una omisión de mi parte, el deliverynote es alfanumérico, hoy me enteré de ello.

**Comment by jccastillo0007** [comment]
[musashi.xsd.txt](https://github.com/user-attachments/files/16677363/musashi.xsd.txt)
[musashi sample.xml.txt](https://github.com/user-attachments/files/16677364/musashi.sample.xml.txt)

**Comment by RigoFlores** [comment]
Pues ahora Musashi deberá reunirse con Jodi, para que le expongan los casos que encontramos.
No se en qué vaya a terminar esto, pero por lo pronto yo hablé con Musashi hoy, y les comenté algo similar a lo que platicamos por la mañana. Es decir, que pienso que Jodi, no ha visto o no ha querido ver, los distintos escenarios que si se pueden presentar como casos reales.

Ya te comento como avanza esto.
Mientras tanto, no quiero entregar el xsd, ya que creo que mas que ayudar, en este momento confundiría a los involucrados.

**Comment by RigoFlores** [comment]
así queda por lo pronto.
