### ISSUE TITLE
PFTV2.0 Addendador Musashi

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2461]
Se debe crear la infraestructura en PFTv20 para soportar addendas.

En este caso, será nuestro cliente el receptor de las facturas, es decir el addendador funcionará para los proveedores.
En los XML que se suban, se debe validar que el receptor debe ser Rfc="MAP120305352"   (por confirmar), y que el emisor sea el RFC del proveedor firmado.

Los proveedores de musashi que existan en el catálogo de proveedores, deberán poder acceder con su RFC como usuario y  contraseña el ID capturado en el catálogo.

Cada proveedor podrá subir XML y agregarles la addenda. 
Tendrán acceso únicamente a consulta, descarga  y reportes de sus XML
El proveedor podrá subir algún otro archivo asociado al mismo XML, como puede ser el PDF de la órden de compra o el PDF de la factura.

Nuestro cliente, Musashi podrá consultar los XML subidos (y los PDFs asociados), aplicando distintos filtros como RFC del proveedor, rango de folios, rango de fechas, básicamente.

Para la pantalla de captura, checar la definición de la addenda.
[Definición Addenda.zip.txt](https://github.com/user-attachments/files/16475036/Definicion.Addenda.zip.txt)

**Comment by jccastillo0007** [comment]
Es mejor usar el rfc de proveedor como usuario y password, ya que en el alias pueden poner un string muy largo

**Comment by jccastillo0007** [comment]
Esto no es necesario protegerlo, no podrán hacer nada:
"Tendrán acceso únicamente a consulta, descarga y reportes de sus XML" pues no tienen folios y en una de esas se animan a contratar folios para sus facturas

**Comment by jccastillo0007** [comment]
No tenemos funcionalidad para consultar archivos asociados a una factura, solo pdf y xml
Dónde y cómo debería funcionar esto?

**Comment by RigoFlores** [comment]
> Es mejor usar el rfc de proveedor como usuario y password, ya que en el alias pueden poner un string muy largo

Si quieres hacerlo simple, pues que así sea. No conozco ninguna aplicación que solicite usuario y contraseña, y que no pueda ser modificado. De hecho, deberíamos darle al proveedor el derecho de hacerlo. Lo pido en el catálogo de proveedores, para que lo haga el administrador (emisor), pero realmente debería ser un tipo registro como el AFT lo tiene.



> Esto no es necesario protegerlo, no podrán hacer nada: "Tendrán acceso únicamente a consulta, descarga y reportes de sus XML" pues no tienen folios y en una de esas se animan a contratar folios para sus facturas

Creo que no está claro. Ellos entrarán con su usuario y contraseña a una cuenta donde NO SON LOS EMISORES. Entonces imagínate que tus proveedores tienen acceso a consultar tus facturas!!!!
Siempre queremos hacerlo simple, en lugar de funcional, seguro y simple. Ahora mismo tenemos un perfil para el FTT. Este tendría que ser un perfil de proveedor.




> No tenemos funcionalidad para consultar archivos asociados a una factura, solo pdf y xml Dónde y cómo debería funcionar esto?

Por lo pronto, solo en consultas. Esto tiene un objetivo de ir sembrando la semilla para que quiten de enmedio el portal de proveedores y nosotros integrarnos directo a SAP.

**Comment by jccastillo0007** [comment]
De acuerdo con el cambio de password, puedes levantar un ticket para implementar eso
Realmente todos deben poder cambiar su password

**Comment by jccastillo0007** [comment]
Esto no es correcto. 
"Creo que no está claro. Ellos entrarán con su usuario y contraseña a una cuenta donde NO SON LOS EMISORES. Entonces imagínate que tus proveedores tienen acceso a consultar tus facturas!!!!" 

El proveedor entrará con su rfc, por lo tanto, solo podrá ver sus propias facturas (que no va a tener ninguna) y las facturas a las que le agregó la addenda, entonces es seguro.

**Comment by jccastillo0007** [comment]
Respecto a los archivos extras que podrán subir, se puede pedir que sea un zip ? o deben ser cada uno por separado?
El zip ayuda a que en consultas puedan descargar el zip, si son archivos por separado, cómo van a elegir que archivo descargar, se complica

**Comment by RigoFlores** [comment]
> Esto no es correcto. "Creo que no está claro. Ellos entrarán con su usuario y contraseña a una cuenta donde NO SON LOS EMISORES. Entonces imagínate que tus proveedores tienen acceso a consultar tus facturas!!!!"
> 
> El proveedor entrará con su rfc, por lo tanto, solo podrá ver sus propias facturas (que no va a tener ninguna) y las facturas a las que le agregó la addenda, entonces es seguro.

Si entendí bien, ayer me comentaste que cada proveedor, realmente tendrá una cuenta como emisor (desde la perspectiva de nosotros). 
¿Cuál será la relación entonces con el catálogo de proveedores que tendrá disponible Musashi?

**Comment by RigoFlores** [comment]
> Respecto a los archivos extras que podrán subir, se puede pedir que sea un zip ? o deben ser cada uno por separado? El zip ayuda a que en consultas puedan descargar el zip, si son archivos por separado, cómo van a elegir que archivo descargar, se complica

Si, pues empecemos con que suban el XML para captura de la addenda, y que suban un zip con los otros documentos. 

Ahora mismo tenemos la opción en consultas de descargar un XML y un PDF, y cada archivo se puede descargar por separado.
Entonces sería mucho problema, implementar eso mismo pero para unos 3-4 documentos adicionales?

**Comment by jccastillo0007** [comment]
"Entonces sería mucho problema, implementar eso mismo pero para unos 3-4 documentos adicionales?" Si

**Comment by RigoFlores** [comment]
No me permite guardar la addenda. Ese error manda en pantalla.
No se si sea porque no le capturé delivery note que es un dato opcional.

El label no debe aparecer en pantalla ni el tipo de documento, ya que si los cambia el usuario podría dar problemas. Son valores fijos que no deben poder modificarse. Si no es posible quitarlos, ponerlos en modo de solo lectura, pero no, no tiene caso que se muestren.

<img width="663" alt="addenda" src="https://github.com/user-attachments/assets/6e0cd876-8d64-4ee6-9d47-bd30c4631f3c">

**Comment by jccastillo0007** [comment]
Debes usar el usuario IIA y además el usuario IIA debe ser el receptor del cfdi

**Comment by RigoFlores** [comment]
Bueno, que el receptor sea IIA está OK.
Pero que el usuario sea IIA, eso es incorrecto.
Los usuarios serán cualquier RFC dado de alta en el catálogo de proveedores. Justo como lo mencioné al inicio de todo esto.

Probaré así como dices, pero no es la configuración que debe quedar.

Musashi no estará capturando las addendas de sus decenas o cientos de proveedores.

**Comment by jccastillo0007** [comment]
Puse el usuario que sea IIA, para que puedas ver después el registro en consultas... no es mandatorio pero solo así podrías verlo.

**Comment by RigoFlores** [comment]
Pues entré con el usuario IIA.
Al XML le cambié los datos del receptor, le puse los de IIA.
Capturé la addenda
Marcó proceso exitoso, pero no puedo ver el resultado. 

No se si porque el emisor no es IIA... que de hecho así será, el emisor no será Musashi.

Cómo lo consulto????

**Comment by RigoFlores** [comment]
no, ya le cambié los datos tanto del emisor y receptor, le coloqué los mismos, es decir IIA, y no puedo consultar el XML que resultó

**Comment by RigoFlores** [comment]
Ya vi que se puede capturar la addenda y descargar en la pantalla donde se capturó.
Qué falta?? Según yo:

1) Validar que la addenda solo trabajará para el RFC de Musashi como receptor del XML.
2) Definir la forma en que los proveedores de musashi accederán a la plataforma. Se solicitó que únicamente accedieran los provedores que existieran en el catálogo de proveedores.
3) Falta que los proveedores puedan consultar y descargar los XML, tanto los originales, como con addenda.
4) Falta que el usuario de Musashi pueda consultar los XML's que han subido los proveedores.

creo que esos son los puntos que faltan.

**Comment by jccastillo0007** [comment]
Comentarios.
1. Lo hago hoy
2. Simplemente se crean sus usuarios
3. Solo podrán consultar el nuevo xml con la addenda y las evidencias
4. Este no está contemplado, habrá que ver como consultar facturas recibidas, y no emitidas.... cómo funciona en la PFTv1?

**Comment by RigoFlores** [comment]
2 . tenemos que crear cientos de usuarios, que son sus proveedores. No me late tener tantas cuentas que NO son emisores ni clientes nuestros. Eso es un parche, y así no está definida esa función, pero bueno, si tu dices, pues los creamos por cueri.
3. no entiendo, no podrán consultar sus XML anteriores??? eso si es necesario
4. en PFTv10 no existe este escenario. Esto es nuevo y así se solicitó desde el inicio. El punto es que como no se quieren hacer cuantas asociadas a nuestro cliente... es decir, cuentas así como el IIAFTT que es un perfil específico de la cuenta IIA en pruebas, pues no sé como pudiéramos hacerle... yo se que esto es nuevo, pero justo esto nuevo es lo que nos pidieron

**Comment by jccastillo0007** [comment]
2. son simples cuentas, que solo usarán el adendador, no veo cual es el problema
3. no, la addenda ya trae el xml anterior chiaaaa
4. lo trabajamos la sig semana

**Comment by RigoFlores** [comment]
2. Pues justo eso, las "simples cuentas" aparecerán como si fueran clientes nuestros y no lo son. El catálogo de proveedores no se ocupará para ello. Entonces, estamos ocupando las funciones para cosas distintas a las que se crearon. Realmente algo muy raro.
3. ok, pero podrán consultar los XML anteriores con addenda?

**Comment by RigoFlores** [comment]
lo mas extraño, es que la petición desde el inicio fue que del catálogo de proveedores, se tomara la info para que ellos puedieran acceder o no al addendador.

**Comment by jccastillo0007** [comment]
1. Validar que la addenda solo trabajará para el RFC de Musashi como receptor del XML: DONE

**Comment by jccastillo0007** [comment]
Respecto a este punto:

"lo mas extraño, es que la petición desde el inicio fue que del catálogo de proveedores, se tomara la info para que ellos puedieran acceder o no al addendador."

Asi sucederá, pero ahorita ya lo hiciste tu, cuando falte algún proveedor me dices y lo doy de alta
