### ISSUE TITLE
PFTv2.0- dar la opción al usuario de poder cambiar la contraseña

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2462]
Lo estoy levantando porque así lo pediste.
Aún no me queda muy claro cómo quedará el tema de los proveedores.

Así que una vez que sepa cómo quedará, le daré seguimiento a este tema.

Ahora mismo, como yo lo visualizaba, es que desde la cuenta de Musashi existe un catálogo de proveedores. 
Entonces cada registro que ahí exista, correspondería a un acceso a la cuenta de musashi con perfil de proveedor. 
Eso es lo que entiendo debería ser así.

**Comment by jccastillo0007** [comment]
Le puedes cambiar el titulo a este ticket, debe ser general para PFTv2

**Comment by jccastillo0007** [comment]
listo

Al intentar cambiar el password, va enviar por correo una liga y un código, ahí es donde se cambiará el password

**Comment by RigoFlores** [comment]
lo intenté hacer para el usuario IVD, pero no me llegó ningún correo.
desde la opción de recuperar contraseña, ya que no encontré algún otro lado donde hacerlo.

Entonces desde donde o cómo es el procedimiento?

**Comment by jccastillo0007** [comment]
depende del email dado de alta en la tabla users, ahorita lo modifico

**Comment by RigoFlores** [comment]
ok, me avisas para hacer la prueba completa, no puedo estar probando parte en un lugar y parte en otro.
Son pruebas end to end.

**Comment by jccastillo0007** [comment]
listo, ya puse tu email y está bien la URL

**Comment by RigoFlores** [comment]
jaló para ivd.
lo intenté para LOCL pero no me llegó ningún correo.

no se donde puedo consultar el correo que está configurado.
