### ISSUE TITLE
AFT - El hostal, no manda los datos del impuesto local al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2463]
En el XML si desglosa bien los impuestos de IVA y del impuesto local ISH

Al PDF no está enviando los datos correspondientes a impuesto local F{montoImpLocal1}

**Comment by jccastillo0007** [comment]
Es PFTv2 o AFT del hostal? chiaaa

**Comment by jccastillo0007** [comment]
si logras generar una factura del hostal con impuestos de hospedaje? yo no puedo, no me lo está reconociendo

**Comment by RigoFlores** [comment]
Generé una desde FR y envía la info del impuesto de hospedaje al PDF.

Pero desde FI, marca también internal error y no puedo validar.

**Comment by jccastillo0007** [comment]
que remisión estás usando?

**Comment by RigoFlores** [comment]
pues según yo cualquiera, pero bueno, lo acabo de hacer desde FI con esta remisión: folio=7252 total=410.00

esta la di de alta hoy, con el layout del hostal y el resultado es el mismo. folio 110545 TOTAL 600

te mandé un video con la evidencia, ya que aparentemente no crees que las pruebas fallan.

**Comment by jccastillo0007** [comment]
acabo de facturar la remisión 110545 de 600 chiaaaa
el pdf si tiene la base correcta
![Screenshot 2024-08-15 at 11 53 30 a m](https://github.com/user-attachments/assets/277d714b-d72d-4f57-948b-468b3f521621)

**Comment by RigoFlores** [comment]
ya estoy confundido, si lo hiciste desde FI??
te mandé el video y desde FI no puedo facturar, ni hostal, ni galpón.

**Comment by jccastillo0007** [comment]
si, checa las facturas de hoy Agosto 19, las hice desde FI
