### ISSUE TITLE
AFT cuando se capturan los datos del ticket del galpón o del hostal, cambia el uso del CFDI 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2464]
tanto en FI como en FR se capturan algunos datos como el uso de cfdi.
Cuando se capturan los datos del ticket, y se agrega a la factura, se cambia el uso de cfdi a gastos en general.

Debe mantener el uso que se capturó previo a la captura de los datos dell ticket

**Comment by jccastillo0007** [comment]
fixed en glapon

**Comment by RigoFlores** [comment]
pues aparentemente lo hizo bien, pero ahora marca internal error, ya que la forma de pago que viene en el archivo, no la pone en la pantalla de captura.

**Comment by jccastillo0007** [comment]
fixed, ya lo puedes probar
