### ISSUE TITLE
AFT Galpón y Hostal, a nivel concepto no incluye el NoIdentificacion correcto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2465]
Tanto en el hostal como en el galpón, solo se incluye un concepto.
El acuerdo ha sido que el NoIdentificacion sea el ID del ticket.

Actualmente lo pone como NoIdentificacion="False"

**Comment by jccastillo0007** [comment]
no lo pude reproducir, a mi si me puso el folio

**Comment by RigoFlores** [comment]
Ahorita ya marca internal error, ya que no toma la forma de pago del archivo.

**Comment by jccastillo0007** [comment]
pásame el archivo que estás usando

**Comment by RigoFlores** [comment]
pues realmente no tienen mucha complejidad, pero bueno, aquí está..  (marca internal error al intentar timbrar).

[galpon TC efe vales transfer.csv.txt](https://github.com/user-attachments/files/16550687/galpon.TC.efe.vales.transfer.csv.txt)

**Comment by jccastillo0007** [comment]
si está funcionando bien

**Comment by RigoFlores** [comment]
negativo, sigue marcando internal error... y no me permite validarlo
Eso es desde FI.

**Comment by jccastillo0007** [comment]
que remisión estás usando? si la subiste con la versión correcta del conector?

**Comment by RigoFlores** [comment]
la subí con la última versión, así como toooodas las pruebas que hago.
esa versión es del 16 de julio.

ya te mandé un video evidencia, ya que aparentemente no estás confiando en estos reportes que levanto.

**Comment by jccastillo0007** [comment]
ya con FI, que parte de esta factura es incorrecta

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="4.0" Serie="FI" Folio="107" Fecha="2024-08-15T14:20:33" Sello="pJqP/I6WbJmR+Gso6vHMWJhFa/s5oVlgPpT/y788P6DNfXprqpQ+3XNSeF0TtB2sHOfuSRzFHjsfHS6/7O1a8aqIA5F7dB19ogwfmTz/9j2aF12rYjQZ0hxW/l/r9kExTuE8lBimzgVdW8/tGY/aRWalbhojkmvIxV+9KrWeJASRvmQZxXlG3JU1GSb8i/rvV0nZQYQ0WzzJI9S2gn5w+zHUW5D+2fjUBKn8AEstuwyod7svg5h/Y1NWV+pEWD9EMljb4T2JkQbXrptPOARgj1Gdr/3U6JYQPT3sGrS7sNgOlB+8NiPoWSHyxGoDvKHPSlGDo6Ql/jV6KwdMlBMhrA==" FormaPago="03" NoCertificado="30001000000500003433" Certificado="MIIF1zCCA7+gAwIBAgIUMzAwMDEwMDAwMDA1MDAwMDM0MzMwDQYJKoZIhvcNAQELBQAwggErMQ8wDQYDVQQDDAZBQyBVQVQxLjAsBgNVBAoMJVNFUlZJQ0lPIERFIEFETUlOSVNUUkFDSU9OIFRSSUJVVEFSSUExGjAYBgNVBAsMEVNBVC1JRVMgQXV0aG9yaXR5MSgwJgYJKoZIhvcNAQkBFhlvc2Nhci5tYXJ0aW5lekBzYXQuZ29iLm14MR0wGwYDVQQJDBQzcmEgY2VycmFkYSBkZSBjYWxpejEOMAwGA1UEEQwFMDYzNzAxCzAJBgNVBAYTAk1YMRkwFwYDVQQIDBBDSVVEQUQgREUgTUVYSUNPMREwDwYDVQQHDAhDT1lPQUNBTjERMA8GA1UELRMIMi41LjQuNDUxJTAjBgkqhkiG9w0BCQITFnJlc3BvbnNhYmxlOiBBQ0RNQS1TQVQwHhcNMjMwNTE4MTI0NjQ5WhcNMjcwNTE4MTI0NjQ5WjCB/jE0MDIGA1UEAxMrSU5ESVNUUklBIElMVU1JTkFET1JBIERFIEFMTUFDRU5FUyBTQSBERSBDVjE0MDIGA1UEKRMrSU5ESVNUUklBIElMVU1JTkFET1JBIERFIEFMTUFDRU5FUyBTQSBERSBDVjE0MDIGA1UEChMrSU5ESVNUUklBIElMVU1JTkFET1JBIERFIEFMTUFDRU5FUyBTQSBERSBDVjElMCMGA1UELRMcSUlBMDQwODA1RFo0IC8gVkFEQTgwMDkyN0RKMzEeMBwGA1UEBRMVIC8gVkFEQTgwMDkyN0hTUlNSTDA1MRMwEQYDVQQLEwpTdWN1cnNhbCAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz+hpn6PiooF9kZWedcyvkPexlLrncvsq2z51HEHG+JrugoGXikqvedT4NwoZLq4zCjJKZt+L9Rf6e1qD/zLlo7xHfjtNgkr90BZM1VSbpYOFmXHxqe4tjCfuQKYJOw/lGIoKjNUedRL6rkpwCkhPpO/zgLUA2Ro/j8H70k1NeAAs/u4RSvlhwYPCVh45z+wTg/5zcCNzS+OlUDfba7KEvogdxo0Xm98UrtB4yh7tzW48vv3QPvjZIpYiAZ3lzbbLFg4CDRGJav2tsWwwZBAtgrtreEfpR7H11uZ5i4cL7fhqnd6T5RPkwERaEh1s8p86ALZOXiD+A4lpG8U8o1PAXQIDAQABox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDANBgkqhkiG9w0BAQsFAAOCAgEAoLh8DXWEAatoJJlZln9SFpMB6+2+u5+VABy+AltaAOoQ0H3U6RWI31UFfjGF7QJFRW9eiQCslzLPis6EuD5ltVoOIGxNntfYFVYh9rEs1dVRwTjBOThltPH5M+9a0BQFBNLyEMus834TGNUMZdE5ekiMC2paR7gItqitMIqTan1ByPbpulP9LK/G/Wj4OuP4gyYyGCWnGzKdcdOrk7AeF4RdY7gMqcpuJ6nU77UJ5YVDLy4z6wPRqCnttl0tkemAOT9ayyBHGgVZ9sBpssP702dQYjOtHBG24Zg2D3MnYW5F/rMDT++42QRj/y+k3LprF/WJn0PeuZZ+ZVTlmTfPgDpnInoFmjDgHMRaesFLjbbxDYprsbxuJ4j9uCkEjscP3T/mnswImfsFd6gx9kDLhaf5oosPsy7RbBYZWHsfnqTmnfOd7mG1bQ1nOsm9A0RvImWiiY9y4YXOV86tt7ORwrTR6Qn5YgpyiyJo/evSqyo43b1119QI7vBmRpdVFP1k+LHejCXjoA0eaipO981iijfnm6vzS0maaY1vTnfN84vRPPW7IE3LRMWOVs7/YekMgcvyDECusTpPj0u07GmHk7DlpLmehvYjotjiPkj30nZUnMNtp9yi4vx/qJiq04rpWVwo/Nc9xTM0Ua5maXM80oeFgqJO7yiAexT4dwM0xMU=" SubTotal="560.34" Moneda="MXN" TipoCambio="1" Total="650.00" TipoDeComprobante="I" Exportacion="01" MetodoPago="PUE" LugarExpedicion="76090" xsi:schemaLocation="http://www.sat.gob.mx/cfd/4 http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd">
    <cfdi:Emisor Rfc="IIA040805DZ4" Nombre="INDISTRIA ILUMINADORA DE ALMACENES" RegimenFiscal="601"/>
    <cfdi:Receptor Rfc="TIA101020BP4" Nombre="TECNOLOGIAS DE INFORMACION APLICADA" DomicilioFiscalReceptor="76090" RegimenFiscalReceptor="601" UsoCFDI="G03"/>
    <cfdi:Conceptos>
        <cfdi:Concepto ClaveProdServ="90101501" NoIdentificacion="7250" Cantidad="1.00" ClaveUnidad="E48" Unidad="Servicio" Descripcion="CONSUMO DE ALIMENTOS" ValorUnitario="560.340000" Importe="560.34" ObjetoImp="02">
            <cfdi:Impuestos>
                <cfdi:Traslados>
                    <cfdi:Traslado Base="560.340000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="89.66"/>
                </cfdi:Traslados>
            </cfdi:Impuestos>
        </cfdi:Concepto>
    </cfdi:Conceptos>
    <cfdi:Impuestos TotalImpuestosTrasladados="89.66">
        <cfdi:Traslados>
            <cfdi:Traslado Base="560.34" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="89.66"/>
        </cfdi:Traslados>
    </cfdi:Impuestos>
    <cfdi:Complemento>
        <tfd:TimbreFiscalDigital xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" FechaTimbrado="2024-08-15T14:20:34" NoCertificadoSAT="30001000000500003456" RfcProvCertif="CVD110412TF6" SelloCFD="pJqP/I6WbJmR+Gso6vHMWJhFa/s5oVlgPpT/y788P6DNfXprqpQ+3XNSeF0TtB2sHOfuSRzFHjsfHS6/7O1a8aqIA5F7dB19ogwfmTz/9j2aF12rYjQZ0hxW/l/r9kExTuE8lBimzgVdW8/tGY/aRWalbhojkmvIxV+9KrWeJASRvmQZxXlG3JU1GSb8i/rvV0nZQYQ0WzzJI9S2gn5w+zHUW5D+2fjUBKn8AEstuwyod7svg5h/Y1NWV+pEWD9EMljb4T2JkQbXrptPOARgj1Gdr/3U6JYQPT3sGrS7sNgOlB+8NiPoWSHyxGoDvKHPSlGDo6Ql/jV6KwdMlBMhrA==" SelloSAT="ZP6fLHuSBHCDS0AIg2vUkCKyjR1pZxL1aNLoVtfChBtI/daZVi0qDOFrTz+E/4b9MQVHq5gD9eGaro9MUn+vFrmDriradOIFWfaN4zHj7vwxlr1m6Ey+kY8/PLASIl89NBfo1IwMzprEML3I4ZuyZDva/Rau7UBhgZl/swhMw/rVda+xGxSmPLAzFNwpVfn+ZzMWl+jDT9qT00QgBvEiOq6qUOSpI2SAKP44WQNMOSzSWDETX8Av0Nh4tIz3/TU7MK1EZVn0NIaKlhkEGtTEJMs8jKB5sJkzmhf553xrKSLwk6/T71gXDw2kLSKmq5Po5zECzwmLt+re+DbjiYCxQw==" UUID="F5D273E2-471F-5EA7-85C6-971234DF98D8" Version="1.1" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/cfd/TimbreFiscalDigital/TimbreFiscalDigitalv11.xsd"/>
    </cfdi:Complemento>

**Comment by RigoFlores** [comment]
no lo sé, tengo que revisar, ya que el problema es que desde FI marcaba internal error, entonces entiendo que ya se corrigió eso del internal error.

**Comment by RigoFlores** [comment]
Se mantiene este problema para el Hostal
Tanto desde FI como desde FR.
Envía el ID del producto como  "False"

Para el galpón tanto en FI como en FR, lo hace bien.

**Comment by jccastillo0007** [comment]
Según la implementación, el campo 1 del archivo txt se toma como el id del producto, con el archivo que estoy probando tiene False, y por eso le pone ese dato.
Desde FTT, le pone el producto Id como NoIdentificacion="PROD_FTT" 

Esta es la línea del archivo que está procesando

False,724.52,Transferencia,OSCAR YAIR VEGA ALVARADO,In House,2023-12-02,2023-12-03,30139,septimohostal@gmail.com,2023-12-02 10:38:00-06:00,17661751098,

**Comment by RigoFlores** [comment]
Eso es según la implementación con el refactor, pero mira los XML de producción. Estos son ambos desde FTT para el hostal, y ahí si coloca bien el idproducto (es decir, pone el ID ticket).

[hostalpro2.xml.txt](https://github.com/user-attachments/files/16683103/hostalpro2.xml.txt)
[hostalPro.xml.txt](https://github.com/user-attachments/files/16683104/hostalPro.xml.txt)


Justo ese es el error reportado, que no está poniendo correctamente el id.

Por otro lado, para el hostal dentro de su archivo,  el ID ticket no está en el campo 1, sino en el campo 8.
Hostal tiene un layout y galpón otro.

**Comment by RigoFlores** [comment]
mira, aquí un XML del galpón, que se generó a partir del FTT. El ID producto, es el ID del ticket.

[galponPro.xml.txt](https://github.com/user-attachments/files/16683122/galponPro.xml.txt)

**Comment by jccastillo0007** [comment]
ok, temo decirte que yo creo no están usando la aplicación... no creo haber movido nada de eso.

**Comment by RigoFlores** [comment]
Es de esta semana esta factura, creo que son de hoy

**Comment by RigoFlores** [comment]
Aquí tienes 3 facturas de ayer 20 de agosto, 2 del galpón (conector y FTT) y una del hostal (FTT), con la nomenclatura correcta en el id.

Lo que si, es que aparentemente en el hostal, ya todo lo manejan desde FTT

[galponHostal.zip.txt](https://github.com/user-attachments/files/16694566/galponHostal.zip.txt)

**Comment by jccastillo0007** [comment]
Sabes si alguien usaba el producto id como PROD_FTT ?
 porque ya se lo quite

**Comment by RigoFlores** [comment]
jajajaja, primero mato, y luego veriguo...

Esa ID del producto, se planteó precisamente para que cuando se genera la remisión desde FTT, busque por ese producto.
En el caso del galpon y hostal, solo se puede tomar para uno de ellos. Seguro que era para el galpón, es decir "CONSUMO DE ALIMENTOS".

El acuerdo seguramente fue que cuando se tratara de una remisión FTT del hostal, en jardcoud, se colocara "HOSPEDAJE" en lugar del producto PROD_FTT

**Comment by RigoFlores** [comment]
Pero OJO, ese ID producto, cuando se trate de FTT será el que tome del catálogo para colocar en la factura de un único producto.

Solo que para el Hostal se hizo una excepción, porque comparte el RFC con el Galpón.

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
Para probar desde conector, hay que usar el nuevo conector que subí hoy 08/23

**Comment by RigoFlores** [comment]
Creo que quedaron todos los escenarios, resulta que el galpón tiene 8 distintos... FI y FR por un lado... y galpón/hostal, por conector o por FTT.  Son 8 distintos escenarios en total, no maaaa!!!
Y el ID producto quedó bien en casi todos, es decir el número de ticket.

En los únicos escenarios donde no pone el número de ticket en el id producto, es galpón FTT (tanto FI, como FR).
Ahí coloca PROD_FTT, y debe ser el número de ticket.
Recordar que PROD_FTT, sirve para ubicar en el catálogo cuál producto incluir cuando llega desde FTT, pero es mejor que coloque el número de ticket, justo para conocer cuál ticket se facturó.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
listo, solo validé esos escenarios que estaban faltando.
