### ISSUE TITLE
FTT El hostal - no reporta bien la base del IVA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2466]
el hostal soporta el FTT.
La única condición es que el número de ticket inicie con H, por ejemplo en pru el ticket es H12121212 y el total son 3500.

La base la reporta como 3500 y debe ser 2928.87

Creo que el resto de cálculos están bien, solo este lo está reportando chueco.

**Comment by jccastillo0007** [comment]
no entiendo este ticket, el FTT solo genera iva no ish, no sé como probarlo

**Comment by RigoFlores** [comment]
FTT ahora mismo tiene 2 sabores.

Cuando el número de ticket inicia con H, significa que se trata de un ticket del Hostal.
El hostal desglosa IVA (16%) y el ISH (3.35%).
Por ejemplo si el total son $500.00. Entonces:
Subtotal = total / 1.195 = 500 / 1.195 = 418.41
IVA = subtotal * 0.16 = 418.41 *.16 = 66.95
ISH = total - subtotal - IVA = 500 - 418.41 - 66.95 = 14,64
 

Cuando el número de ticket no inicia con H, entonces se trata del galpón y por lo tanto solo desglosa el IVA trasladado.
Subtotal = Total / 1,16
IVA = total - subtotal

**Comment by jccastillo0007** [comment]
En donde viste que lo reporta mal? generé una y salió bien en el xml y pdf

debes tomar un curso de como levantar defectos... siempre están incompletos, y de por si me tardo en revisarlos y cuando lo hago no encuentro el problema

XML:
 <cfdi:Traslado Base="2928.870000" Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="468.62"/>

PDF:
![Screenshot 2024-08-15 at 11 53 30 a m](https://github.com/user-attachments/assets/35d5e520-9dea-49a6-9ab2-ee7bea701026)

**Comment by RigoFlores** [comment]
ya lo probé y ya funciona bien.
Este ticket lo levanté la semana pasada, y hasta hoy se responde.

Quizá lo que se hizo corrigiendo los otros tickets que no enviaban bien los impuestos, pudo haber resuelto el problema aquí reportado.
