### ISSUE TITLE
AFT - pasar a mayúsculas el nombre en FI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2467]
cuando capturen el nombre en minúsculas desde FI, pasarlo a mayúsculas.
Aplica solo para letras.

Es que el nombre, he encontrado que puede llevar & o " como parte del nombre. No se que pasa si a esos caracteres les aplican el uppercase.

Si esto no es posible, agregar una leyenda visible que indique que el nombre debe capturarse en mayúsculas.

**Comment by jccastillo0007** [comment]
Puedes ver Galpon ? así está bien?

**Comment by RigoFlores** [comment]
jeje, pues si, está medio chacarrón, pero bueno... lo ideal es que lo pasara a mayúsculas...
Pues ahí está para el galpón.
