### ISSUE TITLE
AFT Alteza, desde FI no envía el importe del impuesto local al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2468]
no está enviando el importe del impuesto local al PDF cuando se incluye en el archivo.
En el XML si lo incluye.

[C33_NPG_20674_CONhospedaje.spf.txt](https://github.com/user-attachments/files/16534812/C33_NPG_20674_CONhospedaje.spf.txt)

**Comment by RigoFlores** [comment]
[C33_NPG_19958.spf.txt](https://github.com/user-attachments/files/16536812/C33_NPG_19958.spf.txt)


aquí un archivo de ejemplo

**Comment by jccastillo0007** [comment]
es en estos campos verdad : nombreImpLocal1, tasaImpLocal1, montoImpLocal1

**Comment by jccastillo0007** [comment]
fixed
