### ISSUE TITLE
MARCA ERROR EN ADDENDADOR PILGRIMS 115 ERROR AL GENERAR CFD

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#247]
PROBÉ CON LA CUENTA DE LA TIA, Y NO JALÓ...

**Comment by RigoFlores** [comment]
TAMPOCO CON GUTF701008N52

**Comment by jccastillo0007** [comment]
Probaste en Pru o Pro ? tal vez me ganaste en validarlo, antes de que lo subiera... acabo de generar dos facturas con la cuenta de la TIA en Pru de dos RFC de Pilgrims..

PPR910701LEA
GPE920525A1A

Ahorita en la noche lo subo a Pro, tambien ya esta la version standalone..... 
http://146.185.159.201:8090/job/FacturaT/

**Comment by RigoFlores** [comment]
me sigue marcando error en producción. Probé con la cuenta de la tia, y marca el error.
Te mandaré por correo los XML con lo que estoy probando.
Tenemos al cliente esperando, uno que ya pagó y otro que le dije que de volada le regresaba una muestra de la adenda para que se convenciera de que podemos agregar la adenda sin problema (addendador).

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
NO, PUES PROBÉ CON EL PROCESO 01, Y AL CAPTURAR PROVEEDOR, PROCESO, PEDIDO, POSICION Y REFERENCIA, TRUENA.
AHORA POR OTRO LADO TAMBIÉN ESTÁ EL TEMA DE CUANDO MANEJAN 2 O MAS PARTIDAS, LLÁMESE 2 O MAS PRODUCTOS.

**Comment by RigoFlores** [comment]
NO ES QUE PROBARA, SINO QUE LE REGRESARON LA ADDENDA AL CLIENTE, Y AL VALIDAR LO QUE ESTABA HACIENDO, TRONÓ.
