### ISSUE TITLE
AFT FI - Hostal y el Galpón, ya no está mostrando la forma de pago en pantalla

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2470]
La forma de pago se incluye en el archivo de texto tanto para hostal o el galpón.
Entonces toma esa información y cuando el ticket se agrega a la pantalla de facturación FI, ahí debe cargar la forma de pago, pero no lo está haciendo.

Lo hice desde FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI FI

**Comment by jccastillo0007** [comment]
fixed
