### ISSUE TITLE
No está funcionando la cancelación masiva (por conector)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2472]
La aplicación desde el conector, aparentemente no tiene problema, ya que es la misma desde hace un rato.
Lo que parece que cambió es en el servidor, y creo que es porque está considerando el número de folio como un entero, y en el caso de nuestro cliente, es alfanumérico.

Este es el log de los intentos que hice hoy.

[FacturaT.log](https://github.com/user-attachments/files/16957009/FacturaT.log)

**Comment by jccastillo0007** [comment]
mysql> select * from CFDiFolios where emisor = 'TRA8402225G0';
+-------+---------------+---------------------+--------------+-----------+-----------+--------+---------------------+
| id    | current_folio | dateOfIssue         | emisor       | fin_range | ini_range | status | date                |
+-------+---------------+---------------------+--------------+-----------+-----------+--------+---------------------+
|  9263 |         10000 | 23/07/2023 20:00:16 | TRA8402225G0 |     10000 |         0 |      4 | 22/07/2022 20:00:16 |
| 10445 |         24015 | 26/03/2025 16:34:18 | TRA8402225G0 |     24015 |     10000 |      4 | 26/03/2024 16:34:18 |
+-------+---------------+---------------------+--------------+-----------+-----------+--------+---------------------+
2 rows in set (0.01 sec)

**Comment by jccastillo0007** [comment]
Ya no tiene folios disponibles desde 26/03/2025 16:34:18

El error que manda es solo para saber que es alfanumérico, pero no se detiene el proceso ahí... 

Igual y luego le quito ese mensaje para que no confunda.

Antes del error dice: 

2024-09-09 13:59:53,495 DEBUG [http-nio-8080-exec-1] (Validator.java:89) - Get folios from DB (TRA8402225G0) : 0

**Comment by RigoFlores** [comment]
ok, ya le notifiqué al cliente.
