### ISSUE TITLE
PFTv2.0 - Configuración tiene un comportamiento distinto en chrome que en mozilla

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2474]
De inicio hay que probar, validando con los únicos campos que deberían ser obligatorios son:

Régimen Fiscal
archivo .cer
archivo .key
contraseña.

todo el resto de la pantalla, es opcional.

Con ello probaré donde está el tema de la pantalla en chrome.

**Comment by RigoFlores** [comment]
si, ya acepta solo los campos mínimos requeridos.
Pero al eliminar el logo o eliminar la plantilla PDF, indica que si la quitó, y después de darle guardar, vuelven a aparecer ambos.

**Comment by jccastillo0007** [comment]
fixed
