### ISSUE TITLE
PFTv2.0 - Carta Porte, mover los catálogos de carta porte a un submenú de carta porte.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2476]
Hoy están todos revueltos, y los de carta porte, me parece que deben quedar aparte, ya que el cliente que no es carta porte, se puede confundir.

Podría ser un submenú de catálogos que diga carta porte.
Los catálogos a mover son:

Remolques
Operadores
Transportes
Ubicaciones
Mercancías 
Propietarios

**Comment by jccastillo0007** [comment]
ya moví este a trello
