### ISSUE TITLE
PFTV2.0 - Carta Porte catálogo de mercancía, homologarlo con lo que se tiene actualmente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2478]
El catálogo de mercancías, debe ir con los campos y agrupaciones que se tienen actualmente en producción.
ahora mismo le faltan campos y no están agrupados, ya que los grupos indican cuáles se deben capturar en conjunto

**Comment by jccastillo0007** [comment]
Este ya lo moví a trello
