### ISSUE TITLE
AFT - está poniendo el mismo CP del receptor en lugar de expedición

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2483]
No manches, es un gran pedo.
Debe poner el CP que se incluye en la llave... tssss

**Comment by jccastillo0007** [comment]
es solo en el xml o pdf también ?

**Comment by RigoFlores** [comment]
Varios puntos:

Desde FI, no jala.
Solo desde FR pude timbrar, pero sigue enviando el CP incorrecto en el PDF
Este cambio debe aplicar a todos los conectores, ya que es una falla para todo AFT.

**Comment by RigoFlores** [comment]
Ok, ya está para alteza FI & FR. Hay que subirlo a pro.

Nos estamos metiendo en un pedo grande, por reportar un CP del emisor que no le corresponde a los otros AFTs.
Hay que arregarlo en chinga.

**Comment by RigoFlores** [comment]
Para Virtual Homes, ni desde FR ni desde FI, le coloca correctamente el CP en el PDF. En el XML si lo hace bien.

Biosplash marca internal error si quiero facturas desde FI. Desde FR trabaja todo OK. Recordar que Biosplash genera las remisione desde la pantalla de PFTv20

**Comment by jccastillo0007** [comment]
Listo Biosplash.

Probaste Galpon ?

**Comment by jccastillo0007** [comment]
Ya revise Virtual Homes, el zipcode si lo manda bien al xml , en el pdf se manda pero imprime otro, checa la plantilla.
lugarExpedicion=64258 //este es el zipcode de virtualhomes en pru

**Comment by RigoFlores** [comment]
acabo de checar una factura del galpón, con fecha de ayer, y sigue el problema...

cuándo se llevó a producción???

**Comment by RigoFlores** [comment]
ya me perdí en este tema, cuál es su status???
Pasa mucho tiempo y ya no recuerdo en que va cada asunto...

**Comment by RigoFlores** [comment]
a ver, la plantilla de virtual homes, tenía fijo el CP entonces ya la cambié, eso ya quedó
El galpón en pru, se validó y todo jaló bien.

**Comment by RigoFlores** [comment]
> Listo Biosplash.
en FI sigue marcando internal error al intentar timbrar
en FR ya lo hizo bien.

**Comment by RigoFlores** [comment]
Listo Biosplash me refería a que ya lo probé nuevamente.
FR bien, pero FI sigue con el error.

**Comment by RigoFlores** [comment]
pues en el hostal ya brincó el pedo...
