### ISSUE TITLE
Addenda Musashi - duplica el XML y el registro en consultas,  cuando se captura mas de una ocasión la addenda

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2485]
Cuando inicialmente el proveedor captura la addenda con error, en algún momento le pedirán que la corrija y tendrá que volver a capturarla.

Si ahora mismo vuelve a capturar la addenda sobre el mismo XML, duplica el registro en consultas, así como el XML.

Hay que mantener únicamente el último archivo/registro capturado

**Comment by jccastillo0007** [comment]
el XML no se duplica, solo la base de datos, estoy viendo como evitar eso

**Comment by jccastillo0007** [comment]
checaste que los cambios hechos la segunda vez, si se persisten en el XML?

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
en pro, el registro se sigue duplicando, pero el XML es el mismo para todos los registros

**Comment by jccastillo0007** [comment]
debes checarlo en pru

el xml debe contener los últimos cambios de la addenda que se capturó

**Comment by RigoFlores** [comment]
en pru, ya está
