### ISSUE TITLE
PFTv20 - marca error al intentar configurar contraseña de MAP120305352

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2486]
no  permite definir la contraseña para ese RFC

**Comment by jccastillo0007** [comment]
Esto no funciona porque existen tres usuarios de MAP120305352
Chiaaa , solo debe haber uno

**Comment by jccastillo0007** [comment]
mysql> select * from Users where userId = 'MAP120305352';
+------+--------------+----------------------+--------------+-----------+----------------------------------+------+--------------------------------------------------------------+
| id   | password     | role                 | userId       | client_id | emails                           | name | passwordV2                                                   |
+------+--------------+----------------------+--------------+-----------+----------------------------------+------+--------------------------------------------------------------+
| 4626 | MAP120305352 | ["ADMIN","CxC_MENU"] | MAP120305352 |    100700 | judith.rodriguez@musashina.com   | NULL | $2a$10$qHUYoRRq2OsgKnbAv24qZeRlU4tx/4KBj6tnWwZm1bIvqi5oVCrHm |
| 4955 | MAP120305352 | ["ADMIN","CxC_MENU"] | MAP120305352 |    100700 | bernardo.hernandez@musashina.com | NULL | $2a$10$y6Dpj6ujeYy7mgzv1.f7T.tR9eQ4d06XDjtnXxy/EHkA9BtA5Bxh2 |
| 4956 | MAP120305352 | ["ADMIN","CxC_MENU"] | MAP120305352 |    100700 | pedro.ramos@musashina.com        | NULL | $2a$10$y6Dpj6ujeYy7mgzv1.f7T.tR9eQ4d06XDjtnXxy/EHkA9BtA5Bxh2 |
+------+--------------+----------------------+--------------+-----------+----------------------------------+------+--------------------------------------------------------------+
3 rows in set (0.00 sec)

**Comment by RigoFlores** [comment]
si lo había comentado antes, que tenía 3 correos...
el tema es que como emisor de facturas, requieren 3 correos...

qué hacemos ahí?

**Comment by jccastillo0007** [comment]
no pueden tener el mismo usuario

**Comment by RigoFlores** [comment]
tenemos emisores con múltiples correos definidos a donde les llegan las facturas en PFTv1

Aquí en la PFV20 cómo hacemos eso?

**Comment by jccastillo0007** [comment]
hay que levantar otro ticket para probar y soportar ese feature

**Comment by RigoFlores** [comment]
antes de levantar otro issue, debo entender cuál es el issue.

Si busco en el keygenerator en ese rfc, solo aparece un correo.
Ahora, si intento entrar desde PFTv1, no puedo.
Veo que existen 3 usuarios iguales con la misma contraseña (MAP120305352), cómo se hizo eso? Aunque son los mismos usuarios, tienen distinto correo. Quién los definió o cómo se dieron de alta esos correos?

**Comment by jccastillo0007** [comment]
no lo sé, tal vez los creé yo por query

**Comment by RigoFlores** [comment]
cerraré este ticket, sin realmente haberse resuelto...
