### ISSUE TITLE
NO ENVIA CORREOS DESDE EL WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#249]
PUES RESULTA QUE A LOS CLIENTES LES SUPER URGE, ES UNA FUNCIÓN QUE LES DESCARGA MUUUCHA CHAMBA.
Y SI, AHORA QUE ESTOY AQUÍ, HAN HABLADO VARIOS CLIENTES QUEJÁNDOSE DE LO MISMO.

**Comment by jccastillo0007** [comment]
Fixed
