### ISSUE TITLE
Addendador Musashi - permite la captura de letras en los ID de los conceptos.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2490]
Una vez que se carga el archivo XML, en la sección de Producto Linea Id, ahí permite capturar letras y permite generar el XML.

Lo que se debe hacer, es validar que únicamente se capturen de 2 a 3 dígitos. Ningún otro caracter

**Comment by jccastillo0007** [comment]
el schema dice hasta 4 caracteres, lo modifico a 3 ?

**Comment by RigoFlores** [comment]
Ese punto no se trató en ningún momento durante la definición y pruebas.
Ayer en el curso brincó, que no iba a rebasar los 3 números.

Se puede modificar el xsd, y/o simplemente restringir la captura en pantalla a máximo 3 dígitos.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
el XSD se mantuvo igual?

**Comment by jccastillo0007** [comment]
Si
