### ISSUE TITLE
Addendador Musashi - piden quitar los '1' que pone por omisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2491]
tanto en número de orden de compra, cómo en delivery note.

dicen que eso puede confundir.

(básicamente, lo mismo que yo dije).

Entiendo que algo tiene que ver con la programación, pero se debe poder hacer algo.
quizá al poner el foco en la orden de compra, limpiar ambos datos, no sé... darle la vuelta de alguna manera.

**Comment by jccastillo0007** [comment]
que le leyenda le pongo?, debe tener un valor, eso es parte de configurar los datos extras y de addenda en la pantalla de configuración

**Comment by RigoFlores** [comment]
Lo que piden ellos, es que no aparezca ningún dato, es decir, que no tengan que borrarlo siempre.
(para mi eso es lo debería ser también, lo indiqué en su momento).

Si no hay de otra opción, pues simplemente no se puede quitar.
Sin embargo quizá algo que se podría hacer, es que cuando tecleen inicialmente la orden de compra, cuando esa caja de texto (orden de compra) tenga el foco, limpiar el contenido del delivery note. 
Está medio chafa, pero pues para evitar errores (que se vaya el 1 por no haberlo borrado), para hacer simple la captura (no estar borrando siempre) puede ser una solución.

De hecho, muy pocos proveedores ocuparán el campo del delivery note.

**Comment by jccastillo0007** [comment]
pero cuando lleguen otros proveedores y ellos capturen los da tos de addenda, deben saber como hacerlo, podemos ponerle un espacio

**Comment by jccastillo0007** [comment]
les puse un espacio, checa a ver si no causa problemas al crear la addenda

**Comment by RigoFlores** [comment]
no, esto no jaló, ya que si manda el espacio vacío en la addenda.
La forma de solucionarlo, será que al momento de cargar el XML, se vacien los valores de PO Number y DeliveryNote...

**Comment by jccastillo0007** [comment]
done
