### ISSUE TITLE
PFTV2.0 - configuración de la TIA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2492]
Cuando entro a la pantalla de configuración con la cuenta de la tia en pro, le doy editar... no me permite editar el correo.
De hecho en el campo de correo, coloca otra cosa.

Luego le doy cancelar, y nuevamente editar, y entonces si ya jala.

tiene por ahí un tema que no permite editar en el primer intento.

eso pasa con la cuenta de la tia, y no pasa con las nuevas cuentas de proveedores de musashi.

Bueno con la cuenta de LOCL80 que es cliente de nosotros, no habilita el botón de guardar.

Por ahí existen temas con cuentas que existen en ambas plataformas.

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Pues sigue igualito en chrome, pero en mozilla lo hace bien... no se que sea, hay que estar pendientes.
