### ISSUE TITLE
PFTv20 - en la cuenta de la tia, pantalla de facturación, producción si buscas por nombre, se queda dando vueltas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2493]
Como si estuviera en un loop infinito.
Tengo que elegir el nombre recorriendo la lista, ya que esa búsqueda no jala.

Adicionalmente, no muestra en orden en listado de los RFC's

**Comment by jccastillo0007** [comment]
veo que no sirve la búsqueda, pero no sé que es lo del loop infinito, no pude reproducirlo

**Comment by RigoFlores** [comment]
el loop infinito es que se queda "dando vueltas", pero no hace nada (no funciona la búsqueda, tal como mencionas).

**Comment by jccastillo0007** [comment]
hmmm en mi caso solo no funciona el search, y el ordenamiento que dices
pero no tiene ningún efecto de loop, puedes checar con otro browser

**Comment by jccastillo0007** [comment]
El problema era un registro que no tenía nombre, chiaaaa

**Comment by RigoFlores** [comment]
es raro que un registro no tuviera nombre, ya que pues el sistema no lo  permite.
Recuerdas cuál era?
