### ISSUE TITLE
Addendador Musashi - Borrar el registro de un proveedor y agregar un pequeño listado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2495]
te envié la info por correo.

Es lo que te comentaba al inicio, ellos necesitarán una herramienta de ABC en los registros de proveedores.

**Comment by jccastillo0007** [comment]
Borrar no es necesario, si acaso para no tener basura en la base de datos, pero no les afecta en nada

**Comment by RigoFlores** [comment]
Se van a confundir, ya que ese borrado, realmente es una modificación al rfc, ya que ese rfc está incorrecto en el primer listado. 
Y en el segundo listado, ya viene corregido.

**Comment by jccastillo0007** [comment]
done
