### ISSUE TITLE
Addendador Musashi - ajustes en orden de compra

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2496]
Cambiar la leyenda de 

PO LineID

a

PO Number

Adicionalmente, validar que únicamente acepte numéricos. Solo números

**Comment by jccastillo0007** [comment]
Esto se hace en la pantalla de configuración de cada proveedor.

**Comment by RigoFlores** [comment]
Ahí está el pedo, jejeje... no es posible hacerlo uno por uno, son muchos...
Hay que hacerlo en tablas directamente, donde se hace??

Y así estarán brincando temas por no haber generado un perfil de proveedor,...

**Comment by jccastillo0007** [comment]
aún con su perfil de proveedor, tendrían que hacerlo 1 por 1

**Comment by RigoFlores** [comment]
yo creo que desde la tabla con un cueri, 
update tal set campo = "PO Number" donde X campo = "PO LineID" and algo

**Comment by RigoFlores** [comment]
de hecho el planteamiento era que la addenda solo estaría definida para el rfc de musashi.
Y del catálogo de proveedores de musashi, se tomarían los datos de usuario y contraseña para cada proveedor.
Con ello, solo en un lugar estaría definida la addenda y los usuarios se podrían modificar any momento por musashi
Y que se definiera el perfil de proveedor, para que solo vieran lo que tenían que ver.

**Comment by jccastillo0007** [comment]
hmmm no entiendo como esa propuesta compleja, puede resolver el tema de los datos de addenda cada que los cambien

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
> hmmm no entiendo como esa propuesta compleja, puede resolver el tema de los datos de addenda cada que los cambien

dado que la addenda solo estaría definida para el usuario de Musashi, pues solo ahí se cambiaría todo lo que tuviera que cambiar de la addenda.

Incluso, este tema va mas allá, ahora mismo no podríamos soportar una addenda adicional o sí??
