### ISSUE TITLE
De donde se toman las plantillas para el PDF en PFTv2.0 ?

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2497]
En pru, para la cuenta IIA, tenía definida una plantilla con terminación jasper (en pftv1 esta debe ser terminación jrxml), y generó la factura bien con un formato a la medida.
Luego se la eliminé de la configuración, quedó vacío, sin plantilla y generó bien la factura, pero con un formato a la medida.

Entonces aquí surge el tema:

Aparentemente no está tomando en cuenta la configuración para la plantilla, que en este caso está vacía
De donde toma la plantilla genérica, cuando no tiene definida una plantilla?

Favor de indicar el detalle de todo el tema de las plantillas jasper. Recuerdo que definimos una nomenclatura estándar. 
Pero no recuerdo donde busca las plantillas?

**Comment by jccastillo0007** [comment]
genericas en : /eFacturaT/jaspertemplates/

personalizadas en: /eFacturaT/customers/{RFC}/setup

**Comment by RigoFlores** [comment]
para PFTv2.0, esas rutas aplican únicamente en el nuevo servidor??
Porque veo que son las mismas que para PFTv1,0

**Comment by RigoFlores** [comment]
OK, entonces ya veo cuál es el problema.
**SI en la pantalla de configuración de PFTv2.0**, por ejemplo en pruebas para IIA, elimino la plantilla para que se vaya por el genérico no lo hace, ya que no borra la plantilla de /eFacturaT/customers/{RFC}/setup

Entonces, no se requiere que la borre; de hecho creo que debe mantenerla en el directorio.
Lo que es un error, es que ignore la configuración y siga buscando en el directorio de setup.

cómo debe quedar en la pantalla de configuración?
... si tiene plantilla configurada, la va a buscar en el directorio local
si no tiene plantilla configurada, no va a buscarla y se va directamente a la genérica.

**Comment by jccastillo0007** [comment]
fixed.

Recuerda que las plantillas personalizadas deben tener este formato:

"cartaporte_" + rfc + ".jrxml";
"ingreso_" + rfc + ".jrxml";
"nomina_" + rfc + ".jrxml";
"egreso_" + rfc + ".jrxml";
"remision_" + rfc + ".jrxml";
etc
