### ISSUE TITLE
PFT20 - ajustes en el reporte de consultas de facturación para biosplash

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#2498]
Este cliente BAR170213PH1 está solicitando estos cambios en el reporte.

Los resalto en amarillo dentro del excel.

Básicamente se trata de repetir el renglón agregando en cada renglón la cantidad y descripción del producto.
En el ejemplo, la primera factura contiene 3 productos, la segunda 2 y la tercera tiene un solo producto.

[AjusteBiosplash.xlsx.txt](https://github.com/user-attachments/files/17739517/AjusteBiosplash.xlsx.txt)

**Comment by RigoFlores** [comment]
Le agregaron la columna del ID producto. Así quedaría.

[AjusteBiosplashV2.xlsx.txt](https://github.com/user-attachments/files/17818632/AjusteBiosplashV2.xlsx.txt)

**Comment by jccastillo0007** [comment]
listo, checa en pru
no hay un rfc específico, funciona para todos, pero vamos a agregar un checkbox para que el cliente decida si quiere el detalle o no

**Comment by RigoFlores** [comment]
Porqué si la factura tiene un solo producto, genera 2 renglones?
El segundo con la cantidar = 0.

Es decir, aunque tenga mas de 1 producto la factura, le está agregando un reglón adicional con cantidad = 0.

**Comment by jccastillo0007** [comment]
un renglón es a nivel factura y es el que aparece en pantalla, el otro renglón es a nivel producto

**Comment by RigoFlores** [comment]
no se puede eliminar cuándo se requiera este reporte?

**Comment by jccastillo0007** [comment]
eliminiar el header ? osea el que aparece en pantalla ? 
si se puede, quieres que lo hagamos así ?

**Comment by RigoFlores** [comment]
me refiero a cuando se solicite el reporte con detalle, se elimine ese registro que tiene cantidad = 0.
Si se puede, sería bueno hacerlo.

**Comment by RigoFlores** [comment]
ya vi los 2 reportes.
El general está bien, así como se genera regularmente.

En del detalle, veo que mantiene un renglón extra con cantidad = 0**. Habría que eliminarlo.** 
Por otro lado, cada producto mostrado, presenta cantidad, ID producto, nombre. Está OK
Sin embargo cada producto también presenta **Subtotal, IVA y total** (pero de toda la factura)

¿¿Es posible para el reporte de detalle, eliminar ese subtotal, IVA y total, y en su lugar colocar precio unitario e importe???

**Comment by jccastillo0007** [comment]
ya quite el renglón con cantidad = 0, si le pongo los datos del producto, ya no verán en ningún lugar los datos del total de la factura, puesto que quite el renglón del general de la factura

**Comment by RigoFlores** [comment]
si, al final ese detalle lo podrán obtener en el reporte general.
aquí, para ser consistentes con la info del producto, pues que muestre cantidad, PU, importe y descuento.

**Comment by jccastillo0007** [comment]
puedo poner esos valores, pero el nombre de las columnas no se puede cambiar

**Comment by jccastillo0007** [comment]
creo que no se va a poder porque lo que muestra en pantalla , en realidad es el primer registro o el header de la factura, y ya trae el primer producto, si cambio esos datos se modifica lo que se está viendo en pantalla.

Hay otra opción pero necesito hablar con Victor para ver algo del UI

**Comment by jccastillo0007** [comment]
no se puede mostrar como lo requieren , porque afectaría a todos los reportes de todos los clientes, pero si podemos agregar otras columnas para el reporte en excel, donde se vean los totales de los productos

**Comment by RigoFlores** [comment]
Bueno entonces así ya quedaría???
Nuevamente no es como lo pide el cliente, sino como se pueda??

**Comment by jccastillo0007** [comment]
podemos agregar la info de los totales de los productos, está bien?

**Comment by RigoFlores** [comment]
no, pues ya hay que dejarlo así, a ver que dicen.
