### ISSUE TITLE
INTENTO DAR DE ALTA UN CLIENTE PREVIAMENTE BORRADO Y ME INDICA QUE YA EXISTE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#25]
APARENTEMENTE NO HACE EL COMMIT, PORQUE VACIÉ LA BD DE CLIENTES, Y AHORA QUIERO DAR DE ALTA UNO (XAXX010101000) Y ME INDICA QUE YA EXISTE. A MENOS QUE ESE RFC TENGA UN TRATO ESPECIAL

**Comment by RigoFlores** [comment]
SIGUE IGUAL

**Comment by jccastillo0007** [comment]
El RFC XAXX010101000 es el RFC que utiliza el usuario demo / demo.

Elige otro RFC para hacer tus pruebas.

**Comment by RigoFlores** [comment]
AHORA INTENTÉ DAR DE ALTA CON MI RFC, Y LO MISMO, INDICA QUE YA EXISTE.
EN ALGÚN MOMENTO LO DÍ DE ALTA, PERO LO ELIMINÉ, Y NO PERMITE CAPTURARLO OTRA VEZ

**Comment by RigoFlores** [comment]
no me permite dar de alta mi rfc como cliente
(ya se, ya sé... ya lo he reportado, pero cada ocasión que se me olvida y lo intento nuevamente, me parte la ma....)

**Comment by jccastillo0007** [comment]
Done....
