### ISSUE TITLE
REGRESAR EL BOTÓN DE CANCELACIÓN A SU POSICIÓN ORIGINAL

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#250]
INCLUYENDO SU COLUMNA DE CANCELAR... 
OBVIAMENTE APLICARÁ SOLO PARA FACTURAS...

**Comment by jccastillo0007** [comment]
Done, en pruebas.

**Comment by RigoFlores** [comment]
Dado que no se puede cancelar en pruebas, no es algo que pueda validar.
Simplemente le dí click en el botón que ya aparece nuevamente, pero arrojó un par de mensajes contradictorios:

Error al cancelar la factura (105)  
La Factura fue cancelada exitosamente !!! 

Si habría que revisar esta situación.

**Comment by jccastillo0007** [comment]
Ups... faltó un restart al tomcat para que vieras la ultima version.... el lunes amanece en Produccion

**Comment by RigoFlores** [comment]
Ya ví el botón en su posición original, OK
Ya ví que desapareció el botón, de la ventana de editar, OK
Lo que es inforrecto, es que después de cancelar, no muestra el acuse de cancelación.
Si el resultado es cancelado exitosamente o previamente cancelado, deberá mostrar el acuse correspondiente.
Además el acuse no incluye el mensaje correspondiente al código, por ejemplo: factura cancelada existosamente, factura previamente cancelada, error en el proceso de cancelación, etc.
