### ISSUE TITLE
REORDENAR LOS CAMPOS DE NOMINA EMPRESARIAL

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#251]
ME PARECE MAS NATURAL CAPTURAR DE ESTA MANERA:
A) FECHA INICIAL DE PAGO
B) FECHA FINAL DE PAGO
C) FECHA DE PAGO

ASÍ EN FORMA DE LISTA, Y QUIZÁS CON FONT EN NEGRITAS O MAS GRANDE.

ADEMAS SE AGREGO EN EL CAMPO DE FECHA DE PAGO , LA FECHA EN LA QUE INGRESO AL SISTEMA DANDO COMO OPCION CAMBIAR DICHA FECHA.

**Comment by FraQue0693** [comment]
Se realizo cambio de estructura en el HTML.

**Comment by FraQue0693** [comment]
Y el ultimo requerimiento ya quedo.
