### ISSUE TITLE
MOSTRAR VENTANA DE CONFIRMACIÓN PREVIO A LA CANCELACION

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#252]
Anteriormente si se contaba con la ventana para confirmar la factura a cancelar. Ahora cancela directamente y es un riesgo grande para los clientes. Ayer ya me reportó uno, que no le pidió confirmación.
La ventana de confirmación, debe mostrar los datos básicos de la factura, así como en el escritorio

**Comment by RigoFlores** [comment]
Igual como lo hace escritorio...

**Comment by jccastillo0007** [comment]
Francisco, hay que actualizar el estatus de los defectos para que Rigo lo pueda checar

**Comment by FraQue0693** [comment]
Ya esta la ventana, nada mas es verificar en produccion.

Esto esta relacionado  con  la #264

**Comment by jccastillo0007** [comment]
Fixed.
