### ISSUE TITLE
VERIFICACION DE XML - no se muestra toda la información comparado con el sat

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#253]
mostrar al menos la información que muestra el sat, a saber:
RFC EMISOR
NOMBRE EMISOR
RFC RECEPTOR
NOMBRE RECEPTOR
FOLIO FISCAL
FECHA DE EXPEDICIÓN
FECHA CERTIFICACION SAT
PAC QUE CERTIFICÓ
TOTAL DEL CFDI
EFECTO DEL COMPROBANTE
ESTADO DEL CFDI

**Comment by RigoFlores** [comment]
y la información se debe mostrar completa, ya que ahora mismo se muestra truncada.

**Comment by jccastillo0007** [comment]
Estoy preparando lo necesario para presentar toda la pantalla de la factura

JC@iPhone.
 Saludos.

**Comment by jccastillo0007** [comment]
No tengo el PAC que certificó...

Que jijos es el Efecto del comprobante ?

**Comment by jccastillo0007** [comment]
Entiendo que este issue ya esta corregido, ya debe estar listo en pruebas.
