### ISSUE TITLE
VERIFICACION XML - agregar botón para agregar proveedor al catálogo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#254]
ahora mismo lo agrega sin preguntar, vale la pena mostrar un botón o mensaje, que le pida al cliente confirmar si se desea agregar al catálogo de proveedores.
Si el proveedor ya existe, preguntar si se desea actualizar la información.

**Comment by FraQue0693** [comment]
Listo

**Comment by jccastillo0007** [comment]
Done.
