### ISSUE TITLE
La leyenda del ícono de la lupa, debe ser Verificar CFDI en el SAT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#255]
Apegándonos a la nomenclatura del sat, la etiqueta del ícono debe ser 'Verificar CFD en el SAT'.
La validación como ahora lo indica, se refiere al tema de la estructura, sello, timbrado, que es un proceso distinto.
Quizás después valga la pena agregar ese botón con esa validación, pero como hemos platicado, si se verifica y el sat lo tiene, entonces lo mas probable es que la estructura haya estado OK

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
CFDI ES CORRECTO.
AHORA MISMO INDICA, CFD.

**Comment by jccastillo0007** [comment]
Done
