### ISSUE TITLE
VENTAS - COTIZACION/PEDIDO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#257]
CUANDO EL USUARIO ELIGE ELABORAR UNA COTIZACIÓN O PEDIDO, SE DEBEN DESHABILITAR LOS SIGUIENTES CAMPOS:
METODO DE PAGO, TARJETA, CFDI (CARTA PORTE, FACTURA, ETC), PAGADA.

**Comment by FraQue0693** [comment]
Faltan detalles en como ocultar el campo de "PAGADA"

**Comment by FraQue0693** [comment]
Listo
