### ISSUE TITLE
VENTAS - COTIZACION/PEDIDO/REMISION ENVIAR NOMBRE DE CF CORRECTO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#258]
CUANDO UN USUARIO ELIGE ELABORAR COTIZACION, PEDIDO O REMISIÓN, SE DEBE ENVIAR AL PDF EL MOBRE DEL COMPROBANTE FISCAL (QUE NO ES COMPROBANTE, PERO SE UTILIZA LA MISMA VARIABLE) QUE CORRESPONDA, A SABER COTIZACION, PEDIDO O REMISION.

**Comment by jccastillo0007** [comment]
Cotizacion, Pedido, Remision etc... es el tipo de documento no el nombre... no tenemos una variable para definir el tipo, me imagino que hay que agregarla.... en otras palabras, se puede tener una cotizacion de una factura... en este caso se manda factura como comprobante.... aunque el tipo sea cotizacion...

**Comment by RigoFlores** [comment]
pues no entendí eso de cotizar una factura... totalmente chueco... el tema es que ahora mismo ya envía el nombre del documento
