### ISSUE TITLE
VENTAS - UTILIZAR LA PLANTILLA CORRESPONDIENTE A COTIZACION, PEDIDO, REMISION.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#259]
Cuando se elige pedido, cotización o remisión, se debe utilizar otra plantilla genérica:
cotización.jrxml, pedido.jrxml o remisión.jrxml.
Se deben enviar todos los datos que ahora mismo se envían, mas el id del documento.
id_cotizacion, id_pedido, id_cotizacion.

**Comment by RigoFlores** [comment]
Fco, te enviará el formato estándar para cotización, remisión y pedido.
Varios clientes preguntan, de cómo va el asunto del este módulo.

**Comment by jccastillo0007** [comment]
Me puedes enviar las plantillas para configurarlas...

**Comment by RigoFlores** [comment]
listón azul....

**Comment by jccastillo0007** [comment]
Donel
