### ISSUE TITLE
NO PUEDO ELIMINAR UN NOMBRE ALTERNO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#26]
NO TENGO LA OPORTUNIDAD DE ELIMINAR UN NOMBRE ALTERNO, INDEPENDIENTEMENTE SI LO TRATÓ COMO SUCURSAL O COMO NOMBRE ALTERNO.

**Comment by jccastillo0007** [comment]
Correcto, si se elimina un nombre alterno, borra todo el cliente....

**Comment by RigoFlores** [comment]
CORRECTO, YA SE PUEDE BORRAR, Y ADEMÁS TAMBIÉN ES CORRECTO QUE LA ETIQUETA SEA NOMBREALTERNO
