### ISSUE TITLE
CANCELACION CFDI - DAR OPCIÓN PARA NOTIFICAR AL RECEPTOR DE LA FACTURA CANCELADA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#260]
NO ME SUENA MAL, LA SUGERENCIA DE UN CLIENTE

**Comment by jccastillo0007** [comment]
Francisco, este requerimiento puede ser facil de resolver, se puede reutilizar la ventana que hiciste para reenviar los correos a los receptores.... solo que aqui se pide al momento de cancelar....

**Comment by RigoFlores** [comment]
SI LO PODEMOS HACER ASÍ, SOLO ME QUEDA LA DUDA, SI TIENE QUE SE AUTOMÁTICO O NÓ.
EN CASO AUTOMÁTICO, AL MOMENTO DE CANCELAR, SE ENVIA EL ACUSE DE CANCELACIÓN EN PDF Y XML, SIEMPRE QUE SE HAYA ENVIADO ESA FACTURA POR CORREO.
EN CASO MANUAL, QUE ES LO QUE ESTÁS PROPONIENDO JC, PUES EL EMISOR SIEMPRE ESTARÍA CONSCIENTE DEL ENVÍO DEL ACUSE AL RECEPTOR.
LO IMPORTANTE DE TODO, ES QUE EL RECEPTOR SE ENTERE, CUANDO SE HA CANCELADO UNA FACTURA, QUE PREVIAMENTE SE LE HABÍA ENTREGADO.

**Comment by jccastillo0007** [comment]
El proceso actual es manual, se mandan los archivos al emisor y receptor,
con la posibilidad de agregar mas correos....

vamos a liberarlo asi primero y vemos la respuesta de los clientes.

Saludos.
JC.

2014-09-24 10:18 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Francisco, hay que actualizar el estatus de los defectos para que Rigo lo pueda checar

**Comment by FraQue0693** [comment]
Ya esta la ventana, nada mas es probar en produccion esto.
Aunque hay un detalle , chequen el #263

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
ESTE ISSUE NO ES POSIBLE VALIDARLO EN PRUEBAS, YA QUE APARENTEMENTE SI NO CANCELA EXITOSAMENTE, NO TE DA LA OPCIÓN DE ENVIAR EL ACUSE, QUE NI SIQUIERA SE GENERA.
CÓMO PODEMOS VALIDAR ESTE TEMA? ES HASTA PRODUCCIÓN? Y SI INYECTAN UNO DE LOS ULTIMAMENTE ACOSTUMBRADOS Y NO BIEN ACEPTADOS POR LOS CLIENTES BUGS...???
