### ISSUE TITLE
Menú de Compras

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#262]
Generar el submenú de compras...

Francisco, aqui describo mas o menos lo que platicamos, dejame saber si algo no esta claro.

Debe existir un menú Compras, con la sig estructura....

Catálogos
   Clientes..
.
Ventas
.
Compras
   Proveedores
   Recepción

Ojo... ya existe el catálogo de proveedores dentro de la sección de Catálogos, hay que moverlo, y cambiar los titulos y lo que sea necesario para que sea un catálogo de Proveedores.

Dentro de la tabla Clients... en el campo owner, es donde se define a que cliente le pertenece ese proveedor..., en la misma tabla Clients, existe el campo clientType que es un enum definido en el proyecto eShared.... en ese enum puedes agregar al final un tipo Provider para distinguir cuando es cliente o proveedor.

Cuando se recibe una factura por medio de la opción Recepción, se debe validar si ya se tiene registrado ese cliente o de lo contrario darlo de alta en el catálogo de proveedores

**Comment by jccastillo0007** [comment]
Closed.

**Comment by RigoFlores** [comment]
SE CIERRA COMO TEMA QUE EXISTE EL MENÚ, PERO SE LEVANTARÁ UN ISSUE EN LA PARTE DE RECEPCION
