### ISSUE TITLE
Reenvio de CFDi

### ISSUE THREAD

**Issue by FraQue0693** [jccastillo0007/eFacturaT#263]
Trata de que el cliente que usa Factura-T en versión web, se dirige a la parte de "Consultas"  y al momento de que visualiza las facturas, aparezca la opción de "reenviar CFDi" , al darle click, aparece una ventana donde carga los datos de la factura que va a reenviar,  y los correos  que tiene el cliente (receptor). Ademas, dar opcion al emisor de agregar uno o mas correos.

Y al momento de dar click en "Enviar CFDi", aparecera un mensaje de que el correo fue enviado exitosamente.

**Comment by FraQue0693** [comment]
Ya envia correos, falta los de adjuntar el PDF y el XML

**Comment by jccastillo0007** [comment]
Francisco, hay que actualizar el estatus de los defectos para que Rigo lo pueda checar

**Comment by FraQue0693** [comment]
Se tienen que hacer modificaciones , porque al momento de que acaba de generar la factura, marca el Error al generar PDF (115), y es debido que el correo(s) del emisor son de tipo "Lista" y lo pasamos a "String",  pone que la sintaxis esta incorrecta.

Y lo que hice fue poner un componente que se llama Iterator, ese sirve para recorrer Listas. Y asi funciono bien de momento la parte del reenvio.

Pero habia platicado con JC de ese detalle, que hay varios clientes que tiene mas de un correo, y que lo ideal era modificar el proyecto EmailingService y el de Shared. Donde llamemos como parametro tipo "Lista" el correo(s) del emisor, para que los envie y ahi , convertirlo a "String" para que se ponga en el formato HTML.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
A VER EXPLÍQUENME ESTO, SIGNIFICA QUE LOS CLIENTES QUE TIENEN INVOLUCRADOS MAS DE UN CORREO EN EL EMISOR O RECEPTOR, MARCA EL ERROR 115?????
ESTE LO TENEMOS ABIERTO DE PRODUCCIÓN

**Comment by jccastillo0007** [comment]
NO... esto se refiere a que de los N correos del emisor, solo se tomaba el primero y a ese se le enviaba la factura...  pero ya quedo resuelto... aún no esta en producción pero ya esta funcionando en pruebas.

**Comment by RigoFlores** [comment]
ok, lo voy a considerar así, pero insisto. Tenemos un problema en producción, el error 115, que según no se puede reproducir, y aquí se menciona un escenario donde se presenta dicho error, aún generando el PDF y XML, tal cual sucede en el problema en producción
