### ISSUE TITLE
DESPUES DE CANCELAR UN CFDI, NO MUESTRA SU STATUS DE CANCELADO O EL QUE APLIQUE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#264]
SE LE TIENE QUE DAR REFRESH A LA PÁGINA PARA QUE LO INDIQUE.
ANTERIORMENTE SI LO MOSTRABA DESPUÉS DE EJECUTAR EL PROCESO DE CANCELACIÓN.

**Comment by jccastillo0007** [comment]
Francisco, hay que actualizar el estatus de los defectos para que Rigo lo pueda checar

**Comment by FraQue0693** [comment]
Hice unas validaciones , nada mas verificar en produccion para ver si no hay algun detalle.

**Comment by RigoFlores** [comment]
el único detalle es que la ventana de confirmación previa a cancelar, es una pantallota, y debe ser algo ad-hoc.
