### ISSUE TITLE
Figueacero- Es inconsistente el manejo de múltiples direcciones de correo de un mismo cliente. 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#268]
La BD solo permite almacenar varios correos para un mismo cliente separados por ‘;’. Pero al momento de enviar múltiples correos, el separador correcto es una ‘,’, ya que el ‘;’ marca error. Ahora mismo la BD no permite almacenar varios correos separados por ‘,’. Conclusión, creo que el separador correcto debe ser ‘,’, tanto en BD, y para el envío múltiple.

JC. No es que te quiera contradecir, pero el caracter final es ';' ya que muchos clientes pueden ya haber ingresado sus correos separados por ';' y si lo cambio por ',' puede causar problemas, y como lo del reenvio de facturas es nuevo, es mas seguro cambiarlo ahi. Fixed.

RIJO, NO ENTENDÍ. COMO QUEDA PARA MÚLTIPLES CORREOS EN BD Y MULTIPLES CORREOS DESDE EL CONECTOR?

**Comment by jccastillo0007** [comment]
siempre se usara ; y no , 

Ya que hasta el momento el cat[alogo soporta ; si le cambio le pega aclientes que ya tienen correos dados de alta, tons, mejor dejamos el ; como el separador gen[erico.

**Comment by RigoFlores** [comment]
correcto, cerramos el tema considerando que el separador de correos, en todo caso será ;
