### ISSUE TITLE
Figueacero - En el envio de correo, aparentemente envía siempre a 'CC'

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#269]
5 En la ventana de enviar factura por email, yo le indico que solo lo envié a ‘PARA’, y le borro el ‘CC’. Aparentemente, le vale madres y lo envía al CC también. Al menos eso se ve cuando llega el correo. Por cierto, eso ha provocado que se llene la bandeja.

JC. mmm el comportamiento que si tiene es que lo manda al emisor, pero no a contacto facturat, tenias como emisor a contacto facturat en la prueba que hiciste?

RIJO. AFIRMATIVO, EL EMISOR TIENE EL CORREO DE CONTACTO.

**Comment by RigoFlores** [comment]
ya revisé a detalle. si le borro el correo de 'CC', no envía el correo.
sin embargo cuando lo recibo, si aparece en el campo 'CC' del cuerpo del correo, el email del emisor (en este caso contacto@factura-t.com.mx)

**Comment by jccastillo0007** [comment]
Este ya debe estar resuelto tambienl
