### ISSUE TITLE
Figueacero - Falta implementar respaldo automático

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#270]
Falta pantalla o archivo properties, donde se indique la periodicidad del respaldo automático, así como la carpeta donde se realizará. (Podría ser en la pantalla de configuración)

JC. El respaldo se hará siempre que levanten la aplicación, a cualquier hora del dia, dado que esta funcionalidad es solo para figueacero, prefiero no meter esos datos en la pantalla de configuración, respecto al folder donde se guardará el respaldo, agregaré una variable en el properties, donde solo figueacero la tendrá.

RIJO, OK PENDIENTE POR IMPLEMENTAR.

**Comment by jccastillo0007** [comment]
Done. work in testing

**Comment by jccastillo0007** [comment]
En el archivo backup.bat, en la linea 22 se encuentra esto ...

set Archive=Backups

Para mover los archivos a otro directorio, solo hay que cambiar Backups por la ruta absoluta... como H:/Backups, no se bien como va la diagonal / o \ pero ahi en guindos tu le sabes.
