### ISSUE TITLE
Figueacero - Implementación de depuración automática

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#271]
Si la aplicación de consulta de históricos, se levantará desde facturat, entonces se deberá tomar la misma configuración del facturat operativo, así como una ruta preestablecida para ejecución de dicha aplicación.
 El punto anterior, servirá para implementar la depuración automática el día 15 de cada mes (este podría ser un tercer parámetro adicional en la pantalla de configuración)

JC. La depuración se hará los dias 15 de cada mes o posterior si el dia 15 no se usa la aplicación, crees que sea necesario configurar eso?

RIJO. ok dejémoslo fijo, y ya veremos la respuesta del cliente

**Comment by jccastillo0007** [comment]
Done... work in testing

**Comment by RigoFlores** [comment]
la tabla de CFD la respalda correctamente, esto es solo transfiere los registros del mes anterior para atrás, dejando los registros del mes actual.
El tema es que la tabla CFDiDetail, la borra completamente del origen y la pasa totalmente al destino. Si no hay manera de conocer las fechas en las tablas, se deberá basar en los índices de los registros que se transfieren de la tabla CFD.

**Comment by jccastillo0007** [comment]
Fixed... solo reemplaza el jar de figueacero_cleanup que se encuentra en la carpeta figueacero.
