### ISSUE TITLE
Levicom - Falta enviar n impresiones cuando así lo indique el archivo de texto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#272]

**Comment by jccastillo0007** [comment]
Done... checar el release chacarron...

**Comment by RigoFlores** [comment]
AÚN TENEMOS ESTE PENDIENTE. CUANDO ES POR CONECTOR, SOPORTAR Y ENVIAR A MAS DE 1 CORREO, CUANDO ASÍ LO INDIQUE EL ARCHIVO DE TEXTO
