### ISSUE TITLE
CONTABILIDAD ELECTRONICA - CATÁLOGO DE CUENTAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#273]
GENERAR LA PANTALLA DE CATÁLOGO DE CUENTAS

**Comment by jccastillo0007** [comment]
Se requiere empezar a desarrollar la contabilidad electr[onica, vamos a empezar por los menús y con el primer XML que se debe generar (y que es el más fácil)

Agregar un menú llamado Contabilidad Electrónica
Agregar un submenú llamado Catálogo de Cuentas

El sub menú debe presentar una pantalla donde se requieren dos filtros de información... ma;ana te marco y te explico y voy subiendo aquí los diferentes catálogos que se requieren, para tener la Info organizada

**Comment by RigoFlores** [comment]
cuando ya lo puedo ver?

**Comment by jccastillo0007** [comment]
Mañana Nov / 14 primer pantalla, el proximo lunes debe estar la pantalla  de balanzas
