### ISSUE TITLE
Workflow ventas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#274]
El japi pad, implica que una cotización pasa a pedido a remisión y a factura
Se puede iniciar el workflow a partir de cualquier documento.
Se puede dar el tracking a una factura, ligando los documentos del worflow que lo generaron, todos relacionados con su uuid
Una cotización, puede editarse antes de pasar al siguiente flujo. Entonces se generarán 2 o mas cotizaciones con el mismo uuid, para poder contar con el historial de la misma cotización o cualquier documento dentro del mismo historial.
Una cotización que ha cumplido su workflow, se puede tomar para generar una nueva factura, pero esto implicará generar un nuevo uuid para dicha cotización y factura.
Se podrá consultar por uuid o por documento, el historial de la misma.

**Comment by jccastillo0007** [comment]
Done tanto en pru y pro.

**Comment by RigoFlores** [comment]
CUANDO UNA COTIZACIÓN HA SIDO FACTURADA, SE PUEDE REUTILIZAR PARA GENERAR OTRO FLUJO.
AHORA MISMO NO LO ESTÁ HACIENDO. LE MANTIENE EL MISMO ID Y SIMPLEMENTE GENERA UN PEDIDO, CON EL MISMO ID DE LA COTIZACIÓN Y FACTURA ANTERIOR.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
CUANDO UNA COTIZACIÓN HA SIDO FACTURADA, SE PUEDE REUTILIZAR PARA GENERAR OTRO FLUJO.
AHORA MISMO NO LO ESTÁ HACIENDO. LE MANTIENE EL MISMO ID Y SIMPLEMENTE GENERA UN PEDIDO, CON EL MISMO ID DE LA COTIZACIÓN ANTERIOR, ADEMÁS CON DATOS VACÍOS.

**Comment by jccastillo0007** [comment]
mmmm esto lo acabas de probar en Pruebas ? es uno de los flujos que probé
ayer.

Saludos.
JC.

2014-11-20 19:37 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
lo acabo de probar

**Comment by RigoFlores** [comment]
posiblemente este es el escenario que no sabías o identificabas, cuando se generaban los documentos vacíos, es decir sin productos. Y esto es cuando 'reutilizas' una cotización.
