### ISSUE TITLE
Produccion Web: solo envía 1 correo, aunque el emisor o receptor tenga definidos mas de uno

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#277]
´En producción Web

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
CON QUE CUENTA PROBARON, PARA PODER REVISAR EN PRUEBAS?

**Comment by RigoFlores** [comment]
sigue igual sin jalar en producción

**Comment by jccastillo0007** [comment]
Fixed.

Hice varios cambios, pero apenas ahorita lo subí a pruebas

**Comment by RigoFlores** [comment]
sigue igual en producción, solo envía a uno correo del emisor.
En pruebas al parecer si jala.
Se supone que ya está igual en pruebas que en producción?

**Comment by jccastillo0007** [comment]
Si, las versiones son las mismas, ya debe estar resuelto... generé una cotización para probar y si jalo

**Comment by RigoFlores** [comment]
Generé una factura en producción, y no.... le indiqué que solo enviara al emisor... el emisor tiene 2 correos configurados... y solamente llegó un correo... sigue igual en producción, para facturas...

**Comment by jccastillo0007** [comment]
Fixed
