### ISSUE TITLE
NO PERMITE CAPTURAR TODOS LOS CAMPOS DE LAS PANTALLAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#28]
PARTICULARMENTE LO VÍ PARA CATÁLOGO DE CLIENTES, DONDE NO ME PRESENTA LA POSIBILIDAD DE CAPTURAR EL CORREO Y TELÉFONOS, PERO AL MOMENTO DE INTENTAR GUARDAR, ME INDICA QUE FALTA CAPTURA EL CORREO. DOBLE FALLA, PRIMERO NO PRESENTA LA CAJA DE TEXTO PARA CAPTURAR TODOS LOS DATOS, Y LUEGO EL CORREO NO ES DATO OBLIGATORIO.
ESTE PROBLEMA, SE ESTÁ PRESENTANDO EN DISTINTAS PANTALLAS.

**Comment by jccastillo0007** [comment]
Correcto, cometi un error en un refactooooooor y le pegue a todos los catálogos, ya esta corregido.

**Comment by RigoFlores** [comment]
APARENTEMENTE QUEDÓ RESUELTO
