### ISSUE TITLE
FIGUEACERO - EN ENVIO DE 'EMAIL(TODO)', PONER PANTALLA DE CONFIRMACIÓN

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#280]
AHORA POR ERROR ENVIARON A TODOS, Y SALIÓ UN CAGADERO DE CORREOS. PIDEN COLOCAR PANTALLA DE CONFIRMACIÓN.
DESEA CONTINUAR EL ENVÍO DE TODOS LAS FACTURAS QUE APARECEN EN EL RESULTADO DE LA CONSULTA ACTUAL???

**Comment by jccastillo0007** [comment]
done
