### ISSUE TITLE
COTIZACION-PEDIDO-REMISIÓN COLOCA EL MISMO PDF EN TODOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#281]
CONFORME AVANZAS EN EL PROCESO, VA PLANCHANDO LOS DOCUMENTOS ANTERIORES.
POR EJEMPLO SI GENERO UNA COTIZACIÓN, UN PEDIDO Y UNA REMISIÓN, AL FINAL LOS 3 MUESTRAN EL MISMO PDF.

**Comment by RigoFlores** [comment]
SIGUE IGUAL.... YA SÉ, NO SE HA REPORTADO COMO RESUELTO.... YO TENÍA LA ESPERANZA....

**Comment by jccastillo0007** [comment]
Fixed.

Hice varios cambios, pero apenas ahorita lo subí a pruebas
