### ISSUE TITLE
no lleva control de consecutivo para cotizacion, pedido y remisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#282]
SE HABÍA PLATICADO Y ACORDADO ASIGNAR POR OMISIÓN LA SERIE COT, PED Y REM PARA PROPÓSITOS DE LLEVAR UN CONSECUTIVO.
AHORA MISMO GENERÉ 2 COTIZACIONES, Y EL FOLIO ASIGNADO, ES EL ID, QUE NO TIENE NADA QUE VER CON UN CONSECUTIVO.

**Comment by jccastillo0007** [comment]
Negativo, nunca acordamos el uso de series predefinidas por nosotros, de hecho, ese es el tema en el que nunca nos hemos puesto de acuerdo, lo que acordamos, es que se debe proporcionar la funcionalidad para que el cliente asigne una serie a cada tipo de documento... ellos podrán definir el nombre que quieran y asignarla al documento.

**Comment by RigoFlores** [comment]
Seguimos en espera a mas de 1 año de este requerimiento... ahora ya lo pidió específicamente un cliente y pues por 'no ponernos de acuerdo' en algo que me parece muy naturalito... sigue atorado este requerimiento

**Comment by jccastillo0007** [comment]
Ya esta en PRU, series hardcoded para PED, COT y REM, el cliente debe dar de alta las series en el catálogo de folios....

Dado que antes no se usaban serie y folio en dichos documentos, me falta hacer que vaya acumulando los folios utilizados....

Por cierto, ya que termines de quejarte, seria bueno que invirtieras tu tiempo en cosas productivas  y pruebes las fichas que ya estan resueltas, en lugar de estar de nena y quitarme el tiempo al leer correos de nenas...

**Comment by RigoFlores** [comment]
Cuando note que aparentemente todo está estancado, siempre levantaré la mano, porque implica por un lado que no estamos aportando, y por otro lado que nos estamos quedando atrás respecto al avance en alcance del producto y desarrollos nuevos... pero es otro tema.

En cuanto al tema de este issue, si te refieres a que no va incrementando el folio, es correcto ya lo validé y no incrementa. 
En este caso, los folios que tenga disponibles el cliente para timbrar NO DEBEN AFECTAR los folios disponibles para documentos que no se timbran. Así lo tienes visto? Es decir, si ya no tiene folios disponibles para timbrar, ellos podrían seguir generando remisiones por ejemplo.

**Comment by jccastillo0007** [comment]
Correcto, mismo entendimiento.

Ya esta listo en PRU y PRO a partir de ma;ana temprano.

Nota. antes no se contemplaban la serie y folio para los documentos Cotización, Pedido y Remisión, por lo que no había afectación al catálogo de folios y series, ahora con esta implementación chacarrona de series hardcoded a huevo, los clientes deben de dar de alta las series cot, ped, rem de lo contrario el folio siempre será 0, y una vez dadas de alta el folio se va incrementando y siempre se incrementará, si por error ellos eligen una serie diferente, también se incrementará el folio.

**Comment by RigoFlores** [comment]
Correcto... de hecho las series ni siquiera deberían aparecer en pantalla para estos documentos, pero se hizo esta implementación chacarrona... para ser consistentes con el manejo de folios para facturas y recibos de nómina.... y si, el cliente deberá definir las series predefinidas.... y a partir de ahí, la aplicación llevará su control de consecutivos de folios para cada tipo de documento...
