### ISSUE TITLE
no envia por correo la cotizacion, pedido, remisión o factura cuando se genera con el flujo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#283]
NO ENVÍA LA COTIZACIÓN POR CORREO.
CUANDO DESDE CONSULTAS SI SIGUE EL FLUJO, PASANDO A PEDIDO, REMISIÓN Y FACTURA, TAMPOCO ENVÍA EL CORREO

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
GENERÉ UNA COTIZACIÓN, Y SI LA ENVIÓ POR CORREO.
DESPUÉS DE LA VENTANA DE CONSULTA, EDITÉ LA COTIZACIÓN Y GENERÉ UN PEDIDO, Y SI LO ENVIÓ POR CORREO.
TOMÉ EL PEDIDO DE LA CONSULTA, Y LO CONVERTÍ EN REMISIÓN Y NO NO NO ENVIÓ EL CORREO.
FINALMENTE DE CONSULTA GENERÉ LA FACTURA A PARTIR DE LA REMISIÓN, Y SI LO ENVIÓ POR CORREO.

CONCLUSIÓN, CUANDO TOMO PEDIDO A REMISIÓN DESDE LA PANTALLA DE CONSULTA, NO LO ENVÍA POR CORREO.

**Comment by jccastillo0007** [comment]
Fixed.

Hice varios cambios, pero apenas ahorita lo subí a pruebas
