### ISSUE TITLE
VENTAS-RECEPCION MARCA INTERNAL ERROR AL MOMENTO DE CARGAR UN XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#284]
AL MOMENTO DE VALIDAR UN XML, MARCA UN ERROR.
DESPUÉS LO VOLVÍ A INTENTAR, Y EL ERROR LO MARCA DESDE QUE SE ACCEDE AL MENÚ DE RECEPCION

**Comment by jccastillo0007** [comment]
No logre reproducir el error, pero si encontre un problema cuando el XML no es del cliente, no marcaba el error adecuado... mandame tu XML para validarlo...

**Comment by RigoFlores** [comment]
NO, ES QUE NI SIQUIERA PUEDO ACCEDER AL MENÚ DE RECEPCIÓN. MARCA ERROR DESDE EL PRINCIPIO.
AHORA, ESTO ES EN PRODUCCIÓN.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
HASTA QUE LO TENGA EN PRO, LO PUEDO CERRAR, YA QUE FUE AHÍ DONDE SE IDENTIFICÓ EL ERROR. O COMO LO MANEJAMOS?

**Comment by jccastillo0007** [comment]
Lo puedes verificar en pruebas, el viernes o sábado pienso subir todo esto a pro.
