### ISSUE TITLE
LEVICOM - HA SOLICITADO GENERAR LA ADDENDA MABE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#286]
GENERACIÓN DE ADDENDA MABE, PERO EN LAYOUT DE LEVICOM

**Comment by RigoFlores** [comment]
ya se había reportado que no está incluyendo en detalle el dato de 
codigoArticulo="REP-01" 

Además, aparentemente no es la última versión de mabe, ya que incluye el domicilio del receptor, y en la última versión me parece que lo habíamos dejado fuera, dado que es opcional...

```
        <mabe:Entrega plantaEntrega="T032"/>

        <mabe:Entrega calle="AV PRODUCTIVIDAD" codigoPostal="25169" noExterior="125" noInterior="" plantaEntrega="240"/>
```

**Comment by jccastillo0007** [comment]
Done.
