### ISSUE TITLE
EN WEB SE BRINCA LOS FOLIOS CUANDO MARCA ERROR 115 DE TIMEOUT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#287]
EL MENSAJE DEBE CAMBIAR, YA QUE ERROR 115 GENERALMENTE LO UBICAMOS RESPECTO A LA PLANTILLA. DEBE INDICAR TIMEOUT O SIMILAR, AMÉN DE NO BRINCARSE LOS FOLIOS

**Comment by jccastillo0007** [comment]
Duplicado con el issue 533
