### ISSUE TITLE
CATÁLOGO DE PRODUCTOS WEB - AGREGAR LA DESCRIPCION EN EL XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#289]
TENEMOS PROBLEMAS EN WEB, YA QUE NO PODEMOS INCLUIR MAS DE 255 CARACTERES EN EL PRODUCTO/SERVICIO, POR LO QUE SE HACE NECESARIO INCLUIR EN EL XML, EN EL CAMPO DE CONCEPTO, EL CONTENIDO DE 'PRODUCTO/SERVICIO' + 'DESCRIPCIÓN'.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Tenemos pendiente el ajuste, para cambiar los enters capturados en la descripción, por espacios para propósitos del XML.
OJO, lo del PDF se debe mantener tal cual se tiene ahora mismo, que si jala todo correctamente
