### ISSUE TITLE
Descripción distinta para el XML y PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#29]
COMENTABA DESDE HACE MUCHO, QUE EN EL CATÁLOGO DE PRODUCTOS TENEMOS LOS CAMPOS DE PRODUCTO, ID Y DESCRIPCION, Y ESTA CONDICIÓN CONFUNDE, YA QUE AHORA MISMO, ENTENDERÍA QUE DESCRIPCIÓN NO TIENE NINGUNA FUNCIÓN.
EL HECHO ES QUE EN EL PDF TOMA LA DESCRIPCIÓN Y EN EL XML TOMA EL CAMPO PRODUCTO. (LOS PONE CHUECOS).
LA SOLICITUD ES SOLO MANTENER PRODUCTO, CON LA ETIQUETA DE PRODUCTO/SERVICIO, Y EN LA SECCIÓN AMPLIA DE CAPTURA.
SOLO DEBEMOS MOSTRAR ID Y PRODUCTO/SERVICIO

**Comment by jccastillo0007** [comment]
Rijo... ahi te va mi choro mareador de productos.

El Id es una clave o un identificador de un producto, todo los productos de los inventarios deben llevar un id, no veo porque nosotros deberiamos saltarnos eso, si bien, facturat no lo maneja, eso es porque siempre hemos tenido esa diferencia de opiniones, pero eso no quiere decir que este bien, y de hecho, tan es comun el id que en la base de datos de la TIA tu manejas una clave de producto que si parece id, checa la imagen que te mando

Aqui esta el resultado del analisis que hice.

Los campos mas comunmente usados en productos son:
1. Id
2. Nombre del producto o servicio (nombre corto)
3. Descripcion.

Nosotros en FacturaT utilizamos
1. Clave del producto (que es el Id)
2. Nombre del producto y servicio (que mas bien parece descripcion, porque es donde permitimos capturar una descripcion muuuuuy grande en el catalogo de producto)
3. Descripcion complementaria (la cual solo aplica para el PDF y se captura en tiempo de facturacion y no de catalogos).

A FacturaT le hace falta el campo Nombre del producto, y te voy a explicar porque:
1. El SAT solicita en el XML el Id, y la descripcion, dicha descripcion debe ser un nombre corto, no una descripcion detalladada, de hecho esta limitada, este campo es el que deberia ser el nombre.
2. En el PDF, no estamos imprimiendo la clave de producto (ID), esto no significa que este bien o que ningun cliente lo vaya a requerir, esto es solo como lo hemos hecho hasta ahora.
3. En el PDF, estamos desplegando lo que tu le llamas Producto / Servicio, pero que es en realidad una descripcion y que puede ser muuuuy detallada, y tambien estamos desplegando la descripcion complemeentaria, si es que se tiene.

En conclusion, eFacturaT propone usar lo siguiente.
1. Identificador
2. Nombre
3. Descripcion
4. Descripcion detallada

Donde 1 y 2 se van para el SAT y tooooodos ellos del 1 al 4 deben estar disponible para el PDF, y ya cada cliente definira que si ocupa y que no ocupa, pero nosotros debemos tener disponibles
todos los datos, esto puede ir en contra de como estan ahorita las plantillas, no lo se, pero si es el caso, habra que actualizarlas, incluso debo validar que eFacturaT este funcionando adecuadamente bajo estas primicias.

Esta es la manera correcta de manejarlo, necesitas dejar de pensar de como esta ahorita FacturaT, es cierto que ahorita nuestros clientes asi lo ocupan, y que estan conformes, pero la idea es tener todas las opciones necesarias para otros clientes y mas si estamos pensando en un ERP.

No me gusta mandar correos con tanto contenido, porque seria mas facil platicarlo, peor  a esta hora ya es un poco tarde.

JC.
![Screen shot 2013-03-03 at 12 44 21 AM](https://f.cloud.github.com/assets/2245679/213939/7fd559d2-83d0-11e2-9666-b575007e4701.png)

**Comment by RigoFlores** [comment]
Comentarios:

a) El ID si lo utilizan algunos clientes en su formato de factura PDF. Son plantillas a la medida. La graaaaaan mayoría de clientes, pidieron que se quitara, por ello es que la plantilla estándar no lo muestra.
b) El SAT indica que la descripcion del bien o servicio (yo le llamo producto/servicio), en principio tiene que ser la misma para el PDF y el XML. No lo menciona explícitamente, pero bajo ninguna circunstancia menciona 2 descripciones distintas.
c) La descripción complementaria, ha sido un gran éxito para los clientes, ya que es una información que aplica para una factura en particular, sin modificar la descripción del producto. Básicamete es útil para esa factura en particular, y para el receptor.
d) Entiendo lo de descripción corta y descripción detallada en un ERP, de hecho manejan mucho mas campos. No olvidemos que uno de los grandes éxitos de facturat es su simplicidad, y con base a ello, la pantalla de productos del ERP cuando la tengamos deberá contener mucha mas info, pero en este caso es un sistema de facturación, que con los campos actuales ha podido cubrir 100% las necesidades de nuestros clientes. Ten por seguro que si los clientes lo hubiesen pedido, ya estaría implementado ese campo.
Mi voto es que se quede tal cual está hoy en día, y si acaso, que la descripción complementaria se almacene en BD, para esa factura en particular

**Comment by jccastillo0007** [comment]
Ok creo que vamos bien:
En conclusion tenemos 4 campos
- id
- nombre
- descripcion 
- descripcion complementaria

Sabemos que :
1. El id si es necesario
2. La descripcion complementaria es un plus de facturat y queremos conservarla en eFacturaT

El problema es entre el nombre y la descripcion, que para ti es una sola cosa y para mi deberian ser separadas, yo me apoyo en lo que pide el SAT, que es una descripcion corta y lo cual contradice  a lo que nosotros permitimos en la descripcion, y luego tenemos que recortarla para cumplir con el SAT

Es muy dificil que los clientes asimilen que se requiere un id, nombre y descripcion?

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
El anexo 20, para esa sección indica:
Descripción
Atributo requerido para precisar la descripción del bien o servicio cubierto por el presente concepto.

En el PDF se pide lo siguiente:
VIII. Cantidad, unidad de medida y clase de los bienes, mercancías o descripción del servicio o del uso y goce que amparen.

Yo entiendo que se refiere a lo mismo. Incluso, creo que cambiando el contenido de descripción para el PDF y XML, podríamos incurrir en un delito fiscal. 
En conclusión, independientemente de cuál descripción se decida manejar, debe ser la misma para XML y PDF

**Comment by jccastillo0007** [comment]
Propongo que para ser consistentes, en el PDF mostremos  :  
nombre + descripcion  en el primer renglon, la descripcion puede o no existir, pero el nombre si debe existir
descripcion complementaria en el segundo renglon, tal cual como esta ahorita en algunos templates.

**Comment by RigoFlores** [comment]
Estuve revisando algunos ERPs al respecto. Definitivamente a la factura se envia la descripción corta, y típicamente la descripción detallada NO. Entiendo que esta descripción detallada, aplica mas bien para remisiones, y pero todo para COTIZACIONES (donde se requiere el detalle del producto o servicio a adquirir).
Mi propuesta es la siguiente.
*Podríamos mantener la nomenclatura id, nombre del producto/servicio, descripcion detallada, para el catálogo de productos.
*Indicar en pantalla, que el nombre se incluye en la factura por omisión.
*En la pantalla de agregar producto, dar la opción al cliente que incluya la descripcion detallada (por default NO la incluye).
*Esta información, se agrega después de un enter, al nombre, quedando nombre + descripcion detallada, juntos, pero separados por un enter. Lo cual de da claridad en la factura.
*La información complementaria, no cambia. Se agregará al final, opcionalmente.

Según yo, así debe quedar.

**Comment by jccastillo0007** [comment]
Done..

Solo no me quedo claro este punto :  
*En la pantalla de agregar producto, dar la opción al cliente que incluya la descripcion detallada (por default NO la incluye).

**Comment by RigoFlores** [comment]
Cuando agregar el producto, en esa pantalla el usuario indicará con un check box, si desea incluir o nó, la descripción detallada; la opción por omisión es NO incluirla (check box vacío). 
Si desea incluirla, en el PDF se mostrará descripción + enter + descripción detallada; para el XML solo sería descripción + descripcion detallada.
En caso contrario en ambos casos solo se mostrará la descripción.
Hice una prueba, y en el PDF muestra descripción + enter + descripción detallada siempre; y en el XML solo la descripción, es decir sigue quedando chueco.

**Comment by RigoFlores** [comment]
YA ME REPORTÓ UN CLIENTE EL TEMA DE DESCRIPCION, DESCRIPCION DETALLADA E INFORMACIÓN COMPLEMENTARIA.
TAL COMO LO COMENTÉ AL INCIO, ESTÁ TOTALMENTE CONFUNDIDO.
LO ÚNICO QUE DEBEMOS MANTENER ES LA DESCRIPCIÓN (TAL CUAL EL ESTÁN ALON), PERO CON UN ESPACIO SIMILAR AL QUE HOY PRESENTA INFORMACIÓN DETALLADA.
LO PLATICAMOS HACE MUCHO, LE INVERTIMOS TIEMPO, Y VOLVEMOS AL ORIGEN SIMPLE Y LLANO: QUE QUEDE TAL CUAL EL ESTÁN ALON

**Comment by RigoFlores** [comment]
AHORA, SI CAPTURAMOS UNA DESCRIPCIÓN MUY LARGA, CUANDO LA MUESTRA EN PANTALLA, EL COMBO 'SE ESTIRA', DEFORMANDO LA PANTALLA DE CAPTURA.
SE REQUIERE QUE LA ÚNICA DESCRIPCIÓN QUEDE EN EL ESPACIO QUE HOY TENEMOS PARA DESCRIPCION DETALLADA, Y ADEMAS QUE EL COMBO DE DESCRIPCIÓN SE PRESENTE CON UN ANCHO MÁXIMO FIJO, Y NO DE ACUERDO AL CONTENIDO DE LA DESCRIPCIÓN
