### ISSUE TITLE
VENTAS, PARA COTIZACION, PEDIDO Y REMISION CAMBIAR TOOLTIP Y ASUNTO DEL CORREO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#291]
AHORA MISMO DICE FACTURAR PARA GENERAR CADA DOCUMENTO, DEBE INDICAR GENERAR COTIZACION, PEDIDO O REMISIÓN SEGÚN SEA EL CASO.
CUANDO SE ENVIA POR CORREO DEBE CAMBIAR, AL MENOS EL ASUNTO, PERO QUIZÁS TAMBIÉN EL MENSAJE.

**Comment by FraQue0693** [comment]
Listo,se subieron cambios al proyecton de eFacturaT, para que lo veas JC.
