### ISSUE TITLE
Cuando capturas datos extra en una factura junto con impuesto local, este último no se reporta correctamente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#293]
En web, cuando utilizamos el impuesto 5 al millar, lo reporta correctamente al XML.
Pero cuando la factura generada, involucra datos extra a nivel general, al parecer surge un conflicto, y no se reporta correctamente el complemento de impuestos locales, ya que todos los datos aparecen como '0', y lo correcto sería reportar las cantidades correspondientes a lo capturado.

**Comment by jccastillo0007** [comment]
Fixed, disponible en pruebas.

**Comment by RigoFlores** [comment]
validado en pruebas, necesitamos llevarlo a producción asap
