### ISSUE TITLE
CATALOGO DE CUENTAS - EL MES NO SE REPORTA CORRECTAMENTE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#296]
EL MES SE DEBE REPORTAR EN NÚMERO

**Comment by FraQue0693** [comment]
Subi cambios de ese detalle, por fas bajas los cambios para que lo veas y lo subas a pruebas JC.

**Comment by RigoFlores** [comment]
esperaré a la nueva versión para validar corrección
