### ISSUE TITLE
CATALOGO DE CUENTAS - MARCA COMO OBLIGATORIO UN CAMPO OPCIONAL

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#297]
CON LA CUENTA DE LA TIA, EN PRUEBAS, CAPTURÉ 2 BANCOS.
EL PRIMERO (INBURSA) ME PERMITIÓ CAPTURARLO SOLO HASTA EL PRIMER CAMPO OPCIONAL.
EL SEGUNDO (BANCOMER), ME MOSTRÓ UN ERROR QUE TENÍA QUE CAPTURAR LOS 3 CAMPOS OPCIONALES.
EL MENSAJE ADEMÁS ME HIZO LA TARDE, POR LA GRACIA QUE ME CAUSÓ:
'EL CAMPO OPCIONAL (02) ES OBLIGATORIO...' JEJE

**Comment by FraQue0693** [comment]
Listo, ya se subieron dichos cambios al proyecto de eFacturaT. Para que lo cheques JC.

**Comment by RigoFlores** [comment]
LO VOY A CERRAR, PORQUE CAMBIARÁ EL COMPORTAMIENTO DE TODA LA PANTALLA, PERO NI EN PRUEBAS NI EN PRODUCCIÓN, SE TIENE ACCESO A LAS PANTALLAS DE eCONTABILIDAD
