### ISSUE TITLE
CATALOGO DE CUENTAS - EN LOS LISTADOS DE COMBOS NO SE DESPLIEGAN CORRECTAMENTE LOS CARACTERES ESPECIALES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#298]
POR EJEMPLO LOS ACENTOS...

**Comment by jccastillo0007** [comment]
Duplicado con 345.

**Comment by RigoFlores** [comment]
Ya cerré el 345, de lo contrario mis métricas en cuanto a tiempo para cerrar los issues se van a sesgar.
Este es el texto del 345:
EL CONTENIDO MOSTRADO POR LOS COMBOS, Y QUE TAMBIÉN SE INCLUYE EN EL XML DEL CATÁLOGO DE CUENTAS, PRESENTA CARACTERES RAROS CUANDO SUPONGO DEBERÍAN LLEVAR ACENTO O 'Ñ'

**Comment by jccastillo0007** [comment]
Fixed.
