### ISSUE TITLE
IMPLEMENTAR MENU DE CONSULTAS PARA RECIBOS DE NÓMINA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#299]
LOS CLIENTES SE QUEJARON INICIALMENTE DE QUE MOVIMOS EL MENÚ DE CONSULTAS, PERO CONSIDERAN QUE ES MUCHO MEJOR QUE VENTAS, COMPRAS, NOMINA Y ADDENDADOR TENGAN SU PROPIA OPCIÓN DE CONSULTAS, LO CUAL ES MUCHO MAS ADECUADO.

**Comment by jccastillo0007** [comment]
Francisco, la misma estrategia de las consultas de addendas y de compras, pero ahora para nómina...

una vez implementado las consultas de nómina en su propio directorio, hay que eliminar esa opción de las consultas en el menú de ventas.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
ATENDIDO EN PRO...
