### ISSUE TITLE
CFDI NO INCLUYE EL TOTAL EN LA INFORMACIÓN GENERADA EN EL CÓDIGO DE BARRAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#3]
RESULTA QUE TENEMOS CLIENTES QUE ESTÁN ESCANEANDO LOS CBB QUE GENERA EL SISTEMA CFDI EN LOS PDF'S.
NO ESTÁ INCLUYENDO EN EL CÓDIGO DE BARRAS, LA INFORMACIÓN DEL TOTAL.
YO CREO QUE DESDE NUNCA LA HA INCLUIDO.
EL CLIENTE ESTÁ DE PESTAÑAS...

**Comment by jccastillo0007** [comment]
Resolved.
