### ISSUE TITLE
CATALOGO DE ADUANAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#30]
LAS ADUANAS SON UN CATÁLOGO INDEPENDIENTE A PRODUCTOS.
UNA MISMA ADUANA, PODRÍA INCLUIRSE PARA DISTINTOS PRODUCTOS.
UN MISMO PRODUCTO, PARA DISTINTAS FACTURAS, PUEDE ASIGNAR DISTINTAS ADUANAS.

LA PETICIÓN ES SACAR EL CATÁLOGO DE ADUANAS, Y PRESENTARLO ÚNICAMENTE DESDE LA PANTALLA DE FACTURACIÓN, CUANDO SE AGREGA EL PRODUCTO A LA FACTURA

**Comment by jccastillo0007** [comment]
Ok, de acuerdo, lo marque como un enhancement porque no detiene el progreso y liberación del sistema.

De hecho, tenemos hoy en dia algún cliente que ocupe aduanas ?

**Comment by RigoFlores** [comment]
SI CONTAMOS CON ALGÚN CLIENTE QUE OCUPA ADUANA, ES EL DE OPTIBELT, UNO DE LOS QUE MAS FACTURAN.
DE HECHO, SE UTILIZA MUY POCO, Y POR LO MISMO, PARA NO METER RUIDO, TE PEDIRÍA SACAR ESTE CATÁLOGO FUERA DE LA PANTALLA DE PRODUCTOS.

**Comment by jccastillo0007** [comment]
las aduanas ya no son requeridas en 3.3 cierto ?

**Comment by RigoFlores** [comment]
jajaja... te tardas tanto tiempo en atender requisitos, que mejor el sat los elimina... jaja
