### ISSUE TITLE
ADDENDADOR - CAMBIAR LEYENDA DE MENU RECEPCION x AGREGAR ADDENDA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#300]
Hace mas sentido Agregar Addenda, que Recepción

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
CORREGIDO EN PRUEBAS, SE CERRARÁ HASTA QUE SE VAYA A PRODUCCIÓN.

**Comment by RigoFlores** [comment]
PUES NI EN PRUEBAS NI EN PRODUCCIÓN.
ESE CONTROL DE VERSIONES NOS ESTÁ PEGANDO.
YA DICE OTRA VEZ EN PRUEBAS Y EN PRODUCCIÓN, 'RECEPCION'

**Comment by jccastillo0007** [comment]
Done.
