### ISSUE TITLE
EN PRUEBAS DE WEB, NO FUNCIONA LA CONSULTA PARA VENTAS Y COMPRAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#301]
NO MUESTRA RESULTADOS AL CONSULTAR LAS FACTURAS EMITIDAS Y RECIBIDAS.
LO QUE APARENTEMENTE SI FUNCIONA ES LO DEL ADDENDADOR Y LO DE RECIBO DE NÓMINAS.

**Comment by jccastillo0007** [comment]
Fixed.
