### ISSUE TITLE
OCULTAR LA SERIE NOM EN LA PANTALLA DE EMISIÓN DE CFDI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#302]
La serie NOM es creada solo para recibos de nómina, por lo que si aparece en la pantalla de elaboración de facturas, seguro podrá generar un error por no cambiar la serie, sobre todo cuando aparece por default, que ya tenemos varios casos detectados

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
RESUELTO EN PRO... CHIAAA... UNOS EN PRU Y OTROS EN PRO....
