### ISSUE TITLE
ESCRITORIO - NO INCLUYE LAS FACTURAS CANCELADAS EN EL REPORTE DE EXCEL

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#303]
Aunque no le pongas filtro de canceladas las omite del reporte.
Si le colocas filtro de canceladas, el reporte aparece vacío.

**Comment by RigoFlores** [comment]
Ahora mismo un cliente se está quejando de este issue que tiene toda la vida abierto... necesitamos atenderlo

**Comment by jccastillo0007** [comment]
Fixed.

Por alguna razón, estaba explícitamente la validación de que las facturas deberían estar activas, ya se lo quite, pero haber si no brinca otro cliente.

Lo puedes checar con el release de hoy en la noche.
