### ISSUE TITLE
ESCRITORIO - SOPORTAR IMPUESTOS LOCALES, ASÍ COMO EN WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#304]
ES DECIR QUE LOS PUEDAS ELEGIR DE LOS COMBOS EN LA PANTALLA DE AGREGAR PRODUCTO.
LOS MISMOS IMPUESTOS QUE HOY SOPORTAMOS EN WEB.
QUE SOPORTE HASTA 3 IMPUESTOS ENTRE LOS ESTÁNDARES Y LOCALES.

**Comment by jccastillo0007** [comment]
Done.

Release 9.1.1, te mande la liga por email.

**Comment by RigoFlores** [comment]
soporta un solo impuesto, lo ideal es que las 3 posibles opciones pudieran aprovecharse para varios impuestos locales
