### ISSUE TITLE
AGREGAR FILTRO DE STATUS EN PANTALLA DE CONSULTAS - WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#307]

**Comment by jccastillo0007** [comment]
Done... checar con Fco si hay algún error.

**Comment by RigoFlores** [comment]
NO TENGO FORMA DE VALIDARLO EN PRUEBAS, YA QUE NO SE CANCELA... ALGUNA SUGERENCIA?
