### ISSUE TITLE
Entregar Acuse de Cancelación al cliente - FactureHoy

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#309]
Muy alta prioridad... hay que resolverlo de alguna manera

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Es decir si estaba de nuestro lado?.
Ahora, eso mismo se podría implementar para escritorio, sin meterle mano al código??? o que pasaría ahora mismo???

**Comment by RigoFlores** [comment]
Ok, para web ya se recupera el acuse, en 2 pasos, pero para el segundo paso se requiere 'cancelar' nuevamente... no sería mejor recuperarlo (después de 2 horas, o el tiempo que se ocupe), con el botón de acuse???

**Comment by RigoFlores** [comment]
La última prueba que hice, no jaló... es decir, indicó que si se había enviado a cancelar, que recuperara en 2 horas... y después de días no se había cancelado realmente... aún creo que hay un issue en la cancelación... mi prueba fue en web
