### ISSUE TITLE
CATALOGO DE PRODUCTOS - NO PERMITE CAPTURAR DATOS EXTRAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#31]
NO PERMITE CAPTURAR LOS DATOS EXTRAS, NI LA ADUANA.
ESTÁN INHABILITADOS.
YA SE SOLICITÓ QUITAR ADUANAS DE ESTA PANTALLA.

**Comment by jccastillo0007** [comment]
EL problema de edición esta resuelto.

El catalogo de aduanas, se encuentra en el item 30.

**Comment by RigoFlores** [comment]
VALIDADO OK
