### ISSUE TITLE
Identificar y corregir Issue de facturas duplicadas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#310]
Este año ya se presentó la condición. Se envió evidencia por correo el pasado 14 de enero, aunque supuestamente el pasado 29 de diciembre se le había colocado un candado.ESTE ISSUE ES SUPER IMPORTANTE, ESTAMOS GENERANDO FACTURAS QUE NI NOSOTROS MISMOS SABEMOS QUE EXISTEN... NOS PUEDEN DEMANDAR.... está muy cabrón este pedo...

**Comment by jccastillo0007** [comment]
misma explicación del ticket 313

**Comment by RigoFlores** [comment]
No es el mismo escenario del ticket 313.
Aquí el cliente si ve sus facturas en consultas, es decir tiene acceso al XML y al PDF, sin embargo en el servidor cada una de estas facturas que se presenta en pantalla, se timbró 2 veces.
De este doble timbrado, ni el cliente ni nosotros nos enteramos.  (LAMENTABLEMENTE EL SAT SI SE ENTERA, Y EN CASO DE UNA AUDITORÍA, SE VAN CONTRA NOSOTROS SEGURAMENTE)... es por ello que este pedo es super delicado k....
NECESITAMOS IDENTIFICAR SUPER CLARAMENTE, CUÁNTOS CASOS TENEMOS DE ESTE ISSUE.

**Comment by jccastillo0007** [comment]
Ese fue el issue identificado, se timbraba con facture hoy y luego con
finkok... ya esta corregido

Saludos.
JC.

2015-01-20 10:54 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Ok, este es el que me indicaste en 29 dic pasado que habías puesto un candado, y luego el 14 de enero se presentó nuevamente. Después del 14 de enero se hizo algo para corregirlo? Si es así, solo confírmame, pero me suena como que no...

**Comment by jccastillo0007** [comment]
Osea tuvimos problemas el dia 8 de enero y luego el 14 de enero otra vez ?

JC

Saludos.
JC.

2015-01-20 18:43 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
No, el problema se volvió a presentar el día 08 de enero, pero el cliente lo reportó el día 14 de enero. Aquí necesito conocer el comando para revisar si no tenemos otros casos...
