### ISSUE TITLE
Recepción de CFDI's - GESTION

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#312]
Ahora mismo tenemos varios mecanismos para recibir y validar una factura:
a) Desde las pantallas web de Compras-Verificar CFDI
b) Con el inbox CFDI 
c) Conectándonos directamente al SAT (desarrollo inconcluso ahora mismo).

Hay que resolver varios Issues:
a) No duplicar facturas en la BD de compras
b) En caso de recibir facturas del mismo emisor, actualizarlos en BD de los datos de proveedores
c) Cuando no se encuentre en el SAT, subirla a la BD indicando su status no encontrado en SAT, o Cancelado o Vigente.
d) agregar los filtros estándares de consulta, descarga, etc.
e) permitir subir el PDF correspondiente. En el caso de Inbox, se puede recibir por correo dicho archivo y subirlo para poder ser consultado y descargado.

Este requerimiento va totalmente de la mano con la contabilidad electrónica, ya que los CFDI's tanto emitidos como recibidos, son insumos para las pólizas (el tema macabrón de la CE)

**Comment by jccastillo0007** [comment]
Done and duplicated, I guess.

**Comment by RigoFlores** [comment]
Que pasó con la prueba de generar una factura calientita para la tía? Tengo que revisar como se comporta cuando no se encuentra en el SAT registrada.

**Comment by jccastillo0007** [comment]
No he podido generarla... en las noches me he enfocado a otras cosas...
puedes probarlo tu ?

Saludos.
JC.

2015-03-10 17:48 GMT-06:00 RigoFlores notifications@github.com:
