### ISSUE TITLE
Addenda Mabe Web desde pantalla de Facturación - agrega SINSERIE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#314]
Dentro de la estructura de la addenda, en la parte de folio, le coloca lo siguiente (SINSERIE) cuando no existe serie definida:

xmlns:mabe="http://recepcionfe.mabempresa.com/cfd/addenda/v1" fecha="2015-01-19" folio="SIN SERIE72" ordenCompra="12345"

**Comment by jccastillo0007** [comment]
Fixed.
