### ISSUE TITLE
Homologar comportamiento de Carta Porte para Web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#315]
Falta que envíe la como dato extra pro 1, cuando capturen la siguiente leyenda como primer renglón de la información complementaria:

[PESO/VOLUMEN]=2.5 TONS

En el ejemplo anterior, lo que se envía como dato extra pro 1, es "2.5 TONS". Solo aplica para el primer renglón de la información complementaria.

**Comment by jccastillo0007** [comment]
En web eso no aplica, ese ajuste chacarron fué en standalone porque no teniamos datos extras a nivel producto, en web si se cuenta con dicha funcionalidad, mas bien hay que implementarlo en ese sentido, pero esa es otra historia y otro ticket .

**Comment by RigoFlores** [comment]
No me ames, esto deberías haberlo comentado desde hace años k... varios clientes se quedaron esperando este fix.... tan simple como capturarlo en los datos extra... chiaaaaaaaaa......!!!!!
