### ISSUE TITLE
Implementar el Catálogo de Métodos de Pago, en la factura electrónica

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#316]
Para la contabilidad electrónica el SAT publicó un catálogo de métodos de pago. Creo que ese sería el super oficial para escritorio y web, que no?
OJO, en escritorio pueden teclear directamente 'encima de la lista desplegada de métodos de pago'
En web aún pendiente esa función.

Pero el requerimiento, es partir de ese catálogo para ir empatando las facturas, con la conta electrónica

**Comment by jccastillo0007** [comment]
De donde puedo obtener ese catálogo ?

Saludos.
JC.

**Comment by RigoFlores** [comment]
está en el dropbox, anexo 24 (que es la biblia para la ce)...

**Comment by RigoFlores** [comment]
Este catálogo NO OCUPA PANTALLAS. Es un catálogo en BD.
Lo único que se pide es que puedan teclear alguna opción distinta, así como en escritorio.
Este catálogo en las pantallas será un combo desplegable.

**Comment by jccastillo0007** [comment]
En web no es posible teclear una opción diferente a las que muestra el combo...  o mas que no sea  posible, nos puede llevar tiempo averiguar como hacerlo...

Podemos agregar las opciones default que publicó el SAT,

**Comment by RigoFlores** [comment]
OK, vamos a resolverlo así... el catálogo del SAT incluye la clave 99, que corresponde a otros, entonces agreguemos al catálogo lo siguiente:

Transferencia Electronica
Transferencia Electronica de Fondos
En Especie

y se los asociamos a la clave 99  .

Ojo todo esto debe ser una tabla con claves y Conceptos, para que cuando cambie o queramos eliminar este parche lo podamos quitar.

**Comment by jccastillo0007** [comment]
Para que es la clave, hoy en dia se usa solo el concepto y se manda al XML... la clave se utiliza para algo mas... porque si es asi el cambió es mucho mas complicado ya que hay que guardar por cada factura no solo el concepto si no la clave....

**Comment by RigoFlores** [comment]
La clave se utilizará en las pólizas de contabilidad.
Para propósitos de la factura, lo que solicito es que precisamente esa descripción del catálogo, sea la que se despliegue en el combo. 
Para temas de estandarizar conceptos.

**Comment by jccastillo0007** [comment]
Ya esta en PRU.

**Comment by RigoFlores** [comment]
Pues tal como lo solicité en su momento, con base a experiencias pasadas, ya brincó un cliente... que si no se indica como estaba anteriormente no le pagan, esto es:
- NO IDENTIFICADO (CLAVE 98)
- TARJETA DE DEBITO  (CLAVE 07; ESTE ES UNA CLARA OMISIÓN DEL SAT, QUE \* EVENTUALMENTE ANEXARAN SEGURAMENTE LA OPCIÓN)
- TRANSFERENCIA ELECTRONICA DE FONDOS (CLAVE 03)
- TRANSFERENCIA ELECTRONICA  (CLAVE 03)

este es un proceso de implantación, que lo podemos mantener durante este año únicamente... tal cual lo pedí, pero no me escuchas..

**Comment by jccastillo0007** [comment]
Puros caprichos

O somos compatibles con el SAT o con los clientes

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
Realmente no creo que sean caprichos. El cliente nos indica que si no lo menciona así, su cliente no le pagará y para propósitos prácticos no le serviría nuestra aplicación.
Ahora no estamos rompiendo nada con el sat, ya que le asignamos claves correctas.
Finalmente este proceso de implantación del catálogo, debe ser paulatino, tal como lo comenté cuando lo solicité.
Simplemente es dar mayor flexibilidad a los clientes, y por otro lado, no romper claves del sat. Yo hablé hoy con el sat, y de alguna manera aceptó que le falta al menos la clave para tarjeta de débito, y me pidió que ingrese mi sugerencia con un procedimiento mas o menos complejo..

**Comment by jccastillo0007** [comment]
Done...
