### ISSUE TITLE
Implementar el catálogo de monedas en la facturación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#317]
El sat publicó un catálogo de monedas para la conta electrónica.
Ahí viene por ejemplo 'MXN', como  'Peso mexicano'   (código y moneda respectivamente).
Para ir homologando con la facturación, quizás vale la pena agregarlo a nuestro catálogo actual. 

Sería elegir el código correspondiente, que tendría precargado dicho código y la moneda, nosotros mantendríamos el 'alias', o 'descripción', que se iría al PDF.

Estos 2 issues, le daría al cliente un 'feel', de conta electrónica en la facturación... 'oye, que porque cambiaron... ah, es que así lo define el sat para la ce'...

**Comment by RigoFlores** [comment]
Igualmente se trata de un catálogo en BD.
En las pantallas se invoca como un combo.

**Comment by jccastillo0007** [comment]
Ya esta en Pru

**Comment by RigoFlores** [comment]
En el catálogo, falta un campo, que es la moneda que se envía al PDF.
Por ejemplo ahora mismo se tiene:
MXN - PESO MEXICANO.

Por lo regular en cantidad con letra, se ocupa PESOS. Con lo que yo considero que falta ese campo en la pantalla del catálogo. En el PDF incluiríamos también algo así como moneda MXN-PESO MEXICANO
Como la bestia?

**Comment by jccastillo0007** [comment]
No me suena adecuado... ya que son muchas monedas y ni siquiera se usan
todas... agregar esa columna es agregar mas información a la base de datos
que no será usada... incluso, yo creo que deberíamos de quitar las monedas
que no se usan y que no se van a usar... estamos guardando información de
más.

Saludos.
JC.

2015-02-23 11:12 GMT-06:00 RigoFlores notifications@github.com:
