### ISSUE TITLE
Compras - recibir facturas por correo (falta el PDF)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#318]
Falta subir el PDF a la pantalla de consultas, en la sección de compras, es decir las facturas que NUESTROS clientes reciben.

**Comment by jccastillo0007** [comment]
Ya esta en Pru

**Comment by RigoFlores** [comment]
Lo validé en pruebas, y si lo recibió. Solo que no muestra el PDF. No se si lo recibió y no lo muestra, o simplemente no lo recibió ni lo muestra.

**Comment by jccastillo0007** [comment]
Fixed.
