### ISSUE TITLE
HOMOLOGAR EDICIÓN DE CATÁLOGOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#32]
AL PRESENTAR LA PANTALLA DEL CATÁLOGO, SOLO SE HABILITA EL BOTÓN DE AGREGAR (YA QUE NO SE HA SELECCIONADO NINGUNO).

SI SE ELIGE UN REGISTRO YA EXISTENTE, ENTONCES SE HABILITA TAMBIÉN EL BOTÓN DE EDITAR Y ELIMINAR.

LOS BOTONES TIENEN QUE MOSTRARSE ALINEADOS.

**Comment by RigoFlores** [comment]
CUANDO ESTÁS CAPTURANDO, DESPUÉS DE DARLE EL BOTÓN DE AGREGAR EN EL CATÁLOGO, SOLO DEBE HABILITAR EL BOTÓN DE GUARDAR O CANCELAR.
AHORA MISMO PRESENTA AGREGAR, ELIMINAR, GUARDAR Y CANCELAR-

**Comment by jccastillo0007** [comment]
La alineación de los botones, tiene que ver con el tama;o de los iconos utilizados... los actuales se pusieron temporalmente hasta que se definan los nuestros.

El resto de comentarios se encuentran en work in progress.

**Comment by RigoFlores** [comment]
OK, ENTERADO

**Comment by RigoFlores** [comment]
Sigue pendiente esta corrección, ya que no está mostrando los mismos botones bajo las mismas condiciones, en los distintos catálogos.

**Comment by jccastillo0007** [comment]
done
