### ISSUE TITLE
Investigar porque podría salirse desde la pantalla de agregar producto a la pantalla inicial

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#324]
Podemos partir del archivo de texto que te envié?

**Comment by jccastillo0007** [comment]
Francisco, puedes tratar de reproducirlo... el log no dice mucho... y si no es facil reproducirlo, no será fácil arreglarlo.

**Comment by jccastillo0007** [comment]
Supongo que este issue ya no se ha visto desde hace un buen.

**Comment by RigoFlores** [comment]
Se le dio la vuelta, indicando al cliente que una vez que cambia el precio en la pantalla de agregar producto, en lugar de irse a guardar, le diera tabulador.... con ello 'se resolvió', ya que por software ese problema debe persistir...
