### ISSUE TITLE
Desarrollar Addenda IMSS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#327]
Hoy te entrego el mapeo.

**Comment by jccastillo0007** [comment]
Listo.. ya se encuentra en pruebas para que lo cheques... con la cuenta de la TIA, generé la factura # 75 con la addenda imss,  ahi en esa cuenta de la TIA esta el archivo de configuración de datos extras que hay que usar.

Para el caso de las series y recepciones que pueden ser muchas, se agregó este formato 

```
    <field>
        <tag>recepciones_3</tag>
        <name>recepciones_3</name>
        <type>STRING</type>
        <length>20</length>
        <value>recepciones3</value>
    </field>
    <field>
        <tag>series_3</tag>
        <name>series_3</name>
        <type>STRING</type>
        <length>20</length>
        <value>serie3</value>
    </field>
```

En el campo <tag> se debe respetar el nombre de "recepciones_x" y "series_x" ... pueden agregar cuantas iteraciones necesiten... y no importa el orden

**Comment by RigoFlores** [comment]
No incluye la información de descripción del producto o servicio en la sección de Artículos.
También algo está chueco en el tema de series y recepciones, porque lo coloca así:
            <Recepciones>
                <Recepcion recepcion="recepciones3">
                    <Serie serieRecepcion="serie3"/>
                </Recepcion>
                <Recepcion recepcion="recepciones2"/>
                <Recepcion recepcion="recepciones1">
                    <Serie serieRecepcion="serie1"/>
                </Recepcion>
                <Recepcion>
                    <Serie serieRecepcion="serie4"/>
                </Recepcion>
            </Recepciones>

**Comment by RigoFlores** [comment]
```
        <Recepciones>
            <Recepcion recepcion="recepciones3">
                <Serie serieRecepcion="serie3"/>
            </Recepcion>
            <Recepcion recepcion="recepciones2"/>
            <Recepcion recepcion="recepciones1">
                <Serie serieRecepcion="serie1"/>
            </Recepcion>
            <Recepcion>
                <Serie serieRecepcion="serie4"/>
            </Recepcion>
        </Recepciones>
```

**Comment by jccastillo0007** [comment]
El nodo de recepciones esta bien... si checas cada recepcion_x corresponde
a su serie_x, tambien puede haber recepciones sin serie y viceversa, no
conozco la regla de negocio detras de este nodo, pero cualquier que sea la
combinación que necesiten, si funciona.

Checo lo de la descripción.

Saludos.
JC.

**Comment by jccastillo0007** [comment]
Esto continua ? o ya esta arreglado.

**Comment by RigoFlores** [comment]
SI NO SE HA REPORTADO COMO CORREGIDO, SEGURO SIGUE... DIGAMOS, NO SE ARREGLA SOLITO, QUE SI?

**Comment by RigoFlores** [comment]
no lo he vuelto a checar, esperando la notificación de corrección ..

**Comment by jccastillo0007** [comment]
Es que yo hice una prueba y si se agrego la información del producto... no
se si tu probaste después de que subí los ultimos cambios.

Saludos.
JC.

**Comment by RigoFlores** [comment]
Busqué la factura 75 con la cuenta de la TIA en web, y no tiene la addenda, a menos que hayas trabajado el addendador...
Estoy retomando este tema, pero si no se ha modificado nada al respecto, no veo porque tendria que jalar, pero como quiera lo quiero revisar... ya que tenemos esta entrega pendiente...
