### ISSUE TITLE
Top 10 requirements.

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#328]
![screen shot 2015-02-19 at 10 21 02 pm](https://cloud.githubusercontent.com/assets/2245679/6281390/191bbf28-b886-11e4-955f-91ff53df3c1b.png)

**Comment by RigoFlores** [comment]
que tengo que hacer?

**Comment by jccastillo0007** [comment]
Por ahora nada... solo quiero tenerlo en GITHUB porque si no se me pierde en el correo... o en docs...

**Comment by jccastillo0007** [comment]
A)     CANCELACION CFDI NO HA QUEDADO, ONQUE SE REPORTÓ QUE SI HACE TIEMPO, Y POCO DESPUÉS SE REPORTÓ QUE NO, PUES NO QUEDA
DONE   -                            ESPEJEAR PRODUCCIÓN EN PRUEBAS, PARA HACER VARIAS VALIDACIONES (CATÁLOGOS DE NOMINA, MULTIEMISOR)
DONE   -                             CONFIGURAR LA CUENTA DE MULTIEMISOR EN PRUEBAS DESPUÉS DE LA ESPEJEADA
D)     AGREGAR EL CORREO DE NOTIFICACIONES Y EL DISTRIBUIDOR, A LA PANTALLA DE CLIENTES DEL KEYGENERATOR…
E)      LOS DETALLES QUE PLATICAMOS DE LA NUEVA APLICACIÓN
F)      AGREGAR MONEDA Y TIPO DE CAMBIO EN EL REPORTE DE FACTURACIÓN… (PARA EL CASO QUE EXISTAN FACTURAS DE VARIAS DIVISAS).

**Comment by jccastillo0007** [comment]
A) CANCELACION CFDI NO HA QUEDADO, ONQUE SE REPORTÓ QUE SI HACE TIEMPO, Y POCO DESPUÉS SE REPORTÓ QUE NO, PUES NO QUEDA

DONE - ESPEJEAR PRODUCCIÓN EN PRUEBAS, PARA HACER VARIAS VALIDACIONES (CATÁLOGOS DE NOMINA, MULTIEMISOR)

DONE - CONFIGURAR LA CUENTA DE MULTIEMISOR EN PRUEBAS DESPUÉS DE LA ESPEJEADA

DONE  -  AGREGAR EL CORREO DE NOTIFICACIONES Y EL DISTRIBUIDOR, A LA PANTALLA DE CLIENTES DEL KEYGENERATOR…

E) LOS DETALLES QUE PLATICAMOS DE LA NUEVA APLICACIÓN
F) AGREGAR MONEDA Y TIPO DE CAMBIO EN EL REPORTE DE FACTURACIÓN… (PARA EL CASO QUE EXISTAN FACTURAS DE VARIAS DIVISAS).

**Comment by RigoFlores** [comment]
![topten](https://cloud.githubusercontent.com/assets/2912775/6956390/b95c8adc-d8aa-11e4-9362-74eb35505bf0.png)

**Comment by jccastillo0007** [comment]
Con respecto a la C.E. debo saber que clientes la van a usar, para activarles el Plugin.

**Comment by jccastillo0007** [comment]
Deprecated..... 

Creo que no sirvió de mucho este ticket... hay que hacer otra lista.
