### ISSUE TITLE
PERMITE REGISTROS DUPLICADOS EN IMPUESTOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#33]
LA LLAVE PARA IMPUESTOS ES TIPO + NOMBRE + TASA.
EN ESTE MOMENTO PERMITE REPETIR REGISTRO CON LOS MISMOS 3 DATOS ARRIBA MENCIONADOS

**Comment by jccastillo0007** [comment]
Fixed
