### ISSUE TITLE
Ordenar por número de cuenta en pantalla

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#330]
Siempre se debe ver el catálogo de menor a mayor... ya sea por número de cuenta o código agrupador, sería lo mismo.
También en el XML para poder revisarlo apropiadamente

**Comment by jccastillo0007** [comment]
Fixed,, ese issue creo que esta duplicado.

**Comment by RigoFlores** [comment]
chiaaaaa... si ya estaba resuelto... va patrás...

**Comment by RigoFlores** [comment]
TAMPOCO EN EL XML LO ORDENA.. ME SUENA A UNA VERSIÓN ANTERIOR, CON TODO Y TOOOODOS SUS DEFECTOS QUE TRAÍA ANTES

**Comment by jccastillo0007** [comment]
Lo hice aldrede... estoy haciendo pruebas para ver donde es el lugar
adecuado para ordenarlo...

Saludos.
JC.

**Comment by jccastillo0007** [comment]
Fixed.... ojo... el ordenamiento no es retroactivo... si agregan activos y luego pasivos y luego otra vez activos, no necesariamente es van a ver todos ordenados.

**Comment by RigoFlores** [comment]
2 cosas.... 
antes si lo hacía así....
y la otra y mas importante... ES ESTRICTAMENTE NECESARIO...

**Comment by jccastillo0007** [comment]
Creo que ya quedo.

**Comment by RigoFlores** [comment]
Cuando agregar una cuenta que debería estar 'enmedio', lo pone hasta el final.
Luego si salvas, lo mantiene hasta el final
Luego si te cambias de menú y regresas, ya lo muestra acomodado.
No se puede hacer que regresando de agregar la cuenta, reacomode todo??  Según yo así estaba antes...

**Comment by RigoFlores** [comment]
por lo pronto así lo dejamos
