### ISSUE TITLE
La edición de una cuenta, duplica el registro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#331]
No funciona bien la edición de un registro ya existente en el catálogo. Al darle guardar duplica el registro.

**Comment by jccastillo0007** [comment]
Esto es en la pantalla de balanza cierto ?

**Comment by RigoFlores** [comment]
En la pantalla de catálogo de cuentas, al editar una que ya aparece la duplica.
Eso lo platicamos el sábado pasado.

**Comment by RigoFlores** [comment]
por lo pronto, lo quitamos para que no estorbe
