### ISSUE TITLE
Catálogo de Cuentas - El número de cuenta es incorrecto para nivel 2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#332]
Para cuentas de nivel 2, el número de cuenta es el mismo código agrupador, y el número de subcuenta es la cuenta correspondiente de nivel 1, es decir la de mayor.

Solo en el caso de cuentas de nivel 3, (las personalizadas, por ejemplo banco inbursa y bancomer), su número de cuenta es el código agrupador mas el .001, .002, etc. En este caso la subcuenta asociada es el código agrupador del nivel 2.

aplica para pantalla y XML

**Comment by jccastillo0007** [comment]
Fixed.
