### ISSUE TITLE
Dar opción para crear catálogo Cuentas del SAT completo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#333]
Ofrecer la opción de crear el catálogo de cuentas del SAT completo.
Es decir con todas las cuentas del nivel 2. Sin cuentas del nivel 3.

Esto es para evitar la captura normal o estándar, que puede tomar horas del un catálogo real... la siguiente semana ya se tiene que presentar el primer reporte de catálogo y balanza....

**Comment by jccastillo0007** [comment]
Work in progress...

Ya muestra niveles 1 y 2... falta agregar nivel(s) 0

**Comment by jccastillo0007** [comment]
Por ahi hay un detallito mínimo.... que igual ni se dan cuenta y además no pegaría en el xml

**Comment by RigoFlores** [comment]
Por ahí si lo generó completo, pero las cuentas que no tienen naturaleza en la BD, las deja vacías. Tal como lo platicamos, esas cuentas quedarán fuera del catálogo del SAT, para que ellos lo asignen manualmente

**Comment by jccastillo0007** [comment]
Done.
