### ISSUE TITLE
En el catálogo de cuentas no se puede agregar la naturaleza para las cuentas que no lo incluyen

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#336]
Algunas cuentas no tienen la naturaleza definida por el SAT, por lo que es decisión del contador definirla. La pantalla debe permitir capturar la naturaleza cuando no se incluya en la BD de la aplicación.

**Comment by jccastillo0007** [comment]
Done.

Se agrego una caja de texto, se activar[a siempre que no exista naturaleza en el catalogo

**Comment by RigoFlores** [comment]
Esto que había quedado muy bien, ya le movieron algo y ahora ya no jala del todo.
Cuando intentas agregar una cuenta que no tiene naturaleza en la BD, no habilita el campo para capturar.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
No, ahora no permite guardar. Marca naturaleza incorrecta.
Según yo, este defecto también ya se había levantado al inicio de todo esto....

**Comment by jccastillo0007** [comment]
Fixed.
