### ISSUE TITLE
Generar archivo XML y ZIP con nomenclatura requerida para el catálgo de cuentas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#337]
LA NOMENCLATURA CORRECTA ES:

RFC + Ejercicio + Periodo + Clave + Extensión
EJEMPLO
TIA101020BP4201501CT.zip

CT CORRESPONDE A CATÁLOGO DE CUENTAS

**Comment by jccastillo0007** [comment]
Done.

Solo me falta crear el ZIP.

**Comment by RigoFlores** [comment]
OK, QUEDA PENDIENTE LO DEL ZIP

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
acabo de generar un catálogo de cuentas en pruebas y ya le cambió el nombre, no cumple con lo aquí señalado.
Ese control de versiones me pone a temblar cada vez que veo algo así.
Capaz que tiene que ver con lo de las adddendas...

**Comment by jccastillo0007** [comment]
Jajaja yo diría mas bien el control de pruebas.... si te refieres a las iniciales de AC en lugar de CT, resulta que desde hace un buen ha estado asi, y hasta ahora lo reportas....  

Ya lo cambié a CT y esta listo en PRU.

Ahora si no te refieres al acrónimo, entonces cuál es el error ? ya que tu comentario anterior no menciona claramente cual es el error.

**Comment by RigoFlores** [comment]
Si, el error es que debe ser CT, tal como se menciona al inicio de este issue.
Yo validé en su momento el XML con el validador del SAT, y pasó sin problemas.
ESTOY SEGURO QUE ESTO ANTERIORMENTE JALABA BIEN. Si se regresó en algún momento, ahí si no lo sé, ya que no volví a revisar hasta ayer... y eso porque se publicó un nuevo ANEXO 24, pero no le hallé las diferencias... :(
