### ISSUE TITLE
Genera Catálogo de Cuentas, aún sin incluir naturaleza en algunas cuentas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#338]
Este atributo es requerido

**Comment by jccastillo0007** [comment]
Fixed.

Hay que volver a capturar las cuentas que no tienen naturaleza, para que se pueda validar.

**Comment by RigoFlores** [comment]
Excelente, cuando tiene definido en BD no permite cambiarlo, y cuando no lo tiene le permite capturarlo. Elegante y simple
