### ISSUE TITLE
INCONSISTENCIA ENTRE LA BD Y LAS FACTURAS GENERADAS OK

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#34]
AL MOMENTO DE CONSULTAR, ME APARECE LA SIGUIENTE PANTALLA, LO CUAL ME INDICA QUE NO COINCIDE EL NÚMERO DE REGISTROS EN LA BD, CON LAS FACTURAS GENERADAS EFECTIVAMENTE

**Comment by RigoFlores** [comment]
CREO QUE PARTE DEL MOTIVO, ES QUE NO BORRA LA PANTALLA DESPUÉS QUE FACTURAS, Y ENTONCES LE PUDES DAR FACTURAR NUEVAMENTE CON LOS MISMOS DATOS

**Comment by jccastillo0007** [comment]
La consulta es correcta, esta mostrando justo lo que tiene la base de datos, y de hecho la cantidad de folios utilizados tambien coincide.

mysql> select id, sourceRFC, targetRFC, folio, serie from CFD where sourceRFC = 'FOPR681125BQ0';
+----+---------------+---------------+-------+-------+
| id | sourceRFC     | targetRFC     | folio | serie |
+----+---------------+---------------+-------+-------+
| 10 | FOPR681125BQ0 | TIA101020BP4  |     4 | ABC   |
| 11 | FOPR681125BQ0 | TIA101020BP4  |     3 | A     |
| 12 | FOPR681125BQ0 | TIA101020BP4  |     1 | A     |
| 13 | FOPR681125BQ0 | TIA101020BP4  |     6 | A     |
| 14 | FOPR681125BQ0 | TIA101020BP4  |     7 | A     |
| 15 | FOPR681125BQ0 | XEXX010101000 |     8 | A     |
| 16 | FOPR681125BQ0 | TIA101020BP4  |     9 | A     |
| 17 | FOPR681125BQ0 | TIA101020BP4  |    10 | A     |
| 18 | FOPR681125BQ0 | TIA101020BP4  |    11 | A     |
| 19 | FOPR681125BQ0 | XEXX010101000 |    12 | A     |
| 20 | FOPR681125BQ0 | TIA101020BP4  |    13 | A     |
| 21 | FOPR681125BQ0 | TIA101020BP4  |    14 | A     |
| 22 | FOPR681125BQ0 | AOSG790804KE3 |    16 | A     |
+----+---------------+---------------+-------+-------+
13 rows in set (0.00 sec)

Probablemente no estoy entendiendo el error.

**Comment by RigoFlores** [comment]
al parecer no se entendió el error.
El asunto es que ese listado que presenta en la consulta, no corresponde 1 a 1, con los PDF's y XML's.
Caso concreto los folios 7A y 11A, no cuentan con PDF y XML correspondiente.
Según yo no se generaron, pero este comportamiento es resultado que no muestra ningún indicador respecto a que está procesando la petición, y entonces el usuario (o sea yo), le vuelve a dar click en facturar (como consecuencia a su vez, que no inhibe los botones de esa pantalla).

**Comment by jccastillo0007** [comment]
Si, efectivamente es por el tema de que la pantalla queda abierta.

Puedes cerrar este defecto, ya que tenemos especificado el 38.

**Comment by RigoFlores** [comment]
OK, LE DAMOS SEGUIMIENTO EN LA FALLA #38
