### ISSUE TITLE
Balanza - la edición es un caos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#340]
Se mueve cuando estás capturando, como que toma sus propias decisiones...es un caos

**Comment by jccastillo0007** [comment]
Fixed. Hay revisarlo y validarlo con Francisco.

Esta disponible en el amb de pruebas.

**Comment by RigoFlores** [comment]
No, siguió con problemas... se brinca el cursor sin mas ni mas... dice fco que ya lo corrigió, pero hasta no ver, no creer...
