### ISSUE TITLE
Edición de Balanza - Permitir modificar la captura de cualquier mes en particular

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#347]
Ahora mismo no permite modificar la balanza capturada previamente para algún mes en específico.
Existe lo que se llama Balanza Normal y Balanza Complementaria.
La complementaria se envía cuando existe la necesidad de corregir la balanza normal, para el mismo mes en cuestión.
De aquí que la edición de una balanza normal, debe 
a) mostrar los valores previamente capturados para ese mes en particular, para su modificación
b) debe mostrar todas aquellas cuentas que no contengan datos capturados respecto al último catálogo de cuentas existente en la BD.

**Comment by jccastillo0007** [comment]
Fixed.

Si se aumentaron las cuentas,  si funciona... es decir, muestra las ya capturadas, mas las nuevas... peeeeroo

Pregunta... que pasa si eliminan cuentas ?

**Comment by RigoFlores** [comment]
Debe mantener las cuentas ya capturadas en la balanza...
