### ISSUE TITLE
NO COLOCA EL IVA POR OMISIÓN, AL AGREGAR PRODUCTO EN LA PANTALLA DE FACTURAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#35]
PARA APUNTAR A LA MISMA SIMPLICIDAD Y MENOS PASOS AL MOMENTO DE GENERAR FACTURA, SE REQUIERE:
A) QUE EL IVA LO ASIGNE POR OMISIÓN
B) QUE EL MÉTODO DE PAGO, SEA NO IDENTIFICADO Y EL NUMERO DE CUENTA, NO IDENTIFICADO (YA SE, SE CONTRADICE CON LO ACTUAL, PERO SERÁ MAS SIMPLE EN UN FUTURO)
C) QUE CUANDO TERMINE DE GENERAR LA FACTURA, LA PRESENTE EN PANTALLA PARA PODER IMPRIMIRLA.

**Comment by jccastillo0007** [comment]
a) Ok, complicado por el momento, pero sera un feature que se agregara despues
b) Ok
c) Ok

**Comment by RigoFlores** [comment]
No está atendido ningún punto, correcto?

**Comment by RigoFlores** [comment]
AYER SURGIÓ EL TEMA CON UN CLIENTE EN WEB.
NECESITAMOS ASIGNAR POR OMISIÓN EL PRIMER IVA TRASLADADO, QUE SE HAYA DADO DE ALTA EN LA TABLA CORRESPONDIENTE.
(NUEVAMENTE, EL ESTÁN ALON ES EL ESTADO DEL ARTE, PERO NO LO QUEREMOS VER ASÍ).
