### ISSUE TITLE
Parsear e Incluir el descuento en el XML y PDF, del formato levicom

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#352]
Ya te envié el correo, pero aquí esta nuevamente:

AHORA SE TIENE ESTO:

S|SUBTOTAL | IMPORTE DEL IVA| TOTAL CON IVA|TASA DE IVA|SUBTOTAL| |

HAY QUE AJUSTARLO A:
S|SUBTOTAL | IMPORTE DEL IVA| TOTAL CON IVA|TASA DE IVA|SUBTOTAL| DESCUENTO|

**Comment by jccastillo0007** [comment]
Done.
