### ISSUE TITLE
Agregar 2 impuestos locales

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#353]
0.2% DE LA CAPACITACIÓN DE LA INDUSTRIA DE LA CONSTRUCCION A.C.

0.5% DE LA INSPECCION, VIGILANCIA Y CONTROL PENA CONVENCIONAL

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
HAY QUE LLEVARLO EN CHINGA A PRODUCCIÓN, LO ESPERAN HOY MISMO... PARA QUE HORA LO COMPROMETO..???
