### ISSUE TITLE
Cuando consultas XML en la pantalla de catálogo de cuentas, siempre te muestra el último generado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#355]
El último XML que generé, lo muestra para cualquier XML histórico previamente generado en el catálogo de cuentas

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Quedó todo bien, pero la pregunta que surge, es como identificar el XML que se generó para enviar al SAT???
