### ISSUE TITLE
Catálogo de Cuentas, no pasa el validador del SAT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#357]
Aquí la pantalla...

**Comment by RigoFlores** [comment]
![validadorsat](https://cloud.githubusercontent.com/assets/2912775/6567674/50ba55c0-c691-11e4-915a-47c1bfc2841a.png)

**Comment by RigoFlores** [comment]
Por lo menos reparar este, para mi reunión de mañana miércoles con un cliente, que traerá a su contador... :(

**Comment by jccastillo0007** [comment]
Fixed.
