### ISSUE TITLE
Nombre de Archivo Incorrecto para Balanza

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#359]
Se forma de ( RFC + año + período + BN) .XML, o en lugar de BN puede ser BC, para balanza complementaria. Actualmente tiene BA en lugar de BN.
![nomenclaturabalanza](https://cloud.githubusercontent.com/assets/2912775/6567776/f9b7d9ee-c692-11e4-94b8-104508be9e5b.png)

**Comment by jccastillo0007** [comment]
Fixed.
