### ISSUE TITLE
VISTA PREVIA, COTIZACION Y CUENTAS POR COBRAR, COMO FUNCIONA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#36]
ASÍ, ES COMO FUNCIONAN, SON EXCLUYENTES?

**Comment by jccastillo0007** [comment]
Vista previa y Cotizacion, no se almacenan nada en BD, solo se genera el PDF para que lo puedan revisar y utilizar 

Cuentas por cobrar si se almacenan en BD con un estatus de cuentas por cobrar.... de hecho la puedes consultar posteriormente, y debemos definir que hacer con esa factura posteriormente....

Acabo de notar que el estatus que muestra la consulta esta en ingles, chaaaaa y con terminologia tecnica.

**Comment by RigoFlores** [comment]
Eventualmente tenemos que guardar la cotización, ya que posteriormente se podría convertir en factura.
Para la vista previa, debería existir un botón y no un check box, ya que solamente debe desplegar el PDF en pantalla.
Para cuentas por cobrar, deja trabajar en una spec, ya que pudieron dar anticipo, debemos capturar la fecha programada de pago, notificar dicha fecha al usuario cuando acceda, posiblemente enviar correo recordando al receptor, referencia bancaria de pago, etc.

**Comment by RigoFlores** [comment]
Por cierto, le di click al check box de vista previa, y de ahí.... facturar, ya que no indica ni muestra nada, y se comportó idéntico a generar una factura.
Bajé el PDF y es como vista previa, pero también bajé el XML y lo generó timbrado.
Es decir PDF vista previa, pero XML timbrado. Totalmente chueco...

**Comment by jccastillo0007** [comment]
A chinga neta

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
Si k, lo que se requiere en vista previa es un botón para desplegar la preFactura. Eso es todo.
Básicamente, y nuevamente, mismo comportamiento que tenemos hoy en día con el ftsa (facturat estánalon)...

**Comment by jccastillo0007** [comment]
Hasta el momento no he encontrado la forma de desplegar automaticamente la factura, por eso se permite bajarla....

**Comment by jccastillo0007** [comment]
Si se puede almacenar la cotizacion sin problema, solo habra que definir el proceso para que despues puedan hacerla factura.

**Comment by jccastillo0007** [comment]
ya existe el boton de preview, en lugar del checkbox.

**Comment by RigoFlores** [comment]
OK, cerraré este, pero abriré el tema de cotización y remisión, independiente
