### ISSUE TITLE
No incluye el atributo TipoEnvio en la balanza

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#362]
Se puede poner inicialmente por omisión N, pero este dato lo debe capturar el usuario.

Valor sugerido: N   (Normal)
Otro valor válido: C (complementaria)

**Comment by jccastillo0007** [comment]
Fco, Hay que agregar un combo con las opciones de N (Normal) y C(Complementaria) en la pantalla de balanza, lo puedes poner entre Version y RFC.

Hay que agregar el campo Tipo de  Envio en la clase ClientAccountBalance.

**Comment by jccastillo0007** [comment]
Fixed.
