### ISSUE TITLE
Implementar multirfc en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#364]
Ya me confundí, como quedó finalmente la asignación de folios de los rfc's hijos?
Favor de detallar como queda este punto

**Comment by jccastillo0007** [comment]
-Puedes probar con el RFC de la TIA en pruebas...
-Tiene 3 RFC como emisores.
-Los emisores deben tener configurado el .cer, .key y pwd... 
-Los emisores deben tener serie creada
-En este caso la TIA debe tener la misma serie que fue creada en los emisores
-Cada emisor debe tener folios asignados en el servidor de timbrado
-Siempre si puede cada emisor entrar directo a la app y utilizarla (avisame si esto no se debe poder)
-En consultas, se puede consultar por usuario... para ver que facturas se generaron.

**Comment by RigoFlores** [comment]
Traté de dar de alta usuarios para pruebas, y me marcó error....
