### ISSUE TITLE
Implementar los reportes de 'producción' por usuario

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#365]
Habíamos comentado que agregando el usuario en los filtros o criterios de consulta, se podría generar este reporte, AGREGANDO una columna donde se incluya el usuario en el reporte excel.

**Comment by jccastillo0007** [comment]
Se supone que ya agrega el usuario al reporte, que no?

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
lo acabo de revisar, y efectivamente si lo incluye. Lo raro es que no recuerdo que lo hayas reportado...
Bueno, me surge la pregunta respecto, a que pasa si dan de alta varios usuarios... esos usuarios generan facturas... y de repente borran uno porque se fue de la chamba, le dieron una patada en el culo, o la razón que sea... ahí como se podrían consultar las facturas que ese loser generó?

**Comment by jccastillo0007** [comment]
jajajaja loser....

Una opción es haciendo una consulta de todas las facturas en un periodo...
el usuario va a salir en el reporte de excel.

Saludos.
JC.

2015-03-12 10:36 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Si no colocas el filtro de loser, no te arroja nada la consulta.
En otras palabras, si no eliges el filtro de usuario, no genera ningún resultado

**Comment by jccastillo0007** [comment]
mmm creo que colocaste alguna condición que no arrojaba resultados... porque si entras a la pantalla de consultas y sin seleccionar nada realizas la busqueda, te muestra todo ...

**Comment by RigoFlores** [comment]
la única condición que coloqué, y eso para poder validar la prueba de manera controlada, es la fecha que fue 14 de marzo.
Si le pones ese único filtro te arroja 1 solo registro...
Si le agregas el filtro de usuario democp, te arroja muchos mas resultados..

**Comment by jccastillo0007** [comment]
Si NO eliges un usuario, te arroja las facturas creadas donde el RFC emisor es el RFC del usuario que esta firmado, en este caso la TIA, 

Si eliges un usuario, te arroja las facturas creadas por ese usuario, independientemente si son del emisor que esta firmado, en este caso la TIA.

**Comment by RigoFlores** [comment]
A ver... creo que sigue sin funcionar.
Accedí a pruebas con la cuenta de la tia usuario TIA101020BP4...
En consultas le coloco el filtro de fecha inicial 14 de marzo... le doy consultar y me arroja una factura... si le doy exportar y reviso el excel, me indica que esa única factura la generó el usuario democp
Ahora si mantengo el filtro de fecha, pero le agrego el filtro de usuario democp, entonces ahora el resultado es distinto....me arroja 10 facturas...

Tambien hice una factura el día de hoy, con el usuario TIA101020BP4... si consulto con el filtro fecha inicial 14 marzo, me arroja una factura (que no hizo ese usuario), ahora si le coloco el filtro de usuario TIA101020BP4, entonces si me arroja la factura que recién emití...

total que si es necesario echarle un vistazo....

**Comment by RigoFlores** [comment]
Y algo importante, cuando no colocas el filtro, entonces te debe arrojar el resultado de TODOS LOS USUARIOS, no el del usuario firmado.....

**Comment by jccastillo0007** [comment]
El comportamiento si es consistente...

Solo revisa las facturas cuando te arroja los 10 resultados, veras que son
de diferente source RFC, por eso no salen en la primer consulta.

Y cuando no colocas filtro, te arroja el resultado de TODOS LOS USUARIOS,
siempre y cuando el SOURCE RFC sea el de la TIA.... me parece que algo
falta para hacerlo mas claro ahora que hay funcionalidad de multi emisor,
los resultados son correctos, pero al parecer causan confusión.

JC.

Saludos.
JC.

2015-03-17 12:49 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
OK, si jala como dices, pero también como dices está raro.
Sin filtro alguno (de usuario), te arroja las facturas del emisor 'base', independientemente del usuario, digamos como funciona normalmente.
Al momento de elegir un usuario en el filtro, entonces te arrojará todas las facturas elaboradas por ese usuario, independientemente del emisor.
