### ISSUE TITLE
No permite dar de alta nuevos usuarios en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#366]
Al parecer la parte del multiemisor le pegó a este asunto...
De hecho, hasta marca error...

**Comment by jccastillo0007** [comment]
Fixed.

El problema no fueron los cambios por el tema de multiemisor... el problema es que la base de datos ya se esta batiendo... habia mas de un cliente con el RFC de la TIA, uno que dí de alta yo para hacer pruebas de multiemisor... 

Creo que valdría la pena limpiar la base de datos, pero hay que identificar que es lo que tú necesitas para poder probar toda la funcionalidad de varios clientes.

**Comment by RigoFlores** [comment]
Chiaaaa... pues la TIA siempre ha existido en pruebas, desde el mero principio... no entiendo porque dar de alta ooootro emisor de la TIA...
los Emisores que te pasé, precisamente los tomé de pruebas... validando los que existen desde que importamos toda la BD de producción...
