### ISSUE TITLE
Multiemisor WEB - Consultas - Todas las facturas elaboradas, independiente al usuario

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#367]
Así como platicamos y me comentaste que es factible hacerlo, tenemos que implementar una consulta que por fecha nos arroje todas las facturas emitidas por el emisor BASE y todos sus emisores SATELITES, independientemente de cuál usuario las generó.

Comentamos que una vez que se configura 'el plug in', entonces ahí servirá para hacer una consulta donde el owner sea el RFC BASE.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Cómo lo valido?

**Comment by RigoFlores** [comment]
Validé en pruebas, con el único usuario configurado, y cuando consulto sin darle ningún filtro ni nada, me arroja facturas del año pasado... que pex?

**Comment by jccastillo0007** [comment]
Y eso como porque esta mal ?
Son facturas que le corresponden a ese Emisor / Usuario, que no ?

**Comment by RigoFlores** [comment]
Está mal porque el rfc multiemisor eje es RIVO8506037R0, mismo que no existía el año pasado.
Chequé una que muestra del 24 de noviembre y es emisor tia, receptor xaxx010101000.
Nada que ver con el rfc eje.
Realmente el reporte general que se requiere es de todas las factura emitidas por LOS USUARIOS DADOS DE ALTA EN EL EMISOR EJE. Aquí no importa el rfc emisor.
OJO, ES PROBABLE QUE HOY DIERON DE ALTA AL USUARIO JUAN... EMITIÓ 1000 FACTURAS, Y MAÑANA YA LO DIERON DE BAJA. ENTONCES TIENE QUE APARECER COMO QUIERA LAS FACTURAS EMITIDAS POR JUAN

**Comment by jccastillo0007** [comment]
El detalle es que ese RFC "RIVO8506037R0" tiene un usuario llamado "TIA101020BP4" y la TIA también tiene un usuario llamado asi... tons al final se confunde con los nombres de usuarios que pertenecen a diferentes clientes....

Debo cambiar esa condición de busqueda por algo mas consistente y un candado mejor estructurado... como quiera, si este es el único defecto que encontraste, entonces ya puedes ir liberándolo... cierto ?

**Comment by RigoFlores** [comment]
Ya borré el usuario TIA101020BP4 de esta cuenta multiemisor, y ya no presentó las otras facturas.
Si aún tiene un detallito...abriré otro issue
