### ISSUE TITLE
PERMITE MINÚSCULAS AL CAPTURAR RFC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#37]
PERMITE MINÚSCULAS EN EL CAMPO DEL RFC, CATÁLOGO DE CLIENTES.
DE HECHO CAPTURÉ UNO EN MINUSCULAS, PERO AL MOMENTO DE FACTURAR MARCÓ EL ERROR 105 DEL PAC.
SOLO DEBE PERMITIR MAYUSCULAS, LETRAS O NUMEROS, Y EL '&'.
HASTA EL MOMENTO NO HE DETECTADO NINGUN OTRO CARACTER VÁLIDO DENTRO DEL RFC

**Comment by jccastillo0007** [comment]
Fixed.

Las letras se actualizan a mayusculas,  por el momento no se esta validando si tiene caracteres raros.

**Comment by RigoFlores** [comment]
solo debe aceptar letras, numeros y &, por lo pronto

**Comment by RigoFlores** [comment]
el cliente aún es propenso a capturar guiones o espacios... esto genera un error al timbrado, nos llaman, tenemos que conectarnos a su equipo, investigamos e identificamos el error. Son detalles que al estar implementados, que nos optimizan tiempos, movimientos y $$$, a todos...

**Comment by jccastillo0007** [comment]
Ok, se agregaron validaciones para los espacios y para el "-".

**Comment by RigoFlores** [comment]
lo del '-' al parecer ya quedó, 
pero lo de espacios, sigue aceptando

**Comment by jccastillo0007** [comment]
Fixed
