### ISSUE TITLE
Cancelación - Cuando cancela OK, el mensaje es incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#370]
Una factura que ya tiene un rato de haber sido generada, y la cancelas te indica 
Enviada a Cancelación. Recupere acuse en 2 hrs
Al ver el acuse, ya trae la cadena original.

El tema es identificar la situación y enviar el mensaje adecuado

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Acabo de cancelar una factura del 18 de mayo. Me dijo que reintente en 2 horas, pero ya la canceló y el acuse incluye la cadena. Esto fue en Web... jeje

**Comment by RigoFlores** [comment]
Este es uno de los escenarios que se quedó abierto en su momento, y ya no se actualizó este issue...
