### ISSUE TITLE
Cancelacion todo terreno - no te entrega el acuse de cancelacion

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#371]
Yo no lo puedo reproducir, pero tu me lo comentaste

**Comment by jccastillo0007** [comment]
Mmmmm y como que quieres que haga yo ? 

Voy a escribirle a Giovanna, pero como es su costumbre no responde, de hecho no me peló con el correo de la forma de pago que excede la longitud... tienes que mover tus influenzas con Yessica.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Ya jaló lo de todo terreno?
Yo no tengo forma de probarlo.
Ya cancela de otros pacs y además entrega cadena original???

**Comment by jccastillo0007** [comment]
Ya no existe cancelación todo terreno,Podemos cerrar este ticket ?

**Comment by RigoFlores** [comment]
La cancelación todo terreno, incluso la tuvimos que detener porque estaba provocando varios problemas, principalmente enfocados a que algunas veces cancelaba y el mensaje decía lo contrario. El cliente nunca se enteraba que su factura había sido cancelada.
Entiendo que ahora, el único que cancela es facture hoy, con su super opción de '1 solo paso'. Entonces para facturas timbradas por finkok, hoy NO ES POSIBLE CANCELAR DICHAS FACTURAS, estoy en lo correcto?
En caso afirmativo, podríamos cerrar este issue, debido a que no es soportado, ya que ni siquiera se ocupa, y no tenemos la capacidad de cancelar facturas de finkok y edicom.
Como la beisbol?

**Comment by jccastillo0007** [comment]
La cancelación todo terreno ya no es usada con FactureHoy.

Finkok cancela solo facturas de finkok.

Edicom no cancela <estas serian las facturas que no se podrían cancelar,
pero entiendo que ya no usamos edicom>

Saludos.
JC.

2015-09-29 7:53 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Si entendí bien, solamente estamos cancelando por FactureHoy, y finkok y edicom no aplica la cancelación, correcto??

**Comment by jccastillo0007** [comment]
correcto.
