### ISSUE TITLE
Llevar a producción catálogo de cuentas y balanza

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#372]
Aún sin plugin, tendremos que liberarlo para su posible uso, la siguiente semana.

**Comment by jccastillo0007** [comment]
A caray, si ya está activado el plugin jajajaja... checalo en pruebas con la TIA, es la única que ya tiene el plugin.

**Comment by RigoFlores** [comment]
Es decir ya está en producción, y te tengo que notificar para quién lo activamos?

**Comment by RigoFlores** [comment]
necesitamos activar en pru y pro para MCE960618487  y  GCR031223579
Ahora mismo en pruebas, para la cuenta de la TIA estamos capturando el catálogo de GCR031223579.
Pero necesitamos habilitar la ootra cuenta MCE960618487 para capturar su catálogo. Están bien chonchos k...

**Comment by jccastillo0007** [comment]
Done.
