### ISSUE TITLE
Migración de catálogo de productos y clientes de escritorio a web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#374]
Se hizo un primer intento, pero no quedó bien.
Los caracteres raros de los clientes, pero lo principal es que toooodos los productos (que son muchos), no incluyeron correctamente su unidad, ni la moneda.
Por ello no pudimos liberar hoy. Urge para el lunes

**Comment by jccastillo0007** [comment]
mmmm si revisaste en Producción ? te pregunto porque todos los productos si estan bien migrados... te voy a enviar el resultado del query.

**Comment by RigoFlores** [comment]
Si claro, revisamos en producción.
Lo que pasó, es que no existía la unidad y ramiro se las estaba asignando una por una.
Le dije, no mames, da de alta la unidad como viene en el catálogo y así lo hizo. Consultamos y seguía igual.
Seguro lo que faltó fue salirse y volver a entrar. Ya vi que tienen las unidades.
Ahora solo falta pulir los datos de los clientes, pero también noté algo en los productos, por ejemplo:
INSERT INTO PRODUCT VALUES(280,'TABLA MELINA .75" X 8" X 8.25\u00b4','PESOS',NULL,0,0,'TABMEL8"','IVA',16.0E0,'PIEZAS',38.7931E0)

estoy seguro que \u00b4 es una secuencia de escape, o similar. pero en el catálogo de productos (y supongo que en clientes tambien) aparece literalmente, lo cual nos lleva a editar no solo los clientes, sino muuuchos productos también. que hacemos aquí?

**Comment by jccastillo0007** [comment]
Ya quité la cadena \u00b4

**Comment by RigoFlores** [comment]
Bueno no se trata de prueba y error... todos los caracteres especiales tienen problemas.... lo que te mencioné fue como mero ejemplo...
Yo creo que ya se extendió demasiado este requerimiento, que no?
Que hacemos, ahora hay que revisar uno a uno productos y clientes, o como?

**Comment by jccastillo0007** [comment]
Si, eso fué lo que te pedí desde la semana pasada, que se corrigieran uno
por uno, tampoco son tantos... en un par de horas están listos, lo que yo
corregí fue porque era fácil hacerlo por query, pero todo lo demás es más
fácil a manita....

Saludos.
JC.

2015-04-06 11:09 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Para una migración tipo los cristeros, esto no será posible, por los cientos de clientes que tienen.
En este caso tuvimos que retocar CADA PRODUCTO Y CLIENTE, y así no es funcional la migración.
Por lo pronto lo cierro, pero es inaceptable migraciones donde tengamos que acceder a cada registros, incluso solo para verificar si está bien o le hace falta ajustar.
