### ISSUE TITLE
Multiemisor WEB - Falta agregar el RFC del emisor en las consultas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#375]
Dado que aquí van existir múltiples emisores, es importante en pantalla agregar el RFC emisor.
Para el excel, es importante agregar el rfc y nombre emisor, ya que ahora mismo se desconoce quién emitió la facutura. Solo aparecen los receptores

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
ok, veo que agregaron el filtro, pero no está tomándolo en cuenta para el query.
1) Falta incluir el filtro del emisor al aplicar el query
2) En el listado en pantalla, no se muestra el RFC emisor
3) En el excel YA APARECE EL RFC EMISOR Y RFC RECEPTOR. OK

**Comment by jccastillo0007** [comment]
Listo.

Cualquier detalle, actualiza este ticket, peeeero también comentale a Fco.

**Comment by RigoFlores** [comment]
Insisto, desconozco quién hizo que..
Por cierto, borraste todas las facturas que anteriormente había emitido para estas pruebas?
En consultas, no muestra ningún resultado. Ya no hay facturas emitidas...

**Comment by jccastillo0007** [comment]
Solo tienes que preguntarle, y ya si él sabe te ayudará o te dice que yo lo
hice, manejamos requerimientos muy dinámicos, él trabaja en muchas cosas de
varios requerimientos y yo en otras, normalmente le pongo hacer algo que
pueda avanzar sin mi ayuda o sin blockers.

No borré nada, hice algunos cambios en el query para evitar mezclar
usuarios con el mismo nombre pero de diferente owner, entiendo entonces que
no funcionan las consultas.

Saludos.
JC.

2015-04-15 8:22 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Podemos cerrar este ticket ?

**Comment by RigoFlores** [comment]
Aquí si recuerdo que hay un issue... necesito datos para retomar las pruebas...
Ya le escribí al cliente, a ver que dice... pero si en meses no dió señales de vida... dudo mucho que responda... como quiera mantenemos este ticket, ya para cerrar el tema multiemisor...

**Comment by jccastillo0007** [comment]
Hay que cerrar este ticket.

**Comment by RigoFlores** [comment]
cuando se ocupe retomamos el tema, según yo quedó inconsistente.
El cliente que pidió esto, dió un anticipo y no volvimos a saber de él... hace poco lo escribí, sin recibir respuesta
