### ISSUE TITLE
Multiemisor Consultas - cuando existe el mismo usuario en otra cuenta, muestra facturas que no corresponden

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#376]
Se tiene que 'amarrar' la condición para identificar de manera única al usuario del multiemisor eje, independientemente que exista ese mismo usuario para otro cliente emisor.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by jccastillo0007** [comment]
Podemos cerrar este ticket ?

**Comment by RigoFlores** [comment]
Este cliente que solicitó esta función ya nunca volvió a llamar. Por ello lo dejamos en la congeladora.
Tenemos de 2, o lo contacto nuevamente para ver que pasó (donde es muy probable que ya no ocupe esto, yo ya no exista la necesidad, o ya se murió, o que se yo), o lo cerramos y cuando surja la necesidad retomamos este tema. 
Lo que si me gustaría es dejar documentado como funciona este asunto:
a) Tu tienes que dar de alta el plugin para un rfc eje, según recuerdo
b) Cómo se dan de alta los distintos usuarios, que podrán emitir facturas multiemisor para ese rfc eje? Eso si ya no lo recuerdo.
c) Cómo se dan de alta, los distintos rfc's emisores?
d) Las consultas de este ticket estaban medio mezcladas, no me queda claro si se atendieron toda o nó.
e) Ahora mismo, cuál es el RFC que tenemos configurado para esta función, y cuáles son los usuarios como para retomar el tema?

**Comment by jccastillo0007** [comment]
Este problema fue resuelto.

En la noche te mando el detalle de como funciona.

Saludos.
JC.

2015-09-29 8:01 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Hay que cerrar este issue.

**Comment by RigoFlores** [comment]
Cuando se ocupe, retomamos el tema... según yo quedó inconsistente
