### ISSUE TITLE
No ordena correctamente el catálogo de cuentas en pantalla

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#377]
En el rfc MCE960618487 puedes checar en producción, como el ordenamiento no es consistente. Sobre todo para cuentas de nivel 3.

**Comment by RigoFlores** [comment]
Sigue igual... no lo ordena bien... chécalo con la cuenta de los gasolineros en pruebas

**Comment by jccastillo0007** [comment]
Ya revisé el RFC "GCR031223579", trataré de explicar el comportamiento

anteriormente, el problema era que intercalaba las cuentas entre sus niveles, por ejemplo podía poner dos niveles 0 juntos, sin sus cuentas a nivel 1, 2 y 3, o podía poner dos niveles 2 sin sus cuentas correspondientes de nivel 1 y 3...

El problema descrito ya se corrigió, ahora el problema que me estas diciendo es 

Muestra primero las cuentas con numero de cuenta 156 y luego 153 y luego 151 etc... en lugar de 151, 152, 153, etc... ese orden se define al momento de capturar las cuentas, y el Id es el que define el SAT, si primero capturan las cuentas de ACTIVO A LARGO PLAZO -  EDIFICIO que tiene la numeración 152 y luego capturan la cuenta ACTIVO A LARGO PLAZO - TERRENO que tiene la numeración 151, así aparecerá en pantalla y en el XML, el sistema no puede cambiar ese orden de captura, lo que si debe asegurar es la consistencia de captura.

Todo este choro aplica también para el ticket 379.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
![cuentasdesordenadas](https://cloud.githubusercontent.com/assets/2912775/7301413/2c053d96-e9a8-11e4-918c-c721c3afa591.png)

**Comment by RigoFlores** [comment]
Esta pantalla en pruebas, dice otra cosa.
Según yo se arreglará de manera natural si:
a) homologamos el formato para las cuentas.. por ejemplo en lugar de 100.01 colocar 100.01.000.000.000   (es decir llenar con '0s' todos los posibles campos dentro del formato del nombre)
b) no estoy seguro que cambiando el '.' por un '-', quizás también sirva... ya consumió mucho este issue y nomás no queda, quizás porque el planteamiento actual no permite de ninguna manera ordenarlo...

**Comment by jccastillo0007** [comment]
De que cliente son estas cuentas ?

Saludos.
JC.

2015-04-23 11:04 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Según yo en pruebas no tenemos muchas opciones, básicamente 3 me parece... las 2 de los clientes que tu mismo subiste, y la de la tia.
Respuesta concreta, es la cuenta de la TIA en PRUEBAS...

**Comment by jccastillo0007** [comment]
Fixed.

Haber si ahora si...
