### ISSUE TITLE
Crear opción para exportar el catálogo de cuentas, a excel o PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#378]
Completo, desde los niveles 0...

**Comment by RigoFlores** [comment]
PARA PROPÓSITOS DEL CLIENTE, CREO QUE PODEMOS INCLUIR EN EL EXCEL Y PDF… LAS SIGUIENTES COLUMNAS:

NUMERO DE CUENTA, NOMBRE, NIVEL, SUBCUENTA, CÓDIGO AGRUPADOR, ASIENTO, TIPO

EL REPORTE DEBE CONTENER TOODAS LAS CUENTAS, INCLUYENDO TOOOODAS.
LO MAS IMPORTANTE, ES QUE DEBE ESTAR ORDENADO POR NUMERO DE CUENTA… ES MUY IMPORTANTE.

**Comment by jccastillo0007** [comment]
Done.... checalo en PRU.

**Comment by RigoFlores** [comment]
NO VEO LA OPCIÓN PARA EXPORTARLO.
GENERÉ EL XML DEL CATÁLOGO DE CUENTAS, Y NI ASÍ SE HABILITÓ OPCIÓN ALGUNA...
COMO LE HAGO???

**Comment by jccastillo0007** [comment]
Cuando generas el XML de catálogo de cuentas, te genera un archivo XML, ZIP
Y Excel... lo hace automáticamente cuando genera el XML.

Saludos.
JC.

2015-04-10 8:21 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
No, pues sigo sin poder verlo... en pruebas, con la cuenta de la gasolinera..GCR031223579

**Comment by jccastillo0007** [comment]
Anexo evidencia de uno de los gasolineros.
Lo que no puedo creer, es que no le preguntes a Fco ese detalle tan simple de como obtener ese archivo de excel, y se pierde un día mas.

![screen shot 2015-04-14 at 10 12 36 pm](https://cloud.githubusercontent.com/assets/2245679/7151766/4373754c-e2f5-11e4-91db-bd164b2cde1c.png)

**Comment by RigoFlores** [comment]
ya vi, NO ES LA OPCIÓN cuando generas el XML como dijiste, sino es cuando generas el ZIP del SAT, son cosas muy distintas...
Creo que no deben estar juntos. Quizás necesites revisar el excel, para estar seguro de enviarlo al SAT, o quizás te lo pide el contador para consulta. Definitivamente habría que separar la opción.
Para mí sería un botón adicional en la parte superior, únicamente para generar el excel.

No conozco el alcance que está cubriendo Fco.
Tampoco conozco en que anda en el día a día...
En este caso, a qué le dedicó tiempo?

**Comment by jccastillo0007** [comment]
Fixed.
