### ISSUE TITLE
No calcula correctamente los consecutivos de cuentas nivel 3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#379]
Si por ejemplo diste de alta Bancos Nacionales - Inbursa... le asignará la cuenta 102.01.001.
Si cierras la ventana y agregas todo bien, pero si de repente tienes la necesidad de agregar otro banco nacional, el valor sugerido será nuevamente 102.01.001, en lugar de 102.01.002 que sería lo correcto.
Es decir, no lleva un correcto control de consecutivos de cuentas, independientemente si se abre y cierra n veces la ventana para agregar las cuentas.

**Comment by jccastillo0007** [comment]
Pssss eso no se va a poder corregir... dado que no tenemos la opción de editar... lo recomendable es que organicen las cuentas y capturen las cuentas del mismo tipo al mismo tiempo.

**Comment by RigoFlores** [comment]
No podemos pedirle eso al cliente... los bancos son un ejemplo, pero existen muchos otros ejemplos de cuentas, que se van agregando por la operación de la empresa o crecimiento de la misma.. lo que se ocupa es llevar este control que es SUMAMENTE DELICADO, para evitar duplicidad de cuentas... hay  que encontrar el mecanismo...

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
acabo de checarlo con Fco en pruebas... el ya vió como no genera los números de cuenta de manera correcta...

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
No, quizás no se entiende completamente el escenario.
Yo dí de alta primero 2 bancos nacionales (INBURSA Y BANCOMER), y asignó los número de cuenta correctamente.
Cerré la ventana, salvé, me pasé a otro lado. Luego vuelvo al catálogo de cuentas, y doy de alta un nuevo banco (BANCRECER). Le di agregar y repite el número de cuenta.
En general el tema, es que es fundamental que no repita números de cuenta, y considerar que las cuentas se pueden agregar en cualquier momento.

![cuentasduplicadas](https://cloud.githubusercontent.com/assets/2912775/7520314/6c6cc6c0-f4ab-11e4-9ed2-5ed341c383e8.png)

**Comment by jccastillo0007** [comment]
Fco, puedes checar este defecto, creí que ya estaba resuelto.

**Comment by FraQue0693** [comment]
Este issue lo vera JC

**Comment by RigoFlores** [comment]
quizás también se resuelva por BD, al colocar un índice de llave única en el número de cuenta, que de hecho, en el catálogo de cuentas, NO SE DEBE REPETIR NINGUNA CUENTA...

**Comment by jccastillo0007** [comment]
Mmmm noup, el modelo de base de datos, no esta pensado para tratar exceptiones de base de datos, como errores de validaciones de negocio, además de que es muy costoso en performance esperar que la base de datos nos resuelva este tipo de integridad de los datos,  y además de que el defecto reportado se presenta en pantalla aún antes de salvar en base de datos.

**Comment by RigoFlores** [comment]
OK, de acuerdo con el último comentario, que el error se encuentra en pantalla, mucho antes de hacer el commit.

**Comment by RigoFlores** [comment]
Defectos de hace muuucho tiempo... simplemente no se atendieron

**Comment by jccastillo0007** [comment]
Este defecto y el 389 si que estan cabrones, y si los veo como defectos graves.... espero que valga la pena el tiempo que le estoy invirtiendo a arreglarlos y que no sean opciones que los clientes nunca usaran.

**Comment by RigoFlores** [comment]
En caso que los clientes nos elijan como opción de econta, si que se hace necesario  atender este requisito.
El punto es que si tenemos los suficientes argumentos para que el cliente nos elija, por encima de coi o contpaq. Los cristeros lo hicieron en su momento, pero al no darles respuesta (caso concreto operación con solo teclado), quizás ya no estén tan convencidos de quedarse con nosotros.
Lo que es un hecho que tengo un año externando, es que el número de cuenta debe ser la llave primaria o similar, para evitar duplicidad de número de cuentas...

**Comment by jccastillo0007** [comment]
Fixed.

Seria una gran perdida los cristeros.... pero puto Ajax no se deja.

**Comment by RigoFlores** [comment]
Ya no me han buscado los cristeros para la econta.
Solo me resta una pregunta, ya validé la solución y está OK. Si quedó como llave ÚNICA el número de cuenta (ya sea por BD o como sea)?
