### ISSUE TITLE
MOSTRAR ALGUN INDICADOR QUE ESTÁ EN PROCESO DE FACTURACION

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#38]
CUANDO LE DAMOS CLICK EN FACTURAR, EL CLIENTE NO SE DA CUENTA SI LA PETICIÓN SE ENCUENTRA EN PROCESO.
SE DEBE INDICAR DE ALGUNA MANERA AL CLIENTE ESTA SITUACIÓN, Y NO DEBE PERMITIR VOLVER A DAR CLICK EN ALGÚN OTRO BOTÓN, YA QUE SI PERMITE DARLE EN FACTURAR CUANTAS VECES UNO QUIERA.

**Comment by jccastillo0007** [comment]
Work in progress..... ya casi casi esta listo.

**Comment by jccastillo0007** [comment]
Ya esta la imagen de loading... ahora solo me falta deshabilitar los botones para que no la caguen...

**Comment by jccastillo0007** [comment]
finally fixed.

**Comment by RigoFlores** [comment]
ya solo falta limpiar la pantalla, y mantener las ligas para bajar el PDF y XML

**Comment by jccastillo0007** [comment]
Chaaaa eso ya esta, ya vez como no revisas bien,.... estas viendo y no ves jaajja
