### ISSUE TITLE
Agregar a todas las cuentas agregadas al catálogo, la etiqueta de 'afectable'

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#380]
Las cuentas que se agregan al catálogo desde la pantalla de agregar cuenta, tendrán que llevar una bandera de 'afectable', para el mas bajo nivel que le corresponda.
En el caso de Activo - Activo Corto Plazo - Bancos - Banco Nacionales - Inbursa, que le corresponde la cuenta 102.01.001, que será afectable. pero ni activo, ni bancos, ni bancos nacionales, serían afectables en este caso.
El tema es para pólizas, incluso para la captura de la balanza, identificar cuáles son las cuentas que se pueden 'afectar', es decir capturar data en ellas.

**Comment by jccastillo0007** [comment]
Esa etiqueta debe guardarse en base de datos, como parte de los atributos de la cuenta, peeeeero, donde se debe mostrar ? durante la captura, o en la tabla de catálogo de cuentas, o en la pantalla de balanza, o en ningún lado por el momento.?

**Comment by RigoFlores** [comment]
Creo que este parámetro ya se almacena en la BD, y corresponde al 'asiento'.
Quizás lo que falta, es asignarle 'SI' en asiento, solo a las cuentas que se agregan desde la pantalla.
Lo verifico y te comento.

**Comment by RigoFlores** [comment]
Por lo pronto lo cerraré...en pólizas veremos si se ocupa..
