### ISSUE TITLE
Dar facilidad para agregar hasta nivel 5 en el catálogo de cuentas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#381]
Hoy permite solo hasta nivel 3.
OJO, cuando agregas un nivel, se agregan 4 dígitos a la cuenta. ejemplo:
Bancos-Nacionales-Bancrecer-Cuenta 1357
102.01.001.0001

Hoy en día como solo soportamos nivel 3, lo indica así:
102.01.001

**Comment by jccastillo0007** [comment]
Semi done... ya acepta niveles 4 y 5, falta el tema del consecutivo...

**Comment by RigoFlores** [comment]
si falta el tema del número de cuenta, así como las subcuentas de los niveles 3, 4  y 5.
Subcuenta de nivel 3, es tal como está ahora
Subcuenta de nivel 4, es la cuenta del nivel 3 asociada
Subcuenta de nivel 5, es la cuenta del nivel 4 asociada
Es decir, falta cubrir el tema de cuentas y subcuentas de niveles 4 y 5. Ahora mismo solo se podría capturar manualmente la cuenta del nivel 5, que además la asigna al nivel 3 y no al 5.

**Comment by RigoFlores** [comment]
![image](https://cloud.githubusercontent.com/assets/2912775/7088963/dd3a45de-df5d-11e4-9056-205c3b7f6934.png)

**Comment by RigoFlores** [comment]
Checa el comportamiento para Capital Contable - Patrimonio - Patrimonio. Hasta nivel 2, todo OK, pero si incluyo nivel 5 las cuentas y subcuentas están mal definidas/asignadas.

**Comment by RigoFlores** [comment]
Existen varios puntos finos, FUNDAMENTALES PARA LA CE....en particular en el catálogo de cuentas... este es uno de ellos...

**Comment by jccastillo0007** [comment]
Agregar registros a nivel 5, ya es posible.

Te refieres al problema del consecutivo de subcuenta y numcuenta ?

**Comment by RigoFlores** [comment]
Si es posible, pero si no se asignan las cuentas correctamente, entonces es contraproducente...
Podemos cerrar este, y abrir otro con el tema de asignar correctamente las cuentas y subcuentas para  nivel 3, 4 y 5

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Lo cerraré en el sentido que si permite hasta nivel 5, pero no asigna correctamente las cuentas. Sin embargo ese issue ya está abierto en otro ticket.
