### ISSUE TITLE
Implementar la migración de gasolineros al web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#383]
ya fue definida al detalle

**Comment by jccastillo0007** [comment]
Catálogo de productos:

De acuerdo a lo platicado anteriormente, se manejarían al menos 2 datos extra en el caso de combustibles (otros productos simplemente no capturarán nada en esos datos extra):

1)      Monto IPES. Es el monto en pesos (por ejemplo 0.36) que se le agrega a cada litro de combustible: magna, premium o diesel.

2)      Precio al público. Cuando se captura el precio al público, se calcula el precio unitario con base a:

PrecioUnitario = (Precio al publico – monto IEPS) / (1 + tasa de iva estándar).

Aquí mismo se puede calcular la Tasa IEPS = montoIEPS / PrecioUnitario

Pantalla de agregar producto a la factura:

Cuando se agrega alguno de los combustibles a la factura, se puede capturar únicamente el total a pagar, y con ello se calcula la cantidad con base a lo siguiente (aplica para cualquier otro escenario):

Cantidad  =(         ( total /   (  (1 + tasaIva + tasaIEPS ) - tasaIvaRetenido - tasaIrsRetenido )     )    +    montoDescuento     )   / PrecioUnitario

También se podría capturar la cantidad y con ello se calcula el total de manera estándar.

Nota. Aquí cuando se trata de combustibles, se debe considerar tanto el IVA como el IEPS trasladado (dependiendo de cada combustible), SIN NECESIDAD QUE EL USUARIO LO ELIJA.

PDF:

Se trata que en el precio unitario para el PDF se le agregue el monto IEPS. Con ello se modifica el importe y subtotal también. El IVA y total no cambia en nada. No se envía el IEPS ni la tasa IEPS al PDF, aunque esto último se resuelve, simplemente no mostrándolo.

Reporte por producto:

Generar el reporte de facturación por producto.

**Comment by jccastillo0007** [comment]
Voy a listar aqui los requerimientos 
1. Datos extras en catalogo de productos. (Listo.) contemplar lo siguiente 
   - El precio unitario se va a actualizar al momento de salvar el producto
   - Los datos extras se deben capturar con el nombre de IEPS y Precio unitario
   - El impuesto IEPS con su respectiva tasa se va a dar de alta automaticamente en los impuestos de este cliente, esto es bueno, peeeero después de un rato, puede ser que existan muchas tasas diferentes y que algunas sean obsoletas
2. Funcionalidad en pantalla de facturación.  
   - El impuesto IVA e IEPS se deben autocompletar / autoseleccionar cuando se trata de algún combustible. (Listo, siempre no estuvo tan cabron.)
3. Revisar funcionalidad al generar el XML de standalone y aplicarlo a web (Listo)
4. Datos que se mandan al PDF (Listo)
5. Consulta de facturas por producto (Listo)
6. Aplicación web para generar / descargar la factura (Listo)
7. Respaldo de documentos en el cloud (No definido)

**Comment by RigoFlores** [comment]
Como aclaración, los datos extra a nivel producto son 'monto IEPS', y 'Precio a Publico'.
Tu comentaste 'precio unitario' como dato extra. No, el precio unitario ya existe, y se re-calcula cuando tu capturas el precio al público.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Pendiente generar correctamente el reporte de gasolineros...

**Comment by jccastillo0007** [comment]
Fco, al momento de exportar una consulta por producto a excel, el reporte debe generar la info con las siguientes columnas... (te mando un archivo csv como ejemplo)

fecha, status, serie, folio, receptor, nombre receptor, producto,  costo,  cantidad,  descuento,  iva trasladado, ieps, iva retenido, isr, subtotal,  total

Nota, si una factura tiene varios productos, unicamente se deben exportar a excel el producto que se eligió en la consulta, se dejan fuera los otros productos.

**Comment by jccastillo0007** [comment]
Rijo, puedes validarlo... ya esta en PRU.

**Comment by RigoFlores** [comment]
Ya genera el reporte, pero los datos son incorrectos
Checatesta... en el XML todo bien..
    <cfdi:Impuestos totalImpuestosTrasladados="218.793108">
        cfdi:Traslados
            <cfdi:Traslado impuesto="IVA" tasa="16.0" importe="182.113104"/>
            <cfdi:Traslado impuesto="IEPS" tasa="3.222613" importe="36.680004"/>
        /cfdi:Traslados
![image](https://cloud.githubusercontent.com/assets/2912775/7667639/6763ad70-fbd5-11e4-9688-822768726f7f.png)

en el excel se reporta el IVA, incorrectamente...

**Comment by RigoFlores** [comment]
```
<cfdi:Impuestos totalImpuestosTrasladados="218.793108">
    <cfdi:Traslados>
        <cfdi:Traslado impuesto="IVA" tasa="16.0" importe="182.113104"/>
        <cfdi:Traslado impuesto="IEPS" tasa="3.222613" importe="36.680004"/>
    </cfdi:Traslados>
```

**Comment by RigoFlores** [comment]
si te das cuenta en lugar de reportar el iva como 182.113104, lo reporta como 218.793108... realmente éste último dato es la suma de los impuestos trasladados, pero no del iva propiamente...
so, es incorrecto el reporte a nivel producto en la columna del IVA

**Comment by jccastillo0007** [comment]
Fixed.
