### ISSUE TITLE
Dar opción para generar XML's con niveles 1y2, o con todos los niveles a partir del 1

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#385]
Esto es para no entregar al sat toooodo el detalle de cuentas.
Aplica catálogo de cuentas y balanza

**Comment by jccastillo0007** [comment]
Esto ya se encuentra resuelto al momento de exportar la balanza.

**Comment by jccastillo0007** [comment]
que falta de este req ?

**Comment by RigoFlores** [comment]
y mi comentario de la mañana????? chiaaaaaaa....
Lo que falta es precisamente lo que se solicitó en este issue, y es que al momento DE GENERAR EL XML, de la opción al usuario de: "nivel 1 y 2" ó "todos los niveles", ya que lo que se tiene ahora mismo, aplica para el excel, pero no para el XML. 
El dafault sería "NIVEL 1 Y 2"  (así solo se envía al SAT la información mínima necesaria).

A diferencia del excel, que ahí si se ocupa elegir un cierto nivel, aquí solo serían 2 opciones, nivel 1y2, o 'todo'.
