### ISSUE TITLE
Cuando capturas mas de una cuenta de nivel 4, replica las cuentas de nivel 3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#389]
En este ejemplo, capturé inventario, de ahí dí de alta 3 cuentas de COMBUSTIBLE (nivel 3), y luego capturé 3 cuentas de nivel 4, que son MAGNA, PREMIUM Y DIESEL. 
El resultado se muestra a continuación:
![cuentas replicadas](https://cloud.githubusercontent.com/assets/2912775/7484398/a8cd9f90-f34d-11e4-8f75-1a462dfb96bd.png)

**Comment by RigoFlores** [comment]
Lo que debió hacer, es dado que la cuenta de COMBUSTIBLE es nivel 3, y se repite en la captura, únicamente dar de alta una cuenta agrupadora COMBUSTIBLE, para las 3 cuentas nivel 4 que dí de alta.
Aplica el mismo caso para ADITIVOS Y LUBRICANTES (nivel 3), ya que capturé 2 cuentas a nivel 4 que son INVENTARIO LUBRICANTE, e INVENTARIO ADITIVOS.

**Comment by RigoFlores** [comment]
Esto no se puede resolver por BD con una llave o índice único para este campo?. Si se maneja apropiadamente la excepción en la BD, estaría resuelto, que no?

**Comment by jccastillo0007** [comment]
Mmmm noup, el modelo de base de datos, no esta pensado para tratar exceptiones de base de datos, como errores de validaciones de negocio, además de que es muy costoso en performance esperar que la base de datos nos resuelva este tipo de integridad de los datos,  y además de que el defecto reportado se presenta en pantalla aún antes de salvar en base de datos.

**Comment by RigoFlores** [comment]
En este caso particular, no importa que el error esté en pantalla antes de dar commit, ya que simplemente no almacenaría las cuentas duplicadas. Pero bueno, pues tu sabrás como resolverlo, para mí esta sería una opción...

**Comment by RigoFlores** [comment]
Otro de los platicados...

**Comment by jccastillo0007** [comment]
fixed... ahi wey.... que pinche fumada la contabilidad electronica...

Checa bien esto de las cuentas a n niveles, para evitar que después surjan otros defectos.

**Comment by RigoFlores** [comment]
Como te decía, si la cuenta se coloca en la llave primaria (de alguna manera), se resuelve el tema.
Lo que hice fue dí de alta una cuenta de nivel 4. Posteriormente cerré la pantalla y volví a abrirla, para dar de alta otra cuenta de nivel 4. El resultado fue que repitió la cuenta de nivel 3. Anexo imagen
![error en cuentas](https://cloud.githubusercontent.com/assets/2912775/12357463/93083b00-bb6d-11e5-8f3f-2c71ac11cc20.png)

**Comment by RigoFlores** [comment]
Por cierto, las cuentas en cuestión son las de "INBURSA" (nivel 3) y "CUENTA 1" y "CUENTA 2", nivel 4.

**Comment by jccastillo0007** [comment]
fixed.

checa si funciona bien con cuentas a nivel 5.

**Comment by RigoFlores** [comment]
Lamentablemente sigue incorrecto...
Si bien no repite ya las cuentas de nivel 3.... en las cuentas de nivel 4 asigna mal el número de cuenta, así como de subcuenta.
Lo que hice primero capturar una CUENTA 1 de nivel 4 de INBURSA. Cerré la ventana... y posteriormente capturé la CUENTA 2 de INBURSA. 
![cuentasnivel 4](https://cloud.githubusercontent.com/assets/2912775/12400826/0a50695e-bde8-11e5-8867-cd2f0431436a.png)

**Comment by RigoFlores** [comment]
Si te das cuenta, ya no repite INBURSA, lo cual es correcto.
Sin embargo, si revisas la CUENTA 2 (hija de INBURSA al igual que la cuenta 1), lo que sucede es:
a) el número de cuenta debería ser 102.01.002.003
b) el número de subcuenta debería ser el de inbursa, es decir... 102.01.002

ya que la subcuenta 102.01.003 ni siquiera existe... esto debe generar unas inconsistencias muy cabronas...

**Comment by jccastillo0007** [comment]
Que pinche fumado esta esto
