### ISSUE TITLE
PORQUE NO PUEDE ENVIAR CORREO A SOPORTE DESDE RFC TIA?

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#39]
LE CONFIGURÉ EL CORREO DE soporte@factura-t.com.mx EN EL RFC DE LA TÍA, Y NO PUEDE ENVIAR EL CORREO COMO RECEPTOR.
EL MISMO CORREO LO CONFIGURÉ PARA OTROS RFC'S, Y AHÍ SI LO ENVÍA.
TIENE ALGO EN PARTICULAR EL RFC DE LA TÍA?

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
se corrigió, pero no se respondió la pregunta...

**Comment by jccastillo0007** [comment]
No, no tiene nada en particular el email de la TIA, habia un error en el procesamiento interno.
