### ISSUE TITLE
Implementar ajuste en aplicación de Españoles-Navision

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#390]
NOS HAN PEDIDO ESTOS AJUSTES

AGREGAR FUNCIONALIDAD DE DESCUENTOS:

A)  LOS DESCUENTOS APARECEN A NIVEL DE PRODUCTO, SO HAY QUE SUMARLOS PARA INTEGRAR EL DESCUENTO QUE SE REPORTARÁ AL XML Y PDF
B)  CADA DESCUENTO A NIVEL PRODUCTO, SE ENVIARÁ COMO DATO EXTRA A NIVEL PRODUCTO, AL PDF. 
C)  El descuento a nivel producto (datoExtraPro3) se toma del campo [Line Discount Amount] de la tabla [IPNavision400SP2].[dbo].[MEXICO - IP$Sales Invoice Line], que es la misma que se ocupa para el resto de los datos
D)  También se debe enviar el porcentaje de descuento [Line Discount %]  a nivel producto (datoExtraPro4) como dato extra para el PDF, que se toma de la misma tabla.
E)  FINALMENTE AGREGAR A LA BITÁCORA, UN REGISTRO DE CUANDO SE ENVÍA EL CORREO AL INBOX, DE PREFERENCIA INDICANDO SI FUE EXITOSO O TUVO PROBLEMAS.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
ya generaron la factura con descuento, y si lo envió al XML.
También ya llegan las facturas al portal.
Lo estaremos observando
