### ISSUE TITLE
Debe acumular los iniciales, haber, deber y finales, hacia las cuentas agrupadoras de nivel 1

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#393]
En la balanza y en general cuando ya se generen las pólizas, debe (sumar) hacia arriba los saldos inicial, deber, haber y final, para las cuentas de nivel 1, es decir las cuentas de mayor

**Comment by jccastillo0007** [comment]
no ma... este si esta cabron.

**Comment by RigoFlores** [comment]
Mientras no se demuestre que la función recursiva no jala, tons la solución ya está definida..

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
al parecer si lo está haciendo correctamente... lo cerraré, pero seguiré validando con varios ejemplos...
