### ISSUE TITLE
Dar opción de importar catálogo de cuentas, pólizas y/o balanza desde excel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#394]
Adicional a las opciones que ahora mismo tenemos, implementar la opción de Importar Catálogo de Cuentas, e Importar Balanza

**Comment by jccastillo0007** [comment]
Issue duplicado con el número 477.

**Comment by RigoFlores** [comment]
Aquel se refiere al formato de los cristeros, que te envié en su momento.
Este se refiere a algo mas genérico, pero como no tenemos el layout genérico, solo dejaré abierto el de los cristeros que es el que si conocemos, aunque igual no se atiendió
