### ISSUE TITLE
ESCRITORIO, NO ENVÍA EL MENSAJE DEL CORREO - OPCIÓN REENVIAR CORREO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#395]
En consultas, cuando tecleas un mensaje para el receptor del correo... no lo está incluyendo como cuerpo del correo.
En web si lo hace.

**Comment by RigoFlores** [comment]
Desde hace varias versiones dejó de enviar el mensaje que capturas en la pantalla de envío de correo en el escritorio...

**Comment by jccastillo0007** [comment]
Fixed, release 9.1.17 de hoy mismo

**Comment by RigoFlores** [comment]
Bueno, mas vale tarde que nunca....
