### ISSUE TITLE
Implementar Remisión para los gasolineros en Web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#397]
Ahora mismo, la remisión que estarían generando los gasolineros, no incluye los ajustes en el PDF similares a la factura.
Esto es precio unitario, importe y subtotal.
Recordar que a partir de remisiones, será que se descarguen o generen las facturas en el portal de DESCARGATE.

**Comment by jccastillo0007** [comment]
Done.... favor de validar en PRU.
