### ISSUE TITLE
Pólizas - Número de Pólizas no editable

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#399]
El número de la póliza no debe ser editable.
El número de póliza debe permitir ordenar por consecutivo
Agregar un guión al número actual: 201505 P001
Debería ser: 201505-P0001
(esta nomenclatura permite ordenar ascendente o descendente??)

**Comment by jccastillo0007** [comment]
En serio no debe ser editable ? seguramente algún cliente tendrá su estándar para nombrar las pólizas..

**Comment by RigoFlores** [comment]
Este punto es exactamente lo mismo, si me preguntaras que el cliente pueda cambiar el número de folios en las facturas. Obviamente, no pueden editarlo.
También atiende un requerimiento específico respecto al número de póliza, por parte del SAT:
"Atributo requerido para expresar el número único de identificación de la póliza. El campo deberá contener la clave o nombre utilizado por el contribuyente para diferenciar, el tipo de póliza y el número correspondiente. En un mes ordinario no debe repetirse un mismo número de póliza con la clave o nombre asignado por el contribuyente."

Si tenemos otra manera de garantizar dicho requerimiento, cuál sería la propuesta?

**Comment by jccastillo0007** [comment]
Si depende de nosotros, puede ser un consecutivo por mes, como tu lo has pedido, peeero mi punto es que estamos obligando a que ese sea el número de póliza, y yo creo que algún cliente puede manejar ya un estándar en el número de póliza y nos va a pedir que lo respetemos, en ese caso, debe ser editable y es bronca de ellos mantener el consecutivo.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Estoy seguro que no es su responsabilidad mantener el consecutivo e irrepetible, como crees?
Todas las aplicaciones que revisé, generan el folio de manera única.
Como te comenté, si quieres que sea un número consecutivo, con el prefijo del añomes, pero si tenemos que generarlo nosotros... piénsale, quizás alguna opción mas simple, pero en definitiva, si tenemos que controlarlo y generar nosotros el folio irrepetible y único, incluso por BD
