### ISSUE TITLE
Catalogo de clientes

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#4]
No se debe manejar sucursales si no nombres alternos
Debe poder modificar la razon social

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
AUNQUE PRESENTA LA OPCIÓN, NO HAY FORMA DE EDITAR EL REGISTRO DE UN CLIENTE YA EXISTENTE, YA QUE AL MODIFICAR Y DARLE GUARDAR, SE QUEDA EN LA MISMA PANTALLA, PUDIENDO REGRESAR A LA ANTERIOR, SOLO CON EL BOTÓN DE CANCELAR.
EN CUANTO AL NOMBRE ALTERNO, SE ABRIÓ UNA FICHA NUEVA

**Comment by RigoFlores** [comment]
YA PERMITE EDITAR LOS CATÁLOGOS DE CLIENTES Y EL DE NOMBRE ALTERNO TAMBIEN
