### ISSUE TITLE
CAMBIAR ETIQUETAS EN PANTALLA DE FACTURA (FACILITO)...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#40]
CAMBIAR LAS ETIQUETAS EN LA PANTALLA DE FACTURA:
Enviar por correo al receptor.
Enviar por correo al emisor.

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
cambiar la palabra Envio por Enviar

**Comment by jccastillo0007** [comment]
Done.... chaaaaaa
