### ISSUE TITLE
Polizas - faltan columnas en la sección de transacciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#401]

**Comment by RigoFlores** [comment]
Las que venían en la pantalla de excel muestra, que les entregué...

**Comment by jccastillo0007** [comment]
Esto, según yo ya esta cubierto con la nueva versión de la página de transacciones.

**Comment by RigoFlores** [comment]
ya ni recuerdo de tanto tiempo que pasó.... lo cerramos, y solo se abrirá si es que falta algo...
