### ISSUE TITLE
Remisión de Gasolineros, no genera la factura correctamente en Descarga tu CFDi

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#402]
Cuando genero una remisión en el portal de facturación, la emite bien, con respecto a la spec de los gasolineros.
Si esa remisión la convierto en factura, desde descarga tu factura, entonces ya no genera correctamente el PDF de la factura, de acuerdo a la spec de los gasolineros.

**Comment by jccastillo0007** [comment]
Duplicated with #404
