### ISSUE TITLE
No permite capturar el número de ticket, como ID para la remisión de gasolineros

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#403]
Para los gasolineros, el número de ticket es algo así como:
80000024235

la aplicación cuando captura dicho número en el ID de seguimiento (folio de remisión), marca internal error.

Recordar que se ocupa que el mismo folio del ticket se capture para la remisión, y así con ello, no tendrían necesidad de imprimir la remisión. Con el ticket actual, podrían generar su factura.
Claro, eso no elimina el proceso de capturar la remisión, donde la condición es asegurar que la cantidad y el total sean correctos.

**Comment by jccastillo0007** [comment]
Fixed, bueno, parcialmente.

Hay un detalle, si el número que capturen es mayor a 2147483647, el sistema lo va a reducir a 9 dígitos, lo que podemos hacer es que los clientes siempre capturen los últimos 5 o 9 digitos del folio del ticket, y no todo el folio.

Cómo ves ?

**Comment by RigoFlores** [comment]
No creo, ellos son muy cerrados. A como los conozco, querrán capturar todo.
De hecho es lo mas conveniente, si le pones a un despachador a tomar esas decisiones, no creo que sea la mejor idea.
Hay que soportar ese tamaño de cadena

**Comment by jccastillo0007** [comment]
Creo que no me expliqué bien, el tracking id = número de ticket SI puede ser de todos los números que tiene el ticket, ahi no hay problema.

Lo que se va a reducir es el folio interno con el que se va a generar la factura, aún así crees que tengan problemas.

**Comment by RigoFlores** [comment]
ok, aquí lo que platicamos es que será uno el id (ya sea sugerido por el sistema, o para los gasolineros, capturado por el usuario), y otro el folio de la factura, sin precisamente estar relacionados, ya que el folio de la factura tiene su propio consecutivo, incluso cuando generen facturas desde el portal tendrán su consecutivo, y cuando generen desde descargat, deberá continuar con su consecutivo.

**Comment by jccastillo0007** [comment]
Done.
