### ISSUE TITLE
No genera la factura correctamente desde DescargaT para gasolineros

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#404]
Si yo captura una remisión para los combustibles, y luego genero la factura desde el descargaT, no considera los cambios en el PDF, de acuerdo a la spec para los gasolineros.
A menos que tenga que probar con algún RFC emisor en particular.
Yo hice las pruebas con la cuenta de la tia, que tiene el plugin de gasolineros.

**Comment by jccastillo0007** [comment]
Fixed.
