### ISSUE TITLE
Remision Gasolineros - El id capturado no es el folio asignado a la remisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#405]
A la hora de generar la remisión, el folio asignado e incluido en el PDF es distinto al id capturado, que debe ser idéntico al que se incluye en el ticket de la bomba. Por ejemplo 8000024240. En este caso, el folio asignado es solamente 24240.

Cuando desde descargaT quieres generar la factura, te pide el folio, pero dado que es incorrecto no lo reconoce. Tienes que teclear el id y así si lo reconoce y te presenta los datos de la factura

**Comment by RigoFlores** [comment]
para descargaT, por lo pronto la etiqueta será la de número de ticket. Ese número de ticket se deberá incluir en el formato de la remisión.

**Comment by jccastillo0007** [comment]
Este ticket por su titulo, quedaría obsoleto.

Por otro lado, ya se cambió la etiqueta que decia folio por No. Ticket.
