### ISSUE TITLE
No muestra las cuentas del catálogo, para agregarlas a la póliza

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#407]
En la cuenta de la TIA, borré todas las cuentas del catálogo y luego volví a capturar algunas para mis pruebas, y nada. En pólizas no muestra ninguna cuenta de las capturadas.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
cuál fue el problema? No hay que hacerle manita de puerco, porque imagínate con todos los clientes?
