### ISSUE TITLE
CE - No incrementa el consecutivo de número de póliza, para el mismo mes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#409]
Siempre repite la póliza 0001.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Negativo, la primera póliza se compone de 3 transacciones por ejemplo.
Esa es la póliza P001 para el mes en cuestión.
A la siguiente póliza del mismo mes, le asignó ahora el número P004, en lugar del P002
