### ISSUE TITLE
DONDE CONFIGURO LO QUE ANTERIORMENTE SE HACÍA EN EL PROPERTIES?

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#41]
PARA EL WEB, DONDE CONFIGURO LO QUE ANTERIORMENTE HACIA EN EL PROPERTIES?
ME QUEDA CLARO QUE ALGUNOS PARÁMETROS NO SE NECESITARÁN CONFIGURAR, PERO OTROS COMO PLANTILLA, AUTOPRINT, ETC SI SERÁ NECESARIO DEFINIRNOS.

**Comment by jccastillo0007** [comment]
En la pantalla de admin, ahi se daran de alta las configuraciones que apliquen para esta version

**Comment by RigoFlores** [comment]
LA PANTALLA DE CONFIGURACIÓN Y LA DE PREFERENCIAS SON DISTINTAS?
ENTIENDO QUE AHORA MISMO LA CONFIGURACIÓN APLICA PARA EL CERTIFICADO Y LOGO.
SUPONDRÍA QUE PREFERENCIAS PODRÍA SER INDEPENDIENTE

**Comment by jccastillo0007** [comment]
Estuve revisando el archivo properties que maneja facturat y me parece que las unicas opciones configurables son:

Envio automatico de la factura al receptor y al emisor.
El template de jasper que sera utilizado
El aviso de expiracion del certificado (me parece que este ya no aplica si definimos un periodo de 1 mes fijo)
El porcentage de folios disponibles ( no se si aplica, ahora vamos a validar los folios que compraron mas no los folios de sus propias series, igual y podemos dejar fijo este valor, para mantenerlo simple)

JC

**Comment by RigoFlores** [comment]
si, también revisé... y creo que son los siguientes:
a) Plantilla a ser utilizada, por cada tipo de llave
b) días para avisar vencimiento de sello (puede quedar fijo, 15 días)
c) Porcentaje para notificar término de folios adquiridos (puede quedar fijo al 10%)
d) para conector autoprint (no se si se ocupe en web, es decir si se implementará conector web)
e) para conector, permitir el envío de correo (no se si se ocupe, es decir si se implementará conector web; puede quedar fijo a true)
f) configuración para personalizar el correo del emisor de la factura
g) configuración del preview (debe quedar fijo, para que cada factura generada la presente en PDF)
h) faltaría configurar la notificación de caducidad de folios (puede quedar fijo a 15 días)

En resumen se configura (a), (d), (f). 
Los parámetros que pueden quedar fijos son: (b), (c), (e), (g) y (h).

**Comment by jccastillo0007** [comment]
Ok, vamos a implementar : a, b, c, h
Estos se implementan en el conector web, cuando lo desarrollemos : d , e
Estos se iimplementaran en una segunda fase : f, g

Este requerimiento esta duplicado con el issue # 54, puedes cerrarlo.

**Comment by jccastillo0007** [comment]
Ya puedes cerrar esta ficha.... ya viste como funciona en PRO.
