### ISSUE TITLE
En la balanza repite las cuentas de asiento = 1, cuando se ocupan en mas de una póliza

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#410]
Es muy simple, debe acumular a la misma cuenta... es UNA SOLA CUENTA...no son n cuentas de la misma.
Insisto, la llave primaria o como se llame, debería ser el número de cuenta tanto en el catálogo como en la balanza....

**Comment by jccastillo0007** [comment]
Fixed.
