### ISSUE TITLE
al momento de salvar una póliza, debe confirmar cuando haber <> deber

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#411]
Cuando salves una póliza y los saldos deber y haber, sean diferentes, debe confirmar, ya que esto es una situación típica de error de dedo...

**Comment by jccastillo0007** [comment]
Fco, puedes atender este ticket.

**Comment by RigoFlores** [comment]
Al momento de guardar la póliza, y si el haber es distinto al deber, entonces se pide confirmación al usuario:
"Póliza no cuadra:, ¿desea continuar?"
Las etiquetas y datos correspondientes a la sumatoria del deber y haber, deben mostrarse en rojo cuando sean distintos y en verde cuando sean iguales.
(Inician en verde porque todos son 0.0), conforme van capturando se pasan a rojo, y hasta que sean iguales se vuelven verdes nuevamente

**Comment by RigoFlores** [comment]
YA SOLO FALTA QUE EL COLOR DEL FONT PARA EL FONDO VERDE O ROJO, SEA BLANCO O SIMILAR, YA QUE SE PIERDE Y NO SE ALCANZA A LEER BIEN..

**Comment by jccastillo0007** [comment]
Done.
