### ISSUE TITLE
no realiza correctamente los cálculos de la primera póliza...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#412]
ya mandé un correo, a ver si jala la imagen...
Checatesta…
Iva pendiente de pago y su cuenta madre, debería tener por ser deudora, un saldo final de (-160)
Ventas y/o Servicios  y sus cuentas madre, por ser acreedora debería tener un saldo final de 1000
Como la bestia?
![bug](https://cloud.githubusercontent.com/assets/2912775/7996151/16d9c8cc-0ae3-11e5-8c7b-41c79fd78a54.png)

**Comment by jccastillo0007** [comment]
Fixed.
