### ISSUE TITLE
Atención al tema de espacio en HD del servidor de timbrado.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#413]
Se saca un backup diario, debo hacer un script que a inicios de mes, borre todos los respaldos del mes anterior, dejando solo el respaldo del ultimo dia

**Comment by jccastillo0007** [comment]
Fixed.

Te va a llegar un correo con el porcentaje de espacio en disco, solo para pruebas, después de unos días, solo va a llegar si el espacio usado es mayor al 70%

**Comment by RigoFlores** [comment]
No sé que pasó con mi comentario, pero la duda era quién va a ejecutar lo que tu hiciste cuando se llenó el disco? Es decir el cierre de este issue, dependería que la automatización en la liberación de dicho espacio, que no?

**Comment by jccastillo0007** [comment]
No necesariamente.

Por un lado, voy a cambiar el envío de esta notificación, para que solo nos
avise cuando el espacio disponible llegue al 80%, y cuando eso suceda, yo
puedo depurar los logs.

Por otro lado, en cuanto pueda, hago un script para hacer esa depuración de
forma mensual, el consumo de espacio en disco aún es manejable, no es algo
urgente, lo que sucedió fue por tener respaldos desde el anio pasado.

Si quieres dejamos este ticket abierto, para recordar el segundo script que
falta, pero lo mas importante es que tanto tu como yo, vamos a saber cuando
lleguemos al 80%.

Saludos.
JC.

2015-07-20 11:34 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Lo cerramos y abrimos otro... posteriormente.. jeje
