### ISSUE TITLE
Notificar por correo cuando el espacio en los servidores de producción se acerque al 5-10%

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#414]
Si es posible con un cron

**Comment by jccastillo0007** [comment]
Fixed.

Te va a llegar un correo con el porcentaje de espacio en disco, solo para pruebas, después de unos días, solo va a llegar si el espacio usado es mayor al 70%

**Comment by RigoFlores** [comment]
Me llegaron 2 notificaciones, para 2 servers distintos (supongo web y timbrado???).
Solo necesitamos monitorear esos 2 equipos?
