### ISSUE TITLE
Exportar las pólizas a excel y PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#415]
De manera individual o por Mes.
En el excel, con todas las columnas que debe llevar.
En el PDF, deja revisar algún ejemplo para tomar los formatos de muestra

**Comment by RigoFlores** [comment]
Ya revisé los criterios con el asesor:
a) por número de póliza
b) por rango de fechas
c) por tipo en combinación de rango de fechas

**Comment by jccastillo0007** [comment]
Fco, en el menú de CE hay que generar otra pantalla de Consultas, asi como tenemos en Ventas, Compras, Nómina etc... 
Las opciones de busqueda serán las que menciona Rigo.
Al realizar una consulta, es ahí donde se debe generar el excel, hay que quitar esa opción de la pantalla de Polizas.
Debe exisitir un renglón por cada transacci[on de cada póliza, y en ese renglón debe tener toda la info de la póliza y de la transacción, para que se puedan ejecutar filtros en excel.

**Comment by jccastillo0007** [comment]
Ya esta el excel... faltaría el PDF... hay que definir la plantilla.
