### ISSUE TITLE
Capturar saldo inicial, cuando se da de alta la cuenta.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#416]
A menos que encuentres un mejor lugar, pero me parece que desde ahí se podría hacer...
Aunque no es dato para el catálogo del sat, sino para la balanza, es en el catálogo de cuentas donde se tiene acceso a todas las cuentas.

**Comment by RigoFlores** [comment]
O podría ser la primera ocasión que alguna cuenta se utiliza para las pólizas???
Insisto, no se ocupa para el catálogo de cuentas, o para las pólizas, pero debemos en algún momento-lugar, capturar el saldo inicial...

**Comment by jccastillo0007** [comment]
Done.... 

Ya se esta tomando en cuenta el saldo inicial de una cuenta capturada, peeeeero, por alguna razón no lo esta reflejando hacia niveles superiores.... puedes realizar algunas pruebas y decirme si solo falta eso o algo mas.
