### ISSUE TITLE
agregar en el reporte de pólizas (cuando son varias) los totales del abonos y cargos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#418]
Agregar al final de la columna del deber y haber, la sumatoria, ya que eso es lo que indica si cuadran o nó... se que la pueden agregar en excel, pero son comentarios de los contadores.
Coincidieron ambos.
Solo espero lo de balanzas, ya que ahí si les estoy refutando sus sumatorias

**Comment by jccastillo0007** [comment]
Ya agregué las columnas, eso parece que esta ok, lo que no me cuadran son los totales... checatesa...

**Comment by RigoFlores** [comment]
no vi nada nuevo...

**Comment by jccastillo0007** [comment]
No inventes, claro que si, las columnas de saldo inicial y final ya se dividen entre deudores y acreedores, si lo estas probando en PRU ? yo lo hice con la cuenta de la TIA para el mes de Junio 2015 y validé el excel

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
no, sigue igual.
Hablamos del reporte excel de pólizas. Solo falta agregar la suma de las columnas del deber y haber

**Comment by jccastillo0007** [comment]
Done.
