### ISSUE TITLE
Balanza o pólizas mal exportadas a excel, cuando contiene ',' el nombre

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#419]
Algunos nombres del catálogo del sat, contienen coma (,).
cuando se muestran en el excel, al ser separado por coma, no los muestra correctamente.
También los acentos se ven incorrectos en pantalla y en excel...

**Comment by jccastillo0007** [comment]
Lo de las comas ya esta arreglado.
Los acentos aún no.

**Comment by RigoFlores** [comment]
generé un excel y sigue apareciendo el tema de las comas y acentos..

**Comment by jccastillo0007** [comment]
Done.

**Comment by jccastillo0007** [comment]
no lo has corroborado ?
algo falta?
algo no funcionó?
 o que pasó?

**Comment by RigoFlores** [comment]
el tema de acentos no ha quedado

**Comment by jccastillo0007** [comment]
Según esto ya esa fixed.

**Comment by RigoFlores** [comment]
![error en excel](https://cloud.githubusercontent.com/assets/2912775/8839422/e073c0d4-309a-11e5-8066-93fdfb979634.png)

**Comment by RigoFlores** [comment]
Anexo evidencia que no incluye correctamente los caracteres con acento, y supongo con ñ tampoco..

**Comment by jccastillo0007** [comment]
haber calale otra vez...

**Comment by RigoFlores** [comment]
ok
