### ISSUE TITLE
ACTUALIZAR DATOS EN "ACERCA DEFACTURA-T"

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#42]
LOS DATOS CORRECTOS SON:
AV. UNIVERSIDAD OTE 155-B, COL. LOS CEDROS CP 76165

Y LA PÁGINA WEB CORRECTA ES...
www.facturat.com    (CHAAAAAAAAA....)

también puedes poner a FACTURA-T, con el indicador de marca registrada...

**Comment by jccastillo0007** [comment]
Ambas paginas llevan al mismo lugar, por eso la puse, de hecho para respetar nuestro guion que nos distingue en Factura-T.

**Comment by RigoFlores** [comment]
Favor de colocar 
Av. Universidad Ote, así literal, es decir mayúsculas y minúsculas, para que no se vea chueco, respecto al resto de la información.
La página facturat.com, es la que hemos trabajado en el tema del SEO, es decir todo el esfuerzo del posicionamiento realizado al momento apunta a ella. No estoy seguro que al entrar a la otra página, y redirigirse a la facturat.com, nos otorgue los mismos puntos para cuestiones de métricas del google.
Para no arriesgarle, creo que mejor dejamos facturat.com, y vamos viendo lo del cambio del correo.

**Comment by jccastillo0007** [comment]
Fixed.
