### ISSUE TITLE
ordenar por póliza el excel de pólizas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#421]
en el excel que integra varias pólizas, ordenar el excel, por número de póliza.
ahora mismo los registros que pertenecen a la misma póliza, aparecen revueltos con otras pólizas.

**Comment by jccastillo0007** [comment]
Si te refieres al excel que se genera en la pantalla de consulta de pólizas ? no hay forma de que salga desordenado, ya que se va guardando poliza por poliza y cada una con sus respectivas transacciones.

**Comment by RigoFlores** [comment]
si estaba desordenado, y ahora ya no
