### ISSUE TITLE
Cuando un mes-balanza, ya está cerrado, no debe permitir volver a cerrarlo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#422]
Debe indicar de alguna manera que ya está cerrado, y NO DEBE PERMITIR CERRARLO NUEVAMENTE

**Comment by jccastillo0007** [comment]
Fixed
La opción de cerrar la balanza, no aparece si ya fue cerrada previamente.

**Comment by RigoFlores** [comment]
Cuando cierras la balanza, no desaparecen los datos en pantalla, entonces te permite cerrar cuantas veces quieras la balanza.
a) Cuando le das click la primera (y debería ser única) vez, tiene que quitar el botón y/o limpiar la pantalla.
b) Solo cuando te cambias de pantalla y regresas a la de balanza, es que ya desaparece el botón de cerrar la balanza...

**Comment by jccastillo0007** [comment]
Fixed.
