### ISSUE TITLE
cuando un mes-balanza ya está cerrado, no debe permitir capturar pólizas para ese mes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#423]
eso antes ya jalaba, pero ahora no... obviamente está muy mal que así lo permita.
Si consulto la balanza de dicho mes, que ya estaba cerrada después de agregar una póliza, aparentemente no considera las operaciones de la póliza agregada, lo cual también es un error sobre error.....

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Básicamente no puedo probar nada, ya que borré todas las pólizas y balanzas, pero ahora NO PERMITE CAPTURAR NINGUNA PÓLIZA.
Me aparece en gris la sección de cuentas.

**Comment by RigoFlores** [comment]
Acabo de reproducir el problema... 
capturé 2 pólizas de junio. luego cerré el mes desde la pantalla de balanzas.
posteriormente me regresé a la pantalla de pólizas, y le dí click en agregar... dado que la fecha por omisión es julio y no junio, me permitió continuar.
Posteriormente le cambié la fecha a junio, pero ahí supongo que ya no validó nada. Entonces continué capturando sin mayor problema una póliza de junio, cuando ya estaba cerrado el mes.
Supongo que lo que validas solo es el mes actual, pero básicamente ese escenario será muy raro... es decir, que cierren el mes actual. 
Lo que hay que validar es que al momento de definir la fecha en la pantalla de las pólizas, ahí es el momento adecuado para validar si se puede o no capturar la póliza. Igual, se puede volver a validar al momento de guardar...

**Comment by jccastillo0007** [comment]
Done.

Una vez identificado el escenario, es fácil validarlo, dado que tengo muy bien alambrado eso.

**Comment by RigoFlores** [comment]
Jeje... ahora no permite capturar mas de una para el mismo mes...

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Al parecer va quedando mejor el alambrado... jeje
