### ISSUE TITLE
tipo de solicitud inválida en el xml de pólizas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#425]
Atributo requerido para expresar el tipo de solicitud de la póliza ( AF - Acto de Fiscalización; FC - Fiscalización Compulsa; DE - Devolución; CO - Compensación )

ESTE ES EL PATRÓN QUE SE DEBE GUARDAR:

AF|FC|DE|CO

**Comment by jccastillo0007** [comment]
Fixed.
