### ISSUE TITLE
falta el mes, en el encabezado del xml de pólizas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#427]
solo contiene el anio, pero le falta el mes... pásame mas info

**Comment by jccastillo0007** [comment]
Fixed.

A que te refieres con que te pase mas info ?

**Comment by jccastillo0007** [comment]
Que falta aqui ?

Necesito mas detalle.

**Comment by RigoFlores** [comment]
anio --> pasame info... (jeje)
no estaba colocando '06', en su lugar decía '6'.
ahora ya está corregido
