### ISSUE TITLE
Sacar datos de header de XML de pólizas, de la pantalla de pólizas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#428]
Estaba viendo que en la pantalla de pólizas, se captura un encabezado que aplica para el XML que aplica para todas las pólizas, y no a nivel de cada una de ellas.
Por esa razón, esos datos se deben sacar a nivel de una pantalla, donde se genere el XML de las pólizas involucradas en el período.
Ahora mismo, dicho encabezado contiene:
version
RFC
Mes
Anio
TipoSolicitud
NumOrden
NumTramite
Sello
noCertificado
Certificado

Entonces, esta información se debe capturar al momento de generar el XML de la póliza.
A como está en este momento, es decir en la balanza, solo estaría faltando el tipo de solicitur, número de orden o trámite.

**Comment by jccastillo0007** [comment]
Ok, de acuerdo... un poco mas de retrabajo no pasa nada.

**Comment by jccastillo0007** [comment]
El campo Tipo que tiene las opciones Ingreso, Egreso, Diario, donde se ocupa ?

**Comment by RigoFlores** [comment]
Ingreso, Egreso y Diario, son los tipos básicos de pólizas, que se utilizarán en futuros reportes como balance general, estado de resultados o que se yo otros reportes que nos soliciten los contadores. Es un estándar contable 100%. De hecho al parecer, podrían existir 'subtipos', pero aún estoy aclarando eso con los contadores...
Lo del encabezado del XML, se debe solicitar únicamente al momento de generar dicho XML.

**Comment by RigoFlores** [comment]
Seguro debe ser un retrabajo y muy probablemente no séa el primero ni el último; todo esto se ha ido presentando con el aprendizaje de este proyecto (contabilidad básica). Los contadores ya hasta me llaman 'colega'... hay que aprenderle muchas cosas mas aún... y la idea no es volverme contador, pero si que lo poco que aprenda, sea firme como para respaldar las funciones de la aplicación.
De hecho, tan solo de ver el XSD, se debió asumir que este header no va a nivel de póliza individual, pero bueno... así el tema...

**Comment by jccastillo0007** [comment]
Correcto, no es el primero ni el ultimo.

Y si, cuando vi el schema vi que no empataba el scope de los datos, pero
dejo que las cosas caigan por su propio peso, si no, no avanzo y la
practica me ha dictado que solo con el tiempo y el feedback de los
usuarios, es que podemos entender bien que es lo que se ocupa, por eso no
todo se debe implementar desde el inicio, ya he hecho varios elefantes
blancos y me consume mucho tiempo, mejor asi vamos avanzando a paso seguro.

Saludos.
JC.

2015-07-07 11:56 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Done.
