### ISSUE TITLE
no coloca el mes correcto en XML de las pólizas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#429]
No debe colocar el mes cuando se genera el XML, que obviamente será distinto al mes de la póliza.
si todo se realiza en orden, la balanza y pólizas de JUNIO se cierran en julio, pero el mes que se debe reportar en el XML es junio (06), y no JULIO como lo está haciendo ahora mismo.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Exacto... quedó fijo... jejejejeje
El mes reportado en el XML, debe ser el mes de las pólizas...
acabo de generar el XML con pólizas de agosto y le colocó mes de junio... es decir, si que quedó fixed... jejeje
Mes="06" Anio="2015"

**Comment by jccastillo0007** [comment]
Esta tomando el mes anterior de cuando se genera el XML de polizas, lo 
cuál entonces es incorrecto.

Debería tomar el mes de una de las polizas, ahi ya quedará fuera de 
nuestro control si mezclan polizas de diferentes meses, por lo pronto va 
a tomar el mes de una poliza y ese es el que se va a reportar.

Saludos.
JC.

**Comment by RigoFlores** [comment]
Debe reportar el mes, al que corresponden las pólizas.
La aplicación NO DEBE PERMITIR MEZCLAR MESES al momento de generar el XML.
Yo creo que cuando solicitas generar el XML, debe preguntar en ese momento el mes y año.
Entiendo que por lo pronto quedó 'a criterio y responsabilidad del cliente', pero quién debe asegurar que todo está bien, es la aplicación... para eso es y debe ser siempre enfocada app (a prueba de pen..sarse), que no???

**Comment by RigoFlores** [comment]
Sigue igual el problema. Generé el XML para el mes de Julio, y en mes le asignó '06'.

**Comment by jccastillo0007** [comment]
mmm.... el xml de polizas se genera  a partir de lo que seleccionen en el criterio de busqueda en la pantalla de busqueda de polizas.

**Comment by jccastillo0007** [comment]
Lo del archivo ya quedo listo.
Hay que revisar como hacemos eso de la validación...

**Comment by RigoFlores** [comment]
Hoy en día existen 2 filtros: fecha inicial y fecha final. Creo que son muy útiles sobre todo para el excel.
En esa misma pantalla, y de manera excluyente con otros filtros se puede pedir mes, año, tipo de solicitud y número de trámite. Este 'filtro alterno' servirá solo para generar el XML
Me parece que en esa pantalla estamos combinando cosas que si bien son resultados a partir de consulta, una cosa es el excel y otra el XML.

**Comment by jccastillo0007** [comment]
mmmm muy confuso, manejar fechas + mes y anio... en todo caso, mejor generar otra pantalla exclusiva para generar el XML de polizas.

**Comment by RigoFlores** [comment]
OK, me late. Un menú de Pólizas para (a) Captura, (b) consultas y (c) generación de XML. Todos debajo del menú de Pólizas

**Comment by jccastillo0007** [comment]
Podemos cerrar este ticket ? Hay que abrir otros tickets que se refieran exactamente a cambios en el menú.
