### ISSUE TITLE
pantalla de pólizas - validar la captura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#430]
Debe solicitar todos los datos obligatorios para la póliza, ya que durante la prueba se fue una transacción sin concepto y no avisó; cuando generé el XML se fue sin concepto,  marcando el error correspondiente el validador del sat.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Ahora permitió guardar la póliza, sin capturar una sola transacción.
El nodo transacción, va de 1 a n, según la especificación y xsd respectivo.
En conclusión, debe capturarse al menos una transacción con TODOS SUS DATOS REQUERIDOS.

Algunos contadores dicen que no debería permitir guardar la póliza cuando no cuadra, pero aún lo estamos validando. Por lo pronto el aviso cuando no cuadra, ayuda muhco.

**Comment by RigoFlores** [comment]
Va avanzando, pero no se consideró lo que comenté arriba, que se debe capturar al menos una transacción.. CON TODOS SUS DATOS REQUERIDOS... lo cual es entre otros concepto...
Permite guardar la póliza, aún cuando en la transacción, no se capturó el concepto. Ese es el nuevo error...

**Comment by jccastillo0007** [comment]
Fixed.
