### ISSUE TITLE
No en todos los casos genera el XML de pólizas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#431]
No he detectado bajo que circunstancia, pero no siempre generar el XML de pólizas.
Anexo evidencia... aquí capturé 2 pólizas, e inmediatamente me fui a generar los XML, pero solo generó el de Balanza... aunque el mensaje incluso indica que si generó los 2..

![error poliza](https://cloud.githubusercontent.com/assets/2912775/8529397/5938a4c6-23df-11e5-9e69-8a818900726f.png)

**Comment by jccastillo0007** [comment]
Mmmmmm checa si sigue sucediendo... ojo... el XML seguramente va a estar mal con los cambios que he hecho.... aún me falta darle una shaineada.

**Comment by RigoFlores** [comment]
Dado que ya cambió el proceso de generar el XML de pólizas... esta ficha, pierde sentido... ahora a revisar por otro lado
