### ISSUE TITLE
Pólizas cuando cierras un mes, no debe permitir capturar pólizas de meses anteriores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#432]
Por ejemplo, para cerrar julio...

a) Debe validar que los meses anteriores deban estar cerrados. Evidentemente, debe identificar a partir de que mes, empieza 'la historia' de la captura....
b) Una vez cerrado Julio-2015, no debe permitir capturar pólizas de junio, mayo, etc. del 2015

**Comment by jccastillo0007** [comment]
Definitivamente no esta considerando varios escenarios que no conozco.

Puedes listar todos los escenarios que se deben considerar para el cierre
y/o generación de balanzas.

Varios de los escenarios los mencionas conforme avanzas en las pruebas,
pero yo necesito conocer todo lo que se debe involucrar para poder hacerlo
desde el principio, porque además me toma tiempo probar y considerar
escenarios que yo no me imagino.

Saludos.
JC.

**Comment by RigoFlores** [comment]
Si es posible, lo que sucede es que para nosotros 'los contadores', es evidente que no puedes cerrar un mes, si alguno atrás está abierto... jeje.
Y tampoco puedes capturar del mes de enero, si ya haz cerrado hasta junio por ejemplo.
Eso tendría que ser una complementaria, y aún no vemos ese tema.
Aquí lo importante, es definir una fecha de inicio de la contabilidad. Cómo se te ocurre que deberíamos definirla? Quizás con la fecha de la primera póliza capturada... o quizás con el primer mes que cierren en la balanza... eso debería ser nuestro 'punto de partida', para que nada hacia atrás se pueda capturar...

**Comment by jccastillo0007** [comment]
Por ahora es responsabilidad de ellos que mes cierran y que mes no... supongo al inicio si se puede dar el caso de tener un desmadre.... como con las declaraciones, cuando empiezas a declarar a partir de un mes y luego te regresas a arreglar el cochinero..

El sistema ya valida que no se puedan capturar polizas de un mes ya cerrado, pero no de meses anteriores, hay que esperar a que la experiencia nos diga si hay que validarlo o no, ya que no suena muy fácil identificarlo..

**Comment by RigoFlores** [comment]
En este momento, solo capturé una póliza de junio, y ya no me permite capturar mas pólizas para junio. Puedes revisar y la balanza no está cerrada.

**Comment by RigoFlores** [comment]
Si puedes chécalo, para conocer que sucede... yo voy a detener mis pruebas, ya que son 'destructivas'... así que tengo que borrar todo nuevamente...

**Comment by jccastillo0007** [comment]
puedes continuar con tus pruebas destructivas.... solo era un problema en un query.

**Comment by RigoFlores** [comment]
cuando retomé mis pruebas el día de hoy, ya todo estaba mas que devastado... no había un pinche byte vivo en la batería de datos...

**Comment by jccastillo0007** [comment]
No pues no, la BD cambió, recuerdas que sacamos algunos datos de nivel de
póliza que ya no aplican, que solo se capturarán a nivel general al momento
de generar el XML, esos cambios impactan código y bd.

Esperate a que liberemos a PRO con la gasolinera, ahi si que habrá desmadre.

Saludos.
JC.

2015-07-08 12:03 GMT-05:00 RigoFlores notifications@github.com:
