### ISSUE TITLE
el reporte excel de varias pólizas con las columnas 'chuecas'

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#433]
Las columnas Tipo de Solicitud y No de tramite/orden..... 
No sé si están de mas, o dado que no incluyen esos datos al momento de generar el reporte de pólizas, se recorren las columnas en el excel, quedando chuecas las columnas...

**Comment by jccastillo0007** [comment]
Fixed.

Se eliminaron las columnas Tipo de Solicitud y No. de Tramite/Orden.
