### ISSUE TITLE
En las pólizas, no cambia al color verde con cantidades iguales a 2 decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#434]
No estoy seguro si tiene que ver con que las cantidades incluyen hasta 2 decimales, es decir:

abonos: 2616.6 y 418.66
cargos: 3035.26

Las cantidades, incluso en pantalla son iguales, pero no cambian al color verde.

Me pide confirmación para guardar... y guarda todo bien, pero no está detectando que las cantidades con 2 decimales son iguales...aparentemente por ahí está el problema

**Comment by jccastillo0007** [comment]
no lo has corroborado ?
algo falta?
algo no funcionó?
o que pasó?

**Comment by RigoFlores** [comment]
no estaba listo... no me reportaste que estaba corregido... lo acabo de validar y cerrar
