### ISSUE TITLE
Solicitar confirmación al momento de cerrar una balanza mensual

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#435]
Este proceso es algo muy delicado. Necesitamos que el cliente esté consciente de lo que está a punto de ejecutar.

No se podrán capturar pólizas adicionales para el mes X
Los saldos finales serán trasladados como saldos iniciales del siguiente mes
¿Está seguro que quiere cerrar la balanza del mes-año?

**Comment by RigoFlores** [comment]
Tampoco fue atendido...

**Comment by jccastillo0007** [comment]
Done, check it out in PRU.

**Comment by RigoFlores** [comment]
Puedes indicar el año y mes pls?

"La Balanza correspondiente a 2015-01 será cerrada definitivamente.
¿Desea continuar?"

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
En pruebas, en la cuenta de la tia, elijo enero 2016 en la pantalla de balanza, y al darle cerrar para validar este issue... me manda al internal error

**Comment by jccastillo0007** [comment]
algo falto de subir, pero ya esta jalando.
