### ISSUE TITLE
No traslada saldos finales a iniciales, cuando se brinca un mes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#436]
Una cuenta que se utilizó en junio si, julio no, agostó si...
No traslada su saldo de junio para agosto... aunque se haya cerrado la balanza de junio y julio...
Es decir, no está resuelto el tema añejo aquel, que no transfiere todos los saldos finales a iniciales, aún cuando no se ocupe una cuenta en un mes... eso es común

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
si lo hizo, aunque aún no me queda claro si lo trabajará correctamente en todo caso.
Por lo pronto si lo cierro, sin embargo necesito hacer otra prueba.
Hay que borrar únicamente las tablas de pólizas y balanzas.
El catálogo de cuentas, hay que dejarlo así como está.

**Comment by RigoFlores** [comment]
Esta es la ficha que levanté en su momento... lo que no dice, es porque pensaba que quizás no trabajaría bien en todo caso...
