### ISSUE TITLE
el tipo de póliza no es parte del header del xml, amén que se repite

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#437]
El tipo de póliza, existe en la pantalla de pólizas y en la de consultas.
Solo debe existir en la pantalla de pólizas.

**Comment by jccastillo0007** [comment]
No es parte del header, pero tu dijiste que es un atributo de cada poliza que será utilizado mas adelante, tengo que guardarlo por poliza.

Se repite porque en las consultas se podrá filtrar por ese campo.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Este atributo será utilizado en reportes, mas adelante.
Al indicar que no era parte del header, me refería a que no debería aparecer como requerido para generar el XML. 
Ahora mismo ya quedó OK
