### ISSUE TITLE
Dar opción de editar las cuentas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#438]
Creo que los datos a editar serían el nombre y el saldo inicial.
El saldo inicial, siempre y cuando no se haya utilizado la cuenta en alguna póliza.
El saldo inicial, siempre y cuando, sea una cuenta del mas bajo nivel.

**Comment by RigoFlores** [comment]
El nombre se podría editar, pero no el número de cuenta. Incluso cuando ya ha sido utilizado en alguna póliza... que ahí lo ideal, sería darle un update a toda póliza que ocupó ese nombre anterior...

**Comment by jccastillo0007** [comment]
Too complicated.

**Comment by RigoFlores** [comment]
Por un lado está que al agregar la cuenta de bancos por ejemplo, si el cliente maneja un solo banco, sugerir el nombre de 'BANCOS NACIONALES' como el SAT lo tiene, pero dar la opción que lo puedan cambiar.

**Comment by RigoFlores** [comment]
OK, como lo resolvemos entonces???
1.-Editar una cuenta cuando ya la capturaste
2.-En el nombre de la cuenta por parte del SAT (por ejemplo BANCOS NACIONALES), sugerirla pero dar opción de modificarla.
