### ISSUE TITLE
Mover menú de consultas, debajo del menú de pólizas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#439]
Lo que faltará después son reportes... que son estándares, como el estado de resultados, balance general, y otro financiero que no recuerdo su nombre... esos son reportes ejecutivos estándares dentro de la contabilidad.
La consulta de pólizas solo será para pólizas, so tendría que estar debajo de pólizas, o en un menú específico para las pólizas.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
realmente lo que quise decir, es a un subnivel de pólizas.. pero nada, ahí lo dejamos por lo pronto
