### ISSUE TITLE
EN QUE SERVIDOR CORRERÁ EL FACTURA-T WEB?

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#44]
EN QUE SERVIDOR, CON QUE REQUERIMIENTOS, ESPACIO EN DISCO, CONCURRENCIA MÁXIMA, ETC?

**Comment by jccastillo0007** [comment]
3 fases.
1. Voy a crear un servidor dedicado a eFacturaT, solo para la parte web, con las mismas caracteristicas del servidor de produccion, esto sera durante un periodo en el cual estaremos probando y puliendo el sistema
2. Unificar los dos servidores de produccion, para que ahora ya exista unicamente un servidor
3. Crear una granja de servidores que pueda crecer y disminuir automaticamente, en base a las estaidsticas de uso del portal

Empezamos con fase 1, para pasar a fase 2 seria cuando el sistema este ya limpio de defectos y completo... la fase 3 seria practicamente hasta que tengamos una utilizacion muy alta del sistema.

El disco duro se puede ir creciendo si es que lo requerimos, voy a generarlo con 2 gb en RAM y la concurrencia la controla tomcat y mysql, lo cual tendremos que hacerle el tunning adecuado.

JC.
