### ISSUE TITLE
Subir los botones de guardar y cancelar en la pantalla de agregar producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#441]
Si ayudará implementar este cambio, pero ya revisé el problema de origen.
La pantalla de agregar producto, se desplegará completa o incompletamente dependiendo de que 'tanto escrol' hayan recorrido la pantalla de facturación. Si suena raro, pero el hecho es que así está.
Indudablemente ayudará la implementación de este cambio, pero la pregunta sería... hay manera de que la posición de la ventana de agregar producto, al abrirse sea 'controlable'?

**Comment by jccastillo0007** [comment]
Done.
Te recomiendo que les recomiendes que compren un monitor touch screen, asi será mucho mas rápido.

**Comment by RigoFlores** [comment]
Hasta donde conozco, ninguno de nuestros clientes maneja touch screen, según yo principalmente en restaurantes se podría ocupar, .....en una gasolinera con toda la grasa que se maneja ahí, no veo funcional el touchscreen... pero si les comentaré...

**Comment by jccastillo0007** [comment]
Para uso rudo hay protectores especiales y micas que permiten el 
funcionamiento del touch screen sin que se ensucien de grasa.

Saludos.
JC.
