### ISSUE TITLE
Implementación de la factura express - Facturar 1 solo producto.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#442]
Una sola pantalla donde puedan elegir:
a) RFC o Nombre receptor
b) Método de Pago / Cta (No Identificado por Omisión)
c) Condiciones de Pago (Contado por omisión).
d) Serie (cuando aplique)
e) Producto  (id o nombre)
f) Cantidad
g) Precio unitario

**Comment by RigoFlores** [comment]
En caso de depurarse aún mas, podría ser colocar el método de pago y cuenta, como 'No Identificado', aunque ese dato si se ocupa en la CE.
Podría también eliminarse el precio unitario, aunque si es de mucha ayuda al momento de facturar, ya que no siempre ofreces el mismo precio por el mismo servicio.
El IVA a aplicar es el estándar por omisión 16%.

**Comment by jccastillo0007** [comment]
Hay que platicarlo cuando tenga la pantalla a la vista, (hoy en la tarde)
porque si no, no me imagino como quedaría.

Al rato te busco.

Saludos.
JC.

2015-07-20 11:42 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Falta la funcionalidad a la medida de los Gasolineros, que finalmente para ellos nació este requerimientos que pronto se extenderá a todos los clientes

**Comment by jccastillo0007** [comment]
Como sabes ? probaste en Producción ?

No encontré datos en PRU para hacer pruebas, y revisando el código, el proceso de timbrado es el mismo, no detecté una razón por la cuál no se realice le proceso de gasolineros.

**Comment by RigoFlores** [comment]
En producción anunciaste su liberación, y si no hubo pruebas hoy???
Tons si, probé en producción, con la cuenta de la tia.

**Comment by jccastillo0007** [comment]
También vi que después de facturar, te manda a la pantalla de factura normal, y no a la pantalla de factura en chinga.

**Comment by jccastillo0007** [comment]
Fixed.... checatesa  y me dices para subirlo en chinga a PRO...

**Comment by jccastillo0007** [comment]
oye cómo le pongo al menú ?

**Comment by RigoFlores** [comment]
Factura ágil, Factura rápido, Factura simple, Factura veloz..... casi todos ellos también son competencia, so... me late la primera...

**Comment by RigoFlores** [comment]
Capturé gasolina magna, en la cuenta de la tia, tal cual está en producción para los gasolineros, y no jaló... al darle facturar se 'quedó en el avión'... en la pantalla gris, que y nunca mas regresó...

**Comment by RigoFlores** [comment]
en espera que se arregle el desmadre de pruebas...

**Comment by RigoFlores** [comment]
En una factura estándar, ya jala bien al parecer.

En una factura de los gasolineros, en pantalla presenta datos incorrectos de subtotal, iva y total, pero en el pdf, una vez generada presenta los datos correctamente. 
En el XML es el problema, ya que no reporta correctamente las tasas de los impuestos (para cuando gasolineras)...

```
<cfdi:Impuestos totalImpuestosTrasladados="32.818966">
    <cfdi:Traslados>
        <cfdi:Traslado impuesto="IVA" tasa="0.16" importe="27.316966"/>
        <cfdi:Traslado impuesto="IEPS" tasa="0.032226" importe="5.502001"/>
    </cfdi:Traslados>
```

Debería ser 16.00 y 3.2226 para iva e ieps respectivamente...

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Al parecer ya quedó, hice prueba con factura estándar y factura gasolineros (magna y premium) y jaló OK...
Entonces ya podemos liberar esta parte a producción...
