### ISSUE TITLE
No asigna el nombre correcto al XML de pólizas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#443]
Capturé pólizas de junio.
Cerré el mes
Generé el XML para las pólizas de Junio, y aunque el XML lo generó correctamente, el nombre está chueco, ya que le asigna TIA101020BP4201507PL.xml, es decir como si fuera de Julio.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Siempre y cuando, la consulta sea para un solo mes... si jala...
