### ISSUE TITLE
Implementar descarga masiva de CFDIs, del portal del SAT.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#444]
Debe aplicar tanto para emitidas como para recibidas.

**Comment by jccastillo0007** [comment]
Subí a dropbox el archivo Selenium.zip al descompactarlo te va a generar lo necesario para ejecutar el archivo Selenium.bat.

En el archivo Selenium.properties, debes ponder el anio, mes y el folder donde quieres que te baje las facturas, además de el usuario y pwd de la clave CIEC del usuario que quieres bajar las facturas, el usuario que se incluye por default es un cliente nuestro que Fco se pirateo para hacer pruebas jojojo.

La app asi como esta funciona, pero le faltan muchas opciones, quiero que lo pruebes para después platicar de como implementarlo.

**Comment by RigoFlores** [comment]
Así como lo colocaste, tiene los issues:
a) El properties, debe ir en la carpeta Jars
b) Cuando abre la página del SAT, si no me cambio manualmente a la opción de contraseña (por omisión es FIEL), no hace nada. Creo que 'la macro' que ejecuta, no está realizando dicho cambio.
c) Ignora la ruta de windows para descargar los  CFDI's, pero los descarga en 'Descargas' por omisión de Windows.

De entrada SI podría servirnos, pero la veo un poco débil en el sentido que si cambia la URL o navegación en la página del SAT, supongo ya no jalaría. Es un poco lenta, pero entiendo que es porque estamos 'automatizando' un proceso manual.
Repito, si nos puede servir de entrada, pero hay que seguir buscándole un proceso mas directo.

**Comment by jccastillo0007** [comment]
Rijo said:

La aplicación Descarga-T, podrá funcionar en 2 sentidos:
1.       Junto con la CE que lo hace operar en la Web,
2.       y en versión escritorio  o incluso web (desintegrada o desacoplada del web) para que el cliente pueda descargar sus facturas de manera independiente a la suite Factura-T on line.

a)      Se podrá acceder configurando la CIEC o FIEL del cliente (este requerimiento, podría quedar pendiente, pero si es CIEC, debe hacer el cambio en automático al momento de ingresar).
b)      RFC
c)       Mes
d)      Año
e)      Vigentes, Canceladas o ambas
f)       Recibidas o Emitidas  (para CE se ocupan ambas).
g)      Por omisión debemos descargar en un directorio como en la facturación a partir del directorio donde está instalada la aplicación o similar, esto es por ejemplo:  c:\Selenium\Descargas\RFC\Recibidas\Año\Mes por ejemplo c:\Selenium\Descargas\TIA101020BP4\Recibidas\2015\Julio
h)      Dar opción de generar ‘PDF Alterno’, esto es no sería el PDF original sino oootra auténtica representación impresa del XML. Creo que esto estaría muy chido… (ya tenemos el PDFor, hay que explotarlo). No se lo he visto a nadie, y por lo que entiendo, no estamos violentando nada, ya que simplemente refleja el contenido del XML

Para la versión de escritorio, adicionalmente
1. Vaciado de todos los XML en un archivo Excel, conteniendo todos y cada uno de los parámetros del XML, es decir contará con un header y un detalle de la factura.

**Comment by RigoFlores** [comment]
Podemos arrancar con solo CIEC, pero se ocupa para la contabilidad electrónica, tanto la emision como la recepción.

**Comment by jccastillo0007** [comment]
Por ahora con estas limitantes :)
a) Solo CIEC
e) Solo recibidas
f) Esta aplicación estará disponible solo en versión web, por lo tanto, este tema de donde se bajan hay que revisarlo
g) No creo adecuado generar una version de escritorio, e incluso una version desacoplada a eFacturaT, porque ? 
    1. Escritorio es tecnologia vieja, y se requiere conexion a Internet, con lo cuál ya no hay excusas para que los clientes no quieran
    2. No es mantenible y eso con lleva a que no es escalable, y se arma un desmadre de versiones, tal cual esta sucediendo con FacturaT Standalone
    3. LLevaría mucho tiempo
    4. Todo cliente puede tener un usuario en la version web, aún cuando solo usen el descargat

El tema del vaciado a un archivo de excel, se puede hacer aún en la versión web, no necesariamente debe ser standalone.

**Comment by jccastillo0007** [comment]
Versiones
1. Ponerle una cara o una pantalla a lo que esta funcionando ahora mismo
   1.1 Pantalla para consultar los XML ya bajados
2. Generar PDF's
3. Descarga de facturas vigentes y/o canceladas y/o ambas
4. Descarga de facturas emitidas
5. Generar el excel chacarron con la info de los XML.

**Comment by jccastillo0007** [comment]
Ya empecé este desarrollo, puedes ver en PRU como va....

Stay tune...

**Comment by jccastillo0007** [comment]
Esta metiendo ruido al momento de timbrado, es un problema con una libreria utilizada con archivos XML.

**Comment by RigoFlores** [comment]
es decir???

**Comment by RigoFlores** [comment]
Intenté probarlo en pruebas, pero no hizo nada....

**Comment by jccastillo0007** [comment]
Que hacer con los XML Recibidos:
a) Agregarlos a las consultas para compras, entiendo que esto implica realmente almacenarlos en tablas correspondientes.
b) Generar opcionalmente el PDF
c) Renombrarlos a rfcEmisor_rfcReceptor_total_fechaEmision. Esto ayudará a elegirlos o asociarlos en las pólizas de la contabilidad. Se ocupan ambos rfc's, ya que un cfdi puede ser emitido o recibido, para propósitos de la contabilidad.
d) El cliente podrá hacer una consulta para descargar los XML a su equipo de cómputo, para el caso de los clientes que solo ocupen esa función.

**Comment by jccastillo0007** [comment]
Este ticket esta repetido con el número 478

**Comment by RigoFlores** [comment]
ok
