### ISSUE TITLE
Depurar el inbox cfdi (recibefactura-t.com.mx)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#445]
Ahora mismo se replica y almacena n veces el mismo correo recibido en el inbox.
Yo creo que mas que guardarse el correo, se debe llevar un registro en alguna tabla de las facturas recibidas por correo, con los generales de la factura, tipo el reporte en excel que generamos desde la pantalla de consultas.
Guardarlo en el inbox, no le veo el caso y si causa problemas. Ahora mismo lo acabo de depurar, pero seguramente se perdieron ya correos de los españoles intentando subir sus facturas al portal web.

**Comment by jccastillo0007** [comment]
Negativo, este problema ya fue arreglado desde hace tiempo, hoy en día ya no hay correos en recibefacturat@factura-t.com.mx

**Comment by RigoFlores** [comment]
Comenté arriba, que HOY LO DEPURÉ, y los 2 últimos correos que habían, son del warning que ya se había llenado. De hecho no había correos de julio de facturas, por ello creo que voy a tener que reenviar las facturas de julio de los españoles.
En bandeja de entrada no había nada, pero en el procesados SI ESTABAN TODOS; para el caso el espacio es el mismo y se saturó...

**Comment by jccastillo0007** [comment]
Chaaaaa, ok, dejame estar al pendiente, eso debería de haber quedado listo...

**Comment by RigoFlores** [comment]
Hay que reclamarle a Fco... chiaaaaa.... alguien debe ser culpable de semejante atrocidad..

**Comment by jccastillo0007** [comment]
Al dia de hoy tanto las cuentas de recibefactura y testrecibefactura, están vacías, lo cuál significa que si se ha estado depurando.

La cuenta de contacto si tiene mas de 100 mensajes, no los borré porque creo que tu la checas no ?

**Comment by RigoFlores** [comment]
Ya revisé también y está limpia, y las factura de los españoles, aparentemente bien.
Lo cerraremos y estaré revisando en unos días
