### ISSUE TITLE
Liberar el descargaT a producción.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#446]
Para empezar a probarlo y ofrecerlo...
Ahora mismo debe jalar para los gasolineros...

**Comment by jccastillo0007** [comment]
Done.
https://efacturat.com.mx/DescargaTuCFDi
Favor de validar cuidadosamente.

**Comment by RigoFlores** [comment]
Mas o menos, porque el comentario de validar con cuidado?
A qué precisamente le debo prestar especial atención?

Empezaré validando con la cuenta de la TIA y enseguida la gasolinera.

**Comment by RigoFlores** [comment]
entré con el rfc de la tía, pero en la sección de generar factura, no aparece ningún rfc emisor.
Entiendo que falta configurar los rfc's emisores (clientes nuestros), que podrán acceder a esta función. Por lo pronto la tia y los gasolineros...

**Comment by jccastillo0007** [comment]
cierto... no me acordaba de esta configuración.

Mi comentario de que pruebes cuidadosamente, es solo para ponerte nervioso.

Ya están configurados.

**Comment by RigoFlores** [comment]
chiaaaaaaa...... jajajaja

**Comment by jccastillo0007** [comment]
Hoy vuelvo a subir la app a PRO.

**Comment by RigoFlores** [comment]
En cuál url lo encontraré ahora?

**Comment by jccastillo0007** [comment]
https://efacturat.com.mx/DescargaTuCFDi

**Comment by RigoFlores** [comment]
Cerraré que ya se posteó, pero por ahí tenemos detalles en otros issues.
El resultado es que hoy no puedo ni validar en pru, las correcciones de issues levantados en pro..
