### ISSUE TITLE
Error en la consulta de producción web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#447]
Con la cuenta de la tia, consulté filtrando por rfc emisor PPR910701LEA, por numero de folio y por fecha, en 3 consultas distintas, y en todas me arroja repetidos el folio 42.
Validé en el SAT y realmente solo se emitió una factura con los datos de la 42. 
Que estará pasando?

**Comment by RigoFlores** [comment]
![error produccion](https://cloud.githubusercontent.com/assets/2912775/8855995/c343e9a6-312d-11e5-81ef-6a933efddd59.jpg)

**Comment by jccastillo0007** [comment]
Pssss ya cheque la DB, y si, hay 5 registros iguales, y unicamente el último esta timbrado... peeeero no te puedo decir que pasó porque esta factura que es desde 22 de agosto 2014, y no tengo logs disponibles jojojo.

**Comment by RigoFlores** [comment]
OK, aquí lo importante, creo yo es:

a) podemos eliminarlos sin pegarle a la aplicación?
b) la mas importante... podemos saber si los clientes tienen alguna situación similar, discriminando los folios que realmente si están duplicados, ya que se han dado caso?
c) podemos contar con un listado de folios 'brincados' en los clientes?

**Comment by jccastillo0007** [comment]
para la pregunta c), existe una tabla llamada ReusableFolios, ahi se guardan los folios que deben usarse la siguiente vez, pero se van borrando conforme se usan.

Hay que hacer un rediseño de este manejo de folios.

**Comment by RigoFlores** [comment]
OK, que hacemos con este issue?

**Comment by jccastillo0007** [comment]
Sigue vigente este team ?
Podemos cerrar este ticket ?

**Comment by RigoFlores** [comment]
Pues si no se corrigió, y no se propuso una solución... que sugieres que hagamos?
Hacer como si nunca hubiese existido?
Ni siquiera tenemos el listado de los folios repetidos....

abriré otro ticket con una propuesta que tengo...

**Comment by jccastillo0007** [comment]
Cerrarlo como Won't Fix, y abrir otro ticket en cuanto suceda otro problema
similar, para poder revisar logs.

Saludos.
JC.
