### ISSUE TITLE
No envia la variable subtotalSD al PDF en Web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#448]
Para los clientes que manejan descuentos no se está enviando la variable subtotalSD (que es el subtotal - montoDescuento).
Por cierto, para los clientes que No manejan descuento... tampoco se envia dicha variable..

**Comment by jccastillo0007** [comment]
Corrección, si se estaba enviando, pero con el subtotal, faltaba restarle el monto descuento.

**Comment by RigoFlores** [comment]
Lo tenemos listo en producción?

**Comment by jccastillo0007** [comment]
Negativo.

Ya esta probado en PRU ?

**Comment by RigoFlores** [comment]
Lo acabo de probar, le agregué la impresion de la variable subtotalSD y con el preview marcó error al generar el PDF. Antes de agregar la variable jaló bien.
Con la cuenta de la tia en pruebas. Ya tiene configurada esa plantilla con la variable en cuestión

**Comment by jccastillo0007** [comment]
Aproveché la prueba que hiciste, y vi este valor en la variable en cuestion :  
subtotalSD=$50.00

El error del preview fué por :  

net.sf.jasperreports.engine.JRException: Resource not found at : base_products.jasper

Esta usando un template customizado llamado  :  /eFacturaT/customers/TIA101020BP4/setup/cfdi_base.JRXML

Observaciones, la extensión del archivo debe estar en minúsculas.
En el directorio /eFacturaT/customers/TIA101020BP4/setup/ falta el archivo que esta buscando base_products.jasper

**Comment by RigoFlores** [comment]
OK, yo solo subí el jrxml, tons subo el products.
Asumí que lo tomaba del repositorio genérico.

**Comment by jccastillo0007** [comment]
So what ?

**Comment by jccastillo0007** [comment]
is it fixed?

**Comment by RigoFlores** [comment]
No lo puedo validar ya que no timbra. A nivel preview si la muestra, pero la prueba es completa, hasta el timbrado y ver las variables correspondientes en el xml

**Comment by RigoFlores** [comment]
Listo en pruebas
