### ISSUE TITLE
No podemos timbrar en pruebas - distribuidores esperan para hacer pruebas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#449]
Para el multiconector se ocupan los siguientes rfcs emisores en el ambiente de pruebas, con 10000 folios c/u:

XAXX010101000
XEXX010101000
GAGS751015F56

**Comment by jccastillo0007** [comment]
Done.

Ufff le encontre el pinche defecto a la configuración de puertos.

Yo di de alta el cliente XAXX010101000, con estos queries puedes dar de alta los otros dos, no se que nombre quieras ponerles.

Nota. En la base de datos de timbres, ya estan dados de alta los 3 RFC con 10000 folios.

insert into ClientConfiguration (owner,sendEmailsToSource,sendEmailsToTarget, licenseType) values ('XAXX010101000',0,0,1);

select \* from ClientConfiguration where owner = 'XAXX010101000';

insert into Client 
(branchName, branchType, clientType, country, dateOfJoining, memberSince, owner, 
rfc, name, neighborhood, number_ext, number_int, municipality, state, street, zipcode, 
clientConfiguration_Id, contact, emails)
values ('MATRIZ',0,1,'MEXICO','22/06/2015','06/2015', 'FacturaT',
'XAXX010101000','Empresa de pruebas S.A. de C.V.','ANDALUCIA','101','C4','ZAPOPAN','JALISCO','ANDALUCIA','45645',
'3', '','');

select id from Client where rfc = 'XAXX010101000';

insert into Users (password, role, userId, client_id) values ('test',0,'XAXX010101000',5);

insert into ClientPlugins (features, owner) values ('["ADDENDAS","EXTRA_DATA_IN_CFD","CARTA_PORTE","GASOLINERIAS","CE"]','XAXX010101000');
