### ISSUE TITLE
Cuando genero remisión, marca error al consultar en descargaT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#450]
Generé una remisión con la cuenta de la TIA. Tiene plugin de gasolinera.
Probé inicialmente generando una remisión simple, es decir sin ieps y todo el desmadre, sino solo iva.
Al momento de consultar en descargat, es decir ingresando el folio, fecha y total, se va al internal error.
Quizas porque no es un producto con ieps, y el desmadre de combustibles.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
La falla la detecté en producción. Dices que ya está corregido, supongo que en pruebas.
En caso afirmativo, cuál sería la URL en pruebas para probarlo.
Como quiera estamos detenidos en ese ambiente, ya que no se puede timbrar...

**Comment by RigoFlores** [comment]
OK, finalmente pude entrar al descargaT, me registré con este rfc GAHC800430N26, pero al buscar una remisión que acababa de hacer, no encontró nada, y para propósitos prácticos no pude generar una factura desde el descargaT. Ha sido muy largo este proceso que validé hace ya varias semanas, y ahora no se que pasó, pero no está jalando con facturas estándar. Aún ni siquiera he empezado a probar gasolineros

**Comment by RigoFlores** [comment]
Corrijo, el tema era que no es claro el folio de la remisión. No existe en el PDF de la remisión, y hasta que no hago una consulta de las remisiones generadas, no conozco dicho folio.

**Comment by jccastillo0007** [comment]
Entonces el tema es que no se conoce el tracking id ?

Sabes si la plantilla ya lo espera ? o necesitamos otra plantilla ?

Saludos.
JC.

2015-08-06 21:19 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Digamos que ya probé y al parecer está listo.
Lo que falta es que me envíes en una nueva variable, el ID para que se incluya en la remisión.
En cuanto me digas como se llama la variable, yo hago el ajuste en la remisión y te la envío.
Por cierto como se llama esa remisión genérica del jasper?

**Comment by jccastillo0007** [comment]
la variable es trackingId, no recuerdo el nombre del template generico,
creo que esta en el dropbox.

Saludos.
JC.

2015-08-07 10:43 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Necesito validar con la plantilla que te envié de remisión...

**Comment by RigoFlores** [comment]
Aún no queda el descargat en pruebas, de hecho no he recibido avance en varios días...

**Comment by jccastillo0007** [comment]
No has recibido avance en varios dias, porque no he hecho nada en varios dias del descargat, de hecho no se que es lo que falta, lo ultimo que supe fue que tenia que enviar el tracking id a jasper y que cambiaste las plantillas.

No se cuál sea el problema o que es lo que falte por hacer.

**Comment by RigoFlores** [comment]
Ya validé y cerraré el issue. 
Me siguen faltando los datos del servidor de pruebas (ip, usr y pwd).
