### ISSUE TITLE
se encuentra abajo el ambiente de pruebas, o no se puede acceder

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#451]

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Que fue lo que tenía. Tengo la impresión que se fue degradando su performance.
Incluso lo noto lento

**Comment by jccastillo0007** [comment]
Se acabo la memoria del tomcat, ahorita es full hay que ver si se vuelve a degradar para ver si requiere de hacer tunning

**Comment by RigoFlores** [comment]
Está super lento... de hecho ya se quedó 'en el avión' durante el timbrado...

**Comment by jccastillo0007** [comment]
No se porque se acaba la memoria, ya esta bien configurado.

Por ahora quité el descargaT para ver si es eso.

**Comment by jccastillo0007** [comment]
Checatesa y me dices.

La ruta para el descargat es : http://efacturat-stagging.com.mx/DescargaTuCFDi

**Comment by RigoFlores** [comment]
después que le di generar una factura express, para gasolineros, se quedó en el limbo... y ahora ya no puedo acceder al sistema... algo sigue notoriamente chueco..
