### ISSUE TITLE
Implementar el complemento de servicios parciales de construcción

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#452]
ya está documentado en un correo.
OJO, la particularidad de este complemento es que lleva el domicilio de la obra, que es casi igual a todos los domicilios que manejamos, EXCEPTO POR que el estado, se toma del catálogo del SAT.
Con ello en el XML se reporta un código de estado, y al PDF me deberás enviar la descripción.
Aquí hay de 2... o se genera una tabla con dicho catálogo, o en los datos extra para este complemento se le agrega la lista para que elijan la entidad federativa (estado).

**Comment by jccastillo0007** [comment]
Done.
