### ISSUE TITLE
Nomina Empresarial - Vista previa (excel) incorrecto 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#455]
Cuando en un empleado, tienes algunas deducciones o percepciones en estado de inhabilitado, el excel los incluye en el total de percepciones y deducciones de la vista previa.

**Comment by jccastillo0007** [comment]
No lo pude reproducir, con la cuenta de la TIA, saque un reporte y luego des habilite las percepciones de un cliente, y al sacar otro reporte lo descontó de manera correcta.

Te mando por correo los dos reportes que obtuve, tal vez sea un escenario mas complejo donde lo viste.

**Comment by jccastillo0007** [comment]
Podemos cerrar este ticket ?
