### ISSUE TITLE
al momento de exportar la balanza al excel, dar la opción de indicar nivel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#457]
Por ejemplo HASTA nivel 1, nivel 2, nivel 3, o todos los niveles

**Comment by RigoFlores** [comment]
Igualmente, esta función la contiene prácticamente todo paquete contable.
Cuando quieres exportar la balanza, le indicas hasta que nivel quieres incluir... nivel 1, sería solo cuentas de mayor, nivel 2 nivel de subcuentas, etc.... el cálculo se hace igualito, solo que se incluirán o nó en el excel, las cuentas que se indiquen...

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
No ví ninguna pantalla que me preguntara hasta cuál nivel quería exportar.
Como es la solución planteada?

**Comment by jccastillo0007** [comment]
en la pantalla de balanza, al darle click en el icono del archivo de excel, te aparece una ventana con las opciones de Todas, 1, 2, 3... 5... no te apareció?

Deja veo en PRU.

**Comment by RigoFlores** [comment]
Negativo, no la ví...

**Comment by jccastillo0007** [comment]
aqui va una imagen..
![screen shot 2016-01-18 at 10 31 43 pm](https://cloud.githubusercontent.com/assets/2245679/12410033/602950fe-be36-11e5-93aa-6e731dc3898d.png)

**Comment by jccastillo0007** [comment]
ya lo hice con la cuenta de la TIA, ojo... debes elegir un periodo, es decir, tipo de balanza, mes y año, para que te salgan las opciones de cerrar balanza e incluso exportar a excel, esa parte no cambia.

**Comment by RigoFlores** [comment]
Si, anteriormente no aparecía... pero ya lo ví...
Es posible hacerlo tipo check button, que entiendo se elige una u otra opción.. es decir, no tiene sentido solicitar el nivel 5 y el 1... 
es uno u otro... incluso, si le puedes agregar el 0, estaría bien... jeje

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Funcionó bien lo de radio button, lo malo es que ahora la balanza ya no le hace caso al nivel seleccionado. Ahora la genera con todos los niveles incluidos

**Comment by jccastillo0007** [comment]
el tema es comprender como funciona ese número que eligen.

El número que eligen es el nivel desde el cuál se empieza a exportar las cuentas, si un cliente tiene cuentas de todos los niveles, y eligen el nivel 2, entonces se van a exportar las cuentas con nível 2,3,4 y 5, y así sucesivamente, esta bien asi, o solo se quiere exportar justo el nivel que eligieron.

**Comment by RigoFlores** [comment]
OK, yo pensaba igual que cuando estaba antes de este último cambio...
Eliges 1 y solo incluye nivel 0 y 1
Eliges 3, entonces incluye niveles del 0 al 3
Eliges 5, y es igual a incluir todos, es decir del 0 al 5
Eliges 0, pues solo incluye las nivel 0

es decir, a partir del nivel que eliges hacia abajo o atrás, como lo quieras ver puesn
(que no es lo mismo que de la mitad, patras...jeje)

**Comment by jccastillo0007** [comment]
pues una vez entendiendo la idea de como funciona, dime como es mas funcional o como lo han solicitado los clientes y asi lo dejo.

**Comment by RigoFlores** [comment]
asimismo, al elegir el nivel... incluir de ahí hacia abajo...
5 sería todos, 2 sería 0, 1 y 2.... y así sucesivamente

**Comment by jccastillo0007** [comment]
Done.
