### ISSUE TITLE
Completar las pólizas con los datos faltantes: uuid, método de pago, etc

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#459]
para ir cerrando el tema de las pólizas.

**Comment by jccastillo0007** [comment]
Este tema es lo de seleccionar uno o mas CFD para ligarlos a la poliza, me parece uno de los mas importantes features que están pendientes. Voy a trabajar sobre esto, mientras surge otro desarrollo o algo mas prioritario.

**Comment by jccastillo0007** [comment]
Done para la seleccion de CFDis por poliza.

Hay que levantar otro ticket para :  
1. Arreglar la pantalla de generación de xml, ya que se vé muy fea
2. Ver lo del método de pago en las polizas.

**Comment by jccastillo0007** [comment]
Según yo, solo faltarían estos datos :  
sello;
noCertificado;
certificado;
OtrMetodoPago

Tú ves algo mas ?

**Comment by RigoFlores** [comment]
Bueno, realmente además del tema del sello, certificado...se ocupa agregar el método de pago, donde pueden ser 3 nodos distintos cuando se trata de:
Cheque
Transferencia
Otro método de pago.

Es decir, se debe poder elegir uno de los 3 (de manera excluyente), y cada uno tiene sus propios parámetros.
Aún mas... esta información, junto con la del cfdi asociado... forman parte de algo que le llaman auxiliares. Entiendo que estos auxiliares se generan, una vez que las pólizas han sido cerradas (de alguna manera) y no se contaba con la información del CFDI y método de pago.

**Comment by jccastillo0007** [comment]
ups, ya me acordé, esta complicado eso del método de pago.... voy a agregar el sello, certificado y NoCertificado y lo del método lo dejamos pendiente va.

**Comment by jccastillo0007** [comment]
Subí un release a Pru de este tema de polizas, se soportan todos los tres diferentes métodos de pago, pero solo uno de cada uno por transacción

**Comment by jccastillo0007** [comment]
Para los tipos de pago cheque y transferencia, ya se agregan al XML, solo falta la opción otro medio de pago.

**Comment by jccastillo0007** [comment]
Ya esta también soportado el medio de pago otros

**Comment by RigoFlores** [comment]
NO HE TENIDO OPORTUNIDAD DE VALIDARLO. NO SÉ PORQUE LO CERRASTE... SUPONGO QUE DE PUROS TOMPIATES...
