### ISSUE TITLE
HOMOLOGAR ETIQUETAS DE COMPROBANTES FISCALES (FACILITO)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#46]
LAS ETIQUETAS DE LOS COMPROBANTES FISCALES SON LITERALMENTE:
FACTURA (POR OMISIÓN)
RECIBO DE HONORARIOS
RECIBO DE ARRENDAMIENTO
RECIBO DE DONATIVOS
NOTA DE CARGA
NOTA DE CREDITO
CARTA PORTE

LOS TIPOS SON (LITERALMENTE):
INGRESO
EGRESO
TRASLADO

**Comment by jccastillo0007** [comment]
Done
