### ISSUE TITLE
Implementar Factura Periódica

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#460]
La idea es que se pueda definir una fecha para emitir la factura mensualmente.
Partiendo de lo que tenemos ahora, sería como capturar una remisión e indicarle que la facture mensualmente.
Lo ideal es tener un menú independiente, así como la factura ágil, para poder hacer evidente esta nueva funcionalidad

**Comment by jccastillo0007** [comment]
Done....

En la pantalla de facturación, agregué un check box hasta abajo para que la factura se guarde como periódica, y se elige la fecha para obtener el día en el que se debe estar facturando.

Agregué una pantalla para consultar las facturas que se han configurado como periódicas, ahi mismo se pueden eliminar

Por ahora va a generar una factura cada 6 horas, para que configures una factura y te esperes un rato para validar que se ejecutó, no lo pongo mas frecuente porque va a estar generando muchas facturas.

**Comment by RigoFlores** [comment]
Marca el internal error cuando timbra eligiendo la factura periódica; le doy volver con la flecha del navegador y si genera la factura, pues ahí la muestra... como que tiene un detalle ahí... voy a esperar las 6 horas para ver si aparece en las consultas... lo que no entendí porque un menú independiente para las periódicas...

**Comment by RigoFlores** [comment]
Ya fui a consultar las periódicas y no aparece nada ahí... pasaron mas de 6 horas...

**Comment by jccastillo0007** [comment]
Maldito sueño.... ya quedó, de hecho deje configurada un CFDi menstrual con la cuenta de la TIA... deje el periodo de facturación cada 3 horas
