### ISSUE TITLE
Implementar cálculo de IVA con base IEPS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#461]
Unicamente en el caso, cuando una factura aplica los impuestos trasladados de IVA e IEPS, dar la opción al cliente por default SI, que calcule el IVA con base IEPS, esto es, según yo en la ventana de agregar producto:

importe = cantidad \* precio unitario
importeIEPS = importe \* tasaIEPS
IVA = (importe + importeIEPS) \* tasaIVA

En caso de que el usuario decida no capturar con base IEPS, el cálculo se queda como ahora mismo se tiene.

OJO. No tocar la funcionalidad actual de las gasolineras, es decir, el cálculo del IEPS e IVA se mantiene intacto.

**Comment by jccastillo0007** [comment]
Oye, yo creo que el default es NO calcular el iva con base IEPS, ya que es lo que se tiene actualmente, y serán pocos los clientes que quieran hacer ese cálculo para poder chingar al cliente no ?

**Comment by RigoFlores** [comment]
Según entendí de lo que investigué, las gasolinas y diesel son los únicos que caen en el esquema actual. 
Prácticamente, el resto de productos o servicios que ocupan IEPS, calcularían IVA con base IEPS.
Eso sería obligarlos a dar un click de mas siempre...

**Comment by jccastillo0007** [comment]
Done.
