### ISSUE TITLE
Completar la factura Pago en Parcialidades

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#463]
Cuando una factura se captura en parcialidades, primero se debe generar una factura normalita por el monto total del producto o servicio.
Enseguida, por cada parcialidad se debe generar una factura con forma de pago "PARCIALIDAD 1 DE N", y se incluirán 4 datos de la factura original:

Folio, Serie, Fecha (con formato ISO 8601, aaaa-mm-ddThh:mm:ss) y  total.
Son 4 datos que deben capturarse. Lo ideal es que se tomen del XML directamente, pero si no fuera el caso, se pueden de manera inicial, abrir 4 campos para capturar, y asegurarse que el formato de la fecha se cumple... lo cual me parece muy suceptible a error humano.

**Comment by jccastillo0007** [comment]
Done..

La forma de pago debe incluir la palabra parcialidad en mayúsculas o minúsculas, puede ser solo parcialidad o parcialidades.

La información capturada se manda como datos extras al PDF

**Comment by RigoFlores** [comment]
Marca el siguiente error:
cvc-datatype-valid.1.2.1: '2015-09-18' is not a valid value for 'dateTime'.cvc-attribute.3: The value '2015-09-18' of attribute 'FechaFolioFiscalOrig' on element 'cfdi:Comprobante' is not valid with respect to its type, '#AnonType_FechaFolioFiscalOrigComprobante'. (301)

También necesito conocer el nombre de las 4 variables para el PDF.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
En cuáles variables me envias en el PDF los 4 nuevos datos para la factura en parcialidades?

**Comment by jccastillo0007** [comment]
Se mandan como datos extras, por ejemplo:

Factura sin otros datos extras, esto es lo que llega a Jasper  (siempre en ese orden)
datoExtra1=xxx,datoExtra2=666,datoExtra3=234.32,datoExtra4=22/09/15

Factura que tenía otros 2 datos extras (valor1 y valor2)
datoExtra1=valor1,datoExtra2=valor 2, datoExtra3=aaaa,datoExtra4=8897,datoExtra5=987.121,datoExtra6=22/09/15

**Comment by RigoFlores** [comment]
Esto no funciona para propósitos del formato en jasper, ya que no es dinámico.
Ahí se le define fija y rígidamente cuál dato mostrar... no aplica 'ahora el datoextra1, ahora el datoextra3, etc).
Creo que si deberíamos definier variables exprofeso para estos datos.
Por otro lado si capturas el total de la factura original con $, no lo manda al XML. Creo que debemos colocar una etiqueta afuera del texto (la de $), y/o ponerle una máscara al total, que solo permita la captura de números.

**Comment by RigoFlores** [comment]
para el folio, también debería permitir solo la captura de números, que no? (de acuerdo al XML)

**Comment by RigoFlores** [comment]
Por lo pronto lo podemos llevar a producción, ya lo validé...pero si entiendo que quedan 2 issues:
a) Generar variables específicas para estos datos hacia el PDF
b) Permitir solo números en la captura de folio y total (entero y flotante respectivamente)

**Comment by jccastillo0007** [comment]
Estas son las variables en las que llegará la información de pago en 
parcialidades.

```
parcialidadSerie;
parcialidadFolio;
parcialidadTotal;
parcialidadDate;
```

Hay que levantar otro ticket para el tema de folio y total solo numéricos.

Saludos.
JC.
