### ISSUE TITLE
Factura Periódica - No envía por correo la factura de acuerdo a la configuración

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#466]
Si la configuración estándar es enviar al emisor y al receptor, la factura periódica no se está enviando por correo

**Comment by jccastillo0007** [comment]
Fixed...

Ojo... la configuración que se aplica es lo configurado en la opción global de administración de ese cliente, y no la configuración de los check boxes de la pantalla de facturas cuando se creo la factura periodica....

Y tanto el emisor como receptor deben tener un correo configurado, si asi se desea enviar la factura.

**Comment by RigoFlores** [comment]
Si claro, la opción que se debe tomar en cuenta, es la de la configuración global.
Debe enviar el correo, si se tiene configurado al menos un correo en el emisor o en el receptor, sin precisamente ser obligado en ambos.
Debe tomar el correo del emisor y/o emisor, aún cuando se realicen cambios en cualquiera de los 2, en el inter de cada envio.
Estoy esperando al siguiente periodo, que se supone será por ahí de las 12....

**Comment by RigoFlores** [comment]
ok
