### ISSUE TITLE
No genera la factura de acuerdo a la periodicidad programada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#467]
Me comentaste que sería cada 3 horas, y estos son los horarios en los que generó hoy una factura que se comportó mas o menos regular...

18Sep2015_110122
18Sep2015_121523
18Sep2015_181531

Si te das cuenta la primera fue a las 11:01, la segunda a las 12:15 y la tercera a las 18:15...(aprox)..
No entendí la periodicidad

**Comment by jccastillo0007** [comment]
Hay que seguir observando, ahorita no veo por que ese comportamiento extra;o, igual y es por las chelas tranquis....

**Comment by jccastillo0007** [comment]
Ahorita esta cada 6 horas, pero eso se mueve conforme reinicio la app.(esto quiere decir que esperarte al dia de ma;ana no te va a servir mucho, ya que hoy reinicié la app)... para hacer una prueba mas real, habría que actualizarlo al menos  24 horas, y que no dependa de si reinicio o no la app... pero eso lo activaré al final, para que no retrase tus pruebas.

**Comment by RigoFlores** [comment]
OK, acaba de generar una después de 5 horas con 15 segundos. Supongo que los 15 segundos son por el poleo de las facturas periódicas.
Daremos el día de hoy para concluir estas pruebas. Si al final del día todo está OK, entonces lo pasamos a producción con periodicidad de 1 día para entregarle al cliente, y al siguiente día, con la periodicidad mensual, lo cual implicaría que el cron solo consulte una vez al día, que no? Quizás por ahí de las 04:00 hrs

**Comment by jccastillo0007** [comment]
Estaba pensando en correrlo a la 1 am pero en realidad cualquier hora es
buena, de preferencia en la madrugada para no afectar la operación.

Saludos.
JC.

2015-09-23 11:23 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Si puede ser a la 1; el chiste es asegurar que no vaya 'agarrar una fecha previa'. Yo creo que a las 3 de la mañana está bien  (por el tema de cambios de horario).

Al parecer ya quedó con la periodicidad correcta (6 horas). Entonces hay que llevarlo a producción con la periodicidad de 1 día, cómo vex? Se lo mostraré al cliente... le tendré que programar una periódica que le llegue al menos unos 2-3 días consecutivos... y de ahí ya le movemos a la fecha programada... como vex?

**Comment by jccastillo0007** [comment]
Lo dejé a las 4 am en PRU... es decir, Jueves, Viernes, Sabado y Domingo 
generará las facturas a las 4 am.... cuando lo pase a PRO ya valido que 
sea a las 4 am de los días especificados.

Saludos.
JC.

**Comment by RigoFlores** [comment]
no, ya está validado en PRU. 
Tengo el compromiso de entregar mañana esta funcionalidad en producción, por ello lo solicité ya en PRO

**Comment by jccastillo0007** [comment]
ok, entonces lo subo a PRO

**Comment by jccastillo0007** [comment]
yasta en PRO

**Comment by RigoFlores** [comment]
Cuál periodicidad quedó y a partir de que hora empieza dicha periodicidad?
