### ISSUE TITLE
Consultas factura periódica

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#468]
Cambiar la etiqueta a 'Facturas Programadas'.
incluir la información de serie y folio, ya que ahora solo se muestra serie, y no se indica el folio como para poder consultar el contenido de la factura.

**Comment by jccastillo0007** [comment]
El folio no lo incluí porque no será el mismo en cada factura generada, aún asi lo requieres ?

**Comment by RigoFlores** [comment]
Entiendo que en esa consulta, solo se presentarán las facturas iniciales o de referencia para hacerla periódica. Entonces si hace falta el folio para tenerla bien identificada.

**Comment by jccastillo0007** [comment]
Done.

Tuve que limpiar la base de datos, ya que no se estaba guardando el folio....
