### ISSUE TITLE
En consultas periódicas, dar la opción de exportar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#469]
Para que genere el excel y el zip, igualito que en la consulta estándar...

**Comment by jccastillo0007** [comment]
Done.
En este caso solo aplica el excel... no veo para que crear el zip, tu si ?

**Comment by RigoFlores** [comment]
Pues el zip que contiene las facturas, si debe ser de utilidad...

**Comment by RigoFlores** [comment]
OK, lo cerraremos y ya vemos si el cliente que será el primer usuario exprofeso de esta función, nos va solicitando el zip con todas las facturas periódicas generadas (no solo la primera)
