### ISSUE TITLE
ALMACENAR LA COTIZACIÓN Y REMISION.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#47]
LAS COTIZACIONES SE DEBEN ALMACENAR, PARA QUE POSTERIORMENTE SE PUEDAN CONVERTIR EN FACTURAS.
MISMO CASO PASARÍA CON REMISIONES.
TANTO COMO COTIZACIONES COMO REMISIONES, UTILIZARÁN LAS PLANTILLAS POR OMISIÓN DE:
cotizacion.jrxml Y remision.jrxml

SE PODRÁ CONSULTAR LAS COTIZACIONES/REMISIONES POR ID, YA QUE A PARTIR DE LA CONSULTA, SE PODRÍAN CONVERTIR EN FACTURAS.

**Comment by jccastillo0007** [comment]
Done. no tengo las plantillas de cotizacion y remision... para subirlas al server.
