### ISSUE TITLE
factura periódica - duplica las consultas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#470]
generé 2 facturas periódicas el día de hoy; una con 3 productos y otra con uno solo.
Al consultar en las consultas normales, me aparecen 4 facturas, resultando que duplicó cada una de las facturas periódicas. Al darle exportar también aparecen 2 veces.
![image](https://cloud.githubusercontent.com/assets/2912775/10035351/b7743728-615e-11e5-82e7-934aa1bc0c14.png)

En el ZIP, ahí si incluyó correctamente solo una factura de c/u

**Comment by RigoFlores** [comment]
![facturaperiodicaduplicada](https://cloud.githubusercontent.com/assets/2912775/10035512/a439476e-6160-11e5-94c6-382a2d2a53d2.png)

**Comment by RigoFlores** [comment]
Ahí en la imagen se ve como en la consulta estándar, duplicó las facturas 1378 y 1379, con la diferencia que unas si tiene id y las otras no.

**Comment by jccastillo0007** [comment]
Ufff cerca la bala.... lo que pasó es que te esta mostrando la factura generada y la factura configurada como periodica (que son las que no tienen id) este issue quedó arreglado.
