### ISSUE TITLE
Addenda tridonex - Eliminar todo lo relativo a schema location 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#472]
ahora:
    cfdi:Addenda
        <ns2:Tridonex xmlns:ns2="http://tempuri.org/Tridonex.xsd" xmlns:tridonex="http://tempuri.org/Tridonex" xsi:schemaLocation="http://tempuri.org/Tridonex http://tempuri.org/Tridonex.xsd">
            <ns2:PODetalle Cantidad="1.0" IVA="66.44" Line="1" PO="12345" SubTotal="415.25" Total="481.69" UUID="4A954D1E-7E57-4AB7-A2AE-7D1EE515E367" noIdentificacion="66661"/>
            <ns2:PODetalle Cantidad="1.0" IVA="66.44" Line="2" PO="12345" SubTotal="415.25" Total="481.69" UUID="4A954D1E-7E57-4AB7-A2AE-7D1EE515E367" noIdentificacion="66662"/>
            <ns2:PODetalle Cantidad="1.0" IVA="66.44" Line="3" PO="12345" SubTotal="415.25" Total="481.69" UUID="4A954D1E-7E57-4AB7-A2AE-7D1EE515E367" noIdentificacion="66663"/>
            <ns2:PODetalle Cantidad="1.0" IVA="66.44" Line="4" PO="12345" SubTotal="415.25" Total="481.69" UUID="4A954D1E-7E57-4AB7-A2AE-7D1EE515E367" noIdentificacion="66664"/>
            <ns2:PODetalle Cantidad="1.0" IVA="66.44" Line="5" PO="12345" SubTotal="415.25" Total="481.69" UUID="4A954D1E-7E57-4AB7-A2AE-7D1EE515E367" noIdentificacion="66665"/>
        /ns2:Tridonex
    /cfdi:Addenda

**Comment by RigoFlores** [comment]
ELIMINAR TODO LO RELATIVO AL SCHEMA LOCATION Y DEJARLO VACÍO

```
    <ns2:Tridonex xmlns:ns2="http://tempuri.org/Tridonex.xsd" xmlns:tridonex="http://tempuri.org/Tridonex" xsi:schemaLocation="http://tempuri.org/Tridonex http://tempuri.org/Tridonex.xsd">
```

ASI QUEDARÍA:

```
    <ns2:Tridonex >
```

**Comment by jccastillo0007** [comment]
Subí un jar al folder de releases chacarrones llamado JaxbXMLProvider...jar... puedes susitituirlo en donde estes probando la addenda  tridonex, y me dices si asi esta bien... no puedo quitar todo ya que el schema indica el namespace y debe ser incluido, asi es como quedaría.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Tridonex xmlns="http://tempuri.org/Tridonex.xsd">
    <PODetalle PO="123456789" Line="1" noIdentificacion="666"
        Cantidad="1.0" SubTotal="24.931035" IVA="3.988966" Total="28.920001"
        UUID="9A3FC5A5-7E57-47A4-88C2-E571FF54E829" />
    <PODetalle PO="99999999" Line="2" noIdentificacion="777"
        Cantidad="3.0" SubTotal="25.931035" IVA="4.148966" Total="30.080001"
        UUID="9A3FC5A5-7E57-47A4-88C2-E571FF54E829" />
</Tridonex>

**Comment by RigoFlores** [comment]
no jaló...
    cfdi:Addenda
        <ns4:Tridonex xmlns="http://tempuri.org/Tridonex.xsd" xmlns:ns4="http://tempuri.org/Tridonex.xsd">
            <PODetalle Cantidad="1.0" IVA="66.44" Line="1" PO="12345" SubTotal="415.25" Total="481.69" UUID="AABB2965-7E57-4D54-9A6C-3AC2426CBEE7" noIdentificacion="66661"/>
            <PODetalle Cantidad="1.0" IVA="66.44" Line="2" PO="12345" SubTotal="415.25" Total="481.69" UUID="AABB2965-7E57-4D54-9A6C-3AC2426CBEE7" noIdentificacion="66662"/>
            <PODetalle Cantidad="1.0" IVA="66.44" Line="3" PO="12345" SubTotal="415.25" Total="481.69" UUID="AABB2965-7E57-4D54-9A6C-3AC2426CBEE7" noIdentificacion="66663"/>
            <PODetalle Cantidad="1.0" IVA="66.44" Line="4" PO="12345" SubTotal="415.25" Total="481.69" UUID="AABB2965-7E57-4D54-9A6C-3AC2426CBEE7" noIdentificacion="66664"/>
            <PODetalle Cantidad="1.0" IVA="66.44" Line="5" PO="12345" SubTotal="415.25" Total="481.69" UUID="AABB2965-7E57-4D54-9A6C-3AC2426CBEE7" noIdentificacion="66665"/>
        /ns4:Tridonex
    /cfdi:Addenda

**Comment by RigoFlores** [comment]
No se porque no se vé, pero no jaló...
el encabezado quedó así:
        <ns4:Tridonex xmlns="http://tempuri.org/Tridonex.xsd" xmlns:ns4="http://tempuri.org/Tridonex.xsd">

es decir, lo sigue mostrando....

**Comment by jccastillo0007** [comment]
Hoy hice algunas pruebas y ajustes... en el dropbox en releases chacarrones subi dos jars.

JAXB_XMLProvider-8.1.4
AddendaTridonex_JaxbProvider-8.1.4

Con esos jars, la addenda va a quedar mas limpia, pero aún va a mostrar : 

<Tridonex xmlns=""> 

el xmlns="" no se lo puedo quitar, a menos que se lo quite a manita, pero no lo creo necesario y además todo se arreglaría si definieran bien el schema.
