### ISSUE TITLE
Mover debajo de consultas, el menú 'Programadas'

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#474]
Para no crecer tanto el menú de ventas, y dado que es una consulta, podemos colocarlo debajo de consultas para las programadas?

**Comment by jccastillo0007** [comment]
Esa opción de Programadas, que es lo que debe tener ? no entendi, te
refieres a consulta de programadas ?

Saludos.
JC.

**Comment by RigoFlores** [comment]
Afirmativo, al estar debajo de consultas, en automático se refiere a consultas, y luego al ser programadas, llega a ser 'consultas programadas', lo cuál lo utilizarán pocos clientes de manera inicial, entonces para que crecer el menú principal que si afecta a todos los usuarios....

**Comment by jccastillo0007** [comment]
No se puede tener mas de dos niveles de menú, si te entendí bien, tu quieres un tercer nivel, pero con el plugin de wicket que estamos usando no es posible, o no se como... tendría que revisar que opciones tenemos.

**Comment by RigoFlores** [comment]
Chiaaaaa.... si que hay que revisar las opciones... ni modo que no lo permita... jeje
