### ISSUE TITLE
En web no recupera acuse de cancelación, cuando ya está cancelada la factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#475]
Lo que se ocupa, es recuperar el acuse y cambiar el status.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Precisamente hoy se repitió el escenario en producción.
SI tu cierre es en pruebas, pos no se como lo validaste, ya que en pruebas no hay cancelación.

**Comment by jccastillo0007** [comment]
Lo validé usando PRO, pero no subí el release... tons ya lo subo.

Saludos.
JC.

2015-10-09 14:26 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Done.
