### ISSUE TITLE
En consultas de Web, cambia el ícono de exportar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#476]
El icono actual es de unas flechas... cambiarlo a uno de excel o un excel encima de un zip.
Acabo de estar con los españoles, y me dicen que las flechitas no le sugerían algo... no sabía que se podía exportar a excel...

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
no lo ví, ni en pro, ni en pru...

**Comment by jccastillo0007** [comment]
ya esta en PRU.

**Comment by RigoFlores** [comment]
cuando lo llevamos a pro?
