### ISSUE TITLE
LOS CRISTEROS - IMPORTAR CATÁLOGO DE CUENTAS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#477]
EL EXCEL QUE TIENEN ELLOS CUENTA CON DESCRIPCIÓN DE CUENTA(COLUMNA C), NÚMERO DE CUENTA (COLUMNA B), ASÍ COMO SUBCUENTA (COLUMNA E) (ES DECIR CUENTA PADRE).
SE DEBE PODER IMPORTAR, Y UNA VEZ DENTRO DEL SISTEMA, TENER POSIBILIDAD DE:

A) INCORPORAR EL CÓDIGO AGRUPADOR
B) CAPTURAR EL SALDO INICIAL
C) INSERTAR DE SER NECESARIO, ALGUNA CUENTA PADRE DEL CATÁLOGO DEL SAT.

Todas estas cuentas deberán ser editables (se podrán eliminar, principalmente).
ES POSIBLE QUE EL EXCEL YA SUBA TAMBIÉN CON LA COLUMNA DEL CÓDIGO AGRUPADOR (COLUMNA D) O QUE SE LA CAPTUREN EN PANTALLA

**Comment by jccastillo0007** [comment]
Este requerimiento sigue vigente ?

No son ellos los putos gasolineros que ya vendieron la gasolineria?

**Comment by RigoFlores** [comment]
Pues todo se quedó en veremos... no la vendieron, pero si la rentaron.
Quizás mas adelante.
Lo que es un hecho, es que si se llega a dar el proyecto del que platicamos, ahí un requisito es precisamente importar las pólizas.
