### ISSUE TITLE
REQUISITO LOS CRISTEROS - IMPLEMENTAR ALGO SIMILAR AL XMLTOOL

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#478]
Me comentaste que ibas a revisar el alcance del XML tool

**Comment by RigoFlores** [comment]
Seguro no lo has revisado, pero ya envié nuevamente un correo donde el tema de los parámetros en las pantallas del sat, se le deja al usuario y solamente se ocupan de descargar los XML's. Según yo, eso debería ayudarnos a resolver esto que tenemos detenido de hace muchos meses... que raro

**Comment by jccastillo0007** [comment]
Ya lo había revisado, y ya te habia dicho que no es posible integrarlo a nuestra aplicación, se puede usar de forma independiente, pero no como parte de facturat, habias quedado de investigar el costo de la vesión comercial y de ver que es lo que se entregaba en dicha versión.

La implementación actual que tenemos, permite descargar facturas recibidas pero no emitidas, esto debería ser suficiente para nuestros clientes, ya que las emitidas las tenemos nosotros.

**Comment by RigoFlores** [comment]
Creo que no hablamos de lo mismo.
En un correo te mandé una liga, donde una de las soluciones para descargar EMITIDAS O RECIBIDAS, le deja la responsabilidad al cliente de llevarlo hasta la pantalla donde ya se listan las facturas (el cliente indica los parámetros de la consulta en la pantalla del sat).
A partir de esa pantalla, existe una opción en la aplicación para descargar los XML mostrados en pantalla. Entendería yo que algo así podríamos hacer sin problema y ya tendríamos cubierto tanto emitidas como recibidas.
En cuanto a suponer que son clientes nuestros y por ello contamos con sus facturas, creo que no esta tanto así. Esta herramienta como bien dices, debe ser independiente a Factura-T, y por lo tanto debe permitir descargar las emitidas y recibidas.
Si le echaste un ojo al video para que hablemos de lo mismo?

**Comment by jccastillo0007** [comment]
Yeap, si vi el video, y si lo ví la ves anterior también... esta aplicación como tal no podriamos usarla nosotros, al menos no como parte del portafolio de FacturaT, pero me dió una idea de tratar de usar selenium, después de que el cliente ingrese los datos, no se si se pueda, voy a revisarlo.

**Comment by RigoFlores** [comment]
Aquí no se trata de utilizar su aplicación, sino implementar algo similar...
Una vez que el usuario ha elegido todos los parámetros de la consulta, incluso ha realizado la consulta... entonces nosotros procedemos a descargar.... no tiene que estar integrado a facturat, puede ser otra aplicación pero la idea es que pueda descargar los XML

**Comment by RigoFlores** [comment]
eni niu?

**Comment by RigoFlores** [comment]
Hacer algo que una vez que el usuario a definido los parámetros de la consulta, a partir de ahí con un botón darle descargar, que entiendo eso es lo que ya hacemos hoy (propiamente la descarga)?

**Comment by RigoFlores** [comment]
Seguimos en espera de esta respuesta... hay varios issues que no se han atendido...

**Comment by jccastillo0007** [comment]
Esta muy pinche raro esto...

**Comment by jccastillo0007** [comment]
Estoy revisando esta opci[on, es opensource ,as[i que en teor[ia podr[ia modificarlo.

http://linuxmanr4.com/2015/01/20/descargar-los-xml-del-sat-de-una-manera-mas-sencilla/

**Comment by jccastillo0007** [comment]
Encontré esta herramienta adminCFDi, se ve muy prometedora y es open source.

https://facturalibre.net/servicios/

**Comment by RigoFlores** [comment]
Yo tengo algo que hacer aquí?... ya empieza la econta el siguiente mes, y aún nos falta este tema.. bueno, varios pero este es uno de los importantes

**Comment by RigoFlores** [comment]
eni nius?

**Comment by jccastillo0007** [comment]
ya logre instalarlo y ejecutarlo en una maquina windows.... se ve prometedor, excepto porque no logro hacer que baje los XML jojojojo... sigo en eso.

**Comment by RigoFlores** [comment]
Aquí otra referencia con las características del software que llevamos meses intentando:
13.2 - CFDI Descarga Masiva (Navaja Suiza del Contador)
Esta herramienta ya es un clásico y en ContadorMx se le bautizo como la Navaja Suiza del Contador, por el hecho de que no solo descarga los XMLs del SAT sino que tiene estas otras utilices funciones.
Verifica la vigencia de los XMLS directo del SAT
 Organiza los XMLs por RFC, tipo, año, mes
 Exporta a Excel la información contenida en el XML
 Genera el XML para la contabilidad electrónica
 MultiRFC
 Genera el PDF del XML con un formato estándar
Si te interesa puedes utilizarlo GRATIS durante 30 días, solo tienes que solicitarlo desde el siguiente enlace: CFDI Descargas Masivas (Navaja Suiza del Contador)

http://contadormx.net/shop/descarga-masiva-de-xml-del-sat-gratis-de-contadormx-com/

**Comment by jccastillo0007** [comment]
Creo que hoy logre resolver el problema de la herramienta que habia visto.

Cree una carpeta en dropbox llamada DescargaT, ahi vienen unos instalables y un readme.txt para que veas los pasos a seguir... yo lo probé y si baja los XML tantos recibidos como emitidos, y es stand alone, lo único que le falta es distinguir entre cancelados y vigentes..

Esta hecha en Python asi que sientate para revisarlo..

Si no te funciona, tenemos que hacer una sesión en vivo para ver que falta y definir el proceso real de instalación.

JC.

**Comment by RigoFlores** [comment]
Python???... requiere de meticuloso cuidado, que no?
Total que no puede completar la instalación:
1. Instalar Python (TUVE QUE DESCARGAR EL 3.4.4 PARA 32 BITS Y LO INSTALÉ)
2. Instalar Firefox  (NO LO TENÍA, YA LO HABÍA INSTALADO ANTERIORMENTE)
3. Descomprimir la carpeta DescargaT  (EN CUALQUIER CARPETA LO HICE)
4. Normalmente Python se instala por default en C:/Python34, dicha carpeta debe agregarse al path  (LA AGREGUÉ AL FINAL DEL PATH)
5. Instalar selenium con el siguiente comando:
   C:\Python34\Scripts\pip install -U selenium

(HASTA AQUÍ LLEGUÉ. LO EJECUTÉ DESDE CMD, PERO SE QUEDA PASMADO, NO HACE NI DICE NADA)
OJO, ANTERIORMENTE SUPONGO QUE YA TENÍA SELENIUM, YA QUE HICE LAS PRUEBAS DE LA OTRA VERSIÓN, QUE NO?
1. Instalar DescargaT con el siguiente comando, [debe estar ubicado en la carpeta donde se descomprimió el archivo DescargaT.zip]
   python.exe setup.py install
2. Una vez que termina de instalar todas las dependencias, ejecutar
   python.exe descargat

**Comment by RigoFlores** [comment]
Ya levanta la pantalla...
Mi primera prueba fue la de recibidas... probé con la tía... aparentemente está bien.... hay que hacer mas pruebas...
lo que no jaló fue lo de recibidas...
La aplicación, debe tener su propia estructura de directorios, según yo idéntica a la de facturaT, solo que sin la carpeta de XML y PDF, ya que en este caso todos son XML

**Comment by jccastillo0007** [comment]
Yo ya la use para varias pruebas tanto emitidas como recibidas, y si me funcionó bien, si tiene sus detalles como, el folder donde debe dejar los archivos, y la elección del estatus de canceladas o vigentes, pero toma en cuenta que no será fácil modificarla.

Yo creo que hay que ofrecerla gratis como parte del plugin de eConta, y una vez abajo los XML ya los procesamos en FacturaT standalone y/o los subimos a eFacturaT.

**Comment by RigoFlores** [comment]
No sé que pasaba, pero si ya ví y aparentemente funciona la descarga para emitidas y recibidas también. Entiendo que no es tan simple modificarla por ¿el lenguaje o por alguna otra razón?.
Hay varios puntos muy importantes que son elementales, por ejemplo:
a) Identificar el directorio para emitidas y recibidas.  Incluso se puede hacer una carpeta temporal, donde lleguen todos los XML y después se pasen a la carpeta que se indique.
b) Tengo entendido que la consulta tiene un tope de 500 facturas. Cuando el número es mayor, se tiene que filtrar por día en particular. Eso también tenemos que tenerlo bajo control.
c) Finalmente faltaría la integración con econta, que como comentaste, se puede implementar una vez que los archivos están ya en carpetas locales.

Y de esto, creo que todo se podría implementar, que no?
- Verifica la vigencia de los XMLS directo del SAT
- Organiza los XMLs por RFC, tipo, año, mes
- Exporta a Excel la información contenida en el XML
- Genera el XML para la contabilidad electrónica
- MultiRFC
- Genera el PDF del XML con un formato estándar

**Comment by jccastillo0007** [comment]
Por el lenguaje, Python es un nuevo lenguaje de scripting, muy poderoso, y puedes hacer un buen de cosas, voy a empezar a aprenderlo, pero si nos puede llevar tiempo, asi que sientate a masticarlo mientras yo estudio jajaja

Para el inciso a), creo que es posible y que no cueste tanto esfuerzo

para b) yo se lo dejaria al usuario, hacerle ver esa limitante, esto le pegará a muy pocos clientes

para c) podemos empezar a implementarlo.

Y si, toda la lista de actividades que pusiste es posible, pero, la primera mas que validar la vigencia, solo los baja a la máquina local, a menos que después usemos el web service que valida si esta o no vigente.

**Comment by RigoFlores** [comment]
Ya cerraste este issue, y todos los pendientes?
Se requiere trabajar en todo lo mencionado... de hecho, el issue dice "SIMILAR AL XML TOOL"
Que hacemos con todos estos pendientes?

**Comment by jccastillo0007** [comment]
Los issues pendientes estan levantadis en otros tickets del descargat
