### ISSUE TITLE
AGREGAR LEYENDA EN DATOEXTRA8, BAJO CIERTAS CONDICIONES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#479]
APLICA PARA NAVISION, ES DECIR LOS ESPAÑOLES, ES DECIR ESCRITORIO REMOTO, ES DECIR LA BD EN SQLSERVER.... ES DECIR, NO SE PRUEBA CON UN UN ARCHIVO DE TEXTO:
SURGE UN NUEVO REQUERIMIENTO PARA LOS ESPAÑOLES… respecto al datoExtra8, que entiendo que hoy en día se tiene lo siguiente:

Nombre:  Name
Domicilio: address + “ “ +  address2
City + “, “ + pais  + “,  C.P. “ + CP
No. Cuenta: CCC No_
CLABE: Clabe
SWIFT: SWIFT Code

Cuando el número de cuenta, resaltado en verde sea igual a 03504856627 solo para este caso, se requiere que el datoExtra8 quede como:

Nombre:  Name
Domicilio: address + “ “ +  address2
City + “, “ + pais  + “,  C.P. “ + CP
No. Cuenta: CCC No_ + “ Referencia 18”
CLABE: Clabe
SWIFT: SWIFT Code

Creo que es lo mas alambrado que estamos haciendo, pero de lo contrario, tendríamos que desglosar el datoextra8 en todos sus componentes, para nosotros desde jasper colocar o no dicha leyenda de “ Referencia 18”. Entonces, seguimos colocando alambritos… o si quieres destazamos en datos extras adicionales ese campo… tu me dices

Lo ocupan desde ya.

**Comment by jccastillo0007** [comment]
DONE.
