### ISSUE TITLE
NO RESPETA EL RANGO SUPERIOR DE FOLIOS DEFINIDO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#48]
DEFINÍ UN RANGO DE FOLIOS SUPERIOR. Y SOLO TENGO UNO DEFINIDO DEL 1 AL 10.
SIN EMBARGO PERMITE SEGUIR FACTURANDO, AÚN CUANDO SE REBASÓ EL RANGO DEFINIDO.
QUE LIMITE LA EMISIÓN DE FACTURAS, NOS HA SERVIDO PARA QUE LOS CLIENTES SOLICITEN RECARGAS, EN CASO DE SER NECESARIO.
AQUÍ DEBE NOTIFICAR CUANDO FALTE EL 10% (O LO QUE SE DEFINA EN PREFERENCIAS), PARA ALCANZAR EL RANGO SUPERIOR

**Comment by jccastillo0007** [comment]
te refieres a los folios que controla el cliente verdad ?... si es asi.... entiendo que hay una falla, pero ... deberiamos limitar el uso a dichos folios.... eso es mas control del cliente no ?

**Comment by jccastillo0007** [comment]
Ok, ya se esta validando los rangos de folios.

Faltaria 
1. avisos de terminacion de folios
2. la serie debe ser opcional, hay un bug ahora mismo.

**Comment by RigoFlores** [comment]
Pues no, no está validando, ya que yo tengo la serie A con rango del 1 al 10, y ya está en el folio 24, y puedo seguir facturando.
Voy a cerrar esta ficha y la cambiaré por aquella funcionalidad que le notificará al usuario 3 puntos importantes:
a) Rango de Folios contratado está por finalizar
b) Vigencia de Folios está por vencer
c) Vigencia del Certificado de Sello Digital está por vencer
