### ISSUE TITLE
MIGRACIÓN DE ESCRITORIO A WEB PARA RFC PGV091119462

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#480]
SUBÍ AL DROPBOX LOS ARCHIVOS XML Y PDF...
SE DEBE GENERAR Y SUBIR LA BD HISTÓRICA, A PARTIR DE LOS XML
SE DEBE SUBIR EL CATÁLOGO DE CLIENTES Y PRODUCTOS A PARTIR DE LOS XML
SE DEBEN SUBIR LOS ARCHIVOS XML Y PDF PARA SU POSTERIOR DESCARGA...

YA GENERÉ SU ACCESO EN WEB

**Comment by RigoFlores** [comment]
Si existe una, lo que no estoy seguro si está completa.
La subí al drots. 
Si vas a migrar desde aquí, como quedarían las canceladas y los acuses correspondientes?
Si me dices que ya jala lo de recuperar el acuse de una cancelada, entonces nosotros podríamos cancelar todas las canceladas... solo que ojo, la migración desde la BD, entonces debería ignorar el status... o no?

**Comment by RigoFlores** [comment]
Es decir, si existe la BD y la subí al drots.
El tema es que no sé si esté completa, y dado que lo que si sabemos y tenemos son los XML, por ello pedí que fuera desde los XML y no desde la BD.
Si podemos hacerlo desde la BD y luego agregar algún registro que haga falta, y eso facilita las cosas, pues adelante,

**Comment by jccastillo0007** [comment]
DONE.
