### ISSUE TITLE
Cambios en la addenda Tridonex para conector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#481]
Nos están pidiendo estos cambios. Lo del schema location, creo que tiene que ver con haberle enviado 'sueltas' las correcciones.
Por otro lado está el tema de los decimales
y Finalmente el prefijo de cada renglón, es decir cambiar ns2, por cfdi.
Addenda recibida:
- cfdi:Addenda
- <ns2:Tridonex xmlns:ns2="http://tempuri.org/Tridonex.xsd" xmlns:tridonex="http://tempuri.org/Tridonex" xsi:schemaLocation="http://tempuri.org/Tridonex http://tempuri.org/Tridonex.xsd">
  <ns2:PODetalle Cantidad="1.0" IVA="1440.0" Line="1" PO="4800000458" SubTotal="9000.0" Total="10440.0" UUID="cacaa4ef-e79d-44f7-9066-04e714bcf5e8" noIdentificacion="SRV" /> 
  /ns2:Tridonex
  /cfdi:Addenda

Correciones:

  cfdi:Addenda
<cfdi:Tridonex >
  <cfdi:PODetalle Cantidad="1.00" IVA="1440.00" Line="1" PO="4800000458" SubTotal="9000.00" Total="10440.00" UUID="cacaa4ef-e79d-44f7-9066-04e714bcf5e8" noIdentificacion="10" /> 
  /cfdi:Tridonex
  /cfdi:Addenda

**Comment by jccastillo0007** [comment]
dONE.

**Comment by RigoFlores** [comment]
OK, esperaremos a ver que dice el cliente... la neta con ese contador, ya no se sabe que esperar
