### ISSUE TITLE
Agregar oootros impuestos locales en Web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#482]
Ahora nos han solicitado estos impuestos:

I.C. Y V.S.F.P.
P.C Y A.I.C.I.C.
A.C.C.E.A.

Si desde el principio se hubiera implementado en BD, ahorita no tendríamos que batallar con tantos y tantos impuestos locales que ya muestra la aplicación y la mayoría de los clientes no los ocupan.
Según yo, debería existir por cada cliente, un archivo de texto o similar (que podamos controlar nosotros), donde se den de alta estos impuestos, y que de ahí los leyera el combo de impuestos. O algo similar. Por lo pronto este cliente ya pagó.

**Comment by jccastillo0007** [comment]
Listo.

Realmente no es problema agregar mas impuestos locales.

Pensar que son muchos es absurdo cuando tenemos cargado los catálogo de moneda, retenciones, percepciones, deducciones, bancos, etc... en los cuales seguramente se ocupan también muy pocos, pero así lo pide el SAT y así se solicitó, y ahora tenemos solo como 8 o 10 impuestos locales.

**Comment by RigoFlores** [comment]
El caso ideal es que cada cliente vea solo los impuestos locales que ocupa.
Ahora mismo, todos los clientes ven el listado, y bueno realmente no los ocuparán la gran mayoría de ellos. Por otro lado, igual y sirve para que tengan claro que pueden elegir impuestos adicionales, a los estándares.

**Comment by RigoFlores** [comment]
VA PATRÁS NUEVAMENTE CON ESTE TEMA... QUE LA COMISIÓN DE AGUA LE REGRESÓ LA FACTURA, Y AHORA QUIERE QUE LOS IMPUESTOS EN LUGAR DE LO SOLICITADO ORIGINALMENTE SEA AHORA:

INSPECCIÓN Y VIGILANCIA
ICIC
APORTACIÓN DE ATENCIÓN A CONTINGENCIAS

INSISTO, ESTO DEBERÍA SER MUCHO MAS SIMPLE, PERO LO PRONTO URGE IMPLEMENTAR ESTE AJUSTE..

**Comment by jccastillo0007** [comment]
Listo, y si, es muy simple.

**Comment by jccastillo0007** [comment]
Por cierto, ningún cliente tiene su propia vista de un catálogo general.
