### ISSUE TITLE
RETENCIONES: FALTA GESTIÓN DE FOLIO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#483]
SE DEBE CONSIDERAR LA SERIE 'RET', Y LLEVAR UN CONTROL CONSECUTIVO DEL FOLIO.
AHORA MISMO SE CAPTURA, PERO DEBE SER AUTOMÁTICO ASÍ COMO LOS FOLIOS DE LAS FACTURAS O DE LOS RECIBOS DE NÓMINA.

EL FOLIO DE CONTROL INTERNO SERÁ LA SERIE 'RET', + CONSECUTIVO
EJEMPLO: "RET123", Y SE DEBE DAR DE ALTA LA SERIE Y EL FOLIO INICIAL, DESDE EL CATÁLOGO DE FOLIOS. ESTO IMPLICA ELIMINAR SU CAPTURA.

**Comment by RigoFlores** [comment]
Ya funciona enviar como SERIE+FOLIO el folio interno de la retención, tanto al XML, como al PDF. En el PDF solo desplegamos el folio, por lo tanto en automático está resuelto.
Ya solo queda pendiente propiamente la gesitón del folio, es decir llevarlo como en nómina.

**Comment by jccastillo0007** [comment]
Done
