### ISSUE TITLE
RETENCIONES: HABILITAR CAPTURA DE DESCRIPCIÓN SOLO CUANDO SE ELIJA OTROS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#484]
Cuando la opción elegida sea 'Otro tipo de retenciones', entonces es que se puede habilita la captura de la descripción.
En otro caso, la descripción se debe enviar conforme la opción elegida.
Por ejemplo para la clave "01", debería ser "Servicios Profesionales"

**Comment by jccastillo0007** [comment]
Orale... y esa opción de retenciones de donde te la sacaste ?

**Comment by RigoFlores** [comment]
La opción dentro del listado, la tomé del catálogo de retenciones que dice:
25 Otro tipo de retenciones

Por otro lado la descripción del documento indica respecto a la descripción:
Atributo opcional que expresa la descripción de la retención e información de pagos en caso de que en el atributo CveRetenc se haya elegido el valor para 'otro tipo de retenciones'

**Comment by jccastillo0007** [comment]
Chiaaaa hasta suerte tienes.

Fixed.
