### ISSUE TITLE
retenciones: permitir la captura opcional del curp para emisor y receptor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#486]
Por lo pronto se podría capturar; posteriormente almacenar en BD.

**Comment by jccastillo0007** [comment]
El CURP del receptor ya se puede capturar en el catálogo de clientes, solo falta ver donde poder capturar la CURP del emisor, no estoy seguro que en la página de retenciones sea el mejor lugar.

**Comment by RigoFlores** [comment]
Si ya lo vi. El lugar ideal sería en la llave o licencia, pero afectaríamos creo yo al core de todo lo que hemos hecho. La otra parte podría ser en la pantalla de configuración, junto con los sellos y plantillas. Ahí le pegaríamos a un solo punto. Tu evaluarás el menor impacto.

**Comment by jccastillo0007** [comment]
done.
