### ISSUE TITLE
retenciones: implementar consulta, descarga y cancelación de retenciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#487]

**Comment by jccastillo0007** [comment]
Ya esta la consulta y descarga.

Falta la cancelación.

**Comment by RigoFlores** [comment]
Solamente vi la consulta, pero la descarga no. Es decir no aparecen los íconos de PDF y XML

**Comment by RigoFlores** [comment]
![consultas retenciones](https://cloud.githubusercontent.com/assets/2912775/10969255/b628f444-838c-11e5-8dd1-ea5e76528b6a.png)

**Comment by jccastillo0007** [comment]
Es por el problema de serie + folio que existia, pero aparitir de hoy, ya todas deben aparecer.

**Comment by jccastillo0007** [comment]
Done, pero con Finkok

**Comment by RigoFlores** [comment]
hay que llevar a producción la cancelación...
