### ISSUE TITLE
retenciones: el valor mínimo para el ejercicio es 2004

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#488]
Aunque el valor por omisión, debería ser el año en curso, si debería dar la opción de elegir desde el año 2004.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
falta considerar que el valor por omisión sea el año en curso.

**Comment by jccastillo0007** [comment]
Fixed
