### ISSUE TITLE
retenciones: no está enviando el total de retenciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#489]
en la variable de 'total' del cfdi estándar, debería enviar también el total de las retenciones, correspondiente a:

montoTotOperacion. Atributo requerido para expresar el total del monto de la operación que se relaciona en el comprobante.
esta dato no está llegando al PDF, pero si se incluye en el XML

**Comment by jccastillo0007** [comment]
Done.
