### ISSUE TITLE
NO PUEDO FACTURAR AL RECEPTOR FOPR681125BQ0

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#49]
NO ME PERMITE GENERAR UNA FACTURA PARA MI RFC.
APLICA TANTO PARA USUARIO DEMO COMO RIJO.
ENVÍA EL ERROR AL SELLAR LA FACTURA CON EL PAC (105).

COMO DEBO INTERPRETAR DICHO ERROR?

**Comment by jccastillo0007** [comment]
El 105, lo manda directamnte el PAC, significa error en el timbrado, a mi me salio una vez y fue porque el RFC del receptor era invalido.

La proxima vez, checa mas o menos a que hora te mando ese error, para validar el log.

**Comment by RigoFlores** [comment]
YA SE PUDO FACTURAR, PERO NO REALICÉ NINGÚN CAMBIO EN EL CLIENTE. ES MAS, NO PUEDO MODIFICAR EL RFC.
AYER EL PROBLEMA SE PRESENTÓ, 2 VECES POR AHÍ DE LAS 11:00 HRS, ACCEDIENDO CON EL USUARIO DEMO Y RIJO. POSTERIORMENTE EN LA TARDE LO INTENTAMOS OTRA VEZ, Y TAMPOCO SE PUDO, POR ESA RAZÓN LO ASOCIÉ AL RFC, YA QUE CON OTROS RFC'S SI SE LOGRÓ FACTURAR.

**Comment by RigoFlores** [comment]
PERDÓN, LO CERRE POR ERROR
