### ISSUE TITLE
retenciones: validar los datos requeridos y los opcionales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#490]
de acuerdo a la especificación del sat.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
De hecho hay algo mal que me parece que está bien.
Según la spec del SAT, el detalle de la constancia (es decir, el equivalente a productos), es opcional.
Está mal la aplicacón de cara al SAT porque lo solicita a huevo, de lo contrario no timbra.
Está bien, porque ahí se detallan los impuestos que se están reteniendo, y me parece que es mucho mas claro, a que no se capturara nada.
Conclusión, nos vamos así, y vamos viendo si esto causa algún conflicto.
