### ISSUE TITLE
CATALOGO DE CUENTAS - al exportarla a excel, no incluye los saldos iniciales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#493]
Ya lo está ocupando un cliente, y nos trae en chinga con detallitos

**Comment by jccastillo0007** [comment]
Se incluyen los saldo iniciales y finales de cada cuenta, a que otro dato como saldo inicial te refieres ?

**Comment by RigoFlores** [comment]
Error mío, no son balanzas... se refiere al catálogo de cuentas...

**Comment by jccastillo0007** [comment]
Mmmmm el saldo inicial y final de que mes ? los saldos se almacenan por balanzas, y se van arrastrando o trasladando de un mes a otro, tons, cuando dicen el saldo inicial y final se refieren al mes corriente, o a la última balanza guardada o cerrada o abierta....??????

**Comment by RigoFlores** [comment]
Cuando capturas de manera inicial el catálogo de cuentas, también capturas EL SALDO INICIAL.
Este issue no menciona saldos finales, únicamente refiere al saldo inicial.
Y lo que está solicitando es que al exportar el catálogo de cuentas a excel, se incluya el saldo inicial.

**Comment by jccastillo0007** [comment]
ah ok, tons esta mas fácil, hoy lo subo a PRU.

Si vi el saldo inicial que se captura con la cuenta, pero como ese saldo inicial queda obsoleto según yo después del cierre de balanzas, pues no creí que fuera ese el que quiere el contador.
