### ISSUE TITLE
En la captura de Pólizas, agregar opción de cuadrar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#494]
Estamos capturando una o varias transacciones de una póliza.... y tenemos que capturar una última transacción. Ahí se ocupa una opción de 'Cuadrar Póliza', que es con un teclazo de preferencia (recordar que tiene que utilizarse en la medida de lo posible con solo teclado), disparar la función de cuadrar póliza, que es que el sistema calcule la cantidad (monto), ya sea en abonos o cargos, de tal manera que la póliza quede cuadrada o balanceada, es decir abonos=cargos.

Son de los detalles que ya nos está pasando un cliente que está ocupando y tomando muy en serio este asunto

**Comment by jccastillo0007** [comment]
Duplicado con issue 513
