### ISSUE TITLE
retenciones- la serie por omisión es RET, y no REM

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#495]
Debe tratarse idéntico a lo de nómina, es decir nosotros damos de alta la serie RET y el folio a partir del cuál va a empezar su consecutivo... con ello la aplicación llevará el control de consecutivo, con la serie RET... donde el número de folio interno de la constancia es RET1, RET2, etc.
Ahora mismo, asigna internamente la serie REM, pero ni siquiera está dada de alta...

**Comment by jccastillo0007** [comment]
Esta listo el tema de que la serie y folio sea consistente, pero falta implementar el mismo manejo que en Nomina, pero para eso esta el issue 483.
