### ISSUE TITLE
el folio enviado al PDF es distinto al enviado al XML y distinto al nombre del archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#496]
PDF: REM45
XML:  45
Nombre de los archivos: REM0_XAXA010101XXX_04Nov2015_192304

jeje, no cuadra ninguno de los 3...

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Hice una prueba y al parecer quedó, estaré pendiente de ello..
