### ISSUE TITLE
EN WEB, AGREGAR COMO METODO DE PAGO 'TRANSFERENCIA BANCARIA'

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#499]
SE ESTÁN PONIENDO BIEN PENDEJOS LOS DE LA CEA PARA PAGARLE A UN CLIENTE.
SI NO INDICA TRANSFERENCIA BANCARIA EN PDF Y XML, NO LE PAGAN
ES EL MISMO DE LOS IMPUESTOS LOCALES, YA TENEMOS VARIOS DÍAS CON ESTE CLIENTE Y NOMÁS NO SALE.
A VER SI CON ESTE CAMBIO, YA QUEDA. LO NECESITAMOS PARA MAÑANA SIN FALTA. TAMBIÉN EL AJUSTE EN LOS IMPUESTOS LOCALES

**Comment by jccastillo0007** [comment]
Done.
