### ISSUE TITLE
No existe catalogo de sucursales del emisor

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#5]

**Comment by RigoFlores** [comment]
CUALQUIER MEJORA SERA CONSIDERADA COMO TAL, EN CASO QUE SEA ADICIONAL A LO QUE TENEMOS CON EL EL ESTANALON.
CUALQUIER FUNCIONALIDAD QUE ESTÉ FALTANDO, SERÁ CONSIDERADA COMO DEFECTO O FALLA.

**Comment by jccastillo0007** [comment]
Mejor cree un nuevo tag que sea missing functionality, te late ?

Es que debo poder diferenciar defects, bug, enhancements y missing stuff
