### ISSUE TITLE
PARA EL USUARIO DEMO, NO MUESTRA RESULTADOS EN PAGINA DE CONSULTA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#50]
ENTRANDO CON EL USUARIO DEMO Y DESPUÉS DE GENERAR UNA O VARIAS FACTURAS, AL MOMENTO DE CONSULTAR DESDE LA PAGINA DE CONSULTA, NO ME MUESTRA NINGUN RESULTADO

**Comment by jccastillo0007** [comment]
Pequeños detalles de BD ¡¡¡¡

**Comment by RigoFlores** [comment]
YA MUESTRA LOS RESULTADOS, LO ESTAREMOS VALIDANDO
