### ISSUE TITLE
retenciones - timbrado con facture hoy

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#501]
timbrar con fhoy en lugar de finkok

**Comment by jccastillo0007** [comment]
Done.

Falta Cancelación

**Comment by RigoFlores** [comment]
ya está en producción?... solo ahí es que puedo validarlo...

**Comment by jccastillo0007** [comment]
Si.

**Comment by RigoFlores** [comment]
Generé una retención para la tía... por la mañana... acabo de intentar cancelarla y me mandó este error.. 127 Error al cancelar CFDi de Retenciones con el PAC
Voy a esperar y por la tarde estaré reintentando, para checar que haya pasado el tiempo necesario para cancelar

**Comment by RigoFlores** [comment]
Oye, el tema aquel de la cuenta especial en FactureHoy, para producción, entonces ya se arregló, o cómo puedo validar que ya estamos timbrando retenciones con fhoy???
