### ISSUE TITLE
Addenda Tridonex - implmentar en Web..

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#503]
pos ahora ya también la ocuparán en Web....

**Comment by RigoFlores** [comment]
y con todo y lo puerco que quedó el desarrollo

**Comment by jccastillo0007** [comment]
Subi los cambios a web, pero no los probé, si tienes tiempo trata de reproducirlo ma;ana durante el dia.

**Comment by RigoFlores** [comment]
Con cuál XML debo probar esta addenda en web???

**Comment by jccastillo0007** [comment]
Esta addenda no ocupa xml de addenda, se completa con los datos propios de la factura... solo tienes que facturar al cliente con el rfc receptor de dicha addenda, empieza con TRI....

**Comment by RigoFlores** [comment]
en conector ocupa 2 datos extra a nivel producto, el POS y el noID
<cfdi:PODetalle Cantidad="1.00" IVA="201.60" Line="2" PO="999888" SubTotal="1260.00" Total="1461.60" UUID="85E46DE9-7E57-485F-B104-C41A9AA2660A" noIdentificacion="SRV"/>

Si los consideraste en el código que subiste??
De hecho el purchase order debe ser el mismo para toda la factura, podría solo capturarse una vez.
Y el noIdentificación, podría ser el id del producto. 
Entonces solo se ocuparía el POS, a nivel general, lo cual si implica tener un XML para esta addenda con un solo dato, que no?

**Comment by jccastillo0007** [comment]
Tienes razon... son dos datos extras a nivel producto... los pueden agregar directamente en la pantalla, aqui no se ocupa XML ya que se soportan datos extras a nivel producto... ojo... el primer dato extra es PO y el segundo es el NoIdentificacion, debe ser en ese orden

**Comment by RigoFlores** [comment]
Bueno, pues así nos vamos aunque debería ser un solo dato... el POS a nivel general, pero para que quede igual que en escritorio, lo manejamos con 2 datos a nivel producto...
