### ISSUE TITLE
Navision-Españoles-SQL Server - no envía la tasa de IVA correctamente al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#506]
A partir del último cambio el 26 de octubre se presentó esta situación.
Se comentó que era porque la factura contenía productos con tasa 0 (realmente comentarios y no productos), pero no.
Revisando al menos la factura 105 y 125, contenían comentarios y productos (es decir tasa 0 y 16%) del IVA, y si se estaban enviando al PDF... algo pasó por ahí...
Entiendo que cuando el tipo del producto es '0', significa que es comentario y no se toma en cuenta para propósitos de ningún cálculo, incluyendo las tasas y montos d eIVA...

**Comment by jccastillo0007** [comment]
Me quedé en que se debe validar con los españoles como manejar esto, ya que se tienen dos tasas y nosotros solo estamos mandando una, antes si funcionaba porque no aceptábamos tasa = 0, pero como ahora si se acepta, la tasa = 0 es la del primer producto y por eso se manda al jasper.

**Comment by RigoFlores** [comment]
Pues no, tampoco es así... antes si se enviaba la tasa 0 al PDF.

Si checas las facturas para el rfc XEXX010101000, por ejemplo la factura 130 del 2015, que es del 23 de septiembre... no lleva IVA (o según ellos IVA exento)... el caso es que en la factura PDF se incluye como tasa y monto del iva 0.00.
En el XML, extrañamente no se envía la tasa 0, simplemente se reporta como exenta (es decir no se reportan impuestos trasladados).
Quizás por aquí está el asunto....
