### ISSUE TITLE
Navision-SQL Server-Españoles - sigue sin llegar 100% de las facturas al inbox

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#507]
Seguimos en las mismas.
La petición es implementar ya algo mas robusto... httpnosequemadres o lo que aplique en este caso

**Comment by jccastillo0007** [comment]
Este no es un defecto nuestro, esta del lado de los españoles, en todo caso, hay que levantar un ticket de mejora para implementar otro mecanismo.
