### ISSUE TITLE
CONECTOR - HOTEL COLONIAL DE VERACRUZ-TASA INCORRECTA DEL ISH

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#508]
EL IMPUESTO SOBRE HOSPEDAJE, SE ESTÁ REPORTANDO AL XML COMO 200.00 EN LUGAR DEL 2.0
EL ARCHIVO DE TEXTO APARENTEMENTE ESTÁ CORRECTO

**Comment by jccastillo0007** [comment]
En realidad lo que esta incorrecto es el archivo txt, la tasa reportada debe ser 0.02 para expresar 2 por ciento, al hacer este cambio el XML se corrige automaticamente, y lo que tengo que arreglar es el PDF.

De lo contrario, si trato de arreglar el XML con la tasa reportada de 2.0, le voy a pegar a todos los clientes que utilizan impuestos locales desde pantalla.

**Comment by RigoFlores** [comment]
Pues no, ya envié evidencia que apunta a que antes si jalaba y ahora ya no...
No sé en que momento se movió, pero el cliente supongo que hasta ahora se dió cuenta...:(

**Comment by jccastillo0007** [comment]
Ya encontré el cambio que provocó este issue, fue el día 1 de febrero de 2015, y efectivamente antes si se soportaba en 2.0, esto quiere decir que cuando capturan una factura desde pantalla con impuestos locales, antes lo hacía como 0.02%.

Voy a respetar lo que el cliente hacía desde el 2010 y aceptar 2.0 en el archivo y corregir como se genera el impuesto local desde pantalla.

**Comment by jccastillo0007** [comment]
Fixed en la versión 9.1.12

**Comment by RigoFlores** [comment]
Si me preocupa este asunto, ya que nunca hemos capturado la tasa como 0.2.
Este impuesto sobre hospedaje, nunca fue capturado en pantalla, ya que el hotel siempre se ha movido por conector.

**Comment by jccastillo0007** [comment]
Si es correcto, la tasa de 2.0 se convierte a 0.02 al momento de calcular
el impuesto, y luego se muestra correctamente en XML y PDF, es m[as un
manejo interno que de captura de la tasa.

Todo esto aplica para los impuestos locales, sin importar si son de
hospedaje o no... e incluso sin importar si llega por conector o pantalla.

Saludos.
JC.

2015-11-18 12:05 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
TE ENVIÉ UN CORREO... TIENE PROBLEMAS QUE CUANDO LO CAPTURAS DESDE PANTALLA, LA TASA LA ENVÍA INCORRECTA AL XML, Y NO ESTÁ ENVIANDO EL NOMBRE DEL IMPUESTO LOCAL AL PDF
