### ISSUE TITLE
Retenciones - Falta la opción de exportar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#511]
Falta agregar la opción de exportar en la pantalla de consultas de retenciones. Para generar un excel con el resultado de la consulta, y el zip con todos los pdf y xml presentados en pantalla

**Comment by jccastillo0007** [comment]
Done....

**Comment by RigoFlores** [comment]
no pues no lo veo en pruebas...

**Comment by jccastillo0007** [comment]
En consultas, hay un botón de exportar abajo, al darle click, genera un zip y un excel, chiaaaaa
![screen shot 2015-12-08 at 9 42 53 pm](https://cloud.githubusercontent.com/assets/2245679/11676122/0726c092-9df5-11e5-95aa-49f0133730bf.png)

**Comment by RigoFlores** [comment]
CUANDO LO LEVANTÉ, NO EXISTÍA ESA OPCIÓN.... CHIAAAA
