### ISSUE TITLE
Figueacero - Validación de XML ante el sat (escritorio)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#512]
Implementación de Validación de archivos XML recibidos por Figueacero
Se entregará una aplicación basada en el Factura-T actual, es decir con la misma tecnología e implementación.
En el equipo de cómputo donde se instale la aplicación, se definirá una carpeta específica para colocar los
archivos XML recibidos por Figueacero, esto es, las facturas electrónicas emitidas por sus proveedores.
a) Se tomará c/u de los archivos XML dentro del directorio definido para dicho fin, y se validará ante el SAT.
Una vez ejecutado el proceso de validación, se moverá a la carpeta de Procesados.
b) Existirán 5 estados como resultado de la validación: Vigente, Cancelado, No existente, SAT no disponible,
Receptor Incorrecto (no es de Figueacero).
c) La información de la validación, se almacenará en BD incluyendo: Fecha Validación, Estado, Folio SAT,
Serie Interna, Folio Interno, Fecha Emisión, RFC Emisor, Nombre Emisor, Total
d) Se podrá consultar en pantalla el resultado de la validación, aplicando distintos filtros, y distinguiendo en
color rojo o similar, las facturas que no contengan el estado Vigente (vigente sería el estado indicativo que todo
está OK).
e) El resultado de la consulta se podrá exportar a excel
f) Si un mismo XML se valida en varias ocasiones, aparecerá varias veces en la pantalla de consultas.
g) La aplicación de facturación actual, será la misma encargada de validar los XML recibidos.
h) La BD de la validación, se someterá a los mismos mecanismos de depuración y respaldo.

**Comment by jccastillo0007** [comment]
todo iba bien hasta el punto en h), chiaaaaa

Oye, en la pantalla de consultas esto es lo que quieren ver:

Fecha Validación, Estado, Folio SAT, Serie Interna, Folio Interno, Fecha Emisión, RFC Emisor, Nombre Emisor, Total

Estos son los únicos datos que se guardarán en la nueva tabla, esta bien?

**Comment by RigoFlores** [comment]
afirmativo

**Comment by jccastillo0007** [comment]
La buena noticia. 
Podemos usar el mismo folder que se usa para procesar los archivos del conector
Se va a validar si es una remision o factura recibida
Si es remision se manda a eFacturaT
Si es factura, se manda timbrar y también se dará de alta en eFacturaT 

Pregunta.
Podemos poner la pantalla de consultas de facturas recibidas ya validadas en web y no en standalone?
En standalone es mucho mas complejo y si lo ponemos en web, ya existe dicha funcionalidad en el menú de compras, asi podemos empujar a usar la versión web.

Como la veis..

**Comment by RigoFlores** [comment]
Me confundí, dices que si es factura se manda a timbrar para dar de alta en eFacturaT.
Aquí estamos hablando de validar un XML ante el SAT; se trata de facturas ya timbradas y donde Figueacero es el receptor de las mismas.
La pantalla me parece, si tendría que ser en escritorio, ya que desde ahí es que operan todo.
Entiendo que es otra pantalla de consultas, pero no se podría ocupar la misma infra que ya se tiene de la pantalla de consulta actual?
Por cierto quedé de dar fecha de entrega, ya dieron el anticipo ayer.

**Comment by jccastillo0007** [comment]
Sorry, me confundí con el otro proyecto donde quieren usar el DescargaT desde conector.

Con respecto a tiempos, pues ya casi tengo la funcionalidad en standalone, ahora el único problema es que la interfaz gráfica se pone muy romantica en Standalone, y aunque voy a reutilizar casi todo lo de la pantalla actual de consultas, como quiera es un relajo hacer que se vea bien... la siguiente semana ya deberia estar.

Estas pensando en venderlo como un plugin para otros posibles clientes interesandos?, yo como que lo veo como parte de la funcionalidad de standalone, ofrecerlo como plus para ganar mas clientes, tú como ves?

**Comment by jccastillo0007** [comment]
Subí al dropbox un release para este requerimiento...

Ojo....
Los archivos se tomarán desde el mismo lugar donde se procesan los archivos txt con las siguientes consideraciones.
1. debe tener ext xml
2. si el xml no esta timbrado, se manda timbrar
3. si el emisor es el rfc cliente de facturat, se manda cancelar
4. si el receptor es el cliente de facturat, se valida ante el sat
5. si el cliente de facturat, no es el emisor ni el receptor, el xml se da de alta con el estatus Receptor Inválido.

Los puntos 1 al 3, es funcionalidad ya conocida, solo se agregaron los puntos 4 y 5

La pantalla de busqueda aún no esta al 100, no se hace el filtrado por rfc y/o nombre del cliente y el export de la info no esta completa.

**Comment by RigoFlores** [comment]
Falta colocar en semáforo verde los vigentes y en rojo o naranja los distintos a vigente. Así como cuando en consultas se realiza para el envío de facturas por mail.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Otra cosa que no detecté yo, sino el cliente. En los filtros para consultar las recibidas, en particular el rfc... muestra el listado de clientes de figueacero, en lugar de mostrar los emisores (proveedores de figueacero)... Es decir, estará faltando una tabla o similar, donde se almacenen los datos de los proveedores de figueacero, para que en las consultas de recibidas se pueda filtrar por rfc emisor.

**Comment by RigoFlores** [comment]
Que también debe mostrar el nombre del emisor, es decir ellos quieren filtrar por rfc o nombre del emisor.

**Comment by jccastillo0007** [comment]
Fixed., este defecto esta duplicado.

**Comment by RigoFlores** [comment]
ok, cerraré este aunque queda el pendiente de la depuración
