### ISSUE TITLE
polizas- agregar opcion de cuadrar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#513]
es un botón que cuadra el último monto a capturar, en el debe o haber (según sea el caso), para que la póliza cuadre. ya lo había solicitado, pero como que no hallo el issue aquí

**Comment by jccastillo0007** [comment]
A que se refiere eso de cuadrar ? que operaciones se deben hacer o no
hacer....esta peligroso que nosotros cambiemos cifras para cuadrar algo, si
es lo que estoy entendiendo.

Saludos.
JC.

**Comment by RigoFlores** [comment]
Precisamente esta función ayuda al usuario a validar sus pólizas.
Imagina que han capturado 100 asientos dentro de la póliza... entonces el último asiento, es decir el que se está capturando en ese momento corresponde a la suma de todas las cantidades de los 100 asientos anteriores. Sumarlos a manopla, sería una chinga. Entonces lo que se hace es darle en cuadrar... y lo que hace es agregarle al deber o al haber, la cantidad que cuadre la póliza. En ese momento se calcula dicha cantidad, y el usuario podrá validar si es correcto o no dicha cifra. En caso de ser incorrecto, tendrá que validar asiento por asiento, para identificar donde la cagó durante la captura.
Esto ya lo hemos comentado, no lo invento yo, ya lo contienen los sistemas actuales como COI, que es en el que nos estamos basando para ello.

**Comment by jccastillo0007** [comment]
psssss vamos a meternos en problemas

Cuando lo vaya hacer, te pregunto que exactamente debo hacer.

Saludos.
JC.

2015-12-03 9:27 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Ahora mismo cuando le das guardar póliza, se ejecuta un proceso de validación de cuadre. Realmente este requerimiento ya lo hacemos, y cuando no cuadra (considerando que ya se corrigió el issue al respecto) se envia un mensaje. El botón de cuadre tiene que hacer lo mismo, y detectará que no cuadra ya que el haber y el deber son distintos. La idea es solo igualar dichos montos en la última transacción capturada en la póliza. Por ejemplo si la suma del deber es 1000 y la suma del haber son 900, el botón de cuadrar agregará 100 en el haber de la transacción (asiento) que se está capturando en ese momento.

**Comment by jccastillo0007** [comment]
Si, ya se que ya existe esa validación, lo complicado es hacerlo y modificar el último registro únicamente..

**Comment by RigoFlores** [comment]
Correcto, solo es sobre el último registro... que debería estar en 0 tanto el deber como el haber, y entonces se calcularía la cantidad correcta.

**Comment by jccastillo0007** [comment]
Checa en PRU como quedo, encontré una opción que era mas fácil de implementar.

Siempre que agreguen un renglón, aparecerá el nuevo renglón con las cifras ya cuadradas, espero que esta opción sea suficiente para mantenerlo simple.

JC.

**Comment by RigoFlores** [comment]
Lo de las pólizas, es la captura de cada transacción de una empresa o negocio. Una transacción puede ser emitir una factura. Esta transacción puede requerir de unos 3-6 asientos en la póliza. Por ello es tan importante que se pueda capturar lo mas ágilmente posible. Eso implica poder capturar únicamente con el teclado y con el menor número de teclazos posible.
Imaginate figueacero que emite 5,000 facturas al mes, mas todos los movimientos bancarios, proveedores, etc. Es una locura. Entonces se busca que la captura sea muy muy ágil, y que no tengan que esta cambiando de teclado a mouse; solo teclado.

**Comment by RigoFlores** [comment]
Dicho lo anterior, esta propuesta de cuadre, provoca que se tenga que estar dando teclazos de más, ya que en cada asiento hay que borrar la cantidad sugerida, que en realidad solo se ocupa a petición del cliente, entonces hay que estar borrando, agregando un paso mas al proceso de captura.
En COI, el cliente se posiciona en la celda de cualquier asiento, le dá cuadrar y automáticamente coloca la cifra del deber o haber, para cuadrar la póliza.
No queremos copiar al COI, queremos hacerlo mejor. Pero tampoco queremos agregar pasos al proceso... (teclazos de mas, ni uso de mouse en esa pantalla)

**Comment by jccastillo0007** [comment]
Debo ver la manera de no usar el mouse, si no, puro tab, eso solucionaria
el problema, ya que la cifra sugerida de cualquier manera la tienen que
modificiar, ya sea por un 0 o por la cifra correcta, ahi no le veo
problema, pero si estarse cambiando a usar el mouse.

Saludos.
JC.

2015-12-18 9:57 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Es como te decía, los asientos NO VAN EN PAREJAS.
Cuando se emite una factura se capturan al menos 3 cuentas (depende de cada contador): 
1. Ventas (DEBER, subtotal)  Ej $100.00
2. IVA facturado (DEBER, monto IVA)  Ej $16.00
3. Clientes (HABER, total de la factura)  Ej $116.00

Al capturar esta póliza simple, que lleva 3 asientos... le estamos agregando un paso, que es el borrar el valor sugerido del HABER en el paso 2, y teclear el valor correcto en el paso 1
Cuando la factura se paga, se tienen que registrar otros tantos movimientos... en bancos, iva por trasladar, clientes, cuentas x cobrar... bla bla bla...

**Comment by RigoFlores** [comment]
No me parece mal la idea de sugerir el valor, pero habría que ver como disparar esa sugerencia... se podría hacer lo siguiente:
cuando llega el tabulador a ese campo, lo sugiere... si se le da tabulador para pasar al siguiente campo lo cambia a cero y ahora el siguiente campo tendría la sugerencia....por otro lado, si se le da enter... acepta el valor y se mueve al siguiente campo dentro del orden tabulador...

**Comment by RigoFlores** [comment]
Creo que es un buen torito, implementar algo mas simple que el COI, ya que es ahí donde podríamos resultar atractivos para los contadores... una captura ágil, cuasiautomática... solo teclado, sugerencia de nombres de cuenta, cuadres...

**Comment by jccastillo0007** [comment]
Como lo veo yo, ustedes ya estan viciados con lo de COI, es cuestión de cambiar el mindset, este es mi análisis.
1. El detalle de no usar el mouse, es fundamental, para poder medir la usabilidad de la pantalla, esto es lo primero que debo arreglar.
2. Una vez resuelto el punto 1, lo que sucede es que al agregar un nuevo registro, una de las dos cantidades haber o deber, se muestra en 0 y la otra con alguna cantidad x para poder cuadrar
3. El 99% de las veces querrán cambiar esos valores seteados en el punto 2, (es el 99% porque solo al final podrían estar de acuerdo con el valor asigando)
4. de las veces que quieran cambiar los valores, el 50% de las veces querrán cambiar el valor propuesto para cuadrar, lo que significa que como quiera deben ingresar una cantidad específica
5. El otro 50% de las veces, querrán poner 0 en lugar de la cifra sugerida, lo cuál solo implicaría un tab y un 0, ya estando en ese registro y arreglado el punto 1, creo que esto ya es lo de menos.

**Comment by RigoFlores** [comment]
Mi comentario, no tiene nada que ver con lo de COI.
Tiene que ver con el contenido de una póliza, que en general se compone al menos de 3 cuentas, es decir 2 cargos y un abono, o viceversa. 
Vamos viendo que le parece al cliente y que ellos mismos digan. Para mí, sugerir siempre el cuadre, provocará mayor número de pasos en el proceso... y quizás también mas fuente de errores de dedo....
Se me ocurre una chacarronada, que creo que podría funcionar.... que pasaría si al colocarse en el cargo o abono, teclean una simple 'c' ó 'C'... al cambiar el foco de la celda con un tabulador, entenderá que es un cuadre... eso serviría???

**Comment by RigoFlores** [comment]
a mi me suena razonable, teclear una simple 'c', y tabulador o cambio de foco del cursor... y con ello sería el indicativo de cuadrar ese registro en particular... ese asiento... mas que chacarrón, hasta elegantioso se escucha

**Comment by RigoFlores** [comment]
eni nius?

**Comment by RigoFlores** [comment]
No es posible lo que estoy proponiendo de que al momento de teclear una C, y luego el cambio de foco (por tabulador o click), entienda que ahí debe aplicar el cuadre????

**Comment by jccastillo0007** [comment]
al dia de hoy, no tengo control sobre lo que el usuario esta tecleando, como para identificar una letra C o un tab, este simple detalle es lo que nos esta atorando de arreglar el tab index y poder navegar con el puro teclado, necesito encontrar un workaround para eso primero, y creeme que yo soy fan de no usar el mouse.

**Comment by RigoFlores** [comment]
Con lo que ya resolviste para el catálogo de cuentas (que no se repitan), ya se podría implementar esto del cuadre con una 'C'?

**Comment by jccastillo0007** [comment]
al dia de hoy, no tengo control sobre lo que el usuario esta tecleando, como para identificar una letra C o un tab, este simple detalle es lo que nos esta atorando de arreglar el tab index y poder navegar con el puro teclado, necesito encontrar un workaround para eso primero, y creeme que yo soy fan de no usar el mouse.
