### ISSUE TITLE
validación XML - reporte excel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#516]
El reporte excel no contiene las mismas columnas que el reporte en pantalla. De hecho los encabezados no coincide
De hecho se debe colocar el nombre del emisor al final, para que no afecten las ',' que contenga el nombre.

**Comment by jccastillo0007** [comment]
Cierto... eso no lo corregí, pero ya esta en el release de hoy.

**Comment by RigoFlores** [comment]
el nombre completo, aún al final se pasa a otra columna.
Yo creo que será necesario eliminar las ',' del nombre del emisor para este reporte de recibidos.
