### ISSUE TITLE
validacion XML - Ordenar consulta por fecha de emision/timbrado y rfc emisor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#517]
Debe tener un orden el desplegado, entonces de acuerdo a los reportes que genera el portal del SAT, debe ser por fecha de emisión (o timbrado si se complica la emisión) y luego por rfc, para una fácil ubicación de las facturas recibidas, ya que en el caso de figueacero reciben muchas facturas...

**Comment by jccastillo0007** [comment]
Ya se ordena por fecha de emisión y RFC, pero como la fecha de emisión tiene hasta segundos, esto ocasiona que el ordenamiento por RFC parezca que no se hizo, ya que sería muy difícil tener dos facturas del mismo segundo.  Esto se puede checar en el release de hoy en el dropbox.

**Comment by RigoFlores** [comment]
El cliente presentó el proceso en toda la empresa, y han determinado que el ordenamiento debe ser conforme se van validando los XML (es decir, como estaba o lo que es lo mismo por ID)...

**Comment by RigoFlores** [comment]
Lo que no me dijo, es si quiere hasta arriba los últimos id o los primeros.
Supongo los últimos, de acuerdo a lo que platicamos hoy en la tarde.

**Comment by jccastillo0007** [comment]
chiaaaaa

Done.

**Comment by RigoFlores** [comment]
OK, quedó al revés... primero coloca los mas viejos y al final de la consulta los mas nuevos.
Lo que pide el cliente (que incluso lo comenté anoche), es que el primer id en la parte superior de la consulta, sea el mas reciente (el id mayor), para que puedan ver con un solo pantallazo (sin necesidad de bajarse), las últimas facturas validadas.

**Comment by jccastillo0007** [comment]
Chiaaa, fixed.
