### ISSUE TITLE
Corregir los mensajes de error, así como la corrección del timbrado y cancelación con finkok

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#519]
Es posible que cuando se implementó lo de retenciones con Finkok, se movió algo.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
PROBÉ CON EL ÚNICO ESCENARIO QUE CONOZCO Y YA MARCÓ EL XML MAL FORMADO. ESTAREMOS PENDIENTES DE ESTO
