### ISSUE TITLE
Permite Modificar rango de folios, y al hacerlo reinicia el consecutivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#52]
Tenía definido un rango de folios del A1 al A10.
Lo edite desde el catalogo de folios, lo cual de entrada es incorrecto, ya que el rango de folios estaba activo, y su consecutivo actual era folio 24... (aún cuando su rango superior era 10,,,, jejeje).
Le modifiqué el rango superior, a 25 en lugar de 10, que ya tenía.

El resultado de lo anterior, es que en la pantalla de factura presenta la serie A, iniciando con el folio 1. Incluso generé la factura, y efectivamente le asignó el folio A1.
Al checar el rango de folios nuevamente desde el catálogo, ahora indica que la serie A va del 1 al 35... es decir le agregó 25 folios al rango superior.

**Comment by jccastillo0007** [comment]
Varios puntos en este defecto
1. No podemos evitar que modifiquen un rango de folios, aun cuando esta activo, dado que es para uso interno del cliente, creo que el deberia poder aumentar de 10 a 100 o 1000 si le da la chin... gana, como ves ?
2. Que reinicie el folio actual a 0, ya esta corregido
3. Si el folio actual llega al rango final, ya no permite usar dicha serie, antes si te dejaba, porque el folio actual se reiniciaba a 0.

**Comment by RigoFlores** [comment]
Cerraré este issue, para atenderlo en el #55, ya que están muy relacionados.
El tema principal de este issue 52, es que reiniciaba el folio actual y eso ya está crregido
