### ISSUE TITLE
CE - INDICA QUE NO CUADRA LA PÓLIZA, CUANDO SI CUADRA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#521]
![poliza incorrecta](https://cloud.githubusercontent.com/assets/2912775/11798326/6bac7680-a28f-11e5-9bfe-f6104d5da5d9.png)

**Comment by jccastillo0007** [comment]
Este issue lo voy a revisar mañana, seguramente traigo una diferencias de milésimas que ocasiona que la comparación no sea igual, pero debe ser despreciable... mañana lo valido para que lo revise tu asesor de bolsillo que tienes., pero lo del botón de cuadrar si esta mas cabron.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Ya quedó en producción también. Lo validé en pruebas.
