### ISSUE TITLE
Permitir la configuración/alta de nuevos impuestos locales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#523]
Ya se está complicando el asunto.
Así como el cliente configura el IVA, ISR o IEPS, dar la posibilidad que configure cualquier otro impuesto, que al llamarse diferente a los demás, será considerado como impuesto local.
Algo muy similar que lo que tenemos en escritorio, pero para web.
Es un pedo estar dando de alta a manita los impuestos locales.

**Comment by jccastillo0007** [comment]
Este requerimiento no es factible, por:

En standalone se tiene un catalogo de impuestos por cliente, ya que cada instalación se refiere a un solo emisor, y esto facilita mucho el hacerlo personalizado, en web, se tiene un catálogo en general y no por emisor.

Lo que implica hacer un catálogo de impuestos por emisor en web, es demasiado esfuerzo, y no es fácil saber que clientes ocupan que impuestos, podríamos batir la base de datos.

**Comment by RigoFlores** [comment]
OK, entonces que no sea por emisor, sino que nosotros podamos agregarlo en una tabla que aplique a toda la aplicación, a solicitud del cliente.
El tema es que mucha ocasiones, los usuarios de esta función cambian el nombre del impuesto aunque se trate del mismo, y así tiene que ir en el pdf y xml, lo cual genera que cada 'cambiecito' le cueste al cliente esperarse 1 día, y con ello en el gobierno les retrasa sus pagos semanas o meses cuando se trata del último día para ingresar una factura.
Si queda general, no es lo ideal pero es un punto intermedio.
