### ISSUE TITLE
Permitir personaliza el correo para enviar las facturas desde web.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#524]
Así como la magnífica versión de escritorio... lo malo es que es web y no sabemos si se pueda... :(

**Comment by jccastillo0007** [comment]
Noup, no se puede.... bueno tal vez si, porque con software todo se puede, tendríamos que agregar la configuración de la cuenta de correo en la pantalla de configuración, pero el esfuerzo es alto.

**Comment by RigoFlores** [comment]
mas bien había pensado que se hiciera como en escritorio, es decir a través de un archivo para no afectar la pantalla actual de configuración. Eso facilitaría su implementación?

**Comment by jccastillo0007** [comment]
Done... ya est[an los campos disponibles en la pantalla de configuraci[on, pero a[un no los toma en cuenta para enviar correos, necesito probar con gmail y hotmail.

**Comment by RigoFlores** [comment]
Entonces no está done, si aún está incompleto.

**Comment by jccastillo0007** [comment]
No inventes, ya esta funcionando con las cuentas de FacturaT, pero no funciona con Gmail y Hotmail.... crap...

**Comment by jccastillo0007** [comment]
Listo, ya funcionó con FacturaT, Gmail y Hotmail.... esta en Pru, el fin de semana lo subo a Pro.

**Comment by RigoFlores** [comment]
Probé con la cuenta que me dió el cliente de manera temporal y no jaló.
cuenta: fiscal@siscomqro.com, pwd:    $fiscal1$   , server: mail.siscomqro.com, pto: 587

en outlook si jaló, desde facturat escritorio también jaló; es en web donde no jaló esta cuenta.

**Comment by jccastillo0007** [comment]
Este es el error que arroja..

2015-12-29 23:26:23,349 ERROR [http-bio-8080-exec-5](SendInvoiceOrCancelInvoiceToReceptor.java:525) - javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
    javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.mail.MessagingException: Could not convert socket to TLS;

Como lo configuraste en StandAlone... en web tenias configurado el puerto 995 y no el 587...., pasame el .properties que usaste en standalone...

Con el usuario de la TIA en PRU, utilicé el cliente XXX....001 y le puse mi correo de facturat para hacer pruebas.

**Comment by RigoFlores** [comment]
Yo le configuré puerto 587, no sé de donde salió el 995 que dices. Como quiera aquí están los parámetros del properties que si jaló en escritorio:
facturaT.SMTP_HOST_NAME=mail.siscomqro.com
facturaT.SMTP_HOST_PORT=587
facturaT.SMTP_AUTH_USER=fiscal@siscomqro.com
facturaT.SMTP_AUTH_PWD=$fiscal1$
facturaT.TLS=false

no tendrá que ver el pwd?

**Comment by RigoFlores** [comment]
Y esto cuándo lo puedes validar? Necesitamos que envíe desde esta cuenta en producción para el cliente que maneja periódicas y que no le están llegando a sus clientes los correos con las facturas.

**Comment by jccastillo0007** [comment]
Listo... faltaba configurar el parámetro TLS, yo estaba asumiendo siempre true, pero en este caso se requiere false.

Estará listo en el release de hoy de PRU y PRO.
