### ISSUE TITLE
Validador XML - no refresca el rfc de un XML recién validado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#525]
Cuando se valida un XML de un emisor que no existe en la BD, no lo muestra en los filtros.
Hay que cerrar el programa y volverlo a abrir y entonces ya lo muestra. Solicita Figueacero que se refresque en automático

**Comment by jccastillo0007** [comment]
wey... cual es el validador XML... no lo encuentro chiaaaaaa es web o standalone...?

**Comment by RigoFlores** [comment]
Es escritorio, vía el conector... detectas un XML (supongo yo que validas que el emisor no sea nuestro cliente, es decir el rfc de la llave), entonces se considera como una factura recibida.
Se procede a validar ante el SAT, y el resultado se consulta en la pantalla de consulta.
Lo que sucede es que si el rfc del emisor es nuevo para facturat, entonces no lo presenta en el filtro de rfc's. Tienes que cerrar el facturat, y luego lo vuelves a abrir, y entonces ya aparece el rfc en la lista para poder filtrar por ello.
