### ISSUE TITLE
Validador XML - cuando se quiere filtrar por nombre, muestra el rfc

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#526]
En la pantalla de consultas del validador, si se ocupa filtrar por rfc aparece el listado de los emisores.
Si se ocupa filtrar por nombre del emisor, igualmente aparece el listado de los RFCs emisores; se ocupa que aparezca el nombre del emisor (obviamente).

**Comment by jccastillo0007** [comment]
chiaaaaa, esto pasa cuando no se prueban bien las cosas antes de liberar jojojojo

**Comment by RigoFlores** [comment]
Estoy validando con el cliente si ocupa que se registren los datos de proveedores, cuando no pasa la validación. Ahora mismo no se están guardando.

**Comment by RigoFlores** [comment]
Confirmado, el cliente ha solicitado que aunque no pase la validación, también se agregue el RFC y nombre para ocupar el filtro.
Es decir el issue se traduce en que no agrega el nombre y rfc cuando el XML no tiene el semáforo en verde.

**Comment by jccastillo0007** [comment]
chiaaaa, done

Ya que se decida el cliente como quiere las cosas y sobre todo que nos pague.

**Comment by RigoFlores** [comment]
Ya muestra el nombre de los emisores, pero ahora no le hace caso al filtro por nombre.
Es decir aunque despliega la lista y yo quiera elegir cualquier nombre, no me hace caso... no lo selecciona, deja el primero que filtraste y de ahí ya no lo cambia... chiaaaaa

**Comment by RigoFlores** [comment]
El filtro de rfc funciona perfecto, no así el de nombre que no lo está tomando en cuenta

**Comment by jccastillo0007** [comment]
Fixed.
