### ISSUE TITLE
Retenciones - no me permite cancelar 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#527]
Intenté hoy con uno de la tia, y marca error...

**Comment by jccastillo0007** [comment]
En este ando.....

**Comment by RigoFlores** [comment]
Lento pero andamos...

**Comment by jccastillo0007** [comment]
??????????? que pedo con tus pinches proveedores de timbrado..

Necesito la info que les pedí para implementar la cancelación.

**Comment by RigoFlores** [comment]
-----Mensaje original-----
De: Yair Castro [mailto:nycastro@facturehoy.com] Enviado el: martes, 05 de enero de 2016 12:52 p.m.
Para: 'JC'
CC: 'Rigoberto Flores'
Asunto: RE: Problemas para cancelar retenciones.

Buena Tarde

Podrías comentarme por favor que error les está apareciendo, y si podría explicarnos de que manera está mandado a cancelar la retención.

Y una duda extra, podría decirme si anteriormente habían realizado alguna cancelación de Retenciones.

Yair Castro

Ejecutivo Atencion a Clientes

**Comment by RigoFlores** [comment]
Ya enviaron otro correo..

**Comment by jccastillo0007** [comment]
Algo le movieron... hoy recibí este mensaje :   

FH1028 - comprobante con folio 9F6B34A2-A87A-48D2-BF9F-8BFA6BB3D24C cancelado, pendiente de enviarse al SAT]

Aún no esta listo el requerimiento, pero si mis pruebas siguen asi, para jueves o viernes ya estar[a lista la cancelaci[on, si es que no quitan los alambritos que estan poniendo.

**Comment by jccastillo0007** [comment]
Done, hoy lo subo a PRO.

**Comment by RigoFlores** [comment]
pues no, no jala en pro...

**Comment by jccastillo0007** [comment]
Un comentario asi de ambiguo no me sirve de nada... yo generé y cancelé dos
retenciones y con la respuesta de FactureHoy, asi que, para poder avanzar
necesito información detallada de las pruebas.

Saludos.
JC.

**Comment by RigoFlores** [comment]
En producción, con la cuenta de la TIA, existen las mismas 2 retenciones desde que inició este proceso y que no se han podido cancelar desde nunca.
Al darle cancelar, sigue marcando error... que ahora dice...

127 Error al cancelar CFDi de Retenciones con el PAC

**Comment by jccastillo0007** [comment]
Ya esta jalando... no te estaba mostrando el error original del PAC, para el primer comprobante que tenia la TIA, es que el comprobante de retención no fué timbrado por facture hoy... el segundo comprobante ya lo cancelé y me di cuenta que faltaban algunos datos de enviarse al PDF, ya los esta enviando y ya esta en PRO.
