### ISSUE TITLE
Plugines - no son compatibles complemento de gobierno con datos extra

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#528]
Si coloca el complemento de impuestos locales en el XML, pero pone ceros en lugar de las cantidades que corresponden.

**Comment by jccastillo0007** [comment]
Esto es en standalone?  si es asi, me pasas la llave que usas pl., si es en web, lo pruebo en pruebas jajaa.

**Comment by RigoFlores** [comment]
El que tenemos detectado claramente es en web, vamos a realizar la misma prueba en escritorio y te comento.

**Comment by RigoFlores** [comment]
En escritorio sucede lo mismo, y el escenario en ambos casos es siempre y cuando captures DATOS EXTRA, junto con IMPUESTOS LOCALES. Es decir, no solamente tiene que ver con los plugines, sino mas bien en combinación con la captura de ambos.

**Comment by jccastillo0007** [comment]
Fixed, en ambos Standalone y Web... si que se arma un desmadre pero ya lo identifiqué.

Ubicas al cliente :  ARG1201271T9

Tiene un proceso medio especial con esto de los impuestos locales, puedes verificar que todo funcione con ese cliente.

**Comment by RigoFlores** [comment]
Este cliente ya no está con nosotros. creo que se dió de baja o simplemente se fue cuando tronaron la empresa...

**Comment by RigoFlores** [comment]
Voy a validar en web y escritorio, entonces entiendo que se liberó una nueva versión en estánalon?

**Comment by jccastillo0007** [comment]
Yeap.

Saludos.
JC.

**Comment by RigoFlores** [comment]
Creo que no reporté este tema, pero en escritorio si le das preview antes de generar la factura, empieza a cambiar la tasa del impuesto local... lo va multiplicando por 10.....

**Comment by jccastillo0007** [comment]
Fixed, release 9.1.17 de hoy mismo

**Comment by RigoFlores** [comment]
Sigue sin jalar:
a) En el XML todo bien, excepto que el nombre del impuesto local no lo incluye
b) En el PDF hace un desmadre.., ya que tampoco envía el nombre del impuesto local capturado, pero además en el contenido del dato extra1, envía nosequemadres de variables internas de la aplicación; esto sucede cuando se captura el impuesto local. El dato extra 1 que capturé, quién sabe donde lo envía... probé en escritorio, con una llave que únicamente tiene datos extra y gobierno

**Comment by RigoFlores** [comment]
![error imp local](https://cloud.githubusercontent.com/assets/2912775/12400612/d1c9b3f2-bde6-11e5-82b8-b20a145940fc.png)

**Comment by jccastillo0007** [comment]
Listo... aqui esta lo que pasaba.
1. Si faltaba enviar los nombres de los impuestos locales al pdf, pero no al XML, ahi si se mandan siempre
2. Cuando el usuario no incluye datos extras, entonces el dato extra 1 es el bean con la informacion del impuesto local
3. Si el cliente incluye datos extras, se respetan los n datos extras, y el dato extra n+1 será el bean con la info del impuesto local

No se como evitar que te afecte el dato extra que tiene el bean de la info del imp. local, ya que lo necesito para poder enviarlo al PDF.

Te mando por correo ejemplos de como te llegarian los datos extras con o sin datos agregados por el usuario.

**Comment by RigoFlores** [comment]
Pues no, como bien conoces... en el jasper, tenemos que indicar y dejar fijo cuál dato extra corresponde lo que se está enviando al PDF.

**Comment by jccastillo0007** [comment]
Eso esta bien, si la plantilla esta esperando un dato extra para ese cliente, entonces seguramente va a llegar el dato extra en esa posición, lo malo sería que tengas una plantilla para un cliente que va a usar datos extras, y que dichos datos extras no se manden, en ese caso te va a llegar en el dato extra 1 la info del imp local.

**Comment by RigoFlores** [comment]
Recordar que los datos extra son opcionales en todo caso. Algunas veces se ocuparán, y otras no.
Pero bueno, lo que me comentas... no puede ser que el dato extra 1 SIEMPRE SEA LA INFO DEL IMPUESTO LOCAL, y con ello, nosotros solo consideramos en la plantilla a partir del dato extra 2 en adelante???...

**Comment by jccastillo0007** [comment]
Negativo... eso es mas costozo... como el dato extra donde viene el
impuesto local es solo temporal, lo mas natural y simple es mandarlo al
final, si lo mando al inicio, le puede pegar a un monton de cosas mas.

Saludos.
JC.

2016-02-03 11:41 GMT-06:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Expired.

**Comment by RigoFlores** [comment]
SE HA CERRADO, IGUALMENTE SIN ATENDER
ASÍ PODEMOS IR CERRANDO TODOS... JEJE... 
FALTA EL STATUS DE 'NO ATENDIDO DE PUROS TOMPIATES'
