### ISSUE TITLE
Enviar al PDF hasta 4 impuestos locales (Web)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#529]
Acabo de reunirme con un cliente y me comentó que ocupa hasta 4 impuestos locales.
Entiendo que en el XML no hay problema, pero en el PDF nos estarían haciendo falta las variables para soportar ese 4° impuesto...

**Comment by jccastillo0007** [comment]
Done... en Pru, pero no lo probé... debería funcionar.

**Comment by RigoFlores** [comment]
Listo, ya solo resta llevarlo a pro.
