### ISSUE TITLE
No trabaja correctamente un rango de folios sin serie

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#53]
Permite dar de alta un rango de folios sin serie, sin embargo despues de guardarla, no se puede editar, ni la muestra como opción en la pantalla de facturar,

**Comment by jccastillo0007** [comment]
Al capturar un rango de folios sin serie, se colocara una cadena por default "SIN SERIE", dicha cadena no aparecera en el xml ni en el pdf.

**Comment by RigoFlores** [comment]
Lo ideal es que simplemente no la mostrara, pero vamos viendo la aceptación del usuario.
Igual y es buena opción.
