### ISSUE TITLE
Polizas - Cuando se edita una póliza cambia el orden de la captura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#530]
Las pólizas se van capturando de manera agrupada. En general una transacción genera unos 3-4 asientos. Y así se van capturando. Pero cuando editas la póliza, les cambia el orden, lo cual provoca que la póliza ya no sea ordenada ni 'legible'.

**Comment by jccastillo0007** [comment]
ahi wey, como editas una poliza?

o no entendi, o no encontré la forma de editar una póliza.

**Comment by RigoFlores** [comment]
jajaja... como así?
En la pantalla de pólizas, eliges una póliza previamente capturada.
Enseguida le das click en el ícono de editar.
Posteriormente empiezas a cambiar data de la póliza.

Necesito investigar mas; acabo de hacer lo que te dije, y no lo pude reproducir. Voy a intentar en pro, donde supuestamente se presentó el asunto.

**Comment by RigoFlores** [comment]
Lo voy a cerrar y en cuanto pueda reproducirlo lo retomamos
