### ISSUE TITLE
No está enviando las notas de crédito Navision al CFDI Inbox

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#531]
En otras palabras, para los españoles, que es conector vía SQL server, no está enviando las notas de crédito al inbox, por lo que no se ven reflejados en el portal web...
Las facturas si se están enviando.... (si que le hemos batallado con este tema... )

**Comment by jccastillo0007** [comment]
Fixed.

Para que el email se dispare, el receptor debe tener configurado un email, si no no manda nada, para el caso de Figueacero, agregué una opción para que siempre las mande, aunque el receptor no tenga un email.

**Comment by RigoFlores** [comment]
No es para Figueacero, es para los españoles... es decir IIP0909294L5
Ellos no tienen configurado correo como emisor, porque no quieren que les lleguen las facturas, sino que se envíen a recibefactura@factura-t.com.mx, que es el inbox o en otras palabras, para que lleguen al portal web

**Comment by jccastillo0007** [comment]
Si por eso.... jajaja, me equivoque al decir figueacero, la validación se hizo para los gachupines e incluso para cualquier cliente que configure el envío automático y que su receptor no tenga configurado un email.

**Comment by RigoFlores** [comment]
A ver, ya no entendí:
a) Se generó una nueva versión para este asunto?
b) porque si enviaba la factura y la nota de crédito no? Respecto al tema de que no tenía correo configurado y por eso no enviaba NADA.
c) Como queda para cualquier cliente que tenga el envío automático y no tenga correo configurado en su llave?

**Comment by jccastillo0007** [comment]
Asi, hay una nueva version en el dropbox para este fix.

El problema podia suceder igualmente en facturas o NC, el pedo era que el
receptor no tenia un email asociado, luego entonces, si el emisor tiene
configurado el envio automatico, y el receptor no tiene correo, como quiera
se le manda el correo a los correos de lemisor.

Si el emisor no tiene ningun correo, como quiera se le manda al receptor
Si el emisor y receptor no tienen ningun correo, pos ya no se manda nada y
a la chingada jajaja.

JC.

Saludos.
JC.

2015-12-28 10:06 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Seguimos sin entendernos.... la pregunta es porque las facturas SI LAS ENVÍA y las notas de crédito NO LAS ENVÍA.... básicamente ahí está mi duda...

**Comment by jccastillo0007** [comment]
Por que depende de que el receptor tenga un email configurado, si eso lo han visto unicamente con Notas de Credito, es mera coincidencia, lo mismo pasaria con facturas donde el receptor no tiene un email configurado.

**Comment by jccastillo0007** [comment]
Favor de revisar y cerrar este issue.

**Comment by RigoFlores** [comment]
OK, acabo de actualizar la versión en producción y será cuestión de esperar.
Ahora mismo, estaba faltando la factura 1 en el portal... solamente estaban la 2 y la 4  (por cierto, la 3 no se porque no se generó, pero es oootro tema que revisaré).
Entonces, consulté el correo del receptor de la factura 4 (que es el mismo receptor de la factura 1), y efectivamente no tiene email configurado.
Lo muy extraño, es que la 1 no está en el portal, pero la 4 SI APARECE EN EL PORTAL.

Muy raro ese comportamiento. Como quiera, oooootra vez estaré pendiente del comportamiento de esta nueva versión. Si es correcto que BAJO CIERTAS SITUACIONES, cuando el receptor no tiene correo configurado, no enviaba la factura por correo, entendemos que ahora la estará enviando siempre y con ello se cerraría el tema. 

Voy a cerrar por lo pronto, pero seguirá en observación, ya que no tengo forma de validarlo ahora mismo, sino hasta que se presente la situación.

**Comment by RigoFlores** [comment]
![cliente sin correo](https://cloud.githubusercontent.com/assets/2912775/12396339/81d7d082-bdcc-11e5-9584-07497308aebe.png)

**Comment by RigoFlores** [comment]
Esta es la factura 4, que para el mismo receptor de la factura 1, si aparecía en el portal, pero la factura 1 no apareció. La envié manualmente.
