### ISSUE TITLE
Para esta cuenta en web SIS130211C95 no siempre envía los correos de las facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#532]
Este cliente ocupa la factura periódica, pero no siempre le llegan el correo al destinatario.
Yo hice pruebas desde consultas, probando con varios correos de gmail o hotmail, y como que si se comporta raro. Mañana va ir el cliente a la oficina, si que está molesto.
Echale un vistazo pls, a ver si le hallas algo extraño.

**Comment by RigoFlores** [comment]
Al parecer, he notado que si agregas el correo en un renglón donde ya te sugiere dicho correo, entonces no lo envía. Si lo agregas en un renglón donde nunca antes lo habías tecleado y por lo tanto no te sugiere, ahí creo que si lo envía. Renglones me refiero a los n correos que puedes agregar cuando le das reenviar una factura. 
Ahora el problema principal es que al momento de generar la factura en automático (periódica), no llega a los destinatarios...

**Comment by jccastillo0007** [comment]
Al intentar reproducirlo desde la pantalla de consultas, lo intente 5 veces y si lo mando

Busque en el log, una factura del 24 de diciembre y fue enviada a :   

From: noreply@factura-t.com.mx^M
To: antonio.arreguin@municipiodequeretaro.gob.mx^M
To: moisessg@gmail.com^M
Cc: moises.sanchez@siscomqro.com^M
Cc: luis.perez@siscomqro.com^M
Cc: soporte@factura-t.com.mx^M

No vi, ningún error en el envío, entiendo que si debió llegar.

Preguntales si ubican una ocasión específica en donde no llegó el correo.

**Comment by RigoFlores** [comment]
En teoría no llegó ningún correo... solo el de soporte.
Te digo que yo estuve reenviando facturas y en muchos casos no llegó a un correo de gmail.
Si existe un problema, pero no está como que muy claro el escenario.

**Comment by RigoFlores** [comment]
Ya configuré en la cuenta de la TIA, en pro, unas facturas periódicas, pero tenía definido que no enviara el correo al emisor y receptor, y ahora pide configuración a huevo, de los parámetros del correo
Esa configuración debe ser totalmente opcional... siempre y cuando capturen un campo, deben capturar todo, sino capturan ningún dato, entonces no debe pedirlo como obligatorio.

**Comment by RigoFlores** [comment]
Necesito que a la cuenta en producción de la TIA, le indiques que siempre envíe por correo al emisor y receptor. Este cliente tiene envíos programados el día 5, y el lunes seguir va a estar llamando.
No se porque razón, pero no están llegando los correos enviados.
La alternativa para ellos, es tomar su cuenta de correo y definirla en la pantalla de configuración, pero aún no me dices si ya quedó eso o nó.

**Comment by jccastillo0007** [comment]
ya quedó lista esta funcionalidad, faltaba configurar el valor de TLS que ocupan los servidores SMTP de correo, yo siempre enviaba true, pero para esta cuenta se requiere false, tons, ya lo agregué a los datos que se deben configurar.

**Comment by RigoFlores** [comment]
Ahora no se puede acceder a la pantalla de configuración para validar la corrección

**Comment by RigoFlores** [comment]
Si está enviando el correo con la nueva cuenta... el problema de que no siempre enviaba al gmail, hotmail, yahoo..etc, sigue pendiente... por lo pronto lo cerraremos
