### ISSUE TITLE
Cuando se genera una cotización, pedido o remisión, se sugiere la serie pero se puede modificar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#537]
Lo cuál podría causar inconsistencia.
Aparece la serie como sugerida, y NO DEBERÍA PERMITIR EDITARLA

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Para evitar inconsistencias, en la pantalla de facturas no debe permitir elegir alguna serie predefinida.
Así como lo hace para la serie NOM, que no la presenta en la pantalla de facturación, asimismo no debe presentar las series de cotización, pedido ni remisión.

**Comment by jccastillo0007** [comment]
ok, ya esta listo.

Te recomiendo hacer mas y mas pruebas de este tema, porque es probable que sigan saliendo detalles ocultas como penalización de tener las series hardcoded

**Comment by RigoFlores** [comment]
OK, seguiré muy pendiente de estos puntos... y sí, esos son ajustes a la medida... aunque deben ser alambres bien hechos, como cola de rata al menos... (si llevaste electricidad, entenderás, sino, pos ya te chin....)

**Comment by jccastillo0007** [comment]
ya me chingue....

**Comment by RigoFlores** [comment]
ok, es el amarre mínimo indispensable en electricidad, existe otros mas seguros...
![cola de rata](https://cloud.githubusercontent.com/assets/2912775/12373447/19f67920-bc3f-11e5-94d5-ce468f88575e.jpg)

**Comment by RigoFlores** [comment]
Bueno, por cierto ya ví que también presenta en la pantalla de facturas la serie reservada RET,,,
(chiaaaaaaa.....)

**Comment by RigoFlores** [comment]
para cerrar este issue, solo se ocupa que en la pantalla de facturas... no ponga a disposición la serie RET, que es la de retenciones...

**Comment by jccastillo0007** [comment]
fixed.
