### ISSUE TITLE
Cuando editas una cotización para pasarla a pedido o remisión, no cambia la serie

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#538]
si yo tengo un documento y lo convertiré a remisión (editando el documento desde la consulta), debe colocar la serie correspondiente al documento REM, PED, o alguna de factura, según sea el caso.
Este manejo, como está ahora va a generar inconsistencias

**Comment by jccastillo0007** [comment]
uuuuuy, osea quieres que le cambie la serie que originalmente se le asignó?, eso si que va hacer delicado, puede pegar en muchos lados, ya que casi siempre para validar la consistencia en consultas y rastreo de CFDis, siempre reviso que hablemos de la misma serie + folio y si ya se tiene folio del sat también, esto no lo puedo resolver.

Ademas al cambiar la serie, seguramente cambiaria el folio, y eso haria que ya no exista ningun mapping entre ellos... es un desastre.

Será la consecuencia de forzar series por tipo de documento.

**Comment by RigoFlores** [comment]
creo que no nos entendemos.
Yo puedo generar una cotización y pasar directo a factura (pensemos que el folio es el mismo, lo cual es una chaqueta mental)
A la siguiente cotización, ahora si se hace una remisión... (ahí ya no empatan los folios, que además NO TIENEN POR QUE EMPATAR, y se alinean o cuadran por el id, para eso y solo para eso existe el ID).
Entonces, en que momento se supone que debemos pensar o considerar que el folio será consistente entre todos los documentos????
Una factura la pueden hacer sin generar ningún documento previo, eso es algo común.

Conclusión, esto no es consecuencia de llevar series preasignadas, sino de asumir que la serie y folio serán lo mismo en toda la traza... eso lo platicamos hace muuuuuucho tiempo, y nuevamente el mismo tiempo vuelve a darme la razón...

**Comment by RigoFlores** [comment]
Aquí el tema, es que si una cotización se cambia a remisión, entonces se toma la serie REM y se asigna el folio siguiente dentro de dicha serie... igual para cualquier caso... excepto para factura, donde si existen varias series, el usuario eligirá la serie adecuada...

**Comment by jccastillo0007** [comment]
Tienes razon, con respecto al folio, fue una chaqueta mental pensar que debería ser el mismo, para el identificar el documento se usa el tracking Id.

Necesito revisar si no pega cambiar la serie, ya que eso nunca antes lo habiamos hecho intencionalmente.

**Comment by RigoFlores** [comment]
Cuando generas una remisión o pedido, etc, desde la pantalla correspondiente... ahora mismo la aplicación si coloca la serie que le toca.
Eso mismo debe suceder cuando EDITAS una cotización (por dar un ejemplo), y la pasas a remisión (en el momento que eliges el documento), en ese momento la aplicación, debe colocar la serie correspondiente, con el folio que le toque:
Cotización: COT
Pedido: PED
Remisión: REM
Factura: la primera diferente a las anteriores, y también diferente a NOM

**Comment by jccastillo0007** [comment]
mmmmm por el momento va a estar cabron arreglar esto porque :  
1. Al editar documnetos se usa la misma pantalla de facturación, y solo se protegen algunos datos de que no se puedan editar.
2. Dado el punto 1, en el combo de series no se cargan las series de NOM, COT, PED, REM <por solicitud tuya de ti>
3. Dado el punto 2, en una cotización si elijo pedido o remisión, no puedo asignarle la serie correspondiente, ya que no se encuentra disponible en el combo
   
   Workaround chacarron para el uso de series chacarronas, sin importar que tenga el combo de serie, al momento de salvar la cotización, pedido o remisión, puedo asignarle la serie adecuada, la cual podr[an ver en la pantalla de consultas.

De hecho, debido al punto 2, si tu editas una cotización, no verás la serie COT.

**Comment by RigoFlores** [comment]
OK, creo que medio entendí porqué no puedes presentar las series.
Pero lo del uorcarraun  ¿¿¿si quedó implementado???
Es decir, SI ES ACEPTABLE COMO SOLUCIÓN ALTERNA QUE de manera interna tome la serie-folio que le toca y que se la asigne, de acuerdo al documento en cuestión...

**Comment by jccastillo0007** [comment]
pues para mi no es aceptable hacer eso, pero ya haz pedido muchas cosas no aceptables desde el punto de vista de software, pero en fin... hoy subo esto a PRU.

**Comment by RigoFlores** [comment]
Si, el tema se deriva en todo caso de las series preasignadas.
Esta fue una propuesta, el de asignarlas previamente según el tipo de documento, tal cual se hace en nómina o retenciones.
Alguna otra alternativa era bienvenida, pero ahora como bien comentaste, al avanzar mas, esto se va complicando.
A mi tampoco me convence mucho la idea de asignar serie y folio en el background, pero el asunto siempre ha sido desde el principio... llevar un control consecutivo, independiente para cada documento. Lo pudimos dejar como responsabilidad al usuario, pero sabemos de antemano que se generarían escenarios de inconsistencia. Por ello optamos por preasignar series, para poder controlar su propio consecutivo. Esperemos que no sigan surgiendo alambritos... 
Por cierto, cuando lo subiremos a PRO, tenemos cliente esperando ya esta solución.

**Comment by jccastillo0007** [comment]
entiendo que ya lo probaste cierto.... tons lo subo hoy...

**Comment by RigoFlores** [comment]
Listo...
