### ISSUE TITLE
Pantalla de Edición de CFDI ya timbrado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#539]
Lo único que se puede editar son los pagos, entonces:
a) No debe presentar el primer pago por omisión, ya que en ese caso no permite elegirlo.
b) El combo debería desplegar la descripción del pago, o quizás la fecha, pero no la cantidad, ya que en tu ejemplo, son 3 pagos de 1,000 y pues realmente ahí no te sugiere nada.
c) en el ejemplo que tu capturaste en pruebas (FE1434), fueron 3 pagos de 1,000. Al elegir cualquiera de ellos, siempre me muestra una descripción que dice pago 1. Entiendo que me está mostrando el mismo registro.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Pues lo ví exactamente igual...
o cual fue el cambio?

**Comment by jccastillo0007** [comment]
Ups... no lo habia subido a PRU, pero ya esta... se arreglaron los puntos a, b y c de este ticket.
