### ISSUE TITLE
Notificar al usuario, 3 condiciones de vencimiento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#54]
a) Vencimiento del rango de folios (cuando los folios adquiridos se van a terminar, antes del año de vigencia)
b) Cuando el rango de folios vencerá su vigencia (cuando se terminarán los 12 meses de vigencia, antes que se termine el rango de folios)
c) Cuando se vencerá la vigencia del Certificado de Sello Digital

Hoy en día contamos con el punto a y c, pero el b no lo tenemos implementado

**Comment by jccastillo0007** [comment]
Estuve trabajando en este req.. ya tengo el primer aviso... para ma;ana ya estarian los tres avisos.

**Comment by jccastillo0007** [comment]
Una vez que el usuario entra a la aplicacion, se mostraran las notificacione

**Comment by RigoFlores** [comment]
Favor de cambiar las etiquetas:
a) Folios disponibles: 36 de 50
b) Vencimiento de Folios: 30/04/2013
c) Vencimiento de Sello Digital: 25/12/2015

Favor de poner el mensaje en un lugar visible, y con un font poco mas grande.

**Comment by jccastillo0007** [comment]
Done...

**Comment by RigoFlores** [comment]
parece que el mensaje está fijo, ya que he generado facturas y me envía el mismo mensaje, en cuanto a folios disponibles

**Comment by jccastillo0007** [comment]
Si, los mensajes de folios disponibles, son los de mi RFC en produccion, hasta que liberemos a produccion se podran ver mensajes de cada usuario, en esta semana voy a generar la instancia de preproduccion.

**Comment by RigoFlores** [comment]
pero para pruebas, debería jalar igual que en pro.... precisamente para ello es ambiente de pruebas

**Comment by jccastillo0007** [comment]
si, pero ahi tengo un constraint de acceso a base de  datos.... las entidades de control de folios esatn pro no en pruebas, eso lo tengo asi para poder mostrar los reportes de consumo de folios...

**Comment by RigoFlores** [comment]
es decir no se podrá cerrar hasta probar en pro?.
Debería poder recrearse el ambiente, que no?

**Comment by jccastillo0007** [comment]
Si quieres recrearlo en pruebas, tendria que deshabilitar los reportes de consumo de folios que se extraen de produccion

**Comment by jccastillo0007** [comment]
Ya puedes cerrar este defecto !!!!!! ya vimos como funciona en pro.

**Comment by RigoFlores** [comment]
Solo falta mostrar el número de folios disponibles correctamente.
Hoy dice Folios Disponibles: 0 de 300,
Debería decir:
Folios Disponibles: 300 de 300,,,,

O la otra es indicar Folios Utilizados: 0 de 300
