### ISSUE TITLE
Incluir en el excel, la columna de pagado y fecha de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#540]
En consultas, la pantalla te muestra la columna de fecha de pago y el monto pagado, pero en el excel no se incluye esta información

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
En la columna pagado, lo está dividiendo entre 1000, es decir si el pago fue de 3000, le coloca 3.... yo capturé un pago de 30,000 y en el reporte muestra 30 únicamente
Si le doy editar... si 'muestra' las cantidades correctas (en otro issue, levanté que no se puede elegir el primer pago de la lista, falta en famoso 'elija una opción').

**Comment by jccastillo0007** [comment]
no lo estaba dividiendo, mas bien era que la cifra tenía comas y lo dividía en varias columnas, ahora ya pone la cifra tal cual.
