### ISSUE TITLE
PRU-DescargaT - Al generar la factura desde descargat, no la muestra en consultas facturat

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#541]
1) Generé una remisión con mi RFC en Factura-T
2) Accedí a descargat con mi RFC y generé la factura (por cierto le puso los datos del registro en descartat, y no los que existen en el catálogo de clientes de facturat; creo que lo platicamos en su momento y así quedó, pero ahora no estoy tan seguro. Como quiera, así está bien por lo pronto)
3) Desde descargat, si aparece la factura en las consultas. 

El issue es que en facturat, no aparece la factura generada en descargat. Si intento editar la remisión que dió origen a dicha factura desde facturat me manda al internal error.
La factura en cuestión tiene folio FE1442, y la remisión es REM17.

Estoy seguro que esto ya jalaba antes, de lo contrario no se hubiera liberado.
Seguiré haciendo otras pruebas, ya que presentaré el demo la siguiente semana.

**Comment by jccastillo0007** [comment]
Si, esto ya funcionaba, y dejo de funcionar por los campos que agregué para la factura frequente, el DescargaT no lo he actualizado desde hace mucho, y estaba ingresando datos nulos...

Ya lo arreglé en PRU y ya muestra la factura que hab[ias generado....

Ahora que validez que todo esta OK, subo el eFacturaT y el DescargaT a PRO.

JC.

**Comment by RigoFlores** [comment]
Ahora NO GENERA la factura desde descargaT.
Marca este error...Error en generador PDF - Jasper (101)
Entiendo que es de la plantilla, aunque desde facturaT con la misma plantilla (que es la plantilla base) si la está generando.

**Comment by RigoFlores** [comment]
no se pueden seguir pruebas, ya que se brinca los folios, en descargat solo se guarda una factura, ya que el folio se repite... en fin, se hace un gran desmadre... mejor me espero... solo era preparar un demo, ya llevamos casi la semanita...

**Comment by jccastillo0007** [comment]
Fixed.

Pedos con el jasper... pero ya quedó arreglado.

Escenario probado.

En eFacturaT cree una remision con la cuenta de la TIA REM 25 Tracking id 000819, por 580.00 pesos, del  día 27 de Enero 2016
En DescargaT entre con mi cuenta y busque esa remision
Se logró facturar sin pedos, y con xml y pdf.
