### ISSUE TITLE
Migración de econta de producción a pruebas para ELE961009FI3

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#542]
Nos reportó un problema de pólizas, y tenemos que revisarlo en pruebas, con lo que se requiere que toooooda la información de pro, pase a pru idéntica.
También ocupo el query para ajustar los saldos iniciales de las cuentas.
Lo mandé por correo, pero no hubo respuesta

**Comment by jccastillo0007** [comment]
pssss no ma, no es tan sencillo... esto de la C.E. se refiere a catalogo de cuentas, balanza, polizas.

Haber checale si esta completa...

**Comment by RigoFlores** [comment]
pues no pasaron las pólizas, no las puedo ver para revisarlas.
Lo que es un hecho, es que la pantalla de captura de pólizas ES DISTINTA PARA PRUEBAS QUE PARA PRODUCCIÓN... está k.....

**Comment by jccastillo0007** [comment]
Es correcto, el refactor al desmadre de  polizas he empezado desde el
domingo... ya nada será igual...

Saludos.
JC.

2016-02-11 9:07 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Y ora como verificamos lo de las pólizas en pruebas?
La otra es que repliques toda su info (de econta) al rfc XAXX010101000 en producción... nop?

**Comment by jccastillo0007** [comment]
Ya se ven las polizas... checale...

Lo de replicar la info esta cabron, ya que intervienen ids de base de datos...

Puedo replicar toda la base de datos y ponerla en PRU en una base alternativa... pero para checar tendrias que usar queries y no la app

**Comment by RigoFlores** [comment]
AYER VINO EL CLIENTE DE ESTE RFC, Y AL CHECAR LA INFORMACIÓN 'MIGRADA', ESTABA INCOMPLETA... FINALMENTE YA NO LA OCUPARÉ, YA LO ATENDIMOS EN PRODUCCIÓN...
SE ACEPTA EL CIERRE DEL ISSUE, CON STATUS 'NO SE MIGRÓ CORRECTAMENTE'
