### ISSUE TITLE
Implementar Addenda Factura-T

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#544]
Debe contener a nivel general:

número de dato extra 
label
contenido

A nivel detalle
información complementaria
número de dato extra
label
contenido

el número de dato extra se ocupa para poder generar el PDF original, a partir del XML con addenda facturat.
Es muy probable que se ocupe para el carta porte

**Comment by jccastillo0007** [comment]
Duplicado con el ticket 551, chiaaaaaa nada mas me quieres asignar mas tickets... me quedo con el ticket 551 porque viene mas detallado.
