### ISSUE TITLE
Implementar cambios para Carta Porte SCT compliance (ESCRITORIO)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#545]
1.  Los datos extra 1, 2 y 6 tu los manejarás internamente:
   Datos extra 1 y 2, tomado del catálogo de clientes, tal cual lo hace ahora, pero eliminando el rfc de ese ‘metadata’
   datoExtra 6 se genera cuando el producto sea ‘DESCRIPCIÓN DE LA CARGA’,  y corresponderá a la información complementaria de dicho producto. Pregunta, si tu manejarás ese dato extra 6, entonces no le pega que lo llegaran a capturar en el extrafields o como podemos manejar esa situación?
2.  Cuando el producto sea ‘DESCRIPCION DE LA CARGA’, para propósitos del XML, se enviará como descripción lo que se haya capturado como información complementaria. 
3.  Eliminaremos totalmente el tema de “[PESO/VOLUMEN]=ALGO”, ya que eso se capturará como datoextra7. Así lo dejamos mucho mas simple.
4.  Carta porte se deberá desplegar ahora como 2 opciones en la pantalla de facturación: CARTA DE PORTE-TRASLADO y CARTA DE PORTE-INGRESO, con tipo (XML) traslado e ingreso respectivamente.

Creo que son todos los cambios mas urgentes, quedando pendiente la addenda.

**Comment by jccastillo0007** [comment]
Chiaaaa nunca debes mezclar mas de un requerimiento por item..
1. Dato extra 1 sin RFC = done
2. Dato extra 2 sin RFC = done
3. Olvidarse del tema de [PESO/VOLUMEN]=ALGO" = done
4. Validar que el producto sea = Descripción de la carga = done
5.  Pregunta, si tu manejarás ese dato extra 6, entonces no le pega que lo llegaran a capturar en el extrafields o como podemos manejar esa situación? JC. No le pega, lo va a sobreescribir
6. Enviar la descripción complementaria, como datoextra 6 cuando el producto sea "Descripción de la carga" = done
7. Enviar la descripcion complementaria como nombre de producto al XML = done
8. Las opciones de carta porte ahora son :  CARTA PORTE (TRASLADO) = done
9. Las opciones de carta porte ahora son :  CARTA PORTE(INGRESO) = pendiente

Pregunta. Ya no se manda nada como datos extras a nivel producto ?

**Comment by RigoFlores** [comment]
Si, lo junté todo aquí, porque es atómico el requerimiento jala o no jala... 
A nivel producto NO se manejarán datos extra.
Vamos a validarlo, y dar comentarios.

**Comment by jccastillo0007** [comment]
1. Las opciones de carta porte ahora son : CARTA PORTE(INGRESO) = done

Done.... I guess.
