### ISSUE TITLE
Descripción de la carga en Carta de Porte debe soportar los enters

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#548]
Cuando la información complementaria para el producto DESCRIPCION DE LA CARGA, incluya enters (que es lo mas normal)... mantenerlo así para propósitos del datoExtra6 (eso ya lo hace correctamente ahora mismo)

Peeeero para propósitos del concepto que se envía al XML, se deben eliminar los enters por espacios en blanco.
OJO, ese producto que se agregará al XML tomará todos los datos que se capturaron en la pantalla de producto, excepto la descripcion, ya que esa la va a sustituir por la información complementaria

**Comment by jccastillo0007** [comment]
Esto ya esta funcionando.... chiaaaa  hice la prueba varias veces y si lo manda bien al PDF y al XML sin enters

**Comment by RigoFlores** [comment]
Si ya validé que funciona:
a) AL PDF no se va la descripcion
b) Al XML se va la información complementaria como descripcion

Dado que no se podía timbrar, abrí este issue para que no se te fuera a pasar.
