### ISSUE TITLE
Permite eliminar rango de folios que ya fueron utilizados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#55]
Al borrar rango de folios que han sido utilizados, se pierde el consecutivo de dicho rango

**Comment by jccastillo0007** [comment]
Debemos controlar esto ?

Estos folios son para uso interno, no se si debemos seguir teniendo ese constraint????

**Comment by RigoFlores** [comment]
Claro que debemos controlarlo por lo siguiente:
a) Para emisor y receptor, este es el folio oficial, aunque para el SAT sea el UUID. Eso es por uso y costumbre
b) Imagina que el usuario emita cuantas veces quiera el folio 1, debido a que elimina y vuelve a dar de alta un rango. Independientemente que sea de uso interno, no puedes repetir folios de uso interno.

Conclusión, si aplica, y antes de descartar alguna funcionalidad sería bueno platicarlo.
Lo mas que se podría hacer con un rango de folios en uso, es permitir la modificación del límite superior, siempre que sea mayor al folio actual.
Ahora, si ya implementamos los avisos de que se terminarán y/o vencerán sus folios contratados, posiblemente el rango superior ya no se necesite en la BD.

**Comment by jccastillo0007** [comment]
Done
