### ISSUE TITLE
CARTA DE PORTE - NO MANDA LLAMAR LA PLANTILLA ESTÁNDAR

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#550]
Anteriormente cuando en escritorio tenías plugin de carta porte, buscaba la plantilla cartaporte.jrxml, independientemente de la plantilla configurada en el properties (que se ocupa para facturas).

Ahora ya no busca por esa plantilla estándar del cartaporte.

**Comment by jccastillo0007** [comment]
Fixed.
