### ISSUE TITLE
Implementar addenda Factura-T

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#551]
Básicamente con 2 secciones:
General:
Número de dato extra
Label
Contenido

Detalle:  (1 a n)
información complementaria
Datos extra (1 a n). Un producto puede tener 1 o mas datos extra.
Número de dato extra
Label
Contenido

Esto es para incluir tooooooda la información de la factura, carta porte, o lo que sea, en esa addenda.

**Comment by jccastillo0007** [comment]
Tiene años que no hacía un schema por mi mismo... jajajaja, esta chido recordar detalles como este.

La información complementaria en los detalles 1 a n, no es necesaria, ya que se estan mandando n datos extras.... uno de ellos puede ser la información complementaria, si es que se ocupa

En verdad necesitamos enviar el número de dato ?

En esto de los schemas, debes definir lo mínimo necesario y no dejar campos que no necesariamente se ocupan.

Tenemos algún cliente confirmado para usar esta addenda?

**Comment by RigoFlores** [comment]
El número de dato, lo ocuparemos para que cuando tengamos que reconstruir un PDF, tengamos todos los elementos para hacerlo.
La información complementaria, si se podría manejar como dato extra, pero recorrería la numeración de los otros datos extra, y al momento de empatarla con el PDF, entiendo que quedaría chueca. Tu me dices como queda finalmente. Finalmente al reconstruir un PDF, tu tendrás que interpretar esos datos extra.
Esta addenda es solicitada por la SCT como obligatoria para carta porte y únicamente se refiere al tema del contrato, pero no indica nada mas que:
Estas condiciones se incorporarán en la
"Addenda" electrónica del CFDI prevista en el
Anexo 20 de la RMF 2014, y se incluirán en el
reverso de su representación impresa

**Comment by jccastillo0007** [comment]
Ya esta lista la addenda, te mando el schema por correo.... ahora que ? en que casos la implementamos, cual es el caso de uso, ese no me queda claro, dices que para SCT, pero ellos ya manejan la carta porte cierto ?

**Comment by RigoFlores** [comment]
Podemos, inicialmente incluirla en carta porte de escritorio?

**Comment by jccastillo0007** [comment]
si, ya lo estoy habilitando, pero...

cual es el caso de uso de hacerlo en standalone, es decir, la addenda se va a agregar al xml guardado localmente en la maquina del cliente, pero no se enviar[a al servidor, ya que las addendas no son parte del xml cuando se manda timbrar, las addendas se agregan despues del timbre del PAC.

**Comment by jccastillo0007** [comment]
listo.

Checa el release chacarron 9.1.19

**Comment by RigoFlores** [comment]
Si, ya ví que la incluyó.
Efectivamente las addendas no llegan al SAT, por definición.
La SCT indicó que el contrato debe incluirse en la sección de addenda del XML... ese fue todo su caso de uso.
Ahora, lo que creo conveniente, es que la addenda se incluya en todo caso, donde se ocupen datos extra y/O INFORMACION COMPLEMENTARIA... esto es, aunque no se trate de carta porte, o aunque no se incluyan datos extra... pero que si se maneje la información complementaria en uno o varios productos, entonces se debe incluir la addenda...

cómo ves? es decir... la addenda ya debe ser nuestro distintivo... incluyan datos extras o nó, pero siempre que al menos se trabaje información complementaria.

**Comment by jccastillo0007** [comment]
Mas que agregarla a huevo, hay que ofrecerla, y agregarla a las facturas de los clientes que la soliciten y compren, no tiene caso estar haciendo un analisis de la información que se incluye en la factura o en los productos para agregar la factura, si al cliente no le interesa, o si le interesa bajo un escenario diferente, para no retrabajar, mejor ofrecela como te gusta ofrecerlas, y quien la necesite se la dejo ir... osea se la agrego... 

Falta implementar esta addenda en carta porte en web.

**Comment by RigoFlores** [comment]
Difícilmente a un cliente le interesará, pero si cuando tengamos necesidad de generar un formato PDF a partir de un XML, donde se incluyó la addenda... entonces se podrá reconstruir completamente cualquier formato PDF... ya sea con información complementaria y/o datos extra... ese es el caso de uso... mas que nada interno... creo que es levicom, el pac que siempre incluye su addenda precisamente con esa información adicional...

**Comment by RigoFlores** [comment]
ah, y si falta en web... desde siempre..

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
Closing....

**Comment by RigoFlores** [comment]
ok
