### ISSUE TITLE
Generación de póliza de cierre de ejercicio o póliza de ajuste, a petición del usuario.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#552]
La póliza de cierre, servirá para calcular la balanza de cierre de ejercicio que ES ADICIONAL A LA BALANZA DE DICIEMBRE.

Se puede generar, únicamente cuando se ha cerrado la BALANZA de DICIEMBRE DEL AÑO EN CUESTIÓN.
La forma de calcularla es tomando todas las cuentas del catálogo 'afectables' o con asiento=1, cuyo código agrupador se encuentra inicia entre 4 y 6. (indispensable)
Esto involucra a las cuentas de ingresos, costos y gastos.
Ejemplo:
Si el saldo final de la cuenta de "VENTAS DE SERVICIO"  con CÓDIGO AGRUPADOR 401.01, NÚMERO DE CUENTA 401.01.001 fue de 200, entonces le corresponderá un asiento en esa póliza de cierre, de tal manera que el saldo final sea 0. En este caso, por ser una cuenta acreedora, entonces le toca un cargo por 200, y así el saldo final será 0.

En este caso las condiciones para generar la póliza de cierre o ajuste son:
1) Se haya cerrado la balanza de diciembre
2) Las cuentas tengan asiento = 1, es decir son las que se despliegan en la pantalla de captura de pólizas
3) Los códigos agrupadores empiezan con 4, 5 o 6, es decir cuentas de ingreso, costos y gastos.

Para calcular los asientos automáticos de la póliza, se toma su saldo final de diciembre y con ello se realiza el cuadre, dependiendo de su naturaleza.
Deudor => saldo final= saldo inicial + deber (cargo) - haber (abono)
Acreedor=> saldo final = saldo inicial - deber (cargo) + haber (abono)

El concepto deberá ser "Ajuste Cierre Anual"

El resultado de generar esta póliza automática será presentar cada cuenta involucrada con cargos o abonos, dependiendo de su saldo inicial, de tal manera que el saldo final sea cero.
Al final, el usuario deberá agregar MANUALMENTE, una última cuenta que seguramente será 'hija' de resultados en los ejercicios anteriores, misma que será cuadrada automáticamente, tal cual lo hace ahora mismo.

**Comment by jccastillo0007** [comment]
me puedes pasar un ejemplo en excel con toda la información de las cuentas, donde se vea como estaban las cuentas antes de esta poliza, y como quedan después... 

Donde será el mejor lugar para poner esta opción ?

**Comment by jccastillo0007** [comment]
con que fecha debe ser generada esta poliza de cierre ?
esto quiere decir que todas las cuentas con código agrupador 4, 5 y 6, tendrán saldo inicial = 0 en Enero, y ya no hay que arrastrar los saldos iniciales de diciembre cierto ?
