### ISSUE TITLE
Generación de Balanza de Ejercicio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#553]
Deberá agregarse la opción, como si fuera el mes 13... de CIERRE DE EJERCICIO, o simplemente cierre.

Esta balanza se genera, una vez que se ha cerrado la balanza de diciembre, y también una vez que se ha generado la póliza de cierre.
La póliza de cierre, simplemente servirá para poner en 0's los saldos finales de las cuentas que empiezan con código agrupador 4, 5 o 6.
El resto de las cuentas, se manejan de manera regular... es decir dado que no estarán involucradas en la póliza de cierre, reflejarán el saldo inicial como saldo final.

**Comment by jccastillo0007** [comment]
esta balanza de cierre, tendrá fecha de diciembre o de enero?, es decir, habrá dos balanzas diferentes para uno de los dos meses, la normal de diciembre y/o enero y la de cierre?
una vez  generada, se debe cerrar automaticamente ?

**Comment by RigoFlores** [comment]
es fecha de diciembre, ya que enero debe iniciar con los saldos en cero... ayer precisamente hicimos una simulación, y definitivamente tiene que iniciar enero en ceros.
Debe tratarse como la balanza de mes 13... tal cual... es decir, se cerrará manualmente y se solicitará una vez que se haya generado la póliza de ajuste o cierre.. que también tendrá fecha de diciembre, pero que no será parte de las pólizas contables de diciembre... jeje

El anexo 24 dice:
Mes
Descripción
Atributo requerido para expresar el mes al que corresponde la balanza de comprobación
Uso
requerido
Tipo Base
xs:string
Valores Permitidos
01 02 03 04 05 06 07 08 09 10 11 12 13
