### ISSUE TITLE
URGE-NO TRANSFIERE LOS SALDOS DE DICIEMBRE 2015 A ENERO 2016

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#554]
No está transfiriendo los saldos finales de diciembre 2015, a saldos iniciales de enero 2016.

Está tomando los mismos del catálogo de cuentas al inicio, y eso precisamente solo es al inicio, después de ello, ya nada será igual otra vez.

Tenemos que transferir los saldos de un mes que se cierra al siguiente mes… aún en cambio de año…

**Comment by jccastillo0007** [comment]
necesito mas detalle de como reproducirlo, esto es tan viejo que no se exactamente como hacer que suceda, con que cliente puedo probar y en PRU o PRO ?

**Comment by RigoFlores** [comment]
Así que digas, que viejo, que viejo, está cayéndose de lo antiguo... no
Hoy apenas se reportó, porque precisamente estamos en ese cambio de año por primera vez desde que se liberó la econta.
En producción puedes ver ahora mismo para ELE961009FI3, tiene una sola póliza en enero del 2016, y en esa los saldos iniciales no son los de diciembre, sino los que se capturaron en su momento y únicamente como punto de partida, en el catálogo de cuentas.

**Comment by jccastillo0007** [comment]
Fixed

**Comment by RigoFlores** [comment]
Ya entré a producción (donde nos está esperando el cliente), y sigue igual...

**Comment by jccastillo0007** [comment]
hoy lo subo a producción.

**Comment by RigoFlores** [comment]
ok, me confirmas pls... para chequear

**Comment by jccastillo0007** [comment]
Done.
