### ISSUE TITLE
Implementar Carta de Porte - Web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#555]
Los datos extra 1, 2 y 6 tu los manejarás internamente: 

Datos extra 1 y 2, tomado del catálogo de clientes, tal cual lo hace ahora, pero eliminando el rfc de ese ‘metadata’ .

Dato extra 6 se genera cuando el producto sea ‘DESCRIPCIÓN DE LA CARGA’, y corresponderá a la información complementaria de dicho producto. 

Cuando el producto sea ‘DESCRIPCION DE LA CARGA’, para propósitos del XML, se enviará como descripción lo que se haya capturado como información complementaria.  

Eliminaremos totalmente el tema de “[PESO/VOLUMEN]=ALGO”, ya que eso se capturará como datoextra7. Así lo dejamos mucho mas simple.

Carta porte se deberá desplegar ahora como 2 opciones en la pantalla de facturación: CARTA DE PORTE-TRASLADO y CARTA DE PORTE-INGRESO, con tipo para propósitos del XML, traslado e ingreso respectivamente.

**Comment by jccastillo0007** [comment]
pssss en web, no se tiene eso de que un tipo de dato extra son los clientes... va a llevar un poco mas de tiempo

**Comment by jccastillo0007** [comment]
Upss, ya vi que si se soporta el tema del remitente y destinatario en los datos extras, el truco esta en que yo tengo que configurarlo para que lo interprete como tal... entonces ya casi esta todo lo de carta porte...

**Comment by jccastillo0007** [comment]
Hoy subi un release a PRU que ya resuelve los puntos:

**Los datos extra 1, 2 y 6 tu los manejarás internamente:

Datos extra 1 y 2, tomado del catálogo de clientes, tal cual lo hace ahora, pero eliminando el rfc de ese ‘metadata’ .

Dato extra 6 se genera cuando el producto sea ‘DESCRIPCIÓN DE LA CARGA’, y corresponderá a la información complementaria de dicho producto.**

**Comment by RigoFlores** [comment]
Con cual RFC probaste? No encontré algunos con los datos extra configurados para carta porte...

**Comment by RigoFlores** [comment]
mañana enviaré el correo a los clientes, que ya contamos con la solución en escritorio y web...

**Comment by RigoFlores** [comment]
sigo detenido con esto, no tengo rfc para probar ya que no puedo dar de alta los datos extra, debido a que no puedo entrar al server de testing

**Comment by jccastillo0007** [comment]
chiaaaaa , asi como vamos a terminar si no se avanza con la pruebas.... debes pedirme todo lo que necesitas y no una cosa cada dia.... 

puedes probar en pru con el usuario de la TIA o en producción con mi usuario jccastillo / beagile007   y todos estos clientes tienen configurados los datos extras con remitente y destinatario

mysql> select id, owner from ClientConfiguration where extradata like '%remitente%';
+-----+---------------+
| id  | owner         |
+-----+---------------+
|   1 | CAAJ7506072P2 |
|  90 | CACM670112RH5 |
|  63 | AEAJ620303K95 |
|  66 | HEML720803E1A |
| 100 | SORM841103GU8 |
| 225 | SORS921122AVA |
| 293 | EIMD8611259I5 |
| 315 | DEI121115N91  |
| 614 | AASP620603CG8 |
| 667 | AIJR741229EU1 |
| 741 | CODJ800114EY1 |
| 756 | TDM130302QJ4  |
| 760 | GAGA5801112W3 |
| 810 | HEJL811015L23 |
| 877 | RUMJ6407114M3 |
| 888 | OARJ930328AZ0 |
| 938 | ATA150216362  |
| 963 | HEJF690612NY5 |
| 980 | MOAA950219DA5 |
+-----+---------------+
19 rows in set (0.00 sec)

**Comment by RigoFlores** [comment]
Me indicaste que en pru validara... ahí intenté con la cuenta de la tia y la tuya, que son las que me parecieron que debían tener la configuración de datos extra para carta porte, y no lo tenían.
Yo se como agregar los datos extra anteriores al cambio, pero es igual, ya que no puedo entrar a pru a darlos de alta por queries.
Si entendí bien, ya está en produccción???? Ese cambio tenemos que subirlo de manera controlada, ya que estaremos cobrando la actualización....

**Comment by RigoFlores** [comment]
Amén que lo que reportaste no era el 100% de los cambios solicitados... así con mayor razón NO HAY QUE LLEVARLO A PRO AÚN...

**Comment by jccastillo0007** [comment]
ups... ya etsa en pro, hoy voy a limitar para que no tengan uso de esa funcionalidad, 
Como quieres que lo restrinja para vender la actualizaci[on, por medio de un plugin ?

**Comment by RigoFlores** [comment]
Yo creo que podemos controlarlo cuando nosotros configuremos sus datos extra, pero hay un problema...
lo anterior no es compatible con lo nuevo, eso quiere decir que ahora mismo, ya no jala lo de carta porte en pro, y los clientes quizás ni se han dado cuenta.
Es posible a partir de la configuracion de los datos extra, saber cuándo comportarse 'como antes' y cuándo con lo nuevo?

Eso es independiente, a que está incompleto aún el desarrollo, correcto?

**Comment by jccastillo0007** [comment]
Es posible a partir de la configuracion de los datos extra, saber cuándo comportarse 'como antes' y cuándo con lo nuevo?

JC. No, no es posible, ya que los datos extras no determinan nada en la funcionalidad, lo único que se hace con ellos es sobreescribir el dato extra 6, todo lo demás es igual.

Eso es independiente, a que está incompleto aún el desarrollo, correcto?
JC. Si, falta verificar que el XML se cree con la descripción adecuada de los productos, de acuerdo a las pruebas, has hecho algo mas ?

Lo único que falta para que el approach anterior sea compatible con el actual, hay que cambiarle el nombre de  a los productos para que se dispare el nuevo approach, de hecho ese podr[ia ser el indicador si se han o no actualizado

**Comment by RigoFlores** [comment]
No me quedó claro... pero se ocupa que lo anterior jale y de lo contrario, mientras no definamos el proceso de migración de cada cliente en lo individual y que puedan convivir ambos esquemas, tendríamos que dar regresión.
Yo estoy viendo de cobrar este cambio, y hasta el momento no ha habido respuesta de los clientes. Tendré que marcarles a uno por uno...

**Comment by jccastillo0007** [comment]
Me refiero a que el trigger para procesar correctamente los datos extras, en el proceso anterior era que la descripción del producto tuviera algo de [PESO/VOLUMEN]=ALGO y ahora es que el nombre del producto sea DESCRIPCION DE CARGA, de otra forma una carta porte si se puede generar, pero no se le dar[ia ningun procedimiento adecuado a los productos.

Entonces, voy a dejar en PRO el proceso anterior de carta porte, y dame el resultado de tus pruebas en PRU para ver que es lo que falta.

**Comment by jccastillo0007** [comment]
Listo, ya esta en PRU con estos datos de prueba... checale y me dices si me falta algo

Ambiente = PRU
Usuario = La Tia, TIA101020BP4 / test  //Le faltaba el plugin de Carta 
Porte chiaaaa
Datos extras ya están configurados, no se si sean todos o si el nombre 
del campo extra este bien, eso lo puedes tu cambiar a como te convenga, 
en realidad lo delicado son solo los dos primeros datos extras que son 
el remitente y el destinatario
Producto = 04

**Comment by RigoFlores** [comment]
Ya validé. Sigue faltando lo de:
a) Nombre del Carta de Porte
b) Tipo de Carta de Porte - Traslado, - Ingreso
c) Incluir la addenda Factura-T

**Comment by jccastillo0007** [comment]
Ya esta listo el a y b, solo falta el c.

**Comment by RigoFlores** [comment]
No hallé el CARTA DE PORTE - INGRESO, dices que ya está listo en pru?

**Comment by jccastillo0007** [comment]
Ahora si ya esta en PRU...

**Comment by RigoFlores** [comment]
Chiaaaa... pareces vieja que dices que ya estaba y no estaba... ahora si ya está.... falta solo lo de la addenda..

**Comment by jccastillo0007** [comment]
la addenda es otro ticket.

**Comment by RigoFlores** [comment]
PARA NO DETENER ESTO EN PRODUCCIÓN... EL ÚNICO CAMBIO LO HAREMOS NOSOTROS EN EL FORMATO... NOS BRINCAREMOS EL DATO EXTRA 6, PARA QUE NO SE IMPRIMA...
LO DEL    "[PESO/VOLUMEN]="  ES LO QUE ESTARÁ DESAPARECIENDO....

AL XML, SE INCLUIRÁ LA DESCRIPCIÓN DE LA CARGA, COMO UN PRODUCTO CON PRECIO UNITARIO 0.

**Comment by RigoFlores** [comment]
ESTAMOS HACIENDO PRUEBAS DE COMPATIBILIDAD DE LO ANTERIOR CON LO ACTUAL... LO RESOLVEREMOS POR PLANTILLA.

DETECTAMOS UN PROBLEMA ADICIONAL... A NIVEL PRODUCTO... ENVÍA COMO DATOPROEXTRA 1, LO QUE CAPTURAS COMO INFORMACIÓN COMPLEMENTARIA, IGNORANDO LO QUE CAPTURASTE EN DATOEXTRAPRO1  (DENTRO DE LA PANTALLA DE AGREGAR PRODUCTO)
.
NO OLVIDAR QUE ESTO ES EL PLUGIN DE CARTA PORTE, CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,  CARTA PORTE,

**Comment by jccastillo0007** [comment]
fixed.
