### ISSUE TITLE
favor de eliminar todo lo referente a econta EN PRUEBAS para la TIA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#556]
TOOOOODO LO DE ECONTA, PARA RETOMAR PRUEBAS CONTROLADAS EN AMBIENTE DE PRU... CREO QUE YO YA SÉ COMO ELIMINAR TOOODO, PERO NO TENGO ACCESO AL SERVER...

ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS, ES EN PRUEBAS

**Comment by jccastillo0007** [comment]
chiaaaa

Done.
