### ISSUE TITLE
REDONDEA EL PRECIO UNITARIO EN CATALOGO DE PRODUCTOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#557]
ALGUNAS OCASIONES PARA LLEGAR AL TOTAL EXACTO Y PRECISO, ES NECESARIO OCUPAR VARIOS DECIMALES EN EL PRECIO UNITARIO.
CUANDO ALMACENAS EN EL CATÁLOGO DE PRODUCTOS, EL PRECIO UNITARIO LO REDONDEA A 3 DECIMALES.
EJEMPLO EN CONCRETO CON UN CLIENTE....
SU PRECIO UNITARIO ES 0.5671, Y DESPUÉS DE DARLE SALVAR EN LA PANTALLA DEL CATÁLOGO, Y AL VOLVERLO A CONSULTAR TE MUESTRA 0.567.
ESTE PRODUCTO LO FACTURAS POR VARIOS MILES (CANTIDAD), Y AHÍ ES DONDE YA NO SE ALCANCE EL TOTAL EXACTO Y PRECISO.
YO RECUERDO QUE A NIVEL CATÁLOGO DE PRODUCTO, SE MANEJABAN HASTA 6 DECIMALES, QUE NO?

**Comment by jccastillo0007** [comment]
Ya revise, el tema no es que redondea el valor unitario, de hecho no lo hace, pero, en pantalla no muestra todos los dígitos, de hecho los calculos si los hace bien, y reporta bien el total, pero ciertamente el precio unitario del producto lo reporta truncado, aunque para los calculos no se trunca... en fin... tengo que arreglar lo que se muestra en pantalla para que quede claro.

**Comment by RigoFlores** [comment]
Diario sin faltar un día, ha estado marcando este cliente....:(
para preguntar si ya está listo este tema...

**Comment by jccastillo0007** [comment]
Checa la versión que subí hoy a PRU, creo que ya quedo, si es así, ma;ana lo subo a PRO.

**Comment by RigoFlores** [comment]
ya está validado, hay que subirlo a pro...
(ahora se avanza de poquitos)...
