### ISSUE TITLE
Agregar los datos de contacto en el reporte de facturación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#558]
Nombre, correo y teléfono.
Esto es para que a partir del listado de facturación, y con los datos de pagado o nó, sepas a quién llamarle y cobrarle... jeje

**Comment by jccastillo0007** [comment]
el reporte de facturación es el reporte de consultas de facturas cierto ?

**Comment by RigoFlores** [comment]
Afirmativo

**Comment by jccastillo0007** [comment]
done.
