### ISSUE TITLE
SIGUE PENDIENTE LA NAVEGACIÓN EN PÓLIZAS CON SOLO TECLADO EN eCONTA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#559]
O QUE PASÓ CON ESTE ISSUE?
AHORA AÚN ES MAS COMPLICADO, YA QUE LA PANTALLA SE HA EXTENDIDO, Y REQUIERE TODAVÍA DE UN CLICK ADICIONAL A LOS QUE YA SE DAN...

**Comment by jccastillo0007** [comment]
Esta complicado, necesito investigar y ver opciones...
