### ISSUE TITLE
No permite editar productos agregados a la factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#56]
Si ya se agregó un producto a la factura, no permite editarlo.

**Comment by jccastillo0007** [comment]
Este defecto ya lo tenia yo identificado, y es complicado de resolver ahora mismo.

**Comment by RigoFlores** [comment]
La verdad no me queda muy claro porque es complicado.
Asumo que la relación entre tablas antes de emitir la factura (son temporales mientras no se timbre), mas o menos se ve así:

RFCemisor->idFacturaTemporal->id's productosTemporales

Claro con toda la data general que ocupa. 
Tons a partir de ahí, porque no podría tomar un productotemporal y simplemente editarlo. Entiendo que son tareas elementales de un catálgo.

**Comment by jccastillo0007** [comment]
No se ocupan tablas temporales, y esta pantalla no es un catalogo

El tema va mas con el control de los totales en parte inferior de la pantalla y con la pantalla modal que se despliega,

Claro que se debe poder y claro que lo tenemos que resolver, pero no es tan sencillo

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
No me refiero a tablas temporales propiamente, sino mas bien a que se va almacenando una factura, que aún no es factura porque no está timbrada, entonces por ello le llame temporal, pero realmente es un registro que se podría o no, ir almacenando sin tener la etiqueta de factura, hasta que se timbre, o hasta que el usuario o el sat o el pac o el facturat, la rechace como factura, y entonces se tendría que eliminar dicho registro temporal.

OK, bueno pues queda pendiente este isuue.

**Comment by jccastillo0007** [comment]
Mmm no lo creo, no funciona asi y seria muy costoso en performance hacerlo asi, el problema es por otro lado

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
Bueno, supongo que algo así se deberá implementar para poder:

a) almacenar cotizaciones
b) almacenar remisiones
c) almacenar facturas incompletas o completas pero sin timbrar

un registro llave de generales + n registros de detalle (uno por cada concepto).

**Comment by jccastillo0007** [comment]
Deprecated.... voy a cambiar el estatus a "missing functionality"

**Comment by RigoFlores** [comment]
AYER SURGIÓ EL TEMA CON UN CLIENTE WEB...
(INSISTO, TODA LA FUNCIONALIDAD DEL ESTÁN ALON, NO ESTÁ DE GRATIS... LA FUIMOS OBTENIENDO POR RETROALIMENTACIÓN DEL CLIENTE, Y OLÍMPICAMENTE LA DEJAMOS DE LADO).
ESTA CLIENTE FUE MUY MAMILA, AMÉN QUE NOS ESTÁ PROBANDO, AMÉN QUE SU PROVEEDOR ACTUAL SI SOPORTA ESTA EDICION DE PRODUCTOS AGREGADOS A LA FACTURA...

**Comment by jccastillo0007** [comment]
Fixed

**Comment by RigoFlores** [comment]
no pude hacerlo ni en pro, ni en pru

**Comment by jccastillo0007** [comment]
Esto funciona solo en el ERP, chaaaaa

JC@iPhone.
 Saludos.
