### ISSUE TITLE
PROBLEMA CRÍTICO EN PRODUCCIÓN-PÓLIZAS  (fecha 01 del mes)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#560]
PARA EL CLIENTE QUE LE PASASTE LOS SALDOS DE DICIEMBRE A ENERO, AHORA EL RESULTADO DE LA CAPTURA DE LAS PÓLIZAS, NO SE VE REFLEJADO EN LA BALANZA DE ENERO.

**Comment by jccastillo0007** [comment]
Creo saber porque es... es probable que afecte la hora + min + segundos de cuando se esta haciendo el query... debo hacer algunas pruebas y arreglar el query si es necesario.

**Comment by RigoFlores** [comment]
El problema es precisamente que aunque se reporta CRÍTICO o como sea, no se corrige... ayer se debió entregar la contabilidad electrónica, y ahora si el cliente ya está de pestañas...
Lo único que sé, es que crees saber por donde, pero si eso le respondo al cliente que ya van 3 horas que marca, yo creo que me recuerda a todos mis ancestros...

**Comment by jccastillo0007** [comment]
No puedo resolver un issue crítico tan rápido, se hace un esfuerzo y lo
mejor sería lograrlo en la misma noche, pero si no es fácil de encontrar y
arreglar no puedo hacer magia... y obvio lo que te digo a ti no es para
decirselo al cliente... hoy me voy a dedicar a eso, y espero si resolverlo,
y si es asi, lo subo a producción directamente.

Saludos.
JC.

2016-03-08 14:44 GMT-06:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
OK, solo hay que tener cuidado de no pegarle a otras cosas... este issue surgió a partir de la corrección de otro...

**Comment by RigoFlores** [comment]
Ya ví, el problema si es problema, pero no es nuevo
Tenía la fecha de 01 de enero, y por ello no pela las pólizas en la balanza.
Tenemos que resolver este issue también, pero bueno, por lo menos está identificado.

**Comment by jccastillo0007** [comment]
chiaaaa. te quieres piratear mi análisis, ya quedo arreglado, el problema es que el filtro del dia inicial no lo hacia desde las 0:0:0 entonces no encontraba las polizas hechas el 1 de enero, porque tenían 0 horas 0 minutos y 0 segundos.

Este fix ya esta en PRO.
