### ISSUE TITLE
Cuando agregas el productos, en el precio unitario aparece el signo de $

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#561]
anteriormente no lo colocaba, y ahora los clientes modifican el precio dejando el signo, y el sistema pone todo en cero.
Por que aparece ahora este signo en text box del precio unitario?
Favor de eliminarlo y dejarlo como estaba antes.

**Comment by jccastillo0007** [comment]
Esto lo pone ahora para arreglar el tema de  los decimales, de que no
trunque el cuarto número decimal.

No me queda claro la falla, dice que si modifican el precio unitario, aún
respetando el signo, pone todo en 0... necesito mas detalle.

Saludos.
JC.

**Comment by RigoFlores** [comment]
Si el precio unitario es por ejemplo $1.00, entonces al cliente se le hace 'natural' modificarlo a $15.00, es decir le dejan el signo de $ en el cuadro de precio unitario. Cuando esto sucede, todos los cálculos importe, iva, total... se van a cero.
Se corrige colocando únicamente 15.00 ó 15, en lugar del $15.00 que capturan algunos clientes.

**Comment by jccastillo0007** [comment]
fixed en PRU.

**Comment by RigoFlores** [comment]
OK, quedó listo en caso que mantengas el signo o igual si se lo quitas... es correcto?
