### ISSUE TITLE
NO ACEPTAR ASIENTO EN PÓLIZA, SI NO SE HA SELECCIONADO CUENTA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#562]
Ahora mismo permite grabar póliza, aunque la cuenta no haya sido seleccionada del listado 'autorizado'.

**Comment by jccastillo0007** [comment]
no lo pude reproducir, siempre que intenté grabar una póliza, si validó que se ingresó al menos una transacción y en esa transacción si validó que se ingresara la cuenta.... 

Cuales son los pasos para reproducir este defecto?

**Comment by RigoFlores** [comment]
Lo acabo de hacer con la póliza 201601 P001 en pruebas de la cuenta de la tía.
1) edité dicha póliza
2) le dí agregar cuenta con el signo mas
3) capturé concepto y una cantidad (pero no elegí la cuenta).
4) repetí el paso 1, 2 y 3.
5) le dí guardar y es todo... lo aceptó.. jeje

**Comment by jccastillo0007** [comment]
fixed, sucede solo con mas de una transacción, no había identificado ese escenario
