### ISSUE TITLE
Reducir un poco el espacio de las columnas de póliza

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#564]
Resulta que el ícono de agregar (+) se movió hasta el lado derecho, provocando que para agregar un asiento, hay que desplazarse con el mouse al lado derecho y darle click en (+).
El tema sigue siendo navegabiilidad y usabilidad...

Una opción es reducir un poco el ancho de las columnas de:
Numero de cuenta: casi a la mitad
Concepto: un poco
Nombre de la cuenta: también un poquito

**Comment by jccastillo0007** [comment]
fixed = PRU
