### ISSUE TITLE
Marca internal error cuando le doy exportar en la pantalla de consultas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#567]
Hice una factura hoy (19 de marzo) (en pruebas con la cuenta de la tía)

Si la consulto y le doy exportar todo bien.
Si genero la consulta a partir del 01 de marzo, se despliegan varias facturas y si le doy exportar marca internal error...

**Comment by jccastillo0007** [comment]
fixed.

Fue porque ahora en el export procesa el email de los clientes, y no todos los clients traen email... ya esta validado.
