### ISSUE TITLE
DescargaMasivaCFDI - colocar en directorios independientes las recibidas de las emitidas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#568]
Una opción, es a partir de lo que se tiene ahora mismo, identificar el emisor dentro del XML.
Cuando sea el RFC del cliente, evidentemente se tratará de emitidas.
En otro caso serán las recibidas, y se pueden colocar en distinto directorio, con una estructura similar facturat de escritorio, pero con la carpeta adicional de recibidas y emitidas.

**Comment by jccastillo0007** [comment]
Done... hay que bajar otra vez el zip de dropbox, ya no es necesario instalar la app, ya solo correr el descargat.
