### ISSUE TITLE
DescargaMasivaCFDI - Implementar el filtro de vigentes y/o canceladas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#569]
Se necesita agregar el filtro o en su caso se puede de una vez ejecuta la validación ante el SAT.
Lo cual quizás sea redundante, ya que si lo descargamos del portal, es porque son legítimas del SAT, pero lo que no conocemos es su estado, entonces podríamos una vez que se han descargado, checar su status con el web service.
Con ello, se puede agregar oootra carpeta que indique vigentes y canceladas, aún cuando si sea posible agregar el filtro.

**Comment by jccastillo0007** [comment]
Si me lleva mucho tiempo implementar el filtro de vigentes y/o cancelados, lo haré una vez que estén abajo los XML, la pregunta aqui, que aplica para todos los requerimientos que levantaste para el descargat es:  
Una vez que se bajaron los XML, deberían levantar el facturat  standalone, y elegir alguna opción para empezar con el procesamiento de los XML descargados ? 
Por ejemplo para el Excel de los archivos descargados, o para moverlos a carpetas de vigentes y cancelados, o moverlos a emitidos y recibidos, etc.... todo esto se haria en FacturaT ?

**Comment by RigoFlores** [comment]
Se podría invocar desde el facturat, la descarga para que posteriormente se continúe ahi mismo todo el procesamiento?

**Comment by jccastillo0007** [comment]
Se puede que descargue únicamente las facturas vigentes, y no dar opción para bajar las canceladas?

**Comment by RigoFlores** [comment]
Yo creo que sí... ya veremos si en adelante nos piden eso... pero de entrada, creo que si puede ser

**Comment by jccastillo0007** [comment]
Done.

Va a descargar unicamente vigentes, tanto emitidas com recibidas.
