### ISSUE TITLE
No respeta los enters al inicio y al final, de la descripcion complementaria

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#57]
Esa funcionalidad es de utilidad para el usuario cuando se requiere acomodar de cierta manera la información complementaria.
Y ya ni mencionar en la factura de gobierno, donde todo lo que capturan en word, igualito debe pasar a la información complementaria

**Comment by jccastillo0007** [comment]
Por fin puedo rechazar uno.

El unico enter que creo no respecto fue al inicio, pero los demas enter durante toda la descripcion si los respeta.

**Comment by RigoFlores** [comment]
Se rechaza el rechazo, ya que la ficha indica que no se respetan los enters al INICIO y FINAL de la descripción complementaria.
Quedó corregido solamente la parte del final.
Falta corregir lo del INICIO.
No entendí porque se rechazó...

**Comment by jccastillo0007** [comment]
No ma, para que quieren un ebter al inicio si jasper ya lo graba un renglon abajo

Rechazo el rechazo del rechazo

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
No quiero que se interprete como capricho, sino como resultado de la experiencia con el facturat durante 2 años, por eso desde el mero principio mi petición fue que se 'comportara idéntico', pero ahí va de nuevo la explicación del porqué si se requieren enters en algunos casos al inicio de la info complementaria:

a) algunas ocasiones requieren colocar información, digamos a la mitad o al final de la factura. Es info que no tiene que ver con el producto, pero con la factura sí. Orden de compra, pedido, número de cliente, lugar de entrega, etc. Puede ser muy variable. Entonces ahí con enters al inicio, ellos acomodan la info a como requieran.
b) la plantilla de libre captura, que se copia el contenido de un formato de word hacia la info complementaria, en algunos casos es muy poca, y para que no se vea tan vacío el espacio, le dan enters al inicio para central la info en el espacio de despliegue
c) otros casos que no tengo detectados.

En fin, como te decía al inicio, las funciones que solicito no me las fumo yo, sino son las necesidades detectadas con base a requerimientos de los distitntos clientes.

**Comment by jccastillo0007** [comment]
Dado que es un problema muy extraño, propongo lo sig.

Puedes colocar un caracter al inicio del primer renglon ?, ya sea . , -  o cualquier otro, el tema es que al poner un caracter, ya puedes dejar todos los enter que quedan... 

Se que es un workaround chacarron, pero funciona.

**Comment by RigoFlores** [comment]
lo tomaré como eso, como un paliativo en lo que se resuelve definitivamente.
Deja revisar desde jasper nuevamente, si existe una propiedad que 'acomode', la información complementaria, debajo de una descripción 'estirada', es decir que ocupa mas espacio que el definido en el diseño.
Por otro lado, posiblemente tendríamos que complementar esta solución, tomando un punto (.) al inicio, para indicar que se agregarán enters o algo así. Mientras lo reviso, lo dejaré abierto pero ya con baja prioridad.

**Comment by RigoFlores** [comment]
YA SURGIÓ EL TEMA CON UN CLIENTE, YA QUE SE ENCIMAN LOS DATOS.
LE COMENTÉ DEL PALIATIVO, PERO DEFINITIVAMENTE ES UN GUORQARRAUN TEMPORAL.
VARIOS ISSUES LEVANTANDOS EN SU MOMENTO, YA ESTÁN SURGIENDO CON LOS CLIENTES WEB....

**Comment by jccastillo0007** [comment]
supongo que esto ya no sucede, después de casi dos años.

**Comment by RigoFlores** [comment]
COMO SI LOS BUGS SE CORRIGIERAN AL PASO DEL TIEMPO... NI QUE FUERAN ENCULAMIENTO... NO, SIGUE IDÉNTICO, NO RESPETA ENTERS AL INICIO, NI AL FINAL..

**Comment by jccastillo0007** [comment]
Cuando un bug no tiene update en 2.5 años dudo mucho que tenga alto impacto y/o que cause problemas, y dado que no es fácil de resolver, no vale la pena dedicarle tiempo
