### ISSUE TITLE
DescargaMasivaCFDI - Implementar un excel con el contenido de los archivos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#570]
Evidentemente deberá tener 2 secciones, una para generales y otra para detalle (productos).
Es posible hacer una shit (ah no, perdón una sheet) por cada XML?
O de que otra manera quedarían varios XML en una sola hoja? quizás filtrando por folio SAT.
Básicamente se ocupa desplegar todos los datos generales y todos los datos de productos.

**Comment by jccastillo0007** [comment]
Esto esta muy fumado no?

Alguien te lo pidió o es idea tuya?

Si se requiere, lo que se me ocurre es
1. Hacer un sheet con lo generales (a este si le puedo ver utilidad)
2. Hacer un sheet por cada xml (este sheet is shit)

osea que habría n+1 sheets

pero si ya se va a generar el pdf, como para que quieren todos los xml en un solo sheet es puro shit lol

**Comment by RigoFlores** [comment]
Esa shit es realmente la que sirve... la vi en el XML Tool, también me la mostró el de la gasolinera cuando los visité... no es una shit por cada XML, es una para tooodos... quizás ahí lo expresé incorrectamente.

A los contadores lo que les sirve, es tener integrado en un excel toda la info de facturación...
Yo lo que ví es que en una hoja tenían los generales al principio (todos y cada uno de ellos)... y en esa misma hoja, en una sección debajo de los generales, el detalle de los productos de cada XML...
Si eso es complicado... podría ser los generales en una hoja y el detalle de tooodas en otra... siempre con la posibilidad de aplicar los filtros....

**Comment by jccastillo0007** [comment]
puedes checar la version del ePDFCreator que subí hoy.

Al momento de leer los XML y crear el PDF, también crea un csv con los datos detallados de todos los XML leídos.
Define que datos conforman el archivo header y el archivo detallado de las facturas, como no lo se aún, puse algunos datos solo para que veas como va a funcionar.

**Comment by RigoFlores** [comment]
Validé... solo incluye información de UN SOLO XML...
Ya te envié un excel ejemplo, con los generales y los detallados de un XML..

**Comment by jccastillo0007** [comment]
Si, por ahora solo es un XML, de hecho, me acabo de dar cuenta que el ePDFCreator funciona solo con un XML a la vez.... creí que estaba validado a soportar N XML...

En el excel que enviaste, supongo que manejan facturas con 1 solo producto, para facturas con 2 o mas productos, no serviría el excel... ya que tendrían que hacer una mezcla chacarrona en todos los campos relacionados con productos, y por otro lado, no sería escalable, ya que para facturas con n productos, seria un cagadero.. y no podr[ian hacer filtros pro producto, etc...

Para probar la versión de hoy, solo reemplaza el archivo ePDFCreator-1.0.0.jar en tu instalación actual del ePDFCreator.

**Comment by RigoFlores** [comment]
Ahí vienen ejemplos con varios productos en un solo renglón... parecido a lo que hacemos en el texto plano del conector... es una opción.... no la veo tan mal, pero si tienes mejor propuesta, es uelcom...

**Comment by jccastillo0007** [comment]
si ya vi, y concatenan los datos de concepto de productos, lo cual me parece super cochino y no es escalable, no podrán hacer filtros en excel por producto o por unidad de producto, o precio , etc... no es funcional a nivel producto, a nivel general puede ser que este bien.

**Comment by jccastillo0007** [comment]
Listo, la version de hoy si procesa multiples XML, de hecho, ya vi lo que me estaba pasando y era un error mio, la herramienta si es capaz de procesar n XML ....

**Comment by RigoFlores** [comment]
afirmativo, el issue no es que no procese n xml, sino que no los registraba en el excel...
Ahora se tiene que integrar con el descargat y empatar con las carpetas configuradas, donde se guardan los XML... debería existir un checkbox, que indique generar PDF y excel

**Comment by RigoFlores** [comment]
algo que no veo en el excel que es super importante para sus propósitos, es el desglose de todos los impuestos a nivel general... inclusive los impuestos locales...columna para:
TRASLADADADOS: IVA, IEPS (TASA, MONTO)
RETENIDOS: IVA, IEPS (TASA, MONTO)
LOCALES: NOMBRE, TASA, MONTO.

**Comment by jccastillo0007** [comment]
Ok, pero hay que empezar a ofrecerlo, para validar el interes sobre la app, capaz que no pega y ya le hemos invertido un buen

**Comment by jccastillo0007** [comment]
Listo.. ... ya subi la versión que lo hace, solo no agregué los imp locales, ya que ese es un complemento y agrega mas desmadrito...

**Comment by RigoFlores** [comment]
Hay un detalle. El tema de los impuestos en excel, te imaginarás que es muy importante, ya que de aquí se derivan las pólizas y por consecuencia la contabilidad.
Existen algunos casos que nosotros no consideramos en nuestro XML, pero otras empresas sí. Correcto o incorrecto, no lo sé, pero el asunto es que así está.
Particularmente impuestos trasladados:

```
(cfdi:Traslados )
  <cfdi:Traslado importe="0.00" tasa="0" impuesto="IVA" 
  <cfdi:Traslado importe="1.31" tasa="16" impuesto="IVA" 
(/cfdi:Traslados )
```

Aunque solo manejan IVA del 16%, reportan un impuesto con tasa IVA 0, y con un monto de 0.

El caso de Telmex es aún mas dramático:
![trasladados telmex](https://cloud.githubusercontent.com/assets/2912775/15343097/c2e0ceca-1c5f-11e6-979a-d91563954a3b.png)

**Comment by RigoFlores** [comment]
Telmex reporta 3 IVAs trasladados, pero realmente solo ocupa uno.
Mi propuesta es que en trasladados, como retenidos... se reporte LA PRIMERA TASA Y MONTO, cuyo importe sea mayor a 0.
Por ejemplo en telmex sería IVA de 16%, con un monto de 55.03

No olvidar que aplica para IVA,  IEPS (traslados) e IVA e ISR (retenidos).

Por cierto, aquí el issue es que la información en el excel se genera chueca para estos casos particulares...

**Comment by jccastillo0007** [comment]
Listo, checale haber si ya se contemplan todo esos escenario.

**Comment by RigoFlores** [comment]
La tasa reportada en el excel para el IVA dice 0.16, pero para el IEPS indica 8... hay que homologar... debe reportarse como entero, es decir 16.00, y no 0.16 para el IVA y también para el IEPS.
De hecho en el XML la tasa viene como 16.00.

Otra cosa, no se que sea mas chacarrón, en el caso de facturas con mas de 1 producto... si el indicar que son 2 por ejemplo, y solo incluir 1... o como el excel de ejemplo, donde se incluyen todos en una sola celda... para mí no tendría problema, que los datos correspondientes a los conceptos, se incluyan en una sola celda... cantidad, unidad, concepto, punitario, importe... cada celda con datos separados por | (o algún otro), para el caso de mas de 1 producto.

Una mas en el excel, existe una columna que dice descripción... me parece que está de sobra, ya que no es parte del anexo 20. De hecho aparece vacía en todo caso.

**Comment by jccastillo0007** [comment]
es mas chacarron incluir varios items (en este caso productos) en una sola celda, ya que eso deshabilita el potencial de excel de hacer filtros y sumatorias, si acaso seria tener un excel con el puro encabezado del cfdi (sin productos), y otro excel con el detalle de productos, teniendo un producto por renglon..

De por si no me agrada el hecho de que esta de moda exportar todo a excel, y menos crear un documento en excel que no será funcional ya que no se pueden hacer filtros....

**Comment by RigoFlores** [comment]
Jejeje... moda? Pues es que el excel es muy cómodo para los no informáticos, que son la gran mayoría de usuarios. La otra es hacer construir nuestro propio excel... 
Si se pueden hacer filtros con celdas de múltiples conceptos, ya que filtras por 'contiene'... pero nada, vamos viendo como se comporta así.. 

lo de las tasas si hay que corregirlo

**Comment by jccastillo0007** [comment]
Para mi, es aferrarse a usar Excel... aún no han evolucionado.

**Comment by RigoFlores** [comment]
Hay que corregir lo de las tasas...

En lugar de excel, que propondrías???

**Comment by jccastillo0007** [comment]
en lugar de excel, seria usar la app, y tal vez agregar reportes mas específicos, pero si les gusta excel, entonces que lo usen bien, y no mezclar mas de un item por columna

Lo de las tasas ya esta listo

**Comment by RigoFlores** [comment]
Negativo, lo de las tasas sigue chueco... lo reporta como 0.16
Para facturas con múltiples productos, ya genera n renglones repetidos, así se programó?

**Comment by jccastillo0007** [comment]
puedes checar otra vez, asegúrate de usar la última versión que esta en dropbox, yo generé el excel a partir de los 32 xml que me enviaste y si genera bien el reporte con 16.0 en la tasa de iva.

Hoy subiré otra vez un zip, para asegurar que tienes la versión mas reciente.

**Comment by RigoFlores** [comment]
Si, ya lo reporta bien... pero no respondiste al tema de que ahora ya muestra n renglones repetidos, cuando la factura incluye n productos...  lo cual para hacer las sumatorias, ya no cuadró...

**Comment by jccastillo0007** [comment]
Si, siempre ha funcionado asi, renglón por producto.

Lo que voy hacer, es otro excel con solo la información general, para mantener consistente la información de sumatorias y no hacer cochinadas.

**Comment by jccastillo0007** [comment]
Subí un release hoy del pdfor, que crea 2 csd, 1  con el detalle y 1 con solo el header.

Estoy trabajando en integrar esto al FacturaT, pero eso es otra historia.
