### ISSUE TITLE
DescargaMasivaCFDI - Dar opción para generar el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#571]
Si así lo requiere el usuario, dar opción para generar el PDF a partir del XML.
Yo entiendo que esto no debe ser tan tan necesario, pero para los contadores podría ser importante, ya que ellos trabajan con PDF's y no con XML.

**Comment by jccastillo0007** [comment]
Esto se cubre con el ePDFCreator, quieres que le agregue esas opciones al facturat standlone, ahi es donde voy hacer el tema del vaciado a los differentes Sheet de shit.

**Comment by RigoFlores** [comment]
Aún desconozco como quedará todo finalmente, pero entiendo que si, el PDFor cumple lo que aquí se pide

**Comment by jccastillo0007** [comment]
Correcto, tratemos de mostrar y venderlo asi en conjunto con el ePDFCreator, y ya luego lo vamos puliendo y automatizando mas.

**Comment by RigoFlores** [comment]
OK, pero a ver si entiendo, ahora por un lado es el descargamasiva, y por otro el PDFor... tienen que copiar manualmente los XML, a la carpeta del PDFor para que los procese... ahí es donde si creo que podríamos integrar, al menos el tema de la carpeta....

**Comment by jccastillo0007** [comment]
no recuerdo como corres tu el PDFor, pero según yo, le pasas la dirección donde estan los XML ...cierto ?, si es asi, solo tienen que enviar el path donde se bajaron los XML.

Cómo ves tu que se puedan integrar el descargamasivaenchinga y el pdfor ?

**Comment by RigoFlores** [comment]
Ejecuto un bat... que contiene lo siguiente:
@echo off

set ALL_DIR=%cd%
set CLASSPATH="%ALL_DIR%"\System\Jar;System\Jar*
set MAIN_CLASS=com.facturat.pdfcreator.ePDFCreator

set PATH_XML=C:\ePDFCreator\XML\
set PATH_PDF=C:\ePDFCreator\PDF\
set PATH_LOGO=C:\ePDFCreator\android-intel.png
set PATH_JASPER=C:\ePDFCreator\cfdi_base.jrxml

java -Xmx1024m -Xms128m -Dfile.encoding=UTF8 -cp .:%CLASSPATH% %MAIN_CLASS% %PATH_XML% %PATH_PDF% %PATH_LOGO% %PATH_JASPER% 

ahí se le indica la ruta del XML y PDF... pero es fijo.
Esta ruta debe empatar con la estructura de directorios del descargamasiva, que incluso ya cuenta con toooda la estrcutura, solo faltaría agregarle el directorio PDF... pero recuerda que es distinto por mes.
También falta invocar a este bat, desde el comando de línea...
