### ISSUE TITLE
Sistema de Nómina - Crear pantalla de generales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#572]
Generar pantalla con datos GENERALES DE NÓMINA.
Son los que aplican para todo empleado y toda nómina.

En una segunda sección dentro de esa misma pantalla, incluir los datos que se ocupan a nivel empleado pero que en la mayoría de los casos aplican para todos los empleados:
Días de aguinaldo, días de vacaciones, % de prima vacacional, días laborados.

Estos datos se podrán modificar en la pantalla de cada empleado, pero los cargará por omisión, y si se modifican se almacenarán a nivel de cada empleado. (algo así como las plantillas generales y las customizadas en el caso de los jasper ).

**Comment by jccastillo0007** [comment]
ya tengo la primer pantalla, la que incluye toda la configuración general de la nómina, no la he subido a PRU porque aún me falta la segunda sección y sobre todo me falta conectar o reutilizar la pantalla de empleados que ya tenemos, tengo un problema de disenio que quiero resolver correctamente, para no duplicar código.

**Comment by RigoFlores** [comment]
En la pantalla actual, entiendo que solo se agregarán campos adicionales para los cálculos.
La manera de agregar percepciones o deducciones casi no debería cambiar. 
Sobre todo el tema de percepciones. 
En lo general, las deducciones serán calculadas, pero habrá deducciones como descuentos por faltas, o préstamos o fondo de ahorro, que se deberán capturar también para realizar los cálculos.

**Comment by jccastillo0007** [comment]
Por ahora se van a guardar todos los datos por cada cliente (no por cada empleado), ya que se visualizan posibles cambios dependiendo del nicho de mercado de cada cliente.

Esta pantalla ya esta casi lista, me falta agregar los datos que son medio generales jajajaja, es decir, generales pero que se pueden cambiar por cada cliente.

**Comment by RigoFlores** [comment]
Aclaración... si habrá datos generales, generales... ya que las tablas de ISR y el IMSS aplican para todo empleado.
También habrá un segundo nivel de datos que pudieran ser generales para toda la empresa (clientes nuestros), por ejemplo días de vacaciones, % de prima vacacional, etc.
Y habrá otros que son a nivel de empleado.
Debemos pensar en un sistema grande, para gestión de RH, donde los datos de empleado deben incluir históricos de pagos, vacaciones (tomadas y por tomar), faltas, etc. Un archivo o cardex por empleado.
Creo que si lo vamos haciendo desde el inicio, pensando en ello, podremos llegar a algo importante. Prácticamente será una nueva área de negocio en la TIA, que quizás requiera incluso capacitación de mi parte (aún lo estoy valorando, un diplomado o maestría en RH).

**Comment by jccastillo0007** [comment]
Ok de acuerdo... asegurate de tener capturados todos esos requerimientos en
 tickets de github, de lo contrario se puede olvidar.

JC.

Saludos.
JC.

2016-04-07 10:07 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Están faltando los siguientes datos:

Días exentos aguinaldo
Días exentos PTU
Días exentos prima vacacional
Meses del Año
Número de SMGDF exentos para horas extra

Está sobrando este dato, o de donde salió: Porcentaje de excedente de 3VSMGF

Número de días promedio del mes se debe calcular (podría ser dato fijo, pero los años bisiestos le parten la mami) a como sigue: 
Redondear a 1 decimal ( dias de año / meses de año )

**Comment by jccastillo0007** [comment]
Me estoy basando en la especificación funcional que me enviaste,  esta en dropbox en FacturaT/Requerimientos/Nomina

El archivo de cálculos aún no lo reviso, ya que aún no estoy ahi.... 

Ojo.. es muy importante que los requerimientos estén bien definidos, y todo lo que tu sabes y estas aprendiendo y ves que se va a  necesitar este en esos requerimientos, lo que me acabas de decir de que todos estos datos se deben almacenar históricamente por año, es algo nuevo, que no tenía contemplado y si me pega en el código que hasta ahora he desarrollado.

Checa la especificación funcional y agrega lo que me falte, de ahí tomé las variables que me dices que sobran.

**Comment by RigoFlores** [comment]
Entiendo lo que dices... pero entre mas me voy metiendo, voy aprendiendo nuevas cosas.
Me parece muy interesante el proyecto, pero si van surgiendo cosas que obvio no tengo consideradas. 
Empecé a analizar los XML que timbramos de nómina, de 2 empresas canadienses, y de ahí es que estoy tomando nuevos escenarios.
Por otro lado, considerar que podemos consultar/generar históricos, lo cual requiere que cada año se almacenen las variables generales, que aplicaron en cada año. Si es nuevo, pero asi van surgiendo. No creo que se presenten muchos mas de esos, pero si concluimos esa primera pantalla, será en firme.
Esto será una herramienta de gestión de RH.

**Comment by jccastillo0007** [comment]
Ok, de acuerdo, pero si actualiza la especificación funcional porque yo la reviso todo el tiempo para continuar con el desarrollo.

**Comment by jccastillo0007** [comment]
Se me hace que este dato que dices que falta:  
       Número de SMGDF exentos para horas extra
Es el que yo tenía como:
       Porcentaje de excedente de 3VSMGF

Será?

Por otro lado, no creo que necesitemos el campo:

Meses por año.... estoy casi casi seguro que siempre son 12..

**Comment by RigoFlores** [comment]
Puede ser que si sea el campo. Voy a revisar mañana temprano.

Si, es muy probable que el parámetro de meses por año no cambie. Al menos los últimos 2016 años ha sido así... jajajajajaja....

Yo lo puse, para no tener en hardcode un dato que se refiere a meses del año. No se si me explico, pero como que no me pareció que en los cálculos dividieras por 12 así de huevos... mas bien que dividieras por la variable $MesesAnio, que ya sabes de que se trata cuando estemos debugueando

**Comment by RigoFlores** [comment]
Ya ví, no está sobrando ese campo.
Actualicé el word, en la sección de generales. 
Como dices, sobre ese nos estaremos basando.

**Comment by jccastillo0007** [comment]
Los defectos de la pantalla se estan levantando aparte.
