### ISSUE TITLE
PROBLEMA CON CONECTOR + ADDENDA TRIDONEX + IMPUESTOS RETENIDOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#573]
Ya envié un correo con todo el contexto:
CUANDO SE COMBINAN ESTOS FACTORES, LE INCLUYE UNAS LEYENDAS QUE SEGÚN EL VALIDADOR DEL SAT, NO CUMPLE CON LA NORMA:

ESCENARIO. SON 2 ARCHIVOS DE TEXTO QUE SE PASAN AL CONECTOR, UNO SI JALA BIEN, EL OTRO INCLUYE UNAS LEYENDAS DONDE EL VALIDADOR DEL SAT MARCA ERROR:

A)  EL ARCHIVO DE TEXTO 49 AGREGA LAS LEYENDAS INCORRECTAS
B)  EL ARCHIVO DE TEXTO 50 NO LAS INCLUYE, ES DECIR ESTÁ OK.
C)  LA DIFERENCIA ENTRE LOS ARCHIVOS DE TEXTO, ES QUE UNO INCLUYE RETENCIONES DE IMPUESTO (IVA RETENIDO)
D)  ANEXO LA LLAVE QUE OCUPÉ PARA LAS PRUEBAS

OCUPANDO UN VISOR XML:
SIN RETENCIONES EL SCHEMA LOCATION ES:
http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd

CON RETENCIONES EL SCHEMA LOCATION ES:
http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd http://www.sat.gob.mx/leyendasFiscales http://www.sat.gob.mx/sitio_internet/cfd/leyendasFiscales /leyendasFisc.xsd

AQUÍ VEO QUE POR UN LADO, CUANDO SE INCLUYEN RETENCIONES DE IMPUESTOS, NO SÉ SI SE DEBA INCLUIR ESO DE LEYENDAS FISCALES (NO ENCUENTRO EL JUSTIFICANTE), Y POR OTRO LADO VEO QUE EXISTE UN ESPACIO ANTES DE /leyendasFisc.xsd QUE QUIZÁS ES DONDE MARCA ERROR EL SAT.

**Comment by jccastillo0007** [comment]
El schema si se requiere, ya que se agrega la addenda, pero lo del espacio si es incorrecto...

**Comment by jccastillo0007** [comment]
fixed.... este defecto también debe tener muuuucho tiempo.

**Comment by RigoFlores** [comment]
No creo porque la addenda es nueva.
Creo que no se entendió el problema completamente...
a) En ambas facturas se incluía la addenda tridonex. 
b) SOLO EN caso de incluir retenciones, AGREGA una leyenda adicional del schema location, misma que es http://www.sat.gob.mx/leyendasFiscales http://www.sat.gob.mx/sitio_internet/cfd/leyendasFiscales/leyendasFisc.xsd
c) en esa leyenda le agregaba un espacio. ESO QUEDÓ CORREGIDO.

Pero la pregunta de porque le agrega esa leyenda SOLO PORQUE SE INCLUYEN RETENCIONES, no quedó resuelta. No veo porque las retenciones de impuestos requieran de esa leyenda.

**Comment by RigoFlores** [comment]
YA PASÓ LA VALIDACIÓN DEL SAT, PERO LA PREGUNTA SIGUE VIGENTE, PORQUE LE AGREGA ESA LEYENDA SOLO EN CASO DE RETENCIONES, A FACTURAS POR CONECTOR Y ADDENDA TRIDONEX. 
CUANDO NO LLEVA RETENCIONES, PERO SI ADDENDA TRIDONEX NO LE AGREGA ESA LEYENDA.

**Comment by jccastillo0007** [comment]
ya vi lo que dices.... le busque pero no encontré algo que me indicara la causa raíz...

ya sin el error del sat, si se puede liberar cierto... mientras veo que pedo..

sabes si esto se puede reproducir, con una factura normal ?

**Comment by RigoFlores** [comment]
LA COMBINACIÓN PARA QUE LE AGREGUE ESA LEYENDA ES (DESDE CONECTOR O DESDE PANTALLA): RETENCIÓN DE IVA + ADDENDA (CUALQUIER ADDENDA).

CON RETENCIÓN DE ISR NO LA AGREGA. 
LO DEL CONECTOR TAMPOCO INFLUYE.

**Comment by jccastillo0007** [comment]
De hecho no se necesita la addenda... el verdadero y único problema son los impuestos retenidos.

**Comment by jccastillo0007** [comment]
Pues encontré la causa raíz, y no es un accidente, específicamente lo pone si la factura incluye impuestos retenidos y el cliente tiene el plugin de addendas, el build de hoy lo elimina, pero mi duda es porque esta configurado asi.... no lo pediste en algún momento?
