### ISSUE TITLE
EN EL REPORTE DE EXCEL, EN ESCRITORIO INCORRECTA LA COLUMNA DE SUBTOTAL

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#574]
POR DEFINICIÓN EN EL ANEXO 20, EL SUBTOTAL ES LA SUMA DE IMPORTES
LO QUE ESTÁ COLOCANDO AHORA MISMO EN ESA COLUMNA ES PRECISAMENTE SUBTOTAL - DESCUENTOS.

QUE RARO QUE APENAS SE HAYA DETECTADO, O QUIZÁS SE INYECTÓ EN UNA VERSIÓN RECIENTE.

**Comment by jccastillo0007** [comment]
Si, que raro que apenas salga....

**Comment by jccastillo0007** [comment]
Fixed.... release 9.1.20 del dropbox...

**Comment by RigoFlores** [comment]
Quedó pior, ahora no muestra el subtotal en el excel, cuando existen descuentos.

**Comment by RigoFlores** [comment]
TENGO QUE ESPERAR ESTA CORRECCIÓN, PARA LIBERAR LA OTRA CORRECCION DE TRIDONEX, YA QUE DE LO CONTRARIO ESTARÍA INYECTANDO UN DEFECTO CONOCIDO. EN OTRAS PALABRAS URGE PARA AYER.

**Comment by jccastillo0007** [comment]
chiaaaaaaa. fixed con el release de hoy.
