### ISSUE TITLE
Complemento Liverpool - Le vale mami el método de pago y siempre envía No Identificado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#575]
No toma en cuenta el método de pago que se captura en pantalla, ya que siempre envía NO IDENTIFICADO, tanto al PDF y XML, independientemente lo que se haya capturado en pantalla.
 Aplica para escritorio, ya que en web no la tenemos esta addenda.

**Comment by jccastillo0007** [comment]
Una vez mas, lo hace aldrede... explicitamente tiene que para complemento liverpool, le debe poner No Identificado.... luego entonces, eso se pidió asi, y no sé si ahora le vaya a pegar a otros clientes.

**Comment by RigoFlores** [comment]
ok, deja revisar la spec de la addenda. seguramente así se pidió

**Comment by RigoFlores** [comment]
Pues no hallé nada que indicara que tenga que ser así.
De hecho en la addenda (complemento), no ocupa este dato.
So, hay que corregir.

**Comment by jccastillo0007** [comment]
Listo... si luego reclaman por este cambio, hay que levantar otro ticket.
