### ISSUE TITLE
Escritorio - No borrar los datos extra de memoria, sino hasta que se ha timbrado una factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#576]
Para el nuevo carta de porte, son muchos datos extras... el cliente le da preview... se da cuenta que la cagó en algo, y regresa a corregir a los datos extra... resulta que tiene que capturar todo nuevamente... esto es en particular para carta de porte, pero en general para todos los datos extra.

Que se borren de memoria, hasta después de timbrado, o hasta que le den el botón limpiar... (cualquier de las 2)

**Comment by jccastillo0007** [comment]
fixed.

Este fix no esta relacionado a carta porte, aplica para todos los tipos de facturas.

**Comment by RigoFlores** [comment]
Si, lo entiendo... ahora solo falta que se limpien con el botón de limpiar... ya que se limpian solamente cuando se timbra...

**Comment by jccastillo0007** [comment]
Done.
