### ISSUE TITLE
Nomina Configuración - Datos repetidos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#577]
Ahora mismo muestra repetidos los datos de dias por año y número de días promedio por mes.

**Comment by jccastillo0007** [comment]
fixed.

Ojo... aún no hace los cálculos automaticfamente, ahorita todo es capturado...

**Comment by RigoFlores** [comment]
Negativo, los sigue repitiendo... chiaaaaaa

No. de días promedio por mes
Número de días promedio al mes (NDPM)

Días por año
Días por año (DPA)

**Comment by jccastillo0007** [comment]
fixed.
