### ISSUE TITLE
Nomina Configuración - Guardar datos para cada año

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#579]
Para poder generar nóminas de años anteriores, obtener reportes históricos, etc

**Comment by jccastillo0007** [comment]
Ya lo esta guardando por año... pero me falta hacer lo propio con el tema de la tabla del ISR.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Aún no guarda independientemente las tablas de ISR y Subsidio.

**Comment by jccastillo0007** [comment]
Listo

**Comment by jccastillo0007** [comment]
?????

**Comment by RigoFlores** [comment]
algo pasó en algunos de mis comentarios... 
aquí el tema es que cuando quieres agregar un nuevo bloque de datos, desaparecen los controles para capturar las tablas de isr y subsidio.
Digamos que quedó ahora pior...

**Comment by jccastillo0007** [comment]
puedes checar otra vez, no lo pude reproducir.

**Comment by RigoFlores** [comment]
ESTA ES LA PANTALLA QUE APARECE CUANDO LE DOY AGREGAR UN NUEVO REGISTRO, SI TE DAS CUENTA NO TENGO CHANCE DE CAPTURAR LAS TABLAS ISR Y SUBSIDIO
![ficha 579](https://cloud.githubusercontent.com/assets/2912775/14627896/5e0775f6-05be-11e6-8570-63f0f6037ea8.png)

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Está peor... si le doy click en el ícono de agregar (+), no pone ningún campo en modo de captura... es decir están como solo lectura, aún cuando le diste agregar registro

**Comment by jccastillo0007** [comment]
Ups... pequeño detalle

**Comment by RigoFlores** [comment]
Si editas el registro, y le cambias el año.... lo permite!!!... el año en este caso, es como el RFC en el caso del catálogo de clientes.... si lo cambias, se trata de ooootro año...
De hecho la solicitud es generar una lista con los años a partir del 2016 al 2100... 
pero como quiera, si cambian de año... entonces se tendría que agregar ooootro registro... 
Me parece que el año, no deberían poder cambiarlo

**Comment by jccastillo0007** [comment]
Listo, no se permite la edición del anio, una vez capturado.

**Comment by RigoFlores** [comment]
Sigue repitiendo los datos Tope 3 veces SMGDF y Porcentaje de excedente de 3 VSMGDF, ya que están en la sección de generales y también en la sección de IMSS. deben mantenerse los de la sección del IMSS.

**Comment by jccastillo0007** [comment]
Chiaaaa
