### ISSUE TITLE
GASOLINERAS, AGREGAR EL NOMBRE AL REPORTE DE PRODUCTOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#58]
Se requiere agregar al reporte de productos, el nombre o razón social en la columna a la derecha del RFC.
Aplica para el FacturaT estánalon.

**Comment by jccastillo0007** [comment]
Fixed.

Release 6.4.5 from jenkins.

**Comment by RigoFlores** [comment]
Ya quedó, pero solo falta eliminar las comas en el nombre o razón social, ya que al ser separador de campos, en algunos casos las columnas se mueven, cuando el nombre contiene comas. Ejemplo:
Tecnologias de Información Aplicada, SA de CV
provocaria que se agregue una nueva columna...

**Comment by jccastillo0007** [comment]
Done.
