### ISSUE TITLE
Nomina Configuración - Completar datos en tabla del IMSS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#580]
![datos para imss](https://cloud.githubusercontent.com/assets/2912775/14399201/fd07481e-fdaf-11e5-9fc8-6083c05ffc0a.png)

**Comment by RigoFlores** [comment]
Hoy se muestra una tabla, pero no está completa.

**Comment by jccastillo0007** [comment]
Hay que completar la especificación con los datos que faltan, en el documento no viene con los datos faltantes.

**Comment by RigoFlores** [comment]
Si viene en la spec... le cambié de nombre, ya que no solo sería nómina sino gestión de RH. Como veo que te movió el tapete, ya lo regresé a su nombre anterior
