### ISSUE TITLE
Nomina Generales - sobra la columna de % en el subsidio del IMSS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#581]
Si que sobra

**Comment by jccastillo0007** [comment]
Ok, ya la quite... la puse porque asi estaba la especificación, o asi le entendi.

**Comment by RigoFlores** [comment]
Negativo, aún aparece ahí

**Comment by jccastillo0007** [comment]
ah ya  entendi, te refieres a la tabla de subsidio al empleo... 

Ok, fixed.

**Comment by jccastillo0007** [comment]
aun muestra el nombre de la columna...

**Comment by RigoFlores** [comment]
si te refieres a la spec, esta no la muestra... si te refieres a la pantalla, aún muestra el encabezado... jeje

![subsidio al empleo](https://cloud.githubusercontent.com/assets/2912775/14517477/76afd6b4-01d3-11e6-9617-948d59eda67d.png)

**Comment by RigoFlores** [comment]
ya entendí, eso es lo que decía tu comentario precisamente, que aún muestra el nombre de la columna, es decir lo que yo le llamo el encabezado

**Comment by jccastillo0007** [comment]
listo.
