### ISSUE TITLE
Nomina Generales - coloca una coma (,) en el año

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#582]
Eso está muy raro... al menos los años que nos tocarán y todos los anteriores, nunca llevaron separador de miles... jeje

**Comment by jccastillo0007** [comment]
fixed, aunque ahora lo toma como string.

**Comment by RigoFlores** [comment]
Será conveniente listar los años, así como aparece en la contabilidad electrónica?
En este caso sería a partir del 2016 hasta el 2100, o que lo tome de una tabla y lo muestre en la lista.
