### ISSUE TITLE
Nómina Configuración - Exportar configuración

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#586]
Falta el ícono que me permita exportar la configuración actual o todas, a un excel.

OJO, aquí se tendrían 2 opciones... 
a) Configuración actual (la que se muestra en pantalla)
b) Todas (las que se tengan almacenadas).

**Comment by jccastillo0007** [comment]
a que te refieres con b) todas las que se tengan almacenadas?

Yo estoy pensando solo en la pantalla general de configuración de nómina, tu ves alguna otra, si es asi, dime la lista de los catálogos que se requiere exportar.

**Comment by RigoFlores** [comment]
Todas las almacenadas... recuerda que puedes tener una por año...

**Comment by jccastillo0007** [comment]
done.
