### ISSUE TITLE
Nomina Configuración - Eliminar las siglas de pantalla

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#587]
El único dato que si corresponde con unas siglas estándar por ley es la de:

Salario Mínimo General en el DF (SMGDF)

Las demás siglas son para uso interno, ya que se mencionan en la spec, pero para que adelante se muestren los cálculos. Realmente sería mejor, conocer el nombre de las variables, así como lo hicimos en la spec de las plantillas, para que tengamos un lenguaje común, de lo contrario si que será complicado entender los cálculos.

**Comment by jccastillo0007** [comment]
Chiaaaaa

Done.
