### ISSUE TITLE
Nomina - Sobra un dato y faltan 2

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#588]
De acuerdo a tu mismísima petición, hay que apoyarse en la spec, misma que actualicé desde hace varios días, pero no sé porque no se refleja en la pantalla:

Sobra:  
Porcentaje de excedente de 3VSMGF

Faltan: 
Número de SMGDF exentos para horas extra
Porcentaje exento horas extra

**Comment by jccastillo0007** [comment]
Listo...

Oye, encontré estos valores en el word :  
Días exentos aguinaldo (DEA): 30
Días exentos PTU (DEPTU): 15
Días exentos Prima Vacacional (DEPV): 15

No se ocupan o que petch ?

**Comment by RigoFlores** [comment]
La especificación está actualizada full, en los datos generales.
Y si los tienes en pantalla, solo que los pusiste a la mitad (no seguiste el orden), pero si aparecen en pantalla.
Si hablamos de lo mismo?

**Comment by jccastillo0007** [comment]
No sorry me confundi de variables, mas bien me refiero a estos : 

Tope 3 VSGMDF (3 veces el SMGDF).
Porcentaje de excedente de 3VSMGF: 0.40%

Están en el doc, después de la tabla de subsidio para el empleo, son los datos que mencionaste que sobran, pero están en el documento, tons ya no se.

**Comment by RigoFlores** [comment]
Mencioné que SOLO UN DATO SOBRA:

Porcentaje de excedente de 3VSMGF

Ya que ese mismo dato ya aparece en la tabla del IMSS.

**Comment by RigoFlores** [comment]
YA NO SOBRA, PERO ESTABA BIEN CLASIFICADO DENTRO DE LA TABLA DE DATOS PARA EL IMSS ESTOS 2 DATOS QUE APARECEN AFUERA DEL CUADRO:
-Tope 3 veces SMGDF
-Porcentaje de excedente de 3 VSMGDF   (que debería ser % de excedente de 3 veces SMGDF)

**Comment by jccastillo0007** [comment]
En la spec se encuentran afuera de la tabla del IMSS, por eso los saque
chiaaaaaa

Saludos.
JC.

**Comment by RigoFlores** [comment]
OK, si se puede interpretar como que está afuera... realmente es parte de los datos del IMSS, por lo que sería mas claro que estuvieran dentro del cuadro.
OJO: esos 2 datos que se mueven NO FORMAN PARTE DEL CÁLCULO DE LA SUMATORIA.
