### ISSUE TITLE
Nomina Configuracion - Cálculo incorrecto del total del porcentaje del IMSS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#589]
Dentro del cuadro del IMSS, el último dato se llama "Total del Porcentaje"

Este dato se calcula sumando todos los datos que que aparecen en pantalla, EXCEPTO EXCEPTO EXCEPTO EXCEPTO LOS 2 PRIMEROS:

a) Tope 3 Salarios Mínimos. 
b) Porcentaje para el cálculo del excedente

Esos 2 no entran en la sumatoria.

**Comment by jccastillo0007** [comment]
done.

**Comment by jccastillo0007** [comment]
aqui que falta o que?

**Comment by RigoFlores** [comment]
Wey, no se guardó mi comentario... 
Lo que está haciendo es que ya suma bien los 4 porcentajes... SOLO LA PRIMERA VEZ.... si después tu modificas alguno de ellos... ese nuevo dato lo suma al total anterior... es decir NO TOMA LOS 4 Y LOS SUMA NUEVAMENTE...esto hace que cuando modificas cualquier dato de porcentaje, el total SIEMPRE SE VA INCREMENTANDO

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
sigue igual, a menos que no hayas subido aún el nuevo rilis
