### ISSUE TITLE
Cálculo incorrecto de importe a nivel producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#59]
Falla elemental y super blocker...
El importe a nivel producto, tanto en el PDF como en el XML, lo presenta con el IVA a nivel producto.
Importe es simplemente cantidad x precio unitario.

**Comment by jccastillo0007** [comment]
fixed.

Estos son los buenos defectos de fondo no de forma .... cuando encuentres dos o tres mas, ya estaremos listos...

**Comment by RigoFlores** [comment]
wey, está peor, ahora pone 0 tanto en el pdf como en el xml..... chaaaa

**Comment by jccastillo0007** [comment]
No maaa como crees.... si lo probe bien.... seguro ?

**Comment by jccastillo0007** [comment]
fixed. 

chaaaaa
