### ISSUE TITLE
Catálogos Nómina - Generar Menú

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#590]
Se requiere generar un menú específico para los catálogos de Nómina.
Quizás no se pueda agregar a tercer nivel, pero entonces habría que buscar alguna alternativa... o de plano pasarlos a la sección de catálogos... ahí no me gustaría tanto ya que se quedarían todos los catálogos revueltos... creo que esto de nómina hay que llevarlos de manera independiente, pensando en vender proyectos de implementación de nómina.

OJO, En todos los menús se ocupan las opciones de: 
Nuevo, Consultar (lo que ya están capturados), Editar, Eliminar (con confirmación), y Exportar a excel. 
Si tenemos que priorizar, exportar a excel podría quedar al final, pero no tenemos que perderlo de vista.

**Comment by jccastillo0007** [comment]
Implemented.

**Comment by RigoFlores** [comment]
No lo veo... esto es un menú específico para agrupa todos los catálogos de nómina.

**Comment by RigoFlores** [comment]
Ah ya lo ví, lo agrupaste en configuración de la nómina
