### ISSUE TITLE
Nómina - Catálogo de Períodos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#591]
Generar catálogo de acuerdo a especificación actual (18 - abril - 2016 ), y cubriendo los estándares de todo catálogo mencionados en el issue 590, correspondiente a Catálogos de Nómina.

**Comment by jccastillo0007** [comment]
Done.

Hoy no subí release a PRU, aguanta a ma;ana a revisar este catálogo.

**Comment by jccastillo0007** [comment]
hoy si subi un release a PRU, pero este ticket esta fallando, solo revisa el otro issue que estaba en resolved.... esto del cálculo automático de periodos, esta cabron... y tengo varias dudas.. luego te las mando.

**Comment by jccastillo0007** [comment]
En que afecta el 7mo día del catálogo, en el cálculo de los días de pago?

Acaso no se pagan periodos vencidos, es decir, si es quincenal, del 1 a 15 se paga el 15 y si es semanal se paga los viernes

Dia de pago, debe tener siempre un número, y no como en tu ejemplo que dice fecha final... sería muy complicado manejar todas las opciones numéricas y alfanuméricas posibles

En realidad la fecha sugerida de pago, se me hace un tanto inútil, ya que casi siempre tendrán que cambiarla, porque caerá en fin de semana o incluso en días festivos... deberíamos quitar todo ese desmadrito...

**Comment by RigoFlores** [comment]
No te confundas...
7° día, significa que vendrá desglosado como días trabajados 6, y adicionalmente se paga el 7° día cuando se trata de un período semanal. Solo aplica para el semanal (quizás en quincenal también pudiera ser, pero es muy poco común).
El día de pago es por ejemplo 5, que si la semana empieza en lunes, entonces se pagará los viernes... la fecha que aparece ahí, se calcula a partir de la fecha de inicio de período + el día de pago... es decir si el inicio de período es 25 de abril, y el día de pago es 5... entonces esa semana se pagará el día 30 de abril...

La fecha sugerida de pago, serviría para automatizar la nómina... es decir, para que ellos no la corran, sino que en las primeras horas del día... sobre todo en web (nuestro server), que se calcule la nómina, pero que no impacte a los timbrados...
La podemos dejar a un lado por lo pronto, pero todo eso ya me estoy adelantando a lo que se tiene que llegar en un momento dado...

**Comment by jccastillo0007** [comment]
Sigo con este catálogo.... se esta poniendo interesante.

**Comment by RigoFlores** [comment]
ok

**Comment by jccastillo0007** [comment]
checa la versión que subí hoy a PRU, ya calcula el tema de fecha inicial, final y fecha de pago... que pinche desmadre para sugerir algo.

**Comment by RigoFlores** [comment]
El año debe elegirse de una lista a partir de 2016 en adelante.
El tipo también debe elegirse de una lista, de acuerdo a la spec.
El calendario de pagos se debe llenar solo, a partir de los datos capturados en el header. Por ejemplo si el primer dia del período es lunes 04 de enero...y el pago es semanal.. entonces se calculan todos números que deberían ser máximo 52 (semanas del año).
Si el tipo es quincenal, se calculan los números como 1 al 16, y 16 al último día del mes.
y así para catorcenal, decenal, mensual.

Quizás le falta el campo nombre, para que la llave de unicidad sea año-tipo-nombre.

**Comment by jccastillo0007** [comment]
El cálculo de los periodos, se controla en base al dato "dias del periodo", no en base al tipo del periodo, se va a requerir mucho mas código si se necesita entender e interpretar cada uno de los valores del tipo de periodo.

No se a que te refieres con la "llave", realmente en base de datos ya no es factible usar llaves compuestas, eso es mucho mas costoso que controlarlo por código.

Mucho desmadre para una fecha de pago sugerida.

**Comment by RigoFlores** [comment]
El tipo de período está definido por ley, de acuerdo a la spec. Por ello es que se solicita de un listado. El año, pues no se diga... ese si, de acuerdo a los últimos 2016 años, no creo que cambie en su secuencia.

Llave me refiero a que sean únicos en esa combinación de "año-tipo-nombre". El nombre lo acabo de incluir para el caso que existan 2 períodos del mismo tipo, pero con distinta configuración para un mismo año. Si se controla por código, es transparente para el usuario, entonces no le veo problema, siempre que cumpla su cometido.

Como te comentaba, podemos dejar pendiente la fecha sugerida, pero este dato estaba pensado para automatizar la emisión de nómina, ya que los datos de fecha inicial, fecha final y fecha de pago, son obligatorios de acuerdo al SAT. Entonces al momento de calcular la 'prenómina', se sugerirían estos datos al usuario, y quizás él los pueda cambiar.
Si las fechas se cambian a mano, se debe validar que no se empalmen con el número anterior, dentro del mismo período. Por ejemplo... si se pagó del 01 al 07 de mayo, pues debe validarse para ese mismo período (2016-semanal-sindicalizados), que el siguiente período sea 08 al 08 al 14 de mayo...

**Comment by RigoFlores** [comment]
Una nómina semanal, con fecha inicial 04 de enero del 2016... su período 2 iniciará el 11, luego el 18, etc... entonces, su fecha final, será un día antes del siguiente período. y la fecha de pago pudiera ser todos los viernes o sábados.

**Comment by jccastillo0007** [comment]
fixed.

Si ves otro escenario que no este calculando bien los días, me dices como lo reproduces.

Toma en cuenta que el sistema suma y resta días, pero no interpreta terminas semanales, quincenales, viernes, sábados etc...

**Comment by RigoFlores** [comment]
Falta agregar el nombre, para que en un mismo año, con un mismo tipo, se puedan definir 2 nóminas distintas.
En cuanto a las fechas inicial y final, las coloca chuecas... ahí lo que se puede garantizar es:
a) cuando es semanal... siempre el siguiente número empezará 7 días despues del inicio
b) cuando es quincenal... la primera quincena es del 1 al 15,  la segunda del 16 al fin de mes
c) cuando es catorcenal, ahí si es fijjo... fecha inicial, mas 14 siempre...
d) mensual, pues solo son 12 números, uno por mes, con fecha inicial el 01 del mes, y fecha final último día del mes..

**Comment by RigoFlores** [comment]
Si, lo anterior tomará mas tiempo, podemos ir avanzando en otros issues...
Al menos lo de agregar el nombre, si se ocupa... en la spec se maneja como ID
