### ISSUE TITLE
Nomina - Catálogo de Prestaciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#597]
Generar catálogo de acuerdo a especificación actual (18 - abril - 2016 ), y cubriendo los estándares de todo catálogo mencionados en el issue 590, correspondiente a Catálogos de Nómina.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Asumí algo que no te pedí...
Un registro completo en este catálogo es realmente una tabla.
Por ejemplo:
Nombre: Prestaciones Sindicalizados (sería la llave)
Y aquí se asocian varios registros con la información solicitada, esto es:
antigüedad, vacaciones, prima vacacional, aguinaldo, bono

Es decir, cada registro es una tabla completa que se utilizará dependiendo de cada empleado.
En una empresa pequeña, solo existirá una sola tabla. En una empresa de manufactura, generalmente existe una tabla para empleados de confianza y otra para sindicalizados (ofrecen distintas prestaciones a cada uno de ellos).

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
Como se menciona en la spec, el nombre es la llave, por lo tanto esa no se captura n veces... en el ejemplo se indica nombre: sindicalizados, y ahí si se capturan n renglones para antigüedad, días de vacaciones, prima vacacional, aguinaldo, prima antigüedad...

Como lo veo, el nombre se elige de una lista, y cuando se selecciona un nombre, aparecen todos los registros

**Comment by jccastillo0007** [comment]
Done.
