### ISSUE TITLE
DescargaMasivaCFDI - Implementar estructura de directorios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#598]
La estructura de directorios de descarga debe ser similar a la del facturaT, con algunos agregados, esto es:

RFC (cliente nuestro)\Año\Mes\Recibidas\XML
RFC (cliente nuestro)\Año\Mes\Emitidas\XML

Eventualmente cuando ya generemos el PDF, entonces se creará la correspondiente carpeta de PDF's.

Ahora ya pudiste modificar esa parte de los directorios, solo habría que completar la ruta completa.
Los requerimientos levantados respecto a la descarga masiva, son los mínimos que se ocupan para que podamos ofrecerla.

**Comment by jccastillo0007** [comment]
pssss estas viendo y no ves...  lo bueno es que estoy aprendiendo python... es muy poderoso y nos puede ayudar mucho.. sientate ..

**Comment by jccastillo0007** [comment]
ya estoy en esto....  pero la parte de generar el pdf, se har[ia con el pdfor y no con la herramienta de python... tambi[en sugiero que cerrando este ticket y el ticket de vigentes/canceladas, se  empiece a ofrecer, solo faltaría el tema de proteger el uso de la app únicamente para nuestro cliente, pero esa parte no sé aún como la voy a resolver, mientras podemos revisar que tan interesante es la app y sobre todo probar si los clientes están dispuestos a pagar por algo asi.

**Comment by jccastillo0007** [comment]
fixed.

Nada mas no puse el RFC del cliente, porque siempre será el mismo para cada cliente nuestro.... según yo no se ocupa.

**Comment by RigoFlores** [comment]
si, el RFC es por si nuestra propuesta es hasta por tantos RFC's... ahí si no lo sé como vamos a controlar finalmente este asunto.. tu dirás...
Por cierto el mes quedó como 04 en lugar de abril... no le veo problema, excepto cuando queramos integrarlo al facturat de escritorio...
