### ISSUE TITLE
Nomina - Catálogo de Tipo de Empleados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#599]
De acuerdo a spec

**Comment by jccastillo0007** [comment]
Estoy avanzando en este catálogo, se volvió un poco complejo dada la cantidad de catálogos que hay que manejar, y he visto que varios datos están duplicados en varias secciones, como departamento, salario base, salario diario integrado, etc.

Puedes revisar la Spec para asegurar que los datos pertenezcan a una sola sección.

**Comment by jccastillo0007** [comment]
Cual es la diferencia entre

Salario (campo compuesto)
Salario base
Salario base integrado
Salario diario
Salario diario integrado

**Comment by RigoFlores** [comment]
Salario diario es igual a salario base, es tu sueldo nominal, el salario diario integrado incluye lo que percibes por vacaciones y por aguinaldo y algunas otras prestaciones. Seguro de gastos médicos, etc. Con ello tu sueldo diario integrado se calcula con base a prestaciones.

**Comment by RigoFlores** [comment]
A ver, ya vi...
Lo que comentas que se repite es la sección kardex.
Ese es el histórico de los ajustes en el sueldo del empleado.
En la sección generales, se captura su sueldo actual (el último, el mas reciente). Cada ajuste (incremento, modificación) al sueldo, generará un nuevo registro en el kardex del empleado.

**Comment by RigoFlores** [comment]
Salario Base = Salario diario... , creo que podemos manejar en general 'diario', en lugar de 'base', aunque dependiendo del usuario, le cambian el nombre... por ejemplo el de RH, o el IMSS

**Comment by RigoFlores** [comment]
Una vez que tengamos todos los catálogos implementados, procederemos a los cálculos. Es decir, primero amarramos y afianzamos los catálogos, para proceder a los cálculos.

**Comment by jccastillo0007** [comment]
Cual es el catálogo de tipos de empleado ? según estoí no esta especificado.

**Comment by jccastillo0007** [comment]
mmm ya lo vi en la especificación crap, no lo he hecho ...

**Comment by jccastillo0007** [comment]
Echale un ojo a como va el catálogo de empleados... ya están casi todos los catálogos, pero la sección de Kardex me confunde mucho, debo leer con mucho cuidado la spec.

**Comment by RigoFlores** [comment]
El kardex, es el archivo histórico del empleado. Fecha de ingreso, vacaciones tomadas, fechas de incrementos de sueldo, etc.
Es precisamente la historia del empleado dentro de la empresa... por ello verás registros de sueldo repetidos, ya que junto con la fecha, registran los distintos ajustes de sueldo recibiidos

**Comment by jccastillo0007** [comment]
Listo... el kardex se moverá a una opción del menú independiente.

**Comment by jccastillo0007** [comment]
quiubo... quiubo...

**Comment by RigoFlores** [comment]
En cuanto se arreglen todos los issues, se levante le keygenerator, se atiendan todos los requerimientos, se terminen las actualizaciones, seguramente me quedará tiempo de retomar este tema..

**Comment by jccastillo0007** [comment]
Hay que chiflar y aplaudir al mismo tiempo o mas bien, caminando y miando porque hay chingo de chamba....

Mientras no este el key generator y los requerimientos, hay que probar lo que ya se tiene....

**Comment by jccastillo0007** [comment]
Aqui casual, cerrando fichas que tienen mucho tiempo de haberse resuelto.
