### ISSUE TITLE
En consultas, ya no permite obtener el pdf y xml

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#60]
Vamos como cangrejos...
En las últimas facturas que hice, ya no puedo obtener el PDF y XML desde la consulta.
Amén que el status, lo mustra como CREATED.
No me queda claro, cuándo podamos estabilizar, ya el tiempo invertido es demasiado....

**Comment by jccastillo0007** [comment]
Ya estamos muy cerca

JC@iPhone.
 Saludos.

**Comment by jccastillo0007** [comment]
Chaaaa a veces suenas como una mujer quejumbrosa.... el problema es con las facturas que no tienen serie.., estoy en este defecto.

fixed

**Comment by RigoFlores** [comment]
y lo del status apá? muestra palabras en inglés; no se que signifiquen, y menos para el usuaurio...
Cuál es el objetivo de esa columna? Que estaremos mostrando?
Si va a ser vigente, necesitamos implementar la cancelación para que valga la pena.
SI es creada, pues todas las de ahí están creadas.
Si será el status para cuentas por cobrar, entonces tenemos que platicarlo,,,,

**Comment by jccastillo0007** [comment]
yeap, es para decir si es cotizacion, cuentas por cobrar, cuentas por pagar, creada, cancelada

**Comment by jccastillo0007** [comment]
Ya se esta almacenando la cotizacion tambien, solo faltaria definir el workflow que seguiran las cotizaciones y cuentass por cobrar
