### ISSUE TITLE
eConta - No transfiere los saldos finales cuando no se ocupó la cuenta en un mes intermedio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#601]
Por ejemplo de la cuenta A, con saldo inicial en 0

a) En enero tuvo movimientos (por lo tanto su saldo final será distinto de 0, digamos saldo Y)
b) En febrero no tuvo movimientos
c) En marzo tiene movimientos, pero el saldo inicial lo toma como 0, en lugar de Y

De ahí, se hace un desajuste en todos los números.

**Comment by jccastillo0007** [comment]
ufffff , lo bueno es que ya lo encontré, era una tontería, y no se como no se cachó desde antes... hay que mejorar el proceso de pruebas.

El gran problema fue que las cuentas no utilizadas en un mes, se deben guardar de cualquier manera para arrastrar su saldo final del mes anterior, y poderlo trasladar al mes siguiente, pero la aplicación lo estaba guardando con el número de mes que si tuvo afectación y no con el mes en el cuál se estaba cerrando la balanza.

Por eso, al cerrar febrero, algunas cuentas se duplicaban en enero y desaparecían en febrero.

**Comment by RigoFlores** [comment]
en pruebas, entre otras di de alta las cuentas bancomer e inbursa, AMBAS CON SALDO INICIAL
En enero ocupé inbursa, pero no bancomer.
En febrero al contrario... solo que en febrero, el saldo inicial de bancomer fue 0.... es decir no transfirió el saldo inicial del catálogo de cuentas, ya que era la primera vez que se iba a ocupar dicha cuenta, por lo tanto su saldo inicial se toma del catálogo de cuentas.

**Comment by jccastillo0007** [comment]
ahi wey.... este si no estuvo sencillo, el comportamiento es diferente cuando inician en saldo = 0 o con saldo != 0 y además no son utilizados en meses anteriores.

Checale en PRU, si todo funciona, tengo todo listo para activar esta versión en PRO (sin mostrar lo que llevamos de la configuración de nómina).

**Comment by RigoFlores** [comment]
Sigue sin jalar completamente...
En pruebas, ocupé la cuenta inbursa en enero y marzo....
para marzo su saldo inicial lo tomó del saldo inicial en el catálogo de cuentas, pero no el final de enero...
Lo que hay que hacer, es tomar los saldos finales de todas las cuentas, y transferirlos como iniciales del siguiente mes.... es muy complicado eso???
Según yo, lo que hace falta es tener en el catálogo de cuentas, un campo para saldo de inicio (al momento de dar de alta la cuenta), y luego otros 2 campos para el saldo inicial y final... que correspondería a la última balanza cerrada... no se puede solucionar algo así... es que cada prueba toma 3 días, y no queda... y el cliente sigue esperando por este detalle...

**Comment by jccastillo0007** [comment]
no es tan sencillo, ya que cuando una cuenta no se ocupa en un mes específico, no sufre cambios... y luego al siguiente mes hay que detectar cuando fue la última vez que se ocupo la cuenta.

Lo que si ayudaría, es que se definan todos los escenarios de prueba, para que pueda validar que se arregló en todos los casos, pero esos 3 días que dices, son también porque siempre reportas un escenario cada día, en lugar de tener claro el requerimiento completo y los escenarios de prueba completos...  hay que detectar los escenario a tiempo, el proceso de pruebas es parte del desarrollo de software, y si toma 3 días es por eso también, por cierto, de acuerdo a lo que vi en el código y que estoy validando y arreglando, me doy cuenta que estos escenarios nunca habían sido probados....

**Comment by RigoFlores** [comment]
OJO, este no es un escenario nuevo.... si te das cuenta, es el mismíto (ocupo en enero, no ocupo en febrero, vuelvo a ocupar en marzo).. solo que ahora, se comportó distinto después del cambio.
Yo creo que todas las cuentas siempre deben pasar su saldo inicial + abonos - cargos (bueno, dependiendo la naturaleza de la cuenta), al saldo final cuando se cierra...así sería irrelevante si se ocupa o nó... y finalmente el saldo final, será el inicial del siguiente período... así está documentado desde hace tiempo en otro issue.

**Comment by jccastillo0007** [comment]
Pues el defecto no habia sido identificando, y yo no he arreglado ning[un defecto hasta ahora, mas bien, estoy implementando mas validaciones y mas casos de uso.

Checale en PRU, ya esta listo, haber que otro escenario encuentras.

**Comment by RigoFlores** [comment]
EL CASO DE USO ES EL MISMO QUE EL INICIAL... Y EN GENERAL, QUE SE TRATA DE TRANSFERIR EL SALDO FINAL AL MOMENTO DEL CIERRE, AL SALDO FINAL DEL SIGUIENTE PERÍODO

QUIZÁS LO QUE HA CONFUNDIDO, ES QUE SE CORRIGE ALGO, ENTONCES SE CONTINUA LA PRUEBA Y SURGE OTRA COSA... COMO RESULTADO QUE ANTERIORMENTE NO SE HABÍA LLEGADO TAN LEJOS

PERO NADA...AL PARECER YA QUEDÓ... HICE VARIAS PRUEBAS, Y YO LO VI BIEN... AHORA HAY QUE CORRERLO CON LAS PÓLIZAS DEL CLIENTE EN PRODUCCIÓN....
