### ISSUE TITLE
eConta - cuando cierras balanza de un mes, desaparecen cuentas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#602]
Volviendo al ejemplo que algunas cuentas tuvieron movimiento en enero, pero NO EN FEBRERO... si antes de cerrar la balanza de febrero consultas, aparece todo muy bien... después que cierras, febrero ya no aparecen las cuentas que no tuvieron movimiento.

Si es mas simple incluir siempre toooodas las cuentas que se 'vayan moviendo', en la balanza pues lo podemos hacer... ya que antes de cerrar si aparece todo bien, pero al momento del cierre desaparecen las que no tuvieron movimiento.

**Comment by jccastillo0007** [comment]
ufffff , lo bueno es que ya lo encontré, era una tontería, y no se como no se cachó desde antes... hay que mejorar el proceso de pruebas.

El gran problema fue que las cuentas no utilizadas en un mes, se deben guardar de cualquier manera para arrastrar su saldo final del mes anterior, y poderlo trasladar al mes siguiente, pero la aplicación lo estaba guardando con el número de mes que si tuvo afectación y no con el mes en el cuál se estaba cerrando la balanza.

Por eso, al cerrar febrero, algunas cuentas se duplicaban en enero y desaparecían en febrero.
