### ISSUE TITLE
eConta - repite cuentas en balanza de enero que ya está cerrada

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#603]
El cliente ELE961009FI3 cerró su balanza de enero y todo bien... pero si la consultas, está repitiendo cuentas, y aparecen unos saldos iniciales distintos de cero, siendo que en enero, todo empezó con saldo inicial cero para toooodas las cuentas...

**Comment by jccastillo0007** [comment]
ufffff , lo bueno es que ya lo encontré, era una tontería, y no se como no se cachó desde antes... hay que mejorar el proceso de pruebas.

El gran problema fue que las cuentas no utilizadas en un mes, se deben guardar de cualquier manera para arrastrar su saldo final del mes anterior, y poderlo trasladar al mes siguiente, pero la aplicación lo estaba guardando con el número de mes que si tuvo afectación y no con el mes en el cuál se estaba cerrando la balanza.

Por eso, al cerrar febrero, algunas cuentas se duplicaban en enero y desaparecían en febrero.
