### ISSUE TITLE
DescargaMasiva - Proteger para que solo el dueño de llave pueda descargar XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#606]
Así como el facturat de escritorio.
Solo el dueño de la llave, podrá descargar emitidas o recibidas

**Comment by jccastillo0007** [comment]
Ok, ero hay que empezar a ofrecerlo, para validar el interes sobre la app, capaz que no pega y ya le hemos invertido un buen

**Comment by RigoFlores** [comment]
Una implementación, sería borrar los XML con emisor o receptor distinto de nuestro cliente, no se puede eso mas o menos simple?

**Comment by RigoFlores** [comment]
La pantalla principal, solicita el RFC... la implementación real sería quitar ese campo y que en automático tome el de una llave o equivalente. También eliminar las pestañas que no estamos ocupando.
De hecho como datos de entrada se ocupa la clave ciec, el directorio de descarga, emitidas o recibidas, mes y año.
Eventualmente se podría elegir el día, para el caso que sean mas de 500 facturas en el año.
Estos puntos, están realmente complicados? Es quitar menús, controles y leer una llave.

**Comment by jccastillo0007** [comment]
Pues justo hoy estuve trabajando en eso en la oficina, y logre resolver las dudas que tenía con respecto a Python.... así que hoy si tengo avance en ese sentido... siéntate a probarlo... te ib a a dar la sorpresa de ese avance... pero me ganaste con tu comentario anterior.

Aunque sea quitar menus y campos, no es tan fácil y no por python si no por entender como esta hecho la app.... pero ya lo resolví, lo de leer la llave, eso no se podrá ya que la llave que generamos tiene varios trucos de encoding para distraer al enemigo, y no sé como hacer eso en python, pero hay otra forma de resolver este requerimiento, te lo voy a mandar por correo.

**Comment by jccastillo0007** [comment]
Modifique los fuentes de python en la oficina, y me los mandé por correo, pero creo que me faltaron algunos porque no me funciona aqui en la casa, mañana te mando la actualización.

**Comment by jccastillo0007** [comment]
ya subí otra versión de esta aplicación, ya se eliminaron los menús de más y los campos que no se deben capturar. En el folder ui hay un archivo config.ini donde están los datos necesarios para que funcione la app, este archivo vendría a sustituir el archivo .key de facturat, solo que no esta encriptada.

Yo soy mas de la idea de integrar el pdftor a facturat, para que sea mas amigable el hecho de generar los PDF y el archivo csv.

**Comment by RigoFlores** [comment]
Yo no tengo problema por incluir el PDFor a Facturat, de hecho es algo que he preguntado desde hace mucho y apenas leo esta propuesta.
Yo soy de la idea que también desde ahí se invoque al descargaXML-T. Ahí ya se conoce el rfc de nuestro cliente. Ya solo habría que pedir la clave CIEC en la pantalla de configuración y toda la estructura de directorios ya se tiene, excepto que se tendría que agregar la carpeta de recibidos y emitidos, ya que aunque podrían ser nuestros clientes emisores de facturas, igual y solo nos contratan el descargaXML-T.

**Comment by jccastillo0007** [comment]
toma en cuenta que hasta este momento no se comunican java y python, solo seria mandar ejecutar el descargaXML-T desde facturat e integrar el pdfor a facturat también.

**Comment by RigoFlores** [comment]
Eso exactamente es lo que pido.
Implica instalar el descargaXML-T, independiente al Factura-T, y a su vez el Factura-T, debe incluir la funcionalidad del PDFor.

**Comment by jccastillo0007** [comment]
Ya subi el setup.py ( que es el instalador original del piton.. ... ah no, mas bien del descargaXML-T...

Pregunta.
DescargaXML-T será el nombre oficial? para ponerlo en la aplicación.... a mi si me gusta...
Hoy genero la funcionalidad para que facturat dispare el descargaxml-t.... 

Y sigo trabajando en incluir lo del pdfor en facturat standalone... pero podemos cerrar este ticket y abrir otro.

**Comment by RigoFlores** [comment]
Pues si, así hay que bautizarlo... descargaXML-T

**Comment by RigoFlores** [comment]
Ya me pidieron el demo, me gustaría mostrar así como quedaría o lo mas parecido a la versión final...

OK, este issue lo cerramos cuando ya esté protegida la llave o como?
Ahora está en un config, que cualquier puede editar y cambiarlo.

**Comment by jccastillo0007** [comment]
mmmm no lo creo... manejar el mismo formato de llave que facturat, me va a llevar tiempo.

Yo digo que lo dejemos así, y vemos que tanto éxito tiene.

**Comment by jccastillo0007** [comment]
Esta bien si pongo un botón en la pantalla de consutlas, que diga DescargaXML-T ?

**Comment by jccastillo0007** [comment]
Oye, estoy integrando el PDFor en FacturaT,  estoy pensando que sería mejor que el DescargaXML-T dejara todos los XML en un solo directorio, y al momento de crear el PDF, entonces los muevo a cada una de las carpetas que les corresponda de acuerdo al mes, como ves ?

**Comment by RigoFlores** [comment]
Si, aunque podría presentarse el escenario, que el cliente solo quiere descargar los XML y no generar el PDF. Eso no lo sé. Bajo esta situación los XML no le crearía una carpeta para identificarlos mes a mes.

Porque no empatar la estructura de directorios, con lo que ya maneja el Factura-T de escritorio.
Solo hay que agregar al final una carpeta que diga emitidas, recibidas.
Hoy otro cliente me preguntó de la herramienta.

**Comment by jccastillo0007** [comment]
el problema es que en Python, los meses los maneja con número y no con letra, y no sé como cambiarlo, y a facturat no le quiero agregar las carpetas de emitidas y recibidas porque le puedo pegar a un chingo de cosas que suceden con los paths, 

Yo creo que la opción que propongo resuelve la mayoría de los escenarios 90% de las necesidades, ya luego revisamos los casos específicos,  incluso si un cliente no quiere el pdf, le dices que los genere para que se acomoden los XML y no pele o borre los PDF.

**Comment by RigoFlores** [comment]
Esas soluciones de pedir al cliente hacer algo que no se ocupará, es algo pro o chacarrón??
Pero bueno, como veas... yo lo veo muy simple, pero creo que nos estamos complicando mucho.
Y precisamente a todo esto me refería con la integración que no se atendió con anterioridad.

Pero nada, yo solo necesito CONOCER COMO VA A QUEDAR FINALMENTE, aunque le tenga que decir al cliente que haga algo que no ocupará...  tengo clientes esperando la respuesta...

**Comment by jccastillo0007** [comment]
ok, asi lo haré.

Solo debes decirle al cliente como funciona la solución, como se usa, y ellos decidiran que si usan y que no..

**Comment by jccastillo0007** [comment]
en el release de hoy de facturat, agregué un botón en la pantalla de consulta de facturas, (hasta abajo), al presionar ese botón intenta ejecutar el archivo DescargaXML-T.bat que debes copiar del dropbox (en el folder DescargaT) y ponerlo en el folder donde levantas facturat

Ese archivo DescargaXML-T hay que editarlos para actualizar los paths que ahi vienen, basicamente en donde esta instalado python (si ya esta en el path, ahi solo se requiere poner python.exe) y hay que actualizar el path donde se encuentra la app de python de DescargaXML-T

Por cierto, subí otra versión de DescargaXML-T, donde le actualicé el nombre de la app, hay que bajar ese nuevo zip.

Igual y hay usar teamviewer para explicar mejor el setup y que quede claro mas rápido.

**Comment by RigoFlores** [comment]
Ya levantó desde el Factura-T.
Preguntas:
a) cuando le das click en descargarXML-T, hay manera de que el botón se inhiba o algo para no volver a levantarlo n veces? Ahora mismo, lo puedes levantar n veces. O un delay de unos 20 seg.
b) Entiendo que solo se invoca al .bat. No se puede configurar que sea modal, de tal manera que si cierras facturat, también se cierre la otra aplicación.
c) cuando invocas al XML, se podría generar 'on the fly' el archivo de configuración donde se capturan los datos de la clave ciec, rutas, y rfc de nuestro cliente?. Sería la manera mas chacarrona de TRATAR de garantizar que no trabajen con otro rfc, pero al menos protegería un poco.
d) Si el archivo de configuración no existe, no debería levantar el descargaXML-T
e) Los datos de acceso en el descargaXML-T, deberían ser de solo lectura.

**Comment by jccastillo0007** [comment]
Respuestas.
a. creo que si por un tiempo finito

b. noup, son procesos independientes

c. la idea es mas bien que nosotros generemos ese archivo, sin que el cliente sepa que existe, y darle al cliente la app ya configurada

d. negativo, la naturaleza de la app es permitir que esos datos se capturen, pero eliminé esos datos de la interfaz gráfica, tal vez puedo validarlo desde java antes de invocar al bat, pero si hacemos el punto anterior, no le veo el caso

e. negativo, misma razon del punto anterior, esos permisos tal vez se los podamos dar nosotros, pero la verdad es que lo podrían cambiar, tal vez podemos hacer una validación de checar el checksum del archivo, ya que si se cambia el archivo en algo mínimo, el checksum sería diferente

JC.

**Comment by RigoFlores** [comment]
OK, entonces me voy por el tema de poner oculto el archivo y escondido... ahora mismo se ubica en una carpeta que se llama configuracion, y el archivo se llama abremeymodificame.dummy
Tenemos que ocultarlo un poco, y me late lo de validar el checksum de alguna manera.

**Comment by jccastillo0007** [comment]
Subi un nuevo release del DescargaXML-T, donde los archivo descargados ya los deja en una sola carpeta, ya que se bajen, de esa carpeta entra en acción el PDFor que ya esta en la versión standalone para generar los PDF y moverlos a las carpetas correspondientes.
También subí una imagen en el folder de DescargaT, que se llama "Donde instalar el descargat.png" para que veas donde se propone que se instale.

Me faltó validar como funciona cuando son XML recibidos y emitidos ....

**Comment by jccastillo0007** [comment]
Too much time as resolved

**Comment by RigoFlores** [comment]
Pues ando hasta la madre de chamba, ramiro va adelantar su salida, estoy capacitando, dando soporte, cotizando, probando, un chingo de cosas... ni siquiera estoy saliendo a comer... ni pedo, si lo cierras, ya habrá tiempo de probarlo en cuanto haya oportunidad

**Comment by RigoFlores** [comment]
OK, lo instalé en la carpeta que se indica en la imagen, lo cual está chueco según yo.
Lo que entendí, es que se instala 'debajo' de la carpeta Factura-T.
El bat que se ejecuta debe estar en la carpeta de descargaT, y no en la de facturaT, como indica la imagen, es correcto esto que comento?
La otra que no encontré, es porque se tiene que instalar en esa carpeta, si finalmente existe un archivo donde configuras las rutas? 
Me comentas...?

**Comment by RigoFlores** [comment]
Medio lo eché a andar. 
En la configuración indica directorio para generacion de PDF. Realmente es el directorio origen para tomar los XML. Es el famoso directorio único que le llamas.
Ahora, si está tomando los XML, y los envía a la carpeta de mes año, pero no está distinguiendo que sean recibidas o emitidas.

**Comment by RigoFlores** [comment]
La opción de generar PDF a partir del XML, se encuentra en la pantalla de la configuración, cuando debería estar en las consultas de recibidos, que no?

**Comment by RigoFlores** [comment]
Hice la consultas de recibidos, y no me presentó ningún resultado, aunque se habían ya procesado los XML recibidos.
Total que no me queda claro como se supone que debe funcionar la integración de todo.

**Comment by jccastillo0007** [comment]
1. Se debe instalar en la carpeta donde se instale el facturat, independientemente del nombre que le pongan, debe estar a esa altura, en mi caso dicha carpeta se llama solo FacturaT
2. El archivo DescargaXML-T.bat efectivamente debe estar dentro de la carpeta DescargaT
3. El descargat se debe instalar dentro de la carpeta FacturaT, para que cuando lo levanten en la pantalla de consultas de facturas, se pueda ejecutar directamente, la idea es que el cliente NO ejecute el bat de descargat directamente, si no a traves de facturat
4. La carpeta del descargat se debe llamar DescargaT, para que funcione la ejecución automática
5. Si me falta guardar los archivos como emitidos o recibidos, lo que normalmente tienen los usuarios en las carpetas de año/mes son los emitidos, entonces solo voy a crear carpeta especial para los recibidos
6. Lo del nombre y ubicación de la opción para generar  los PDFs, pues no había nada definido, pensé que ahi sería un buen lugar
7. El PDFor que esta integrado al FacturaT, actualmente solo genera los PDF a partir de los XML, pero no los ingresa a la base de datos como recibidos, esto también faltaría.

Total que al parecer me falta concluir los puntos 5 y 7, además de que definas el punto 6

Subí otro release de facturat standalone y de descargat para arreglar el tema del bat mencionado en el punto 2.

Nota. En el zip de DescargaT, el archivo DescargaXML-T.bat tiene el path de donde se encuentra instalado python, eso no es necesario si se encuentra bien configurado el path con la carpeta de donde se instaló python.

(También subí un nuevo release de eFacturaT a PRU, con avances del catálogo de empleados y tipo de empleado, aunque esto es de otro ticket, pero pa que sepas.).

**Comment by jccastillo0007** [comment]
ya esta listo el punto 5.

**Comment by jccastillo0007** [comment]
ya esta listo el punto 7, solo almacena los recibidos, los emitidos no los procesa dado que fueron ya emitidos por facturat.

Solo falta definir el punto 6, no se si deba ir en la opción de recibidos, ya que por medio del descargat se pueden obtener también los emitidos.

**Comment by RigoFlores** [comment]
No noté ningún cambio respecto a mi prueba anterior. Tomé la última versión del drotbots.
Si levante el descargat, si genera los PDF pero los deja en la misma carpeta de las emitidas.
Los XML, los deja en el mismo directorio donde los dejó el DescargaT
En consultas de recibidos no presenta nada, aún después de procesados.

**Comment by jccastillo0007** [comment]
mmmm entonces no estas usando la última versión que subí, ya que la creación del folder Recibidos esta confirmada

**Comment by RigoFlores** [comment]
Como lo comenté, tomé la versión del DescargaT con fecha del 26 de enero.
Y tomé la versión 10.0.3 del facturat, cuyo jar tiene fecha del 29 de junio, 11:28 pm
Es lo que tengo, si alguna versión mas reciente hay que subirla al drotsbots

**Comment by jccastillo0007** [comment]
Pues algo anda mal, con frecuencia no toma los cambios que instalas, no
tendrás algo configurado de más en tu path o classpath.

JC.

Saludos.
JC.

**Comment by jccastillo0007** [comment]
La última versión del DescargaT es del 26 de Junio chiaaaaa y toma la última versión de facturat.

**Comment by RigoFlores** [comment]
Jajaja... la cagué, dije enero en lugar de junio... es decir si probé con la última versión del descargat, y del facturat, ni se diga, casi diario la actualizo...
Echale un vistazo al descargat, hay que asegurar que realmente sea la versión que dices que jala de todo a todo, pero en mi máquina no...

**Comment by jccastillo0007** [comment]
El descargat solo deja todos los XML en una sola carpeta.

el proceso que reparte los PDF en sus respectivas carpetas y además agrega la carpeta de recibidos, es el facturat... no el descargat... 

Hoy en la noche voy a volver a correrlo... pero estoy seguro que funciona, el problema puede estar en tu path o classpath.

**Comment by jccastillo0007** [comment]
acabo de probar este proceso, y funciona correctamente, distribuyendo los XML al directorio adecuado y los recibidos debajo de la carpeta adecuada, hay algo mal en tu ambiente.

**Comment by RigoFlores** [comment]
No era ambiente, era falta de comunicación... jeje
