### ISSUE TITLE
Agregar variables en Web y Escritorio a nivel producto producto producto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#607]
precioUCD: precio unitario menos descuento
importeCD: es igual a cantidad x precio unitario incluyendo descuento.

Ejemplo: cantidad 3, precio unitario: 100.00, descuento 20%
entonces:
precioUCD=80
importeCD=240

se trata de AGREGAR AGREGAR AGREGAR, las demás variables las dejamos tal cuál están ahora mismo. Estas variables se tienen que enviar al PDF (jasper).
Lo esperan sobre todo para web.

**Comment by jccastillo0007** [comment]
Según yo, ya se envían esos datos.... no estaremos duplicando ?

Saludos.
JC.

**Comment by RigoFlores** [comment]
Hay unas variables que son similares, pero a nivel general... esas seguro si ya las tenemos.
Si crees que ya las tenemos a nivel producto también, pásame sus nombres pls...

**Comment by jccastillo0007** [comment]
Ok, no existían a nivel producto, de hecho el descuento no se estaba enviando a jasper (a nivel producto), ya hice estas modificaciones en PRU, avisame si todo esta ok para subirlo a pro.

**Comment by RigoFlores** [comment]
Ya envía las 2 variables.
Solo que el valor de importeCD, lo envia incorrectamente, ya que es igual a importe.

**Comment by jccastillo0007** [comment]
listo... tuve que hacer algunas maniobras ya que el descuento llega en cantidad no en porcentaje...

**Comment by RigoFlores** [comment]
ok... listo... a pro...!!!!
