### ISSUE TITLE
Uso de git

### ISSUE THREAD

**Issue by aaroncadillac** [jccastillo0007/eFacturaT#608]
Sabes si se le puede instalar git en neubox???

**Comment by jccastillo0007** [comment]
mmmmm, la respuesta corta sería si, pero, no vería porque hacerlo en neubox, ya que es un hospedaje de app web, y la renta de un servidor dedicado ahi costaría mas que en digital ocean.

**Comment by RigoFlores** [comment]
no entendí que pexcado?

**Comment by aaroncadillac** [comment]
No pues si está cañon el asunto, seguiremos usando github, aunque haya que pagar por los repos privados :(
