### ISSUE TITLE
Implementar timbrador con addenda facturaT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#609]
Se ocupa implementar el timbrador tal cual está ahora mismo, pero con la addenda facturat, es decir que se tomen los datos de la addenda y se envíen como datos extra al PDF.

Por cierto, no pude acceder al xsd de la addenda

**Comment by jccastillo0007** [comment]
El xsd de la addenda no esta público, por eso no pudiste acceder...

El timbrador es el de standalone verdad ? porque en web es el addendador cierto?

**Comment by RigoFlores** [comment]
Si, el timbrador es escritorio...
En el correo que te envié, te comento que faltan 2 campos de llenar.. que son el número (supongo el número de dato extra), así como la etiqueta (para conocer a que se refiere el dato extra)...
Según yo no los está llenando la addenda desde el carta porte actual.

**Comment by jccastillo0007** [comment]
Pues no, no se estaba enviando esa información y de hecho la agrupación de cada producto con sus datos extras, estaba incorrecto también, se nota que no se probó esta addenda correctamente.

No esta tan rápido hacer el proceso inverso, de la addenda en el xml, leearla interpretarla y enviarlo al PDF.... lo voy a trabajar ma;ana para que lo pruebes el lunes.

**Comment by RigoFlores** [comment]
Ya ví la historia... fue cuando cerraste issue no puros tanantes; aquí los resultados.
En esa historia, insistía que la información complementaria a nivel producto, se incluyera en la addenda.
También insistía que para toda factura que incluya información complementaria, datos extra producto o general, debería generarse la addenda. Y el caso de uso es precisamente, este que estamos trabajando (también en la historia se menciona), que es interpretar los datos extra generales, producto y complementaria... para enviarlos al PDF.
Total que AÚN NO LE RESPONDO AL CLIENTE QUE YA HIZO SU IMPLEMENTACIÓN CHUECA, de cómo debe ir finalmente la información

**Comment by jccastillo0007** [comment]
Preguntas.

Los datos de la addenda facturat, se mandan al pdf como datos extras ?,  esto quiere decir que se mandan los valores, de cada dato extra, pero no el nombre y la posición, lo cuál me dejó pensando como es que esperas dichos datos extras en el jasper.... 

Además se estan enviando solo los datos extras a nivel header, y no a nivel detalle.

Tal vez algo no he entendido o yo no veo algo que tu si.

En la vesión que subí al jasper, ya se están enviando los datos extras del header (solo el valor)

Checale...

**Comment by RigoFlores** [comment]
El nombre del dato, es para identificar a qué dato corresponde cuando leas la addenda.
El número de dato, es para que TU IDENTIFIQUES DE QUE DATO EXTRA SE TRATA y así lo envíes al PDF (es posible que no vengan consecutivos, entonces para ello es el número de dato).
El valor, es precisamente lo único que se ocupa en el Japser, pero tiene que estar identificado como datoExtra1=valor, datoExtra2=valor2, etc. Eso te lo indicará el número de dato.

Finalmente, los datos extra a nivel producto, no se envían en esta ocasión, pero habrá otras implementaciones que si lo ocupan, así que aplica algo similar a los datos extra generales, que no?

**Comment by jccastillo0007** [comment]
El nombre del dato no lo uso.
El número de dato, es intrapiernoso para mi, yo leo los datos en el orden en el que se encuentran y asi los mando,
El Valor, es lo que se manda al jasper

Luego entonces, este razocinio me da la razón cuando mencioné que no era necesaria la posicíon, a menos que quieras que la mande a jasper.

**Comment by RigoFlores** [comment]
El nombre de dato, lo usamos nosotros (facturat), para validar que los datos que se envían en el XML, corresponden correctamente en el PDF.
El número de dato, es para el caso que envíen el dato 1, 4, 6 y 9, es decir que por la razón que sea, no ocupen los datos 2,3,5,7 y 8.
Valor se manda al Jasper.
No, no ocupamos la posición al jasper, pero cuando los datos extras no vengan completos, nos servirá para que TU IDENTIFIQUES CUÁL DATO EXTRA SE ESTARÁ ENVIANDO AL JASPER.

Lo veo muy claro, pero no entiendo porque tanto rollo.

**Comment by jccastillo0007** [comment]
yo no lo veo tan claro, pero igual no entiendo tu punto de vista, en lo practico, no uso nada mas que el valor, pero si tu lo ves bien, entonces yo estoy bien

Entiendo entonces que este requerimeinto ya esta listo, cierto ?

**Comment by RigoFlores** [comment]
Nada mas que quede claro, si en algún momento el cliente no ocupa un dato extra y se lo brinca, entonces no debe enviarse consecutivos los datos extra. Eso te debe servir a tí. Y A MI, SI ME SIRVE LA DESCRIPCIÓN DEL VALOR, para saber que si están enviando y que no.

BTW, en escritorio en lugar de posición, llega la descripción repetida (no el valor, la descripción)

**Comment by jccastillo0007** [comment]
mmmm no funciona asi, la app no se pone a revisar cuantos datos extras mandaron, y si fueron 10 por ejemplo, no se pone a revisar que vayan en orden 1, 2, 3, 4 ...10, y mucho menos que si falta el 5, entonces le respete su lugar o algo asi... si falta el 5 o alguno otro, simplemente mandará los 9 que si llegaron... y asi...

debes indicarle al cliente que mande los datos extras necesarios, de acuerdo a lo que tu necesitas en el jasper, si por alguna razón no lo hace así , no es responsabilidad de nosotros, ya que nosotros no estamos agregando la addenda si no ellos.

Hoy checo lo de la descripción en lugar de la posición

**Comment by jccastillo0007** [comment]
Te voy a mandar por correo, un ejemplo que acabo de correr para probar el manejo de la creación de la addenda facturat y el envio de los valores a jasper

**Comment by jccastillo0007** [comment]
asegurate de usar la version FacturaT_9.1.22, hoy subo otra versión que dispara el DescargaXML-T

**Comment by RigoFlores** [comment]
Pregunta, ellos tienen algo que hacer con el schemalocation o con el xsd???
Recordar que ellos solo tomaron la estructura de la addenda, como texto plano (tal cual se las envié), y modificarán la data necesaria.
¿Con eso es suficiente?

**Comment by jccastillo0007** [comment]
en lo que les enviaste viene el schema location ?
Se supone les debes enviar un XML ya con la addenda facturat, ahi se ve el schema location.... 
Espero que no vayan a crear la addenda a manita como si fuera un archivo de texto, mas bien deben usar algo crear XML's cierto ? no me espantes

Y noup, no tendrían que hacer algo diferente, solo poner el schema location de manera natural, como en un XML creado por nosotros.

**Comment by RigoFlores** [comment]
Si, les envié todo completo (incluyendo el schema location).
De hecho, ya me enviaron un ejemplo de como quedó firnalmente, y el timbrador lo procesó correctamente.
No sé como están construyendo la addenda, pero si contiene todo lo que les pedí... de acuerdo a los últimos cambios.
