### ISSUE TITLE
Ordenar las listas lexicográficamente (ok alfabéticamente)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#61]
Ordenar todos los listados de la aplicación.

**Comment by jccastillo0007** [comment]
Clientes 
Products (por nombre)
Unidades

Son las que me encontre por ahora, avisame si requieres alguna otra.

**Comment by jccastillo0007** [comment]
so what ???

**Comment by RigoFlores** [comment]
wey no mames, esta chingadera no se que le pasa, pero es la tercera vez que tengo que captura y volver a probar para recordar.... ahora si, ya no me está latiendo esta madre....

**Comment by RigoFlores** [comment]
A ver primero en la pantalla de catálogos

-Productos les falta poder ordenar por id. Esta lista que falta, también debe ser ordenada durante su despliegue.
-Clientes les falta poder ordenar por nombre o razón social. Igualmente se debe ordenar.

En la pantalla de facturas, 
cuando buscas el cliente por nombre o razón social, no presenta la lista ordenada.
cuando buscas el producto por id, no presenta la lista ordenada.

Es la última vez que capturo y vuelvo a probar lo mismo.

**Comment by jccastillo0007** [comment]
chaaaa que reinita...

**Comment by jccastillo0007** [comment]
Esto ya esta : 

En la pantalla de facturas, 
cuando buscas el cliente por nombre o razón social, no presenta la lista ordenada.
cuando buscas el producto por id, no presenta la lista ordenada.

Esto aun falta:

Productos les falta poder ordenar por id. Esta lista que falta, también debe ser ordenada durante su despliegue.
-Clientes les falta poder ordenar por nombre o razón social. Igualmente se debe ordenar.

**Comment by RigoFlores** [comment]
Ya quedó en todos lados, excepto que omití comentar en consultas.
Ya ordena por RFC, y solo falta ordenar por nombre o razón social

**Comment by jccastillo0007** [comment]
Fixed.
