### ISSUE TITLE
No está enviando el XML al momento de generar las facturas desde el web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#610]
ya te envié los correos que llegan incompletos... solo llega el PDF.
Ayer generamos un carta porte en producción, y en este caso no llegó el correo cuando se emitió, y tampoco lo reenvió... estuvo mas crítico aún.

Total, que este es un issue importante que no sé a cuantos clientes esté afectando.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Creo que quedó para carta porte traslado, pero no para carta porte ingreso.
Ahí aún no lo envía; te envié un correo con evidencia.

**Comment by jccastillo0007** [comment]
Crap.... lo que si te puedo asegurar, es que nunca antes lo había enviado con carta porte - ingreso, lo que significa que no es usada.... pero nada, hoy le agrego ese tipo de documento.

**Comment by RigoFlores** [comment]
Lo de carta de porte - ingreso, lo acabas de subir la semana pasada. Estoy seguro que antes no se enviaba.. jejeje.
A partir de que se subió, algunos clientes empezaron a utilizarla, aún sin la actualización (cabrones). 

En resumen, esto es nuevo y no está enviando el XML cuando es carta porte ingreso.
Supongo que hay que aplicar el mismo correctivo que se hizo para el carta porte de traslado

**Comment by jccastillo0007** [comment]
yeap

**Comment by jccastillo0007** [comment]
Listo, en PRU, este supongo no es tan tan tan urgente llevarlo a PRO

**Comment by RigoFlores** [comment]
Si, es muy muy muy urgente, ya que el primer reporte de este comportamiento ya tiene mas de una semana.... entonces ellos tienen que estar reenviando manualmente sus facturas. Para propósitos de eficiencia, es retrabajo y están emputados.
Pinches clientes ocupan el carta de porte ingreso, pero no han pagado actualización.
Hay forma de poner un candado?

**Comment by jccastillo0007** [comment]
ok, tons lo subo a PRO... ahora mismo.

La única manera de protegerlo es con el plugin de carta porte, el cuál incluiría tanto carta porte traslado e ingreso.
