### ISSUE TITLE
Enviar por correo XML Y PDF generados desde el Timbrador

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#611]
Dentro de los datos extra de la addenda Factura-T, y en conjunto con el  timbrador... existe uno que enviarán, donde incluirán el correo del receptor para que se envié en automático.
Me parece que independientemente del dato extra que se trate, SIEMPRE QUE LA DESCRIPCIÓN DEL DATO SEA **correoReceptor** (que es el nombre de nuestra variable en el PDF)... se tome como el correo del receptor, uno o varias direcciones de correo separadas por ';', para que una vez timbrado y generado el PDF, se envíe por correo.

**Comment by jccastillo0007** [comment]
mmmm no me agrada la idea de tener que analizar los datos extras del xml por medio del timbrador... vamos a empezar con customizaciones a la medida ....

**Comment by RigoFlores** [comment]
ok, cuál sería otra propuesta para enviar desde el timbrador a un destinatario de correo.
Yo pienso que la addenda facturat está mas que puesta para ello...

**Comment by jccastillo0007** [comment]
una vez timbrada la factura, en las consultas se pueden reenviar por email... ese es el procedimiento est[andar para reenvío de facturas...

**Comment by RigoFlores** [comment]
El timbrador se ocupa como el conector, o como el web service... es decir es ciego... si no tuviera interfase quizás no afectaría.
Lo que se busca es un procedimiento automático para el envío de los correos. Ellos no consultan pantallas de facturat.
Entonces, dentro de la addenda, podría ir un parámetro o atributo que se llame correoEmisor.
Es decir, ya no como dato extra, sino como parte del header de la addenda.

De hecho tenemos mecanismo para desde el conector enviar en automático los correos, lo que no tenemos es en el timbrador.

**Comment by jccastillo0007** [comment]
ok, tomemoslo de un dato del header, como dices correoEmisor, y esa funcionalidad la puedes ofrecer a quienes estén interesados, ya que se aplicará siempre y no solo para etse cliente.

De acuerdo?

**Comment by RigoFlores** [comment]
Si, ya solo ocuparía un ejemplo de como quedaría la addenda ya al final, para enviársela al cliente como ejemplo.
Y si, sería para algo general, para todos aquellos clientes que ocupen timbrador y quieran enviar por correo sus archivos

**Comment by jccastillo0007** [comment]
acabo de subir un release ahorita en la mañana, que en teoría manda por correo la factura, siempre y cuando un dato extra del header tenga el campo correoReceptor

Puedes checarlo para efectos de pruebas, aunque después le cambiemos el nombre o la posición del dato extra.

**Comment by RigoFlores** [comment]
lo puse al final, pero no envió la factura...
        [facturat:fields>
          facturat:position10/facturat:position
          facturat:namecorreoEmisor/facturat:name
          facturat:valuesoporte@factura-t.com.mx/facturat:value
        [/facturat:fields>

**Comment by jccastillo0007** [comment]
El nombre del campo debe ser :  correoReceptor

**Comment by RigoFlores** [comment]
Ah si, que wey... deja ver

**Comment by RigoFlores** [comment]
Pos no, aún después de corregido, no lo envió...
No tiene que ver que no es el primer campo?

**Comment by jccastillo0007** [comment]
Listo.

Ya con el uso de los datos en el header, como este ejemplo :   

```
    <facturat:addendaFacturaT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:facturat="http://www.efacturat.com/AddendaFacturaTSchema"
        xsi:schemaLocation="http://www.efacturat.com/AddendaFacturaTSchema http://www.efacturat.com/AddendaFacturaTSchema.xsd">
        <facturat:header correoEmisor="jccastillo@factura-t.com.mx">
            <facturat:fields>
                <facturat:position>1</facturat:position>
                <facturat:name>name</facturat:name>
                <facturat:value>value1</facturat:value>
            </facturat:fields>
```

....etc etc ..

/>

**Comment by RigoFlores** [comment]
En tu ejemplo mencionas correoEmisor; realmente debe ser correoReceptor.
Por otro lado, sea cualquiera de los 2... igualmente los toma y los envía, es decir si se incluyen ambos atributos, tomará los correos de ambos y entonces enviará el correo para ambos... correcto?
