### ISSUE TITLE
no pude instalar el descargaT

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#612]
Como comenté anteriormente, creo que faltaban archivos, y ahora que lo intenté nuevamente no se pudo.
Ahora marcó esto siguiendo el ridmi:

Setup del descargat
1. Instalar Python OK
2. Instalar Firefox OK
3. Descomprimir la carpeta DescargaT OK
4. Normalmente Python se instala por default en C:/Python34, dicha carpeta debe agregarse al path OK
5. Instalar selenium con el siguiente comando: OK
   C:\Python34\Scripts\pip install -U selenium
6. Instalar DescargaT con el siguiente comando, [debe estar ubicado en la carpeta donde se descomprimió el archivo DescargaT.zip]
   python.exe setup.py install

tuve que mover el setup.py a la carpeta descomprimida que se menciona y marcó esto:

C:\DescargaT\DescargaT>python.exe setup.py install
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\download.py", line 412, in get_file_content
    with open(url) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    reqs = [str(ir.req) for ir in install_reqs]
  File "setup.py", line 10, in <listcomp>
    reqs = [str(ir.req) for ir in install_reqs]
  File "C:\Python34\lib\site-packages\pip\req\req_file.py", line 77, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "C:\Python34\lib\site-packages\pip\download.py", line 416, in get_file_content
    'Could not open requirements file: %s' % str(exc)
pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

C:\DescargaT\DescargaT>cd ..

Incluso le copié un archivo que se llama requirements.txt (que no está en el dropbox) y no, tampoco jaló.
Necesito todos los archivos completos para instalar. La anterior ocasión, lo que tenía era que no levantaba, pero si instaló todo correctamente.

**Comment by jccastillo0007** [comment]
aqui va a estar lo delicado...

subi al dropbox en la carpeta de DescargaT, los archivos de requerimientos.txt y contributors.txt, hay que ponerlos en el directorio donde descomprimiste el zip...

El problema es que debes probarlo en máquinas donde no lo tengas ya instalado, para saber que si funciona, yo en la máquina de windows que tengo, ya esta instalado, tons ya mis pruebas de instalación no es 100% confiable

Avisame que te sale, justo después de copiar los archivos... capaz que aqui si debemos hacer un screen sharing con teamviewer..

**Comment by RigoFlores** [comment]
Ya apareció el peine... ahora resulta que ya hay un tercer archivo que no tenía... el contributors.txt

Por supuesto que lo estoy probando en una máquina distinta a la mía, ya que debo validar y documentar el procedimiento de instalación, pero pues así va a estar medio cabrón

**Comment by RigoFlores** [comment]
Tenía por aquí guardado el primer primer zip que subiste y que jaló... tiene muchos mas archivos en la raiz de descargat, pero pues así lo pude instalar... entendería que no todos se ocupan, pero para saberle.... va a estar complicado...

**Comment by RigoFlores** [comment]
Cerraré el issue porque ya pude instalarlo, pero de eso a dominar el tema... jeje
