### ISSUE TITLE
en conector o timbrador, no enviar mensajes modales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#613]
ya que impiden la continuidad del timbrado, y son procesos 'ciegos'.
cuando no existe internet, se pueden hacer reintentos?

así lo pidió el cliente...

**Comment by jccastillo0007** [comment]
no se pueden hacer reintentos de manera automatica, ya que no sabriamos cada cuando y por cuanto tiempo, y esto nos puede meter en problemas de performance, lo que si, es que quite los mensajes de dialogo para este cliente de industrias ETSA.

**Comment by RigoFlores** [comment]
OK, entonces para responderle al cliente... en caso de falla de internet, que sucede cuando falla y cuando regresa el internet?
a) con las peticiones en proceso
b) con las peticiones nuevas

**Comment by RigoFlores** [comment]
alguna respuesta a estas preguntas formuladas hace 2 semanas?

**Comment by jccastillo0007** [comment]
chiaaaaa pues lo normal k

a) dichas peticiones van a fallar y el archivo se moverá a la carpeta de procesados con el prefijo de Error
b) lo va a intentar, y luego sucederá lo mismo que el inciso a

chiaaaa \* 2

**Comment by RigoFlores** [comment]
El punto es, cuando regrese el internet retomará las peticiones, y las que llegaron mientras no hubo conexión, simplemente se pasan a procesados con error... es decir, se pierden... correcto?

**Comment by RigoFlores** [comment]
No solo se pierden, no hay forma que el usuario sepa que se perdieron

**Comment by jccastillo0007** [comment]
Correcto, el usuario si se puede dar cuenta porque se.mueven con.prefijo
Error a procesados

JC

**Comment by RigoFlores** [comment]
OK, recordar que el conector en este caso no es 'visible' para el usuario.
El usuario simplemente no encuentra su factura y es todo. Tiene que marcar al área de sistemas, los de sistemas se tienen que meter al servidor y de ahí investigar que sucedió. Cuando se dan cuenta tienen que reprocesar los archivos (supongo).
Creo que algo que se podría hacer es simplemente un ping al servidor antes de timbrar. Si el ping responde, entonces procesar los archivos. Si el ping no responde, esperar hasta el siguiente período para reintentar. Con ello no necesitaríamos estar validando demasiado, y no gastaríamos mas recurso del que hoy se cuando se manda a timbrar y no hay conexión, ya que se tiene que esperar al timeout, y enviarlo a procesados con error, y así con cada archivo.
Cómo la beisbol?

**Comment by RigoFlores** [comment]
Y cuando el ping no responda, enviar a procesados un mensaje de error de que no hay conexión a internet.
La diferencia cuál es?, que no tendrían que estar reintentando manualmente y no cambiaría nada en el procesamiento actual de archivos.

**Comment by jccastillo0007** [comment]
Si se puede hacer, tendría que ver como hacer un ping desde java.

No creo que cubra el 100% de los casos, sobre todo si hay una factura a la mitad de procesamiento justo cuando se va internet, pero si se protege de no seguir reintentando y generando archivos con error.

**Comment by RigoFlores** [comment]
si, obvio no aplica para todos los casos, pero si llegaramos a implementar eso del ping (o cualquiera similar), si ayudaría al +80% de los casos que se lleguen a presentar, y nos ahorramos el tema de los reintentos sobre los archivos y lo mejor, atendemos LA VOZ DEL CLIENTE...
Lo levantaré en otro issue.
