### ISSUE TITLE
Agregar atributos genéricos en el header de la addenda Factura-T

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#614]
Agregar todos ellos como opcionales
Cuando se incluya alguno de los correos emisor o receptor, entonces se enviará a dichos correos los PDF y XML generados por el timbrador
Cuando se incluya cualquiera de los atributos generales se enviarán al PDF

Emisor y Receptor:
correoEmisor (_)
telefonoEmisor (_)
pagWebEmisor
claveEmisor
nombreComercialEmisor
bancoEmisor
cuentaBancariaEmisor
CLABEEmisor

Estos atributos ya se encuentran en variables del jasper, pero se toman o de la llave o del catálogo de clientes. Aquí partimos del supositorio que estamos timbrando XML que no se generaron en el facturat, aunque eventualmente toda factura emitida desde la plataforma facturat, debería incluir la poderosa addenda.

**Comment by jccastillo0007** [comment]
Done.

El schema se subió al dropbox.
