### ISSUE TITLE
Implementar Complemento INE - versión WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#615]
Ahora hasta para esos hijos de su pink floyd tenemos que trabajar.... ni pex...
Es para el WEB

Hubo un malentendido interno, y nos lo pidió la semana pasada… chiaaaa…

http://www.sat.gob.mx/informacion_fiscal/factura_electronica/Paginas/Complemento_INE.aspx

se manejarán estos  datos:

Versión: 1.0 (valor fijo)
Tipo de proceso: Ordinario   (Requerido. Valores aceptados: Ordinario, Precampaña, Campaña)
Tipo de comité   CEN  (Condicional. Valores aceptados: Ejecutivo Nacional, Ejecutivo Estatal)
Id contabilidad   196      (opcional)

Nodo Opcional:
Entidad
Clave entidad  (del catálogo)
Ambito:   (opcional)

Por lo pronto el nodo opcional, no lo ocupará, pero eventualmente se requerirá… tu sabrás si lo implementas de una vez….

**Comment by jccastillo0007** [comment]
Listo en PRU.... mandé archivo de datos de addenda por correo.

**Comment by RigoFlores** [comment]
Te mandé varios puntos:
a) El validador del SAT marcó error. Te lo mandé por correo
b) Te mandé un extracto del estándar de este complemento, donde indica dónde ubicar el schemalocation, y según entendí, no lo estamos poniendo ahí.
c) El RFC receptor de este complemento son:
**PVE930113JS1** PAN400301JR5, PRI460307AN9, PRD890526PA3, PTR901211LL0, **PVE930113J51**, CPO981127713,  CON990630A86,  NAL050801458

**Comment by jccastillo0007** [comment]
a) puto validador
b) mas puto el estándar
c) done, Ya di de alta los RFCs

a y b son el mismo error, y estoy trabajando en ello... espero tenerlo hoy por que no esta tan fácil, lo bueno es que ya lo habiamos hecho en la nómina.

JC.

**Comment by jccastillo0007** [comment]
Ya subí una versión que genera el complemento correctamente, el pedo esta en que una vez timbrado, el PAC agrega el schema location a nivel del complemento, lo cuál no esta del todo mal, pero el pedo es que al guardar el xml, por alguna rara razón se estan mezclando los schema location, por ahora hay que dejarlo así, ya que no necesariamente es un error, mientras pase el validador del sat estamos ok.

**Comment by RigoFlores** [comment]
Entiendo que ya está en PRO, y por lo pronto no tengo nada mas que hacer, sino esperar que la cliente usuaria hable para decirnos que no pasó?
O que puedo hacer para validar en producción?

**Comment by RigoFlores** [comment]
?

**Comment by jccastillo0007** [comment]
solo generar un xml con el complemento y validarlo ante el sat, yo lo hice y si funcionó, va hacer un pedo tratar de quitarle los schemas después de haber timbrado

**Comment by RigoFlores** [comment]
te refieres a realizar la prueba en producción, correcto?
Este complemento solo se configura mediante el XML y cuando el receptor sea alguno de los RFC's que te facilité, correcto?
Me acaba de escribir la cliente... anda no sé en que país... que no podía generar su recibo (ya le volví a explicar cómo)... entonces, va a generarlo y enviarlo al partido... a ver como nos vá con esto... la neta, me parece algo sencillo y creo que lo hemos ido alargando y complicando demasiado...

**Comment by jccastillo0007** [comment]
Correcto, hay que generarlo en producción, y si, esta sencillo

Saludos.
JC.

2016-06-07 6:47 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Pues no superó la prueba del validador del sat... sigue marcando lo siguiente...

Versión del estándar: 3.2

Codificación
Comprobante expresado en UTF-8

Validación de estructura: Inválido

"Versión del complemento ine:INE no permitida para la versión del CFDI 3.2"

IMPORTANTE: Los resultados anteriores se presentan a efecto de que valide
la estructura, cadena original y sello de su CFDI. Para que una factura
electrónica sea válida para efectos fiscales, deberá reunir los requisitos que
establecen las disposiciones fiscales vigentes.

**Comment by RigoFlores** [comment]
Este issue se mantiene como question, misma que es ¿y ahora que putas hacemos? Ese error me suena que el validador del sat está chueco o no se que pex...

**Comment by RigoFlores** [comment]
pues a ver que pasa, a mi me suena mas problema del schema location, que de la versión del complemento...

**Comment by RigoFlores** [comment]
lo cerramos y a ver que pasa... hasta el momento no ha habido quejas...
por ahí quizás lo solicite otro cliente
