### ISSUE TITLE
Manejar misma nomenclatura y directorios de este RFC HSI860519QT2 al grupo ETSA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#616]
Estos RFC's trabajan por el conector: ETE790117358, TET100426PJ7, SME830518PHA, ETS000216IL2. Manejan una estructura propia de directorios, así como una nomenclatura propia de los XML y PDF's generados. Les llamo grupo ETSA.

Este otro RFC es nuevo HSI860519QT2... ocupará el timbrador + addenda facturat... es el que estuviste ya trabajando... y lo tenemos listo, solo que necesitamos cubrir este otro requerimiento.

**Comment by RigoFlores** [comment]
![estructura etsa](https://cloud.githubusercontent.com/assets/2912775/15730590/8fea4728-2833-11e6-9cfa-fce4bd4ab50e.png)

ESTA ES LA ESTRUCTURA DE DIRECTORIOS, Y NOMENCLATURA DE ARCHIVOS DEL GRUPO ETSA

**Comment by jccastillo0007** [comment]
Done.

Agregué el RFC HSI860519QT2 a la lista de condiciones especificadas para todas las industrias ETSA

**Comment by RigoFlores** [comment]
NO TENGO NUEVA VERSIÓN PARA VALIDAR... CHIAAAA

**Comment by RigoFlores** [comment]
VALIDÉ EN PRUEBAS, Y MARCÓ ERROR EN GENERACIÓN DE CFD (REALMENTE PDF).
ESTO ARROJA EL LOG
2016-06-02 19:05:50.0228 ERROR pool-4-thread-1 com.facturat.controller.CFD.creator.FacturaTiCreator javax.xml.transform.TransformerException: java.io.FileNotFoundException: C:\CONECTOR\FACTURAS\201606\XML\19992_FAMR781024N95_02jun2016_190548_addendafacturat.xml (El sistema no puede encontrar la ruta especificada) 
javax.xml.transform.TransformerException: java.io.FileNotFoundException: C:\CONECTOR\FACTURAS\201606\XML\19992_FAMR781024N95_02jun2016_190548_addendafacturat.xml (El sistema no puede encontrar la ruta especificada)

Según entiendo, no está del todo homologada la ruta para el timbrador.. está buscando una carpeta XML y esa no existe. También la nomenclatura de los archivos que busca no es la correcta.

Grupo etsa, le llama así a sus archivos (ya lo había comentado):
CFDI_ETE790117358_ZSS8107103P6_PCUF208041

**Comment by jccastillo0007** [comment]
olvidé mencionar que las modificaciones las hice en la versión standalone y no web, puedes checar ahi.

**Comment by RigoFlores** [comment]
Chiaaaaa... pos claro que es en escritorio, en web de pruebas no tengo acceso al log... y en web de producción no tendría sentido el día de hoy...
Estamos hablando de escritorio... la diferencia, es que en el timbrador generas otro XML y lo estás buscando en nosequeruta

**Comment by jccastillo0007** [comment]
ah ok, es que como dijiste que validaste en pruebas...

es el primer RFC de esta empresa que usa el timbrador ?

**Comment by RigoFlores** [comment]
Este es el RFC del timbrador... HSI860519QT2
Según yo el tema, es que generas 2 XML's (que habría que borrar el que solo es de paso), y por ello el problema...

**Comment by jccastillo0007** [comment]
Ya esta arreglado ese issue, lo que pasó es que como ningún RFC del grupo ETSA usaba el timbrador, en el plugin de timbrador, no se validaban los paths específicos.

Lo de XML con la addenda facturat, solo hay que ver si no le ves un uso futuro de aclaraciones, pues lo borramos.

**Comment by RigoFlores** [comment]
No puedo probar, ya que no tengo el RFC en pruebas.. levanté un issue desde hace 2 días, pero no ha sido atendido

**Comment by RigoFlores** [comment]
Pues sigue sin jalar... como lo validas tu?
Esto me marcó con el timbrador...

2016-06-06 21:53:28.0409 ERROR pool-4-thread-1 com.facturat.controller.CFD.creator.FacturaTiCreator javax.xml.transform.TransformerException: java.io.FileNotFoundException: C:\CONECTOR\FACTURAS\201606\XML\19992_FAMR781024N95_06jun2016_215325_addendafacturat.xml (El sistema no puede encontrar la ruta especificada) 
javax.xml.transform.TransformerException: java.io.FileNotFoundException: C:\CONECTOR\FACTURAS\201606\XML\19992_FAMR781024N95_06jun2016_215325_addendafacturat.xml (El sistema no puede encontrar la ruta especificada)

**Comment by jccastillo0007** [comment]
para probar el timbrador, use un xml con el source rfc = HSI860519QT2 y lo timbró bien, sin error y generando bien el xml timbrado y pdf, que más debería probar?
te mando por email el xml que utilicé.

**Comment by jccastillo0007** [comment]
listo, checa la versión de justo hace 10 minutos.

**Comment by RigoFlores** [comment]
Ya la revisé, le pasé el XML del cliente con la addenda facturat, y sigue marcando lo mismo.
No está encontrando el XML de la addenda. De hecho lo busco por fuera en las carpetas y no existe, como si nunca se hubiera generado...
La factura si se alcanza a timbrar, porque aparece en el log, pero luego cuando busca la addenda, supongo yo para incorporársela al final al XML, no la encuentra y por ello marca errores...

2016-06-07 15:19:33.0194 ERROR pool-4-thread-1 com.facturat.controller.CFD.creator.FacturaTiCreator javax.xml.transform.TransformerException: java.io.FileNotFoundException: C:\CONECTOR\FACTURAS\201606\XML\19992_FAMR781024N95_07jun2016_151930_addendafacturat.xml (El sistema no puede encontrar la ruta especificada) 
javax.xml.transform.TransformerException: java.io.FileNotFoundException: C:\CONECTOR\FACTURAS\201606\XML\19992_FAMR781024N95_07jun2016_151930_addendafacturat.xml (El sistema no puede encontrar la ruta especificada)

**Comment by RigoFlores** [comment]
Había levantado un issue que se eliminara la addenda, ¿no es por eso que ya no se genera?

**Comment by jccastillo0007** [comment]
Asegurate de usar la versión que acabo de subir, ya que ejecuté el mismo
archivo xml que me enviaste y lo procesó bien con todo y addenda.

Saludos.
JC.

**Comment by RigoFlores** [comment]
![timbrador no jala](https://cloud.githubusercontent.com/assets/2912775/15874462/db349154-2cc8-11e6-808b-79fa80eba664.png)

ESTA ES LA ÚLTIMA, QUE NO?

**Comment by RigoFlores** [comment]
ese directorio XML en la ruta, está demás...
C:\CONECTOR\FACTURAS\201606\XML\19992_FAMR781024N95_07jun2016_151930_addendafacturat.xml (El sistema no puede encontrar la ruta especificada)

En la estructura ETSA no existe... por ello a ti si te jala... ya lo cree a manopla y si jaló
Hay que quitarselo, pero mientras tanto le entregaré al cliente

**Comment by jccastillo0007** [comment]
Si veo bien, no instalaste la última versión sobre un folder limpio, mas
bien, copiaste el jar de facturat a una instalación previa, es correcto?

Saludos.
JC.

2016-06-07 16:05 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
El procedimiento de actualización, que ejecutamos en la gran mayoría de los casos es:
a) Borrar todos los jars anteriores (*.jars; previo respaldo por si las flais)
b) Poner los nuevos jars en la carpeta Jars

Es todo!!!, ya quedó la actualización. 
Que estaría mal de ello?
