### ISSUE TITLE
IMPLEMENTAR CAMBIOS DEL MÉTODO DE PAGO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#617]
EN ESCRITORIO, EN WEB, EN CONECTOR TEXTO PLANO, EN CONECTOR LEVICOM 1 Y 2, EN CONECTOR SQL DE LOS ESPAÑOLES...
YA TE MANDÉ EL CORREO CON EL ANÁLISIS

**Comment by jccastillo0007** [comment]
El release 9.1.23 ya tiene los nuevos métodos de pago, ya no se permite teclear un método de pago customizado.

Este cambio lo hice para facturas generadas por la interfaz, pero también debe solucionar el escenario en todos los conectores, ya que se cambia del label código justo antes de generar el XML únicamente.

En el caso de conectores, si el método de pago ingresado, no es ninguno de los aceptados, se va a poner OTRO.

**Comment by RigoFlores** [comment]
No veo la versión nueva. Si la subiste?

**Comment by jccastillo0007** [comment]
se supone que la deje subiendose, pero no esta, al rato checo que pasó y te aviso

**Comment by RigoFlores** [comment]
Validé en escritorio, y desde pantalla aparentemente lo hace bien, pero en el PDF no está colocando la clave (03.Transferencia). No me quiero aventar la bronca de actualizar 2 veces a todos los de escritorio; si el SAT decide que vaya la clave, o la descripción o ambos, ya estaríamos cumpliendo de facto.

En el conector de texto, trabaja bien también.

Para el timbrador tenemos detalles, por lo que hay que hacer una de 2:
1) Si pedimos que el cliente ponga la clave en el método de pago del XML, entonces nosotros tenemos que enviar al PDF la leyenda que corresponda a la clave.

2) Si le pedimos al cliente que envíe la leyenda del método de pago en el XML, entonces nosotros nos encargaremos de cambiar la clave en el XML; y mantener la leyenda en el PDF.

FALTA IMPLEMENTAR EN WEB

**Comment by jccastillo0007** [comment]
ok, ya actualicé la leyenda que saldrá en el pdf, y así aparecerá en la interfaz gráfica también.

Para el timbrador, dado que es un xml generado por algún otro sistema, yo creo que no debemos meternos en problemas de corregir la info, ahi les estamos dando el servicio de tramitar el timbre y el pdf , con la premisia de que su XML ya cumple con el Anexo 20, no es nuestra responsabilidad, y si le metemos mano, nos podemos meter en broncas, incluso no validamos nada mas, ningún otro constraint especificado en el anexo 20 lo estamos validando, ahi tienes que hacerles ver a nuestros clientes del timbrador, que se aseguren que su app o proveedor que genera el xml, cumpla con las modificaciones del sat.

**Comment by RigoFlores** [comment]
OK, partimos de NO TOCAR EL XML... correcto.
Lo que SI TENEMOS QUE HACER, es tomar la clave y enviar al PDF (porque eso si lo generamos nosotros), la descripción correspondiente del método de pago..
Por ejemplo en el XML viene '03', entonces al PDF se envia 'TRANSFERENCIA'

**Comment by RigoFlores** [comment]
Ya valió madres... la versión 10.0.1 dejó de jalar todo lo del conector con texto. Es decir, ni el no colocar la versión cerrada, le dejó sin defectos.

Ahora en lugar de buscar por "Transferencia" (o cualquier otro) en el archivo de texto, ahora busca "03.Transferencia"...
Chiaaaaa....
En el texto, o en la BD de los españoles, para levicom, lo que sea... dejó de jalar..

**Comment by RigoFlores** [comment]
Urge la corrección, tuvimos que dar patrás a las actualizaciones por conector

**Comment by jccastillo0007** [comment]
ah ok, es solo la leyenda que recibe cieto.... voy a eliminar el prefijo.

**Comment by RigoFlores** [comment]
chiaaaaa.... pos y luego???

**Comment by jccastillo0007** [comment]
listo.... (osea que empezaron a actualizar sin probar ?)

**Comment by RigoFlores** [comment]
La última versión la probé en pantalla y jaló... asumí que todo lo demás jalaría igual... pero no, el problema fue a nivel conector... ya que está buscando por "03.Transferencia"...
Por cierto, noté que las descripciones de los métodos ... solo las acepta sin acento... así está programado?

**Comment by jccastillo0007** [comment]
De hecho no se pueden ingresar las descripciones, ya están configuradas, y si, sin acentos y en mayúsculas

**Comment by jccastillo0007** [comment]
Estoy subiendo una versión justo ahora, checale...

y voy a subir la versión web también en un rato mas

**Comment by RigoFlores** [comment]
Si, a lo que me refería es que solo acepta los métodos de pago sin acentos... a nivel del archivo de texto... o en la BD de los españoles... es decir, me refiero al conector

La versión web, por favor NO LA SUBAS A PRO... SI ACASO A PRU... PERO A PRO NO

**Comment by RigoFlores** [comment]
Voy a cerrar este issue, y abriré otros para el seguimiento a lo pendiente
