### ISSUE TITLE
Genera 2 XML en el timbrador con addenda facturat

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#618]
Para el cliente que ocupará el timbrador con addenda facturat, está generando un XML supongo que es temporal, pero causará ruido al cliente. No se puede eliminar?

**Comment by jccastillo0007** [comment]
ese XML es la pura addenda, que después de timbrar se va a agregar otra vez al xml, si se puede eliminar, pero creo que nos puede servir para aclaraciones

**Comment by jccastillo0007** [comment]
????

Ya que no recibí respuesta si era buena idea o no, y como te estas quejando de ese archivo, ya agregué lo necesario para que lo elimine al final del proceso.

**Comment by RigoFlores** [comment]
No pensé que necesitaba retro, perdón. Aunque el issue en sí, habla por sí mesmo.
Ya ví que ya no lo genera, o mas bien, ya no lo mantiene...
