### ISSUE TITLE
Dar de alta HSI860519QT2 en pruebas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#619]
Para validar todo el tema del timbrador con addenda facturat

**Comment by RigoFlores** [comment]
Pues sigo sin poder validar lo de la estructura de directorios y nomenclatura, porque no cuento con este rfc en pruebas...

**Comment by jccastillo0007** [comment]
El RFC ya estaba en pruebas para timbrado desde la semana pasada.
Si lo necesitas en web, ya lo di de alta también.

**Comment by RigoFlores** [comment]
Yo lo pedí la semana pasada, y no me confirmaste.
Ya vi que si está.
