### ISSUE TITLE
Conector-Timbrador-Addenda FacturaT, requiere de un directorio extra para grupo ETSA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#620]
La estructura de directorios para las facturas es simple; por ejemplo:

C:\CONECTOR\FACTURAS\201606

Ahí se almacenan los PDF y XML's.

En el caso de este escenario en específico para este issue, necesita un directorio adicional, sino marca error aún cuando si timbró el XML (lo cuál está pior aún).

C:\CONECTOR\FACTURAS\201606\XML   para guardar ahí un XML que nadie ocupa, y que corresponde al de la addenda facturat; digo que nadie ocupa, ya que una vez timbrado el XML, se le agrega dicha addenda.

La intención es quitar esta dependencia de este directorio que se tiene que crear a mano.

**Comment by jccastillo0007** [comment]
mmmm tendría que probar en una máquina windows, porque yo acabo de probarlo otra vez, y me genera todo dentro del mismo directorio, sin crear una carpeta XML, hay dos puntos a revisar.
1. Que la llave que estes usando para pruebas, tenga correctamente el RFC 
2. Que estes usando la última versión de facturat

voy a probar en windows mañana, pero realmente no creo que tenga que ver el sistema operativo.

**Comment by RigoFlores** [comment]
Si trabajé con la última versión hasta ayer.
La versión de hoy, ya no tiene ese problema.
