### ISSUE TITLE
Para este cliente PVC911113QX7, armar la descripción del concepto (en web)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#621]
Para propósitos de incluirlo en el XML

Sería enviar como concepto al XML: 

descripción + informacionComplementaria + datoExtraPro1 + .... + datoExtraPron

Aquí no sabemos cuántos datos extras a nivel producto se ocuparían, pero todos lo que tengan valor asociado (que se hayan capturado), enviarlos al XML

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
como lo valido?, intenté entrar a pruebas con este rfc y no entró..

**Comment by RigoFlores** [comment]
Este rfc no está en pruebas... con cuál rfc lo validaste?

**Comment by jccastillo0007** [comment]
Lo validé con el mío, y luego lo cambié a ese RFC, pero no lo dí de alta en
PRU, lo hago ahorita en un ratito y te aviso.

Saludos.
JC.

**Comment by RigoFlores** [comment]
ok

**Comment by jccastillo0007** [comment]
ya lo di de alta en PRU.

**Comment by RigoFlores** [comment]
chiaaaaa.... yo soy el que debería estar dormido!!!.... le falta lo de addendas y datos extra, o como pruebo?

**Comment by RigoFlores** [comment]
pls

**Comment by jccastillo0007** [comment]
Listo

**Comment by RigoFlores** [comment]
OK. ya validé... si hizo todo, excepto que no incluyó la información complementaria. Lo podemos dejar pendiente, o si no se complica y no le pegas a otra cosa, de un vez lo agregamos.
Urge llevarlo a PRO.
