### ISSUE TITLE
Modificar el Catálogo de Métodos de Pago del SAT para escritorio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#622]
Si se hubiese implementado en tablas, como en su momento lo pedí, esto no sería necesario, pero bueno.
Te enviaré por correo el nuevo catálogo.

Aplicar factura en pantalla, conector texto, conector Navision, Levicom I, Levicom II, Timbrador con Addenda facturat y timbrador estándar.

**Comment by jccastillo0007** [comment]
listo.... la frecuencia de cambio de dicho catálogo, no justifica el esfuerzo por sacarlo a base de datos.

**Comment by RigoFlores** [comment]
ok, lo valido para retomar nuestro proceso de actualización de clientes.
Hoy platiqué via chat con el sat, y según ellos debe llevar la clave y descripción en el XML (cada persona dirá cosa diferente, eso ya me la sé).
Lo que hoy envió facture hoy, es que solo se incluye la clave en el XML, con el nuevo catálogo.
Total que de los 2 ni a cuál creerle tanto, el pinche pac me aseguró el otro catálogo y ahora resulta que hay uno nuevo... 
Total, probaré tanto escritorio y web, y trataré de confirmar por otro medio antes de retomar la actualización con clientes...

**Comment by RigoFlores** [comment]
No está aceptando el 05. Monedero Electrónico.... acepta "monederos electronicos" y así lo manda al PDF, lo cual es incorrecto.
Para este nuevo catálogo pasó de plural a singular en el caso del 05. Monedero Electrónico

**Comment by jccastillo0007** [comment]
listo.

**Comment by RigoFlores** [comment]
Pues no, no hay nueva versión. La última es del dia 07 de junio. Yo comenté el día 08 de junio lo de monedero electronico

**Comment by jccastillo0007** [comment]
ya  se esta subiendo

**Comment by jccastillo0007** [comment]
ya esta lista
