### ISSUE TITLE
Implementar el catálogo de metodos de pago nuevo, en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#623]
Una vez, que lo probemos lo liberamos.
Recordar que el recibo de nómina lleva método de pago, y ahora creo que está fijo. Habría que abrirle el campo, que no? Es decir colocar una opción en la pantalla actual de individual, donde indiquen el método de pago para la nómina... 

De hecho, el xml para nómina será de los cambios importantes en la versión 3.3 del anexo 20... (ay mi madre!!!!)

**Comment by jccastillo0007** [comment]
Mejor dejamos lo de nómina para cuando se ocupe, ya que tengamos todos los campos necesarios, agrego lo de método de pago.

**Comment by RigoFlores** [comment]
Lo de nómina se ocupará y será obligatorio al mismo tiempo que la factura.
Que campos se ocupan?... pues lo mismo... el catálogo de metodos de pago (formas de pago que le llamó el sat)...

**Comment by RigoFlores** [comment]
pero bueno, eso quiere decir que ya está en web el catálogo nuevo, en ambiente de pruebas?

**Comment by jccastillo0007** [comment]
Es que dijiste que lo de nómina tendrá otros cambios e impactos importantes con la nueva versión del anexo 20, por eso digo que nos esperemos.

Si, ya esta en PRU y PRO

**Comment by RigoFlores** [comment]
Negativo, lo que ví que si está en pru y en pro, es el catálogo anterior.
Por ello la pregunta era si ya estaba el catálogo nuevo. 
Necesitamos corregir ASAP., ya que no todos esos códigos son válidos.

**Comment by jccastillo0007** [comment]
Done... ojo.. en web (PRU y PRO) quedó en base de datos.
En standalone, quedó en enum

**Comment by RigoFlores** [comment]
Chiaaaa.... donde es más fácil actualizar a todos los clientes, es decir en web, si quedó en BD... donde tenemos que entrar máquina por máquina, quedó en jardcoud.... chiaaaaaa!!!!
Lo de la nómina tendrá cambios no sé hasta cuando, pero mientras tanto si se ocupa implementar ese método de pago.... voy a investigar poco mas y te confirmo

**Comment by jccastillo0007** [comment]
en standalone, aunque estuviera en base de datos, de todos modos tienes
que actualizar a todos los clientes, es una desventaja del standalone, no
veo tu punto...

y no se implementó en base de datos, dada la complejidad.

Saludos.
JC.

2016-06-16 6:55 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
La actualización cuando se trabaja con un catálogo en escritorio puede ser simplemente telefónica, o con un vidio.
En jarcoud, es a huevito entrar a su máquina para actualizar código.
Pero nada, vamos por el sistema de nómina... se va a enfriar y el socio de tamaulipas anda movido...

**Comment by jccastillo0007** [comment]
No recomiendo eso del video o via telefónica, si alguien diferente a
nosotros le mete mano a la base de datos, y se comete algún error, puede
ser un grave problema,

JC

Saludos.
JC.

2016-06-17 7:50 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
Catálogo en escritorio = pantalla con altas, bajas, consultas y cambios a una (o varias) tablas en particular. 
Es decir, la implementación de un catálogo
