### ISSUE TITLE
Eliminar el schema dentro del nodo de addenda ZF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#624]
Te envié un correo.
Escenario: conector texto + formato levicom II + addenda ZF

Si lo timbras en pruebas, no le agrega nada de schema location
Si lo timbras en producción, le agrega un schema location dentro del nodo addenda; a nuestro cliente le detuvieron sus pagos...

**Comment by RigoFlores** [comment]
Te mandé ooootro correo con la voz del cliente

**Comment by RigoFlores** [comment]
Ya escribí a facturehoy, pero en lo que si o no, tenemos que buscar como quitar esa leyenda.
Te recuerdo que es por conector, en formato levicom II, es decir del grupo ETSA, donde este RFC TET100426PJ7 pertenece.

**Comment by jccastillo0007** [comment]
no hay defecto que perseguir, hasta que se demuestre lo contrario

**Comment by RigoFlores** [comment]
Ya pedí que prueben... voy a esperar respuesta... o incluso, nosotros mismos podemos hacer la prueba en producción, que no?

**Comment by jccastillo0007** [comment]
Ya la hice, y te mande el xml timbrado con mi rfc en producción

Saludos.
JC.

**Comment by RigoFlores** [comment]
Quedó con la versión actualizada, chiaaaa
