### ISSUE TITLE
ELIMINAR LA SERIE SIN SERIE DE ESTE CLIENTE EN PRO PVC911113QX7

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#625]
EN PRODUCCIÓN.
TRABAJARÁ CON LA SERIE V, ENTONCES PLS ELIMINAR LA SERIE 'SIN SERIE', YA QUE APARECE POR OMISIÓN Y SEGURAMENTE LES CAUSARÁ PROBLEMAS.

**Comment by jccastillo0007** [comment]
done.
