### ISSUE TITLE
Mensajes de cancelación confusos nuevamente en WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#626]
Acabo de enviar a cancelar una factura de la tia.
El mensaje dice "Cancelación de Factura enviado al SAT."
Se genera el acuse y el status es 201, que típicamente significa que se canceló correctamente.

Verifiqué en el portal del SAT y aparece como cancelada.

El mensaje debió ser "Factura cancelada con éxito", o el equivalente que se envía ahora mismo.

Emisor:
RFC Emisor: TIA101020BP4
PUBLICO EN GENERAL
4f54ef6f-b853-48b0-b8a7-1db774dcb3f5
Receptor:
Folio SAT (UUID):
RFC Receptor: XAXX010101000
Total: 1.16
Serie:
Folio Interno:
SIN SERIE
216
Fecha Solicitud:
Fecha Cancelacion:
16/06/2016 06:57:26
16/06/2016 06:57:30
Sello Cancelacion SAT:
0jo/882sLQ4p1w/Qb7mp98WBZNWASBrdpS5+80NSSqNrTAP+KrZkEmT16vh0JZAJKrjOqI4eJMqXC1rb1s/2Ug==

**Comment by jccastillo0007** [comment]
Recuerda que FactureHoy nos regresa un status de que la factura se mandó al SAT a cancelar, lo cuál puede ser inmediato o no.... por esa razón nosotros mostramos el 201, no siempre se cancela en tiempo real...
