### ISSUE TITLE
DAR DE ALTA OOOOOTRO IMPUESTO LOCAL EN WEB

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#627]
AL CLIENTE LE URGE PARA VARIAR... 
LA PREGUNTA RESURGE, PORQUE NO IMPLEMENTAR LO MISMO QUE EN ESCRITORIO...???

"DERECHO POR LOS SERVICIOS DE INSPECCIÓN, VIGILANCIA Y CONTROL"

**Comment by RigoFlores** [comment]
Por supuesto un SLA de 1 día para un 'impuestito', es algo menos que inaceptable...

**Comment by jccastillo0007** [comment]
Es un cambio, y un día es lo más rápido a lo que nos podemos comprometer,
si les has dicho lo contrario entonces ya la regaste.

Saludos.
JC.

**Comment by RigoFlores** [comment]
El tema es que no ves el problema de raiz... si en escritorio se trata de simplemente darlo de alta, como cualquier otro impuesto... porque no ofrecer el mismo servicio en web... y preferimos decir que nuestros SLA's son de 1 día para dar de alta un impuesto, en lugar de ver como podemos implementar que sea algo como dar de alta un IVA...

**Comment by jccastillo0007** [comment]
ya lo hemos hablado, y te habia comentado que el esfuerzo requerido no
justifica un cambio que se solicita de vez en cuando, se cual es tu punto
de fondo, pero se te olvido lo que ya habia dicho.

Saludos.
JC.

2016-06-21 17:32 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Listo.
