### ISSUE TITLE
No está enviando correos de facturas en web, en pruebas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#629]
Desde facturas emitidas o desde la opción de reenviar... no esté saliendo el correo (porque no llega a los destinatarios, son varios y a ninguno llega). 
En producción si lo envía.
No se vaya a inyectar este defecto de pru a pro

**Comment by jccastillo0007** [comment]
Checa la configuración de la cuenta de correo que tienes... tal vez este
por ahí,

Ya probaste con los datos default, es decir, sin configurar datos de cuenta
de correo ?

Saludos.
JC.

**Comment by RigoFlores** [comment]
No lo envía con el correo de default.
No tiene configurado ningún otro correo, es la cuenta de la tia en pruebas.

**Comment by jccastillo0007** [comment]
Negativo, te acaba de llegar un email de una factura generada en PRU con mi user y con los datos default para envío de correos.

**Comment by RigoFlores** [comment]
Pues desde la cuenta de la tia, no envía tons pues ahí si no sé... voy a revisar nuevamente
