### ISSUE TITLE
Permite modificar el rango inicial de folios, aún perdiendo el consecutivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#63]
Solamente se podrá modificar el rango superior, siempre y cuando sea mayor al folio actual.
Sin embargo, creo que ya no debemos controlar mas que el folio de inicio de una serie.
El sistema debe avisarle al usuario, cuando ya se encuentre al 10% de que se termine el rango de folios contratado, amén de la vigencia de los folios y la vigencia del sello.

**Comment by jccastillo0007** [comment]
Se implemento la validacion de no modificar el rango inicial

El resto de comentarios pertenecen a la ficha numero 54
