### ISSUE TITLE
Agregar al catálogo de métodos de pago, en WEB WEB WEB el "NA", con código 98

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#630]
Está nebuloso este tema, sin embargo por lo pronto en web, ya que ahí hacer algún ajuste no es tan costoso. Este cambio lo pidió así la contraloría de sanborns, así que por lo pronto lo hacemos así, en lo que identificamos mas mejor como queda.

En escritorio cuestan mas los cambios, porque hay que actualizar uno por uno.

el SAT me dijo hoy por chat, que debe incluirse NA como clave cuando el método de pago sea NA, pero ellos te dicen distinto cada vez.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
:(
