### ISSUE TITLE
Implementar complemento educativo vía el conector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#631]
Con nuestro formato estándar... la información quedaría así en los extra data A NIVEL PRODUCTO:

extradata[Alumno|Fulanito de tal|curp|FOPR681125HDFBC9|Grado|Secundaria|clave|28PST0030N|]}

o también así

extradata[|Fulanito de tal||FOPR681125HDFBC9||Secundaria||28PST0030N|]}

donde la etiqueta realmente solo sirve para dar claridad a los datos... 

En caso que se deba incluir a huevo el RFC dentro del complemento (es que me parece que es opcional), entonces que se tome el RFC receptor.

Este complemento ya lo tenemos en escritorio, pero desde pantalla...

**Comment by jccastillo0007** [comment]
Done.... de hecho no hice mucho... solo un ajuste con la clave... este es el escenario de pruebas:
1. Usar la llave del cliente AVA621016TH4
2. Los datos extras del producto deben estar en este orden:
   extradata[CURP|FOPR681125HDFBC9|Grado|Secundaria|Alumno|Fulanito de tal|clave|28PST0030N|]}
   osea CURP, Grado, Alumno y Clave
3. La palabra CURP debe ir en mayúsculas

Así debería funcionar, solo me falta el RFC del nuevo cliente, para darlo de alta en el uso del plugin de complemento educación... pero mientras con el RFC AVA621016TH4 puedes probar.

**Comment by RigoFlores** [comment]
OK, 
¿entiendo que el RFC emisor, puede ser cualquiera o lo tienes que dar de alta en jarcoud?
La palabra CURP en mayúsculas, entiendo que es la que dispara el complemento educativo, correcto?
Para no dar de alta pluguines de mas, cuáles son exactamente los que se ocupan: conector, extra data y addendas, o sobra addendas?
De lo demás jaló bien a la primera... vientos!!!
PD. Los clientes me traen a pan y verga, y al parecer se les terminó el pan esta semana... no maaaaa....

**Comment by jccastillo0007** [comment]
Se tiene que dar de alta, por ahora solo esta el RFC AVA621016TH4, pero mandame el nuevo emisor  y lo doy de alta.
La palabra CURP es para poder identificar los datos extras que son de un alumno, el candado de que se a CURP, es por el truco chacarron que se hizo en el catálogo de clientes para dar de alta los datos extras por producto
Connector, extra data y addenda.

Lo chido es que no implementé nada de código para que jalara desde conector.

Nota. Putos clientes, diles que si chingan tanto, al menos pidan más proyectos y ajustes facturables.

**Comment by RigoFlores** [comment]
OK, ya que tocas el tema.
Cuando es por pantalla, en el producto se debe capturar el nombre del alumno como producto... jeje
y el ID del alumno es un RFC.
Como datos extra, se captura el CURP y el nivel escolar. La clave de la escuela se toma del properties.
Cuando se timbra, la aplicación cambia el concepto a COLEGIATURA, el RFC del complemento lo toma del rfc receptor, y el resto de datos del 'producto'.
¿Eso como empata con la versión del conector?
Yo supondría que son en la parte de los datos, totalmente independiente.

**Comment by RigoFlores** [comment]
Vi un detalle... yo te pedí por error incluir la clave en los datos extra, pero ese dato se toma del properties. Yo creo que para no mandar tantos datos, que se tome del properties o ya lo dejamos así???

**Comment by jccastillo0007** [comment]
Dejalo así, de esa forma el proceso por conector queda totalmente
independiente del proceso por pantalla.

Lo único interesante por conector es el orden de los datos y el inicio con
la palabra CURP.

El proceso en pantalla no cambió en nada.

JC.

Saludos.
JC.

**Comment by RigoFlores** [comment]
OK, de acuerdo.
Ya solo te pido dar de alta este RFC para complemento educativo, en pru (para validar)  y pro (para ya entregar) .,...
CEM001031GY1

**Comment by RigoFlores** [comment]
No es pregunta (question) , pero se me pasó totalmente solicitarte esto y solo eso falta para entregar... no maaaaaa....

**Comment by jccastillo0007** [comment]
Listo... el RFC 'CEM001031GY1' se dió de alta en PRU y se configuró como emisor del complemento de educación.

**Comment by RigoFlores** [comment]
Dar de alta ooootro RFC para este complemento...
CKQ051005413

**Comment by jccastillo0007** [comment]
listo, es el que dí de alta ayer  chiaaaaa

**Comment by RigoFlores** [comment]
como reclamaste que no levanté ishu, pos que lo levanto k....
