### ISSUE TITLE
Escritorio - al tipo de cambio le antepone un $ en el tipo de cambio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#632]
El tipo de cambio es un factor, un rate, pero no es una moneda...

**Comment by jccastillo0007** [comment]
oye, en donde le pone el $, yo generé una factura y no lo vi ni en el PDF ni XML ni en pantalla, dime como lo puedo reproducir.

**Comment by RigoFlores** [comment]
PUES YO LO PUEDO VER TANTO EN UNA PLANTILLA QUE DESPLIEGUE EL TIPO DE CAMBIO (QUE NO ES TAN COMÚN QUE ASÍ SEA), COMO EN EL LOG... AQUÍ UN EXTRACTO DEL LOG

,numeroTarjeta=NO IDENTIFICADO,moneda=PESOS,tipoDeCambio=$1.00,folioSAT.....

¿SI LO VALIDASTE EN ESCRITORIO?

**Comment by jccastillo0007** [comment]
Si, lo cheque en escritorio, lo raro fué que con la plantilla que yo estoy usando no se ve, dejame quitarselo desde el inicio.

**Comment by RigoFlores** [comment]
OJO, la plantilla no refleja precisamente el $, ya que podría estar truncado, amén que ese dato casi no lo desplegamos en PDF.

**Comment by jccastillo0007** [comment]
cree una moneda en dolares, y si lo desplegó el jasper pero sin $, ando haciendo esas pruebas

**Comment by RigoFlores** [comment]
chécale bien, quizás sea con tipo de cambio = 1.00

**Comment by jccastillo0007** [comment]
listo, el $ se lo pone justo al mandar los datos a Jasper, curioso porque en unas plantillas no lo pone, en la noche subo esta version, sería todavía la versión 10.0.3.
