### ISSUE TITLE
Por conector no detecta el método de pago NA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#633]
Dado que fue lo último que se agregó, no lo detecta.
Cuando en el conector el método de pago sea NA, entonces la clave que sea la 98, y el método de pago = NA.

**Comment by jccastillo0007** [comment]
Según lo que platicamos por whatsapp, tanto clave como label será NA, este será el método de pago default para cuando indiquen un método de pago no conocido o que indiquen directamente NA

**Comment by RigoFlores** [comment]
CUANDO NO RECONOCE EL METODO DE PAGO, ASIGNA 'NA' (CORRECTO)
EL PROBLEMA SIGUE SIENDO EL QUE SE REPORTÓ AL INICIO DE ESTE ISSUE, EL MÉTODO DE PAGO 'NA' NO LO ESTÁ RECONOCIENDO YA QUE LE ASIGNA '02' EN EL XML Y 'CHEQUE NOMINATIVO' EN EL PDF, LO CUAL ESTÁ CHUECO.
DEBE SER NA EN EL XML Y NA EN EL PDF.
POR ELLO COMENTÉ QUE SI ERA NECESARIO QUE LA FRASE SEA 'NO APLICA' EN LUGAR DE 'NA' DENTRO DEL ARCHIVO DE TEXTO, PARA EVITAR ESTA CONFUSIÓN QUE AL PARECER NO HA QUEDADO DEL TODO CLARA

**Comment by jccastillo0007** [comment]
Listo... el problema es que el método de pago "Cheque Nominativo" tiene un na en medio de la palabra, y se quedaba con esa opción.

Ya lo probé con NA y con na y con otro método de pago no identificado.
