### ISSUE TITLE
Escritorio-Consultas-Recibidos agregar el botón de DescargaSAT y CrearPDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#634]
Desde un solo punto, poder descargar, crear pedefe y consultar... que super chido, no?

**Comment by jccastillo0007** [comment]
Si, estaria super chido siempre y cuando lo usen

Done.

**Comment by RigoFlores** [comment]
Estaba pensando que el plugin no será necesario, ya que aunque vean las opciones, no podrán aplicar hasta que paguen y les instalemos, que no?
