### ISSUE TITLE
Escritorio-Consultas-Facturas, agregar el botón de crearPDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#635]
Realmente el botón de crearPDF es mucho mas que la creación del PDF...
a) CrearPDF
b) Generar reporte general y detallado
c) Registrar en BD para la consulta

**Comment by jccastillo0007** [comment]
Done.

Si, hace todo eso, pero no se como ponerle al botón... tal vez "Procesar XML."

**Comment by RigoFlores** [comment]
Aún no registra las emitidas, es correcto eso???

**Comment by RigoFlores** [comment]
ya vi que hay otro ishu para esta cueshtion...
