### ISSUE TITLE
Escritorio-Consultas-Facturas.... no despliega las facturas descargadas (emitidas)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#636]
Cuando se le da crearPDF desde esta pantalla, debe:

a) Asegurarse que el rfc emisor sea cliente nuestro
b) Asegurarse que no se duplique el registro en la BD de emitidas
c) ¿Como asegurar que no se repitan los XML y PDF's descargados? (pregunta para el área de desarrollo).

Por lo pronto permitiremos que se repliquen los archivos PDF/XML en caso que ya existan... de hecho hay forma de conocer si un XML/PDF ya existe previamente? Según yo solo por nombre, y eso no nos asegura 100% que no se repitan

**Comment by jccastillo0007** [comment]
update
a. ya lo hace, si la factura no tiene a nuestro cliente como emisor o receptor, no la procesa
b. listo.
c. voy hacer la prueba en windows, según yo solo se sobre escribe el archivo y listo, dado que es el mismo nombre cuando se baja del SAT, si se intenta volver a crear un PDF, se crearía con el mismo nombre y eso provocaría que se sobre escriba también, así que no le veo problema

**Comment by jccastillo0007** [comment]
Aqui casual,  cerrando issue con mucho tiempo de haberse corregido.
