### ISSUE TITLE
Escritorio-Consultas-Recibidos ordenar por fecha de emisión

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#637]
Para ser consistentes con nosotros mismos, hasta arriba se presentan los mas viejos y hasta abajo los mas recientes...

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Jejeje... quedó al revés...
Primero los mas viejos y luego los mas recientes.... chiaaaaaa

**Comment by jccastillo0007** [comment]
mmmmm neta.... no estar[as tu al revés ?

haber checale otra vez

**Comment by RigoFlores** [comment]
no puedo estar reprobando cada vez que no creas en la ficha...
![no ordena recibidos](https://cloud.githubusercontent.com/assets/2912775/16854713/cd297e7c-49d7-11e6-94c5-ac8874de407e.png)

**Comment by jccastillo0007** [comment]
jajaja no es que no crea, pero una de dos, o no pruebas bien, o no usas la
versión adecuada, esto lo creo porque esa funcionalidad yo la probé y si me
funcionó.

De hecho lo que hice ahorita fué invertir el ordenamiento, para ver que
comentarios me dabas, es decir, ahorita ordena totalmente al reves que
antes, y tu me reportas el mismo comportamiento.

Saludos.
JC.

**Comment by RigoFlores** [comment]
pues lo hiciste al revés y ya quedó... así ya somos consistentes con la ventana de emitidos, y con ventanas similares que tenemos en web.
Es un orden ascendente (supongo), porque presenta los mas viejos y hasta el final los mas recientes.
Pero nada, en un lo que creo que es la última versión ya quedó.
