### ISSUE TITLE
Factura-T-PDFor, no procesa todos los XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#638]
Estoy seguro que antes ya lo hacía, ya que cuando estaba por juera, no dejaba comadre pa bailar, y ahora discrimina algunos XML que ya te los envié por correo...

**Comment by RigoFlores** [comment]
Lo acabo de verificar por el último PDFor que tengo (estánalon), y no tiene problema... procesa todos, incluyendo los que te envié por correo...
Chiaaaaa.... son bugs heredados, o falta en control de cambios, o el candys ya no es buen lugar para desarrollar y corregir bugs...!!!!!

**Comment by jccastillo0007** [comment]
mmmm no lo creo.... el problema es que el folio en los archivos que me enviaste es :  
folio="50010524731"
folio="00012680001939913934"

Ese número tan grande no cabe en un tipo de dato int, que es donde la app trata de almacenar el folio, luego entonces no los procesa.

Verifica bien las pruebas que hiciste hoy, no hay manera de que si los procese correctamente.

Con la versión que estoy subiendo hoy al dropbox, estoy validando ese dato, y si es tan tan tan grande, le va a asignar 0.

**Comment by RigoFlores** [comment]
Stop, stop, stop...
No hay que tomar decisiones así a la ligera... para eso tenemos una spec llamada anexo 20...
![specfoliointerno](https://cloud.githubusercontent.com/assets/2912775/16691258/8e33d6da-44f1-11e6-96f5-7d3fe3e2aa55.png)

Resulta que los que estamos mal, somos nosotros por no poder procesar folios taaaan largos, cuando la spec menciona hasta 20 posiciones... como la bestia?

**Comment by RigoFlores** [comment]
Verifiqué y en el estánalon si lo procesa... lo cual parece mas que lógico, porque ahí no interviene el facturat de escritorio. 
Esta versión del pedefor es aquella que ejecuto con un bat, y simplemente para generar los PDF's a partir de unos XML's
Te lo enviaré por correo...

**Comment by RigoFlores** [comment]
LABELS:
DEFECT: no procesa los folios muy chonchos que se apegan a 
QUESTION:  ¿y ahora que hacemos?

**Comment by jccastillo0007** [comment]
Listo, ya esta arreglado... chiaaaa

**Comment by jccastillo0007** [comment]
Por cierto, ya viste cuantos schemas incluye el cfdi del banco jajajajaja, justicia divina, ya que eres muy picky con eso de los schemas incluidos en los cfdisssss...

**Comment by RigoFlores** [comment]
no he visto, pero lo checaré..
