### ISSUE TITLE
Definir si es necesario o nó, el folio final

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#64]
Si se implementará lo solicitado en la ficha 54, entonces se deberá eliminar el rango superior, de la pantalla de captura correspondiente.
Por lo pronto permite modificar el rango superior, aún cuando capturas un número  menor al folio actual.

**Comment by jccastillo0007** [comment]
Fixed.

El rango final debe ser mayor al inicial y al current folio.

Luego vemos si aplica o no el rango final, aun cuando lo pueden modificar, se me haria raro no definir un rango final
