### ISSUE TITLE
TIMBRADOR - DISTINGUIR NOMINA DE NOTAS DE CRÉDITO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#640]
Hasta hace unos días nuestro único cliente del timbrador era de nómina.
Ahora como vamos palante, tenemos oootro cliente usuario del timbrador.
Pero resulta que en un CFDI, el tipo egreso aplica para nómina y también para nota de crédito.
Tons, en su momento definimos que sería nomina el tipoCF, siempre que su tipo fuera egreso.(no teníamos otra opción)

OK, ahora en nuestra evolución, necesitamos identificar cuando se trate de nómina o cuando se trate de nota de crédito. Esto lo podrás distinguir por el complemento de nómina solo se incluye en un recibo de nómina, a diferencia de la nota de crédito, que es cfdi estándar.

Lo que se ocupa es:
a) Si se identifica nota de credito, tomar la plantilla que le corresponde por omisión, es decir cfdi_notaCredito.jrxml

b) el nombre del comprobante **nombreCF** debe ser nota de crédito o recibo de nómina según sea el caso.
c) está de sobra este punto, pero en el correo que envía la aplicación, incluye el nombre del comprobante fiscal en el asunto, y supongo que cubriendo el punto (b), entonces en automático enviará el correo con el nombre correcto... ya que hoy envia una nota de crédito, y dice que es un recibo de nómina... jejejeje
Cómo la bestia???

**Comment by RigoFlores** [comment]
Me comentaste que debería distinguir entre nota de crédito y recibo de nómina, eso está confirmado, o solo te lo fumaste en el candys, mientras una edecarne te hacía un praibet?

**Comment by jccastillo0007** [comment]
chiaaaa pos esta confirmado....
