### ISSUE TITLE
Para Figueacero enviar ademas del XML y PDF, otro PDF con ubicación y nombre fijo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#641]
Si el nombre puede ser dinámico, mucho mejor.
La ruta donde colocar dicho PDF, podría ser en la raiz del directorio de facturas...
Entre menos se metan a las carpetas del facturat, mejor.

**Comment by jccastillo0007** [comment]
almost done.., shiaaaaaa ya me corrieron de black coffee, ma;ana temprano le sigo.

**Comment by RigoFlores** [comment]
almost tested.... no maaaaa....
Pos pide mas café, o cerveza si estás en el candy's..

**Comment by jccastillo0007** [comment]
Listo... agregar en el facturat.properties, la siguiente leyenda :   

defaultPDF = /JC@/IT/FacturaT/CurrentRelease/jc.pdf

**Comment by RigoFlores** [comment]
Pos le probé de muy distintas formas en windows, y nomás no le dí
Necesito que me indiques la FORMA PRECISA de indicar el parámetro para windows
Incluso, tu ejemplo maneja espacios antes y después del '=', esos espacios no los tiene ni Obama, es decir, ningún otro parámetro ocupa espacios...
Esto también funciona, estoy suponiendo para el reenvio de facturas... y no depende del RFC emisor

Son supositorios que necesitas confirmar, ya que nomás no jaló...

**Comment by jccastillo0007** [comment]
mmmm no logre levantar el facturat en la maquina windows de mis hijos... podemos tener una sesion conjunta para arreglar este problema... los espacios que mencionas no deben afectar.

Y no, no funciona para reenvio de facturas, son flujos diferentes y no fué solicitado para este caso de uso._

**Comment by jccastillo0007** [comment]
por cierto en windows, me esta marcando que el sello no fué generado exitosamente, sabes que puede ser ?

Estoy usando mi cer y key.

**Comment by RigoFlores** [comment]
No tengo idea porque marque ese error. Entendería que ya se venció el sello o la contraseña no coincide.
Oye, estoy recordando que figueacero ÚNICAMENTE ENVÍA CORREOS desde la pantalla de consultas, por lo que este requerimiento SI DEBE CONSIDERAR INCLUIR EL PDF, desde el reenvío de las facturas.

Favor de considerarlo.

**Comment by RigoFlores** [comment]
2 semanas de atraso para NUESTRO CLIENTE MAS IMPORTANTE...!!!
Ojo, es el que mas ingresos nos genera, y no lo hemos atendido... imagínate...

**Comment by jccastillo0007** [comment]
Hoy me dedico a windows para sacar este pendiente

**Comment by jccastillo0007** [comment]
ya esta listo, la version 10.0.9 del dropbox.... solo enviará las facturas desde consultas, ya no al momento de facturar.

**Comment by RigoFlores** [comment]
Voy a validar, pero la petición NO fue quitar el envío de facturas cuando se emite la factura desde conector. 

La petición es enviar el PDF de promociones, junto con la factura... desde las consultas... pero el resto de la funcionalidad no se debe tocar.

De hecho esa función es básica para el grupo ETSA, y supongo algunos otros clientes.
Entendería que esto que comentas que ya no enviará, solo aplica para figueacero?

**Comment by RigoFlores** [comment]
Si entendí bien, solo se enviará desde consultas el PDF adicional.
El resto se mantiene como siempre.
