### ISSUE TITLE
Soportar Simultáneos Métodos de Pago por el Conector

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#642]
Me marcó el Hotel Colonial de Veracruz.

Dice que ahora si, deben reportar distintos métodos de pago de manera simultánea (esto se tenía que hacer siempre y no lo hacían.... pero ahora sí lo van a hacer).

Entonces la propuesta para ellos, es que envíen la cadena tal cual se incluirá en el XML y en el PDF, y nosotros a ciegas la colocaremos. Pero también, se deberá mantener la compatibilidad con lo anterior...

Ahora mismo tenemos:
metodoDePago=transferencia|6969

Evoluciona a:

metodoDePago=metodosXML|metodosPDF|NoCuenta

Es decir, si contiene 2 pipes '|', en lugar de 1, entonces pasamos lo que contiene la cadena al XML y PDF. Ejemplo:

**metodoDePago=01, 04|Efectivo, Tarjeta de Credito|1234**

Indicaria que al XML se envíe el '01, 04' con cuenta '1234', 

y al PDF se enviaría 'Efectivo, Tarjeta de Credito' con número de cuenta '1234'

Si solo contiene un pipe, entonces se comportará igualito que ahora mismo...

**Comment by jccastillo0007** [comment]
No es necesario cambiar algo en el conector, si mandan una de las leyendas
configuradas, el conector las va a parsear y le va a poner su respectivo
código, esto ya funciona lo puedes probar.

Saludos.
JC.

**Comment by RigoFlores** [comment]
A ver, no estamos entendiendo... dice SIMULTÁNEAS... no dice 'una de las leyendas'... se ocupa para cuando una factura se paga con mas de 1 método de pago... probé lo que comentas y me lo batea a 'NA'... jeje
Favor de leer cuidadosamente la petición...

**Comment by jccastillo0007** [comment]
a cabron... simultaneas ? ... tons hasta que vea el código, almenos un
método de pago si debe reconocerlo siempre y cuando este bien escrito,
conforme el catálogo del SAT

Saludos.
JC.

2016-07-12 11:59 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
no es necesario mandar códigos y leyendas, con que manden el código esta
bien, el sistema le asignará la leyenda correspondiente.

metodoDePago=01|02|03|04

no se debe mezclar el número de cuenta en el método de pago, si actualmente
no la recibimos, entonces agregamos otro campo

numeroDeCuenta=1234567890

Saludos.
JC.

2016-07-12 12:09 GMT-05:00 JC@Gmail jccastillo0007@gmail.com:

**Comment by RigoFlores** [comment]
Aunque uno si lo reconozca, la petición es distinguir cuando nosotros vamos a colocar la clave... tal cual funciona ahora mismo.

Y la otra opción es **# pasar sin ver lo que ellos quieran reportar al catálogo y el PDF**....

Te digo que hay que leer con cuidado la petición... creo que sigues sin entenderla

**Comment by jccastillo0007** [comment]
ya la entendí (creo) lo que ahora te estoy diciendo es la mejor forma de
hacerlo.

solo que manden el código separado por pipes de los n métodos de pago y en
otro dato el número de cuenta, cómo nosotros nos regimos por los catálogos
del SAT, ellos mandan el código y nosotros le colocamos la leyenda que le
corresponde, no sería válido que ellos le quieran poner una leyenda X
 diferente a la aprobada por el SAT, eso nos complica más la solución.

El sistema va a reconocer si trae n códigos o una leyenda (formato anterior)

Saludos.
JC.

2016-07-12 12:13 GMT-05:00 RigoFlores notifications@github.com:

**Comment by RigoFlores** [comment]
La idea es NO PEGARLE A TOOOOODOS nuestros clientes con conector, solo por esta petición del Hotel. Me extraña tu propuesta, porque le pegaría a todos.

a) Soportar lo mismo mismo mismo que hoy en día tenemos
b) Si quieren enviar libre captura en el método de pago, entonces una opción es mi propuesta, o de plano agregar una linea adicional que diga:

metodoDePagoLibre=metodoXML|metodoPDF|cuenta

y así no le pegamos a toooodos los clientes que no ocupan esta opción.

**Comment by jccastillo0007** [comment]
Negativo, este approach soportará ambas versiones, me extraña que creas eso
chiaaaaaa

Saludos.
JC.

2016-07-12 13:14 GMT-05:00 RigoFlores notifications@github.com:

**Comment by jccastillo0007** [comment]
Me extraña que te extrañe que no me diera cuenta...

Saludos.
JC.

2016-07-12 13:55 GMT-05:00 JC@Gmail jccastillo0007@gmail.com:

**Comment by RigoFlores** [comment]
Me extraña, que te extrañe, que me extrañe... ya que siempre ha sido extraño esta funcionalidad tan extrañamente complicada...

**Comment by jccastillo0007** [comment]
Entonces estos serán los formatos.

normal ya soportado :  
metodoDePago=Transferencia

nuevo :  
metodoDePago=01|03|05|29

la solución es backward compatible, me falta solo lo del número de cuenta

**Comment by RigoFlores** [comment]
Corrección... hoy en día así estamos:

metodoDePago=Transferencia|NoCuenta

A lo que tu quieres llegar, es que el número de cuenta ahora se ocupe para ooootro método de pago..

para mí tiene que ser mucho mas simple, y esto es agregar un nuevo renglón, para lo que ellos quieran reportar al SAT:

metodosDePago=metodosPagoXML|metodosPagoPDF|cuenta

ellos reportarán a COMO ENTIENDAN E INTERPRETEN la miscelánea fiscal. Nosotros solo enviamos al XML los métodos de pago que indiquen, mismo caso para el PDF (como lo quieran presentar)... y finalmente la cuenta se va para ambos archivos.

Dado que por lo pronto solo tenemos un cliente que lo está YA PIDIENDO, entonces primero busca la cadena actual, y en segundo término la cadena nueva... para darle prioridad a lo actual...

**Comment by jccastillo0007** [comment]
mmm se complica el traslado de dos datos de metodos de pago, lo que va al xml y lo que va al pdf, normalmente solo arrastro uno de ellos, y al momento de mandar la info a jasper se traduce en la leyenda que le corresponde, pero aqui se esta solicitando arrastrar ambos datos y no interpretarlos ni validarlos, lo cual se sale de la lógica de como funciona FacturaT.

**Comment by jccastillo0007** [comment]
Asi queda:  
actual:
metodoDePago=Transferencia|NoCuenta

nuevo
metodoDePago=01|03|29
numeroDeCuenta=1234567890

Se soportan ambos approaches

peeeeeero todavia no esta listo.
Lo de cancelar facturas y lo del pdf de figueacero ya quedo listo...

**Comment by RigoFlores** [comment]
NO jaló:
esto mandé en el archivo texto
metodoDePago=01|02|03
numeroDeCuenta=1234567890

esto reportó en el XML
metodoDePago="99,99,99,"  NumCtaPago="1234567890"

El método de pago no lo interpretó correctamente para el XML, además que LE SOBRA UNA COMA AL FINAL.
En el PDF, aparentemente lo envió bien: 01.EFECTIVO,02.CHEQUE NOMINATIVO,03.

**Comment by jccastillo0007** [comment]
Fixed.
