### ISSUE TITLE
Web - agregar chekbox para incluir o nó, la información complementaria dentro del XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#644]
Darle facilitades al cliente para que controle si quiere enviar la información complementaria al XML, como parte de concepto

Si el checkbox se habilita, entonces al XML se envía:

concepto (XML) = concepto + " " + descripcion + " " + informacionComplementaria.

los 2 primeros campos son del catálogo de clientes, y el último se toma de la pantalla de agregar producto.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
En una misma factura, agregué 2 productos. A uno le indiqué que si incluyera la información complementaria y al otro no. Lo incluyó en los 2.
Además cada ocasión que quiero editar un producto ya agregado a la factura, no me presenta la información complementaria previamente capturada, por lo que si la vuelvo a capturar, la duplica en la descripción del producto
Finalmente, los enters los agrega con un caracter extraño en el XML. Hay que suprimirlos por espacio, como ha sido siempre.

**Comment by jccastillo0007** [comment]
a cabron... esa funcionalidad se requiere por producto ..... mmmmta

**Comment by RigoFlores** [comment]
Pues'así'lo'planteaste,'es'decir'tu'colocaste'el'check'box'a'nivel'producto.
si'se'puede'colocar'a'nivel'factura'también,'si'eso'te'lo'hace'mas'simple.
No'le'veo'demasiado'demasiado'problema,'pero'si'lo'puedes'manejar'a'nivel'producto,'queda'de'alto'pedorraje'la'solución...'tu'dirás

**Comment by jccastillo0007** [comment]
Listo en PRU... ya agrega la info complementaria solo de los productos seleccionados, y ya te muestra la info complementaria si lo editas (después de agregarlo a la factura), no te recuerda si elegiste o no el checkbox de info complementaria, pero si lo hace bien

**Comment by RigoFlores** [comment]
Lo voy a cerrar por el tema que ya permite seleccionar y respeta, cuál producto si incluye y cuál producto no en el XML.
