### ISSUE TITLE
La última versión, ya no cancela las facturas del grupo ETSA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#645]
Escenario:
Conector, formato levicom II, ellos cancelan colocando un archivo con nombre y formato específico.

Estuvimos trabajando todo el tema del timbrador, pero el resto de los RFC's trabajan con conector.
Marca el error que mandé por correo...

**Comment by jccastillo0007** [comment]
fixed, el error se metió con el cambio de tipo de dato del folio de int a long para soportar las facturas de bancomer.

**Comment by RigoFlores** [comment]
Oye, y eso no pega en otra cosa... esos cambios que aparentemente son 'solo de tipo', ya vimos que nos afectan... donde mas podría pegar?

**Comment by RigoFlores** [comment]
Ahora marca que no encuentra el archivo para cancelar... no le pegó también este asunto?
Para el grupo ETSA, los archivos tienen una nomenclatura particular, y una ubicación particular... igual y es eso.
Estoy haciendo las pruebas en pruebas, y lo que esperaba es que me indicara que no se pudo cancelar, pero marca que no encuentra el archivo XML.

**Comment by jccastillo0007** [comment]
según mis pruebas y la revisión de código que he hecho, todo esta bien,  lo que me deja pensar una de dos:  
1. La serie y folio del archivo que estas intentando cancelar no se encuentra en tu base de datos
2. El archivo xml correspondiente a la serie y folio que estas intentando cancelar, no existe en la ruta especificada

Puedes volver a checar esas dos opciones... si aún asi, crees que algo esta mal, voy a necesitar tu base de datos y el archivo XML que intentas cancelar.

**Comment by RigoFlores** [comment]
Mi prueba fue desde cero, es decir primero generé la factura... con un XML (timbrador), y posteriormente lo intenté cancelar y dice que no encuentra el archivo.
OK, me fui mas patras aún, generando una factura desde un archivo de texto, para luego intentar cancelarlo y tampoco halló el XML.
Rregresé al origen. Con una llave normal (ya no del grupo etsa); borré toda la BD para evitar que se esté confundiendo... le puse un archivo de texto para generar la factura y la hizo. Tomé el XML, y lo puse en el directorio de archivos planos para cancelar y pues tampoco hizo ni madre..
como que ya no jala nada de cancelación por conector...

**Comment by RigoFlores** [comment]
Acabo de probar con la última versión.
De las facturas del grupo ETSA, que se cancelan a partir de un archivo de texto en particular, no está jalando.

**Comment by jccastillo0007** [comment]
entonces ya no cancela nada de ningún cliente ?

Pasame tu BD y los archivos que estas utilizando para probar.

**Comment by RigoFlores** [comment]
La BD, como dije está limpia... borré todo el histórico.
Voy a documentar todos los escenarios. Son un chingo... neta que esto me quita un chingo de tiempo... ni pedo..

**Comment by jccastillo0007** [comment]
no es necesario documentar todos los escenarios, el problema debe ser el mismo... solo necesito uno para poder reproducirlo... entonces voy a intentar como tú, con una base de datos limpia.

**Comment by RigoFlores** [comment]
Yo creo que si, ya que fixeas uno y le pegas a los demás...
Creo que es importante que tengas claro, todos los escenarios... al menos los mas importantes, para que cuando le estás pegando a algo, por lo menos voltees a ver lo demás, porque siento que ya es un desmadre, y cada versión un distinto cliente brinca... y no solo eso, tenemos detenidos pagos por todos esto

**Comment by RigoFlores** [comment]
Estoy separando cada escenario de pruebas... me tomará un tiempo separar cada uno de ellos en una instalación independiente

**Comment by RigoFlores** [comment]
el pedo es que en pruebas se comporta distinto.... yo esperaba un falla en el proceso de cancelación, y nunca lo envió
Hice la prueba directamente en pruebas con el cliente, y ya lo canceló...
Tons ya no entendí...
Espero que si cancele en todos los demás escenarios

**Comment by jccastillo0007** [comment]
mmmmmmmta... osea que el cliente y yo si podemos procesar el archivo  pero tú no... tons ya no hay delito que perseguir ?

**Comment by RigoFlores** [comment]
A ver otra vez... para no confundirnos.... este issue se abrió porque el cliente reportó que con la versión 1005, YA NO PODÍA CANCELAR, y con la versión anterior SI PUDO CANCELAR, tons le dió regresión.
Luego tu enviaste la corrección, que era por el tipo longnosequemadres...
Luego YO ESPERABA QUE LA APLICACIÓN EN PRUEBAS me mandara el mensaje de error en la cancelación, pero eso ya hasta el final de todo el proceso (eso si lo hacía antes, estoy seguro)..
Entonces, como en pruebas se trababa la aplicación (como que no regresaba de alguna petición), yo seguí con la línea que no funcionaba, ya que ANTES NO SE TRABABA EN PRUEBAS.

Entonces pensé que quizás era el ambiente, y le pedí al cliente su log de cuando no pudo cancelar.
Ahí me dí cuenta que el proceso en pruebas, se trababa en una llamada o algo así.
Le pedí al cliente que probáramos la nueva versión directamente en producción para validar un comportamiento que en pruebas era muy distinto.
Total que con la última versión, apuntando a producción ya pudo cancelar. 
En pruebas no se puede cancelar
Y lo que no sé, es cómo tu si pudiste cancelar una factura con su formato específico en pruebas, me parece muy raro...
