### ISSUE TITLE
Agregar Método de Pago para Emisión de Recibos de Nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#646]
No quedó claro el requerimiento... y ya tenemos el tiempo encima
a) Agregar método de pago a nivel individual (OK)
b) Colocar por default, método de pago = 'NA', para hacerlo compatible con el NO IDENTIFICADO, que ahora mismo asignamos a lo cabrón.
c) El método de pago, va acompañado por el NUMERO DE CUENTA, que para algunos métodos de pago es obligatorio. Esto no lo incluiste en la pantalla de nómina... chiaaaaaa
d) En nómina con un solo click, agregar el método de pago y cuenta, que aplique para todos los empleados, y además que lo almacene en sus respectivos registros

De todo, solo el punto (a), se cubrió. El punto (d), dijimos que podría esperar un poco... esto es, un par de días... pero b y c son a huevo, y eso entra a partir de mañana como obligatorio..

**Comment by jccastillo0007** [comment]
ya quedo C, pero b no me funcionó.... 
El punto d, esta medio jalado porque no creo que sea el mismo método de pago para todos o si?

**Comment by RigoFlores** [comment]
no asigna en pantalla el NA para los empleados ya capturados, pero al momento de timbrar sin haber realizado cambio, si le asigna el NA.
También cuando cambias y grabas un nuevo método de pago, si lo almacena y reporta en el XML.
