### ISSUE TITLE
POR CONECTOR, CAMBIAR EL MÉTODO DE PAGO POR DEFAULT DE NA A OTROS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#649]
HOY EN DÍA CUANDO NO RECONOCE EL MÉTODO DE PAGO, ACORDAMOS QUE LE ASIGNA "NA"
LA PETICIÓN ES CAMBIARLO A "OTROS"

UNA PREGUNTA SE PUEDE HACER QUE SI POR EJEMPLO ELLOS PONEN:

"TARJETA DE CREDITO AMERICAN EXPRESS", CÓMO MÉTODO DE PAGO... LO IDENTIFIQUE COMO TARJETA DE CRÉDITO?

**Comment by jccastillo0007** [comment]
Chiaaaaa, ya decidete.... pareces vieja, primero si luego no, luego me duele la cabeza jajaja

Con respecto a la pregunta, la respuesta es no, pueden poner Tarjeta o Credito y podría interpretarlo como Tarjeta de Credito, pero las palabras American Express, o cualquier otra provocarían que no se encontrara ninguna relación.

**Comment by RigoFlores** [comment]
Lo ideal sería dejarlo configurable, para que el cliente se atienda solo...

**Comment by jccastillo0007** [comment]
Chiaaaaa

Fixed.

**Comment by RigoFlores** [comment]
Ahora ya no reconoce el NA, ya que le asigna Otros.

El requisito es que reconozca todo el catálogo.
También debe reconocer NA.

Cuando no coincida nada con el catálogo o con NA, entonces le asigna 99.Otros, que sería el dafault.

De hecho, como comenté, lo ideal sería que ese default, se pudiera configurar para que sea lo que el cliente indique: Otros o NA.

**Comment by jccastillo0007** [comment]
chiaaaaa a que desmadre....

Ahorita voy a subir otro release con este fix.

No dejes que el cliente decida, si no, va armar un desmadre y pedir muchas más opciones.
