### ISSUE TITLE
CUENTAS POR COBRAR - SPEC INICIAL

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#65]
Agregar al catálogo de clientes, además del número de cuenta para temas del método de pago:
a) Transferencia - Se debe agregar el banco.
b) Cheque.- Banco, Número de Cheque
c) Tarjeta Crédito.- Tipo (Visa, Master Card, American Express, etc), Número últimos 4 dígitos, Banco (opcional)
d) Tarjeta Débito.- Número (últimos 4 dígitos), Banco (opcional).

Un cliente, podrá tener asociados varios métodos de pago.

Al momento de generar la factura, se deben considerar el estatus (no estoy seguro que este estatus, sea complementario al que manejamos de vigente o cancelada. Posiblemente vigente significará pagada o por cobrar):
1) Pagada
2) Por cobrar
3) Cancelada

El estatus por omisión, al momento de generar la factura, será Pagada.
Al estatus, se le debe asociar una fecha de pago programada. Si cuando se genera la factura, ya está pagada, la fecha de emisión y la fecha de pago, serán la misma.
Cuando una factura ha sido pagada, se deberá indicar el método de pago, junto con los datos asociados al mismo. (ver primer párrafo de este rollote).

Cuando una factura no ha sido pagada, se deberá capturar la fecha comprometida o estimada de pago, así como el método de pago esperado (una opción es No Identificado). Estos datos podrán ser modificados por el usuario.

Cuando una factura ha sido cancelada, deberá cambiarse el status de la misma.

Finalmente, el usuario podrá generar un reporte de cuentas por cobrar, con los filtros muy similares a los de consulta, agregando el status de la factura, respecto a su cobro: todas, pagada, por cobrar, cancelada.
El reporte generado por excel, deberá incluir el método de pago, así como el correo(s), teléfono(s) y nombre(s) del contacto(s) del cliente. (para propósitos de poder contactarlo, para realizar la gestión del cobro, en caso de ser necesario).

**Comment by jccastillo0007** [comment]
implementado en ERP.

**Comment by jccastillo0007** [comment]
Hay que cerrar este issue, chiaaaa

**Comment by RigoFlores** [comment]
Pues nunca se atendió completamente... en ese entonces ni siquiera había aparecido la econta, y ahora muchas de las cosas de la econtabilidad, aquí se plantearon hace ya 3 años....
Cuentas por cobrar, ni siquiera genera un reporte de los clientes que me deben, fecha compromiso de pago, y montos totales... que hacemos?

**Comment by jccastillo0007** [comment]
Expired.

Puedes abrir un ticket por cada una de las cosas que faltan para poder llevar el tracking.
