### ISSUE TITLE
Ejecutar migración FULL de escritorio a web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#651]
FULL = tablas de productos (implica asegurar unidades y monedas), clientes, histórico de facturación, documentos XML y P#CDMX

Se encuentra la documentación en el drotbots... C:\Users\Rijo\Dropbox\FacturaT\MIGRACION_DSI920716DI7

Les pedí que dejaran de facturar, así que tenemos que entregarles ASAP. Podemos hacerlo en 2 etapas, primero BD, y luego los documentos. 
Pero EL LUNES A PRIMERA HORA, tendría que estar al menos la BD.

**Comment by jccastillo0007** [comment]
ok, work in progress....

**Comment by jccastillo0007** [comment]
Listo, solo faltan los documentos.

**Comment by RigoFlores** [comment]
En el catálogo de productos, está duplicado el producto/servicio con la descripción de productos.

¿Con que query puedo eliminar la sección de descripción?
