### ISSUE TITLE
Ejecutar OTRA OTRA OTRA migración full de escritorio a WEB para el LUNES igualmente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#652]
Ahora se trata de otra migración ubicada en el dropbox en:

C:\Users\Rijo\Dropbox\FacturaT\MIGRACION_CRM9708218N8

OJO, al igual que la otra migración que ya 'está en progress', en este caso, empezaremos con el acceso, y subiendo la BD completa al Web, para que puedan retomar su facturación a partir del LUNES.
Los archivos XML y PDF, aún no los tengo ya que son demasiados y no los pude traer con un copy paste, son mas de 2 Gb comprimidos, de PDF y XML, sin PNG.

Esto me hace recordar que tenemos un issue de espacio en disco duro.

**Comment by jccastillo0007** [comment]
Asi es... voy a revisar cuando espacio podriamos liberar si limpiamos un
poco la base de datos, eliminando 2010 y mediados de  2011.

JC

Saludos.
JC.

**Comment by RigoFlores** [comment]
Porque mejor no les vendemos al cliente la idea, de que mas de 5 años, ya tienen que pagar por almacenamiento? Yo creo que les interesaría. Unos $1,000.00 anuales. 
Si no quieren, les notificamos que borraremos su información, para que la respalden o hagan lo que quieran.

OTRA. No podemos indicarles a los clientes que en 'en línea' tendrán los 2 últimos años, y el resto de información sería a petición? ¿Eso nos facilitaría?

**Comment by jccastillo0007** [comment]
Ya esta lista la migración, solo me faltan lo archivos.

Bastante buena tu idea, y para almacenarlos, los podemos mover a DigitalOcean

Quieres que te diga que clientes son los que están en este caso ?

El tema de los 2 últimos años, no esta mal, pero se puede convertir en una molestia para nosotros... ahora que si entra dentro del pago de 1000 anual, entonces si... jojojojo

**Comment by RigoFlores** [comment]
Está al igual que la otra migración, duplicando la información de producto/servicio, con la descripción... esto en la pantalla de catálogo de productos...
Necesito el query para borrar la sección de descripción para estos 2 clientes...
