### ISSUE TITLE
Establecer el procedimiento para manejo de información histórica en el web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#655]
Me has comentado que ya está muy saturado y requerimos espacio adicional.
Yo creo que la BD histórica la debemos mantener al menos 5 años por cliente.

Donde si podríamos maniobrar, sería con los archivos históricos (PDF y XML).
Esos podríamos mover lo de 3 años hacia atrás, a un repositorio en digital ocean, o donde nos cueste menos. 
Ahora si es almacenamiento únicamente, no convendrá tenerlo en discos nosotros mismos...?
Compramos un par de discos y almacenamos ahí la historia... una copia la tienes tu y otra la tengo yo... no sé, algo así... como la bestia?

**Comment by jccastillo0007** [comment]
Si, de hecho, yo tengo respaldo de todos los XML generados desde el mero principio, el problema vendría si empezamos a recibir peticiones de recuperar los XML puede ser muy tedioso... pero debería ser manejable por alguien de soporte, lo malo es que ahorita no tenemos... 
Con el cambio de tipo de respaldo acumulativo de Base de Datos, se liberó suficiente espacio y ya no estamos en peligro por lo menos durante el resto del 2016...

**Comment by RigoFlores** [comment]
te digo que necesitamos ubicar los logos de tamaño arriba de 100k...
