### ISSUE TITLE
Cerrar llave de finkok y edicom, a partir del 01 de agosto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#656]
Habíamos platicado que mañana 26 de julio.... pero es cierre de mes, y entonces nos complicaríamos nosotros mismos. 
A partir del 01 de agosto, puedes cerrar esa opción?
¿puedes implementar 'algo' que me permita abrir y cerrar dicha opción?

**Comment by jccastillo0007** [comment]
hmmmm dejame pensar como hacerle, pero de una reiniciada al tomcat no nos
salvamos ....

Saludos.
JC.

**Comment by jccastillo0007** [comment]
Listo... la llave ha sido cerrada, no pude hacer algún procedimiento amigable para hacer el switch, tons... si algo se pone feo me avisas y lo cambio ASAP.

**Comment by RigoFlores** [comment]
Nos traen como sus pendejos los de facturehoy.
Hoy me dí cuenta que ahora ya permiten nuevamente que se maneje como antes estaba.... según ellos por linea del SAT... la neta están pendejeándola mucho y a nosotros nos llevan entre las patas...
