### ISSUE TITLE
Optimizar el espacio requerido en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#657]
Necesitamos conocer cuáles logos miden mas de 50k, eso ya es mucho.
Tenemos que actualizar dichos logos a un tamaño mas pequeño.
Quizás regenerar todos los PDF's que tengan un logo mas grande a 50k

Limitar en la configuración, que suban logos mas grandes a 50k, con un mensaje para que se depure.

**Comment by jccastillo0007** [comment]
Por ahora, optimicé el proceso de respaldos de la base de datos, se saca un respaldo diario pero, es acumulativo, es decir, siempre tendremos el backup del día anterior, pero no de más atras... considero que esta bien, ya que no es factible tratar de regresar la base de datos a muchos días atras, y de hecho nunca lo hemos utilizado.

Como quiera voy a seguir viendo lo de los archivos muy grandes, pero por ahora ya no hay prisa.

**Comment by RigoFlores** [comment]
Cuando cambié de logo, a uno mas pequeño para una de las migraciones que hicimos, ocupó 58 veces menos espacio que el original...!!!!
Tu dirás si no ahorra espacio este asunto..
