### ISSUE TITLE
nomina - empleados no permite guardar después de editar el registro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#659]
Al momento de editar - guardar, marca el sig error:

'25/11/68;25/11/68;;25/11/68;' no es un Date válido.
El campo 'Periodicidad de pago' es obligatorio.

La fecha, la elegí con el calendario, y la aplicación la duplica.
El campo periodicidad de pago no existe para captura... pero es obligatorio... jejeje

**Comment by jccastillo0007** [comment]
fixed.
