### ISSUE TITLE
Incorporar Cancelación de Facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#66]
Agregar cancelación de Facturas al estanalon y web.

**Comment by RigoFlores** [comment]
CADA CLIENTE NUEVO, LO ESTÁ PIDIENDO.
HOY FUERON 2 CLIENTES QUE PRÁCTICAMENTE ME LO CONDICIONAN PARA CONTRATAR...
CÓMO VAMOS?

**Comment by jccastillo0007** [comment]
done
