### ISSUE TITLE
Concluir la migración para CRM9708218N8, esto es los XML y PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#664]
Ya los subí al drotbots..,

**Comment by jccastillo0007** [comment]
oye, ya se que vas a decir que no mame, pero me puedes pasar los archivos pdf y xml en un zip sin carpetas.. es decir, todo en un solo folder, según yo en Windows es posible con el winzip, pero en mac no encontré la opción adecuada... ya tengo todo listo para subirlos en chinga... pero me tardo mucho en moverlos de cada carpeta a una sola.

**Comment by RigoFlores** [comment]
Pues si, sobre todo que ya tenemos un rato con este tema, y apenas dices como necesitas la distribución de los archivos.
Ya está listo

**Comment by jccastillo0007** [comment]
Done.
