### ISSUE TITLE
Implementar Addenda SANOFI para el addendador

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#666]
Ahora mismo tenemos la addenda sanofi, únicamente generada desde la pantalla de facturación.
1. Lo que se requiere es poderla agregar desde el addendador.
2. También se ocupa que el esquema actual, sea compatible con el anterior.

https://mexico.sanofi.com/schemas/sanofi.xsd

¿Cuál es el detalle? esta addenda maneja 2 datos extra a nivel producto.
Entonces para el addendador, debemos detectar cuántos productos incluye el XML ya timbrado, para solicitar los 2 datos extra por cada producto incluido.

**Comment by jccastillo0007** [comment]
Por un lado, los esquemas son idénticos, según text wrangler, y por otro lado, yo no podría hacer que fueran compatibles, el addendador debe generar una addenda en base a un schema y no en base a dos schemas.

Lo que no entiendo es a que te refieres con solicitar los datos extras por cada producto?... en realidad el addendador lee el xml y lee el archivo de datos extras y genera la addenda... los datos extras ya deben tener todo lo necesario

**Comment by jccastillo0007** [comment]
Por cierto, el addendador ya funciona de forma transparente para agregar la addenda sanofi, lo acabo de probar... solo faltaria lo de los dos datos extras a nivel producto, necesito entender bien como estas pensando resolverlo con eso de "solicitar"

Según yo, hay que agregar dos datos extras en el archivo por cada producto, con cierta nomenclatura, pero habría que saber cuantos productos van a procesar, para que agreguen los datos extras.

**Comment by jccastillo0007** [comment]
Ya vi lo que dices de solicitar los datos extras a productos y si se puede... 

ya estará listo para ma;ana temprano.

**Comment by jccastillo0007** [comment]
esta listo en PRU... me avisas si te funciona bien para subirlo a PRO en chinga loca <como la mudanza>

**Comment by RigoFlores** [comment]
Oye, pero como quedó el XML de los datos de la addenda?
No es dinámico, dependiendo del número de productos?
Como quiera, mándame el XML de datos extra de la addenda

**Comment by RigoFlores** [comment]
sino, como puedo probar?

**Comment by RigoFlores** [comment]
cuando capturas los datos vía el addendador, marca error de que faltan datos, cuando no capturas observaciones.
Las observaciones son opcionales dentro de la addenda.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Ok, favor de colocar en producción. 
Por cierto está función que dinámicamente solicite datos, dependiendo del número de productos dentro del XML, hay que bautizarla. Será de mucha utilidad, y de hecho en el addendador pilgrims debería implementarse, pero bueno por lo pronto hay que referirla como: "Datos Extra Pro Dinámicos"????
