### ISSUE TITLE
agregar FXA740814UQ6 para addenda sanofi

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#668]
es el nuevo

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Creo que ya me confundí.... este RFC es el nuevo rfc emisor (cliente nuestro), mismo que tratando de entender mi confusión, NO SE REQUIERE DAR DE ALTA DENTRO DEL CÓDIGO DE ADDENDA SANOFI.

Los que si se ocupan (me parece), son los RFC's de los receptores, ante lo cual el RFC receptor que se debe dar de alta es **# SAM951123978.**

Si mi confusión ha sido desconfusionada, pls da de baja el RFC originalmente solicitado en este issue, ya que es del emisor (cliente nuestro), y dar de alta el RFC del receptor (de la addenda).

**Comment by RigoFlores** [comment]
Ya ni me acordaba de esto, pero ya vi que el emisor dentro del  XML a addendar, debe ser el mismo de la llave (el cliente nuestro puesn), sino pinta cremas, lo cual es muy adecuado.

Necesito probar con el rfc receptor nuevo  # **

> SAM951123978

**

**Comment by jccastillo0007** [comment]
Ese cliente ya esta dado de alta desde el mero principio que hicimos la addenda sanofi, luego entonces, si puedes probar tanto en pru y pro.

**Comment by RigoFlores** [comment]
Solo para estar bajo el mismo entendimiento, el RFC SAM951123978, ya existe como 

RECEPTOR DE LA ADDENDA, RECEPTOR DE LA ADDENDA, RECEPTOR DE LA ADDENDA?

Te digo que confundí todo, pero este es el RFC que había que agregar como receptor de la addenda. Igual y cuando la implementamos, el cliente entregó el listado de RFC's y si está este.

**Comment by RigoFlores** [comment]
Ya ví, si ya existe... nos lo pasaron en la primera vez.
