### ISSUE TITLE
llevar a pro la versión 1.1 del INE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#669]

**Comment by jccastillo0007** [comment]
la versión que subí hoy a las 5 pm, ya trae la versión 1.1 del complemento INE

 Vi que generaron un XML y FactureHoy regresó esto ::  
2016-08-03 10:26:45,891 DEBUG [http-8080-8](CFDiController.java:173) -  isError : true
2016-08-03 10:26:45,892 DEBUG [http-8080-8](CFDiController.java:174) -  UUID :
2016-08-03 10:26:45,892 DEBUG [http-8080-8](CFDiController.java:175) -  Fecha/Hora timbrado: null
2016-08-03 10:26:45,892 DEBUG [http-8080-8](CFDiController.java:176) - Link/Ruta Acuse Recepcion SAT: FH22 - Datos mínimos o formato de datos del XML incorrectos

Pero eso no es de nuestro   lado... tal vez le falte algo al XML que se creo

**Comment by RigoFlores** [comment]
Acabo de realizar una prueba en PRO, la misma que hice en PRU, y sigue igual, sin jalar.
Lo que me hace pensar 2 cosas:
a) No es el mismo código
b) FactureHoy (PRO) está validando algo adicional que Edicom (PRU) no valida

No sé si está de nuestro lado o no, pero las fechas que se envían previo al timbrado dentro del XML, siempre las colocamos nosotros. 
Y la fecha/hora timbrado, no sé en que momento se debería agregar...

**Comment by RigoFlores** [comment]
Encontré cosas adicionales:

Para la versión 1.1, en pruebas que es donde si timbra, en el schemalocation, apunta a la versión 1.0 del complemento.

http://www.sat.gob.mx/ine 
http://www.sat.gob.mx/sitio_internet/cfd/ine/ine10.xsd

En el estándar del complemento v1.1, entiendo que apunta a:

http://www.sat.gob.mx/ine
 http://www.sat.gob.mx/sitio_internet/cfd/ine/ine11.xsd "

Por otro lado, buscando en el portal del SAT, indica que la versión 1.0 será vigente hasta el fin de agosto, y la versión 1.1 será obligatoria a partir del 01 de septiembre.
Con ello entiendo que no hubiese sido necesario cambiar la versión (o no lo sé), pero el chiste es que envía el mismo error en producción, tanto en la versión 1.0 como en la versión 1.1 (aunque reporta xsd 1.0)

**Comment by jccastillo0007** [comment]
Done... esperemos a Septiembre para liberar la 1.1

**Comment by RigoFlores** [comment]
Pendiente la sesión con FactureHoy...

**Comment by jccastillo0007** [comment]
El problema de timbrado de facture hoy, no debe detener el cierre de este ticket, ya que comprobamos que edicom si lo timbra bien.

**Comment by RigoFlores** [comment]
Con la versión 1.0 si, pero con la versión 1.1 no.
Este ticket solicita llevar la versión 1.1 a partir del 01 de septiembre.
Lo dejamos abierto, no?

**Comment by jccastillo0007** [comment]
done.
