### ISSUE TITLE
Metodo de Pago y Numero de cuenta, no se despliegan correctamente en PDF y XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#67]
En el PDF método de pago está chueco con respecto a forma de pago (igual y es consecuencia de una plantilla obsoleta).
El número de cuenta no se incluye en el XML.
En el XML, el método de pago SIEMPRE aparece como NO IDENTIFICADO..

**Comment by jccastillo0007** [comment]
La version de hoy no era correcta, era una version de hace mucho tiempo, y tenia estos errores.

Favor de validarlos con la version actual

y pasame las plantillas, ahi no debe haber ningun cambio respecto a tus anteriores pruebas.
