### ISSUE TITLE
Menú de Reporte de Folios en el keygenerator no jala

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#670]
Me manda al internal error... y se ocupa para enviar el correo de notificación de folios próximos a vencer...

**Comment by RigoFlores** [comment]
Ya entró, pero le di enviar correo y no me llegó ninguno a mí.... no se si a los clientes les habrá llegado, cómo puedo saberlo??

**Comment by jccastillo0007** [comment]
faltaba subir el archivo txt con todos los emails de los clientes, ya lo subí y ya lo disparé, debes tener chingo de correos en tu inbots.

**Comment by RigoFlores** [comment]
Y si tenías la última versión de ese archivo? ya que lo actualizo cada cierto tiempo.
