### ISSUE TITLE
Adecuación Conector Optibelt OME111223UN4

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#671]
Es el formato Levicom II
Es conector, el sistema de ellos es AS400, y cualquier cambio por mínimo que sea, lo deben pedir a los alemanes en la matriz.

Por ello requieren que cuando el método de pago sea reportado como "Recibo", este sea traducido o entendio como "NA", para que se reporte así al XML y PDF.

**Comment by jccastillo0007** [comment]
Done, release 10.0.10, hay que hacer pruebas antes de liberarlo eeeeeeh.

**Comment by RigoFlores** [comment]
ok, ya hice varias pruebas, y también con conector estándar... al parecer todo bien
