### ISSUE TITLE
CFDI v3.3 Catálogo de Monedas - 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#672]
En el CFDI v3.3, se manejarán alrededor de 23 catálogos. Según yo, vale la pena poder capturarlos en tablas para ser desplegados, o en otro caso, tener muy claro y a la mano la manera de que hasta yo pueda modificarlos cuando sea necesario.

1) Para monedas distintas al MXN (peso mexicano), requerir capturar el tipo de cambio
2) Para moneda igual al MXN, no será necesario solicitar el tipo de cambio, ni enviarlo al XML
3) Para todo tipo de moneda, solicitar la leyenda que desplegará en la cantidad con letra, para la moneda en sí, así como para el sufijo que se agregará al final de la cantidad con letra.
Ejemplo:
Moneda: MXN
Tipo de cambio:      (no se requiere para MXN)
LeyendaCantidadconLetra: Pesos
Sufijo: M.N.

Es decir estarían faltando 2 campos, para mostrar en el catálogo.

En la adecuación a producción de estos nuevos campos, de cara a lo que se tiene ahora mismo, se llenarían de la siguiente manera:

Moneda: MXN
TipoCambio: vacío
LeyendaCantidadConLetra: PESOS
Sufijo: M.N.

Para cualquier otra moneda:
Moneda: USD
TipodeCambio: 19.00
LeyendaCantidadConLetra:USD   (es decir sería igual que el dato moneda)
Sufijo:       (vacío; ellos lo llenarían de acuerdo a sus necesidades).

la cantidad con letra, queda:

veinte PESOS 15/100 M.N.

**Comment by jccastillo0007** [comment]
Voy a cerrar el ticket 986, nos quedamos con este, chiaaaa no se trata de crear tickets de mas.... solo se puede refrescar o agregar un comentario extra, para que se mueve a los más recientes.
