### ISSUE TITLE
Addendador SANOFI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#674]
Para los datos dinámicos a nivel producto:

a) Por omisión, presentar "0000000000" (diez ceros), tanto para puente como para entrada, con la opción de que ellos lo puedan cambiar.
b) Agregar un dato adicional por cada producto, y este sería 'Unidad de Medida', ya que el sistema actual del cliente (muy pinchemente), no permite cambiar la unidad de medida (que pedo con eso??).

**Comment by jccastillo0007** [comment]
what ?

A que te refieres con puente y entrada... esos datos no se usan en la addenda sanofi, y además recuerda que los datos default se configuran en el archivo xml de datos extras de addenda

**Comment by RigoFlores** [comment]
![sanofi](https://cloud.githubusercontent.com/assets/2912775/17682668/9ec6cb12-6312-11e6-86e3-f8be088071b4.png)

como a que me refiero, son los 2 datos dinámicos que se presentan ahora (no parten del XML de configuración). Solo hasta que se elige el XML es que se agregan dinámicamente. Tons, ya que los agregamos, necesitamos inicializarlos con 10 ceros, amén de agregar el dato que corresponde a la unidad dentro de los datos de la addenda a nivel producto. 
Hoy en día la unidad se toma del XML ya timbrado, pero su pinche programa no puede personalizar unidades, y por ello tendrán que capturarla en la addenda

**Comment by jccastillo0007** [comment]
ah es que estaba viendo los datos a nivel general.
Lo que no puedo hacer, es agregar datos para 1 producto, si el xml no trae productos.... no sé si eso me pediste pero eso entendí.

**Comment by RigoFlores** [comment]
chiaaaaa...
Lo que estoy pidiendo, es que en los datos que ahora son dinámicos (dependiendo del número de productos en el XML ya timbrado), se inicialicen con 10 ceros.
Además, en lugar de solo 2 datos extra a nivel producto, agregar dinámicamente un tercer dato, que será la unidad de medida... chiaaaaaa

**Comment by jccastillo0007** [comment]
ah ok... tons ya esta listo

**Comment by RigoFlores** [comment]
no, pues no veo ni una cosa (inicializar con 10 ceros), ni la otra (agregar el nuevo dato extra dinámico a nivel producto llamado 'unidad de medida')..

**Comment by jccastillo0007** [comment]
chiaaa pos todavia no lo subia

**Comment by RigoFlores** [comment]
CUANDO LE CAMBIO EL DATO DE UNIDAD DE MEDIDA (QUE PARA ELLO SE SOLICITÓ), SI LO CAMBIA EN LA PANTALLA, PERO EN EL XML CON ADDENDA, SIGUE MANTENIENDO LA UNIDAD DE MEDIDA DEL XML ORIGINAL.
CHIAAAA....

**Comment by RigoFlores** [comment]
??

**Comment by jccastillo0007** [comment]
ya esta listo... te mande correo según yo

no, ya vi, te avise por skype... esta listo en PRO

**Comment by RigoFlores** [comment]
sigue-sin-jalar....ahora-si-yo-capturo-unidades-distintas-en-cada-producto,-les-asigna-LA-MISMA-unidad-a-todos-los-productos-dentro-de-la-addenda.
Wey,-esto-debería-ser-algo-simple-y-rapido....

**Comment by jccastillo0007** [comment]
pssss pues si, pero no todo resulta ser tan fácil como se cree...
Pero bueno, ya esta listo... en PRU y PRO, ya lo probé con múltiples productos.

**Comment by RigoFlores** [comment]
OK, DICES QUE EN PRO YA ESTÁ, TONS HOY ENTREGO..
