### ISSUE TITLE
Pasar a la tia a timbrar con FactureHoy desde Pro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#675]
Para hacer la prueba del complemento INE 1.0

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
ya timbró facturehoy, con la versión 1.0 en producción. Le hiciste algo?
Supongo que ellos si..
Puedes mover a la cliente MAHP4803129K5 de regreso a facturehoy?
