### ISSUE TITLE
EN PRODUCTO LE AGREGA UN &#xD; EN EL XML CUANDO INCLUYE UN ENTER

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#676]
EN DESCRIPCIÓN DEL PRODUCTO O EN INFORMACIÓN COMPLEMENTARIA, CUANDO SE INCLUYE ENTERS, Y LO MANDA AL XML, LE COLOCA LA SECUENCIA DE ESCAPE ME IMAGINO &#xD;
ANTERIORMENTE LO SUSTITUÍAMOS POR ESPACIOS.
¿CÓMO QUEDA FINALMENTE?

**Comment by jccastillo0007** [comment]
fixed. ya le va a quitar los enters, lo malo es que lo mismo se va a mandar al pdf.

Listo en la versión nocturna de hoy.

**Comment by RigoFlores** [comment]
NEGATIVO, SI LE VA A QUITAR LOS ENTERS AL PDF, NO FUNCIONA.
AQUÍ LA PETICIÓN DE SER POSIBLE ES:

CUANDO CONTENGA ENTERS EN LA DESCRIPCIÓN O EN LA INFORMACIÓN COMLEMENTARIA, RESPECTARLOS PARA EL PDF Y EN EL XML CAMBIARLOS POR ESPACIOS. SI ESO NO ES POSIBLE, QUE SE QUEDE CON LA SECUENCIA DE ESCAPE ACTUAL, PERO QUE NO SE ELIMINE DEL PDF, NO MANCHES

**Comment by jccastillo0007** [comment]
o que pues.... decidete, se arregla o no... ya que lo había resuelto...

Dejame ver si puedo hacerlo por separado... chiaaaa pareces vieja...

**Comment by RigoFlores** [comment]
Yo nunca pedí que eliminaras enter del PDF, no manches... tu decidiste eliminarlos de puros tomiates... cómo crees, si son de los pocos elementos para formatear el contenido de una factura.

**Comment by jccastillo0007** [comment]
Fixed.... tal como tu lo esperas, se modifica para el XML pero no para el PDF, al rato la subo a PRO
