### ISSUE TITLE
Cuando incluyes la info complementaria, no le agrega el enter en el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#677]
Si no incluyes info complementaria en el XML, se comporta así en el PDF:

_Descripción del producto
Información complementaria_

Cuando SI incluyes info complementaria en el XML se comporta distinto el PDF:

_Descripción del producto Información complementaria_

Es decir, **cuando eliges si incluir info complementaria en el XML, concatena la información complementaria en lugar de respetarla con el enter despúes de la descripción del producto.**

**Comment by jccastillo0007** [comment]
mmmmmm , pues asi esta bien no? es que cuando agrega la info complementaria para el xml le quita los enters....

**Comment by RigoFlores** [comment]
Aquí el issue es que para propósitos del PDF, no debe cambiar su apariencia... independientemente si se incluye la información complementaria en el XML o nó.
Cuando no se incluye, todo es normal.
Cuando se incluye, elimina un enter que tiene esto es:

producto + <enter> + <descricpion> + <enter> + informacion complementaria

cuando le indicas que lo incluya en el XML, le elimina el segundo enter en el PDF, y no le veo razón para ello.

**Comment by jccastillo0007** [comment]
Fixed.
Ya debe estar resuelto con el fix del issue 676

**Comment by RigoFlores** [comment]
NO, SIGUE IGUAL

**Comment by jccastillo0007** [comment]
chiaaaa todavía no subo el nuevo release, lo voy a subir ya con un profile de proveedor.
chiaaaa

**Comment by jccastillo0007** [comment]
ahora si, ya esta lista.
