### ISSUE TITLE
Para OME111223UN4, conector, formato Levicom I, interpretar "02 Cheque nominativo"

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#678]
Ahora mismo consideramos para ellos OME111223UN4:
1. cheque
2. cheque nominativo

Pero resulta que si incluye el "02 " al inicio, no lo puede interpretar correctamente.

**Comment by jccastillo0007** [comment]
Estos son los streams reconocidos en general :  
"01.EFECTIVO"
"02.CHEQUE NOMINATIVO"
"03.TRANSFERENCIA ELECTRONICA DE FONDOS"
"04.TARJETA DE CREDITO"
"05.MONEDERO ELECTRONICO"
"06.DINERO ELECTRONICO"
"08.VALES DE DESPENSA"
"28.TARJETA DE DEBITO"
"29.TARJETA DE SERVICIO"
"99.OTROS"
"NA"

Para estos de optiblet, se tienen estas dos condiciones :  

Si se manda algo que contenga "recibo" se manda "NA"
Y ahora agregué la condición de que si se recibe "nominativo" se va a mandar la opción 02 de Cheque Nominativo.

**Comment by RigoFlores** [comment]
Negativo, las leyendas reconocidas en general son únicamente las descripciones, SIN NÚMERO.
Ya que a los clientes les pedimos que prácticamente no modifiquen sus sistemas. Por ello, solo esperamos la descripción, y en ningún momento se solicitó incluir el número, y mucho menos el punto decimal.
Para optibelt, tenemos estas adecuaciones a la medida:

**Cheque -->            02.CHEQUE NOMINATIVO
Transferencia   -->         03.TRANSFERENCIA ELECTRÓNICA DE FONDOS
03 Transfer. electr. de fondos  -->     98.OTROS
Recibo  -->  NA.NA
Cualquier otro distinto a los anteriores o distinto a los estándares   --> 98.OTROS**

Lo que se pide es interpretar ahora en lugar de cheque, "02 Cheque nominativo"

**Comment by jccastillo0007** [comment]
Si, es que la comparación que se hace, no afecta si no trae el número, de esa forma funciona correctamente, el único detalle es que con 02 Cheque nominativo, si trae el número y en ese caso esperaría también el . 
Pero bueno, si se puede ajustar para los alemanes, ahorita subo el release.
