### ISSUE TITLE
Definir desde la pantalla de configuracion la plantilla a utilizar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#68]
RECUERDA QUE LA PLANTILLA SE COMPONE AL MENOS DE 2 ARCHIVOS (GRACIAS, ERA SOLO UNO ANTES)... Y PODRÍA LLEVAR UNA O VARIAS IMÁGENES A UTILIZAR DENTRO DE LA PLANTILLA.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Si configuro una plantilla que ocupa ooootro archivo products, marca error.
Por eso comentaba que se requiere cargar 2 archivos, el jrxml y el jasper

**Comment by RigoFlores** [comment]
Configuré una plantilla que utiliza el jasper base, y marca error.
No permite el preview y mucho menos generar factura. Envía el siguiente error:
Error en generador PDF - Jasper (101)

**Comment by jccastillo0007** [comment]
Si se utiliza la plantilla default, se debe dejar vacio el campo y toma la configuracion default de la plantilla y de products.

Si se utiliza una plantilla a la medida, podemos subir nosotros el jasper de productos...

No me agrada la idea de tener que subir mas archvios por medio de la pantalla de configuracion, imaginate que utilizara 3 o 4 subreportes o imagenes, de todos modos tendriamos que subirlo nosotros....

Luego te platico un tip de como tu puedes actualizarle su plantilla.

**Comment by RigoFlores** [comment]
Que significa subir nosotros el jasper de products? (o sea tu, o yo, o el cliente desde la pantalla.... como está eso?), porque lo ví y no encontré forma de subir otro products, sin embargo ya no marcó error cuando subí una plantilla que ocupa el mismo products que la base?
