### ISSUE TITLE
Generalizar el tipo de dato remitente y/o destinatario de carta porte a todos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#681]
El-tipo-de-dato-en-web-se-da-de-alta-asi:

```
 update ClientConfiguration set extradata = 
 '[{"length":0,"name":"Remitente","type":"remitente","value":"valor 1"},{"length":0,"name":"Destinatario","type":"destinatario","value":"valor 1"},{"length":0,"name":"Origen"},{"length":0,"name":"Destino"},{"length":0,"name":"Valor Unitario"},{"length":0,"name":"Valor Declarado"},{"length":0,"name":"Reembarco"},{"length":0,"name":"Reembarcarse"},{"length":0,"name":"Observaciones"},{"length":0,"name":"Camion Placas"},{"length":0,"name":"Operador"},{"length":0,"name":"Documento"}]'
 where owner = 'RUEL740101R5A';
```

entonces-se-ocupa-el-mismo-comportamiento-para-CUALQUIER-CLIENTE.... Esto.es.un.desglose.del.registro.de.cliente (catálogo-de-cliente)-.en.un.solo.dato-extra-a-nivel-general
Como,quiera.hay.que.darlas.de.alta.manualmente,-entonces-es-mu-específico.

**Comment by jccastillo0007** [comment]
ahora que llegues me dices para revisarlo con el cliente que te lo pidió.
Mi usuario en web  en PRO, no tiene plugin de carta porte, y si pude leer y entender un dato extra remitente y destinatario, mandando los datos del cliente seleccionado como datos extras

**Comment by RigoFlores** [comment]
Este es el rfc del cliente en cuestión: CAQ1305077ZA
