### ISSUE TITLE
Plataforma-Proveedor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#683]
Al registrar un CFDi te pregunta si quieres actualizar el registro del proveedor, y que en caso afirmativo le des click en guardar.
No existe el botón guardar en ese escenario/pantalla.

**Comment by jccastillo0007** [comment]
fixed, se agregó la funcionalidad de salvar los datos del proveedor.
Este cambio aún no esta disponible, será en el siguiente release que se suba a PRU.

**Comment by RigoFlores** [comment]
Cuando.le.das.guardar.y.luego.intentas.subir.otro.xml
dice.que.no.pertenece.al.rfc.emisor....
(lo.mismo.que.pasaba.con.el.boton.limpiar)

**Comment by jccastillo0007** [comment]
Fixed.
