### ISSUE TITLE
Plataforma - Receptor - Compras

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#684]
Falta la pantalla para actualizar el status de la factura subida por el proovedor. Podríamos iniciar con esta:
- Registrada (cuando se sube)
- En proceso de revisión
- Programada a pago (dar fecha de pago)
- Pagada
- Rechazada (dar motivo de rechazo)

Creo que faltaría una columna en la vista que indique la fecha programada de pago.

En otros casos, quizás la integración sea mucho mas pro... es decir, que por WS  o similar disparemos el proceso interno de cuentas por pagar de nuestro cliente (emisor). Un cliente que nos pida esto, nos dejaría un billete seguramente..

**Comment by jccastillo0007** [comment]
Done... aunque creo que ya estaba duplicado este issue del estatus y fecha de pago.
