### ISSUE TITLE
Implementar Addenda Envases Universales por Addendador

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#686]
Te mandaré un correo con el XML anterior y nuevo, para que veas los campos que deben capturarse.
Anteriormente asumía que del XML original se podían tomar los datos... y SI...
pero no todos los sistemas pueden cambiar unidad de medida, tipo de cambio, moneda, etc.

Entonces ahora el approach es tomarlo del XML o  presentarlo por omisión, y ya si ellos quieren que modifiquen el campo.

**Comment by jccastillo0007** [comment]
done, esta listo en PRU... ojo :  
- el orden de los campos quedó diferente, primero los originales y luego los nuevos... te mando un xml como ejemplo
- el campo tipo de cambio debe ser numérico, en el ejemplo enviaste MXN, supongo es un error de copy & paste.

**Comment by RigoFlores** [comment]
Está mezclando la addenda sanofi (la parte de los datos dinámicos), con la addenda enum.
La addenda de envases universales no incluye datos a nivel producto.
OJO, no vayas a pegarle a sanofi, que quedó super chido eso de los datos dinámicos.

![erroraddendaeum](https://cloud.githubusercontent.com/assets/2912775/18029290/9fdbaff4-6c59-11e6-829b-e655c4e9befc.png)

**Comment by jccastillo0007** [comment]
ok, fixed.
Estará listo en el release de el domingo.
