### ISSUE TITLE
Plataforma - Proveedor - Consulta - Exportar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#688]
En el excel todos los comprobantes aparecen como tipo egreso, y realmente todos eran de tipo ingreso.

También el tema de que cuando los nombres incluyen comas, se extienden a la siguiente celda.
Lo que hay que hacer es sustituir las comas por espacios en blanco, solo para propósitos del contenido del excel.

**Comment by jccastillo0007** [comment]
no inventes.... en serio... se usa el mismo servicio de las otras consultas cuando se exportan a excel... entonces algo anda mal desde antes.

**Comment by jccastillo0007** [comment]
fixed.
El tema de ingeso y/o egreso, era desde que se sube el archivo...
El tema de las , en teoría ya debe estar resuelto... solo agregué unas validaciones

**Comment by RigoFlores** [comment]
Lo de ingreso, sigue indicándolo.
Lo de las comas ya se corrigió

**Comment by jccastillo0007** [comment]
ok, yo creo no subí la versión que lo arregla, sorry, hoy me la pase haciendo refactor para arreglar el desmadre de tipo de cliente + roles + tipo de licencias etc...
todo esto es necesario para llevar un control adecuado de roles en la nueva plataforma de facturación
