### ISSUE TITLE
Agregar a la pantalla de addendas, el botón de cerrar, OK, o similar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#69]
Para donatarias, hay que entrar a la pantalla de addendas. Falta agregar un botón para cerrar dicha ventana, ya que ahora mismo se cierra únicamente con la X

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
no presenta ningún botón, o como debe hacerse? Me está faltando algo?
Por cierto, accedí con la cuenta demo/demo en pru, y traté de generar una factura con addeda mabe, pero me marcó error de donatarias. Asumo que el plug in de donatarias no se lleva con el de adendas (por aquello de los multi-archivos  XML de adendas). Por ello, sería importante que el demo demo, sea adendas o donatarias, pero no las 2 simultáneamente.
