### ISSUE TITLE
Pantalla para dar de alta cuentas de proveedores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#691]
Se ocupa una pantalla nueva donde el emisor pueda dar de alta las cuentas de los proveedores para que puedan acceder al portal de proveedores:

a) Es posible que el proveedor NO exista y NO sea cliente de Factura-T
b) Mismo caso que el anterior pero el proveedor ya existe   (para este mismo emisor o algún otro emisor)
c) Es posible que el proveedor sea también cliente Factura-T, es decir que también sea emisor. (aquí que dijimos que pasaría???)

**Comment by jccastillo0007** [comment]
Este issue ya esta resuelto...
