### ISSUE TITLE
Pantalla para definir la fecha de pago de las facturas recibidas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#692]
Se vería reflejado en  la columna status, del portal de proveedores.
Se podrán obtener reportes de cuánto y cuándo se debe pagar y a quién?
Eventualmente, notificar días de pago.

**Comment by jccastillo0007** [comment]
ya esta listo el manejo de estatus y de la fecha de pago... pero, hay que definir los reportes que se quieren sacar, si se puede, pero debería ser en otra página según yo
