### ISSUE TITLE
DescargaT-Consultas-Incluir la opción de exportar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#693]
Incluir la opción de exportar en la pantalla de consultas.
Debe ser el excel, junto con su respectivo zip

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
no puedo acceder al descargaT.
Se queda la pantalla en blanco.
Estoy intentando con esta cuenta: HAM9303031M2

**Comment by jccastillo0007** [comment]
Si, ya vi el error, problema de roles como te había dicho.. pero ya estoy subiendo el fix.
