### ISSUE TITLE
Implementar script+query mágico para inicializar el ambiente de pruebas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#699]
Borrar documentos XML y PDF, HISTÓRICOS DE:
Emisores: ETE790117358, FIG881205GG2, 
Proveedores: TIA101020BP4,
Receptor: eliminar las cuentas de acceso al descargat para todos los receptores correspondientes de las facturas de los emisores.

Quizás en alguna pantalla, colocar ese botón para que pueda resetear durante las pruebas

**Comment by jccastillo0007** [comment]
Listo, es un script que se corre directo a la base de datos.

**Comment by RigoFlores** [comment]
Pero desde donde o como lo ejecuto?
No se puede poner un botón escondido que lo ejecute?

**Comment by jccastillo0007** [comment]
Negativo, no es tan transparente... mejor me avisas cuando lo necesites, y/o cuando ya tengas hecho el setup de la llave de SSH que te mandé para Putty, asi podrías tu entrar directo a PRU y ejecutarlo.

**Comment by RigoFlores** [comment]
Chiaaaaaa......
