### ISSUE TITLE
Catalogo de impuestos - clasificar trasladados/retenidos

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#7]
Impuesto IETU no existe

Se debe soportar IVA trasladado exento que es diferente a tasa cero

**Comment by jccastillo0007** [comment]
Manejar los decimales a seis posiciones, en caso de que se ocupen las 6 posiciones, no redondear.

**Comment by RigoFlores** [comment]
LOS IMPUESTOS TRASLADADOS SON IVA, IVA EXENTO E IEPS
LOS IMPUESTOS RETENIDOS SON IVA E ISR
(PARA EVITAR ERRORES POR PARTE DEL USUARIO)

**Comment by jccastillo0007** [comment]
Esto ya esta soportado desde hace un buen.

**Comment by RigoFlores** [comment]
Desde siempre, NO HA JALADO.
lo acabo de revisar nuevamente...
en escritorio si tu eliges trasladado, solo te da opción a impuestos trasladados (IVA, IEPS)
en retenciones, debería dar opción de (IVA, ISR).
Ahora mismo te muestra todos, por lo que el usuario se podría equivocar.
Lo cerramos con status "NO ATENDIDO, POR RAZÓN DESCONOCIDA"
