### ISSUE TITLE
Plataforma-Proveedores-Notificar de un nuevo CFDI agregado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#701]
Ahora mismo estamos ofreciendo que se notifique por correo electrónico a las áreas internas del cliente, cuando se reciba (suba) una factura en el portal del proveedor. Falta implementar esta función, supongo yo podría agregarse en el catálogo de proveedores; en la pantalla de usuarios, donde se indique quién 
recibirá notificaciones de proveedor, o de receptor.

Eventualmente esta parte es de las que serán personalizadas; algunos querrán el whatsapp, otros un webservice, etc.

**Comment by jccastillo0007** [comment]
done... supongo que hay que definir un template para este tipo de emails

**Comment by RigoFlores** [comment]
Y donde se definió o se definirá el correo al que tiene que notificar?
Recordar que este correo, es muy probable que no sea el correo de nuestro cliente, ya que seguramente la notificación tiene que llegar a contabilidad o cuentas por pagar... así que debe ser oootro correo.

**Comment by jccastillo0007** [comment]
Por ahora se usa el correo que tiene definido el cliente, no se donde sea el lugar adecuado para capturar un correo especial para estas notificaciones, probablemente nos hace falta una pantalla de configuración de la plataforma, que otros datos deberían configurarse ?

**Comment by RigoFlores** [comment]
Según yo... cuando se crea la cuenta de un usuario... debería indicarse si debe ser notificado de emitidas o recibidas, y a cuál cuenta. 
Recordar que falta la pantalla de usuarios y perfiles, donde se indicarán los privilegios de cada usuario.

**Comment by jccastillo0007** [comment]
ok, entonces hay que mejorar la pantalla donde se crean usuarios, es buena idea poner ahi configuración específica del usuario, pero hay que cerrar este issue y abrir uno dedicado a la pantalla de usuarios, donde hay que especificar que otras opciones hay que dar de alta, además del correo de notificaciones de emitidas y/o recibidas.
