### ISSUE TITLE
Plataforma - Emisor - Subir facturas de otro proveedor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#702]
Implementar función para subir los XML de otro proveedor.
Lo ideal es que suban un bonche de XML simultáneos, o en su defecto que se tomen de un zip, para que la plataforma los descomprima y suba uno por uno, validando que no estén repetidos.

**Comment by jccastillo0007** [comment]
Agregué una opción en el menú de ventas, para subir facturas de otros proveedores
Por ahora solo sube 1 xml, me falta aceptar zip files.

**Comment by RigoFlores** [comment]
Pendiente el zip, o elegir un bonche...

**Comment by jccastillo0007** [comment]
Solo se podrá el ZIP, el controller para subir muchos esta medio cab.....

**Comment by jccastillo0007** [comment]
Listo,, y si puede configurar el tema de multiselección de archivo... a huevo... incluso puedes seleccionar xml y zip al mismo tiempo.

**Comment by RigoFlores** [comment]
Cómo lo validaste?
No tengo facturas de otros proveedores...
Entiendo que no validas quién la hizo, sino simplemente que la suba????

**Comment by jccastillo0007** [comment]
no se valida quien la hizo, ni quien la suba, solo se valida que el rfc emisor sea el rfc del cliente de facturat, de lo contrario se rechaza.
Yo lo probé con facturas reales que le he dado a la TIA, de hecho aunque la timbremos nosotros, se puede subir por esa opción, ya que ahí se usa solo el XML.

**Comment by RigoFlores** [comment]
Espántame panteón...
