### ISSUE TITLE
Dar de alta a todos los clientes en el KeyGenerator

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#703]
Necesito tener la BD de TODOS los clientes en el KeyGenerator, para poder consultar en chinga sus datos, y sobre todo para tener actualizado su correo electrónico y teléfonos para las notificaciones.
Ese control (mas bien descontrol) se lleva a cabo desde excel, pero son muchos los clientes que están cambiando su correo constantemente.
Esta BD, me servirá para poder enviar las notificaciones a todos... eventos, nuevos productos, servicios, etc, pero sobre todo, para tener un repositorio común de esos datos, ya que ahorita andan en varias fuentes.
En el Keygenerator, necesitaríamos conocer también cuales clientes emiten desde el web y cuáles desde escritorio (ahora que aún se puede saber).

**Comment by jccastillo0007** [comment]
what ?

**Comment by jccastillo0007** [comment]
Según mis super queries son 56 clientes que recargaron en 2016 y que no los tenemos en la base de datos de clientes web.... anexo archivo, en los próximos días los voy a actualizar
[emisores que faltan en eFacturaT db.txt](https://github.com/jccastillo0007/eFacturaT/files/496403/emisores.que.faltan.en.eFacturaT.db.txt)

**Comment by RigoFlores** [comment]
Si, aunque algunos clientes facturan escritorio y tienen recibo de nómina en web... 
Pero bueno, para el caso de los correos y las notificaciones, hay que agregar todos.
Lo único malo, es que ya no sabremos cuáles son web y cuáles escritorio. Por lo pronto estos últimos hay que ponerles una etiqueta de escritorio

**Comment by jccastillo0007** [comment]
Listo... ya no hay nada que unificar y nada que agregar... ya es una sola tabla.
