### ISSUE TITLE
Emisor - compras - subir CFDI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#704]
Previamente subí 2 XML desde el portal de proveedores.
Luego accedí como emisor.
Consulté en el catálogo de proveedores, y no tiene ningún registro.
Luego intenté subir el mismo XMLL, y si bien marcó duplicado me mostró lo siguiente:

Existe un registro de este Proveedor
¿Desea actualizar este Proveedor?(Dar click en Guardar)
CFDi duplicado.

A que se refiere ese mensaje? A que existe una cuenta de proveedor o a que supuestamente ya se encuentra en el catálogo de proveedores,

Luego le dí guardar y me indicó:
Proveedor actualizado éxito,verifique en el Catálogo de Proveedores

Finalmente si lo guardó en la tabla de proveedores, pero los mensajes al parecer están chuecos o no se está poniendo el ambiente a cero correctametne

**Comment by jccastillo0007** [comment]
A que se refiere ese mensaje? A que existe una cuenta de proveedor o a que supuestamente ya se encuentra en el catálogo de proveedores,"

Se refiere a que ya existe en el catálogo de proveedores.

La incongruencia es por la base de datos, no había limpiado antes la tabla de proveedores.
