### ISSUE TITLE
Proveedor - Consultas - Descargar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#705]
En el archivo XML, la primera columna que es fecha, la muestra así:

14Feb2014_080541

lo cual no permitirá ordenar por ese campo... si va a ser fecha-hora, que se muestre en el formato adecuado.

**Comment by jccastillo0007** [comment]
Este es buen formato "ddMMyyyyHHmmss" 

Este formato de fecha / hora aparece en muchos de los archivos de excel que exportan información, pero apenas me lo reportaste en este de proveedores ?? hay que revisar si con ese formato se puede ordenar de manera óptima.

**Comment by RigoFlores** [comment]
Ahora está pior... ahora le pone supongo el taimestam: 19012016133714

Ojo, el formato que dices, creo que está bien, pero aún así, no fue lo que reporté, ya que lleva un '_' (guión bajo entre la fecha y la hora, y ese es el que no permitiría ordenar adecuadamente

**Comment by jccastillo0007** [comment]
Pues le esta poniendo el formato  "ddMMyyyyHHmmss", ya sin guión

**Comment by RigoFlores** [comment]
te.mandé.por.correo.evidencia

**Comment by jccastillo0007** [comment]
Para efectos de ordenamiento, el formato se cambió a "yyyyMMddHHmm"

Checa bien el dato, y verás que cumple con el formato indicado.

**Comment by RigoFlores** [comment]
Algo estamos haciendo o viendo distinto... sigue apareciendo la fecha en formato timestamp... ya te envié por correo el csv que yo veo.

**Comment by RigoFlores** [comment]
ah no había leido... aparece todo junto... creo que no es lo mas adecuado.
revisé el reporte de facturas generadas, y también aparece la fecha así : 
20Sep2016_092807

Según yo no se podría ordenar por fecha.
En el reporte de folios consumidos por los clientes si aparece así: 11/02/2015

No se puede manejar este mismo formato?

**Comment by jccastillo0007** [comment]
Si, se puede manejar cualquier formato, ahora lo cambio al que ya definiste.

**Comment by RigoFlores** [comment]
quizás sería bueno, homologar el formato en todos los reportes de excel que genera la plataforma
