### ISSUE TITLE
Proveedor y Emisor-Compras, no sube todos los CFDi

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#707]
No sé si porque tiene retenciones, pero marca error... te lo mando por correo.

Error al guardar el CFDi en Base de Datos

**Comment by jccastillo0007** [comment]
Fixed.

El problema era que no traía nodo Expedido En...

ojo. Ya subí los dos XML que me enviaste.

**Comment by RigoFlores** [comment]
OJO, hay que considerar los campos opcionales dentro del XML.
ExpedidoEn es opcional, no debió rechazar el XML
