### ISSUE TITLE
Proveedor - Registrar CFDI - mensaje poco claro cuando está duplicado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#709]
Ahora indica CFDI Duplicado
Creo que hay que indicar "El CFDI YA se encuentra registrado en el Portal, no se permiten duplicados"

**Comment by jccastillo0007** [comment]
Done.

No estaría de mas darle una revisada a todos los mensajes que manda la app, he encontrado algunos medio raros que puso Francisco... los he ido cambiando conforme los encuentro.

**Comment by RigoFlores** [comment]
Dejemos que el cliente haga su chamba... que nos reporte los mensajes.. jejee
