### ISSUE TITLE
Super-Conector-No.envia.todos.los.datos.al.PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#710]
Hice.una.revisión.del.formato.figueacero,.y.en.el.pdf.están.faltando.los.siguientes.datos:
El.régimen.fiscal.
Forma.de.pago.(solo.aparece.la.clave.pero.no.la.descripcion)
certificado.del.emisor
el.precio.unitario.de.los.2.últimos.productos.no.es.el.mismo
sello.digital.del.emisor
código.de.barras.tampoco.aparece.

**Comment by jccastillo0007** [comment]
Fixed.
