### ISSUE TITLE
Generar pantalla de configuración (alta) de usuarios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#711]
Dado que ahora vamos a tener varios roles en el emisor (cliente nuestro), debemos configurar los privilegios a los que tendrá acceso cada usuario:
a) Cada uno de los menús de la aplicación
b) Emisión de Facturas
c) Cancelación de Facturas
d) Correo Electrónico 
e) Recibir notificación de emitidas
f) Recibir notificación de recibidas

**Comment by jccastillo0007** [comment]
Subí un avance, pero no esta terminado... el tema de los pocos roles que teníamos y ahora que queremos dar privilegios a nivel de cada opción de menú se esta complicando.

**Comment by jccastillo0007** [comment]
Listo.

Hay que probar con usuarios reales y nuevos... según yo ya esta jalando al 100

**Comment by RigoFlores** [comment]
Ayer me reportó un cliente que no podía cancelar, porque no tenía privilegios para hacerlo.
Será que esta nueva opción, quedó lista para que nadie cancele?
Pero si consulto el único usuario de la TIA en producción, y entiendo que está bien... no tiene chequeado el control que dice NO Permitir Cancelación, lo cuál al parecer es una lógica inversa. Anteriormente decía "Permitir Cancelar CFDi"
