### ISSUE TITLE
Conector figuacero no incrementa el consecutivo del folio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#712]
No tengo idea de donde saca el folio actual, pero no coincide con la configuración de los folios.
Cuando procesa la factura, y me voy al facturat_db.log, ni siquiera modificó la tabla folios.
Una situación que me llamó la atención, es que el número de jars, en la versión de figueacero son 114, en lugar de los 120 (aprox) que veníamos manejando en la última versión de producción.

**Comment by jccastillo0007** [comment]
Chiaaaa pues ese resultado es debido a los grandes refactors de optimización que he estado haciendo... también debes de ver la app más rápida, incluso arranca en menos de 40 segundos... pero al menos el log que me enviaste no era usando la última versión... yo ya lo probé varias veces y si me incrementó los folios de la serie afectada...

**Comment by RigoFlores** [comment]
La última versión en el dropbox es del 22 de septiembre a las 08:52 pm... y contiene 115 jars, donde uno de ellos siempre se repite, quedando únicamente 114 jars.
Estamos hablando de lo mismo?

**Comment by jccastillo0007** [comment]
si, hablamos de lo mismo.
lo cerramos?

**Comment by RigoFlores** [comment]
no había tal issue.... chiaaaa
