### ISSUE TITLE
CxC - Agregar campos en el catálogo de clientes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#713]
Se requiere agregar:
Número de Cliente
Días de Crédito
Límite de Crédito

Aplica igualmente para nombre Alterno (que igual podríamos ir cambiando esa nomenclatura a Sucursal Cliente).

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Aquí se me pasó pedirte que se capture el saldo inicial también.
Para un cliente nuevo será 0.
Para un cliente nuevo, pero que apenas van a elaborar la primera factura desde la plataforma, sera distinto de cero.

**Comment by jccastillo0007** [comment]
Done
