### ISSUE TITLE
CxC - Crear menú de CxC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#714]
Menú Principal: CxC

Submenús: Cobros, Cartera

Le llaman cartera a todos los clientes que les deben.
La cartera puede estar vigente (aún no se cumple el vencimiento de la factura)
Vencida, cuando ya se cumplió el vencimiento de la factura, y aún no la paga el cliente de nuestro cliente (receptor).

**Comment by jccastillo0007** [comment]
Done... voy a renombrar el menú de consultas por cartera.
