### ISSUE TITLE
CxC - Cobros

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#715]
Es una pantalla con los filtros tipo consulta, pero agregando los datos que se registran en un cobro.
Me la imagino así:
1) Encabezado - Filtros . Se eligen las facturas a desplegar, a partir del RFC o Número de Cliente, Nombre de Cliente, Fecha Inicial y Fecha Final, Concepto.
2) La segunda parte del encabezado me permitirá registrar los datos generales del cobro: Clave (PA o NC), Fecha de Cobro (por omisión la actual),
3) Una vez que aplicaste los filtros, en la pantalla del resultado de la consulta, te aparece una pantalla similar a la siguiente matriz:

**Comment by RigoFlores** [comment]
![captura de cobros](https://cloud.githubusercontent.com/assets/2912775/18960076/0a97a9b8-862e-11e6-8455-af14c9b3e8ba.jpg)

**Comment by RigoFlores** [comment]
Aquí es donde se podrán elegir varias facturas.
Cuando se elige una factura, en automático se sugiere que el saldo sea el mismo que el cargo, con posibilidad de editar. De hecho, en esa pantalla de resultado de la consulta, será la única columna editable para facturas QUE NO HAN SIDO PAGADAS AL 100%, ya sea vigentes o vencidas.

Las columnas son:
Clave: FA (factura), PA (pago), NC (nota de crédito).
Fecha: de emisión para FA o NC; fecha de cobro para PA
Doc: Folio de la factura o NC. Para el PA será el folio de la factura cobrada.
Cargo: total de la factura
Abono: registro de pago total, parcial o con NC
Saldo: Saldo anterior + Cargo - Abono
Vencimiento: fecha de vencimiento de acuerdo a los días de crédito.
Concepto: datoExtra2 para FA o NC; referencia para PA

**Comment by RigoFlores** [comment]
La estructura de datos para CxC, debe ser visualizada de tal manera que sea fácilmente desplegable un reporte del tipo Por Cliente - Todos (pagadas y vencidas):

![porclientetodos](https://cloud.githubusercontent.com/assets/2912775/18974822/618b465c-866b-11e6-9a5f-b90f65ef4cd1.jpg)

**Comment by RigoFlores** [comment]
Del reporte anterior, se puede intuir que para cada factura existirá un cargo, y uno o varios abonos.
Este reporte solo se resume en la suma de los abonos por cada factura.

**Comment by RigoFlores** [comment]
Ahora existirá otro reporte, donde se involucran todos los clientes. Puede ser únicamente de vencidos o totales (vencidos involucra las facturas ya vencidas, y total involucra todas las facturas: pagadas, vigentes y vencidas).
![totaltotal](https://cloud.githubusercontent.com/assets/2912775/18975262/7de2bd6e-866e-11e6-93e5-171c30fc71e7.jpg)

Aquí están todos los clientes, con todos los cargos y todos los abonos. Vencidos, vigentes y pagados

**Comment by jccastillo0007** [comment]
ya esta listo el reporte de cartera por cliente.... aunque puede tener detalles jojojo

**Comment by jccastillo0007** [comment]
Listo el reporte general de cartera

**Comment by RigoFlores** [comment]
este issue se refiere a cobros no a cartera.
Lo cerraré esperando a que liberes lo que platicamos ayer, y que también envié por correo.
