### ISSUE TITLE
CxC - Optibelt - no registra el cliente cuando recibe una nueva factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#716]
Debe registrar al cliente con todo y su número de cliente.
Si el cliente ya existe, debe validar el número de cliente para revisar si tiene que agregar un registro nuevo o actualizar el ya existente

**Comment by jccastillo0007** [comment]
mmmm no estoy seguro que debamos hacer esto cada vez que se recibe un cfdi... imáginate después de 1000 facturas recibidas y tal vez solo la primera debió registrar el cliente... creo que es mucho overhead y esta administración se debe llevar acabo en las pantallas, si no, nos vamos a acabar el server con puras validaciones falsos positivos.

**Comment by RigoFlores** [comment]
Todo debe ser automático y también tienes razón en el overhead.
Mi sugerencia sería lo siguiente:
a) Hacer una carga inicial de catálogo de clientes e histórico de facturas.
b) Quienes mas emiten CFDI, ocupan conector. Entonces será el conector quién validará si un cliente se debe agregar o nó. En caso afirmativo, deberá enviar los datos por un WS alterno, para que registre únicamente cuando sea necesario. De esta manera no estaría validando todo el tiempo el WS actual. Solo se invicaría a un WS alterno (el que registra clientes en web), cuando sea necesario. 

Que te parece?

**Comment by jccastillo0007** [comment]
Me parece que ya esta repetido con el issue #731  como quiera ya esta resuelto, con el uso de la super poderosa y multifuncional AddendaFacturaT.
