### ISSUE TITLE
CxC- Registrar cobro - Sugerir valores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#717]
Cuando se va a registrar el cobro de UNA SOLA FACTURA, esto es cuando solo eligen el primer checkbox, debe sugerir los valores por default:
Importe del cobro = total de la factura
Fecha: la fecha actual
Docto: es el folio de la factura
Concepto: este si lo tienen que capturar, ya que es la referencia bancaria.

Cuando se van a pagar varias facturas, la fecha y la referencia deberían ser la misma para todas las facturas elegidas. Sin embargo, deberá poderse capturar el importe del cobro y el docto para cada cobro.

**Comment by RigoFlores** [comment]
Importe del Cobro y Docto, son datos que se deben capturar a nivel de la matriz. (son distintos para cada factura).
Fecha y Concepto, son datos que se pueden capturar a nivel header (son generales)

**Comment by jccastillo0007** [comment]
crap

**Comment by RigoFlores** [comment]
es decir?

**Comment by jccastillo0007** [comment]
Ya se sugieren los valores cuando es una sola factura, me falta lo de los datos parciales de cada factura
