### ISSUE TITLE
CxC - Consultas - Status

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#718]
Los status de los cobros son Pagada, Vigente o Vencida.

Recordar que son status distintos a las cuentas por pagar.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Agregar un status adicional, que es Vigente+Vencida... o lo que es lo mismo distinta a pagada.
En ambas pantallas de CxC

**Comment by jccastillo0007** [comment]
no mames... en serio

**Comment by jccastillo0007** [comment]
done
