### ISSUE TITLE
CxC - Número de cliente debe ser desplegado de una lista

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#719]
Así como el RFC, el número de cliente se deberá desplegar de una lista, si es que se requiere aplicar ese filtro.
Si ya eligieron el RFC, solo desplegará los números de cliente que le correspondan al RFC.

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
¿ya aparece como lista, pero cómo se va a llenar?

**Comment by jccastillo0007** [comment]
En el catálogo de clientes, ahi se pone su número de cliente.

No tenemos nada automático en web, en standalone, hoy platicamos como se va a llenar.
