### ISSUE TITLE
CxC - Registrar cobro - no muestra facturas cobradas parcialmente.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#720]
Cuando en una factura registras un pago parcial, cuando vuelves a consultar (desde registrar cobro) no te aparece la factura con dicho pago parcial.
Esto es como si hubiera sido pagada totalmente. 
Debe mostrarse en esta pantalla MIENTRAS NO SEA PAGADA TOTALMENTE. (obvio, siempre que apliquen el filtro adecuado para que se muestre).

**Comment by jccastillo0007** [comment]
si de acuerdo, solo que ahorita no esta contemplando pagos parciales.

**Comment by jccastillo0007** [comment]
fixed.
