### ISSUE TITLE
CxC - Ingresar Cobro - Falta mostrar varias columnas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#722]
En la matriz mostrada en pantalla, como resultado de la consulta, falta mostrar la columna "Concepto" y "Docto", "Saldo".

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Las columnas deben mostrar lo siguiente:
CLAVE, FECHA, DOCTO (FOLIO PARA EL CASO DE FACTURAS Y NC), CARGO (TOTAL DE LA FACTURA), ABONO (LO PAGADO A DICHA FACTURA), PENDIENTE (SALDO PENDIENTE A ESA FACTURA), SALDO (SALDO ACUMULADO), VENCIMIENTO, CONCEPTO.

**Comment by RigoFlores** [comment]
Subí un documento al dropbox para mayor referencia

**Comment by jccastillo0007** [comment]
Dichas columnas aparecen en la consulta de cartera, ya que cuando ingresan un cobro, no se realizan operaciones para saber los saldos de los clientes, solo aparece la información de las facturas vigentes no pagadas.
