### ISSUE TITLE
DATOS DEL CLIENTE - AGREGAR SALDO INICIAL EN EL CATÁLOGO DE CLIENTES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#723]
EL SALDO INICIAL PARA UN CLIENTE NUEVO ES CERO. (SE SUGIERE CERO).
EL SALDO INICIAL SE OCUPA PARA IR CALCULANDO EL SALDO ACTUAL DE LOS CLIENTES, CADA VEZ QUE SE EMITE UNA FACTURA.
SALDO ACTUAL = SALDO ANTERIOR + CARGOS - ABONOS

**Comment by jccastillo0007** [comment]
Done.
