### ISSUE TITLE
Ingresar Cobro - no muestra el concepto en la columna de concepto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#724]
El concepto viene como datoextra2 de la addenda.
Ese dato se debe ingresar en automático cuando se recibe una factura de OPTIBELT

**Comment by jccastillo0007** [comment]
De acuerdo a lo que hemos estado platicando, me parece que este defecto era en la pantalla de consulta de cartera por cliente y general, pero no en la pantalla de ingresar cobro, ya que ahí capturan la referencia.

Por cierto, esta listo este cambio, por la noche lo puedes probar

**Comment by RigoFlores** [comment]
Como parte de la información del cobro, la referencia (concepto) de las facturas a cobrar, me parece que si lo ocupan. Lo puedes agregar pls?

**Comment by jccastillo0007** [comment]
Listo.
