### ISSUE TITLE
Ingresar Cobro - Consulta - no funcionan los filtros de #Cliente, RFC, status

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#725]
Si aplico cualquiera de los filtros arriba mencionados, no muestra nada.
Hay que invertir la posición de los filtros de RFC y Número de Cliente.
Ya que si primero eligen RFC, el filtro de número de cliente, solo debe mostrar los números de cliente con el RFC elegido.

**Comment by RigoFlores** [comment]
Sigue sin funcionar por RFC, además que hay que invertir el orden...

**Comment by jccastillo0007** [comment]
fixed... no sé a que te refieres con invertir el orden.

**Comment by RigoFlores** [comment]
Ahora mismo el primer filtro del lado izquierdo es el número de cliente, y enseguida el rfc.
Dado que el RFC puede incluir varios números de cliente, y no al contrario... por ello mi sugerencia es que primero aparezca el RFC... una vez seleccionado, el filtro de número de cliente se reduce, que no?

**Comment by jccastillo0007** [comment]
pero que pasa si se memorizan el número de cliente , y lo quieren acceder de inmediato, creo que no debemos restringir el número de cliente a que seleccionen el RFC... pero si los puedo cambiar de lugar si es necesario, es decir, poner primero el rfc y luego el no. cliente.

**Comment by RigoFlores** [comment]
OK, podemos dejarlos como están ahora mismo.
Y si, podrían memorizar el número de cliente e ingresarlo directamente.
También es posible que quieran obtener un listado de los números de clientes asociados a un RFC, y por ello primero aplicarían el filtro de RFC y después el de número de cliente, donde solo tendría que mostrar los números de cliente asociados al RFC previamente seleccionado, correcto?

**Comment by jccastillo0007** [comment]
negativo... es una opción o la otra, es decir.
1. se muestran todos los números de clientes para que ellos los accedan directamente
2. se muestran los números de clientes, que corresponden a un RFC previamente seleccionado

Esta limitante es porque el contenido del combo se le deben definir de donde leer la información a presentar, luego entonces, se le define leer los nombres alternos de toooodos los clientes del emisor, o se define leer los nombres alternos de un RFC.

**Comment by RigoFlores** [comment]
Ya se hizo un desmadre con el tema de que los rfcs están duplicados 
Si aplico un filtro por rfc o por número de cliente no muestra nada, siendo que si tiene facturas cualquiera de los clientes listados

**Comment by jccastillo0007** [comment]
ok, voy a borrar todo para yo probar desde cero... el tema de dar de alta clientes o sucursales en web, debe usarse con la última versión de standalone.. para que sea consistente, de otra forma puede tener comportamientos raros...

**Comment by jccastillo0007** [comment]
creo que es por lo inconsistente que quedó la base de datos, ahorita ya tengo casi 30 facturas de solo 4 rfc, y todo esta funcionando correctamente

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Si ocupo el filtro de RFC, a huevo le asigna un número de cliente... supongo el primero para ese RFC.
No olvidemos que para otros clientes nuestros, quizás no ocupen el número de cliente y permanezca vacío, en cuyo caso el filtro que debe funcionar es únicamente el RFC.

El punto es que ahora mismo, si quiero filtrar por RFC no lo permite (le asocia un número de cliente a juercita).

Quizás para optibelt esté bien, pero para el resto de nuestros clientes no lo esté tanto.

**Comment by jccastillo0007** [comment]
Probé con mi usuario, con un cliente sin sucursal, y si hace bien el filtro... asi que fuera de optibelt no debe haber problema.

**Comment by RigoFlores** [comment]
Ya ves que en sus observaciones si nos lo pidieron...

**Comment by RigoFlores** [comment]
no se porque estaba cerrado este issue, pero salió hoy con optibelt.
Hace falta en cobros... que elijan el rfc.... luego, podrían elegir un número de cliente, perteneciente a ese rfc...
Con esto podrán generar reportes por cliente o por grupo de clientes (RFC con sucursales).

**Comment by jccastillo0007** [comment]
a que bonito desmadrito este tipo de filtros, pero me parece que ya quedo listo.

**Comment by RigoFlores** [comment]
Si elijo el RFC AME0010162W9 y con fecha del 02 de diciembre, me muestra 3 registros.
Luego aplico un filtro por número de cliente y funciona bien.
Pero si luego quito el filtro de número de cliente para consultar nuevamente todos, me marca internal error.

**Comment by jccastillo0007** [comment]
con que usuario lo probaste ?

**Comment by RigoFlores** [comment]
Con el de optibelt... OME111223UN4

**Comment by jccastillo0007** [comment]
Listo.

**Comment by RigoFlores** [comment]
Sigue mal... ahora ya no se va a internal error, pero regresa resultados que no corresponden.
Con el RFC receptor AME0010162W9como filtro, se meustran 3 facturas como resultado de la consulta.
Cuando elijo algún número de cliente, y luego regreso a todos, pero manteniendo el filtro de RFC receptor... no respeta el filtro del rfc receptor.

**Comment by jccastillo0007** [comment]
chequeando...

**Comment by jccastillo0007** [comment]
fixed.
