### ISSUE TITLE
Permitir agregar otra imagen en las plantillas PDF en web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#726]
Ahora mismo solo permite el logo, pero por ejemplo (casualmente), optibelt ocupa una imagen alterna en sus facturas... la tia también... jeje

**Comment by jccastillo0007** [comment]
Hoy en día se envían 2 imágenes, el logo y el código cbb, voy agregar una tercera imagen, peeeero de donde se va a tomar el path de la imagen? será algo fijo, o lo agrego a la pantalla de configuración?

**Comment by RigoFlores** [comment]
Pues en escritorio se busca en el directorio Jar, y no especificamos nada.
Pudiera ser que se almacene en la misma carpeta donde se guardan los sellos de cada cliente, y que la imagen se llame forzosamente marcaAgua.jpg o marcaAgua.Png.... eso sirve?

**Comment by jccastillo0007** [comment]
si, eso nos ahorra temas de configuración... 

work in progress.

**Comment by jccastillo0007** [comment]
Listo, el archivo se debe llamar marcaAgua.png, y supongo que lo vamos a subir nosotros al directorio setup de cada cliente...

Si dicho archivo existe, manda el path a jasper en la variable marcaAgua, si no existe, manda vacía esa variable.

**Comment by RigoFlores** [comment]
Oyes, podría ser también que busque por extensión jpg, para ser consistente.

**Comment by jccastillo0007** [comment]
si, si se puede y ya esta listo... lol.

**Comment by RigoFlores** [comment]
probé con la cuenta de la tia en pruebas, y no jaló la plantilla... esta plantilla invoca una imagen que se llama marcaAgua.png
Esta imagen en escritorio la busca en el directorio Jar.
En web la debería de buscar en el directorio setup... o lo que es lo mismo, en la misma carpeta donde se suben sellos, logos, plantillas, archivos de addenda dentro del web.

**Comment by jccastillo0007** [comment]
[10/18/16 9:08:21 PM] JC@GDL: chiaaaaa
[10/18/16 9:08:43 PM] JC@GDL: debes buscar lo que trae la variable marcaAgua... que en si trae el path de donde se encuentra la imagen
[10/18/16 9:09:05 PM] JC@GDL: vi la plantilla y tu estas poniendo "marcaAgua.png" chiaaaa

Tal cual lo haces para la imagen del logo.

**Comment by RigoFlores** [comment]
En.escritorio.se.busca.cualquier.imagen.que.se.invoca.al.pdf.en.el.directorio.Jar. Puede.ser.una.o.n.imágenes.
El.símil,pudiera.ser.buscar.las.imágenes.que.sean.en.la.carpeta.setup.de.cada.cliente...
es.correcto?

**Comment by jccastillo0007** [comment]
Negativo... la infraestructura es diferente, no se puede hacer lo mismo que en standalone porque en web hay o puede haber cientos de miles de usuarios..., la misma  tecnología no lo recomienda... es por eso que mandamos el path absoluto de la imagen, tanto para el logo, código de barras y ahora la marca de agua.

**Comment by RigoFlores** [comment]
Ya le cambié a nombre de variable, igual que el logo... y sigue marcando error... que será tu?
Acabo de realizar la prueba... 14:23  hrs.

**Comment by jccastillo0007** [comment]
chiaaaa, le pusiste marcaAgua.png a la variable jajajaja
Ya le quité el .png y ya jalo....

Checa tu plantilla local.

**Comment by RigoFlores** [comment]
si ya vi.... chiaaaaa.....
