### ISSUE TITLE
Optibelt - No almacena el número de cliente en la BD de facturat

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#727]
Por lo tanto, no se puede capturar una lista de correos identificados por número de cliente.
Lo que entiendo que debería hacer, es almacenar para un mismo RFC:
a) un registro 'principal' en el catálogo de clientes. Para la primera factura que llegue de ese RFC
b) registros adicionales como nombre alterno para cada número de cliente distinto relacionado al mismo rfc
d) consultar el número de cliente en el archivo y enviar la factura a la lista de correos asociados a dícho número de cliente.

**Comment by jccastillo0007** [comment]
Listo, se esta subiendo la version que implementa este requerimiento.

criterios.
1. Si el cliente no existe, lo da de alta
2. Si existe el cliente verifica el no. de cliente asociado
2.1 si es el mismo, entonces ya esta dado de alta y no le hace nada
2.2 si el registro en bd no tiene no. de cliente, le asigna el no. de cliente leido del archivo
2.3 si el registro en bd ya tiene no. de cliente, pero es diferente al leido del archivo, entonces  verifica si existe alguna sucursal con ese no. de cliente
 2.3.1 Si existe una sucursal con ese no. de cliente, ya no le hace nada
2.3.2 Si no existe sucursal, da de alta una nueva sucursal

**Comment by RigoFlores** [comment]
Si, los criterios están bien definidos.
Ahora el tema es que en consultas, no aparecen en los filtros los números de cliente que se dieron de alta como nombre alterno. Eso limita ese filtro a solo los números de cliente que aparecen en el catálogo de clientes.

**Comment by jccastillo0007** [comment]
chiaaaaa

Fixed.... en un ratito verás otro release en el drotbots

**Comment by RigoFlores** [comment]
Jeje   vamos al paso  
Ahora si aparecen todos los números de cliente en consultas, pero si elijo el número de cliente de un nombre alterno, no toma en cuenta el filtro y ni siquiera lo elige, ya que toma el número del rfc base 
Es decir aunque aparece listado eliges un número de cliente correspondiente al nombre alterno, toma el número de cliente del rfc base, y ese es el filtro que toma en cuenta para el despliegue del resultado de la consulta

**Comment by jccastillo0007** [comment]
crap... hay que quitar el número de cliente de esa consulta... le estoy haciendo demasiado manita de puerco solo por esos putos que ni nos han pagado.

**Comment by jccastillo0007** [comment]
de hecho no tomaba en cuenta el número de cliente, solo el rfc, por eso en consulta ves todo lo de ese rfc, le voy agregar el número de cliente al query.

**Comment by jccastillo0007** [comment]
crap... se sigue complicando... cuando se genera una factura no se guardaba que número de cliente lo generó, solo el rfc.... ahora hay que guardar el número de cliente para poder hacer queries en base a eso... (esto es solo en Standalone) en web si lo almacena... chiaaa

**Comment by jccastillo0007** [comment]
ya mejor quite el tema del combo de número de cliente, ya que la app esta lista para mostrar cliente y no sucursales de lcientes, además de que no se guarda el número del cliente que facturó, solo el rfc.

**Comment by RigoFlores** [comment]
Aquí hay algo medio extraño... no sé si está mal o quizás bien para optibelt.
Quedamos que en catálogo de nombres alternos, el nombre no cambiaría, sin embargo si cambia y le asigna el número de cliente, en lugar de la razón social. 
No es el caso, pero si quisieran facturarle a un cliente con un nombre alterno, en lugar de razón social le asignaría el número de cliente, lo cual evidentemente estaría mal.
Dado que no se agregó el nombre de 'la sucursal del receptor', se ocupa el nombre o razón social para distinguir.
Insisto, para optibelt no le afecta, pero quizás a los demás clientes si.....
Por otro lado, los demás clientes capturarán a manita los nombres alternos... 
¿tu como vex?

**Comment by jccastillo0007** [comment]
Esto del no. cliente como nombre de sucursal, es solo para optibelt, y es para poder distinguir entre sucursales, cualquier otro cliente, no usará este workaround
