### ISSUE TITLE
Registro de Cobros - Mantiene en memoria el dato anterior

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#728]
Primero le indico que el cobro será de 100 pesos por ejemplo... y navego en la pantalla, capturo a nivel de factura los 100 pesos... pero si después rectifico el cobro... por ejemplo 200, al seleccionar nuevamente las facturas... mantiene en memoria los 100 pesos anteriores... particularmente para el cálculo de 'Saldo disponible para pago de CFDi's'
Nota la imagen de abajo. No hay ninguna factura seleccionada y el saldo es 100 pesos menos del cobro.

**Comment by RigoFlores** [comment]
![cobros](https://cloud.githubusercontent.com/assets/2912775/19398460/56520ac0-9212-11e6-8509-0735c042adcb.png)

**Comment by RigoFlores** [comment]
En esa misma imagen, revisar porqué la segunda factura muestra pinche mil decimales... eso para propósitos de los cálculos, se seguro meterá ruido... amén que se ve muy extraño

**Comment by jccastillo0007** [comment]
fixed... lo de los decimales, es aleatorio, voy a redondear las cifras a 4 decimales para evitar estos casos...
