### ISSUE TITLE
Cobros - no muestra los registros para un cliente en particular

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#730]
Mandé varias facturas... en cartera muestra todas.
En cobro para el número de cliente 511538, no muestra las facturas para registrar el cobro.
En la prueba anterior si mostraba todo.
Tengo 3 clientes registrados; de los otros 2 si muestra sus facturas en la pantalla de cobros.

**Comment by jccastillo0007** [comment]
Pues no lo muestra, y no hace bien los filtros, porque tienes un desmadre de datos... en el catálogo de clientes tienes estos rfc - no. cliente:  

AME0010162W9 - 511538
BAS101010JU2 - 529800
BTA130730R98 - 745512

y en las facturas tienes esta relación:

| clientNumber | targetRFC  
+--------------+--------------
| 511633       | AME0010162W9 
| 511638       | AME0010162W9 

Osea que no coinciden en ningún caso, solo si buscas por RFC.

Voy a actualizar los datos, para corregir esto y seguir haciendo pruebas de los filtros.

**Comment by RigoFlores** [comment]
OK, entonces de manera natural... este issue nos demanda el tema de mantener actualizado el catálogo de clientes, incluyendo el número de cliente, que no?
