### ISSUE TITLE
Implementar actualización automática de Clientes desde el superconector hacia web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#731]
Comentaste que un campo adicional en la addenda, le indicará al web si es necesario actualizar o nó, algún registro de clientes en particular.
Esto es, el superconector validará localmente cuando detecte un nuevo cliente, en cuyo caso, le enviará una bandera al web, para que registre dicho cliente en el catálogo.
OJO. En el caso de optibelt, UN CLIENTE NUEVO ES AQUÉL NÚMERO DE CLIENTE NO REGISTRADO NI COMO CLIENTE PRINCIPAL, NI COMO NOMBRE ALTERNO.Ñ

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Está duplicando los registros en el catálogo de clientes en el web, amén que no almacena los clientes cuando el número de cliente no existe (es.decir.mismo.rfc.distinto.no.cliente)
Mandé n facturas de un mismo rfc, y generó n registros del mismo rfc como nombres alternos 
Puedes chequearlo ahora mismo para el rfc AME0010162W9

**Comment by jccastillo0007** [comment]
Se debe usar la última versión de standalone... y el problema puede ser que como standalone no refresca la base de datos de inmediato, puede ser que registre un cliente n veces... crap.. debo meter un candado

**Comment by jccastillo0007** [comment]
ya hice las pruebas, en lo que respecta a dar de alta clientes y/o sucursales, todo funciona bien... esto es lo que se debe de tener como prerequisito para que sea consistente.
1. La última versión de facturat standalone (voy a subir una versión cambiándole el número de versión para evitar confusiones)
2. Borrar los clientes y sucursales de la base de datos de standalone
3. (En mi caso) borre todos los clientes y sucursales de la bd de web
4. Mandé timbrar los 15 archivos que me enviaste de optibelt, alterando en algunos casos el número de cliente para forzar a crear sucursales

Bajo este workflow, las pruebas salieron bien.

**Comment by jccastillo0007** [comment]
haber si ahora si

**Comment by RigoFlores** [comment]
Al parecer si... ya no duplicó sucursales... ni duplicó RFC's.
Aquí si me preocupa un poco que sea el escritorio quién lleve este control... si por cualquier razón se genera alguna inconsistencia, la reflejará al web... siendo que en web se puede poner un candado para la combinación RFC + númeroCliente
