### ISSUE TITLE
Conector-Optibelt-no despliega los rfc nuevos en catálogo de clientes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#732]
Cuando procesa archivos con un nuevo rfc si los toma en cuenta pero no lo puedes consultar en el catálogo de clientes;tienes que cerrar y abrir la aplicación para que se vean 
Esto mismo NO SUCEDE PARA NOMBRES ALTERNOS, esos si los despliega al vuelo, al igual que en la pantalla de consultas.
Tendría que ser consistente, que no?.

**Comment by jccastillo0007** [comment]
fixed.
