### ISSUE TITLE
Superconector - Optibelt  -Duplica el registro del nombre alterno al capturar los correos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#733]
De las últimas pruebas que estoy realizando porque ya jala desde siempre, es el envío de correos múltiples.
Optibelt tendrá que capturar a mano los correos de los clientes... esto es, buscará el rfc o el nombre alterno y capturará el correo.
Yo lo que hice fue capturar varios correos en un nombre alterno, y lo que hizo fue duplicar el registro.
Igualmente creo que por ello no envió el correo cuando generé la factura.

**Comment by jccastillo0007** [comment]
fixed.
