### ISSUE TITLE
Dar de alta correo, teléfonos y logo de Optibelt al envío de su correo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#734]
Ayer pasé los datos, pero no se han reflejado en el correo que se envia:

Contacto: Marisol Piña Galvan (m.pina@optibelt.mx)
Telefonos: 01 (442) 210-3741, 210-4863, 210-5003 y 210-5004.
![logo_optibelt](https://cloud.githubusercontent.com/assets/2912775/19531221/7ec1fb1c-95fc-11e6-9cca-21dd445e0ef1.png)

**Comment by jccastillo0007** [comment]
Done
