### ISSUE TITLE
Facilidad para modificar la fecha de vencimiento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#735]
5.       Ofrecer la facilidad para modificar la fecha de vencimiento para cualquier factura nueva y que no contenga abonos asociados. Se deberá capturar el motivo del cambio, así como registrar usuario que hizo el cambio.

Para algunas facturas, la fecha de vencimiento calculada por el sistema no aplica, ya que son pedidos especiales o negociados por aparte.
Creo que en Ventas - Consultas - Edición, sería un buen lugar para editar dicho dato.

**Comment by jccastillo0007** [comment]
Done.
