### ISSUE TITLE
CxP-Calcular fecha de vencimiento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#738]
Cuando.se.sube.una.factura.de.proveedor...calcular.la.fecha.de.vencimiento.de.acuerdo.a.lo.configurado.en.el.catálogo.de.proveedores.
Si.el.dato.no.se.ha.capturado...asignar.7.días.por.default.

**Comment by jccastillo0007** [comment]
Done.

Esto se esta haciendo en 3 lugares.
1. Menú proveedores, cuando ellos suben el cfdi
2. Menú compras, que según yo hay que quitarlo y moverlo a Menú CxP

**Comment by RigoFlores** [comment]
Subí un XML desde el menú de Compras, con la cuenta de la TIA y no me calculó la fecha de pago. Previamente le había capturado que el proveedor correspondiente me daba 15 dias de crédito.

El menú de compras si está relacionado con CxP, pero quizás convenga dejarlos separados.
Primero se debe registrar o subir XML. (Hay que cambiar el nombre a Registrar CFDI o Registrar Factura).
Después basado en los días de crédito, se calculará la fecha de pago, misma que se podrá consultar en Compras-Consultas, así como en CxP-Pagos.

Mencionaste que se hacía en 3 lugares, pero solo listaste 2. Cuál es el tercero?

Ahora que la tia tiene todos los menús habilitados, entiendo que el menú de Proveedor, es cuando la tía asume el rol de proveedor, para cualquier otro RFC que también es cliente de la tia, es correcto?

**Comment by jccastillo0007** [comment]
chiaaa, apenas voy a subir el release a PRU.

Subir facturas solo se hace en dos lugares.
1. compras
2. proveedores

Consultar dichas facturas se hace en tres lugares
1. compras
2. proveedores
3. CxP

Con respecto a la pregunta de la TIA como Proveedor, es correcto...

**Comment by jccastillo0007** [comment]
subi el nuevo release a PRU, pero no me dió tiempo de probarlo, lo haré ma;ana temprano

**Comment by jccastillo0007** [comment]
oye estamos hablando de la fecha de pago o de la fecha de vencimiento, son dos diferentes (hasta ahora).

**Comment by jccastillo0007** [comment]
Done.
