### ISSUE TITLE
CxP-Registrar Pagos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#739]
Replicar la pantalla de cobros: 
1)Cambiar etiquetas de cliente por proveedor
2)Cambiar etiquetas de cobro por pago
3)Incluir la columna Serie   (optibelt no ocupa serie, pero las demás facturas es muuuy probable que si)

4)Cuando se registra un pago notificar por correo a los clientes o rfcs involucrados 
5)Dar opción de agregar documento digital como comprobante del pago

Quizás cambie el cálculo, ya que esta cuenta es de naturaleza acreedora, pero lo investigo y te digo.

**Comment by jccastillo0007** [comment]
el punto 3 aplica también a la página de CxC no? o vamos a dejar chimuelo al bebé ?

A que te refieres con el punto 5? no es buena idea dejar que suban y suban cosas.

**Comment by RigoFlores** [comment]
El punto (3), si debería aplicar en general, pero recuerda que Optibelt no maneja Serie.
El punto (5), si se refiere por ejemplo a subir el comprobante de pago en el banco, o donde se haya hecho. Yo siempre pido que me envíen el comprobante de pago, para quitarlos de la lista negra.

**Comment by jccastillo0007** [comment]
No estamos preparados para permitir subir ese tipo de documentos.
Al permitir subir comprobantes, debemos permitir verlo, bajarlo, cambiarlo etc... ese punto lo dejamos pendiente.

**Comment by jccastillo0007** [comment]
Done... solo dejamos el punto 5 para un futuro mejor... cuando ganemos unos 80k cada uno, entonces ya nos aventamos este refactor.
