### ISSUE TITLE
Error en Lugar de Expedición

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#74]
Lo toma de los datos del receptor, y siempre debe ser de los datos del emisor en el formato 'municipio, estado'

**Comment by RigoFlores** [comment]
En la pantalla los muestra ok, pero los envía incorrectos al PDF y al XML...

**Comment by RigoFlores** [comment]
Blocker...

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
ahora falta corregir lo siguiente. 
En la pantalla de factura, por omisión de sugiere el lugar de expedición (municipio, estado del emisot), pero permite modificarlo.
Cuando lo modificas, no envía la modificación al PDF y XML, sino mantiene fijo el municipio, estado del emisor.

**Comment by jccastillo0007** [comment]
Es buena idea permitir miduficarlo?

JC@iPhone.
 Saludos.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Posiblemente no sea tan buena idea, pero así entiendo que les sirve, y así lo tenemos en están alon.
Cuando se agregue el tema de sucursales del emisor, el lugar de expedición sugerido, será el municipio, estado de la sucursal elegida.
(nuevamente, tal cuál el están alon)
