### ISSUE TITLE
Dar de baja Servicio de Cancelación de FINKOK

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#741]
El deber ser es... validar el PAC que timbró; si es facturehoy, ejecutar el proceso actual de cancelación.
En otro caso, entonces ejecutar la cancelación todo terreno.

Si lo anterior es complicado, al menos dar de baja la cancelación finkok... ya que lejos de darnos beneficio, nos genera conflicto.. porque entiendo que al no validar el PAC que timbra, se intenta cancelar por finkok cuando falla por cualquier razón facturehoy, y se generan mensajes que solo confunden al usuario y a nosotros.

Cuando doy de alta sellos ejecuto estos scripts:
 cipherTool.sh  createPFX.sh 

Si damos de baja finkok, ¿cuál ya no sería necesario?

**Comment by jccastillo0007** [comment]
Ya di de baja la cancelación de Finkok, aún no tenemos implementado la cancelación todo  terreno, de hecho no recuerdo si eso era con finkok o facture hoy

El script de cipherTool.sh es el que ya no será necesario ejecutar.

**Comment by RigoFlores** [comment]
Era con FactureHoy... nos costaba... no se ahora.
Lo importante seria identificar quién timbró, para con ello ejecutar la actual o la todo terreno.
