### ISSUE TITLE
Usuarios y Perfiles - CxP

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#742]
Le doy acceso a catálogos, compras y cuentas por pagar.
Esto implicaría de alguna manera, el perfil de CxP.
Me da acceso a Compras, pero NO  a registrar CFDI
Me da acceso a CxP, pero no a reporte por Cliente (debe ser proveedor)
Me da acceso a CxP, pero no a reporte General

**Comment by jccastillo0007** [comment]
fixed.
