### ISSUE TITLE
Nuevo KeyGenerator

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#746]
No ordena por rfc ni por nombre... lo cual hace un desmadre para poder hacer una recarga o cambio de domicilio... 
Se tiene que ordenar por ambos criterios, tanto recargas como llaves

**Comment by jccastillo0007** [comment]
Según lo que vi, para recargas si esta ordenado tanto por nombre y rfc, pero para llaves nuevas si faltaba el ordenamiento, lo cuál ya esta corregido, en la noche lo subo.
