### ISSUE TITLE
Nomina 1.2 - ajustes en CFDI estándar para nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#750]
Voy a levantar un solo issue con todos los ajustes **ESPECÍFICOS PARA NÓMINA**:

1  Condiciones de pago no debe INCLUIRSE
2  Subtotal es igual a la suma de total de percepciones + totalOtrosPagos
3  Descuento = total deducciones
4  Motivo de descuento no existe
5  Moneda = MXN
6  metodo de pago = 'NA'
7  lugar de expedición = Código Postal de domicilioFiscal
8  Número de cuenta = no debe existir
9  si el emisor es persona física, debe asegurar el CURP del emisor.
10  domicilio fiscal y expedidoen, no deben existir.
11  el régimen fiscal, debe estar apegado al catálogo publicado por el sat
12  impuestos = </Impuestos> sin reportar trasladados ni retenidos
13  retenciones y traslados no deben existir

A NIVEL CONCEPTO
14  concepto solo debe ser uno, y cantidad 1
15  unidad=ACT
16  no identificación a nivel concepto no debe existit
17  descripcion=Pago de nómina
18  valor unitario = suma de TotalPercepciones + otrospagos
19  importe = suma de TotalPercepciones + otrospagos

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
se abrieron de manera individual cada issue... cerraré este, y si detecto alguna omisión, se tratará en específico.
