### ISSUE TITLE
Nómina 1.2 - Actualizar los catálogos de nómina existentes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#751]
Cambios:
1.Régimen del trabajador 
2. Bancos - completar el listado.
3. Riesgo (**sin cambios**)
4. Tipo Percepción... aquí  actualizar el catálogo actual (se elimina el 16, 17,, 40, 41,42; se agregan del 44 al 49)

**Comment by jccastillo0007** [comment]
1. Régimen del trabajador = DONE
2. Bancos ? de verdad quieres que ponga la lista de 97 bancos ?
3. Riesgos, sin cambios
4. Tipo Percepción = DONE

**Comment by RigoFlores** [comment]
Dime como los puedes subir a la BD o en un archivo de texto o al código .... y te lo envío...
La idea es que estén completos todos los catálogos...

**Comment by jccastillo0007** [comment]
en el caso de bancos y percepciones, no están en base de datos, si no en enum
no es nada dificil, pero ser vería engorroso subir 97 bancos, cuando casi siempre usan unos 20 o 30 máximo

**Comment by RigoFlores** [comment]
Tipo de percepcion, falta agregar las percepciones nuevas.

**Comment by RigoFlores** [comment]
Lo de los bancos lo podemos dejar, pero tarde o temprano los tendremos que capturar... hasta el momento, cubrimos a nuestros clientes con ello...

**Comment by jccastillo0007** [comment]
Ya están listas, solo que no he subido un release a PRU, ma;ana temprano ya estará en PRU.

**Comment by RigoFlores** [comment]
lo cerraré y se atenderán individualmente.
