### ISSUE TITLE
Nomina 1.2 - Agregar los catálogos nuevos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#752]
- Catálogo de Entidades Federativas. Se incluye en los generales del Empleado.
- Periodicidad de Pago. Incluir catálogo en combo
- RégimenFiscal. En la pantalla de configuración se deberá mostrar la leyenda del régimen, e incluir la clave correspondiente en el XML.
- Tipo de Contrato
- Tipos de Hora Extra
- Tipo de Incapacidad
- Tipo de Jornada
- Tipo de Nómina.- (se agrega a los generales de cada empleado)
- Tipo Otro Pago . Aquí para no cambiar lo actual, sugiero agregarlo al final de las percepciones. Internamente la aplicación deberá distinguir entre percepciones y otro pago.

**Comment by jccastillo0007** [comment]
Catálogo de Entidades Federativas. Se incluye en los generales del Empleado. (JC. Done)
Régimen Fiscal, (JC, Done)

**Comment by RigoFlores** [comment]
Negativo, ese no es para sustituir la dirección del empleado, que creo que ya ni se requiere

**Comment by jccastillo0007** [comment]
Listo, ya están todos estos catálogos, estoy trabajando sobre el de Otro Pago, espero subirlo hoy mismo.
Estos catálogos los puedes ver en la opción de Recibo de Nómina del menú Nómina.

**Comment by RigoFlores** [comment]
lo voy a cerrar para tratarlos individualmente
