### ISSUE TITLE
Producción - Proveedores -Subir CFDI

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#754]
No en todos los casos sube el XML, pero si está el registro de la factura. (accediendo como proveedor).
RFC cliente nuestro EARA620117GT8.
Supongo que aplica también desde el menú de compras, cuando accedes como emisor.

**Comment by jccastillo0007** [comment]
por un lado, ya arreglé el problema con los XML que no se ven en PRO para ese RFC, y voy a subir un fix para evitar que vuelva a suceder.
El problema era que el folio del XML trae un '0' a la izquierda, y al convertirlo a numérico ese '0' se pierde... el fix hace que el archivo se guarde sin el che '0'
