### ISSUE TITLE
Pantalla de configuración

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#759]
Agregar en la pantalla de configuración, la captura del CURP.
El curp se deberá capturar cuando:

a) El RFC sea de persona física (13 caracteres de longitud)
b) Emita nómina con nosotros.

Hay que validar dicho escenario (son de las validaciones del SAT).

**Comment by RigoFlores** [comment]
Ahora mismo, pide el curp a hueso, siendo que la cuenta es de persona moral.
Falta implementar la validación que sea persona física y que tenga contratado con nosotros la nómina. Son 2 condiciones requeridas

**Comment by jccastillo0007** [comment]
Ok, ingresé la validación de que si el RFC = 13 posiciones, la CURP debe ir informada, de lo contrario es intravenoso si la ponen o no, ya no es obligatoria para todos los casos.

El tema de que si tiene o no nómina con nosotros, lo voy a validar cuando generen recibo de nómina, ahi es el mejor lugar para hacerlo, ya que en la pantalla de configuración no necesariamente debemos saber que si tiene contratado o no.

**Comment by RigoFlores** [comment]
Lo que sucederá es que para personas físicas que no tengan contratada la nómina, les pedirá como obligatorio un dato que no es requerido (si no emiten nómina).
Cuando capturen el curp también hay que validar que sea de longitud 18.

**Comment by jccastillo0007** [comment]
no le veo problema con pedir la CURP, pues que la ingresen y listo.
Voy a validar que sea de 18.

**Comment by RigoFlores** [comment]
No le ves problema a capturar un dato de 18 caracteres, todo raro... cuando no es obligatorio.
Terminaré diciendo que si no tienen nómina pongan cualquier cosa y eso me parece menos profesional aún. 
Pero seguro habrá quién no lo tenga a la mano, y que además no tenga nómina con nosotros. De hecho la mayoría.
