### ISSUE TITLE
Mostrar los datos completos del cliente en pantalla de Acerca de....

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#76]
En la pantalla de Acerca de Factura-T, mostrar los datos del emisor:
Nombre o Razón social:
RFC:
Calle + no ext + no int
localidad, municipio, estado, CP

mas o menos en esa distribución...

**Comment by RigoFlores** [comment]
Faltó la información de correo (no la había solicitado previamente), dado que existe la opción de enviar al emisor, es importante que el cliente sepa, cuál es ese correo configurado del emisor, al cuál llegarían las facturas.
Si nos queremos lucir, también indicar el nombre del contacto, y sus teléfonos.

**Comment by jccastillo0007** [comment]
Done.
