### ISSUE TITLE
Nomina 1.2 Agregar catálogo de entidades federativas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#760]
En la pantalla de nómina individual, a nivel de datos generales del empleado, agregar el catálogo de entidades federativas.
Se puede agregar desde ya, pero no se enviará.
POR OMISIÓN, SU VALOR ES EL ESTADO DEL DOMICILIO FISCAL DEL EMISOR.

**Comment by jccastillo0007** [comment]
Listo, por ahora se muestra donde esta la dirección del empleado, después quitaremos la dirección y solo se quedará la entidad federativa.

**Comment by RigoFlores** [comment]
Faltó que el valor por omisión sea el estado del domicilio fiscal.

**Comment by jccastillo0007** [comment]
Listo.

**Comment by RigoFlores** [comment]
Pues no, si quedó en pruebas no está colocando el estado del emisor (domicilio fiscal).
Si quedó en producción, no tengo forma de validarlo porque no tengo acceso al menú.

**Comment by RigoFlores** [comment]
Este empleado FIAA6505253H7 tiene en estado Morelos, pero el estado del emisor es Querétaro.
Cuando vayamos a producción, este dato tendrá que ser el estado del emisor.
