### ISSUE TITLE
Nomina 1.2 Agregar el catálogo de Periodicidad de Pago.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#761]
Hoy es libre captura en la pantalla de nómina individual, en el header.
Para lo nuevo, se debe tomar el catálogo del SAT.
Lo podemos llevar ya a producción, enviando la descripción de catálogo.

OJO OJO OJO
Seguramente en la versión 1.2 se tendrá que enviar una clave, pero mientras tanto se enviará la descripción.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Despliega el catálogo, no puedo validar que se tome de BD, pero si lo despliega.
No puedo validar si envía la leyenda correcta al XML ahora, ya que no me permite timbrar.

**Comment by jccastillo0007** [comment]
A caray,... estoy viendo la pantalla y este catálogo aún no esta, me falto subirlo a PRU...

**Comment by jccastillo0007** [comment]
Listo, ya subí este catálogo
