### ISSUE TITLE
Nomina 1.2 Agregar el catálogo de Tipo de Contrato en nómina individual

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#762]
Hoy es de libre captura
Se puede agregar el catálogo sin afectar la funcionalidad actual.
Se lleva a PRO y se envía la descripción.
En la nómina 1.2, seguramente se enviará la clave.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Ya despliega el catálogo.
No sé donde validar si lo está tomando de una tabla (BD), así como quedamos.
No puedo validar si envía al XML la leyenda correcta, porque no me permite timbrar.
Probé con el primer empleado de la tia en pruebas, Alberto Figueroa Almanza

**Comment by jccastillo0007** [comment]
Tested. con el empleado con RFC FIAA6505253H7
