### ISSUE TITLE
Nomina 1.2 Agregar el tipo de Jornada en la nómina Individual

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#763]
Hoy es de libre captura.
Se debe incluir el catálogo del SAT.
Hoy se enviará la descripción.
Para enero seguramente se enviará la clave
Son compatibles hoy en día.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Ya despliega el catálogo.
No sé donde validar si lo está tomando de una tabla (BD), así como quedamos.
No puedo validar si envía al XML la leyenda correcta, porque no me permite timbrar.
Probé con el primer empleado de la tia en pruebas, Alberto Figueroa Almanza

**Comment by jccastillo0007** [comment]
Mismo comentarios de los otros defectos... para no hacer copy / paste de la respuesta.

Varios de los catálogos ya los tenía en enum, solo los complementé, me parece que solo entidad federativa y régimen fiscal estan en base de datos.

**Comment by jccastillo0007** [comment]
Listo, ya lo validé con el RFC FIAA6505253H7.
