### ISSUE TITLE
Nomina 1.2.- Agregar catálogo de Tipo de Nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#764]
Este dato no existe actualmente. Se agrega en los generales de nómina individual. (header).
Se agrega desde YA y no afectará a lo actual, mientras no se utilice.
Sin embargo sirve para hacer transparente la migración.
Valor por omisión 'O'   (ordinaria).

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Ya despliega el catálogo.
No sé donde validar si lo está tomando de una tabla (BD), así como quedamos.
No puedo validar que NO lo envíe por lo pronto al XML porque no me permite timbrar.
Probé con el primer empleado de la tia en pruebas, Alberto Figueroa Almanza

**Comment by jccastillo0007** [comment]
Este catálogo esta en un enum.

Deja veo porque no timbra, es probable que sea el pedo del pac, ya que para el XML no se han hecho cambios, eso sucederá hasta Enero... a menos que podamos iniciar las pruebas con Finkok quien se supone ya esta listo para esta versión.

**Comment by jccastillo0007** [comment]
Tested. con el empleado con RFC FIAA6505253H7
