### ISSUE TITLE
Nomina 1.2 Agregar catálogo de tipo de horas extra

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#765]
En la sección de horas extra, dentro de la nómina individual hoy es de libre captura.
Se agrega el catálogo y por omisión serán simples.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Ya despliega el catálogo.
No sé donde validar si lo está tomando de una tabla (BD), así como quedamos.
No puedo validar si envía al XML la leyenda correcta, porque no me permite timbrar.
Probé con el primer empleado de la tia en pruebas, Alberto Figueroa Almanza

**Comment by jccastillo0007** [comment]
Este catálogo esta en un enum.

Deja veo porque no timbra, es probable que sea el pedo del pac, ya que para el XML no se han hecho cambios, eso sucederá hasta Enero... a menos que podamos iniciar las pruebas con Finkok quien se supone ya esta listo para esta versión.
