### ISSUE TITLE
Nomina 1.2 - Actualizar claves en el catálogo de incapacidades

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#766]
Nomina Individual, sección Incapacidades. 
Lo que cambió fueron las claves. 
Este cambio si pegaría, en caso que algunas de nuestras nóminas ocupen incapacidades.
¿podemos saber si alguien las ocupa?
Antes eran:

1 Riesgo de trabajo
2 Enfermedad en general
3 Maternidad

Ahora son:

c_TipoIncapacidad	Descripción
01	Riesgo de trabajo.
02	Enfermedad en general.
03	Maternidad.

**Comment by jccastillo0007** [comment]
En realidad, el catálogo ya esta bien, con las claves 01, 02 y 03, solo que actualmente la clave de incapacidad en el schema es un entero, entonces se convierte a entero y quedan 1, 2 o 3
Para Enero, con el nuevo schema simplemente se quitará dicha conversión.
