### ISSUE TITLE
Nomina 1.2 - Agregar seccion de Otro Pago, en nómina Individual

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#767]
Como si fueran percepciones, deducciones, incapacidades y horas extra, se deberá agregar esta sección, donde se capturan 3 datos:
Esto también se puede agregar y no afectará a lo actual, mientras no se ocupe.

Tipo de Otro pago. Se toma del catálogo del SAT
Clave.- Se sugiere con opcion a cambio, la misma clave del sat
Descripción. Se sugiere con opcion a cambio, la misma descripción del sat
Importe

**Comment by jccastillo0007** [comment]
mmm tanto el tipo como la clave están definidas en el catálogo.

Done.

**Comment by RigoFlores** [comment]
Por lo pronto se cubre este issue.
Falta validar que lo envie al XML, pero eso será en las pruebas de timbrado
