### ISSUE TITLE
Error 113, no se puede guardar CFD en BD (web)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#768]
Resulta que cuando capturan un concepto muuuy largo (catálogo de productos), marca este error.
lo correcto es que el concepto se algo corto, y si requieren algún enunciado lo capturen en la seccion de descripción.

El asunto es que la aplicación permite conceptos muy largos, pero al momento de timbrar marca error.
Hay que limitar esas capturas, indicando el número de caracteres máximo permitidos, y en todo caso que capturen en la descripción.

Ahora mismo, tenemos ese problema... lo podemos ajustar por queries?

**Comment by jccastillo0007** [comment]
me puedes pasar los datos de un error como este?, para revisar donde esta el problema, capaz que si se puede resolver por  query.

**Comment by RigoFlores** [comment]
EN PRUEBAS, CON FECHA DE HOY (26 NOV)... INTENTÉ ALMACENAR UN CONCEPTO LARGO Y ME MARCÓ ERROR.
CON ESO LO PUEDES RASTREAR?

**Comment by jccastillo0007** [comment]
ok, ya lo ví, y agregué una validación para que no permita captura de nombres tan largos, máximo 200 caracteres, que ya es mucho, pero lo permite la base de datos.

Mi duda es que crei que todo esto sucedia al momento de timbrar, pero al parecer, es al momento de guardar o actualizar un producto.

**Comment by RigoFlores** [comment]
Son 2 problemas distintos, que se podrían solucionar de una vez.
1) Al momento de almacenar no debe permitir conceptos tan largos. Se podría hacer que al 7 espacio en blanco (para tomar las primeras 7 palabras), trunque y el resto del concepto lo agregue al principio en descripción?
2) Hoy en día ya existen conceptos que se capturaron en su momento muy largos. Entonces ese error se presenta al momento de timbrar. Aquí es donde me refería que lo solucionemos por queries, es decir a todas aquellos conceptos con mas de 200 de longitud, tomar quizas los primeros 20 como concepto y el resto enviarlo a descripcion. OJO, tener cuidado en caso que ya exista una descripción capturada, ya que se tendrá que enviar hasta el final.

**Comment by jccastillo0007** [comment]
En realidad esa restricción no deberiamos tenerla, la base de datos soporta longitudes grandes, y el XML no tiene límite, estuve checando y la longitud mas grande de un campo name en la tabla Products es de 383, ni siquiera es tanto, lo que hice es modificar la tabla donde se guardan los productos facturados, para soportar longitudes mayores a 255 que es el default.

**Comment by RigoFlores** [comment]
ya está en producción?

**Comment by jccastillo0007** [comment]
Correcto.

**Comment by RigoFlores** [comment]
El problema de permitir conceptos muy largos, es que la pantalla se deforma totalmente, ya que el combo queda muuuy ancho.
Por ello pedía que quedara de la siguiente manera:
Concepto= primeras 7 palabras
Descripción = todo el contenido después de las primeras 7 palabras + descripción anterior.
