### ISSUE TITLE
Una vez que guardas configuración, no muestra el curp

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#769]
No puedes saber que valor capturaste en el campo curp, porque no lo muestra una vez que lo salvaste en la BD (pantalla de configuración)

**Comment by jccastillo0007** [comment]
Si esta guardando la CURP en BD y si la muestra cuando entras a la pantalla de configuración, tal vez se te olvido darle salvar, ya que revisé la bd y solo yo y figueacero tienen curp (fueron mis pruebas)

**Comment by jccastillo0007** [comment]
Fixed.
