### ISSUE TITLE
Genera el error 401 y bloquea toda emisión de facturas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#77]
Este error se presenta comúnmente, que tiene que ver con sincronía del reloj del equipo del emisor, vs el reloj del sat o edicom (asumo edicom).
Como podríamos asegurar que no se presente, ya que bloquearía la emisión de todos los clientes...

**Comment by jccastillo0007** [comment]
Una opcion es generar automaticamente un factura en el ambiente de pruebas, (para edicom es el mismo server, solo cambia el metodo) y revisar la hora y fecha.

Puedo generar un script que corra diario y genere una factura, revisar la hora del sistema de edicom y enviarnos un correo, para validar que siempre estemos por debajo de ellos.... 

Otra opcion seria sincronizar la hora de nuestro servidor con el mismo servidor con el cual se sincronizan ellos.

Le voy a poner estatus de enhacements.,

**Comment by jccastillo0007** [comment]
Este defecto, supongo ya no procede, ya que no timbramos con Edicom.

**Comment by RigoFlores** [comment]
Ah cabrón... yo creo que este error no debería ser propio de Edicom, o sí???
No debería permitir timbrar con fecha posterior a la actual... facturehoy si lo permite?

**Comment by jccastillo0007** [comment]
es que la descripción menciona específicamente Edicom, y con FactureYa no hemos tenido ese problema, asi que yo creo que ya no es necesario.

**Comment by RigoFlores** [comment]
Bueno, realmente yo nunca mencioné edicom, fuiste tú en su primer comentario.
Ya validé y facturehoy, también puede marcar ese error.

No hay que perder de vista el contexto de este problema. Lo que indica es que cuando llega a pasar que en el servidor de producción (incluso de pruebas pasó hace poco), se adelanta la hora, entonces se BLOQUEA TODA LA EMISIÓN DE FACTURAS... entonces lo que se requiere es garantizar que el servidor nunca adelantará su hora... o que llegado el momento se detectará y corregirá en automático.

**Comment by jccastillo0007** [comment]
entiendo el contexto, pero desde que timbramos con facture hoy no hemos tenido ese problema, el caso de PRU fué diferente, porque se cambió la zona horaria... 

Sugiero cerrar este ticket y abrir otro si es que ocurre con facture hoy.

**Comment by RigoFlores** [comment]
Si lo podemos cerrar, aunque podríamos incluir en el reporte de timbradas la hora del servidor para comparar con la hora de nuestras máquina y estar pendientes de que no se adelante 'mucho' o suficiente para que marque este error.
Como ves, lo cerramos incluyendo el reloj del servidor en dicho reporte. O quizás sea suficiente con saber a que hora se dispara ese reporte

**Comment by jccastillo0007** [comment]
no creo que sea buena idea, o no estoy entendiendo.

Si ponemos la hora del servidor al momento de generar el reporte, pues todas las facturas tendrán su propia fecha, y al mismo tempo todas tendrán la fecha actual del servidor, no le veo la relación entre las dos fecha/hora

Si lo que quieres es estar al pendiente de la hora del servidor, lo podemos ver nosotros, al momento de generar una factura, justo ahí trae la fecha del servidor y la fecha de timbrado, de hecho todas las facturas tienen esas dos fechas, y ahi podemos darnos cuenta de la diferencia.

Este problema de diferencia de fecha/hora nunca se ha dado con facture hoy, según yo.

**Comment by RigoFlores** [comment]
Lo que yo proponía es al momento de generar el reporte de folios consumidos (que se genera diariamente), incluir la hora del servidor al momento de emisión del correo, para que al llegar (que casi debería ser simultáneo), podamos comparar.
Lo cierro y estaremos pendientes.
