### ISSUE TITLE
Nomina 1.1, marca error al timbrar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#770]
Con la integración de los nuevos catálogos, donde se debería de tomar la leyenda y no la clave (para nomina 1.1), no me permite timbrar ahora mismo.
Si ya me permitiera timbrar podríamos subir a producción estos cambios.
Primero marcó Null(3) y en un segundo intento marcó internal error.

**Comment by jccastillo0007** [comment]
El problema eran básicamente 2 cosas.
1. Edicom
2. La CLABE del empleado no estaba completa

**Comment by RigoFlores** [comment]
OK, cuando la CLABE no esté completa, debería entonces enviar otro mensaje, que no?
