### ISSUE TITLE
CxC - Cartera por Cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#771]
No funciona el filtro de RFC + NoCliente.
Este filtro debe funcionar idéntico al de ingresar cobro.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Mismo comportamiento.
Cuando tengo un RFC + número de cliente, OK.
Pero si de ahí elimino número de cliente, el filtro del RFC ya no lo toma en cuenta y muestra todo.

**Comment by jccastillo0007** [comment]
Si, tengo ese detalle, y no sé porque pierde el RFC, sigo chequeando
