### ISSUE TITLE
CxC - Cartera por Cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#772]
Falta implementar el reporte de Cartera x Cliente.
Una vez que se aplican los filtros, debe generar un excel como el que se indica en la spec, esto es el excel que se llama Reportes, pestaña x Clientes.
El reporte en sí ya lo había ingresado en otro issue.
Se debe ver así:

![reportexcliente](https://cloud.githubusercontent.com/assets/2912775/20847374/6007742c-b893-11e6-93e3-c5f0248ae91f.jpg)

**Comment by RigoFlores** [comment]
Aquí aparecen los cargos y abonos, así como el saldo.
El saldo se va incrementando registro a registro.
El saldo total, es igual al último saldo.
De hecho este excel, esto debe ser muy parecido a la pantalla de ingresar cobro.

**Comment by RigoFlores** [comment]
Ya lo tenemos en pantalla, solo hay que llevarlo a excel:
![reportecarteraxcliente](https://cloud.githubusercontent.com/assets/2912775/20847514/18a114e8-b894-11e6-81a3-879ec39796fe.png)

**Comment by RigoFlores** [comment]
Si te das cuenta ya está, salvo las siguientes observaciones:
Saldo=saldo anterior + cargos - abonos.  (esto es, ahora mismo está chueco el cálculo, sale con signo negativo).
El saldo se debe ir acumulando, no es un saldo por factura, sino considerar el saldo anterior.
Al final falta agregar un Saldo Total, que realmente es el último saldo.

**Comment by jccastillo0007** [comment]
Done... solo no agregué eso del saldo al final....  donde sería bueno, hasta abajo ? antes de la tabla? o esta de más.?

**Comment by RigoFlores** [comment]
Es estrictamente necesario (aunque se repite con el último saldo).
Donde, en la misma posición que se muestra de la imagen de su reporte actual, en este issue

**Comment by RigoFlores** [comment]
Pues aunque ya lo puso, el folio de las facturas es incorrecto... en todos lados para optibelt..
algo le moviste

**Comment by jccastillo0007** [comment]
Negativo... asi esta.
