### ISSUE TITLE
CxC - Dar opción para modificar la fecha de vencimiento.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#773]
No está condicionado a nada.
Anteriormente se manejó una condición (que ya hubieran capturado algún pago parcial), pero no... no aplica.
Se debe poder modificar la fecha, que originalmente se calcula con base a las condiciones de pago que vienen en el archivo.

**Comment by jccastillo0007** [comment]
En donde es el mejor lugar para permitir esta configuración ? en las pantallas de CxC no se maneja esa fecha ....

**Comment by RigoFlores** [comment]
Precisamente en CxC existe una columna que dice Vencimiento... no se si aquí convenga o quizás en la pantalla de Compras-Consultas-Editar... ahí hoy en día se capturan los pagos... quizás sería bueno que ahí mismo se pueda modificar dicha fecha...
Me late mas en ventas-consultas-editar... de hecho, está puesto para ello...

**Comment by jccastillo0007** [comment]
de hecho si, son ventas no compras...

**Comment by RigoFlores** [comment]
Correcto, quise decir ventas..

**Comment by jccastillo0007** [comment]
Pues la buena noticia es que eso ya se puede hacer... jojojo, la pantalla que se abre para editar una factura, solo te permite modificar la fecha de vencimiento e introducir un comentario.

**Comment by RigoFlores** [comment]
Probando con Optibelt, manda internal error

**Comment by RigoFlores** [comment]
sin cambios aún?

**Comment by jccastillo0007** [comment]
Es que borramos todo lo de Optibelt jojojojo, y no pude probar lo del error que manda... lo puedes reproducir con alguna factura de la TIA ?

**Comment by RigoFlores** [comment]
De optibelt en pruebas tenemos facturas desde el 13 de diciembre... es decir, inmediatamente despues de que las borraste, volví a generalas

**Comment by jccastillo0007** [comment]
Chiaaaa no sabia... bueno ya esta arreglado.

**Comment by RigoFlores** [comment]
El comentario y el historial de cambios, donde se pueden consultar?
