### ISSUE TITLE
RECARGA DE FOLIOS - NO MUESTRA FOLIOS DISPONIBLES.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#776]
NO MUESTRA LOS FOLIOS DISPONIBLES, EN SU LUGAR MUESTRA EL 'CURRENT FOLIO'

LOS FOLIOS DISPONIBLES, SON LA **SUMATORIA DE AQUELLOS RANGOS QUE TENGAN STATUS '0'**, Y 
SE CALCULAN: **FOLIOS DISPONIBLES = RANGO FINAL - CURRENT FOLIO**

**Comment by jccastillo0007** [comment]
fixed, favor de revisar en 12/07
