### ISSUE TITLE
Nomina 1.2  Descuento = totalDeducciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#784]

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
no aparece en el XML el descuento... ni siquiera se pudo validar la resolución a esta ficha

**Comment by jccastillo0007** [comment]
antes el descuento eran las deducciones distintas a ISR, ahora incluye el ISR también?

**Comment by RigoFlores** [comment]
Entiendo que si. Lo que dice el sat es:

es la suma de todas las deducciones (descuentos) aplicables al trabajador, incluyendo el Total Impuestos Retenidos (ISR), esto es la suma de "TotalOtrasDeducciones" mas "TotalImpuestosRetenidos" de las deducciones

**Comment by RigoFlores** [comment]
afirmativo.... lo que pasa es que el ISR se reporta por otro lado
