### ISSUE TITLE
Nomina 1.2 - Eliminar la captura de método de pago y número de cuenta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#787]
Para nómina 1.2, el método de pago es 'NA' simplemente, y el número de cuenta no se reporta al XML

**Comment by jccastillo0007** [comment]
El número de cuenta pasa a ser la cuenta bancaria cierto ?
Es decir, entre CLABE y Número de cuenta, solo nos quedamos con uno que ahora se llama Cuenta Bancaria.

**Comment by RigoFlores** [comment]
Creo que si..... es decir no entendí muy bien pero es así:
Método de Pago + Número de Cuenta = (son como viruta y capulina, como tin tan y su carnal marcelo, como el gordo y el flaco... van juntas, van de la mano, como diría polo polo, 'como calzón y caca').... estas desaparecen.
Anteriormente existía CLABE, esta es la que pasa a ser Cuenta Bancaria.
Internamente no sé como se te facilite, pero conceptualmente se mantiene CLABE, solo que cambia de nombre y método de pago/numero de cuenta se eliminan
