### ISSUE TITLE
Nomina 1.2, eliminar domicilio fiscal y expedido en del emisor

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#790]

**Comment by jccastillo0007** [comment]
Done... esto del complemento de la nómina verdad, no del CFDi normal.?

**Comment by jccastillo0007** [comment]
Ups lo cerré por error.

**Comment by RigoFlores** [comment]
chiaaaa... en el complemento no van esos datos... no puede decir que se atendió, cuando no se hizo nada...
Cuando indico complemento nomina 1.2, me refiero en sí al complemento.
Cuando indico nomina 1.2, me refiero al cfdi estándar que acompaña al complemento de nómina.

**Comment by jccastillo0007** [comment]
mismo caso que el nodo vacío de impuestos... estos cambios pueden afectar todos los CFDis, esta delicado...
