### ISSUE TITLE
Nomina 1.2 - A nivel de concepto.... varios candados...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#791]
Solo debe existir un concepto, con cantidad=1, Unidad de medida='ACT', noIdentificación NO DEBE EXISTIR, descripcion= 'Pago de Nómina', valor unitario = totalPercepciones + totalOtrosPagos

**Comment by jccastillo0007** [comment]
chiaaaa este issue ya esta repetido con algún otro que ya esta resuelto.

**Comment by RigoFlores** [comment]
le sobra un espacio a la descripcion.
Lo del valor unitario, será lo último que valide, ya que tiene que ver con los totales, y aún no llego a esa parte.

**Comment by jccastillo0007** [comment]
fixed.
