### ISSUE TITLE
Nomina 1.2, régimen del emisor, enviar clave en lugar de descripción

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#792]

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Chiaaaa... no está enviando la clave correcta, además que en cuyo caso tiene que ir 02 y no 2.
Aquí se refiere al régimen fiscal del emisor... no es el el TipoRegimen del empleado.
Estas claves son las que corresponden al catálogo que se encuentra en la pantalla de configuración, donde capturas los sellos, el curp, el logo, etc...
chiaaaaaa

**Comment by jccastillo0007** [comment]
Fixed.
