### ISSUE TITLE
Nomina 1.2 - Nodo Impuestos - se reporta así: <Impuestos/>

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#793]
Ya que no se reporta el nodo de trasladados ni retenidos... a nivel XML estándar

**Comment by jccastillo0007** [comment]
mmm osea, es correcto que se reporte <Impuestos/> o es incorrecto, según yo es incorrecto, pero no es claro el issue, es como las percepciones y deducciones cuando no hay cierto.?

**Comment by RigoFlores** [comment]
Aquí dice A NIVEL ESTANDAR, es decir no estamos hablando del complemento, sino del XML estándar.
Y lo que pide es que el nodo de impuestos (que por cierto no se incluye a nivel del complemento), deba reportarse así como lo menciono arriba.

**Comment by jccastillo0007** [comment]
No se para que quieres que se reporte vacío, normalmente piden lo contrario, si se puede hacer, pero esto sucederá en todas las facturas generadas, esta bien ?

**Comment by RigoFlores** [comment]
A ver, estamos confundidos...
a) yo no lo quiero así o de otra manera, así lo pide el sat
b) aquí estamos tratando el tema de nómina, no sé en que momento entraron las facturas

Nómina = CFDi estándar (con los ajustes de nómina) + Complemento de Nómina

**Comment by jccastillo0007** [comment]
Lo que digo, es que el CFDI estándar es una CFDi tal cual, con algunos ajustes para la nómina, como el tema de un solo producto, si pongo el nodo de impuestos vacío, entonces eso se lo va a poner a todas las facturas en la sección de CFDi estándar.
Lo del complemento de nómina es aparte.
Hemos tenido algún problema por no incluirlo ? llevamos casi miles de CFDis, nunca se ha dado ese caso? o apenas si lo pidió el SAT ?

**Comment by RigoFlores** [comment]
No hemos entendido... todo lo que estoy pidiendo es nuevo para la nómina.
Hay cambios que aplican a nivel CFDi estándar (cuando es recibo de nómina), y también hay cambios en el complemento.
Este cambio así lo pide el SAT para esta versión, y debe aplicar solo cuando sea CFDI + Complemento de nómina.
Si hablamos de facturas o cualquier otro CFDI, se mantiene normal como hasta ahora.

**Comment by jccastillo0007** [comment]
eso es lo que no has entendido... 
"Si hablamos de facturas o cualquier otro CFDI, se mantiene normal como hasta ahora."
el cambio de agregar el nodo de impuestos vacío solo cuando es nómina, no lo puedo hacer  a como esta ahorita la solución... tendría que hacer varios cambios...

Hay que esperar un poco

**Comment by jccastillo0007** [comment]
chiaaaa.... done.
