### ISSUE TITLE
Complemento Nomina 1.2 - Validación tipo de nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#794]
Cuando el tipo de nómina es O (ordinaria), entonces la periodicidad de pago solo puede ser del 01 al 09.
Cuando el tipo de nómina es E (extraordinaria), entonces la periodicidad de pago en automático debe ser 99.

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
Podemos amarrar que cuando tipo de nómina sea E, la periodicidad de pago sea 99 (ya ví que sí), pero además que no la puedan cambiar? porque ahora mismo se podría cambiar y entiendo que generaría un error al timbrar.
Digamos nomina = 'E', periodicidad de pago igual a 99, y no lo pueden cambiar.
Con nómina ='O', entonces se habilita el combo para que lo cambien.

**Comment by jccastillo0007** [comment]
no hay problema porque la cambien, marcará error al intentar salvar

No es factible implementar esa validación, ya que cuando sea O y se habilite el combo, no deberían elegir 99, como quiera al momento de salvar se debe validar la info.

**Comment by RigoFlores** [comment]
Preveo llamadas de soporte... "no me permite guardar"
Pero ok, lo dejamos así a ver como se comporta...
