### ISSUE TITLE
Complemento nomina 1.2, fechas de pago para nómina tipo E

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#795]
Cuando el tipo de nómina sea E, se tomará como referencia la fecha de pago, y se asignará a la fecha inicial de pago, y fecha final de pago.
Es decir las 3 fechas iguales, considerando como eje o referencia, la fecha de pago.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Elegí nomina E, luego cambié la fecha de pago... y no actualizó las otras fechas.
Le dí salvar y luego consulté... y nada, las fechas inicio y fin no las actualizó a fecha de pago...

**Comment by jccastillo0007** [comment]
mmm bueno, las fechas de inicio y fin se actualizan al momento de facturar... no en pantalla, deja le pongo eso

**Comment by jccastillo0007** [comment]
Done.
