### ISSUE TITLE
Complemento Nomina 1.2, agregar sección de Separación Indeminización

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#797]
Hoy en día aparece hasta arriba las Percepciones.
Debajo de esta sección se capturan las horas extra (es decir se reubica horas extras)
Debajo de horas extras, la sección de **Separacion Indeminización** (esta seccion no entiendo porque no la solicité junto con la otra nueva).

Estos 3 bloques conformarán el nodo completo de Percepciones, por ello solicito que se junten hasta arriba.

Indeminzaciones ocupa: 
TOTAL PAGADO      totalPagado   Atributo requerido que indica el monto total del pago.
NUMERO DE AÑOS DE SERVICIO      numAniosServicio   Atributo requerido para expresar el número de años de servicio del trabajador. **Se redondea al entero superior si la cifra contiene años y meses y hay más de 6 meses.**
ULTIMO SUELDO MENSUAL ORDINARIO      ultimoSueldoMensualOrdinario   Atributo requerido que indica el último sueldo mensual ordinario
INGRESO ACUMULABLE      ingresoAcumulable   Atributo requerido para expresar los ingresos acumulables.
INGRESO NO ACUMULABLE      ingresoNoAcumulable   Atributo requerido para expresar los ingresos no acumulables.

**Comment by jccastillo0007** [comment]
Oye, las percepciones de acciones o titulos y la de JubilacionPensionRetiro, también ocupan algunos datos particulares, las deberíamos sacar a capturarlas fuera de las Percepciones, tal como Horas Extras e Indemnizaciones ?

**Comment by jccastillo0007** [comment]
Además de la pregunta anterior ( y que no la pelaste), te comento que moví la sección de Otros Pagos debajo de Separación Indemnización... para dejar todas las percepciones juntas.

**Comment by jccastillo0007** [comment]
Listo... oye estas cifras se acumulan junto con las percepciones cierto ?

Estoy sumando el total de cada indemnización...

**Comment by RigoFlores** [comment]
Lo de las sumas aún no reviso como quedan.
Lo de otros pagos, yo lo dejaría al final, ya que según yo no se ocupará tanto, o quizás nunca (al menos con nuestros clientes).
Lo de jubilación pensión retiro, lo dejé pendiente por lo pronto (dijimos que saldríamos con la versión mas ligera posible). Si ya lo quieres incluir, que se coloque hasta el final de la pantalla. No creo que tengamos ese caso ya que nuestros clientes no creo que estén pagando jubilaciones o pensiones; eso es mas del gobierno.
