### ISSUE TITLE
Complemento nomina 1.2, cuando no apliquen percepciones o deducciones, no se incluye el nodo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#798]
Es posible que solo exisitieran por ejemplo otros pagos, entonces no se reporta el nodo de percepciones.
Igualmente si no se capturó ninguna deducción, no se reporta dicho nodo.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Sigue abierto, ya lo comentamos por correo..

**Comment by RigoFlores** [comment]
Ahora mismo no permite generar un recibo, si no lleva deducciones, lo cual es incorrecto.

**Comment by RigoFlores** [comment]
tenemos un cliente esperando este issue.
Si en un recibo no lleva deducciones, no debe intentar armar el nodo a huevo.

Hoy en día, hay que ponerle al menos 1 centavo, para que el nodo de deducciones lo forme bien, de lo contrario marca XML mal formado.

**Comment by jccastillo0007** [comment]
para standalone ya esta lista la version en dropbox

**Comment by jccastillo0007** [comment]
para web ya esta en PRU.

Ojo.. en ningún caso pude probar un caso de éxito, timbrando el recibo de nómina, ya que no cuento con datos para probar... pero estuve manipulando los datos disponibles y verifiqué que el xml no generara percepciones o deducciones vacías...

**Comment by RigoFlores** [comment]
Creo que no solo se trata de no incluir el nodo de deducciones.
Supongo que al momento de armar el XML, por omisión incluyes el parámetro de descuento, y el descuento está directamente relacionado a la deducciones.
Entonces ahí es donde ahora truena:

CFDI33110 : El TipoDeComprobante NO es I,E o N, y un concepto incluye el campo descuento. (3)

Validé en pruebas con el usuario TCM970625MB1 y con el único empleado que tiene dado de alta.
Lo que no estoy seguro es, si no se debe incluir el parámetro descuento, o se debe incluir con valor = 0.
Supongo que si no se incluyen deducciones, no se debe reportar.

**Comment by jccastillo0007** [comment]
listo en pru

**Comment by RigoFlores** [comment]
Ya validé sin deducciones y con deducciones.
Yo creo que ya hay que llevarlo a pro. Lo están esperando
