### ISSUE TITLE
Complemento nomina 1.2, Condicionar la captura de registro patronal

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#799]
Cuando el tipo de contrato sea del 01 al 08, deberá incluirse el registro patronal (requerido para estos tipos de contrato).
Si el registro patronal se captura, entonces se obliga a capturar también:
NUM SS, FECHA INICIO RELACIÓN LABORAL, ANTIGÜEDAD, RIESGO PUESTO, SDI. 
EN CASO QUE EL REGISTRO PATRONAL NO SE CAPTURE, NO SE CAPTURA NINGUNO DE LOS ANTERIORES

**Comment by jccastillo0007** [comment]
Done. Favor de validarlo el 12/13
