### ISSUE TITLE
Si el impuesto no tiene descripción, tiene un comportamiento extraño el manejo de impuestos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#80]
Cuando el campo de descripción en el catálogo de impuestos, lo dejas vacío, el sistema se comporta de manera irregular.
1) En la pantalla de la factura no muestra los impuestos en la sección correspondiente
2) En el total si los incluye
3) En el preview, sucede lo mismo

**Comment by RigoFlores** [comment]
Generé la factura A2 tuya, para que valides como queda el PDF y el XML, cuando la tasa de 16.00 no cuenta con descripción

**Comment by jccastillo0007** [comment]
Fixed.

Voy a usar esta factura para intentar cancelarla.

JC.
