### ISSUE TITLE
Complemento nomina 1.2, calcular la antigüedad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#800]
Se debe calcular con base a la fecha de inicio de relación laboral para cada emisión de recibos.
Lo podemos reportar en semanas:

Por ejemplo si tiene antigüedad de 110 semanas, se reporta así:
Antigüedad=P110W

Es decir siempre llevará una P al principio, y para no estar calculando varios formatos, podemos casarnos con el de semanas.

**Comment by jccastillo0007** [comment]
que significa la P ?
y no se como calcular las semanas entre dos fechas
chiaaa

**Comment by RigoFlores** [comment]
La P es como un prefijo, así lo pide el SAT. Su significado en concreto no lo sé.
Algo así como la T en la fecha-hora.
Si se te facilita calcular los días, es opción. O los meses.
Excel lo hace simplemente restando las fechas.
Supongo que hay que restar el timestamp, con base a los segundos transcurridos, ya se pueden calcular las semanas, que no???

**Comment by jccastillo0007** [comment]
Done.
