### ISSUE TITLE
Complemento de Nomina 1.2, desaparece CLABE aparece Cuenta bancaria

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#801]
Ya lo tenemos, pero ahora hay que validar de 10 a 18 posiciones.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
no está validando la longitud de 10 a 18.
Cuando la longitud sea de 18 posiciones, se trata de una CLABE... en ese caso, banco ya no aplica... es decir no se incluye en el XML. Quizás no desaparecerlo de pantalla, pero ignorarlo al momento de enviarlo al XML.

**Comment by jccastillo0007** [comment]
si es CLABE banco no aplica, pero no pasa nada si lo mandamos supongo.... tons, si lo informan se manda, como quiera no afecta.

**Comment by RigoFlores** [comment]
No sé si marcará error... las validaciones que ha impuesto el sat, supongo que son para algo... 
Todo lo levantado en issues está documentado por el SAT.

**Comment by jccastillo0007** [comment]
lo probamos cuando podamos timbrar, esos weyes de facture hoy ya no responden nada.... 

Como quiera el banco es opcional, asi que puedo o no ir.

**Comment by jccastillo0007** [comment]
Done.
