### ISSUE TITLE
Complemento Nomina 1.2, ajustar los campos de captura de Deducciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#803]
Desaparece Importe Gravado e Importe Exento, en su lugar solo queda Importe.
Con ello hay que ajustar la pantalla de captura, para integrar un solo campo para el importe de deducciones.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
pero el total de deducciones, ya lo eliminaste!!!....
ese si hace falta, para corroborar que los datos capturados sume correctamente

**Comment by jccastillo0007** [comment]
Pues en realidad quiero eliminar todos los subtotales, también el de percepciones, para que todos estén igual... hasta abajo esta el gran total y ahí se puede ver que todo este bien..

**Comment by RigoFlores** [comment]
Negativo, ayudan bastante. 
No es lo mismo ver la suma en corto de percepciones, deducciones, otros pagos, tiempo extra, etc... que solo ver un total sin saber PORQUE NO COINCIDE.
Eso ayuda a que el cliente se dé cuenta si su captura va bien o mal... y nos ayuda a estar revisando nosotros a ciegas porque no cuadran los totales.
Definitivamente los grupos de percepciones y deducciones, deben tener totales.
Y lo de siempre, PORQUE QUITARLE AL CLIENTE, ALGO QUE AHORA MISMO YA TIENE?

**Comment by jccastillo0007** [comment]
pues como no estaban en horas extras, incapacidades,etc... pues dije, igual y ayuda mas tener la pantalla mas limpia... luego los agrego de nuevo,, es mucha talacha

**Comment by RigoFlores** [comment]
Incluso para pruebas simplemente, es importante contar con esa info.
