### ISSUE TITLE
Complemento Nomina 1.2 - Implementar el nuevo esquema en el XML de salida

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#805]
Aunque no tengamos donde timbrar aún, hay que implementar el esquema y reflejarlo en un XML para ir revisando vs el xsd.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Favor de referirse al documento mapeoNomina1.2...
No está calculando correctamente el subtotal, ni el total.
Al nodo de percepciones le está faltando incluir atributos: TotalSueldos, TotalExento.
Para mayor referencia consulta el recibo 23 de nómina en pruebas, con la cuenta de la tia

**Comment by RigoFlores** [comment]
lo cierro, ya que abrí individual cada punto que está faltando
