### ISSUE TITLE
El keygenerator no asigna FOLIOS a llaves nuevas...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#806]
Ya reporté un caso, y tengo este otro...
ZAGP8412019K3
FSA680618RE3

**Comment by RigoFlores** [comment]
Como tengo que entregar, le hice una recarga a ZAGP8412019K3 por 50 folios, y se 'tragó' uno, es decir le asignó del 1 al 50, dejando solo 49 disponibles.
Lo corregiré en BD

**Comment by RigoFlores** [comment]
Ya lo corregí, pero el tema es:
1) no asigna folios cuando creas la llave por primera vez
2) al hacer la 'recarga' de folios por primera vez a esa llave recién generada, se traga un folio.

Todo esto desde el key generator.

**Comment by jccastillo0007** [comment]
Chiaaa que wey, le quite esa funcionalidad, pero ya esta listo... ahorita lo subo a PRO,,, también arregle el hecho de que la recarga lo inicia en 1, aunque ya no usarás esta opción como quiera ya esta arreglado.

**Comment by RigoFlores** [comment]
ok, ahora con la siguiente nueva llave, se validará la corrección.

**Comment by RigoFlores** [comment]
pues no, no asignó ni madres de folios... 
![nojalakiyeneraitor](https://cloud.githubusercontent.com/assets/2912775/21461746/2cdc52f6-c91a-11e6-8099-d0b28643c46f.PNG)
![nojalakiyeneraitor2](https://cloud.githubusercontent.com/assets/2912775/21461747/30523338-c91a-11e6-90cf-1263a52f2d9d.PNG)

**Comment by RigoFlores** [comment]
y se sigue tragando el folio... chiaaaaaa!!!!
![nojalakiyeneraitor3](https://cloud.githubusercontent.com/assets/2912775/21461771/6d5b87c0-c91a-11e6-8b57-8add647a8c6f.PNG)

**Comment by jccastillo0007** [comment]
Fixed... me parece que no habia subido bien la versión que lo resuelve, pero ya esta

**Comment by RigoFlores** [comment]
Ahora si creó el usuario nuevo, pero en pantalla muestra datos chuecos... 
Checa el header vs las recargas. Las recargas están bien, el header como que está recorrido o algo así...

![image](https://cloud.githubusercontent.com/assets/2912775/21911316/eb7f3964-d8e5-11e6-8d34-35b825c4c304.png)

en conclusión sigue algo chueco, al momento de crear una nueva licencia

**Comment by jccastillo0007** [comment]
si, ya lo vi... y sepa que chingados esta haciendo... debo revisarlo con calma... pero la recarga la hace bien, eso es lo bueno.

**Comment by jccastillo0007** [comment]
ya cerramos este issue? según yo ya no sucede.
