### ISSUE TITLE
Corregir los regímenes fiscales, ya que no muestra correctamente el acento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#807]
Pantalla de configuración en web, nuevo catálogo.

**Comment by jccastillo0007** [comment]
Fixed... al menos uno...

**Comment by RigoFlores** [comment]
Quedaron sin acentos, entonces supongo que el resto de los catálogos estarán en la mismas condiciones.
Hay que corregirlos también
