### ISSUE TITLE
Optibelt - Ventas - Consultas - no muestra el número de folio de la factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#808]
no muestra el número de folio correcto de la factura.
En el ID muestra correcto el ID que se toma de la addenda facturat.
Pero en el folio, muestra lo que sería el ID interno de facturat, en lugar del folio de la factura.

**Comment by jccastillo0007** [comment]
negativo... ese es el folio de la factura... los folios que muestra por ejemplo apartir del 1 de diciembre son, 161045309, 161045312.... etc, esos son los folios chiaaaaa
