### ISSUE TITLE
CxC - Cartera por Cliente - no muestra resultados con filtro de status o quitándolo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#809]
Con la cuenta de optibelt, todas estas pruebas de CxC... chiaaaaa

Cuando elijo una consulta por ejemplo RFC (AME00...) + fecha inicial (01 dic) ... me arroja resultados OK
Igual si es RFC + No Cliente + fecha... correcto OK

Si partiendo del escenario de arriba, le pongo un filtro de status, no arroja resultados (que si debería por ejemplo con vigentes).
Le quito el filtro y de todos modos ya no arroja resultados.

**Comment by jccastillo0007** [comment]
Fixed.
