### ISSUE TITLE
Mostrar de manera estandar las cantidades de precio unitario, importe, subtotal, total...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#81]
Precio unitario, se debe mostrar con 4 decimales al igual que cantidad.
Importe, subtotal, impuestos, descuento y total, debe mostrar solamente 2 decimales.

Ahora lo que pasa es que si el importe es 10.00, lo muestra como 10.0
Si el importe fuera 10.65, entonces si lo muestra como 10.65.

El formato de las cantidades debe ser estándar en todo momento.

**Comment by RigoFlores** [comment]
ME VOLVIÓ A MARCAR EL CLIENTE PREGUNTANDO EL AVANCE DE ESTE ISSUE.
(INCLUSO ME PIDIÓ EL NÚMERO DE CASO, INTERESANTE, QUE NO?)

**Comment by jccastillo0007** [comment]
dile que es el 69

lol

Saludos.
JC.

**Comment by jccastillo0007** [comment]
ya tengo el fix, con jquery.... a huevo.... solo necesito terminar lo de multirfc connector

**Comment by jccastillo0007** [comment]
Ya esta arreglado para el tema de ljasper.

**Comment by RigoFlores** [comment]
OK, lo dejaremos a nivel de jasper. Creo que es suficiente, y si solicitaran algo en pantalla, lo revisamos. Se cierra issue abierto hace año y medio... jeje
