### ISSUE TITLE
CxC - Cartera General

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#810]
Falta hacer el reporte tal cual se solicitó hace meses...
![totaltotal](https://cloud.githubusercontent.com/assets/2912775/20994500/6474f8b4-bcb6-11e6-837d-8e41f339bdc1.jpg)

**Comment by RigoFlores** [comment]
En este rerporte, solo incluye un renglón POR NÚMERO DE CLIENTE, y con un resumen de su saldo.
Igual al final se presenta un saldo total de todo lo que le deben.
El filtro debería ser por status... pero ahi no debe mostrar toooodas las facturas, sino solo un registro por cliente... debe hacer los cálculos internos...
Según yo, este reporte debe almacenarse y actualizarse en BD... ya que sería muy costoso hacerlo al vuelo.
Cuando se actualiza?... cuando se recibe una factura o cuando se ingresa un cobro.... que no???

**Comment by jccastillo0007** [comment]
Done.

Por el momento se genera al vuelo... ya que estoy seguro que el conocer los totales por cliente, van a tener dudas, y van a recurrir a un reporte detallado por cliente, vamos viendo la demanda que tiene este reporte...

**Comment by RigoFlores** [comment]
este reporte es ejecutivo
detallado por cliente es operativo.
Ambos se ocupan, y ambos se tienen ya listos... con la carga de facturas, lo que hay que ver, es cuánto se tarda en generarse, o lo peor que se vaya atascar el server...
