### ISSUE TITLE
KeyGenerator - Presentar las recargas por período de tiempo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#811]
Hoy muestras el historial del cliente por dafault en la pantalla de recargas.

Entonces quizás el botón de visto previo, podría servir para presentar las últimas recargas.. por rango de fecha, donde por default sea la fecha inicial = fecha final = today(), obvio con opción a cambiarlas.

**Comment by RigoFlores** [comment]
Este historial, es para conocer las recargas no de un solo cliente, sino todas las realizadas en un día o en un período de tiempo.

**Comment by jccastillo0007** [comment]
ok, got it, y es buena idea.

**Comment by RigoFlores** [comment]
Solo que están al revés, primero muestra las iniciales, es decir del 2011... lo cual obviamente no nos sierve para nada... lo que se tiene que mostrar son las últimas recargas realizadas

**Comment by jccastillo0007** [comment]
Fixed.
