### ISSUE TITLE
Complemento de Nomina 1.2 - eliminar el domicilio del empleado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#813]
son muchos datos ya.... hay que ir limpiando esa pantalla...

**Comment by jccastillo0007** [comment]
Estos datos también se eliminarán del nodo receptor del CFDi estándar

Done.

**Comment by RigoFlores** [comment]
A ver, no confundamos...
Una cosa es el nodo receptor del complemento de nómina y otra el nodo receptor del cfdi estándar.
En la version 3.3 del cfdi estándar, es probable que no se ocupe ya el domicilio, pero mientras eso sucede, no tiene porque ser un espejo uno de otro, ya que conceptualmente son cosas distintas.

**Comment by jccastillo0007** [comment]
son dos nodos diferentes, es correcto, pero si quitamos de pantalla los datos de la dirección del empleado, es decir del receptor, de donde tomaría la info para incluirla en el CFDi estándar ?

**Comment by jccastillo0007** [comment]
De hecho, si dejamos los datos en pantalla, se enviarían en el nodo receptor del CFDi estándar, ya que el complemento nómina ni siquiera los contempla, osea que hay que decidir, entre limpiar la pantalla o dejar los datos del domicilio para enviarlos en el CFDi estándar.

**Comment by RigoFlores** [comment]
A ver, aguanta...

**Comment by RigoFlores** [comment]
OK, limpiamos la pantalla.
Aún en la versión 3.2 el domicilio del receptor es opcional, y dado que no aparece en el PDF, entonces lo quitamos... no se mandará al CFDI estándar + Complemento Nómina.

OJO. CFDI estándar (facturas, notas de crédito, etc), si incluirán dicho nodo... solo nómina NO LO INCLUIRÁ.
