### ISSUE TITLE
Complemento Nomina 1.2 - No se están reportando a nivel del header los totales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#816]
Ya encontré los totales. Se deben reportar a nivel de header como atributos condicionales:
Total Percepciones: SUMA DE LAS PERCEPCIONES (sueldos + indemización + jubilación)
Total Deducciones: SUMA DE DEDUCCIONES (otras deducciones + impuestos retenidos)
Total Otros Pagos: SUMA DE OTROS PAGOS

**Comment by jccastillo0007** [comment]
Done.
