### ISSUE TITLE
Complemento de Nomina 1.2 - Reporta el CURP con personas morales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#817]
No debe reportar el curp en el nodo emisor, para personas morales.
Aplica solo para personas físicas.
Yo creo que tiene que ver desde la configuración. Si ahí es persona moral, el curp se pone a vacío, y si el curp es vacío no se reporta en nómina. Así lo veo, igual lo puedes resolver por otro lado.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
ahora aparece vacío... Curp=""
Entiendo que no se debe enviar siquiera en este caso

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
OK, ya no lo envía con personas morales... solo me falta validar que si lo exija y envíe con personas físicas..
