### ISSUE TITLE
Complemento Nomina 1.2 - Campo Sindicalizado, no se está reportando

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#818]
Este campo es opcional. Ahora mismo no aparece en pantalla.
Se deben desplegar 3 opciones: SI, NO, Vacío.
Con el vacío, se entiende que no se enviará dicho dato al XML

**Comment by jccastillo0007** [comment]
mmmmm dado que es opcional, dejémoslo así un tiempo, hasta que lo pidan... de hecho ningún patron le gusta tener gente sindicalizada por pinches grilleros.

**Comment by RigoFlores** [comment]
Si, de hecho no creo que tengamos clientes con gente de sindicato. Es casi un hecho.

Lo que si tenemos son muchos clientes con empleados que cobran por sueldos y salarios... y en ese sentido, **se debe reportar el campo SINDICALIZADO = NO**.
Cuando la clave de percepciones sea de asimilados, entonces no se reporta.

Si no queremos ponerlo en pantalla, entonces lo podemos enviar por omisión como NO, y solo en caso de tipoRegimen (del empleado)  del 05 al 11, dejar de enviarlo.

**Comment by jccastillo0007** [comment]
Done.
