### ISSUE TITLE
Se modifica el diseño de la plantilla (fonts, tamaño, distribución, diseño en gral), al generar el PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#82]
Seguimos con el problema de la interpretación de la plantilla.
De hecho el cliente me reportó el tema de espacios (en general distrubución de la información en la plantilla).
El tema es que yo en el están alon, lo veo bien, y tengo control de los espacios y distribución, pero cuando lo muestras en uev, ya se nota distinto.

No es algo que pueda corregir, ya que como quiera lo mueve el uev.
Que hacemos?
Según yo, habría que finiquitar el tema de los fonts.

**Comment by jccastillo0007** [comment]
Fixed by Rijo..... nice...

**Comment by RigoFlores** [comment]
La plantilla si la probé anteriormente, pero aún no la muestra como el dafault en pru; también debe darse de alta en pro como el default.
OJO, no alterar la plantilla actual de la donataria
