### ISSUE TITLE
Complemento Nomina 1.2 - No se está reportando el nodo separación indeminizacion

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#826]
Y todos sus datos

**Comment by jccastillo0007** [comment]
Done.

**Comment by jccastillo0007** [comment]
Oye aqui es el mismo caso de las horas extras ? es decir, se contabilizan como una percepción tal cual, y luego las van a volver a capturar en el nodo de indemnizaciones, pero ahi ya no se vuelven a sumar, solo se reportan cierto ?
I hope so...
