### ISSUE TITLE
Complemento Nomina 1.2 - Otros Pagos - falta un dato cuando se trata de subsidio al empleo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#828]
Cuando la clave de otro pago sea 002 (que es muy común), SE DEBE capturar un dato que se llama SubsidioCausado.
Pienso que siempre debe aparecer, y que se capture cuando se trate del 002.
En caso que no se capture nada, no se enviará al XML.
Si se captura, solo se enviará cuando la clave sea 002.

**Comment by jccastillo0007** [comment]
Ok, agrego ese campo, pero según yo la otra opción Compensación saldo a favor, ocupa un layout diferente también.

**Comment by RigoFlores** [comment]
Afirmativo, pero si ves el excel, es de los que dejaremos pendientes... en pantalla...
Por conector, si lo estaré definiendo... correcto, o no?

**Comment by jccastillo0007** [comment]
done.
