### ISSUE TITLE
Agregar cotización, pedido y remisión (prácticamente lo mismo que un factura)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#83]
Un registro de factura, debe incluir su folio correspondiente de cotización, pedido, remisión y factura. 
Básicamente la información es la misma, solo que se agrega un folio por cada estado y la fecha correspondiente.
Hay que implementar el flujo, y agregar los campos de folio_cotizacion, fecha_cotización, etc., junto con un estado, que indicará ese registro a que corresponde en ese momento, si a una cotización, pedido, remisión o factura.
Cotización->Pedido->Remisión->Factura.

De la derecha a la izquierda, puede nacer el documento en cualquier momento,

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
duplicado, se cierra
