### ISSUE TITLE
CFDI Estandar + Nomina - tipo de cambio = 1

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#831]
Actualmente se reporta como 1.00

No sé si esto marque error, pero si se puede dejar a como lo piden "1", que mejor.

**Comment by jccastillo0007** [comment]
fixed.
El proceso de la nómina ya lo envía como 1, pero la generación estándar de CFDi lo formatea a 1.00, si se puede cambiar pero sería para toooodos los CFDis, yo digo que veamos is pasa la validación así.
