### ISSUE TITLE
CFDI Estándar+Nómina - No se debe reportar el atributo NumCtaPago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#833]
Siempre te has confundido con la cuenta que se captura en los datos de la nómina.
Esa cuenta va en el nodo receptor del complemento, pero no a nivel estándar.

A nivel estándar, no aplica este atributo.

**Comment by jccastillo0007** [comment]
ok, creo que ya esta. jajajaja
