### ISSUE TITLE
CxC- Cartera General - Varios

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#836]
Cambiar el nombre del reporte a "Cartera General"
Agregar el total al final el Total Saldos= Sumatoria de Saldos Totales
El Total Saldo se calcula como Total Cargos - Total Abonos (se está calculando al contrario)

**Comment by jccastillo0007** [comment]
Done

**Comment by RigoFlores** [comment]
Todo esto aplica a nivel de pantalla. Igual a nivel de excel, pero se levantó por la pantalla no por el excel.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
El total en pantalla, está mal calculado

**Comment by jccastillo0007** [comment]
orale... quien sabe de donde saca ese valor
