### ISSUE TITLE
CxC - Cartera General - Reporte

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#837]
El reporte en excel, no refleja el mismo contenido de la pantalla.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Ya solo falta invertir las 2 primeras columnas, ya que primero va el número de cliente (que a su vez es el criterio de ordenamiento) y luego va el nombre del cliente.
Adicionalmente, el saldo total se puede colocar debajo de la columna de saldo?

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
**El saldo en pantalla es incorrecto.**
El saldo en excel es correcto.

Es posible que en el excel muestre al final del reporte,  solo la cantidad, en la columna total saldo, y en la columna de la izquierda la leyenda "Total Saldos : "

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Negativo, marca internal error al generar el reporte en excel y pdf

**Comment by jccastillo0007** [comment]
ya se esta generando, en el pdf los datos que falta llenar, no se que es lo que llevan o no se como calcularlos, sobre todo los saldos anteriores

**Comment by RigoFlores** [comment]
Saldo anterior, a nivel de cliente... quedamos en eliminarlo.. de hecho no aparece en la plantilla.
Saldo total, es a nivel de cliente... y es Total Cargo - Total Abono
Totales... es la sumatoria de los Saldo Total (de cada cliente)
