### ISSUE TITLE
CxC - Cartera Por cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#838]
En el reporte de excel se incluye el rfc en lugar del nombre del cliente

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
al parecer el reporte ya está chueco.
Creo que está generando el reporte general en excel, en lugar del reporte por cliente.
Cuando el reporte contenta el filtro de todos (no eligieron ningún cliente), en nombre de cliente debe enviar "TODOS"

**Comment by RigoFlores** [comment]
Cuando el nombre del cliente incluye ',' (comas), favor de eliminarlas y colocar un espacio.
Igualmente dentro del excel, el total debe aparecer debajo de la columna correspondiente, y la leyenda en la celda de la izquierda.

**Comment by jccastillo0007** [comment]
Fixed.
