### ISSUE TITLE
CxC - Generar reporte en PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#839]
Ya envié la plantilla...
Supongo que se deberá colocar en la misma carpeta de setup de cada cliente, correcto?

**Comment by jccastillo0007** [comment]
Si es una plantilla genérica para este reporte, puede estar en donde están las genéricas y no customizadas

**Comment by jccastillo0007** [comment]
Listo.

Preguntas.
Que va en Saldo Anterior y  Saldo Total del encabezado.
El saldo total me imagino es el saldo restante después de todos los movimientos, pero el saldo anterior no lo se.

**Comment by RigoFlores** [comment]
Saldo total, efectivamente es el total después de todos los movimientos.
Saldo anterior puede ser muy complicado o muy simple.
a) Muy complicado: todos los clientes inician con 0 en su saldo cuando 'nacen', y a partir de ahí su saldo se va moviendo... mientras tengan adeudo, será mayor a cero. El saldo anterior, es el saldo antes de la primera factura presentada en el reporte, dependiendo del filtro elegido.
b) Todos los ejemplos vienen con cero, podemos iniciar por omisión con cero, pero no sé si eso rebote en algún momento
