### ISSUE TITLE
Agregar usuario al reporte excel generado desde la consulta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#84]

**Comment by jccastillo0007** [comment]
ETA this weekend.

**Comment by RigoFlores** [comment]
No entendí, pero lo que se ocupa es agregar el usuario que generó cada factura en el reporte.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
no puede terminar de probar, porque no me permite agregar productos en la pantalla de facturación. Si abre la pantalla de productos, pero no permite agregar... dice que si deseo salir de esa pantalla o algo así....
El usuario está duplicado en el reporte de excel...

**Comment by RigoFlores** [comment]
También en nómina está duplicado el usuario...

**Comment by jccastillo0007** [comment]
chiaaaaa esto ya estaba implementado.

**Comment by RigoFlores** [comment]
Si ves el historial, nunca se reportó como implmentado...
