### ISSUE TITLE
Complemento Nomina 1.2 - Revisar el cálculo de la antigüedad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#842]
Estrictamente hablando esto dice el SAT:
Si el valor de este atributo cumple con el patrón P[1-9][0-9]{0,3}W, entonces el valor numérico del atributo debe ser menor o igual al cociente de (la suma del número de días transcurridos entre la FechaInicioRelLaboral y la FechaFinalPago más uno) dividido entre siete;

Entiendo que si nos fuimos por el formato de W (semanas), debemos cumplir con lo que dice ahí.
Ahora existe el formato de Y, M, etc... pero es complicar mas el cálculo. Yo creo que semanas es lo mas llevadero....

**Comment by RigoFlores** [comment]
En el caso del ejemplo tenemos inicio relación: 01 dic, fecha final de pago: 32 dic.
Con ello los días transcurridos son 30 + 1 = 31 / 7 = 4.42... entonces se toma solo el entero, en este caso 4.
Quedamos que tu lo harías por diferencia de timestamp entre las 2 fechas, pero tu cálculo da 5. Será que estás redondeando hacia arriba, en cuyo caso no debería ser así.
El timestamp de una fecha, que hora considera del día?

**Comment by RigoFlores** [comment]
Según lo que dijimos, tomar solo la parte entera (que es lo mas adecuado) o restarle 1 al cálculo (es lo chacarrón)

**Comment by jccastillo0007** [comment]
Listo, y también lo puse como solo lectura.

**Comment by RigoFlores** [comment]
Vientos!!
