### ISSUE TITLE
Complemento Nomina 1.2  - Validaciones de Numero de Cuenta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#843]
El valor de este atributo debe tener una longitud de 10, 11, 16 ó 18 posiciones.
Si el valor de este atributo contiene una cuenta CLABE (número con 18 posiciones), no debe existir el atributo Banco.

(con voz de tenor..."te lo dijeeeee!!!")...
cuando sean 18 posiciones, NO DEBE ENVIAR LA CLAVE DEL BANCO... tu dices que como quiera, pero ya ves que no es así, están aplicando validaciones estrictas...

**Comment by jccastillo0007** [comment]
Chiaaaa, done.

**Comment by RigoFlores** [comment]
Si le capturo 18 posiciones, es decir cuenta CLABE, marca lo siguiente:

NOM184 - El dígito de control del atributo Nomina:Receptor:CuentaBancaria es incorrecto (3)

lo cual casi me asegura, que mandas el banco en este caso, y que no debería ser... recuerdo que dijiste, 'lo mando, como quiera no afecta'... jajaja

**Comment by jccastillo0007** [comment]
pues tu cuasiaseguración es incorrecta, reproduje el escenario y no se manda el banco, seguramente la clabe debe seguir algún formato que ellos conocen, 

hay otro problema, que es la convertir la cuenta a biginteger, se pierden los 0 a la izq.

**Comment by jccastillo0007** [comment]
Listo... se agrego la siguiente validación.
Si el número de cuenta es de 18 posiciones, no se manda banco, pero si empieza con 0, tampoco se manda la cuenta.
Si el número de cuenta es < 18 posiciones, si se manda banco, pero, si el número de cuenta empieza con 0, no se manda nada.

Esto es al momento de generar la nómina, no cuando salvas la info.
