### ISSUE TITLE
Complemento Nomina 1.2 - Validacion de curp

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#844]
Si bien no se valida la estructura, que sería complicado (supongo), el mensaje de error debe indicar al menos que debe ser de 18 posiciones el CURP.
capturé un curp de 19 posiciones, y solo indica "CURP Inváido", cambiarlo por "La longitud del CURP debe ser de 18 caracteres"

**Comment by jccastillo0007** [comment]
Done.
