### ISSUE TITLE
Complemento Nomina 1.2 - Indicar campos obligatorios con un *, y con ** los condicionales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#846]
Indicar en la pantalla 3 condiciones básicas de los campos a capturar:

**(*) Obligatorios
(**) Condicional, no aplica para asimilados a salarios
(***) Si se paga con transferencia, cheque o depósito.**

* Tipo Nómina 
* Fecha de Pago
* Fecha inicial de Pago
* Fecha final de Pago
* Número de Días pagados
  **  Registro Patronal 
* CURP
  **  No. IMSS
  **  Fecha Inicio Relacion Laboral
* Tipo de Contrato
  ** Tipo de Jornada
* Régimen
* Número de Empleado
* Periodicidad de Pago
   *** Banco
   *** Cuenta Bancaria
  **  Salario Base
  **  Salario Diario Integrado
* Entidad Federativa

**Comment by RigoFlores** [comment]
Y si reorganizamos la captura de este manera los campos en la pantalla de captura?


* Obligatorios
* Tipo Nómina
* Fecha de Pago
* Fecha inicial de Pago
* Fecha final de Pago
* Número de Días pagados
* Tipo de Contrato
* Régimen
* Número de Empleado
* Periodicidad de Pago
* CURP     FIAA650525HMSGLL04
* Entidad Federativa

***  Condicional, no aplica para asimilados a salarios
** No. IMSS
** Fecha Inicio Relacion Laboral
** Registro Patronal
** Tipo de Jornada
** Salario Base
** Salario Diario Integrado


*** Si se paga con transferencia, cheque o depósito.

*** Banco
*** Cuenta Bancaria


OPCIONALES:

Puesto
Departamento
Riesgo
Email

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
No lo puse a propósito, pero si se va a mostrar la antigüedad, es en campos condicionales.
Además poner campos condicionales (NO APLICAN PARA ASIMILADOS A SALARIOS).

Es muy importante esa etiqueta

**Comment by RigoFlores** [comment]
Además de la etiqueta, al haber agrupado... ya no son necesarios los ** en cada campo, ni al final de la pantalla

**Comment by jccastillo0007** [comment]
Done.
