### ISSUE TITLE
Complemento Nomina 1.2 - validar la longitud del RFC a 13 posiciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#847]
No puede ser a 12, ya que correspondería a persona moral.
Debe ser a 13 posiciones.
Cualquier caso de error, indicar:

"Capturar RFC a 13 posiciones, sin espacios ni guiones"

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
negativo, me permitió guardarlo con 14 de longitud. Lo puedes checar en la BD... aceptó 14

**Comment by jccastillo0007** [comment]
es que lo estaba validando al momento de facturar... deja lo pongo al momento de salvar
.
.
.
Listo
