### ISSUE TITLE
Complemento Nomina 1.2 - Pide obligatorio la cuenta

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#848]
La cuenta es un campo opcional, ya que algunas veces se paga en efectivo (cada vez menos), pero todavía.
Entonces si no la capturo, me lo pide a huevo.
El banco debería ser opcional en teoría.

En conclusión, no me permite dejar en blanco la cuenta. Luego la capturo, y me pide el banco.
En teoría son opcionales, pero hay que validar eso.

El issue, es que no me lo exija, y probamos si pasa el timbrado

**Comment by jccastillo0007** [comment]
conste que banco y cuenta son opcionales.
listo

**Comment by RigoFlores** [comment]
Son condicionales, de acuerdo a la spec. 
Anteriormente también era opcional el banco, y te lo pedía facturehoy, lo cual era un error, pero tenían que capturarlo a wilson

**Comment by RigoFlores** [comment]
Al momento de guardar, ya me permite dejar en blanco la cuenta y el banco, pero ya cuando timbras, te pide el banco... chiaaaaaa...
Recordar que esto es de acuerdo a spec del sat, y quizás haya que darle patrás, si no cumple.

**Comment by jccastillo0007** [comment]
Listo... sin embargo, no pude resolver el tema de que al crear el big integer , le borre los 0 a la izquierda, esto sucede mas que nada con la CLABE, luego entonces, dado que la cuenta siempre es opcional, si la cuenta empieza con 0 (a la izquierda obviamente) no la voy a enviar.

**Comment by RigoFlores** [comment]
Estamos al revés, la cuenta si es CLABE (18 de longitud), entonces no se debe enviar el BANCO. Esa es la regla.
Cuando la cuenta sea de 10, 11, 15 o 16 posiciones, entonces el banco es a wilson.
OK, si capturan 18 y el primero es 0.... y si dices que por tipo de dato, no se puede... podríamos llenarla con 1 al inicio, en lo que se corrige esa definición???

**Comment by jccastillo0007** [comment]
si la regla esta bien definida, a lo que voy es que si la cuenta empieza con 0 no enviaré nada.
no podemos alterar la CLABE con un 1, porque el pac esta validando el número, lleva un patrón, de ahi el error que te manda del digito verificador.

**Comment by RigoFlores** [comment]
ok, pero entonces no se envía el banco, ya que te pedirá la cuenta a oevo

**Comment by jccastillo0007** [comment]
asi es como queda.
Si el cliente capturó una cuenta y si esa cuenta no empieza con 0, entonces si se manda la cuenta

Cuando si se manda la cuenta, y dicha cuenta es de 18 dígitos, no se manda el banco, en otro caso si se manda banco.
