### ISSUE TITLE
Nomina 1.2 - Marca error descuento porque no es igual a total deducciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#849]
No sé si el ejemplo anterior es fijo, pero dí de alta un empleado nuevo.
Percepciones 2000 (una sola)
Deducciones 1  (uno solo).

Y cuando mando timbrar pasa esto:

NOM107 - El valor de descuento no es igual a Nomina12:TotalDeducciones (3)

**Comment by jccastillo0007** [comment]
Fixed.
