### ISSUE TITLE
Agregar al KeyGenerator la opción para activar nómina con un click

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#851]
Tenemos que validar que: 
(1) se pueden inhibir todas las nóminas (previo respaldo de lo actual, para regresar por cualquier caso), y 

(2) que se pueden ir activando las nóminas por cada rfc desde el keygenerator

**Comment by jccastillo0007** [comment]
done

**Comment by jccastillo0007** [comment]
Ya tengo la forma de deshabilitar a todos los usuarios del menú de nómina, es por medio de privilegios.
La forma de habilitarlos, es agregarles el privilegio de nómina en la base de gatos.
Solo me falta ponerle ese checkbox en el key generator.
Ma;ana lo termino y lo subo justo cuando subamos la versión a PRO.

**Comment by jccastillo0007** [comment]
Done...
Si el cliente a actualizar ya tiene seleccionada la opción de complemento de nómina, aún en ese caso, hay que darle editar y salvar para que le active la nómina como privilegio.

**Comment by RigoFlores** [comment]
OK, veo que los 2 clientes que habilitaste no tienen chequeado el complemento de nómina.
Entonces ese check box, no refleja la BD?

**Comment by jccastillo0007** [comment]
lo que pasa es que el famoso tema de los plugins, ya esta obsoleto, ahora son privilegios, y el key generator esta mostrando los plugins... debo actualizar eso
