### ISSUE TITLE
NO JALA EL KEY GENERATOR NI PARA FOLIOS, NI PARA LLAVES

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#852]
EN PRODUCCIÓN, NO SE QUE LE HICISTE ORA...

**Comment by jccastillo0007** [comment]
Dada la ambiguedad (con dieresis) del issue, no se cual era el error, si te refieres a que marcaba un internal error al entrar  a la opción de recarga de folios, se debió a que de alguna forma creaste el cliente con rfc : "KBE070820CZ6" y nombre : "pendiente" y se creo con saldo, dias de crédito y monto de crédito = null, lo cual es una exception.

Dime como creaste ese usuario, para corregir el código, si es que lo creaste por la aplicación... 

Fixed.

**Comment by RigoFlores** [comment]
Chiaaaa...  pues ayer te lo comenté.
1) Primero hice un acceso en el descargat, que nunca jaló.
2) Luego para probar, agregué ese cliente en el catálogo de clientes de figueacero.

De ahí en adelante, no sé como un cliente de nuestro cliente, se pasó al keygenerator

**Comment by jccastillo0007** [comment]
Ya jala el key generator, falta ver el misterio de l oque pasó con ese cliente.

**Comment by RigoFlores** [comment]
si, ese cliente (de nuestro cliente figueacero) como comenté... lo dí de alta en el DescargaT...
Hay que echarle un vistazo, porque debemos asegurar que vean sus facturas
