### ISSUE TITLE
Complemento Nomina 1.2 - Actualizar catálogo de deducciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#853]
Que ahora son estas adicionales a las que ya estaban. Son cambios que va comunicando el SAT... chiaaa

024	Ajuste en Gratificación Anual (Aguinaldo) Exento
025	Ajuste en Gratificación Anual (Aguinaldo) Gravado
026	Ajuste en Participación de los Trabajadores en las Utilidades PTU Exento
027	Ajuste en Participación de los Trabajadores en las Utilidades PTU Gravado
028	Ajuste en Reembolso de Gastos Médicos Dentales y Hospitalarios Exento
029	Ajuste en Fondo de ahorro Exento
030	Ajuste en Caja de ahorro Exento
031	Ajuste en Contribuciones a Cargo del Trabajador Pagadas por el Patrón Exento
032	Ajuste en Premios por puntualidad Gravado
033	Ajuste en Prima de Seguro de vida Exento
034	Ajuste en Seguro de Gastos Médicos Mayores Exento
035	Ajuste en Cuotas Sindicales Pagadas por el Patrón Exento
036	Ajuste en Subsidios por incapacidad Exento
037	Ajuste en Becas para trabajadores y/o hijos Exento
038	Ajuste en Horas extra Exento
039	Ajuste en Horas extra Gravado
040	Ajuste en Prima dominical Exento
041	Ajuste en Prima dominical Gravado
042	Ajuste en Prima vacacional Exento
043	Ajuste en Prima vacacional Gravado
044	Ajuste en Prima por antigüedad Exento
045	Ajuste en Prima por antigüedad Gravado
046	Ajuste en Pagos por separación Exento
047	Ajuste en Pagos por separación Gravado
048	Ajuste en Seguro de retiro Exento
049	Ajuste en Indemnizaciones Exento
050	Ajuste en Indemnizaciones Gravado
051	Ajuste en Reembolso por funeral Exento
052	Ajuste en Cuotas de seguridad social pagadas por el patrón Exento
053	Ajuste en Comisiones Gravado
054	Ajuste en Vales de despensa Exento
055	Ajuste en Vales de restaurante Exento
056	Ajuste en Vales de gasolina Exento
057	Ajuste en Vales de ropa Exento
058	Ajuste en Ayuda para renta Exento
059	Ajuste en Ayuda para artículos escolares Exento
060	Ajuste en Ayuda para anteojos Exento
061	Ajuste en Ayuda para transporte Exento
062	Ajuste en Ayuda para gastos de funeral Exento
063	Ajuste en Otros ingresos por salarios Exento
064	Ajuste en Otros ingresos por salarios Gravado
065	Ajuste en Jubilaciones, pensiones o haberes de retiro Exento
066	Ajuste en Jubilaciones, pensiones o haberes de retiro Gravado
067	Ajuste en Pagos por separación Acumulable
068	Ajuste en Pagos por separación No acumulable
069	Ajuste en Jubilaciones, pensiones o haberes de retiro Acumulable
070	Ajuste en Jubilaciones, pensiones o haberes de retiro No acumulable
071	Ajuste en Subsidio para el empleo (efectivamente entregado al trabajador)
072	Ajuste en Ingresos en acciones o títulos valor que representan bienes Exento
073	Ajuste en Ingresos en acciones o títulos valor que representan bienes Gravado
074	Ajuste en Alimentación Exento
075	Ajuste en Alimentación Gravado
076	Ajuste en Habitación Exento
077	Ajuste en Habitación Gravado
078	Ajuste en Premios por asistencia
079	Ajuste en Pagos distintos a los listados y que no deben considerarse como ingreso por sueldos, salarios o ingresos asimilados.
080	Ajuste en Viáticos no comprobados
081	Ajuste en Viáticos anticipados
082	Ajuste en Fondo de ahorro Gravado
083	Ajuste en Caja de ahorro Gravado
084	Ajuste en Prima de Seguro de vida Gravado
085	Ajuste en Seguro de Gastos Médicos Mayores Gravado
086	Ajuste en Subsidios por incapacidad Gravado
087	Ajuste en Becas para trabajadores y/o hijos Gravado
088	Ajuste en Seguro de retiro Gravado
089	Ajuste en Vales de despensa Gravado
090	Ajuste en Vales de restaurante Gravado
091	Ajuste en Vales de gasolina Gravado
092	Ajuste en Vales de ropa Gravado
093	Ajuste en Ayuda para renta Gravado
094	Ajuste en Ayuda para artículos escolares Gravado
095	Ajuste en Ayuda para anteojos Gravado
096	Ajuste en Ayuda para transporte Gravado
097	Ajuste en Ayuda para gastos de funeral Gravado
098	Ajuste a ingresos asimilados a salarios gravados
099	Ajuste a ingresos por sueldos y salarios gravados

**Comment by jccastillo0007** [comment]
done
