### ISSUE TITLE
Complemento Nomina 1.2 - Empatar validaciones de tipo contrato, con régimen

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#854]
Si el tipo de contrato va del 01 al 08, entonces el régimen únicamente puede ser 02, 03 o 04 (es decir sueldos, jubilados o pensionados).

Si el tipo de contrato es 09 o mayor, entonces el régimen debe ser 05 o mayor.

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
![image](https://cloud.githubusercontent.com/assets/2912775/21754741/0725c984-d5cc-11e6-915b-88bebdf9ff0e.png)

**Comment by RigoFlores** [comment]
Aquí guardó sueldos y salarios, cuando el tipo de contrato era otros.
Sueldos y Salarios, Jubilados y Pensionados... solo deben empatar con tipo de contrato del 01 al 08.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
ESTAS SON LAS VALIDACIONES QUE AL PARECER NO ESTÁN JALANDO PARA EL CONECTOR.
TU DICES QUE ES OTRA COSA, PERO AL MENOS PARECE QUE ESTO NO ESTÁ JALANDO.
