### ISSUE TITLE
Complemento Nomina 1.2 - Si el régimen es sueldos y salarios, solicitar los campos condicionles

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#855]
Cuando el régimen sea sueldos y salarios, solicitar como requeridos los campos condicionales.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
![image](https://cloud.githubusercontent.com/assets/2912775/21754727/a9fd36d4-d5cb-11e6-86bf-2605b7cc16d9.png)

**Comment by RigoFlores** [comment]
aquí me permitió almacenar sin haber capturado el registro patronal.
Como lo hice fue que elegí, sueldos y salarios, y la daba guardar.
Me fue pidiendo uno por uno los campos. Riesgo patronal se lo brincó de alguna manera y permitió almacenar. Banco y cuenta, está OK que no los pida obligatorios.

**Comment by RigoFlores** [comment]
en esta otra pantalla, sucede al contrario... si tiene registro patronal... pero marca que no se tiene capturado y no permite guardar... lo que hice, fue solo modificar el número de cuenta para hacer una prueba, pero todo ya estaba capturado. De hecho, el empleado no lo pude modificar... puedes reproducir el escenario, si es necesario ya que no hice ningún cambio...
![image](https://cloud.githubusercontent.com/assets/2912775/21755389/a62cee8e-d5d8-11e6-8bed-118ffbe24df7.png)

**Comment by jccastillo0007** [comment]
si, es que había una doble negación....
Fixed.
