### ISSUE TITLE
Complemento Nomina 1.2 - No acepta la entidad federativa querétaro

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#857]
No sé si está mal nuestro catálogo o el del PAC, pero no acepta Querétaro... y aquí tenemos varias nómina...:(

**Comment by jccastillo0007** [comment]
Es el del PAC, la clave es QUE, y es lo que mandamos.

**Comment by RigoFlores** [comment]
ok, entonces pls envíales un correo indicando la situación para que corrijan...
