### ISSUE TITLE
Pantalla Nomina 1.2 - no calcula correctamente la suma de percepciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#859]
Lo que te mostré en pantalla, que no se de donde sacaba 1500.
El antecedente es que originalmente tenia una percepción de 1500.
luego le agregué aguinaldo 1500, después de ello le deshabilité la percepción original. Ahí fue donde mantuvo 3000, en lugar de 1500. A partir de ahí, se quedó con ese overhead de 1500

**Comment by RigoFlores** [comment]
El cliente IRT070328PK1, comentó que sucede lo mismo con las deducciones.
Por un lado no muestra el total, para poder ajustarlo a manopla, y por otro, no sé de donde está tomando cantidades que arrojan cálculos incorrectos.
Las percepciones se corrigen manualmente, las deducciones por decreto, no es posible ya que desapareció el total que antes se mostraba...

**Comment by jccastillo0007** [comment]
ya validé el tema de deducciones , el pedo estaba en que anteriormente teníamos importe gravado e importe exento, hoy en día solo es importe... pero para los empleados que anteriormente ya estaban configurados, tenian ambas cantidades capturadas, y el importe total contabilizaba tanto importe gravado como exento...

**Comment by RigoFlores** [comment]
pero se aplicó lo mismo para las percepciones o porque ahí también lo duplicaba? porque ahí si se mantuvo lo de gravado y exento...

**Comment by RigoFlores** [comment]
le cambiaré de question a falla... te mandé un correo respecto a este issue...

**Comment by jccastillo0007** [comment]
este problema es de sincronización de datos cuando habilitas o deshabilitas una percepción, y es un problema que pudo haberse dado incluso desde la versión anterior.

cambié la estrategia de calculo de totales, para tratar de evitar esa desincronización, voy a subirlo a producción y probar...

Ojo... si ves un empleado que tiene ese problema, lo que debes hacer para corregirlo, es habilitar y deshabilitar alguna de las percepciones, y en ese momento va a recalcular los totales.
