### ISSUE TITLE
Habilitar el ambiente de produccion con el puerto seguro de tomcat.

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#86]

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Necesitamos conocer la especificación del certificado a adquirir. Revisamos y existen varios precios, varias características. Unos muuuy caros, otros muuuy baratos... tons no sabemos cuál es el bueno, y que nos deberían entregar y como?

**Comment by jccastillo0007** [comment]
mandame la liga para ver las opciones

jc

Saludos.
JC.

**Comment by jccastillo0007** [comment]
Este defecto ya esta corregido... solo queda pendiente el tema del certificado...

Que por cierto, si se puede usar el de la TIA, como ves? de hecho un certificado del SAT para la TIA que ofrece servicios de FE en el portal eFacturaT.... creo que si aplica.

**Comment by RigoFlores** [comment]
Realmente la corrección, será cuando utilicemos un certificado que no indique que la url es de alto riesgo; eso nos deja muy mal parados con el cliente y su confianza.
Solo tenemos que definir cuál es el certificado adecuado, para adquirirlo y ponerlo en el sitio.
Una vez realizado lo anterior, cerraremos esta ficha. 
Hoy digamos que está implementada, pero no al 100% por el mensaje que le entregamos a nuestros clientes.
