### ISSUE TITLE
Con subsidio al empleo (otros pagos), marca error... 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#860]
al parecer con cualquier otro elemento de la lista también...

FH22 - cvc-pattern-valid: Value 'Subsidio para el empleo.' is not facet-valid with respect to pattern '([A-Z]|[a-z]|[0-9]| |Ñ|ñ|!|"|%|&|'|´|-|:|;|>|=|<|@|_|,|\{|\}|`|~|á|é|í|ó|ú|Á|É|Í|Ó|Ú|ü|Ü){1,100}' for type '#AnonType_ConceptoOtroPagoOtrosPagosNomina'. cvc-attribute.3: The value 'Subsidio para el empleo.' of attribute 'Concepto' on element 'nomina12:OtroPago' is not valid with respect to its type, 'null'. (3

**Comment by jccastillo0007** [comment]
mmmm como asi.... es el tema de los paréntesis cierto ?

Lo subiste para documentarlo, o encontraste otro patrón de error

**Comment by jccastillo0007** [comment]
chiaaaa , era un puto punto.

**Comment by RigoFlores** [comment]
Porque razón un punto también le pega?
Quizás el () mas o menos se justifica, pero el punto?
Muchos campos podrían llevar punto.... o solo es con un punto al final?

**Comment by jccastillo0007** [comment]
porque es el formato definido en el schema, y definieron que no se soportan ni () ni . 
la definición del formato es lo que aparece en el mensaje de error... es un chorizote, asi que sientate para analizarlo
