### ISSUE TITLE
No jala el DescargaT para Figueacero

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#861]
Sigo sin  poder ver nada con este RFC KBE070820CZ6, que además cuando lo dí de alta, no se porque se fue a la BD del keygenerator y tronaba la aplicación.

**Comment by jccastillo0007** [comment]
fixed.
Si era lo que mencioné, la versión que estaba en PRO era un poco vieja... ya la actualicé y ya esta jalando.

**Comment by RigoFlores** [comment]
Voy a probar creando una nueva cuenta para el receptor (cliente de Figueacero) en descargaT.
Lo haré por la tarde, por si le pega nuevamente al keygenerator.
