### ISSUE TITLE
Complemento Nómina 1.2 - Percepciones invierte clave y tipo de percepcion

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#862]
La clave es la que sugerimos.
El tipo es del catálogo del SAT.

Si nuestra sugerencia la cambia el cliente, truena, ya que inverte estos dato, y ya no coincide con el catálogo del SAT.

**Comment by jccastillo0007** [comment]
fixed... ups, siempre mandaba la clave .
