### ISSUE TITLE
Complemento Nomina 1.2 - Número de IMSS, indicar que no lleva espacios ni guiones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#863]
Anteriormente si aceptaba guiones, ahora ya no.

Lo mas simple sería con una leyenda indicar que no acepta espacios ni guiones.
La mas complicada sería validar al momento de guardar el registro, pero creo que es overhead innecesario.
La mas elegante, es el tooltip, pero creo que no todos le harían caso, ya que forzosamente tendrían que pasar el maus encima.

Conclusión, la mas simple nos ayuda un chingo, ya que evita un error en el timbrado..

**Comment by jccastillo0007** [comment]
done.
