### ISSUE TITLE
Complemento Nomina 1.2 - Total de Percepciones incorrecto en excel y PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#866]
En la vista previa de Nómina Empresarial, NO ESTÁ CONSIDERANDO EL SUBSIDIO AL EMPLEO en los cálculos de percepciones, y por lo tanto de totales. (incluso debe considerar indeminización).

Para el caso del recibo de Nómina en PDF, FAVOR DE CONSIDERAR PERCEPCIONES, INDEMINIZACIÓN, Y SUBSIDIO AL EMPLEO, como parte de las percepciones que se envían al Jasper, ya que en otro caso tendríamos que poner variables específicas por estos rubros.

**Comment by jccastillo0007** [comment]
si, ok, no he modificado nada de nomina empresarial...

modifico lo de percepciones para el jasper.

**Comment by jccastillo0007** [comment]
te refieres a las variables que van como  totalImporteGravadoPercepcion y  totalImporteExentoPercepcion ?

**Comment by jccastillo0007** [comment]
pues ya le agregué lo necesario tanto el excel de nómina gral como el jasper de nómina individual, checale y me dices.

**Comment by RigoFlores** [comment]
En producción sigue igual...

**Comment by RigoFlores** [comment]
En pru, para propósitos del PDF, NO MUESTRA EL SUBSIDIO AL EMPLEO EN LA SECCIÓN DE PERCEPCIONES... ya se que no es percepción, sino otros pagos... pero la petición es juntar (mostrar) percepciones, indeminización y otros pagos, en el PDF como percepciones todas.

**Comment by RigoFlores** [comment]
En pru, en nómina empresarial ya muestra los cálculos correctos... tons queda pendiente lo del PDF

**Comment by RigoFlores** [comment]
Este requisito lo comprometí sin falta para mañana... lo de enviar al PDF el subsidio como parte de las percepciones..

**Comment by jccastillo0007** [comment]
osea que indemnizacion y otros pagos te los mando como percepciones .... orale, le llevamos la contra al sat.... luego van a brincar.

**Comment by RigoFlores** [comment]
puede ser, pero para el empleado, la neta es que le interesa cuánto recibe y de que...
si es subsidio o no, eso le vale madres... y por otro lado lo estamos mostrando... tons, simplemente no estamos clasificando como el SAT para propósitos del PDF, obvio en el XML cumplimos full...

**Comment by jccastillo0007** [comment]
ya se lo puse ... haber que ta... esta en pru y pro
