### ISSUE TITLE
Complemento Nomina 1.2 - Enviar al PDF descripción de tipo de Nómina

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#867]
En lugar de la clave, ya que hoy aparece O, en lugar de Ordinaria

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
negativo, ni en pro, ni en pru... hasta que subas algún cambio, reportarlo como fijo pls

**Comment by jccastillo0007** [comment]
fixed., si estaba, pero se me habia olvidado quitar el código muerto. chiaaa
