### ISSUE TITLE
Nomina Individual - Vista previa (excel) incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#870]
Te envié por correo un ejemplo, donde viene el emisor y como muestra una serie de inconsistencias.
Ese cliente es un de los mas duros sinodales de nuestra aplicación, ya que se dedica (supuestamente) al desarrollo, y no pasa nada por alto.
Hasta podríamos pedirle apoyo como pruebas... detecta buenas cosas, y las reporta en formato chingaquedito... jejeje

**Comment by RigoFlores** [comment]
ya están presionando los clientes con este fix...
Este reporte lo ocupan para cuadrar lo reportado en el excel, con su cálculo de nómina ingresado.

**Comment by jccastillo0007** [comment]
te mande por correo un reporte que genere hoy... todo se ve bien, revise 6 empleados aleatorios y el total coincide, yo creo que el problema era el mismo de cuando no calculaba bien las deducciones.
