### ISSUE TITLE
No jala el envio de correo automático de Optibelt en ambiente de red

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#871]
Hay que buscarle un poco mas a todo este desmadre, de lo contrario buscar el camino alterno en el web server.

**Comment by jccastillo0007** [comment]
chiaaaa, a mandarlos desde web

**Comment by jccastillo0007** [comment]
listo.. ya le puse también el logo, no lo mostraba porque no lo estaba mandando a jasper...

**Comment by RigoFlores** [comment]
No envía correo, no incluye el logo en el PDF, y duplica la descripción de los productos.
