### ISSUE TITLE
Complemento de Nomina 1.2 -Marca error en la antigüedad 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#872]
Pero no sé por donde pueda estar el problema, ya que no presenta el cálculo realizado.
Lo puedes mostrar en modo solo lectura, o lo puedes sugerir con posibilidad a que ellos lo cambien???

**Comment by RigoFlores** [comment]
![nomina](https://cloud.githubusercontent.com/assets/2912775/22001476/0b9bfbec-dc0b-11e6-86aa-5da46ef86fe1.png)

**Comment by jccastillo0007** [comment]
fixed... era por no tomar la fecha de corte al dia de fecha inicial de pago... tomaba el dia actual.

**Comment by RigoFlores** [comment]
Sigue dando problemas el cálculo... te mandé un correo con evidencia....

**Comment by jccastillo0007** [comment]
vale ma.... ya esta ok, revise con ese cliente en PRO y esta ok.

**Comment by RigoFlores** [comment]
Sigue 'un poco' mal el cálculo, te envié evidencia por correo. Está calculando creo yo, una semana de menos, lo cual podría arrojar un valor negativo.

![image](https://cloud.githubusercontent.com/assets/2912775/22117662/6e21f25e-de3a-11e6-8e1f-bba292bc2e8c.png)

**Comment by jccastillo0007** [comment]
rerererefixed.
