### ISSUE TITLE
Al momento de timbrar nómina marca que no se cuenta con la funcionalidad

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#874]
Es un cliente nuevo. rfc: IDM110205SE8
puedes intentar con el empleado Pineda Ramirez Irving

**Comment by jccastillo0007** [comment]
Era por falta del plugin de addendas.... por ahora sigue configurando los plugins tal como lo hacias antes, hasta que arregle el desmadre de plugins vs privilegios.
