### ISSUE TITLE
Enviar el certificado de pruebas, y toda la carpeta setup de optibelt en pruebas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#875]
desde ayer pedí el certificado de pruebas y llave que acepta facturehoy para probar en escritorio.
Tampoco lo de optibelt lo tengo...

**Comment by jccastillo0007** [comment]
ya lo mande, ojo, no es con facture hoy, es con finkok... es con el que me funcionó primero.

**Comment by RigoFlores** [comment]
pues no, sigue marcando error cuando quiero hacer una factura simple desde escritorio... que el sello no corresponde... estás seguro que tenemos bien el ambiente de pruebas???

**Comment by jccastillo0007** [comment]
mande correo con la info.
