### ISSUE TITLE
Complemento Nomina 1.2 - deducciones marca error en cesantía

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#876]
Habíamos acordado que eliminaríamos los paréntesis o los puntos al final del enunciado para percepciones o deducción. 

El caso de cesantía sigue teniendo punto al final, y truena al momento del timbrado.

**Comment by jccastillo0007** [comment]
issue repetido, chiaaa

**Comment by RigoFlores** [comment]
Pues no, este issue se refiere a que el catálogo de deducciones tiene todavía puntos y paréntesis.

El otro se refiere a los conceptos ya capturados (heredados), de la v1.1. Aunque el problema resultante es el mismo, son 2 distintos orígenes.
