### ISSUE TITLE
Optibelt - el PDF en web está incompleto, ya que no muestra datos extra a nivel pro.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#877]
Hay que arreglarlo

**Comment by jccastillo0007** [comment]
de hecho es solo 1 dato extra a nivel producto, eso lo vi en las addendas facturat que llegan al server

**Comment by RigoFlores** [comment]
realmente son los datos de la aduana: nombre, fecha y número
