### ISSUE TITLE
Optibelt - Las notas de crédito emitidas, aparecen como facturas en el web

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#878]
Todas las notas de crédito que envía el super conector, aparecen como facturas en el web.
Recordar que la nota de crédito es egreso y las facturas son ingreso.

Para un formato personalizado de notas de crédito, ocupa el mismo PDF, pero renombrar a cfdi_notaCredito_OME111223UN4.jrxml

Necesitamos que se guarden y reconozcan como notas de crédito, incluyendo las que ya existen ahora mismo.

**Comment by jccastillo0007** [comment]
ok, pero entonces también necesito la plantilla genérica cfdi_notaCredito.jrxml

Listo...hay que probar en producción... voy a subir este cambio
