### ISSUE TITLE
Optibelt - Subir las facturas vivas para iniciar con lo de CxC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#879]
Ellos ya quieren iniciar su captura de pagos, para lo cual se ocupa:

a) Subir la información de las facturas 'vivas'. OJO, aquí hay notas de crédito, pagos parciales y facturas.
b) Todas las facturas/notas de crédito con fecha de emisión anterior al 31 de diciembre, deberán ser eliminadas del histórico de facturación, tanto en BD como en archivos.
c) Ellos quieren validar que los saldos iniciales son correctos, por lo que primero revisarán que el saldo inicial es correcto, para ello además de eliminar todas las facturas que no aparecen en el listado de excel, también las facturas del 2017 se deberán ocultar o incluso borrar. Si se borran, después las tendremos que subir. OJO, este asunto es delicado por el tema de los datos extra a nivel general y producto

**Comment by jccastillo0007** [comment]
pues ya se subi[o la info... hay inconsistencias, pero de nuestro lado ya debe estar todo listo.

**Comment by RigoFlores** [comment]
Hay que tener bien claro el procedimiento último que ejecutaste, ya que aparentemente está OK.
Esto es porque cambiarán nuevamente el contenido del excel, y eso nos mete en problemas.
Le comentaré del precio del soporte de los 6 primeros meses, que serian unos 3k mensuales???
