### ISSUE TITLE
Generar version solo para administradores de FacturaT

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#88]
Debe contener :

Reportes 
Charts
Key generator

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
pero nos está costando un servidor mas... es decir el mismo costo que pro, por ejemplo.
Que alternativas tenemos?

**Comment by jccastillo0007** [comment]
Es temporal... un par de meses...

Saludos.
JC.

**Comment by RigoFlores** [comment]
Por que en un solo servidor, no se levanta la instancia de pruebas escritorio y web?????
Según yo, dada la carga de esos ambientes.... no debería existir ningún pedo para ello

**Comment by jccastillo0007** [comment]
Si, es correcto, ese es el objetivo... pero vamos poco a poco... para 
igualar servidores..

Saludos.
JC.

**Comment by jccastillo0007** [comment]
Si, es correcto, ese es el objetivo... pero vamos poco a poco... para 
igualar servidores..... eso es lo bueno del cloud, que puedes crear y 
eliminar servidores en cualquier momento...

tambien hay que migrar la infraestructura de SVN, Jenkins y Nexus.

Saludos.
JC.
