### ISSUE TITLE
CxC - Ingresar cobro - Mostrar las facturas y las NOTAS DE CRÉDITO

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#881]
Cuando se realiza una consulta, se deberán mostrar tanto las facturas como las NOTAS DE CRÉDITO.
El importe de las notas de crédito, aparecerán en la columna de ABONO.

Las facturas aparecerán como hasta ahora, es decir como cargos.

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
OJO, aquí tenemos que mostrar este comportamiento para las facturas, pagos y notas de crédito 'vivas'.
Esto es un blocker ahora mismo, ya que ellos están esperando que subamos dichas facturas vivas para que validen los saldos.

**Comment by jccastillo0007** [comment]
done... le agregué un campo en la tabla de consultas, para reflejar cuales son facturas y cuales son notas de crédito, me faltar[ia el tema de distinguir cuales NC est[an vivas y permitir que las seleccionen para pagar facturas, pero eso es otro ticket.
