### ISSUE TITLE
CONDOMINIO - CxC - Ingresar cobro - Pagos Excedentes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#882]
Hasta el momento manejamos 3 tipos de claves:

FA - es una factura
PA - Cuando se registra un pago
NC - cuando se trata de una nota de crédito.

Resulta que algunas ocasiones, se necesita registrar un PAGO EXCEDENTE, es decir el cliente paga 100 pesos, pero realmente solo liquida facturas por 80 pesos. Que sucede con los 20 pesos restantes?
Se crea una nueva clave, (SF) que su manejo es idéntico a la NC, pero que no tiene un CFDI asociado.

Al igual que la NC, el SF muestra su monto en la columna de CARGO, y no de abono.

**Comment by jccastillo0007** [comment]
no ma, este no esta tan fácil... ya que todo parte de CFDi previamente guardados... ya sea para facturas o NC... ahora tengo algo que se llama SF que no es un CFDi pero que debo mostrarlo en la lista de CFDis.... chiaaa

**Comment by jccastillo0007** [comment]
Este tipo de saldo a favor, se crea a partir de lo que sobra de un pago, o también puede sobrar a partir de una NC ?

Es absolutamente necesario soportar esto?

**Comment by RigoFlores** [comment]
Lo que pidió específicamente el cliente, fue excedente de pago... eso es parte de lo que indiqué, ya se salía de alcance original, y aceptó que le indicara de a como el cambio...

Lo d NC, quedamos que se aplicarían completas, y no se soportarían parcialidades.

Peeeero, en la migración de facturas vivas, encontré un caso donde quedó una NC parcialmente cobrada... chiaaaaaa....
Por otro lado, si se implementa lo de el excedente en pagos, no es lo mismo mismo para excedente en NC?

**Comment by RigoFlores** [comment]
Este es un requisito de inicio para el condominio.
Resulta que algunos vecinos pagan por adelantado todo el año. Entonces debemos considerar este escenario.
