### ISSUE TITLE
CxC - Ingresar Cobro - Editar Pagos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#883]
Algunas veces por error de captura o por error del cliente se tiene que editar un pago ya capturado.
Como saberlo? Se captura la referencia y se le da consultar.... si existen pagos asociados a esa referencia, entonces se muestran y a partir de ahí, se pueden editar como si recién estuviera capturando los pagos...

Una alternativa para no aventarse la bronca de editar un pago, sería BORRAR ese pago asociado a la referencia. Una vez borrado (PREVIA CONFIRMACIÓN), pues entonces que vuelvan a ejecutar su proceso de ingresar cobro. Quizás sea la opción mas simple y consistente.
Que implica borrar un pago? Pues que todas las facturas que fueron registradas con pago y con esa referencia, simplemente quedan limpias, como las recién emitidas.

**Comment by jccastillo0007** [comment]
Pues de hecho si debemos borrar los pagos, porque si permitieramos la edición de pagos, imaginate que ponen la referencia y al darle buscar, aparecen 5 facturas pagadas con esa referencia, y una nota de crédito que es la que usaron para pagar, hasta ahi todo bien, pero que tal si lo que quieren es agregar otras facturas al pago, en lugar de las facturas inicialmente seleccionadas, en ese caso, tendrían que usar los filtros de busqueda para encontrar las facturas, y entonces ya se arma un reverendo desmadre.... mejor solo vamos a permitir borrar.

Work in progress.

**Comment by jccastillo0007** [comment]
ya  agregue la pantalla para consulta de pagos, y apartir de ahi borrar un pago... ya funciona el filtro por referencia.... solo me falta agregar el botón de eliminar

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Negativo, no aparece el botón de borrar.
OK, yo pensé que esta pantalla era para consultar cobros por referencia, pero sirve muy bien para ambas.
a) generar el reporte de cobro por referencia.
b) exportar a un excel lo mostrado en pantalla. El Header debe incluir el RFC del receptor, la fecha de pago, y la referencia. El detalle será lo mostrado en pantalla.
c) En caso de agregar aquí el botón de borrar el pago, identificado con la referencia... se debe pedir confirmación del borrado... muy importante esto último.

**Comment by jccastillo0007** [comment]
Duplicado con el issue de la pantalla de reporte de cobros... yo digo que hay que cerrar el otro ticket, y dejar este, que habla de la edición/cancelación de pagos.

**Comment by jccastillo0007** [comment]
Ya borra los pagos, y actualiza los estatus de las facturas que fueron pagadas.

**Comment by RigoFlores** [comment]
Necesitamos_
a) pedir confirmación del borrado
b) indicar que ya se borró con éxito.

no dice nada nada

**Comment by jccastillo0007** [comment]
chiaaaa, neta

**Comment by RigoFlores** [comment]
Pues no indica absolutamente nada... pedir confirmación e indicar que ya se borró, es lo mínimo decente en ese proceso de borrado de pagos
