### ISSUE TITLE
CxC - Ingresar pago tipo NC o SF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#884]
Cuando haces una consulta para ingresar un cobro, se muestran las facturas, pero también pueden existir NC (notas de crédito) que no se han utilizado.
Si se elige una NC, en automático se considera que se quiere ingresar un pago tipo NC, por un monto equivalente al importe de la nota de crédito y cuya referencia es el folio de la nota seleccionada.
A partir de ahí, el ingreso del pago se realiza de manera natural. Obvio, un pago no puede capturarse en una NC, ya que la NC propiamente es un saldo a favor del cliente.

**Comment by jccastillo0007** [comment]
Done...

Tiene muchas validaciones, hay que hacer varias pruebas.

**Comment by RigoFlores** [comment]
Estoy viendo que cuando eliges la NC para ingresar el cobro, coloca como referencia ... la referencia que ya trae la nota... y lo que debe hacer es poner como referencia el folio de la nota de crédito.... checa lo resaltado en amarillo... dado que ya estamos estableciendo el mecanismo para pagar con NC, me parece que el dato de la derecha, ya sale sobrando

![pagonc](https://cloud.githubusercontent.com/assets/2912775/22956009/f8576bfc-f2e4-11e6-8b2a-e5b56dd61d5d.PNG)

**Comment by jccastillo0007** [comment]
okas me late, sirve que se limpia un poco la pantalla.

**Comment by jccastillo0007** [comment]
Done.

ojo.... apenas lo voy a subir.

**Comment by RigoFlores** [comment]
ahora se valida hasta que se complete el 2o round de optibelt

**Comment by RigoFlores** [comment]
Cerraré por la parte de NC, y abriré una para SF
