### ISSUE TITLE
Nómina Individual - eliminar caracteres de los conceptos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#885]
Para las percepciones o deducciones ... en la sección de conceptos (lo que si se envía al SAT), eliminar los puntos o paréntesis al final del registro... ya que como hemos visto marca error...

Son conceptos que ya se tenían, pero al incluir un punto al final del renglón, marca error..

**Comment by jccastillo0007** [comment]
pues según yo solo lo ví en cesantía y vejez... tu identificas algún otro ?

**Comment by RigoFlores** [comment]
No nos entendimos.
Uno son los catálogos del SAT, donde el cliente elige y al final se envía la clave de percepción, deducción, otros pagos, etc.
Y otra cosa son los conceptos que se le sugieren al cliente, y esos si se envían de manera literal.
En esos conceptos, podrían existir puntos o paréntesis... ya que son herencia de la versión anterior de nómina. Ahí es donde este issue se refiere, ya que indica CONCEPTO CONCEPTO CONCEPTO CONCEPTO, y no clave. 
De alguna manera están relacionados, pero el concepto heredado de la versión 1.1 de nómina, pudiera contener . o ), y nosotros eso ahora mismo no lo validamos ni conocemos.

La petición, es eliminar esos caracteres que tanto ruido meten, de los conceptos actuales de todos los clientes...

**Comment by jccastillo0007** [comment]
no inventes, son 2200 empleados, y no lo puedo hacer por query, tendrá que ser cada que actualicen un cliente para generar su recibo, se lo quito por código, estaré eliminando (, ), . y ,
 nada mas va.

Para probar solo es cuestión de editar un empleado y luego salvarlo, y le debe quitar los caracteres arriba definidos... este código lo voy a dejar solo un tiempo, y luego lo quitamos para evitar tanto overhead.

**Comment by RigoFlores** [comment]
Entiendo que actualizar un cliente, se refiere a actualizar un empleado. Esto es, cuando modifiquen CUALQUIER PARÁMETRO DEL EMPLEADO, aunque no sea el concepto, eliminará esos caracteres???

**Comment by jccastillo0007** [comment]
Si correcto, dicho en otras palabras, cuando editan y guardan un cliente, se van a revisar todas las percepciones y deducciones para eliminar esos caracteres.... este proceso debemos dejarlo vigente solo por un tiempo, porque va hacer mucho overhead.

**Comment by RigoFlores** [comment]
ok
