### ISSUE TITLE
CxC - Agregar Reporte por Referencia

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#886]
Un reporte basado en rango de fechas, donde se indicará únicamente:

Reporte de Pagos por Referencia

Rango de Fechas: del tal a tal

FECHA - REFERENCIA -  IMPORTE

**Comment by RigoFlores** [comment]
Falta cambiar el título de la pantalla...
"Reporte de Cobros por Referencia"

**Comment by RigoFlores** [comment]
Jajaja... esta pantalla era para editar pagos... es decir borrar pagos... jejeje
Pero ya vimos que tendrá 3 funciones:
a) reporte por referencia
b) exportar a excel dicho reporte
c) eliminar (previa confirmación, indicando que no hay marcha atrás), un pago...

**Comment by RigoFlores** [comment]
El reporte que se muestra está incompleto.
El reporte debe ser un extracto de la cartera por cliente, cuando no aplicas filtro de status, y filtrado por referencia.

**Comment by jccastillo0007** [comment]
No le puse de nombre Reporte de .... porque esta pantalla también servirá para eliminar pagos.

**Comment by jccastillo0007** [comment]
solo me falta la parte de eliminar.

**Comment by RigoFlores** [comment]
OK, solo un detalle... el orden en que aparecen los datos... debe ser el MISMO MISMO MISMO MISMO... que aparece en la cartera de cliente.... esto es una factura y sus pagos asociados, otra factura y sus nc y pagos, etc... todos esos pagos asociados a la misma referencia

**Comment by jccastillo0007** [comment]
esto no es posible, por una diferencia esencial, el reporte de cartera por cliente, se basa en facturas y sus pagos, el reporte por referencia, se basa en referencias y sus facturas

**Comment by RigoFlores** [comment]
mismo caso que cartera de cliente... hay algo que no cuadra... tenemos que revisarlo EN CONJUNTO... de lo contrario no nos entendemos.
