### ISSUE TITLE
No está jalando lo de retenciones - internal error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#887]
ni en pru, ni en pro... cuenta de la tia

**Comment by jccastillo0007** [comment]
Como lo probaste: ni pru ni pro tenían la serie RET dada de alta, chiaaa

EN pru no pude generar una retención porque finkok marca error.
En pro , si generé una retención con la cuenta de la TIA, ahora hay que cancelarla jojojjo

Cuando genere en PRO, hubo un problema y no mostr[o el XML y PDF, eso ya lo arreglé.

Dime como puedo reproducir el internal error.

**Comment by RigoFlores** [comment]
lo del internal error, ya no aparece, ahora en su lugar muestra:

Error al timbrar el CFDi de retenciones (124)

supongo que es porque finkok no timbra eso, o no hemos pagado o no tenemos contratado el timbrado de retenciones con finkok

**Comment by jccastillo0007** [comment]
debes usar la cuenta ACO560518KW7 es la única que acepta finkok.
