### ISSUE TITLE
Implementar complemento dividendos para retenciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#889]
En la carpeta de proyectos, ya existe la de dividendos con el mapeo.
Antes no lo cobraban aparte, y ahora facturehoy dice que si.
Esperaré respuesta de finkok.

Yo coticé y aceptaron la propuesta, pero espero que no salga mas caro el caldo que las putas albóndigas

**Comment by jccastillo0007** [comment]
Pues no ha cambiado la versión... no son cambios dificiles en código, pero hay que validar lo del costo con finkok... cuanto cuesta con facture hoy? vi lo que te mandó Emmanuel, pero pues no viene el costo de cada timbre con este complemento.

**Comment by RigoFlores** [comment]
Ya validé con FactureHoy, y resulta que nuestro paquete si incluye retenciones, así que no hay nada mas que pagar, solo hay que implementarlo. Ya transcurrió la mitad del tiempo que le ofrecí al cliente...

**Comment by RigoFlores** [comment]
lo voy a cerrar, para levantar issues individuales (específicos).
