### ISSUE TITLE
No envía el nombre alterno correctamente al PDF y XML (nombre alterno no, domicilio alterno si)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#89]
Cuando a un mismo RFC se le asigna uno o varios nombres alternos, si se utilizan en la pantalla de facturas, no toma el nombre o razón social correspondiente al nombre alterno elegido, para enviarlo al PDF y XML.
El domicilio alterno, si lo envía correctamente.

**Comment by jccastillo0007** [comment]
Rejected.
