### ISSUE TITLE
Superconector - no agrega los nuevos clientes detectados en escritorio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#891]
al menos para el caso optibelt. No sé si tenga que ver con los números de cliente, que son clientes nuevos, pero asociados a un mismo rfc

**Comment by jccastillo0007** [comment]
Fixed.... no era nada de eso, era un problema en específico con XEXX010101000, ya que existe por todas partes con muchos clientes.

**Comment by RigoFlores** [comment]
Esto lo retomaremos hasta que se presente nuevamente el caso....
Por cierto, ya comentó Optibelt que mandarán ooooootro nuevo excel actualizado.
Lo malo el retrabajo, lo bueno que ya sabemos por donde.
