### ISSUE TITLE
Información Optibelt incorrecta (rfc con guiones)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#893]
Existe un cliente GOMR600427-4M8 y otro GOMR6004274M8
Entiendo que son lo mismo, pero incluso ambos tienen asociadas facturas.

De casualidad lo ví, porque en los archivos de texto que enviaste, no aparecen... no entiendo que está pasando.

**Comment by jccastillo0007** [comment]
Fixed.

Y pues lo que esta pasando es que ese RFC viene de la base de datos, chiaaaaa, lo que no vi son facturas asociadas.

**Comment by RigoFlores** [comment]
ok, quizás lo capturaron mal desde origen... luego intentó timbrar y les marcó error... pero en ese inter, ya se había almacenado el RFC con guión.
De hecho el factura-t, no debería aceptar guiones, ni espacios en el rfc cuando se intenta almacenar
