### ISSUE TITLE
Nomina 1.2 - Conector  entidad federativa incorrecta al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#897]
Siempre manda D.F. (esa ya ni existe)

**Comment by jccastillo0007** [comment]
mmmmm si habia un error al poner la entidad federativa, pero no veo porque ponga siempre D.F., como bien dices, ese ya no existe en el catálogo

**Comment by jccastillo0007** [comment]
ya vi porque... como había un error y no interpretaba bien la clave del estado, siempre le pone el estado que mandabas en el conector para el receptor.

Fixed.
