### ISSUE TITLE
Nomina 1.2 conector - envia entidad federativa fija al XML

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#898]
Siempre QUE (querétaro), y no la del archivo

**Comment by jccastillo0007** [comment]
va un poco relacionado al ticket 897, no interpretaba bien la clave del estado que mandaba en el layout, pero ya quedo arreglado.

**Comment by RigoFlores** [comment]
Le puse una clave incorrecta y me envió entidad querétaro.
No sé que también esté eso... quizás debería marcar entidad no identificada o algo así...?

**Comment by jccastillo0007** [comment]
tiene por default entidad federativa querétaro... 

mmmm yo digo que mejor dejemos una por default, porque causa muchos problemas

**Comment by RigoFlores** [comment]
ok, no tan de acuerdo, tampoco tan desacuerdo... ni a favor ni en contra, ni fu ni fa, ni si, ni no... ni muy muy, ni tan tan...
