### ISSUE TITLE
Nomina 1.2 por conector - Incluir los importes del CFDI estándar.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#899]
Yo creo que como está ahora mismo, nos estaría generando problemas por las inconsistencias en los números. Unos provienen del cliente y otros son de nosotros, y deben empatar.

Me explico, ahora mismo, facturat calcula los totales a nivel complemento, a partir de las percepciones, deducciones, otros pagos, etc.
OK, a nivel de complemento ya se calcula, tanto conector como web, y está bien.

Total Percepciones: SUMA DE LAS PERCEPCIONES (sueldos + indemización + jubilación)
Total Deducciones: SUMA DE DEDUCCIONES (otras deducciones + impuestos retenidos)
Total Otros Pagos: SUMA DE OTROS PAGOS

A nivel de CFDI estándar, dado que los números están dictaminados (de acuerdo a spec del SAT) por los cálculos de arriba, entonces en automático hay que incluirlos nosotros en el XML estándar.

SUBTOTAL= TOTAL PERCEPCIONES + TOTAL OTROS PAGOS
DESCUENTO = TOTAL DEDUCCIONES
VALOR UNITARIO = TOTAL PERCEPCIONES + TOTAL OTROS PAGOS
IMPORTE = TOTAL PERCEPCIONES + TOTAL OTROS PAGOS
TOTAL = TOTAL PERCEPCIONES + TOTAL OTROS PAGOS - TOTAL DEDUCCIONES

Si la respuesta es que nos metemos en broncas por cálculos, lo contrarrespuesta es que no, ya que ahora mismo hacemos ya dichos cálculos, y para evitar conflictos mejor los metemos al cfdi estándar también.

**Comment by jccastillo0007** [comment]
jajajaja bug, enhancement y además missingfunctionality chiaaaa

**Comment by jccastillo0007** [comment]
osea que me plancho lo que ellos indicaron en el archivo txt como total, subtotal, descuento, valor unitario e importe ?

**Comment by RigoFlores** [comment]
Bag, porque si lo que viene en los datos del estándar, está chueco con respecto al complemento de nómina, marca error.
Enjeismen porque evitará ese error típico del conector, y ahorrará soportes.
Misin funcionaliti porque no lo tenemos, y debiste haberlo considerado...

Si, nos planchamos sus datos... si estaban mal, corregiremos... si estaban bien, entonces serán los mismos que planchemos... (enjeisment, que no?)

**Comment by jccastillo0007** [comment]
conste que yo no estaba de acuerdo... pero bueno... 

La versión de hoy en la noche del dropbox tiene estos cambios.
