### ISSUE TITLE
Complemento Dividendos - Internal error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#901]
Cuando eliges algún elemento de la lista, en los 2 catálogos que incluye el dividendo

**Comment by jccastillo0007** [comment]
chiaaaaaa, yo no he dicho que ya esta listo para pruebas, solo era para que vieras el avance de la vista.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
lo que levanté, fue para que se atendiera conforme el avance...
