### ISSUE TITLE
Complemento Dividendos - no timbra, marca internal error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#902]
Eso es al momento de timbrar

**Comment by jccastillo0007** [comment]
chiaaaa ticket triplicado.

**Comment by RigoFlores** [comment]
negativo, esto es al MOMENTO DE TIMBRAR...
Hoy precisamente preguntaron como vamos con esto

**Comment by RigoFlores** [comment]
dice que timbró, pero cuando quise descargar el XML, justo tumbaste el ambiente... chiaaaaaaa
