### ISSUE TITLE
Complemento Dividendos - modificar etiquetas o agregar tooltips

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#903]
Quedará muy atascado o colocamos tooltip con el rollo que viene en el mapeo? Esto último podría ser mejor opción. Lo que pasa es que yo no entiendo nada de esto, y si me preguntan solo diría lo que viene en la spec del SAT.

Tipo Dividendo/Utilidad
Importe o Retención Dividendo/Utilidad Nacional
Importe o Retencion Dividendo/Utilidad Extranjero
Retencion Dividendo del Extranjero
Tipo Sociedad
ISR Acreditable Nacional
Monto Dividendo Acumulable Nacional
Monto Dividendo Acumulable Extranjero

**Comment by jccastillo0007** [comment]
Done.
