### ISSUE TITLE
Dirigir este cliente EPN010312GC0 para que timbre por Finkok

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#906]
El cliente ya sabe que no podrá cancelar desde sistema.
Últimamente facturehoy se tarda mucho en entregar/publicar las facturas en el SAT.

Según yo, andan con bronquillas...

**Comment by jccastillo0007** [comment]
oye, es por web o standalone, es lo mismo pero no es igual.

**Comment by jccastillo0007** [comment]
nevermind... puedo desviarlo sin importar de donde venga la petición.

**Comment by RigoFlores** [comment]
Ok, vamos a estar observando a este rfc
