### ISSUE TITLE
Retenciones - Enviar las variables del complemento de dividendos al Jasper

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#907]
para desplegarlas en el PDF.
Favor de indicar como se llamarán y así las incluyo.

**Comment by jccastillo0007** [comment]
Hoy en dia ya se mandan las retenciones como datos extas cierto :+1: 
		fields.add(new Field("retencion", shared.getKeyRetention()));
		fields.add(new Field("descretencion", shared.getDescRetention()));
		fields.add(new Field("curpemisor", shared.getSourceCURP()));
		fields.add(new Field("nacionalidad", shared.getTargetNationality()));
		fields.add(new Field("curpreceptor", shared.getTargetCURP()));
		fields.add(new Field("mesinicial", shared.getIniMonth()));
		fields.add(new Field("mesfinal", shared.getEndMonth()));
		fields.add(new Field("ano", shared.getYear()));
		fields.add(new Field("gravable", shared.getGravable() + ""));
		fields.add(new Field("exento", shared.getExento() + ""));
		fields.add(new Field("retenido", shared.getTotalRetenido() + ""));

**Comment by jccastillo0007** [comment]
a esos datos extras les voy a agregar el complemento de dividendos, y quedará asi

**Comment by jccastillo0007** [comment]
fields.add(new Field("dividendos_type", shared.getDividendosType() + ""));
		fields.add(new Field("montdivacumext", df.format(shared.getMontDivAcumExt() + "")));
		fields.add(new Field("montdivacumnal", df.format(shared.getMontDivAcumNal() + "")));
		fields.add(new Field("montisracrednal", df.format(shared.getMontISRAcredNal() + "")));
		fields.add(new Field("montisracredretext", df.format(shared.getMontISRAcredRetExtranjero() + "")));
		fields.add(new Field("isracredretmex", df.format(shared.getMontISRAcredRetMexico() + "")));
		fields.add(new Field("montretextdivext", df.format(shared.getMontRetExtDivExt() + "")));
		fields.add(new Field("proporcionrem", df.format(shared.getProporcionRem() + "")));
		fields.add(new Field("tiposocdistrdiv", shared.getTipoSocDistrDiv() + ""));


Tu no le hagas caso al primer parametro que viene ahi como datos extras.... 

Te puse todo eso, para que veas como va el orden de los datos extras, pero a Jasper solo llega e lvalor.

**Comment by RigoFlores** [comment]
pues lo único que hice, fue mostrar los datos extras... 12, 13, 14 y 15, pero marca error del jasper... no sé como estás enviando las variables.

**Comment by jccastillo0007** [comment]
Este es el comentario que ayer no se subió correctamente

Este es el orden de los datos extras que te van a llegar a jasper

		fields.add(new Field("retencion", shared.getKeyRetention()));
		fields.add(new Field("descretencion", shared.getDescRetention()));
		fields.add(new Field("curpemisor", shared.getSourceCURP()));
		fields.add(new Field("nacionalidad", shared.getTargetNationality()));
		fields.add(new Field("curpreceptor", shared.getTargetCURP()));
		fields.add(new Field("mesinicial", shared.getIniMonth()));
		fields.add(new Field("mesfinal", shared.getEndMonth()));
		fields.add(new Field("ano", shared.getYear()));
		fields.add(new Field("gravable", shared.getGravable() + ""));
		fields.add(new Field("exento", shared.getExento() + ""));
		fields.add(new Field("retenido", shared.getTotalRetenido() + ""));

		fields.add(new Field("dividendos_type", shared.getDividendosType()));
		fields.add(new Field("montdivacumext", df.format(shared.getMontDivAcumExt())));
		fields.add(new Field("montdivacumnal", df.format(shared.getMontDivAcumNal())));
		fields.add(new Field("montisracrednal", df.format(shared.getMontISRAcredNal())));
		fields.add(new Field("montisracredretext", df.format(shared.getMontISRAcredRetExtranjero())));
		fields.add(new Field("isracredretmex", df.format(shared.getMontISRAcredRetMexico())));
		fields.add(new Field("montretextdivext", df.format(shared.getMontRetExtDivExt())));
		fields.add(new Field("proporcionrem", df.format(shared.getProporcionRem())));
		fields.add(new Field("tiposocdistrdiv", shared.getTipoSocDistrDiv()));

**Comment by jccastillo0007** [comment]
para ti todos son datos extras en ese orden, el resto de la sintaxis java , la puedes ignorar.

**Comment by jccastillo0007** [comment]
Ya verifiqué y los datos extras si lelgan en ese orden.
