### ISSUE TITLE
RECIBO DE NÓMINA DE INDEMINIZACIÓN - FALTÓ UNA PERCEPCIÓN EN EL PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#908]
NO MANDÓ AL PDF LA PERCEPCIÓN Vacaciones Pago. SI LA CONTABILIZÓ Y EN EL XML APARECE, PERO NO LO MUESTRA EN EL PDF.

RECORDAR QUE CON SUBSIDIO AL EMPLEO, O INDEMINIZACIÓN SE ENVÍA “COMO PERCEPCIÓN” AL PDF, AL FINAL DE TODAS LAS PERCEPCIONES ESTÁNDARES.

    <nomina12:Percepciones TotalExento="15953.57" TotalGravado="30810.7" TotalSeparacionIndemnizacion="12351.77" TotalSueldos="34412.5">
                <nomina12:Percepcion Clave="022" Concepto="Prima por antiguedad" ImporteExento="12351.77" ImporteGravado="0.0" TipoPercepcion="022"/>
                **_<nomina12:Percepcion Clave="001" Concepto="Vacaciones Pago" ImporteExento="0.0" ImporteGravado="24900.0" TipoPercepcion="001"/>_**
                <nomina12:Percepcion Clave="021" Concepto="Prima vacacional" ImporteExento="1200.6" ImporteGravado="5024.4" TipoPercepcion="021"/>
                <nomina12:Percepcion Clave="002" Concepto="Aguinaldo" ImporteExento="2401.2" ImporteGravado="886.3" TipoPercepcion="002"/>
                <nomina12:SeparacionIndemnizacion IngresoAcumulable="12351.77" IngresoNoAcumulable="12351.77" NumAñosServicio="6" TotalPagado="12351.77" UltimoSueldoMensOrd="1250.0"/>            </nomina12:Percepciones>

**Comment by jccastillo0007** [comment]
Pues si hizo algo raro...

Esto es lo que mandó a Jasper:

tipoPercepcion1=022,clavePercepcion1=022,conceptoPercepcion1=Prima por antiguedad,importePercepcion1=12351.77,
tipoPercepcion2=Separación o Indemnización,clavePercepcion2=001,conceptoPercepcion2=Separación o Indemnización,importePercepcion2=12351.77,
tipoPercepcion3=021,clavePercepcion3=021,conceptoPercepcion3=Prima vacacional,importePercepcion3=6225.0,
tipoPercepcion4=002,clavePercepcion4=002,conceptoPercepcion4=Aguinaldo,importePercepcion4=3287.5,

La segunda percepción es incorrecta, ahí esta mandando el tema de indemnización, (lo cuál es correcto), pero no sé porque reemplazó la vacaciones,

ando en eso revisando.

**Comment by jccastillo0007** [comment]
Fixed, pequeño problema de indices... por eso se reemplazaba el tipo percepción 2.

**Comment by RigoFlores** [comment]
ya quedó en pro para volver a generar el recibo?

**Comment by RigoFlores** [comment]
no, ahora quitó indeminización... chiaaaaa...

el cliente lo tenemos esperando desde el viernes....

**Comment by RigoFlores** [comment]
no, sigue chueco... ya cumple con lo que pedí, pero está chueco... 
con base a las aclaraciones... SOLO SE ENVIARÁ AL PDF... LO QUE SE CAPTURE EN PERCEPCIONES
LO QUE SE CAPTURA DE MANERA INDEPENDIENTE EN INDEMNIZACIONES, NO SE ENVIARÁ COMO PERCEPCIONES.
Disculpa la confusión, pero bueno... ahora mismo quedó chueco el PDF
