### ISSUE TITLE
Complemento de Nomina 1.2 - Revisar cálculo de percepciones

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#909]
APLICA PARA WEB Y PARA ESCRITORIO (CONECTOR)

LOS INGRESOS TODOS PROVIENEN DE LO QUE SE CAPTURE EN PERCEPCIONES + OTROS PAGOS.

EL TOTAL DE PERCEPCIONES, PROVIENE DE LA SUMA DE TODO LO QUE SE CAPTURE EN PERCEPCIONES.
PARA EL CASO DE INDEMINIZACIONES TENEMOS  QUE SEPARAR LAS CLAVES 022, 023 Y 025
PARA EL CASO DE JUBILACIONES, TENEMOS QUE SEPARAR LAS CLAVES 039 Y 044

Total Percepciones: SUMA DE LAS PERCEPCIONES (sueldos (TODAS LAS PERCEPCIONES EXCEPTO 22, 23, 25, 39 Y 44) + indemización (022, 023 Y 025) + jubilación (039, 044) )
Total Deducciones: SUMA DE DEDUCCIONES (otras deducciones + impuestos retenidos)
Total Otros Pagos: SUMA DE OTROS PAGOS

A NIVEL CFDI ESTÁNDAR:

SUBTOTAL= TOTAL PERCEPCIONES + TOTAL OTROS PAGOS
DESCUENTO = TOTAL DEDUCCIONES
VALOR UNITARIO = TOTAL PERCEPCIONES + TOTAL OTROS PAGOS
IMPORTE = TOTAL PERCEPCIONES + TOTAL OTROS PAGOS
TOTAL = TOTAL PERCEPCIONES + TOTAL OTROS PAGOS - TOTAL DEDUCCIONES

**Comment by jccastillo0007** [comment]
Esto ya esta cuadrado cierto ?

**Comment by RigoFlores** [comment]
hoy reviso

**Comment by RigoFlores** [comment]
en web (PRU) no pude validar, ya que pide (urge el switch automático):

**nom165 : El nodo Nomina.Emisor.EntidadSNCF debe existir. (3)**

Al rato checo en escritorio...

**Comment by RigoFlores** [comment]
En escritorio al parecer no está jalando... marca esto.. (te mandaré un correo con los detalles)..


code=003,description=nom157 : El valor del atributo Nomina.TotalPercepciones no coincide con la suma TotalSueldos más TotalSeparacionIndemnizacion más TotalJubilacionPensionRetiro del  nodo Percepciones.]
