### ISSUE TITLE
CxC - Ingresar cobro con NC

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#911]
Cuando inicialmente se elige una NC para pagar, lo hace bien.
Pero cuando cuadro las cantidades, pone el monto del cobro a cero.
Si quito la selección para empezar de cero, mantiene el monto de cobro, aún sin elegir ninguna NC

**Comment by RigoFlores** [comment]
Ver el video describiendo el error, en la carpeta del dropbox, para optibelt

**Comment by jccastillo0007** [comment]
Listo...todavia hay un issue cuando deseleccionas todo ... pero... será ese un caso real ?, en ese caso que le den limpiar jojojo

**Comment by RigoFlores** [comment]
no sé si sea caso real, pero a mí me salí naturalito este caso de prueba...
Lo cerraré y vemos que dice el cliente.
