### ISSUE TITLE
Error al timbrar Retenciones + Dividendos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#912]
En PRU con la cuenta ACO (que es la única que timbra, ya no lo incluiré en los issues).

marca:

Error al timbrar el CFDi de retenciones (124)

**Comment by jccastillo0007** [comment]
tons ya quedo esto en PRO ?

**Comment by RigoFlores** [comment]
hay un detalle que se le puede dar la vuelta, pero estrictamente hablando, el nodo de impuestos retenidos es opcional... y entiendo que nosotros lo pedimos a wilson... que pasaría si lo dejamos opcional???
Podemos validar ese timbrado en pru???

**Comment by jccastillo0007** [comment]
pues el problema en PRU es que Finkok manda XML mal formado, y no me da ninguna idea de que puede estar mal... para corregirlo... yo recuerdo que si logre timbrar en PRU las retenciones, pero antes del complemento de dividendos, tal vez esta por ahi el problema

**Comment by RigoFlores** [comment]
ok, pero entonces nosotros somos los que ponemos la restricción????

**Comment by jccastillo0007** [comment]
mmm cual restricción ?

Lo que yo digo es que antes de agregar el complemento de dividendos, finkok si timbraba bien.

**Comment by RigoFlores** [comment]
ya mezclé issues... ok,hay que ver porque marca error finkok... al menos debe timbrar, si no capturas el complemento...
