### ISSUE TITLE
Mejorar addenda pilgrims

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#914]
EN LA ADDENDA PILGRIMS TENEMOS DATOS DEL HEADER Y A NIVEL PRODUCTO

HEADER:

SI EL COMPRADOR SE DEJA VACÍO, NO SE INCLUYE EN LA ADDENDA . ESTO YA TRABAJA OK SIN PEDOS…
EL PEDIDO AUNQUE VA A NIVEL PRODUCTO, SE REPITE PARA TODOS, POR LO TANTO SE CONSIDERA PARTE DEL JEDER

                <fields>
                               <field>
                                               <tag>Proveedor</tag>
                                               <name>Proveedor</name>
                                               <type>STRING</type>
                                               <length>60</length>
                                               <value>420155</value>
                               </field>
                               <field>
                                               <tag>Comprador</tag>
                                               <name>Comprador</name>
                                               <type>STRING</type>
                                               <length>60</length>
                                               <value></value>
                               </field>
                               <field>
                                               <tag>Proceso</tag>
                                               <name>Proceso</name>
                                               <type>STRING</type>
                                               <length>60</length>
                                               <value>01</value>
                               </field>
                               <field>
                                               <tag>Pedido</tag>
                                               <name>Pedido</name>
                                               <type>STRING</type>
                                               <length>60</length>
                                               <value></value>
                               </field>

DETALLE:
1.	PEDIDO. SE REPITE PARA TODAS LAS PARTIDAS. SE TOMA DEL JEDER
2.	LA POSICIÓN SIEMPRE SERÁ 10, 20, 30, ETC (DEPENDIENDO DEL NÚMERO DE PARTIDA). HOY EN DÍA APARECE EN EL ARCHIVO DE CONFIGURACIÓN, COMO UN VALOR POR OMISIÓN.
3.	MATERIAL PUEDE SER EL ID O LA DESCRIPCIÓN DEL PRODUCTO EN LA FACTURA. PODEMOS TOMAR EL ID DEL PRODUCTO.
4.	SI ENTRADA VA VACÍO, NO SE TOMA EN CUENTA. (PRÁCTICAMENTE SE PUEDE IGNORAR)
5.	SI REFERENCIA VA VACÍO NO SE TOMA EN CUENTA, PERO PODEMOS SUGERIR QUE SEA LA SERIE Y FOLIO, SIN ESPACIOS Y SIN GUIONES. EJEMPLO “FE123”. 
6.	PRECIO, SE TOMA DE LA FACTURA ESTÁNDAR.

HOY EN DÍA SE CAPTURAN LOS DATOS POR CADA PARTIDA Y SE CARGA UN ARCHIVO DE ADDENDA QUE CONTENGA EL NÚMERO DE PARTIDAS, PERO REALMENTE SE PUEDE DEJAR AUTOMÁTICO

EL CLIENTE QUE TE COMENTO, TIENE 120 PARTIDAS EN UNA FACTURA. SI SE EQUIVOCA EN LA CAPTURA SERÁ UN DESMADRE. HAY QUE AUTOMATIZARLO.

LA PETICIÓN ES AUTOMATIZAR LOS PUNTOS 2,3 Y 5… QUE SON LOS QUE HOY EN DÍA SE CAPTURAN.
LA OTRA PETICIÓN, SERÍA PODER GUARDAR UNA PREFACTURA, PARA IRLA CAPTURANDO POR PARTES…. Y DAR OPCIÓN A EDITARLA…PARA IRLE AGREGANDO MAS PRODUCTOS… Y QUE FINALMENTE SE PUEDA TIMBRAR… 
COMO LA BESIBOL??

                               <field>                                                                                               
                                               <tag>Pro_1_Dato_1</tag>                                                       
                                               <name>Posicion1</name>                                                                                      
                                               <type>STRING</type>                                                                                              
                                               <length>60</length>                                                                                  
                                               <value>10</value>                                                                                      
                               </field>                                                                                                             
                               <field>                                                                                               
                                               <tag>Pro_1_Dato_2</tag>                                                                                      
                                               <name>Material1</name>                                                                                      
                                               <type>STRING</type>                                                                                              
                                               <length>60</length>                                                                                  
                                               <value></value>                                                                                           
                               </field>                                                                                                             
                               <field>                                                                                               
                                               <tag>Pro_1_Dato_3</tag>                                                                                      
                                               <name>Entrada1</name>                                                                                       
                                               <type>STRING</type>                                                                                              
                                               <length>60</length>                                                                                  
                                               <value></value>                                                                                           
                               </field>                                                                                                             
                               <field>                                                                                               
                                               <tag>Pro_1_Dato_4</tag>                                                                                      
                                               <name>Referencia1</name>                                                                                 
                                               <type>STRING</type>                                                                                              
                                               <length>60</length>                                                                                  
                                               <value></value>                                                                                           
                               </field>

**Comment by jccastillo0007** [comment]
Si se puede automatizar al 100, ya que no hay ningún dato que deban capturar a manita, todo se puede agregar al leer la factura.

Es mas viable automatizar la parte de generar la addenda, que el tema de generar la factura por partes.

Pregunta. Si van a generar la factura con nosotros, entonces también van a generar una factura con 120 productos?

**Comment by jccastillo0007** [comment]
por donde se va a generar esta addenda, por pantalla ? o desde el addendador?

**Comment by RigoFlores** [comment]
El cliente va a generar la factura y addenda con nosotros. Como le indiquemos, desde pantalla y luego addendador, o todo junto.

Cuando ingrese un producto al catálogo, el ID será el que tenga la orden de compra, al igual que la descripción será idéntica a la orden de compra. Al momento de agregar un producto a la factura, es muy probable que se ocupe la información complementaria.... ta cabrón capturar tanto, pero bueno.

Con ello, la parte de MATERIAL de la addenda será cubierto. OJO... serepiten varios productos en la orden de compra (el mismo mismo), pero con distinto precio unitario, y digamos distinta información complementaria. 
Yo veo aquí una gran oportunidad para nosotros... si hacemos eficiente la addenda y el PDF, y le llega a pilgrims, capaz que nos empieza a recomendar.

Cuál es mi carta a los reyes:
a) Automatizar lo automatizable. Hacerlo compatible con lo que hoy tenemos, esto es, en la pantalla de captura de la addenda, se mostrarán precargados todos los datos que correspondan a las partidas en la addenda. Con eso evitamos doble captura, pero damos oportunidad al usuario de que modifique cualquier dato.
b) El otro punto que es importante, que surge de aquí pero es a nivel de usabilidad de la aplicación, es que una factura tan choncha, se pueda capturar 'en episodios', esto es que se pueda almacenar una prefactura, y posteriormente seguirla capturando o modificando.
c) otro aspecto, igual a nivel general, pero que surge de aquí... es que de un excel, jale toda la información de los productos en una factura; las columnas serían tal cual aparecen en el layout del conector. Para este cliente le daría mucha facilidad de generar su factura. Ver en un excel todos los datos y corregir si fuera necesario. Incluso puede ser un excel separado por comas, o como mas nos convenga.


COMO LA BEISBOL?... este issue es el punto (a), pero coméntame que onda con el b y c.

**Comment by jccastillo0007** [comment]
pues tanto b como c, están bien jalados jajajaja, ambos se podrían, pero debemos cobrarlo bien, ya que realmente sería un esfuerzo muy particular  para ellos, o para todos los clientes de Pilgrims, y eso lo digo porque desde que tenemos la addenda pilgrims, hasta ahorita surge esa necesidad y solo para un cliente, no me gustaría volver a trabajar en una funcionalidad que se supone podríamos revender, pero que casi nadie lo usa, como otro elefante blanco.

Si es para un cliente, tendríamos que cobrarlo bien, casi casi los puntos b y c serían unos 10k, si fueran varios con pedido levantado, podría no ser tan caro.

Por lo pronto trabajare en el punto a, mientras vemos el tema de viabilidad

**Comment by RigoFlores** [comment]
El punto (b) y (c) no son para este cliente, y nadie lo está pidiendo... (si le serviría a este cliente).... son para mejorar nuestra plataforma... clientes que tengan que incluir cientos de productos en una factura, se refiere a precisamente otro nicho de mercado...
Bueno, este cliente de la addenda, YA PAGÓ... tons sería importante implementar ASAP el punto (a)

**Comment by jccastillo0007** [comment]
Mmmmmm ok, no estoy seguro a cuantos clientes de los que aún no tenemos, podría servirles esta funcionalidad.... hay que ponerlo en el wish list, para hacerlo cuando no tengamos otros pendientes o cuando tengamos clientes interesados.

El a, queda para mañana probablemente.

**Comment by RigoFlores** [comment]
No sé a cuantos les sirva, pero si cada factura de esas, la vendes a unos 5k, creo que vale la pena el esfuerzo.
Me dijo que en pilgrims, vió una factura con 1,000 partidas... no maaaa!!!!
Yo ya le dije como se captura la factura y la addenda... la neta, yo no lo haría... es un chingo de información, son muchos los puntos donde te puedes equivocar... y le invertirás horas y horas... 
como te digo, importarlo de un texto o excel, sería lo adecuado...
Quizás debamos dejar que pase aceite, para ofrecerle la solución una vez que pilgrims se la regrese 2-3 veces... pero la neta, no está chida esa captura...

**Comment by jccastillo0007** [comment]
Ok, entonces voy implementar el inciso a), con esto, el super mega archivo xml de configuraci[on de addenda ya nos e va a necesitar, todo se va a tomar de los productos tal cual del xml

**Comment by RigoFlores** [comment]
ok, jalaría para el addendador?????

**Comment by RigoFlores** [comment]
porque seguramente terminaré haciéndola por el conector, .... al cliente no le quedará
ni a tí, ni a mí... si la hiciéramos manual

**Comment by jccastillo0007** [comment]
yeap, va a quedar por cualquier modo o forma, asi como con las putas.... jajajaja

Por cierto, este procedimiento, quedará implementado para todos los usuarios de la addenda pilgrims.

**Comment by RigoFlores** [comment]
Era para hoy... si el cliente la teclea manualmente, este beneficio ya no tiene mucho sentido...

En la addenda pilgrims, va un precio A NIVEL DETALLE... ese precio lo tomas de la información de producto a nivel CFDI estándar. Debe ser el precio unitario.... puedes confirmar... no sea que vaya a tomar el importe...

**Comment by jccastillo0007** [comment]
si, eso del precio ya lo habias especificado, y si, puede quedar hoy.

Ayer estuve subiendo las facturas de optibelt, crei que era mas urgente, ya que no me habias dicho para cuando era esto de pilgrims.

**Comment by RigoFlores** [comment]
ya le indiqué al cliente que primero genere la factura.
En un segundo paso le agregará la addenda pilgrims.
Esto es, ya comprometí el addendador, con el paso (a) cubierto. Insisto, este nuevo approach, debe ser compatible con el actual... es decir, al capturar la addenda mostrará los datos precargados en el número que corresponda según la factura, con la posibilidad de modificarlos.

**Comment by jccastillo0007** [comment]
Hhmmmmm hacerlo compatible es mucho mas costozo, lo que te comenté arriba
en los comentarios, es que este proceso reemplaza la funcionalidad anterior
para todos los usuarios de la addenda pilgrims, y de hecho, ya no se
ocuparía el super mega archivo de configuración.

Nosotros le vamos a agregar todos los datos, de acuerdo al mapeo que me
pasaste.

JC.

Saludos.
JC.

2017-02-21 16:54 GMT-06:00 RigoFlores <notifications@github.com>:

**Comment by RigoFlores** [comment]
OK, quizás hablamos de lo mismos pero diferente.
Hacerlo compatible, implica solo tomar los primeros datos de la captura... es decir los del jeder.
Y mostrar precargados los datos del detalle, de acuerdo a lo capturado en la factura....
Esto lo tienes tal cual en la addenda SANOFI, ISSUE Addendador SANOFI #674

**Comment by jccastillo0007** [comment]
Si, estamos ok.

Ya subí esta funcionalidad a PRU.

En la cuenta de la TIA, modifiqué el archivo xml de configuraci[on de la addenda, ya que solo se necesita un xml con los 4 datos iniciales.

Para poder probar, debes usar un rfc receptor de addenda pilgrims, como : SAP001026380, vi que ten[ias un mega archivo para cada RFC receptor de esta addenda, tuve que borrar el del RFC SAP001026380, para que tomara el que yo subí

**Comment by RigoFlores** [comment]
Espera, pero no que en pruebas solo se puede timbrar con el rfc ACO...???
Probé con ACO, cargué el xml enorme, y si me hizo la addenda en la factura timbrada, pero tuve que capturar todo a manopla.
Voy a ver que se hizo en la cuenta de la TIA...

**Comment by RigoFlores** [comment]
Correcto, no timbró con la cuenta de la tia... voy a cargar el XML de configuración de la addenda, con los datos del solo header.... y probar en ACO

**Comment by RigoFlores** [comment]
Ya probé en ACO, y no jaló... no sé como probaste, ya que en la cuenta de la tia no timbra... chiaaa
este fue el resultado, una addenda incompleta...
Pilgrims>
 .           <Proveedor>420155</Proveedor>
 .           <Proceso>01</Proceso>
/Pilgrims>

**Comment by jccastillo0007** [comment]
Probé con la cuenta de la TIA, con un XML ya timbrado previamente, ya que usé el addendador, que es el approach que me dijiste que usará ese cliente.

No trates de timbrar, o hazlo previamente con el rfc ACO... 

Con el addendador trata de agregar la addenda  únicamente, con el XML que solo trae los 4 datos del header.

**Comment by RigoFlores** [comment]
ok, deja revisar

**Comment by RigoFlores** [comment]
NOP, LA POSICIÓN LA INICIA CON 0, EN LUGAR DE 10 PARA EL PRIMER PRODUCTO.....

**Comment by jccastillo0007** [comment]
Ok, el resto esta bien ?

**Comment by RigoFlores** [comment]
no estoy seguro, ocupé el addendador con la cuenta ACO... y aparentemente no jaló
No sé porque pide el pedido para cada producto, si este se captura solo como header, aunque internamente se incluye para cada producto... pero lo pide una sola vez....

**Comment by jccastillo0007** [comment]
Hay dos opciones.

1. cuando le das el preview de los datos de la addenda, el pedido debe tener un valor default predefinido, para que tu lo veas en todos los productos
2. Si no tiene nada precargado, lo ver[as en blanco, pero si tu lo capturas en el header, de todos modos se lo va a aponer a todos los productos.

Probablemente, debemos quitar el pedido de los datos de los productos, cierto ?

**Comment by RigoFlores** [comment]
Si... digamos que el problema que encontré es:
a) no inicia con la posición 10; en su lugar inicia con la posición 0
b) el pedido no es algo que se deba capturar en cada partida, solo en el header
c) NO AGREGÓ LA ADDENDA AL XML YA TIMBRADO, DESDE EL ADDENDADOR... :(

ya ví, y si agrega la addenda... tomando el pedido que se captura en el header, ignorando el pedido a nivel producto (no debe aparecer a nivel producto)... pero solo si el pedido es numérico... yo en la mañana hice prueba con un alfanumérico y ahi si no la agrega... ya revisé la spec, y SI, EL PEDIDO DEBE SER NUMÉRICO... por ello no lo agregó en la primera prueba. SOLO QUEDAN LOS PUNTOS A Y B. 
Espero que no sea too late, ya que el cliente lleva 2 días capturando la factura y addenda... jeje

**Comment by jccastillo0007** [comment]
jajaja, esperate a que termine... y cuando te diga que ya esta que la revises, le dices, ya no es necesario, esta automatizada jajajaja

**Comment by jccastillo0007** [comment]
Listo, probado con el addendador, para generarla desde la pantalla de facturación, hay que hacer mas cambios para poder agregarlos datos de las partidas dinamicamente.
