### ISSUE TITLE
Nomina 1.2 - Conector - Si no incluye otros pagos, no procesa archivo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#915]
Si queremos procesar un archivo con el nodo de otros pagos vacio (o inexistente), no lo procesa.

**Comment by jccastillo0007** [comment]
Fixed.
Subí el release al dropbox 10.1.8

**Comment by RigoFlores** [comment]
OK, ya procesa cuando NO INCLUYE SUBSIDIO.
Lo que pasa ahora es que cuando SI INCLUYE SUBSIDIO (OTROS PAGOS), no lo envía al PDF.... chiaaaa

**Comment by jccastillo0007** [comment]
Antes si lo mandaba?

Por que yo solo agregué la validación de cuando no hay otros pagos... el resto sigue funcionando como antes.

Supongo que no se había probado, cierto ?

**Comment by RigoFlores** [comment]
Ya ví, antes tampoco lo enviaba.
Asumí que tenía el mismo comportamiento que en web... :(

**Comment by jccastillo0007** [comment]
Okas, ya lo agregué al final de las pecepciones, como en web.

Hay mucho código compartido entre standalone y web, lo más posible, pero no siempre los cambios aplican en ambas plataformas.
