### ISSUE TITLE
CxC - Optibelt, poner a punto el ambiente para validar la importación de data

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#916]
1) Facturas vivas. OJO, aquí no comprometimos el XML o PDF, sin embargo son los insumos para la BD
a) Eliminar facturas duplicadas en facturat
b) Subir información de 3 XML's generados por otro proveedor, donde ya les agregué el folio, ya que no lo tenía. Se alteró el XML, pero ellos lo tienen claro
2) Subir la información de Pagos, de acuerdo al excel enviado el día de hoy, 21 de febrero.
3) Enviar información en texto, de acuerdo a lo solicitado. La vez pasada me enviaste 2 archivos de texto, conteniendo la información de la cartera para todos los clientes: facturas, NC y pagos.

**Comment by jccastillo0007** [comment]
a) Eliminar facturas duplicadas en facturat. DONE
2) Subir la información de Pagos, de acuerdo al excel enviado el día de hoy, 21 de febrero.
DONE

Aún me falta el punto 1, como quiera te voy a enviarla info que esta ahorita en la base de datos, por si puedes ir revisando algo, si no, sería hasta ma;ana cuando ya quede todo listo

**Comment by jccastillo0007** [comment]
b) Agregar los 3 XML. DONE

3. Enviar archivos.... DONE por email.
