### ISSUE TITLE
CxP - Ligar el nuevo desarrollo a la plataforma de proveedores

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#918]
El cliente que nos contrató hace tiempo el módulo de CxP, se la estaba llevando con el menú de compras, pero ya es insuficiente.
Estuve revisando el avance actual de CxP, y me parece que está completo para operar con ese cliente.
Lo que si veo que falta, es que en la plataforma, cuando accedes como proveedor, no refleja el status de lo que se captura en el menú de CxP, ingresar cobro. En su lugar refleja un status que se cambia en el menú compras - consultas -edición. Aquí mismo, había que agregar la columna de referencia, para que el proveedor pueda buscar su pago.

Como ves, que consideraciones tenemos que tomar en cuenta para hacer este switch?

**Comment by jccastillo0007** [comment]
Deja veo las pantallas para reproducir lo que dices... tengo los estatus de CxC y CxP por separado, asi que no debe haber mucho impacto.

**Comment by RigoFlores** [comment]
En la pantalla de compras se manejan los siguientes status: 
![statuscfdi_compras](https://cloud.githubusercontent.com/assets/2912775/23317035/7d401198-fa92-11e6-87c2-5ad5a9751b6d.png)

**Comment by RigoFlores** [comment]
Y en la pantalla de CxP, se manejan los status Vigente, Pagada, Vencida.
En el portal de proveedores, ellos ven reflejado el status de compras y la fecha de pago correspondiente.
![portalproveedores](https://cloud.githubusercontent.com/assets/2912775/23317207/0b884db2-fa93-11e6-8256-50ad30e3b5c3.png)

**Comment by RigoFlores** [comment]
Pero en la pantalla de CxP, se maneja la siguiente info. Lo que se tiene que hacer es mapear los status de compras a CxP (éste último será el bueno), y reflejar toda la información de un pago, en el portal de proveedores.
![image](https://cloud.githubusercontent.com/assets/2912775/23317379/c8731a38-fa93-11e6-99e0-ef7abaaff20a.png)

**Comment by RigoFlores** [comment]
Ya me está presionando este cliente... 2 semanas que levanté este issue...
Que hacemos?

**Comment by jccastillo0007** [comment]
Ok, si entendí bien son dos cosas.

1. homologar los estatus disponibles en CxP, (tanto en compras como en CxP, como en el portal de proveedores) se deben mostrar los mismos estatus = DONE
2. En el portal de proveedores, hay que agregar una pantalla de consulta de pagos ? no estoy seguro si a eso te refieres cuando dices "reflejar toda la información de un pago, en el portal de proveedores."

**Comment by RigoFlores** [comment]
lo revisé en PRU, y no aparecen los mismos status.
Yo creo que los que debemos manejar en portal de proveedores, en CxP y en compras (éste último va a desaparecer, ya no tendría caso):
Vigente
Vencida
Pagada
Rechazada (cuando la factura no sea aceptada).

En cuanto a la información de la pantalla de proveeddores, le faltaría me parece lo de cargos y abonos. O igual y por lo pronto lo dejamos así, y vamos viendo

**Comment by jccastillo0007** [comment]
ok, lo dejamos asi y luego vemos que es lo que realmente se ocupa.

Los estatus si son los mismos, : 
registrada
en revision
programada para pago
rechazada
pagada
pago parcial

**Comment by jccastillo0007** [comment]
Esos son los datos que anteriormente habiamos acordado,

**Comment by RigoFlores** [comment]
ok, cuando ingreses un pago... cómo vas a saber cuál status colocarle???

en que momento pasa de registrada... a en revisión, programada para pago, rechazada????

Cuando el cliente quiera conocer a quién le debe, con base a los días de crédito que le otorgan, no podrá conocer dicho status... ya que no aparece como vigente o vencida... según yo, solo se ocupa:

Vigente  (cuando se recibe y no ha pasado el tiempo del crédito)
Vencida  (ya rebasó el tiempo días de crédito otorgado por el proveedor y no se HA PAGADO TOTALMENTE)
Pagada  (se ha liquidado al 100% )
Rechazada (cuando la factura no sea aceptada).

**Comment by jccastillo0007** [comment]
Ok, done.

**Comment by RigoFlores** [comment]
hice un pago a un proveedor... desde CxP, y lo pasó a status pagada... luego entré con ese proveedor, y en consulta no muestra el status.

**Comment by jccastillo0007** [comment]
ok, ese detalle ya lo corregí, pero no estoy seguro que sea consistente CxP con todos los cambios que hemos hecho con CxC hay que probarlo muy bien

**Comment by RigoFlores** [comment]
CxP, NO ES CONSISTENTE CON CxC... es un hecho.
Primero quería levantar este issue, para homologar los status... y luego voy a levantar detalle a detalle... ya ví varios issues cuando hice unas ligeras pruebas... pero dont worry, los levanto

**Comment by RigoFlores** [comment]
Creo que no nos entendemos. Si accedo como emisor, y realizo un pago a un proveedor, pone la factura a pagada.
Si con la cuenta de ese proveedor, accedo a la plataforma de proveedor, el status es registrada.
Aquí la evidencia..


![desdecxp](https://cloud.githubusercontent.com/assets/2912775/24383371/c95d3994-1319-11e7-8541-e15e66eb61d4.PNG)


![desdeplataformaproveedor](https://cloud.githubusercontent.com/assets/2912775/24383375/cf56f7cc-1319-11e7-8c0f-80500e7f884f.PNG)

**Comment by RigoFlores** [comment]
Seguimos con este problema... ya viene el CFDI 3.3 y tenemos arrastrando muchos issues

**Comment by jccastillo0007** [comment]
ok, de hecho ya estoy empezando con CFDI 3.3 ,

**Comment by jccastillo0007** [comment]
done.
