### ISSUE TITLE
CxC - optibelt - no se despliegan algunas facturas del excel 

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#919]
No se despliegan los siguientes pagos (no cliente, rfc, folio, status, etc son las columnas):

209200	MYC081121NC7	121001780	PAGADA	08/02/2016	10315		-$1,080.08			PA
612400	FECA870303MY2	161045473	PAGADA	06/01/2017	163001844, 1856, 1888		-$892.83	 
PA

**Comment by jccastillo0007** [comment]
fixed.

Esos pagos, corresponden a las 3 facturas que subí apartir del XML, y a dichos registros faltaba asignarles correctametne el tracking id.

**Comment by RigoFlores** [comment]
pero son solo 2 que no se veían...
El segundo SIGUE SIN APARECER...
612400	FECA870303MY2	161045473	PAGADA	06/01/2017	163001844, 1856, 1888	-$892.83
PA

**Comment by jccastillo0007** [comment]
Ese segundo no aparece, porque no existe una factura con el folio 161045473, ni en el excel ni en la base de gatos.

chiaaaa

**Comment by RigoFlores** [comment]
SI, EN EL EXCEL SI EXISTE... PERO NADA, YA TE LO ENVIÉ POR CORREO, FAVOR DE SUBIRLA Y COMPLETAR SUS PAGOS...

**Comment by RigoFlores** [comment]
No tiene rfc receptor asociado, la factura que se subió a partir del vivitas.txt

Tenemos que tener muy claro el asunto de subir las facturas... a partir de la BD o a partir de los XML, ya que en este caso quedó inconsistente la información.

**Comment by jccastillo0007** [comment]
chiaaaa, eso pasa por mandar todo por partes, 

Fixed.

**Comment by RigoFlores** [comment]
para producción, tenemos solamente vivas + vivitas...
