### ISSUE TITLE
Enviar los datos del xml donatarias, como datos extra al PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#92]
Se enviarán en el mismo orden que aparecen en el XML.
Ojo, no el orden de la pantalla, ya que esa desaparecerá eventualmente

**Comment by jccastillo0007** [comment]
Para no basarnos en la pantalla, lo planteo de otra forma.

No se pueden enviar en el orden del xml, eso es mas costoso, se mandan en el orden que se cargan en el xml de la addenda..... si ahi los pones en el orden del XML entonces obtienes lo que estas pidiendo.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Traté de validar la solución en pruebas, con usuario demo (que cuenta con el plugin donatarias), y no me está tomando la nueva plantilla que le envié con los datos extras, en lugar de la leyenda fija.
Cómo puedo validar esta corrección en pru????
