### ISSUE TITLE
CxC . Optibelt datos incompletos en cartera de clientes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#920]
![error en cartera de clientes](https://cloud.githubusercontent.com/assets/2912775/23285400/ab62df0c-f9f6-11e6-8920-31f9c98dcc02.png)
No despliega la referencia de la factura, aunque en el texto que me pasaste como vaciado de la BD, si aparece.
En los pagos no aparece el folio... es importante para relacionarlo visualmente.

**Comment by jccastillo0007** [comment]
fixed.
