### ISSUE TITLE
CxC - Optibelt - no aparece la factura 161043217 en ft pero si en el excel

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#921]

**Comment by jccastillo0007** [comment]
No tan extraño cuando el error viene de la base de datos de standalone jojojojo

Ahi no viene.

**Comment by RigoFlores** [comment]
OK, ES DE 2017 Y ESAS NO LAS TRAJIMOS DE ACUERDO A LO PLATICADO CON ELLOS..
