### ISSUE TITLE
CxC Optibelt factura 161036859 con receptor incorrecto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#922]
Error muy extraño, necesitamos saber de donde se originó

**Comment by jccastillo0007** [comment]
No tan extraño cuando el error viene de la base de datos de standalone jojojojo

Te mande correo con la evidencia.

**Comment by RigoFlores** [comment]
ok, mañana lo reviso con ellos... es el excel, porque la BD origen yo mismo la tomé de su computadora
