### ISSUE TITLE
Optibelt - Número de cliente incorrecto para varias facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#923]
Envié por correo el excel

Existen muuuchos registros en facturat, con el número de cliente chueco. Eso lo puedes revisar en la pestaña “FA Y NC ORIGINALES” del Excel anexo y filtrando los valores 0 en la columna M. Todos esas facturas tienen el número de cliente chueco. No sé si el problema va mas allá, y los números de cliente en web (y escritorio), hay que revisarlos. Recuerdas como se puso el número de cliente en el web???

**Comment by jccastillo0007** [comment]
listo, ya lo arreglé.
