### ISSUE TITLE
CxC Optibelt - algunas referencias están 'medio chuecas'

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#924]
![extradata chueco](https://cloud.githubusercontent.com/assets/2912775/23291131/a15d13cc-fa1b-11e6-95c2-d936eb1aa3d8.PNG)

**Comment by RigoFlores** [comment]
se leen raros los acentos o algunos caracteres extraños

**Comment by jccastillo0007** [comment]
Ok, pues busqué los acentos, y solo encontré en el ó y ya lo cambie,... tampoco hay ñ , asi que ya debemos estar listos.
