### ISSUE TITLE
Nomina 1.2 por conector, el elemento EntidadSNCF no debe existir para producción.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#925]
Apuntamos el conector a producción  y marcó el error:

NOM166 - Si el RFC del emisor no existe en el listado de RFC inscritos no cancelados en el SAT (l_RFC) o no tiene marca de unidad adherida al Sistema Nacional de CoordinaciónFiscal, el elemento EntidadSNCF no debe existir

**Comment by jccastillo0007** [comment]
ya vi, como es conector tons es en standalone.
Puedes probar con otra versión ?

**Comment by jccastillo0007** [comment]
ya subí, una versión que no trae eso.
