### ISSUE TITLE
Ingresar Cobro - Optibelt (no asigna correctamente la referencia)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#926]
Cuando se hizo el cambio para ingresar cobro con NC, se movió lo de la referencia. Ahora siempre asigna el folio de la factura en cuestión.
Lo que finalmente se capture en pantalla, para la referencia, deberá asociarse a todos los pagos.
Para el caso de pago con una NC, se sugerirá el folio de la NC, pero si ellos la cambian, se deberá tomar lo que se capture en referencia.
Para el caso de pago de varias NC, entonces la referencia  deberán capturarla ellos.

**Comment by jccastillo0007** [comment]
fixed.
