### ISSUE TITLE
CxC - Ingresar Cobro - no acepta modificar el monto del pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#927]
Lo que le llaman pago parcial.
El pago sugerido es por el total de la factura. Si el usuario modifica dicho monto, deberá tomarlo como dato del pago. Pero no, aparentemente mantiene en memoria el dato originalmente sugerido, y por ello no se pueden hacer pagos parciales a facturas.

Si ingreso 15,000 de pago... elijo 5 facturas... me sobran 500 pesos... a la 6a factura le ingreso cantidad a pagar 500, para cuadrar el pago... no lo acepta. Esto realmente impacta que NO SE PUEDEN HACER PAGOS SIMULTÁNEOS A VARIAS FACTURAS... por el hecho que no acepta esa modificación en la cantidad.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
ahora ya lo acepta, pero es muy común que marque el -0 como saldo disponible, y no permite avanzar-
O redondeamos las cantidades a 2 decimales... o mostramos la cantidad a capturar completa...
Esto surge a partir de donde? Ellos envían los totales en el archivo, según recuerdo... entonces porque se generan cantidades a 4 o 6 decimales?
