### ISSUE TITLE
CxX-Ingresar cobro - seleccionar/deseleccionar facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#928]
Cuando estoy en la pantalla de cobro, si capturo la cantidad a cobrar, la referencia, el cliente... y consulto, me despliega las facturas.
Yo elijo cualquiera de ellas, pero me equivoqué... simplemente la deselecciono... y nada, ya le sumó a la cantidad que se va a pagar...
NO ACEPTA SELECCIONAR Y DESELECCIONAR UNA FACTURA... YA QUE HACE COSAS RARAS CON LAS CANTIDADES A PAGAR...

**Comment by jccastillo0007** [comment]
fixed.
