### ISSUE TITLE
CxC - Consulta de cobros - marca internal error

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#929]
Para poder ingresar un cobro... la ÚNICA MANERA QUE EXISTE es que la cantidad a pagar coincida exactamente con la(s) factura(s) elegida(s). Hice esta prueba, lo aceptó.
Si quiero consultar cobros por referencia, después de haber ingresado este pago, marca internal error.

**Comment by jccastillo0007** [comment]
fixed. a veces marca un error con -0, pero en  realidad es por los centavos... tal vez debo mostrar las cantidades 4 decimales, cómo ves?

**Comment by RigoFlores** [comment]
Es muy común este escenario, el del -0, pero este issue se refiere al internal error al momento de consultar por referencia.
Están relacionados o mezclaste issues?
El issue del -0, se está dando seguimiento en un issue distinto a este.

Aqui lo que me gustaría conocer es porque se daba este error del internal error, y como fue corregido

**Comment by RigoFlores** [comment]
Ya revisando el reporte, que debe llamarse POR REFERENCIA (así fue solicitado), no está presentando toda la información. El siguiente es un ejemplo de un reporte de cartera por cliente y otro de cobros por referencia:
![carteracliente_cso680801p93](https://cloud.githubusercontent.com/assets/2912775/23367378/a985664c-fccf-11e6-916a-145a14dd1c63.PNG)


![consultaxreferencia_cso680801p93](https://cloud.githubusercontent.com/assets/2912775/23367390/b3c64536-fccf-11e6-9428-4f8fcf1148ed.PNG)

**Comment by RigoFlores** [comment]
La referencia fue TEST11. El reporte de cartera por cliente, SI MUESTRA TODA LA INFORMACIÓN DE LA REFERENCIA. 
El reporte por referencia, únicamente muestra las facturas... pero realmente lo que se busca es los montos del cobro, y a cuáles facturas. Digamos que es un extracto del reporte de cartera por cliente. 
La diferencia es que en el reporte por referencia, NO INCLUYES LOS FILTROS DE CLIENTE, NI FOLIOS, NI NADA... ÚNICAMENTE LA REFERENCIA. 
En conclusión, al reporte por referencia, le están faltando los cobros realizados con la referencia ingresada. Hoy en día solo muestra las facturas pagadas.

**Comment by RigoFlores** [comment]
Favor de chequear el correo que estaré enviando...
