### ISSUE TITLE
No siempre presenta los botones de addenda, vista previa, facturar y limpiar en pantalla de factura

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#93]
Aparentemente, después del primer acceso a la pantalla de facturas, ya no presenta los botones mencionados. Si está habilitada la función, pero no carga los botones.
Parece que los presenta alternadamente, dependiendo de los accesos a esa pantalla

**Comment by jccastillo0007** [comment]
Parece ser un issue de IE y solo depende de como este configurado

**Comment by RigoFlores** [comment]
Lo mantendremos en observación y cualquier cosa, lo reportamos
