### ISSUE TITLE
CXC - INGRESAR COBRO - NO INDICA QUE NO ACEPTA LA MISMA REFERENCIA

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#930]
Cuando vas a ingresar un cobro, pero capturas la misma referencia capturada en otro cobro... y le das guardar, no lo almacena... lo cual es correcto, pero no envía mensaje que la referencia ya ha sido capturada anteriormente, con lo que el usuario no sabe que hacer o porque no guardó.

Se requiere enviar mensaje a pantalla indicando que la referencia está ya registrada

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
LA LEYENDA DEBE INDICAR:
"No se permite duplicar REFERENCIA utilizada en otros cobros"
