### ISSUE TITLE
CXC - COBRO HÍBRIDO - LAS NC APARECEN COMO PAGADAS, CON ABONO.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#931]
CUANDO SE REALIZA UN COBRO HIBRIDO, ES DECIR CON CASH + NOTA DE CRÉDITO....
LA FACTURA PAGADA APARECE COMO LIQUIDADA, PERO LA NC TAMBIÉN APARECE COMO PAGADA.... 

QUIZÁS NO ESTÁ TAN MAL (HOY NO LO SÉ), PERO EN EL CASO DE NOTA DE CRÉDITO, NO SE DEBERÍA HACER CARGO YA QUE NO CUADRAN LAS CANTIDADES.
ESTRICTAMENTE HABLANDO, LA NC SIMPLEMENTE APARECE COMO APLICADA (O PAGADA), PERO ENTONCES EL ABONO A LA FACTURA TENDRÍA QUE SER LA DIFERENCIA, ENTRE EL TOTAL DE LA FACTURA - NOTA DE CRÉDITO.
SE LOS TENGO QUE PRESENTAR PARA QUE VEAN LA PROBLEMÁTICA Y ME INDIQUEN COMO PROCEDER. NO ESTÁ SIMPLE LA DEFINICIÓN QUE PIDIERON.

![cobro hibrido](https://cloud.githubusercontent.com/assets/2912775/23345322/dd569e1a-fc51-11e6-996d-b00ef6c50e2d.PNG)

**Comment by jccastillo0007** [comment]
Yo creo que aqui ya te confundiste.... o no entendi nada... tal vez el estatus deba decir Aplicada o algo asi, pero eso asi ya estaba atnes y no te dijeron ellos nada...

**Comment by RigoFlores** [comment]
No dijeron nada, porque no pudimos capturar ningún pago por la problemática que se corrigió (que no permitía modificar el monto a pagar).
Cuando una factura es liquidada, el monto de la misma (cargo), se mata con un abono (en PA, NC o HI).
Entonces, si vamos a mostrar que una NC ya fue pagada o aplicada, entonces el monto de la NC (saldo a favor del cliente) que se muestra en la columna de abono, tendría que matarse con un registro, así como se muestra ahora mismo, pero en la columna de cargo. 

Checa el correo que te enviaré en unos momentos.

**Comment by RigoFlores** [comment]
esto aplica para cobros con solo NC, es decir no solamente para híbridos.

**Comment by jccastillo0007** [comment]
al parecer ya quedo, encontré el patron adecuado, para saber cuando mostrar la NC y además los Pagos realizados, sin que se dupliquen.

**Comment by RigoFlores** [comment]
ahora lo que hace, es que muestra la NC con el abono original (como fue emitida), pero no muestra nada que la mate:
a) o debe mostrar un pago (abono) con la cantidad idéntica en negativo
b) debe mostrar un cargo a la NC... si eso se contradice con algo, entonces el punto a está OK

El cliente levantó este issue también

**Comment by jccastillo0007** [comment]
es que a una NC no se le mata con un pago, porque la NC es un pago o una acreditación a la deuda, lo que mata una NC es el saldo deudor de ese cliente, es decir el saldo de las facturas.

Mandame un ejemplo como el que enviaste por whatsapp, que yo pueda de alguna manera reproducir, para asegurar que llegamos a un saldo 0 después de un pago híbrido entre cash y NC

**Comment by RigoFlores** [comment]
Es simple... pago 1000 en cash y 500 en NC... total 1,500
Las facturas involucradas tienen pagos por 1,500 pesos en total... (abonos entre cash + NC)..

Peeeeero, además está el abono de la NC original... entonces en lugar que todo cuadre a 0, queda un saldo a favor del cliente por 500 pesos... en este ejemplo... por que el abono de la NC original, no se 'mató'...

**Comment by jccastillo0007** [comment]
Aqui es donde esta el detalle : "Peeeeero, además está el abono de la NC original... " eso no lo debes ver asi, mas bien ese saldo de 500 de la NC, se suma a los 1000 para completar los 1500.

**Comment by jccastillo0007** [comment]
listo, ya subi el release que muestra lo que acordamos por skype.

**Comment by RigoFlores** [comment]
tenemos que verlo en conjunto, ya que sigue algo raro... lo voy a cerrar para que una vez que platiquemos, lo revisemos
