### ISSUE TITLE
CxC-Ingresar cobro - muestra -0 muy comúnmente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#932]
Aunque captures la cantidad que se muestra en "Saldo disponible para pago de CFDi's: ", te marca muy comunmente -0.
a) o se redondea a 2 decimales
b) o se muestra la cantidad exacta restante (con los decimales que se requiera)
c) cuando el monto de la última factura seleccionada sea mayor al saldo disponible, entonces SUGERIR EL PAGO PARA CERRAR A CERO.

Cómo quedará este asunto?

**Comment by jccastillo0007** [comment]
al parecer ya quedo, hice un par de pruebas con combinaciones raras, y no lo pude reproducir.
