### ISSUE TITLE
CxC-Ingresar cobro en múltiples pantallas - se pierde la selección de las pantallas previas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#934]
Cuando se ingresan cobros, correspondientes a mas de 1 pantalla... eliges las NC y/o FA de la primera pantalla, enseguida te pasas a la 2a pantalla y haces lo mismo, es decir, eliges la NC y FA que deseas aplicar.
Si regresas a la primera pantalla, YA NO APARECEN seleccionadas las facturas iniciales, pero las cantidades se mantienen.

El issue, es que debe mostrar cuáles son las FA y NC seleccionadas en cada pantalla, cuando el ingreso de cobro, involucre mas de 1 pantalla... pueden ser 2 o mas....

**Comment by jccastillo0007** [comment]
ok, dejamos esto para cuando el resto ya este bien...

**Comment by RigoFlores** [comment]
no muy después, necesitamos cerrar esto para pasar a otras cosas que ya urgen...

**Comment by RigoFlores** [comment]
ya valió madres, quién sabe cuántos pagos han ingresado bajo esta condición y no está jalando.
Me lo acaban de reportar hoy, pero no es la primera vez que ocurre; me comentó que anteriormente no había revisando el pago completo.
Necesitamos atender fichas que si se levantan, es porque se requiere resolverlas...
No tengo idea de cuántos pagos se han visto impactados en optibelt por este issues que 'se dejó para después'...

Un paliativo chafa, pero que entiendo que jala, es mostrar hasta 200 facturas por página... recuerda que ellos emiten muchísimas facturas

**Comment by jccastillo0007** [comment]
Ya se están mostrando 200 items en la consulta hecha para ingresar pagos.
