### ISSUE TITLE
AGREGAR NUEVO RFC EMISOR EN ADDENDA LIVERPOOL SAMM6701196C8

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#935]
OJO, ES RFC EMISOR... ES DECIR NUESTRO CLIENTE...
EN UN MOMENTO MAS ME INDICARÁ SI SE OCUPA AGREGAR OTRO RECEPTOR YA PROPIAMENTE DE LA ADDENDA.

ESTÁ MUY CHAFA QUE EN CÓDIGO ESTÉN LOS RFC'S DE LOS EMISORES... TODAVÍA LOS RECEPTORES BUENO, PERO NUESTROS CLIENTES???? CHIAAAA

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
chiaaaaaaaa
