### ISSUE TITLE
Error al timbrar nómina por conector para asimilados - detenida la nómina del cliente

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#939]
Tipo de comprobante es NOMINA, pero no se cuenta con la información necesaria para generar el complemento

ES QUE SI MANDAS ASIMILADOS A SALARIOS EN EL ARCHIVO DE TEXTO, NO DEBE INCLUIR EL REGISTRO PATRONAL, Y AHÍ ES DONDE ESTÁ TRONANDO…

SI LO INCLUYES MARCA ERROR PARA ASMILADOS, YA QUE NO LO DEBE LLEVAR (SEGÚN YO DEL SAT)….
SI NO LO INCLUYES MANDA EL ERROR DE ARRIBA AL LOG… (SEGÚN YO MENSAJE DE ERROR DE FACTURAT)

YO CREO QUE TENDRÍAMOS QUE SABER SI ES ASMILADOS, CUÁLES DATOS TOMAR Y CUÁLES IGNORAR, QUE NO???

**Comment by jccastillo0007** [comment]
fixed, version 10.1.8.1
