### ISSUE TITLE
Implementar Complemento Comercio Exterior - Fase I

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#940]
La fase I, son las adecuaciones que se tienen que implementar a nivel CFDI Estándar.
Ya las levanté en un archivo de word, en el dropbox, carpeta de proyectos, comercio exterior.
Tenemos que hacerlo en Web para algunos clientes... y por conector (para un par de clientes, con 5 RFC's y 25-30k folios de consumo anual).
Ya lo están esperando desde el 01 de marzo.

**Comment by jccastillo0007** [comment]
Este issue esta muy genérico, yo creo que hay que cerrar este, y dar seguimiento con los otros issues que has levantado.

**Comment by RigoFlores** [comment]
si, era para empezar con el word, desde el fin de semana pasado, pero creo que no resultó...jeje
