### ISSUE TITLE
Complemento Comercio Exterior 1.1 (CCE11) - Cambios CFDI estándar - Tipo de Cambio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#943]
Estos cambios se estarán implementando para CCE11, pero buscando que sean compatibles con la v 3.3, incluso con la versión 3.2 del CFDI, y así le vamos avanzando en ambos caminos de manera paralela.

Respecto al tipo de cambio: 

El tipo de cambio debe soportar hasta 6 decimales.

**Comment by RigoFlores** [comment]
Es posible manejar el tipo de cambio, de acuerdo a lo que se capture exactamente?
1
1.0
1.1234
1.123456

Es decir manejar los decimales de acuerdo a lo que se capture en pantalla???

**Comment by jccastillo0007** [comment]
para soportar eso, el tipo de cambio debería ser tipo texto, y convertirlo a double para hacer operaciones, pero si perder el texto que ingresaron originalmente... esta delicado poder hacer eso, tendría que revisar el impacto en toda la app.

**Comment by RigoFlores** [comment]
OK, entonces manejemos todo a 6 decimales... eso si se puede?

**Comment by jccastillo0007** [comment]
si, pero sería el tipo de cambio a 6 decimales para todos los clientes, para cualquier tipo de documento, esta bien?

**Comment by RigoFlores** [comment]
Pues entonces hagámoslo así (tc a 6 decimales para todo cfdi)... nuestro respaldo son los documentos del SAT
