### ISSUE TITLE
CCE11 - CFDIE - Lugar de Expedición

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#944]
Debe reportarse el CP del LUGAR DE EXPEDICIÓN (es decir de la matriz o sucursal donde se emita el CFDI) , y debe estar contenido en el catálogo correspondiente.

(Aquí lo que se hace, es que lo capture; si no está dentro del catálogo, el PAC regresará un error) De hecho esto ya ha pasado.
La otra es efectivamente manejar el catálogo de CP, que como quiera lo manejaremos para el domicilio del receptor.

**Comment by jccastillo0007** [comment]
Done.

Ojo... aún no implementó el catálogo, pero puedes probar que el lugar de expedición se cambia por el código postal.
