### ISSUE TITLE
CCE11 - identificar el CFDI cuando se requiera incorporar el CCE

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#946]
Lo que platicamos ayer, se le agregaron 2 opciones (chuecas por cierto), y está faltando una.

Si el camino será ese, se debe homologar:
Ingreso - Comercio Exterior
Egreso - Comercio Exterior
Traslado - Comercio Exterior

Si por otro lado, la idea no es agregar ningún comprobante, algo chaca sería elegir:
a) Factura   (para ingreso)
b) Nota de Crédito   (para egreso)
c) Carta Porte - Traslado

y colocar un checkbox, para que se indique que llevará el CCE. Eso le daría el comportamiento correspondiente. Son las 2 opciones que veo.

La mas complicada, es generar una pantalla aparte para CCE11

**Comment by RigoFlores** [comment]
cómo quedó finalmente?
Veo un checkbox donde le indicas el complemento, y también veo 2 nuevos tipos, egreso y traslado.
Entonces el ingreso será con la factura, o se agregará el ingreso?

**Comment by jccastillo0007** [comment]
Ingeso será con la factura
Egreso y Traslado pasan tal cual de forma natural

En cualquier caso deben seleccionar el checkbox de CCE, de lo contrario no se asume nada.
