### ISSUE TITLE
CCE11 - Captura de datos de domicilio fiscal

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#948]
A partir del CCE11, y seguramente en adelante para otros CFDI's, cambia la manera de capturar los domicilios. Aquí se plantea para el emisor, expedidoEn y receptor.

Se deben involucrar los catálogos del SAT. Entiendo que debemos almacenarlos solo una vez, y que la pantalla correspondiente lo consulte.
Son 2 procesos independientes:

Primero: SE CAPTURA PAÍS Y DE AHÍ, ESTADO. CON EL ESTADO EL MUNICIPIO Y LOCALIDAD.

Segundo: SE CAPTURA EL CP, Y DE AHÍ LA COLONIA.

Para los datos arriba mencionados, SE DEBERÁ ENVIAR LA CLAVE EN EL CATÁLOGO AL XML.
Al PDF, se enviará la descripción.

Referencia, Calle, número exterior e interior, son de libre captura.

Para el emisor el país es "MEX"

**Comment by jccastillo0007** [comment]
ya se tienen cargados los catálogos de pais y estados.
este es el task mas tardado de  toda el CCE.

**Comment by jccastillo0007** [comment]
Ya están todos los catálogos cargados y funcionando en el catálogo de clientes.

**Comment by RigoFlores** [comment]
Lo que hace falta, es que no borre los datos de RFC, nombre, curp, calle, no exterior, no interior... cuando se selecciona alguno de los datos de los catálogos

**Comment by jccastillo0007** [comment]
listo.
