### ISSUE TITLE
Dar de alta usuario admin en ambiente de pruebas.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#95]
RFC: XAXX010101000 ó XEXX010101000
Nombre: Su Empresa o Persona Física, SA de CV
Domicilio: Universidad Pte. # 551-22 Col. Lomas de San Antonio
Municipio: El Marqués
Estado: Querétaro
País: México
CP: 76000
correo: contacto@factura-t.com.mx

Usuario: admin
pwd: facturat
Plugin: Factura estándar
Folios asignados: 2,000

Este usuario, lo utilizaremos en nuestras campañas publicitarias del sistema en web, como demo del mismo.
Será posible programar, como alguna vez comentamos, que diariamente se borre la BD, excepto la configuración?

**Comment by jccastillo0007** [comment]
Done..

el usuario lo puse como guest y no admin,,,,, asi se maneja siempre que son pruebas de usuario..... el admin sugiere otro tipo de funcionalidad...

**Comment by RigoFlores** [comment]
Favor de poner toda la información en minúsculas, porque los clientes luego son muy mamilas al respecto.
Ahora mismo, el domicilio fiscal del emisor aparece en mayúsculas y minúsculas, se ve chueco.
Precisamente por ello, notifiqué tooooodos los datos con punto y coma, pero creo que no aclaré...:(

**Comment by jccastillo0007** [comment]
Done..

JC.

**Comment by RigoFlores** [comment]
Favor de colocar la dirección, tal cual está definida. 
De aquí se desprenderán todas las plantillas demo, y varios temas similares. 
Por ello es importante que cumpla tal cual está definido, con maýúsculas y minúsculas:

Nombre: Su Empresa o Persona Física, SA de CV
Calle: Universidad Pte.
No ext: 551
No int: 22 
Colonia: Lomas de San Antonio
Municipio: El Marqués
Estado: Querétaro
País: México
CP: 76000
correo: contacto@factura-t.com.mx

**Comment by jccastillo0007** [comment]
Pues no me pediste que todo en minusculas?

JC@iPhone.
 Saludos.

**Comment by RigoFlores** [comment]
Pues como que no está muy claro, pero realmente si menciona que es en mayúsculas y minúsculas, tal cual aparece arriba

**Comment by jccastillo0007** [comment]
mmm ok,,, es que cuando lei esto :  
"Favor de poner toda la información en minúsculas, porque los clientes luego son muy mamilas al respecto."

Me confundi, entendi que era todo en minúsculas.
