### ISSUE TITLE
Implementar Complemento de Comercio Exterior v 1.1 (CCE11)

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#951]
Aquí la SPEC:

http://www.sat.gob.mx/sitio_internet/cfd/ComercioExterior11/ComercioExterior11.xsd

**Comment by jccastillo0007** [comment]
Subi a PRU los avances que tengo, ya están todos los catálogos e incluso el código para generar el complemento con las claves del domicilio fiscal del emisor y receptor, pero aún no esta generando la addenda como tal en el xml.
Me falta también la pantalla customizada para capturar los datos propios del CCE, voy a usar la clasica pantalla de datos extras, pero customizada para los datos de CCE.

**Comment by RigoFlores** [comment]
los pendientes están documentados de manera específica
