### ISSUE TITLE
CxC - Ingresar cobro, validar que se capturen datos obligatorios al momento de salvar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#953]
Monto, fecha y referencia.

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
esto ya está en pro???... en pru ya vi que si quedó

**Comment by jccastillo0007** [comment]
Negativo, solo lo subi a PRO

**Comment by RigoFlores** [comment]
pues aquí según yo estoy en pru...
![referenciainvalida](https://cloud.githubusercontent.com/assets/2912775/23760297/d968da0a-04b4-11e7-9822-7d8a068885b6.PNG)

**Comment by jccastillo0007** [comment]
Perdon, quise decir que solo lo subí a PRU.
