### ISSUE TITLE
CxC - Considerar ÚNICAMENTE facturas vigentes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#954]
Las facturas emitidas canceladas por nuestros clientes, no tiene ningún sentido que aparezcan en CxC.

**Comment by RigoFlores** [comment]
En el caso de optibelt, ellos han generado cualquier cantidad de facturas duplicadas.
Bueno, si las cancelan desde el portal, simplemente ya no se tomarían en cuenta en CxC, dejando que dependan de nosotros para borrar dichas facturas.
Por otro lado, el otro cliente usuario de CxC, tiene cualquier cantidad de facturas canceladas y no deben incluirse en las CxC.
Urge.

**Comment by jccastillo0007** [comment]
ok, ya no se muestran las facturas canceladas.
