### ISSUE TITLE
CxC - Ingresar cobro - aún con saldo cero aparece como factura por pagar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#955]
En el menú ingresar cobro, solo aparecen facturas que no HAN SIDO PAGADAS TOTALMENTE.
Pero te envié por correo, un ejemplo donde el saldo es cero, y aparece como vigente, esto es no está cerrada (pagada).
Este issue ya nos ha quitado mucho tiempo (desde el famoso -0). Necesitamos solucionarlo de una vez por todas. Para mí el asunto es redondear...  por ejemplo:

1.02**5**934 pasa a ser 1.03    (se redondea)
1.18**4**9999 pasa a ser 1.18   (se trunca)

si el tercer decimal es mayor a 5, entoces se redendea toda la cifra
es decir tomar el tercer decimal, si es menor a 5 entonces se trunca a 2 decimales, la cantidad

**Comment by jccastillo0007** [comment]
Agregué un par de validaciones, para no contemplar la cantidad 0.001 o -0.001 como un saldo restante, si vuelve a suceder mandame los datos con los que pueda revisar ese caso en particular.

**Comment by jccastillo0007** [comment]
Por cierto, estas validaciones las agregué al momento de guardar los pagos, con el objetivo de que no se queden facturas vigentes o vencidas que ya fueron pagadas, pero si consultan cartera de clietnes es posible que aún los vean, no puedo meterlo en consultas, porque sería un overhead que puede tirar la base de datos.

**Comment by RigoFlores** [comment]
Sigue algo mal... HOY LE ACABO DE ENTREGAR A OTRO CLIENTE, EARA610906PV9, y resulta que hicimos algunos pagos y te aparece lo siguiente:
![vigentessaldocero](https://cloud.githubusercontent.com/assets/2912775/23863889/906a959e-07d6-11e7-92d9-41afb5afb46f.PNG)

**Comment by RigoFlores** [comment]
Si te das cuenta, aparece como Vigente con saldo cero. Es decir no lo está tomando aún... la solución de los nanofracciones de peso, debe ser resuelto de una vez por todas.
Este cliente, es el primero que pagó por la plataforma, y apenas le estamos entregando lo de CxC.

**Comment by jccastillo0007** [comment]
Estos movimientos que ingresaron como pagos, fueron hoy?

**Comment by RigoFlores** [comment]
afirmativo

**Comment by jccastillo0007** [comment]
Fixed.
