### ISSUE TITLE
CxC-En cartera general muestra una cantidad que no corresponde a facturas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#956]
Aparentemente es información de pedidos, pero no sé cómo llega a ese monto. Ese RFC solo tiene levantados pedidos, pero no facturas (de hecho es un proveedor, jeje).
CxC, solo debe considerar facturas, pero no cotizaciones, remisiones o pedidos.
Si gustas revisar es el cliente  EARA620117GT8, con el usuario ana.estrada

![errorcarterageneral](https://cloud.githubusercontent.com/assets/2912775/23865737/40f476f0-07dc-11e7-85df-ed643624dba2.PNG)

**Comment by jccastillo0007** [comment]
pues ya estuve revisando y si esta aplicando bien el filtro, ya no contempla pedidos ni cotizaciones ni remisiones ni otro cosa que no sea factura o nc.

**Comment by RigoFlores** [comment]
aquí tienes otro ejemplo... el primer registro, no es ni cliente ni proveedor... jeje.. pero ahí aparece...
![errorcarterageneral2](https://cloud.githubusercontent.com/assets/2912775/23933483/6ec8cda0-0904-11e7-930c-a9a843a27fe3.PNG)

**Comment by jccastillo0007** [comment]
si aparece, es porque debe ser su cliente, checa sus clientes para ver si tienen a Maria..

**Comment by jccastillo0007** [comment]
Chiaaaa

mysql> select financialDetails_id, CxCStatus, sourceRFC, targetRFC, targetName, clientNumber, invoiceName, folioSAT from CFD where sourceRFC like 'EARA620117GT8%' and invoiceName = 'FACTURA' and targetRFC = 'HEMM650722HZ5';;
+---------------------+-----------+---------------+---------------+----------------------------------+--------------+-------------+--------------------------------------+
| financialDetails_id | CxCStatus | sourceRFC     | targetRFC     | targetName                       | clientNumber | invoiceName | folioSAT                             |
+---------------------+-----------+---------------+---------------+----------------------------------+--------------+-------------+--------------------------------------+
|              814770 | Vigente   | EARA620117GT8 | HEMM650722HZ5 | MARIA MAGDALENA HERNANDEZ MEDINA | NULL         | FACTURA     | 59863e68-c1d8-4985-9cfe-d0181a36bcae |
|              814774 | Vigente   | EARA620117GT8 | HEMM650722HZ5 | MARIA MAGDALENA HERNANDEZ MEDINA | NULL         | FACTURA     | 77d0fbf6-c665-499f-a968-2d1fa846e658 |
|              814780 | Vigente   | EARA620117GT8 | HEMM650722HZ5 | MARIA MAGDALENA HERNANDEZ MEDINA | NULL         | FACTURA     | 8433d41c-4d85-4b81-bc12-027d4ff2d837 |
|              814784 | Vigente   | EARA620117GT8 | HEMM650722HZ5 | MARIA MAGDALENA HERNANDEZ MEDINA | NULL         | FACTURA     | c7a923a8-612c-43e7-8d4b-d4c47a70e892 |
+---------------------+-----------+---------------+---------------+----------------------------------+--------------+-------------+--------------------------------------+
4 rows in set (0.70 sec)

mysql> select total from CFD_FinancialDetails where id = 814770;
+-------+
| total |
+-------+
|  3712 |
+-------+
1 row in set (0.00 sec)

mysql> select total from CFD_FinancialDetails where id = 814774;
+-------+
| total |
+-------+
|  3712 |
+-------+
1 row in set (0.00 sec)

mysql> select total from CFD_FinancialDetails where id = 814780;
+-------+
| total |
+-------+
|  1566 |
+-------+
1 row in set (0.00 sec)

mysql> select total from CFD_FinancialDetails where id = 814784;
+-------+
| total |
+-------+
|  3480 |
+-------+
1 row in set (0.00 sec)

**Comment by RigoFlores** [comment]
Wey, pues algo está pasando, por tercer día consecutivo, muestra una información que no se de donde putas la obtiene... no me digas que se dan de alta clientes y se borran diariamente.. checatesta...
![errorcarterageneral3](https://cloud.githubusercontent.com/assets/2912775/23959016/8bb407a8-0969-11e7-81c7-ed4148a34b72.PNG)

**Comment by RigoFlores** [comment]
JUAN SALVADOR MEDINA DORANTES, NO EXISTE NI COMO CLIENTE, NI COMO PROVEEDOR.
Mejor investígale... chiaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by jccastillo0007** [comment]
MARIA MAGDALENA HERNANDEZ MEDINA tampoco existe como cliente o proveedor, pero si tienen esas facturas dadas de alta, probablemente subieron los XML como externos

**Comment by RigoFlores** [comment]
RECUERDA QUE ELLOS OCUPAN EL PORTAL DE PROVEEDORES... PERO PARA QUE ACCEDAN SUS PROVEEDORES, PRIMERO LOS TUVIERON QUE DAR DE ALTA, QUE NO?
TOTAL, QUE APARENTEMENTE ESTAS FACTURAS NO TIENEN MADRE, ES DECIR ESTÁN HUÉRFANAS, Y NO SABEMOS DE DONDE SALE LA RELACIÓN, PERO EL PEDO ES QUE ESTE ISSUE ESTÁ MAS VIGENTE QUE NUNCA... JEJE

**Comment by jccastillo0007** [comment]
de hecho, si est[an identificadas, ellos son el emisor, y el receptor aparece en la base de datos, el tema es que la pantalla de consultas, muestra el nombre y no el rfc, y además no tienen número de cliente, entiendo que ya les preguntaste a ellos verdad ?

**Comment by RigoFlores** [comment]
noup

**Comment by RigoFlores** [comment]
ah bueno, el primero dijo que era proveedor... digamos el del primer reporte...

**Comment by jccastillo0007** [comment]
jajaja entonces tu quieres saber de dodne salió esa factura, y no les has preguntado a ellos ?

**Comment by RigoFlores** [comment]
si checamos el reporte inicial.... se trata de pedidos.... que levantaron y ahí aparecen... yo comenté eso, tu dijiste que no, que eso ya estaba mas que filtrado... y luego te indiqué que nel, que seguía mal... lo extraño es que no aparecen como clientes esos rfcs.... mi teoría es que dan de alta el cliente, generan pedido, y luego borran al cliente... jeje

**Comment by RigoFlores** [comment]
OK, los 2 primeros casos... se trata de clientes, que levantaron pedidos, y que luego ELIMINARON.
El tercer caso, se trata de un trabajador de ellos... jejeje

Hay inconsistencias al momento de borrar los clientes, que además son proveedores... un cagadero puesn

**Comment by RigoFlores** [comment]
Ya le pedí que no borren así porque sí, ya que provocan inconsistencias...

**Comment by jccastillo0007** [comment]
aqui yo no tengo nada que hacer.

**Comment by RigoFlores** [comment]
No es que se tenga que corregir por código, pero si tenemos que conocer porque se muestra y corregir en la BD para que ya aparezca.
Luego también, quizás agregar un candado, excepción o similar, para cuando se repita la situación.

Evidentemente el cliente, es el que menos tendría que hacer algo, no tiene idea de lo que pasa.

**Comment by jccastillo0007** [comment]
mmmmmm , pues si ellos facturan y luego borran, nosotros no podemos evitarlo, eso sería parte del entrenamiento que se les da cuando inician a usar la app.

**Comment by RigoFlores** [comment]
1) la capacitación fue solo para emisión de FE
2) Nunca mencionaron que ocuparían pedidos - para hacer pedidos a sus proveedores!!!!
3) Si la aplicación permite que la info quede inconsistente, es nuestra responsabilidad, ya que hasta por error se puede borrar un cliente.

yo creo que debemos dejar de dar vueltas, y ver como CORREGIMOS esta situación, que definitivamente afecta en CxC

**Comment by jccastillo0007** [comment]
pues no estoy de acuerdo en tu forma de ver los errores, pero si en arreglarlo.

No tengo idea de como evitar algo asi, amenos que no permitamos borrar registros si no antes de validar que no se ocupen en otros lados, lo cual no es viable ya que sería muy costozo, y el mismo caso pasaría con clientes, productos, sucursales, unidades, impuestos etc...

Por otro lado, me imagino que ellos están conscientes de lo que hicieron y ya les explicaste que eso no se debe hacer.

**Comment by RigoFlores** [comment]
No están borrando clientes que ya facturaron.
Ellos dieron de alta proveedores en el catálogo de clientes para levantarles un pedido (a sus proveedores), y después borraron esos registros del catálogo de clientes.
Realmente el problema desde el inicio, es que ahí en cartera, está mostrando información que NO CORRESPONDE A FACTURAS, sino a pedidos o no se que otro... quizás hasta nómina..

**Comment by RigoFlores** [comment]
Necesitamos eliminar la información que corresponde a PEDIDOS.
Que hacemos?

**Comment by jccastillo0007** [comment]
mmmm o sea , la borro de la base de datos, o mas bien al momento de consultar las facturas ?, si es lo segundo, ya esta implementado, ya que solo se leen CFDi que tengan un UUID válido, si ese campo esta vacío, no las muestra

**Comment by RigoFlores** [comment]
Acabo de consultar la cartera general. Recordar que nos referimos a este cliente EARA620117GT8, con el usuario ana.estrada (contraseña igual).
Me marca internal error

**Comment by jccastillo0007** [comment]
ups, pequeño detalle de los mensajes de debug que puse para el cliente con el que probamos que todo cuadrara.

**Comment by RigoFlores** [comment]
lo revisé nuevamente en producción y sigue marcando error... de hecho ahí es donde surgió este issue
