### ISSUE TITLE
Ingresar Cobro - No cambia el status de NC cuando se aplican en pagos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#957]
Tenemos 2 casos en optibelt. Esto es nuevo, y junto con el issue que levanté hoy en la mañana, me parece que es un defecto recién inyectado. Los de optibelt, ya se volvieron locochones.

Si consultas por referencia, verás lo que te digo:

LOSZA14037, 14052
LOSZA13758,13835,13887

**Comment by RigoFlores** [comment]
Según yo, tampoco cambia el status de las facturas pagadas..., es decir no solo las de NC

**Comment by jccastillo0007** [comment]
De la referencia LOSZA14037, 14052, actualié 3 facturas y 1 NC a Pagada
De la referencia LOSZA13758,13835,13887, actualicé 6 facturas y 1 NC a Pagada

**Comment by RigoFlores** [comment]
pero el problema de raiz, es que no actualiza al capturar pagos...

**Comment by RigoFlores** [comment]
Es decir, si va a actualizar a pagadas, cuando efectivamente se realicen los pagos???

**Comment by jccastillo0007** [comment]
como asi? de eso se trata este issue no ?

**Comment by RigoFlores** [comment]
se trata de que cuando ingreses un cobro... con NC, le ponga status de pagada... igual a las facturas... me parece que ya quedó atendido... al menos ya no lo reportaron
