### ISSUE TITLE
CxC - No actualiza el status de facturas vencidas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#958]
Este cliente EARA620117GT8 emite las facturas desde la plataforma, a diferencia de optibelt, que vienen desde el superconector.
Bien, pues no les está actualizando el status. Todas dicen vigente, y deberían ser ya varias vencidas, porque en el catálogo de clientes tiene 30 días de crédito. Esto es cuando rebasa la fecha esos 30 días, entonces se debe poner a vencida. De hecho no sé si en Optibelt suceda lo mismo, pero también esto es algo que ya se había validado y aprobado anteriormente.
![vigentesincorrectas](https://cloud.githubusercontent.com/assets/2912775/23902769/da6fd878-0887-11e7-9c2e-054729953a62.PNG)

**Comment by RigoFlores** [comment]
ya ví en optibelt, y sucede lo mismo.... obviamente todas las facturas del 2015, deberían estar vencidas...
Esto fue de lo primero que validamos...
![vigentesincorrectas2](https://cloud.githubusercontent.com/assets/2912775/23903037/ca9aa0f8-0888-11e7-9e04-32af1111734b.PNG)

**Comment by jccastillo0007** [comment]
a chinga, y quien le cambia a vencidas o como ? no recuerdo que tuvieramos un proceso automatizado para hacer eso.

algún evento debe disparar el update, deja veo el código.

**Comment by RigoFlores** [comment]
En su momento, platicamos de un trigger diario (por la madrugada), que checaría y actualizaría el status de las facturas. La otra que platicamos fue, que al momento de la consulta se aplicaría dicho proceso.
No recuerdo como quedó, pero es MUY IMPORTANTE ATENDER ESTO, ya que para propósitos de CxC, a ningún cliente habría que cobrarles... jeje

**Comment by jccastillo0007** [comment]
ok, pues ahora que lo mencionas, si recuerdo eso del job para actualizar el estatus, pero se me hace que solo lo platicamos
Ya puse un shell script para hacerlo durante las noches..

Ahorita acabo de actualizar 40209 facturas vencidas de acuerdo a su fecha de expiración

**Comment by RigoFlores** [comment]
Pregunta, esas tantas facturas que se actualizaron... son de toooodos los clientes???? o porque son tantos...
Ahora, que pasa con la gran mayoría de clientes, que no tienen capturado ningún dato en días de crédito? Cuál es el dato que toma por omisión, recuerdo que lo habíamos platicado.
