### ISSUE TITLE
CxC - Cartera de Cliente - sin filtro no muestra las pagadas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#959]
En cartera de cliente, lo hice para optibelt. Filtré por número de cliente 409300, pero no apliqué filtro de vigencia (que realmente debería ser status); si no aplico este filtro indica todas (pagadas, vigentes, vencidas). Sin embargo solo muestra vigentes y vencidas.
Pero si elijo el filtro de pagadas, si las muestra.
Entonces cuando no se aplique ningún filtro, debe mostrar todas.

Esto también ya jalaba... no sé que está pasando, pero hay muchos detalles que están regresando de antes.

**Comment by jccastillo0007** [comment]
ese filtro si lo puse aldrede... la semana pasada...  no recuerdo si le pegaba a otra cosa...

**Comment by jccastillo0007** [comment]
chiaaa tuve que agregar un query especial para consultas hechas para ingresar pagos, y otro para consultas en general y por cliente.
