### ISSUE TITLE
Los únicos datos obligatorios en la captura del cliente son RFC y País

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#96]
De acuerdo al anexo 20 vigente, son los únicos 2 datos obligatorios en los datos del emisor. El resto son opcionales.
Favor de agregar esta condición tanto en uev, como en están alon.
Ayer pasó con un cliente que no le capturó el pais, y le envió un mensaje de error. Por omisión, el país siempre debe ser MEXICO, con la opción de editarlo durante la edición del registro del cliente.

**Comment by jccastillo0007** [comment]
Done en web y standalone.

Si no capturan nada, por default pone MEXICO.

**Comment by RigoFlores** [comment]
Al menos en web (porque no encontré una nueva versión del están alon), también exige el nombre. Es decir, nombre o razón social no es estrictamente obligatorio desde el punto de vista del xsd...

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
CORRECTÍSIMO, SI NO CAPTURAS PAÍS, NO TE LA HACE DE EMOCIÓN, PERO LE PONE EL DEFAULT COMO MEXICO.
EN ESTÁN ALON Y EN WEB
