### ISSUE TITLE
AJUSTES DE TIPO DE CAMBIO EN EL FORMATO LEVICOM II

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#960]
YA ENVIÉ LOS REQUEST POR CORREO:

ES EL CÓDIGO QUE APLICA PARA ESTE RFC (ENTRE OTROS DEL GRUPO) ETE790117358

LO QUE SE OCUPA ES PARSEAR EL DATO DE TIPO DE CAMBIO, QUE VIENE JUSTO ANTES DE LA CANTIDAD CON LETRA, Y ENVIARLO AL XML Y AL PDF:
AQUÍ EL DETALLE ES QUE ESE CÓDIGO SOLO APLICA PARA EL GRUPO DE RFCS DE ESPECIALIDADES TÉRMICAS, ENTONCES COMO LO PRUEBO EN PRU DONDE SOLO SE TIMBRA CON EL RFC ACO_ALGO???

H1|ETSF|39615| |20161118|39615|20161118|PAGO EN UNA SOLA EXHIBICION|Contado|ORIGINAL|FACTURA||EATONCON|NA|USD|Orden de Compra: 9892470023748|1|( Seis mil Seiscientos Noventa y Nueve Dólares 70/100 USD   )|0|P|||felipe@especialidadestermicas.com|GUADALAJARA, JAL.

**Comment by jccastillo0007** [comment]
done.
