### ISSUE TITLE
CxC - Borrado de pagos por referencia - solicitar confirmación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#961]
Solicitar confirmación y mostrar el resultado del proceso.
Ahora mismo no dice nada.

**Comment by jccastillo0007** [comment]
Ya le puse la confirmación de borrado, y el indicador de que lo hizo.... el efecto de la pantalla en gris, la ventana de confirmación aún no la pongo .

**Comment by RigoFlores** [comment]
Vi en pru, que manda un mensaje de que fue borrado exitosamente.
Ya solo resta la confirmación.

**Comment by jccastillo0007** [comment]
Done.

Not  yet, algo esta pasando que no muestra la ventana de confirmaci´øn

**Comment by jccastillo0007** [comment]
Done.

Estos cambios los voy a subir a PRO mañana.

**Comment by RigoFlores** [comment]
"Esta seguro de borrar el pago mostrado en pantalla?"

**Comment by jccastillo0007** [comment]
No lo quería customizar tnato, porque ese mismo dialogo será reutilizado, pero bueno... lo voy a parametrizar.

**Comment by RigoFlores** [comment]
oye, y el disco de guardar en lugar de aceptar... se puede poner el tooltip aceptar, o de plano cambiar el ícono o ya queda así???

**Comment by jccastillo0007** [comment]
Le pongo el tooltip de aceptar, y podría poner otro ícono se fuera necesario pero no un botón.

**Comment by RigoFlores** [comment]
chiaaaaaa.... que un botón de aceptar es chaca, naco, autudeit o que?
