### ISSUE TITLE
Pone como pagada una factura que tiene un pago parcial

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#962]
Wey, esto ya lo teníamos dominado... seguimos regresando defectos, y estamos perdiendo mucha confiabilidad con el cliente... chiaaaaa

![pagosparciales](https://cloud.githubusercontent.com/assets/2912775/23976560/1803795c-09ae-11e7-9fe8-800eee791130.PNG)

**Comment by jccastillo0007** [comment]
fixed.

Otra vez el tema de -0.001 ... la validación que puse es :  
Si el saldo restante es <= 0.001 o >= -0.001 entonces la pone como pagada, cualquier otra diferencia, no la pone como pagada

**Comment by RigoFlores** [comment]
OK, quizás quedó para los pagos nuevos, pero como corregimos los anteriores que están en esa condición??? 
El reporte original del cliente, la factura 171047997 tiene esa condición que aparece como pagada, pero en realidad no está completamente pagada..


![pagadaerroneamente](https://cloud.githubusercontent.com/assets/2912775/24010730/5296dfe2-0a3e-11e7-951a-3f3ed6465316.PNG)

**Comment by jccastillo0007** [comment]
Pasame toda la lista si la tienes, si no, voy va ver si puedo sacar todos los pagos que hicieron ayer y de ahi corrijo... según yo, corregí el que me enviaste.

**Comment by RigoFlores** [comment]
No existe dicha lista... solo me reportaron esa factura... no es posible con query conocer dicha lista?

**Comment by jccastillo0007** [comment]
ok, por query validé los últimos 250 pagos, y ese fue el único caso.
