### ISSUE TITLE
CCE11 - ATRIBUTOS CONDICIONALES SON POR LO PRONTO OBLIGATORIOS

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#965]
DADO QUE EN EL CATÁLOGO DE CLAVES DE PEDIMENTO, SOLO EXISTE LA OPCIÓN DE EXPORTACIÓN, EN AUTOMÁTICO LOS SIGUIENTES ATRIBUTOS CONDICIONALES SE VUELVEN OBLIGADOS:

ClaveDePedimento
CertificadoOrigen
Incoterm
Subdivision
TipoCambioUSD
TotalUSD

**Comment by RigoFlores** [comment]
PUES NO ENCONTRÉ COMO CAPTURAR TODOS ESTOS ATRIBUTOS OBLIGATORIOS... SEGÚN YO ENTIENDO POR ESO MARCA EL ERROR...

CCE159 : El atributo XXXX debe registrarse si la clave de cce11:ComercioExterior:TipoOperacion registrada es '1' ó '2'. (3)

ASI LO CAPTURÉ CON DATOS CORRECTOS...

![cce1](https://cloud.githubusercontent.com/assets/2912775/24525976/a73df65e-1559-11e7-9164-1e6563b98087.PNG)


FALTA EL CERTIFICADO DE ORIGEN... QUE VA EN 0
Y EL TIPO DE CAMBIO Y TOTAL, NO SÉ COMO LO INCLUYE...?

**Comment by jccastillo0007** [comment]
esos tres datos los pone directamente en el xml, lo malo es que no puedes ver el xml generado, pero yo si lo he visto y lo crea bien, casi igual al de ejemplo que enviaste, excepto por las mercancias, eso si me falta, capaz que va por ahi, hoy voy a trabajar en parametrizar las mercancias y agregarlas al xml al vuelo para ser capturadas.
