### ISSUE TITLE
CCE1.1 - Si el tipo del CFDI estándar es Ingreso, entonces NO EXISTEN...

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#966]
A nivel de complemento:

NO EXISTE MOTIVO DE TRASLADO
NO EXISTE NODO PROPIETARIO

**Comment by jccastillo0007** [comment]
ambos campos no son incluidos en mis pruebas.

**Comment by RigoFlores** [comment]
Cuando el tipo de cfdi sea ingreso, no se envía el motivo de traslado.
Hice una prueba con tipo ingreso, y capturando el motivo de traslado, y supongo que si lo intentó enviar, ya que marca lo siguiente...

CCE113 : El atributo MotivoTraslado no debe existir cuando cfdi:Comprobante:tipoDeComprobante es distinto de 'traslado'. (3)

**Comment by jccastillo0007** [comment]
chiaaaaa pues que no capturen nada y listo

**Comment by jccastillo0007** [comment]
Fixed.
