### ISSUE TITLE
CCE1.1 - Si el tipo de CFDI estándar es Traslado entonces....

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#967]
DEBE EXISTIR MOTIVO DE TRASLADO

Si motivo de traslado 01 al 04, NO SE REGISTRA PROPIETARIO

Si el motivo de traslado es 05, entonces se debe incluir PROPIETARIO

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
En el nodo propietario, se deben capturar 2 datos:

NumRegIdTrib   (le capturé un dato correcto, hasta donde entiendo)
ResidenciaFiscal  (es una clave de país, pero no hay cuadro de texto para captura).

Ahora mismo marca este error... según yo porque falta el dato de residencia fiscal en este nodo.

CCE174 : El atributo cce11:ComercioExterior:Propietario:NumRegIdTrib no tiene un valor que exista en el registro del país indicado en el atributo cce1:Propietario:ResidenciaFiscal. (3)

**Comment by jccastillo0007** [comment]
como pais se esta poniendo MEX por default, y manda lo mismo... 

Quieres que agregue un dato extra para ese campo ?

**Comment by RigoFlores** [comment]
Si... recuerda que este complemento se ocupa para exportar.... tons generalmente no es MEX el país a donde se exporta (hay un solo caso, pero entonces no sería exportación.. jeje)

Recuerda que propietario se captura, cuando el receptor, no es el dueño de la mercancía... solo la recibe.

En todo caso debes poner el país del receptor, A MENOS QUE SE CAPTURE EL PAIS, del propietario,,,

estos 2 parámetros, solo se envían en caso de traslado y motivo de traslado = 05

**Comment by jccastillo0007** [comment]
Ok, agregó la captura de la clave de país del propietario, yo creía que el propietario era el que vendía, por eso le había puesto MEX.
