### ISSUE TITLE
CCE1.1 - Si certificado de Origen= 0, entonces no existe NumCertificadoOrigen

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#968]
Creo que es parte del problema que tuviste ayer 27 de marzo.
Hay que irnos con pruebas paulatinas... esto es, certificado de origen=0, entonces no incluimos el número de certificado de origen.

**Comment by jccastillo0007** [comment]
ok, esta bien, pero con la observación de que también intente este escenario.

**Comment by RigoFlores** [comment]
si el certificado es 0, y capturo el número de certificado de origen... lo envía al XML y marca error.
Este issue se levantó precisamente para que si certificado de origen es 0, entonces se ignora (simplemente no se envía), el número de certificado de origen.

CCE160 : El atributo cce11:ComercioExterior:NumCertificadoOrigen no se debe registrar si el valor de cce11:ComercioExterior:CertificadoOrigen es '0'. (3)

**Comment by jccastillo0007** [comment]
Fixed.
