### ISSUE TITLE
Catálogo de Clientes - Tenemos varios problemas con los clientes

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#969]
El CP no coincide con el alta del SAT en varios casos... y varios clientes ya me la están haciendo de super pedo.

Entonces, podemos hacer un ajuste para que 
a) una vez elegido el municipio y estado, se listen todas las colonias dentro del municipio y una vez elegida, se coloque el CP....

ó

b) si no aparece una coincidencia de CP vs Colonia, poner un par de cajas de texto para que lo capturen... al menos mientras se homologa correctamente en el SAT

**Comment by jccastillo0007** [comment]
Esto ya esta arreglado inclusive en PRO
