### ISSUE TITLE
Problema con el schema location de donatarias

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#97]
PARA LOS CLIENTES QUE TIENEN EL ESTÁN ALON, Y TAMBIÉN WEB, AL PARECER ESTÁ MAL ESCRITO EL SCHEMA LOCATION DE DONATARIAS (le falta 1.1):

Anexo ejemplos XML’s de CFDI y CFD generados por nosotros; es urgente porque estamos ofreciendo que cumplimos 100% con el complemento, y al parecer está incorrecto.

En caso afirmativo, urge la corrección para CFD y CFDI, (ambos en están alon, y CFDI también para el web)

Así aparece el xml:

```
    <donat:Donatarias xmlns:donat="http://www.sat.gob.mx/donat" fechaAutorizacion="2010-02-05" leyenda="Este comprobante ampara un donativo, el cual será destinado por la donataria a los fines propios de su objeto social. En el caso de que los bienes donados hayan sido deducidos previamente para los efectos del impuesto sobre la renta, este donativo no es deducible. La reproducción no autorizada de este comprobante constituye un delito en los términos de las disposiciones fiscales." noAutorizacion="600-04-05-2010-66491" version="1.1" xsi:schemaLocation="http://www.sat.gob.mx/donat http://www.sat.gob.mx/sitio_internet/cfd/donat/donat.xsd"/>



    <donat:Donatarias xmlns:donat="http://www.sat.gob.mx/donat" fechaAutorizacion="2003-04-15" leyenda="Este comprobante ampara un donativo, el cual será destinado por la donataria a los fines propios de su objeto social. En el caso de que los bienes donados hayan sido deducidos previamente para los efectos del impuesto sobre la renta, este donativo no es deducible. La reproducción no autorizada de este comprobante constituye un delito en los términos de las disposiciones fiscales." noAutorizacion="325-SAT-22-D-2995" version="1.1" xsi:schemaLocation="http://www.sat.gob.mx/donat http://www.sat.gob.mx/sitio_internet/cfd/donat/donat.xsd"/>
```

Y la spec indica:

Para CFD:

<Comprobante

…

xmlns="http://www.sat.gob.mx/cfd/2"

xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

xmlns:donat="http://www.sat.gob.mx/donat"

xsi:schemaLocation="

http://www.sat.gob.mx/cfd/2

http://www.sat.gob.mx/sitio_internet/cfd/2/cfdv22.xsd

http://www.sat.gob.mx/donat

http://www.sat.gob.mx/sitio_internet/cfd/donat/donat11.xsd"

….

</Comprobante>

Para CFDI:

<Comprobante

…

xmlns:cfdi="http://www.sat.gob.mx/cfd/3"

xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

xmlns:donat="http://www.sat.gob.mx/donat"

xsi:schemaLocation="

http://www.sat.gob.mx/cfd/3

http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd

http://www.sat.gob.mx/donat

http://www.sat.gob.mx/sitio_internet/cfd/donat/donat11.xsd"

**Comment by jccastillo0007** [comment]
fixed

Ojo... no es 1.1 si no 11 lo que faltaba.

**Comment by RigoFlores** [comment]
Correcto, es 11, pero me refería mas bien a la versión 1.1.
Pendiente la actualización en están alón para cfd y cfdi... de hecho tenemos donatarias en cfd y cfdi están alon; también 2 en web cfdi.

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
Probado en escritorio y web
Jaló para CFD y CFDI.
