### ISSUE TITLE
CCE1.1- Reacomodar el número de certificado de origen

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#970]
En la pantalla de captura de datos de la addenda (complemento, realmente), colocar el número de certificado de origen, debajo del parámetro certificado de origen.. (son pareja... chiaaaa).

No le quise mover al XML de configuración, ya que no sé cómo tomas el orden de datos...

**Comment by jccastillo0007** [comment]
Done.

Agregué un dato, después del motivo traslado, es para capturar el registro de no se que madres del propietario.
