### ISSUE TITLE
CCE1.1 - total en USD y tipo de cambio dentro del complemento incorrectos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#971]
Si la moneda del CFDI es distinto a USD, entonces estos atributos deben calcularse, con base a lo capturado en el catálogo de monedas..

Este atributo dentro del complemento, siempre será en USD.
Si la moneda original es pesos, entonces hay que hacer la conversión.
Si la moneda no es ni pesos, ni USD... entonces hay que convertir a pesos, y luego a USD (supongo este último escenario sería poco común)...

**Comment by jccastillo0007** [comment]
ok, entonces si es pesos lo debe transformar a USD.... que raro que sin hacer esa transformación ya nos esta aceptando el complemento, pero cuando la moneda es USD marca error

**Comment by RigoFlores** [comment]
Ya ví donde está el problema... total USD, debe ser la suma de valorDolares en el nodo mercancia (detalle) del complemento.
Esto es... lo que tenemos que pasar a USD, es el valor unitario, hasta 2 decimales. 
Con ello el valorDolares (importe x valor unitario) del complemento será también una cantidad en dólares.
Finalmente el totalUSD a nivel header del complemento, deberá estar en 2 decimales...

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
no está haciendo la conversión de monedas...
Pero este hay que dejarlo pendiente... esa conversión contiene unas fórmulas bien pinches mafufas...
lo que podemos hacer en facturar en USD... únicamente... jeje
Ya que para pesos, o cualquier otra moneda, no estará funcionando.....

**Comment by RigoFlores** [comment]
En teoría es esto.... tienes oportunidad de validarlo nuevamente...??

Revisando la guía de CE, encontré lo siguiente.
Dentro del complemento…  existe totalUSD a nivel general (aquí es donde marcaba el error), pero dentro del CCE a nivel mercancía (detalle), para cada producto se incluye el valor unitario Aduana y valor Dolares

Valor unitario es el precio unitario en USD expresado a 2 decimales (ahí es donde todo cuadra).
Valor Dólares, es el valor unitario por la cantidad… (te dará una cifra a 2 decimales)

totalUSD es la sumatoria de valorDolares de todos los productos dentro del complemento.

Entonces, para una factura en moneda distinta a USD, se debe:

a)	El precio unitario de cada producto o servicio, pasarlo a USD con 2 decimales. Para ello tendrás que ocupar el tipo de cambio. Si la moneda no es MXN, entonces tendrás que convertir a MXN y luego a USD.
b)	Del punto anterior, tendremos el valorUnitarioAduana del nodo mercancía dentro del complemento
c)	Del punto anterior y junto con la cantidad, tendremos el valor de valorDolares del nodo mercancía dentro del complemento.
d)	Finalmente, con la suma de todos los ( c ), se estima el totalUSD a nivel jeder del complemento.


Ejemplo:
USD TC:18.3
EUR TC:17.5

Precio Unitario: $100.00 MXN  === > 100/18.3 = 5.4644808743…. redondeado $5.46 USD
Precio Unitario: E 90.00 EUR    ====> 90*17.5 / 18.3 = 86.065573…. redondeando  $86.07 USD
