### ISSUE TITLE
CCE11- TRASLADO... error cuando motivo de traslado es 05

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#972]
Cuando se trata de cfdi tipo traslado, y el motivo de traslado es 05 Envío de mercancías propiedad de terceros, se debe registrar al menos un propietario dentro del complemento.

CCE112 : El nodo Propietario se debe registrar cuando cfdi:Comprobante:tipoDeComprobante tiene el valor 'traslado' y MotivoTraslado tiene la clave '05'. (3)

No estoy seguro que se ocupe ahora mismo, yo entendería que este escenario aplica para transportistas, que llevan mercancía al otro lado.
Tampoco descarto que nos lo lleguen a pedir... 
Por lo pronto, la plataforma no soporta el 05, sin embargo los demás motivos si los está soportando.

**Comment by jccastillo0007** [comment]
Fixed.

Ya se validan las condiciones, pero no pude probar porque no sé que dato ponerle en el campo de Registro del Propietario, le puse simplemente 123456789 y me dice que no existe.. tons no sé como probarlo, pero tú tal vez tengas el dato.

**Comment by RigoFlores** [comment]
Es el tema del país del propietario... cierro este, y lo seguimos atendiendo desde el issue 967
