### ISSUE TITLE
CCE1.1 - marca error cuando la moneda seleccionada es distinta a MXN

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#973]
VALIDÉ CON USD Y EUR.

Marca XML mal formado.

**Comment by jccastillo0007** [comment]
pues no sé si se debía a otro problema ya solucionado, porque yo generé una factura con USD y otra con EUR y no marco error, me parece que no hizo las transformaciones necesarias, pero ese es otro error. 971

**Comment by RigoFlores** [comment]
Pero si incluiste el complemento... el problema es cuando se incluye el CCE con una moneda distinta a MXN

**Comment by RigoFlores** [comment]
Lo acabo de validar nuevamente... si quieres lo vemos en conjunto...
igual y hablamos de cosas distintas...
pero es generar una factura, eligiendo una moneda por ejemplo USD, agregar producto, indicar que lleva el complemento, capturar el complemento y darle facturar...

**Comment by RigoFlores** [comment]
correcto, ya no marca error... pero realmente no hace la transformación... eso es ooootro asunto
