### ISSUE TITLE
CCE1.1 - incluir el curp del emisor, cuando éste sea persona física

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#975]
ESTE DATO YA LO CAPTURAMOS EN LA CONFIGURACIÓN DE CADA EMISOR. (PANTALLA CONFIGURACIÓN).
LO QUE HAY QUE HACER, ES ENVIARLO EN EL NODO EMISOR DEL COMPLEMENTO DE CE, CUANDO DETECTES QUE LA LONGITUD DEL RFC EMISOR ES DE 13 (ESTO ES, SE TRATA DE PERSONA FÍSICA).

HOY NO TENDRÍA FORMA DE PROBARLO EN PRUEBAS, PERO SI TIENES QUE VALIDAR AL MENOS GENERANDO EL XML SIN TIMBRAR PARA CHECARLO...

**Comment by jccastillo0007** [comment]
Ok, lo pruebo con mi RFC y te mando evidencia, ya esta el código listo.

**Comment by RigoFlores** [comment]
LO RETOMAREMOS CUANDO SE OCUPE
