### ISSUE TITLE
CCE1.1 - ENVIAR LAS SIGUIENTES VARIABLES AL PDF

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#976]
Enviarlas en el formato como el método de pago, es decir clave.descripcion:

motivoTraslado
tipoOperacion
clavePedimento
certificadoOrigen
numeroCertificadoOrigen
incoterm
sundivision
registroFiscalReceptor

A nivel producto, enviar (pueden ser como datos extra, tu me dices):
fraccionArancelaria
unidadAduana

**Comment by jccastillo0007** [comment]
vamos a empezar por enviarlas, y luego vemos lo de clave.descripción.

**Comment by jccastillo0007** [comment]
A nivel general se mandarán en este orden
			datoExtra1 = ce2.getMotivoTraslado();
			datoExtra2 = ce2.getTipoOperacion();
			datoExtra3 = ce2.getClaveDePedimento().name();
			datoExtra4 = ce2.getCertificadoOrigen().intValue() + "";
			datoExtra5 = ce2.getNumCertificadoOrigen();
			datoExtra6 = ce2.getIncoterm().name();
			datoExtra7 = ce2.getSubdivision().intValue() + "";
			datoExtra8 = ce2.getReceptor().getNumRegIdTrib();

**Comment by jccastillo0007** [comment]
y por producto
product.setDatoExtraPro1(item.getFraccionArancelaria());
product.setDatoExtraPro1(item.getUnidadAduana());

**Comment by RigoFlores** [comment]
Para empezar, tengo que entender a que dato extra, supuestamente corresponde cada dato que se captura en la aplicación, ya que el orden en que lo mandas es distinto y no coincide con la pantalla  (chiaaaaa):

Motivo de Traslado   (datoExtra1)
Número Registro Propietario   (datoExtra8)
Clave País Propietario       (datoExtra3)
Incoterm            (datoExtra6)
Subdivision         (datoExtra7)
Numero de Registro Receptor     (supongo que es el datoExtra2)
Certificado de Origen      (datoExtra4)
Numero de Certificado de Origen   (datoExtra5)

**Comment by RigoFlores** [comment]
Llené todos los campos y al PDF solo llegó. OJO, dado que posiblemente están en desorden, no sé exactamente cuál falta. Creo que tiene que ver con tipos de datos... los que faltan son numéricos y los datos extra son string todos ellos.

Motivo de Traslado: null
No. Registro del Propietario: null
Clave País del Propietario: USA
Certificado de Origen: 1
No. Certificado Origen: null
INCOTERM: FOB
Subdivisión: null
ID o Registro Fiscal receptor: 889010357

        <cce11:ComercioExterior xmlns:cce11="http://www.sat.gob.mx/ComercioExterior11" CertificadoOrigen="1" ClaveDePedimento="A1" Incoterm="FOB" MotivoTraslado="05" NumCertificadoOrigen="9C6F5746-DEEA-41F5-AA50-B8E7460DBFED" Subdivision="0" TipoCambioUSD="1.0" TipoOperacion="2" TotalUSD="107201.88" Version="1.1">
            <cce11:Propietario NumRegIdTrib="756985236" ResidenciaFiscal="USA"/>
            <cce11:Receptor NumRegIdTrib="889010357"/>
            <cce11:Mercancias>
                <cce11:Mercancia CantidadAduana="1.0" FraccionArancelaria="01039102" NoIdentificacion="ANT-01" UnidadAduana="07" ValorDolares="107201.88" ValorUnitarioAduana="107201.88"/>
            </cce11:Mercancias>
        </cce11:ComercioExterior>

**Comment by jccastillo0007** [comment]
A nivel general se mandarán en este orden
datoExtra1 = ce2.getMotivoTraslado();
datoExtra2 = ce2.getTipoOperacion();
datoExtra3 = ce2.getClaveDePedimento().name();
datoExtra4 = ce2.getCertificadoOrigen().intValue() + "";
datoExtra5 = ce2.getNumCertificadoOrigen();
datoExtra6 = ce2.getIncoterm().name();
datoExtra7 = ce2.getSubdivision().intValue() + "";
datoExtra8 = ce2.getReceptor().getNumRegIdTrib();

**Comment by jccastillo0007** [comment]
a caray, pues si están igual, no ha cambiado, deja hago pruebas.

Ya esta enviando las variables en el orden indicado.

**Comment by jccastillo0007** [comment]
Esta es la lista final de datos enviados a jasper, en este orden
datoExtra1 = ce2.getMotivoTraslado();
datoExtra2 = ce2.getTipoOperacion();
datoExtra3 = ce2.getClaveDePedimento().name();
datoExtra4 = ce2.getCertificadoOrigen().intValue() + "";
datoExtra5 = ce2.getNumCertificadoOrigen();
datoExtra6 = ce2.getIncoterm().name();
datoExtra7 = ce2.getSubdivision().intValue() + "";
datoExtra8 = ce2.getReceptor().getNumRegIdTrib();
datoExtra9 = propietario.getNumRegIdTrib()
datoExtra10 = propietario.getResidenciaFiscal().name()

**Comment by jccastillo0007** [comment]
Para los productos solo se mandan dos:

datoextrapro1 = fracción arancelaria
datoextrapro2 = unidadaduana

**Comment by RigoFlores** [comment]
no, ahora envía hasta los datos extra a nivel producto, como datos generales
La verdad no sé, porque se está complicando tanto esto, pero ya nos retrasó una semana mas....
Lo peor es que van 2 veces que le pegamos a producción... y eso deberías ver todo el desmadre que provoca aquí...

**Comment by RigoFlores** [comment]
la plantilla actual, despliega los datos de datoExtra1 al 10... para que lo revises, pero al parecer no le estás tomando mucho en cuenta... o no entiendo que pasa....
