### ISSUE TITLE
Actualizar las plantillas base.

### ISSUE THREAD

**Issue by jccastillo0007** [jccastillo0007/eFacturaT#98]
Esta es la primera plantilla base que tenemos para web (favor de eliminar la anterior).

Resulta que dependiendo del logo del cliente (ancho o largo), y de sus necesidades (uno o varios impuestos), nos vemos en la necesidad de contar con al menos 4 plantillas base.

Cómo sugieres que podamos manejar esta plantillas por default, es decir para no estarlas subiendo todo el tiempo.

Algo que estaría atractivo, es que el cliente pudiera elegir sus plantillas a partir de un ejemplo de las mismas. Capaz que en lugar de 4, les subimos unos 10 diseños distintos y de ahí que elijan.

Te lo dejo de tarea, y por lo pronto, aquí va la primera plantilla base en web, ya probada en pru. Tuve que retrazar todo en Linux.

Saludos, rijo

**Comment by jccastillo0007** [comment]
Por un lado...
1. seria bueno tener un pdf de cada template, y dejar que el cliente los vea y de ahi elegir...
2. debemos trabajar en una pantalla mas elaborada para configurar los templates
3. debemos permitir elegir entre templates default y/o uno customizado y por tipo de documento, eso estaria bien chingon.
4. por el momento no nos queda de otra que poder subir cada uno de ellos.
5. Por cierto esta es la ruta que debes configurar para cada imagen utilizada en el template:
   
   /eFacturaT/customers/<RFC del cliente>/setup/<Nombre imagen>

ejemplo :

```
/eFacturaT/customers/PEI950612354/setup/LOGOIAP.png
```

Ya tienes ssh o putty en tu maquina ? para ense;arte como subir los archivos.

JC.

**Comment by RigoFlores** [comment]
Acuérdate que lo hago desde linux, con el ssh.
Hace poco tuve que acceder para modificar el reloj del servidor.
Supongo que se debe realizar vía ftp.

**Comment by RigoFlores** [comment]
las imágenes utilizadas, se suben previamente como si fueran plantilla.
Al final se sube la plantilla principal, por ejemplo wcfdi_arca.jrxml
