### ISSUE TITLE
CxC - CxC - Cartera General - inconsistencia de información en los reportes.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#980]
No están cuadrando las cifras de cartera por cliente y cartera general. Casos concretos aplicando el filtro de Vigentes + Vencidas:

NO. CLIENTE / SALDO EN CARTERA POR CLIENTE / SALDO EN CARTERA GENERAL
177702	42705.56	3544.17
287700	9030.60	366948.6
26900	16439.74	0.0

Se supone que el dato correcto es el de cartera por cliente.

En cartera por cliente se muestra el desglose de todas las facturas y sus pagos, de aquellas que no han sido pagadas totalmente.
El reporte de cartera general, no es otra cosa mas que el resumen del de cartera por cliente… donde se suman todos los cargos (facturación) y se restan todos los abonos (pagos), de las facturas vigentes y vencidas, o dependiendo el filtro que se aplique.

En cartera general se muestra todo el adeudo de todos los clientes a Optibelt, te imaginarás que están un poquito estresados ya que desconocen el adeudo total real, y además la confiabilidad de la información se pone a tela de juicio.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by jccastillo0007** [comment]
Not yet.

**Comment by jccastillo0007** [comment]
ahora si.

**Comment by RigoFlores** [comment]
revisé solo 3 casos, y están ok.
El cliente nos dará su VoBo.
Mientras tanto cerraré el issue.
