### ISSUE TITLE
CxP - Eliminar Tipo de pago y Folio de los datos de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#982]
Debe funcionar como CxC.
Entonces se elimina tipo de pago y folio.

Al eliminar el folio que aplicaba para NC, entonces se deberá mostrar en el listado tanto facturas como NC.
Los datos a capturar son: monto, fecha y referencia.

**Comment by jccastillo0007** [comment]
ahi wey , este no esta tan tan sencillo, debo replicar la funcionalidad de seleccionar NC de la lista de resultados ?

**Comment by RigoFlores** [comment]
Afirmativo, básicamente debe ser la misma funcionalidad...
Quizás convenga hasta replicar el código, y adaptarla para que los CDFI's mostrados, sean los de proveedores donde nuestro cliente, sea el receptor.
Los status deberían mostrarse en el portal de proveedores.

**Comment by jccastillo0007** [comment]
Esto supongo ya esta cubierto, ya que este ticket es muy viejo, y me parece que ya se cubrió la funcionalidad
