### ISSUE TITLE
CxP - Ingresar Pago - mostrar solo facturas vigentes o vencidas

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#983]
Con la cuenta de la tia, ingresé 2 pagos para el proveedor CCO... y en ese momento indica que fue ingresado con éxito, pero si vuelvo a consultar esas mismas facturas, me vuelven a aparecer como para ingresar el pago.

Urge cerrar los módulos que solo se van quedando como carga, pero que no funcionan.

**Comment by jccastillo0007** [comment]
Done.

**Comment by RigoFlores** [comment]
Ahora ya no muestra ninguna factura.
Subí una nueva factura, y de todos modos no muestra nada.
Según yo, es porque los status están chuecos... cuando consultas en el menú de compras aparece como registrada, pero en cxp el filtro es vencida + vigente... supongo que eso es.
Lo que hay que hacer es homologar los status. ya existe un issue desde hace meses al respecto

**Comment by jccastillo0007** [comment]
Fixed.
