### ISSUE TITLE
CFDI3.3- Método de Pago es opcional

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#984]
Si se desconoce el método de pago, se omite.
Quizás agregar una opción, que diga desconocido o similar, para que con ello la aplicación no envíe el método de pago al XML y PDF

**Comment by jccastillo0007** [comment]
pues mas bien, si no lo conocen, que no capturen nada y listo... solo hay que validar que no se mande vacío.

**Comment by RigoFlores** [comment]
La guia de captura del anexo 20, no coincide totalmente con el anexo 20.
Este texto es de la guía...

![metodopago](https://cloud.githubusercontent.com/assets/2912775/25139671/94b221a8-2423-11e7-8065-f8b3e5f789bf.PNG)

Este otro texto es del anexo 20.... 

![metodopagoanexo20](https://cloud.githubusercontent.com/assets/2912775/25139824/0155ca94-2424-11e7-94fc-1834863853c2.PNG)

**Comment by RigoFlores** [comment]
Yo entiendo que si no se conoce la forma de pago, deberán indicarlo con clave 99... y después tendrán que generar un documento de comprobante de pago, que es el otro CFDI.

**Comment by jccastillo0007** [comment]
El catálogo ya tiene la opción 99, que elijan eso los clientes... que más tengo que hacer yo ?

**Comment by RigoFlores** [comment]
OK, CERRAREMOS ESTE ISSUE, BAJO EL ENTENDIMIENTO QUE SIEMPRE TENDRÁN QUE CAPTURAR, AL MENOS EL 99... 
SIN EMBARGO, LA DOCUMENTACION DEL SAT ES CONTRADICTORIA AL RESPECTO.
POR LO PRONTO ASÍ SALIMOS....
