### ISSUE TITLE
CFDI3.3 - Desaparece Motivo de Descuento

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#985]
Desaparece motivo del descuento

**Comment by jccastillo0007** [comment]
Este campo es opcional, en CFDi 3.2, podemos eliminarlo de una vez

**Comment by RigoFlores** [comment]
OK, creo que no se ocupa mucho... espero no pegarle a algún cliente.
Lo que si se puede hacer, es enviarlo al PDF en caso que lo capturen, y solo eliminarlo del XML.

**Comment by RigoFlores** [comment]
OK, al PDF se sigue enviando y al XML ya no.
