### ISSUE TITLE
Web CFDI3.3 - Tipo de Cambio

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#987]
Incluir el tipo de cambio a 6 decimales, cuando la clave de la moneda elegida sea DISTINTA a MXN ó XXX.

**Comment by jccastillo0007** [comment]
XXX , cómo asi? todas van a ser distintas a XXX... que quisiste decir?

**Comment by RigoFlores** [comment]
XXX es un código mas dentro del catálogo...
![image](https://cloud.githubusercontent.com/assets/2912775/25139056/c8b0dce4-2421-11e7-977f-e47d183b06af.png)

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
Estoy confirmando si cuando la moneda sea MXN, no debe enviar el tipo de cambio a 1... como lo está haciendo ahora mismo

**Comment by jccastillo0007** [comment]
si se ocupa, de hecho fue una de las cosas que cambié, el validador de Finkok me lo indicó asi.

**Comment by RigoFlores** [comment]
Si elijo moneda USD marca error...

CFDI33113 : El campo TipoCambio no tiene el valor "1" y la moneda indicada es MXN. (3)

al parecer no está enviando la moneda elegida en la pantalla de factuaración

**Comment by RigoFlores** [comment]
De hecho desde el catálogo de impuestos no está aceptando los 6 decimales...

**Comment by jccastillo0007** [comment]
es que tiene la moneda MXN por defecto.. jojojo... ese es el escenario básico.

**Comment by RigoFlores** [comment]
a estas alturas del partido, después de 3 meses, este ya no debería ser escenario básico...

**Comment by jccastillo0007** [comment]
Fixed.

**Comment by RigoFlores** [comment]
En el catálogo de monedas, sigue mostrando únicamente 3 decimales, lo cual de entrada ya es incorrecto.
Hay que mostrar los 6 decimales, para conocer el tipo de cambio capturado
