### ISSUE TITLE
CFDI3-3 - total - número de decimales

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#988]
Debe incluir el número de decimales, de acuerdo al catálogo de monedas del SAT.
Se debe aplicar redondeo, al momento de truncar los decimales.
0.5 o mas, se redeondea hacia arriba.

**Comment by jccastillo0007** [comment]
mmmm algo no entendí, el número de decimales del total, depende del tipo de moneda ?

podemos dejarlo fijo a 5 decimales.?

**Comment by RigoFlores** [comment]
Afirmativo, el número de decimales depende de la moneda.
Por lo regular, las monedas mas utilizadas, ocupan solo 2 decimales.
Para el total se debe incluir el número de decimales soportados por la moneda (de acuerdo al catálogo del sat)

**Comment by jccastillo0007** [comment]
como habiamos quedado, se manejara basicamente a dos decimales, hasta que un cliente choncho nos pague el desmadre de manejar decimales de forma dinámica, estoy poniendo los totales a dos decimales.
