### ISSUE TITLE
CFDI3.3 - total - establecer límite superior

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#989]
Para ingreso o egreso, el límite superior es de 20,000,000 (por lo pronto)
Para nómina, el límite superior es 400,000

En caso que se rebase el monto arriba mencionado, se deberá pedir una confirmación al PAC. Por lo pronto esto último, no vamos a soportarlo, o lo dejaremos pendiente para un siguiente rilis.

**Comment by jccastillo0007** [comment]
y para el nuevo tipo de cfdi (pago) cual es el límite ?

**Comment by jccastillo0007** [comment]
oye para nómina, estas seguro de ese límite? se me hace poco para algunos CEO's ... y para nosotros después de esta actualización.

**Comment by RigoFlores** [comment]
Chiaaaa... pago va con 0 en el total, igual que el traslados.... chiaaaa
Jejeje... 400 k después de la actualización... jeje

**Comment by RigoFlores** [comment]
Si coloco un total superior a lo que aquí marca, que debo esperar? Supongo que un mensaje, pero me marca XML mal formato. Eso no lo envía la aplicación o si???

**Comment by jccastillo0007** [comment]
mmmmm el xml mal formado es por otra cosa, seria bueno que empieces con facturas sencillas , no se como estes creando la factura, yo hice una normal, y si pude probar estas validaciones de montos máximos... si te marca xml mal formado, debe ser por otra cosa que tal vez aún no se ha implementado o validado.

**Comment by RigoFlores** [comment]
Solo se pudo validar para Facturación, ya que en nómina marca error..

**Comment by jccastillo0007** [comment]
checa corrigiendo el pais

**Comment by RigoFlores** [comment]
Aquí no interviene el país... es otra cosa... quizás sea algo que se tiene que ajustar a la nómina, con la versión 3.3... este es el mensaje de error..

Error al generar CFD (115)

**Comment by RigoFlores** [comment]
Ya levanté los issues que aplican como ajuste para nomina 1.2, en combinación con cfdi 3.3 (realmente son 3 y se ven muy sencillos, sería bueno de una vez atenderlos)

**Comment by jccastillo0007** [comment]
Este issue ya esta resuelto ? faltando solo lo de nómina, pero hay otro ticket de eso.

**Comment by RigoFlores** [comment]
Hay que eliminar la validación del límite... el SAT ya lo cambió... resulta que no conviene para el robadero y fraudes propios de algunas empresas...
ahora mismo el límite es.. '999 999 999 999 999 999.999999

Dime si no es ridículo... mejor lo quitamos y ya... urge, porque tenemos clientes de ese calibre y no les permite facturar ahora mismo... chiaaaaa

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
quedó para pruebas, asumí que en producción también, y ni madres... ahorita marcó el cliente super emputado... chiaaa, hace 7 días levantó su reporte...
no voy a probar en producción, una factura de mas de 200 millones por supuesto...

**Comment by jccastillo0007** [comment]
mmmm acabo de revisar la version de PRO y es del 15 de Noviembre, asi que si debe estar esa corrección... le mandaba el mismo error ?

**Comment by jccastillo0007** [comment]
yo quite la validacion del total para facturas, pero tambien tenemos restricción para nómina

				if (cfdT.getInvoiceName().contains("NOMINA") && cfdT.getFinancialDetails().getTotal() > 400000.00) {

Le voy a quitar esa tambien

**Comment by jccastillo0007** [comment]
otra cosa... la validación la quite al momento de facturar, pero aún seguía al momento de vista previa.... no me digas que dieron vista previa y como les mando el error no intentaron facturar ? no maaaaa que pend....

**Comment by RigoFlores** [comment]
hay que quitar todo mensaje relacionado al tema.

**Comment by jccastillo0007** [comment]
Fixed.
