### ISSUE TITLE
CFDI3.3 - total - debe ser 0 cuando el tipo sea traslado o pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#990]
Para los CFDI de tipo traslado o pago, el total debe ser 0.00

**Comment by jccastillo0007** [comment]
a cabron... como asi? si el total es 0, entonces, donde se especifica la cantidad del traslado o de pago?

**Comment by RigoFlores** [comment]
El total debe ser 0.
Entiendo que el carta porte, no será ocupado mas para temas de deductibilidad, sino solo para el traslado.
Para poder deducir un gasto por servicio de transporte, se deberá generar un ingreso.

(en conclusión, este lineamiento generará doble timbrado, lo cual es conveniente para nosotros)

**Comment by jccastillo0007** [comment]
que pinche fumado esta esto

**Comment by jccastillo0007** [comment]
pues yo generé un traslado con un producto y con total = 0, y si hizo el xml bien

**Comment by RigoFlores** [comment]
Checa el carta porte con folio 44 en la cuenta de la tia.
Tiene total distinto de 0....

**Comment by jccastillo0007** [comment]
pues tiene un producto con una cantidad mayor a 0, debe la aplicación poner total =0 sin importar los productos que se agregaron ? o mas bien valido si el total es > 0 y que marque un error ?

**Comment by jccastillo0007** [comment]
haber ahora.

**Comment by RigoFlores** [comment]
Yo creo que en el carta porte, ya no se incluirán los conceptos de flete, maniobra, estadía, etc.
Pero hoy en día se pueden incluir... con ello, entendería que para traslado, el total simpre debería ser 0... 
es decir, por lo pronto para cumplir con este requisito, tenemos que hacer manita de puerco, y que el subtotal sea 0, para que el iva y demás impuestos que apliquen sean 0... y finalmente por consecuencia el total también sería 0

**Comment by jccastillo0007** [comment]
pues, nosotros no debemos maquillar los subtotales o totales, mas bien, el usuario debe hacerlo en sus productos... entonces la aplicación esta validando que el total sea 0.

**Comment by RigoFlores** [comment]
No es maquillar, son los requisitos del SAT para el CFDI de tipo traslado o pago, y estos son que el subtotal sea 0... como quiera marcará error cuando quieran timbrar algo que no sea cero.

**Comment by RigoFlores** [comment]
Marca error al crear el XML, cuando intento generar un cartaporte-traslado, o simplemente un traslado.

**Comment by jccastillo0007** [comment]
ok, ya esta generando carta porte y traslados.
El cliente se debe asegurar de que su total sea 0, la app lo va a validar, pero nó va a modificar el subtotal o total.

**Comment by RigoFlores** [comment]
OK, vamos a ver que dice mas adelante el SAT o la SCT, ya que su requerimiento es incompleto.
Si el subtotal es 0, entonces solo sirve para descripción de la carga el documento de traslado.
Entonces, toda la sección de concepto (flete, maniobra, etc), está sobrando.
