### ISSUE TITLE
CFDI3.3 - tipo de comprobante - enviar la clave de acuerdo al catálogo

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#991]
Ahora se enviará la clave, además que aparecen nuevos tipos de comprobante

**Comment by jccastillo0007** [comment]
entonces ahora la nomina además de ser egreso, el tipo será N, o mas bien ya no es egreso.

**Comment by RigoFlores** [comment]
Jejeje... solo puede existir un tipo, para nómina de acuerdo al catálogo será N.
Por cierto, ahora mismo no envía el atributo de tipo de comprobante... esto ya es error... jeje

**Comment by jccastillo0007** [comment]
noup, es un error controlado, es decir, es un error implementado jajajaja

es que no tenía el catálogo, pero ya esta

**Comment by jccastillo0007** [comment]
listo

**Comment by RigoFlores** [comment]
OK, no he validado nómina, pero en su caso abriría otro issue si encuentro problemas
