### ISSUE TITLE
Web CFDI3.3 Tipo de Comprobante - Descuento a nivel concepto

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#993]
No debe existir descuento A NIVEL CONCEPTO - cuando el tipo de comprobante es T o P

**Comment by RigoFlores** [comment]
La forma de solucionarlo, es que una vez que eligieron el tipo de comprobante... cartaporte traslado o traslado... entonces al agregar productos... no debe permitir capturar descuento...
De lo contrario queda inconsistente el CFDI... por un lado para los cálculos y total si considera el descuento, pero no lo envía... jeje... el punto es que no aplica para T o P

**Comment by jccastillo0007** [comment]
duplicado con el ticket 1012.

**Comment by RigoFlores** [comment]
El ticket 1012 ya está validado, y está OK.
Este ticket atiende una excepción para el descuento a nivel producto... si bien está relacionado, son 2 cosas distintas...

**Comment by jccastillo0007** [comment]
ya esta implementada la validación., pero como quiera hay que esperar a que se implemente el otro ticket.

**Comment by RigoFlores** [comment]
Entiendo que no puedo validar, correcto?

**Comment by RigoFlores** [comment]
No se puede validar, ya que el traslado no está timbrando... y el pago aún no está listo...

**Comment by jccastillo0007** [comment]
según mis pruebas ya esta timbrando... jojojo, hay un error con la plantilla de jasper, puedes subirle al usuario ACO... la plantilla de pagos... 

Yo validé que ya estaba timbrando, ya que vi el xml en el log...

**Comment by RigoFlores** [comment]
negativo, no está timbrando aún...
el compromiso es 01 de octubre para el web... es facturas, nómina, addendador, CCE, validación con el sat... en fin, que falta mucho y no le avanzamos

**Comment by jccastillo0007** [comment]
mmmm  no entendi si algo falla de este ticket, o era solo para desahogarte ? por whats dijiste que ya había timbrado no_

**Comment by RigoFlores** [comment]
No estaba timbrando, pero ahora ya... y cuando capturo un descuento, marca error:

El valor del campo Importe o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido (3)

**Comment by jccastillo0007** [comment]
fixed.

Era el tema de que el subtotal no estaba bien.

**Comment by RigoFlores** [comment]
Sigue marcando lo mesmo...

El valor del campo Importe o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido (3)

**Comment by jccastillo0007** [comment]
fixed
