### ISSUE TITLE
Web CFDi3.3 - Tipo de Comprobante - Nodo impuestos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#994]
El nodo impuestos no debe existir si el tipo de comprobante es T, P, N

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
De hecho al parece si intenta poner el nodo con el tipo traslado, porque marca este error...

CFDI33154 : El valor del campo Base que corresponde a Traslado debe ser mayor que cero (3)

Y el valor Base, corresponde al nodo de impuestos.

**Comment by jccastillo0007** [comment]
fixed.

**Comment by RigoFlores** [comment]
Pues no, sigue marcando ahora otro error...
El valor del campo Importe o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido (3)
Aún cuando el producto capturado, tiene importe 0. Anexo pantalla

![errortraslado](https://user-images.githubusercontent.com/2912775/29581777-0e35d9d2-8740-11e7-8fae-dd24249e764a.PNG)

**Comment by RigoFlores** [comment]
Por lo pronto, solo puedo validar en el tipo traslado... falta pago y nómina

**Comment by jccastillo0007** [comment]
ya se puede validar este ticket, cierto

**Comment by RigoFlores** [comment]
ok, deja probarlo en cuanto tenga chance...
hoy si ya empezó la presión cabrona por los clietnes.... y este cabrón de soporte que nos dejó como novias de pueblo.. chiaaaa

**Comment by RigoFlores** [comment]
Negativo, probé para traslado y marca el siguiente error:

El valor del campo Importe o que corresponde a Traslado no se encuentra entre el limite inferior y superior permitido (3)

El único producto que le agregué tenía precio de 0.
Lo cual pareciera que no está enviando correctamente el importe en el XML, pero eso no lo puedo ver.

Y nómina, mientras no se ajusate, no puedo validarlo.

**Comment by RigoFlores** [comment]
voy a cerrar este issue, para abrir uno referente a traslados y otro referente a nómina.
