### ISSUE TITLE
CFDI3.3 - Tipo de Comprobante - Forma/Método de pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#995]
No debe existir la forma de pago, ni método de pago cuando el tipo de comprobante es T o P.

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
No lo envía para tipo T...OK
Tampoco lo envía para tipo E.... incorrecto
Para tipo I... envía la forma de pago, pero no el método de pago..

**Comment by jccastillo0007** [comment]
Fixed.

Ahorita tiene fijo "PUE" mientras definimos como se manejan los catálogos de método de pago de la versión 3.2 y 3.3

**Comment by RigoFlores** [comment]
Para Ingreso, envía forma y método: OK
Para Egreso, no envía ninguno de los 2: Incorrecto, debe enviar ambos. Ya se había reportado arriba, y al parecer no se hacen caso a los comentarios, haciendo muy tardado el proceso de pruebas.
Para Traslado: no se puede probar, marca error al crear el XML

**Comment by RigoFlores** [comment]
Para traslado, marca error con carta porte.
Si elijo simplemente traslado, y al producto que agrego le capturo un 0 en precio unitario, si lo procesa.
Y para el tipo traslado no envía ni el método, ni la forma: OK.

Entonces queda el issue para el tipo Egreso, que ahí SI DEBE ENVIARLOS

**Comment by jccastillo0007** [comment]
done.
