### ISSUE TITLE
CFDIv3.3 - Método de Pago

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#996]
Enviar la clave correspondiente, dependiendo del método de pago.
Recordar que al XML se envia la clave, y al PDF se envia clave.descripcion

**Comment by jccastillo0007** [comment]
Repetido con el t icket 984.

**Comment by jccastillo0007** [comment]
de por si son muchos, chiaaaa

**Comment by RigoFlores** [comment]
No están duplicados... el otro se refería a que ES OPCIONAL EL MÉTODO DE PAGO.... OPCIONAL, OPCIONAL, OPCIONAL... a eso se refería... ya está cerrado.

Aquí se refiere a enviar la clave al XML y al PDF enviar clave.descripción
Si se envía, pero falta actualizar las claves del nuevo catálogo. Nos traen como calzón de puta... ya volvieron a actualizar el puto catálogo...
![image](https://cloud.githubusercontent.com/assets/2912775/25551127/feb3b7fe-2c45-11e7-8d87-0002cdaf3ec7.png)

**Comment by jccastillo0007** [comment]
ah ok, es que cuando leí el ticket, no vi donde decía eso de actualizar el catálogo.

**Comment by RigoFlores** [comment]
ojo, vamos de una vez a llamarle correctamente... el método de pago tiene su propio catálogo, que ahora será:
	
c_MetodoPago	Descripción
PUE	Pago en una sola exhibición
PIP	Pago inicial y parcialidades
PPD	Pago en parcialidades o diferido

**Comment by jccastillo0007** [comment]
si, y la forma de pago es el otro catálogo, chiaaaa

**Comment by jccastillo0007** [comment]
done.

**Comment by RigoFlores** [comment]
A ESTE CATÁLOGO AGREGARLE LA OPCIÓN DE "DESCONOCIDO"... PARA QUE EL VALOR POR OMISIÓN SEA PAGO EN UNA SOLA EXHIBICIÓN... O COMO LO PODEMOS HACER?

**Comment by RigoFlores** [comment]
ya ví, si existe la opción de 'no poner ninguna opción'.
Entonces solo colocar PUE como por omisión.

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
No, ahora ya no existe la opción de 'no poner ninguna'. Hay que agregarle ese renglón que tenía antes... algo así como 'seleccione una opción'... lo cual significa que va vacío....
o la otra es que me indiques como sería para no enviar el método de pago?

**Comment by jccastillo0007** [comment]
mmmm solo hay una de dos opciones.

O se pone una por default o se permite dejar vacío, pero no las dos opciones, asi que decidete.

**Comment by RigoFlores** [comment]
a) Debemos darle la opción al cliente de dejarlo vacío, lo cual implica no enviarlo. Este es el menor de los casos.
b) El mayor de todos los casos, es pago en una sola exhibición. Ese click es el que quiero evitarle al cliente.

Antes si se podía, yo lo ví... pero lo quitaste.

**Comment by jccastillo0007** [comment]
done.
