### ISSUE TITLE
Web CFDIv3.3 - Nodo CFDI's relacionados - Tipo Relacion

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#998]
Se podrá incluir opcionalmente el nodo CFDIs relacionados:

Atributo TipoRelacion .- Se enviará la clave del catálogo.

**Comment by RigoFlores** [comment]
Está faltando elegir los CFDI's relacionados.
Estos se pueden tomar de la BD de nuestro cliente (emisor), o también se podría tomar un XML del disco duro local, para que de ahí solo se tome el UUID.

**Comment by jccastillo0007** [comment]
Eso de los CFDi relacionados es el issue 999 , así que este ticket ya debería estar cerrado que no ?

**Comment by RigoFlores** [comment]
Negativo, no he podido validar que se incluye la clave de tipo de relación en el XML.
Los 2 issues van de la mano y se resuelven y cierran simultáneamente, una vez que se incluyan correctametne en el XML timbrado.

**Comment by jccastillo0007** [comment]
esto ya esta no?

al menos el tema de seleccionar un cfdi y tomar de ahi el uuid.

**Comment by RigoFlores** [comment]
esta pendiente que suban el XML de disco o que lo capturen en pantalla.

**Comment by RigoFlores** [comment]
Lo abriré en otro issue... lo de capturar solo el uuid, creo que no jalará porque de donde tomará los datos que son del XML que están pagando???
