### ISSUE TITLE
Web CFDIv3.3 - Nodo CFDI's relacionados - CFDI Relacionado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/eFacturaT#999]
Incluir el valor del o de los CFDI's relacionados.
Aquí es donde se ocupa elegir uno o varios XML del disco duro local, para simplemente tomar el UUID.
Eso ya lo hacemos actualmente para cargar uno o varios XML de proveedores, en el menú de Compras.

**Comment by RigoFlores** [comment]
Ya revisé, y no es en el menú de compras, sino en ventas-registrar cfdi externo.
Aquí se puede subir un XML solo, o varios desde un zip. Ambos casos del disco duro.
Ya pensé bien, y se ocupan 3 distintas opciones:
a) Poder elegir del historial de facturación en la plataforma
b) Elegir un XML o varios (en zip) del disco duro
c) Poder capturar uno o varios UUID tecleados directamente.

Se ocupan las 3 opciones para darle versatilidad al cliente.

**Comment by jccastillo0007** [comment]
Ya esta funcionando la opción de elegir cfdi a partir de una consulta.

Falta elegir un xml y capturar el uuid

**Comment by jccastillo0007** [comment]
hay que dejarlo asi como esta, para no meterle mas complejidad... a menos que alguien lo pida y lo pague

como la beisbol

**Comment by RigoFlores** [comment]
no estoy muy convencido, ya que los features que nadie tiene nos generan clientes.
Te pongo un ejemplo... estoy en tratos con un prospecto que dice que nadie ofrece el formato de la SCT como nosotros, y de hecho que lo ha estado buscando.
La policía federal, después de 2 años, ya se puso al día y ahora les exige el carta porte CFDI. Entonces supongo que varios nos buscarán.

Regresando al tema, dadas las circunstancias actuales lo cerraré, pero que busque un XML en disco duro, ya lo tienes desarrollado... y capturar el uuid también lo tienes desarrollado en escritorio.
